cc_binary(
    name = "fuzz_dash_e",
    srcs = [
        "fuzz_dash_e.cc",
    ],
    tags = ["manual"],
    visibility = ["//visibility:public"],
    deps = [
        "//main:realmain",
        "//payload/binary:some",
        "//payload/text:empty",
    ],
)
