class <constant:<root>> < ::<constant:Object> () -> <Class:<root>>
  class <constant:T1> < ::<constant:Object> () -> <Class:T1>
  class <constant:TestSig> < ::<constant:Object> () -> <Class:TestSig>
    method test_resolve () -> T1
  class <singleton class:<constant:T1>> < ::<singleton class:<constant:Object>> ()
  class <singleton class:<constant:TestSig>> < ::<singleton class:<constant:Object>> ()
  method <static-init>$7 ()
  static-field <constant:T2> -> <Class:T1>

