class <constant:<root>> < ::<constant:Object> () -> <Class:<root>>
  class <constant:Child> < ::<constant:Parent> (<constant:Mixin2>) -> <Class:Child>
  class <constant:Mixin1> (<constant:BasicObject>) -> <Class:Mixin1>
  class <constant:Mixin2> (<constant:BasicObject>) -> <Class:Mixin2>
  class <constant:Parent> < ::<constant:Object> (<constant:Mixin1>) -> <Class:Parent>
  class <singleton class:<constant:Child>> < ::<singleton class:<constant:Parent>> ()
  class <singleton class:<constant:Mixin1>> < ::<constant:Module> ()
  class <singleton class:<constant:Mixin2>> < ::<constant:Module> ()
  class <singleton class:<constant:Parent>> < ::<singleton class:<constant:Object>> ()
  method <static-init>$6 ()

