class <C <U <root>>> < <C <U Object>> () @ (Loc {file=test/testdata/namer/circular_mixin.rb start=2:1 end=13:4}, Loc {file=https://git.corp.stripe.com/stripe-internal/sorbet/tree/master/bazel-out/host/genfiles/rbi/procs.rbi start=1:1 end=252:4}, Loc {file=https://git.corp.stripe.com/stripe-internal/sorbet/tree/master/rbi/test_bootstrap.rbi start=1:1 end=3365:4})
  method <N <U <static-init>> $3> (<blk>) @ Loc {file=test/testdata/namer/circular_mixin.rb start=2:1 end=13:4}
    argument <N <U <static-init>> $3><blk><block> @ Loc {file=test/testdata/namer/circular_mixin.rb start=??? end=???}
  class <C <U A>> < <C <U RubyTyper>><C <U ImplicitModuleSuperclass>> (<C <U B>>, <C <U StubAncestor>>) @ Loc {file=test/testdata/namer/circular_mixin.rb start=11:1 end=11:9}
  class <S <C <U A>> $1> < <C <U Module>> () @ Loc {file=test/testdata/namer/circular_mixin.rb start=2:8 end=2:9}
    method <S <C <U A>> $1><U <static-init>> (<blk>) @ Loc {file=test/testdata/namer/circular_mixin.rb start=??? end=???}
      argument <S <C <U A>> $1><U <static-init>><blk><block> @ Loc {file=test/testdata/namer/circular_mixin.rb start=??? end=???}
  class <C <U B>> < <C <U RubyTyper>><C <U ImplicitModuleSuperclass>> (<C <U StubAncestor>>) @ Loc {file=test/testdata/namer/circular_mixin.rb start=7:1 end=7:9}
  class <S <C <U B>> $1> < <C <U Module>> () @ Loc {file=test/testdata/namer/circular_mixin.rb start=3:8 end=3:9}
    method <S <C <U B>> $1><U <static-init>> (<blk>) @ Loc {file=test/testdata/namer/circular_mixin.rb start=??? end=???}
      argument <S <C <U B>> $1><U <static-init>><blk><block> @ Loc {file=test/testdata/namer/circular_mixin.rb start=??? end=???}

