begin
  <emptyTree>
  class <emptyTree><<C <root>>> < (::<todo sym>)
    def self.<static-init><<static-init>$CENSORED>(<blk>)
      begin
        <emptyTree>
        <keep-for-ide>(::A)
        <emptyTree>
      end
    end
  end
  module ::A<<C A>> < ()
    def Foo(<blk>)
      <emptyTree>
    end

    def self.<static-init>(<blk>)
      begin
        <runtime method definition of Foo>
        begin
          <emptyTree>
          <keep-for-ide>(::A::Foo)
          <emptyTree>
        end
        <emptyTree>
      end
    end
  end
  class ::A::Foo<<C Foo>> < (::<todo sym>)
    def self.<static-init>(<blk>)
      <emptyTree>
    end
  end
  <emptyTree>
end
