begin
  class <emptyTree><<constant:<root>>> < ()
    <emptyTree>

    <emptyTree>

    def self.<static-init><<static-init>$74>()
      #$a = 1
    end
  end
  class ::A<<constant:A>> < (::<todo sym>)
    <emptyTree>

    <emptyTree>

    def meth<meth>()
      [#$a, #$b, #$c]
    end

    def self.<static-init><<static-init>>()
      begin
        #$b = 2
        #$a
        <emptyTree>
      end
    end
  end
  <emptyTree>
end
