begin
  <emptyTree>
  class <emptyTree><<C <root>>> < (::<todo sym>)
    def self.<static-init><<static-init>$CENSORED>(<blk>)
      begin
        $a = 1
        begin
          <emptyTree>
          ::Sorbet::Private::Static.keep_for_ide(::A)
          <emptyTree>
        end
        <emptyTree>
      end
    end
  end
  class ::A<<C A>> < (::<todo sym>)
    def meth(<blk>)
      [$a, $b, $c]
    end

    def self.<static-init>(<blk>)
      begin
        $b = 2
        $a
        :meth
        <emptyTree>
      end
    end
  end
  <emptyTree>
end
