class <emptyTree>::<constant:TestLocals><<constant:TestLocals>> < (::<constant:<todo sym>>)
  def method<method>()
    begin
      a = 1
      c = 4
      self(<constant:TestLocals>).proc() do ||
        begin
          b$5812 = 2
          a.+(b$5812)
          self(<constant:TestLocals>).proc() do ||
            b$5812.+(c)
          end
        end
      end
      b = 3
      self(<constant:TestLocals>).proc() do |a$5814, b$5814|
        a$5814.+(b$5814)
      end
    end
  end
end
