begin
  class <emptyTree><<constant:<root>>> < ()
    def self.<static-init><<static-init>$78>()
      begin
        begin
          ::RubyTyper.keep_for_ide(::A)
          <emptyTree>
        end
        begin
          ::RubyTyper.keep_for_ide(::C)
          <emptyTree>
        end
        <emptyTree>
      end
    end
  end
  module ::A<<constant:A>> < ()
    def self.<static-init><<static-init>>()
      begin
        ::RubyTyper.keep_for_ide(::A::B)
        <emptyTree>
      end
    end
  end
  class ::A::B<<constant:B>> < (::<todo sym>)  end
  class ::C<<constant:C>> < (::<todo sym>)  end
  <emptyTree>
end
