begin
  ::RubyTyper.<U keep_for_ide>(::Test)
  class ::Test<<C <U Test>>> < (::<todo sym>)
    def <U test_next_break><<U test_next_break>>(<blk>)
      <U <self>>.<U each>() do ||
        begin
          if <U <self>>.<U rand>()
            next(::Test::Foo)
          else
            <emptyTree>
          end
          if <U <self>>.<U rand>()
            break(::Test::Bar)
          else
            <emptyTree>
          end
        end
      end
    end
  end
  <emptyTree>
end
