begin
  <emptyTree>
  class <emptyTree><<C <root>>> < (::<todo sym>)
    def self.<static-init><<static-init>$CENSORED>(<blk>)
      begin
        ::<Magic>.<define-top-class-or-module>(::Main)
        ::Sorbet::Private::Static.keep_for_ide(::Main)
        <emptyTree>
      end
    end
  end
  class ::Main<<C Main>> < (::<todo sym>)
    def foo<foo$1>(a, <blk>)
      a
    end

    def foo<foo$2>(a, b, <blk>)
      <emptyTree>
    end

    def foo(a, b, c, <blk>)
      <emptyTree>
    end

    def self.<static-init>(<blk>)
      begin
        ::Sorbet::Private::Static.sig(<self>) do ||
          <self>.params(:"a", ::Integer).returns(::Integer)
        end
        <self>.extend(::T::Sig)
        ::Sorbet::Private::Static.keep_def(<self>, :"foo")
        ::Sorbet::Private::Static.keep_def(<self>, :"foo")
        ::Sorbet::Private::Static.keep_def(<self>, :"foo")
        <emptyTree>
      end
    end
  end
  <emptyTree>
end
