digraph "redefines_object.rb" {
subgraph "cluster_#<static-init>" {
    label = "#<static-init>";
    color = blue;
    "bb#<static-init>_0" [shape = invhouse];
    "bb#<static-init>_1" [shape = parallelogram];

    "bb#<static-init>_0" [
        label = "block[id=0]()\l<constant:RubyTyper>$7 = alias <constant:RubyTyper> : <Class:RubyTyper>\l<constant:Foo>$14 = alias <constant:Foo> : <Class:Foo>\l<constant:Bar>$9 = alias <constant:Bar> : <Class:Bar>\l<statTemp>$5 = <constant:RubyTyper>$7.keep_for_ide(<constant:Bar>$9) : T.untyped\l<statTemp>$11 = <constant:RubyTyper>$7.keep_for_ide(<constant:Foo>$14) : T.untyped\l<finalReturn> = return <returnMethodTemp>$2 : <impossible>\l<unconditional>\l"
    ];

    "bb#<static-init>_0" -> "bb#<static-init>_1" [style="bold"];
    "bb#<static-init>_1" [
        label = "block[id=1]()\l<unconditional>\l"
    ];

    "bb#<static-init>_1" -> "bb#<static-init>_1" [style="bold"];
}

subgraph "cluster_::Trigger#trigger" {
    label = "::Trigger#trigger";
    color = blue;
    "bb::Trigger#trigger_0" [shape = invhouse];
    "bb::Trigger#trigger_1" [shape = parallelogram];

    "bb::Trigger#trigger_0" [
        label = "block[id=0]()\l@__fake_logger$4 = alias @__fake_logger : T.untyped\l<returnMethodTemp>$2 = @__fake_logger$4 : T.untyped\l<finalReturn> = return <returnMethodTemp>$2 : <impossible>\l<unconditional>\l"
    ];

    "bb::Trigger#trigger_0" -> "bb::Trigger#trigger_1" [style="bold"];
    "bb::Trigger#trigger_1" [
        label = "block[id=1]()\l<unconditional>\l"
    ];

    "bb::Trigger#trigger_1" -> "bb::Trigger#trigger_1" [style="bold"];
}

}

