class ::<root> < ::Object () @ test/testdata/namer/sig_good.rb:2
  class ::<Class:A> < ::<Class:Object> () @ test/testdata/namer/sig_good.rb:7
  class ::<Class:M1> < ::Module () @ test/testdata/namer/sig_good.rb:4
  class ::<Class:T1> < ::<Class:Object> () @ test/testdata/namer/sig_good.rb:2
  class ::<Class:T2> < ::<Class:Object> () @ test/testdata/namer/sig_good.rb:3
  class ::A < ::Object () @ test/testdata/namer/sig_good.rb:7
    method ::A#good (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) -> T2 @ test/testdata/namer/sig_good.rb:31
      argument ::A#good#a<> -> TupleType {
        0 = T1
        1 = T2
      } @ test/testdata/namer/sig_good.rb:9
      argument ::A#good#b<> -> T1 @ test/testdata/namer/sig_good.rb:10
      argument ::A#good#c<> -> T1 | NilClass @ test/testdata/namer/sig_good.rb:11
      argument ::A#good#d<> -> T1 | T2 @ test/testdata/namer/sig_good.rb:12
      argument ::A#good#e<> -> T.untyped @ test/testdata/namer/sig_good.rb:13
      argument ::A#good#f<> -> AppliedType {
        klass = ::Array
        targs = [
          <constant:Elem> = T1
        ]
      } @ test/testdata/namer/sig_good.rb:14
      argument ::A#good#g<> -> AppliedType {
        klass = ::Hash
        targs = [
          <constant:K> = T1
          <constant:V> = T2
          <constant:Elem> = TupleType {
              0 = T1
              1 = T2
            }
        ]
      } @ test/testdata/namer/sig_good.rb:15
      argument ::A#good#h<> -> FalseClass | Integer | Float | String | Symbol @ test/testdata/namer/sig_good.rb:16
      argument ::A#good#i<> -> T1 @ test/testdata/namer/sig_good.rb:17
      argument ::A#good#j<> -> <Class:T1> @ test/testdata/namer/sig_good.rb:18
      argument ::A#good#k<> -> <Class:T1> @ test/testdata/namer/sig_good.rb:19
      argument ::A#good#l<> -> <Class:T1> @ test/testdata/namer/sig_good.rb:20
      argument ::A#good#m<> -> <Class:T1> @ test/testdata/namer/sig_good.rb:21
      argument ::A#good#n<> -> <Class:M1> @ test/testdata/namer/sig_good.rb:22
      argument ::A#good#o<> -> ShapeType {
        Symbol(:"foo") => String
        Symbol(:"bar") => Integer | NilClass
      } @ test/testdata/namer/sig_good.rb:23
      argument ::A#good#p<> -> ShapeType {
      } @ test/testdata/namer/sig_good.rb:27
      argument ::A#good#q<> -> ShapeType {
        String("hi") => String
        Symbol(:"bye") => String
      } @ test/testdata/namer/sig_good.rb:28
  class ::M1 (<constant:BasicObject>) @ test/testdata/namer/sig_good.rb:4
  class ::T1 < ::Object () @ test/testdata/namer/sig_good.rb:2
  class ::T2 < ::Object () @ test/testdata/namer/sig_good.rb:3
  method #<static-init> () @ test/testdata/namer/sig_good.rb:2
  static-field #A1 -> AliasType { symbol = ::T1 } @ test/testdata/namer/sig_good.rb:5

