class <constant:<root>> < ::Object () -> <Class:<root>> @ test/testdata/namer/singleton_class.rb:1
  class <constant:A> () -> <Class:A> @ test/testdata/namer/singleton_class.rb:1
    class <constant:B> () -> <Class:A::B> @ test/testdata/namer/singleton_class.rb:1
      class <constant:C> < ::Object () -> <Class:A::B::C> @ test/testdata/namer/singleton_class.rb:1
      class <singleton class:<constant:C>> < ::<Class:Object> () @ test/testdata/namer/singleton_class.rb:1
    class <singleton class:<constant:B>> < ::Module () @ test/testdata/namer/singleton_class.rb:1
  class <constant:Object> < ::BasicObject (<constant:Kernel>) -> <Class:Object> @ https://git.corp.stripe.com/stripe-internal/ruby-typer/tree/master/rbi/core.rbi#L8357
    method main () @ test/testdata/namer/singleton_class.rb:4
  class <singleton class:<constant:A>> < ::Module () @ test/testdata/namer/singleton_class.rb:1
  method <static-init>$10 () @ test/testdata/namer/singleton_class.rb:1

