class <C <U <root>>> < <C <U Object>> () @ (Loc {file=test/testdata/namer/yield.rb start=2:1 end=27:14}, Loc {file=https://git.corp.stripe.com/stripe-internal/sorbet/tree/master/bazel-out/host/genfiles/rbi/procs.rbi start=1:1 end=252:4}, Loc {file=https://git.corp.stripe.com/stripe-internal/sorbet/tree/master/rbi/light.rbi start=7:1 end=3322:4})
  method <N <U <static-init>> $3> (<blk>) @ Loc {file=test/testdata/namer/yield.rb start=2:1 end=27:14}
    argument <N <U <static-init>> $3><blk><block> @ Loc {file=test/testdata/namer/yield.rb start=??? end=???}
  class <C <U Main>> < <C <U Object>> () @ Loc {file=test/testdata/namer/yield.rb start=2:1 end=2:11}
    method <C <U Main>><U blockpass> (&blk) @ Loc {file=test/testdata/namer/yield.rb start=7:5 end=7:24}
      argument <C <U Main>><U blockpass>&blk<block> @ Loc {file=test/testdata/namer/yield.rb start=7:19 end=7:23}
    method <C <U Main>><U blockyield> (<blk>) @ Loc {file=test/testdata/namer/yield.rb start=15:5 end=15:19}
      argument <C <U Main>><U blockyield><blk><block> @ Loc {file=test/testdata/namer/yield.rb start=??? end=???}
      method <C <U Main>><U blockyield><N <U <block>> $2> (i) @ Loc {file=test/testdata/namer/yield.rb start=16:9 end=16:30}
        argument <C <U Main>><U blockyield><N <U <block>> $2>i<> @ Loc {file=test/testdata/namer/yield.rb start=16:19 end=16:20}
    method <C <U Main>><U main> (<blk>) @ Loc {file=test/testdata/namer/yield.rb start=19:5 end=19:13}
      argument <C <U Main>><U main><blk><block> @ Loc {file=test/testdata/namer/yield.rb start=??? end=???}
      method <C <U Main>><U main><N <U <block>> $2> (x) @ Loc {file=test/testdata/namer/yield.rb start=20:13 end=20:35}
        argument <C <U Main>><U main><N <U <block>> $2>x<> @ Loc {file=test/testdata/namer/yield.rb start=20:22 end=20:23}
    method <C <U Main>><U mixed> (&blk) @ Loc {file=test/testdata/namer/yield.rb start=11:5 end=11:20}
      argument <C <U Main>><U mixed>&blk<block> @ Loc {file=test/testdata/namer/yield.rb start=11:15 end=11:19}
    method <C <U Main>><U yielder> (<blk>) @ Loc {file=test/testdata/namer/yield.rb start=3:5 end=3:16}
      argument <C <U Main>><U yielder><blk><block> @ Loc {file=test/testdata/namer/yield.rb start=??? end=???}
  class <S <C <U Main>> $1> < <S <C <U Object>> $1> () @ Loc {file=test/testdata/namer/yield.rb start=2:7 end=2:11}

