load("@com_github_bazelbuild_buildtools//buildifier:def.bzl", "buildifier")

buildifier(
    name = "fix",
)

buildifier(
    name = "diff",
    mode = "diff",
)

buildifier(
    name = "lint",
    mode = "check",
)
