cc_library(
    name = "errorqueue",
    srcs = [
        "ConcurrentErrorQueue.cc",
        "ConcurrentErrorQueue.h",
    ],
    copts = ["--std=c++14"],
    visibility = ["//visibility:public"],
    deps = [
        "//common/concurrency",
        "//core",
    ],
)
