cc_library(
    name = "version",
    hdrs = [
        "version.h",
    ],
    linkstamp = "version.cc",
    visibility = ["//visibility:public"],
)

# in order to make a versioned artifact you need to pass --stamp
