cc_library(
    name = "Names",
    srcs = [
        "Names.h",
        "Names.cc",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"],
    deps = [
        "@com_stripe_ruby_typer//core",
        "@spdlog",
    ],
)
