Begin {
  stmts = [
    DefMethod {
      name = <U foo>
      args = NULL
      body = NULL
    }
    DefMethod {
      name = <U m>
      args = Args {
        args = [
          Arg {
            name = <U args>
          }
        ]
      }
      body = NULL
    }
    OpAsgn {
      left = Send {
        receiver = Send {
          receiver = NULL
          method = <U foo>
          args = [
          ]
        }
        method = <U []>
        args = [
          Integer {
            val = "0"
          }
          Integer {
            val = "1"
          }
        ]
      }
      op = <U +>
      right = Send {
        receiver = NULL
        method = <U m>
        args = [
          Send {
            receiver = NULL
            method = <U foo>
            args = [
            ]
          }
        ]
      }
    }
  ]
}
