Begin {
  stmts = [
    DefMethod {
      name = <U bar>
      args = NULL
      body = NULL
    }
    DSymbol {
      nodes = [
        String {
          val = <U foo>
        }
        Begin {
          stmts = [
            Send {
              receiver = NULL
              method = <U bar>
              args = [
              ]
            }
          ]
        }
        String {
          val = <U baz>
        }
      ]
    }
  ]
}
