pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - status-success=All tests and builds succeeded
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash
