tmp="$(mktemp)"
pre="test/cli/autocorrect-nilable-untyped/pre.rb"
post="test/cli/autocorrect-nilable-untyped/post.rb"
cp "$pre" "$tmp"
main/sorbet --silence-dev-message -a "$tmp"
diff "$post" "$tmp"
rm "$tmp"
