#include "core/json/json.h"
#include "core/GlobalState.h"
#include "core/packages/PackageDB.h"

using namespace std;

namespace sorbet::core {

namespace {

// Maps StrictLevel to the PascalCase names used in proto/File.proto's StrictLevel enum.
// These names differ from SigilTraits<StrictLevel>::toString(), which uses lowercase names
// (e.g., "true" vs "True"). We use the proto enum names here so that the JSON output is
// backwards-compatible with the previous protobuf-based serialization.
string_view strictLevelToJSONString(StrictLevel level) {
    switch (level) {
        case StrictLevel::None:
            return "None"sv;
        case StrictLevel::Internal:
            // We should never attempt to serialize any state that had internal errors.
            Exception::raise("Should never attempt to serialize StrictLevel::Internal to JSON");
        case StrictLevel::Ignore:
            return "Ignore"sv;
        case StrictLevel::False:
            return "False"sv;
        case StrictLevel::True:
            return "True"sv;
        case StrictLevel::Strict:
            return "Strict"sv;
        case StrictLevel::Strong:
            return "Strong"sv;
        case StrictLevel::Max:
            return "Max"sv;
        case StrictLevel::Autogenerated:
            return "Autogenerated"sv;
        case StrictLevel::Stdlib:
            return "Stdlib"sv;
    }
}

} // namespace

// Writes a single file entry as a JSON object to the writer.
// Fields set to their proto3 default values are omitted, matching the behavior of
// the previous protobuf JSON serialization (proto3 omits default-valued fields).
void JSON::fileToJSON(rapidjson::PrettyWriter<rapidjson::StringBuffer> &writer, const GlobalState &gs, FileRef file,
                      long untypedUsages) {
    const auto &data = file.data(gs);

    writer.StartObject();

    auto path = data.path();
    if (!path.empty()) {
        writer.Key("path");
        writer.String(path.data(), path.size());
    }

    // Omit enum fields when they equal the proto3 default (enum value 0 = "None")
    if (data.originalSigil != StrictLevel::None) {
        writer.Key("sigil");
        auto s = strictLevelToJSONString(data.originalSigil);
        writer.String(s.data(), s.size());
    }

    if (data.strictLevel != StrictLevel::None) {
        writer.Key("strict");
        auto s = strictLevelToJSONString(data.strictLevel);
        writer.String(s.data(), s.size());
    }

    auto minErr = data.minErrorLevel();
    if (minErr != StrictLevel::None) {
        writer.Key("min_error_level");
        auto s = strictLevelToJSONString(minErr);
        writer.String(s.data(), s.size());
    }

    // "compiled" is always CompiledNone (proto3 default), so always omitted.

    if (untypedUsages != 0) {
        writer.Key("untyped_usages");
        writer.Int(untypedUsages);
    }

    const auto &packageDB = gs.packageDB();
    if (packageDB.enabled()) {
        const auto &pkgName = packageDB.getPackageNameForFile(file);
        if (pkgName.exists()) {
            auto pkg = packageDB.getPackageInfo(pkgName).show(gs);
            if (!pkg.empty()) {
                writer.Key("pkg");
                writer.String(pkg.data(), pkg.size());
            }
        }
    }

    writer.EndObject();
}

} // namespace sorbet::core
