; ModuleID = 'payload'
source_filename = "llvm-link"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

%struct.rb_execution_context_struct = type { i64*, i64, %struct.rb_control_frame_struct*, %struct.rb_vm_tag*, %struct.rb_vm_protect_tag*, i32, i32, %struct.rb_fiber_struct*, %struct.rb_thread_struct*, %struct.st_table*, i64, i64, i64*, i64, %struct.rb_ensure_list*, %struct.rb_trace_arg_struct*, i64, i64, i8, i8, i64, %struct.anon.7 }
%struct.rb_control_frame_struct = type { i64*, i64*, %struct.rb_iseq_struct*, i64, i64*, i8*, i64* }
%struct.rb_iseq_struct = type { i64, i64, %struct.rb_iseq_constant_body*, %union.anon.17 }
%struct.rb_iseq_constant_body = type { i32, i32, i64*, %struct.anon, %struct.rb_iseq_location_struct, %struct.iseq_insn_info, i64*, %struct.iseq_catch_table*, %struct.rb_iseq_struct*, %struct.rb_iseq_struct*, %union.iseq_inline_storage_entry*, %struct.rb_call_data*, %struct.anon.16, i32, i32, i32, i32, i32, i8, i64 }
%struct.anon = type { %struct.anon.0, i32, i32, i32, i32, i32, i32, i32, i64*, %struct.rb_iseq_param_keyword* }
%struct.anon.0 = type { i16, [2 x i8] }
%struct.rb_iseq_param_keyword = type { i32, i32, i32, i32, i64*, i64* }
%struct.rb_iseq_location_struct = type { i64, i64, i64, i64, i32, %struct.rb_code_location_struct }
%struct.rb_code_location_struct = type { %struct.rb_code_position_struct, %struct.rb_code_position_struct }
%struct.rb_code_position_struct = type { i32, i32 }
%struct.iseq_insn_info = type { %struct.iseq_insn_info_entry*, i32*, i32, %struct.succ_index_table* }
%struct.iseq_insn_info_entry = type opaque
%struct.succ_index_table = type opaque
%struct.iseq_catch_table = type opaque
%union.iseq_inline_storage_entry = type { %struct.iseq_inline_cache_entry }
%struct.iseq_inline_cache_entry = type { i64, %struct.rb_cref_struct*, i64 }
%struct.rb_cref_struct = type { i64, i64, i64, %struct.rb_cref_struct*, %struct.rb_scope_visi_struct }
%struct.rb_scope_visi_struct = type { i8, [3 x i8] }
%struct.rb_call_data = type { %struct.rb_call_cache, %struct.rb_call_info }
%struct.rb_call_cache = type { i64, [3 x i64], %struct.rb_callable_method_entry_struct*, i64, i64 (%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_calling_info*, %struct.rb_call_data*)*, %union.anon.15 }
%struct.rb_callable_method_entry_struct = type { i64, i64, %struct.rb_method_definition_struct*, i64, i64 }
%struct.rb_method_definition_struct = type { i64, %union.anon.13, i64, i64 }
%union.anon.13 = type { %struct.rb_method_cfunc_struct }
%struct.rb_method_cfunc_struct = type { i64 (...)*, i64 (i64, i32, i64*, i64 (...)*)*, i32 }
%struct.rb_calling_info = type { i64, i64, i32, i32 }
%union.anon.15 = type { i32 }
%struct.rb_call_info = type { i64, i32, i32 }
%struct.anon.16 = type { i64, i64, i64, i64* }
%union.anon.17 = type { %struct.anon.18 }
%struct.anon.18 = type { i64, i32 }
%struct.rb_vm_tag = type { i64, i64, [5 x i8*], %struct.rb_vm_tag*, i32 }
%struct.rb_vm_protect_tag = type { %struct.rb_vm_protect_tag* }
%struct.rb_fiber_struct = type opaque
%struct.rb_thread_struct = type { %struct.list_node, i64, %struct.rb_vm_struct*, %struct.rb_execution_context_struct*, i64, %struct.rb_calling_info*, i64, i64, i64, i8, i8, i32, %struct.native_thread_data_struct, i8*, i64, i64, i64, i64, %union.pthread_mutex_t, %struct.rb_unblock_callback, i64, %struct.rb_mutex_struct*, %struct.rb_thread_list_struct*, %union.anon.10, i32, i64, %struct.rb_fiber_struct*, [5 x i8*], i64 }
%struct.list_node = type { %struct.list_node*, %struct.list_node* }
%struct.rb_vm_struct = type { i64, %struct.rb_global_vm_lock_struct, %struct.rb_thread_struct*, %struct.rb_thread_struct*, i8*, i64, %union.pthread_mutex_t, %struct.list_head, %struct.list_head, %struct.list_head, %struct.list_head, i64, i32, i32, i8, i32, i64, [5 x i64], i64, i64, i64, i64, i64, i64, i64, %struct.st_table*, %struct.st_table*, %struct.anon.5, %struct.rb_hook_list_struct, %struct.st_table*, %struct.rb_postponed_job_struct*, i32, i32, %struct.list_head, %union.pthread_mutex_t, i64, i64, i64, i64, i64, i32, %struct.st_table*, %struct.rb_objspace*, %struct.rb_at_exit_list*, i64*, %struct.st_table*, %struct.rb_builtin_function*, i32, %struct.anon.6, [29 x i16] }
%struct.rb_global_vm_lock_struct = type { %struct.rb_thread_struct*, %union.pthread_mutex_t, %struct.list_head, %struct.rb_thread_struct*, i32, %union.pthread_cond_t, %union.pthread_cond_t, i32, i32 }
%union.pthread_cond_t = type { %struct.__pthread_cond_s }
%struct.__pthread_cond_s = type { %union.anon, %union.anon, [2 x i32], [2 x i32], i32, i32, [2 x i32] }
%union.anon = type { i64 }
%struct.anon.5 = type { [65 x i64] }
%struct.rb_hook_list_struct = type { %struct.rb_event_hook_struct*, i32, i32, i32 }
%struct.rb_event_hook_struct = type opaque
%struct.rb_postponed_job_struct = type opaque
%struct.list_head = type { %struct.list_node }
%struct.rb_objspace = type opaque
%struct.rb_at_exit_list = type { void (%struct.rb_vm_struct*)*, %struct.rb_at_exit_list* }
%struct.rb_builtin_function = type opaque
%struct.anon.6 = type { i64, i64, i64, i64 }
%struct.native_thread_data_struct = type { %struct.list_head, %union.anon.9 }
%union.anon.9 = type { %union.pthread_cond_t }
%union.pthread_mutex_t = type { %struct.__pthread_mutex_s }
%struct.__pthread_mutex_s = type { i32, i32, i32, i32, i32, i16, i16, %struct.__pthread_internal_list }
%struct.__pthread_internal_list = type { %struct.__pthread_internal_list*, %struct.__pthread_internal_list* }
%struct.rb_unblock_callback = type { void (i8*)*, i8* }
%struct.rb_mutex_struct = type opaque
%struct.rb_thread_list_struct = type { %struct.rb_thread_list_struct*, %struct.rb_thread_struct* }
%union.anon.10 = type { %struct.anon.11 }
%struct.anon.11 = type { i64, i64, i32 }
%struct.st_table = type { i8, i8, i8, i32, %struct.st_hash_type*, i64, i64*, i64, i64, %struct.st_table_entry* }
%struct.st_hash_type = type { i32 (i64, i64)*, i64 (i64)* }
%struct.st_table_entry = type opaque
%struct.rb_ensure_list = type { %struct.rb_ensure_list*, %struct.rb_ensure_entry }
%struct.rb_ensure_entry = type { i64, i64 (i64)*, i64 }
%struct.rb_trace_arg_struct = type { i32, %struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, i64, i64, i64, i64, i64, i32, i32, i64 }
%struct.anon.7 = type { i64*, i64*, i64, [1 x %struct.__jmp_buf_tag] }
%struct.__jmp_buf_tag = type { [8 x i64], i32, %struct.__sigset_t }
%struct.__sigset_t = type { [16 x i64] }
%struct.SorbetLineNumberInfo = type { i32, %struct.iseq_insn_info_entry*, i64* }
%struct.FunctionInlineCache = type { %struct.rb_kwarg_call_data }
%struct.rb_kwarg_call_data = type { %struct.rb_call_cache, %struct.rb_call_info_with_kwarg }
%struct.rb_call_info_with_kwarg = type { %struct.rb_call_info, %struct.rb_call_info_kw_arg* }
%struct.rb_call_info_kw_arg = type { i32, [1 x i64] }
%struct.ExceptionClosure = type { i64 (i64**, i64, %struct.rb_control_frame_struct*)*, i64**, i64, %struct.rb_control_frame_struct*, i64* }

@ruby_current_execution_context_ptr = external local_unnamed_addr global %struct.rb_execution_context_struct*, align 8
@ruby_vm_global_constant_state = external local_unnamed_addr global i64, align 8
@rb_eTypeError = external local_unnamed_addr global i64, align 8
@.str.1 = private unnamed_addr constant [25 x i8] c"Passed `nil` into T.must\00", align 1
@rb_eRuntimeError = external local_unnamed_addr global i64, align 8
@sorbet_getTRetry.retry = internal constant [25 x i8] c"T::Private::Retry::RETRY\00", align 16
@rb_eException = external local_unnamed_addr global i64, align 8
@.str.9 = private unnamed_addr constant [95 x i8] c"sorbet_getBuildSCMRevision: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@.str.10 = private unnamed_addr constant [93 x i8] c"sorbet_getIsReleaseBuild: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@"stackFramePrecomputed_func_<root>.<static-init>$151" = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@"rubyIdPrecomputed_<top (required)>" = internal unnamed_addr global i64 0, align 8
@"str_<top (required)>" = private unnamed_addr constant [17 x i8] c"<top (required)>\00", align 1
@"rubyStrFrozen_<top (required)>" = internal unnamed_addr global i64 0, align 8
@"rubyStrFrozen_test/testdata/compiler/intrinsics/t_must.rb" = internal unnamed_addr global i64 0, align 8
@"str_test/testdata/compiler/intrinsics/t_must.rb" = private unnamed_addr constant [44 x i8] c"test/testdata/compiler/intrinsics/t_must.rb\00", align 1
@iseqEncodedArray = internal global [28 x i64] zeroinitializer
@fileLineNumberInfo = internal global %struct.SorbetLineNumberInfo zeroinitializer
@str_Test = private unnamed_addr constant [5 x i8] c"Test\00", align 1
@ic_test_known_nil = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_test_known_nil = internal unnamed_addr global i64 0, align 8
@str_test_known_nil = private unnamed_addr constant [15 x i8] c"test_known_nil\00", align 1
@ic_test_nilable_arg = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_test_nilable_arg = internal unnamed_addr global i64 0, align 8
@str_test_nilable_arg = private unnamed_addr constant [17 x i8] c"test_nilable_arg\00", align 1
@ic_test_nilable_arg.1 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_test_nilable_arg.2 = internal global %struct.FunctionInlineCache zeroinitializer
@stackFramePrecomputed_func_Test.test_known_nil = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@"rubyIdPrecomputed_<exceptionValue>" = internal unnamed_addr global i64 0, align 8
@"str_<exceptionValue>" = private unnamed_addr constant [17 x i8] c"<exceptionValue>\00", align 1
@"rubyIdPrecomputed_<magic>" = internal unnamed_addr global i64 0, align 8
@"str_<magic>" = private unnamed_addr constant [8 x i8] c"<magic>\00", align 1
@"rubyIdPrecomputed_<returnMethodTemp>" = internal unnamed_addr global i64 0, align 8
@"str_<returnMethodTemp>" = private unnamed_addr constant [19 x i8] c"<returnMethodTemp>\00", align 1
@"rubyIdPrecomputed_<gotoDeadTemp>" = internal unnamed_addr global i64 0, align 8
@"str_<gotoDeadTemp>" = private unnamed_addr constant [15 x i8] c"<gotoDeadTemp>\00", align 1
@"stackFramePrecomputed_func_Test.test_known_nil$block_2" = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@"rubyIdPrecomputed_rescue for" = internal unnamed_addr global i64 0, align 8
@"str_rescue for" = private unnamed_addr constant [11 x i8] c"rescue for\00", align 1
@"rubyStrFrozen_rescue for" = internal unnamed_addr global i64 0, align 8
@"stackFramePrecomputed_func_Test.test_known_nil$block_3" = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@"rubyIdPrecomputed_ensure for" = internal unnamed_addr global i64 0, align 8
@"str_ensure for" = private unnamed_addr constant [11 x i8] c"ensure for\00", align 1
@"rubyStrFrozen_ensure for" = internal unnamed_addr global i64 0, align 8
@"<retry-singleton>" = internal unnamed_addr global i64 0
@rubyIdPrecomputed_must = internal unnamed_addr global i64 0, align 8
@str_must = private unnamed_addr constant [5 x i8] c"must\00", align 1
@ic_must = internal global %struct.FunctionInlineCache zeroinitializer
@"ic_is_a?" = internal global %struct.FunctionInlineCache zeroinitializer
@"rubyIdPrecomputed_is_a?" = internal unnamed_addr global i64 0, align 8
@"str_is_a?" = private unnamed_addr constant [6 x i8] c"is_a?\00", align 1
@ic_puts = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_puts = internal unnamed_addr global i64 0, align 8
@str_puts = private unnamed_addr constant [5 x i8] c"puts\00", align 1
@stackFramePrecomputed_func_Test.test_nilable_arg = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@rubyIdPrecomputed_arg = internal unnamed_addr global i64 0, align 8
@str_arg = private unnamed_addr constant [4 x i8] c"arg\00", align 1
@"stackFramePrecomputed_func_Test.test_nilable_arg$block_2" = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@"stackFramePrecomputed_func_Test.test_nilable_arg$block_3" = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@ic_must.3 = internal global %struct.FunctionInlineCache zeroinitializer
@"rubyStrFrozen_ wasn't nil" = internal unnamed_addr global i64 0, align 8
@"str_ wasn't nil" = private unnamed_addr constant [12 x i8] c" wasn't nil\00", align 1
@"rubyIdPrecomputed_<string-interpolate>" = internal unnamed_addr global i64 0, align 8
@"str_<string-interpolate>" = private unnamed_addr constant [21 x i8] c"<string-interpolate>\00", align 1
@ic_puts.4 = internal global %struct.FunctionInlineCache zeroinitializer
@"ic_is_a?.5" = internal global %struct.FunctionInlineCache zeroinitializer
@ic_puts.6 = internal global %struct.FunctionInlineCache zeroinitializer
@"stackFramePrecomputed_func_Test.<static-init>" = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@rubyIdPrecomputed_normal = internal unnamed_addr global i64 0, align 8
@str_normal = private unnamed_addr constant [7 x i8] c"normal\00", align 1
@ic_keep_self_def = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_keep_self_def = internal unnamed_addr global i64 0, align 8
@str_keep_self_def = private unnamed_addr constant [14 x i8] c"keep_self_def\00", align 1
@ic_keep_self_def.7 = internal global %struct.FunctionInlineCache zeroinitializer
@guard_epoch_Test = linkonce local_unnamed_addr global i64 0
@guarded_const_Test = linkonce local_unnamed_addr global i64 0
@rb_eStandardError = external local_unnamed_addr constant i64

declare i64 @rb_id2sym(i64) local_unnamed_addr #0

declare i64 @rb_errinfo() local_unnamed_addr #0

; Function Attrs: noreturn
declare void @sorbet_raiseArity(i32, i32, i32) local_unnamed_addr #1

declare %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64, i64, i64, i64, %struct.rb_iseq_struct*, i32, i32, %struct.SorbetLineNumberInfo*, i64*, i32, i32) local_unnamed_addr #0

declare void @sorbet_initLineNumberInfo(%struct.SorbetLineNumberInfo*, i64*, i32) local_unnamed_addr #0

declare i64 @sorbet_getConstant(i8*, i64) local_unnamed_addr #0

declare i64 @sorbet_readRealpath() local_unnamed_addr #0

declare %struct.rb_control_frame_struct* @sorbet_pushStaticInitFrame(i64) local_unnamed_addr #0

declare void @sorbet_popFrame() local_unnamed_addr #0

declare void @sorbet_vm_env_write_slowpath(i64*, i32, i64) local_unnamed_addr #0

declare void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache*, i64, i32, i32, i32, i64*) local_unnamed_addr #0

declare i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache*, i64) local_unnamed_addr #0

declare void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_iseq_struct*) local_unnamed_addr #0

declare void @sorbet_setExceptionStackFrame(%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_iseq_struct*) local_unnamed_addr #0

declare i64 @sorbet_stringInterpolate(i64, i64, i32, i64*, i64 (i64, i64, i32, i64*, i64)*, i64) local_unnamed_addr #0

declare void @sorbet_vm_define_method(i64, i8*, i64 (i32, i64*, i64, %struct.rb_control_frame_struct*)*, i8*, %struct.rb_iseq_struct*, i1 zeroext) local_unnamed_addr #0

declare i64 @rb_define_module(i8*) local_unnamed_addr #0

declare i64 @rb_intern2(i8*, i64) local_unnamed_addr #0

declare i64 @rb_fstring_new(i8*, i64) local_unnamed_addr #0

declare void @rb_gc_register_mark_object(i64) local_unnamed_addr #0

; Function Attrs: noreturn
declare void @rb_raise(i64, i8*, ...) local_unnamed_addr #1

; Function Attrs: argmemonly nofree nosync nounwind willreturn
declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #2

; Function Attrs: argmemonly nofree nosync nounwind willreturn
declare void @llvm.lifetime.end.p0i8(i64 immarg, i8* nocapture) #2

declare i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct*, i32) local_unnamed_addr #0

; Function Attrs: allocsize(0,1)
declare noalias nonnull i8* @ruby_xcalloc(i64, i64) local_unnamed_addr #3

; Function Attrs: allocsize(0,1)
declare noalias nonnull i8* @ruby_xmalloc2(i64, i64) local_unnamed_addr #3

; Function Attrs: argmemonly nofree nosync nounwind willreturn
declare void @llvm.memcpy.p0i8.p0i8.i64(i8* noalias nocapture writeonly, i8* noalias nocapture readonly, i64, i1 immarg) #2

declare void @rb_set_errinfo(i64) local_unnamed_addr #0

; Function Attrs: nounwind ssp uwtable
define internal noundef i64 @sorbet_applyExceptionClosure(i64 %0) #4 {
  %2 = inttoptr i64 %0 to %struct.ExceptionClosure*
  %3 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %2, i64 0, i32 0
  %4 = load i64 (i64**, i64, %struct.rb_control_frame_struct*)*, i64 (i64**, i64, %struct.rb_control_frame_struct*)** %3, align 8, !tbaa !4
  %5 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %2, i64 0, i32 1
  %6 = load i64**, i64*** %5, align 8, !tbaa !10
  %7 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %2, i64 0, i32 2
  %8 = load i64, i64* %7, align 8, !tbaa !11
  %9 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %2, i64 0, i32 3
  %10 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %9, align 8, !tbaa !12
  %11 = tail call i64 %4(i64** %6, i64 %8, %struct.rb_control_frame_struct* %10) #8
  %12 = icmp eq i64 %11, 52
  br i1 %12, label %16, label %13

13:                                               ; preds = %1
  %14 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %2, i64 0, i32 4
  %15 = load i64*, i64** %14, align 8, !tbaa !13
  store i64 %11, i64* %15, align 8, !tbaa !14
  br label %16

16:                                               ; preds = %13, %1
  ret i64 52
}

; Function Attrs: nofree norecurse nosync nounwind ssp uwtable willreturn writeonly
define internal noundef i64 @sorbet_rescueStoreException(i64 %0, i64 %1) #5 {
  %3 = inttoptr i64 %0 to i64*
  store i64 %1, i64* %3, align 8, !tbaa !14
  ret i64 52
}

declare i64 @rb_rescue2(i64 (i64)*, i64, i64 (i64, i64)*, i64, ...) local_unnamed_addr #0

; Function Attrs: noreturn
declare void @rb_exc_raise(i64) local_unnamed_addr #1

; Function Attrs: nounwind ssp uwtable
define weak i32 @sorbet_getIsReleaseBuild() local_unnamed_addr #4 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !14
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* noundef getelementptr inbounds ([93 x i8], [93 x i8]* @.str.10, i64 0, i64 0)) #9
  unreachable
}

; Function Attrs: nounwind ssp uwtable
define weak i8* @sorbet_getBuildSCMRevision() local_unnamed_addr #4 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !14
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* noundef getelementptr inbounds ([95 x i8], [95 x i8]* @.str.9, i64 0, i64 0)) #9
  unreachable
}

; Function Attrs: nofree nosync nounwind readnone willreturn
declare i8* @llvm.frameaddress.p0i8(i32 immarg) #6

; Function Attrs: nofree nosync nounwind willreturn
declare i8* @llvm.stacksave() #7

; Function Attrs: nounwind
declare i32 @llvm.eh.sjlj.setjmp(i8*) #8

; Function Attrs: noreturn nounwind
declare void @llvm.eh.sjlj.longjmp(i8*) #9

; Function Attrs: nounwind sspreq uwtable
define internal fastcc void @"func_Test.<static-init>L62"(%struct.rb_control_frame_struct* %cfp) unnamed_addr #10 !dbg !15 {
fastSymCallIntrinsic_Static_keep_self_def:
  %stackFrame = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Test.<static-init>", align 8
  %0 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !19
  %1 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %0, i64 0, i32 2
  %2 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %1, align 8, !tbaa !20
  %3 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 2
  store %struct.rb_iseq_struct* %stackFrame, %struct.rb_iseq_struct** %3, align 8, !tbaa !24
  %4 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 4
  %5 = load i64*, i64** %4, align 8, !tbaa !26
  %6 = load i64, i64* %5, align 8, !tbaa !14
  %7 = and i64 %6, -33
  store i64 %7, i64* %5, align 8, !tbaa !14
  tail call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* %0, %struct.rb_control_frame_struct* %2, %struct.rb_iseq_struct* %stackFrame) #8
  %8 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %cfp, i64 0, i32 0
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 6), i64** %8, align 8, !dbg !27, !tbaa !19
  %rubyId_test_known_nil = load i64, i64* @rubyIdPrecomputed_test_known_nil, align 8, !dbg !28
  %rawSym = tail call i64 @rb_id2sym(i64 %rubyId_test_known_nil), !dbg !28
  %rubyId_normal = load i64, i64* @rubyIdPrecomputed_normal, align 8, !dbg !28
  %rawSym17 = tail call i64 @rb_id2sym(i64 %rubyId_normal), !dbg !28
  %9 = load i64, i64* @guard_epoch_Test, align 8, !dbg !28
  %10 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !28, !tbaa !29
  %needTakeSlowPath = icmp ne i64 %9, %10, !dbg !28
  br i1 %needTakeSlowPath, label %11, label %12, !dbg !28, !prof !31

11:                                               ; preds = %fastSymCallIntrinsic_Static_keep_self_def
  tail call void @const_recompute_Test(), !dbg !28
  br label %12, !dbg !28

12:                                               ; preds = %fastSymCallIntrinsic_Static_keep_self_def, %11
  %13 = load i64, i64* @guarded_const_Test, align 8, !dbg !28
  %14 = load i64, i64* @guard_epoch_Test, align 8, !dbg !28
  %15 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !28, !tbaa !29
  %guardUpdated = icmp eq i64 %14, %15, !dbg !28
  tail call void @llvm.assume(i1 %guardUpdated), !dbg !28
  %stackFrame18 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @stackFramePrecomputed_func_Test.test_known_nil, align 8, !dbg !28
  %16 = tail call noalias nonnull i8* @ruby_xcalloc(i64 noundef 1, i64 noundef 64) #17, !dbg !28
  %17 = bitcast i8* %16 to i16*, !dbg !28
  %18 = load i16, i16* %17, align 8, !dbg !28
  %19 = and i16 %18, -384, !dbg !28
  store i16 %19, i16* %17, align 8, !dbg !28
  %20 = getelementptr inbounds i8, i8* %16, i64 4, !dbg !28
  %21 = bitcast i8* %20 to i32*, !dbg !28
  tail call void @llvm.memset.p0i8.i64(i8* nonnull align 4 %20, i8 0, i64 28, i1 false), !dbg !28
  tail call void @sorbet_vm_define_method(i64 %13, i8* noundef getelementptr inbounds ([15 x i8], [15 x i8]* @str_test_known_nil, i64 0, i64 0), i64 (i32, i64*, i64, %struct.rb_control_frame_struct*)* noundef @func_Test.test_known_nil, i8* nonnull %16, %struct.rb_iseq_struct* %stackFrame18, i1 noundef zeroext true) #8, !dbg !28
  %22 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !28, !tbaa !19
  %23 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %22, i64 0, i32 5, !dbg !28
  %24 = load i32, i32* %23, align 8, !dbg !28, !tbaa !32
  %25 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %22, i64 0, i32 6, !dbg !28
  %26 = load i32, i32* %25, align 4, !dbg !28, !tbaa !33
  %27 = xor i32 %26, -1, !dbg !28
  %28 = and i32 %27, %24, !dbg !28
  %29 = icmp eq i32 %28, 0, !dbg !28
  br i1 %29, label %fastSymCallIntrinsic_Static_keep_self_def31, label %30, !dbg !28, !prof !34

30:                                               ; preds = %12
  %31 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %22, i64 0, i32 8, !dbg !28
  %32 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %31, align 8, !dbg !28, !tbaa !35
  %33 = tail call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* %32, i32 noundef 0) #8, !dbg !28
  br label %fastSymCallIntrinsic_Static_keep_self_def31, !dbg !28

fastSymCallIntrinsic_Static_keep_self_def31:      ; preds = %12, %30
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 14), i64** %8, align 8, !dbg !28, !tbaa !19
  %rubyId_test_nilable_arg = load i64, i64* @rubyIdPrecomputed_test_nilable_arg, align 8, !dbg !36
  %rawSym23 = tail call i64 @rb_id2sym(i64 %rubyId_test_nilable_arg), !dbg !36
  %rubyId_normal24 = load i64, i64* @rubyIdPrecomputed_normal, align 8, !dbg !36
  %rawSym25 = tail call i64 @rb_id2sym(i64 %rubyId_normal24), !dbg !36
  %stackFrame32 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @stackFramePrecomputed_func_Test.test_nilable_arg, align 8, !dbg !36
  %34 = tail call noalias nonnull i8* @ruby_xcalloc(i64 noundef 1, i64 noundef 64) #17, !dbg !36
  %35 = bitcast i8* %34 to i16*, !dbg !36
  %36 = load i16, i16* %35, align 8, !dbg !36
  %37 = and i16 %36, -384, !dbg !36
  %38 = or i16 %37, 1, !dbg !36
  store i16 %38, i16* %35, align 8, !dbg !36
  %39 = getelementptr inbounds i8, i8* %34, i64 8, !dbg !36
  %40 = bitcast i8* %39 to i32*, !dbg !36
  store i32 1, i32* %40, align 8, !dbg !36, !tbaa !37
  %41 = getelementptr inbounds i8, i8* %34, i64 12, !dbg !36
  %42 = bitcast i8* %41 to i32*, !dbg !36
  %43 = getelementptr inbounds i8, i8* %34, i64 4, !dbg !36
  %44 = bitcast i8* %43 to i32*, !dbg !36
  tail call void @llvm.memset.p0i8.i64(i8* nonnull align 4 %41, i8 0, i64 20, i1 false), !dbg !36
  store i32 1, i32* %44, align 4, !dbg !36, !tbaa !40
  %positional_table = alloca i64, align 8, !dbg !36
  %rubyId_arg = load i64, i64* @rubyIdPrecomputed_arg, align 8, !dbg !36
  store i64 %rubyId_arg, i64* %positional_table, align 8, !dbg !36
  %45 = tail call noalias nonnull i8* @ruby_xmalloc2(i64 noundef 1, i64 noundef 8) #17, !dbg !36
  %46 = bitcast i64* %positional_table to i8*, !dbg !36
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* nocapture nonnull writeonly align 1 %45, i8* nocapture noundef nonnull readonly align 8 dereferenceable(8) %46, i64 noundef 8, i1 noundef false) #8, !dbg !36
  %47 = getelementptr inbounds i8, i8* %34, i64 32, !dbg !36
  %48 = bitcast i8* %47 to i8**, !dbg !36
  store i8* %45, i8** %48, align 8, !dbg !36, !tbaa !41
  tail call void @sorbet_vm_define_method(i64 %13, i8* noundef getelementptr inbounds ([17 x i8], [17 x i8]* @str_test_nilable_arg, i64 0, i64 0), i64 (i32, i64*, i64, %struct.rb_control_frame_struct*)* noundef @func_Test.test_nilable_arg, i8* nonnull %34, %struct.rb_iseq_struct* %stackFrame32, i1 noundef zeroext true) #8, !dbg !36
  %49 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !36, !tbaa !19
  %50 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %49, i64 0, i32 5, !dbg !36
  %51 = load i32, i32* %50, align 8, !dbg !36, !tbaa !32
  %52 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %49, i64 0, i32 6, !dbg !36
  %53 = load i32, i32* %52, align 4, !dbg !36, !tbaa !33
  %54 = xor i32 %53, -1, !dbg !36
  %55 = and i32 %54, %51, !dbg !36
  %56 = icmp eq i32 %55, 0, !dbg !36
  br i1 %56, label %normalReturn, label %57, !dbg !36, !prof !34

57:                                               ; preds = %fastSymCallIntrinsic_Static_keep_self_def31
  %58 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %49, i64 0, i32 8, !dbg !36
  %59 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %58, align 8, !dbg !36, !tbaa !35
  %60 = tail call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* %59, i32 noundef 0) #8, !dbg !36
  br label %normalReturn, !dbg !36

normalReturn:                                     ; preds = %57, %fastSymCallIntrinsic_Static_keep_self_def31
  ret void
}

; Function Attrs: sspreq
define void @Init_t_must() local_unnamed_addr #11 {
entry:
  %locals.i44.i = alloca i64, i32 0, align 8
  %locals.i28.i = alloca i64, i32 5, align 8
  %locals.i23.i = alloca i64, i32 4, align 8
  %locals.i.i = alloca i64, i32 0, align 8
  %realpath = tail call i64 @sorbet_readRealpath()
  %0 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 noundef 16) #8
  store i64 %0, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %1 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([15 x i8], [15 x i8]* @str_test_known_nil, i64 0, i64 0), i64 noundef 14) #8
  store i64 %1, i64* @rubyIdPrecomputed_test_known_nil, align 8
  %2 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([17 x i8], [17 x i8]* @str_test_nilable_arg, i64 0, i64 0), i64 noundef 16) #8
  store i64 %2, i64* @rubyIdPrecomputed_test_nilable_arg, align 8
  %3 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<exceptionValue>", i64 0, i64 0), i64 noundef 16) #8
  store i64 %3, i64* @"rubyIdPrecomputed_<exceptionValue>", align 8
  %4 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([8 x i8], [8 x i8]* @"str_<magic>", i64 0, i64 0), i64 noundef 7) #8
  store i64 %4, i64* @"rubyIdPrecomputed_<magic>", align 8
  %5 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([19 x i8], [19 x i8]* @"str_<returnMethodTemp>", i64 0, i64 0), i64 noundef 18) #8
  store i64 %5, i64* @"rubyIdPrecomputed_<returnMethodTemp>", align 8
  %6 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([15 x i8], [15 x i8]* @"str_<gotoDeadTemp>", i64 0, i64 0), i64 noundef 14) #8
  store i64 %6, i64* @"rubyIdPrecomputed_<gotoDeadTemp>", align 8
  %7 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([11 x i8], [11 x i8]* @"str_rescue for", i64 0, i64 0), i64 noundef 10) #8
  store i64 %7, i64* @"rubyIdPrecomputed_rescue for", align 8
  %8 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([11 x i8], [11 x i8]* @"str_ensure for", i64 0, i64 0), i64 noundef 10) #8
  store i64 %8, i64* @"rubyIdPrecomputed_ensure for", align 8
  %9 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([5 x i8], [5 x i8]* @str_must, i64 0, i64 0), i64 noundef 4) #8
  store i64 %9, i64* @rubyIdPrecomputed_must, align 8
  %10 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([6 x i8], [6 x i8]* @"str_is_a?", i64 0, i64 0), i64 noundef 5) #8
  store i64 %10, i64* @"rubyIdPrecomputed_is_a?", align 8
  %11 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([5 x i8], [5 x i8]* @str_puts, i64 0, i64 0), i64 noundef 4) #8
  store i64 %11, i64* @rubyIdPrecomputed_puts, align 8
  %12 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @str_arg, i64 0, i64 0), i64 noundef 3) #8
  store i64 %12, i64* @rubyIdPrecomputed_arg, align 8
  %13 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([21 x i8], [21 x i8]* @"str_<string-interpolate>", i64 0, i64 0), i64 noundef 20) #8
  store i64 %13, i64* @"rubyIdPrecomputed_<string-interpolate>", align 8
  %14 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([7 x i8], [7 x i8]* @str_normal, i64 0, i64 0), i64 noundef 6) #8
  store i64 %14, i64* @rubyIdPrecomputed_normal, align 8
  %15 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([14 x i8], [14 x i8]* @str_keep_self_def, i64 0, i64 0), i64 noundef 13) #8
  store i64 %15, i64* @rubyIdPrecomputed_keep_self_def, align 8
  %16 = tail call i64 @rb_fstring_new(i8* noundef getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 noundef 16) #8
  tail call void @rb_gc_register_mark_object(i64 %16) #8
  store i64 %16, i64* @"rubyStrFrozen_<top (required)>", align 8
  %17 = tail call i64 @rb_fstring_new(i8* noundef getelementptr inbounds ([44 x i8], [44 x i8]* @"str_test/testdata/compiler/intrinsics/t_must.rb", i64 0, i64 0), i64 noundef 43) #8
  tail call void @rb_gc_register_mark_object(i64 %17) #8
  store i64 %17, i64* @"rubyStrFrozen_test/testdata/compiler/intrinsics/t_must.rb", align 8
  tail call void @sorbet_initLineNumberInfo(%struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i32 0, i32 0), i32 noundef 28)
  %"rubyId_<top (required)>.i.i" = load i64, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %"rubyStr_<top (required)>.i.i" = load i64, i64* @"rubyStrFrozen_<top (required)>", align 8
  %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/intrinsics/t_must.rb", align 8
  %18 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_<top (required)>.i.i", i64 %"rubyId_<top (required)>.i.i", i64 %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i.i", i64 %realpath, %struct.rb_iseq_struct* noundef null, i32 noundef 0, i32 noundef 5, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef nonnull %locals.i.i, i32 noundef 0, i32 noundef 2)
  store %struct.rb_iseq_struct* %18, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_<root>.<static-init>$151", align 8
  %rubyId_test_known_nil.i = load i64, i64* @rubyIdPrecomputed_test_known_nil, align 8, !dbg !42
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_test_known_nil, i64 %rubyId_test_known_nil.i, i32 noundef 16, i32 noundef 0, i32 noundef 0, i64* noundef null), !dbg !42
  %rubyId_test_nilable_arg.i = load i64, i64* @rubyIdPrecomputed_test_nilable_arg, align 8, !dbg !44
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_test_nilable_arg, i64 %rubyId_test_nilable_arg.i, i32 noundef 16, i32 noundef 1, i32 noundef 0, i64* noundef null), !dbg !44
  %rubyId_test_nilable_arg2.i = load i64, i64* @rubyIdPrecomputed_test_nilable_arg, align 8, !dbg !45
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_test_nilable_arg.1, i64 %rubyId_test_nilable_arg2.i, i32 noundef 16, i32 noundef 1, i32 noundef 0, i64* noundef null), !dbg !45
  %rubyId_test_nilable_arg4.i = load i64, i64* @rubyIdPrecomputed_test_nilable_arg, align 8, !dbg !46
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_test_nilable_arg.2, i64 %rubyId_test_nilable_arg4.i, i32 noundef 16, i32 noundef 1, i32 noundef 0, i64* noundef null), !dbg !46
  %19 = call i64 @rb_fstring_new(i8* noundef getelementptr inbounds ([15 x i8], [15 x i8]* @str_test_known_nil, i64 0, i64 0), i64 noundef 14) #8
  call void @rb_gc_register_mark_object(i64 %19) #8
  %20 = bitcast i64* %locals.i23.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 32, i8* nonnull %20)
  %rubyId_test_known_nil.i.i = load i64, i64* @rubyIdPrecomputed_test_known_nil, align 8
  %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i22.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/intrinsics/t_must.rb", align 8
  %"rubyId_<exceptionValue>.i.i" = load i64, i64* @"rubyIdPrecomputed_<exceptionValue>", align 8
  store i64 %"rubyId_<exceptionValue>.i.i", i64* %locals.i23.i, align 8
  %"rubyId_<magic>.i.i" = load i64, i64* @"rubyIdPrecomputed_<magic>", align 8
  %21 = getelementptr i64, i64* %locals.i23.i, i32 1
  store i64 %"rubyId_<magic>.i.i", i64* %21, align 8
  %"rubyId_<returnMethodTemp>.i.i" = load i64, i64* @"rubyIdPrecomputed_<returnMethodTemp>", align 8
  %22 = getelementptr i64, i64* %locals.i23.i, i32 2
  store i64 %"rubyId_<returnMethodTemp>.i.i", i64* %22, align 8
  %"rubyId_<gotoDeadTemp>.i.i" = load i64, i64* @"rubyIdPrecomputed_<gotoDeadTemp>", align 8
  %23 = getelementptr i64, i64* %locals.i23.i, i32 3
  store i64 %"rubyId_<gotoDeadTemp>.i.i", i64* %23, align 8
  %24 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 %19, i64 %rubyId_test_known_nil.i.i, i64 %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i22.i", i64 %realpath, %struct.rb_iseq_struct* noundef null, i32 noundef 1, i32 noundef 6, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef nonnull align 8 %locals.i23.i, i32 noundef 4, i32 noundef 2)
  store %struct.rb_iseq_struct* %24, %struct.rb_iseq_struct** @stackFramePrecomputed_func_Test.test_known_nil, align 8
  call void @llvm.lifetime.end.p0i8(i64 32, i8* nonnull %20)
  %25 = call i64 @rb_fstring_new(i8* noundef getelementptr inbounds ([11 x i8], [11 x i8]* @"str_rescue for", i64 0, i64 0), i64 noundef 10) #8
  call void @rb_gc_register_mark_object(i64 %25) #8
  store i64 %25, i64* @"rubyStrFrozen_rescue for", align 8
  %stackFrame.i.i = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @stackFramePrecomputed_func_Test.test_known_nil, align 8
  %"rubyId_rescue for.i.i" = load i64, i64* @"rubyIdPrecomputed_rescue for", align 8
  %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i24.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/intrinsics/t_must.rb", align 8
  %26 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 %25, i64 %"rubyId_rescue for.i.i", i64 %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i24.i", i64 %realpath, %struct.rb_iseq_struct* %stackFrame.i.i, i32 noundef 4, i32 noundef 6, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef null, i32 noundef 0, i32 noundef 2)
  store %struct.rb_iseq_struct* %26, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Test.test_known_nil$block_2", align 8
  %27 = call i64 @rb_fstring_new(i8* noundef getelementptr inbounds ([11 x i8], [11 x i8]* @"str_ensure for", i64 0, i64 0), i64 noundef 10) #8
  call void @rb_gc_register_mark_object(i64 %27) #8
  store i64 %27, i64* @"rubyStrFrozen_ensure for", align 8
  %stackFrame.i25.i = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @stackFramePrecomputed_func_Test.test_known_nil, align 8
  %"rubyId_ensure for.i.i" = load i64, i64* @"rubyIdPrecomputed_ensure for", align 8
  %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i26.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/intrinsics/t_must.rb", align 8
  %28 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 %27, i64 %"rubyId_ensure for.i.i", i64 %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i26.i", i64 %realpath, %struct.rb_iseq_struct* %stackFrame.i25.i, i32 noundef 5, i32 noundef 6, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef null, i32 noundef 0, i32 noundef 2)
  store %struct.rb_iseq_struct* %28, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Test.test_known_nil$block_3", align 8
  %29 = call i64 @sorbet_getConstant(i8* noundef getelementptr inbounds ([25 x i8], [25 x i8]* @sorbet_getTRetry.retry, i64 0, i64 0), i64 noundef 25) #8
  store i64 %29, i64* @"<retry-singleton>", align 8
  %rubyId_must.i = load i64, i64* @rubyIdPrecomputed_must, align 8, !dbg !47
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_must, i64 %rubyId_must.i, i32 noundef 16, i32 noundef 1, i32 noundef 0, i64* noundef null), !dbg !47
  %"rubyId_is_a?.i" = load i64, i64* @"rubyIdPrecomputed_is_a?", align 8, !dbg !50
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @"ic_is_a?", i64 %"rubyId_is_a?.i", i32 noundef 16, i32 noundef 1, i32 noundef 0, i64* noundef null), !dbg !50
  %rubyId_puts.i = load i64, i64* @rubyIdPrecomputed_puts, align 8, !dbg !52
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_puts, i64 %rubyId_puts.i, i32 noundef 20, i32 noundef 1, i32 noundef 0, i64* noundef null), !dbg !52
  %30 = call i64 @rb_fstring_new(i8* noundef getelementptr inbounds ([17 x i8], [17 x i8]* @str_test_nilable_arg, i64 0, i64 0), i64 noundef 16) #8
  call void @rb_gc_register_mark_object(i64 %30) #8
  %31 = bitcast i64* %locals.i28.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 40, i8* nonnull %31)
  %rubyId_test_nilable_arg.i.i = load i64, i64* @rubyIdPrecomputed_test_nilable_arg, align 8
  %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i27.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/intrinsics/t_must.rb", align 8
  %"rubyId_<exceptionValue>.i29.i" = load i64, i64* @"rubyIdPrecomputed_<exceptionValue>", align 8
  store i64 %"rubyId_<exceptionValue>.i29.i", i64* %locals.i28.i, align 8
  %rubyId_arg.i.i = load i64, i64* @rubyIdPrecomputed_arg, align 8
  %32 = getelementptr i64, i64* %locals.i28.i, i32 1
  store i64 %rubyId_arg.i.i, i64* %32, align 8
  %"rubyId_<magic>.i30.i" = load i64, i64* @"rubyIdPrecomputed_<magic>", align 8
  %33 = getelementptr i64, i64* %locals.i28.i, i32 2
  store i64 %"rubyId_<magic>.i30.i", i64* %33, align 8
  %"rubyId_<returnMethodTemp>.i31.i" = load i64, i64* @"rubyIdPrecomputed_<returnMethodTemp>", align 8
  %34 = getelementptr i64, i64* %locals.i28.i, i32 3
  store i64 %"rubyId_<returnMethodTemp>.i31.i", i64* %34, align 8
  %"rubyId_<gotoDeadTemp>.i32.i" = load i64, i64* @"rubyIdPrecomputed_<gotoDeadTemp>", align 8
  %35 = getelementptr i64, i64* %locals.i28.i, i32 4
  store i64 %"rubyId_<gotoDeadTemp>.i32.i", i64* %35, align 8
  %36 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 %30, i64 %rubyId_test_nilable_arg.i.i, i64 %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i27.i", i64 %realpath, %struct.rb_iseq_struct* noundef null, i32 noundef 1, i32 noundef 14, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef nonnull align 8 %locals.i28.i, i32 noundef 5, i32 noundef 3)
  store %struct.rb_iseq_struct* %36, %struct.rb_iseq_struct** @stackFramePrecomputed_func_Test.test_nilable_arg, align 8
  call void @llvm.lifetime.end.p0i8(i64 40, i8* nonnull %31)
  %"rubyId_rescue for.i34.i" = load i64, i64* @"rubyIdPrecomputed_rescue for", align 8
  %"rubyStr_rescue for.i35.i" = load i64, i64* @"rubyStrFrozen_rescue for", align 8
  %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i36.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/intrinsics/t_must.rb", align 8
  %37 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_rescue for.i35.i", i64 %"rubyId_rescue for.i34.i", i64 %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i36.i", i64 %realpath, %struct.rb_iseq_struct* %36, i32 noundef 4, i32 noundef 14, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef null, i32 noundef 0, i32 noundef 3)
  store %struct.rb_iseq_struct* %37, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Test.test_nilable_arg$block_2", align 8
  %stackFrame.i37.i = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @stackFramePrecomputed_func_Test.test_nilable_arg, align 8
  %"rubyId_ensure for.i38.i" = load i64, i64* @"rubyIdPrecomputed_ensure for", align 8
  %"rubyStr_ensure for.i39.i" = load i64, i64* @"rubyStrFrozen_ensure for", align 8
  %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i40.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/intrinsics/t_must.rb", align 8
  %38 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_ensure for.i39.i", i64 %"rubyId_ensure for.i38.i", i64 %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i40.i", i64 %realpath, %struct.rb_iseq_struct* %stackFrame.i37.i, i32 noundef 5, i32 noundef 14, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef null, i32 noundef 0, i32 noundef 3)
  store %struct.rb_iseq_struct* %38, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Test.test_nilable_arg$block_3", align 8
  %rubyId_must9.i = load i64, i64* @rubyIdPrecomputed_must, align 8, !dbg !53
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_must.3, i64 %rubyId_must9.i, i32 noundef 16, i32 noundef 1, i32 noundef 0, i64* noundef null), !dbg !53
  %39 = call i64 @rb_fstring_new(i8* noundef getelementptr inbounds ([12 x i8], [12 x i8]* @"str_ wasn't nil", i64 0, i64 0), i64 noundef 11) #8
  call void @rb_gc_register_mark_object(i64 %39) #8
  store i64 %39, i64* @"rubyStrFrozen_ wasn't nil", align 8
  %rubyId_puts11.i = load i64, i64* @rubyIdPrecomputed_puts, align 8, !dbg !56
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_puts.4, i64 %rubyId_puts11.i, i32 noundef 20, i32 noundef 1, i32 noundef 0, i64* noundef null), !dbg !56
  %"rubyId_is_a?14.i" = load i64, i64* @"rubyIdPrecomputed_is_a?", align 8, !dbg !57
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @"ic_is_a?.5", i64 %"rubyId_is_a?14.i", i32 noundef 16, i32 noundef 1, i32 noundef 0, i64* noundef null), !dbg !57
  %rubyId_puts16.i = load i64, i64* @rubyIdPrecomputed_puts, align 8, !dbg !59
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_puts.6, i64 %rubyId_puts16.i, i32 noundef 20, i32 noundef 1, i32 noundef 0, i64* noundef null), !dbg !59
  %"rubyId_<top (required)>.i41.i" = load i64, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %"rubyStr_<top (required)>.i42.i" = load i64, i64* @"rubyStrFrozen_<top (required)>", align 8
  %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i43.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/intrinsics/t_must.rb", align 8
  %40 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_<top (required)>.i42.i", i64 %"rubyId_<top (required)>.i41.i", i64 %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i43.i", i64 %realpath, %struct.rb_iseq_struct* noundef null, i32 noundef 3, i32 noundef 5, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef nonnull %locals.i44.i, i32 noundef 0, i32 noundef 4)
  store %struct.rb_iseq_struct* %40, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Test.<static-init>", align 8
  %rubyId_keep_self_def.i = load i64, i64* @rubyIdPrecomputed_keep_self_def, align 8, !dbg !28
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_keep_self_def, i64 %rubyId_keep_self_def.i, i32 noundef 16, i32 noundef 3, i32 noundef 0, i64* noundef null), !dbg !28
  %rubyId_keep_self_def20.i = load i64, i64* @rubyIdPrecomputed_keep_self_def, align 8, !dbg !36
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_keep_self_def.7, i64 %rubyId_keep_self_def20.i, i32 noundef 16, i32 noundef 3, i32 noundef 0, i64* noundef null), !dbg !36
  %41 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !19
  %42 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %41, i64 0, i32 2
  %43 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %42, align 8, !tbaa !20
  %stackFrame.i = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_<root>.<static-init>$151", align 8
  %44 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %43, i64 0, i32 2
  store %struct.rb_iseq_struct* %stackFrame.i, %struct.rb_iseq_struct** %44, align 8, !tbaa !24
  %45 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %43, i64 0, i32 4
  %46 = load i64*, i64** %45, align 8, !tbaa !26
  %47 = load i64, i64* %46, align 8, !tbaa !14
  %48 = and i64 %47, -33
  store i64 %48, i64* %46, align 8, !tbaa !14
  call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* %41, %struct.rb_control_frame_struct* %43, %struct.rb_iseq_struct* %stackFrame.i) #8
  %49 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %43, i64 0, i32 0
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 5), i64** %49, align 8, !dbg !60, !tbaa !19
  %50 = call i64 @rb_define_module(i8* noundef getelementptr inbounds ([5 x i8], [5 x i8]* @str_Test, i64 0, i64 0)) #8, !dbg !61
  %51 = call %struct.rb_control_frame_struct* @sorbet_pushStaticInitFrame(i64 %50) #8, !dbg !61
  call fastcc void @"func_Test.<static-init>L62"(%struct.rb_control_frame_struct* %51) #8, !dbg !61
  call void @sorbet_popFrame() #8, !dbg !61
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 24), i64** %49, align 8, !dbg !61, !tbaa !19
  %52 = load i64, i64* @guard_epoch_Test, align 8, !dbg !42
  %53 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !42, !tbaa !29
  %needTakeSlowPath = icmp ne i64 %52, %53, !dbg !42
  br i1 %needTakeSlowPath, label %54, label %55, !dbg !42, !prof !31

54:                                               ; preds = %entry
  call void @const_recompute_Test(), !dbg !42
  br label %55, !dbg !42

55:                                               ; preds = %entry, %54
  %56 = load i64, i64* @guarded_const_Test, align 8, !dbg !42
  %57 = load i64, i64* @guard_epoch_Test, align 8, !dbg !42
  %58 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !42, !tbaa !29
  %guardUpdated = icmp eq i64 %57, %58, !dbg !42
  call void @llvm.assume(i1 %guardUpdated), !dbg !42
  %59 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %43, i64 0, i32 1, !dbg !42
  %60 = load i64*, i64** %59, align 8, !dbg !42
  store i64 %56, i64* %60, align 8, !dbg !42, !tbaa !14
  %61 = getelementptr inbounds i64, i64* %60, i64 1, !dbg !42
  store i64* %61, i64** %59, align 8, !dbg !42
  %send = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_test_known_nil, i64 0), !dbg !42
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 25), i64** %49, align 8, !dbg !42, !tbaa !19
  %62 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %43, i64 0, i32 1, !dbg !44
  %63 = load i64*, i64** %62, align 8, !dbg !44
  store i64 %56, i64* %63, align 8, !dbg !44, !tbaa !14
  %64 = getelementptr inbounds i64, i64* %63, i64 1, !dbg !44
  store i64 21, i64* %64, align 8, !dbg !44, !tbaa !14
  %65 = getelementptr inbounds i64, i64* %64, i64 1, !dbg !44
  store i64* %65, i64** %62, align 8, !dbg !44
  %send2 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_test_nilable_arg, i64 0), !dbg !44
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 26), i64** %49, align 8, !dbg !44, !tbaa !19
  %66 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %43, i64 0, i32 1, !dbg !45
  %67 = load i64*, i64** %66, align 8, !dbg !45
  store i64 %56, i64* %67, align 8, !dbg !45, !tbaa !14
  %68 = getelementptr inbounds i64, i64* %67, i64 1, !dbg !45
  store i64 0, i64* %68, align 8, !dbg !45, !tbaa !14
  %69 = getelementptr inbounds i64, i64* %68, i64 1, !dbg !45
  store i64* %69, i64** %66, align 8, !dbg !45
  %send4 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_test_nilable_arg.1, i64 0), !dbg !45
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 27), i64** %49, align 8, !dbg !45, !tbaa !19
  %70 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %43, i64 0, i32 1, !dbg !46
  %71 = load i64*, i64** %70, align 8, !dbg !46
  store i64 %56, i64* %71, align 8, !dbg !46, !tbaa !14
  %72 = getelementptr inbounds i64, i64* %71, i64 1, !dbg !46
  store i64 8, i64* %72, align 8, !dbg !46, !tbaa !14
  %73 = getelementptr inbounds i64, i64* %72, i64 1, !dbg !46
  store i64* %73, i64** %70, align 8, !dbg !46
  %send6 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_test_nilable_arg.2, i64 0), !dbg !46
  ret void
}

; Function Attrs: nounwind sspreq uwtable
define i64 @func_Test.test_known_nil(i32 %argc, i64* nocapture nofree readnone %argArray, i64 %selfRaw, %struct.rb_control_frame_struct* nonnull align 8 dereferenceable(8) %cfp) #10 !dbg !49 {
functionEntryInitializers:
  %0 = alloca i64, align 8
  %1 = alloca %struct.ExceptionClosure, align 8
  %2 = alloca i64, align 8
  %3 = alloca %struct.ExceptionClosure, align 8
  %4 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %cfp, i64 0, i32 0
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 6), i64** %4, align 8, !tbaa !19
  %exceptionValue = alloca i64, align 8, !dbg !62
  %ecTag = alloca %struct.rb_vm_tag, align 8, !dbg !62
  %tooManyArgs = icmp ugt i32 %argc, 0, !dbg !63
  br i1 %tooManyArgs, label %argCountFailBlock, label %fillRequiredArgs, !dbg !63, !prof !64

argCountFailBlock:                                ; preds = %functionEntryInitializers
  tail call void @sorbet_raiseArity(i32 %argc, i32 noundef 0, i32 noundef 0) #18, !dbg !63
  unreachable, !dbg !63

fillRequiredArgs:                                 ; preds = %functionEntryInitializers
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 8), i64** %4, align 8, !dbg !65, !tbaa !19
  %previousException = tail call i64 @rb_errinfo(), !dbg !62
  %5 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !62, !tbaa !19
  %6 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %ecTag, i64 0, i32 4, !dbg !62
  store i32 0, i32* %6, align 8, !dbg !62, !tbaa !66
  %7 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %ecTag, i64 0, i32 0, !dbg !62
  store i64 52, i64* %7, align 8, !dbg !62, !tbaa !68
  %8 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %5, i64 0, i32 3, !dbg !62
  %9 = load %struct.rb_vm_tag*, %struct.rb_vm_tag** %8, align 8, !dbg !62, !tbaa !69
  %10 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %ecTag, i64 0, i32 3, !dbg !62
  store %struct.rb_vm_tag* %9, %struct.rb_vm_tag** %10, align 8, !dbg !62, !tbaa !70
  %11 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %ecTag, i64 0, i32 2, i64 0, !dbg !62
  %12 = tail call i8* @llvm.frameaddress.p0i8(i32 noundef 0) #8, !dbg !62
  store i8* %12, i8** %11, align 8, !dbg !62
  %13 = tail call i8* @llvm.stacksave() #8, !dbg !62
  %14 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %ecTag, i64 0, i32 2, i64 2, !dbg !62
  store i8* %13, i8** %14, align 8, !dbg !62
  %15 = bitcast i8** %11 to i8*, !dbg !62
  %16 = call i32 @llvm.eh.sjlj.setjmp(i8* nonnull align 8 %15) #8, !dbg !62
  %17 = icmp eq i32 %16, 0, !dbg !62
  br i1 %17, label %sorbet_initializeTag.exit.thread, label %sorbet_initializeTag.exit, !dbg !62

sorbet_initializeTag.exit.thread:                 ; preds = %fillRequiredArgs
  store %struct.rb_vm_tag* %ecTag, %struct.rb_vm_tag** %8, align 8, !dbg !62, !tbaa !69
  br label %exception-entry.preheader, !dbg !62

sorbet_initializeTag.exit:                        ; preds = %fillRequiredArgs
  %18 = load %struct.rb_vm_tag*, %struct.rb_vm_tag** %8, align 8, !dbg !62, !tbaa !69
  %19 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %18, i64 0, i32 4, !dbg !62
  %20 = load i32, i32* %19, align 8, !dbg !62, !tbaa !66
  store i32 0, i32* %19, align 8, !dbg !62, !tbaa !66
  %21 = icmp ne i32 %20, 0, !dbg !62
  br i1 %21, label %exception-ensure, label %exception-entry.preheader, !dbg !62

exception-entry.preheader:                        ; preds = %sorbet_initializeTag.exit.thread, %sorbet_initializeTag.exit
  %22 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %cfp, i64 0, i32 4
  %23 = bitcast i64* %0 to i8*
  %24 = bitcast %struct.ExceptionClosure* %1 to i8*
  %25 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %1, i64 0, i32 0
  %26 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %1, i64 0, i32 1
  %27 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %1, i64 0, i32 2
  %28 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %1, i64 0, i32 3
  %29 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %1, i64 0, i32 4
  %30 = icmp eq i64 %previousException, 8
  %31 = ptrtoint %struct.ExceptionClosure* %1 to i64
  %32 = ptrtoint i64* %exceptionValue to i64
  %33 = bitcast i64* %2 to i8*
  %34 = bitcast %struct.ExceptionClosure* %3 to i8*
  %35 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %3, i64 0, i32 0
  %36 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %3, i64 0, i32 1
  %37 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %3, i64 0, i32 2
  %38 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %3, i64 0, i32 3
  %39 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %3, i64 0, i32 4
  %40 = ptrtoint %struct.ExceptionClosure* %3 to i64
  br i1 %30, label %exception-entry.us, label %exception-entry, !dbg !62

exception-entry.us:                               ; preds = %exception-entry.preheader, %sorbet_try.exit.us
  %41 = load i64*, i64** %22, align 8, !dbg !62, !tbaa !26
  %42 = load i64, i64* %41, align 8, !dbg !62, !tbaa !14
  %43 = and i64 %42, 8, !dbg !62
  %44 = icmp eq i64 %43, 0, !dbg !62
  br i1 %44, label %46, label %45, !dbg !62, !prof !34

45:                                               ; preds = %exception-entry.us
  call void @sorbet_vm_env_write_slowpath(i64* nonnull align 8 dereferenceable(8) %41, i32 noundef -3, i64 noundef 8) #8, !dbg !62
  br label %sorbet_writeLocal.exit.us, !dbg !62

46:                                               ; preds = %exception-entry.us
  %47 = getelementptr inbounds i64, i64* %41, i64 -3, !dbg !62
  store i64 8, i64* %47, align 8, !dbg !62, !tbaa !14
  br label %sorbet_writeLocal.exit.us, !dbg !62

sorbet_writeLocal.exit.us:                        ; preds = %46, %45
  call void @llvm.lifetime.start.p0i8(i64 noundef 8, i8* noundef nonnull align 8 %23) #19, !dbg !62
  store i64 52, i64* %0, align 8, !dbg !62, !tbaa !14
  call void @llvm.lifetime.start.p0i8(i64 noundef 40, i8* noundef nonnull align 8 %24) #19, !dbg !62
  store i64 (i64**, i64, %struct.rb_control_frame_struct*)* @"func_Test.test_known_nil$block_1", i64 (i64**, i64, %struct.rb_control_frame_struct*)** %25, align 8, !dbg !62, !tbaa !4
  store i64** %4, i64*** %26, align 8, !dbg !62, !tbaa !10
  store i64 0, i64* %27, align 8, !dbg !62, !tbaa !11
  store %struct.rb_control_frame_struct* %cfp, %struct.rb_control_frame_struct** %28, align 8, !dbg !62, !tbaa !12
  store i64* %0, i64** %29, align 8, !dbg !62, !tbaa !13
  store i64 8, i64* %exceptionValue, align 8, !dbg !62, !tbaa !14
  %48 = load i64, i64* @rb_eException, align 8, !dbg !62, !tbaa !14
  %49 = call i64 (i64 (i64)*, i64, i64 (i64, i64)*, i64, ...) @rb_rescue2(i64 (i64)* noundef nonnull @sorbet_applyExceptionClosure, i64 noundef %31, i64 (i64, i64)* noundef nonnull @sorbet_rescueStoreException, i64 %32, i64 %48, i32 0) #8, !dbg !62
  %50 = load i64, i64* %0, align 8, !dbg !62
  call void @llvm.lifetime.end.p0i8(i64 noundef 40, i8* noundef nonnull %24) #8, !dbg !62
  call void @llvm.lifetime.end.p0i8(i64 noundef 8, i8* noundef nonnull %23) #8, !dbg !62
  %isReturnValue.us = icmp ne i64 %50, 52, !dbg !62
  br i1 %isReturnValue.us, label %exception-body-return, label %exception-body-handlers.us, !dbg !62

exception-body-handlers.us:                       ; preds = %sorbet_writeLocal.exit.us
  %51 = load i64, i64* %exceptionValue, align 8, !dbg !62
  %52 = load i64*, i64** %22, align 8, !dbg !62, !tbaa !26
  %53 = load i64, i64* %52, align 8, !dbg !62, !tbaa !14
  %54 = and i64 %53, 8, !dbg !62
  %55 = icmp eq i64 %54, 0, !dbg !62
  br i1 %55, label %57, label %56, !dbg !62, !prof !34

56:                                               ; preds = %exception-body-handlers.us
  call void @sorbet_vm_env_write_slowpath(i64* nonnull align 8 dereferenceable(8) %52, i32 noundef -3, i64 %51) #8, !dbg !62
  br label %sorbet_writeLocal.exit19.us, !dbg !62

57:                                               ; preds = %exception-body-handlers.us
  %58 = getelementptr inbounds i64, i64* %52, i64 -3, !dbg !62
  store i64 %51, i64* %58, align 8, !dbg !62, !tbaa !14
  br label %sorbet_writeLocal.exit19.us, !dbg !62

sorbet_writeLocal.exit19.us:                      ; preds = %57, %56
  %59 = icmp ne i64 %51, 8, !dbg !62
  %handler.us = select i1 %59, i64 (i64**, i64, %struct.rb_control_frame_struct*)* @"func_Test.test_known_nil$block_2", i64 (i64**, i64, %struct.rb_control_frame_struct*)* @"func_Test.test_known_nil$block_4", !dbg !62
  call void @llvm.lifetime.start.p0i8(i64 noundef 8, i8* noundef nonnull align 8 %33) #19, !dbg !62
  store i64 52, i64* %2, align 8, !dbg !62, !tbaa !14
  call void @llvm.lifetime.start.p0i8(i64 noundef 40, i8* noundef nonnull align 8 %34) #19, !dbg !62
  store i64 (i64**, i64, %struct.rb_control_frame_struct*)* %handler.us, i64 (i64**, i64, %struct.rb_control_frame_struct*)** %35, align 8, !dbg !62, !tbaa !4
  store i64** %4, i64*** %36, align 8, !dbg !62, !tbaa !10
  store i64 0, i64* %37, align 8, !dbg !62, !tbaa !11
  store %struct.rb_control_frame_struct* %cfp, %struct.rb_control_frame_struct** %38, align 8, !dbg !62, !tbaa !12
  store i64* %2, i64** %39, align 8, !dbg !62, !tbaa !13
  store i64 8, i64* %exceptionValue, align 8, !dbg !62, !tbaa !14
  %60 = icmp eq i64 %51, 8, !dbg !62
  br i1 %60, label %sorbet_try.exit.us, label %61, !dbg !62

61:                                               ; preds = %sorbet_writeLocal.exit19.us
  call void @rb_set_errinfo(i64 %51) #8, !dbg !62
  br label %sorbet_try.exit.us, !dbg !62

sorbet_try.exit.us:                               ; preds = %61, %sorbet_writeLocal.exit19.us
  %62 = load i64, i64* @rb_eException, align 8, !dbg !62, !tbaa !14
  %63 = call i64 (i64 (i64)*, i64, i64 (i64, i64)*, i64, ...) @rb_rescue2(i64 (i64)* noundef nonnull @sorbet_applyExceptionClosure, i64 noundef %40, i64 (i64, i64)* noundef nonnull @sorbet_rescueStoreException, i64 %32, i64 %62, i32 0) #8, !dbg !62
  %64 = load i64, i64* %2, align 8, !dbg !62
  call void @llvm.lifetime.end.p0i8(i64 noundef 40, i8* noundef nonnull %34) #8, !dbg !62
  call void @llvm.lifetime.end.p0i8(i64 noundef 8, i8* noundef nonnull %33) #8, !dbg !62
  %65 = load i64, i64* %exceptionValue, align 8, !dbg !62
  %66 = icmp ne i64 %65, 8, !dbg !62
  %67 = load i64*, i64** %22, align 8, !dbg !62, !tbaa !26
  %68 = getelementptr inbounds i64, i64* %67, i64 -3, !dbg !62
  %69 = load i64, i64* %68, align 8, !dbg !62, !tbaa !14
  %70 = icmp ne i64 %69, 8, !dbg !62
  %71 = select i1 %70, i64 %69, i64 8, !dbg !62
  %72 = select i1 %66, i64 %65, i64 %71, !dbg !62
  call void @rb_set_errinfo(i64 %72), !dbg !62
  %"<retry-singleton>.us" = load i64, i64* @"<retry-singleton>", align 8, !dbg !62
  %shouldRetry.us = icmp eq i64 %64, %"<retry-singleton>.us", !dbg !62
  %73 = and i1 %59, %shouldRetry.us, !dbg !62
  br i1 %73, label %exception-entry.us, label %exception-ensure, !dbg !62

exception-entry:                                  ; preds = %exception-entry.preheader, %sorbet_try.exit
  %74 = load i64*, i64** %22, align 8, !dbg !62, !tbaa !26
  %75 = load i64, i64* %74, align 8, !dbg !62, !tbaa !14
  %76 = and i64 %75, 8, !dbg !62
  %77 = icmp eq i64 %76, 0, !dbg !62
  br i1 %77, label %78, label %80, !dbg !62, !prof !34

78:                                               ; preds = %exception-entry
  %79 = getelementptr inbounds i64, i64* %74, i64 -3, !dbg !62
  store i64 8, i64* %79, align 8, !dbg !62, !tbaa !14
  br label %sorbet_writeLocal.exit, !dbg !62

80:                                               ; preds = %exception-entry
  call void @sorbet_vm_env_write_slowpath(i64* nonnull align 8 dereferenceable(8) %74, i32 noundef -3, i64 noundef 8) #8, !dbg !62
  br label %sorbet_writeLocal.exit, !dbg !62

sorbet_writeLocal.exit:                           ; preds = %78, %80
  call void @llvm.lifetime.start.p0i8(i64 noundef 8, i8* noundef nonnull align 8 %23) #19, !dbg !62
  store i64 52, i64* %0, align 8, !dbg !62, !tbaa !14
  call void @llvm.lifetime.start.p0i8(i64 noundef 40, i8* noundef nonnull align 8 %24) #19, !dbg !62
  store i64 (i64**, i64, %struct.rb_control_frame_struct*)* @"func_Test.test_known_nil$block_1", i64 (i64**, i64, %struct.rb_control_frame_struct*)** %25, align 8, !dbg !62, !tbaa !4
  store i64** %4, i64*** %26, align 8, !dbg !62, !tbaa !10
  store i64 0, i64* %27, align 8, !dbg !62, !tbaa !11
  store %struct.rb_control_frame_struct* %cfp, %struct.rb_control_frame_struct** %28, align 8, !dbg !62, !tbaa !12
  store i64* %0, i64** %29, align 8, !dbg !62, !tbaa !13
  store i64 8, i64* %exceptionValue, align 8, !dbg !62, !tbaa !14
  call void @rb_set_errinfo(i64 %previousException) #8, !dbg !62
  %81 = load i64, i64* @rb_eException, align 8, !dbg !62, !tbaa !14
  %82 = call i64 (i64 (i64)*, i64, i64 (i64, i64)*, i64, ...) @rb_rescue2(i64 (i64)* noundef nonnull @sorbet_applyExceptionClosure, i64 noundef %31, i64 (i64, i64)* noundef nonnull @sorbet_rescueStoreException, i64 %32, i64 %81, i32 0) #8, !dbg !62
  %83 = load i64, i64* %0, align 8, !dbg !62
  call void @llvm.lifetime.end.p0i8(i64 noundef 40, i8* noundef nonnull %24) #8, !dbg !62
  call void @llvm.lifetime.end.p0i8(i64 noundef 8, i8* noundef nonnull %23) #8, !dbg !62
  %isReturnValue = icmp ne i64 %83, 52, !dbg !62
  br i1 %isReturnValue, label %exception-body-return, label %exception-body-handlers, !dbg !62

exception-body-return:                            ; preds = %sorbet_writeLocal.exit, %sorbet_writeLocal.exit.us
  %.lcssa = phi i64 [ %50, %sorbet_writeLocal.exit.us ], [ %83, %sorbet_writeLocal.exit ], !dbg !62
  call void @rb_set_errinfo(i64 %previousException), !dbg !62
  br label %exception-ensure, !dbg !62

exception-body-handlers:                          ; preds = %sorbet_writeLocal.exit
  %84 = load i64, i64* %exceptionValue, align 8, !dbg !62
  %85 = load i64*, i64** %22, align 8, !dbg !62, !tbaa !26
  %86 = load i64, i64* %85, align 8, !dbg !62, !tbaa !14
  %87 = and i64 %86, 8, !dbg !62
  %88 = icmp eq i64 %87, 0, !dbg !62
  br i1 %88, label %89, label %91, !dbg !62, !prof !34

89:                                               ; preds = %exception-body-handlers
  %90 = getelementptr inbounds i64, i64* %85, i64 -3, !dbg !62
  store i64 %84, i64* %90, align 8, !dbg !62, !tbaa !14
  br label %sorbet_writeLocal.exit19, !dbg !62

91:                                               ; preds = %exception-body-handlers
  call void @sorbet_vm_env_write_slowpath(i64* nonnull align 8 dereferenceable(8) %85, i32 noundef -3, i64 %84) #8, !dbg !62
  br label %sorbet_writeLocal.exit19, !dbg !62

sorbet_writeLocal.exit19:                         ; preds = %89, %91
  %92 = icmp ne i64 %84, 8, !dbg !62
  %handler = select i1 %92, i64 (i64**, i64, %struct.rb_control_frame_struct*)* @"func_Test.test_known_nil$block_2", i64 (i64**, i64, %struct.rb_control_frame_struct*)* @"func_Test.test_known_nil$block_4", !dbg !62
  call void @llvm.lifetime.start.p0i8(i64 noundef 8, i8* noundef nonnull align 8 %33) #19, !dbg !62
  store i64 52, i64* %2, align 8, !dbg !62, !tbaa !14
  call void @llvm.lifetime.start.p0i8(i64 noundef 40, i8* noundef nonnull align 8 %34) #19, !dbg !62
  store i64 (i64**, i64, %struct.rb_control_frame_struct*)* %handler, i64 (i64**, i64, %struct.rb_control_frame_struct*)** %35, align 8, !dbg !62, !tbaa !4
  store i64** %4, i64*** %36, align 8, !dbg !62, !tbaa !10
  store i64 0, i64* %37, align 8, !dbg !62, !tbaa !11
  store %struct.rb_control_frame_struct* %cfp, %struct.rb_control_frame_struct** %38, align 8, !dbg !62, !tbaa !12
  store i64* %2, i64** %39, align 8, !dbg !62, !tbaa !13
  store i64 8, i64* %exceptionValue, align 8, !dbg !62, !tbaa !14
  %93 = icmp eq i64 %84, 8, !dbg !62
  br i1 %93, label %sorbet_try.exit, label %94, !dbg !62

94:                                               ; preds = %sorbet_writeLocal.exit19
  call void @rb_set_errinfo(i64 %84) #8, !dbg !62
  br label %sorbet_try.exit, !dbg !62

sorbet_try.exit:                                  ; preds = %sorbet_writeLocal.exit19, %94
  %95 = load i64, i64* @rb_eException, align 8, !dbg !62, !tbaa !14
  %96 = call i64 (i64 (i64)*, i64, i64 (i64, i64)*, i64, ...) @rb_rescue2(i64 (i64)* noundef nonnull @sorbet_applyExceptionClosure, i64 noundef %40, i64 (i64, i64)* noundef nonnull @sorbet_rescueStoreException, i64 %32, i64 %95, i32 0) #8, !dbg !62
  %97 = load i64, i64* %2, align 8, !dbg !62
  call void @llvm.lifetime.end.p0i8(i64 noundef 40, i8* noundef nonnull %34) #8, !dbg !62
  call void @llvm.lifetime.end.p0i8(i64 noundef 8, i8* noundef nonnull %33) #8, !dbg !62
  %98 = load i64, i64* %exceptionValue, align 8, !dbg !62
  %99 = icmp ne i64 %98, 8, !dbg !62
  %100 = load i64*, i64** %22, align 8, !dbg !62, !tbaa !26
  %101 = getelementptr inbounds i64, i64* %100, i64 -3, !dbg !62
  %102 = load i64, i64* %101, align 8, !dbg !62, !tbaa !14
  %103 = icmp ne i64 %102, 8, !dbg !62
  %104 = select i1 %103, i64 %102, i64 %previousException, !dbg !62
  %105 = select i1 %99, i64 %98, i64 %104, !dbg !62
  call void @rb_set_errinfo(i64 %105), !dbg !62
  %"<retry-singleton>" = load i64, i64* @"<retry-singleton>", align 8, !dbg !62
  %shouldRetry = icmp eq i64 %97, %"<retry-singleton>", !dbg !62
  %106 = and i1 %92, %shouldRetry, !dbg !62
  br i1 %106, label %exception-entry, label %exception-ensure, !dbg !62

exception-ensure:                                 ; preds = %sorbet_try.exit, %sorbet_try.exit.us, %exception-body-return, %sorbet_initializeTag.exit
  %107 = phi i32 [ 0, %exception-body-return ], [ %20, %sorbet_initializeTag.exit ], [ 0, %sorbet_try.exit.us ], [ 0, %sorbet_try.exit ]
  %108 = phi i64 [ %.lcssa, %exception-body-return ], [ 52, %sorbet_initializeTag.exit ], [ %64, %sorbet_try.exit.us ], [ %97, %sorbet_try.exit ], !dbg !62
  %109 = phi i64 [ 8, %exception-body-return ], [ %previousException, %sorbet_initializeTag.exit ], [ %72, %sorbet_try.exit.us ], [ %105, %sorbet_try.exit ], !dbg !62
  %110 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !62, !tbaa !19
  %111 = load %struct.rb_vm_tag*, %struct.rb_vm_tag** %10, align 8, !dbg !62, !tbaa !70
  %112 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %110, i64 0, i32 3, !dbg !62
  store %struct.rb_vm_tag* %111, %struct.rb_vm_tag** %112, align 8, !dbg !62, !tbaa !69
  %stackFrame.i = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Test.test_known_nil$block_3", align 8
  %113 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %110, i64 0, i32 2
  %114 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %113, align 8, !tbaa !20
  call void @sorbet_setExceptionStackFrame(%struct.rb_execution_context_struct* %110, %struct.rb_control_frame_struct* %114, %struct.rb_iseq_struct* %stackFrame.i) #8
  %115 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !19
  %116 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %115, i64 0, i32 2
  %117 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %116, align 8, !tbaa !20
  %118 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %117, i64 0, i32 0
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 6), i64** %118, align 8, !tbaa !19
  call void @sorbet_popFrame()
  %119 = icmp eq i32 %107, 0, !dbg !62
  br i1 %119, label %sorbet_maybeContinueUnwind.exit, label %120, !dbg !62

120:                                              ; preds = %exception-ensure
  %121 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !62, !tbaa !19
  %122 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %121, i64 0, i32 3, !dbg !62
  %123 = load %struct.rb_vm_tag*, %struct.rb_vm_tag** %122, align 8, !dbg !62, !tbaa !69
  %124 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %123, i64 0, i32 4, !dbg !62
  store i32 %107, i32* %124, align 8, !dbg !62, !tbaa !66
  %125 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %123, i64 0, i32 2, i64 0, !dbg !62
  %126 = bitcast i8** %125 to i8*, !dbg !62
  call void @llvm.eh.sjlj.longjmp(i8* nonnull %126) #9, !dbg !62
  unreachable, !dbg !62

sorbet_maybeContinueUnwind.exit:                  ; preds = %exception-ensure
  %isReturnValue11 = icmp ne i64 %108, 52, !dbg !62
  br i1 %isReturnValue11, label %normalReturn, label %exception-continue, !dbg !62

exception-continue:                               ; preds = %sorbet_maybeContinueUnwind.exit
  %127 = icmp eq i64 %109, 8, !dbg !62
  br i1 %127, label %sorbet_raiseIfNotNil.exit18, label %128, !dbg !62

128:                                              ; preds = %exception-continue
  call void @rb_exc_raise(i64 %109) #9, !dbg !62
  unreachable, !dbg !62

sorbet_raiseIfNotNil.exit18:                      ; preds = %exception-continue
  %129 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %cfp, i64 0, i32 4, !dbg !62
  %130 = load i64*, i64** %129, align 8, !dbg !62, !tbaa !26
  %131 = getelementptr inbounds i64, i64* %130, i64 -3, !dbg !62
  %132 = load i64, i64* %131, align 8, !dbg !62, !tbaa !14
  %133 = icmp eq i64 %132, 8, !dbg !62
  br i1 %133, label %sorbet_raiseIfNotNil.exit, label %134, !dbg !62

134:                                              ; preds = %sorbet_raiseIfNotNil.exit18
  call void @rb_exc_raise(i64 %132) #9, !dbg !62
  unreachable, !dbg !62

sorbet_raiseIfNotNil.exit:                        ; preds = %sorbet_raiseIfNotNil.exit18
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 12), i64** %4, align 8, !tbaa !19
  %135 = getelementptr inbounds i64, i64* %130, i64 -5, !dbg !71
  %136 = load i64, i64* %135, align 8, !dbg !71, !tbaa !14
  br label %normalReturn, !dbg !71

normalReturn:                                     ; preds = %sorbet_maybeContinueUnwind.exit, %sorbet_raiseIfNotNil.exit
  %"<returnValue>.sroa.0.0" = phi i64 [ %136, %sorbet_raiseIfNotNil.exit ], [ %108, %sorbet_maybeContinueUnwind.exit ], !dbg !65
  ret i64 %"<returnValue>.sroa.0.0"
}

; Function Attrs: nounwind ssp
define internal noundef i64 @"func_Test.test_known_nil$block_1"(i64** nocapture nonnull writeonly align 8 dereferenceable(8) %pc, i64 %localsOffset, %struct.rb_control_frame_struct* %cfp) #12 !dbg !48 {
fastSymCallIntrinsic_T_must:
  %callArgs = alloca [2 x i64], align 8
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 8), i64** %pc, align 8, !tbaa !19
  %callArgs0Addr = getelementptr [2 x i64], [2 x i64]* %callArgs, i32 0, i64 0, !dbg !47
  store i64 8, i64* %callArgs0Addr, align 8, !dbg !47
  %0 = getelementptr [2 x i64], [2 x i64]* %callArgs, i64 0, i64 0, !dbg !47
  tail call void @llvm.experimental.noalias.scope.decl(metadata !72), !dbg !47
  %1 = load i64, i64* %0, align 8, !dbg !47, !tbaa !14, !alias.scope !72
  %2 = icmp eq i64 %1, 8, !dbg !47
  br i1 %2, label %11, label %sorbet_T_must.exit, !dbg !47, !prof !64

afterSend:                                        ; preds = %21, %sorbet_T_must.exit
  %3 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %cfp, i64 0, i32 4, !dbg !47
  %4 = load i64*, i64** %3, align 8, !dbg !47, !tbaa !26
  %5 = load i64, i64* %4, align 8, !dbg !47, !tbaa !14
  %6 = and i64 %5, 8, !dbg !47
  %7 = icmp eq i64 %6, 0, !dbg !47
  br i1 %7, label %8, label %10, !dbg !47, !prof !34

8:                                                ; preds = %afterSend
  %9 = getelementptr inbounds i64, i64* %4, i64 -5, !dbg !47
  store i64 %1, i64* %9, align 8, !dbg !47, !tbaa !14
  br label %normalReturn, !dbg !47

10:                                               ; preds = %afterSend
  tail call void @sorbet_vm_env_write_slowpath(i64* nonnull align 8 dereferenceable(8) %4, i32 noundef -5, i64 %1) #8, !dbg !47
  br label %normalReturn, !dbg !47

11:                                               ; preds = %fastSymCallIntrinsic_T_must
  %12 = load i64, i64* @rb_eTypeError, align 8, !dbg !47, !tbaa !14, !noalias !72
  tail call void (i64, i8*, ...) @rb_raise(i64 %12, i8* noundef getelementptr inbounds ([25 x i8], [25 x i8]* @.str.1, i64 0, i64 0)) #9, !dbg !47, !noalias !72
  unreachable, !dbg !47

sorbet_T_must.exit:                               ; preds = %fastSymCallIntrinsic_T_must
  %13 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !47, !tbaa !19
  %14 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %13, i64 0, i32 5, !dbg !47
  %15 = load i32, i32* %14, align 8, !dbg !47, !tbaa !32
  %16 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %13, i64 0, i32 6, !dbg !47
  %17 = load i32, i32* %16, align 4, !dbg !47, !tbaa !33
  %18 = xor i32 %17, -1, !dbg !47
  %19 = and i32 %18, %15, !dbg !47
  %20 = icmp eq i32 %19, 0, !dbg !47
  br i1 %20, label %afterSend, label %21, !dbg !47, !prof !34

21:                                               ; preds = %sorbet_T_must.exit
  %22 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %13, i64 0, i32 8, !dbg !47
  %23 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %22, align 8, !dbg !47, !tbaa !35
  %24 = tail call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* %23, i32 noundef 0) #8, !dbg !47
  br label %afterSend, !dbg !47

normalReturn:                                     ; preds = %10, %8
  ret i64 52
}

; Function Attrs: ssp
define internal noundef i64 @"func_Test.test_known_nil$block_2"(i64** nocapture nofree readnone %pc, i64 %localsOffset, %struct.rb_control_frame_struct* nocapture nofree readnone %cfp) #13 !dbg !51 {
vm_get_ep.exit34:
  %0 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !19
  %1 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %0, i64 0, i32 2
  %2 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %1, align 8, !tbaa !20
  %3 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 3
  %4 = load i64, i64* %3, align 8, !tbaa !75
  %stackFrame = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Test.test_known_nil$block_2", align 8
  tail call void @sorbet_setExceptionStackFrame(%struct.rb_execution_context_struct* %0, %struct.rb_control_frame_struct* %2, %struct.rb_iseq_struct* %stackFrame) #8
  %5 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !19
  %6 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %5, i64 0, i32 2
  %7 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %6, align 8, !tbaa !20
  %8 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %7, i64 0, i32 0
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 9), i64** %8, align 8, !tbaa !19
  %9 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !50, !tbaa !19
  %10 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %9, i64 0, i32 2, !dbg !50
  %11 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %10, align 8, !dbg !50, !tbaa !20
  %12 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %11, i64 0, i32 4, !dbg !50
  %13 = load i64*, i64** %12, align 8, !dbg !50
  %14 = getelementptr inbounds i64, i64* %13, i64 -1, !dbg !50
  %15 = load i64, i64* %14, align 8, !dbg !50, !tbaa !14
  %16 = and i64 %15, -4, !dbg !50
  %17 = inttoptr i64 %16 to i64*, !dbg !50
  %18 = getelementptr inbounds i64, i64* %17, i64 -3, !dbg !50
  %19 = load i64, i64* %18, align 8, !dbg !50, !tbaa !14
  %20 = load i64, i64* @rb_eStandardError, align 8, !dbg !50
  %21 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %11, i64 0, i32 1, !dbg !50
  %22 = load i64*, i64** %21, align 8, !dbg !50
  store i64 %19, i64* %22, align 8, !dbg !50, !tbaa !14
  %23 = getelementptr inbounds i64, i64* %22, i64 1, !dbg !50
  store i64 %20, i64* %23, align 8, !dbg !50, !tbaa !14
  %24 = getelementptr inbounds i64, i64* %23, i64 1, !dbg !50
  store i64* %24, i64** %21, align 8, !dbg !50
  %send = tail call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @"ic_is_a?", i64 0), !dbg !50
  %25 = and i64 %send, -9, !dbg !50
  %26 = icmp ne i64 %25, 0, !dbg !50
  br i1 %26, label %vm_get_ep.exit32, label %vm_get_ep.exit, !dbg !50

blockExit:                                        ; preds = %78, %76, %63, %61
  tail call void @sorbet_popFrame()
  ret i64 52

vm_get_ep.exit32:                                 ; preds = %vm_get_ep.exit34
  %27 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !76, !tbaa !19
  %28 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %27, i64 0, i32 2, !dbg !76
  %29 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %28, align 8, !dbg !76, !tbaa !20
  %30 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %29, i64 0, i32 4, !dbg !76
  %31 = load i64*, i64** %30, align 8, !dbg !76
  %32 = getelementptr inbounds i64, i64* %31, i64 -1, !dbg !76
  %33 = load i64, i64* %32, align 8, !dbg !76, !tbaa !14
  %34 = and i64 %33, -4, !dbg !76
  %35 = inttoptr i64 %34 to i64*, !dbg !76
  %36 = load i64, i64* %35, align 8, !dbg !76, !tbaa !14
  %37 = and i64 %36, 8, !dbg !76
  %38 = icmp eq i64 %37, 0, !dbg !76
  br i1 %38, label %39, label %41, !dbg !76, !prof !34

39:                                               ; preds = %vm_get_ep.exit32
  %40 = getelementptr inbounds i64, i64* %35, i64 -3, !dbg !76
  store i64 8, i64* %40, align 8, !dbg !76, !tbaa !14
  br label %vm_get_ep.exit30, !dbg !76

41:                                               ; preds = %vm_get_ep.exit32
  tail call void @sorbet_vm_env_write_slowpath(i64* nonnull align 8 dereferenceable(8) %35, i32 noundef -3, i64 noundef 8) #8, !dbg !76
  br label %vm_get_ep.exit30, !dbg !76

vm_get_ep.exit30:                                 ; preds = %39, %41
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 10), i64** %8, align 8, !dbg !77, !tbaa !19
  %42 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !52, !tbaa !19
  %43 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %42, i64 0, i32 2, !dbg !52
  %44 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %43, align 8, !dbg !52, !tbaa !20
  %45 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %44, i64 0, i32 1, !dbg !52
  %46 = load i64*, i64** %45, align 8, !dbg !52
  store i64 %4, i64* %46, align 8, !dbg !52, !tbaa !14
  %47 = getelementptr inbounds i64, i64* %46, i64 1, !dbg !52
  store i64 %19, i64* %47, align 8, !dbg !52, !tbaa !14
  %48 = getelementptr inbounds i64, i64* %47, i64 1, !dbg !52
  store i64* %48, i64** %45, align 8, !dbg !52
  %send42 = tail call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_puts, i64 0), !dbg !52
  %49 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !52, !tbaa !19
  %50 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %49, i64 0, i32 2, !dbg !52
  %51 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %50, align 8, !dbg !52, !tbaa !20
  %52 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %51, i64 0, i32 4, !dbg !52
  %53 = load i64*, i64** %52, align 8, !dbg !52
  %54 = getelementptr inbounds i64, i64* %53, i64 -1, !dbg !52
  %55 = load i64, i64* %54, align 8, !dbg !52, !tbaa !14
  %56 = and i64 %55, -4, !dbg !52
  %57 = inttoptr i64 %56 to i64*, !dbg !52
  %58 = load i64, i64* %57, align 8, !dbg !52, !tbaa !14
  %59 = and i64 %58, 8, !dbg !52
  %60 = icmp eq i64 %59, 0, !dbg !52
  br i1 %60, label %61, label %63, !dbg !52, !prof !34

61:                                               ; preds = %vm_get_ep.exit30
  %62 = getelementptr inbounds i64, i64* %57, i64 -5, !dbg !52
  store i64 %send42, i64* %62, align 8, !dbg !52, !tbaa !14
  br label %blockExit, !dbg !52

63:                                               ; preds = %vm_get_ep.exit30
  tail call void @sorbet_vm_env_write_slowpath(i64* nonnull align 8 dereferenceable(8) %57, i32 noundef -5, i64 %send42) #8, !dbg !52
  br label %blockExit, !dbg !52

vm_get_ep.exit:                                   ; preds = %vm_get_ep.exit34
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 8), i64** %8, align 8, !tbaa !19
  %64 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !78, !tbaa !19
  %65 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %64, i64 0, i32 2, !dbg !78
  %66 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %65, align 8, !dbg !78, !tbaa !20
  %67 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %66, i64 0, i32 4, !dbg !78
  %68 = load i64*, i64** %67, align 8, !dbg !78
  %69 = getelementptr inbounds i64, i64* %68, i64 -1, !dbg !78
  %70 = load i64, i64* %69, align 8, !dbg !78, !tbaa !14
  %71 = and i64 %70, -4, !dbg !78
  %72 = inttoptr i64 %71 to i64*, !dbg !78
  %73 = load i64, i64* %72, align 8, !dbg !78, !tbaa !14
  %74 = and i64 %73, 8, !dbg !78
  %75 = icmp eq i64 %74, 0, !dbg !78
  br i1 %75, label %76, label %78, !dbg !78, !prof !34

76:                                               ; preds = %vm_get_ep.exit
  %77 = getelementptr inbounds i64, i64* %72, i64 -6, !dbg !78
  store i64 20, i64* %77, align 8, !dbg !78, !tbaa !14
  br label %blockExit, !dbg !78

78:                                               ; preds = %vm_get_ep.exit
  tail call void @sorbet_vm_env_write_slowpath(i64* nonnull align 8 dereferenceable(8) %72, i32 noundef -6, i64 noundef 20) #8, !dbg !78
  br label %blockExit, !dbg !78
}

; Function Attrs: argmemonly nofree norecurse nosync nounwind ssp willreturn writeonly
define internal noundef i64 @"func_Test.test_known_nil$block_4"(i64** nocapture nofree nonnull writeonly align 8 dereferenceable(8) %pc, i64 %localsOffset, %struct.rb_control_frame_struct* nocapture nofree readnone %cfp) #14 !dbg !79 {
functionEntryInitializers:
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 6), i64** %pc, align 8, !tbaa !19
  ret i64 52
}

; Function Attrs: nounwind sspreq uwtable
define i64 @func_Test.test_nilable_arg(i32 %argc, i64* nocapture readonly %argArray, i64 %selfRaw, %struct.rb_control_frame_struct* nonnull align 8 dereferenceable(8) %cfp) #10 !dbg !55 {
functionEntryInitializers:
  %0 = alloca i64, align 8
  %1 = alloca %struct.ExceptionClosure, align 8
  %2 = alloca i64, align 8
  %3 = alloca %struct.ExceptionClosure, align 8
  %4 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %cfp, i64 0, i32 0
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 14), i64** %4, align 8, !tbaa !19
  %exceptionValue = alloca i64, align 8, !dbg !80
  %ecTag = alloca %struct.rb_vm_tag, align 8, !dbg !80
  %tooManyArgs = icmp ugt i32 %argc, 1, !dbg !81
  %tooFewArgs = icmp ult i32 %argc, 1, !dbg !81
  %or.cond = or i1 %tooManyArgs, %tooFewArgs, !dbg !81
  br i1 %or.cond, label %argCountFailBlock, label %fillRequiredArgs, !dbg !81, !prof !82

argCountFailBlock:                                ; preds = %functionEntryInitializers
  tail call void @sorbet_raiseArity(i32 %argc, i32 noundef 1, i32 noundef 1) #18, !dbg !81
  unreachable, !dbg !81

fillRequiredArgs:                                 ; preds = %functionEntryInitializers
  %rawArg_arg = load i64, i64* %argArray, align 8, !dbg !81
  %5 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %cfp, i64 0, i32 4, !dbg !81
  %6 = load i64*, i64** %5, align 8, !dbg !81, !tbaa !26
  %7 = load i64, i64* %6, align 8, !dbg !81, !tbaa !14
  %8 = and i64 %7, 8, !dbg !81
  %9 = icmp eq i64 %8, 0, !dbg !81
  br i1 %9, label %10, label %12, !dbg !81, !prof !34

10:                                               ; preds = %fillRequiredArgs
  %11 = getelementptr inbounds i64, i64* %6, i64 -4, !dbg !81
  store i64 %rawArg_arg, i64* %11, align 8, !dbg !81, !tbaa !14
  br label %sorbet_writeLocal.exit, !dbg !81

12:                                               ; preds = %fillRequiredArgs
  tail call void @sorbet_vm_env_write_slowpath(i64* nonnull align 8 dereferenceable(8) %6, i32 noundef -4, i64 %rawArg_arg) #8, !dbg !81
  br label %sorbet_writeLocal.exit, !dbg !81

sorbet_writeLocal.exit:                           ; preds = %10, %12
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 16), i64** %4, align 8, !dbg !83, !tbaa !19
  %previousException = tail call i64 @rb_errinfo(), !dbg !80
  %13 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !80, !tbaa !19
  %14 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %ecTag, i64 0, i32 4, !dbg !80
  store i32 0, i32* %14, align 8, !dbg !80, !tbaa !66
  %15 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %ecTag, i64 0, i32 0, !dbg !80
  store i64 52, i64* %15, align 8, !dbg !80, !tbaa !68
  %16 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %13, i64 0, i32 3, !dbg !80
  %17 = load %struct.rb_vm_tag*, %struct.rb_vm_tag** %16, align 8, !dbg !80, !tbaa !69
  %18 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %ecTag, i64 0, i32 3, !dbg !80
  store %struct.rb_vm_tag* %17, %struct.rb_vm_tag** %18, align 8, !dbg !80, !tbaa !70
  %19 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %ecTag, i64 0, i32 2, i64 0, !dbg !80
  %20 = tail call i8* @llvm.frameaddress.p0i8(i32 noundef 0) #8, !dbg !80
  store i8* %20, i8** %19, align 8, !dbg !80
  %21 = tail call i8* @llvm.stacksave() #8, !dbg !80
  %22 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %ecTag, i64 0, i32 2, i64 2, !dbg !80
  store i8* %21, i8** %22, align 8, !dbg !80
  %23 = bitcast i8** %19 to i8*, !dbg !80
  %24 = call i32 @llvm.eh.sjlj.setjmp(i8* nonnull align 8 %23) #8, !dbg !80
  %25 = icmp eq i32 %24, 0, !dbg !80
  br i1 %25, label %sorbet_initializeTag.exit.thread, label %sorbet_initializeTag.exit, !dbg !80

sorbet_initializeTag.exit.thread:                 ; preds = %sorbet_writeLocal.exit
  store %struct.rb_vm_tag* %ecTag, %struct.rb_vm_tag** %16, align 8, !dbg !80, !tbaa !69
  br label %exception-entry.preheader, !dbg !80

sorbet_initializeTag.exit:                        ; preds = %sorbet_writeLocal.exit
  %26 = load %struct.rb_vm_tag*, %struct.rb_vm_tag** %16, align 8, !dbg !80, !tbaa !69
  %27 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %26, i64 0, i32 4, !dbg !80
  %28 = load i32, i32* %27, align 8, !dbg !80, !tbaa !66
  store i32 0, i32* %27, align 8, !dbg !80, !tbaa !66
  %29 = icmp ne i32 %28, 0, !dbg !80
  br i1 %29, label %exception-ensure, label %exception-entry.preheader, !dbg !80

exception-entry.preheader:                        ; preds = %sorbet_initializeTag.exit.thread, %sorbet_initializeTag.exit
  %30 = bitcast i64* %0 to i8*
  %31 = bitcast %struct.ExceptionClosure* %1 to i8*
  %32 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %1, i64 0, i32 0
  %33 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %1, i64 0, i32 1
  %34 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %1, i64 0, i32 2
  %35 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %1, i64 0, i32 3
  %36 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %1, i64 0, i32 4
  %37 = icmp eq i64 %previousException, 8
  %38 = ptrtoint %struct.ExceptionClosure* %1 to i64
  %39 = ptrtoint i64* %exceptionValue to i64
  %40 = bitcast i64* %2 to i8*
  %41 = bitcast %struct.ExceptionClosure* %3 to i8*
  %42 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %3, i64 0, i32 0
  %43 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %3, i64 0, i32 1
  %44 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %3, i64 0, i32 2
  %45 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %3, i64 0, i32 3
  %46 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %3, i64 0, i32 4
  %47 = ptrtoint %struct.ExceptionClosure* %3 to i64
  br i1 %37, label %exception-entry.us, label %exception-entry, !dbg !80

exception-entry.us:                               ; preds = %exception-entry.preheader, %sorbet_try.exit.us
  %48 = load i64*, i64** %5, align 8, !dbg !80, !tbaa !26
  %49 = load i64, i64* %48, align 8, !dbg !80, !tbaa !14
  %50 = and i64 %49, 8, !dbg !80
  %51 = icmp eq i64 %50, 0, !dbg !80
  br i1 %51, label %53, label %52, !dbg !80, !prof !34

52:                                               ; preds = %exception-entry.us
  call void @sorbet_vm_env_write_slowpath(i64* nonnull align 8 dereferenceable(8) %48, i32 noundef -3, i64 noundef 8) #8, !dbg !80
  br label %sorbet_writeLocal.exit20.us, !dbg !80

53:                                               ; preds = %exception-entry.us
  %54 = getelementptr inbounds i64, i64* %48, i64 -3, !dbg !80
  store i64 8, i64* %54, align 8, !dbg !80, !tbaa !14
  br label %sorbet_writeLocal.exit20.us, !dbg !80

sorbet_writeLocal.exit20.us:                      ; preds = %53, %52
  call void @llvm.lifetime.start.p0i8(i64 noundef 8, i8* noundef nonnull align 8 %30) #19, !dbg !80
  store i64 52, i64* %0, align 8, !dbg !80, !tbaa !14
  call void @llvm.lifetime.start.p0i8(i64 noundef 40, i8* noundef nonnull align 8 %31) #19, !dbg !80
  store i64 (i64**, i64, %struct.rb_control_frame_struct*)* @"func_Test.test_nilable_arg$block_1", i64 (i64**, i64, %struct.rb_control_frame_struct*)** %32, align 8, !dbg !80, !tbaa !4
  store i64** %4, i64*** %33, align 8, !dbg !80, !tbaa !10
  store i64 0, i64* %34, align 8, !dbg !80, !tbaa !11
  store %struct.rb_control_frame_struct* %cfp, %struct.rb_control_frame_struct** %35, align 8, !dbg !80, !tbaa !12
  store i64* %0, i64** %36, align 8, !dbg !80, !tbaa !13
  store i64 8, i64* %exceptionValue, align 8, !dbg !80, !tbaa !14
  %55 = load i64, i64* @rb_eException, align 8, !dbg !80, !tbaa !14
  %56 = call i64 (i64 (i64)*, i64, i64 (i64, i64)*, i64, ...) @rb_rescue2(i64 (i64)* noundef nonnull @sorbet_applyExceptionClosure, i64 noundef %38, i64 (i64, i64)* noundef nonnull @sorbet_rescueStoreException, i64 %39, i64 %55, i32 0) #8, !dbg !80
  %57 = load i64, i64* %0, align 8, !dbg !80
  call void @llvm.lifetime.end.p0i8(i64 noundef 40, i8* noundef nonnull %31) #8, !dbg !80
  call void @llvm.lifetime.end.p0i8(i64 noundef 8, i8* noundef nonnull %30) #8, !dbg !80
  %isReturnValue.us = icmp ne i64 %57, 52, !dbg !80
  br i1 %isReturnValue.us, label %exception-body-return, label %exception-body-handlers.us, !dbg !80

exception-body-handlers.us:                       ; preds = %sorbet_writeLocal.exit20.us
  %58 = load i64, i64* %exceptionValue, align 8, !dbg !80
  %59 = load i64*, i64** %5, align 8, !dbg !80, !tbaa !26
  %60 = load i64, i64* %59, align 8, !dbg !80, !tbaa !14
  %61 = and i64 %60, 8, !dbg !80
  %62 = icmp eq i64 %61, 0, !dbg !80
  br i1 %62, label %64, label %63, !dbg !80, !prof !34

63:                                               ; preds = %exception-body-handlers.us
  call void @sorbet_vm_env_write_slowpath(i64* nonnull align 8 dereferenceable(8) %59, i32 noundef -3, i64 %58) #8, !dbg !80
  br label %sorbet_writeLocal.exit21.us, !dbg !80

64:                                               ; preds = %exception-body-handlers.us
  %65 = getelementptr inbounds i64, i64* %59, i64 -3, !dbg !80
  store i64 %58, i64* %65, align 8, !dbg !80, !tbaa !14
  br label %sorbet_writeLocal.exit21.us, !dbg !80

sorbet_writeLocal.exit21.us:                      ; preds = %64, %63
  %66 = icmp ne i64 %58, 8, !dbg !80
  %handler.us = select i1 %66, i64 (i64**, i64, %struct.rb_control_frame_struct*)* @"func_Test.test_nilable_arg$block_2", i64 (i64**, i64, %struct.rb_control_frame_struct*)* @"func_Test.test_nilable_arg$block_4", !dbg !80
  call void @llvm.lifetime.start.p0i8(i64 noundef 8, i8* noundef nonnull align 8 %40) #19, !dbg !80
  store i64 52, i64* %2, align 8, !dbg !80, !tbaa !14
  call void @llvm.lifetime.start.p0i8(i64 noundef 40, i8* noundef nonnull align 8 %41) #19, !dbg !80
  store i64 (i64**, i64, %struct.rb_control_frame_struct*)* %handler.us, i64 (i64**, i64, %struct.rb_control_frame_struct*)** %42, align 8, !dbg !80, !tbaa !4
  store i64** %4, i64*** %43, align 8, !dbg !80, !tbaa !10
  store i64 0, i64* %44, align 8, !dbg !80, !tbaa !11
  store %struct.rb_control_frame_struct* %cfp, %struct.rb_control_frame_struct** %45, align 8, !dbg !80, !tbaa !12
  store i64* %2, i64** %46, align 8, !dbg !80, !tbaa !13
  store i64 8, i64* %exceptionValue, align 8, !dbg !80, !tbaa !14
  %67 = icmp eq i64 %58, 8, !dbg !80
  br i1 %67, label %sorbet_try.exit.us, label %68, !dbg !80

68:                                               ; preds = %sorbet_writeLocal.exit21.us
  call void @rb_set_errinfo(i64 %58) #8, !dbg !80
  br label %sorbet_try.exit.us, !dbg !80

sorbet_try.exit.us:                               ; preds = %68, %sorbet_writeLocal.exit21.us
  %69 = load i64, i64* @rb_eException, align 8, !dbg !80, !tbaa !14
  %70 = call i64 (i64 (i64)*, i64, i64 (i64, i64)*, i64, ...) @rb_rescue2(i64 (i64)* noundef nonnull @sorbet_applyExceptionClosure, i64 noundef %47, i64 (i64, i64)* noundef nonnull @sorbet_rescueStoreException, i64 %39, i64 %69, i32 0) #8, !dbg !80
  %71 = load i64, i64* %2, align 8, !dbg !80
  call void @llvm.lifetime.end.p0i8(i64 noundef 40, i8* noundef nonnull %41) #8, !dbg !80
  call void @llvm.lifetime.end.p0i8(i64 noundef 8, i8* noundef nonnull %40) #8, !dbg !80
  %72 = load i64, i64* %exceptionValue, align 8, !dbg !80
  %73 = icmp ne i64 %72, 8, !dbg !80
  %74 = load i64*, i64** %5, align 8, !dbg !80, !tbaa !26
  %75 = getelementptr inbounds i64, i64* %74, i64 -3, !dbg !80
  %76 = load i64, i64* %75, align 8, !dbg !80, !tbaa !14
  %77 = icmp ne i64 %76, 8, !dbg !80
  %78 = select i1 %77, i64 %76, i64 8, !dbg !80
  %79 = select i1 %73, i64 %72, i64 %78, !dbg !80
  call void @rb_set_errinfo(i64 %79), !dbg !80
  %"<retry-singleton>.us" = load i64, i64* @"<retry-singleton>", align 8, !dbg !80
  %shouldRetry.us = icmp eq i64 %71, %"<retry-singleton>.us", !dbg !80
  %80 = and i1 %66, %shouldRetry.us, !dbg !80
  br i1 %80, label %exception-entry.us, label %exception-ensure, !dbg !80

exception-entry:                                  ; preds = %exception-entry.preheader, %sorbet_try.exit
  %81 = load i64*, i64** %5, align 8, !dbg !80, !tbaa !26
  %82 = load i64, i64* %81, align 8, !dbg !80, !tbaa !14
  %83 = and i64 %82, 8, !dbg !80
  %84 = icmp eq i64 %83, 0, !dbg !80
  br i1 %84, label %85, label %87, !dbg !80, !prof !34

85:                                               ; preds = %exception-entry
  %86 = getelementptr inbounds i64, i64* %81, i64 -3, !dbg !80
  store i64 8, i64* %86, align 8, !dbg !80, !tbaa !14
  br label %sorbet_writeLocal.exit20, !dbg !80

87:                                               ; preds = %exception-entry
  call void @sorbet_vm_env_write_slowpath(i64* nonnull align 8 dereferenceable(8) %81, i32 noundef -3, i64 noundef 8) #8, !dbg !80
  br label %sorbet_writeLocal.exit20, !dbg !80

sorbet_writeLocal.exit20:                         ; preds = %85, %87
  call void @llvm.lifetime.start.p0i8(i64 noundef 8, i8* noundef nonnull align 8 %30) #19, !dbg !80
  store i64 52, i64* %0, align 8, !dbg !80, !tbaa !14
  call void @llvm.lifetime.start.p0i8(i64 noundef 40, i8* noundef nonnull align 8 %31) #19, !dbg !80
  store i64 (i64**, i64, %struct.rb_control_frame_struct*)* @"func_Test.test_nilable_arg$block_1", i64 (i64**, i64, %struct.rb_control_frame_struct*)** %32, align 8, !dbg !80, !tbaa !4
  store i64** %4, i64*** %33, align 8, !dbg !80, !tbaa !10
  store i64 0, i64* %34, align 8, !dbg !80, !tbaa !11
  store %struct.rb_control_frame_struct* %cfp, %struct.rb_control_frame_struct** %35, align 8, !dbg !80, !tbaa !12
  store i64* %0, i64** %36, align 8, !dbg !80, !tbaa !13
  store i64 8, i64* %exceptionValue, align 8, !dbg !80, !tbaa !14
  call void @rb_set_errinfo(i64 %previousException) #8, !dbg !80
  %88 = load i64, i64* @rb_eException, align 8, !dbg !80, !tbaa !14
  %89 = call i64 (i64 (i64)*, i64, i64 (i64, i64)*, i64, ...) @rb_rescue2(i64 (i64)* noundef nonnull @sorbet_applyExceptionClosure, i64 noundef %38, i64 (i64, i64)* noundef nonnull @sorbet_rescueStoreException, i64 %39, i64 %88, i32 0) #8, !dbg !80
  %90 = load i64, i64* %0, align 8, !dbg !80
  call void @llvm.lifetime.end.p0i8(i64 noundef 40, i8* noundef nonnull %31) #8, !dbg !80
  call void @llvm.lifetime.end.p0i8(i64 noundef 8, i8* noundef nonnull %30) #8, !dbg !80
  %isReturnValue = icmp ne i64 %90, 52, !dbg !80
  br i1 %isReturnValue, label %exception-body-return, label %exception-body-handlers, !dbg !80

exception-body-return:                            ; preds = %sorbet_writeLocal.exit20, %sorbet_writeLocal.exit20.us
  %.lcssa = phi i64 [ %57, %sorbet_writeLocal.exit20.us ], [ %90, %sorbet_writeLocal.exit20 ], !dbg !80
  call void @rb_set_errinfo(i64 %previousException), !dbg !80
  br label %exception-ensure, !dbg !80

exception-body-handlers:                          ; preds = %sorbet_writeLocal.exit20
  %91 = load i64, i64* %exceptionValue, align 8, !dbg !80
  %92 = load i64*, i64** %5, align 8, !dbg !80, !tbaa !26
  %93 = load i64, i64* %92, align 8, !dbg !80, !tbaa !14
  %94 = and i64 %93, 8, !dbg !80
  %95 = icmp eq i64 %94, 0, !dbg !80
  br i1 %95, label %96, label %98, !dbg !80, !prof !34

96:                                               ; preds = %exception-body-handlers
  %97 = getelementptr inbounds i64, i64* %92, i64 -3, !dbg !80
  store i64 %91, i64* %97, align 8, !dbg !80, !tbaa !14
  br label %sorbet_writeLocal.exit21, !dbg !80

98:                                               ; preds = %exception-body-handlers
  call void @sorbet_vm_env_write_slowpath(i64* nonnull align 8 dereferenceable(8) %92, i32 noundef -3, i64 %91) #8, !dbg !80
  br label %sorbet_writeLocal.exit21, !dbg !80

sorbet_writeLocal.exit21:                         ; preds = %96, %98
  %99 = icmp ne i64 %91, 8, !dbg !80
  %handler = select i1 %99, i64 (i64**, i64, %struct.rb_control_frame_struct*)* @"func_Test.test_nilable_arg$block_2", i64 (i64**, i64, %struct.rb_control_frame_struct*)* @"func_Test.test_nilable_arg$block_4", !dbg !80
  call void @llvm.lifetime.start.p0i8(i64 noundef 8, i8* noundef nonnull align 8 %40) #19, !dbg !80
  store i64 52, i64* %2, align 8, !dbg !80, !tbaa !14
  call void @llvm.lifetime.start.p0i8(i64 noundef 40, i8* noundef nonnull align 8 %41) #19, !dbg !80
  store i64 (i64**, i64, %struct.rb_control_frame_struct*)* %handler, i64 (i64**, i64, %struct.rb_control_frame_struct*)** %42, align 8, !dbg !80, !tbaa !4
  store i64** %4, i64*** %43, align 8, !dbg !80, !tbaa !10
  store i64 0, i64* %44, align 8, !dbg !80, !tbaa !11
  store %struct.rb_control_frame_struct* %cfp, %struct.rb_control_frame_struct** %45, align 8, !dbg !80, !tbaa !12
  store i64* %2, i64** %46, align 8, !dbg !80, !tbaa !13
  store i64 8, i64* %exceptionValue, align 8, !dbg !80, !tbaa !14
  %100 = icmp eq i64 %91, 8, !dbg !80
  br i1 %100, label %sorbet_try.exit, label %101, !dbg !80

101:                                              ; preds = %sorbet_writeLocal.exit21
  call void @rb_set_errinfo(i64 %91) #8, !dbg !80
  br label %sorbet_try.exit, !dbg !80

sorbet_try.exit:                                  ; preds = %sorbet_writeLocal.exit21, %101
  %102 = load i64, i64* @rb_eException, align 8, !dbg !80, !tbaa !14
  %103 = call i64 (i64 (i64)*, i64, i64 (i64, i64)*, i64, ...) @rb_rescue2(i64 (i64)* noundef nonnull @sorbet_applyExceptionClosure, i64 noundef %47, i64 (i64, i64)* noundef nonnull @sorbet_rescueStoreException, i64 %39, i64 %102, i32 0) #8, !dbg !80
  %104 = load i64, i64* %2, align 8, !dbg !80
  call void @llvm.lifetime.end.p0i8(i64 noundef 40, i8* noundef nonnull %41) #8, !dbg !80
  call void @llvm.lifetime.end.p0i8(i64 noundef 8, i8* noundef nonnull %40) #8, !dbg !80
  %105 = load i64, i64* %exceptionValue, align 8, !dbg !80
  %106 = icmp ne i64 %105, 8, !dbg !80
  %107 = load i64*, i64** %5, align 8, !dbg !80, !tbaa !26
  %108 = getelementptr inbounds i64, i64* %107, i64 -3, !dbg !80
  %109 = load i64, i64* %108, align 8, !dbg !80, !tbaa !14
  %110 = icmp ne i64 %109, 8, !dbg !80
  %111 = select i1 %110, i64 %109, i64 %previousException, !dbg !80
  %112 = select i1 %106, i64 %105, i64 %111, !dbg !80
  call void @rb_set_errinfo(i64 %112), !dbg !80
  %"<retry-singleton>" = load i64, i64* @"<retry-singleton>", align 8, !dbg !80
  %shouldRetry = icmp eq i64 %104, %"<retry-singleton>", !dbg !80
  %113 = and i1 %99, %shouldRetry, !dbg !80
  br i1 %113, label %exception-entry, label %exception-ensure, !dbg !80

exception-ensure:                                 ; preds = %sorbet_try.exit, %sorbet_try.exit.us, %exception-body-return, %sorbet_initializeTag.exit
  %114 = phi i32 [ 0, %exception-body-return ], [ %28, %sorbet_initializeTag.exit ], [ 0, %sorbet_try.exit.us ], [ 0, %sorbet_try.exit ]
  %115 = phi i64 [ %.lcssa, %exception-body-return ], [ 52, %sorbet_initializeTag.exit ], [ %71, %sorbet_try.exit.us ], [ %104, %sorbet_try.exit ], !dbg !80
  %116 = phi i64 [ 8, %exception-body-return ], [ %previousException, %sorbet_initializeTag.exit ], [ %79, %sorbet_try.exit.us ], [ %112, %sorbet_try.exit ], !dbg !80
  %117 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !80, !tbaa !19
  %118 = load %struct.rb_vm_tag*, %struct.rb_vm_tag** %18, align 8, !dbg !80, !tbaa !70
  %119 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %117, i64 0, i32 3, !dbg !80
  store %struct.rb_vm_tag* %118, %struct.rb_vm_tag** %119, align 8, !dbg !80, !tbaa !69
  %stackFrame.i = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Test.test_nilable_arg$block_3", align 8
  %120 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %117, i64 0, i32 2
  %121 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %120, align 8, !tbaa !20
  call void @sorbet_setExceptionStackFrame(%struct.rb_execution_context_struct* %117, %struct.rb_control_frame_struct* %121, %struct.rb_iseq_struct* %stackFrame.i) #8
  %122 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !19
  %123 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %122, i64 0, i32 2
  %124 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %123, align 8, !tbaa !20
  %125 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %124, i64 0, i32 0
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 14), i64** %125, align 8, !tbaa !19
  call void @sorbet_popFrame()
  %126 = icmp eq i32 %114, 0, !dbg !80
  br i1 %126, label %sorbet_maybeContinueUnwind.exit, label %127, !dbg !80

127:                                              ; preds = %exception-ensure
  %128 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !80, !tbaa !19
  %129 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %128, i64 0, i32 3, !dbg !80
  %130 = load %struct.rb_vm_tag*, %struct.rb_vm_tag** %129, align 8, !dbg !80, !tbaa !69
  %131 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %130, i64 0, i32 4, !dbg !80
  store i32 %114, i32* %131, align 8, !dbg !80, !tbaa !66
  %132 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %130, i64 0, i32 2, i64 0, !dbg !80
  %133 = bitcast i8** %132 to i8*, !dbg !80
  call void @llvm.eh.sjlj.longjmp(i8* nonnull %133) #9, !dbg !80
  unreachable, !dbg !80

sorbet_maybeContinueUnwind.exit:                  ; preds = %exception-ensure
  %isReturnValue11 = icmp ne i64 %115, 52, !dbg !80
  br i1 %isReturnValue11, label %normalReturn, label %exception-continue, !dbg !80

exception-continue:                               ; preds = %sorbet_maybeContinueUnwind.exit
  %134 = icmp eq i64 %116, 8, !dbg !80
  br i1 %134, label %sorbet_raiseIfNotNil.exit19, label %135, !dbg !80

135:                                              ; preds = %exception-continue
  call void @rb_exc_raise(i64 %116) #9, !dbg !80
  unreachable, !dbg !80

sorbet_raiseIfNotNil.exit19:                      ; preds = %exception-continue
  %136 = load i64*, i64** %5, align 8, !dbg !80, !tbaa !26
  %137 = getelementptr inbounds i64, i64* %136, i64 -3, !dbg !80
  %138 = load i64, i64* %137, align 8, !dbg !80, !tbaa !14
  %139 = icmp eq i64 %138, 8, !dbg !80
  br i1 %139, label %sorbet_raiseIfNotNil.exit, label %140, !dbg !80

140:                                              ; preds = %sorbet_raiseIfNotNil.exit19
  call void @rb_exc_raise(i64 %138) #9, !dbg !80
  unreachable, !dbg !80

sorbet_raiseIfNotNil.exit:                        ; preds = %sorbet_raiseIfNotNil.exit19
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 21), i64** %4, align 8, !tbaa !19
  %141 = getelementptr inbounds i64, i64* %136, i64 -6, !dbg !84
  %142 = load i64, i64* %141, align 8, !dbg !84, !tbaa !14
  br label %normalReturn, !dbg !84

normalReturn:                                     ; preds = %sorbet_maybeContinueUnwind.exit, %sorbet_raiseIfNotNil.exit
  %"<returnValue>.sroa.0.0" = phi i64 [ %142, %sorbet_raiseIfNotNil.exit ], [ %115, %sorbet_maybeContinueUnwind.exit ], !dbg !83
  ret i64 %"<returnValue>.sroa.0.0"
}

; Function Attrs: ssp
define internal noundef i64 @"func_Test.test_nilable_arg$block_1"(i64** nocapture nonnull writeonly align 8 dereferenceable(8) %pc, i64 %localsOffset, %struct.rb_control_frame_struct* nonnull align 8 dereferenceable(40) %cfp) #13 !dbg !54 {
fastSymCallIntrinsic_T_must:
  %callArgs = alloca [3 x i64], align 8
  %0 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !19
  %1 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %0, i64 0, i32 2
  %2 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %1, align 8, !tbaa !20
  %3 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 3
  %4 = load i64, i64* %3, align 8, !tbaa !75
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 16), i64** %pc, align 8, !tbaa !19
  %5 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %cfp, i64 0, i32 4, !dbg !53
  %6 = load i64*, i64** %5, align 8, !dbg !53, !tbaa !26
  %7 = getelementptr inbounds i64, i64* %6, i64 -4, !dbg !53
  %8 = load i64, i64* %7, align 8, !dbg !53, !tbaa !14
  %callArgs0Addr = getelementptr [3 x i64], [3 x i64]* %callArgs, i32 0, i64 0, !dbg !53
  store i64 %8, i64* %callArgs0Addr, align 8, !dbg !53
  %9 = getelementptr [3 x i64], [3 x i64]* %callArgs, i64 0, i64 0, !dbg !53
  tail call void @llvm.experimental.noalias.scope.decl(metadata !85), !dbg !53
  %10 = load i64, i64* %9, align 8, !dbg !53, !tbaa !14, !alias.scope !85
  %11 = icmp eq i64 %10, 8, !dbg !53
  br i1 %11, label %26, label %sorbet_T_must.exit, !dbg !53, !prof !64

afterSend:                                        ; preds = %36, %sorbet_T_must.exit
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 17), i64** %pc, align 8, !dbg !53, !tbaa !19
  %"rubyStr_ wasn't nil" = load i64, i64* @"rubyStrFrozen_ wasn't nil", align 8, !dbg !88
  %12 = load i64*, i64** %5, align 8, !dbg !89, !tbaa !26
  %13 = getelementptr inbounds i64, i64* %12, i64 -4, !dbg !89
  %14 = load i64, i64* %13, align 8, !dbg !89, !tbaa !14
  store i64 %14, i64* %callArgs0Addr, align 8, !dbg !89
  %callArgs1Addr = getelementptr [3 x i64], [3 x i64]* %callArgs, i32 0, i64 1, !dbg !89
  store i64 %"rubyStr_ wasn't nil", i64* %callArgs1Addr, align 8, !dbg !89
  %"rubyId_<string-interpolate>" = load i64, i64* @"rubyIdPrecomputed_<string-interpolate>", align 8, !dbg !89
  %rawSendResult13 = call i64 @sorbet_stringInterpolate(i64 noundef 8, i64 %"rubyId_<string-interpolate>", i32 noundef 2, i64* noundef nonnull %9, i64 (i64, i64, i32, i64*, i64)* noundef null, i64 noundef 0), !dbg !89
  %15 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %cfp, i64 0, i32 1, !dbg !56
  %16 = load i64*, i64** %15, align 8, !dbg !56
  store i64 %4, i64* %16, align 8, !dbg !56, !tbaa !14
  %17 = getelementptr inbounds i64, i64* %16, i64 1, !dbg !56
  store i64 %rawSendResult13, i64* %17, align 8, !dbg !56, !tbaa !14
  %18 = getelementptr inbounds i64, i64* %17, i64 1, !dbg !56
  store i64* %18, i64** %15, align 8, !dbg !56
  %send = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_puts.4, i64 0), !dbg !56
  %19 = load i64*, i64** %5, align 8, !dbg !56, !tbaa !26
  %20 = load i64, i64* %19, align 8, !dbg !56, !tbaa !14
  %21 = and i64 %20, 8, !dbg !56
  %22 = icmp eq i64 %21, 0, !dbg !56
  br i1 %22, label %23, label %25, !dbg !56, !prof !34

23:                                               ; preds = %afterSend
  %24 = getelementptr inbounds i64, i64* %19, i64 -6, !dbg !56
  store i64 %send, i64* %24, align 8, !dbg !56, !tbaa !14
  br label %sorbet_writeLocal.exit, !dbg !56

25:                                               ; preds = %afterSend
  call void @sorbet_vm_env_write_slowpath(i64* nonnull align 8 dereferenceable(8) %19, i32 noundef -6, i64 %send) #8, !dbg !56
  br label %sorbet_writeLocal.exit, !dbg !56

sorbet_writeLocal.exit:                           ; preds = %23, %25
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 16), i64** %pc, align 8, !dbg !56, !tbaa !19
  ret i64 52

26:                                               ; preds = %fastSymCallIntrinsic_T_must
  %27 = load i64, i64* @rb_eTypeError, align 8, !dbg !53, !tbaa !14, !noalias !85
  tail call void (i64, i8*, ...) @rb_raise(i64 %27, i8* noundef getelementptr inbounds ([25 x i8], [25 x i8]* @.str.1, i64 0, i64 0)) #9, !dbg !53, !noalias !85
  unreachable, !dbg !53

sorbet_T_must.exit:                               ; preds = %fastSymCallIntrinsic_T_must
  %28 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !53, !tbaa !19
  %29 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %28, i64 0, i32 5, !dbg !53
  %30 = load i32, i32* %29, align 8, !dbg !53, !tbaa !32
  %31 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %28, i64 0, i32 6, !dbg !53
  %32 = load i32, i32* %31, align 4, !dbg !53, !tbaa !33
  %33 = xor i32 %32, -1, !dbg !53
  %34 = and i32 %33, %30, !dbg !53
  %35 = icmp eq i32 %34, 0, !dbg !53
  br i1 %35, label %afterSend, label %36, !dbg !53, !prof !34

36:                                               ; preds = %sorbet_T_must.exit
  %37 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %28, i64 0, i32 8, !dbg !53
  %38 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %37, align 8, !dbg !53, !tbaa !35
  %39 = tail call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* %38, i32 noundef 0) #8, !dbg !53
  br label %afterSend, !dbg !53
}

; Function Attrs: ssp
define internal noundef i64 @"func_Test.test_nilable_arg$block_2"(i64** nocapture nofree readnone %pc, i64 %localsOffset, %struct.rb_control_frame_struct* nocapture nofree readnone %cfp) #13 !dbg !58 {
vm_get_ep.exit34:
  %0 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !19
  %1 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %0, i64 0, i32 2
  %2 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %1, align 8, !tbaa !20
  %3 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 3
  %4 = load i64, i64* %3, align 8, !tbaa !75
  %stackFrame = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Test.test_nilable_arg$block_2", align 8
  tail call void @sorbet_setExceptionStackFrame(%struct.rb_execution_context_struct* %0, %struct.rb_control_frame_struct* %2, %struct.rb_iseq_struct* %stackFrame) #8
  %5 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !19
  %6 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %5, i64 0, i32 2
  %7 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %6, align 8, !tbaa !20
  %8 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %7, i64 0, i32 0
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 18), i64** %8, align 8, !tbaa !19
  %9 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !57, !tbaa !19
  %10 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %9, i64 0, i32 2, !dbg !57
  %11 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %10, align 8, !dbg !57, !tbaa !20
  %12 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %11, i64 0, i32 4, !dbg !57
  %13 = load i64*, i64** %12, align 8, !dbg !57
  %14 = getelementptr inbounds i64, i64* %13, i64 -1, !dbg !57
  %15 = load i64, i64* %14, align 8, !dbg !57, !tbaa !14
  %16 = and i64 %15, -4, !dbg !57
  %17 = inttoptr i64 %16 to i64*, !dbg !57
  %18 = getelementptr inbounds i64, i64* %17, i64 -3, !dbg !57
  %19 = load i64, i64* %18, align 8, !dbg !57, !tbaa !14
  %20 = load i64, i64* @rb_eStandardError, align 8, !dbg !57
  %21 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %11, i64 0, i32 1, !dbg !57
  %22 = load i64*, i64** %21, align 8, !dbg !57
  store i64 %19, i64* %22, align 8, !dbg !57, !tbaa !14
  %23 = getelementptr inbounds i64, i64* %22, i64 1, !dbg !57
  store i64 %20, i64* %23, align 8, !dbg !57, !tbaa !14
  %24 = getelementptr inbounds i64, i64* %23, i64 1, !dbg !57
  store i64* %24, i64** %21, align 8, !dbg !57
  %send = tail call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @"ic_is_a?.5", i64 0), !dbg !57
  %25 = and i64 %send, -9, !dbg !57
  %26 = icmp ne i64 %25, 0, !dbg !57
  br i1 %26, label %vm_get_ep.exit32, label %vm_get_ep.exit, !dbg !57

blockExit:                                        ; preds = %78, %76, %63, %61
  tail call void @sorbet_popFrame()
  ret i64 52

vm_get_ep.exit32:                                 ; preds = %vm_get_ep.exit34
  %27 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !90, !tbaa !19
  %28 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %27, i64 0, i32 2, !dbg !90
  %29 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %28, align 8, !dbg !90, !tbaa !20
  %30 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %29, i64 0, i32 4, !dbg !90
  %31 = load i64*, i64** %30, align 8, !dbg !90
  %32 = getelementptr inbounds i64, i64* %31, i64 -1, !dbg !90
  %33 = load i64, i64* %32, align 8, !dbg !90, !tbaa !14
  %34 = and i64 %33, -4, !dbg !90
  %35 = inttoptr i64 %34 to i64*, !dbg !90
  %36 = load i64, i64* %35, align 8, !dbg !90, !tbaa !14
  %37 = and i64 %36, 8, !dbg !90
  %38 = icmp eq i64 %37, 0, !dbg !90
  br i1 %38, label %39, label %41, !dbg !90, !prof !34

39:                                               ; preds = %vm_get_ep.exit32
  %40 = getelementptr inbounds i64, i64* %35, i64 -3, !dbg !90
  store i64 8, i64* %40, align 8, !dbg !90, !tbaa !14
  br label %vm_get_ep.exit30, !dbg !90

41:                                               ; preds = %vm_get_ep.exit32
  tail call void @sorbet_vm_env_write_slowpath(i64* nonnull align 8 dereferenceable(8) %35, i32 noundef -3, i64 noundef 8) #8, !dbg !90
  br label %vm_get_ep.exit30, !dbg !90

vm_get_ep.exit30:                                 ; preds = %39, %41
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 19), i64** %8, align 8, !dbg !91, !tbaa !19
  %42 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !59, !tbaa !19
  %43 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %42, i64 0, i32 2, !dbg !59
  %44 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %43, align 8, !dbg !59, !tbaa !20
  %45 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %44, i64 0, i32 1, !dbg !59
  %46 = load i64*, i64** %45, align 8, !dbg !59
  store i64 %4, i64* %46, align 8, !dbg !59, !tbaa !14
  %47 = getelementptr inbounds i64, i64* %46, i64 1, !dbg !59
  store i64 %19, i64* %47, align 8, !dbg !59, !tbaa !14
  %48 = getelementptr inbounds i64, i64* %47, i64 1, !dbg !59
  store i64* %48, i64** %45, align 8, !dbg !59
  %send42 = tail call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_puts.6, i64 0), !dbg !59
  %49 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !59, !tbaa !19
  %50 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %49, i64 0, i32 2, !dbg !59
  %51 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %50, align 8, !dbg !59, !tbaa !20
  %52 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %51, i64 0, i32 4, !dbg !59
  %53 = load i64*, i64** %52, align 8, !dbg !59
  %54 = getelementptr inbounds i64, i64* %53, i64 -1, !dbg !59
  %55 = load i64, i64* %54, align 8, !dbg !59, !tbaa !14
  %56 = and i64 %55, -4, !dbg !59
  %57 = inttoptr i64 %56 to i64*, !dbg !59
  %58 = load i64, i64* %57, align 8, !dbg !59, !tbaa !14
  %59 = and i64 %58, 8, !dbg !59
  %60 = icmp eq i64 %59, 0, !dbg !59
  br i1 %60, label %61, label %63, !dbg !59, !prof !34

61:                                               ; preds = %vm_get_ep.exit30
  %62 = getelementptr inbounds i64, i64* %57, i64 -6, !dbg !59
  store i64 %send42, i64* %62, align 8, !dbg !59, !tbaa !14
  br label %blockExit, !dbg !59

63:                                               ; preds = %vm_get_ep.exit30
  tail call void @sorbet_vm_env_write_slowpath(i64* nonnull align 8 dereferenceable(8) %57, i32 noundef -6, i64 %send42) #8, !dbg !59
  br label %blockExit, !dbg !59

vm_get_ep.exit:                                   ; preds = %vm_get_ep.exit34
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 16), i64** %8, align 8, !tbaa !19
  %64 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !92, !tbaa !19
  %65 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %64, i64 0, i32 2, !dbg !92
  %66 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %65, align 8, !dbg !92, !tbaa !20
  %67 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %66, i64 0, i32 4, !dbg !92
  %68 = load i64*, i64** %67, align 8, !dbg !92
  %69 = getelementptr inbounds i64, i64* %68, i64 -1, !dbg !92
  %70 = load i64, i64* %69, align 8, !dbg !92, !tbaa !14
  %71 = and i64 %70, -4, !dbg !92
  %72 = inttoptr i64 %71 to i64*, !dbg !92
  %73 = load i64, i64* %72, align 8, !dbg !92, !tbaa !14
  %74 = and i64 %73, 8, !dbg !92
  %75 = icmp eq i64 %74, 0, !dbg !92
  br i1 %75, label %76, label %78, !dbg !92, !prof !34

76:                                               ; preds = %vm_get_ep.exit
  %77 = getelementptr inbounds i64, i64* %72, i64 -7, !dbg !92
  store i64 20, i64* %77, align 8, !dbg !92, !tbaa !14
  br label %blockExit, !dbg !92

78:                                               ; preds = %vm_get_ep.exit
  tail call void @sorbet_vm_env_write_slowpath(i64* nonnull align 8 dereferenceable(8) %72, i32 noundef -7, i64 noundef 20) #8, !dbg !92
  br label %blockExit, !dbg !92
}

; Function Attrs: argmemonly nofree norecurse nosync nounwind ssp willreturn writeonly
define internal noundef i64 @"func_Test.test_nilable_arg$block_4"(i64** nocapture nofree nonnull writeonly align 8 dereferenceable(8) %pc, i64 %localsOffset, %struct.rb_control_frame_struct* nocapture nofree readnone %cfp) #14 !dbg !93 {
functionEntryInitializers:
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 14), i64** %pc, align 8, !tbaa !19
  ret i64 52
}

; Function Attrs: inaccessiblememonly nofree nosync nounwind willreturn
declare void @llvm.experimental.noalias.scope.decl(metadata) #15

; Function Attrs: argmemonly nofree nosync nounwind willreturn writeonly
declare void @llvm.memset.p0i8.i64(i8* nocapture writeonly, i8, i64, i1 immarg) #16

; Function Attrs: nofree nosync nounwind willreturn
declare void @llvm.assume(i1 noundef) #7

; Function Attrs: ssp
define linkonce void @const_recompute_Test() local_unnamed_addr #13 {
  %1 = tail call i64 @sorbet_getConstant(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_Test, i64 0, i64 0), i64 4)
  store i64 %1, i64* @guarded_const_Test, align 8
  %2 = load i64, i64* @ruby_vm_global_constant_state, align 8, !tbaa !29
  store i64 %2, i64* @guard_epoch_Test, align 8
  ret void
}

attributes #0 = { "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #1 = { noreturn "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #2 = { argmemonly nofree nosync nounwind willreturn }
attributes #3 = { allocsize(0,1) "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #4 = { nounwind ssp uwtable "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #5 = { nofree norecurse nosync nounwind ssp uwtable willreturn writeonly "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #6 = { nofree nosync nounwind readnone willreturn }
attributes #7 = { nofree nosync nounwind willreturn }
attributes #8 = { nounwind }
attributes #9 = { noreturn nounwind }
attributes #10 = { nounwind sspreq uwtable }
attributes #11 = { sspreq }
attributes #12 = { nounwind ssp }
attributes #13 = { ssp }
attributes #14 = { argmemonly nofree norecurse nosync nounwind ssp willreturn writeonly }
attributes #15 = { inaccessiblememonly nofree nosync nounwind willreturn }
attributes #16 = { argmemonly nofree nosync nounwind willreturn writeonly }
attributes #17 = { nounwind allocsize(0,1) }
attributes #18 = { noreturn }
attributes #19 = { nounwind willreturn }

!llvm.module.flags = !{!0}
!llvm.dbg.cu = !{!1}

!0 = !{i32 2, !"Debug Info Version", i32 3}
!1 = distinct !DICompileUnit(language: DW_LANG_C, file: !2, producer: "Sorbet LLVM", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, enums: !3)
!2 = !DIFile(filename: "test/testdata/compiler/intrinsics/t_must.rb", directory: ".")
!3 = !{}
!4 = !{!5, !6, i64 0}
!5 = !{!"ExceptionClosure", !6, i64 0, !6, i64 8, !9, i64 16, !6, i64 24, !6, i64 32}
!6 = !{!"any pointer", !7, i64 0}
!7 = !{!"omnipotent char", !8, i64 0}
!8 = !{!"Simple C/C++ TBAA"}
!9 = !{!"long", !7, i64 0}
!10 = !{!5, !6, i64 8}
!11 = !{!5, !9, i64 16}
!12 = !{!5, !6, i64 24}
!13 = !{!5, !6, i64 32}
!14 = !{!9, !9, i64 0}
!15 = distinct !DISubprogram(name: "Test.<static-init>", linkageName: "func_Test.<static-init>L62", scope: null, file: !2, line: 5, type: !16, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!16 = !DISubroutineType(types: !17)
!17 = !{!18}
!18 = !DIBasicType(name: "VALUE", size: 64, encoding: DW_ATE_signed)
!19 = !{!6, !6, i64 0}
!20 = !{!21, !6, i64 16}
!21 = !{!"rb_execution_context_struct", !6, i64 0, !9, i64 8, !6, i64 16, !6, i64 24, !6, i64 32, !22, i64 40, !22, i64 44, !6, i64 48, !6, i64 56, !6, i64 64, !9, i64 72, !9, i64 80, !6, i64 88, !9, i64 96, !6, i64 104, !6, i64 112, !9, i64 120, !9, i64 128, !7, i64 136, !7, i64 137, !9, i64 144, !23, i64 152}
!22 = !{!"int", !7, i64 0}
!23 = !{!"", !6, i64 0, !6, i64 8, !9, i64 16, !7, i64 24}
!24 = !{!25, !6, i64 16}
!25 = !{!"rb_control_frame_struct", !6, i64 0, !6, i64 8, !6, i64 16, !9, i64 24, !6, i64 32, !6, i64 40, !6, i64 48}
!26 = !{!25, !6, i64 32}
!27 = !DILocation(line: 0, scope: !15)
!28 = !DILocation(line: 6, column: 3, scope: !15)
!29 = !{!30, !30, i64 0}
!30 = !{!"long long", !7, i64 0}
!31 = !{!"branch_weights", i32 1, i32 10000}
!32 = !{!21, !22, i64 40}
!33 = !{!21, !22, i64 44}
!34 = !{!"branch_weights", i32 2000, i32 1}
!35 = !{!21, !6, i64 56}
!36 = !DILocation(line: 14, column: 3, scope: !15)
!37 = !{!38, !22, i64 8}
!38 = !{!"rb_sorbet_param_struct", !39, i64 0, !22, i64 4, !22, i64 8, !22, i64 12, !22, i64 16, !22, i64 20, !22, i64 24, !22, i64 28, !6, i64 32, !22, i64 40, !22, i64 44, !22, i64 48, !22, i64 52, !6, i64 56}
!39 = !{!"", !22, i64 0, !22, i64 0, !22, i64 0, !22, i64 0, !22, i64 0, !22, i64 0, !22, i64 0, !22, i64 0, !22, i64 1, !22, i64 1}
!40 = !{!38, !22, i64 4}
!41 = !{!38, !6, i64 32}
!42 = !DILocation(line: 24, column: 1, scope: !43)
!43 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.<static-init>$151", scope: null, file: !2, line: 5, type: !16, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!44 = !DILocation(line: 25, column: 1, scope: !43)
!45 = !DILocation(line: 26, column: 1, scope: !43)
!46 = !DILocation(line: 27, column: 1, scope: !43)
!47 = !DILocation(line: 8, column: 7, scope: !48)
!48 = distinct !DISubprogram(name: "Test.test_known_nil", linkageName: "func_Test.test_known_nil$block_1", scope: !49, file: !2, line: 6, type: !16, scopeLine: 6, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!49 = distinct !DISubprogram(name: "Test.test_known_nil", linkageName: "func_Test.test_known_nil", scope: null, file: !2, line: 6, type: !16, scopeLine: 6, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!50 = !DILocation(line: 9, column: 15, scope: !51)
!51 = distinct !DISubprogram(name: "Test.test_known_nil", linkageName: "func_Test.test_known_nil$block_2", scope: !49, file: !2, line: 6, type: !16, scopeLine: 6, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!52 = !DILocation(line: 10, column: 7, scope: !51)
!53 = !DILocation(line: 16, column: 7, scope: !54)
!54 = distinct !DISubprogram(name: "Test.test_nilable_arg", linkageName: "func_Test.test_nilable_arg$block_1", scope: !55, file: !2, line: 14, type: !16, scopeLine: 14, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!55 = distinct !DISubprogram(name: "Test.test_nilable_arg", linkageName: "func_Test.test_nilable_arg", scope: null, file: !2, line: 14, type: !16, scopeLine: 14, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!56 = !DILocation(line: 17, column: 7, scope: !54)
!57 = !DILocation(line: 18, column: 15, scope: !58)
!58 = distinct !DISubprogram(name: "Test.test_nilable_arg", linkageName: "func_Test.test_nilable_arg$block_2", scope: !55, file: !2, line: 14, type: !16, scopeLine: 14, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!59 = !DILocation(line: 19, column: 7, scope: !58)
!60 = !DILocation(line: 0, scope: !43)
!61 = !DILocation(line: 5, column: 1, scope: !43)
!62 = !DILocation(line: 8, column: 7, scope: !49)
!63 = !DILocation(line: 6, column: 3, scope: !49)
!64 = !{!"branch_weights", i32 1, i32 2000}
!65 = !DILocation(line: 0, scope: !49)
!66 = !{!67, !7, i64 64}
!67 = !{!"rb_vm_tag", !9, i64 0, !9, i64 8, !7, i64 16, !6, i64 56, !7, i64 64}
!68 = !{!67, !9, i64 0}
!69 = !{!21, !6, i64 24}
!70 = !{!67, !6, i64 56}
!71 = !DILocation(line: 12, column: 3, scope: !49)
!72 = !{!73}
!73 = distinct !{!73, !74, !"sorbet_T_must: argument 0"}
!74 = distinct !{!74, !"sorbet_T_must"}
!75 = !{!25, !9, i64 24}
!76 = !DILocation(line: 0, scope: !51)
!77 = !DILocation(line: 9, column: 5, scope: !51)
!78 = !DILocation(line: 8, column: 7, scope: !51)
!79 = distinct !DISubprogram(name: "Test.test_known_nil", linkageName: "func_Test.test_known_nil$block_4", scope: !49, file: !2, line: 6, type: !16, scopeLine: 6, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!80 = !DILocation(line: 16, column: 7, scope: !55)
!81 = !DILocation(line: 14, column: 3, scope: !55)
!82 = !{!"branch_weights", i32 4001, i32 4000000}
!83 = !DILocation(line: 0, scope: !55)
!84 = !DILocation(line: 21, column: 3, scope: !55)
!85 = !{!86}
!86 = distinct !{!86, !87, !"sorbet_T_must: argument 0"}
!87 = distinct !{!87, !"sorbet_T_must"}
!88 = !DILocation(line: 17, column: 19, scope: !54)
!89 = !DILocation(line: 17, column: 12, scope: !54)
!90 = !DILocation(line: 0, scope: !58)
!91 = !DILocation(line: 18, column: 5, scope: !58)
!92 = !DILocation(line: 16, column: 7, scope: !58)
!93 = distinct !DISubprogram(name: "Test.test_nilable_arg", linkageName: "func_Test.test_nilable_arg$block_4", scope: !55, file: !2, line: 14, type: !16, scopeLine: 14, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
