; ModuleID = 'payload'
source_filename = "llvm-link"
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"

%struct.rb_vm_struct = type { i64, %struct.rb_global_vm_lock_struct, %struct.rb_thread_struct*, %struct.rb_thread_struct*, i8*, i64, %union.pthread_mutex_t, %union.anon.12, %union.anon.12, %union.anon.12, %union.anon.12, i64, i32, i8, i32, i64, [5 x i64], i64, i64, i64, i64, i64, i64, i64, %struct.st_table*, %struct.st_table*, %struct.anon.18, %struct.rb_hook_list_struct, %struct.st_table*, %struct.rb_postponed_job_struct*, i32, i32, %union.anon.12, %union.pthread_mutex_t, i64, i64, i64, i64, i64, i32, i64, %struct.rb_objspace*, %struct.rb_at_exit_list*, i64*, %struct.st_table*, %struct.anon.19, [28 x i16] }
%struct.rb_global_vm_lock_struct = type { %struct.rb_thread_struct*, %union.pthread_mutex_t, %union.anon.12, %struct.rb_thread_struct*, i32, %union.pthread_cond_t, %union.pthread_cond_t, i32, i32 }
%union.pthread_cond_t = type { %struct.anon.14 }
%struct.anon.14 = type { i32, i32, i64, i64, i64, i8*, i32, i32 }
%struct.rb_thread_struct = type { %struct.list_node, i64, %struct.rb_vm_struct*, %struct.rb_execution_context_struct*, i64, %struct.rb_calling_info*, i64, i64, i64, i8, i8, i32, %struct.native_thread_data_struct, i8*, i64, i64, i64, i64, %union.pthread_mutex_t, %struct.rb_unblock_callback, i64, %struct.rb_mutex_struct*, %struct.rb_thread_list_struct*, %union.anon.15, i32, i64, %struct.rb_fiber_struct*, [1 x %struct.__jmp_buf_tag], i64 }
%struct.list_node = type { %struct.list_node*, %struct.list_node* }
%struct.rb_execution_context_struct = type { i64*, i64, %struct.rb_control_frame_struct*, %struct.rb_vm_tag*, %struct.rb_vm_protect_tag*, i32, i32, %struct.rb_fiber_struct*, %struct.rb_thread_struct*, %struct.st_table*, i64, i64, i64*, i64, %struct.rb_ensure_list*, %struct.rb_trace_arg_struct*, i64, i64, i8, i8, i64, %struct.anon.11 }
%struct.rb_control_frame_struct = type { i64*, i64*, %struct.rb_iseq_struct*, i64, i64*, i8*, i64* }
%struct.rb_iseq_struct = type { i64, i64, %struct.rb_iseq_constant_body*, %union.anon.8 }
%struct.rb_iseq_constant_body = type { i32, i32, i64*, %struct.anon.1, %struct.rb_iseq_location_struct, %struct.iseq_insn_info, i64*, %struct.iseq_catch_table*, %struct.rb_iseq_struct*, %struct.rb_iseq_struct*, %union.iseq_inline_storage_entry*, %struct.rb_call_info*, %struct.rb_call_cache*, %struct.anon.7, i32, i32, i32, i32, i32, i64 (%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*)*, i64, %struct.rb_mjit_unit*, i8 }
%struct.anon.1 = type { %struct.anon.2, i32, i32, i32, i32, i32, i32, i32, i64*, %struct.rb_iseq_param_keyword* }
%struct.anon.2 = type { i8, [3 x i8] }
%struct.rb_iseq_param_keyword = type { i32, i32, i32, i32, i64*, i64* }
%struct.rb_iseq_location_struct = type { i64, i64, i64, i64, i32, %struct.rb_code_location_struct }
%struct.rb_code_location_struct = type { %struct.rb_code_position_struct, %struct.rb_code_position_struct }
%struct.rb_code_position_struct = type { i32, i32 }
%struct.iseq_insn_info = type { %struct.rb_code_position_struct*, i32*, i32, %struct.succ_index_table* }
%struct.succ_index_table = type opaque
%struct.iseq_catch_table = type opaque
%union.iseq_inline_storage_entry = type { %struct.iseq_inline_cache_entry }
%struct.iseq_inline_cache_entry = type { i64, %struct.rb_cref_struct*, %union.anon.0 }
%struct.rb_cref_struct = type { i64, i64, i64, %struct.rb_cref_struct*, %struct.anon.2 }
%union.anon.0 = type { i64 }
%struct.rb_call_info = type { i64, i32, i32 }
%struct.rb_call_cache = type { i64, i64, %struct.rb_callable_method_entry_struct*, i64 (%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_calling_info*, %struct.rb_call_info*, %struct.rb_call_cache*)*, %union.anon.6 }
%struct.rb_callable_method_entry_struct = type { i64, i64, %struct.rb_method_definition_struct*, i64, i64 }
%struct.rb_method_definition_struct = type { i64, %union.anon.5, i64 }
%union.anon.5 = type { %struct.rb_method_cfunc_struct }
%struct.rb_method_cfunc_struct = type { i64 (...)*, i64 (i64 (...)*, i64, i32, i64*)*, i32 }
%union.anon.6 = type { i32 }
%struct.anon.7 = type { i64, i64, i64, i64* }
%struct.rb_mjit_unit = type opaque
%union.anon.8 = type { %struct.anon.9 }
%struct.anon.9 = type { i64, i32 }
%struct.rb_vm_tag = type { i64, i64, [1 x %struct.__jmp_buf_tag], %struct.rb_vm_tag*, i32 }
%struct.rb_vm_protect_tag = type { %struct.rb_vm_protect_tag* }
%struct.rb_ensure_list = type { %struct.rb_ensure_list*, %struct.rb_ensure_entry }
%struct.rb_ensure_entry = type { i64, i64 (...)*, i64 }
%struct.rb_trace_arg_struct = type { i32, %struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, i64, i64, i64, i64, i64, i32, i32, i64 }
%struct.anon.11 = type { i64*, i64*, i64, [1 x %struct.__jmp_buf_tag] }
%struct.rb_calling_info = type { i64, i64, i32 }
%struct.native_thread_data_struct = type { %union.anon.12, %union.anon.13 }
%union.anon.13 = type { %union.pthread_cond_t }
%struct.rb_unblock_callback = type { void (i8*)*, i8* }
%struct.rb_mutex_struct = type opaque
%struct.rb_thread_list_struct = type { %struct.rb_thread_list_struct*, %struct.rb_thread_struct* }
%union.anon.15 = type { %struct.RBasic }
%struct.RBasic = type { i64, i64 }
%struct.rb_fiber_struct = type opaque
%struct.__jmp_buf_tag = type { [8 x i64], i32, %struct.__sigset_t }
%struct.__sigset_t = type { [16 x i64] }
%struct.anon.18 = type { [65 x i64], [65 x i8] }
%struct.rb_hook_list_struct = type { %struct.rb_event_hook_struct*, i32, i32, i32 }
%struct.rb_event_hook_struct = type opaque
%struct.rb_postponed_job_struct = type opaque
%union.anon.12 = type { %struct.list_node }
%union.pthread_mutex_t = type { %struct.__pthread_mutex_s }
%struct.__pthread_mutex_s = type { i32, i32, i32, i32, i32, i16, i16, %struct.__pthread_internal_list }
%struct.__pthread_internal_list = type { %struct.__pthread_internal_list*, %struct.__pthread_internal_list* }
%struct.rb_objspace = type opaque
%struct.rb_at_exit_list = type { void (%struct.rb_vm_struct*)*, %struct.rb_at_exit_list* }
%struct.st_table = type { i8, i8, i8, i32, %struct.st_hash_type*, i64, i64*, i64, i64, %struct.st_table_entry* }
%struct.st_hash_type = type { i32 (...)*, i64 (...)* }
%struct.st_table_entry = type opaque
%struct.anon.19 = type { i64, i64, i64, i64 }
%struct.FunctionInlineCache = type { %struct.rb_callable_method_entry_struct*, i64, i64 }
%struct.ExceptionClosure = type { i64 (i64**, i64*, i64)*, i64**, i64*, i64, i64* }

@rb_eRuntimeError = external local_unnamed_addr global i64, align 8
@.str.1 = private unnamed_addr constant [95 x i8] c"sorbet_getBuildSCMRevision: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@.str.2 = private unnamed_addr constant [93 x i8] c"sorbet_getIsReleaseBuild: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@ruby_current_vm_ptr = external local_unnamed_addr global %struct.rb_vm_struct*, align 8
@rb_eException = external local_unnamed_addr global i64, align 8
@rb_eTypeError = external local_unnamed_addr global i64, align 8
@ruby_current_execution_context_ptr = external local_unnamed_addr global %struct.rb_execution_context_struct*, align 8
@.str.17 = private unnamed_addr constant [24 x i8] c"$__sorbet_ruby_realpath\00", align 1
@.str.18 = private unnamed_addr constant [63 x i8] c"Invalid '$__sorbet_ruby_realpath' when loading compiled module\00", align 1
@rb_cModule = external local_unnamed_addr constant i64, align 8
@.str.20 = private unnamed_addr constant [25 x i8] c"Passed `nil` into T.must\00", align 1
@.str.24 = private unnamed_addr constant [25 x i8] c"T::Private::Retry::RETRY\00", align 1
@"stackFramePrecomputed_func_<root>.<static-init>$153" = internal unnamed_addr global i8* null, align 8
@"rubyIdPrecomputed_<top (required)>" = internal unnamed_addr global i64 0, align 8
@"str_<top (required)>" = private unnamed_addr constant [17 x i8] c"<top (required)>\00", align 1
@"rubyStrFrozen_<top (required)>" = internal unnamed_addr global i64 0, align 8
@"rubyStrFrozen_test/testdata/compiler/intrinsics/t_must.rb" = internal unnamed_addr global i64 0, align 8
@"str_test/testdata/compiler/intrinsics/t_must.rb" = private unnamed_addr constant [44 x i8] c"test/testdata/compiler/intrinsics/t_must.rb\00", align 1
@str_cast = private unnamed_addr constant [5 x i8] c"cast\00", align 1
@"str_T.class_of(<root>)" = private unnamed_addr constant [19 x i8] c"T.class_of(<root>)\00", align 1
@str_Test = private unnamed_addr constant [5 x i8] c"Test\00", align 1
@rubyIdPrecomputed_test_known_nil = internal unnamed_addr global i64 0, align 8
@str_test_known_nil = private unnamed_addr constant [15 x i8] c"test_known_nil\00", align 1
@ic_callFunc_test_known_nil = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_test_nilable_arg = internal unnamed_addr global i64 0, align 8
@str_test_nilable_arg = private unnamed_addr constant [17 x i8] c"test_nilable_arg\00", align 1
@ic_callFunc_test_nilable_arg = internal global %struct.FunctionInlineCache zeroinitializer
@ic_callFunc_test_nilable_arg.1 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_callFunc_test_nilable_arg.2 = internal global %struct.FunctionInlineCache zeroinitializer
@stackFramePrecomputed_func_Test.test_known_nil = internal unnamed_addr global i8* null, align 8
@"rubyIdPrecomputed_<exceptionValue>" = internal unnamed_addr global i64 0, align 8
@"str_<exceptionValue>" = private unnamed_addr constant [17 x i8] c"<exceptionValue>\00", align 1
@"rubyIdPrecomputed_<magic>" = internal unnamed_addr global i64 0, align 8
@"str_<magic>" = private unnamed_addr constant [8 x i8] c"<magic>\00", align 1
@"rubyIdPrecomputed_<returnMethodTemp>" = internal unnamed_addr global i64 0, align 8
@"str_<returnMethodTemp>" = private unnamed_addr constant [19 x i8] c"<returnMethodTemp>\00", align 1
@"rubyIdPrecomputed_<self>" = internal unnamed_addr global i64 0, align 8
@"str_<self>" = private unnamed_addr constant [7 x i8] c"<self>\00", align 1
@"rubyIdPrecomputed_<gotoDeadTemp>" = internal unnamed_addr global i64 0, align 8
@"str_<gotoDeadTemp>" = private unnamed_addr constant [15 x i8] c"<gotoDeadTemp>\00", align 1
@"stackFramePrecomputed_func_Test.test_known_nil$block_2" = internal unnamed_addr global i8* null, align 8
@"rubyIdPrecomputed_rescue for" = internal unnamed_addr global i64 0, align 8
@"str_rescue for" = private unnamed_addr constant [11 x i8] c"rescue for\00", align 1
@"rubyStrFrozen_rescue for" = internal unnamed_addr global i64 0, align 8
@"stackFramePrecomputed_func_Test.test_known_nil$block_3" = internal unnamed_addr global i8* null, align 8
@"rubyIdPrecomputed_ensure for" = internal unnamed_addr global i64 0, align 8
@"str_ensure for" = private unnamed_addr constant [11 x i8] c"ensure for\00", align 1
@"rubyStrFrozen_ensure for" = internal unnamed_addr global i64 0, align 8
@"str_T.class_of(Test)" = private unnamed_addr constant [17 x i8] c"T.class_of(Test)\00", align 1
@"<retry-singleton>" = internal unnamed_addr global i64 0
@str_must = private unnamed_addr constant [5 x i8] c"must\00", align 1
@"rubyIdPrecomputed_is_a?" = internal unnamed_addr global i64 0, align 8
@"str_is_a?" = private unnamed_addr constant [6 x i8] c"is_a?\00", align 1
@"ic_callFunc_is_a?" = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_puts = internal unnamed_addr global i64 0, align 8
@str_puts = private unnamed_addr constant [5 x i8] c"puts\00", align 1
@ic_callFunc_puts = internal global %struct.FunctionInlineCache zeroinitializer
@stackFramePrecomputed_func_Test.test_nilable_arg = internal unnamed_addr global i8* null, align 8
@rubyIdPrecomputed_arg = internal unnamed_addr global i64 0, align 8
@str_arg = private unnamed_addr constant [4 x i8] c"arg\00", align 1
@"stackFramePrecomputed_func_Test.test_nilable_arg$block_2" = internal unnamed_addr global i8* null, align 8
@"stackFramePrecomputed_func_Test.test_nilable_arg$block_3" = internal unnamed_addr global i8* null, align 8
@"rubyStrFrozen_ wasn't nil" = internal unnamed_addr global i64 0, align 8
@"str_ wasn't nil" = private unnamed_addr constant [12 x i8] c" wasn't nil\00", align 1
@"str_<string-interpolate>" = private unnamed_addr constant [21 x i8] c"<string-interpolate>\00", align 1
@ic_callFunc_puts.4 = internal global %struct.FunctionInlineCache zeroinitializer
@"ic_callFunc_is_a?.5" = internal global %struct.FunctionInlineCache zeroinitializer
@ic_callFunc_puts.6 = internal global %struct.FunctionInlineCache zeroinitializer
@"stackFramePrecomputed_func_Test.<static-init>" = internal unnamed_addr global i8* null, align 8
@"<static-init-locals-storage>.7" = internal global [0 x i64] zeroinitializer
@str_keep_self_def = private unnamed_addr constant [14 x i8] c"keep_self_def\00", align 1
@guard_epoch_Test = linkonce local_unnamed_addr global i64 0
@guarded_const_Test = linkonce local_unnamed_addr global i64 0
@rb_eStandardError = external local_unnamed_addr constant i64

; Function Attrs: nounwind ssp uwtable
define weak i8* @sorbet_getBuildSCMRevision() local_unnamed_addr #0 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !4
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* getelementptr inbounds ([95 x i8], [95 x i8]* @.str.1, i64 0, i64 0)) #17
  unreachable
}

; Function Attrs: noreturn
declare void @rb_raise(i64, i8*, ...) local_unnamed_addr #1

; Function Attrs: nounwind ssp uwtable
define weak i32 @sorbet_getIsReleaseBuild() local_unnamed_addr #0 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !4
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* getelementptr inbounds ([93 x i8], [93 x i8]* @.str.2, i64 0, i64 0)) #17
  unreachable
}

declare i64 @rb_fstring_new(i8*, i64) local_unnamed_addr #2

declare void @rb_gc_register_mark_object(i64) local_unnamed_addr #2

declare i64 @rb_intern2(i8*, i64) local_unnamed_addr #2

declare i64 @rb_id2sym(i64) local_unnamed_addr #2

; Function Attrs: noinline nounwind ssp uwtable
declare i64 @sorbet_getConstant(i8*, i64) local_unnamed_addr #3

declare i64 @rb_define_module(i8*) local_unnamed_addr #2

declare void @rb_define_singleton_method(i64, i8*, i64 (...)*, i32) local_unnamed_addr #2

; Function Attrs: cold noreturn nounwind optsize ssp uwtable
declare void @sorbet_cast_failure(i64, i8*, i8*) local_unnamed_addr #4

; Function Attrs: noreturn nounwind ssp uwtable
declare void @sorbet_raiseArity(i32, i32, i32) local_unnamed_addr #5

; Function Attrs: noreturn
declare void @rb_exc_raise(i64) local_unnamed_addr #1

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #6

declare i64 @rb_funcallv(i64, i64, i32, i64*) local_unnamed_addr #2

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.end.p0i8(i64 immarg, i8* nocapture) #6

; Function Attrs: nounwind ssp uwtable
declare i8* @sorbet_allocateRubyStackFrame(i64, i64, i64, i64, i8*, i32, i32, i32, i64* nocapture readonly, i32) local_unnamed_addr #0

declare i64 @rb_gv_get(i8*) local_unnamed_addr #2

declare i64 @rb_gv_set(i8*, i64) local_unnamed_addr #2

; Function Attrs: noinline nounwind ssp uwtable
define internal fastcc void @vm_env_write_slowpath(i64* nocapture, i32, i64) unnamed_addr #3 {
  %4 = getelementptr inbounds i64, i64* %0, i64 1
  %5 = load i64, i64* %4, align 8, !tbaa !4
  tail call void @rb_gc_writebarrier_remember(i64 %5) #16
  %6 = sext i32 %1 to i64
  %7 = getelementptr inbounds i64, i64* %0, i64 %6
  store i64 %2, i64* %7, align 8, !tbaa !4
  %8 = load i64, i64* %0, align 8, !tbaa !4
  %9 = and i64 %8, -9
  store i64 %9, i64* %0, align 8, !tbaa !4
  ret void
}

declare void @rb_gc_writebarrier_remember(i64) local_unnamed_addr #2

; Function Attrs: noinline nounwind ssp uwtable
declare void @sorbet_setExceptionStackFrame(%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct* nocapture readonly, %struct.rb_iseq_struct*) local_unnamed_addr #3

declare i64 @rb_errinfo() local_unnamed_addr #2

; Function Attrs: noinline nounwind ssp uwtable
declare void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* nocapture readnone, %struct.rb_control_frame_struct*, %struct.rb_iseq_struct* nocapture readonly) local_unnamed_addr #3

declare void @rb_vm_pop_frame(%struct.rb_execution_context_struct*) local_unnamed_addr #2

; Function Attrs: nounwind readnone
declare i64 @rb_obj_is_kind_of(i64, i64) local_unnamed_addr #7

; Function Attrs: nounwind readnone
declare i64 @rb_class_inherited_p(i64, i64) local_unnamed_addr #7

declare i64 @rb_str_concat_literals(i32, i64*) local_unnamed_addr #2

declare i64 @rb_obj_as_string_result(i64, i64) local_unnamed_addr #2

; Function Attrs: alwaysinline norecurse nounwind readonly ssp uwtable
declare i64 @sorbet_getConstantEpoch() local_unnamed_addr #8

; Function Attrs: noinline nounwind ssp uwtable
declare i64 @sorbet_callFuncWithCache(i64, i64, i32, i64* noalias nocapture, %struct.FunctionInlineCache* nocapture) local_unnamed_addr #3

declare void @rb_set_errinfo(i64) local_unnamed_addr #2

; Function Attrs: nounwind ssp uwtable
define internal i64 @sorbet_applyExceptionClosure(i64) #0 {
  %2 = inttoptr i64 %0 to %struct.ExceptionClosure*
  %3 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %2, i64 0, i32 0
  %4 = load i64 (i64**, i64*, i64)*, i64 (i64**, i64*, i64)** %3, align 8, !tbaa !8
  %5 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %2, i64 0, i32 1
  %6 = load i64**, i64*** %5, align 8, !tbaa !11
  %7 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %2, i64 0, i32 2
  %8 = load i64*, i64** %7, align 8, !tbaa !12
  %9 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %2, i64 0, i32 3
  %10 = load i64, i64* %9, align 8, !tbaa !13
  %11 = tail call i64 %4(i64** %6, i64* %8, i64 %10) #16
  %12 = icmp eq i64 %11, 52
  br i1 %12, label %16, label %13

13:                                               ; preds = %1
  %14 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %2, i64 0, i32 4
  %15 = load i64*, i64** %14, align 8, !tbaa !14
  store i64 %11, i64* %15, align 8, !tbaa !4
  br label %16

16:                                               ; preds = %13, %1
  ret i64 52
}

; Function Attrs: nounwind ssp uwtable
define internal i64 @sorbet_rescueStoreException(i64) #0 {
  %2 = inttoptr i64 %0 to i64*
  %3 = tail call i64 @rb_errinfo() #16
  store i64 %3, i64* %2, align 8, !tbaa !4
  ret i64 52
}

declare i64 @rb_rescue2(i64 (...)*, i64, i64 (...)*, i64, ...) local_unnamed_addr #2

; Function Attrs: nounwind sspreq
define void @Init_t_must() local_unnamed_addr #9 {
entry:
  %callArgs.i = alloca [1 x i64], align 8
  %locals1.i12.i = alloca [6 x i64], align 8
  %locals1.i.i = alloca [5 x i64], align 8
  %0 = tail call i64 @rb_gv_get(i8* getelementptr inbounds ([24 x i8], [24 x i8]* @.str.17, i64 0, i64 0)) #16
  %1 = and i64 %0, 7
  %2 = icmp ne i64 %1, 0
  %3 = and i64 %0, -9
  %4 = icmp eq i64 %3, 0
  %5 = or i1 %2, %4
  br i1 %5, label %12, label %6

6:                                                ; preds = %entry
  %7 = inttoptr i64 %0 to %struct.RBasic*
  %8 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %7, i64 0, i32 0
  %9 = load i64, i64* %8, align 8, !tbaa !15
  %10 = and i64 %9, 31
  %11 = icmp eq i64 %10, 5
  br i1 %11, label %sorbet_readRealpath.exit, label %12

12:                                               ; preds = %6, %entry
  %13 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !4
  tail call void (i64, i8*, ...) @rb_raise(i64 %13, i8* getelementptr inbounds ([63 x i8], [63 x i8]* @.str.18, i64 0, i64 0)) #17
  unreachable

sorbet_readRealpath.exit:                         ; preds = %6
  %14 = tail call i64 @rb_gv_set(i8* getelementptr inbounds ([24 x i8], [24 x i8]* @.str.17, i64 0, i64 0), i64 8) #16
  %15 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 16) #16
  store i64 %15, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %16 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([15 x i8], [15 x i8]* @str_test_known_nil, i64 0, i64 0), i64 14) #16
  store i64 %16, i64* @rubyIdPrecomputed_test_known_nil, align 8
  %17 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([17 x i8], [17 x i8]* @str_test_nilable_arg, i64 0, i64 0), i64 16) #16
  store i64 %17, i64* @rubyIdPrecomputed_test_nilable_arg, align 8
  %18 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<exceptionValue>", i64 0, i64 0), i64 16) #16
  store i64 %18, i64* @"rubyIdPrecomputed_<exceptionValue>", align 8
  %19 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([8 x i8], [8 x i8]* @"str_<magic>", i64 0, i64 0), i64 7) #16
  store i64 %19, i64* @"rubyIdPrecomputed_<magic>", align 8
  %20 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([19 x i8], [19 x i8]* @"str_<returnMethodTemp>", i64 0, i64 0), i64 18) #16
  store i64 %20, i64* @"rubyIdPrecomputed_<returnMethodTemp>", align 8
  %21 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([7 x i8], [7 x i8]* @"str_<self>", i64 0, i64 0), i64 6) #16
  store i64 %21, i64* @"rubyIdPrecomputed_<self>", align 8
  %22 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([15 x i8], [15 x i8]* @"str_<gotoDeadTemp>", i64 0, i64 0), i64 14) #16
  store i64 %22, i64* @"rubyIdPrecomputed_<gotoDeadTemp>", align 8
  %23 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([11 x i8], [11 x i8]* @"str_rescue for", i64 0, i64 0), i64 10) #16
  store i64 %23, i64* @"rubyIdPrecomputed_rescue for", align 8
  %24 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([11 x i8], [11 x i8]* @"str_ensure for", i64 0, i64 0), i64 10) #16
  store i64 %24, i64* @"rubyIdPrecomputed_ensure for", align 8
  %25 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_must, i64 0, i64 0), i64 4) #16
  %26 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([6 x i8], [6 x i8]* @"str_is_a?", i64 0, i64 0), i64 5) #16
  store i64 %26, i64* @"rubyIdPrecomputed_is_a?", align 8
  %27 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_puts, i64 0, i64 0), i64 4) #16
  store i64 %27, i64* @rubyIdPrecomputed_puts, align 8
  %28 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_arg, i64 0, i64 0), i64 3) #16
  store i64 %28, i64* @rubyIdPrecomputed_arg, align 8
  %29 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([21 x i8], [21 x i8]* @"str_<string-interpolate>", i64 0, i64 0), i64 20) #16
  %30 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([14 x i8], [14 x i8]* @str_keep_self_def, i64 0, i64 0), i64 13) #16
  %31 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 16) #16
  tail call void @rb_gc_register_mark_object(i64 %31) #16
  store i64 %31, i64* @"rubyStrFrozen_<top (required)>", align 8
  %32 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([44 x i8], [44 x i8]* @"str_test/testdata/compiler/intrinsics/t_must.rb", i64 0, i64 0), i64 43) #16
  tail call void @rb_gc_register_mark_object(i64 %32) #16
  store i64 %32, i64* @"rubyStrFrozen_test/testdata/compiler/intrinsics/t_must.rb", align 8
  %"rubyId_<top (required)>.i.i" = load i64, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %"rubyStr_<top (required)>.i.i" = load i64, i64* @"rubyStrFrozen_<top (required)>", align 8
  %33 = tail call i8* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_<top (required)>.i.i", i64 %"rubyId_<top (required)>.i.i", i64 %32, i64 %0, i8* null, i32 1, i32 1, i32 27, i64* getelementptr inbounds ([0 x i64], [0 x i64]* @"<static-init-locals-storage>.7", i64 0, i64 0), i32 0) #16
  store i8* %33, i8** @"stackFramePrecomputed_func_<root>.<static-init>$153", align 8
  %34 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([15 x i8], [15 x i8]* @str_test_known_nil, i64 0, i64 0), i64 14) #16
  tail call void @rb_gc_register_mark_object(i64 %34) #16
  %35 = bitcast [5 x i64]* %locals1.i.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 40, i8* nonnull %35) #16
  %rubyId_test_known_nil.i.i = load i64, i64* @rubyIdPrecomputed_test_known_nil, align 8
  %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i2.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/intrinsics/t_must.rb", align 8
  %"rubyId_<exceptionValue>.i.i" = load i64, i64* @"rubyIdPrecomputed_<exceptionValue>", align 8
  %"rubyId_<magic>.i.i" = load i64, i64* @"rubyIdPrecomputed_<magic>", align 8
  %"rubyId_<returnMethodTemp>.i.i" = load i64, i64* @"rubyIdPrecomputed_<returnMethodTemp>", align 8
  %"rubyId_<self>.i.i" = load i64, i64* @"rubyIdPrecomputed_<self>", align 8
  %"rubyId_<gotoDeadTemp>.i.i" = load i64, i64* @"rubyIdPrecomputed_<gotoDeadTemp>", align 8
  %locals1.sub.i.i = getelementptr inbounds [5 x i64], [5 x i64]* %locals1.i.i, i64 0, i64 0
  store i64 %"rubyId_<exceptionValue>.i.i", i64* %locals1.sub.i.i, align 8
  %36 = getelementptr inbounds [5 x i64], [5 x i64]* %locals1.i.i, i64 0, i64 1
  store i64 %"rubyId_<magic>.i.i", i64* %36, align 8
  %37 = getelementptr inbounds [5 x i64], [5 x i64]* %locals1.i.i, i64 0, i64 2
  store i64 %"rubyId_<returnMethodTemp>.i.i", i64* %37, align 8
  %38 = getelementptr inbounds [5 x i64], [5 x i64]* %locals1.i.i, i64 0, i64 3
  store i64 %"rubyId_<self>.i.i", i64* %38, align 8
  %39 = getelementptr inbounds [5 x i64], [5 x i64]* %locals1.i.i, i64 0, i64 4
  store i64 %"rubyId_<gotoDeadTemp>.i.i", i64* %39, align 8
  %40 = call i8* @sorbet_allocateRubyStackFrame(i64 %34, i64 %rubyId_test_known_nil.i.i, i64 %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i2.i", i64 %0, i8* null, i32 1, i32 6, i32 12, i64* nonnull %locals1.sub.i.i, i32 5) #16
  store i8* %40, i8** @stackFramePrecomputed_func_Test.test_known_nil, align 8
  call void @llvm.lifetime.end.p0i8(i64 40, i8* nonnull %35) #16
  %41 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([11 x i8], [11 x i8]* @"str_rescue for", i64 0, i64 0), i64 10) #16
  tail call void @rb_gc_register_mark_object(i64 %41) #16
  store i64 %41, i64* @"rubyStrFrozen_rescue for", align 8
  %stackFrame_func_Test.test_known_nil.i.i = load i8*, i8** @stackFramePrecomputed_func_Test.test_known_nil, align 8
  %"rubyId_rescue for.i.i" = load i64, i64* @"rubyIdPrecomputed_rescue for", align 8
  %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i3.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/intrinsics/t_must.rb", align 8
  %42 = tail call i8* @sorbet_allocateRubyStackFrame(i64 %41, i64 %"rubyId_rescue for.i.i", i64 %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i3.i", i64 %0, i8* %stackFrame_func_Test.test_known_nil.i.i, i32 4, i32 6, i32 12, i64* null, i32 0) #16
  store i8* %42, i8** @"stackFramePrecomputed_func_Test.test_known_nil$block_2", align 8
  %43 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([11 x i8], [11 x i8]* @"str_ensure for", i64 0, i64 0), i64 10) #16
  tail call void @rb_gc_register_mark_object(i64 %43) #16
  store i64 %43, i64* @"rubyStrFrozen_ensure for", align 8
  %stackFrame_func_Test.test_known_nil.i4.i = load i8*, i8** @stackFramePrecomputed_func_Test.test_known_nil, align 8
  %"rubyId_ensure for.i.i" = load i64, i64* @"rubyIdPrecomputed_ensure for", align 8
  %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i5.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/intrinsics/t_must.rb", align 8
  %44 = tail call i8* @sorbet_allocateRubyStackFrame(i64 %43, i64 %"rubyId_ensure for.i.i", i64 %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i5.i", i64 %0, i8* %stackFrame_func_Test.test_known_nil.i4.i, i32 5, i32 6, i32 12, i64* null, i32 0) #16
  store i8* %44, i8** @"stackFramePrecomputed_func_Test.test_known_nil$block_3", align 8
  %45 = tail call i64 @sorbet_getConstant(i8* getelementptr inbounds ([25 x i8], [25 x i8]* @.str.24, i64 0, i64 0), i64 24) #16
  store i64 %45, i64* @"<retry-singleton>", align 8
  %46 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([17 x i8], [17 x i8]* @str_test_nilable_arg, i64 0, i64 0), i64 16) #16
  tail call void @rb_gc_register_mark_object(i64 %46) #16
  %47 = bitcast [6 x i64]* %locals1.i12.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 48, i8* nonnull %47) #16
  %rubyId_test_nilable_arg.i.i = load i64, i64* @rubyIdPrecomputed_test_nilable_arg, align 8
  %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i6.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/intrinsics/t_must.rb", align 8
  %"rubyId_<exceptionValue>.i7.i" = load i64, i64* @"rubyIdPrecomputed_<exceptionValue>", align 8
  %rubyId_arg.i.i = load i64, i64* @rubyIdPrecomputed_arg, align 8
  %"rubyId_<self>.i8.i" = load i64, i64* @"rubyIdPrecomputed_<self>", align 8
  %"rubyId_<magic>.i9.i" = load i64, i64* @"rubyIdPrecomputed_<magic>", align 8
  %"rubyId_<returnMethodTemp>.i10.i" = load i64, i64* @"rubyIdPrecomputed_<returnMethodTemp>", align 8
  %"rubyId_<gotoDeadTemp>.i11.i" = load i64, i64* @"rubyIdPrecomputed_<gotoDeadTemp>", align 8
  %locals1.sub.i13.i = getelementptr inbounds [6 x i64], [6 x i64]* %locals1.i12.i, i64 0, i64 0
  store i64 %"rubyId_<exceptionValue>.i7.i", i64* %locals1.sub.i13.i, align 8
  %48 = getelementptr inbounds [6 x i64], [6 x i64]* %locals1.i12.i, i64 0, i64 1
  store i64 %rubyId_arg.i.i, i64* %48, align 8
  %49 = getelementptr inbounds [6 x i64], [6 x i64]* %locals1.i12.i, i64 0, i64 2
  store i64 %"rubyId_<self>.i8.i", i64* %49, align 8
  %50 = getelementptr inbounds [6 x i64], [6 x i64]* %locals1.i12.i, i64 0, i64 3
  store i64 %"rubyId_<magic>.i9.i", i64* %50, align 8
  %51 = getelementptr inbounds [6 x i64], [6 x i64]* %locals1.i12.i, i64 0, i64 4
  store i64 %"rubyId_<returnMethodTemp>.i10.i", i64* %51, align 8
  %52 = getelementptr inbounds [6 x i64], [6 x i64]* %locals1.i12.i, i64 0, i64 5
  store i64 %"rubyId_<gotoDeadTemp>.i11.i", i64* %52, align 8
  %53 = call i8* @sorbet_allocateRubyStackFrame(i64 %46, i64 %rubyId_test_nilable_arg.i.i, i64 %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i6.i", i64 %0, i8* null, i32 1, i32 14, i32 21, i64* nonnull %locals1.sub.i13.i, i32 6) #16
  store i8* %53, i8** @stackFramePrecomputed_func_Test.test_nilable_arg, align 8
  call void @llvm.lifetime.end.p0i8(i64 48, i8* nonnull %47) #16
  %"rubyId_rescue for.i14.i" = load i64, i64* @"rubyIdPrecomputed_rescue for", align 8
  %"rubyStr_rescue for.i15.i" = load i64, i64* @"rubyStrFrozen_rescue for", align 8
  %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i16.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/intrinsics/t_must.rb", align 8
  %54 = tail call i8* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_rescue for.i15.i", i64 %"rubyId_rescue for.i14.i", i64 %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i16.i", i64 %0, i8* %53, i32 4, i32 14, i32 21, i64* null, i32 0) #16
  store i8* %54, i8** @"stackFramePrecomputed_func_Test.test_nilable_arg$block_2", align 8
  %stackFrame_func_Test.test_nilable_arg.i17.i = load i8*, i8** @stackFramePrecomputed_func_Test.test_nilable_arg, align 8
  %"rubyId_ensure for.i18.i" = load i64, i64* @"rubyIdPrecomputed_ensure for", align 8
  %"rubyStr_ensure for.i19.i" = load i64, i64* @"rubyStrFrozen_ensure for", align 8
  %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i20.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/intrinsics/t_must.rb", align 8
  %55 = tail call i8* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_ensure for.i19.i", i64 %"rubyId_ensure for.i18.i", i64 %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i20.i", i64 %0, i8* %stackFrame_func_Test.test_nilable_arg.i17.i, i32 5, i32 14, i32 21, i64* null, i32 0) #16
  store i8* %55, i8** @"stackFramePrecomputed_func_Test.test_nilable_arg$block_3", align 8
  %56 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([12 x i8], [12 x i8]* @"str_ wasn't nil", i64 0, i64 0), i64 11) #16
  tail call void @rb_gc_register_mark_object(i64 %56) #16
  store i64 %56, i64* @"rubyStrFrozen_ wasn't nil", align 8
  %"rubyId_<top (required)>.i21.i" = load i64, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %"rubyStr_<top (required)>.i22.i" = load i64, i64* @"rubyStrFrozen_<top (required)>", align 8
  %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i23.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/intrinsics/t_must.rb", align 8
  %57 = tail call i8* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_<top (required)>.i22.i", i64 %"rubyId_<top (required)>.i21.i", i64 %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i23.i", i64 %0, i8* null, i32 1, i32 1, i32 5, i64* null, i32 0) #16
  store i8* %57, i8** @"stackFramePrecomputed_func_Test.<static-init>", align 8
  %58 = load %struct.rb_vm_struct*, %struct.rb_vm_struct** @ruby_current_vm_ptr, align 8, !tbaa !17
  %59 = getelementptr inbounds %struct.rb_vm_struct, %struct.rb_vm_struct* %58, i64 0, i32 17
  %60 = load i64, i64* %59, align 8, !tbaa !18
  %61 = bitcast [1 x i64]* %callArgs.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %61)
  %"stackFrame_func_<root>.<static-init>$153.i" = load i8*, i8** @"stackFramePrecomputed_func_<root>.<static-init>$153", align 8
  %62 = bitcast i8* %"stackFrame_func_<root>.<static-init>$153.i" to %struct.rb_iseq_struct*
  %63 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !17
  %64 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %63, i64 0, i32 2
  %65 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %64, align 8, !tbaa !28
  %66 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %65, i64 0, i32 2
  %67 = bitcast %struct.rb_iseq_struct** %66 to i8**
  store i8* %"stackFrame_func_<root>.<static-init>$153.i", i8** %67, align 8, !tbaa !31
  %68 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %65, i64 0, i32 4
  %69 = load i64*, i64** %68, align 8, !tbaa !33
  %70 = load i64, i64* %69, align 8, !tbaa !4
  %71 = and i64 %70, -129
  store i64 %71, i64* %69, align 8, !tbaa !4
  tail call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* undef, %struct.rb_control_frame_struct* nonnull %65, %struct.rb_iseq_struct* %62) #16
  %72 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %65, i64 0, i32 0
  %73 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %66, align 8, !tbaa !31
  %74 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %73, i64 0, i32 2
  %75 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %74, align 8, !tbaa !34
  %76 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %75, i64 0, i32 2
  %77 = load i64*, i64** %76, align 8, !tbaa !36
  %78 = getelementptr inbounds i64, i64* %77, i64 5
  store i64* %78, i64** %72, align 8, !tbaa !17
  %rubyId_test_nilable_arg.i = load i64, i64* @rubyIdPrecomputed_test_nilable_arg, align 8, !dbg !45
  %79 = load %struct.rb_vm_struct*, %struct.rb_vm_struct** @ruby_current_vm_ptr, align 8, !dbg !50, !tbaa !17
  %80 = getelementptr inbounds %struct.rb_vm_struct, %struct.rb_vm_struct* %79, i64 0, i32 17, !dbg !50
  %81 = load i64, i64* %80, align 8, !dbg !50, !tbaa !18
  %82 = icmp eq i64 %81, %60, !dbg !50
  br i1 %82, label %"func_<root>.<static-init>$153.exit", label %codeRepl, !dbg !50, !prof !51

codeRepl:                                         ; preds = %sorbet_readRealpath.exit
  tail call fastcc void @Init_t_must.cold.1(i64 %60) #18
  unreachable

"func_<root>.<static-init>$153.exit":             ; preds = %sorbet_readRealpath.exit
  %rubyId_test_known_nil.i = load i64, i64* @rubyIdPrecomputed_test_known_nil, align 8, !dbg !52
  %83 = tail call i64 @rb_define_module(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_Test, i64 0, i64 0)) #16, !dbg !50
  %84 = load i64, i64* @guard_epoch_Test, align 8, !dbg !50
  %85 = tail call i64 @sorbet_getConstantEpoch(), !dbg !50
  %needTakeSlowPath = icmp eq i64 %84, %85, !dbg !50
  br i1 %needTakeSlowPath, label %87, label %86, !dbg !50, !prof !53

86:                                               ; preds = %"func_<root>.<static-init>$153.exit"
  tail call void @const_recompute_Test() #16, !dbg !50
  br label %87, !dbg !50

87:                                               ; preds = %"func_<root>.<static-init>$153.exit", %86
  %88 = load i64, i64* @guarded_const_Test, align 8, !dbg !50
  %89 = load i64, i64* @guard_epoch_Test, align 8, !dbg !50
  %90 = tail call i64 @sorbet_getConstantEpoch(), !dbg !50
  %guardUpdated = icmp eq i64 %89, %90, !dbg !50
  tail call void @llvm.assume(i1 %guardUpdated), !dbg !50
  %91 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !17
  %92 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %91, i64 0, i32 2
  %93 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %92, align 8, !tbaa !28
  %94 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %93, i64 0, i32 0
  %95 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %93, i64 0, i32 2
  %96 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %95, align 8, !tbaa !31
  %97 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %96, i64 0, i32 2
  %98 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %97, align 8, !tbaa !34
  %99 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %98, i64 0, i32 2
  %100 = load i64*, i64** %99, align 8, !tbaa !36
  %rubyId_test_known_nil.i.i1 = load i64, i64* @rubyIdPrecomputed_test_known_nil, align 8, !dbg !54
  %rubyId_test_nilable_arg.i.i2 = load i64, i64* @rubyIdPrecomputed_test_nilable_arg, align 8, !dbg !57
  %101 = getelementptr inbounds i64, i64* %100, i64 6, !dbg !58
  store i64* %101, i64** %94, align 8, !dbg !58, !tbaa !17
  %rawSym.i.i = tail call i64 @rb_id2sym(i64 %rubyId_test_known_nil.i.i1) #16, !dbg !54
  tail call void @rb_define_singleton_method(i64 %88, i8* getelementptr inbounds ([15 x i8], [15 x i8]* @str_test_known_nil, i64 0, i64 0), i64 (...)* bitcast (i64 (i32, i64*, i64)* @func_Test.test_known_nil to i64 (...)*), i32 -1) #16, !dbg !54
  %102 = getelementptr inbounds i64, i64* %100, i64 14, !dbg !54
  store i64* %102, i64** %94, align 8, !dbg !54, !tbaa !17
  %rawSym17.i.i = tail call i64 @rb_id2sym(i64 %rubyId_test_nilable_arg.i.i2) #16, !dbg !57
  tail call void @rb_define_singleton_method(i64 %88, i8* getelementptr inbounds ([17 x i8], [17 x i8]* @str_test_nilable_arg, i64 0, i64 0), i64 (...)* bitcast (i64 (i32, i64*, i64)* @func_Test.test_nilable_arg to i64 (...)*), i32 -1) #16, !dbg !57
  %103 = getelementptr inbounds i64, i64* %77, i64 24
  store i64* %103, i64** %72, align 8, !tbaa !17
  %callFunc_test_known_nil.i = tail call i64 @sorbet_callFuncWithCache(i64 %88, i64 %rubyId_test_known_nil.i, i32 0, i64* null, %struct.FunctionInlineCache* nonnull @ic_callFunc_test_known_nil) #16, !dbg !52
  %104 = getelementptr inbounds i64, i64* %77, i64 25, !dbg !52
  store i64* %104, i64** %72, align 8, !dbg !52, !tbaa !17
  %callArgs0Addr.i = getelementptr inbounds [1 x i64], [1 x i64]* %callArgs.i, i64 0, i64 0, !dbg !45
  store i64 21, i64* %callArgs0Addr.i, align 8, !dbg !45
  %callFunc_test_nilable_arg.i = call i64 @sorbet_callFuncWithCache(i64 %88, i64 %rubyId_test_nilable_arg.i, i32 1, i64* nonnull %callArgs0Addr.i, %struct.FunctionInlineCache* nonnull @ic_callFunc_test_nilable_arg) #16, !dbg !45
  %105 = getelementptr inbounds i64, i64* %77, i64 26, !dbg !45
  store i64* %105, i64** %72, align 8, !dbg !45, !tbaa !17
  store i64 0, i64* %callArgs0Addr.i, align 8, !dbg !59
  %callFunc_test_nilable_arg47.i = call i64 @sorbet_callFuncWithCache(i64 %88, i64 %rubyId_test_nilable_arg.i, i32 1, i64* nonnull %callArgs0Addr.i, %struct.FunctionInlineCache* nonnull @ic_callFunc_test_nilable_arg.1) #16, !dbg !59
  %106 = getelementptr inbounds i64, i64* %77, i64 27, !dbg !59
  store i64* %106, i64** %72, align 8, !dbg !59, !tbaa !17
  store i64 8, i64* %callArgs0Addr.i, align 8, !dbg !60
  %callFunc_test_nilable_arg54.i = call i64 @sorbet_callFuncWithCache(i64 %88, i64 %rubyId_test_nilable_arg.i, i32 1, i64* nonnull %callArgs0Addr.i, %struct.FunctionInlineCache* nonnull @ic_callFunc_test_nilable_arg.2) #16, !dbg !60
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %61)
  ret void
}

; Function Attrs: nounwind sspreq uwtable
define i64 @func_Test.test_known_nil(i32 %argc, i64* nocapture readnone %argArray, i64 %selfRaw) #10 !dbg !61 {
functionEntryInitializers:
  %0 = alloca i64, align 8
  %1 = alloca %struct.ExceptionClosure, align 8
  %2 = alloca i64, align 8
  %3 = alloca %struct.ExceptionClosure, align 8
  %stackFrame_func_Test.test_known_nil = load i8*, i8** @stackFramePrecomputed_func_Test.test_known_nil, align 8
  %4 = bitcast i8* %stackFrame_func_Test.test_known_nil to %struct.rb_iseq_struct*
  %5 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !17
  %6 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %5, i64 0, i32 2
  %7 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %6, align 8, !tbaa !28
  %8 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %7, i64 0, i32 2
  %9 = bitcast %struct.rb_iseq_struct** %8 to i8**
  store i8* %stackFrame_func_Test.test_known_nil, i8** %9, align 8, !tbaa !31
  %10 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %7, i64 0, i32 4
  %11 = load i64*, i64** %10, align 8, !tbaa !33
  %12 = load i64, i64* %11, align 8, !tbaa !4
  %13 = and i64 %12, -129
  store i64 %13, i64* %11, align 8, !tbaa !4
  tail call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* undef, %struct.rb_control_frame_struct* nonnull %7, %struct.rb_iseq_struct* %4) #16
  %14 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %7, i64 0, i32 0
  %15 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %8, align 8, !tbaa !31
  %16 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %15, i64 0, i32 2
  %17 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %16, align 8, !tbaa !34
  %18 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %17, i64 0, i32 2
  %19 = load i64*, i64** %18, align 8, !tbaa !36
  %20 = getelementptr inbounds i64, i64* %19, i64 1
  store i64* %20, i64** %14, align 8, !tbaa !17
  %exceptionValue = alloca i64, align 8, !dbg !62
  %tooManyArgs = icmp eq i32 %argc, 0, !dbg !63
  br i1 %tooManyArgs, label %fillRequiredArgs, label %argCountFailBlock, !dbg !63, !prof !51

argCountFailBlock:                                ; preds = %functionEntryInitializers
  tail call void @sorbet_raiseArity(i32 %argc, i32 0, i32 0), !dbg !63
  unreachable, !dbg !63

fillRequiredArgs:                                 ; preds = %functionEntryInitializers
  %21 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !63, !tbaa !17
  %22 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %21, i64 0, i32 2, !dbg !63
  %23 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %22, align 8, !dbg !63, !tbaa !28
  %24 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %23, i64 0, i32 4, !dbg !63
  %25 = load i64*, i64** %24, align 8, !dbg !63, !tbaa !33
  %26 = load i64, i64* %25, align 8, !dbg !63, !tbaa !4
  %27 = and i64 %26, 8, !dbg !63
  %28 = icmp eq i64 %27, 0, !dbg !63
  br i1 %28, label %29, label %31, !dbg !63, !prof !51

29:                                               ; preds = %fillRequiredArgs
  %30 = getelementptr inbounds i64, i64* %25, i64 -6, !dbg !63
  store i64 %selfRaw, i64* %30, align 8, !dbg !63, !tbaa !4
  br label %sorbet_writeLocal.exit, !dbg !63

31:                                               ; preds = %fillRequiredArgs
  tail call fastcc void @vm_env_write_slowpath(i64* nonnull %25, i32 -6, i64 %selfRaw) #16, !dbg !63
  br label %sorbet_writeLocal.exit, !dbg !63

sorbet_writeLocal.exit:                           ; preds = %29, %31
  store i64* %20, i64** %14, align 8, !tbaa !17
  %32 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !63, !tbaa !17
  %33 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %32, i64 0, i32 2, !dbg !63
  %34 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %33, align 8, !dbg !63, !tbaa !28
  %35 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %34, i64 0, i32 4, !dbg !63
  %36 = load i64*, i64** %35, align 8, !dbg !63, !tbaa !33
  %37 = getelementptr inbounds i64, i64* %36, i64 -6, !dbg !63
  %38 = load i64, i64* %37, align 8, !dbg !63, !tbaa !4
  %39 = load i64, i64* @guard_epoch_Test, align 8, !dbg !63
  %40 = tail call i64 @sorbet_getConstantEpoch(), !dbg !63
  %needTakeSlowPath = icmp eq i64 %39, %40, !dbg !63
  br i1 %needTakeSlowPath, label %42, label %41, !dbg !63, !prof !53

41:                                               ; preds = %sorbet_writeLocal.exit
  tail call void @const_recompute_Test() #16, !dbg !63
  br label %42, !dbg !63

42:                                               ; preds = %sorbet_writeLocal.exit, %41
  %43 = load i64, i64* @guarded_const_Test, align 8, !dbg !63
  %44 = load i64, i64* @guard_epoch_Test, align 8, !dbg !63
  %45 = tail call i64 @sorbet_getConstantEpoch(), !dbg !63
  %guardUpdated = icmp eq i64 %44, %45, !dbg !63
  tail call void @llvm.assume(i1 %guardUpdated), !dbg !63
  %46 = icmp eq i64 %38, %43, !dbg !63
  br i1 %46, label %typeTestSuccess, label %47, !dbg !63

47:                                               ; preds = %42
  %48 = load i64, i64* @rb_cModule, align 8, !dbg !63, !tbaa !4
  %49 = tail call i64 @rb_obj_is_kind_of(i64 %38, i64 %48) #7, !dbg !63
  %50 = icmp eq i64 %49, 0, !dbg !63
  br i1 %50, label %codeRepl, label %sorbet_isa_class_of.exit, !dbg !63, !prof !64

sorbet_isa_class_of.exit:                         ; preds = %47
  %51 = tail call i64 @rb_class_inherited_p(i64 %38, i64 %43) #7, !dbg !63
  %52 = icmp eq i64 %51, 0, !dbg !63
  br i1 %52, label %codeRepl, label %typeTestSuccess, !dbg !63, !prof !65

typeTestSuccess:                                  ; preds = %sorbet_isa_class_of.exit, %42
  %53 = load i64, i64* %36, align 8, !dbg !63, !tbaa !4
  %54 = and i64 %53, 8, !dbg !63
  %55 = icmp eq i64 %54, 0, !dbg !63
  br i1 %55, label %sorbet_writeLocal.exit28, label %56, !dbg !63, !prof !51

56:                                               ; preds = %typeTestSuccess
  tail call fastcc void @vm_env_write_slowpath(i64* nonnull %36, i32 -6, i64 %38) #16, !dbg !63
  br label %sorbet_writeLocal.exit28, !dbg !63

sorbet_writeLocal.exit28:                         ; preds = %typeTestSuccess, %56
  %57 = getelementptr inbounds i64, i64* %19, i64 3
  store i64* %57, i64** %14, align 8, !tbaa !17
  %previousException = tail call i64 @rb_errinfo() #16, !dbg !62
  %58 = bitcast i64* %0 to i8*, !dbg !66
  %59 = bitcast %struct.ExceptionClosure* %1 to i8*, !dbg !66
  %60 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %1, i64 0, i32 0, !dbg !66
  %61 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %1, i64 0, i32 1, !dbg !66
  %62 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %1, i64 0, i32 2, !dbg !66
  %63 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %1, i64 0, i32 3, !dbg !66
  %64 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %1, i64 0, i32 4, !dbg !66
  %65 = icmp eq i64 %previousException, 8, !dbg !66
  %66 = ptrtoint %struct.ExceptionClosure* %1 to i64, !dbg !66
  %67 = ptrtoint i64* %exceptionValue to i64, !dbg !66
  %68 = bitcast i64* %2 to i8*, !dbg !66
  %69 = bitcast %struct.ExceptionClosure* %3 to i8*, !dbg !66
  %70 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %3, i64 0, i32 0, !dbg !66
  %71 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %3, i64 0, i32 1, !dbg !66
  %72 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %3, i64 0, i32 2, !dbg !66
  %73 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %3, i64 0, i32 3, !dbg !66
  %74 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %3, i64 0, i32 4, !dbg !66
  %75 = ptrtoint %struct.ExceptionClosure* %3 to i64, !dbg !66
  br i1 %65, label %exception-entry.us, label %exception-entry, !dbg !62

exception-entry.us:                               ; preds = %sorbet_writeLocal.exit28, %sorbet_try.exit.us
  %76 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !62, !tbaa !17
  %77 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %76, i64 0, i32 2, !dbg !62
  %78 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %77, align 8, !dbg !62, !tbaa !28
  %79 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %78, i64 0, i32 4, !dbg !62
  %80 = load i64*, i64** %79, align 8, !dbg !62, !tbaa !33
  %81 = load i64, i64* %80, align 8, !dbg !62, !tbaa !4
  %82 = and i64 %81, 8, !dbg !62
  %83 = icmp eq i64 %82, 0, !dbg !62
  br i1 %83, label %85, label %84, !dbg !62, !prof !51

84:                                               ; preds = %exception-entry.us
  call fastcc void @vm_env_write_slowpath(i64* nonnull %80, i32 -3, i64 8) #16, !dbg !62
  br label %sorbet_writeLocal.exit29.us, !dbg !62

85:                                               ; preds = %exception-entry.us
  %86 = getelementptr inbounds i64, i64* %80, i64 -3, !dbg !62
  store i64 8, i64* %86, align 8, !dbg !62, !tbaa !4
  br label %sorbet_writeLocal.exit29.us, !dbg !62

sorbet_writeLocal.exit29.us:                      ; preds = %85, %84
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %58) #16, !dbg !62
  store i64 52, i64* %0, align 8, !dbg !62, !tbaa !4
  call void @llvm.lifetime.start.p0i8(i64 40, i8* nonnull %59) #16, !dbg !62
  store i64 (i64**, i64*, i64)* @"func_Test.test_known_nil$block_1", i64 (i64**, i64*, i64)** %60, align 8, !dbg !62, !tbaa !8
  store i64** %14, i64*** %61, align 8, !dbg !62, !tbaa !11
  store i64* %19, i64** %62, align 8, !dbg !62, !tbaa !12
  store i64 0, i64* %63, align 8, !dbg !62, !tbaa !13
  store i64* %0, i64** %64, align 8, !dbg !62, !tbaa !14
  store i64 8, i64* %exceptionValue, align 8, !dbg !62, !tbaa !4
  %87 = load i64, i64* @rb_eException, align 8, !dbg !62, !tbaa !4
  %88 = call i64 (i64 (...)*, i64, i64 (...)*, i64, ...) @rb_rescue2(i64 (...)* bitcast (i64 (i64)* @sorbet_applyExceptionClosure to i64 (...)*), i64 %66, i64 (...)* bitcast (i64 (i64)* @sorbet_rescueStoreException to i64 (...)*), i64 %67, i64 %87, i32 0) #16, !dbg !62
  %89 = load i64, i64* %0, align 8, !dbg !62
  call void @llvm.lifetime.end.p0i8(i64 40, i8* nonnull %59) #16, !dbg !62
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %58) #16, !dbg !62
  %isReturnValue.us = icmp eq i64 %89, 52, !dbg !62
  br i1 %isReturnValue.us, label %exception-body-continue.us, label %exception-body-return, !dbg !62

exception-body-continue.us:                       ; preds = %sorbet_writeLocal.exit29.us
  %90 = load i64, i64* %exceptionValue, align 8, !dbg !62
  %91 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !62, !tbaa !17
  %92 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %91, i64 0, i32 2, !dbg !62
  %93 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %92, align 8, !dbg !62, !tbaa !28
  %94 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %93, i64 0, i32 4, !dbg !62
  %95 = load i64*, i64** %94, align 8, !dbg !62, !tbaa !33
  %96 = load i64, i64* %95, align 8, !dbg !62, !tbaa !4
  %97 = and i64 %96, 8, !dbg !62
  %98 = icmp eq i64 %97, 0, !dbg !62
  br i1 %98, label %100, label %99, !dbg !62, !prof !51

99:                                               ; preds = %exception-body-continue.us
  call fastcc void @vm_env_write_slowpath(i64* nonnull %95, i32 -3, i64 %90) #16, !dbg !62
  br label %sorbet_writeLocal.exit30.us, !dbg !62

100:                                              ; preds = %exception-body-continue.us
  %101 = getelementptr inbounds i64, i64* %95, i64 -3, !dbg !62
  store i64 %90, i64* %101, align 8, !dbg !62, !tbaa !4
  br label %sorbet_writeLocal.exit30.us, !dbg !62

sorbet_writeLocal.exit30.us:                      ; preds = %100, %99
  %102 = icmp ne i64 %90, 8, !dbg !62
  %handler.us = select i1 %102, i64 (i64**, i64*, i64)* @"func_Test.test_known_nil$block_2", i64 (i64**, i64*, i64)* @"func_Test.test_known_nil$block_4", !dbg !62
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %68) #16, !dbg !62
  store i64 52, i64* %2, align 8, !dbg !62, !tbaa !4
  call void @llvm.lifetime.start.p0i8(i64 40, i8* nonnull %69) #16, !dbg !62
  store i64 (i64**, i64*, i64)* %handler.us, i64 (i64**, i64*, i64)** %70, align 8, !dbg !62, !tbaa !8
  store i64** %14, i64*** %71, align 8, !dbg !62, !tbaa !11
  store i64* %19, i64** %72, align 8, !dbg !62, !tbaa !12
  store i64 0, i64* %73, align 8, !dbg !62, !tbaa !13
  store i64* %2, i64** %74, align 8, !dbg !62, !tbaa !14
  store i64 8, i64* %exceptionValue, align 8, !dbg !62, !tbaa !4
  %103 = icmp eq i64 %90, 8, !dbg !62
  br i1 %103, label %sorbet_try.exit.us, label %104, !dbg !62

104:                                              ; preds = %sorbet_writeLocal.exit30.us
  call void @rb_set_errinfo(i64 %90) #16, !dbg !62
  br label %sorbet_try.exit.us, !dbg !62

sorbet_try.exit.us:                               ; preds = %104, %sorbet_writeLocal.exit30.us
  %105 = load i64, i64* @rb_eException, align 8, !dbg !62, !tbaa !4
  %106 = call i64 (i64 (...)*, i64, i64 (...)*, i64, ...) @rb_rescue2(i64 (...)* bitcast (i64 (i64)* @sorbet_applyExceptionClosure to i64 (...)*), i64 %75, i64 (...)* bitcast (i64 (i64)* @sorbet_rescueStoreException to i64 (...)*), i64 %67, i64 %105, i32 0) #16, !dbg !62
  %107 = load i64, i64* %2, align 8, !dbg !62
  call void @llvm.lifetime.end.p0i8(i64 40, i8* nonnull %69) #16, !dbg !62
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %68) #16, !dbg !62
  %108 = load i64, i64* %exceptionValue, align 8, !dbg !62
  %109 = icmp eq i64 %108, 8, !dbg !62
  %110 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !62, !tbaa !17
  %111 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %110, i64 0, i32 2, !dbg !62
  %112 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %111, align 8, !dbg !62, !tbaa !28
  %113 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %112, i64 0, i32 4, !dbg !62
  %114 = load i64*, i64** %113, align 8, !dbg !62, !tbaa !33
  %115 = getelementptr inbounds i64, i64* %114, i64 -3, !dbg !62
  %116 = load i64, i64* %115, align 8, !dbg !62, !tbaa !4
  %117 = select i1 %109, i64 %116, i64 %108, !dbg !62
  call void @rb_set_errinfo(i64 %117) #16, !dbg !62
  %"<retry-singleton>.us" = load i64, i64* @"<retry-singleton>", align 8, !dbg !62
  %shouldRetry.us = icmp eq i64 %107, %"<retry-singleton>.us", !dbg !62
  %118 = and i1 %102, %shouldRetry.us, !dbg !62
  br i1 %118, label %exception-entry.us, label %exception-ensure, !dbg !62

codeRepl:                                         ; preds = %47, %sorbet_isa_class_of.exit
  tail call fastcc void @func_Test.test_known_nil.cold.1(i64 %38) #18, !dbg !63
  unreachable

exception-entry:                                  ; preds = %sorbet_writeLocal.exit28, %sorbet_try.exit
  %119 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !62, !tbaa !17
  %120 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %119, i64 0, i32 2, !dbg !62
  %121 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %120, align 8, !dbg !62, !tbaa !28
  %122 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %121, i64 0, i32 4, !dbg !62
  %123 = load i64*, i64** %122, align 8, !dbg !62, !tbaa !33
  %124 = load i64, i64* %123, align 8, !dbg !62, !tbaa !4
  %125 = and i64 %124, 8, !dbg !62
  %126 = icmp eq i64 %125, 0, !dbg !62
  br i1 %126, label %127, label %129, !dbg !62, !prof !51

127:                                              ; preds = %exception-entry
  %128 = getelementptr inbounds i64, i64* %123, i64 -3, !dbg !62
  store i64 8, i64* %128, align 8, !dbg !62, !tbaa !4
  br label %sorbet_writeLocal.exit29, !dbg !62

129:                                              ; preds = %exception-entry
  call fastcc void @vm_env_write_slowpath(i64* nonnull %123, i32 -3, i64 8) #16, !dbg !62
  br label %sorbet_writeLocal.exit29, !dbg !62

sorbet_writeLocal.exit29:                         ; preds = %127, %129
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %58) #16, !dbg !62
  store i64 52, i64* %0, align 8, !dbg !62, !tbaa !4
  call void @llvm.lifetime.start.p0i8(i64 40, i8* nonnull %59) #16, !dbg !62
  store i64 (i64**, i64*, i64)* @"func_Test.test_known_nil$block_1", i64 (i64**, i64*, i64)** %60, align 8, !dbg !62, !tbaa !8
  store i64** %14, i64*** %61, align 8, !dbg !62, !tbaa !11
  store i64* %19, i64** %62, align 8, !dbg !62, !tbaa !12
  store i64 0, i64* %63, align 8, !dbg !62, !tbaa !13
  store i64* %0, i64** %64, align 8, !dbg !62, !tbaa !14
  store i64 8, i64* %exceptionValue, align 8, !dbg !62, !tbaa !4
  call void @rb_set_errinfo(i64 %previousException) #16, !dbg !62
  %130 = load i64, i64* @rb_eException, align 8, !dbg !62, !tbaa !4
  %131 = call i64 (i64 (...)*, i64, i64 (...)*, i64, ...) @rb_rescue2(i64 (...)* bitcast (i64 (i64)* @sorbet_applyExceptionClosure to i64 (...)*), i64 %66, i64 (...)* bitcast (i64 (i64)* @sorbet_rescueStoreException to i64 (...)*), i64 %67, i64 %130, i32 0) #16, !dbg !62
  %132 = load i64, i64* %0, align 8, !dbg !62
  call void @llvm.lifetime.end.p0i8(i64 40, i8* nonnull %59) #16, !dbg !62
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %58) #16, !dbg !62
  %isReturnValue = icmp eq i64 %132, 52, !dbg !62
  br i1 %isReturnValue, label %exception-body-continue, label %exception-body-return, !dbg !62

exception-body-return:                            ; preds = %sorbet_writeLocal.exit29, %sorbet_writeLocal.exit29.us
  %.lcssa = phi i64 [ %89, %sorbet_writeLocal.exit29.us ], [ %132, %sorbet_writeLocal.exit29 ], !dbg !62
  call void @rb_set_errinfo(i64 %previousException) #16, !dbg !62
  %"stackFrame_func_Test.test_known_nil$block_31.i32" = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** bitcast (i8** @"stackFramePrecomputed_func_Test.test_known_nil$block_3" to %struct.rb_iseq_struct**), align 8
  %133 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !17
  %134 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %133, i64 0, i32 2
  %135 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %134, align 8, !tbaa !28
  call void @sorbet_setExceptionStackFrame(%struct.rb_execution_context_struct* %133, %struct.rb_control_frame_struct* %135, %struct.rb_iseq_struct* %"stackFrame_func_Test.test_known_nil$block_31.i32") #16
  %136 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %135, i64 0, i32 0
  %137 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %135, i64 0, i32 2
  %138 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %137, align 8, !tbaa !31
  %139 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %138, i64 0, i32 2
  %140 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %139, align 8, !tbaa !34
  %141 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %140, i64 0, i32 2
  %142 = load i64*, i64** %141, align 8, !tbaa !36
  %143 = getelementptr inbounds i64, i64* %142, i64 1
  store i64* %143, i64** %136, align 8, !tbaa !17
  %144 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !17
  call void @rb_vm_pop_frame(%struct.rb_execution_context_struct* %144) #16
  ret i64 %.lcssa, !dbg !62

exception-body-continue:                          ; preds = %sorbet_writeLocal.exit29
  %145 = load i64, i64* %exceptionValue, align 8, !dbg !62
  %146 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !62, !tbaa !17
  %147 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %146, i64 0, i32 2, !dbg !62
  %148 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %147, align 8, !dbg !62, !tbaa !28
  %149 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %148, i64 0, i32 4, !dbg !62
  %150 = load i64*, i64** %149, align 8, !dbg !62, !tbaa !33
  %151 = load i64, i64* %150, align 8, !dbg !62, !tbaa !4
  %152 = and i64 %151, 8, !dbg !62
  %153 = icmp eq i64 %152, 0, !dbg !62
  br i1 %153, label %154, label %156, !dbg !62, !prof !51

154:                                              ; preds = %exception-body-continue
  %155 = getelementptr inbounds i64, i64* %150, i64 -3, !dbg !62
  store i64 %145, i64* %155, align 8, !dbg !62, !tbaa !4
  br label %sorbet_writeLocal.exit30, !dbg !62

156:                                              ; preds = %exception-body-continue
  call fastcc void @vm_env_write_slowpath(i64* nonnull %150, i32 -3, i64 %145) #16, !dbg !62
  br label %sorbet_writeLocal.exit30, !dbg !62

sorbet_writeLocal.exit30:                         ; preds = %154, %156
  %157 = icmp ne i64 %145, 8, !dbg !62
  %handler = select i1 %157, i64 (i64**, i64*, i64)* @"func_Test.test_known_nil$block_2", i64 (i64**, i64*, i64)* @"func_Test.test_known_nil$block_4", !dbg !62
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %68) #16, !dbg !62
  store i64 52, i64* %2, align 8, !dbg !62, !tbaa !4
  call void @llvm.lifetime.start.p0i8(i64 40, i8* nonnull %69) #16, !dbg !62
  store i64 (i64**, i64*, i64)* %handler, i64 (i64**, i64*, i64)** %70, align 8, !dbg !62, !tbaa !8
  store i64** %14, i64*** %71, align 8, !dbg !62, !tbaa !11
  store i64* %19, i64** %72, align 8, !dbg !62, !tbaa !12
  store i64 0, i64* %73, align 8, !dbg !62, !tbaa !13
  store i64* %2, i64** %74, align 8, !dbg !62, !tbaa !14
  store i64 8, i64* %exceptionValue, align 8, !dbg !62, !tbaa !4
  %158 = icmp eq i64 %145, 8, !dbg !62
  br i1 %158, label %sorbet_try.exit, label %159, !dbg !62

159:                                              ; preds = %sorbet_writeLocal.exit30
  call void @rb_set_errinfo(i64 %145) #16, !dbg !62
  br label %sorbet_try.exit, !dbg !62

sorbet_try.exit:                                  ; preds = %sorbet_writeLocal.exit30, %159
  %160 = load i64, i64* @rb_eException, align 8, !dbg !62, !tbaa !4
  %161 = call i64 (i64 (...)*, i64, i64 (...)*, i64, ...) @rb_rescue2(i64 (...)* bitcast (i64 (i64)* @sorbet_applyExceptionClosure to i64 (...)*), i64 %75, i64 (...)* bitcast (i64 (i64)* @sorbet_rescueStoreException to i64 (...)*), i64 %67, i64 %160, i32 0) #16, !dbg !62
  %162 = load i64, i64* %2, align 8, !dbg !62
  call void @llvm.lifetime.end.p0i8(i64 40, i8* nonnull %69) #16, !dbg !62
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %68) #16, !dbg !62
  %163 = load i64, i64* %exceptionValue, align 8, !dbg !62
  %164 = icmp eq i64 %163, 8, !dbg !62
  %165 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !62, !tbaa !17
  %166 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %165, i64 0, i32 2, !dbg !62
  %167 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %166, align 8, !dbg !62, !tbaa !28
  %168 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %167, i64 0, i32 4, !dbg !62
  %169 = load i64*, i64** %168, align 8, !dbg !62, !tbaa !33
  %170 = getelementptr inbounds i64, i64* %169, i64 -3, !dbg !62
  %171 = load i64, i64* %170, align 8, !dbg !62, !tbaa !4
  %172 = icmp eq i64 %171, 8, !dbg !62
  %173 = select i1 %172, i64 %previousException, i64 %171, !dbg !62
  %174 = select i1 %164, i64 %173, i64 %163, !dbg !62
  call void @rb_set_errinfo(i64 %174) #16, !dbg !62
  %"<retry-singleton>" = load i64, i64* @"<retry-singleton>", align 8, !dbg !62
  %shouldRetry = icmp eq i64 %162, %"<retry-singleton>", !dbg !62
  %175 = and i1 %157, %shouldRetry, !dbg !62
  br i1 %175, label %exception-entry, label %exception-ensure, !dbg !62

exception-ensure:                                 ; preds = %sorbet_try.exit, %sorbet_try.exit.us
  %.lcssa37 = phi i64 [ %107, %sorbet_try.exit.us ], [ %162, %sorbet_try.exit ], !dbg !62
  %.lcssa36 = phi i64 [ %117, %sorbet_try.exit.us ], [ %174, %sorbet_try.exit ], !dbg !62
  %"stackFrame_func_Test.test_known_nil$block_31.i" = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** bitcast (i8** @"stackFramePrecomputed_func_Test.test_known_nil$block_3" to %struct.rb_iseq_struct**), align 8
  %176 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !17
  %177 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %176, i64 0, i32 2
  %178 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %177, align 8, !tbaa !28
  call void @sorbet_setExceptionStackFrame(%struct.rb_execution_context_struct* %176, %struct.rb_control_frame_struct* %178, %struct.rb_iseq_struct* %"stackFrame_func_Test.test_known_nil$block_31.i") #16
  %179 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %178, i64 0, i32 0
  %180 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %178, i64 0, i32 2
  %181 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %180, align 8, !tbaa !31
  %182 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %181, i64 0, i32 2
  %183 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %182, align 8, !tbaa !34
  %184 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %183, i64 0, i32 2
  %185 = load i64*, i64** %184, align 8, !tbaa !36
  %186 = getelementptr inbounds i64, i64* %185, i64 1
  store i64* %186, i64** %179, align 8, !tbaa !17
  %187 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !17
  call void @rb_vm_pop_frame(%struct.rb_execution_context_struct* %187) #16
  %isReturnValue13 = icmp eq i64 %.lcssa37, 52, !dbg !62
  br i1 %isReturnValue13, label %exception-continue, label %exception-return, !dbg !62

exception-continue:                               ; preds = %exception-ensure
  %188 = icmp eq i64 %.lcssa36, 8, !dbg !62
  br i1 %188, label %sorbet_raiseIfNotNil.exit31, label %189, !dbg !62

189:                                              ; preds = %exception-continue
  call void @rb_exc_raise(i64 %.lcssa36) #17, !dbg !62
  unreachable, !dbg !62

sorbet_raiseIfNotNil.exit31:                      ; preds = %exception-continue
  %190 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !62, !tbaa !17
  %191 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %190, i64 0, i32 2, !dbg !62
  %192 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %191, align 8, !dbg !62, !tbaa !28
  %193 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %192, i64 0, i32 4, !dbg !62
  %194 = load i64*, i64** %193, align 8, !dbg !62, !tbaa !33
  %195 = getelementptr inbounds i64, i64* %194, i64 -3, !dbg !62
  %196 = load i64, i64* %195, align 8, !dbg !62, !tbaa !4
  %197 = icmp eq i64 %196, 8, !dbg !62
  br i1 %197, label %sorbet_raiseIfNotNil.exit, label %198, !dbg !62

198:                                              ; preds = %sorbet_raiseIfNotNil.exit31
  call void @rb_exc_raise(i64 %196) #17, !dbg !62
  unreachable, !dbg !62

sorbet_raiseIfNotNil.exit:                        ; preds = %sorbet_raiseIfNotNil.exit31
  store i64* %20, i64** %14, align 8, !tbaa !17
  %199 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !63, !tbaa !17
  %200 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %199, i64 0, i32 2, !dbg !63
  %201 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %200, align 8, !dbg !63, !tbaa !28
  %202 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %201, i64 0, i32 4, !dbg !63
  %203 = load i64*, i64** %202, align 8, !dbg !63, !tbaa !33
  %204 = getelementptr inbounds i64, i64* %203, i64 -5, !dbg !63
  %205 = load i64, i64* %204, align 8, !dbg !63, !tbaa !4
  ret i64 %205

exception-return:                                 ; preds = %exception-ensure
  ret i64 %.lcssa37, !dbg !62
}

; Function Attrs: noreturn nounwind ssp
define internal i64 @"func_Test.test_known_nil$block_1"(i64** nocapture %pc, i64* %iseq_encoded, i64 %localsOffset) #11 !dbg !67 {
  %1 = getelementptr inbounds i64, i64* %iseq_encoded, i64 3
  store i64* %1, i64** %pc, align 8, !tbaa !17
  %2 = load i64, i64* @rb_eTypeError, align 8, !dbg !68, !tbaa !4, !noalias !69
  tail call void (i64, i8*, ...) @rb_raise(i64 %2, i8* getelementptr inbounds ([25 x i8], [25 x i8]* @.str.20, i64 0, i64 0)) #17, !dbg !68, !noalias !69
  unreachable, !dbg !68
}

; Function Attrs: nounwind ssp
define internal i64 @"func_Test.test_known_nil$block_2"(i64** nocapture readnone %pc, i64* nocapture readnone %iseq_encoded, i64 %localsOffset) #12 !dbg !72 {
.preheader.i29:
  %callArgs = alloca [1 x i64], align 8
  %"stackFrame_func_Test.test_known_nil$block_222" = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** bitcast (i8** @"stackFramePrecomputed_func_Test.test_known_nil$block_2" to %struct.rb_iseq_struct**), align 8
  %0 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !17
  %1 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %0, i64 0, i32 2
  %2 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %1, align 8, !tbaa !28
  tail call void @sorbet_setExceptionStackFrame(%struct.rb_execution_context_struct* %0, %struct.rb_control_frame_struct* %2, %struct.rb_iseq_struct* %"stackFrame_func_Test.test_known_nil$block_222") #16
  %3 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 0
  %4 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 2
  %5 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %4, align 8, !tbaa !31
  %6 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %5, i64 0, i32 2
  %7 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %6, align 8, !tbaa !34
  %8 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %7, i64 0, i32 2
  %9 = load i64*, i64** %8, align 8, !tbaa !36
  %"rubyId_is_a?" = load i64, i64* @"rubyIdPrecomputed_is_a?", align 8, !dbg !73
  %rubyId_puts = load i64, i64* @rubyIdPrecomputed_puts, align 8, !dbg !74
  %10 = getelementptr inbounds i64, i64* %9, i64 4
  store i64* %10, i64** %3, align 8, !tbaa !17
  %11 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !73, !tbaa !17
  %12 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %11, i64 0, i32 2, !dbg !73
  %13 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %12, align 8, !dbg !73, !tbaa !28
  %14 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %13, i64 0, i32 4, !dbg !73
  %15 = load i64*, i64** %14, align 8, !dbg !73, !tbaa !33
  %16 = getelementptr inbounds i64, i64* %15, i64 -1, !dbg !73
  %17 = load i64, i64* %16, align 8, !dbg !73, !tbaa !4
  %18 = and i64 %17, -4, !dbg !73
  %19 = inttoptr i64 %18 to i64*, !dbg !73
  %20 = getelementptr inbounds i64, i64* %19, i64 -3, !dbg !73
  %21 = load i64, i64* %20, align 8, !dbg !73, !tbaa !4
  %22 = load i64, i64* @rb_eStandardError, align 8, !dbg !73
  %callArgs0Addr = getelementptr inbounds [1 x i64], [1 x i64]* %callArgs, i64 0, i64 0, !dbg !73
  store i64 %22, i64* %callArgs0Addr, align 8, !dbg !73
  %"callFunc_is_a?" = call i64 @sorbet_callFuncWithCache(i64 %21, i64 %"rubyId_is_a?", i32 1, i64* nonnull %callArgs0Addr, %struct.FunctionInlineCache* nonnull @"ic_callFunc_is_a?"), !dbg !73
  %23 = and i64 %"callFunc_is_a?", -9, !dbg !73
  %24 = icmp eq i64 %23, 0, !dbg !73
  br i1 %24, label %.preheader.i, label %.preheader.i27, !dbg !73

blockExit:                                        ; preds = %83, %81, %67, %65
  %25 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !17
  tail call void @rb_vm_pop_frame(%struct.rb_execution_context_struct* %25) #16
  ret i64 52

.preheader.i27:                                   ; preds = %.preheader.i29
  %26 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !17
  %27 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %26, i64 0, i32 2
  %28 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %27, align 8, !tbaa !28
  %29 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %28, i64 0, i32 4
  %30 = load i64*, i64** %29, align 8, !tbaa !33
  %31 = getelementptr inbounds i64, i64* %30, i64 -1
  %32 = load i64, i64* %31, align 8, !tbaa !4
  %33 = and i64 %32, -4
  %34 = inttoptr i64 %33 to i64*
  %35 = load i64, i64* %34, align 8, !tbaa !4
  %36 = and i64 %35, 8
  %37 = icmp eq i64 %36, 0
  br i1 %37, label %38, label %40, !prof !51

38:                                               ; preds = %.preheader.i27
  %39 = getelementptr inbounds i64, i64* %34, i64 -3
  store i64 8, i64* %39, align 8, !tbaa !4
  br label %.preheader.i23

40:                                               ; preds = %.preheader.i27
  tail call fastcc void @vm_env_write_slowpath(i64* nonnull %34, i32 -3, i64 8) #16
  br label %.preheader.i23

.preheader.i23:                                   ; preds = %38, %40
  %41 = getelementptr inbounds i64, i64* %9, i64 5, !dbg !75
  store i64* %41, i64** %3, align 8, !dbg !75, !tbaa !17
  store i64 %21, i64* %callArgs0Addr, align 8, !dbg !74
  %42 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !74, !tbaa !17
  %43 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %42, i64 0, i32 2, !dbg !74
  %44 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %43, align 8, !dbg !74, !tbaa !28
  %45 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %44, i64 0, i32 4, !dbg !74
  %46 = load i64*, i64** %45, align 8, !dbg !74, !tbaa !33
  %47 = getelementptr inbounds i64, i64* %46, i64 -1, !dbg !74
  %48 = load i64, i64* %47, align 8, !dbg !74, !tbaa !4
  %49 = and i64 %48, -4, !dbg !74
  %50 = inttoptr i64 %49 to i64*, !dbg !74
  %51 = getelementptr inbounds i64, i64* %50, i64 -6, !dbg !74
  %52 = load i64, i64* %51, align 8, !dbg !74, !tbaa !4
  %callFunc_puts = call i64 @sorbet_callFuncWithCache(i64 %52, i64 %rubyId_puts, i32 1, i64* nonnull %callArgs0Addr, %struct.FunctionInlineCache* nonnull @ic_callFunc_puts), !dbg !74
  %53 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !74, !tbaa !17
  %54 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %53, i64 0, i32 2, !dbg !74
  %55 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %54, align 8, !dbg !74, !tbaa !28
  %56 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %55, i64 0, i32 4, !dbg !74
  %57 = load i64*, i64** %56, align 8, !dbg !74, !tbaa !33
  %58 = getelementptr inbounds i64, i64* %57, i64 -1, !dbg !74
  %59 = load i64, i64* %58, align 8, !dbg !74, !tbaa !4
  %60 = and i64 %59, -4, !dbg !74
  %61 = inttoptr i64 %60 to i64*, !dbg !74
  %62 = load i64, i64* %61, align 8, !dbg !74, !tbaa !4
  %63 = and i64 %62, 8, !dbg !74
  %64 = icmp eq i64 %63, 0, !dbg !74
  br i1 %64, label %65, label %67, !dbg !74, !prof !51

65:                                               ; preds = %.preheader.i23
  %66 = getelementptr inbounds i64, i64* %61, i64 -5, !dbg !74
  store i64 %callFunc_puts, i64* %66, align 8, !dbg !74, !tbaa !4
  br label %blockExit, !dbg !74

67:                                               ; preds = %.preheader.i23
  tail call fastcc void @vm_env_write_slowpath(i64* nonnull %61, i32 -5, i64 %callFunc_puts) #16, !dbg !74
  br label %blockExit, !dbg !74

.preheader.i:                                     ; preds = %.preheader.i29
  %68 = getelementptr inbounds i64, i64* %9, i64 3
  store i64* %68, i64** %3, align 8, !tbaa !17
  %69 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !76, !tbaa !17
  %70 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %69, i64 0, i32 2, !dbg !76
  %71 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %70, align 8, !dbg !76, !tbaa !28
  %72 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %71, i64 0, i32 4, !dbg !76
  %73 = load i64*, i64** %72, align 8, !dbg !76, !tbaa !33
  %74 = getelementptr inbounds i64, i64* %73, i64 -1, !dbg !76
  %75 = load i64, i64* %74, align 8, !dbg !76, !tbaa !4
  %76 = and i64 %75, -4, !dbg !76
  %77 = inttoptr i64 %76 to i64*, !dbg !76
  %78 = load i64, i64* %77, align 8, !dbg !76, !tbaa !4
  %79 = and i64 %78, 8, !dbg !76
  %80 = icmp eq i64 %79, 0, !dbg !76
  br i1 %80, label %81, label %83, !dbg !76, !prof !51

81:                                               ; preds = %.preheader.i
  %82 = getelementptr inbounds i64, i64* %77, i64 -7, !dbg !76
  store i64 20, i64* %82, align 8, !dbg !76, !tbaa !4
  br label %blockExit, !dbg !76

83:                                               ; preds = %.preheader.i
  tail call fastcc void @vm_env_write_slowpath(i64* nonnull %77, i32 -7, i64 20) #16, !dbg !76
  br label %blockExit, !dbg !76
}

; Function Attrs: nofree norecurse nounwind ssp writeonly
define internal i64 @"func_Test.test_known_nil$block_4"(i64** nocapture %pc, i64* %iseq_encoded, i64 %localsOffset) #13 !dbg !77 {
functionEntryInitializers:
  %0 = getelementptr inbounds i64, i64* %iseq_encoded, i64 1
  store i64* %0, i64** %pc, align 8, !tbaa !17
  ret i64 52
}

; Function Attrs: nounwind sspreq uwtable
define i64 @func_Test.test_nilable_arg(i32 %argc, i64* nocapture readonly %argArray, i64 %selfRaw) #10 !dbg !78 {
functionEntryInitializers:
  %0 = alloca i64, align 8
  %1 = alloca %struct.ExceptionClosure, align 8
  %2 = alloca i64, align 8
  %3 = alloca %struct.ExceptionClosure, align 8
  %stackFrame_func_Test.test_nilable_arg = load i8*, i8** @stackFramePrecomputed_func_Test.test_nilable_arg, align 8
  %4 = bitcast i8* %stackFrame_func_Test.test_nilable_arg to %struct.rb_iseq_struct*
  %5 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !17
  %6 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %5, i64 0, i32 2
  %7 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %6, align 8, !tbaa !28
  %8 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %7, i64 0, i32 2
  %9 = bitcast %struct.rb_iseq_struct** %8 to i8**
  store i8* %stackFrame_func_Test.test_nilable_arg, i8** %9, align 8, !tbaa !31
  %10 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %7, i64 0, i32 4
  %11 = load i64*, i64** %10, align 8, !tbaa !33
  %12 = load i64, i64* %11, align 8, !tbaa !4
  %13 = and i64 %12, -129
  store i64 %13, i64* %11, align 8, !tbaa !4
  tail call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* undef, %struct.rb_control_frame_struct* nonnull %7, %struct.rb_iseq_struct* %4) #16
  %14 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %7, i64 0, i32 0
  %15 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %8, align 8, !tbaa !31
  %16 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %15, i64 0, i32 2
  %17 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %16, align 8, !tbaa !34
  %18 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %17, i64 0, i32 2
  %19 = load i64*, i64** %18, align 8, !tbaa !36
  %20 = getelementptr inbounds i64, i64* %19, i64 1
  store i64* %20, i64** %14, align 8, !tbaa !17
  %exceptionValue = alloca i64, align 8, !dbg !79
  %21 = icmp eq i32 %argc, 1, !dbg !80
  br i1 %21, label %fillRequiredArgs, label %argCountFailBlock, !dbg !80, !prof !81

argCountFailBlock:                                ; preds = %functionEntryInitializers
  tail call void @sorbet_raiseArity(i32 %argc, i32 1, i32 1), !dbg !80
  unreachable, !dbg !80

fillRequiredArgs:                                 ; preds = %functionEntryInitializers
  %22 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !80, !tbaa !17
  %23 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %22, i64 0, i32 2, !dbg !80
  %24 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %23, align 8, !dbg !80, !tbaa !28
  %25 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %24, i64 0, i32 4, !dbg !80
  %26 = load i64*, i64** %25, align 8, !dbg !80, !tbaa !33
  %27 = load i64, i64* %26, align 8, !dbg !80, !tbaa !4
  %28 = and i64 %27, 8, !dbg !80
  %29 = icmp eq i64 %28, 0, !dbg !80
  br i1 %29, label %30, label %32, !dbg !80, !prof !51

30:                                               ; preds = %fillRequiredArgs
  %31 = getelementptr inbounds i64, i64* %26, i64 -5, !dbg !80
  store i64 %selfRaw, i64* %31, align 8, !dbg !80, !tbaa !4
  br label %sorbet_writeLocal.exit, !dbg !80

32:                                               ; preds = %fillRequiredArgs
  tail call fastcc void @vm_env_write_slowpath(i64* nonnull %26, i32 -5, i64 %selfRaw) #16, !dbg !80
  br label %sorbet_writeLocal.exit, !dbg !80

sorbet_writeLocal.exit:                           ; preds = %30, %32
  %rawArg_arg = load i64, i64* %argArray, align 8, !dbg !80
  %33 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !80, !tbaa !17
  %34 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %33, i64 0, i32 2, !dbg !80
  %35 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %34, align 8, !dbg !80, !tbaa !28
  %36 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %35, i64 0, i32 4, !dbg !80
  %37 = load i64*, i64** %36, align 8, !dbg !80, !tbaa !33
  %38 = load i64, i64* %37, align 8, !dbg !80, !tbaa !4
  %39 = and i64 %38, 8, !dbg !80
  %40 = icmp eq i64 %39, 0, !dbg !80
  br i1 %40, label %41, label %43, !dbg !80, !prof !51

41:                                               ; preds = %sorbet_writeLocal.exit
  %42 = getelementptr inbounds i64, i64* %37, i64 -4, !dbg !80
  store i64 %rawArg_arg, i64* %42, align 8, !dbg !80, !tbaa !4
  br label %sorbet_writeLocal.exit28, !dbg !80

43:                                               ; preds = %sorbet_writeLocal.exit
  tail call fastcc void @vm_env_write_slowpath(i64* nonnull %37, i32 -4, i64 %rawArg_arg) #16, !dbg !80
  br label %sorbet_writeLocal.exit28, !dbg !80

sorbet_writeLocal.exit28:                         ; preds = %41, %43
  store i64* %20, i64** %14, align 8, !tbaa !17
  %44 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !80, !tbaa !17
  %45 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %44, i64 0, i32 2, !dbg !80
  %46 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %45, align 8, !dbg !80, !tbaa !28
  %47 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %46, i64 0, i32 4, !dbg !80
  %48 = load i64*, i64** %47, align 8, !dbg !80, !tbaa !33
  %49 = getelementptr inbounds i64, i64* %48, i64 -5, !dbg !80
  %50 = load i64, i64* %49, align 8, !dbg !80, !tbaa !4
  %51 = load i64, i64* @guard_epoch_Test, align 8, !dbg !80
  %52 = tail call i64 @sorbet_getConstantEpoch(), !dbg !80
  %needTakeSlowPath = icmp eq i64 %51, %52, !dbg !80
  br i1 %needTakeSlowPath, label %54, label %53, !dbg !80, !prof !53

53:                                               ; preds = %sorbet_writeLocal.exit28
  tail call void @const_recompute_Test() #16, !dbg !80
  br label %54, !dbg !80

54:                                               ; preds = %sorbet_writeLocal.exit28, %53
  %55 = load i64, i64* @guarded_const_Test, align 8, !dbg !80
  %56 = load i64, i64* @guard_epoch_Test, align 8, !dbg !80
  %57 = tail call i64 @sorbet_getConstantEpoch(), !dbg !80
  %guardUpdated = icmp eq i64 %56, %57, !dbg !80
  tail call void @llvm.assume(i1 %guardUpdated), !dbg !80
  %58 = icmp eq i64 %50, %55, !dbg !80
  br i1 %58, label %typeTestSuccess, label %59, !dbg !80

59:                                               ; preds = %54
  %60 = load i64, i64* @rb_cModule, align 8, !dbg !80, !tbaa !4
  %61 = tail call i64 @rb_obj_is_kind_of(i64 %50, i64 %60) #7, !dbg !80
  %62 = icmp eq i64 %61, 0, !dbg !80
  br i1 %62, label %codeRepl, label %sorbet_isa_class_of.exit, !dbg !80, !prof !64

sorbet_isa_class_of.exit:                         ; preds = %59
  %63 = tail call i64 @rb_class_inherited_p(i64 %50, i64 %55) #7, !dbg !80
  %64 = icmp eq i64 %63, 0, !dbg !80
  br i1 %64, label %codeRepl, label %typeTestSuccess, !dbg !80, !prof !65

typeTestSuccess:                                  ; preds = %sorbet_isa_class_of.exit, %54
  %65 = load i64, i64* %48, align 8, !dbg !80, !tbaa !4
  %66 = and i64 %65, 8, !dbg !80
  %67 = icmp eq i64 %66, 0, !dbg !80
  br i1 %67, label %sorbet_writeLocal.exit29, label %68, !dbg !80, !prof !51

68:                                               ; preds = %typeTestSuccess
  tail call fastcc void @vm_env_write_slowpath(i64* nonnull %48, i32 -5, i64 %50) #16, !dbg !80
  br label %sorbet_writeLocal.exit29, !dbg !80

sorbet_writeLocal.exit29:                         ; preds = %typeTestSuccess, %68
  %69 = getelementptr inbounds i64, i64* %19, i64 3
  store i64* %69, i64** %14, align 8, !tbaa !17
  %previousException = tail call i64 @rb_errinfo() #16, !dbg !79
  %70 = bitcast i64* %0 to i8*, !dbg !82
  %71 = bitcast %struct.ExceptionClosure* %1 to i8*, !dbg !82
  %72 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %1, i64 0, i32 0, !dbg !82
  %73 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %1, i64 0, i32 1, !dbg !82
  %74 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %1, i64 0, i32 2, !dbg !82
  %75 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %1, i64 0, i32 3, !dbg !82
  %76 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %1, i64 0, i32 4, !dbg !82
  %77 = icmp eq i64 %previousException, 8, !dbg !82
  %78 = ptrtoint %struct.ExceptionClosure* %1 to i64, !dbg !82
  %79 = ptrtoint i64* %exceptionValue to i64, !dbg !82
  %80 = bitcast i64* %2 to i8*, !dbg !82
  %81 = bitcast %struct.ExceptionClosure* %3 to i8*, !dbg !82
  %82 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %3, i64 0, i32 0, !dbg !82
  %83 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %3, i64 0, i32 1, !dbg !82
  %84 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %3, i64 0, i32 2, !dbg !82
  %85 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %3, i64 0, i32 3, !dbg !82
  %86 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %3, i64 0, i32 4, !dbg !82
  %87 = ptrtoint %struct.ExceptionClosure* %3 to i64, !dbg !82
  br i1 %77, label %exception-entry.us, label %exception-entry, !dbg !79

exception-entry.us:                               ; preds = %sorbet_writeLocal.exit29, %sorbet_try.exit.us
  %88 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !79, !tbaa !17
  %89 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %88, i64 0, i32 2, !dbg !79
  %90 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %89, align 8, !dbg !79, !tbaa !28
  %91 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %90, i64 0, i32 4, !dbg !79
  %92 = load i64*, i64** %91, align 8, !dbg !79, !tbaa !33
  %93 = load i64, i64* %92, align 8, !dbg !79, !tbaa !4
  %94 = and i64 %93, 8, !dbg !79
  %95 = icmp eq i64 %94, 0, !dbg !79
  br i1 %95, label %97, label %96, !dbg !79, !prof !51

96:                                               ; preds = %exception-entry.us
  call fastcc void @vm_env_write_slowpath(i64* nonnull %92, i32 -3, i64 8) #16, !dbg !79
  br label %sorbet_writeLocal.exit30.us, !dbg !79

97:                                               ; preds = %exception-entry.us
  %98 = getelementptr inbounds i64, i64* %92, i64 -3, !dbg !79
  store i64 8, i64* %98, align 8, !dbg !79, !tbaa !4
  br label %sorbet_writeLocal.exit30.us, !dbg !79

sorbet_writeLocal.exit30.us:                      ; preds = %97, %96
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %70) #16, !dbg !79
  store i64 52, i64* %0, align 8, !dbg !79, !tbaa !4
  call void @llvm.lifetime.start.p0i8(i64 40, i8* nonnull %71) #16, !dbg !79
  store i64 (i64**, i64*, i64)* @"func_Test.test_nilable_arg$block_1", i64 (i64**, i64*, i64)** %72, align 8, !dbg !79, !tbaa !8
  store i64** %14, i64*** %73, align 8, !dbg !79, !tbaa !11
  store i64* %19, i64** %74, align 8, !dbg !79, !tbaa !12
  store i64 0, i64* %75, align 8, !dbg !79, !tbaa !13
  store i64* %0, i64** %76, align 8, !dbg !79, !tbaa !14
  store i64 8, i64* %exceptionValue, align 8, !dbg !79, !tbaa !4
  %99 = load i64, i64* @rb_eException, align 8, !dbg !79, !tbaa !4
  %100 = call i64 (i64 (...)*, i64, i64 (...)*, i64, ...) @rb_rescue2(i64 (...)* bitcast (i64 (i64)* @sorbet_applyExceptionClosure to i64 (...)*), i64 %78, i64 (...)* bitcast (i64 (i64)* @sorbet_rescueStoreException to i64 (...)*), i64 %79, i64 %99, i32 0) #16, !dbg !79
  %101 = load i64, i64* %0, align 8, !dbg !79
  call void @llvm.lifetime.end.p0i8(i64 40, i8* nonnull %71) #16, !dbg !79
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %70) #16, !dbg !79
  %isReturnValue.us = icmp eq i64 %101, 52, !dbg !79
  br i1 %isReturnValue.us, label %exception-body-continue.us, label %exception-body-return, !dbg !79

exception-body-continue.us:                       ; preds = %sorbet_writeLocal.exit30.us
  %102 = load i64, i64* %exceptionValue, align 8, !dbg !79
  %103 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !79, !tbaa !17
  %104 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %103, i64 0, i32 2, !dbg !79
  %105 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %104, align 8, !dbg !79, !tbaa !28
  %106 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %105, i64 0, i32 4, !dbg !79
  %107 = load i64*, i64** %106, align 8, !dbg !79, !tbaa !33
  %108 = load i64, i64* %107, align 8, !dbg !79, !tbaa !4
  %109 = and i64 %108, 8, !dbg !79
  %110 = icmp eq i64 %109, 0, !dbg !79
  br i1 %110, label %112, label %111, !dbg !79, !prof !51

111:                                              ; preds = %exception-body-continue.us
  call fastcc void @vm_env_write_slowpath(i64* nonnull %107, i32 -3, i64 %102) #16, !dbg !79
  br label %sorbet_writeLocal.exit31.us, !dbg !79

112:                                              ; preds = %exception-body-continue.us
  %113 = getelementptr inbounds i64, i64* %107, i64 -3, !dbg !79
  store i64 %102, i64* %113, align 8, !dbg !79, !tbaa !4
  br label %sorbet_writeLocal.exit31.us, !dbg !79

sorbet_writeLocal.exit31.us:                      ; preds = %112, %111
  %114 = icmp ne i64 %102, 8, !dbg !79
  %handler.us = select i1 %114, i64 (i64**, i64*, i64)* @"func_Test.test_nilable_arg$block_2", i64 (i64**, i64*, i64)* @"func_Test.test_nilable_arg$block_4", !dbg !79
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %80) #16, !dbg !79
  store i64 52, i64* %2, align 8, !dbg !79, !tbaa !4
  call void @llvm.lifetime.start.p0i8(i64 40, i8* nonnull %81) #16, !dbg !79
  store i64 (i64**, i64*, i64)* %handler.us, i64 (i64**, i64*, i64)** %82, align 8, !dbg !79, !tbaa !8
  store i64** %14, i64*** %83, align 8, !dbg !79, !tbaa !11
  store i64* %19, i64** %84, align 8, !dbg !79, !tbaa !12
  store i64 0, i64* %85, align 8, !dbg !79, !tbaa !13
  store i64* %2, i64** %86, align 8, !dbg !79, !tbaa !14
  store i64 8, i64* %exceptionValue, align 8, !dbg !79, !tbaa !4
  %115 = icmp eq i64 %102, 8, !dbg !79
  br i1 %115, label %sorbet_try.exit.us, label %116, !dbg !79

116:                                              ; preds = %sorbet_writeLocal.exit31.us
  call void @rb_set_errinfo(i64 %102) #16, !dbg !79
  br label %sorbet_try.exit.us, !dbg !79

sorbet_try.exit.us:                               ; preds = %116, %sorbet_writeLocal.exit31.us
  %117 = load i64, i64* @rb_eException, align 8, !dbg !79, !tbaa !4
  %118 = call i64 (i64 (...)*, i64, i64 (...)*, i64, ...) @rb_rescue2(i64 (...)* bitcast (i64 (i64)* @sorbet_applyExceptionClosure to i64 (...)*), i64 %87, i64 (...)* bitcast (i64 (i64)* @sorbet_rescueStoreException to i64 (...)*), i64 %79, i64 %117, i32 0) #16, !dbg !79
  %119 = load i64, i64* %2, align 8, !dbg !79
  call void @llvm.lifetime.end.p0i8(i64 40, i8* nonnull %81) #16, !dbg !79
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %80) #16, !dbg !79
  %120 = load i64, i64* %exceptionValue, align 8, !dbg !79
  %121 = icmp eq i64 %120, 8, !dbg !79
  %122 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !79, !tbaa !17
  %123 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %122, i64 0, i32 2, !dbg !79
  %124 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %123, align 8, !dbg !79, !tbaa !28
  %125 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %124, i64 0, i32 4, !dbg !79
  %126 = load i64*, i64** %125, align 8, !dbg !79, !tbaa !33
  %127 = getelementptr inbounds i64, i64* %126, i64 -3, !dbg !79
  %128 = load i64, i64* %127, align 8, !dbg !79, !tbaa !4
  %129 = select i1 %121, i64 %128, i64 %120, !dbg !79
  call void @rb_set_errinfo(i64 %129) #16, !dbg !79
  %"<retry-singleton>.us" = load i64, i64* @"<retry-singleton>", align 8, !dbg !79
  %shouldRetry.us = icmp eq i64 %119, %"<retry-singleton>.us", !dbg !79
  %130 = and i1 %114, %shouldRetry.us, !dbg !79
  br i1 %130, label %exception-entry.us, label %exception-ensure, !dbg !79

codeRepl:                                         ; preds = %59, %sorbet_isa_class_of.exit
  tail call void @sorbet_cast_failure(i64 %50, i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_cast, i64 0, i64 0), i8* getelementptr inbounds ([17 x i8], [17 x i8]* @"str_T.class_of(Test)", i64 0, i64 0)) #16, !dbg !83
  unreachable, !dbg !83

exception-entry:                                  ; preds = %sorbet_writeLocal.exit29, %sorbet_try.exit
  %131 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !79, !tbaa !17
  %132 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %131, i64 0, i32 2, !dbg !79
  %133 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %132, align 8, !dbg !79, !tbaa !28
  %134 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %133, i64 0, i32 4, !dbg !79
  %135 = load i64*, i64** %134, align 8, !dbg !79, !tbaa !33
  %136 = load i64, i64* %135, align 8, !dbg !79, !tbaa !4
  %137 = and i64 %136, 8, !dbg !79
  %138 = icmp eq i64 %137, 0, !dbg !79
  br i1 %138, label %139, label %141, !dbg !79, !prof !51

139:                                              ; preds = %exception-entry
  %140 = getelementptr inbounds i64, i64* %135, i64 -3, !dbg !79
  store i64 8, i64* %140, align 8, !dbg !79, !tbaa !4
  br label %sorbet_writeLocal.exit30, !dbg !79

141:                                              ; preds = %exception-entry
  call fastcc void @vm_env_write_slowpath(i64* nonnull %135, i32 -3, i64 8) #16, !dbg !79
  br label %sorbet_writeLocal.exit30, !dbg !79

sorbet_writeLocal.exit30:                         ; preds = %139, %141
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %70) #16, !dbg !79
  store i64 52, i64* %0, align 8, !dbg !79, !tbaa !4
  call void @llvm.lifetime.start.p0i8(i64 40, i8* nonnull %71) #16, !dbg !79
  store i64 (i64**, i64*, i64)* @"func_Test.test_nilable_arg$block_1", i64 (i64**, i64*, i64)** %72, align 8, !dbg !79, !tbaa !8
  store i64** %14, i64*** %73, align 8, !dbg !79, !tbaa !11
  store i64* %19, i64** %74, align 8, !dbg !79, !tbaa !12
  store i64 0, i64* %75, align 8, !dbg !79, !tbaa !13
  store i64* %0, i64** %76, align 8, !dbg !79, !tbaa !14
  store i64 8, i64* %exceptionValue, align 8, !dbg !79, !tbaa !4
  call void @rb_set_errinfo(i64 %previousException) #16, !dbg !79
  %142 = load i64, i64* @rb_eException, align 8, !dbg !79, !tbaa !4
  %143 = call i64 (i64 (...)*, i64, i64 (...)*, i64, ...) @rb_rescue2(i64 (...)* bitcast (i64 (i64)* @sorbet_applyExceptionClosure to i64 (...)*), i64 %78, i64 (...)* bitcast (i64 (i64)* @sorbet_rescueStoreException to i64 (...)*), i64 %79, i64 %142, i32 0) #16, !dbg !79
  %144 = load i64, i64* %0, align 8, !dbg !79
  call void @llvm.lifetime.end.p0i8(i64 40, i8* nonnull %71) #16, !dbg !79
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %70) #16, !dbg !79
  %isReturnValue = icmp eq i64 %144, 52, !dbg !79
  br i1 %isReturnValue, label %exception-body-continue, label %exception-body-return, !dbg !79

exception-body-return:                            ; preds = %sorbet_writeLocal.exit30, %sorbet_writeLocal.exit30.us
  %.lcssa = phi i64 [ %101, %sorbet_writeLocal.exit30.us ], [ %144, %sorbet_writeLocal.exit30 ], !dbg !79
  call void @rb_set_errinfo(i64 %previousException) #16, !dbg !79
  %"stackFrame_func_Test.test_nilable_arg$block_31.i33" = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** bitcast (i8** @"stackFramePrecomputed_func_Test.test_nilable_arg$block_3" to %struct.rb_iseq_struct**), align 8
  %145 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !17
  %146 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %145, i64 0, i32 2
  %147 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %146, align 8, !tbaa !28
  call void @sorbet_setExceptionStackFrame(%struct.rb_execution_context_struct* %145, %struct.rb_control_frame_struct* %147, %struct.rb_iseq_struct* %"stackFrame_func_Test.test_nilable_arg$block_31.i33") #16
  %148 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %147, i64 0, i32 0
  %149 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %147, i64 0, i32 2
  %150 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %149, align 8, !tbaa !31
  %151 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %150, i64 0, i32 2
  %152 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %151, align 8, !tbaa !34
  %153 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %152, i64 0, i32 2
  %154 = load i64*, i64** %153, align 8, !tbaa !36
  %155 = getelementptr inbounds i64, i64* %154, i64 1
  store i64* %155, i64** %148, align 8, !tbaa !17
  %156 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !17
  call void @rb_vm_pop_frame(%struct.rb_execution_context_struct* %156) #16
  ret i64 %.lcssa, !dbg !79

exception-body-continue:                          ; preds = %sorbet_writeLocal.exit30
  %157 = load i64, i64* %exceptionValue, align 8, !dbg !79
  %158 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !79, !tbaa !17
  %159 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %158, i64 0, i32 2, !dbg !79
  %160 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %159, align 8, !dbg !79, !tbaa !28
  %161 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %160, i64 0, i32 4, !dbg !79
  %162 = load i64*, i64** %161, align 8, !dbg !79, !tbaa !33
  %163 = load i64, i64* %162, align 8, !dbg !79, !tbaa !4
  %164 = and i64 %163, 8, !dbg !79
  %165 = icmp eq i64 %164, 0, !dbg !79
  br i1 %165, label %166, label %168, !dbg !79, !prof !51

166:                                              ; preds = %exception-body-continue
  %167 = getelementptr inbounds i64, i64* %162, i64 -3, !dbg !79
  store i64 %157, i64* %167, align 8, !dbg !79, !tbaa !4
  br label %sorbet_writeLocal.exit31, !dbg !79

168:                                              ; preds = %exception-body-continue
  call fastcc void @vm_env_write_slowpath(i64* nonnull %162, i32 -3, i64 %157) #16, !dbg !79
  br label %sorbet_writeLocal.exit31, !dbg !79

sorbet_writeLocal.exit31:                         ; preds = %166, %168
  %169 = icmp ne i64 %157, 8, !dbg !79
  %handler = select i1 %169, i64 (i64**, i64*, i64)* @"func_Test.test_nilable_arg$block_2", i64 (i64**, i64*, i64)* @"func_Test.test_nilable_arg$block_4", !dbg !79
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %80) #16, !dbg !79
  store i64 52, i64* %2, align 8, !dbg !79, !tbaa !4
  call void @llvm.lifetime.start.p0i8(i64 40, i8* nonnull %81) #16, !dbg !79
  store i64 (i64**, i64*, i64)* %handler, i64 (i64**, i64*, i64)** %82, align 8, !dbg !79, !tbaa !8
  store i64** %14, i64*** %83, align 8, !dbg !79, !tbaa !11
  store i64* %19, i64** %84, align 8, !dbg !79, !tbaa !12
  store i64 0, i64* %85, align 8, !dbg !79, !tbaa !13
  store i64* %2, i64** %86, align 8, !dbg !79, !tbaa !14
  store i64 8, i64* %exceptionValue, align 8, !dbg !79, !tbaa !4
  %170 = icmp eq i64 %157, 8, !dbg !79
  br i1 %170, label %sorbet_try.exit, label %171, !dbg !79

171:                                              ; preds = %sorbet_writeLocal.exit31
  call void @rb_set_errinfo(i64 %157) #16, !dbg !79
  br label %sorbet_try.exit, !dbg !79

sorbet_try.exit:                                  ; preds = %sorbet_writeLocal.exit31, %171
  %172 = load i64, i64* @rb_eException, align 8, !dbg !79, !tbaa !4
  %173 = call i64 (i64 (...)*, i64, i64 (...)*, i64, ...) @rb_rescue2(i64 (...)* bitcast (i64 (i64)* @sorbet_applyExceptionClosure to i64 (...)*), i64 %87, i64 (...)* bitcast (i64 (i64)* @sorbet_rescueStoreException to i64 (...)*), i64 %79, i64 %172, i32 0) #16, !dbg !79
  %174 = load i64, i64* %2, align 8, !dbg !79
  call void @llvm.lifetime.end.p0i8(i64 40, i8* nonnull %81) #16, !dbg !79
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %80) #16, !dbg !79
  %175 = load i64, i64* %exceptionValue, align 8, !dbg !79
  %176 = icmp eq i64 %175, 8, !dbg !79
  %177 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !79, !tbaa !17
  %178 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %177, i64 0, i32 2, !dbg !79
  %179 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %178, align 8, !dbg !79, !tbaa !28
  %180 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %179, i64 0, i32 4, !dbg !79
  %181 = load i64*, i64** %180, align 8, !dbg !79, !tbaa !33
  %182 = getelementptr inbounds i64, i64* %181, i64 -3, !dbg !79
  %183 = load i64, i64* %182, align 8, !dbg !79, !tbaa !4
  %184 = icmp eq i64 %183, 8, !dbg !79
  %185 = select i1 %184, i64 %previousException, i64 %183, !dbg !79
  %186 = select i1 %176, i64 %185, i64 %175, !dbg !79
  call void @rb_set_errinfo(i64 %186) #16, !dbg !79
  %"<retry-singleton>" = load i64, i64* @"<retry-singleton>", align 8, !dbg !79
  %shouldRetry = icmp eq i64 %174, %"<retry-singleton>", !dbg !79
  %187 = and i1 %169, %shouldRetry, !dbg !79
  br i1 %187, label %exception-entry, label %exception-ensure, !dbg !79

exception-ensure:                                 ; preds = %sorbet_try.exit, %sorbet_try.exit.us
  %.lcssa38 = phi i64 [ %119, %sorbet_try.exit.us ], [ %174, %sorbet_try.exit ], !dbg !79
  %.lcssa37 = phi i64 [ %129, %sorbet_try.exit.us ], [ %186, %sorbet_try.exit ], !dbg !79
  %"stackFrame_func_Test.test_nilable_arg$block_31.i" = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** bitcast (i8** @"stackFramePrecomputed_func_Test.test_nilable_arg$block_3" to %struct.rb_iseq_struct**), align 8
  %188 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !17
  %189 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %188, i64 0, i32 2
  %190 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %189, align 8, !tbaa !28
  call void @sorbet_setExceptionStackFrame(%struct.rb_execution_context_struct* %188, %struct.rb_control_frame_struct* %190, %struct.rb_iseq_struct* %"stackFrame_func_Test.test_nilable_arg$block_31.i") #16
  %191 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %190, i64 0, i32 0
  %192 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %190, i64 0, i32 2
  %193 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %192, align 8, !tbaa !31
  %194 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %193, i64 0, i32 2
  %195 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %194, align 8, !tbaa !34
  %196 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %195, i64 0, i32 2
  %197 = load i64*, i64** %196, align 8, !tbaa !36
  %198 = getelementptr inbounds i64, i64* %197, i64 1
  store i64* %198, i64** %191, align 8, !tbaa !17
  %199 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !17
  call void @rb_vm_pop_frame(%struct.rb_execution_context_struct* %199) #16
  %isReturnValue13 = icmp eq i64 %.lcssa38, 52, !dbg !79
  br i1 %isReturnValue13, label %exception-continue, label %exception-return, !dbg !79

exception-continue:                               ; preds = %exception-ensure
  %200 = icmp eq i64 %.lcssa37, 8, !dbg !79
  br i1 %200, label %sorbet_raiseIfNotNil.exit32, label %201, !dbg !79

201:                                              ; preds = %exception-continue
  call void @rb_exc_raise(i64 %.lcssa37) #17, !dbg !79
  unreachable, !dbg !79

sorbet_raiseIfNotNil.exit32:                      ; preds = %exception-continue
  %202 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !79, !tbaa !17
  %203 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %202, i64 0, i32 2, !dbg !79
  %204 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %203, align 8, !dbg !79, !tbaa !28
  %205 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %204, i64 0, i32 4, !dbg !79
  %206 = load i64*, i64** %205, align 8, !dbg !79, !tbaa !33
  %207 = getelementptr inbounds i64, i64* %206, i64 -3, !dbg !79
  %208 = load i64, i64* %207, align 8, !dbg !79, !tbaa !4
  %209 = icmp eq i64 %208, 8, !dbg !79
  br i1 %209, label %sorbet_raiseIfNotNil.exit, label %210, !dbg !79

210:                                              ; preds = %sorbet_raiseIfNotNil.exit32
  call void @rb_exc_raise(i64 %208) #17, !dbg !79
  unreachable, !dbg !79

sorbet_raiseIfNotNil.exit:                        ; preds = %sorbet_raiseIfNotNil.exit32
  store i64* %20, i64** %14, align 8, !tbaa !17
  %211 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !80, !tbaa !17
  %212 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %211, i64 0, i32 2, !dbg !80
  %213 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %212, align 8, !dbg !80, !tbaa !28
  %214 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %213, i64 0, i32 4, !dbg !80
  %215 = load i64*, i64** %214, align 8, !dbg !80, !tbaa !33
  %216 = getelementptr inbounds i64, i64* %215, i64 -7, !dbg !80
  %217 = load i64, i64* %216, align 8, !dbg !80, !tbaa !4
  ret i64 %217

exception-return:                                 ; preds = %exception-ensure
  ret i64 %.lcssa38, !dbg !79
}

; Function Attrs: nounwind ssp
define internal i64 @"func_Test.test_nilable_arg$block_1"(i64** nocapture %pc, i64* %iseq_encoded, i64 %localsOffset) #12 !dbg !85 {
fastSymCallIntrinsic_T_must:
  %callArgs = alloca [2 x i64], align 8
  %"rubyStr_ wasn't nil" = load i64, i64* @"rubyStrFrozen_ wasn't nil", align 8, !dbg !86
  %rubyId_puts = load i64, i64* @rubyIdPrecomputed_puts, align 8, !dbg !87
  %0 = getelementptr inbounds i64, i64* %iseq_encoded, i64 3
  store i64* %0, i64** %pc, align 8, !tbaa !17
  %1 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !88, !tbaa !17
  %2 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %1, i64 0, i32 2, !dbg !88
  %3 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %2, align 8, !dbg !88, !tbaa !28
  %4 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 4, !dbg !88
  %5 = load i64*, i64** %4, align 8, !dbg !88, !tbaa !33
  %6 = getelementptr inbounds i64, i64* %5, i64 -4, !dbg !88
  %7 = load i64, i64* %6, align 8, !dbg !88, !tbaa !4
  %callArgs0Addr = getelementptr inbounds [2 x i64], [2 x i64]* %callArgs, i64 0, i64 0, !dbg !88
  store i64 %7, i64* %callArgs0Addr, align 8, !dbg !88
  %8 = icmp eq i64 %7, 8, !dbg !88
  br i1 %8, label %41, label %9, !dbg !88, !prof !65

9:                                                ; preds = %fastSymCallIntrinsic_T_must
  %10 = getelementptr inbounds i64, i64* %iseq_encoded, i64 4, !dbg !88
  store i64* %10, i64** %pc, align 8, !dbg !88, !tbaa !17
  %11 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !89, !tbaa !17
  %12 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %11, i64 0, i32 2, !dbg !89
  %13 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %12, align 8, !dbg !89, !tbaa !28
  %14 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %13, i64 0, i32 4, !dbg !89
  %15 = load i64*, i64** %14, align 8, !dbg !89, !tbaa !33
  %16 = getelementptr inbounds i64, i64* %15, i64 -4, !dbg !89
  %17 = load i64, i64* %16, align 8, !dbg !89, !tbaa !4
  store i64 %17, i64* %callArgs0Addr, align 8, !dbg !89
  %callArgs1Addr = getelementptr inbounds [2 x i64], [2 x i64]* %callArgs, i64 0, i64 1, !dbg !89
  store i64 %"rubyStr_ wasn't nil", i64* %callArgs1Addr, align 8, !dbg !89
  %18 = and i64 %17, 7, !dbg !89
  %19 = icmp ne i64 %18, 0, !dbg !89
  %20 = and i64 %17, -9, !dbg !89
  %21 = icmp eq i64 %20, 0, !dbg !89
  %22 = or i1 %19, %21, !dbg !89
  br i1 %22, label %29, label %23, !dbg !89

23:                                               ; preds = %9
  %24 = inttoptr i64 %17 to %struct.RBasic*, !dbg !89
  %25 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %24, i64 0, i32 0, !dbg !89
  %26 = load i64, i64* %25, align 8, !dbg !89, !tbaa !15
  %27 = and i64 %26, 31, !dbg !89
  %28 = icmp eq i64 %27, 5, !dbg !89
  br i1 %28, label %32, label %29, !dbg !89

29:                                               ; preds = %23, %9
  %30 = tail call i64 @rb_funcallv(i64 %17, i64 3217, i32 0, i64* null) #16, !dbg !89
  %31 = tail call i64 @rb_obj_as_string_result(i64 %30, i64 %17) #16, !dbg !89
  store i64 %31, i64* %callArgs0Addr, align 8, !dbg !89, !tbaa !4
  br label %32, !dbg !89

32:                                               ; preds = %29, %23
  %33 = and i64 %"rubyStr_ wasn't nil", 7, !dbg !89
  %34 = icmp ne i64 %33, 0, !dbg !89
  %35 = and i64 %"rubyStr_ wasn't nil", -9, !dbg !89
  %36 = icmp eq i64 %35, 0, !dbg !89
  %37 = or i1 %34, %36, !dbg !89
  br i1 %37, label %49, label %43, !dbg !89

38:                                               ; preds = %sorbet_stringInterpolate.exit
  %39 = getelementptr inbounds i64, i64* %64, i64 -7, !dbg !87
  store i64 %callFunc_puts, i64* %39, align 8, !dbg !87, !tbaa !4
  br label %sorbet_writeLocal.exit, !dbg !87

40:                                               ; preds = %sorbet_stringInterpolate.exit
  call fastcc void @vm_env_write_slowpath(i64* nonnull %64, i32 -7, i64 %callFunc_puts) #16, !dbg !87
  br label %sorbet_writeLocal.exit, !dbg !87

sorbet_writeLocal.exit:                           ; preds = %38, %40
  store i64* %0, i64** %pc, align 8, !dbg !87, !tbaa !17
  ret i64 52

41:                                               ; preds = %fastSymCallIntrinsic_T_must
  %42 = load i64, i64* @rb_eTypeError, align 8, !dbg !88, !tbaa !4, !noalias !90
  tail call void (i64, i8*, ...) @rb_raise(i64 %42, i8* getelementptr inbounds ([25 x i8], [25 x i8]* @.str.20, i64 0, i64 0)) #17, !dbg !88, !noalias !90
  unreachable, !dbg !88

43:                                               ; preds = %32
  %44 = inttoptr i64 %"rubyStr_ wasn't nil" to %struct.RBasic*, !dbg !89
  %45 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %44, i64 0, i32 0, !dbg !89
  %46 = load i64, i64* %45, align 8, !dbg !89, !tbaa !15
  %47 = and i64 %46, 31, !dbg !89
  %48 = icmp eq i64 %47, 5, !dbg !89
  br i1 %48, label %sorbet_stringInterpolate.exit, label %49, !dbg !89

49:                                               ; preds = %43, %32
  %50 = tail call i64 @rb_funcallv(i64 %"rubyStr_ wasn't nil", i64 3217, i32 0, i64* null) #16, !dbg !89
  %51 = tail call i64 @rb_obj_as_string_result(i64 %50, i64 %"rubyStr_ wasn't nil") #16, !dbg !89
  store i64 %51, i64* %callArgs1Addr, align 8, !dbg !89, !tbaa !4
  br label %sorbet_stringInterpolate.exit, !dbg !89

sorbet_stringInterpolate.exit:                    ; preds = %49, %43
  %52 = call i64 @rb_str_concat_literals(i32 2, i64* nonnull %callArgs0Addr) #16, !dbg !89
  store i64 %52, i64* %callArgs0Addr, align 8, !dbg !87
  %53 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !87, !tbaa !17
  %54 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %53, i64 0, i32 2, !dbg !87
  %55 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %54, align 8, !dbg !87, !tbaa !28
  %56 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %55, i64 0, i32 4, !dbg !87
  %57 = load i64*, i64** %56, align 8, !dbg !87, !tbaa !33
  %58 = getelementptr inbounds i64, i64* %57, i64 -5, !dbg !87
  %59 = load i64, i64* %58, align 8, !dbg !87, !tbaa !4
  %callFunc_puts = call i64 @sorbet_callFuncWithCache(i64 %59, i64 %rubyId_puts, i32 1, i64* nonnull %callArgs0Addr, %struct.FunctionInlineCache* nonnull @ic_callFunc_puts.4), !dbg !87
  %60 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !87, !tbaa !17
  %61 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %60, i64 0, i32 2, !dbg !87
  %62 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %61, align 8, !dbg !87, !tbaa !28
  %63 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %62, i64 0, i32 4, !dbg !87
  %64 = load i64*, i64** %63, align 8, !dbg !87, !tbaa !33
  %65 = load i64, i64* %64, align 8, !dbg !87, !tbaa !4
  %66 = and i64 %65, 8, !dbg !87
  %67 = icmp eq i64 %66, 0, !dbg !87
  br i1 %67, label %38, label %40, !dbg !87, !prof !51
}

; Function Attrs: nounwind ssp
define internal i64 @"func_Test.test_nilable_arg$block_2"(i64** nocapture readnone %pc, i64* nocapture readnone %iseq_encoded, i64 %localsOffset) #12 !dbg !93 {
.preheader.i29:
  %callArgs = alloca [2 x i64], align 8
  %"stackFrame_func_Test.test_nilable_arg$block_222" = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** bitcast (i8** @"stackFramePrecomputed_func_Test.test_nilable_arg$block_2" to %struct.rb_iseq_struct**), align 8
  %0 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !17
  %1 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %0, i64 0, i32 2
  %2 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %1, align 8, !tbaa !28
  tail call void @sorbet_setExceptionStackFrame(%struct.rb_execution_context_struct* %0, %struct.rb_control_frame_struct* %2, %struct.rb_iseq_struct* %"stackFrame_func_Test.test_nilable_arg$block_222") #16
  %3 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 0
  %4 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 2
  %5 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %4, align 8, !tbaa !31
  %6 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %5, i64 0, i32 2
  %7 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %6, align 8, !tbaa !34
  %8 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %7, i64 0, i32 2
  %9 = load i64*, i64** %8, align 8, !tbaa !36
  %"rubyId_is_a?" = load i64, i64* @"rubyIdPrecomputed_is_a?", align 8, !dbg !94
  %rubyId_puts = load i64, i64* @rubyIdPrecomputed_puts, align 8, !dbg !95
  %10 = getelementptr inbounds i64, i64* %9, i64 5
  store i64* %10, i64** %3, align 8, !tbaa !17
  %11 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !94, !tbaa !17
  %12 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %11, i64 0, i32 2, !dbg !94
  %13 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %12, align 8, !dbg !94, !tbaa !28
  %14 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %13, i64 0, i32 4, !dbg !94
  %15 = load i64*, i64** %14, align 8, !dbg !94, !tbaa !33
  %16 = getelementptr inbounds i64, i64* %15, i64 -1, !dbg !94
  %17 = load i64, i64* %16, align 8, !dbg !94, !tbaa !4
  %18 = and i64 %17, -4, !dbg !94
  %19 = inttoptr i64 %18 to i64*, !dbg !94
  %20 = getelementptr inbounds i64, i64* %19, i64 -3, !dbg !94
  %21 = load i64, i64* %20, align 8, !dbg !94, !tbaa !4
  %22 = load i64, i64* @rb_eStandardError, align 8, !dbg !94
  %callArgs0Addr = getelementptr inbounds [2 x i64], [2 x i64]* %callArgs, i64 0, i64 0, !dbg !94
  store i64 %22, i64* %callArgs0Addr, align 8, !dbg !94
  %"callFunc_is_a?" = call i64 @sorbet_callFuncWithCache(i64 %21, i64 %"rubyId_is_a?", i32 1, i64* nonnull %callArgs0Addr, %struct.FunctionInlineCache* nonnull @"ic_callFunc_is_a?.5"), !dbg !94
  %23 = and i64 %"callFunc_is_a?", -9, !dbg !94
  %24 = icmp eq i64 %23, 0, !dbg !94
  br i1 %24, label %.preheader.i, label %.preheader.i27, !dbg !94

blockExit:                                        ; preds = %83, %81, %67, %65
  %25 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !17
  tail call void @rb_vm_pop_frame(%struct.rb_execution_context_struct* %25) #16
  ret i64 52

.preheader.i27:                                   ; preds = %.preheader.i29
  %26 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !17
  %27 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %26, i64 0, i32 2
  %28 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %27, align 8, !tbaa !28
  %29 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %28, i64 0, i32 4
  %30 = load i64*, i64** %29, align 8, !tbaa !33
  %31 = getelementptr inbounds i64, i64* %30, i64 -1
  %32 = load i64, i64* %31, align 8, !tbaa !4
  %33 = and i64 %32, -4
  %34 = inttoptr i64 %33 to i64*
  %35 = load i64, i64* %34, align 8, !tbaa !4
  %36 = and i64 %35, 8
  %37 = icmp eq i64 %36, 0
  br i1 %37, label %38, label %40, !prof !51

38:                                               ; preds = %.preheader.i27
  %39 = getelementptr inbounds i64, i64* %34, i64 -3
  store i64 8, i64* %39, align 8, !tbaa !4
  br label %.preheader.i23

40:                                               ; preds = %.preheader.i27
  tail call fastcc void @vm_env_write_slowpath(i64* nonnull %34, i32 -3, i64 8) #16
  br label %.preheader.i23

.preheader.i23:                                   ; preds = %38, %40
  %41 = getelementptr inbounds i64, i64* %9, i64 6, !dbg !96
  store i64* %41, i64** %3, align 8, !dbg !96, !tbaa !17
  store i64 %21, i64* %callArgs0Addr, align 8, !dbg !95
  %42 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !95, !tbaa !17
  %43 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %42, i64 0, i32 2, !dbg !95
  %44 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %43, align 8, !dbg !95, !tbaa !28
  %45 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %44, i64 0, i32 4, !dbg !95
  %46 = load i64*, i64** %45, align 8, !dbg !95, !tbaa !33
  %47 = getelementptr inbounds i64, i64* %46, i64 -1, !dbg !95
  %48 = load i64, i64* %47, align 8, !dbg !95, !tbaa !4
  %49 = and i64 %48, -4, !dbg !95
  %50 = inttoptr i64 %49 to i64*, !dbg !95
  %51 = getelementptr inbounds i64, i64* %50, i64 -5, !dbg !95
  %52 = load i64, i64* %51, align 8, !dbg !95, !tbaa !4
  %callFunc_puts = call i64 @sorbet_callFuncWithCache(i64 %52, i64 %rubyId_puts, i32 1, i64* nonnull %callArgs0Addr, %struct.FunctionInlineCache* nonnull @ic_callFunc_puts.6), !dbg !95
  %53 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !95, !tbaa !17
  %54 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %53, i64 0, i32 2, !dbg !95
  %55 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %54, align 8, !dbg !95, !tbaa !28
  %56 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %55, i64 0, i32 4, !dbg !95
  %57 = load i64*, i64** %56, align 8, !dbg !95, !tbaa !33
  %58 = getelementptr inbounds i64, i64* %57, i64 -1, !dbg !95
  %59 = load i64, i64* %58, align 8, !dbg !95, !tbaa !4
  %60 = and i64 %59, -4, !dbg !95
  %61 = inttoptr i64 %60 to i64*, !dbg !95
  %62 = load i64, i64* %61, align 8, !dbg !95, !tbaa !4
  %63 = and i64 %62, 8, !dbg !95
  %64 = icmp eq i64 %63, 0, !dbg !95
  br i1 %64, label %65, label %67, !dbg !95, !prof !51

65:                                               ; preds = %.preheader.i23
  %66 = getelementptr inbounds i64, i64* %61, i64 -7, !dbg !95
  store i64 %callFunc_puts, i64* %66, align 8, !dbg !95, !tbaa !4
  br label %blockExit, !dbg !95

67:                                               ; preds = %.preheader.i23
  tail call fastcc void @vm_env_write_slowpath(i64* nonnull %61, i32 -7, i64 %callFunc_puts) #16, !dbg !95
  br label %blockExit, !dbg !95

.preheader.i:                                     ; preds = %.preheader.i29
  %68 = getelementptr inbounds i64, i64* %9, i64 3
  store i64* %68, i64** %3, align 8, !tbaa !17
  %69 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !97, !tbaa !17
  %70 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %69, i64 0, i32 2, !dbg !97
  %71 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %70, align 8, !dbg !97, !tbaa !28
  %72 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %71, i64 0, i32 4, !dbg !97
  %73 = load i64*, i64** %72, align 8, !dbg !97, !tbaa !33
  %74 = getelementptr inbounds i64, i64* %73, i64 -1, !dbg !97
  %75 = load i64, i64* %74, align 8, !dbg !97, !tbaa !4
  %76 = and i64 %75, -4, !dbg !97
  %77 = inttoptr i64 %76 to i64*, !dbg !97
  %78 = load i64, i64* %77, align 8, !dbg !97, !tbaa !4
  %79 = and i64 %78, 8, !dbg !97
  %80 = icmp eq i64 %79, 0, !dbg !97
  br i1 %80, label %81, label %83, !dbg !97, !prof !51

81:                                               ; preds = %.preheader.i
  %82 = getelementptr inbounds i64, i64* %77, i64 -8, !dbg !97
  store i64 20, i64* %82, align 8, !dbg !97, !tbaa !4
  br label %blockExit, !dbg !97

83:                                               ; preds = %.preheader.i
  tail call fastcc void @vm_env_write_slowpath(i64* nonnull %77, i32 -8, i64 20) #16, !dbg !97
  br label %blockExit, !dbg !97
}

; Function Attrs: cold minsize noreturn nounwind sspreq
define internal fastcc void @Init_t_must.cold.1(i64) unnamed_addr #14 {
newFuncRoot:
  tail call void @sorbet_cast_failure(i64 %0, i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_cast, i64 0, i64 0), i8* getelementptr inbounds ([19 x i8], [19 x i8]* @"str_T.class_of(<root>)", i64 0, i64 0)) #16, !dbg !50
  unreachable, !dbg !50
}

; Function Attrs: cold minsize noreturn nounwind sspreq uwtable
define internal fastcc void @func_Test.test_known_nil.cold.1(i64) unnamed_addr #15 {
newFuncRoot:
  tail call void @sorbet_cast_failure(i64 %0, i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_cast, i64 0, i64 0), i8* getelementptr inbounds ([17 x i8], [17 x i8]* @"str_T.class_of(Test)", i64 0, i64 0)), !dbg !63
  unreachable, !dbg !63
}

; Function Attrs: nofree norecurse nounwind ssp writeonly
define internal i64 @"func_Test.test_nilable_arg$block_4"(i64** nocapture, i64*, i64) #13 {
  %4 = getelementptr inbounds i64, i64* %1, i64 1
  store i64* %4, i64** %0, align 8, !tbaa !17
  ret i64 52
}

; Function Attrs: nounwind
declare void @llvm.assume(i1) #16

define linkonce void @const_recompute_Test() local_unnamed_addr {
  %1 = tail call i64 @sorbet_getConstant(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_Test, i64 0, i64 0), i64 4)
  store i64 %1, i64* @guarded_const_Test, align 8
  %2 = tail call i64 @sorbet_getConstantEpoch()
  store i64 %2, i64* @guard_epoch_Test, align 8
  ret void
}

attributes #0 = { nounwind ssp uwtable }
attributes #1 = { noreturn }
attributes #2 = { "addedToSilenceEmptyAttrsError" }
attributes #3 = { noinline nounwind ssp uwtable }
attributes #4 = { cold noreturn nounwind optsize ssp uwtable }
attributes #5 = { noreturn nounwind ssp uwtable }
attributes #6 = { argmemonly nounwind }
attributes #7 = { nounwind readnone }
attributes #8 = { alwaysinline norecurse nounwind readonly ssp uwtable }
attributes #9 = { nounwind sspreq }
attributes #10 = { nounwind sspreq uwtable }
attributes #11 = { noreturn nounwind ssp }
attributes #12 = { nounwind ssp }
attributes #13 = { nofree norecurse nounwind ssp writeonly }
attributes #14 = { cold minsize noreturn nounwind sspreq }
attributes #15 = { cold minsize noreturn nounwind sspreq uwtable }
attributes #16 = { nounwind }
attributes #17 = { noreturn nounwind }
attributes #18 = { noinline }

!llvm.module.flags = !{!0}
!llvm.dbg.cu = !{!1}

!0 = !{i32 2, !"Debug Info Version", i32 3}
!1 = distinct !DICompileUnit(language: DW_LANG_C, file: !2, producer: "Sorbet LLVM", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, enums: !3)
!2 = !DIFile(filename: "test/testdata/compiler/intrinsics/t_must.rb", directory: ".")
!3 = !{}
!4 = !{!5, !5, i64 0}
!5 = !{!"long", !6, i64 0}
!6 = !{!"omnipotent char", !7, i64 0}
!7 = !{!"Simple C/C++ TBAA"}
!8 = !{!9, !10, i64 0}
!9 = !{!"ExceptionClosure", !10, i64 0, !10, i64 8, !10, i64 16, !5, i64 24, !10, i64 32}
!10 = !{!"any pointer", !6, i64 0}
!11 = !{!9, !10, i64 8}
!12 = !{!9, !10, i64 16}
!13 = !{!9, !5, i64 24}
!14 = !{!9, !10, i64 32}
!15 = !{!16, !5, i64 0}
!16 = !{!"RBasic", !5, i64 0, !5, i64 8}
!17 = !{!10, !10, i64 0}
!18 = !{!19, !5, i64 400}
!19 = !{!"rb_vm_struct", !5, i64 0, !20, i64 8, !10, i64 192, !10, i64 200, !10, i64 208, !24, i64 216, !6, i64 224, !21, i64 264, !21, i64 280, !21, i64 296, !21, i64 312, !5, i64 328, !23, i64 336, !23, i64 340, !23, i64 340, !23, i64 340, !23, i64 340, !23, i64 344, !5, i64 352, !6, i64 360, !5, i64 400, !5, i64 408, !5, i64 416, !5, i64 424, !5, i64 432, !5, i64 440, !5, i64 448, !10, i64 456, !10, i64 464, !25, i64 472, !26, i64 1064, !10, i64 1088, !10, i64 1096, !23, i64 1104, !23, i64 1108, !21, i64 1112, !6, i64 1128, !5, i64 1168, !5, i64 1176, !5, i64 1184, !5, i64 1192, !5, i64 1200, !23, i64 1208, !5, i64 1216, !10, i64 1224, !10, i64 1232, !10, i64 1240, !10, i64 1248, !27, i64 1256, !6, i64 1288}
!20 = !{!"rb_global_vm_lock_struct", !10, i64 0, !6, i64 8, !21, i64 48, !10, i64 64, !23, i64 72, !6, i64 80, !6, i64 128, !23, i64 176, !23, i64 180}
!21 = !{!"list_head", !22, i64 0}
!22 = !{!"list_node", !10, i64 0, !10, i64 8}
!23 = !{!"int", !6, i64 0}
!24 = !{!"long long", !6, i64 0}
!25 = !{!"", !6, i64 0, !6, i64 520}
!26 = !{!"rb_hook_list_struct", !10, i64 0, !23, i64 8, !23, i64 12, !23, i64 16}
!27 = !{!"", !5, i64 0, !5, i64 8, !5, i64 16, !5, i64 24}
!28 = !{!29, !10, i64 16}
!29 = !{!"rb_execution_context_struct", !10, i64 0, !5, i64 8, !10, i64 16, !10, i64 24, !10, i64 32, !23, i64 40, !23, i64 44, !10, i64 48, !10, i64 56, !10, i64 64, !5, i64 72, !5, i64 80, !10, i64 88, !5, i64 96, !10, i64 104, !10, i64 112, !5, i64 120, !5, i64 128, !6, i64 136, !6, i64 137, !5, i64 144, !30, i64 152}
!30 = !{!"", !10, i64 0, !10, i64 8, !5, i64 16, !6, i64 24}
!31 = !{!32, !10, i64 16}
!32 = !{!"rb_control_frame_struct", !10, i64 0, !10, i64 8, !10, i64 16, !5, i64 24, !10, i64 32, !10, i64 40, !10, i64 48}
!33 = !{!32, !10, i64 32}
!34 = !{!35, !10, i64 16}
!35 = !{!"rb_iseq_struct", !5, i64 0, !5, i64 8, !10, i64 16, !6, i64 24}
!36 = !{!37, !10, i64 8}
!37 = !{!"rb_iseq_constant_body", !6, i64 0, !23, i64 4, !10, i64 8, !38, i64 16, !40, i64 64, !43, i64 120, !10, i64 152, !10, i64 160, !10, i64 168, !10, i64 176, !10, i64 184, !10, i64 192, !10, i64 200, !44, i64 208, !23, i64 240, !23, i64 244, !23, i64 248, !23, i64 252, !23, i64 256, !10, i64 264, !5, i64 272, !10, i64 280, !6, i64 288}
!38 = !{!"", !39, i64 0, !23, i64 4, !23, i64 8, !23, i64 12, !23, i64 16, !23, i64 20, !23, i64 24, !23, i64 28, !10, i64 32, !10, i64 40}
!39 = !{!"", !23, i64 0, !23, i64 0, !23, i64 0, !23, i64 0, !23, i64 0, !23, i64 0, !23, i64 0, !23, i64 0}
!40 = !{!"rb_iseq_location_struct", !5, i64 0, !5, i64 8, !5, i64 16, !5, i64 24, !23, i64 32, !41, i64 36}
!41 = !{!"rb_code_location_struct", !42, i64 0, !42, i64 8}
!42 = !{!"rb_code_position_struct", !23, i64 0, !23, i64 4}
!43 = !{!"iseq_insn_info", !10, i64 0, !10, i64 8, !23, i64 16, !10, i64 24}
!44 = !{!"", !5, i64 0, !5, i64 8, !5, i64 16, !10, i64 24}
!45 = !DILocation(line: 25, column: 1, scope: !46)
!46 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.<static-init>$153", scope: null, file: !2, line: 5, type: !47, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!47 = !DISubroutineType(types: !48)
!48 = !{!49}
!49 = !DIBasicType(name: "VALUE", size: 64, encoding: DW_ATE_signed)
!50 = !DILocation(line: 5, column: 1, scope: !46)
!51 = !{!"branch_weights", i32 2000, i32 1}
!52 = !DILocation(line: 24, column: 1, scope: !46)
!53 = !{!"branch_weights", i32 10000, i32 1}
!54 = !DILocation(line: 6, column: 3, scope: !55, inlinedAt: !56)
!55 = distinct !DISubprogram(name: "Test.<static-init>", linkageName: "func_Test.<static-init>L62", scope: null, file: !2, line: 5, type: !47, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!56 = distinct !DILocation(line: 5, column: 1, scope: !46)
!57 = !DILocation(line: 14, column: 3, scope: !55, inlinedAt: !56)
!58 = !DILocation(line: 5, column: 1, scope: !55, inlinedAt: !56)
!59 = !DILocation(line: 26, column: 1, scope: !46)
!60 = !DILocation(line: 27, column: 1, scope: !46)
!61 = distinct !DISubprogram(name: "Test.test_known_nil", linkageName: "func_Test.test_known_nil", scope: null, file: !2, line: 6, type: !47, scopeLine: 6, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!62 = !DILocation(line: 8, column: 7, scope: !61)
!63 = !DILocation(line: 6, column: 3, scope: !61)
!64 = !{!"branch_weights", i32 1073205, i32 2146410443}
!65 = !{!"branch_weights", i32 1, i32 2000}
!66 = !DILocation(line: 0, scope: !61)
!67 = distinct !DISubprogram(name: "Test.test_known_nil", linkageName: "func_Test.test_known_nil$block_1", scope: !61, file: !2, line: 6, type: !47, scopeLine: 6, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!68 = !DILocation(line: 8, column: 7, scope: !67)
!69 = !{!70}
!70 = distinct !{!70, !71, !"sorbet_T_must: argument 0"}
!71 = distinct !{!71, !"sorbet_T_must"}
!72 = distinct !DISubprogram(name: "Test.test_known_nil", linkageName: "func_Test.test_known_nil$block_2", scope: !61, file: !2, line: 6, type: !47, scopeLine: 6, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!73 = !DILocation(line: 9, column: 15, scope: !72)
!74 = !DILocation(line: 10, column: 7, scope: !72)
!75 = !DILocation(line: 9, column: 5, scope: !72)
!76 = !DILocation(line: 8, column: 7, scope: !72)
!77 = distinct !DISubprogram(name: "Test.test_known_nil", linkageName: "func_Test.test_known_nil$block_4", scope: !61, file: !2, line: 6, type: !47, scopeLine: 6, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!78 = distinct !DISubprogram(name: "Test.test_nilable_arg", linkageName: "func_Test.test_nilable_arg", scope: null, file: !2, line: 14, type: !47, scopeLine: 14, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!79 = !DILocation(line: 16, column: 7, scope: !78)
!80 = !DILocation(line: 14, column: 3, scope: !78)
!81 = !{!"branch_weights", i32 4000000, i32 4001}
!82 = !DILocation(line: 0, scope: !78)
!83 = !DILocation(line: 6, column: 3, scope: !61, inlinedAt: !84)
!84 = distinct !DILocation(line: 14, column: 3, scope: !78)
!85 = distinct !DISubprogram(name: "Test.test_nilable_arg", linkageName: "func_Test.test_nilable_arg$block_1", scope: !78, file: !2, line: 14, type: !47, scopeLine: 14, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!86 = !DILocation(line: 17, column: 19, scope: !85)
!87 = !DILocation(line: 17, column: 7, scope: !85)
!88 = !DILocation(line: 16, column: 7, scope: !85)
!89 = !DILocation(line: 17, column: 12, scope: !85)
!90 = !{!91}
!91 = distinct !{!91, !92, !"sorbet_T_must: argument 0"}
!92 = distinct !{!92, !"sorbet_T_must"}
!93 = distinct !DISubprogram(name: "Test.test_nilable_arg", linkageName: "func_Test.test_nilable_arg$block_2", scope: !78, file: !2, line: 14, type: !47, scopeLine: 14, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!94 = !DILocation(line: 18, column: 15, scope: !93)
!95 = !DILocation(line: 19, column: 7, scope: !93)
!96 = !DILocation(line: 18, column: 5, scope: !93)
!97 = !DILocation(line: 16, column: 7, scope: !93)
