; ModuleID = 'payload'
source_filename = "llvm-link"
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"

%struct.rb_execution_context_struct = type { i64*, i64, %struct.rb_control_frame_struct*, %struct.rb_vm_tag*, %struct.rb_vm_protect_tag*, i32, i32, %struct.rb_fiber_struct*, %struct.rb_thread_struct*, %struct.st_table*, i64, i64, i64*, i64, %struct.rb_ensure_list*, %struct.rb_trace_arg_struct*, i64, i64, i8, i8, i64, %struct.anon.5 }
%struct.rb_control_frame_struct = type { i64*, i64*, %struct.rb_iseq_struct*, i64, i64*, i8*, i64* }
%struct.rb_iseq_struct = type { i64, i64, %struct.rb_iseq_constant_body*, %union.anon.12 }
%struct.rb_iseq_constant_body = type { i32, i32, i64*, %struct.anon, %struct.rb_iseq_location_struct, %struct.iseq_insn_info, i64*, %struct.iseq_catch_table*, %struct.rb_iseq_struct*, %struct.rb_iseq_struct*, %union.iseq_inline_storage_entry*, %struct.rb_call_data*, %struct.anon.11, i32, i32, i32, i32, i32, i8, i64 (%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*)*, i64, %struct.rb_mjit_unit*, i64 }
%struct.anon = type { %struct.anon.0, i32, i32, i32, i32, i32, i32, i32, i64*, %struct.rb_iseq_param_keyword* }
%struct.anon.0 = type { i16, [2 x i8] }
%struct.rb_iseq_param_keyword = type { i32, i32, i32, i32, i64*, i64* }
%struct.rb_iseq_location_struct = type { i64, i64, i64, i64, i32, %struct.rb_code_location_struct }
%struct.rb_code_location_struct = type { %struct.rb_code_position_struct, %struct.rb_code_position_struct }
%struct.rb_code_position_struct = type { i32, i32 }
%struct.iseq_insn_info = type { %struct.iseq_insn_info_entry*, i32*, i32, %struct.succ_index_table* }
%struct.iseq_insn_info_entry = type opaque
%struct.succ_index_table = type opaque
%struct.iseq_catch_table = type opaque
%union.iseq_inline_storage_entry = type { %struct.iseq_inline_cache_entry }
%struct.iseq_inline_cache_entry = type { i64, %struct.rb_cref_struct*, i64 }
%struct.rb_cref_struct = type { i64, i64, i64, %struct.rb_cref_struct*, %struct.rb_scope_visi_struct }
%struct.rb_scope_visi_struct = type { i8, [3 x i8] }
%struct.rb_call_data = type { %struct.rb_call_cache, %struct.rb_call_info }
%struct.rb_call_cache = type { i64, [3 x i64], %struct.rb_callable_method_entry_struct*, i64, i64 (%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_calling_info*, %struct.rb_call_data*)*, %union.anon.15 }
%struct.rb_callable_method_entry_struct = type { i64, i64, %struct.rb_method_definition_struct*, i64, i64 }
%struct.rb_method_definition_struct = type { i64, %union.anon, i64, i64 }
%union.anon = type { %struct.rb_method_cfunc_struct }
%struct.rb_method_cfunc_struct = type { i64 (...)*, i64 (i64, i32, i64*, i64 (...)*)*, i32 }
%struct.rb_calling_info = type { i64, i64, i32, i32 }
%union.anon.15 = type { i32 }
%struct.rb_call_info = type { i64, i32, i32 }
%struct.anon.11 = type { i64, i64, i64, i64* }
%struct.rb_mjit_unit = type opaque
%union.anon.12 = type { %struct.anon.13 }
%struct.anon.13 = type { i64, i32 }
%struct.rb_vm_tag = type { i64, i64, [5 x i8*], %struct.rb_vm_tag*, i32 }
%struct.rb_vm_protect_tag = type { %struct.rb_vm_protect_tag* }
%struct.rb_fiber_struct = type opaque
%struct.rb_thread_struct = type { %struct.list_node, i64, %struct.rb_vm_struct*, %struct.rb_execution_context_struct*, i64, %struct.rb_calling_info*, i64, i64, i64, i8, i8, i32, %struct.native_thread_data_struct, i8*, i64, i64, i64, i64, %union.pthread_mutex_t, %struct.rb_unblock_callback, i64, %struct.rb_mutex_struct*, %struct.rb_thread_list_struct*, %union.anon.8, i32, i64, %struct.rb_fiber_struct*, [5 x i8*], i64 }
%struct.list_node = type { %struct.list_node*, %struct.list_node* }
%struct.rb_vm_struct = type { i64, %struct.rb_global_vm_lock_struct, %struct.rb_thread_struct*, %struct.rb_thread_struct*, i8*, i64, %union.pthread_mutex_t, %struct.list_head, %struct.list_head, %struct.list_head, %struct.list_head, i64, i32, i32, i8, i32, i64, [5 x i64], i64, i64, i64, i64, i64, i64, i64, %struct.st_table*, %struct.st_table*, %struct.anon.3, %struct.rb_hook_list_struct, %struct.st_table*, %struct.rb_postponed_job_struct*, i32, i32, %struct.list_head, %union.pthread_mutex_t, i64, i64, i64, i64, i64, i32, %struct.st_table*, %struct.rb_objspace*, %struct.rb_at_exit_list*, i64*, %struct.st_table*, %struct.rb_builtin_function*, i32, %struct.anon.4, [29 x i16] }
%struct.rb_global_vm_lock_struct = type { %struct.rb_thread_struct*, %union.pthread_mutex_t, %struct.list_head, %struct.rb_thread_struct*, i32, %union.pthread_cond_t, %union.pthread_cond_t, i32, i32 }
%union.pthread_cond_t = type { %struct.anon.2 }
%struct.anon.2 = type { i32, i32, i64, i64, i64, i8*, i32, i32 }
%struct.anon.3 = type { [65 x i64] }
%struct.rb_hook_list_struct = type { %struct.rb_event_hook_struct*, i32, i32, i32 }
%struct.rb_event_hook_struct = type opaque
%struct.rb_postponed_job_struct = type opaque
%struct.list_head = type { %struct.list_node }
%struct.rb_objspace = type opaque
%struct.rb_at_exit_list = type { void (%struct.rb_vm_struct*)*, %struct.rb_at_exit_list* }
%struct.rb_builtin_function = type opaque
%struct.anon.4 = type { i64, i64, i64, i64 }
%struct.native_thread_data_struct = type { %struct.list_head, %union.anon.7 }
%union.anon.7 = type { %union.pthread_cond_t }
%union.pthread_mutex_t = type { %struct.__pthread_mutex_s }
%struct.__pthread_mutex_s = type { i32, i32, i32, i32, i32, i16, i16, %struct.__pthread_internal_list }
%struct.__pthread_internal_list = type { %struct.__pthread_internal_list*, %struct.__pthread_internal_list* }
%struct.rb_unblock_callback = type { void (i8*)*, i8* }
%struct.rb_mutex_struct = type opaque
%struct.rb_thread_list_struct = type { %struct.rb_thread_list_struct*, %struct.rb_thread_struct* }
%union.anon.8 = type { %struct.anon.9 }
%struct.anon.9 = type { i64, i64, i32 }
%struct.st_table = type { i8, i8, i8, i32, %struct.st_hash_type*, i64, i64*, i64, i64, %struct.st_table_entry* }
%struct.st_hash_type = type { i32 (i64, i64)*, i64 (i64)* }
%struct.st_table_entry = type opaque
%struct.rb_ensure_list = type { %struct.rb_ensure_list*, %struct.rb_ensure_entry }
%struct.rb_ensure_entry = type { i64, i64 (i64)*, i64 }
%struct.rb_trace_arg_struct = type { i32, %struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, i64, i64, i64, i64, i64, i32, i32, i64 }
%struct.anon.5 = type { i64*, i64*, i64, [1 x %struct.__jmp_buf_tag] }
%struct.__jmp_buf_tag = type { [8 x i64], i32, %struct.__sigset_t }
%struct.__sigset_t = type { [16 x i64] }
%struct.FunctionInlineCache = type { %struct.rb_kwarg_call_data }
%struct.rb_kwarg_call_data = type { %struct.rb_call_cache, %struct.rb_call_info_with_kwarg }
%struct.rb_call_info_with_kwarg = type { %struct.rb_call_info, %struct.rb_call_info_kw_arg* }
%struct.rb_call_info_kw_arg = type { i32, [1 x i64] }
%struct.ExceptionClosure = type { i64 (i64**, i64*, i64)*, i64**, i64*, i64, i64* }

@ruby_vm_global_constant_state = external local_unnamed_addr global i64, align 8
@rb_eTypeError = external local_unnamed_addr global i64, align 8
@.str.2 = private unnamed_addr constant [25 x i8] c"Passed `nil` into T.must\00", align 1
@ruby_current_execution_context_ptr = external local_unnamed_addr global %struct.rb_execution_context_struct*, align 8
@rb_eRuntimeError = external local_unnamed_addr global i64, align 8
@sorbet_getTRetry.retry = internal constant [25 x i8] c"T::Private::Retry::RETRY\00", align 16
@rb_eException = external local_unnamed_addr global i64, align 8
@.str.7 = private unnamed_addr constant [95 x i8] c"sorbet_getBuildSCMRevision: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@.str.8 = private unnamed_addr constant [93 x i8] c"sorbet_getIsReleaseBuild: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@"stackFramePrecomputed_func_<root>.<static-init>$152" = internal unnamed_addr global i8* null, align 8
@"rubyIdPrecomputed_<top (required)>" = internal unnamed_addr global i64 0, align 8
@"str_<top (required)>" = private unnamed_addr constant [17 x i8] c"<top (required)>\00", align 1
@"rubyStrFrozen_<top (required)>" = internal unnamed_addr global i64 0, align 8
@"rubyStrFrozen_test/testdata/compiler/intrinsics/t_must.rb" = internal unnamed_addr global i64 0, align 8
@"str_test/testdata/compiler/intrinsics/t_must.rb" = private unnamed_addr constant [44 x i8] c"test/testdata/compiler/intrinsics/t_must.rb\00", align 1
@str_Test = private unnamed_addr constant [5 x i8] c"Test\00", align 1
@ic_test_known_nil = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_test_known_nil = internal unnamed_addr global i64 0, align 8
@str_test_known_nil = private unnamed_addr constant [15 x i8] c"test_known_nil\00", align 1
@ic_test_nilable_arg = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_test_nilable_arg = internal unnamed_addr global i64 0, align 8
@str_test_nilable_arg = private unnamed_addr constant [17 x i8] c"test_nilable_arg\00", align 1
@ic_test_nilable_arg.1 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_test_nilable_arg.2 = internal global %struct.FunctionInlineCache zeroinitializer
@stackFramePrecomputed_func_Test.test_known_nil = internal unnamed_addr global i8* null, align 8
@"rubyIdPrecomputed_<exceptionValue>" = internal unnamed_addr global i64 0, align 8
@"str_<exceptionValue>" = private unnamed_addr constant [17 x i8] c"<exceptionValue>\00", align 1
@"rubyIdPrecomputed_<magic>" = internal unnamed_addr global i64 0, align 8
@"str_<magic>" = private unnamed_addr constant [8 x i8] c"<magic>\00", align 1
@"rubyIdPrecomputed_<returnMethodTemp>" = internal unnamed_addr global i64 0, align 8
@"str_<returnMethodTemp>" = private unnamed_addr constant [19 x i8] c"<returnMethodTemp>\00", align 1
@"rubyIdPrecomputed_<self>" = internal unnamed_addr global i64 0, align 8
@"str_<self>" = private unnamed_addr constant [7 x i8] c"<self>\00", align 1
@"rubyIdPrecomputed_<gotoDeadTemp>" = internal unnamed_addr global i64 0, align 8
@"str_<gotoDeadTemp>" = private unnamed_addr constant [15 x i8] c"<gotoDeadTemp>\00", align 1
@"stackFramePrecomputed_func_Test.test_known_nil$block_2" = internal unnamed_addr global i8* null, align 8
@"rubyIdPrecomputed_rescue for" = internal unnamed_addr global i64 0, align 8
@"str_rescue for" = private unnamed_addr constant [11 x i8] c"rescue for\00", align 1
@"rubyStrFrozen_rescue for" = internal unnamed_addr global i64 0, align 8
@"stackFramePrecomputed_func_Test.test_known_nil$block_3" = internal unnamed_addr global i8* null, align 8
@"rubyIdPrecomputed_ensure for" = internal unnamed_addr global i64 0, align 8
@"str_ensure for" = private unnamed_addr constant [11 x i8] c"ensure for\00", align 1
@"rubyStrFrozen_ensure for" = internal unnamed_addr global i64 0, align 8
@"<retry-singleton>" = internal unnamed_addr global i64 0
@rubyIdPrecomputed_must = internal unnamed_addr global i64 0, align 8
@str_must = private unnamed_addr constant [5 x i8] c"must\00", align 1
@ic_must = internal global %struct.FunctionInlineCache zeroinitializer
@"ic_is_a?" = internal global %struct.FunctionInlineCache zeroinitializer
@"rubyIdPrecomputed_is_a?" = internal unnamed_addr global i64 0, align 8
@"str_is_a?" = private unnamed_addr constant [6 x i8] c"is_a?\00", align 1
@ic_puts = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_puts = internal unnamed_addr global i64 0, align 8
@str_puts = private unnamed_addr constant [5 x i8] c"puts\00", align 1
@stackFramePrecomputed_func_Test.test_nilable_arg = internal unnamed_addr global i8* null, align 8
@rubyIdPrecomputed_arg = internal unnamed_addr global i64 0, align 8
@str_arg = private unnamed_addr constant [4 x i8] c"arg\00", align 1
@"stackFramePrecomputed_func_Test.test_nilable_arg$block_2" = internal unnamed_addr global i8* null, align 8
@"stackFramePrecomputed_func_Test.test_nilable_arg$block_3" = internal unnamed_addr global i8* null, align 8
@ic_must.3 = internal global %struct.FunctionInlineCache zeroinitializer
@"rubyStrFrozen_ wasn't nil" = internal unnamed_addr global i64 0, align 8
@"str_ wasn't nil" = private unnamed_addr constant [12 x i8] c" wasn't nil\00", align 1
@"rubyIdPrecomputed_<string-interpolate>" = internal unnamed_addr global i64 0, align 8
@"str_<string-interpolate>" = private unnamed_addr constant [21 x i8] c"<string-interpolate>\00", align 1
@ic_puts.4 = internal global %struct.FunctionInlineCache zeroinitializer
@"ic_is_a?.5" = internal global %struct.FunctionInlineCache zeroinitializer
@ic_puts.6 = internal global %struct.FunctionInlineCache zeroinitializer
@"stackFramePrecomputed_func_Test.<static-init>" = internal unnamed_addr global i8* null, align 8
@"<static-init-locals-storage>.7" = internal global [0 x i64] zeroinitializer
@rubyIdPrecomputed_normal = internal unnamed_addr global i64 0, align 8
@str_normal = private unnamed_addr constant [7 x i8] c"normal\00", align 1
@ic_keep_self_def = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_keep_self_def = internal unnamed_addr global i64 0, align 8
@str_keep_self_def = private unnamed_addr constant [14 x i8] c"keep_self_def\00", align 1
@ic_keep_self_def.8 = internal global %struct.FunctionInlineCache zeroinitializer
@guard_epoch_Test = linkonce local_unnamed_addr global i64 0
@guarded_const_Test = linkonce local_unnamed_addr global i64 0
@rb_eStandardError = external local_unnamed_addr constant i64

; Function Attrs: noreturn
declare void @sorbet_raiseArity(i32, i32, i32) local_unnamed_addr #0

declare i8* @sorbet_allocateRubyStackFrame(i64, i64, i64, i64, i8*, i32, i32, i32, i64*, i32, i32) local_unnamed_addr #1

declare i64 @sorbet_getConstant(i8*, i64) local_unnamed_addr #1

declare i64 @sorbet_readRealpath() local_unnamed_addr #1

declare void @sorbet_popRubyStack() local_unnamed_addr #1

declare void @sorbet_vm_env_write_slowpath(i64*, i32, i64) local_unnamed_addr #1

declare void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache*, i64, i32, i32, i32, i64*) local_unnamed_addr #1

declare i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache*, i64) local_unnamed_addr #1

declare void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_iseq_struct*) local_unnamed_addr #1

declare void @sorbet_setExceptionStackFrame(%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_iseq_struct*) local_unnamed_addr #1

declare i64 @sorbet_stringInterpolate(i64, i64, i32, i64*, i64 (i64, i64, i32, i64*, i64)*, i64) local_unnamed_addr #1

declare i64 @rb_define_module(i8*) local_unnamed_addr #1

declare extern_weak void @rb_define_singleton_method(i64, i8*, i64 (...)*, i32) local_unnamed_addr #1

declare i64 @rb_intern2(i8*, i64) local_unnamed_addr #1

declare i64 @rb_id2sym(i64) local_unnamed_addr #1

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #2

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.end.p0i8(i64 immarg, i8* nocapture) #2

declare i64 @rb_fstring_new(i8*, i64) local_unnamed_addr #1

declare void @rb_gc_register_mark_object(i64) local_unnamed_addr #1

; Function Attrs: noreturn
declare void @rb_raise(i64, i8*, ...) local_unnamed_addr #0

declare void @rb_set_errinfo(i64) local_unnamed_addr #1

; Function Attrs: nounwind ssp uwtable
define internal i64 @sorbet_applyExceptionClosure(i64) #3 {
  %2 = inttoptr i64 %0 to %struct.ExceptionClosure*
  %3 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %2, i64 0, i32 0
  %4 = load i64 (i64**, i64*, i64)*, i64 (i64**, i64*, i64)** %3, align 8, !tbaa !4
  %5 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %2, i64 0, i32 1
  %6 = load i64**, i64*** %5, align 8, !tbaa !10
  %7 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %2, i64 0, i32 2
  %8 = load i64*, i64** %7, align 8, !tbaa !11
  %9 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %2, i64 0, i32 3
  %10 = load i64, i64* %9, align 8, !tbaa !12
  %11 = tail call i64 %4(i64** %6, i64* %8, i64 %10) #10
  %12 = icmp eq i64 %11, 52
  br i1 %12, label %16, label %13

13:                                               ; preds = %1
  %14 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %2, i64 0, i32 4
  %15 = load i64*, i64** %14, align 8, !tbaa !13
  store i64 %11, i64* %15, align 8, !tbaa !14
  br label %16

16:                                               ; preds = %13, %1
  ret i64 52
}

; Function Attrs: nofree norecurse nounwind ssp uwtable writeonly
define internal i64 @sorbet_rescueStoreException(i64, i64) #4 {
  %3 = inttoptr i64 %0 to i64*
  store i64 %1, i64* %3, align 8, !tbaa !14
  ret i64 52
}

declare i64 @rb_rescue2(i64 (i64)*, i64, i64 (i64, i64)*, i64, ...) local_unnamed_addr #1

; Function Attrs: noreturn
declare void @rb_exc_raise(i64) local_unnamed_addr #0

; Function Attrs: nounwind ssp uwtable
define weak i32 @sorbet_getIsReleaseBuild() local_unnamed_addr #3 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !14
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* getelementptr inbounds ([93 x i8], [93 x i8]* @.str.8, i64 0, i64 0)) #11
  unreachable
}

; Function Attrs: nounwind ssp uwtable
define weak i8* @sorbet_getBuildSCMRevision() local_unnamed_addr #3 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !14
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* getelementptr inbounds ([95 x i8], [95 x i8]* @.str.7, i64 0, i64 0)) #11
  unreachable
}

declare i64 @rb_errinfo() local_unnamed_addr #1

; Function Attrs: sspreq
define void @Init_t_must() local_unnamed_addr #5 {
entry:
  %locals1.i26.i = alloca [6 x i64], align 8
  %locals1.i.i = alloca [5 x i64], align 8
  %realpath = tail call i64 @sorbet_readRealpath()
  %0 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 16) #10
  store i64 %0, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %1 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([15 x i8], [15 x i8]* @str_test_known_nil, i64 0, i64 0), i64 14) #10
  store i64 %1, i64* @rubyIdPrecomputed_test_known_nil, align 8
  %2 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([17 x i8], [17 x i8]* @str_test_nilable_arg, i64 0, i64 0), i64 16) #10
  store i64 %2, i64* @rubyIdPrecomputed_test_nilable_arg, align 8
  %3 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<exceptionValue>", i64 0, i64 0), i64 16) #10
  store i64 %3, i64* @"rubyIdPrecomputed_<exceptionValue>", align 8
  %4 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([8 x i8], [8 x i8]* @"str_<magic>", i64 0, i64 0), i64 7) #10
  store i64 %4, i64* @"rubyIdPrecomputed_<magic>", align 8
  %5 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([19 x i8], [19 x i8]* @"str_<returnMethodTemp>", i64 0, i64 0), i64 18) #10
  store i64 %5, i64* @"rubyIdPrecomputed_<returnMethodTemp>", align 8
  %6 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([7 x i8], [7 x i8]* @"str_<self>", i64 0, i64 0), i64 6) #10
  store i64 %6, i64* @"rubyIdPrecomputed_<self>", align 8
  %7 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([15 x i8], [15 x i8]* @"str_<gotoDeadTemp>", i64 0, i64 0), i64 14) #10
  store i64 %7, i64* @"rubyIdPrecomputed_<gotoDeadTemp>", align 8
  %8 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([11 x i8], [11 x i8]* @"str_rescue for", i64 0, i64 0), i64 10) #10
  store i64 %8, i64* @"rubyIdPrecomputed_rescue for", align 8
  %9 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([11 x i8], [11 x i8]* @"str_ensure for", i64 0, i64 0), i64 10) #10
  store i64 %9, i64* @"rubyIdPrecomputed_ensure for", align 8
  %10 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_must, i64 0, i64 0), i64 4) #10
  store i64 %10, i64* @rubyIdPrecomputed_must, align 8
  %11 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([6 x i8], [6 x i8]* @"str_is_a?", i64 0, i64 0), i64 5) #10
  store i64 %11, i64* @"rubyIdPrecomputed_is_a?", align 8
  %12 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_puts, i64 0, i64 0), i64 4) #10
  store i64 %12, i64* @rubyIdPrecomputed_puts, align 8
  %13 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_arg, i64 0, i64 0), i64 3) #10
  store i64 %13, i64* @rubyIdPrecomputed_arg, align 8
  %14 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([21 x i8], [21 x i8]* @"str_<string-interpolate>", i64 0, i64 0), i64 20) #10
  store i64 %14, i64* @"rubyIdPrecomputed_<string-interpolate>", align 8
  %15 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([7 x i8], [7 x i8]* @str_normal, i64 0, i64 0), i64 6) #10
  store i64 %15, i64* @rubyIdPrecomputed_normal, align 8
  %16 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([14 x i8], [14 x i8]* @str_keep_self_def, i64 0, i64 0), i64 13) #10
  store i64 %16, i64* @rubyIdPrecomputed_keep_self_def, align 8
  %17 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 16) #10
  tail call void @rb_gc_register_mark_object(i64 %17) #10
  store i64 %17, i64* @"rubyStrFrozen_<top (required)>", align 8
  %18 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([44 x i8], [44 x i8]* @"str_test/testdata/compiler/intrinsics/t_must.rb", i64 0, i64 0), i64 43) #10
  tail call void @rb_gc_register_mark_object(i64 %18) #10
  store i64 %18, i64* @"rubyStrFrozen_test/testdata/compiler/intrinsics/t_must.rb", align 8
  %"rubyId_<top (required)>.i.i" = load i64, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %"rubyStr_<top (required)>.i.i" = load i64, i64* @"rubyStrFrozen_<top (required)>", align 8
  %19 = tail call i8* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_<top (required)>.i.i", i64 %"rubyId_<top (required)>.i.i", i64 %18, i64 %realpath, i8* null, i32 1, i32 1, i32 27, i64* getelementptr inbounds ([0 x i64], [0 x i64]* @"<static-init-locals-storage>.7", i64 0, i64 0), i32 0, i32 2)
  store i8* %19, i8** @"stackFramePrecomputed_func_<root>.<static-init>$152", align 8
  %rubyId_test_known_nil.i = load i64, i64* @rubyIdPrecomputed_test_known_nil, align 8, !dbg !15
  tail call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_test_known_nil, i64 %rubyId_test_known_nil.i, i32 16, i32 0, i32 0, i64* null), !dbg !15
  %rubyId_test_nilable_arg.i = load i64, i64* @rubyIdPrecomputed_test_nilable_arg, align 8, !dbg !20
  tail call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_test_nilable_arg, i64 %rubyId_test_nilable_arg.i, i32 16, i32 1, i32 0, i64* null), !dbg !20
  %rubyId_test_nilable_arg2.i = load i64, i64* @rubyIdPrecomputed_test_nilable_arg, align 8, !dbg !21
  tail call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_test_nilable_arg.1, i64 %rubyId_test_nilable_arg2.i, i32 16, i32 1, i32 0, i64* null), !dbg !21
  %rubyId_test_nilable_arg4.i = load i64, i64* @rubyIdPrecomputed_test_nilable_arg, align 8, !dbg !22
  tail call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_test_nilable_arg.2, i64 %rubyId_test_nilable_arg4.i, i32 16, i32 1, i32 0, i64* null), !dbg !22
  %20 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([15 x i8], [15 x i8]* @str_test_known_nil, i64 0, i64 0), i64 14) #10
  tail call void @rb_gc_register_mark_object(i64 %20) #10
  %21 = bitcast [5 x i64]* %locals1.i.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 40, i8* nonnull %21)
  %rubyId_test_known_nil.i.i = load i64, i64* @rubyIdPrecomputed_test_known_nil, align 8
  %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i21.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/intrinsics/t_must.rb", align 8
  %locals1.sub.i.i = getelementptr inbounds [5 x i64], [5 x i64]* %locals1.i.i, i64 0, i64 0
  %"rubyId_<exceptionValue>.i.i" = load i64, i64* @"rubyIdPrecomputed_<exceptionValue>", align 8
  store i64 %"rubyId_<exceptionValue>.i.i", i64* %locals1.sub.i.i, align 8
  %"rubyId_<magic>.i.i" = load i64, i64* @"rubyIdPrecomputed_<magic>", align 8
  %22 = getelementptr inbounds [5 x i64], [5 x i64]* %locals1.i.i, i64 0, i64 1
  store i64 %"rubyId_<magic>.i.i", i64* %22, align 8
  %"rubyId_<returnMethodTemp>.i.i" = load i64, i64* @"rubyIdPrecomputed_<returnMethodTemp>", align 8
  %23 = getelementptr inbounds [5 x i64], [5 x i64]* %locals1.i.i, i64 0, i64 2
  store i64 %"rubyId_<returnMethodTemp>.i.i", i64* %23, align 8
  %"rubyId_<self>.i.i" = load i64, i64* @"rubyIdPrecomputed_<self>", align 8
  %24 = getelementptr inbounds [5 x i64], [5 x i64]* %locals1.i.i, i64 0, i64 3
  store i64 %"rubyId_<self>.i.i", i64* %24, align 8
  %"rubyId_<gotoDeadTemp>.i.i" = load i64, i64* @"rubyIdPrecomputed_<gotoDeadTemp>", align 8
  %25 = getelementptr inbounds [5 x i64], [5 x i64]* %locals1.i.i, i64 0, i64 4
  store i64 %"rubyId_<gotoDeadTemp>.i.i", i64* %25, align 8
  %26 = call i8* @sorbet_allocateRubyStackFrame(i64 %20, i64 %rubyId_test_known_nil.i.i, i64 %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i21.i", i64 %realpath, i8* null, i32 1, i32 6, i32 12, i64* nonnull %locals1.sub.i.i, i32 5, i32 2)
  store i8* %26, i8** @stackFramePrecomputed_func_Test.test_known_nil, align 8
  call void @llvm.lifetime.end.p0i8(i64 40, i8* nonnull %21)
  %27 = call i64 @rb_fstring_new(i8* getelementptr inbounds ([11 x i8], [11 x i8]* @"str_rescue for", i64 0, i64 0), i64 10) #10
  call void @rb_gc_register_mark_object(i64 %27) #10
  store i64 %27, i64* @"rubyStrFrozen_rescue for", align 8
  %stackFrame_func_Test.test_known_nil.i.i = load i8*, i8** @stackFramePrecomputed_func_Test.test_known_nil, align 8
  %"rubyId_rescue for.i.i" = load i64, i64* @"rubyIdPrecomputed_rescue for", align 8
  %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i22.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/intrinsics/t_must.rb", align 8
  %28 = call i8* @sorbet_allocateRubyStackFrame(i64 %27, i64 %"rubyId_rescue for.i.i", i64 %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i22.i", i64 %realpath, i8* %stackFrame_func_Test.test_known_nil.i.i, i32 4, i32 6, i32 12, i64* null, i32 0, i32 2)
  store i8* %28, i8** @"stackFramePrecomputed_func_Test.test_known_nil$block_2", align 8
  %29 = call i64 @rb_fstring_new(i8* getelementptr inbounds ([11 x i8], [11 x i8]* @"str_ensure for", i64 0, i64 0), i64 10) #10
  call void @rb_gc_register_mark_object(i64 %29) #10
  store i64 %29, i64* @"rubyStrFrozen_ensure for", align 8
  %stackFrame_func_Test.test_known_nil.i23.i = load i8*, i8** @stackFramePrecomputed_func_Test.test_known_nil, align 8
  %"rubyId_ensure for.i.i" = load i64, i64* @"rubyIdPrecomputed_ensure for", align 8
  %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i24.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/intrinsics/t_must.rb", align 8
  %30 = call i8* @sorbet_allocateRubyStackFrame(i64 %29, i64 %"rubyId_ensure for.i.i", i64 %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i24.i", i64 %realpath, i8* %stackFrame_func_Test.test_known_nil.i23.i, i32 5, i32 6, i32 12, i64* null, i32 0, i32 2)
  store i8* %30, i8** @"stackFramePrecomputed_func_Test.test_known_nil$block_3", align 8
  %31 = call i64 @sorbet_getConstant(i8* getelementptr inbounds ([25 x i8], [25 x i8]* @sorbet_getTRetry.retry, i64 0, i64 0), i64 25) #10
  store i64 %31, i64* @"<retry-singleton>", align 8
  %rubyId_must.i = load i64, i64* @rubyIdPrecomputed_must, align 8, !dbg !23
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_must, i64 %rubyId_must.i, i32 16, i32 1, i32 0, i64* null), !dbg !23
  %"rubyId_is_a?.i" = load i64, i64* @"rubyIdPrecomputed_is_a?", align 8, !dbg !26
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @"ic_is_a?", i64 %"rubyId_is_a?.i", i32 16, i32 1, i32 0, i64* null), !dbg !26
  %rubyId_puts.i = load i64, i64* @rubyIdPrecomputed_puts, align 8, !dbg !28
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_puts, i64 %rubyId_puts.i, i32 16, i32 1, i32 0, i64* null), !dbg !28
  %32 = call i64 @rb_fstring_new(i8* getelementptr inbounds ([17 x i8], [17 x i8]* @str_test_nilable_arg, i64 0, i64 0), i64 16) #10
  call void @rb_gc_register_mark_object(i64 %32) #10
  %33 = bitcast [6 x i64]* %locals1.i26.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 48, i8* nonnull %33)
  %rubyId_test_nilable_arg.i.i = load i64, i64* @rubyIdPrecomputed_test_nilable_arg, align 8
  %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i25.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/intrinsics/t_must.rb", align 8
  %locals1.sub.i27.i = getelementptr inbounds [6 x i64], [6 x i64]* %locals1.i26.i, i64 0, i64 0
  %"rubyId_<exceptionValue>.i28.i" = load i64, i64* @"rubyIdPrecomputed_<exceptionValue>", align 8
  store i64 %"rubyId_<exceptionValue>.i28.i", i64* %locals1.sub.i27.i, align 8
  %rubyId_arg.i.i = load i64, i64* @rubyIdPrecomputed_arg, align 8
  %34 = getelementptr inbounds [6 x i64], [6 x i64]* %locals1.i26.i, i64 0, i64 1
  store i64 %rubyId_arg.i.i, i64* %34, align 8
  %"rubyId_<self>.i29.i" = load i64, i64* @"rubyIdPrecomputed_<self>", align 8
  %35 = getelementptr inbounds [6 x i64], [6 x i64]* %locals1.i26.i, i64 0, i64 2
  store i64 %"rubyId_<self>.i29.i", i64* %35, align 8
  %"rubyId_<magic>.i30.i" = load i64, i64* @"rubyIdPrecomputed_<magic>", align 8
  %36 = getelementptr inbounds [6 x i64], [6 x i64]* %locals1.i26.i, i64 0, i64 3
  store i64 %"rubyId_<magic>.i30.i", i64* %36, align 8
  %"rubyId_<returnMethodTemp>.i31.i" = load i64, i64* @"rubyIdPrecomputed_<returnMethodTemp>", align 8
  %37 = getelementptr inbounds [6 x i64], [6 x i64]* %locals1.i26.i, i64 0, i64 4
  store i64 %"rubyId_<returnMethodTemp>.i31.i", i64* %37, align 8
  %"rubyId_<gotoDeadTemp>.i32.i" = load i64, i64* @"rubyIdPrecomputed_<gotoDeadTemp>", align 8
  %38 = getelementptr inbounds [6 x i64], [6 x i64]* %locals1.i26.i, i64 0, i64 5
  store i64 %"rubyId_<gotoDeadTemp>.i32.i", i64* %38, align 8
  %39 = call i8* @sorbet_allocateRubyStackFrame(i64 %32, i64 %rubyId_test_nilable_arg.i.i, i64 %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i25.i", i64 %realpath, i8* null, i32 1, i32 14, i32 21, i64* nonnull %locals1.sub.i27.i, i32 6, i32 3)
  store i8* %39, i8** @stackFramePrecomputed_func_Test.test_nilable_arg, align 8
  call void @llvm.lifetime.end.p0i8(i64 48, i8* nonnull %33)
  %"rubyId_rescue for.i33.i" = load i64, i64* @"rubyIdPrecomputed_rescue for", align 8
  %"rubyStr_rescue for.i34.i" = load i64, i64* @"rubyStrFrozen_rescue for", align 8
  %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i35.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/intrinsics/t_must.rb", align 8
  %40 = call i8* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_rescue for.i34.i", i64 %"rubyId_rescue for.i33.i", i64 %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i35.i", i64 %realpath, i8* %39, i32 4, i32 14, i32 21, i64* null, i32 0, i32 3)
  store i8* %40, i8** @"stackFramePrecomputed_func_Test.test_nilable_arg$block_2", align 8
  %stackFrame_func_Test.test_nilable_arg.i36.i = load i8*, i8** @stackFramePrecomputed_func_Test.test_nilable_arg, align 8
  %"rubyId_ensure for.i37.i" = load i64, i64* @"rubyIdPrecomputed_ensure for", align 8
  %"rubyStr_ensure for.i38.i" = load i64, i64* @"rubyStrFrozen_ensure for", align 8
  %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i39.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/intrinsics/t_must.rb", align 8
  %41 = call i8* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_ensure for.i38.i", i64 %"rubyId_ensure for.i37.i", i64 %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i39.i", i64 %realpath, i8* %stackFrame_func_Test.test_nilable_arg.i36.i, i32 5, i32 14, i32 21, i64* null, i32 0, i32 3)
  store i8* %41, i8** @"stackFramePrecomputed_func_Test.test_nilable_arg$block_3", align 8
  %rubyId_must9.i = load i64, i64* @rubyIdPrecomputed_must, align 8, !dbg !29
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_must.3, i64 %rubyId_must9.i, i32 16, i32 1, i32 0, i64* null), !dbg !29
  %42 = call i64 @rb_fstring_new(i8* getelementptr inbounds ([12 x i8], [12 x i8]* @"str_ wasn't nil", i64 0, i64 0), i64 11) #10
  call void @rb_gc_register_mark_object(i64 %42) #10
  store i64 %42, i64* @"rubyStrFrozen_ wasn't nil", align 8
  %rubyId_puts11.i = load i64, i64* @rubyIdPrecomputed_puts, align 8, !dbg !32
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_puts.4, i64 %rubyId_puts11.i, i32 16, i32 1, i32 0, i64* null), !dbg !32
  %"rubyId_is_a?13.i" = load i64, i64* @"rubyIdPrecomputed_is_a?", align 8, !dbg !33
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @"ic_is_a?.5", i64 %"rubyId_is_a?13.i", i32 16, i32 1, i32 0, i64* null), !dbg !33
  %rubyId_puts15.i = load i64, i64* @rubyIdPrecomputed_puts, align 8, !dbg !35
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_puts.6, i64 %rubyId_puts15.i, i32 16, i32 1, i32 0, i64* null), !dbg !35
  %"rubyId_<top (required)>.i40.i" = load i64, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %"rubyStr_<top (required)>.i41.i" = load i64, i64* @"rubyStrFrozen_<top (required)>", align 8
  %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i42.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/intrinsics/t_must.rb", align 8
  %43 = call i8* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_<top (required)>.i41.i", i64 %"rubyId_<top (required)>.i40.i", i64 %"rubyStr_test/testdata/compiler/intrinsics/t_must.rb.i42.i", i64 %realpath, i8* null, i32 1, i32 1, i32 5, i64* null, i32 0, i32 4)
  store i8* %43, i8** @"stackFramePrecomputed_func_Test.<static-init>", align 8
  %rubyId_keep_self_def.i = load i64, i64* @rubyIdPrecomputed_keep_self_def, align 8, !dbg !36
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_keep_self_def, i64 %rubyId_keep_self_def.i, i32 16, i32 3, i32 0, i64* null), !dbg !36
  %rubyId_keep_self_def19.i = load i64, i64* @rubyIdPrecomputed_keep_self_def, align 8, !dbg !38
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_keep_self_def.8, i64 %rubyId_keep_self_def19.i, i32 16, i32 3, i32 0, i64* null), !dbg !38
  %"stackFrame_func_<root>.<static-init>$152.i" = load i8*, i8** @"stackFramePrecomputed_func_<root>.<static-init>$152", align 8
  %44 = bitcast i8* %"stackFrame_func_<root>.<static-init>$152.i" to %struct.rb_iseq_struct*
  %45 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !39
  %46 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %45, i64 0, i32 2
  %47 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %46, align 8, !tbaa !40
  %48 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %47, i64 0, i32 2
  %49 = bitcast %struct.rb_iseq_struct** %48 to i8**
  store i8* %"stackFrame_func_<root>.<static-init>$152.i", i8** %49, align 8, !tbaa !44
  %50 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %47, i64 0, i32 4
  %51 = load i64*, i64** %50, align 8, !tbaa !46
  %52 = load i64, i64* %51, align 8, !tbaa !14
  %53 = and i64 %52, -129
  store i64 %53, i64* %51, align 8, !tbaa !14
  call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* %45, %struct.rb_control_frame_struct* nonnull %47, %struct.rb_iseq_struct* %44) #10
  %54 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %47, i64 0, i32 0
  %55 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %48, align 8, !tbaa !44
  %56 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %55, i64 0, i32 2
  %57 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %56, align 8, !tbaa !47
  %58 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %57, i64 0, i32 2
  %59 = load i64*, i64** %58, align 8, !tbaa !49
  %60 = getelementptr inbounds i64, i64* %59, i64 5
  store i64* %60, i64** %54, align 8, !dbg !58, !tbaa !39
  %61 = call i64 @rb_define_module(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_Test, i64 0, i64 0)) #10, !dbg !59
  %62 = load i64, i64* @guard_epoch_Test, align 8, !dbg !59
  %63 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !59, !tbaa !60
  %needTakeSlowPath = icmp eq i64 %62, %63, !dbg !59
  br i1 %needTakeSlowPath, label %65, label %64, !dbg !59, !prof !62

64:                                               ; preds = %entry
  call void @const_recompute_Test(), !dbg !59
  br label %65, !dbg !59

65:                                               ; preds = %entry, %64
  %66 = load i64, i64* @guarded_const_Test, align 8, !dbg !59
  %67 = load i64, i64* @guard_epoch_Test, align 8, !dbg !59
  %68 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !59, !tbaa !60
  %guardUpdated = icmp eq i64 %67, %68, !dbg !59
  call void @llvm.assume(i1 %guardUpdated), !dbg !59
  %69 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !39
  %70 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %69, i64 0, i32 2
  %71 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %70, align 8, !tbaa !40
  %72 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %71, i64 0, i32 0
  %73 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %71, i64 0, i32 2
  %74 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %73, align 8, !tbaa !44
  %75 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %74, i64 0, i32 2
  %76 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %75, align 8, !tbaa !47
  %77 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %76, i64 0, i32 2
  %78 = load i64*, i64** %77, align 8, !tbaa !49
  %79 = getelementptr inbounds i64, i64* %78, i64 6, !dbg !63
  store i64* %79, i64** %72, align 8, !dbg !63, !tbaa !39
  %rubyId_test_known_nil.i.i1 = load i64, i64* @rubyIdPrecomputed_test_known_nil, align 8, !dbg !65
  %rawSym.i.i = call i64 @rb_id2sym(i64 %rubyId_test_known_nil.i.i1) #10, !dbg !65
  %rubyId_normal.i.i = load i64, i64* @rubyIdPrecomputed_normal, align 8, !dbg !65
  %rawSym18.i.i = call i64 @rb_id2sym(i64 %rubyId_normal.i.i) #10, !dbg !65
  call void @rb_define_singleton_method(i64 %66, i8* getelementptr inbounds ([15 x i8], [15 x i8]* @str_test_known_nil, i64 0, i64 0), i64 (...)* bitcast (i64 (i32, i64*, i64)* @func_Test.test_known_nil to i64 (...)*), i32 -1) #10, !dbg !65
  %80 = getelementptr inbounds i64, i64* %78, i64 14, !dbg !65
  store i64* %80, i64** %72, align 8, !dbg !65, !tbaa !39
  %rubyId_test_nilable_arg.i.i2 = load i64, i64* @rubyIdPrecomputed_test_nilable_arg, align 8, !dbg !66
  %rawSym23.i.i = call i64 @rb_id2sym(i64 %rubyId_test_nilable_arg.i.i2) #10, !dbg !66
  %rubyId_normal24.i.i = load i64, i64* @rubyIdPrecomputed_normal, align 8, !dbg !66
  %rawSym25.i.i = call i64 @rb_id2sym(i64 %rubyId_normal24.i.i) #10, !dbg !66
  call void @rb_define_singleton_method(i64 %66, i8* getelementptr inbounds ([17 x i8], [17 x i8]* @str_test_nilable_arg, i64 0, i64 0), i64 (...)* bitcast (i64 (i32, i64*, i64)* @func_Test.test_nilable_arg to i64 (...)*), i32 -1) #10, !dbg !66
  %81 = getelementptr inbounds i64, i64* %59, i64 24, !dbg !58
  store i64* %81, i64** %54, align 8, !dbg !58, !tbaa !39
  %82 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !15, !tbaa !39
  %83 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %82, i64 0, i32 2, !dbg !15
  %84 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %83, align 8, !dbg !15, !tbaa !40
  %85 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %84, i64 0, i32 1, !dbg !15
  %86 = load i64*, i64** %85, align 8, !dbg !15, !tbaa !67
  %87 = getelementptr inbounds i64, i64* %86, i64 1, !dbg !15
  store i64* %87, i64** %85, align 8, !dbg !15, !tbaa !67
  store i64 %66, i64* %86, align 8, !dbg !15, !tbaa !14
  %send.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_test_known_nil, i64 0) #10, !dbg !15
  %88 = getelementptr inbounds i64, i64* %59, i64 25, !dbg !15
  store i64* %88, i64** %54, align 8, !dbg !15, !tbaa !39
  %89 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !20, !tbaa !39
  %90 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %89, i64 0, i32 2, !dbg !20
  %91 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %90, align 8, !dbg !20, !tbaa !40
  %92 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %91, i64 0, i32 1, !dbg !20
  %93 = load i64*, i64** %92, align 8, !dbg !20, !tbaa !67
  %94 = getelementptr inbounds i64, i64* %93, i64 1, !dbg !20
  store i64 %66, i64* %93, align 8, !dbg !20, !tbaa !14
  %95 = getelementptr inbounds i64, i64* %93, i64 2, !dbg !20
  store i64* %95, i64** %92, align 8, !dbg !20, !tbaa !67
  store i64 21, i64* %94, align 8, !dbg !20, !tbaa !14
  %send43.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_test_nilable_arg, i64 0) #10, !dbg !20
  %96 = getelementptr inbounds i64, i64* %59, i64 26, !dbg !20
  store i64* %96, i64** %54, align 8, !dbg !20, !tbaa !39
  %97 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !21, !tbaa !39
  %98 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %97, i64 0, i32 2, !dbg !21
  %99 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %98, align 8, !dbg !21, !tbaa !40
  %100 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %99, i64 0, i32 1, !dbg !21
  %101 = load i64*, i64** %100, align 8, !dbg !21, !tbaa !67
  %102 = getelementptr inbounds i64, i64* %101, i64 1, !dbg !21
  store i64 %66, i64* %101, align 8, !dbg !21, !tbaa !14
  %103 = getelementptr inbounds i64, i64* %101, i64 2, !dbg !21
  store i64* %103, i64** %100, align 8, !dbg !21, !tbaa !67
  store i64 0, i64* %102, align 8, !dbg !21, !tbaa !14
  %send48.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_test_nilable_arg.1, i64 0) #10, !dbg !21
  %104 = getelementptr inbounds i64, i64* %59, i64 27, !dbg !21
  store i64* %104, i64** %54, align 8, !dbg !21, !tbaa !39
  %105 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !22, !tbaa !39
  %106 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %105, i64 0, i32 2, !dbg !22
  %107 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %106, align 8, !dbg !22, !tbaa !40
  %108 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %107, i64 0, i32 1, !dbg !22
  %109 = load i64*, i64** %108, align 8, !dbg !22, !tbaa !67
  %110 = getelementptr inbounds i64, i64* %109, i64 1, !dbg !22
  store i64 %66, i64* %109, align 8, !dbg !22, !tbaa !14
  %111 = getelementptr inbounds i64, i64* %109, i64 2, !dbg !22
  store i64* %111, i64** %108, align 8, !dbg !22, !tbaa !67
  store i64 8, i64* %110, align 8, !dbg !22, !tbaa !14
  %send54.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_test_nilable_arg.2, i64 0) #10, !dbg !22
  ret void
}

; Function Attrs: nounwind sspreq uwtable
define i64 @func_Test.test_known_nil(i32 %argc, i64* nocapture readnone %argArray, i64 %selfRaw) #6 !dbg !25 {
functionEntryInitializers:
  %0 = alloca i64, align 8
  %1 = alloca %struct.ExceptionClosure, align 8
  %2 = alloca i64, align 8
  %3 = alloca %struct.ExceptionClosure, align 8
  %stackFrame_func_Test.test_known_nil = load i8*, i8** @stackFramePrecomputed_func_Test.test_known_nil, align 8
  %4 = bitcast i8* %stackFrame_func_Test.test_known_nil to %struct.rb_iseq_struct*
  %5 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !39
  %6 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %5, i64 0, i32 2
  %7 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %6, align 8, !tbaa !40
  %8 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %7, i64 0, i32 2
  %9 = bitcast %struct.rb_iseq_struct** %8 to i8**
  store i8* %stackFrame_func_Test.test_known_nil, i8** %9, align 8, !tbaa !44
  %10 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %7, i64 0, i32 4
  %11 = load i64*, i64** %10, align 8, !tbaa !46
  %12 = load i64, i64* %11, align 8, !tbaa !14
  %13 = and i64 %12, -129
  store i64 %13, i64* %11, align 8, !tbaa !14
  tail call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* %5, %struct.rb_control_frame_struct* nonnull %7, %struct.rb_iseq_struct* %4) #10
  %14 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %7, i64 0, i32 0
  %15 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %8, align 8, !tbaa !44
  %16 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %15, i64 0, i32 2
  %17 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %16, align 8, !tbaa !47
  %18 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %17, i64 0, i32 2
  %19 = load i64*, i64** %18, align 8, !tbaa !49
  %20 = getelementptr inbounds i64, i64* %19, i64 1
  store i64* %20, i64** %14, align 8, !tbaa !39
  %exceptionValue = alloca i64, align 8, !dbg !68
  %tooManyArgs = icmp eq i32 %argc, 0, !dbg !69
  br i1 %tooManyArgs, label %fillRequiredArgs, label %argCountFailBlock, !dbg !69, !prof !70

argCountFailBlock:                                ; preds = %functionEntryInitializers
  tail call void @sorbet_raiseArity(i32 %argc, i32 0, i32 0) #10, !dbg !69
  unreachable, !dbg !69

fillRequiredArgs:                                 ; preds = %functionEntryInitializers
  %21 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !69, !tbaa !39
  %22 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %21, i64 0, i32 2, !dbg !69
  %23 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %22, align 8, !dbg !69, !tbaa !40
  %24 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %23, i64 0, i32 4, !dbg !69
  %25 = load i64*, i64** %24, align 8, !dbg !69, !tbaa !46
  %26 = load i64, i64* %25, align 8, !dbg !69, !tbaa !14
  %27 = and i64 %26, 8, !dbg !69
  %28 = icmp eq i64 %27, 0, !dbg !69
  br i1 %28, label %29, label %31, !dbg !69, !prof !70

29:                                               ; preds = %fillRequiredArgs
  %30 = getelementptr inbounds i64, i64* %25, i64 -6, !dbg !69
  store i64 %selfRaw, i64* %30, align 8, !dbg !69, !tbaa !14
  br label %sorbet_writeLocal.exit, !dbg !69

31:                                               ; preds = %fillRequiredArgs
  tail call void @sorbet_vm_env_write_slowpath(i64* nonnull %25, i32 -6, i64 %selfRaw) #10, !dbg !69
  br label %sorbet_writeLocal.exit, !dbg !69

sorbet_writeLocal.exit:                           ; preds = %29, %31
  %32 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !71, !tbaa !39
  %33 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %32, i64 0, i32 2, !dbg !71
  %34 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %33, align 8, !dbg !71, !tbaa !40
  %35 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %34, i64 0, i32 4, !dbg !71
  %36 = load i64*, i64** %35, align 8, !dbg !71, !tbaa !46
  %37 = load i64, i64* %36, align 8, !dbg !71, !tbaa !14
  %38 = and i64 %37, 8, !dbg !71
  %39 = icmp eq i64 %38, 0, !dbg !71
  br i1 %39, label %sorbet_writeLocal.exit26, label %40, !dbg !71, !prof !70

40:                                               ; preds = %sorbet_writeLocal.exit
  %41 = getelementptr inbounds i64, i64* %36, i64 -6, !dbg !71
  %42 = load i64, i64* %41, align 8, !dbg !71, !tbaa !14
  tail call void @sorbet_vm_env_write_slowpath(i64* nonnull %36, i32 -6, i64 %42) #10, !dbg !71
  br label %sorbet_writeLocal.exit26, !dbg !71

sorbet_writeLocal.exit26:                         ; preds = %sorbet_writeLocal.exit, %40
  %43 = getelementptr inbounds i64, i64* %19, i64 3, !dbg !71
  store i64* %43, i64** %14, align 8, !dbg !71, !tbaa !39
  %previousException = tail call i64 @rb_errinfo() #10, !dbg !68
  %44 = bitcast i64* %0 to i8*, !dbg !71
  %45 = bitcast %struct.ExceptionClosure* %1 to i8*, !dbg !71
  %46 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %1, i64 0, i32 0, !dbg !71
  %47 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %1, i64 0, i32 1, !dbg !71
  %48 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %1, i64 0, i32 2, !dbg !71
  %49 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %1, i64 0, i32 3, !dbg !71
  %50 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %1, i64 0, i32 4, !dbg !71
  %51 = icmp eq i64 %previousException, 8, !dbg !71
  %52 = ptrtoint %struct.ExceptionClosure* %1 to i64, !dbg !71
  %53 = ptrtoint i64* %exceptionValue to i64, !dbg !71
  %54 = bitcast i64* %2 to i8*, !dbg !71
  %55 = bitcast %struct.ExceptionClosure* %3 to i8*, !dbg !71
  %56 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %3, i64 0, i32 0, !dbg !71
  %57 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %3, i64 0, i32 1, !dbg !71
  %58 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %3, i64 0, i32 2, !dbg !71
  %59 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %3, i64 0, i32 3, !dbg !71
  %60 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %3, i64 0, i32 4, !dbg !71
  %61 = ptrtoint %struct.ExceptionClosure* %3 to i64, !dbg !71
  br i1 %51, label %exception-entry.us, label %exception-entry, !dbg !68

exception-entry.us:                               ; preds = %sorbet_writeLocal.exit26, %sorbet_try.exit.us
  %62 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !68, !tbaa !39
  %63 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %62, i64 0, i32 2, !dbg !68
  %64 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %63, align 8, !dbg !68, !tbaa !40
  %65 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %64, i64 0, i32 4, !dbg !68
  %66 = load i64*, i64** %65, align 8, !dbg !68, !tbaa !46
  %67 = load i64, i64* %66, align 8, !dbg !68, !tbaa !14
  %68 = and i64 %67, 8, !dbg !68
  %69 = icmp eq i64 %68, 0, !dbg !68
  br i1 %69, label %71, label %70, !dbg !68, !prof !70

70:                                               ; preds = %exception-entry.us
  call void @sorbet_vm_env_write_slowpath(i64* nonnull %66, i32 -3, i64 8) #10, !dbg !68
  br label %sorbet_writeLocal.exit27.us, !dbg !68

71:                                               ; preds = %exception-entry.us
  %72 = getelementptr inbounds i64, i64* %66, i64 -3, !dbg !68
  store i64 8, i64* %72, align 8, !dbg !68, !tbaa !14
  br label %sorbet_writeLocal.exit27.us, !dbg !68

sorbet_writeLocal.exit27.us:                      ; preds = %71, %70
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %44) #10, !dbg !68
  store i64 52, i64* %0, align 8, !dbg !68, !tbaa !14
  call void @llvm.lifetime.start.p0i8(i64 40, i8* nonnull %45) #10, !dbg !68
  store i64 (i64**, i64*, i64)* @"func_Test.test_known_nil$block_1", i64 (i64**, i64*, i64)** %46, align 8, !dbg !68, !tbaa !4
  store i64** %14, i64*** %47, align 8, !dbg !68, !tbaa !10
  store i64* %19, i64** %48, align 8, !dbg !68, !tbaa !11
  store i64 0, i64* %49, align 8, !dbg !68, !tbaa !12
  store i64* %0, i64** %50, align 8, !dbg !68, !tbaa !13
  store i64 8, i64* %exceptionValue, align 8, !dbg !68, !tbaa !14
  %73 = load i64, i64* @rb_eException, align 8, !dbg !68, !tbaa !14
  %74 = call i64 (i64 (i64)*, i64, i64 (i64, i64)*, i64, ...) @rb_rescue2(i64 (i64)* nonnull @sorbet_applyExceptionClosure, i64 %52, i64 (i64, i64)* nonnull @sorbet_rescueStoreException, i64 %53, i64 %73, i32 0) #10, !dbg !68
  %75 = load i64, i64* %0, align 8, !dbg !68
  call void @llvm.lifetime.end.p0i8(i64 40, i8* nonnull %45) #10, !dbg !68
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %44) #10, !dbg !68
  %isReturnValue.us = icmp eq i64 %75, 52, !dbg !68
  br i1 %isReturnValue.us, label %exception-body-continue.us, label %exception-body-return, !dbg !68

exception-body-continue.us:                       ; preds = %sorbet_writeLocal.exit27.us
  %76 = load i64, i64* %exceptionValue, align 8, !dbg !68
  %77 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !68, !tbaa !39
  %78 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %77, i64 0, i32 2, !dbg !68
  %79 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %78, align 8, !dbg !68, !tbaa !40
  %80 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %79, i64 0, i32 4, !dbg !68
  %81 = load i64*, i64** %80, align 8, !dbg !68, !tbaa !46
  %82 = load i64, i64* %81, align 8, !dbg !68, !tbaa !14
  %83 = and i64 %82, 8, !dbg !68
  %84 = icmp eq i64 %83, 0, !dbg !68
  br i1 %84, label %86, label %85, !dbg !68, !prof !70

85:                                               ; preds = %exception-body-continue.us
  call void @sorbet_vm_env_write_slowpath(i64* nonnull %81, i32 -3, i64 %76) #10, !dbg !68
  br label %sorbet_writeLocal.exit28.us, !dbg !68

86:                                               ; preds = %exception-body-continue.us
  %87 = getelementptr inbounds i64, i64* %81, i64 -3, !dbg !68
  store i64 %76, i64* %87, align 8, !dbg !68, !tbaa !14
  br label %sorbet_writeLocal.exit28.us, !dbg !68

sorbet_writeLocal.exit28.us:                      ; preds = %86, %85
  %88 = icmp ne i64 %76, 8, !dbg !68
  %handler.us = select i1 %88, i64 (i64**, i64*, i64)* @"func_Test.test_known_nil$block_2", i64 (i64**, i64*, i64)* @"func_Test.test_known_nil$block_4", !dbg !68
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %54) #10, !dbg !68
  store i64 52, i64* %2, align 8, !dbg !68, !tbaa !14
  call void @llvm.lifetime.start.p0i8(i64 40, i8* nonnull %55) #10, !dbg !68
  store i64 (i64**, i64*, i64)* %handler.us, i64 (i64**, i64*, i64)** %56, align 8, !dbg !68, !tbaa !4
  store i64** %14, i64*** %57, align 8, !dbg !68, !tbaa !10
  store i64* %19, i64** %58, align 8, !dbg !68, !tbaa !11
  store i64 0, i64* %59, align 8, !dbg !68, !tbaa !12
  store i64* %2, i64** %60, align 8, !dbg !68, !tbaa !13
  store i64 8, i64* %exceptionValue, align 8, !dbg !68, !tbaa !14
  %89 = icmp eq i64 %76, 8, !dbg !68
  br i1 %89, label %sorbet_try.exit.us, label %90, !dbg !68

90:                                               ; preds = %sorbet_writeLocal.exit28.us
  call void @rb_set_errinfo(i64 %76) #10, !dbg !68
  br label %sorbet_try.exit.us, !dbg !68

sorbet_try.exit.us:                               ; preds = %90, %sorbet_writeLocal.exit28.us
  %91 = load i64, i64* @rb_eException, align 8, !dbg !68, !tbaa !14
  %92 = call i64 (i64 (i64)*, i64, i64 (i64, i64)*, i64, ...) @rb_rescue2(i64 (i64)* nonnull @sorbet_applyExceptionClosure, i64 %61, i64 (i64, i64)* nonnull @sorbet_rescueStoreException, i64 %53, i64 %91, i32 0) #10, !dbg !68
  %93 = load i64, i64* %2, align 8, !dbg !68
  call void @llvm.lifetime.end.p0i8(i64 40, i8* nonnull %55) #10, !dbg !68
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %54) #10, !dbg !68
  %94 = load i64, i64* %exceptionValue, align 8, !dbg !68
  %95 = icmp eq i64 %94, 8, !dbg !68
  %96 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !68, !tbaa !39
  %97 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %96, i64 0, i32 2, !dbg !68
  %98 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %97, align 8, !dbg !68, !tbaa !40
  %99 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %98, i64 0, i32 4, !dbg !68
  %100 = load i64*, i64** %99, align 8, !dbg !68, !tbaa !46
  %101 = getelementptr inbounds i64, i64* %100, i64 -3, !dbg !68
  %102 = load i64, i64* %101, align 8, !dbg !68, !tbaa !14
  %103 = select i1 %95, i64 %102, i64 %94, !dbg !68
  call void @rb_set_errinfo(i64 %103) #10, !dbg !68
  %"<retry-singleton>.us" = load i64, i64* @"<retry-singleton>", align 8, !dbg !68
  %shouldRetry.us = icmp eq i64 %93, %"<retry-singleton>.us", !dbg !68
  %104 = and i1 %88, %shouldRetry.us, !dbg !68
  br i1 %104, label %exception-entry.us, label %exception-ensure, !dbg !68

exception-entry:                                  ; preds = %sorbet_writeLocal.exit26, %sorbet_try.exit
  %105 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !68, !tbaa !39
  %106 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %105, i64 0, i32 2, !dbg !68
  %107 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %106, align 8, !dbg !68, !tbaa !40
  %108 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %107, i64 0, i32 4, !dbg !68
  %109 = load i64*, i64** %108, align 8, !dbg !68, !tbaa !46
  %110 = load i64, i64* %109, align 8, !dbg !68, !tbaa !14
  %111 = and i64 %110, 8, !dbg !68
  %112 = icmp eq i64 %111, 0, !dbg !68
  br i1 %112, label %113, label %115, !dbg !68, !prof !70

113:                                              ; preds = %exception-entry
  %114 = getelementptr inbounds i64, i64* %109, i64 -3, !dbg !68
  store i64 8, i64* %114, align 8, !dbg !68, !tbaa !14
  br label %sorbet_writeLocal.exit27, !dbg !68

115:                                              ; preds = %exception-entry
  call void @sorbet_vm_env_write_slowpath(i64* nonnull %109, i32 -3, i64 8) #10, !dbg !68
  br label %sorbet_writeLocal.exit27, !dbg !68

sorbet_writeLocal.exit27:                         ; preds = %113, %115
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %44) #10, !dbg !68
  store i64 52, i64* %0, align 8, !dbg !68, !tbaa !14
  call void @llvm.lifetime.start.p0i8(i64 40, i8* nonnull %45) #10, !dbg !68
  store i64 (i64**, i64*, i64)* @"func_Test.test_known_nil$block_1", i64 (i64**, i64*, i64)** %46, align 8, !dbg !68, !tbaa !4
  store i64** %14, i64*** %47, align 8, !dbg !68, !tbaa !10
  store i64* %19, i64** %48, align 8, !dbg !68, !tbaa !11
  store i64 0, i64* %49, align 8, !dbg !68, !tbaa !12
  store i64* %0, i64** %50, align 8, !dbg !68, !tbaa !13
  store i64 8, i64* %exceptionValue, align 8, !dbg !68, !tbaa !14
  call void @rb_set_errinfo(i64 %previousException) #10, !dbg !68
  %116 = load i64, i64* @rb_eException, align 8, !dbg !68, !tbaa !14
  %117 = call i64 (i64 (i64)*, i64, i64 (i64, i64)*, i64, ...) @rb_rescue2(i64 (i64)* nonnull @sorbet_applyExceptionClosure, i64 %52, i64 (i64, i64)* nonnull @sorbet_rescueStoreException, i64 %53, i64 %116, i32 0) #10, !dbg !68
  %118 = load i64, i64* %0, align 8, !dbg !68
  call void @llvm.lifetime.end.p0i8(i64 40, i8* nonnull %45) #10, !dbg !68
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %44) #10, !dbg !68
  %isReturnValue = icmp eq i64 %118, 52, !dbg !68
  br i1 %isReturnValue, label %exception-body-continue, label %exception-body-return, !dbg !68

exception-body-return:                            ; preds = %sorbet_writeLocal.exit27, %sorbet_writeLocal.exit27.us
  %.lcssa = phi i64 [ %75, %sorbet_writeLocal.exit27.us ], [ %118, %sorbet_writeLocal.exit27 ], !dbg !68
  call void @rb_set_errinfo(i64 %previousException) #10, !dbg !68
  %"stackFrame_func_Test.test_known_nil$block_31.i32" = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** bitcast (i8** @"stackFramePrecomputed_func_Test.test_known_nil$block_3" to %struct.rb_iseq_struct**), align 8
  %119 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !39
  %120 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %119, i64 0, i32 2
  %121 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %120, align 8, !tbaa !40
  call void @sorbet_setExceptionStackFrame(%struct.rb_execution_context_struct* %119, %struct.rb_control_frame_struct* %121, %struct.rb_iseq_struct* %"stackFrame_func_Test.test_known_nil$block_31.i32") #10
  %122 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %121, i64 0, i32 0
  %123 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %121, i64 0, i32 2
  %124 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %123, align 8, !tbaa !44
  %125 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %124, i64 0, i32 2
  %126 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %125, align 8, !tbaa !47
  %127 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %126, i64 0, i32 2
  %128 = load i64*, i64** %127, align 8, !tbaa !49
  %129 = getelementptr inbounds i64, i64* %128, i64 1
  store i64* %129, i64** %122, align 8, !tbaa !39
  call void @sorbet_popRubyStack() #10
  ret i64 %.lcssa, !dbg !68

exception-body-continue:                          ; preds = %sorbet_writeLocal.exit27
  %130 = load i64, i64* %exceptionValue, align 8, !dbg !68
  %131 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !68, !tbaa !39
  %132 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %131, i64 0, i32 2, !dbg !68
  %133 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %132, align 8, !dbg !68, !tbaa !40
  %134 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %133, i64 0, i32 4, !dbg !68
  %135 = load i64*, i64** %134, align 8, !dbg !68, !tbaa !46
  %136 = load i64, i64* %135, align 8, !dbg !68, !tbaa !14
  %137 = and i64 %136, 8, !dbg !68
  %138 = icmp eq i64 %137, 0, !dbg !68
  br i1 %138, label %139, label %141, !dbg !68, !prof !70

139:                                              ; preds = %exception-body-continue
  %140 = getelementptr inbounds i64, i64* %135, i64 -3, !dbg !68
  store i64 %130, i64* %140, align 8, !dbg !68, !tbaa !14
  br label %sorbet_writeLocal.exit28, !dbg !68

141:                                              ; preds = %exception-body-continue
  call void @sorbet_vm_env_write_slowpath(i64* nonnull %135, i32 -3, i64 %130) #10, !dbg !68
  br label %sorbet_writeLocal.exit28, !dbg !68

sorbet_writeLocal.exit28:                         ; preds = %139, %141
  %142 = icmp ne i64 %130, 8, !dbg !68
  %handler = select i1 %142, i64 (i64**, i64*, i64)* @"func_Test.test_known_nil$block_2", i64 (i64**, i64*, i64)* @"func_Test.test_known_nil$block_4", !dbg !68
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %54) #10, !dbg !68
  store i64 52, i64* %2, align 8, !dbg !68, !tbaa !14
  call void @llvm.lifetime.start.p0i8(i64 40, i8* nonnull %55) #10, !dbg !68
  store i64 (i64**, i64*, i64)* %handler, i64 (i64**, i64*, i64)** %56, align 8, !dbg !68, !tbaa !4
  store i64** %14, i64*** %57, align 8, !dbg !68, !tbaa !10
  store i64* %19, i64** %58, align 8, !dbg !68, !tbaa !11
  store i64 0, i64* %59, align 8, !dbg !68, !tbaa !12
  store i64* %2, i64** %60, align 8, !dbg !68, !tbaa !13
  store i64 8, i64* %exceptionValue, align 8, !dbg !68, !tbaa !14
  %143 = icmp eq i64 %130, 8, !dbg !68
  br i1 %143, label %sorbet_try.exit, label %144, !dbg !68

144:                                              ; preds = %sorbet_writeLocal.exit28
  call void @rb_set_errinfo(i64 %130) #10, !dbg !68
  br label %sorbet_try.exit, !dbg !68

sorbet_try.exit:                                  ; preds = %sorbet_writeLocal.exit28, %144
  %145 = load i64, i64* @rb_eException, align 8, !dbg !68, !tbaa !14
  %146 = call i64 (i64 (i64)*, i64, i64 (i64, i64)*, i64, ...) @rb_rescue2(i64 (i64)* nonnull @sorbet_applyExceptionClosure, i64 %61, i64 (i64, i64)* nonnull @sorbet_rescueStoreException, i64 %53, i64 %145, i32 0) #10, !dbg !68
  %147 = load i64, i64* %2, align 8, !dbg !68
  call void @llvm.lifetime.end.p0i8(i64 40, i8* nonnull %55) #10, !dbg !68
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %54) #10, !dbg !68
  %148 = load i64, i64* %exceptionValue, align 8, !dbg !68
  %149 = icmp eq i64 %148, 8, !dbg !68
  %150 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !68, !tbaa !39
  %151 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %150, i64 0, i32 2, !dbg !68
  %152 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %151, align 8, !dbg !68, !tbaa !40
  %153 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %152, i64 0, i32 4, !dbg !68
  %154 = load i64*, i64** %153, align 8, !dbg !68, !tbaa !46
  %155 = getelementptr inbounds i64, i64* %154, i64 -3, !dbg !68
  %156 = load i64, i64* %155, align 8, !dbg !68, !tbaa !14
  %157 = icmp eq i64 %156, 8, !dbg !68
  %158 = select i1 %157, i64 %previousException, i64 %156, !dbg !68
  %159 = select i1 %149, i64 %158, i64 %148, !dbg !68
  call void @rb_set_errinfo(i64 %159) #10, !dbg !68
  %"<retry-singleton>" = load i64, i64* @"<retry-singleton>", align 8, !dbg !68
  %shouldRetry = icmp eq i64 %147, %"<retry-singleton>", !dbg !68
  %160 = and i1 %142, %shouldRetry, !dbg !68
  br i1 %160, label %exception-entry, label %exception-ensure, !dbg !68

exception-ensure:                                 ; preds = %sorbet_try.exit, %sorbet_try.exit.us
  %.lcssa36 = phi i64 [ %93, %sorbet_try.exit.us ], [ %147, %sorbet_try.exit ], !dbg !68
  %.lcssa35 = phi i64 [ %103, %sorbet_try.exit.us ], [ %159, %sorbet_try.exit ], !dbg !68
  %"stackFrame_func_Test.test_known_nil$block_31.i" = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** bitcast (i8** @"stackFramePrecomputed_func_Test.test_known_nil$block_3" to %struct.rb_iseq_struct**), align 8
  %161 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !39
  %162 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %161, i64 0, i32 2
  %163 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %162, align 8, !tbaa !40
  call void @sorbet_setExceptionStackFrame(%struct.rb_execution_context_struct* %161, %struct.rb_control_frame_struct* %163, %struct.rb_iseq_struct* %"stackFrame_func_Test.test_known_nil$block_31.i") #10
  %164 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %163, i64 0, i32 0
  %165 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %163, i64 0, i32 2
  %166 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %165, align 8, !tbaa !44
  %167 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %166, i64 0, i32 2
  %168 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %167, align 8, !tbaa !47
  %169 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %168, i64 0, i32 2
  %170 = load i64*, i64** %169, align 8, !tbaa !49
  %171 = getelementptr inbounds i64, i64* %170, i64 1
  store i64* %171, i64** %164, align 8, !tbaa !39
  call void @sorbet_popRubyStack() #10
  %isReturnValue13 = icmp eq i64 %.lcssa36, 52, !dbg !68
  br i1 %isReturnValue13, label %exception-continue, label %exception-return, !dbg !68

exception-continue:                               ; preds = %exception-ensure
  %172 = icmp eq i64 %.lcssa35, 8, !dbg !68
  br i1 %172, label %sorbet_raiseIfNotNil.exit, label %173, !dbg !68

173:                                              ; preds = %exception-continue
  call void @rb_exc_raise(i64 %.lcssa35) #11, !dbg !68
  unreachable, !dbg !68

sorbet_raiseIfNotNil.exit:                        ; preds = %exception-continue
  %174 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !68, !tbaa !39
  %175 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %174, i64 0, i32 2, !dbg !68
  %176 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %175, align 8, !dbg !68, !tbaa !40
  %177 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %176, i64 0, i32 4, !dbg !68
  %178 = load i64*, i64** %177, align 8, !dbg !68, !tbaa !46
  %179 = getelementptr inbounds i64, i64* %178, i64 -3, !dbg !68
  %180 = load i64, i64* %179, align 8, !dbg !68, !tbaa !14
  %181 = icmp eq i64 %180, 8, !dbg !68
  br i1 %181, label %sorbet_raiseIfNotNil.exit29, label %182, !dbg !68

182:                                              ; preds = %sorbet_raiseIfNotNil.exit
  call void @rb_exc_raise(i64 %180) #11, !dbg !68
  unreachable, !dbg !68

sorbet_raiseIfNotNil.exit29:                      ; preds = %sorbet_raiseIfNotNil.exit
  store i64* %20, i64** %14, align 8, !tbaa !39
  %183 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !69, !tbaa !39
  %184 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %183, i64 0, i32 2, !dbg !69
  %185 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %184, align 8, !dbg !69, !tbaa !40
  %186 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %185, i64 0, i32 4, !dbg !69
  %187 = load i64*, i64** %186, align 8, !dbg !69, !tbaa !46
  %188 = getelementptr inbounds i64, i64* %187, i64 -5, !dbg !69
  %189 = load i64, i64* %188, align 8, !dbg !69, !tbaa !14
  ret i64 %189

exception-return:                                 ; preds = %exception-ensure
  ret i64 %.lcssa36, !dbg !68
}

; Function Attrs: noreturn nounwind ssp
define internal i64 @"func_Test.test_known_nil$block_1"(i64** nocapture %pc, i64* %iseq_encoded, i64 %localsOffset) #7 !dbg !24 {
  %1 = getelementptr inbounds i64, i64* %iseq_encoded, i64 3
  store i64* %1, i64** %pc, align 8, !tbaa !39
  %2 = load i64, i64* @rb_eTypeError, align 8, !dbg !23, !tbaa !14, !noalias !72
  tail call void (i64, i8*, ...) @rb_raise(i64 %2, i8* getelementptr inbounds ([25 x i8], [25 x i8]* @.str.2, i64 0, i64 0)) #11, !dbg !23, !noalias !72
  unreachable, !dbg !23
}

; Function Attrs: ssp
define internal i64 @"func_Test.test_known_nil$block_2"(i64** nocapture readnone %pc, i64* nocapture readnone %iseq_encoded, i64 %localsOffset) #8 !dbg !27 {
.preheader.i30:
  %"stackFrame_func_Test.test_known_nil$block_223" = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** bitcast (i8** @"stackFramePrecomputed_func_Test.test_known_nil$block_2" to %struct.rb_iseq_struct**), align 8
  %0 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !39
  %1 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %0, i64 0, i32 2
  %2 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %1, align 8, !tbaa !40
  tail call void @sorbet_setExceptionStackFrame(%struct.rb_execution_context_struct* %0, %struct.rb_control_frame_struct* %2, %struct.rb_iseq_struct* %"stackFrame_func_Test.test_known_nil$block_223") #10
  %3 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 0
  %4 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 2
  %5 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %4, align 8, !tbaa !44
  %6 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %5, i64 0, i32 2
  %7 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %6, align 8, !tbaa !47
  %8 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %7, i64 0, i32 2
  %9 = load i64*, i64** %8, align 8, !tbaa !49
  %10 = getelementptr inbounds i64, i64* %9, i64 4
  store i64* %10, i64** %3, align 8, !tbaa !39
  %11 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !26, !tbaa !39
  %12 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %11, i64 0, i32 2, !dbg !26
  %13 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %12, align 8, !dbg !26, !tbaa !40
  %14 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %13, i64 0, i32 4, !dbg !26
  %15 = load i64*, i64** %14, align 8, !dbg !26, !tbaa !46
  %16 = getelementptr inbounds i64, i64* %15, i64 -1, !dbg !26
  %17 = load i64, i64* %16, align 8, !dbg !26, !tbaa !14
  %18 = and i64 %17, -4, !dbg !26
  %19 = inttoptr i64 %18 to i64*, !dbg !26
  %20 = getelementptr inbounds i64, i64* %19, i64 -3, !dbg !26
  %21 = load i64, i64* %20, align 8, !dbg !26, !tbaa !14
  %22 = load i64, i64* @rb_eStandardError, align 8, !dbg !26
  %23 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %13, i64 0, i32 1, !dbg !26
  %24 = load i64*, i64** %23, align 8, !dbg !26, !tbaa !67
  %25 = getelementptr inbounds i64, i64* %24, i64 1, !dbg !26
  store i64 %21, i64* %24, align 8, !dbg !26, !tbaa !14
  %26 = getelementptr inbounds i64, i64* %24, i64 2, !dbg !26
  store i64* %26, i64** %23, align 8, !dbg !26, !tbaa !67
  store i64 %22, i64* %25, align 8, !dbg !26, !tbaa !14
  %send = tail call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @"ic_is_a?", i64 0), !dbg !26
  %27 = and i64 %send, -9, !dbg !26
  %28 = icmp eq i64 %27, 0, !dbg !26
  br i1 %28, label %.preheader.i, label %.preheader.i28, !dbg !26

blockExit:                                        ; preds = %90, %88, %74, %72
  tail call void @sorbet_popRubyStack()
  ret i64 52

.preheader.i28:                                   ; preds = %.preheader.i30
  %29 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !75, !tbaa !39
  %30 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %29, i64 0, i32 2, !dbg !75
  %31 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %30, align 8, !dbg !75, !tbaa !40
  %32 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %31, i64 0, i32 4, !dbg !75
  %33 = load i64*, i64** %32, align 8, !dbg !75, !tbaa !46
  %34 = getelementptr inbounds i64, i64* %33, i64 -1, !dbg !75
  %35 = load i64, i64* %34, align 8, !dbg !75, !tbaa !14
  %36 = and i64 %35, -4, !dbg !75
  %37 = inttoptr i64 %36 to i64*, !dbg !75
  %38 = load i64, i64* %37, align 8, !dbg !75, !tbaa !14
  %39 = and i64 %38, 8, !dbg !75
  %40 = icmp eq i64 %39, 0, !dbg !75
  br i1 %40, label %41, label %43, !dbg !75, !prof !70

41:                                               ; preds = %.preheader.i28
  %42 = getelementptr inbounds i64, i64* %37, i64 -3, !dbg !75
  store i64 8, i64* %42, align 8, !dbg !75, !tbaa !14
  br label %.preheader.i24, !dbg !75

43:                                               ; preds = %.preheader.i28
  tail call void @sorbet_vm_env_write_slowpath(i64* nonnull %37, i32 -3, i64 8) #10, !dbg !75
  br label %.preheader.i24, !dbg !75

.preheader.i24:                                   ; preds = %41, %43
  %44 = getelementptr inbounds i64, i64* %9, i64 5, !dbg !76
  store i64* %44, i64** %3, align 8, !dbg !76, !tbaa !39
  %45 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !28, !tbaa !39
  %46 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %45, i64 0, i32 2, !dbg !28
  %47 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %46, align 8, !dbg !28, !tbaa !40
  %48 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %47, i64 0, i32 4, !dbg !28
  %49 = load i64*, i64** %48, align 8, !dbg !28, !tbaa !46
  %50 = getelementptr inbounds i64, i64* %49, i64 -1, !dbg !28
  %51 = load i64, i64* %50, align 8, !dbg !28, !tbaa !14
  %52 = and i64 %51, -4, !dbg !28
  %53 = inttoptr i64 %52 to i64*, !dbg !28
  %54 = getelementptr inbounds i64, i64* %53, i64 -6, !dbg !28
  %55 = load i64, i64* %54, align 8, !dbg !28, !tbaa !14
  %56 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %47, i64 0, i32 1, !dbg !28
  %57 = load i64*, i64** %56, align 8, !dbg !28, !tbaa !67
  %58 = getelementptr inbounds i64, i64* %57, i64 1, !dbg !28
  store i64 %55, i64* %57, align 8, !dbg !28, !tbaa !14
  %59 = getelementptr inbounds i64, i64* %57, i64 2, !dbg !28
  store i64* %59, i64** %56, align 8, !dbg !28, !tbaa !67
  store i64 %21, i64* %58, align 8, !dbg !28, !tbaa !14
  %send11 = tail call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_puts, i64 0), !dbg !28
  %60 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !28, !tbaa !39
  %61 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %60, i64 0, i32 2, !dbg !28
  %62 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %61, align 8, !dbg !28, !tbaa !40
  %63 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %62, i64 0, i32 4, !dbg !28
  %64 = load i64*, i64** %63, align 8, !dbg !28, !tbaa !46
  %65 = getelementptr inbounds i64, i64* %64, i64 -1, !dbg !28
  %66 = load i64, i64* %65, align 8, !dbg !28, !tbaa !14
  %67 = and i64 %66, -4, !dbg !28
  %68 = inttoptr i64 %67 to i64*, !dbg !28
  %69 = load i64, i64* %68, align 8, !dbg !28, !tbaa !14
  %70 = and i64 %69, 8, !dbg !28
  %71 = icmp eq i64 %70, 0, !dbg !28
  br i1 %71, label %72, label %74, !dbg !28, !prof !70

72:                                               ; preds = %.preheader.i24
  %73 = getelementptr inbounds i64, i64* %68, i64 -5, !dbg !28
  store i64 %send11, i64* %73, align 8, !dbg !28, !tbaa !14
  br label %blockExit, !dbg !28

74:                                               ; preds = %.preheader.i24
  tail call void @sorbet_vm_env_write_slowpath(i64* nonnull %68, i32 -5, i64 %send11) #10, !dbg !28
  br label %blockExit, !dbg !28

.preheader.i:                                     ; preds = %.preheader.i30
  %75 = getelementptr inbounds i64, i64* %9, i64 3
  store i64* %75, i64** %3, align 8, !tbaa !39
  %76 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !77, !tbaa !39
  %77 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %76, i64 0, i32 2, !dbg !77
  %78 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %77, align 8, !dbg !77, !tbaa !40
  %79 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %78, i64 0, i32 4, !dbg !77
  %80 = load i64*, i64** %79, align 8, !dbg !77, !tbaa !46
  %81 = getelementptr inbounds i64, i64* %80, i64 -1, !dbg !77
  %82 = load i64, i64* %81, align 8, !dbg !77, !tbaa !14
  %83 = and i64 %82, -4, !dbg !77
  %84 = inttoptr i64 %83 to i64*, !dbg !77
  %85 = load i64, i64* %84, align 8, !dbg !77, !tbaa !14
  %86 = and i64 %85, 8, !dbg !77
  %87 = icmp eq i64 %86, 0, !dbg !77
  br i1 %87, label %88, label %90, !dbg !77, !prof !70

88:                                               ; preds = %.preheader.i
  %89 = getelementptr inbounds i64, i64* %84, i64 -7, !dbg !77
  store i64 20, i64* %89, align 8, !dbg !77, !tbaa !14
  br label %blockExit, !dbg !77

90:                                               ; preds = %.preheader.i
  tail call void @sorbet_vm_env_write_slowpath(i64* nonnull %84, i32 -7, i64 20) #10, !dbg !77
  br label %blockExit, !dbg !77
}

; Function Attrs: nofree norecurse nounwind ssp writeonly
define internal i64 @"func_Test.test_known_nil$block_4"(i64** nocapture %pc, i64* %iseq_encoded, i64 %localsOffset) #9 !dbg !78 {
functionEntryInitializers:
  %0 = getelementptr inbounds i64, i64* %iseq_encoded, i64 1
  store i64* %0, i64** %pc, align 8, !tbaa !39
  ret i64 52
}

; Function Attrs: nounwind sspreq uwtable
define i64 @func_Test.test_nilable_arg(i32 %argc, i64* nocapture readonly %argArray, i64 %selfRaw) #6 !dbg !31 {
functionEntryInitializers:
  %0 = alloca i64, align 8
  %1 = alloca %struct.ExceptionClosure, align 8
  %2 = alloca i64, align 8
  %3 = alloca %struct.ExceptionClosure, align 8
  %stackFrame_func_Test.test_nilable_arg = load i8*, i8** @stackFramePrecomputed_func_Test.test_nilable_arg, align 8
  %4 = bitcast i8* %stackFrame_func_Test.test_nilable_arg to %struct.rb_iseq_struct*
  %5 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !39
  %6 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %5, i64 0, i32 2
  %7 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %6, align 8, !tbaa !40
  %8 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %7, i64 0, i32 2
  %9 = bitcast %struct.rb_iseq_struct** %8 to i8**
  store i8* %stackFrame_func_Test.test_nilable_arg, i8** %9, align 8, !tbaa !44
  %10 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %7, i64 0, i32 4
  %11 = load i64*, i64** %10, align 8, !tbaa !46
  %12 = load i64, i64* %11, align 8, !tbaa !14
  %13 = and i64 %12, -129
  store i64 %13, i64* %11, align 8, !tbaa !14
  tail call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* %5, %struct.rb_control_frame_struct* nonnull %7, %struct.rb_iseq_struct* %4) #10
  %14 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %7, i64 0, i32 0
  %15 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %8, align 8, !tbaa !44
  %16 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %15, i64 0, i32 2
  %17 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %16, align 8, !tbaa !47
  %18 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %17, i64 0, i32 2
  %19 = load i64*, i64** %18, align 8, !tbaa !49
  %20 = getelementptr inbounds i64, i64* %19, i64 1
  store i64* %20, i64** %14, align 8, !tbaa !39
  %exceptionValue = alloca i64, align 8, !dbg !79
  %21 = icmp eq i32 %argc, 1, !dbg !80
  br i1 %21, label %fillRequiredArgs, label %argCountFailBlock, !dbg !80, !prof !81

argCountFailBlock:                                ; preds = %functionEntryInitializers
  tail call void @sorbet_raiseArity(i32 %argc, i32 1, i32 1) #10, !dbg !80
  unreachable, !dbg !80

fillRequiredArgs:                                 ; preds = %functionEntryInitializers
  %22 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !80, !tbaa !39
  %23 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %22, i64 0, i32 2, !dbg !80
  %24 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %23, align 8, !dbg !80, !tbaa !40
  %25 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %24, i64 0, i32 4, !dbg !80
  %26 = load i64*, i64** %25, align 8, !dbg !80, !tbaa !46
  %27 = load i64, i64* %26, align 8, !dbg !80, !tbaa !14
  %28 = and i64 %27, 8, !dbg !80
  %29 = icmp eq i64 %28, 0, !dbg !80
  br i1 %29, label %30, label %32, !dbg !80, !prof !70

30:                                               ; preds = %fillRequiredArgs
  %31 = getelementptr inbounds i64, i64* %26, i64 -5, !dbg !80
  store i64 %selfRaw, i64* %31, align 8, !dbg !80, !tbaa !14
  br label %sorbet_writeLocal.exit, !dbg !80

32:                                               ; preds = %fillRequiredArgs
  tail call void @sorbet_vm_env_write_slowpath(i64* nonnull %26, i32 -5, i64 %selfRaw) #10, !dbg !80
  br label %sorbet_writeLocal.exit, !dbg !80

sorbet_writeLocal.exit:                           ; preds = %30, %32
  %rawArg_arg = load i64, i64* %argArray, align 8, !dbg !80
  %33 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !80, !tbaa !39
  %34 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %33, i64 0, i32 2, !dbg !80
  %35 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %34, align 8, !dbg !80, !tbaa !40
  %36 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %35, i64 0, i32 4, !dbg !80
  %37 = load i64*, i64** %36, align 8, !dbg !80, !tbaa !46
  %38 = load i64, i64* %37, align 8, !dbg !80, !tbaa !14
  %39 = and i64 %38, 8, !dbg !80
  %40 = icmp eq i64 %39, 0, !dbg !80
  br i1 %40, label %41, label %43, !dbg !80, !prof !70

41:                                               ; preds = %sorbet_writeLocal.exit
  %42 = getelementptr inbounds i64, i64* %37, i64 -4, !dbg !80
  store i64 %rawArg_arg, i64* %42, align 8, !dbg !80, !tbaa !14
  br label %sorbet_writeLocal.exit28, !dbg !80

43:                                               ; preds = %sorbet_writeLocal.exit
  tail call void @sorbet_vm_env_write_slowpath(i64* nonnull %37, i32 -4, i64 %rawArg_arg) #10, !dbg !80
  br label %sorbet_writeLocal.exit28, !dbg !80

sorbet_writeLocal.exit28:                         ; preds = %41, %43
  %44 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !82, !tbaa !39
  %45 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %44, i64 0, i32 2, !dbg !82
  %46 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %45, align 8, !dbg !82, !tbaa !40
  %47 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %46, i64 0, i32 4, !dbg !82
  %48 = load i64*, i64** %47, align 8, !dbg !82, !tbaa !46
  %49 = load i64, i64* %48, align 8, !dbg !82, !tbaa !14
  %50 = and i64 %49, 8, !dbg !82
  %51 = icmp eq i64 %50, 0, !dbg !82
  br i1 %51, label %sorbet_writeLocal.exit29, label %52, !dbg !82, !prof !70

52:                                               ; preds = %sorbet_writeLocal.exit28
  %53 = getelementptr inbounds i64, i64* %48, i64 -5, !dbg !82
  %54 = load i64, i64* %53, align 8, !dbg !82, !tbaa !14
  tail call void @sorbet_vm_env_write_slowpath(i64* nonnull %48, i32 -5, i64 %54) #10, !dbg !82
  br label %sorbet_writeLocal.exit29, !dbg !82

sorbet_writeLocal.exit29:                         ; preds = %sorbet_writeLocal.exit28, %52
  %55 = getelementptr inbounds i64, i64* %19, i64 3, !dbg !82
  store i64* %55, i64** %14, align 8, !dbg !82, !tbaa !39
  %previousException = tail call i64 @rb_errinfo() #10, !dbg !79
  %56 = bitcast i64* %0 to i8*, !dbg !82
  %57 = bitcast %struct.ExceptionClosure* %1 to i8*, !dbg !82
  %58 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %1, i64 0, i32 0, !dbg !82
  %59 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %1, i64 0, i32 1, !dbg !82
  %60 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %1, i64 0, i32 2, !dbg !82
  %61 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %1, i64 0, i32 3, !dbg !82
  %62 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %1, i64 0, i32 4, !dbg !82
  %63 = icmp eq i64 %previousException, 8, !dbg !82
  %64 = ptrtoint %struct.ExceptionClosure* %1 to i64, !dbg !82
  %65 = ptrtoint i64* %exceptionValue to i64, !dbg !82
  %66 = bitcast i64* %2 to i8*, !dbg !82
  %67 = bitcast %struct.ExceptionClosure* %3 to i8*, !dbg !82
  %68 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %3, i64 0, i32 0, !dbg !82
  %69 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %3, i64 0, i32 1, !dbg !82
  %70 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %3, i64 0, i32 2, !dbg !82
  %71 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %3, i64 0, i32 3, !dbg !82
  %72 = getelementptr inbounds %struct.ExceptionClosure, %struct.ExceptionClosure* %3, i64 0, i32 4, !dbg !82
  %73 = ptrtoint %struct.ExceptionClosure* %3 to i64, !dbg !82
  br i1 %63, label %exception-entry.us, label %exception-entry, !dbg !79

exception-entry.us:                               ; preds = %sorbet_writeLocal.exit29, %sorbet_try.exit.us
  %74 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !79, !tbaa !39
  %75 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %74, i64 0, i32 2, !dbg !79
  %76 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %75, align 8, !dbg !79, !tbaa !40
  %77 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %76, i64 0, i32 4, !dbg !79
  %78 = load i64*, i64** %77, align 8, !dbg !79, !tbaa !46
  %79 = load i64, i64* %78, align 8, !dbg !79, !tbaa !14
  %80 = and i64 %79, 8, !dbg !79
  %81 = icmp eq i64 %80, 0, !dbg !79
  br i1 %81, label %83, label %82, !dbg !79, !prof !70

82:                                               ; preds = %exception-entry.us
  call void @sorbet_vm_env_write_slowpath(i64* nonnull %78, i32 -3, i64 8) #10, !dbg !79
  br label %sorbet_writeLocal.exit30.us, !dbg !79

83:                                               ; preds = %exception-entry.us
  %84 = getelementptr inbounds i64, i64* %78, i64 -3, !dbg !79
  store i64 8, i64* %84, align 8, !dbg !79, !tbaa !14
  br label %sorbet_writeLocal.exit30.us, !dbg !79

sorbet_writeLocal.exit30.us:                      ; preds = %83, %82
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %56) #10, !dbg !79
  store i64 52, i64* %0, align 8, !dbg !79, !tbaa !14
  call void @llvm.lifetime.start.p0i8(i64 40, i8* nonnull %57) #10, !dbg !79
  store i64 (i64**, i64*, i64)* @"func_Test.test_nilable_arg$block_1", i64 (i64**, i64*, i64)** %58, align 8, !dbg !79, !tbaa !4
  store i64** %14, i64*** %59, align 8, !dbg !79, !tbaa !10
  store i64* %19, i64** %60, align 8, !dbg !79, !tbaa !11
  store i64 0, i64* %61, align 8, !dbg !79, !tbaa !12
  store i64* %0, i64** %62, align 8, !dbg !79, !tbaa !13
  store i64 8, i64* %exceptionValue, align 8, !dbg !79, !tbaa !14
  %85 = load i64, i64* @rb_eException, align 8, !dbg !79, !tbaa !14
  %86 = call i64 (i64 (i64)*, i64, i64 (i64, i64)*, i64, ...) @rb_rescue2(i64 (i64)* nonnull @sorbet_applyExceptionClosure, i64 %64, i64 (i64, i64)* nonnull @sorbet_rescueStoreException, i64 %65, i64 %85, i32 0) #10, !dbg !79
  %87 = load i64, i64* %0, align 8, !dbg !79
  call void @llvm.lifetime.end.p0i8(i64 40, i8* nonnull %57) #10, !dbg !79
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %56) #10, !dbg !79
  %isReturnValue.us = icmp eq i64 %87, 52, !dbg !79
  br i1 %isReturnValue.us, label %exception-body-continue.us, label %exception-body-return, !dbg !79

exception-body-continue.us:                       ; preds = %sorbet_writeLocal.exit30.us
  %88 = load i64, i64* %exceptionValue, align 8, !dbg !79
  %89 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !79, !tbaa !39
  %90 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %89, i64 0, i32 2, !dbg !79
  %91 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %90, align 8, !dbg !79, !tbaa !40
  %92 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %91, i64 0, i32 4, !dbg !79
  %93 = load i64*, i64** %92, align 8, !dbg !79, !tbaa !46
  %94 = load i64, i64* %93, align 8, !dbg !79, !tbaa !14
  %95 = and i64 %94, 8, !dbg !79
  %96 = icmp eq i64 %95, 0, !dbg !79
  br i1 %96, label %98, label %97, !dbg !79, !prof !70

97:                                               ; preds = %exception-body-continue.us
  call void @sorbet_vm_env_write_slowpath(i64* nonnull %93, i32 -3, i64 %88) #10, !dbg !79
  br label %sorbet_writeLocal.exit31.us, !dbg !79

98:                                               ; preds = %exception-body-continue.us
  %99 = getelementptr inbounds i64, i64* %93, i64 -3, !dbg !79
  store i64 %88, i64* %99, align 8, !dbg !79, !tbaa !14
  br label %sorbet_writeLocal.exit31.us, !dbg !79

sorbet_writeLocal.exit31.us:                      ; preds = %98, %97
  %100 = icmp ne i64 %88, 8, !dbg !79
  %handler.us = select i1 %100, i64 (i64**, i64*, i64)* @"func_Test.test_nilable_arg$block_2", i64 (i64**, i64*, i64)* @"func_Test.test_nilable_arg$block_4", !dbg !79
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %66) #10, !dbg !79
  store i64 52, i64* %2, align 8, !dbg !79, !tbaa !14
  call void @llvm.lifetime.start.p0i8(i64 40, i8* nonnull %67) #10, !dbg !79
  store i64 (i64**, i64*, i64)* %handler.us, i64 (i64**, i64*, i64)** %68, align 8, !dbg !79, !tbaa !4
  store i64** %14, i64*** %69, align 8, !dbg !79, !tbaa !10
  store i64* %19, i64** %70, align 8, !dbg !79, !tbaa !11
  store i64 0, i64* %71, align 8, !dbg !79, !tbaa !12
  store i64* %2, i64** %72, align 8, !dbg !79, !tbaa !13
  store i64 8, i64* %exceptionValue, align 8, !dbg !79, !tbaa !14
  %101 = icmp eq i64 %88, 8, !dbg !79
  br i1 %101, label %sorbet_try.exit.us, label %102, !dbg !79

102:                                              ; preds = %sorbet_writeLocal.exit31.us
  call void @rb_set_errinfo(i64 %88) #10, !dbg !79
  br label %sorbet_try.exit.us, !dbg !79

sorbet_try.exit.us:                               ; preds = %102, %sorbet_writeLocal.exit31.us
  %103 = load i64, i64* @rb_eException, align 8, !dbg !79, !tbaa !14
  %104 = call i64 (i64 (i64)*, i64, i64 (i64, i64)*, i64, ...) @rb_rescue2(i64 (i64)* nonnull @sorbet_applyExceptionClosure, i64 %73, i64 (i64, i64)* nonnull @sorbet_rescueStoreException, i64 %65, i64 %103, i32 0) #10, !dbg !79
  %105 = load i64, i64* %2, align 8, !dbg !79
  call void @llvm.lifetime.end.p0i8(i64 40, i8* nonnull %67) #10, !dbg !79
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %66) #10, !dbg !79
  %106 = load i64, i64* %exceptionValue, align 8, !dbg !79
  %107 = icmp eq i64 %106, 8, !dbg !79
  %108 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !79, !tbaa !39
  %109 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %108, i64 0, i32 2, !dbg !79
  %110 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %109, align 8, !dbg !79, !tbaa !40
  %111 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %110, i64 0, i32 4, !dbg !79
  %112 = load i64*, i64** %111, align 8, !dbg !79, !tbaa !46
  %113 = getelementptr inbounds i64, i64* %112, i64 -3, !dbg !79
  %114 = load i64, i64* %113, align 8, !dbg !79, !tbaa !14
  %115 = select i1 %107, i64 %114, i64 %106, !dbg !79
  call void @rb_set_errinfo(i64 %115) #10, !dbg !79
  %"<retry-singleton>.us" = load i64, i64* @"<retry-singleton>", align 8, !dbg !79
  %shouldRetry.us = icmp eq i64 %105, %"<retry-singleton>.us", !dbg !79
  %116 = and i1 %100, %shouldRetry.us, !dbg !79
  br i1 %116, label %exception-entry.us, label %exception-ensure, !dbg !79

exception-entry:                                  ; preds = %sorbet_writeLocal.exit29, %sorbet_try.exit
  %117 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !79, !tbaa !39
  %118 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %117, i64 0, i32 2, !dbg !79
  %119 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %118, align 8, !dbg !79, !tbaa !40
  %120 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %119, i64 0, i32 4, !dbg !79
  %121 = load i64*, i64** %120, align 8, !dbg !79, !tbaa !46
  %122 = load i64, i64* %121, align 8, !dbg !79, !tbaa !14
  %123 = and i64 %122, 8, !dbg !79
  %124 = icmp eq i64 %123, 0, !dbg !79
  br i1 %124, label %125, label %127, !dbg !79, !prof !70

125:                                              ; preds = %exception-entry
  %126 = getelementptr inbounds i64, i64* %121, i64 -3, !dbg !79
  store i64 8, i64* %126, align 8, !dbg !79, !tbaa !14
  br label %sorbet_writeLocal.exit30, !dbg !79

127:                                              ; preds = %exception-entry
  call void @sorbet_vm_env_write_slowpath(i64* nonnull %121, i32 -3, i64 8) #10, !dbg !79
  br label %sorbet_writeLocal.exit30, !dbg !79

sorbet_writeLocal.exit30:                         ; preds = %125, %127
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %56) #10, !dbg !79
  store i64 52, i64* %0, align 8, !dbg !79, !tbaa !14
  call void @llvm.lifetime.start.p0i8(i64 40, i8* nonnull %57) #10, !dbg !79
  store i64 (i64**, i64*, i64)* @"func_Test.test_nilable_arg$block_1", i64 (i64**, i64*, i64)** %58, align 8, !dbg !79, !tbaa !4
  store i64** %14, i64*** %59, align 8, !dbg !79, !tbaa !10
  store i64* %19, i64** %60, align 8, !dbg !79, !tbaa !11
  store i64 0, i64* %61, align 8, !dbg !79, !tbaa !12
  store i64* %0, i64** %62, align 8, !dbg !79, !tbaa !13
  store i64 8, i64* %exceptionValue, align 8, !dbg !79, !tbaa !14
  call void @rb_set_errinfo(i64 %previousException) #10, !dbg !79
  %128 = load i64, i64* @rb_eException, align 8, !dbg !79, !tbaa !14
  %129 = call i64 (i64 (i64)*, i64, i64 (i64, i64)*, i64, ...) @rb_rescue2(i64 (i64)* nonnull @sorbet_applyExceptionClosure, i64 %64, i64 (i64, i64)* nonnull @sorbet_rescueStoreException, i64 %65, i64 %128, i32 0) #10, !dbg !79
  %130 = load i64, i64* %0, align 8, !dbg !79
  call void @llvm.lifetime.end.p0i8(i64 40, i8* nonnull %57) #10, !dbg !79
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %56) #10, !dbg !79
  %isReturnValue = icmp eq i64 %130, 52, !dbg !79
  br i1 %isReturnValue, label %exception-body-continue, label %exception-body-return, !dbg !79

exception-body-return:                            ; preds = %sorbet_writeLocal.exit30, %sorbet_writeLocal.exit30.us
  %.lcssa = phi i64 [ %87, %sorbet_writeLocal.exit30.us ], [ %130, %sorbet_writeLocal.exit30 ], !dbg !79
  call void @rb_set_errinfo(i64 %previousException) #10, !dbg !79
  %"stackFrame_func_Test.test_nilable_arg$block_31.i35" = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** bitcast (i8** @"stackFramePrecomputed_func_Test.test_nilable_arg$block_3" to %struct.rb_iseq_struct**), align 8
  %131 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !39
  %132 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %131, i64 0, i32 2
  %133 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %132, align 8, !tbaa !40
  call void @sorbet_setExceptionStackFrame(%struct.rb_execution_context_struct* %131, %struct.rb_control_frame_struct* %133, %struct.rb_iseq_struct* %"stackFrame_func_Test.test_nilable_arg$block_31.i35") #10
  %134 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %133, i64 0, i32 0
  %135 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %133, i64 0, i32 2
  %136 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %135, align 8, !tbaa !44
  %137 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %136, i64 0, i32 2
  %138 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %137, align 8, !tbaa !47
  %139 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %138, i64 0, i32 2
  %140 = load i64*, i64** %139, align 8, !tbaa !49
  %141 = getelementptr inbounds i64, i64* %140, i64 1
  store i64* %141, i64** %134, align 8, !tbaa !39
  call void @sorbet_popRubyStack() #10
  ret i64 %.lcssa, !dbg !79

exception-body-continue:                          ; preds = %sorbet_writeLocal.exit30
  %142 = load i64, i64* %exceptionValue, align 8, !dbg !79
  %143 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !79, !tbaa !39
  %144 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %143, i64 0, i32 2, !dbg !79
  %145 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %144, align 8, !dbg !79, !tbaa !40
  %146 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %145, i64 0, i32 4, !dbg !79
  %147 = load i64*, i64** %146, align 8, !dbg !79, !tbaa !46
  %148 = load i64, i64* %147, align 8, !dbg !79, !tbaa !14
  %149 = and i64 %148, 8, !dbg !79
  %150 = icmp eq i64 %149, 0, !dbg !79
  br i1 %150, label %151, label %153, !dbg !79, !prof !70

151:                                              ; preds = %exception-body-continue
  %152 = getelementptr inbounds i64, i64* %147, i64 -3, !dbg !79
  store i64 %142, i64* %152, align 8, !dbg !79, !tbaa !14
  br label %sorbet_writeLocal.exit31, !dbg !79

153:                                              ; preds = %exception-body-continue
  call void @sorbet_vm_env_write_slowpath(i64* nonnull %147, i32 -3, i64 %142) #10, !dbg !79
  br label %sorbet_writeLocal.exit31, !dbg !79

sorbet_writeLocal.exit31:                         ; preds = %151, %153
  %154 = icmp ne i64 %142, 8, !dbg !79
  %handler = select i1 %154, i64 (i64**, i64*, i64)* @"func_Test.test_nilable_arg$block_2", i64 (i64**, i64*, i64)* @"func_Test.test_nilable_arg$block_4", !dbg !79
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %66) #10, !dbg !79
  store i64 52, i64* %2, align 8, !dbg !79, !tbaa !14
  call void @llvm.lifetime.start.p0i8(i64 40, i8* nonnull %67) #10, !dbg !79
  store i64 (i64**, i64*, i64)* %handler, i64 (i64**, i64*, i64)** %68, align 8, !dbg !79, !tbaa !4
  store i64** %14, i64*** %69, align 8, !dbg !79, !tbaa !10
  store i64* %19, i64** %70, align 8, !dbg !79, !tbaa !11
  store i64 0, i64* %71, align 8, !dbg !79, !tbaa !12
  store i64* %2, i64** %72, align 8, !dbg !79, !tbaa !13
  store i64 8, i64* %exceptionValue, align 8, !dbg !79, !tbaa !14
  %155 = icmp eq i64 %142, 8, !dbg !79
  br i1 %155, label %sorbet_try.exit, label %156, !dbg !79

156:                                              ; preds = %sorbet_writeLocal.exit31
  call void @rb_set_errinfo(i64 %142) #10, !dbg !79
  br label %sorbet_try.exit, !dbg !79

sorbet_try.exit:                                  ; preds = %sorbet_writeLocal.exit31, %156
  %157 = load i64, i64* @rb_eException, align 8, !dbg !79, !tbaa !14
  %158 = call i64 (i64 (i64)*, i64, i64 (i64, i64)*, i64, ...) @rb_rescue2(i64 (i64)* nonnull @sorbet_applyExceptionClosure, i64 %73, i64 (i64, i64)* nonnull @sorbet_rescueStoreException, i64 %65, i64 %157, i32 0) #10, !dbg !79
  %159 = load i64, i64* %2, align 8, !dbg !79
  call void @llvm.lifetime.end.p0i8(i64 40, i8* nonnull %67) #10, !dbg !79
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %66) #10, !dbg !79
  %160 = load i64, i64* %exceptionValue, align 8, !dbg !79
  %161 = icmp eq i64 %160, 8, !dbg !79
  %162 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !79, !tbaa !39
  %163 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %162, i64 0, i32 2, !dbg !79
  %164 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %163, align 8, !dbg !79, !tbaa !40
  %165 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %164, i64 0, i32 4, !dbg !79
  %166 = load i64*, i64** %165, align 8, !dbg !79, !tbaa !46
  %167 = getelementptr inbounds i64, i64* %166, i64 -3, !dbg !79
  %168 = load i64, i64* %167, align 8, !dbg !79, !tbaa !14
  %169 = icmp eq i64 %168, 8, !dbg !79
  %170 = select i1 %169, i64 %previousException, i64 %168, !dbg !79
  %171 = select i1 %161, i64 %170, i64 %160, !dbg !79
  call void @rb_set_errinfo(i64 %171) #10, !dbg !79
  %"<retry-singleton>" = load i64, i64* @"<retry-singleton>", align 8, !dbg !79
  %shouldRetry = icmp eq i64 %159, %"<retry-singleton>", !dbg !79
  %172 = and i1 %154, %shouldRetry, !dbg !79
  br i1 %172, label %exception-entry, label %exception-ensure, !dbg !79

exception-ensure:                                 ; preds = %sorbet_try.exit, %sorbet_try.exit.us
  %.lcssa39 = phi i64 [ %105, %sorbet_try.exit.us ], [ %159, %sorbet_try.exit ], !dbg !79
  %.lcssa38 = phi i64 [ %115, %sorbet_try.exit.us ], [ %171, %sorbet_try.exit ], !dbg !79
  %"stackFrame_func_Test.test_nilable_arg$block_31.i" = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** bitcast (i8** @"stackFramePrecomputed_func_Test.test_nilable_arg$block_3" to %struct.rb_iseq_struct**), align 8
  %173 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !39
  %174 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %173, i64 0, i32 2
  %175 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %174, align 8, !tbaa !40
  call void @sorbet_setExceptionStackFrame(%struct.rb_execution_context_struct* %173, %struct.rb_control_frame_struct* %175, %struct.rb_iseq_struct* %"stackFrame_func_Test.test_nilable_arg$block_31.i") #10
  %176 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %175, i64 0, i32 0
  %177 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %175, i64 0, i32 2
  %178 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %177, align 8, !tbaa !44
  %179 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %178, i64 0, i32 2
  %180 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %179, align 8, !tbaa !47
  %181 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %180, i64 0, i32 2
  %182 = load i64*, i64** %181, align 8, !tbaa !49
  %183 = getelementptr inbounds i64, i64* %182, i64 1
  store i64* %183, i64** %176, align 8, !tbaa !39
  call void @sorbet_popRubyStack() #10
  %isReturnValue13 = icmp eq i64 %.lcssa39, 52, !dbg !79
  br i1 %isReturnValue13, label %exception-continue, label %exception-return, !dbg !79

exception-continue:                               ; preds = %exception-ensure
  %184 = icmp eq i64 %.lcssa38, 8, !dbg !79
  br i1 %184, label %sorbet_raiseIfNotNil.exit, label %185, !dbg !79

185:                                              ; preds = %exception-continue
  call void @rb_exc_raise(i64 %.lcssa38) #11, !dbg !79
  unreachable, !dbg !79

sorbet_raiseIfNotNil.exit:                        ; preds = %exception-continue
  %186 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !79, !tbaa !39
  %187 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %186, i64 0, i32 2, !dbg !79
  %188 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %187, align 8, !dbg !79, !tbaa !40
  %189 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %188, i64 0, i32 4, !dbg !79
  %190 = load i64*, i64** %189, align 8, !dbg !79, !tbaa !46
  %191 = getelementptr inbounds i64, i64* %190, i64 -3, !dbg !79
  %192 = load i64, i64* %191, align 8, !dbg !79, !tbaa !14
  %193 = icmp eq i64 %192, 8, !dbg !79
  br i1 %193, label %sorbet_raiseIfNotNil.exit32, label %194, !dbg !79

194:                                              ; preds = %sorbet_raiseIfNotNil.exit
  call void @rb_exc_raise(i64 %192) #11, !dbg !79
  unreachable, !dbg !79

sorbet_raiseIfNotNil.exit32:                      ; preds = %sorbet_raiseIfNotNil.exit
  store i64* %20, i64** %14, align 8, !tbaa !39
  %195 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !80, !tbaa !39
  %196 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %195, i64 0, i32 2, !dbg !80
  %197 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %196, align 8, !dbg !80, !tbaa !40
  %198 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %197, i64 0, i32 4, !dbg !80
  %199 = load i64*, i64** %198, align 8, !dbg !80, !tbaa !46
  %200 = getelementptr inbounds i64, i64* %199, i64 -7, !dbg !80
  %201 = load i64, i64* %200, align 8, !dbg !80, !tbaa !14
  ret i64 %201

exception-return:                                 ; preds = %exception-ensure
  ret i64 %.lcssa39, !dbg !79
}

; Function Attrs: ssp
define internal i64 @"func_Test.test_nilable_arg$block_1"(i64** nocapture %pc, i64* %iseq_encoded, i64 %localsOffset) #8 !dbg !30 {
fastSymCallIntrinsic_T_must:
  %callArgs = alloca [3 x i64], align 8
  %0 = getelementptr inbounds i64, i64* %iseq_encoded, i64 3
  store i64* %0, i64** %pc, align 8, !tbaa !39
  %1 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !29, !tbaa !39
  %2 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %1, i64 0, i32 2, !dbg !29
  %3 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %2, align 8, !dbg !29, !tbaa !40
  %4 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 4, !dbg !29
  %5 = load i64*, i64** %4, align 8, !dbg !29, !tbaa !46
  %6 = getelementptr inbounds i64, i64* %5, i64 -4, !dbg !29
  %7 = load i64, i64* %6, align 8, !dbg !29, !tbaa !14
  %callArgs0Addr = getelementptr inbounds [3 x i64], [3 x i64]* %callArgs, i64 0, i64 0, !dbg !29
  store i64 %7, i64* %callArgs0Addr, align 8, !dbg !29
  %8 = icmp eq i64 %7, 8, !dbg !29
  br i1 %8, label %39, label %afterSend, !dbg !29, !prof !83

afterSend:                                        ; preds = %fastSymCallIntrinsic_T_must
  %9 = getelementptr inbounds i64, i64* %iseq_encoded, i64 4, !dbg !29
  store i64* %9, i64** %pc, align 8, !dbg !29, !tbaa !39
  %"rubyStr_ wasn't nil" = load i64, i64* @"rubyStrFrozen_ wasn't nil", align 8, !dbg !84
  %10 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !85, !tbaa !39
  %11 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %10, i64 0, i32 2, !dbg !85
  %12 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %11, align 8, !dbg !85, !tbaa !40
  %13 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %12, i64 0, i32 4, !dbg !85
  %14 = load i64*, i64** %13, align 8, !dbg !85, !tbaa !46
  %15 = getelementptr inbounds i64, i64* %14, i64 -4, !dbg !85
  %16 = load i64, i64* %15, align 8, !dbg !85, !tbaa !14
  store i64 %16, i64* %callArgs0Addr, align 8, !dbg !85
  %callArgs1Addr = getelementptr inbounds [3 x i64], [3 x i64]* %callArgs, i64 0, i64 1, !dbg !85
  store i64 %"rubyStr_ wasn't nil", i64* %callArgs1Addr, align 8, !dbg !85
  %"rubyId_<string-interpolate>" = load i64, i64* @"rubyIdPrecomputed_<string-interpolate>", align 8, !dbg !85
  %rawSendResult11 = call i64 @sorbet_stringInterpolate(i64 8, i64 %"rubyId_<string-interpolate>", i32 2, i64* nonnull %callArgs0Addr, i64 (i64, i64, i32, i64*, i64)* null, i64 %localsOffset), !dbg !85
  %17 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !32, !tbaa !39
  %18 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %17, i64 0, i32 2, !dbg !32
  %19 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %18, align 8, !dbg !32, !tbaa !40
  %20 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %19, i64 0, i32 4, !dbg !32
  %21 = load i64*, i64** %20, align 8, !dbg !32, !tbaa !46
  %22 = getelementptr inbounds i64, i64* %21, i64 -5, !dbg !32
  %23 = load i64, i64* %22, align 8, !dbg !32, !tbaa !14
  %24 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %19, i64 0, i32 1, !dbg !32
  %25 = load i64*, i64** %24, align 8, !dbg !32, !tbaa !67
  %26 = getelementptr inbounds i64, i64* %25, i64 1, !dbg !32
  store i64 %23, i64* %25, align 8, !dbg !32, !tbaa !14
  %27 = getelementptr inbounds i64, i64* %25, i64 2, !dbg !32
  store i64* %27, i64** %24, align 8, !dbg !32, !tbaa !67
  store i64 %rawSendResult11, i64* %26, align 8, !dbg !32, !tbaa !14
  %send15 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_puts.4, i64 0), !dbg !32
  %28 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !32, !tbaa !39
  %29 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %28, i64 0, i32 2, !dbg !32
  %30 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %29, align 8, !dbg !32, !tbaa !40
  %31 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %30, i64 0, i32 4, !dbg !32
  %32 = load i64*, i64** %31, align 8, !dbg !32, !tbaa !46
  %33 = load i64, i64* %32, align 8, !dbg !32, !tbaa !14
  %34 = and i64 %33, 8, !dbg !32
  %35 = icmp eq i64 %34, 0, !dbg !32
  br i1 %35, label %36, label %38, !dbg !32, !prof !70

36:                                               ; preds = %afterSend
  %37 = getelementptr inbounds i64, i64* %32, i64 -7, !dbg !32
  store i64 %send15, i64* %37, align 8, !dbg !32, !tbaa !14
  br label %sorbet_writeLocal.exit, !dbg !32

38:                                               ; preds = %afterSend
  call void @sorbet_vm_env_write_slowpath(i64* nonnull %32, i32 -7, i64 %send15) #10, !dbg !32
  br label %sorbet_writeLocal.exit, !dbg !32

sorbet_writeLocal.exit:                           ; preds = %36, %38
  store i64* %0, i64** %pc, align 8, !dbg !32, !tbaa !39
  ret i64 52

39:                                               ; preds = %fastSymCallIntrinsic_T_must
  %40 = load i64, i64* @rb_eTypeError, align 8, !dbg !29, !tbaa !14, !noalias !86
  tail call void (i64, i8*, ...) @rb_raise(i64 %40, i8* getelementptr inbounds ([25 x i8], [25 x i8]* @.str.2, i64 0, i64 0)) #11, !dbg !29, !noalias !86
  unreachable, !dbg !29
}

; Function Attrs: ssp
define internal i64 @"func_Test.test_nilable_arg$block_2"(i64** nocapture readnone %pc, i64* nocapture readnone %iseq_encoded, i64 %localsOffset) #8 !dbg !34 {
.preheader.i30:
  %"stackFrame_func_Test.test_nilable_arg$block_223" = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** bitcast (i8** @"stackFramePrecomputed_func_Test.test_nilable_arg$block_2" to %struct.rb_iseq_struct**), align 8
  %0 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !39
  %1 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %0, i64 0, i32 2
  %2 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %1, align 8, !tbaa !40
  tail call void @sorbet_setExceptionStackFrame(%struct.rb_execution_context_struct* %0, %struct.rb_control_frame_struct* %2, %struct.rb_iseq_struct* %"stackFrame_func_Test.test_nilable_arg$block_223") #10
  %3 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 0
  %4 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 2
  %5 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %4, align 8, !tbaa !44
  %6 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %5, i64 0, i32 2
  %7 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %6, align 8, !tbaa !47
  %8 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %7, i64 0, i32 2
  %9 = load i64*, i64** %8, align 8, !tbaa !49
  %10 = getelementptr inbounds i64, i64* %9, i64 5
  store i64* %10, i64** %3, align 8, !tbaa !39
  %11 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !33, !tbaa !39
  %12 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %11, i64 0, i32 2, !dbg !33
  %13 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %12, align 8, !dbg !33, !tbaa !40
  %14 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %13, i64 0, i32 4, !dbg !33
  %15 = load i64*, i64** %14, align 8, !dbg !33, !tbaa !46
  %16 = getelementptr inbounds i64, i64* %15, i64 -1, !dbg !33
  %17 = load i64, i64* %16, align 8, !dbg !33, !tbaa !14
  %18 = and i64 %17, -4, !dbg !33
  %19 = inttoptr i64 %18 to i64*, !dbg !33
  %20 = getelementptr inbounds i64, i64* %19, i64 -3, !dbg !33
  %21 = load i64, i64* %20, align 8, !dbg !33, !tbaa !14
  %22 = load i64, i64* @rb_eStandardError, align 8, !dbg !33
  %23 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %13, i64 0, i32 1, !dbg !33
  %24 = load i64*, i64** %23, align 8, !dbg !33, !tbaa !67
  %25 = getelementptr inbounds i64, i64* %24, i64 1, !dbg !33
  store i64 %21, i64* %24, align 8, !dbg !33, !tbaa !14
  %26 = getelementptr inbounds i64, i64* %24, i64 2, !dbg !33
  store i64* %26, i64** %23, align 8, !dbg !33, !tbaa !67
  store i64 %22, i64* %25, align 8, !dbg !33, !tbaa !14
  %send = tail call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @"ic_is_a?.5", i64 0), !dbg !33
  %27 = and i64 %send, -9, !dbg !33
  %28 = icmp eq i64 %27, 0, !dbg !33
  br i1 %28, label %.preheader.i, label %.preheader.i28, !dbg !33

blockExit:                                        ; preds = %90, %88, %74, %72
  tail call void @sorbet_popRubyStack()
  ret i64 52

.preheader.i28:                                   ; preds = %.preheader.i30
  %29 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !89, !tbaa !39
  %30 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %29, i64 0, i32 2, !dbg !89
  %31 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %30, align 8, !dbg !89, !tbaa !40
  %32 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %31, i64 0, i32 4, !dbg !89
  %33 = load i64*, i64** %32, align 8, !dbg !89, !tbaa !46
  %34 = getelementptr inbounds i64, i64* %33, i64 -1, !dbg !89
  %35 = load i64, i64* %34, align 8, !dbg !89, !tbaa !14
  %36 = and i64 %35, -4, !dbg !89
  %37 = inttoptr i64 %36 to i64*, !dbg !89
  %38 = load i64, i64* %37, align 8, !dbg !89, !tbaa !14
  %39 = and i64 %38, 8, !dbg !89
  %40 = icmp eq i64 %39, 0, !dbg !89
  br i1 %40, label %41, label %43, !dbg !89, !prof !70

41:                                               ; preds = %.preheader.i28
  %42 = getelementptr inbounds i64, i64* %37, i64 -3, !dbg !89
  store i64 8, i64* %42, align 8, !dbg !89, !tbaa !14
  br label %.preheader.i24, !dbg !89

43:                                               ; preds = %.preheader.i28
  tail call void @sorbet_vm_env_write_slowpath(i64* nonnull %37, i32 -3, i64 8) #10, !dbg !89
  br label %.preheader.i24, !dbg !89

.preheader.i24:                                   ; preds = %41, %43
  %44 = getelementptr inbounds i64, i64* %9, i64 6, !dbg !90
  store i64* %44, i64** %3, align 8, !dbg !90, !tbaa !39
  %45 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !35, !tbaa !39
  %46 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %45, i64 0, i32 2, !dbg !35
  %47 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %46, align 8, !dbg !35, !tbaa !40
  %48 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %47, i64 0, i32 4, !dbg !35
  %49 = load i64*, i64** %48, align 8, !dbg !35, !tbaa !46
  %50 = getelementptr inbounds i64, i64* %49, i64 -1, !dbg !35
  %51 = load i64, i64* %50, align 8, !dbg !35, !tbaa !14
  %52 = and i64 %51, -4, !dbg !35
  %53 = inttoptr i64 %52 to i64*, !dbg !35
  %54 = getelementptr inbounds i64, i64* %53, i64 -5, !dbg !35
  %55 = load i64, i64* %54, align 8, !dbg !35, !tbaa !14
  %56 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %47, i64 0, i32 1, !dbg !35
  %57 = load i64*, i64** %56, align 8, !dbg !35, !tbaa !67
  %58 = getelementptr inbounds i64, i64* %57, i64 1, !dbg !35
  store i64 %55, i64* %57, align 8, !dbg !35, !tbaa !14
  %59 = getelementptr inbounds i64, i64* %57, i64 2, !dbg !35
  store i64* %59, i64** %56, align 8, !dbg !35, !tbaa !67
  store i64 %21, i64* %58, align 8, !dbg !35, !tbaa !14
  %send11 = tail call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_puts.6, i64 0), !dbg !35
  %60 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !35, !tbaa !39
  %61 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %60, i64 0, i32 2, !dbg !35
  %62 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %61, align 8, !dbg !35, !tbaa !40
  %63 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %62, i64 0, i32 4, !dbg !35
  %64 = load i64*, i64** %63, align 8, !dbg !35, !tbaa !46
  %65 = getelementptr inbounds i64, i64* %64, i64 -1, !dbg !35
  %66 = load i64, i64* %65, align 8, !dbg !35, !tbaa !14
  %67 = and i64 %66, -4, !dbg !35
  %68 = inttoptr i64 %67 to i64*, !dbg !35
  %69 = load i64, i64* %68, align 8, !dbg !35, !tbaa !14
  %70 = and i64 %69, 8, !dbg !35
  %71 = icmp eq i64 %70, 0, !dbg !35
  br i1 %71, label %72, label %74, !dbg !35, !prof !70

72:                                               ; preds = %.preheader.i24
  %73 = getelementptr inbounds i64, i64* %68, i64 -7, !dbg !35
  store i64 %send11, i64* %73, align 8, !dbg !35, !tbaa !14
  br label %blockExit, !dbg !35

74:                                               ; preds = %.preheader.i24
  tail call void @sorbet_vm_env_write_slowpath(i64* nonnull %68, i32 -7, i64 %send11) #10, !dbg !35
  br label %blockExit, !dbg !35

.preheader.i:                                     ; preds = %.preheader.i30
  %75 = getelementptr inbounds i64, i64* %9, i64 3
  store i64* %75, i64** %3, align 8, !tbaa !39
  %76 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !91, !tbaa !39
  %77 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %76, i64 0, i32 2, !dbg !91
  %78 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %77, align 8, !dbg !91, !tbaa !40
  %79 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %78, i64 0, i32 4, !dbg !91
  %80 = load i64*, i64** %79, align 8, !dbg !91, !tbaa !46
  %81 = getelementptr inbounds i64, i64* %80, i64 -1, !dbg !91
  %82 = load i64, i64* %81, align 8, !dbg !91, !tbaa !14
  %83 = and i64 %82, -4, !dbg !91
  %84 = inttoptr i64 %83 to i64*, !dbg !91
  %85 = load i64, i64* %84, align 8, !dbg !91, !tbaa !14
  %86 = and i64 %85, 8, !dbg !91
  %87 = icmp eq i64 %86, 0, !dbg !91
  br i1 %87, label %88, label %90, !dbg !91, !prof !70

88:                                               ; preds = %.preheader.i
  %89 = getelementptr inbounds i64, i64* %84, i64 -8, !dbg !91
  store i64 20, i64* %89, align 8, !dbg !91, !tbaa !14
  br label %blockExit, !dbg !91

90:                                               ; preds = %.preheader.i
  tail call void @sorbet_vm_env_write_slowpath(i64* nonnull %84, i32 -8, i64 20) #10, !dbg !91
  br label %blockExit, !dbg !91
}

; Function Attrs: nofree norecurse nounwind ssp writeonly
define internal i64 @"func_Test.test_nilable_arg$block_4"(i64** nocapture, i64*, i64) #9 {
  %4 = getelementptr inbounds i64, i64* %1, i64 1
  store i64* %4, i64** %0, align 8, !tbaa !39
  ret i64 52
}

; Function Attrs: nounwind
declare void @llvm.assume(i1) #10

; Function Attrs: ssp
define linkonce void @const_recompute_Test() local_unnamed_addr #8 {
  %1 = tail call i64 @sorbet_getConstant(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_Test, i64 0, i64 0), i64 4)
  store i64 %1, i64* @guarded_const_Test, align 8
  %2 = load i64, i64* @ruby_vm_global_constant_state, align 8, !tbaa !60
  store i64 %2, i64* @guard_epoch_Test, align 8
  ret void
}

attributes #0 = { noreturn }
attributes #1 = { "addedToSilenceEmptyAttrsError" }
attributes #2 = { argmemonly nounwind }
attributes #3 = { nounwind ssp uwtable }
attributes #4 = { nofree norecurse nounwind ssp uwtable writeonly }
attributes #5 = { sspreq }
attributes #6 = { nounwind sspreq uwtable }
attributes #7 = { noreturn nounwind ssp }
attributes #8 = { ssp }
attributes #9 = { nofree norecurse nounwind ssp writeonly }
attributes #10 = { nounwind }
attributes #11 = { noreturn nounwind }

!llvm.module.flags = !{!0}
!llvm.dbg.cu = !{!1}

!0 = !{i32 2, !"Debug Info Version", i32 3}
!1 = distinct !DICompileUnit(language: DW_LANG_C, file: !2, producer: "Sorbet LLVM", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, enums: !3)
!2 = !DIFile(filename: "test/testdata/compiler/intrinsics/t_must.rb", directory: ".")
!3 = !{}
!4 = !{!5, !6, i64 0}
!5 = !{!"ExceptionClosure", !6, i64 0, !6, i64 8, !6, i64 16, !9, i64 24, !6, i64 32}
!6 = !{!"any pointer", !7, i64 0}
!7 = !{!"omnipotent char", !8, i64 0}
!8 = !{!"Simple C/C++ TBAA"}
!9 = !{!"long", !7, i64 0}
!10 = !{!5, !6, i64 8}
!11 = !{!5, !6, i64 16}
!12 = !{!5, !9, i64 24}
!13 = !{!5, !6, i64 32}
!14 = !{!9, !9, i64 0}
!15 = !DILocation(line: 24, column: 1, scope: !16)
!16 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.<static-init>$152", scope: null, file: !2, line: 5, type: !17, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!17 = !DISubroutineType(types: !18)
!18 = !{!19}
!19 = !DIBasicType(name: "VALUE", size: 64, encoding: DW_ATE_signed)
!20 = !DILocation(line: 25, column: 1, scope: !16)
!21 = !DILocation(line: 26, column: 1, scope: !16)
!22 = !DILocation(line: 27, column: 1, scope: !16)
!23 = !DILocation(line: 8, column: 7, scope: !24)
!24 = distinct !DISubprogram(name: "Test.test_known_nil", linkageName: "func_Test.test_known_nil$block_1", scope: !25, file: !2, line: 6, type: !17, scopeLine: 6, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!25 = distinct !DISubprogram(name: "Test.test_known_nil", linkageName: "func_Test.test_known_nil", scope: null, file: !2, line: 6, type: !17, scopeLine: 6, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!26 = !DILocation(line: 9, column: 15, scope: !27)
!27 = distinct !DISubprogram(name: "Test.test_known_nil", linkageName: "func_Test.test_known_nil$block_2", scope: !25, file: !2, line: 6, type: !17, scopeLine: 6, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!28 = !DILocation(line: 10, column: 7, scope: !27)
!29 = !DILocation(line: 16, column: 7, scope: !30)
!30 = distinct !DISubprogram(name: "Test.test_nilable_arg", linkageName: "func_Test.test_nilable_arg$block_1", scope: !31, file: !2, line: 14, type: !17, scopeLine: 14, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!31 = distinct !DISubprogram(name: "Test.test_nilable_arg", linkageName: "func_Test.test_nilable_arg", scope: null, file: !2, line: 14, type: !17, scopeLine: 14, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!32 = !DILocation(line: 17, column: 7, scope: !30)
!33 = !DILocation(line: 18, column: 15, scope: !34)
!34 = distinct !DISubprogram(name: "Test.test_nilable_arg", linkageName: "func_Test.test_nilable_arg$block_2", scope: !31, file: !2, line: 14, type: !17, scopeLine: 14, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!35 = !DILocation(line: 19, column: 7, scope: !34)
!36 = !DILocation(line: 6, column: 3, scope: !37)
!37 = distinct !DISubprogram(name: "Test.<static-init>", linkageName: "func_Test.<static-init>L62", scope: null, file: !2, line: 5, type: !17, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!38 = !DILocation(line: 14, column: 3, scope: !37)
!39 = !{!6, !6, i64 0}
!40 = !{!41, !6, i64 16}
!41 = !{!"rb_execution_context_struct", !6, i64 0, !9, i64 8, !6, i64 16, !6, i64 24, !6, i64 32, !42, i64 40, !42, i64 44, !6, i64 48, !6, i64 56, !6, i64 64, !9, i64 72, !9, i64 80, !6, i64 88, !9, i64 96, !6, i64 104, !6, i64 112, !9, i64 120, !9, i64 128, !7, i64 136, !7, i64 137, !9, i64 144, !43, i64 152}
!42 = !{!"int", !7, i64 0}
!43 = !{!"", !6, i64 0, !6, i64 8, !9, i64 16, !7, i64 24}
!44 = !{!45, !6, i64 16}
!45 = !{!"rb_control_frame_struct", !6, i64 0, !6, i64 8, !6, i64 16, !9, i64 24, !6, i64 32, !6, i64 40, !6, i64 48}
!46 = !{!45, !6, i64 32}
!47 = !{!48, !6, i64 16}
!48 = !{!"rb_iseq_struct", !9, i64 0, !9, i64 8, !6, i64 16, !7, i64 24}
!49 = !{!50, !6, i64 8}
!50 = !{!"rb_iseq_constant_body", !7, i64 0, !42, i64 4, !6, i64 8, !51, i64 16, !53, i64 64, !56, i64 120, !6, i64 152, !6, i64 160, !6, i64 168, !6, i64 176, !6, i64 184, !6, i64 192, !57, i64 200, !42, i64 232, !42, i64 236, !42, i64 240, !42, i64 244, !42, i64 248, !7, i64 252, !6, i64 256, !9, i64 264, !6, i64 272, !9, i64 280}
!51 = !{!"", !52, i64 0, !42, i64 4, !42, i64 8, !42, i64 12, !42, i64 16, !42, i64 20, !42, i64 24, !42, i64 28, !6, i64 32, !6, i64 40}
!52 = !{!"", !42, i64 0, !42, i64 0, !42, i64 0, !42, i64 0, !42, i64 0, !42, i64 0, !42, i64 0, !42, i64 0, !42, i64 1, !42, i64 1}
!53 = !{!"rb_iseq_location_struct", !9, i64 0, !9, i64 8, !9, i64 16, !9, i64 24, !42, i64 32, !54, i64 36}
!54 = !{!"rb_code_location_struct", !55, i64 0, !55, i64 8}
!55 = !{!"rb_code_position_struct", !42, i64 0, !42, i64 4}
!56 = !{!"iseq_insn_info", !6, i64 0, !6, i64 8, !42, i64 16, !6, i64 24}
!57 = !{!"", !9, i64 0, !9, i64 8, !9, i64 16, !6, i64 24}
!58 = !DILocation(line: 0, scope: !16)
!59 = !DILocation(line: 5, column: 1, scope: !16)
!60 = !{!61, !61, i64 0}
!61 = !{!"long long", !7, i64 0}
!62 = !{!"branch_weights", i32 10000, i32 1}
!63 = !DILocation(line: 0, scope: !37, inlinedAt: !64)
!64 = distinct !DILocation(line: 5, column: 1, scope: !16)
!65 = !DILocation(line: 6, column: 3, scope: !37, inlinedAt: !64)
!66 = !DILocation(line: 14, column: 3, scope: !37, inlinedAt: !64)
!67 = !{!45, !6, i64 8}
!68 = !DILocation(line: 8, column: 7, scope: !25)
!69 = !DILocation(line: 6, column: 3, scope: !25)
!70 = !{!"branch_weights", i32 2000, i32 1}
!71 = !DILocation(line: 0, scope: !25)
!72 = !{!73}
!73 = distinct !{!73, !74, !"sorbet_T_must: argument 0"}
!74 = distinct !{!74, !"sorbet_T_must"}
!75 = !DILocation(line: 0, scope: !27)
!76 = !DILocation(line: 9, column: 5, scope: !27)
!77 = !DILocation(line: 8, column: 7, scope: !27)
!78 = distinct !DISubprogram(name: "Test.test_known_nil", linkageName: "func_Test.test_known_nil$block_4", scope: !25, file: !2, line: 6, type: !17, scopeLine: 6, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!79 = !DILocation(line: 16, column: 7, scope: !31)
!80 = !DILocation(line: 14, column: 3, scope: !31)
!81 = !{!"branch_weights", i32 4000000, i32 4001}
!82 = !DILocation(line: 0, scope: !31)
!83 = !{!"branch_weights", i32 1, i32 2000}
!84 = !DILocation(line: 17, column: 19, scope: !30)
!85 = !DILocation(line: 17, column: 12, scope: !30)
!86 = !{!87}
!87 = distinct !{!87, !88, !"sorbet_T_must: argument 0"}
!88 = distinct !{!88, !"sorbet_T_must"}
!89 = !DILocation(line: 0, scope: !34)
!90 = !DILocation(line: 18, column: 5, scope: !34)
!91 = !DILocation(line: 16, column: 7, scope: !34)
