class <emptyTree><<C <root>>> < (::<todo sym>)
  class <emptyTree>::<C Test><<C <todo sym>>> < (::<todo sym>)
    def test_case<<todo method>>(&<blk>)
      begin
        begin
          <assignTemp>$2 = <self>.a()
          if <self>.foo1().===(<assignTemp>$2)
            :a
          else
            if if <self>.foo3().===(<assignTemp>$2)
                true
              else
                <self>.foo2().===(<assignTemp>$2)
              end
              :b
            else
              :c
            end
          end
        end
        if <self>.test1()
          :a
        else
          if if <self>.test3()
              true
            else
              <self>.test2()
            end
            :b
          else
            <emptyTree>
          end
        end
      end
    end
  end
end
