def test_csend<<constant:<todo sym>>>()
  begin
    begin
      assignTmp$0 = self(<constant:<todo sym>>).foo()
      if assignTmp$0.nil?()
        nil
      else
        assignTmp$0.bar()
      end
    end
    begin
      assignTmp$1 = self(<constant:<todo sym>>).foo()
      if assignTmp$1.nil?()
        nil
      else
        assignTmp$1.bar() do |x|
          x
        end
      end
    end
  end
