class <emptyTree><<C <U <root>>>> < ()
  def <U test_csend><<C <U <todo sym>>>>(&<U <blk>>)
    begin
      begin
        <D <U <assignTemp>> $2> = <U <self>>.<U foo>()
        if <D <U <assignTemp>> $2>.<U ==>(nil)
          nil
        else
          <D <U <assignTemp>> $2>.<U bar>()
        end
      end
      begin
        <D <U <assignTemp>> $3> = <U <self>>.<U foo>()
        if <D <U <assignTemp>> $3>.<U ==>(nil)
          nil
        else
          <D <U <assignTemp>> $3>.<U bar>() do |<U x>|
            <U x>
          end
        end
      end
      begin
        <D <U <assignTemp>> $4> = <U <self>>.<U foo>()
        if <D <U <assignTemp>> $4>.<U ==>(nil)
          nil
        else
          <D <U <assignTemp>> $4>.<U bar=>(5)
        end
      end
      begin
        <D <U <assignTemp>> $5> = <U <self>>.<U foo>()
        if <D <U <assignTemp>> $5>.<U ==>(nil)
          nil
        else
          begin
            <D <U bar> $6> = <D <U <assignTemp>> $5>
            <D <U bar> $6>.<U bar=>(<D <U bar> $6>.<U bar>().<U +>(5))
          end
        end
      end
      begin
        <D <U <assignTemp>> $7> = <U <self>>.<U foo>()
        if <D <U <assignTemp>> $7>.<U ==>(nil)
          nil
        else
          begin
            <D <U bar> $8> = <D <U <assignTemp>> $7>
            <D <U bar> $9> = <D <U bar> $8>.<U bar>()
            if <D <U bar> $9>
              <D <U bar> $8>.<U bar=>(5)
            else
              <D <U bar> $9>
            end
          end
        end
      end
      begin
        <D <U <assignTemp>> $10> = <U <self>>.<U foo>()
        if <D <U <assignTemp>> $10>.<U ==>(nil)
          nil
        else
          begin
            <D <U bar> $11> = <D <U <assignTemp>> $10>
            <D <U bar> $12> = <D <U bar> $11>.<U bar>()
            if <D <U bar> $12>
              <D <U bar> $12>
            else
              <D <U bar> $11>.<U bar=>(5)
            end
          end
        end
      end
    end
  end

  begin
    <D <U <assignTemp>> $2> = <emptyTree>::<C <U BasicObject>>.<U new>()
    if <D <U <assignTemp>> $2>.<U ==>(nil)
      nil
    else
      <D <U <assignTemp>> $2>.<U __id__>()
    end
  end

  class <emptyTree>::<C <U A>><<C <U <todo sym>>>> < (::<todo sym>)
    <U <self>>.<U extend>(<emptyTree>::<C <U T>>::<C <U Sig>>)

    <U <self>>.<U sig>() do ||
      <U <self>>.<U params>({:"x" => <emptyTree>::<C <U T>>.<U any>(<emptyTree>::<C <U FalseClass>>, <emptyTree>::<C <U NilClass>>)}).<U returns>(<emptyTree>::<C <U T>>.<U nilable>(<emptyTree>::<C <U TrueClass>>))
    end

    def <U foo><<C <U <todo sym>>>>(<U x>, &<U <blk>>)
      begin
        <D <U <assignTemp>> $2> = <U x>
        if <D <U <assignTemp>> $2>.<U ==>(nil)
          nil
        else
          <D <U <assignTemp>> $2>.<U |>(true)
        end
      end
    end
  end
end
