class <constant:<root>> < ::<constant:Object> () -> <Class:<root>>
  class <constant:Destructure> < ::<constant:Object> () -> <Class:Destructure>
    method f (<destructure>$2, z)
      argument <destructure>$2<>
      argument z<>
      method <block>$2 (<destructure>$4)
        argument <destructure>$4<>
  class <singleton class:<constant:Destructure>> < ::<singleton class:<constant:Object>> ()

