class <emptyTree><<C <root>>> < (::<todo sym>)
  expr = []

  begin
    <assignTemp>$2 = expr
    if ::T.unsafe(::Kernel).raise("Sorbet rewriter pass partially unimplemented")
      begin
        a = ::T.unsafe(::Kernel).raise("Sorbet rewriter pass partially unimplemented")
        <emptyTree>::<C T>.reveal_type(a)
      end
    else
      if ::T.unsafe(::Kernel).raise("Sorbet rewriter pass partially unimplemented")
        begin
          b = ::T.unsafe(::Kernel).raise("Sorbet rewriter pass partially unimplemented")
          <emptyTree>::<C T>.reveal_type(b)
        end
      else
        if ::T.unsafe(::Kernel).raise("Sorbet rewriter pass partially unimplemented")
          begin
            c = ::T.unsafe(::Kernel).raise("Sorbet rewriter pass partially unimplemented")
            d = ::T.unsafe(::Kernel).raise("Sorbet rewriter pass partially unimplemented")
            begin
              <emptyTree>::<C T>.reveal_type(c)
              <emptyTree>::<C T>.reveal_type(d)
            end
          end
        else
          if ::T.unsafe(::Kernel).raise("Sorbet rewriter pass partially unimplemented")
            begin
              e = ::T.unsafe(::Kernel).raise("Sorbet rewriter pass partially unimplemented")
              f = ::T.unsafe(::Kernel).raise("Sorbet rewriter pass partially unimplemented")
              h = ::T.unsafe(::Kernel).raise("Sorbet rewriter pass partially unimplemented")
              g = ::T.unsafe(::Kernel).raise("Sorbet rewriter pass partially unimplemented")
              begin
                <emptyTree>::<C T>.reveal_type(e)
                <emptyTree>::<C T>.reveal_type(f)
                <emptyTree>::<C T>.reveal_type(g)
                <emptyTree>::<C T>.reveal_type(h)
              end
            end
          else
            if ::T.unsafe(::Kernel).raise("Sorbet rewriter pass partially unimplemented")
              begin
                i = ::T.unsafe(::Kernel).raise("Sorbet rewriter pass partially unimplemented")
                <emptyTree>::<C T>.reveal_type(i)
              end
            else
              if ::T.unsafe(::Kernel).raise("Sorbet rewriter pass partially unimplemented")
                begin
                  k = ::T.unsafe(::Kernel).raise("Sorbet rewriter pass partially unimplemented")
                  l = ::T.unsafe(::Kernel).raise("Sorbet rewriter pass partially unimplemented")
                  begin
                    <emptyTree>::<C T>.reveal_type(k)
                    <emptyTree>::<C T>.reveal_type(l)
                  end
                end
              else
                if ::T.unsafe(::Kernel).raise("Sorbet rewriter pass partially unimplemented")
                  begin
                    m = ::T.unsafe(::Kernel).raise("Sorbet rewriter pass partially unimplemented")
                    n = ::T.unsafe(::Kernel).raise("Sorbet rewriter pass partially unimplemented")
                    begin
                      <emptyTree>::<C T>.reveal_type(m)
                      <emptyTree>::<C T>.reveal_type(n)
                    end
                  end
                else
                  <emptyTree>
                end
              end
            end
          end
        end
      end
    end
  end
end
