class <emptyTree><<C <root>>> < (::<todo sym>)
  expr = []

  begin
    <assignTemp>$1 = expr
    if ::<Magic>.<rewriter-raise-unimplemented>()
      begin
        a = ::<Magic>.<rewriter-raise-unimplemented>()
        <emptyTree>::<C T>.reveal_type(a)
      end
    else
      if ::<Magic>.<rewriter-raise-unimplemented>()
        begin
          b = ::<Magic>.<rewriter-raise-unimplemented>()
          <emptyTree>::<C T>.reveal_type(b)
        end
      else
        if ::<Magic>.<rewriter-raise-unimplemented>()
          begin
            c = ::<Magic>.<rewriter-raise-unimplemented>()
            d = ::<Magic>.<rewriter-raise-unimplemented>()
            begin
              <emptyTree>::<C T>.reveal_type(c)
              <emptyTree>::<C T>.reveal_type(d)
            end
          end
        else
          if ::<Magic>.<rewriter-raise-unimplemented>()
            begin
              e = ::<Magic>.<rewriter-raise-unimplemented>()
              f = ::<Magic>.<rewriter-raise-unimplemented>()
              h = ::<Magic>.<rewriter-raise-unimplemented>()
              g = ::<Magic>.<rewriter-raise-unimplemented>()
              begin
                <emptyTree>::<C T>.reveal_type(e)
                <emptyTree>::<C T>.reveal_type(f)
                <emptyTree>::<C T>.reveal_type(g)
                <emptyTree>::<C T>.reveal_type(h)
              end
            end
          else
            if ::<Magic>.<rewriter-raise-unimplemented>()
              begin
                i = ::<Magic>.<rewriter-raise-unimplemented>()
                <emptyTree>::<C T>.reveal_type(i)
              end
            else
              if ::<Magic>.<rewriter-raise-unimplemented>()
                begin
                  k = ::<Magic>.<rewriter-raise-unimplemented>()
                  l = ::<Magic>.<rewriter-raise-unimplemented>()
                  begin
                    <emptyTree>::<C T>.reveal_type(k)
                    <emptyTree>::<C T>.reveal_type(l)
                  end
                end
              else
                if ::<Magic>.<rewriter-raise-unimplemented>()
                  begin
                    m = ::<Magic>.<rewriter-raise-unimplemented>()
                    n = ::<Magic>.<rewriter-raise-unimplemented>()
                    begin
                      <emptyTree>::<C T>.reveal_type(m)
                      <emptyTree>::<C T>.reveal_type(n)
                    end
                  end
                else
                  <emptyTree>
                end
              end
            end
          end
        end
      end
    end
  end
end
