class <emptyTree><<C <root>>> < (::<todo sym>)
  expr = "x"

  <emptyTree>::<C T>.reveal_type(expr)

  x = begin
    <assignTemp>$1 = expr
    if ::<Magic>.<rewriter-raise-unimplemented>()
      begin
        s = ::<Magic>.<rewriter-raise-unimplemented>()
        begin
          <emptyTree>::<C T>.reveal_type(s)
          1
        end
      end
    else
      if ::<Magic>.<rewriter-raise-unimplemented>()
        begin
          x = ::<Magic>.<rewriter-raise-unimplemented>()
          begin
            <emptyTree>::<C T>.reveal_type(x)
            1
          end
        end
      else
        if ::<Magic>.<rewriter-raise-unimplemented>()
          begin
            expr = ::<Magic>.<rewriter-raise-unimplemented>()
            begin
              <emptyTree>::<C T>.reveal_type(expr)
              1
            end
          end
        else
          if ::<Magic>.<rewriter-raise-unimplemented>()
            begin
              <emptyTree>::<C T>.reveal_type(x)
              <emptyTree>::<C T>.reveal_type(expr)
              1
            end
          else
            1
          end
        end
      end
    end
  end

  <emptyTree>::<C T>.reveal_type(x)
end
