digraph "gerald.rb"{
subgraph "cluster_::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeout>#initialize" {
    label = "::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeout>#initialize";
    color = blue;
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeout>#initialize_0" [shape = invhouse];
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeout>#initialize_1" [shape = parallelogram];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeout>#initialize_0" [label = "()
@rule_token$6 = alias @rule_token : untyped
selfMethodTemp$2 = self : MatchTimeout
message = load_arg(selfMethodTemp$2#initialize, 0) : untyped
rule_token = load_arg(selfMethodTemp$2#initialize, 1) : untyped
statTemp$4 = self : MatchTimeout
statTemp$3 = statTemp$4.super(message) : untyped
returnMethodTemp$7 = return rule_token : <bottom>
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeout>#initialize_0" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeout>#initialize_1";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeout>#initialize_1" [label = "()
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeout>#initialize_1" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeout>#initialize_1";
}

subgraph "cluster_::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#initialize" {
    label = "::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#initialize";
    color = blue;
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#initialize_0" [shape = invhouse];
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#initialize_1" [shape = parallelogram];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#initialize_0" [label = "(invalid_rules)
<constant:GeraldRule>$8 = alias <constant:GeraldRule> : untyped
@rules$14 = alias @rules : untyped
statTemp$9 = <symbol:deleted_at_is_nil> : Symbol(:\"deleted_at_is_nil\")
statTemp$6 = <constant:GeraldRule>$8.query_by(statTemp$9) : untyped
hashTemp$11 = alias {} : HashType {\n}
statTemp$10 = hashTemp$11.<build-hash>() : HashType {\n}
statTemp$5 = statTemp$6.load_all(statTemp$10) : untyped
statTemp$12 = NotSupported() : untyped
assignTemp$10000 = statTemp$5.partition(statTemp$12) : untyped
statTemp$16 = 0 : Integer(0)
@rules$14 = assignTemp$10000.[](statTemp$16) : untyped
statTemp$19 = 1 : Integer(1)
invalid_rules = assignTemp$10000.[](statTemp$19) : untyped
statTemp$21 = invalid_rules.empty?() : untyped
ifTemp$20 = statTemp$21.!() : untyped
ifTemp$20"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#initialize_0" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#initialize_2";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#initialize_0" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#initialize_3";

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#initialize_1" [label = "()
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#initialize_1" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#initialize_1";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#initialize_2" [label = "(returnMethodTemp$1, invalid_rules)
statTemp$26 = NotSupported() : untyped
statTemp$24 = invalid_rules.map(statTemp$26) : untyped
statTemp$27 = , : String(\",\")
invalid_rule_ids = statTemp$24.join(statTemp$27) : untyped
statTemp$29 = self : Matcher
statTemp$28 = statTemp$29.log() : untyped
statTemp$31 = Gerald skipping invalid rules:  : String(\"Gerald skipping invalid rules: \")
statTemp$30 = statTemp$31.+(invalid_rule_ids) : String
returnMethodTemp$1 = statTemp$28.warn(statTemp$30) : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#initialize_2" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#initialize_4";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#initialize_3" [label = "(returnMethodTemp$1)
returnMethodTemp$1 = NotSupported() : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#initialize_3" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#initialize_4";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#initialize_4" [label = "(returnMethodTemp$1)
returnMethodTemp$33 = return returnMethodTemp$1 : <bottom>
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#initialize_4" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#initialize_1";
}

subgraph "cluster_::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match" {
    label = "::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match";
    color = blue;
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_0" [shape = invhouse];
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_1" [shape = parallelogram];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_0" [label = "(match_context, <constant:MatchTimeBudget>$27, @rules$29)
<constant:MAX_AFFECTED_FILES>$10 = alias <constant:MAX_AFFECTED_FILES> : untyped
<constant:MatchTimeBudget>$27 = alias <constant:MatchTimeBudget> : <class:MatchTimeBudget>
@rules$29 = alias @rules : untyped
selfMethodTemp$2 = self : Matcher
match_context = load_arg(selfMethodTemp$2#match, 0) : untyped
statTemp$7 = match_context.diff() : untyped
statTemp$6 = statTemp$7.affected_files() : untyped
statTemp$5 = statTemp$6.count() : untyped
ifTemp$4 = statTemp$5.>(<constant:MAX_AFFECTED_FILES>$10) : untyped
ifTemp$4"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_0" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_2";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_0" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_3";

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_1" [label = "()
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_1" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_1";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_2" [label = "(match_context)
statTemp$13 = self : Matcher
statTemp$12 = statTemp$13.log() : untyped
statTemp$17 = Gerald skipping large PR with  : String(\"Gerald skipping large PR with \")
statTemp$21 = match_context.diff() : untyped
statTemp$20 = statTemp$21.affected_files() : untyped
statTemp$19 = statTemp$20.count() : untyped
statTemp$18 = statTemp$19.to_s() : untyped
statTemp$16 = statTemp$17.concat(statTemp$18) : String
statTemp$23 =  affected files : String(\" affected files\")
statTemp$15 = statTemp$16.concat(statTemp$23) : String
statTemp$14 = statTemp$15.to_s() : String
statTemp$11 = statTemp$12.warn(statTemp$14) : untyped
returnTemp$24 = NotSupported() : untyped
statTemp$3 = return returnTemp$24 : <bottom>
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_2" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_1";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_3" [label = "(match_context, budget, statTemp$28, <constant:MatchTimeBudget>$27, @rules$29)
statTemp$3 = NotSupported() : untyped
budget = <constant:MatchTimeBudget>$27.new() : MatchTimeBudget
statTemp$28 = @rules$29 : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_3" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_4";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_4" [label = "(match_context, budget, <block-nested: r>, statTemp$28, @rules$29)
outerLoops: 1
<block-call>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_4" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_6";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_4" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_5";

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_5" [label = "(@rules$29)
returnMethodTemp$1 = @rules$29.select() : untyped
returnMethodTemp$36 = return returnMethodTemp$1 : <bottom>
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_5" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_1";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_6" [label = "(match_context, budget, <block-nested: r>, statTemp$28, @rules$29)
outerLoops: 1
<block-nested: r> = load_arg(statTemp$28#select, 0) : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_6" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_7";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_7" [label = "(match_context, budget, <block-nested: r>, statTemp$28, @rules$29)
outerLoops: 2
<block-call>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_7" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_9";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_7" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_8";

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_8" [label = "(match_context, budget, <block-nested: r>, statTemp$28, @rules$29)
outerLoops: 1
blockReturnTemp$30 = budget.time_rule(<block-nested: r>) : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_8" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_4";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_9" [label = "(match_context, budget, <block-nested: r>, statTemp$28, @rules$29)
outerLoops: 2
blockReturnTemp$33 = <block-nested: r>.matches?(match_context) : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_9" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Matcher>#match_7";
}

subgraph "cluster_::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchContext>#initialize" {
    label = "::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchContext>#initialize";
    color = blue;
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchContext>#initialize_0" [shape = invhouse];
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchContext>#initialize_1" [shape = parallelogram];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchContext>#initialize_0" [label = "()
@repo$4 = alias @repo : untyped
@assignee$6 = alias @assignee : untyped
@gh_user$8 = alias @gh_user : untyped
@merge_branch$10 = alias @merge_branch : untyped
@body$12 = alias @body : untyped
@title$14 = alias @title : untyped
@diff$16 = alias @diff : untyped
@openapi_diff$17 = alias @openapi_diff : untyped
selfMethodTemp$2 = self : MatchContext
repo = load_arg(selfMethodTemp$2#initialize, 0) : untyped
assignee = load_arg(selfMethodTemp$2#initialize, 1) : untyped
gh_user = load_arg(selfMethodTemp$2#initialize, 2) : untyped
merge_branch = load_arg(selfMethodTemp$2#initialize, 3) : untyped
body = load_arg(selfMethodTemp$2#initialize, 4) : untyped
title = load_arg(selfMethodTemp$2#initialize, 5) : untyped
diff = load_arg(selfMethodTemp$2#initialize, 6) : untyped
openapi_diff = load_arg(selfMethodTemp$2#initialize, 7) : untyped
returnMethodTemp$18 = return openapi_diff : <bottom>
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchContext>#initialize_0" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchContext>#initialize_1";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchContext>#initialize_1" [label = "()
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchContext>#initialize_1" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchContext>#initialize_1";
}

subgraph "cluster_::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchContext>#user_stripe_suffix?" {
    label = "::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchContext>#user_stripe_suffix?";
    color = blue;
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchContext>#user_stripe_suffix?_0" [shape = invhouse];
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchContext>#user_stripe_suffix?_1" [shape = parallelogram];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchContext>#user_stripe_suffix?_0" [label = "()
@repo$5 = alias @repo : untyped
statTemp$6 = stripe-internal/ : String(\"stripe-internal/\")
statTemp$3 = @repo$5.start_with?(statTemp$6) : untyped
returnMethodTemp$1 = statTemp$3.!() : untyped
returnMethodTemp$7 = return returnMethodTemp$1 : <bottom>
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchContext>#user_stripe_suffix?_0" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchContext>#user_stripe_suffix?_1";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchContext>#user_stripe_suffix?_1" [label = "()
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchContext>#user_stripe_suffix?_1" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchContext>#user_stripe_suffix?_1";
}

subgraph "cluster_::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#initialize" {
    label = "::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#initialize";
    color = blue;
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#initialize_0" [shape = invhouse];
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#initialize_1" [shape = parallelogram];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#initialize_0" [label = "()
@start$3 = alias @start : untyped
<constant:Time>$5 = alias <constant:Time> : <class:Time>
@start$3 = <constant:Time>$5.now() : Time
returnMethodTemp$6 = return @start$3 : <bottom>
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#initialize_0" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#initialize_1";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#initialize_1" [label = "()
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#initialize_1" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#initialize_1";
}

subgraph "cluster_::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#check!" {
    label = "::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#check!";
    color = blue;
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#check!_0" [shape = invhouse];
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#check!_1" [shape = parallelogram];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#check!_0" [label = "(<constant:TOTAL_TIME_MS>$14, <constant:MatchTimeout>$18)
<constant:Time>$7 = alias <constant:Time> : <class:Time>
@start$9 = alias @start : untyped
<constant:TOTAL_TIME_MS>$14 = alias <constant:TOTAL_TIME_MS> : untyped
<constant:MatchTimeout>$18 = alias <constant:MatchTimeout> : <class:MatchTimeout>
statTemp$5 = <constant:Time>$7.now() : Time
statTemp$4 = statTemp$5.-(@start$9) : Float | Time
statTemp$10 = 1000 : Integer(1000)
dur_ms = statTemp$4.*(statTemp$10) : untyped
ifTemp$11 = dur_ms.>(<constant:TOTAL_TIME_MS>$14) : untyped
ifTemp$11"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#check!_0" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#check!_2";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#check!_0" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#check!_3";

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#check!_1" [label = "()
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#check!_1" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#check!_1";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#check!_2" [label = "(returnMethodTemp$1, <constant:TOTAL_TIME_MS>$14, <constant:MatchTimeout>$18)
statTemp$15 = self : MatchTimeBudget
statTemp$22 = Gerald match time budged exceeded  : String(\"Gerald match time budged exceeded \")
statTemp$23 = <constant:TOTAL_TIME_MS>$14.to_s() : untyped
statTemp$21 = statTemp$22.concat(statTemp$23) : String
statTemp$25 = ms : String(\"ms\")
statTemp$20 = statTemp$21.concat(statTemp$25) : String
statTemp$19 = statTemp$20.to_s() : String
statTemp$16 = <constant:MatchTimeout>$18.new(statTemp$19) : MatchTimeout
returnMethodTemp$1 = statTemp$15.raise(statTemp$16) : NilClass
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#check!_2" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#check!_4";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#check!_3" [label = "(returnMethodTemp$1)
returnMethodTemp$1 = NotSupported() : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#check!_3" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#check!_4";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#check!_4" [label = "(returnMethodTemp$1)
returnMethodTemp$26 = return returnMethodTemp$1 : <bottom>
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#check!_4" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#check!_1";
}

subgraph "cluster_::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#time_rule" {
    label = "::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#time_rule";
    color = blue;
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#time_rule_0" [shape = invhouse];
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#time_rule_1" [shape = parallelogram];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#time_rule_0" [label = "(dur_ms, rule, res, <constant:PER_RULE_MS>$17, <constant:MatchTimeout>$21)
<constant:Time>$5 = alias <constant:Time> : <class:Time>
<constant:PER_RULE_MS>$17 = alias <constant:PER_RULE_MS> : untyped
<constant:MatchTimeout>$21 = alias <constant:MatchTimeout> : <class:MatchTimeout>
selfMethodTemp$2 = self : MatchTimeBudget
rule = load_arg(selfMethodTemp$2#time_rule, 0) : untyped
rule_start = <constant:Time>$5.now() : Time
res = NotSupported() : untyped
statTemp$9 = <constant:Time>$5.now() : Time
statTemp$8 = statTemp$9.-(rule_start) : Float | Time
statTemp$12 = 1000 : Integer(1000)
dur_ms = statTemp$8.*(statTemp$12) : untyped
ifTemp$14 = dur_ms.>(<constant:PER_RULE_MS>$17) : untyped
ifTemp$14"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#time_rule_0" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#time_rule_2";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#time_rule_0" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#time_rule_3";

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#time_rule_1" [label = "()
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#time_rule_1" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#time_rule_1";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#time_rule_2" [label = "(dur_ms, rule, res, <constant:PER_RULE_MS>$17, <constant:MatchTimeout>$21)
statTemp$18 = self : MatchTimeBudget
statTemp$29 = Gerald rule ' : String(\"Gerald rule '\")
statTemp$31 = rule.token() : untyped
statTemp$30 = statTemp$31.to_s() : untyped
statTemp$28 = statTemp$29.concat(statTemp$30) : String
statTemp$33 = ' exceeded per-rule time budget actual= : String(\"' exceeded per-rule time budget actual=\")
statTemp$27 = statTemp$28.concat(statTemp$33) : String
statTemp$35 = dur_ms.to_i() : untyped
statTemp$34 = statTemp$35.to_s() : untyped
statTemp$26 = statTemp$27.concat(statTemp$34) : String
statTemp$37 = ms budget= : String(\"ms budget=\")
statTemp$25 = statTemp$26.concat(statTemp$37) : String
statTemp$38 = <constant:PER_RULE_MS>$17.to_s() : untyped
statTemp$24 = statTemp$25.concat(statTemp$38) : String
statTemp$40 = ms : String(\"ms\")
statTemp$23 = statTemp$24.concat(statTemp$40) : String
statTemp$22 = statTemp$23.to_s() : String
hashTemp$42 = <symbol:rule_token> : Symbol(:\"rule_token\")
hashTemp$43 = rule.token() : untyped
hashTemp$45 = alias {} : HashType {\n}
statTemp$41 = hashTemp$45.<build-hash>(hashTemp$42, hashTemp$43) : HashType {\n  Symbol(:\"rule_token\") => untyped\n}
statTemp$19 = <constant:MatchTimeout>$21.new(statTemp$22, statTemp$41) : MatchTimeout
statTemp$13 = statTemp$18.raise(statTemp$19) : NilClass
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#time_rule_2" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#time_rule_4";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#time_rule_3" [label = "(res)
statTemp$13 = NotSupported() : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#time_rule_3" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#time_rule_4";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#time_rule_4" [label = "(res)
statTemp$47 = self : MatchTimeBudget
statTemp$46 = statTemp$47.check!() : untyped
returnMethodTemp$48 = return res : <bottom>
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#time_rule_4" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:MatchTimeBudget>#time_rule_1";
}

subgraph "cluster_::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#initialize" {
    label = "::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#initialize";
    color = blue;
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#initialize_0" [shape = invhouse];
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#initialize_1" [shape = parallelogram];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#initialize_0" [label = "()
@raw$4 = alias @raw : untyped
@parsed$5 = alias @parsed : untyped
selfMethodTemp$2 = self : Diff
raw_diff = load_arg(selfMethodTemp$2#initialize, 0) : untyped
statTemp$6 = self : Diff
@parsed$5 = statTemp$6.parse(raw_diff) : untyped
returnMethodTemp$8 = return @parsed$5 : <bottom>
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#initialize_0" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#initialize_1";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#initialize_1" [label = "()
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#initialize_1" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#initialize_1";
}

subgraph "cluster_::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#affected_files" {
    label = "::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#affected_files";
    color = blue;
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#affected_files_0" [shape = invhouse];
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#affected_files_1" [shape = parallelogram];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#affected_files_0" [label = "()
statTemp$5 = self : Diff
statTemp$4 = statTemp$5.added_files() : untyped
statTemp$7 = self : Diff
statTemp$6 = statTemp$7.deleted_files() : untyped
statTemp$3 = statTemp$4.+(statTemp$6) : untyped
statTemp$9 = self : Diff
statTemp$8 = statTemp$9.changed_files() : untyped
returnMethodTemp$1 = statTemp$3.+(statTemp$8) : untyped
returnMethodTemp$10 = return returnMethodTemp$1 : <bottom>
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#affected_files_0" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#affected_files_1";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#affected_files_1" [label = "()
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#affected_files_1" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#affected_files_1";
}

subgraph "cluster_::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files" {
    label = "::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files";
    color = blue;
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files_0" [shape = invhouse];
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files_1" [shape = parallelogram];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files_0" [label = "(statTemp$4, @parsed$5)
@parsed$5 = alias @parsed : untyped
statTemp$4 = @parsed$5 : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files_0" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files_2";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files_1" [label = "()
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files_1" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files_1";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files_2" [label = "(statTemp$4, @parsed$5)
outerLoops: 1
<block-call>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files_2" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files_4";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files_2" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files_3";

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files_3" [label = "(statTemp$3, @parsed$5)
statTemp$3 = @parsed$5.select() : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files_3" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files_5";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files_4" [label = "(statTemp$4, @parsed$5)
outerLoops: 1
<block-nested: part> = load_arg(statTemp$4#select, 0) : untyped
statTemp$9 = <symbol:a_name> : Symbol(:\"a_name\")
statTemp$7 = <block-nested: part>.[](statTemp$9) : untyped
statTemp$10 = /dev/null : String(\"/dev/null\")
blockReturnTemp$6 = statTemp$7.==(statTemp$10) : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files_4" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files_2";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files_5" [label = "(statTemp$3)
outerLoops: 1
<block-call>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files_5" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files_7";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files_5" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files_6";

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files_6" [label = "(statTemp$3)
returnMethodTemp$1 = statTemp$3.map() : untyped
returnMethodTemp$14 = return returnMethodTemp$1 : <bottom>
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files_6" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files_1";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files_7" [label = "(statTemp$3)
outerLoops: 1
<block-nested: part> = load_arg(statTemp$3#map, 0) : untyped
statTemp$13 = <symbol:b_name> : Symbol(:\"b_name\")
blockReturnTemp$11 = <block-nested: part>.[](statTemp$13) : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files_7" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_files_5";
}

subgraph "cluster_::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files" {
    label = "::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files";
    color = blue;
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files_0" [shape = invhouse];
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files_1" [shape = parallelogram];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files_0" [label = "(statTemp$4, @parsed$5)
@parsed$5 = alias @parsed : untyped
statTemp$4 = @parsed$5 : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files_0" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files_2";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files_1" [label = "()
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files_1" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files_1";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files_2" [label = "(statTemp$4, @parsed$5)
outerLoops: 1
<block-call>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files_2" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files_4";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files_2" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files_3";

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files_3" [label = "(statTemp$3, @parsed$5)
statTemp$3 = @parsed$5.select() : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files_3" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files_5";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files_4" [label = "(statTemp$4, @parsed$5)
outerLoops: 1
<block-nested: part> = load_arg(statTemp$4#select, 0) : untyped
statTemp$9 = <symbol:b_name> : Symbol(:\"b_name\")
statTemp$7 = <block-nested: part>.[](statTemp$9) : untyped
statTemp$10 = /dev/null : String(\"/dev/null\")
blockReturnTemp$6 = statTemp$7.==(statTemp$10) : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files_4" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files_2";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files_5" [label = "(statTemp$3)
outerLoops: 1
<block-call>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files_5" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files_7";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files_5" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files_6";

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files_6" [label = "(statTemp$3)
returnMethodTemp$1 = statTemp$3.map() : untyped
returnMethodTemp$14 = return returnMethodTemp$1 : <bottom>
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files_6" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files_1";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files_7" [label = "(statTemp$3)
outerLoops: 1
<block-nested: part> = load_arg(statTemp$3#map, 0) : untyped
statTemp$13 = <symbol:a_name> : Symbol(:\"a_name\")
blockReturnTemp$11 = <block-nested: part>.[](statTemp$13) : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files_7" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#deleted_files_5";
}

subgraph "cluster_::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files" {
    label = "::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files";
    color = blue;
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files_0" [shape = invhouse];
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files_1" [shape = parallelogram];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files_0" [label = "(statTemp$4, @parsed$5)
@parsed$5 = alias @parsed : untyped
statTemp$4 = @parsed$5 : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files_0" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files_2";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files_1" [label = "()
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files_1" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files_1";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files_2" [label = "(statTemp$4, @parsed$5)
outerLoops: 1
<block-call>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files_2" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files_4";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files_2" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files_3";

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files_3" [label = "(statTemp$3, @parsed$5)
statTemp$3 = @parsed$5.select() : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files_3" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files_5";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files_4" [label = "(statTemp$4, @parsed$5)
outerLoops: 1
<block-nested: part> = load_arg(statTemp$4#select, 0) : untyped
statTemp$9 = <symbol:a_name> : Symbol(:\"a_name\")
statTemp$7 = <block-nested: part>.[](statTemp$9) : untyped
statTemp$12 = <symbol:b_name> : Symbol(:\"b_name\")
statTemp$10 = <block-nested: part>.[](statTemp$12) : untyped
blockReturnTemp$6 = statTemp$7.==(statTemp$10) : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files_4" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files_2";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files_5" [label = "(statTemp$3)
outerLoops: 1
<block-call>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files_5" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files_7";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files_5" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files_6";

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files_6" [label = "(statTemp$3)
returnMethodTemp$1 = statTemp$3.map() : untyped
returnMethodTemp$16 = return returnMethodTemp$1 : <bottom>
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files_6" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files_1";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files_7" [label = "(statTemp$3)
outerLoops: 1
<block-nested: part> = load_arg(statTemp$3#map, 0) : untyped
statTemp$15 = <symbol:b_name> : Symbol(:\"b_name\")
blockReturnTemp$13 = <block-nested: part>.[](statTemp$15) : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files_7" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_files_5";
}

subgraph "cluster_::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_lines" {
    label = "::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_lines";
    color = blue;
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_lines_0" [shape = invhouse];
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_lines_1" [shape = parallelogram];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_lines_0" [label = "(statTemp$4, @parsed$5)
@parsed$5 = alias @parsed : untyped
statTemp$4 = @parsed$5 : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_lines_0" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_lines_2";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_lines_1" [label = "()
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_lines_1" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_lines_1";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_lines_2" [label = "(statTemp$4, @parsed$5)
outerLoops: 1
<block-call>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_lines_2" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_lines_4";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_lines_2" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_lines_3";

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_lines_3" [label = "(@parsed$5)
statTemp$3 = @parsed$5.map() : untyped
returnMethodTemp$1 = statTemp$3.flatten() : untyped
returnMethodTemp$9 = return returnMethodTemp$1 : <bottom>
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_lines_3" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_lines_1";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_lines_4" [label = "(statTemp$4, @parsed$5)
outerLoops: 1
<block-nested: part> = load_arg(statTemp$4#map, 0) : untyped
statTemp$8 = <symbol:added_lines> : Symbol(:\"added_lines\")
blockReturnTemp$6 = <block-nested: part>.[](statTemp$8) : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_lines_4" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#added_lines_2";
}

subgraph "cluster_::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#removed_lines" {
    label = "::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#removed_lines";
    color = blue;
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#removed_lines_0" [shape = invhouse];
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#removed_lines_1" [shape = parallelogram];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#removed_lines_0" [label = "(statTemp$4, @parsed$5)
@parsed$5 = alias @parsed : untyped
statTemp$4 = @parsed$5 : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#removed_lines_0" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#removed_lines_2";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#removed_lines_1" [label = "()
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#removed_lines_1" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#removed_lines_1";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#removed_lines_2" [label = "(statTemp$4, @parsed$5)
outerLoops: 1
<block-call>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#removed_lines_2" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#removed_lines_4";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#removed_lines_2" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#removed_lines_3";

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#removed_lines_3" [label = "(@parsed$5)
statTemp$3 = @parsed$5.map() : untyped
returnMethodTemp$1 = statTemp$3.flatten() : untyped
returnMethodTemp$9 = return returnMethodTemp$1 : <bottom>
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#removed_lines_3" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#removed_lines_1";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#removed_lines_4" [label = "(statTemp$4, @parsed$5)
outerLoops: 1
<block-nested: part> = load_arg(statTemp$4#map, 0) : untyped
statTemp$8 = <symbol:removed_lines> : Symbol(:\"removed_lines\")
blockReturnTemp$6 = <block-nested: part>.[](statTemp$8) : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#removed_lines_4" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#removed_lines_2";
}

subgraph "cluster_::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_lines" {
    label = "::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_lines";
    color = blue;
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_lines_0" [shape = invhouse];
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_lines_1" [shape = parallelogram];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_lines_0" [label = "()
statTemp$4 = self : Diff
statTemp$3 = statTemp$4.added_lines() : untyped
statTemp$6 = self : Diff
statTemp$5 = statTemp$6.removed_lines() : untyped
returnMethodTemp$1 = statTemp$3.+(statTemp$5) : untyped
returnMethodTemp$7 = return returnMethodTemp$1 : <bottom>
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_lines_0" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_lines_1";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_lines_1" [label = "()
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_lines_1" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_lines_1";
}

subgraph "cluster_::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_openapi?" {
    label = "::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_openapi?";
    color = blue;
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_openapi?_0" [shape = invhouse];
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_openapi?_1" [shape = parallelogram];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_openapi?_0" [label = "()
<constant:SPEC_PATH>$6 = alias <constant:SPEC_PATH> : untyped
statTemp$4 = self : Diff
statTemp$3 = statTemp$4.changed_files() : untyped
returnMethodTemp$1 = statTemp$3.include?(<constant:SPEC_PATH>$6) : untyped
returnMethodTemp$7 = return returnMethodTemp$1 : <bottom>
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_openapi?_0" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_openapi?_1";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_openapi?_1" [label = "()
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_openapi?_1" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#changed_openapi?_1";
}

subgraph "cluster_::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse" {
    label = "::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse";
    color = blue;
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_0" [shape = invhouse];
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_1" [shape = parallelogram];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_0" [label = "(parts, <constant:Range>$9)
<constant:Range>$9 = alias <constant:Range> : <class:Range>
selfMethodTemp$2 = self : Diff
diff = load_arg(selfMethodTemp$2#parse, 0) : untyped
statTemp$6 = NotSupported() : untyped
statTemp$4 = diff.split(statTemp$6) : untyped
statTemp$10 = 1 : Integer(1)
statTemp$11 = -1 : Integer(-1)
statTemp$7 = <constant:Range>$9.new(statTemp$10, statTemp$11) : Range
parts = statTemp$4.[](statTemp$7) : untyped
ifTemp$13 = parts : untyped
ifTemp$13"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_0" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_2";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_0" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_3";

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_1" [label = "()
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_1" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_1";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_2" [label = "(parts, <constant:Range>$9)
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_2" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_4";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_3" [label = "(parts, <constant:Range>$9)
parts = NotSupported() : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_3" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_4";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_4" [label = "(parts, statTemp$15, <constant:Range>$9)
statTemp$15 = parts : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_4" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_5";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_5" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 1
<block-call>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_5" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_7";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_5" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_6";

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_6" [label = "(parts)
statTemp$14 = parts.map() : untyped
returnMethodTemp$1 = statTemp$14.compact() : untyped
returnMethodTemp$101 = return returnMethodTemp$1 : <bottom>
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_6" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_1";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_7" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 1
<block-nested: part> = load_arg(statTemp$15#map, 0) : untyped
statTemp$19 = 
 : String(\"\n\")
<block-nested: lines> = <block-nested: part>.split(statTemp$19) : untyped
<block-nested: b_name> = NotSupported() : untyped
<block-nested: added_lines> = NotSupported() : untyped
<block-nested: removed_lines> = NotSupported() : untyped
statTemp$24 = <block-nested: lines> : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_7" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_8";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_8" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 2
<block-call>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_8" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_10";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_8" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_9";

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_9" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 1
statTemp$23 = <block-nested: lines>.each() : untyped
ifTemp$89 = <block-nested: b_name>.nil?() : untyped
ifTemp$89"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_9" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_37";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_9" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_38";

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_10" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 2
<block-nested: line> = load_arg(statTemp$24#each, 0) : untyped
statTemp$28 = index  : String(\"index \")
statTemp$29 = @@ : String(\"@@\")
statTemp$30 = new file mode : String(\"new file mode\")
ifTemp$26 = <block-nested: line>.start_with?(statTemp$28, statTemp$29, statTemp$30) : untyped
ifTemp$26"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_10" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_11";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_10" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_12";

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_11" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 2
returnTemp$31 = NotSupported() : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_11" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_8";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_12" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 2
statTemp$34 = --- : String(\"---\")
ifTemp$32 = <block-nested: line>.start_with?(statTemp$34) : untyped
ifTemp$32"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_12" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_13";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_12" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_14";

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_13" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 2
statTemp$39 = 4 : Integer(4)
statTemp$40 = -1 : Integer(-1)
statTemp$37 = <constant:Range>$9.new(statTemp$39, statTemp$40) : Range
<block-nested: a_name> = <block-nested: line>.[](statTemp$37) : untyped
ifTemp$42 = <block-nested: b_name> : untyped
ifTemp$42"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_13" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_15";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_13" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_16";

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_14" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 2
statTemp$52 = +++ : String(\"+++\")
ifTemp$50 = <block-nested: line>.start_with?(statTemp$52) : untyped
ifTemp$50"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_14" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_21";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_14" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_22";

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_15" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 2
statTemp$44 = a/ : String(\"a/\")
ifTemp$41 = <block-nested: b_name>.start_with?(statTemp$44) : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_15" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_17";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_16" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 2
ifTemp$41 = <block-nested: b_name> : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_16" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_17";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_17" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 2
ifTemp$41"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_17" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_18";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_17" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_19";

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_18" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 2
statTemp$48 = 2 : Integer(2)
statTemp$49 = -1 : Integer(-1)
statTemp$46 = <constant:Range>$9.new(statTemp$48, statTemp$49) : Range
<block-nested: a_name> = <block-nested: b_name>.[](statTemp$46) : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_18" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_20";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_19" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 2
blockReturnTemp$25 = NotSupported() : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_19" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_20";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_20" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 2
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_20" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_36";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_21" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 2
statTemp$57 = 4 : Integer(4)
statTemp$58 = -1 : Integer(-1)
statTemp$55 = <constant:Range>$9.new(statTemp$57, statTemp$58) : Range
<block-nested: b_name> = <block-nested: line>.[](statTemp$55) : untyped
ifTemp$60 = <block-nested: b_name> : untyped
ifTemp$60"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_21" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_23";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_21" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_24";

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_22" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 2
statTemp$70 = + : String(\"+\")
ifTemp$68 = <block-nested: line>.start_with?(statTemp$70) : untyped
ifTemp$68"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_22" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_29";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_22" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_30";

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_23" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 2
statTemp$62 = b/ : String(\"b/\")
ifTemp$59 = <block-nested: b_name>.start_with?(statTemp$62) : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_23" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_25";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_24" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 2
ifTemp$59 = <block-nested: b_name> : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_24" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_25";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_25" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 2
ifTemp$59"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_25" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_26";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_25" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_27";

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_26" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 2
statTemp$63 = <block-nested: b_name> : untyped
statTemp$66 = 2 : Integer(2)
statTemp$67 = -1 : Integer(-1)
statTemp$64 = <constant:Range>$9.new(statTemp$66, statTemp$67) : Range
<block-nested: b_name> = statTemp$63.[](statTemp$64) : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_26" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_28";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_27" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 2
blockReturnTemp$25 = NotSupported() : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_27" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_28";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_28" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 2
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_28" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_35";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_29" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 2
statTemp$76 = 1 : Integer(1)
statTemp$77 = -1 : Integer(-1)
statTemp$74 = <constant:Range>$9.new(statTemp$76, statTemp$77) : Range
statTemp$72 = <block-nested: line>.[](statTemp$74) : untyped
blockReturnTemp$25 = <block-nested: added_lines>.<<(statTemp$72) : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_29" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_34";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_30" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 2
statTemp$80 = - : String(\"-\")
ifTemp$78 = <block-nested: line>.start_with?(statTemp$80) : untyped
ifTemp$78"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_30" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_31";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_30" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_32";

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_31" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 2
statTemp$86 = 1 : Integer(1)
statTemp$87 = -1 : Integer(-1)
statTemp$84 = <constant:Range>$9.new(statTemp$86, statTemp$87) : Range
statTemp$82 = <block-nested: line>.[](statTemp$84) : untyped
blockReturnTemp$25 = <block-nested: removed_lines>.<<(statTemp$82) : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_31" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_33";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_32" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 2
blockReturnTemp$25 = NotSupported() : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_32" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_33";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_33" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 2
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_33" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_34";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_34" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 2
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_34" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_35";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_35" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 2
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_35" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_36";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_36" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 2
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_36" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_8";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_37" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 1
returnTemp$91 = NotSupported() : untyped
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_37" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_5";
    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_38" [label = "(parts, <block-nested: lines>, <block-nested: b_name>, <block-nested: added_lines>, <block-nested: removed_lines>, <block-nested: line>, statTemp$15, statTemp$24, <constant:Range>$9, ifTemp$41, ifTemp$59)
outerLoops: 1
statTemp$88 = NotSupported() : untyped
hashTemp$92 = <symbol:a_name> : Symbol(:\"a_name\")
hashTemp$94 = <symbol:b_name> : Symbol(:\"b_name\")
hashTemp$96 = <symbol:added_lines> : Symbol(:\"added_lines\")
hashTemp$98 = <symbol:removed_lines> : Symbol(:\"removed_lines\")
hashTemp$100 = alias {} : HashType {\n}
blockReturnTemp$16 = hashTemp$100.<build-hash>(hashTemp$92, <block-nested: b_name>, hashTemp$94, <block-nested: b_name>, hashTemp$96, <block-nested: added_lines>, hashTemp$98, <block-nested: removed_lines>) : HashType {\n  Symbol(:\"a_name\") => untyped\n  Symbol(:\"b_name\") => untyped\n  Symbol(:\"added_lines\") => untyped\n  Symbol(:\"removed_lines\") => untyped\n}
<unconditional>"];

    "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_38" -> "bb::<constant:Opus>::<constant:CIBot>::<constant:Gerald>::<constant:Diff>#parse_5";
}

subgraph "cluster_::<constant:Range>#initialize" {
    label = "::<constant:Range>#initialize";
    color = blue;
    "bb::<constant:Range>#initialize_0" [shape = invhouse];
    "bb::<constant:Range>#initialize_1" [shape = parallelogram];

    "bb::<constant:Range>#initialize_0" [label = "()
selfMethodTemp$5 = self : Range
returnMethodTemp$4 = NotSupported() : untyped
returnMethodTemp$6 = return returnMethodTemp$4 : <bottom>
<unconditional>"];

    "bb::<constant:Range>#initialize_0" -> "bb::<constant:Range>#initialize_1";
    "bb::<constant:Range>#initialize_1" [label = "()
<unconditional>"];

    "bb::<constant:Range>#initialize_1" -> "bb::<constant:Range>#initialize_1";
}

}

