class <singleton class:<root>> (Class)
class <singleton class:<root>> (Class)
class Opus ()
  class CIBot ()
    class Gerald ()
      class <singleton class:Diff> (Class)
      class <singleton class:MatchContext> (Class)
      class <singleton class:MatchTimeout> (Class)
      class <singleton class:Matcher> (Class)
      class Diff (Object)
        field @parsed -> untyped
        field @raw -> untyped
        method added_files ()
          method <block>$10 (part)
            argument part
          method <block>$8 (part)
            argument part
        method added_lines ()
          method <block>$20 (part)
            argument part
        method affected_files ()
        method changed_files ()
          method <block>$16 (part)
            argument part
          method <block>$18 (part)
            argument part
        method changed_lines ()
        method changed_openapi? ()
        method deleted_files ()
          method <block>$12 (part)
            argument part
          method <block>$14 (part)
            argument part
        method initialize (raw_diff)
          argument raw_diff
        method parse (diff)
          argument diff
          method <block>$25 (part)
            argument part
            method <block>$27 (line)
              argument line
        method removed_lines ()
          method <block>$22 (part)
            argument part
      class MatchContext (Object)
        field @assignee -> untyped
        field @body -> untyped
        field @diff -> untyped
        field @gh_user -> untyped
        field @merge_branch -> untyped
        field @openapi_diff -> untyped
        field @repo -> untyped
        field @title -> untyped
        method initialize (repo, assignee, gh_user, merge_branch, body, title, diff, openapi_diff)
          argument assignee
          argument body
          argument diff
          argument gh_user
          argument merge_branch
          argument openapi_diff
          argument repo
          argument title
        method user_stripe_suffix? ()
      class MatchTimeBudget (Object)
        field @start -> untyped
        method check! ()
        method initialize ()
        method time_rule (rule)
          argument rule
        static-field PER_RULE_MS -> untyped
        static-field TOTAL_TIME_MS -> untyped
      class MatchTimeout (untyped)
        field @rule_token -> untyped
        method initialize (message, rule_token)
          argument message
          argument rule_token
      class Matcher (untyped)
        field @rules -> untyped
        method initialize ()
        method match (match_context)
          argument match_context
          method <block>$4 (r)
            argument r
            method <block>$6 ()
        static-field MAX_AFFECTED_FILES -> untyped

