class <constant:<root>> < ::<constant:Object> () @ test/testdata/first/namer.rb:2
  class <constant:ANamespace> (<constant:BasicObject>) @ test/testdata/first/namer.rb:13
    class <constant:ClassInNamespace> < ::<constant:Object> () @ test/testdata/first/namer.rb:17
    class <constant:ObviousChild> < ::<constant:Object> () @ test/testdata/first/namer.rb:14
    class <singleton class:<constant:ClassInNamespace>> < ::<singleton class:<constant:Object>> () @ test/testdata/first/namer.rb:17
    class <singleton class:<constant:ObviousChild>> < ::<singleton class:<constant:Object>> () @ test/testdata/first/namer.rb:14
  class <constant:Child> < ::<constant:Parent> (<constant:Mixin>) @ test/testdata/first/namer.rb:26
    method <static-init> () @ test/testdata/first/namer.rb:26
  class <constant:Mixin> (<constant:BasicObject>) @ test/testdata/first/namer.rb:22
  class <constant:NormalClass> < ::<constant:Object> () @ test/testdata/first/namer.rb:2
    class <constant:InnerClass> < ::<constant:Object> () @ test/testdata/first/namer.rb:7
    class <constant:InnerModule> (<constant:BasicObject>) @ test/testdata/first/namer.rb:9
    class <singleton class:<constant:InnerClass>> < ::<singleton class:<constant:Object>> () @ test/testdata/first/namer.rb:7
    class <singleton class:<constant:InnerModule>> < ::<constant:Module> () @ test/testdata/first/namer.rb:9
    method normal_method () @ test/testdata/first/namer.rb:3
  class <constant:OtherMixin> (<constant:BasicObject>) @ test/testdata/first/namer.rb:24
  class <constant:Parent> < ::<constant:Object> () @ test/testdata/first/namer.rb:20
  class <singleton class:<constant:ANamespace>> < ::<constant:Module> () @ test/testdata/first/namer.rb:13
  class <singleton class:<constant:Child>> < ::<singleton class:<constant:Parent>> () @ test/testdata/first/namer.rb:26
    method <block>$2 () @ test/testdata/first/namer.rb:30
  class <singleton class:<constant:Mixin>> < ::<constant:Module> () @ test/testdata/first/namer.rb:22
  class <singleton class:<constant:NormalClass>> < ::<singleton class:<constant:Object>> () @ test/testdata/first/namer.rb:2
    method normal_static_method () @ test/testdata/first/namer.rb:5
  class <singleton class:<constant:OtherMixin>> < ::<constant:Module> () @ test/testdata/first/namer.rb:24
  class <singleton class:<constant:Parent>> < ::<singleton class:<constant:Object>> () @ test/testdata/first/namer.rb:20
  method <static-init>$10 () @ test/testdata/first/namer.rb:2

