begin
  class <emptyTree><<constant:<root>>> < ()
    def self.<static-init><<static-init>$10>()
      begin
        <emptyTree>
        <emptyTree>
      end
    end
  end
  class <emptyTree>::<constant:Outer1><<constant:Outer1>> < (::<constant:<todo sym>>)  end
  class <emptyTree>::<constant:Outer2><<constant:Outer2>> < (::<constant:<todo sym>>)
    <emptyTree>

    <emptyTree>

    <emptyTree>

    <emptyTree>
  end
  class <emptyTree>::<constant:C><<constant:C>> < (::<constant:<todo sym>>)  end
  class <emptyTree>::<constant:Inner1><<constant:Inner1>> < (::<constant:<todo sym>>)
    <emptyTree>

    <emptyTree>
  end
  class <emptyTree>::<constant:A><<constant:A>> < (::<constant:<todo sym>>)  end
  class <emptyTree>::<constant:Inner2><<constant:Inner2>> < (::<constant:<todo sym>>)
    def self.<static-init><<static-init>>()
      begin
        ::<constant:Outer2>::<constant:Inner1>::<constant:A>
        ::<constant:Outer2>::<constant:Inner1>
        ::<constant:Outer2>::<constant:Inner1>::<constant:Inner2>
        ::<constant:Outer1>
        <emptyTree>
      end
    end
  end
  class <emptyTree>::<constant:Inner1>::<constant:Inner2><<constant:Inner2>> < (::<constant:<todo sym>>)
    def self.<static-init><<static-init>>()
      begin
        ::<constant:Outer2>::<constant:C>
        ::<constant:Outer2>::<constant:Inner1>::<constant:Inner2>::<constant:A>
        <emptyTree>
      end
    end
  end
  class <emptyTree>::<constant:Other><<constant:Other>> < (::<constant:Outer2>::<constant:Inner1>::<constant:Inner2>)  end
  <emptyTree>
end
