digraph "sigil.rb"{
subgraph "cluster_::<constant:Object>#foo" {
    label = "::<constant:Object>#foo";
    color = blue;
    "bb::<constant:Object>#foo_0" [shape = invhouse];
    "bb::<constant:Object>#foo_1" [shape = parallelogram];

    "bb::<constant:Object>#foo_0" [label = "block[id=0]()
<statTemp>$4 = 3 : String(\"3\")
<statTemp>$5 = 3 : Integer(3)
<returnMethodTemp>$2 = <statTemp>$4.+(<statTemp>$5) : String
<finalReturn> = return <returnMethodTemp>$2 : <bottom>
<unconditional>"];

    "bb::<constant:Object>#foo_0" -> "bb::<constant:Object>#foo_1" [style="bold"];
    "bb::<constant:Object>#foo_1" [label = "block[id=1]()
<unconditional>"];

    "bb::<constant:Object>#foo_1" -> "bb::<constant:Object>#foo_1" [style="bold"];
}

}

