begin
  class <emptyTree><<C <root>>> < (::<todo sym>)
    <emptyTree>

    <emptyTree>

    <emptyTree>

    <emptyTree>

    def self.<static-init><<static-init>$CENSORED>(<blk>)
      begin
        ::A.new().outer_method()
        ::A.new().inner_method()
        b = ::B.new()
        b.outer_method()
        b.inner_method()
        ::C.outer_method()
        ::C.new().inner_method()
        ::D.outer_method()
        ::D.inner_method()
        <emptyTree>
      end
    end
  end
  class ::A<<C A>> < (::<todo sym>)
    def outer_method(<blk>)
      <runtime method definition of inner_method>
    end

    def inner_method(<blk>)
      <self>.puts(<self>)
    end

    def self.<static-init>(<blk>)
      <runtime method definition of outer_method>
    end
  end
  class ::B<<C B>> < (::<todo sym>)
    def outer_method(<blk>)
      <runtime method definition of self.inner_method>
    end

    def inner_method(<blk>)
      <self>.puts(<self>)
    end

    def self.<static-init>(<blk>)
      <runtime method definition of outer_method>
    end
  end
  class ::C<<C C>> < (::<todo sym>)
    def self.outer_method(<blk>)
      <runtime method definition of inner_method>
    end

    def inner_method(<blk>)
      <self>.puts(<self>)
    end

    def self.<static-init>(<blk>)
      <runtime method definition of self.outer_method>
    end
  end
  class ::D<<C D>> < (::<todo sym>)
    def self.outer_method(<blk>)
      <runtime method definition of self.inner_method>
    end

    def self.inner_method(<blk>)
      <self>.puts(<self>)
    end

    def self.<static-init>(<blk>)
      <runtime method definition of self.outer_method>
    end
  end
  <emptyTree>
end
