method ::<Class:<root>>#<static-init> {

bb0[rubyRegionId=0, firstDead=26]():
    <self>: T.class_of(<root>) = cast(<self>: NilClass, T.class_of(<root>));
    <cfgAlias>$7: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$9: T.class_of(MyEnum) = alias <C MyEnum>
    <statTemp>$5: Sorbet::Private::Static::Void = <cfgAlias>$7: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$9: T.class_of(MyEnum))
    <cfgAlias>$12: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$14: T.class_of(T::Enum) = alias <C Enum>
    <cfgAlias>$16: T.class_of(T) = alias <C T>
    <statTemp>$10: Sorbet::Private::Static::Void = <cfgAlias>$12: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$14: T.class_of(T::Enum))
    <cfgAlias>$21: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$23: T.class_of(NotAnEnum) = alias <C NotAnEnum>
    <statTemp>$19: Sorbet::Private::Static::Void = <cfgAlias>$21: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$23: T.class_of(NotAnEnum))
    <cfgAlias>$28: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$30: T.class_of(EnumsDoEnum) = alias <C EnumsDoEnum>
    <statTemp>$26: Sorbet::Private::Static::Void = <cfgAlias>$28: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$30: T.class_of(EnumsDoEnum))
    <cfgAlias>$33: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$35: T.class_of(T::Enum) = alias <C Enum>
    <cfgAlias>$37: T.class_of(T) = alias <C T>
    <statTemp>$31: Sorbet::Private::Static::Void = <cfgAlias>$33: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$35: T.class_of(T::Enum))
    <cfgAlias>$42: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$44: T.class_of(BadConsts) = alias <C BadConsts>
    <statTemp>$40: Sorbet::Private::Static::Void = <cfgAlias>$42: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$44: T.class_of(BadConsts))
    <cfgAlias>$47: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$49: T.class_of(T::Enum) = alias <C Enum>
    <cfgAlias>$51: T.class_of(T) = alias <C T>
    <statTemp>$45: Sorbet::Private::Static::Void = <cfgAlias>$47: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$49: T.class_of(T::Enum))
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

method ::<Class:MyEnum>#<static-init> {

bb0[rubyRegionId=0, firstDead=-1]():
    <C X>$30: MyEnum::X = alias <C X>
    <C Y>$49: MyEnum::Y = alias <C Y>
    <C Z>$69: MyEnum::Z = alias <C Z>
    <self>: T.class_of(MyEnum) = cast(<self>: NilClass, T.class_of(MyEnum));
    <cfgAlias>$6: T.class_of(T::Helpers) = alias <C Helpers>
    <statTemp>$3: T.class_of(MyEnum) = <self>: T.class_of(MyEnum).extend(<cfgAlias>$6: T.class_of(T::Helpers))
    <statTemp>$7: Sorbet::Private::Static::Void = <self>: T.class_of(MyEnum).abstract!()
    <statTemp>$9: Sorbet::Private::Static::Void = <self>: T.class_of(MyEnum).sealed!()
    <block-pre-call-temp>$13: Sorbet::Private::Static::Void = <self>: T.class_of(MyEnum).enums()
    <selfRestore>$14: T.class_of(MyEnum) = <self>
    <unconditional> -> bb2

# backedges
# - bb3(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
# - bb5(rubyRegionId=1)
bb2[rubyRegionId=1, firstDead=-1](<self>: T.class_of(MyEnum), <block-pre-call-temp>$13: Sorbet::Private::Static::Void, <selfRestore>$14: T.class_of(MyEnum), <C X>$30: MyEnum::X, <C Y>$49: MyEnum::Y, <C Z>$69: MyEnum::Z):
    # outerLoops: 1
    <block-call> -> (NilClass ? bb5 : bb3)

# backedges
# - bb2(rubyRegionId=1)
bb3[rubyRegionId=0, firstDead=2](<block-pre-call-temp>$13: Sorbet::Private::Static::Void, <selfRestore>$14: T.class_of(MyEnum)):
    <statTemp>$11: Sorbet::Private::Static::Void = Solve<<block-pre-call-temp>$13, enums>
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb2(rubyRegionId=1)
bb5[rubyRegionId=1, firstDead=40](<self>: T.class_of(MyEnum), <block-pre-call-temp>$13: Sorbet::Private::Static::Void, <selfRestore>$14: T.class_of(MyEnum), <C X>$30: MyEnum::X, <C Y>$49: MyEnum::Y, <C Z>$69: MyEnum::Z):
    # outerLoops: 1
    <self>: T.class_of(MyEnum) = loadSelf(enums)
    <cfgAlias>$21: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$23: T.class_of(MyEnum::X) = alias <C X$1>
    <statTemp>$19: Sorbet::Private::Static::Void = <cfgAlias>$21: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$23: T.class_of(MyEnum::X))
    <cfgAlias>$26: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$28: T.class_of(MyEnum) = alias <C MyEnum>
    <statTemp>$24: Sorbet::Private::Static::Void = <cfgAlias>$26: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$28: T.class_of(MyEnum))
    <cfgAlias>$32: T.class_of(MyEnum::X) = alias <C X$1>
    keep_for_ide$31: T.class_of(MyEnum::X) = <cfgAlias>$32
    keep_for_ide$31: T.untyped = <keep-alive> keep_for_ide$31
    <cfgAlias>$35: T.class_of(MyEnum::X) = alias <C X$1>
    <castTemp>$33: MyEnum::X = <cfgAlias>$35: T.class_of(MyEnum::X).new()
    <C X>$30: MyEnum::X = <castTemp>$33
    <cfgAlias>$40: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$42: T.class_of(MyEnum::Y) = alias <C Y$1>
    <statTemp>$38: Sorbet::Private::Static::Void = <cfgAlias>$40: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$42: T.class_of(MyEnum::Y))
    <cfgAlias>$45: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$47: T.class_of(MyEnum) = alias <C MyEnum>
    <statTemp>$43: Sorbet::Private::Static::Void = <cfgAlias>$45: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$47: T.class_of(MyEnum))
    <cfgAlias>$51: T.class_of(MyEnum::Y) = alias <C Y$1>
    keep_for_ide$50: T.class_of(MyEnum::Y) = <cfgAlias>$51
    keep_for_ide$50: T.untyped = <keep-alive> keep_for_ide$50
    <cfgAlias>$54: T.class_of(MyEnum::Y) = alias <C Y$1>
    <statTemp>$55: String("y") = "y"
    <castTemp>$52: MyEnum::Y = <cfgAlias>$54: T.class_of(MyEnum::Y).new(<statTemp>$55: String("y"))
    <C Y>$49: MyEnum::Y = <castTemp>$52
    <cfgAlias>$60: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$62: T.class_of(MyEnum::Z) = alias <C Z$1>
    <statTemp>$58: Sorbet::Private::Static::Void = <cfgAlias>$60: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$62: T.class_of(MyEnum::Z))
    <cfgAlias>$65: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$67: T.class_of(MyEnum) = alias <C MyEnum>
    <statTemp>$63: Sorbet::Private::Static::Void = <cfgAlias>$65: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$67: T.class_of(MyEnum))
    <cfgAlias>$71: T.class_of(MyEnum::Z) = alias <C Z$1>
    keep_for_ide$70: T.class_of(MyEnum::Z) = <cfgAlias>$71
    keep_for_ide$70: T.untyped = <keep-alive> keep_for_ide$70
    <cfgAlias>$74: T.class_of(MyEnum::Z) = alias <C Z$1>
    <castTemp>$72: MyEnum::Z = <cfgAlias>$74: T.class_of(MyEnum::Z).new()
    <C Z>$69: MyEnum::Z = <castTemp>$72
    <blockReturnTemp>$16: NilClass = nil
    <blockReturnTemp>$75: T.noreturn = blockreturn<enums> <blockReturnTemp>$16: NilClass
    <unconditional> -> bb2

}

method ::MyEnum::<Class:X>#<static-init> {

bb0[rubyRegionId=0, firstDead=2]():
    <self>: T.class_of(MyEnum::X) = cast(<self>: NilClass, T.class_of(MyEnum::X));
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

method ::MyEnum::<Class:Y>#<static-init> {

bb0[rubyRegionId=0, firstDead=2]():
    <self>: T.class_of(MyEnum::Y) = cast(<self>: NilClass, T.class_of(MyEnum::Y));
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

method ::MyEnum::<Class:Z>#<static-init> {

bb0[rubyRegionId=0, firstDead=2]():
    <self>: T.class_of(MyEnum::Z) = cast(<self>: NilClass, T.class_of(MyEnum::Z));
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

method ::<Class:NotAnEnum>#<static-init> {

bb0[rubyRegionId=0, firstDead=-1]():
    <C X>$9: T.untyped = alias <C X>
    <C Y>$16: NotAnEnum = alias <C Y>
    <self>: T.class_of(NotAnEnum) = cast(<self>: NilClass, T.class_of(NotAnEnum));
    <block-pre-call-temp>$4: Sorbet::Private::Static::Void = <self>: T.class_of(NotAnEnum).enums()
    <selfRestore>$5: T.class_of(NotAnEnum) = <self>
    <unconditional> -> bb2

# backedges
# - bb3(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
# - bb5(rubyRegionId=1)
bb2[rubyRegionId=1, firstDead=-1](<self>: T.class_of(NotAnEnum), <block-pre-call-temp>$4: Sorbet::Private::Static::Void, <selfRestore>$5: T.class_of(NotAnEnum), <C X>$9: T.untyped, <C Y>$16: NotAnEnum):
    # outerLoops: 1
    <block-call> -> (NilClass ? bb5 : bb3)

# backedges
# - bb2(rubyRegionId=1)
bb3[rubyRegionId=0, firstDead=2](<block-pre-call-temp>$4: Sorbet::Private::Static::Void, <selfRestore>$5: T.class_of(NotAnEnum)):
    <returnMethodTemp>$2: T.untyped = Solve<<block-pre-call-temp>$4, enums>
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: T.untyped
    <unconditional> -> bb1

# backedges
# - bb2(rubyRegionId=1)
bb5[rubyRegionId=1, firstDead=12](<self>: T.class_of(NotAnEnum), <block-pre-call-temp>$4: Sorbet::Private::Static::Void, <selfRestore>$5: T.class_of(NotAnEnum), <C X>$9: T.untyped, <C Y>$16: NotAnEnum):
    # outerLoops: 1
    <self>: T.class_of(NotAnEnum) = loadSelf(enums)
    <cfgAlias>$11: T.class_of(<Magic>) = alias <C <Magic>>
    <cfgAlias>$14: T.class_of(<Magic>) = alias <C <Magic>>
    <statTemp>$12: T.attached_class (of NotAnEnum) = <cfgAlias>$14: T.class_of(<Magic>).<self-new>(<self>: T.class_of(NotAnEnum))
    <C X>$9: T.attached_class (of NotAnEnum) = <cfgAlias>$11: T.class_of(<Magic>).<suggest-constant-type>(<statTemp>$12: T.attached_class (of NotAnEnum))
    keep_for_ide$17: T.class_of(NotAnEnum) = <self>
    keep_for_ide$17: T.untyped = <keep-alive> keep_for_ide$17
    <cfgAlias>$20: T.class_of(<Magic>) = alias <C <Magic>>
    <castTemp>$18: T.attached_class (of NotAnEnum) = <cfgAlias>$20: T.class_of(<Magic>).<self-new>(<self>: T.class_of(NotAnEnum))
    <C Y>$16: NotAnEnum = cast(<castTemp>$18: T.attached_class (of NotAnEnum), NotAnEnum);
    <blockReturnTemp>$7: NotAnEnum = <C Y>$16
    <blockReturnTemp>$22: T.noreturn = blockreturn<enums> <blockReturnTemp>$7: NotAnEnum
    <unconditional> -> bb2

}

method ::EnumsDoEnum#something_outside {

bb0[rubyRegionId=0, firstDead=2]():
    <self>: EnumsDoEnum = cast(<self>: NilClass, EnumsDoEnum);
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

method ::<Class:EnumsDoEnum>#<static-init> {

bb0[rubyRegionId=0, firstDead=-1]():
    <C X>$30: EnumsDoEnum::X = alias <C X>
    <C Y>$49: EnumsDoEnum::Y = alias <C Y>
    <C Z>$69: EnumsDoEnum::Z = alias <C Z>
    <self>: T.class_of(EnumsDoEnum) = cast(<self>: NilClass, T.class_of(EnumsDoEnum));
    <cfgAlias>$6: T.class_of(T::Helpers) = alias <C Helpers>
    <statTemp>$3: T.class_of(EnumsDoEnum) = <self>: T.class_of(EnumsDoEnum).extend(<cfgAlias>$6: T.class_of(T::Helpers))
    <statTemp>$7: Sorbet::Private::Static::Void = <self>: T.class_of(EnumsDoEnum).abstract!()
    <statTemp>$9: Sorbet::Private::Static::Void = <self>: T.class_of(EnumsDoEnum).sealed!()
    <block-pre-call-temp>$13: Sorbet::Private::Static::Void = <self>: T.class_of(EnumsDoEnum).enums()
    <selfRestore>$14: T.class_of(EnumsDoEnum) = <self>
    <unconditional> -> bb2

# backedges
# - bb3(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
# - bb5(rubyRegionId=1)
bb2[rubyRegionId=1, firstDead=-1](<self>: T.class_of(EnumsDoEnum), <block-pre-call-temp>$13: Sorbet::Private::Static::Void, <selfRestore>$14: T.class_of(EnumsDoEnum), <C X>$30: EnumsDoEnum::X, <C Y>$49: EnumsDoEnum::Y, <C Z>$69: EnumsDoEnum::Z):
    # outerLoops: 1
    <block-call> -> (NilClass ? bb5 : bb3)

# backedges
# - bb2(rubyRegionId=1)
bb3[rubyRegionId=0, firstDead=2](<block-pre-call-temp>$13: Sorbet::Private::Static::Void, <selfRestore>$14: T.class_of(EnumsDoEnum)):
    <statTemp>$11: Sorbet::Private::Static::Void = Solve<<block-pre-call-temp>$13, enums>
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb2(rubyRegionId=1)
bb5[rubyRegionId=1, firstDead=40](<self>: T.class_of(EnumsDoEnum), <block-pre-call-temp>$13: Sorbet::Private::Static::Void, <selfRestore>$14: T.class_of(EnumsDoEnum), <C X>$30: EnumsDoEnum::X, <C Y>$49: EnumsDoEnum::Y, <C Z>$69: EnumsDoEnum::Z):
    # outerLoops: 1
    <self>: T.class_of(EnumsDoEnum) = loadSelf(enums)
    <cfgAlias>$21: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$23: T.class_of(EnumsDoEnum::X) = alias <C X$1>
    <statTemp>$19: Sorbet::Private::Static::Void = <cfgAlias>$21: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$23: T.class_of(EnumsDoEnum::X))
    <cfgAlias>$26: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$28: T.class_of(EnumsDoEnum) = alias <C EnumsDoEnum>
    <statTemp>$24: Sorbet::Private::Static::Void = <cfgAlias>$26: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$28: T.class_of(EnumsDoEnum))
    <cfgAlias>$32: T.class_of(EnumsDoEnum::X) = alias <C X$1>
    keep_for_ide$31: T.class_of(EnumsDoEnum::X) = <cfgAlias>$32
    keep_for_ide$31: T.untyped = <keep-alive> keep_for_ide$31
    <cfgAlias>$35: T.class_of(EnumsDoEnum::X) = alias <C X$1>
    <castTemp>$33: EnumsDoEnum::X = <cfgAlias>$35: T.class_of(EnumsDoEnum::X).new()
    <C X>$30: EnumsDoEnum::X = <castTemp>$33
    <cfgAlias>$40: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$42: T.class_of(EnumsDoEnum::Y) = alias <C Y$1>
    <statTemp>$38: Sorbet::Private::Static::Void = <cfgAlias>$40: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$42: T.class_of(EnumsDoEnum::Y))
    <cfgAlias>$45: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$47: T.class_of(EnumsDoEnum) = alias <C EnumsDoEnum>
    <statTemp>$43: Sorbet::Private::Static::Void = <cfgAlias>$45: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$47: T.class_of(EnumsDoEnum))
    <cfgAlias>$51: T.class_of(EnumsDoEnum::Y) = alias <C Y$1>
    keep_for_ide$50: T.class_of(EnumsDoEnum::Y) = <cfgAlias>$51
    keep_for_ide$50: T.untyped = <keep-alive> keep_for_ide$50
    <cfgAlias>$54: T.class_of(EnumsDoEnum::Y) = alias <C Y$1>
    <statTemp>$55: String("y") = "y"
    <castTemp>$52: EnumsDoEnum::Y = <cfgAlias>$54: T.class_of(EnumsDoEnum::Y).new(<statTemp>$55: String("y"))
    <C Y>$49: EnumsDoEnum::Y = <castTemp>$52
    <cfgAlias>$60: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$62: T.class_of(EnumsDoEnum::Z) = alias <C Z$1>
    <statTemp>$58: Sorbet::Private::Static::Void = <cfgAlias>$60: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$62: T.class_of(EnumsDoEnum::Z))
    <cfgAlias>$65: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$67: T.class_of(EnumsDoEnum) = alias <C EnumsDoEnum>
    <statTemp>$63: Sorbet::Private::Static::Void = <cfgAlias>$65: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$67: T.class_of(EnumsDoEnum))
    <cfgAlias>$71: T.class_of(EnumsDoEnum::Z) = alias <C Z$1>
    keep_for_ide$70: T.class_of(EnumsDoEnum::Z) = <cfgAlias>$71
    keep_for_ide$70: T.untyped = <keep-alive> keep_for_ide$70
    <cfgAlias>$74: T.class_of(EnumsDoEnum::Z) = alias <C Z$1>
    <castTemp>$72: EnumsDoEnum::Z = <cfgAlias>$74: T.class_of(EnumsDoEnum::Z).new()
    <C Z>$69: EnumsDoEnum::Z = <castTemp>$72
    <blockReturnTemp>$16: NilClass = nil
    <blockReturnTemp>$75: T.noreturn = blockreturn<enums> <blockReturnTemp>$16: NilClass
    <unconditional> -> bb2

}

method ::EnumsDoEnum::<Class:X>#<static-init> {

bb0[rubyRegionId=0, firstDead=2]():
    <self>: T.class_of(EnumsDoEnum::X) = cast(<self>: NilClass, T.class_of(EnumsDoEnum::X));
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

method ::EnumsDoEnum::<Class:Y>#<static-init> {

bb0[rubyRegionId=0, firstDead=2]():
    <self>: T.class_of(EnumsDoEnum::Y) = cast(<self>: NilClass, T.class_of(EnumsDoEnum::Y));
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

method ::EnumsDoEnum::<Class:Z>#<static-init> {

bb0[rubyRegionId=0, firstDead=2]():
    <self>: T.class_of(EnumsDoEnum::Z) = cast(<self>: NilClass, T.class_of(EnumsDoEnum::Z));
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

method ::<Class:BadConsts>#<static-init> {

bb0[rubyRegionId=0, firstDead=-1]():
    <C Before>$24: BadConsts::Before = alias <C Before>
    <C StaticField1>$31: Integer = alias <C StaticField1>
    <C Inside>$51: BadConsts::Inside = alias <C Inside>
    <C StaticField2>$58: Integer = alias <C StaticField2>
    <C After>$73: BadConsts::After = alias <C After>
    <C StaticField3>$80: Integer = alias <C StaticField3>
    <C StaticField4>$82: Integer = alias <C StaticField4>
    <self>: T.class_of(BadConsts) = cast(<self>: NilClass, T.class_of(BadConsts));
    <cfgAlias>$6: T.class_of(T::Helpers) = alias <C Helpers>
    <statTemp>$3: T.class_of(BadConsts) = <self>: T.class_of(BadConsts).extend(<cfgAlias>$6: T.class_of(T::Helpers))
    <statTemp>$7: Sorbet::Private::Static::Void = <self>: T.class_of(BadConsts).abstract!()
    <statTemp>$9: Sorbet::Private::Static::Void = <self>: T.class_of(BadConsts).sealed!()
    <cfgAlias>$15: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$17: T.class_of(BadConsts::Before) = alias <C Before$1>
    <statTemp>$13: Sorbet::Private::Static::Void = <cfgAlias>$15: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$17: T.class_of(BadConsts::Before))
    <cfgAlias>$20: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$22: T.class_of(BadConsts) = alias <C BadConsts>
    <statTemp>$18: Sorbet::Private::Static::Void = <cfgAlias>$20: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$22: T.class_of(BadConsts))
    <cfgAlias>$26: T.class_of(BadConsts::Before) = alias <C Before$1>
    keep_for_ide$25: T.class_of(BadConsts::Before) = <cfgAlias>$26
    keep_for_ide$25: T.untyped = <keep-alive> keep_for_ide$25
    <cfgAlias>$29: T.class_of(BadConsts::Before) = alias <C Before$1>
    <castTemp>$27: BadConsts::Before = <cfgAlias>$29: T.class_of(BadConsts::Before).new()
    <C Before>$24: BadConsts::Before = <castTemp>$27
    <C StaticField1>$31: Integer(1) = 1
    <block-pre-call-temp>$34: Sorbet::Private::Static::Void = <self>: T.class_of(BadConsts).enums()
    <selfRestore>$35: T.class_of(BadConsts) = <self>
    <unconditional> -> bb2

# backedges
# - bb3(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
# - bb5(rubyRegionId=1)
bb2[rubyRegionId=1, firstDead=-1](<self>: T.class_of(BadConsts), <block-pre-call-temp>$34: Sorbet::Private::Static::Void, <selfRestore>$35: T.class_of(BadConsts), <C Inside>$51: BadConsts::Inside, <C StaticField2>$58: Integer, <C After>$73: BadConsts::After, <C StaticField3>$80: Integer, <C StaticField4>$82: Integer):
    # outerLoops: 1
    <block-call> -> (NilClass ? bb5 : bb3)

# backedges
# - bb2(rubyRegionId=1)
bb3[rubyRegionId=0, firstDead=20](<block-pre-call-temp>$34: Sorbet::Private::Static::Void, <selfRestore>$35: T.class_of(BadConsts), <C After>$73: BadConsts::After, <C StaticField3>$80: Integer, <C StaticField4>$82: Integer):
    <statTemp>$32: Sorbet::Private::Static::Void = Solve<<block-pre-call-temp>$34, enums>
    <cfgAlias>$64: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$66: T.class_of(BadConsts::After) = alias <C After$1>
    <statTemp>$62: Sorbet::Private::Static::Void = <cfgAlias>$64: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$66: T.class_of(BadConsts::After))
    <cfgAlias>$69: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$71: T.class_of(BadConsts) = alias <C BadConsts>
    <statTemp>$67: Sorbet::Private::Static::Void = <cfgAlias>$69: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$71: T.class_of(BadConsts))
    <cfgAlias>$75: T.class_of(BadConsts::After) = alias <C After$1>
    keep_for_ide$74: T.class_of(BadConsts::After) = <cfgAlias>$75
    keep_for_ide$74: T.untyped = <keep-alive> keep_for_ide$74
    <cfgAlias>$78: T.class_of(BadConsts::After) = alias <C After$1>
    <castTemp>$76: BadConsts::After = <cfgAlias>$78: T.class_of(BadConsts::After).new()
    <C After>$73: BadConsts::After = <castTemp>$76
    <C StaticField3>$80: Integer(3) = 3
    <cfgAlias>$84: T.class_of(Integer) = alias <C Integer>
    keep_for_ide$83: T.class_of(Integer) = <cfgAlias>$84
    keep_for_ide$83: T.untyped = <keep-alive> keep_for_ide$83
    <castTemp>$85: Integer(1) = 1
    <C StaticField4>$82: Integer = cast(<castTemp>$85: Integer(1), Integer);
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb2(rubyRegionId=1)
bb5[rubyRegionId=1, firstDead=16](<self>: T.class_of(BadConsts), <block-pre-call-temp>$34: Sorbet::Private::Static::Void, <selfRestore>$35: T.class_of(BadConsts), <C Inside>$51: BadConsts::Inside, <C StaticField2>$58: Integer, <C After>$73: BadConsts::After, <C StaticField3>$80: Integer, <C StaticField4>$82: Integer):
    # outerLoops: 1
    <self>: T.class_of(BadConsts) = loadSelf(enums)
    <cfgAlias>$42: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$44: T.class_of(BadConsts::Inside) = alias <C Inside$1>
    <statTemp>$40: Sorbet::Private::Static::Void = <cfgAlias>$42: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$44: T.class_of(BadConsts::Inside))
    <cfgAlias>$47: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$49: T.class_of(BadConsts) = alias <C BadConsts>
    <statTemp>$45: Sorbet::Private::Static::Void = <cfgAlias>$47: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$49: T.class_of(BadConsts))
    <cfgAlias>$53: T.class_of(BadConsts::Inside) = alias <C Inside$1>
    keep_for_ide$52: T.class_of(BadConsts::Inside) = <cfgAlias>$53
    keep_for_ide$52: T.untyped = <keep-alive> keep_for_ide$52
    <cfgAlias>$56: T.class_of(BadConsts::Inside) = alias <C Inside$1>
    <castTemp>$54: BadConsts::Inside = <cfgAlias>$56: T.class_of(BadConsts::Inside).new()
    <C Inside>$51: BadConsts::Inside = <castTemp>$54
    <C StaticField2>$58: Integer(2) = 2
    <blockReturnTemp>$37: NilClass = nil
    <blockReturnTemp>$59: T.noreturn = blockreturn<enums> <blockReturnTemp>$37: NilClass
    <unconditional> -> bb2

}

method ::BadConsts::<Class:Before>#<static-init> {

bb0[rubyRegionId=0, firstDead=2]():
    <self>: T.class_of(BadConsts::Before) = cast(<self>: NilClass, T.class_of(BadConsts::Before));
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

method ::BadConsts::<Class:Inside>#<static-init> {

bb0[rubyRegionId=0, firstDead=2]():
    <self>: T.class_of(BadConsts::Inside) = cast(<self>: NilClass, T.class_of(BadConsts::Inside));
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

method ::BadConsts::<Class:After>#<static-init> {

bb0[rubyRegionId=0, firstDead=2]():
    <self>: T.class_of(BadConsts::After) = cast(<self>: NilClass, T.class_of(BadConsts::After));
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

