begin
  class <emptyTree><<C <U <root>>>> < ()
    def self.<U <static-init>><<N <U <static-init>> $3>>(<blk>)
      begin
        begin
          ::RubyTyper.<U keep_for_ide>(::Opus::DB::Model::MyModel)
          <emptyTree>
        end
        ::Opus::DB::Model::MyModel
        <emptyTree>
      end
    end
  end
  class ::Opus::DB::Model::MyModel<<C <U MyModel>>> < (::<todo sym>)  end
  <emptyTree>
end
