digraph "constructors.rb"{
subgraph "cluster_::<singleton class:<constant:Foo2>>#new" {
    label = "::<singleton class:<constant:Foo2>>#new";
    color = blue;
    "bb::<singleton class:<constant:Foo2>>#new_0" [shape = invhouse];
    "bb::<singleton class:<constant:Foo2>>#new_1" [shape = parallelogram];

    "bb::<singleton class:<constant:Foo2>>#new_0" [label = "()
selfMethodTemp$2 = self : <class:Foo2>
returnMethodTemp$1 = NotSupported() : untyped
returnMethodTemp$3 = return returnMethodTemp$1 : <bottom>
<unconditional>"];

    "bb::<singleton class:<constant:Foo2>>#new_0" -> "bb::<singleton class:<constant:Foo2>>#new_1";
    "bb::<singleton class:<constant:Foo2>>#new_1" [label = "()
<unconditional>"];

    "bb::<singleton class:<constant:Foo2>>#new_1" -> "bb::<singleton class:<constant:Foo2>>#new_1";
}

subgraph "cluster_::<constant:Foo3>#initialize" {
    label = "::<constant:Foo3>#initialize";
    color = blue;
    "bb::<constant:Foo3>#initialize_0" [shape = invhouse];
    "bb::<constant:Foo3>#initialize_1" [shape = parallelogram];

    "bb::<constant:Foo3>#initialize_0" [label = "()
selfMethodTemp$2 = self : Foo3
returnMethodTemp$1 = NotSupported() : untyped
returnMethodTemp$3 = return returnMethodTemp$1 : <bottom>
<unconditional>"];

    "bb::<constant:Foo3>#initialize_0" -> "bb::<constant:Foo3>#initialize_1";
    "bb::<constant:Foo3>#initialize_1" [label = "()
<unconditional>"];

    "bb::<constant:Foo3>#initialize_1" -> "bb::<constant:Foo3>#initialize_1";
}

subgraph "cluster_::<constant:Bar>#foo" {
    label = "::<constant:Bar>#foo";
    color = blue;
    "bb::<constant:Bar>#foo_0" [shape = invhouse];
    "bb::<constant:Bar>#foo_1" [shape = parallelogram];

    "bb::<constant:Bar>#foo_0" [label = "()
<constant:Foo1>$5 = alias <constant:Foo1> : <class:Foo1>
<constant:Foo2>$8 = alias <constant:Foo2> : <class:Foo2>
<constant:Foo3>$11 = alias <constant:Foo3> : <class:Foo3>
statTemp$3 = <constant:Foo1>$5.new() : Foo1
statTemp$9 = 1 : Integer(1)
statTemp$6 = <constant:Foo2>$8.new(statTemp$9) : untyped
statTemp$12 = 1 : Integer(1)
statTemp$13 = 2 : Integer(2)
returnMethodTemp$1 = <constant:Foo3>$11.new(statTemp$12, statTemp$13) : Foo3
returnMethodTemp$14 = return returnMethodTemp$1 : <bottom>
<unconditional>"];

    "bb::<constant:Bar>#foo_0" -> "bb::<constant:Bar>#foo_1";
    "bb::<constant:Bar>#foo_1" [label = "()
<unconditional>"];

    "bb::<constant:Bar>#foo_1" -> "bb::<constant:Bar>#foo_1";
}

subgraph "cluster_::<constant:InstanceMethod>#test_imethod_new" {
    label = "::<constant:InstanceMethod>#test_imethod_new";
    color = blue;
    "bb::<constant:InstanceMethod>#test_imethod_new_0" [shape = invhouse];
    "bb::<constant:InstanceMethod>#test_imethod_new_1" [shape = parallelogram];

    "bb::<constant:InstanceMethod>#test_imethod_new_0" [label = "()
<constant:Object>$5 = alias <constant:Object> : <class:Object>
o = <constant:Object>$5.new() : Object
returnMethodTemp$1 = o.new() : untyped
returnMethodTemp$7 = return returnMethodTemp$1 : <bottom>
<unconditional>"];

    "bb::<constant:InstanceMethod>#test_imethod_new_0" -> "bb::<constant:InstanceMethod>#test_imethod_new_1";
    "bb::<constant:InstanceMethod>#test_imethod_new_1" [label = "()
<unconditional>"];

    "bb::<constant:InstanceMethod>#test_imethod_new_1" -> "bb::<constant:InstanceMethod>#test_imethod_new_1";
}

}

