digraph "controlFlow3.rb"{
subgraph "cluster_::<constant:Test>#normalize_params" {
    label = "::<constant:Test>#normalize_params";
    color = blue;
    "bb::<constant:Test>#normalize_params_0" [shape = invhouse];
    "bb::<constant:Test>#normalize_params_1" [shape = parallelogram];

    "bb::<constant:Test>#normalize_params_0" [label = "block[id=0](v, <constant:Array>$16)
<constant:Hash>$8 = alias <constant:Hash> : <class:Hash>
<constant:Array>$16 = alias <constant:Array> : <class:Array>
selfMethodTemp$4 = self : Test
v = load_arg(selfMethodTemp$4#normalize_params, 0) : untyped
ifTemp$5 = v.is_a?(<constant:Hash>$8) : untyped
ifTemp$5"];

    "bb::<constant:Test>#normalize_params_0" -> "bb::<constant:Test>#normalize_params_2" [style="bold"];
    "bb::<constant:Test>#normalize_params_0" -> "bb::<constant:Test>#normalize_params_3" [style="tapered"];

    "bb::<constant:Test>#normalize_params_1" [label = "block[id=1]()
<unconditional>"];

    "bb::<constant:Test>#normalize_params_1" -> "bb::<constant:Test>#normalize_params_1" [style="bold"];
    "bb::<constant:Test>#normalize_params_2" [label = "block[id=2](v, returnMethodTemp$3)
statTemp$10 = self : Test
statTemp$11 = v.to_a() : Array
statTemp$9 = statTemp$10.normalize_params(statTemp$11) : untyped
returnMethodTemp$3 = statTemp$9.sort() : untyped
<unconditional>"];

    "bb::<constant:Test>#normalize_params_2" -> "bb::<constant:Test>#normalize_params_10" [style="bold"];
    "bb::<constant:Test>#normalize_params_3" [label = "block[id=3](v, <constant:Array>$16)
ifTemp$13 = v.is_a?(<constant:Array>$16) : untyped
ifTemp$13"];

    "bb::<constant:Test>#normalize_params_3" -> "bb::<constant:Test>#normalize_params_4" [style="bold"];
    "bb::<constant:Test>#normalize_params_3" -> "bb::<constant:Test>#normalize_params_5" [style="tapered"];

    "bb::<constant:Test>#normalize_params_4" [label = "block[id=4](v, statTemp$17)
statTemp$17 = v : Array
<unconditional>"];

    "bb::<constant:Test>#normalize_params_4" -> "bb::<constant:Test>#normalize_params_6" [style="bold"];
    "bb::<constant:Test>#normalize_params_5" [label = "block[id=5](v, returnMethodTemp$3)
returnMethodTemp$3 = v : untyped
<unconditional>"];

    "bb::<constant:Test>#normalize_params_5" -> "bb::<constant:Test>#normalize_params_10" [style="bold"];
    "bb::<constant:Test>#normalize_params_6" [label = "block[id=6](statTemp$17)
outerLoops: 1
<block-call>"];

    "bb::<constant:Test>#normalize_params_6" -> "bb::<constant:Test>#normalize_params_8" [style="bold"];
    "bb::<constant:Test>#normalize_params_6" -> "bb::<constant:Test>#normalize_params_7" [style="tapered"];

    "bb::<constant:Test>#normalize_params_7" [label = "block[id=7](returnMethodTemp$3, statTemp$17)
returnMethodTemp$3 = statTemp$17.map() : Array | Enumerator
<unconditional>"];

    "bb::<constant:Test>#normalize_params_7" -> "bb::<constant:Test>#normalize_params_10" [style="bold"];
    "bb::<constant:Test>#normalize_params_8" [label = "block[id=8](statTemp$17)
outerLoops: 1
<block-nested: e> = load_arg(statTemp$17#map, 0) : untyped
statTemp$19 = self : Test
blockReturnTemp$18 = statTemp$19.normalize_params(<block-nested: e>) : untyped
<unconditional>"];

    "bb::<constant:Test>#normalize_params_8" -> "bb::<constant:Test>#normalize_params_6" [style="bold"];
    "bb::<constant:Test>#normalize_params_10" [label = "block[id=10](returnMethodTemp$3)
returnMethodTemp$21 = return returnMethodTemp$3 : <bottom>
<unconditional>"];

    "bb::<constant:Test>#normalize_params_10" -> "bb::<constant:Test>#normalize_params_1" [style="bold"];
}

}

