digraph "fields.rb"{
subgraph "cluster_::<constant:Foo>#foo" {
    label = "::<constant:Foo>#foo";
    color = blue;
    "bb::<constant:Foo>#foo_0" [shape = invhouse];
    "bb::<constant:Foo>#foo_1" [shape = parallelogram];

    "bb::<constant:Foo>#foo_0" [label = "block[id=0]()
@ivar$4 = alias @ivar : Integer
@ivar$4 = 2 : Integer(2)
@ivar$4 = ss : untyped
returnMethodTemp$5 = return @ivar$4 : <bottom>
<unconditional>"];

    "bb::<constant:Foo>#foo_0" -> "bb::<constant:Foo>#foo_1" [style="bold"];
    "bb::<constant:Foo>#foo_1" [label = "block[id=1]()
<unconditional>"];

    "bb::<constant:Foo>#foo_1" -> "bb::<constant:Foo>#foo_1" [style="bold"];
}

}

