digraph "infer1.rb"{
subgraph "cluster_::String#getbyte" {
    label = "::String#getbyte";
    color = blue;
    bb26_0 [shape = invhouse];
    bb26_1 [shape = parallelogram];

    bb26_0 [label = "()\n<self>$3 = self : String\n<ret>$2 = NotSupported() : <dynamic>\n<ret>$4 = return <ret>$2 : <bottom>\n<never>"];
    bb26_0 -> bb26_1;
    bb26_1 [label = "()\n<never>"];
    bb26_1 -> bb26_1;
}

subgraph "cluster_::Integer#+" {
    label = "::Integer#+";
    color = blue;
    bb29_0 [shape = invhouse];
    bb29_1 [shape = parallelogram];

    bb29_0 [label = "()\n<self>$6 = self : Integer\n<ret>$5 = NotSupported() : <dynamic>\n<ret>$7 = return <ret>$5 : <bottom>\n<never>"];
    bb29_0 -> bb29_1;
    bb29_1 [label = "()\n<never>"];
    bb29_1 -> bb29_1;
}

subgraph "cluster_::Object#baz1" {
    label = "::Object#baz1";
    color = blue;
    bb31_0 [shape = invhouse];
    bb31_1 [shape = parallelogram];

    bb31_0 [label = "()\na = foo : String(\"foo\")\nb = a.getbyte(a) : Integer | NilClass\n<ret>$13 = return b : <bottom>\n<never>"];
    bb31_0 -> bb31_1;
    bb31_1 [label = "()\n<never>"];
    bb31_1 -> bb31_1;
}

subgraph "cluster_::Object#baz2" {
    label = "::Object#baz2";
    color = blue;
    bb34_0 [shape = invhouse];
    bb34_1 [shape = parallelogram];

    bb34_0 [label = "()\na = foo : String(\"foo\")\nstatTmp$18 = foo : String(\"foo\")\nb = a.getbyte(statTmp$18) : Integer | NilClass\n<ret>$19 = return b : <bottom>\n<never>"];
    bb34_0 -> bb34_1;
    bb34_1 [label = "()\n<never>"];
    bb34_1 -> bb34_1;
}

subgraph "cluster_::Object#baz3" {
    label = "::Object#baz3";
    color = blue;
    bb37_0 [shape = invhouse];
    bb37_1 [shape = parallelogram];

    bb37_0 [label = "()\nstatTmp$22 = foo : String(\"foo\")\nstatTmp$23 = foo : String(\"foo\")\nb = statTmp$22.getbyte(statTmp$23) : Integer | NilClass\n<ret>$24 = return b : <bottom>\n<never>"];
    bb37_0 -> bb37_1;
    bb37_1 [label = "()\n<never>"];
    bb37_1 -> bb37_1;
}

subgraph "cluster_::Object#baz4" {
    label = "::Object#baz4";
    color = blue;
    bb39_0 [shape = invhouse];
    bb39_1 [shape = parallelogram];

    bb39_0 [label = "()\nstatTmp$28 = self : Object\nstatTmp$27 = statTmp$28.a() : <dynamic>\nstatTmp$29 = foo : String(\"foo\")\nb = statTmp$27.getbyte(statTmp$29) : <dynamic>\n<ret>$30 = return b : <bottom>\n<never>"];
    bb39_0 -> bb39_1;
    bb39_1 [label = "()\n<never>"];
    bb39_1 -> bb39_1;
}

subgraph "cluster_::Object#baz5" {
    label = "::Object#baz5";
    color = blue;
    bb41_0 [shape = invhouse];
    bb41_1 [shape = parallelogram];

    bb41_0 [label = "()\nifTmp$34 = true : TrueClass(true)\nifTmp$34"];
    bb41_0 -> bb41_2;
    bb41_0 -> bb41_3;

    bb41_1 [label = "()\n<never>"];
    bb41_1 -> bb41_1;
    bb41_2 [label = "(b)\nb = 1 : Integer(1)\n<always>"];
    bb41_2 -> bb41_4;
    bb41_3 [label = "(b)\nb = foo : String(\"foo\")\n<always>"];
    bb41_3 -> bb41_4;
    bb41_4 [label = "(b)\nstatTmp$35 = b : Integer | String\nstatTmp$36 = 1 : Integer(1)\nb = statTmp$35.getbyte(statTmp$36) : <dynamic>\n<ret>$37 = return b : <bottom>\n<never>"];
    bb41_4 -> bb41_1;
}

subgraph "cluster_::Object#baz6" {
    label = "::Object#baz6";
    color = blue;
    bb43_0 [shape = invhouse];
    bb43_1 [shape = parallelogram];

    bb43_0 [label = "()\nifTmp$41 = true : TrueClass(true)\nifTmp$41"];
    bb43_0 -> bb43_2;
    bb43_0 -> bb43_3;

    bb43_1 [label = "()\n<never>"];
    bb43_1 -> bb43_1;
    bb43_2 [label = "(b)\nb = 1 : Integer(1)\n<always>"];
    bb43_2 -> bb43_4;
    bb43_3 [label = "(b)\nb = foo : String(\"foo\")\n<always>"];
    bb43_3 -> bb43_4;
    bb43_4 [label = "(b)\nstatTmp$42 = foo : String(\"foo\")\nstatTmp$43 = b : Integer | String\nb = statTmp$42.getbyte(statTmp$43) : Integer | NilClass\n<ret>$44 = return b : <bottom>\n<never>"];
    bb43_4 -> bb43_1;
}

subgraph "cluster_::Object#baz7" {
    label = "::Object#baz7";
    color = blue;
    bb45_0 [shape = invhouse];
    bb45_1 [shape = parallelogram];

    bb45_0 [label = "()\nifTmp$48 = true : TrueClass(true)\nifTmp$48"];
    bb45_0 -> bb45_2;
    bb45_0 -> bb45_3;

    bb45_1 [label = "()\n<never>"];
    bb45_1 -> bb45_1;
    bb45_2 [label = "(b)\nb = 1 : Integer(1)\n<always>"];
    bb45_2 -> bb45_4;
    bb45_3 [label = "()\nstatTmp$47 = NotSupported() : <dynamic>\n<always>"];
    bb45_3 -> bb45_4;
    bb45_4 [label = "(b)\nstatTmp$49 = foo : String(\"foo\")\nstatTmp$50 = b : Integer | NilClass\nb = statTmp$49.getbyte(statTmp$50) : Integer | NilClass\n<ret>$51 = return b : <bottom>\n<never>"];
    bb45_4 -> bb45_1;
}

subgraph "cluster_::Object#baz8" {
    label = "::Object#baz8";
    color = blue;
    bb47_0 [shape = invhouse];
    bb47_1 [shape = parallelogram];

    bb47_0 [label = "()\n<always>"];
    bb47_0 -> bb47_2;
    bb47_1 [label = "()\n<never>"];
    bb47_1 -> bb47_1;
    bb47_2 [label = "()\nouterLoops: 1\nwhileTmp$54 = true : TrueClass(true)\nwhileTmp$54"];
    bb47_2 -> bb47_3;
    bb47_2 -> bb47_4;

    bb47_3 [label = "()\nouterLoops: 1\nb = 1 : Integer(1)\n<always>"];
    bb47_3 -> bb47_2;
    bb47_4 [label = "()\n<ret>$52 = nil : NilClass\n<ret>$56 = return <ret>$52 : <bottom>\n<never>"];
    bb47_4 -> bb47_1;
}

}

