digraph "singleton_of_singleton.rb" {
subgraph "cluster_::<Class:A>#foo" {
    label = "::<Class:A>#foo";
    color = blue;
    "bb::<Class:A>#foo_0" [shape = invhouse];
    "bb::<Class:A>#foo_1" [shape = parallelogram];

    "bb::<Class:A>#foo_0" [
        label = "block[id=0]()\l<finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass\l<unconditional>\l"
    ];

    "bb::<Class:A>#foo_0" -> "bb::<Class:A>#foo_1" [style="bold"];
    "bb::<Class:A>#foo_1" [
        label = "block[id=1]()\l<unconditional>\l"
    ];

    "bb::<Class:A>#foo_1" -> "bb::<Class:A>#foo_1" [style="bold"];
}

subgraph "cluster_::<Class:<Class:A>>#bar" {
    label = "::<Class:<Class:A>>#bar";
    color = blue;
    "bb::<Class:<Class:A>>#bar_0" [shape = invhouse];
    "bb::<Class:<Class:A>>#bar_1" [shape = parallelogram];

    "bb::<Class:<Class:A>>#bar_0" [
        label = "block[id=0]()\l<returnMethodTemp>$2: T.class_of(T.class_of(A)) = self\l<finalReturn>: T.noreturn = return <returnMethodTemp>$2: T.class_of(T.class_of(A))\l<unconditional>\l"
    ];

    "bb::<Class:<Class:A>>#bar_0" -> "bb::<Class:<Class:A>>#bar_1" [style="bold"];
    "bb::<Class:<Class:A>>#bar_1" [
        label = "block[id=1]()\l<unconditional>\l"
    ];

    "bb::<Class:<Class:A>>#bar_1" -> "bb::<Class:<Class:A>>#bar_1" [style="bold"];
}

}

