digraph "zsuper.rb"{
subgraph "cluster_::<constant:Foo>#baz" {
    label = "::<constant:Foo>#baz";
    color = blue;
    "bb::<constant:Foo>#baz_0" [shape = invhouse];
    "bb::<constant:Foo>#baz_1" [shape = parallelogram];

    "bb::<constant:Foo>#baz_0" [label = "block[id=0]()
selfMethodTemp$3 = self : Foo
a = load_arg(selfMethodTemp$3#baz, 0) : untyped
statTemp$4 = self : Foo
returnMethodTemp$2 = statTemp$4.puts(a) : NilClass
finalReturn = return returnMethodTemp$2 : <bottom>
<unconditional>"];

    "bb::<constant:Foo>#baz_0" -> "bb::<constant:Foo>#baz_1" [style="bold"];
    "bb::<constant:Foo>#baz_1" [label = "block[id=1]()
<unconditional>"];

    "bb::<constant:Foo>#baz_1" -> "bb::<constant:Foo>#baz_1" [style="bold"];
}

subgraph "cluster_::<constant:Bar>#baz" {
    label = "::<constant:Bar>#baz";
    color = blue;
    "bb::<constant:Bar>#baz_0" [shape = invhouse];
    "bb::<constant:Bar>#baz_1" [shape = parallelogram];

    "bb::<constant:Bar>#baz_0" [label = "block[id=0]()
selfMethodTemp$4 = self : Bar
b = load_arg(selfMethodTemp$4#baz, 0) : untyped
statTemp$5 = self : Bar
statTemp$6 = b : untyped
<unconditional>"];

    "bb::<constant:Bar>#baz_0" -> "bb::<constant:Bar>#baz_2" [style="bold"];
    "bb::<constant:Bar>#baz_1" [label = "block[id=1]()
<unconditional>"];

    "bb::<constant:Bar>#baz_1" -> "bb::<constant:Bar>#baz_1" [style="bold"];
    "bb::<constant:Bar>#baz_2" [label = "block[id=2](statTemp$5, statTemp$6)
outerLoops: 1
<block-call>"];

    "bb::<constant:Bar>#baz_2" -> "bb::<constant:Bar>#baz_4" [style="bold"];
    "bb::<constant:Bar>#baz_2" -> "bb::<constant:Bar>#baz_3" [style="tapered"];

    "bb::<constant:Bar>#baz_3" [label = "block[id=3](statTemp$5, statTemp$6)
returnMethodTemp$3 = statTemp$5.super(statTemp$6) : untyped
finalReturn = return returnMethodTemp$3 : <bottom>
<unconditional>"];

    "bb::<constant:Bar>#baz_3" -> "bb::<constant:Bar>#baz_1" [style="bold"];
    "bb::<constant:Bar>#baz_4" [label = "block[id=4](statTemp$5, statTemp$6)
outerLoops: 1
a$5817 = load_arg(statTemp$5#super, 0) : untyped
statTemp$8 = self : Bar
blockReturnTemp$7 = statTemp$8.puts(a$5817) : NilClass
<unconditional>"];

    "bb::<constant:Bar>#baz_4" -> "bb::<constant:Bar>#baz_2" [style="bold"];
}

}

