#!/bin/bash

set -e

# This file was inspired by https://github.com/bazelbuild/bazel at d6fec93.

# This script will be run bazel when building process starts to
# generate key-value information that represents the status of the
# workspace. The output should be like
#
# KEY1 VALUE1
# KEY2 VALUE2
#
# If the script exits with non-zero code, it's considered as a failure
# and the output will be discarded.

# The code below presents an implementation that works for git repository
git_rev=$(git rev-parse HEAD)
echo "BUILD_SCM_REVISION ${git_rev}"

# Check whether there are any uncommited changes
set +e
if git diff-index --quiet HEAD --; then
    tree_status=""
else
    tree_status="-dirty"
fi
set -e
echo "BUILD_SCM_STATUS ${tree_status}"
