module Opus::Types::Test::SealedModuleSandbox
  # Sometimes we need to ignore sealed class violations because they're for
  # benign purposes (like intermediate files generated by Stripe's autoloader
  # that don't add behavior, and match up existing real definitions elsewhere.)

  class SealedChildBadWhitelisted < SealedParent; end
end
