# There are two reasons we intentionally put everything we can on mac machine:
#  - our mac machine has 12 cores, while linux one has 4 cores.
#  - we use macs for development thus we want to make sure all scripts run there

steps:
  - label: "Release build: static on Mac"
    artifact_paths: _out_/**/*
    command: .buildkite/release-static.sh
    agents:
      os: mac
