# There are two reasons we intentionally put everything we can on mac machine:
#  - our mac machine has 12 cores, while linux one has 4 cores.
#  - we use macs for development thus we want to make sure all scripts run there

steps:
  - label: "Linters"
    command: .buildkite/linters.sh
    agents:
      os: linux
  - label: "Test: sorbet-static on Mac"
    command: .buildkite/test-static-sanitized.sh
    artifact_paths: _out_/**/*
    agents:
      os: mac
  - label: "Test: sorbet-static on Linux"
    command: .buildkite/test-static-sanitized.sh
    artifact_paths: _out_/**/*
    agents:
      os: linux
  - label: "Website"
    command: .buildkite/build-website.sh
    artifact_paths: _out_/**/*
    agents:
      os: mac
  - label: "Test: sorbet-runtime"
    command: .buildkite/test-and-build-ruby-runtime.sh
    artifact_paths: _out_/**/*
    agents:
      os: mac
  - wait: ~
  - label: "Release build: static on Mac"
    artifact_paths: _out_/**/*
    command: .buildkite/release-static.sh
    agents:
      os: mac
  - label: "Release build: static on WebAsm"
    command: .buildkite/build-emscripten.sh
    artifact_paths: _out_/**/*
    agents:
      os: mac
  - label: "Release build: static on Linux"
    artifact_paths: _out_/**/*
    command: .buildkite/release-static.sh
    agents:
      os: linux
  - wait: ~
  - label: "All tests and builds succeeded"
    command: .buildkite/all-succeeded.sh
  - label: "Deploy"
    command: .buildkite/publish.sh
    agents:
      os: linux
  - wait: ~
  - block: "Run optional code coverage"
  - wait: ~
  - label: "Coverage: sorbet-static on Mac"
    command: .buildkite/coverage-static-sanitized.sh
    artifact_paths: _out_/**/*
    retry:
      automatic: true
    agents:
      os: mac
