# We define MissesInstanceMethods here, since this test case specifically 
# targets pre_cache_modules in GemGeneratorTracepoint::Tracer, which enumerates
# ObjectSpace before any gems or user code are loaded, but *after* the Gemfile 
# has been evaluated for the first time (via FetchRBIs).

class MissesInstanceMethods
  def self.instance_methods(*args)
    raise "You need to use Sorbet::Private::RealStdlib here"
  end
  
  def self.private_instance_methods(*args)
    raise "You need to use Sorbet::Private::RealStdlib here"
  end
end