digraph "blocks.rb" {
subgraph "cluster_::<Class:<root>>#<static-init>" {
    label = "::<Class:<root>>#<static-init>";
    color = blue;
    "bb::<Class:<root>>#<static-init>_0" [shape = invhouse];
    "bb::<Class:<root>>#<static-init>_1" [shape = parallelogram];

    "bb::<Class:<root>>#<static-init>_0" [
        label = "block[id=0, rubyBlockId=0]()\l<self>: T.class_of(<root>) = cast(<self>: NilClass, AppliedType {\l  klass = <S <C <U <root>>> $1>\l  targs = [\l    <C <U <AttachedClass>>> = SelfTypeParam(<S <C <U <root>>> $1><C <U <AttachedClass>>>)\l  ]\l});\l<statTemp>$5: T.class_of(Sorbet::Private::Static) = alias <C Static>\l<statTemp>$6: T.class_of(BlockTest) = alias <C BlockTest>\l<statTemp>$4: Sorbet::Private::Static::Void = <statTemp>$5: T.class_of(Sorbet::Private::Static).keep_for_ide(<statTemp>$6: T.class_of(BlockTest))\l<finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass\l<unconditional>\l"
    ];

    "bb::<Class:<root>>#<static-init>_0" -> "bb::<Class:<root>>#<static-init>_1" [style="bold"];
    "bb::<Class:<root>>#<static-init>_1" [
        label = "block[id=1, rubyBlockId=0]()\l<unconditional>\l"
    ];

    "bb::<Class:<root>>#<static-init>_1" -> "bb::<Class:<root>>#<static-init>_1" [style="bold"];
}

subgraph "cluster_::BlockTest#blockPass" {
    label = "::BlockTest#blockPass";
    color = blue;
    "bb::BlockTest#blockPass_0" [shape = invhouse];
    "bb::BlockTest#blockPass_1" [shape = parallelogram];

    "bb::BlockTest#blockPass_0" [
        label = "block[id=0, rubyBlockId=0]()\l<self>: BlockTest = cast(<self>: NilClass, BlockTest);\l<statTemp>$4: Integer(1) = 1\l<statTemp>$5: Integer(2) = 2\l<statTemp>$6: Integer(3) = 3\l<block-pre-call-temp>$7: Sorbet::Private::Static::Void = <self>: BlockTest.foo(<statTemp>$4: Integer(1), <statTemp>$5: Integer(2), <statTemp>$6: Integer(3))\l<selfRestore>$8: BlockTest = <self>\l<unconditional>\l"
    ];

    "bb::BlockTest#blockPass_0" -> "bb::BlockTest#blockPass_2" [style="bold"];
    "bb::BlockTest#blockPass_1" [
        label = "block[id=1, rubyBlockId=0]()\l<unconditional>\l"
    ];

    "bb::BlockTest#blockPass_1" -> "bb::BlockTest#blockPass_1" [style="bold"];
    "bb::BlockTest#blockPass_2" [
        label = "block[id=2, rubyBlockId=1](<self>: BlockTest, <selfRestore>$8: BlockTest, <block-pre-call-temp>$7: Sorbet::Private::Static::Void)\louterLoops: 1\l<block-call>: NilClass\l"
    ];

    "bb::BlockTest#blockPass_2" -> "bb::BlockTest#blockPass_5" [style="bold"];
    "bb::BlockTest#blockPass_2" -> "bb::BlockTest#blockPass_3" [style="tapered"];

    "bb::BlockTest#blockPass_3" [
        label = "block[id=3, rubyBlockId=0](<selfRestore>$8: BlockTest, <block-pre-call-temp>$7: Sorbet::Private::Static::Void)\l<returnMethodTemp>$2: T.untyped = Solve<<block-pre-call-temp>$7, foo>\l<finalReturn>: T.noreturn = return <returnMethodTemp>$2: T.untyped\l<unconditional>\l"
    ];

    "bb::BlockTest#blockPass_3" -> "bb::BlockTest#blockPass_1" [style="bold"];
    "bb::BlockTest#blockPass_5" [
        label = "block[id=5, rubyBlockId=1](<self>: BlockTest, <selfRestore>$8: BlockTest, <block-pre-call-temp>$7: Sorbet::Private::Static::Void)\louterLoops: 1\l<self>: BlockTest = loadSelf\l<blk>$9: T.untyped = load_yield_params(foo)\l<blk>$10: Integer(0) = 0\lx$1: T.untyped = <blk>$9: T.untyped.[](<blk>$10: Integer(0))\l<blk>$10: Integer(1) = 1\ly$1: T.untyped = <blk>$9: T.untyped.[](<blk>$10: Integer(1))\l<blockReturnTemp>$11: T.untyped = x$1\l<blockReturnTemp>$12: T.noreturn = blockreturn<foo> <blockReturnTemp>$11: T.untyped\l<unconditional>\l"
    ];

    "bb::BlockTest#blockPass_5" -> "bb::BlockTest#blockPass_2" [style="bold"];
}

subgraph "cluster_::<Class:BlockTest>#<static-init>" {
    label = "::<Class:BlockTest>#<static-init>";
    color = blue;
    "bb::<Class:BlockTest>#<static-init>_0" [shape = invhouse];
    "bb::<Class:BlockTest>#<static-init>_1" [shape = parallelogram];

    "bb::<Class:BlockTest>#<static-init>_0" [
        label = "block[id=0, rubyBlockId=0]()\l<self>: T.class_of(BlockTest) = cast(<self>: NilClass, AppliedType {\l  klass = <S <C <U BlockTest>> $1>\l  targs = [\l    <C <U <AttachedClass>>> = SelfTypeParam(<S <C <U BlockTest>> $1><C <U <AttachedClass>>>)\l  ]\l});\l<returnMethodTemp>$2: Symbol(:\"blockPass\") = :\"blockPass\"\l<finalReturn>: T.noreturn = return <returnMethodTemp>$2: Symbol(:\"blockPass\")\l<unconditional>\l"
    ];

    "bb::<Class:BlockTest>#<static-init>_0" -> "bb::<Class:BlockTest>#<static-init>_1" [style="bold"];
    "bb::<Class:BlockTest>#<static-init>_1" [
        label = "block[id=1, rubyBlockId=0]()\l<unconditional>\l"
    ];

    "bb::<Class:BlockTest>#<static-init>_1" -> "bb::<Class:BlockTest>#<static-init>_1" [style="bold"];
}

}

