digraph "blocks.rb"{
subgraph "cluster_::BlockTest#block_pass" {
    label = "::BlockTest#block_pass";
    color = blue;
    bb24_0 [shape = invhouse];
    bb24_1 [shape = parallelogram];

    bb24_0 [label = "(statTmp$2, statTmp$3, statTmp$4, statTmp$5)\nstatTmp$2 = self : BlockTest\nstatTmp$3 = 1 : Integer(1)\nstatTmp$4 = 2 : Integer(2)\nstatTmp$5 = 3 : Integer(3)\n<unconditinal>"];
    bb24_0 -> bb24_2;
    bb24_1 [label = "()\n<unconditinal>"];
    bb24_1 -> bb24_1;
    bb24_2 [label = "(statTmp$2, statTmp$3, statTmp$4, statTmp$5)\nouterLoops: 1\n<block-call>"];
    bb24_2 -> bb24_4;
    bb24_2 -> bb24_3;

    bb24_3 [label = "(statTmp$2, statTmp$3, statTmp$4, statTmp$5)\n<ret>$2 = statTmp$2.foo(statTmp$3, statTmp$4, statTmp$5) : <dynamic>\n<ret>$7 = return <ret>$2 : <bottom>\n<unconditinal>"];
    bb24_3 -> bb24_1;
    bb24_4 [label = "(statTmp$2, statTmp$3, statTmp$4, statTmp$5)\nouterLoops: 1\nx$1 = load_arg(statTmp$2#foo, 0) : <dynamic>\n<unconditinal>"];
    bb24_4 -> bb24_2;
}

}

