digraph "next.rb"{
subgraph "cluster_::Object#foo" {
    label = "::Object#foo";
    color = blue;
    bb23_0 [shape = invhouse];
    bb23_1 [shape = parallelogram];

    bb23_0 [label = "(statTmp$2)\nstatTmp$2 = NotSupported() : untyped\n<unconditional>"];
    bb23_0 -> bb23_2;
    bb23_1 [label = "()\nstatTmp$10 = self\n<blockret>$3 = statTmp$10.bad()\n<unconditional>"];
    bb23_1 -> bb23_1;
    bb23_2 [label = "(statTmp$2)\nouterLoops: 1\n<block-call>"];
    bb23_2 -> bb23_4;
    bb23_2 -> bb23_3;

    bb23_3 [label = "(statTmp$2)\n<ret>$1 = statTmp$2.map() : untyped\n<ret>$11 = return <ret>$1 : <bottom>\n<unconditional>"];
    bb23_3 -> bb23_1;
    bb23_4 [label = "(statTmp$2)\nouterLoops: 1\nstatTmp$5 = self : Object\nstatTmp$4 = statTmp$5.good() : untyped\nstatTmp$8 = NotSupported() : untyped\nstatTmp$9 = 1 : Integer(1)\nreturnTmp$7 = statTmp$8.+(statTmp$9) : untyped\n<unconditional>"];
    bb23_4 -> bb23_2;
}

}

