digraph "rescue_complex.rb" {
subgraph "cluster_::TestRescue#meth" {
    label = "::TestRescue#meth";
    color = blue;
    "bb::TestRescue#meth_0" [shape = invhouse];
    "bb::TestRescue#meth_1" [shape = parallelogram];

    "bb::TestRescue#meth_0" [
        label = "block[id=0]()\l<returnMethodTemp>$2 = 0 : Integer(0)\l<finalReturn> = return <returnMethodTemp>$2 : <impossible>\l<unconditional>\l"
    ];

    "bb::TestRescue#meth_0" -> "bb::TestRescue#meth_1" [style="bold"];
    "bb::TestRescue#meth_1" [
        label = "block[id=1]()\l<unconditional>\l"
    ];

    "bb::TestRescue#meth_1" -> "bb::TestRescue#meth_1" [style="bold"];
}

subgraph "cluster_::TestRescue#foo" {
    label = "::TestRescue#foo";
    color = blue;
    "bb::TestRescue#foo_0" [shape = invhouse];
    "bb::TestRescue#foo_1" [shape = parallelogram];

    "bb::TestRescue#foo_0" [
        label = "block[id=0]()\l<returnMethodTemp>$2 = 1 : Integer(1)\l<finalReturn> = return <returnMethodTemp>$2 : <impossible>\l<unconditional>\l"
    ];

    "bb::TestRescue#foo_0" -> "bb::TestRescue#foo_1" [style="bold"];
    "bb::TestRescue#foo_1" [
        label = "block[id=1]()\l<unconditional>\l"
    ];

    "bb::TestRescue#foo_1" -> "bb::TestRescue#foo_1" [style="bold"];
}

subgraph "cluster_::TestRescue#bar" {
    label = "::TestRescue#bar";
    color = blue;
    "bb::TestRescue#bar_0" [shape = invhouse];
    "bb::TestRescue#bar_1" [shape = parallelogram];

    "bb::TestRescue#bar_0" [
        label = "block[id=0]()\l<returnMethodTemp>$2 = 2 : Integer(2)\l<finalReturn> = return <returnMethodTemp>$2 : <impossible>\l<unconditional>\l"
    ];

    "bb::TestRescue#bar_0" -> "bb::TestRescue#bar_1" [style="bold"];
    "bb::TestRescue#bar_1" [
        label = "block[id=1]()\l<unconditional>\l"
    ];

    "bb::TestRescue#bar_1" -> "bb::TestRescue#bar_1" [style="bold"];
}

subgraph "cluster_::TestRescue#baz" {
    label = "::TestRescue#baz";
    color = blue;
    "bb::TestRescue#baz_0" [shape = invhouse];
    "bb::TestRescue#baz_1" [shape = parallelogram];

    "bb::TestRescue#baz_0" [
        label = "block[id=0]()\l<returnMethodTemp>$2 = 3 : Integer(3)\l<finalReturn> = return <returnMethodTemp>$2 : <impossible>\l<unconditional>\l"
    ];

    "bb::TestRescue#baz_0" -> "bb::TestRescue#baz_1" [style="bold"];
    "bb::TestRescue#baz_1" [
        label = "block[id=1]()\l<unconditional>\l"
    ];

    "bb::TestRescue#baz_1" -> "bb::TestRescue#baz_1" [style="bold"];
}

subgraph "cluster_::TestRescue#take_arg" {
    label = "::TestRescue#take_arg";
    color = blue;
    "bb::TestRescue#take_arg_0" [shape = invhouse];
    "bb::TestRescue#take_arg_1" [shape = parallelogram];

    "bb::TestRescue#take_arg_0" [
        label = "block[id=0]()\l<selfMethodTemp>$3 = self : TestRescue\lx = load_arg(<selfMethodTemp>$3#take_arg, 0) : untyped\l<finalReturn> = return x : <impossible>\l<unconditional>\l"
    ];

    "bb::TestRescue#take_arg_0" -> "bb::TestRescue#take_arg_1" [style="bold"];
    "bb::TestRescue#take_arg_1" [
        label = "block[id=1]()\l<unconditional>\l"
    ];

    "bb::TestRescue#take_arg_1" -> "bb::TestRescue#take_arg_1" [style="bold"];
}

subgraph "cluster_::TestRescue#initialize" {
    label = "::TestRescue#initialize";
    color = blue;
    "bb::TestRescue#initialize_0" [shape = invhouse];
    "bb::TestRescue#initialize_1" [shape = parallelogram];

    "bb::TestRescue#initialize_0" [
        label = "block[id=0]()\l@ex$4 = alias @ex : StandardError | NilClass\l<castTemp$5 = nil : NilClass\l@ex$4 = cast(<castTemp$5, StandardError | NilClass); : StandardError | NilClass\l<finalReturn> = return @ex$4 : <impossible>\l<unconditional>\l"
    ];

    "bb::TestRescue#initialize_0" -> "bb::TestRescue#initialize_1" [style="bold"];
    "bb::TestRescue#initialize_1" [
        label = "block[id=1]()\l<unconditional>\l"
    ];

    "bb::TestRescue#initialize_1" -> "bb::TestRescue#initialize_1" [style="bold"];
}

subgraph "cluster_::TestRescue#multiple_rescue" {
    label = "::TestRescue#multiple_rescue";
    color = blue;
    "bb::TestRescue#multiple_rescue_0" [shape = invhouse];
    "bb::TestRescue#multiple_rescue_1" [shape = parallelogram];

    "bb::TestRescue#multiple_rescue_0" [
        label = "block[id=0]()\l<constant:StandardError>$8 = alias <constant:StandardError> : <Class:StandardError>\l<rescueTemp$4 = <unanalyzable> : untyped\l<rescueTemp$4\l"
    ];

    "bb::TestRescue#multiple_rescue_0" -> "bb::TestRescue#multiple_rescue_3" [style="bold"];
    "bb::TestRescue#multiple_rescue_0" -> "bb::TestRescue#multiple_rescue_4" [style="tapered"];

    "bb::TestRescue#multiple_rescue_1" [
        label = "block[id=1]()\l<unconditional>\l"
    ];

    "bb::TestRescue#multiple_rescue_1" -> "bb::TestRescue#multiple_rescue_1" [style="bold"];
    "bb::TestRescue#multiple_rescue_3" [
        label = "block[id=3](<rescueTemp$4, <constant:StandardError>$8)\l<rescueTemp$9 = <rescueTemp$4.is_a?(<constant:StandardError>$8) : untyped\l<rescueTemp$9\l"
    ];

    "bb::TestRescue#multiple_rescue_3" -> "bb::TestRescue#multiple_rescue_8" [style="bold"];
    "bb::TestRescue#multiple_rescue_3" -> "bb::TestRescue#multiple_rescue_9" [style="tapered"];

    "bb::TestRescue#multiple_rescue_4" [
        label = "block[id=4]()\l<statTemp>$5 = self : TestRescue\l<returnMethodTemp>$2 = <statTemp>$5.meth() : untyped\l<unconditional>\l"
    ];

    "bb::TestRescue#multiple_rescue_4" -> "bb::TestRescue#multiple_rescue_7" [style="bold"];
    "bb::TestRescue#multiple_rescue_7" [
        label = "block[id=7](<returnMethodTemp>$2)\l<finalReturn> = return <returnMethodTemp>$2 : <impossible>\l<unconditional>\l"
    ];

    "bb::TestRescue#multiple_rescue_7" -> "bb::TestRescue#multiple_rescue_1" [style="bold"];
    "bb::TestRescue#multiple_rescue_8" [
        label = "block[id=8](<rescueTemp$4)\l<statTemp>$10 = self : TestRescue\l<returnMethodTemp>$2 = <statTemp>$10.baz() : untyped\l<unconditional>\l"
    ];

    "bb::TestRescue#multiple_rescue_8" -> "bb::TestRescue#multiple_rescue_7" [style="bold"];
    "bb::TestRescue#multiple_rescue_9" [
        label = "block[id=9](<rescueTemp$4, <constant:StandardError>$8)\l<rescueTemp$12 = <rescueTemp$4.is_a?(<constant:StandardError>$8) : untyped\l<rescueTemp$12\l"
    ];

    "bb::TestRescue#multiple_rescue_9" -> "bb::TestRescue#multiple_rescue_10" [style="bold"];
    "bb::TestRescue#multiple_rescue_9" -> "bb::TestRescue#multiple_rescue_1" [style="tapered"];

    "bb::TestRescue#multiple_rescue_10" [
        label = "block[id=10](<rescueTemp$4)\l<statTemp>$13 = self : TestRescue\l<returnMethodTemp>$2 = <statTemp>$13.bar() : untyped\l<unconditional>\l"
    ];

    "bb::TestRescue#multiple_rescue_10" -> "bb::TestRescue#multiple_rescue_7" [style="bold"];
}

subgraph "cluster_::TestRescue#multiple_rescue_classes" {
    label = "::TestRescue#multiple_rescue_classes";
    color = blue;
    "bb::TestRescue#multiple_rescue_classes_0" [shape = invhouse];
    "bb::TestRescue#multiple_rescue_classes_1" [shape = parallelogram];

    "bb::TestRescue#multiple_rescue_classes_0" [
        label = "block[id=0]()\l<constant:Foo>$8 = alias <constant:Foo> : untyped\l<constant:Bar>$11 = alias <constant:Bar> : untyped\l<rescueTemp$4 = <unanalyzable> : untyped\l<rescueTemp$4\l"
    ];

    "bb::TestRescue#multiple_rescue_classes_0" -> "bb::TestRescue#multiple_rescue_classes_3" [style="bold"];
    "bb::TestRescue#multiple_rescue_classes_0" -> "bb::TestRescue#multiple_rescue_classes_4" [style="tapered"];

    "bb::TestRescue#multiple_rescue_classes_1" [
        label = "block[id=1]()\l<unconditional>\l"
    ];

    "bb::TestRescue#multiple_rescue_classes_1" -> "bb::TestRescue#multiple_rescue_classes_1" [style="bold"];
    "bb::TestRescue#multiple_rescue_classes_3" [
        label = "block[id=3](<rescueTemp$4, <constant:Foo>$8, <constant:Bar>$11)\l<rescueTemp$9 = <rescueTemp$4.is_a?(<constant:Foo>$8) : untyped\l<rescueTemp$9\l"
    ];

    "bb::TestRescue#multiple_rescue_classes_3" -> "bb::TestRescue#multiple_rescue_classes_8" [style="bold"];
    "bb::TestRescue#multiple_rescue_classes_3" -> "bb::TestRescue#multiple_rescue_classes_9" [style="tapered"];

    "bb::TestRescue#multiple_rescue_classes_4" [
        label = "block[id=4]()\l<statTemp>$5 = self : TestRescue\l<returnMethodTemp>$2 = <statTemp>$5.meth() : untyped\l<unconditional>\l"
    ];

    "bb::TestRescue#multiple_rescue_classes_4" -> "bb::TestRescue#multiple_rescue_classes_7" [style="bold"];
    "bb::TestRescue#multiple_rescue_classes_7" [
        label = "block[id=7](<returnMethodTemp>$2)\l<finalReturn> = return <returnMethodTemp>$2 : <impossible>\l<unconditional>\l"
    ];

    "bb::TestRescue#multiple_rescue_classes_7" -> "bb::TestRescue#multiple_rescue_classes_1" [style="bold"];
    "bb::TestRescue#multiple_rescue_classes_8" [
        label = "block[id=8](<rescueTemp$4)\lbaz = <rescueTemp$4 : untyped\l<returnMethodTemp>$2 = baz : untyped\l<unconditional>\l"
    ];

    "bb::TestRescue#multiple_rescue_classes_8" -> "bb::TestRescue#multiple_rescue_classes_7" [style="bold"];
    "bb::TestRescue#multiple_rescue_classes_9" [
        label = "block[id=9](<rescueTemp$4, <constant:Bar>$11)\l<rescueTemp$12 = <rescueTemp$4.is_a?(<constant:Bar>$11) : untyped\l<rescueTemp$12\l"
    ];

    "bb::TestRescue#multiple_rescue_classes_9" -> "bb::TestRescue#multiple_rescue_classes_8" [style="bold"];
    "bb::TestRescue#multiple_rescue_classes_9" -> "bb::TestRescue#multiple_rescue_classes_1" [style="tapered"];

}

subgraph "cluster_::TestRescue#parse_rescue_ensure" {
    label = "::TestRescue#parse_rescue_ensure";
    color = blue;
    "bb::TestRescue#parse_rescue_ensure_0" [shape = invhouse];
    "bb::TestRescue#parse_rescue_ensure_1" [shape = parallelogram];

    "bb::TestRescue#parse_rescue_ensure_0" [
        label = "block[id=0]()\l<constant:StandardError>$9 = alias <constant:StandardError> : <Class:StandardError>\l<rescueTemp$4 = <unanalyzable> : untyped\l<rescueTemp$4\l"
    ];

    "bb::TestRescue#parse_rescue_ensure_0" -> "bb::TestRescue#parse_rescue_ensure_3" [style="bold"];
    "bb::TestRescue#parse_rescue_ensure_0" -> "bb::TestRescue#parse_rescue_ensure_4" [style="tapered"];

    "bb::TestRescue#parse_rescue_ensure_1" [
        label = "block[id=1]()\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_rescue_ensure_1" -> "bb::TestRescue#parse_rescue_ensure_1" [style="bold"];
    "bb::TestRescue#parse_rescue_ensure_3" [
        label = "block[id=3](<rescueTemp$4, <constant:StandardError>$9)\l<rescueTemp$10 = <rescueTemp$4.is_a?(<constant:StandardError>$9) : untyped\l<rescueTemp$10\l"
    ];

    "bb::TestRescue#parse_rescue_ensure_3" -> "bb::TestRescue#parse_rescue_ensure_8" [style="bold"];
    "bb::TestRescue#parse_rescue_ensure_3" -> "bb::TestRescue#parse_rescue_ensure_1" [style="tapered"];

    "bb::TestRescue#parse_rescue_ensure_4" [
        label = "block[id=4]()\l<statTemp>$5 = self : TestRescue\l<returnMethodTemp>$2 = <statTemp>$5.meth() : untyped\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_rescue_ensure_4" -> "bb::TestRescue#parse_rescue_ensure_6" [style="bold"];
    "bb::TestRescue#parse_rescue_ensure_6" [
        label = "block[id=6](<returnMethodTemp>$2)\l<statTemp>$7 = self : TestRescue\l<rescueTemp$6 = <statTemp>$7.bar() : untyped\l<finalReturn> = return <returnMethodTemp>$2 : <impossible>\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_rescue_ensure_6" -> "bb::TestRescue#parse_rescue_ensure_1" [style="bold"];
    "bb::TestRescue#parse_rescue_ensure_8" [
        label = "block[id=8](<rescueTemp$4)\l<statTemp>$11 = self : TestRescue\l<returnMethodTemp>$2 = <statTemp>$11.baz() : untyped\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_rescue_ensure_8" -> "bb::TestRescue#parse_rescue_ensure_6" [style="bold"];
}

subgraph "cluster_::TestRescue#parse_bug_rescue_empty_else" {
    label = "::TestRescue#parse_bug_rescue_empty_else";
    color = blue;
    "bb::TestRescue#parse_bug_rescue_empty_else_0" [shape = invhouse];
    "bb::TestRescue#parse_bug_rescue_empty_else_1" [shape = parallelogram];

    "bb::TestRescue#parse_bug_rescue_empty_else_0" [
        label = "block[id=0]()\l<constant:LoadError>$7 = alias <constant:LoadError> : <Class:LoadError>\l<rescueTemp$4 = <unanalyzable> : untyped\l<rescueTemp$4\l"
    ];

    "bb::TestRescue#parse_bug_rescue_empty_else_0" -> "bb::TestRescue#parse_bug_rescue_empty_else_3" [style="bold"];
    "bb::TestRescue#parse_bug_rescue_empty_else_0" -> "bb::TestRescue#parse_bug_rescue_empty_else_7" [style="tapered"];

    "bb::TestRescue#parse_bug_rescue_empty_else_1" [
        label = "block[id=1]()\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_bug_rescue_empty_else_1" -> "bb::TestRescue#parse_bug_rescue_empty_else_1" [style="bold"];
    "bb::TestRescue#parse_bug_rescue_empty_else_3" [
        label = "block[id=3](<rescueTemp$4, <constant:LoadError>$7)\l<rescueTemp$8 = <rescueTemp$4.is_a?(<constant:LoadError>$7) : untyped\l<rescueTemp$8\l"
    ];

    "bb::TestRescue#parse_bug_rescue_empty_else_3" -> "bb::TestRescue#parse_bug_rescue_empty_else_7" [style="bold"];
    "bb::TestRescue#parse_bug_rescue_empty_else_3" -> "bb::TestRescue#parse_bug_rescue_empty_else_1" [style="tapered"];

    "bb::TestRescue#parse_bug_rescue_empty_else_7" [
        label = "block[id=7]()\l<finalReturn> = return <returnMethodTemp>$2 : <impossible>\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_bug_rescue_empty_else_7" -> "bb::TestRescue#parse_bug_rescue_empty_else_1" [style="bold"];
}

subgraph "cluster_::TestRescue#parse_ruby_bug_12686" {
    label = "::TestRescue#parse_ruby_bug_12686";
    color = blue;
    "bb::TestRescue#parse_ruby_bug_12686_0" [shape = invhouse];
    "bb::TestRescue#parse_ruby_bug_12686_1" [shape = parallelogram];

    "bb::TestRescue#parse_ruby_bug_12686_0" [
        label = "block[id=0]()\l<constant:StandardError>$10 = alias <constant:StandardError> : <Class:StandardError>\l<statTemp>$4 = self : TestRescue\l<rescueTemp$6 = <unanalyzable> : untyped\l<rescueTemp$6\l"
    ];

    "bb::TestRescue#parse_ruby_bug_12686_0" -> "bb::TestRescue#parse_ruby_bug_12686_3" [style="bold"];
    "bb::TestRescue#parse_ruby_bug_12686_0" -> "bb::TestRescue#parse_ruby_bug_12686_4" [style="tapered"];

    "bb::TestRescue#parse_ruby_bug_12686_1" [
        label = "block[id=1]()\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_ruby_bug_12686_1" -> "bb::TestRescue#parse_ruby_bug_12686_1" [style="bold"];
    "bb::TestRescue#parse_ruby_bug_12686_3" [
        label = "block[id=3](<statTemp>$4, <rescueTemp$6, <constant:StandardError>$10)\l<rescueTemp$11 = <rescueTemp$6.is_a?(<constant:StandardError>$10) : untyped\l<rescueTemp$11\l"
    ];

    "bb::TestRescue#parse_ruby_bug_12686_3" -> "bb::TestRescue#parse_ruby_bug_12686_8" [style="bold"];
    "bb::TestRescue#parse_ruby_bug_12686_3" -> "bb::TestRescue#parse_ruby_bug_12686_1" [style="tapered"];

    "bb::TestRescue#parse_ruby_bug_12686_4" [
        label = "block[id=4](<statTemp>$4)\l<statTemp>$7 = self : TestRescue\l<statTemp>$5 = <statTemp>$7.bar() : untyped\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_ruby_bug_12686_4" -> "bb::TestRescue#parse_ruby_bug_12686_7" [style="bold"];
    "bb::TestRescue#parse_ruby_bug_12686_7" [
        label = "block[id=7](<statTemp>$4, <statTemp>$5)\l<returnMethodTemp>$2 = <statTemp>$4.take_arg(<statTemp>$5) : untyped\l<finalReturn> = return <returnMethodTemp>$2 : <impossible>\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_ruby_bug_12686_7" -> "bb::TestRescue#parse_ruby_bug_12686_1" [style="bold"];
    "bb::TestRescue#parse_ruby_bug_12686_8" [
        label = "block[id=8](<statTemp>$4, <rescueTemp$6)\l<statTemp>$5 = nil : NilClass\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_ruby_bug_12686_8" -> "bb::TestRescue#parse_ruby_bug_12686_7" [style="bold"];
}

subgraph "cluster_::TestRescue#parse_rescue_mod" {
    label = "::TestRescue#parse_rescue_mod";
    color = blue;
    "bb::TestRescue#parse_rescue_mod_0" [shape = invhouse];
    "bb::TestRescue#parse_rescue_mod_1" [shape = parallelogram];

    "bb::TestRescue#parse_rescue_mod_0" [
        label = "block[id=0]()\l<constant:StandardError>$8 = alias <constant:StandardError> : <Class:StandardError>\l<rescueTemp$4 = <unanalyzable> : untyped\l<rescueTemp$4\l"
    ];

    "bb::TestRescue#parse_rescue_mod_0" -> "bb::TestRescue#parse_rescue_mod_3" [style="bold"];
    "bb::TestRescue#parse_rescue_mod_0" -> "bb::TestRescue#parse_rescue_mod_4" [style="tapered"];

    "bb::TestRescue#parse_rescue_mod_1" [
        label = "block[id=1]()\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_rescue_mod_1" -> "bb::TestRescue#parse_rescue_mod_1" [style="bold"];
    "bb::TestRescue#parse_rescue_mod_3" [
        label = "block[id=3](<rescueTemp$4, <constant:StandardError>$8)\l<rescueTemp$9 = <rescueTemp$4.is_a?(<constant:StandardError>$8) : untyped\l<rescueTemp$9\l"
    ];

    "bb::TestRescue#parse_rescue_mod_3" -> "bb::TestRescue#parse_rescue_mod_8" [style="bold"];
    "bb::TestRescue#parse_rescue_mod_3" -> "bb::TestRescue#parse_rescue_mod_1" [style="tapered"];

    "bb::TestRescue#parse_rescue_mod_4" [
        label = "block[id=4]()\l<statTemp>$5 = self : TestRescue\l<returnMethodTemp>$2 = <statTemp>$5.meth() : untyped\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_rescue_mod_4" -> "bb::TestRescue#parse_rescue_mod_7" [style="bold"];
    "bb::TestRescue#parse_rescue_mod_7" [
        label = "block[id=7](<returnMethodTemp>$2)\l<finalReturn> = return <returnMethodTemp>$2 : <impossible>\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_rescue_mod_7" -> "bb::TestRescue#parse_rescue_mod_1" [style="bold"];
    "bb::TestRescue#parse_rescue_mod_8" [
        label = "block[id=8](<rescueTemp$4)\l<statTemp>$10 = self : TestRescue\l<returnMethodTemp>$2 = <statTemp>$10.bar() : untyped\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_rescue_mod_8" -> "bb::TestRescue#parse_rescue_mod_7" [style="bold"];
}

subgraph "cluster_::TestRescue#parse_resbody_list_var" {
    label = "::TestRescue#parse_resbody_list_var";
    color = blue;
    "bb::TestRescue#parse_resbody_list_var_0" [shape = invhouse];
    "bb::TestRescue#parse_resbody_list_var_1" [shape = parallelogram];

    "bb::TestRescue#parse_resbody_list_var_0" [
        label = "block[id=0]()\l<rescueTemp$4 = <unanalyzable> : untyped\l<rescueTemp$4\l"
    ];

    "bb::TestRescue#parse_resbody_list_var_0" -> "bb::TestRescue#parse_resbody_list_var_3" [style="bold"];
    "bb::TestRescue#parse_resbody_list_var_0" -> "bb::TestRescue#parse_resbody_list_var_4" [style="tapered"];

    "bb::TestRescue#parse_resbody_list_var_1" [
        label = "block[id=1]()\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_resbody_list_var_1" -> "bb::TestRescue#parse_resbody_list_var_1" [style="bold"];
    "bb::TestRescue#parse_resbody_list_var_3" [
        label = "block[id=3](<rescueTemp$4)\l<statTemp>$8 = self : TestRescue\l<rescueTemp$7 = <statTemp>$8.foo() : untyped\l<rescueTemp$9 = <rescueTemp$4.is_a?(<rescueTemp$7) : untyped\l<rescueTemp$9\l"
    ];

    "bb::TestRescue#parse_resbody_list_var_3" -> "bb::TestRescue#parse_resbody_list_var_8" [style="bold"];
    "bb::TestRescue#parse_resbody_list_var_3" -> "bb::TestRescue#parse_resbody_list_var_1" [style="tapered"];

    "bb::TestRescue#parse_resbody_list_var_4" [
        label = "block[id=4]()\l<statTemp>$5 = self : TestRescue\l<returnMethodTemp>$2 = <statTemp>$5.meth() : untyped\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_resbody_list_var_4" -> "bb::TestRescue#parse_resbody_list_var_7" [style="bold"];
    "bb::TestRescue#parse_resbody_list_var_7" [
        label = "block[id=7](<returnMethodTemp>$2)\l<finalReturn> = return <returnMethodTemp>$2 : <impossible>\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_resbody_list_var_7" -> "bb::TestRescue#parse_resbody_list_var_1" [style="bold"];
    "bb::TestRescue#parse_resbody_list_var_8" [
        label = "block[id=8](<rescueTemp$4)\l<statTemp>$10 = self : TestRescue\l<returnMethodTemp>$2 = <statTemp>$10.bar() : untyped\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_resbody_list_var_8" -> "bb::TestRescue#parse_resbody_list_var_7" [style="bold"];
}

subgraph "cluster_::TestRescue#parse_rescue_else_ensure" {
    label = "::TestRescue#parse_rescue_else_ensure";
    color = blue;
    "bb::TestRescue#parse_rescue_else_ensure_0" [shape = invhouse];
    "bb::TestRescue#parse_rescue_else_ensure_1" [shape = parallelogram];

    "bb::TestRescue#parse_rescue_else_ensure_0" [
        label = "block[id=0]()\l<constant:StandardError>$10 = alias <constant:StandardError> : <Class:StandardError>\l<rescueTemp$4 = <unanalyzable> : untyped\l<rescueTemp$4\l"
    ];

    "bb::TestRescue#parse_rescue_else_ensure_0" -> "bb::TestRescue#parse_rescue_else_ensure_3" [style="bold"];
    "bb::TestRescue#parse_rescue_else_ensure_0" -> "bb::TestRescue#parse_rescue_else_ensure_4" [style="tapered"];

    "bb::TestRescue#parse_rescue_else_ensure_1" [
        label = "block[id=1]()\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_rescue_else_ensure_1" -> "bb::TestRescue#parse_rescue_else_ensure_1" [style="bold"];
    "bb::TestRescue#parse_rescue_else_ensure_3" [
        label = "block[id=3](<rescueTemp$4, <constant:StandardError>$10)\l<rescueTemp$11 = <rescueTemp$4.is_a?(<constant:StandardError>$10) : untyped\l<rescueTemp$11\l"
    ];

    "bb::TestRescue#parse_rescue_else_ensure_3" -> "bb::TestRescue#parse_rescue_else_ensure_8" [style="bold"];
    "bb::TestRescue#parse_rescue_else_ensure_3" -> "bb::TestRescue#parse_rescue_else_ensure_1" [style="tapered"];

    "bb::TestRescue#parse_rescue_else_ensure_4" [
        label = "block[id=4]()\l<statTemp>$5 = self : TestRescue\l<returnMethodTemp>$2 = <statTemp>$5.meth() : untyped\l<statTemp>$6 = self : TestRescue\l<returnMethodTemp>$2 = <statTemp>$6.foo() : untyped\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_rescue_else_ensure_4" -> "bb::TestRescue#parse_rescue_else_ensure_6" [style="bold"];
    "bb::TestRescue#parse_rescue_else_ensure_6" [
        label = "block[id=6](<returnMethodTemp>$2)\l<statTemp>$8 = self : TestRescue\l<rescueTemp$7 = <statTemp>$8.bar() : untyped\l<finalReturn> = return <returnMethodTemp>$2 : <impossible>\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_rescue_else_ensure_6" -> "bb::TestRescue#parse_rescue_else_ensure_1" [style="bold"];
    "bb::TestRescue#parse_rescue_else_ensure_8" [
        label = "block[id=8](<rescueTemp$4)\l<statTemp>$12 = self : TestRescue\l<returnMethodTemp>$2 = <statTemp>$12.baz() : untyped\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_rescue_else_ensure_8" -> "bb::TestRescue#parse_rescue_else_ensure_6" [style="bold"];
}

subgraph "cluster_::TestRescue#parse_rescue" {
    label = "::TestRescue#parse_rescue";
    color = blue;
    "bb::TestRescue#parse_rescue_0" [shape = invhouse];
    "bb::TestRescue#parse_rescue_1" [shape = parallelogram];

    "bb::TestRescue#parse_rescue_0" [
        label = "block[id=0]()\l<constant:StandardError>$8 = alias <constant:StandardError> : <Class:StandardError>\l<rescueTemp$4 = <unanalyzable> : untyped\l<rescueTemp$4\l"
    ];

    "bb::TestRescue#parse_rescue_0" -> "bb::TestRescue#parse_rescue_3" [style="bold"];
    "bb::TestRescue#parse_rescue_0" -> "bb::TestRescue#parse_rescue_4" [style="tapered"];

    "bb::TestRescue#parse_rescue_1" [
        label = "block[id=1]()\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_rescue_1" -> "bb::TestRescue#parse_rescue_1" [style="bold"];
    "bb::TestRescue#parse_rescue_3" [
        label = "block[id=3](<rescueTemp$4, <constant:StandardError>$8)\l<rescueTemp$9 = <rescueTemp$4.is_a?(<constant:StandardError>$8) : untyped\l<rescueTemp$9\l"
    ];

    "bb::TestRescue#parse_rescue_3" -> "bb::TestRescue#parse_rescue_8" [style="bold"];
    "bb::TestRescue#parse_rescue_3" -> "bb::TestRescue#parse_rescue_1" [style="tapered"];

    "bb::TestRescue#parse_rescue_4" [
        label = "block[id=4]()\l<statTemp>$5 = self : TestRescue\l<returnMethodTemp>$2 = <statTemp>$5.meth() : untyped\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_rescue_4" -> "bb::TestRescue#parse_rescue_7" [style="bold"];
    "bb::TestRescue#parse_rescue_7" [
        label = "block[id=7](<returnMethodTemp>$2)\l<finalReturn> = return <returnMethodTemp>$2 : <impossible>\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_rescue_7" -> "bb::TestRescue#parse_rescue_1" [style="bold"];
    "bb::TestRescue#parse_rescue_8" [
        label = "block[id=8](<rescueTemp$4)\l<statTemp>$10 = self : TestRescue\l<returnMethodTemp>$2 = <statTemp>$10.foo() : untyped\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_rescue_8" -> "bb::TestRescue#parse_rescue_7" [style="bold"];
}

subgraph "cluster_::TestRescue#parse_resbody_var" {
    label = "::TestRescue#parse_resbody_var";
    color = blue;
    "bb::TestRescue#parse_resbody_var_0" [shape = invhouse];
    "bb::TestRescue#parse_resbody_var_1" [shape = parallelogram];

    "bb::TestRescue#parse_resbody_var_0" [
        label = "block[id=0]()\l<constant:StandardError>$8 = alias <constant:StandardError> : <Class:StandardError>\l<rescueTemp$4 = <unanalyzable> : untyped\l<rescueTemp$4\l"
    ];

    "bb::TestRescue#parse_resbody_var_0" -> "bb::TestRescue#parse_resbody_var_3" [style="bold"];
    "bb::TestRescue#parse_resbody_var_0" -> "bb::TestRescue#parse_resbody_var_4" [style="tapered"];

    "bb::TestRescue#parse_resbody_var_1" [
        label = "block[id=1]()\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_resbody_var_1" -> "bb::TestRescue#parse_resbody_var_1" [style="bold"];
    "bb::TestRescue#parse_resbody_var_3" [
        label = "block[id=3](<rescueTemp$4, <constant:StandardError>$8)\l<rescueTemp$9 = <rescueTemp$4.is_a?(<constant:StandardError>$8) : untyped\l<rescueTemp$9\l"
    ];

    "bb::TestRescue#parse_resbody_var_3" -> "bb::TestRescue#parse_resbody_var_8" [style="bold"];
    "bb::TestRescue#parse_resbody_var_3" -> "bb::TestRescue#parse_resbody_var_1" [style="tapered"];

    "bb::TestRescue#parse_resbody_var_4" [
        label = "block[id=4]()\l<statTemp>$5 = self : TestRescue\l<returnMethodTemp>$2 = <statTemp>$5.meth() : untyped\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_resbody_var_4" -> "bb::TestRescue#parse_resbody_var_7" [style="bold"];
    "bb::TestRescue#parse_resbody_var_7" [
        label = "block[id=7](<returnMethodTemp>$2)\l<finalReturn> = return <returnMethodTemp>$2 : <impossible>\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_resbody_var_7" -> "bb::TestRescue#parse_resbody_var_1" [style="bold"];
    "bb::TestRescue#parse_resbody_var_8" [
        label = "block[id=8](<rescueTemp$4)\l<statTemp>$10 = self : TestRescue\l<returnMethodTemp>$2 = <statTemp>$10.bar() : untyped\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_resbody_var_8" -> "bb::TestRescue#parse_resbody_var_7" [style="bold"];
}

subgraph "cluster_::TestRescue#parse_resbody_var_1" {
    label = "::TestRescue#parse_resbody_var_1";
    color = blue;
    "bb::TestRescue#parse_resbody_var_1_0" [shape = invhouse];
    "bb::TestRescue#parse_resbody_var_1_1" [shape = parallelogram];

    "bb::TestRescue#parse_resbody_var_1_0" [
        label = "block[id=0]()\l<constant:StandardError>$8 = alias <constant:StandardError> : <Class:StandardError>\l@ex$11 = alias @ex : StandardError | NilClass\l<rescueTemp$4 = <unanalyzable> : untyped\l<rescueTemp$4\l"
    ];

    "bb::TestRescue#parse_resbody_var_1_0" -> "bb::TestRescue#parse_resbody_var_1_3" [style="bold"];
    "bb::TestRescue#parse_resbody_var_1_0" -> "bb::TestRescue#parse_resbody_var_1_4" [style="tapered"];

    "bb::TestRescue#parse_resbody_var_1_1" [
        label = "block[id=1]()\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_resbody_var_1_1" -> "bb::TestRescue#parse_resbody_var_1_1" [style="bold"];
    "bb::TestRescue#parse_resbody_var_1_3" [
        label = "block[id=3](<rescueTemp$4, <constant:StandardError>$8, @ex$11)\l<rescueTemp$9 = <rescueTemp$4.is_a?(<constant:StandardError>$8) : untyped\l<rescueTemp$9\l"
    ];

    "bb::TestRescue#parse_resbody_var_1_3" -> "bb::TestRescue#parse_resbody_var_1_8" [style="bold"];
    "bb::TestRescue#parse_resbody_var_1_3" -> "bb::TestRescue#parse_resbody_var_1_1" [style="tapered"];

    "bb::TestRescue#parse_resbody_var_1_4" [
        label = "block[id=4]()\l<statTemp>$5 = self : TestRescue\l<returnMethodTemp>$2 = <statTemp>$5.meth() : untyped\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_resbody_var_1_4" -> "bb::TestRescue#parse_resbody_var_1_7" [style="bold"];
    "bb::TestRescue#parse_resbody_var_1_7" [
        label = "block[id=7](<returnMethodTemp>$2)\l<finalReturn> = return <returnMethodTemp>$2 : <impossible>\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_resbody_var_1_7" -> "bb::TestRescue#parse_resbody_var_1_1" [style="bold"];
    "bb::TestRescue#parse_resbody_var_1_8" [
        label = "block[id=8](<rescueTemp$4, @ex$11)\l@ex$11 = <rescueTemp$4 : StandardError\l<statTemp>$12 = self : TestRescue\l<returnMethodTemp>$2 = <statTemp>$12.bar() : untyped\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_resbody_var_1_8" -> "bb::TestRescue#parse_resbody_var_1_7" [style="bold"];
}

subgraph "cluster_::TestRescue#parse_rescue_mod_op_assign" {
    label = "::TestRescue#parse_rescue_mod_op_assign";
    color = blue;
    "bb::TestRescue#parse_rescue_mod_op_assign_0" [shape = invhouse];
    "bb::TestRescue#parse_rescue_mod_op_assign_1" [shape = parallelogram];

    "bb::TestRescue#parse_rescue_mod_op_assign_0" [
        label = "block[id=0]()\l<constant:StandardError>$10 = alias <constant:StandardError> : <Class:StandardError>\l<statTemp>$4 = foo : NilClass\l<rescueTemp$6 = <unanalyzable> : untyped\l<rescueTemp$6\l"
    ];

    "bb::TestRescue#parse_rescue_mod_op_assign_0" -> "bb::TestRescue#parse_rescue_mod_op_assign_3" [style="bold"];
    "bb::TestRescue#parse_rescue_mod_op_assign_0" -> "bb::TestRescue#parse_rescue_mod_op_assign_4" [style="tapered"];

    "bb::TestRescue#parse_rescue_mod_op_assign_1" [
        label = "block[id=1]()\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_rescue_mod_op_assign_1" -> "bb::TestRescue#parse_rescue_mod_op_assign_1" [style="bold"];
    "bb::TestRescue#parse_rescue_mod_op_assign_3" [
        label = "block[id=3](<statTemp>$4, <rescueTemp$6, <constant:StandardError>$10)\l<rescueTemp$11 = <rescueTemp$6.is_a?(<constant:StandardError>$10) : untyped\l<rescueTemp$11\l"
    ];

    "bb::TestRescue#parse_rescue_mod_op_assign_3" -> "bb::TestRescue#parse_rescue_mod_op_assign_8" [style="bold"];
    "bb::TestRescue#parse_rescue_mod_op_assign_3" -> "bb::TestRescue#parse_rescue_mod_op_assign_1" [style="tapered"];

    "bb::TestRescue#parse_rescue_mod_op_assign_4" [
        label = "block[id=4](<statTemp>$4)\l<statTemp>$7 = self : TestRescue\l<statTemp>$5 = <statTemp>$7.meth() : untyped\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_rescue_mod_op_assign_4" -> "bb::TestRescue#parse_rescue_mod_op_assign_7" [style="bold"];
    "bb::TestRescue#parse_rescue_mod_op_assign_7" [
        label = "block[id=7](<statTemp>$4, <statTemp>$5)\lfoo = <statTemp>$4.+(<statTemp>$5) : untyped\l<finalReturn> = return foo : <impossible>\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_rescue_mod_op_assign_7" -> "bb::TestRescue#parse_rescue_mod_op_assign_1" [style="bold"];
    "bb::TestRescue#parse_rescue_mod_op_assign_8" [
        label = "block[id=8](<statTemp>$4, <rescueTemp$6)\l<statTemp>$12 = self : TestRescue\l<statTemp>$5 = <statTemp>$12.bar() : untyped\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_rescue_mod_op_assign_8" -> "bb::TestRescue#parse_rescue_mod_op_assign_7" [style="bold"];
}

subgraph "cluster_::TestRescue#parse_ruby_bug_12402" {
    label = "::TestRescue#parse_ruby_bug_12402";
    color = blue;
    "bb::TestRescue#parse_ruby_bug_12402_0" [shape = invhouse];
    "bb::TestRescue#parse_ruby_bug_12402_1" [shape = parallelogram];

    "bb::TestRescue#parse_ruby_bug_12402_0" [
        label = "block[id=0]()\l<constant:StandardError>$10 = alias <constant:StandardError> : <Class:StandardError>\l<rescueTemp$4 = <unanalyzable> : untyped\l<rescueTemp$4\l"
    ];

    "bb::TestRescue#parse_ruby_bug_12402_0" -> "bb::TestRescue#parse_ruby_bug_12402_3" [style="bold"];
    "bb::TestRescue#parse_ruby_bug_12402_0" -> "bb::TestRescue#parse_ruby_bug_12402_4" [style="tapered"];

    "bb::TestRescue#parse_ruby_bug_12402_1" [
        label = "block[id=1]()\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_ruby_bug_12402_1" -> "bb::TestRescue#parse_ruby_bug_12402_1" [style="bold"];
    "bb::TestRescue#parse_ruby_bug_12402_3" [
        label = "block[id=3](<rescueTemp$4, <constant:StandardError>$10)\l<rescueTemp$11 = <rescueTemp$4.is_a?(<constant:StandardError>$10) : untyped\l<rescueTemp$11\l"
    ];

    "bb::TestRescue#parse_ruby_bug_12402_3" -> "bb::TestRescue#parse_ruby_bug_12402_8" [style="bold"];
    "bb::TestRescue#parse_ruby_bug_12402_3" -> "bb::TestRescue#parse_ruby_bug_12402_1" [style="tapered"];

    "bb::TestRescue#parse_ruby_bug_12402_4" [
        label = "block[id=4]()\l<statTemp>$5 = self : TestRescue\l<statTemp>$7 = self : TestRescue\l<statTemp>$6 = <statTemp>$7.bar() : untyped\lfoo = <statTemp>$5.raise(<statTemp>$6) : <impossible>\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_ruby_bug_12402_4" -> "bb::TestRescue#parse_ruby_bug_12402_7" [style="bold"];
    "bb::TestRescue#parse_ruby_bug_12402_7" [
        label = "block[id=7](foo)\l<finalReturn> = return foo : <impossible>\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_ruby_bug_12402_7" -> "bb::TestRescue#parse_ruby_bug_12402_1" [style="bold"];
    "bb::TestRescue#parse_ruby_bug_12402_8" [
        label = "block[id=8](<rescueTemp$4)\lfoo = nil : NilClass\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_ruby_bug_12402_8" -> "bb::TestRescue#parse_ruby_bug_12402_7" [style="bold"];
}

subgraph "cluster_::TestRescue#parse_ruby_bug_12402_1" {
    label = "::TestRescue#parse_ruby_bug_12402_1";
    color = blue;
    "bb::TestRescue#parse_ruby_bug_12402_1_0" [shape = invhouse];
    "bb::TestRescue#parse_ruby_bug_12402_1_1" [shape = parallelogram];

    "bb::TestRescue#parse_ruby_bug_12402_1_0" [
        label = "block[id=0]()\l<constant:StandardError>$12 = alias <constant:StandardError> : <Class:StandardError>\l<statTemp>$4 = foo : NilClass\l<rescueTemp$6 = <unanalyzable> : untyped\l<rescueTemp$6\l"
    ];

    "bb::TestRescue#parse_ruby_bug_12402_1_0" -> "bb::TestRescue#parse_ruby_bug_12402_1_3" [style="bold"];
    "bb::TestRescue#parse_ruby_bug_12402_1_0" -> "bb::TestRescue#parse_ruby_bug_12402_1_4" [style="tapered"];

    "bb::TestRescue#parse_ruby_bug_12402_1_1" [
        label = "block[id=1]()\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_ruby_bug_12402_1_1" -> "bb::TestRescue#parse_ruby_bug_12402_1_1" [style="bold"];
    "bb::TestRescue#parse_ruby_bug_12402_1_3" [
        label = "block[id=3](<statTemp>$4, <rescueTemp$6, <constant:StandardError>$12)\l<rescueTemp$13 = <rescueTemp$6.is_a?(<constant:StandardError>$12) : untyped\l<rescueTemp$13\l"
    ];

    "bb::TestRescue#parse_ruby_bug_12402_1_3" -> "bb::TestRescue#parse_ruby_bug_12402_1_8" [style="bold"];
    "bb::TestRescue#parse_ruby_bug_12402_1_3" -> "bb::TestRescue#parse_ruby_bug_12402_1_1" [style="tapered"];

    "bb::TestRescue#parse_ruby_bug_12402_1_4" [
        label = "block[id=4](<statTemp>$4)\l<statTemp>$7 = self : TestRescue\l<statTemp>$9 = self : TestRescue\l<statTemp>$8 = <statTemp>$9.bar() : untyped\l<statTemp>$5 = <statTemp>$7.raise(<statTemp>$8) : <impossible>\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_ruby_bug_12402_1_4" -> "bb::TestRescue#parse_ruby_bug_12402_1_7" [style="bold"];
    "bb::TestRescue#parse_ruby_bug_12402_1_7" [
        label = "block[id=7](<statTemp>$4, <statTemp>$5)\lfoo = <statTemp>$4.+(<statTemp>$5) : untyped\l<finalReturn> = return foo : <impossible>\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_ruby_bug_12402_1_7" -> "bb::TestRescue#parse_ruby_bug_12402_1_1" [style="bold"];
    "bb::TestRescue#parse_ruby_bug_12402_1_8" [
        label = "block[id=8](<statTemp>$4, <rescueTemp$6)\l<statTemp>$5 = nil : NilClass\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_ruby_bug_12402_1_8" -> "bb::TestRescue#parse_ruby_bug_12402_1_7" [style="bold"];
}

subgraph "cluster_::TestRescue#parse_ruby_bug_12402_2" {
    label = "::TestRescue#parse_ruby_bug_12402_2";
    color = blue;
    "bb::TestRescue#parse_ruby_bug_12402_2_0" [shape = invhouse];
    "bb::TestRescue#parse_ruby_bug_12402_2_1" [shape = parallelogram];

    "bb::TestRescue#parse_ruby_bug_12402_2_0" [
        label = "block[id=0]()\l<constant:StandardError>$20 = alias <constant:StandardError> : <Class:StandardError>\l<statTemp>$5 = self : TestRescue\l[]$3 = <statTemp>$5.foo() : untyped\l[]$4 = 0 : Integer(0)\l<statTemp>$10 = []$3.[]([]$4) : untyped\l<rescueTemp$14 = <unanalyzable> : untyped\l<rescueTemp$14\l"
    ];

    "bb::TestRescue#parse_ruby_bug_12402_2_0" -> "bb::TestRescue#parse_ruby_bug_12402_2_3" [style="bold"];
    "bb::TestRescue#parse_ruby_bug_12402_2_0" -> "bb::TestRescue#parse_ruby_bug_12402_2_4" [style="tapered"];

    "bb::TestRescue#parse_ruby_bug_12402_2_1" [
        label = "block[id=1]()\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_ruby_bug_12402_2_1" -> "bb::TestRescue#parse_ruby_bug_12402_2_1" [style="bold"];
    "bb::TestRescue#parse_ruby_bug_12402_2_3" [
        label = "block[id=3](<statTemp>$10, <rescueTemp$14, <constant:StandardError>$20, []$3, []$4)\l<rescueTemp$21 = <rescueTemp$14.is_a?(<constant:StandardError>$20) : untyped\l<rescueTemp$21\l"
    ];

    "bb::TestRescue#parse_ruby_bug_12402_2_3" -> "bb::TestRescue#parse_ruby_bug_12402_2_8" [style="bold"];
    "bb::TestRescue#parse_ruby_bug_12402_2_3" -> "bb::TestRescue#parse_ruby_bug_12402_2_1" [style="tapered"];

    "bb::TestRescue#parse_ruby_bug_12402_2_4" [
        label = "block[id=4](<statTemp>$10, []$3, []$4)\l<statTemp>$15 = self : TestRescue\l<statTemp>$17 = self : TestRescue\l<statTemp>$16 = <statTemp>$17.bar() : untyped\l<statTemp>$13 = <statTemp>$15.raise(<statTemp>$16) : <impossible>\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_ruby_bug_12402_2_4" -> "bb::TestRescue#parse_ruby_bug_12402_2_7" [style="bold"];
    "bb::TestRescue#parse_ruby_bug_12402_2_7" [
        label = "block[id=7](<statTemp>$10, <statTemp>$13, []$3, []$4)\l<statTemp>$9 = <statTemp>$10.+(<statTemp>$13) : untyped\l<returnMethodTemp>$2 = []$3.[]=([]$4, <statTemp>$9) : untyped\l<finalReturn> = return <returnMethodTemp>$2 : <impossible>\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_ruby_bug_12402_2_7" -> "bb::TestRescue#parse_ruby_bug_12402_2_1" [style="bold"];
    "bb::TestRescue#parse_ruby_bug_12402_2_8" [
        label = "block[id=8](<statTemp>$10, <rescueTemp$14, []$3, []$4)\l<statTemp>$13 = nil : NilClass\l<unconditional>\l"
    ];

    "bb::TestRescue#parse_ruby_bug_12402_2_8" -> "bb::TestRescue#parse_ruby_bug_12402_2_7" [style="bold"];
}

}

