method ::<Class:<root>>#<static-init> {

bb0[firstDead=3]():
    <self>: T.class_of(<root>) = cast(<self>: NilClass, T.class_of(<root>));
    <returnMethodTemp>$2: Symbol(:a) = :a
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: Symbol(:a)
    <unconditional> -> bb1

# backedges
# - bb0
bb1[firstDead=-1]():
    <unconditional> -> bb1

}

method ::Object#a {

bb0[firstDead=-1]():
    <self>: Object = cast(<self>: NilClass, Object);
    <exceptionValue>$3: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$3 -> (T.nilable(Exception) ? bb3 : bb4)

# backedges
# - bb4
# - bb6
# - bb9
bb1[firstDead=-1]():
    <exceptionValue>$3 = <get-current-exception>
    <unconditional> -> bb1

# backedges
# - bb0
bb3[firstDead=-1](<exceptionValue>$3: Exception):
    # rubyRegionId: 2
    <cfgAlias>$7: T.class_of(StandardError) = alias <C StandardError>
    <isaCheckTemp>$8: T::Boolean = <cfgAlias>$7: T.class_of(StandardError).===(<exceptionValue>$3: Exception)
    <isaCheckTemp>$8 -> (T::Boolean ? bb7 : bb8)

# backedges
# - bb0
bb4[firstDead=2]():
    # rubyRegionId: 1
    <returnTemp>$4: Integer(1) = 1
    <returnMethodTemp>$2: T.noreturn = return <returnTemp>$4: Integer(1)
    <unconditional> -> bb1

# backedges
# - bb7
# - bb8
bb6[firstDead=-1](<gotoDeadTemp>$9: T.nilable(TrueClass)):
    # rubyRegionId: 3
    <gotoDeadTemp>$9 -> (T.nilable(TrueClass) ? bb1 : bb9)

# backedges
# - bb3
bb7[firstDead=-1](<exceptionValue>$3: StandardError):
    # rubyRegionId: 2
    <exceptionValue>$3: NilClass = nil
    <keepForCfgTemp>$5: T.untyped = <keep-alive> <exceptionValue>$3
    <unconditional> -> bb6

# backedges
# - bb3
bb8[firstDead=-1]():
    <gotoDeadTemp>$9: TrueClass = true
    <unconditional> -> bb6

# backedges
# - bb6
bb9[firstDead=1]():
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

}

