method ::<Class:<root>>#<static-init> {

bb0[firstDead=2]():
    <self>: T.class_of(<root>) = cast(<self>: NilClass, T.class_of(<root>));
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb0
bb1[firstDead=-1]():
    <unconditional> -> bb1

}

method ::<Class:TestRescue>#<static-init> {

bb0[firstDead=-1]():
    <self>: T.class_of(TestRescue) = cast(<self>: NilClass, T.class_of(TestRescue));
    <block-pre-call-temp>$5: Sorbet::Private::Static::Void = <self>: T.class_of(TestRescue).sig()
    <selfRestore>$6: T.class_of(TestRescue) = <self>
    <unconditional> -> bb2

# backedges
# - bb7
bb1[firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0
# - bb5
bb2[firstDead=-1](<self>: T.class_of(TestRescue), <block-pre-call-temp>$5: Sorbet::Private::Static::Void, <selfRestore>$6: T.class_of(TestRescue)):
    # outerLoops: 1
    <block-call> -> (NilClass ? bb5 : bb3)

# backedges
# - bb2
bb3[firstDead=-1](<block-pre-call-temp>$5: Sorbet::Private::Static::Void, <selfRestore>$6: T.class_of(TestRescue)):
    <statTemp>$3: Sorbet::Private::Static::Void = Solve<<block-pre-call-temp>$5, sig>
    <self>: T.class_of(TestRescue) = <selfRestore>$6
    <block-pre-call-temp>$22: Sorbet::Private::Static::Void = <self>: T.class_of(TestRescue).sig()
    <selfRestore>$23: T.class_of(TestRescue) = <self>
    <unconditional> -> bb6

# backedges
# - bb2
bb5[firstDead=9](<self>: T.class_of(TestRescue), <block-pre-call-temp>$5: Sorbet::Private::Static::Void, <selfRestore>$6: T.class_of(TestRescue)):
    # outerLoops: 1
    <self>: T::Private::Methods::DeclBuilder = loadSelf(sig)
    <cfgAlias>$11: T.class_of(T::Array) = alias <C Array>
    <cfgAlias>$13: T.class_of(T) = alias <C T>
    <cfgAlias>$16: T.class_of(T) = alias <C T>
    <cfgAlias>$18: T.class_of(Exception) = alias <C Exception>
    <statTemp>$14: Runtime object representing type: T.class_of(Exception) = <cfgAlias>$16: T.class_of(T).class_of(<cfgAlias>$18: T.class_of(Exception))
    <statTemp>$9: Runtime object representing type: T::Array[T.class_of(Exception)] = <cfgAlias>$11: T.class_of(T::Array).[](<statTemp>$14: Runtime object representing type: T.class_of(Exception))
    <blockReturnTemp>$7: T::Private::Methods::DeclBuilder = <self>: T::Private::Methods::DeclBuilder.returns(<statTemp>$9: Runtime object representing type: T::Array[T.class_of(Exception)])
    <blockReturnTemp>$19: T.noreturn = blockreturn<sig> <blockReturnTemp>$7: T::Private::Methods::DeclBuilder
    <unconditional> -> bb2

# backedges
# - bb3
# - bb9
bb6[firstDead=-1](<self>: T.class_of(TestRescue), <block-pre-call-temp>$22: Sorbet::Private::Static::Void, <selfRestore>$23: T.class_of(TestRescue)):
    # outerLoops: 1
    <block-call> -> (NilClass ? bb9 : bb7)

# backedges
# - bb6
bb7[firstDead=7](<block-pre-call-temp>$22: Sorbet::Private::Static::Void, <selfRestore>$23: T.class_of(TestRescue)):
    <statTemp>$20: Sorbet::Private::Static::Void = Solve<<block-pre-call-temp>$22, sig>
    <self>: T.class_of(TestRescue) = <selfRestore>$23
    <cfgAlias>$42: T.class_of(T::Sig) = alias <C Sig>
    <cfgAlias>$44: T.class_of(T) = alias <C T>
    <statTemp>$39: T.class_of(TestRescue) = <self>: T.class_of(TestRescue).extend(<cfgAlias>$42: T.class_of(T::Sig))
    <returnMethodTemp>$2: Symbol(:parse_ruby_bug_12402_2) = :parse_ruby_bug_12402_2
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: Symbol(:parse_ruby_bug_12402_2)
    <unconditional> -> bb1

# backedges
# - bb6
bb9[firstDead=11](<self>: T.class_of(TestRescue), <block-pre-call-temp>$22: Sorbet::Private::Static::Void, <selfRestore>$23: T.class_of(TestRescue)):
    # outerLoops: 1
    <self>: T::Private::Methods::DeclBuilder = loadSelf(sig)
    <cfgAlias>$30: T.class_of(T) = alias <C T>
    <cfgAlias>$32: T.class_of(TypeError) = alias <C TypeError>
    <arrayTemp>$28: Runtime object representing type: T.class_of(TypeError) = <cfgAlias>$30: T.class_of(T).class_of(<cfgAlias>$32: T.class_of(TypeError))
    <cfgAlias>$35: T.class_of(T) = alias <C T>
    <cfgAlias>$37: T.class_of(ArgumentError) = alias <C ArgumentError>
    <arrayTemp>$33: Runtime object representing type: T.class_of(ArgumentError) = <cfgAlias>$35: T.class_of(T).class_of(<cfgAlias>$37: T.class_of(ArgumentError))
    <magic>$27: T.class_of(<Magic>) = alias <C <Magic>>
    <statTemp>$26: [Runtime object representing type: T.class_of(TypeError), Runtime object representing type: T.class_of(ArgumentError)] = <magic>$27: T.class_of(<Magic>).<build-array>(<arrayTemp>$28: Runtime object representing type: T.class_of(TypeError), <arrayTemp>$33: Runtime object representing type: T.class_of(ArgumentError))
    <blockReturnTemp>$24: T::Private::Methods::DeclBuilder = <self>: T::Private::Methods::DeclBuilder.returns(<statTemp>$26: [Runtime object representing type: T.class_of(TypeError), Runtime object representing type: T.class_of(ArgumentError)])
    <blockReturnTemp>$38: T.noreturn = blockreturn<sig> <blockReturnTemp>$24: T::Private::Methods::DeclBuilder
    <unconditional> -> bb6

}

method ::TestRescue#meth {

bb0[firstDead=3]():
    <self>: TestRescue = cast(<self>: NilClass, TestRescue);
    <returnMethodTemp>$2: Integer(0) = 0
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: Integer(0)
    <unconditional> -> bb1

# backedges
# - bb0
bb1[firstDead=-1]():
    <unconditional> -> bb1

}

method ::TestRescue#foo {

bb0[firstDead=3]():
    <self>: TestRescue = cast(<self>: NilClass, TestRescue);
    <returnMethodTemp>$2: Integer(1) = 1
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: Integer(1)
    <unconditional> -> bb1

# backedges
# - bb0
bb1[firstDead=-1]():
    <unconditional> -> bb1

}

method ::TestRescue#bar {

bb0[firstDead=3]():
    <self>: TestRescue = cast(<self>: NilClass, TestRescue);
    <returnMethodTemp>$2: Integer(2) = 2
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: Integer(2)
    <unconditional> -> bb1

# backedges
# - bb0
bb1[firstDead=-1]():
    <unconditional> -> bb1

}

method ::TestRescue#baz {

bb0[firstDead=3]():
    <self>: TestRescue = cast(<self>: NilClass, TestRescue);
    <returnMethodTemp>$2: Integer(3) = 3
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: Integer(3)
    <unconditional> -> bb1

# backedges
# - bb0
bb1[firstDead=-1]():
    <unconditional> -> bb1

}

method ::TestRescue#take_arg {

bb0[firstDead=4]():
    <self>: TestRescue = cast(<self>: NilClass, TestRescue);
    x: T.untyped = load_arg(x)
    <returnMethodTemp>$2: T.untyped = x
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: T.untyped
    <unconditional> -> bb1

# backedges
# - bb0
bb1[firstDead=-1]():
    <unconditional> -> bb1

}

method ::TestRescue#untyped_exceptions {

bb0[firstDead=5]():
    <self>: TestRescue = cast(<self>: NilClass, TestRescue);
    <cfgAlias>$5: T.class_of(Exception) = alias <C Exception>
    <magic>$3: T.class_of(<Magic>) = alias <C <Magic>>
    <returnMethodTemp>$2: [T.class_of(Exception)] = <magic>$3: T.class_of(<Magic>).<build-array>(<cfgAlias>$5: T.class_of(Exception))
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: [T.class_of(Exception)]
    <unconditional> -> bb1

# backedges
# - bb0
bb1[firstDead=-1]():
    <unconditional> -> bb1

}

method ::TestRescue#typed_exceptions {

bb0[firstDead=5]():
    <self>: TestRescue = cast(<self>: NilClass, TestRescue);
    <cfgAlias>$5: T.class_of(Exception) = alias <C Exception>
    <magic>$3: T.class_of(<Magic>) = alias <C <Magic>>
    <returnMethodTemp>$2: [T.class_of(Exception)] = <magic>$3: T.class_of(<Magic>).<build-array>(<cfgAlias>$5: T.class_of(Exception))
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: [T.class_of(Exception)]
    <unconditional> -> bb1

# backedges
# - bb0
bb1[firstDead=-1]():
    <unconditional> -> bb1

}

method ::TestRescue#tuple_exceptions {

bb0[firstDead=6]():
    <self>: TestRescue = cast(<self>: NilClass, TestRescue);
    <cfgAlias>$5: T.class_of(TypeError) = alias <C TypeError>
    <cfgAlias>$7: T.class_of(ArgumentError) = alias <C ArgumentError>
    <magic>$3: T.class_of(<Magic>) = alias <C <Magic>>
    <returnMethodTemp>$2: [T.class_of(TypeError), T.class_of(ArgumentError)] = <magic>$3: T.class_of(<Magic>).<build-array>(<cfgAlias>$5: T.class_of(TypeError), <cfgAlias>$7: T.class_of(ArgumentError))
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: [T.class_of(TypeError), T.class_of(ArgumentError)]
    <unconditional> -> bb1

# backedges
# - bb0
bb1[firstDead=-1]():
    <unconditional> -> bb1

}

method ::TestRescue#initialize {

bb0[firstDead=10]():
    @ex$3: T.nilable(StandardError) = alias @ex
    <self>: TestRescue = cast(<self>: NilClass, TestRescue);
    <cfgAlias>$6: T.class_of(T) = alias <C T>
    <cfgAlias>$8: T.class_of(StandardError) = alias <C StandardError>
    keep_for_ide$4: Runtime object representing type: T.nilable(StandardError) = <cfgAlias>$6: T.class_of(T).nilable(<cfgAlias>$8: T.class_of(StandardError))
    keep_for_ide$4: T.untyped = <keep-alive> keep_for_ide$4
    <castTemp>$9: NilClass = nil
    @ex$3: T.nilable(StandardError) = cast(<castTemp>$9: NilClass, T.nilable(StandardError));
    <returnMethodTemp>$2: T.nilable(StandardError) = @ex$3
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: T.nilable(StandardError)
    <unconditional> -> bb1

# backedges
# - bb0
bb1[firstDead=-1]():
    <unconditional> -> bb1

}

method ::TestRescue#multiple_rescue {

bb0[firstDead=-1]():
    <self>: TestRescue = cast(<self>: NilClass, TestRescue);
    <exceptionValue>$3: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$3 -> (T.nilable(Exception) ? bb3 : bb4)

# backedges
# - bb6
# - bb7
# - bb9
# - bb10
# - bb11
bb1[firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0
# - bb4
bb3[firstDead=-1](<self>: TestRescue, <returnMethodTemp>$2: T.untyped, <exceptionValue>$3: Exception):
    <cfgAlias>$7: T.class_of(StandardError) = alias <C StandardError>
    <isaCheckTemp>$8: T::Boolean = <cfgAlias>$7: T.class_of(StandardError).===(<exceptionValue>$3: Exception)
    <isaCheckTemp>$8 -> (T::Boolean ? bb7 : bb8)

# backedges
# - bb0
bb4[firstDead=-1](<self>: TestRescue):
    <returnMethodTemp>$2: T.untyped = <self>: TestRescue.meth()
    <exceptionValue>$3: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$3 -> (T.nilable(Exception) ? bb3 : bb6)

# backedges
# - bb4
bb6[firstDead=-1](<returnMethodTemp>$2: T.untyped, <gotoDeadTemp>$15: NilClass):
    <gotoDeadTemp>$15 -> (NilClass ? bb1 : bb11)

# backedges
# - bb3
bb7[firstDead=-1](<self>: TestRescue, <exceptionValue>$3: StandardError):
    <exceptionValue>$3: NilClass = nil
    <keepForCfgTemp>$5: T.untyped = <keep-alive> <exceptionValue>$3
    <returnMethodTemp>$2: T.untyped = <self>: TestRescue.baz()
    <gotoDeadTemp>$15 -> (NilClass ? bb1 : bb11)

# backedges
# - bb3
bb8[firstDead=-1](<self>: TestRescue, <returnMethodTemp>$2: T.untyped, <exceptionValue>$3: Exception):
    <cfgAlias>$12: T.class_of(StandardError) = alias <C StandardError>
    <isaCheckTemp>$13: T::Boolean = <cfgAlias>$12: T.class_of(StandardError).===(<exceptionValue>$3: Exception)
    <isaCheckTemp>$13 -> (T::Boolean ? bb9 : bb10)

# backedges
# - bb8
bb9[firstDead=-1](<self>: TestRescue, <exceptionValue>$3: StandardError):
    <exceptionValue>$3: NilClass = nil
    <keepForCfgTemp>$10: T.untyped = <keep-alive> <exceptionValue>$3
    <returnMethodTemp>$2: T.untyped = <self>: TestRescue.bar()
    <gotoDeadTemp>$15 -> (NilClass ? bb1 : bb11)

# backedges
# - bb8
bb10[firstDead=-1](<returnMethodTemp>$2: T.untyped):
    <gotoDeadTemp>$15: TrueClass = true
    <gotoDeadTemp>$15 -> (TrueClass ? bb1 : bb11)

# backedges
# - bb6
# - bb7
# - bb9
# - bb10
bb11[firstDead=1](<returnMethodTemp>$2: T.untyped):
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: T.untyped
    <unconditional> -> bb1

}

method ::TestRescue#multiple_rescue_classes {

bb0[firstDead=-1]():
    <self>: TestRescue = cast(<self>: NilClass, TestRescue);
    <exceptionValue>$3: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$3 -> (T.nilable(Exception) ? bb3 : bb4)

# backedges
# - bb6
# - bb7
# - bb9
# - bb10
bb1[firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0
# - bb4
bb3[firstDead=-1](<returnMethodTemp>$2: T.untyped, <exceptionValue>$3: Exception):
    <cfgAlias>$7: T.untyped = alias <C T.untyped>
    <isaCheckTemp>$8: T.untyped = <cfgAlias>$7: T.untyped.===(<exceptionValue>$3: Exception)
    <isaCheckTemp>$8 -> (T.untyped ? bb7 : bb8)

# backedges
# - bb0
bb4[firstDead=-1](<self>: TestRescue):
    <returnMethodTemp>$2: T.untyped = <self>: TestRescue.meth()
    <exceptionValue>$3: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$3 -> (T.nilable(Exception) ? bb3 : bb6)

# backedges
# - bb4
bb6[firstDead=-1](<returnMethodTemp>$2: T.untyped, <gotoDeadTemp>$12: NilClass):
    <gotoDeadTemp>$12 -> (NilClass ? bb1 : bb10)

# backedges
# - bb3
# - bb8
bb7[firstDead=-1](<exceptionValue>$3: Exception):
    baz: Exception = <exceptionValue>$3
    <exceptionValue>$3: NilClass = nil
    <keepForCfgTemp>$5: T.untyped = <keep-alive> <exceptionValue>$3
    <returnMethodTemp>$2: Exception = baz
    <gotoDeadTemp>$12 -> (NilClass ? bb1 : bb10)

# backedges
# - bb3
bb8[firstDead=-1](<returnMethodTemp>$2: T.untyped, <exceptionValue>$3: Exception):
    <cfgAlias>$10: T.untyped = alias <C T.untyped>
    <isaCheckTemp>$11: T.untyped = <cfgAlias>$10: T.untyped.===(<exceptionValue>$3: Exception)
    <isaCheckTemp>$11 -> (T.untyped ? bb7 : bb9)

# backedges
# - bb8
bb9[firstDead=-1](<returnMethodTemp>$2: T.untyped):
    <gotoDeadTemp>$12: TrueClass = true
    <gotoDeadTemp>$12 -> (TrueClass ? bb1 : bb10)

# backedges
# - bb6
# - bb7
# - bb9
bb10[firstDead=1](<returnMethodTemp>$2: T.untyped):
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: T.untyped
    <unconditional> -> bb1

}

method ::TestRescue#multiple_rescue_classes_varuse {

bb0[firstDead=-1]():
    <self>: TestRescue = cast(<self>: NilClass, TestRescue);
    <exceptionValue>$4: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$4 -> (T.nilable(Exception) ? bb3 : bb4)

# backedges
# - bb6
# - bb7
# - bb9
# - bb10
bb1[firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0
# - bb4
bb3[firstDead=-1](<exceptionValue>$4: Exception):
    <cfgAlias>$8: T.class_of(LoadError) = alias <C LoadError>
    <isaCheckTemp>$9: T::Boolean = <cfgAlias>$8: T.class_of(LoadError).===(<exceptionValue>$4: Exception)
    <isaCheckTemp>$9 -> (T::Boolean ? bb7 : bb8)

# backedges
# - bb0
bb4[firstDead=-1](<self>: TestRescue):
    <statTemp>$3: T.untyped = <self>: TestRescue.meth()
    <exceptionValue>$4: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$4 -> (T.nilable(Exception) ? bb3 : bb6)

# backedges
# - bb4
bb6[firstDead=-1](baz: NilClass, <gotoDeadTemp>$13: NilClass):
    <gotoDeadTemp>$13 -> (NilClass ? bb1 : bb10)

# backedges
# - bb3
# - bb8
bb7[firstDead=-1](<exceptionValue>$4: T.any(LoadError, SocketError)):
    baz: T.any(LoadError, SocketError) = <exceptionValue>$4
    <exceptionValue>$4: NilClass = nil
    <keepForCfgTemp>$6: T.untyped = <keep-alive> <exceptionValue>$4
    <gotoDeadTemp>$13 -> (NilClass ? bb1 : bb10)

# backedges
# - bb3
bb8[firstDead=-1](<exceptionValue>$4: Exception):
    <cfgAlias>$11: T.class_of(SocketError) = alias <C SocketError>
    <isaCheckTemp>$12: T::Boolean = <cfgAlias>$11: T.class_of(SocketError).===(<exceptionValue>$4: Exception)
    <isaCheckTemp>$12 -> (T::Boolean ? bb7 : bb9)

# backedges
# - bb8
bb9[firstDead=-1]():
    <gotoDeadTemp>$13: TrueClass = true
    <gotoDeadTemp>$13 -> (TrueClass ? bb1 : bb10)

# backedges
# - bb6
# - bb7
# - bb9
bb10[firstDead=3](baz: T.nilable(T.any(LoadError, SocketError))):
    <cfgAlias>$16: T.class_of(T) = alias <C T>
    <returnMethodTemp>$2: T.nilable(T.any(LoadError, SocketError)) = <cfgAlias>$16: T.class_of(T).reveal_type(baz: T.nilable(T.any(LoadError, SocketError)))
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: T.nilable(T.any(LoadError, SocketError))
    <unconditional> -> bb1

}

method ::TestRescue#rescue_loop {

bb0[firstDead=-1]():
    <self>: TestRescue = cast(<self>: NilClass, TestRescue);
    <cfgAlias>$6: T.class_of(T) = alias <C T>
    <cfgAlias>$8: T.class_of(StandardError) = alias <C StandardError>
    keep_for_ide$4: Runtime object representing type: T.nilable(StandardError) = <cfgAlias>$6: T.class_of(T).nilable(<cfgAlias>$8: T.class_of(StandardError))
    keep_for_ide$4: T.untyped = <keep-alive> keep_for_ide$4
    <castTemp>$9: NilClass = nil
    ex: T.nilable(StandardError) = cast(<castTemp>$9: NilClass, T.nilable(StandardError));
    <block-pre-call-temp>$11: Sorbet::Private::Static::Void = <self>: TestRescue.loop()
    <selfRestore>$12: TestRescue = <self>
    <unconditional> -> bb2

# backedges
# - bb3
# - bb10
# - bb11
# - bb12
bb1[firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0
# - bb13
bb2[firstDead=-1](<self>: TestRescue, ex: T.nilable(StandardError), <block-pre-call-temp>$11: Sorbet::Private::Static::Void, <selfRestore>$12: TestRescue, <blockReturnTemp>$13: NilClass, <gotoDeadTemp>$21: NilClass):
    # outerLoops: 1
    <block-call> -> (NilClass ? bb5 : bb3)

# backedges
# - bb2
bb3[firstDead=1](<block-pre-call-temp>$11: Sorbet::Private::Static::Void, <selfRestore>$12: TestRescue):
    <returnMethodTemp>$2: T.noreturn = Solve<<block-pre-call-temp>$11, loop>
    <finalReturn> = return <returnMethodTemp>$2
    <unconditional> -> bb1

# backedges
# - bb2
bb5[firstDead=-1](<self>: TestRescue, ex: T.nilable(StandardError), <block-pre-call-temp>$11: Sorbet::Private::Static::Void, <selfRestore>$12: TestRescue, <blockReturnTemp>$13: NilClass, <gotoDeadTemp>$21: NilClass):
    # outerLoops: 1
    <self>: TestRescue = loadSelf(loop)
    ex: NilClass = nil
    <exceptionValue>$15: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$15 -> (T.nilable(Exception) ? bb7 : bb8)

# backedges
# - bb5
# - bb8
bb7[firstDead=-1](<self>: TestRescue, ex: NilClass, <block-pre-call-temp>$11: Sorbet::Private::Static::Void, <selfRestore>$12: TestRescue, <blockReturnTemp>$13: T.untyped, <exceptionValue>$15: Exception, <gotoDeadTemp>$21: NilClass):
    # outerLoops: 1
    <cfgAlias>$19: T.class_of(StandardError) = alias <C StandardError>
    <isaCheckTemp>$20: T::Boolean = <cfgAlias>$19: T.class_of(StandardError).===(<exceptionValue>$15: Exception)
    <isaCheckTemp>$20 -> (T::Boolean ? bb11 : bb12)

# backedges
# - bb5
bb8[firstDead=-1](<self>: TestRescue, ex: NilClass, <block-pre-call-temp>$11: Sorbet::Private::Static::Void, <selfRestore>$12: TestRescue, <gotoDeadTemp>$21: NilClass):
    # outerLoops: 1
    <blockReturnTemp>$13: T.untyped = <self>: TestRescue.meth()
    <exceptionValue>$15: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$15 -> (T.nilable(Exception) ? bb7 : bb10)

# backedges
# - bb8
bb10[firstDead=-1](<self>: TestRescue, ex: NilClass, <block-pre-call-temp>$11: Sorbet::Private::Static::Void, <selfRestore>$12: TestRescue, <blockReturnTemp>$13: T.untyped, <gotoDeadTemp>$21: NilClass):
    # outerLoops: 1
    <gotoDeadTemp>$21 -> (NilClass ? bb1 : bb13)

# backedges
# - bb7
bb11[firstDead=-1](<self>: TestRescue, ex: NilClass, <block-pre-call-temp>$11: Sorbet::Private::Static::Void, <selfRestore>$12: TestRescue, <blockReturnTemp>$13: T.untyped, <exceptionValue>$15: StandardError, <gotoDeadTemp>$21: NilClass):
    # outerLoops: 1
    ex: StandardError = <exceptionValue>$15
    <exceptionValue>$15: NilClass = nil
    <keepForCfgTemp>$17: T.untyped = <keep-alive> <exceptionValue>$15
    <gotoDeadTemp>$21 -> (NilClass ? bb1 : bb13)

# backedges
# - bb7
bb12[firstDead=-1](<self>: TestRescue, ex: NilClass, <block-pre-call-temp>$11: Sorbet::Private::Static::Void, <selfRestore>$12: TestRescue, <blockReturnTemp>$13: T.untyped):
    # outerLoops: 1
    <gotoDeadTemp>$21: TrueClass = true
    <gotoDeadTemp>$21 -> (TrueClass ? bb1 : bb13)

# backedges
# - bb10
# - bb11
# - bb12
bb13[firstDead=1](<self>: TestRescue, ex: T.nilable(StandardError), <block-pre-call-temp>$11: Sorbet::Private::Static::Void, <selfRestore>$12: TestRescue, <blockReturnTemp>$13: T.untyped, <gotoDeadTemp>$21: NilClass):
    # outerLoops: 1
    <blockReturnTemp>$23: T.noreturn = blockreturn<loop> <blockReturnTemp>$13: T.untyped
    <unconditional> -> bb2

}

method ::TestRescue#rescue_untyped_splat {

bb0[firstDead=-1]():
    <self>: TestRescue = cast(<self>: NilClass, TestRescue);
    <exceptionValue>$3: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$3 -> (T.nilable(Exception) ? bb3 : bb4)

# backedges
# - bb6
# - bb7
# - bb8
# - bb9
bb1[firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0
# - bb4
bb3[firstDead=-1](<self>: TestRescue, <returnMethodTemp>$2: T.untyped, <exceptionValue>$3: Exception):
    <cfgAlias>$8: T.class_of(<Magic>) = alias <C <Magic>>
    <statTemp>$9: T.untyped = <self>: TestRescue.untyped_exceptions()
    <exceptionClassTemp>$6: T.untyped = <cfgAlias>$8: T.class_of(<Magic>).<splat>(<statTemp>$9: T.untyped)
    <isaCheckTemp>$11: T.untyped = <exceptionClassTemp>$6: T.untyped.===(<exceptionValue>$3: Exception)
    <isaCheckTemp>$11 -> (T.untyped ? bb7 : bb8)

# backedges
# - bb0
bb4[firstDead=-1](<self>: TestRescue):
    <returnMethodTemp>$2: T.untyped = <self>: TestRescue.meth()
    <exceptionValue>$3: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$3 -> (T.nilable(Exception) ? bb3 : bb6)

# backedges
# - bb4
bb6[firstDead=-1](<returnMethodTemp>$2: T.untyped, <gotoDeadTemp>$15: NilClass):
    <gotoDeadTemp>$15 -> (NilClass ? bb1 : bb9)

# backedges
# - bb3
bb7[firstDead=-1](<exceptionValue>$3: Exception):
    e: Exception = <exceptionValue>$3
    <exceptionValue>$3: NilClass = nil
    <keepForCfgTemp>$5: T.untyped = <keep-alive> <exceptionValue>$3
    <cfgAlias>$13: T.class_of(T) = alias <C T>
    <returnMethodTemp>$2: Exception = <cfgAlias>$13: T.class_of(T).reveal_type(e: Exception)
    <gotoDeadTemp>$15 -> (NilClass ? bb1 : bb9)

# backedges
# - bb3
bb8[firstDead=-1](<returnMethodTemp>$2: T.untyped):
    <gotoDeadTemp>$15: TrueClass = true
    <gotoDeadTemp>$15 -> (TrueClass ? bb1 : bb9)

# backedges
# - bb6
# - bb7
# - bb8
bb9[firstDead=1](<returnMethodTemp>$2: T.untyped):
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: T.untyped
    <unconditional> -> bb1

}

method ::TestRescue#rescue_typed_splat {

bb0[firstDead=-1]():
    <self>: TestRescue = cast(<self>: NilClass, TestRescue);
    <exceptionValue>$3: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$3 -> (T.nilable(Exception) ? bb3 : bb4)

# backedges
# - bb6
# - bb7
# - bb8
# - bb9
bb1[firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0
# - bb4
bb3[firstDead=-1](<self>: TestRescue, <returnMethodTemp>$2: T.untyped, <exceptionValue>$3: Exception):
    <cfgAlias>$8: T.class_of(<Magic>) = alias <C <Magic>>
    <statTemp>$9: T::Array[T.class_of(Exception)] = <self>: TestRescue.typed_exceptions()
    <exceptionClassTemp>$6: T::Array[T.class_of(Exception)] = <cfgAlias>$8: T.class_of(<Magic>).<splat>(<statTemp>$9: T::Array[T.class_of(Exception)])
    <isaCheckTemp>$11: T::Boolean = <exceptionClassTemp>$6: T::Array[T.class_of(Exception)].===(<exceptionValue>$3: Exception)
    <isaCheckTemp>$11 -> (T::Boolean ? bb7 : bb8)

# backedges
# - bb0
bb4[firstDead=-1](<self>: TestRescue):
    <returnMethodTemp>$2: T.untyped = <self>: TestRescue.meth()
    <exceptionValue>$3: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$3 -> (T.nilable(Exception) ? bb3 : bb6)

# backedges
# - bb4
bb6[firstDead=-1](<returnMethodTemp>$2: T.untyped, <gotoDeadTemp>$15: NilClass):
    <gotoDeadTemp>$15 -> (NilClass ? bb1 : bb9)

# backedges
# - bb3
bb7[firstDead=-1](<exceptionValue>$3: Exception):
    e: Exception = <exceptionValue>$3
    <exceptionValue>$3: NilClass = nil
    <keepForCfgTemp>$5: T.untyped = <keep-alive> <exceptionValue>$3
    <cfgAlias>$13: T.class_of(T) = alias <C T>
    <returnMethodTemp>$2: Exception = <cfgAlias>$13: T.class_of(T).reveal_type(e: Exception)
    <gotoDeadTemp>$15 -> (NilClass ? bb1 : bb9)

# backedges
# - bb3
bb8[firstDead=-1](<returnMethodTemp>$2: T.untyped):
    <gotoDeadTemp>$15: TrueClass = true
    <gotoDeadTemp>$15 -> (TrueClass ? bb1 : bb9)

# backedges
# - bb6
# - bb7
# - bb8
bb9[firstDead=1](<returnMethodTemp>$2: T.untyped):
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: T.untyped
    <unconditional> -> bb1

}

method ::TestRescue#rescue_typed_splat {

bb0[firstDead=-1]():
    <self>: TestRescue = cast(<self>: NilClass, TestRescue);
    <exceptionValue>$3: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$3 -> (T.nilable(Exception) ? bb3 : bb4)

# backedges
# - bb6
# - bb7
# - bb8
# - bb9
bb1[firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0
# - bb4
bb3[firstDead=-1](<self>: TestRescue, <returnMethodTemp>$2: T.untyped, <exceptionValue>$3: Exception):
    <cfgAlias>$8: T.class_of(<Magic>) = alias <C <Magic>>
    <statTemp>$9: [T.class_of(TypeError), T.class_of(ArgumentError)] = <self>: TestRescue.tuple_exceptions()
    <exceptionClassTemp>$6: [T.class_of(TypeError), T.class_of(ArgumentError)] = <cfgAlias>$8: T.class_of(<Magic>).<splat>(<statTemp>$9: [T.class_of(TypeError), T.class_of(ArgumentError)])
    <isaCheckTemp>$11: T::Boolean = <exceptionClassTemp>$6: [T.class_of(TypeError), T.class_of(ArgumentError)].===(<exceptionValue>$3: Exception)
    <isaCheckTemp>$11 -> (T::Boolean ? bb7 : bb8)

# backedges
# - bb0
bb4[firstDead=-1](<self>: TestRescue):
    <returnMethodTemp>$2: T.untyped = <self>: TestRescue.meth()
    <exceptionValue>$3: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$3 -> (T.nilable(Exception) ? bb3 : bb6)

# backedges
# - bb4
bb6[firstDead=-1](<returnMethodTemp>$2: T.untyped, <gotoDeadTemp>$15: NilClass):
    <gotoDeadTemp>$15 -> (NilClass ? bb1 : bb9)

# backedges
# - bb3
bb7[firstDead=-1](<exceptionValue>$3: Exception):
    e: Exception = <exceptionValue>$3
    <exceptionValue>$3: NilClass = nil
    <keepForCfgTemp>$5: T.untyped = <keep-alive> <exceptionValue>$3
    <cfgAlias>$13: T.class_of(T) = alias <C T>
    <returnMethodTemp>$2: Exception = <cfgAlias>$13: T.class_of(T).reveal_type(e: Exception)
    <gotoDeadTemp>$15 -> (NilClass ? bb1 : bb9)

# backedges
# - bb3
bb8[firstDead=-1](<returnMethodTemp>$2: T.untyped):
    <gotoDeadTemp>$15: TrueClass = true
    <gotoDeadTemp>$15 -> (TrueClass ? bb1 : bb9)

# backedges
# - bb6
# - bb7
# - bb8
bb9[firstDead=1](<returnMethodTemp>$2: T.untyped):
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: T.untyped
    <unconditional> -> bb1

}

method ::TestRescue#parse_rescue_ensure {

bb0[firstDead=-1]():
    <self>: TestRescue = cast(<self>: NilClass, TestRescue);
    <exceptionValue>$3: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$3 -> (T.nilable(Exception) ? bb3 : bb4)

# backedges
# - bb6
# - bb9
bb1[firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0
# - bb4
bb3[firstDead=-1](<self>: TestRescue, <returnMethodTemp>$2: T.untyped, <exceptionValue>$3: Exception):
    <cfgAlias>$10: T.class_of(StandardError) = alias <C StandardError>
    <isaCheckTemp>$11: T::Boolean = <cfgAlias>$10: T.class_of(StandardError).===(<exceptionValue>$3: Exception)
    <isaCheckTemp>$11 -> (T::Boolean ? bb7 : bb8)

# backedges
# - bb0
bb4[firstDead=-1](<self>: TestRescue):
    <returnMethodTemp>$2: T.untyped = <self>: TestRescue.meth()
    <exceptionValue>$3: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$3 -> (T.nilable(Exception) ? bb3 : bb6)

# backedges
# - bb4
# - bb7
# - bb8
bb6[firstDead=-1](<self>: TestRescue, <returnMethodTemp>$2: T.untyped, <exceptionValue>$3: T.nilable(Exception), <gotoDeadTemp>$13: T.nilable(TrueClass)):
    <cfgAlias>$6: T.class_of(T) = alias <C T>
    <rescueTemp>$2: T.untyped = <cfgAlias>$6: T.class_of(T).unsafe(<exceptionValue>$3: T.nilable(Exception))
    <throwAwayTemp>$14: T.untyped = <self>: TestRescue.bar()
    <gotoDeadTemp>$13 -> (T.nilable(TrueClass) ? bb1 : bb9)

# backedges
# - bb3
bb7[firstDead=-1](<self>: TestRescue, <exceptionValue>$3: StandardError):
    <exceptionValue>$3: NilClass = nil
    <keepForCfgTemp>$8: T.untyped = <keep-alive> <exceptionValue>$3
    <returnMethodTemp>$2: T.untyped = <self>: TestRescue.baz()
    <unconditional> -> bb6

# backedges
# - bb3
bb8[firstDead=-1](<self>: TestRescue, <returnMethodTemp>$2: T.untyped, <exceptionValue>$3: Exception):
    <gotoDeadTemp>$13: TrueClass = true
    <unconditional> -> bb6

# backedges
# - bb6
bb9[firstDead=1](<returnMethodTemp>$2: T.untyped):
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: T.untyped
    <unconditional> -> bb1

}

method ::TestRescue#parse_bug_rescue_empty_else {

bb0[firstDead=-1]():
    <self>: TestRescue = cast(<self>: NilClass, TestRescue);
    <exceptionValue>$3: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$3 -> (T.nilable(Exception) ? bb3 : bb4)

# backedges
# - bb6
# - bb7
# - bb8
# - bb9
bb1[firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0
# - bb4
bb3[firstDead=-1](<exceptionValue>$3: Exception):
    <cfgAlias>$6: T.class_of(LoadError) = alias <C LoadError>
    <isaCheckTemp>$7: T::Boolean = <cfgAlias>$6: T.class_of(LoadError).===(<exceptionValue>$3: Exception)
    <isaCheckTemp>$7 -> (T::Boolean ? bb7 : bb8)

# backedges
# - bb0
bb4[firstDead=-1]():
    <exceptionValue>$3: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$3 -> (T.nilable(Exception) ? bb3 : bb6)

# backedges
# - bb4
bb6[firstDead=-1](<gotoDeadTemp>$8: NilClass):
    <gotoDeadTemp>$8 -> (NilClass ? bb1 : bb9)

# backedges
# - bb3
bb7[firstDead=-1](<exceptionValue>$3: LoadError):
    <exceptionValue>$3: NilClass = nil
    <keepForCfgTemp>$4: T.untyped = <keep-alive> <exceptionValue>$3
    <gotoDeadTemp>$8 -> (NilClass ? bb1 : bb9)

# backedges
# - bb3
bb8[firstDead=-1]():
    <gotoDeadTemp>$8: TrueClass = true
    <gotoDeadTemp>$8 -> (TrueClass ? bb1 : bb9)

# backedges
# - bb6
# - bb7
# - bb8
bb9[firstDead=1]():
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

}

method ::TestRescue#parse_ruby_bug_12686 {

bb0[firstDead=-1]():
    <self>: TestRescue = cast(<self>: NilClass, TestRescue);
    <exceptionValue>$5: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$5 -> (T.nilable(Exception) ? bb3 : bb4)

# backedges
# - bb6
# - bb7
# - bb8
# - bb9
bb1[firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0
# - bb4
bb3[firstDead=-1](<self>: TestRescue, <statTemp>$4: T.untyped, <exceptionValue>$5: Exception):
    <cfgAlias>$9: T.class_of(StandardError) = alias <C StandardError>
    <isaCheckTemp>$10: T::Boolean = <cfgAlias>$9: T.class_of(StandardError).===(<exceptionValue>$5: Exception)
    <isaCheckTemp>$10 -> (T::Boolean ? bb7 : bb8)

# backedges
# - bb0
bb4[firstDead=-1](<self>: TestRescue):
    <statTemp>$4: T.untyped = <self>: TestRescue.bar()
    <exceptionValue>$5: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$5 -> (T.nilable(Exception) ? bb3 : bb6)

# backedges
# - bb4
bb6[firstDead=-1](<self>: TestRescue, <statTemp>$4: T.untyped, <gotoDeadTemp>$11: NilClass):
    <gotoDeadTemp>$11 -> (NilClass ? bb1 : bb9)

# backedges
# - bb3
bb7[firstDead=-1](<self>: TestRescue, <exceptionValue>$5: StandardError):
    <exceptionValue>$5: NilClass = nil
    <keepForCfgTemp>$7: T.untyped = <keep-alive> <exceptionValue>$5
    <statTemp>$4: NilClass = nil
    <gotoDeadTemp>$11 -> (NilClass ? bb1 : bb9)

# backedges
# - bb3
bb8[firstDead=-1](<self>: TestRescue, <statTemp>$4: T.untyped):
    <gotoDeadTemp>$11: TrueClass = true
    <gotoDeadTemp>$11 -> (TrueClass ? bb1 : bb9)

# backedges
# - bb6
# - bb7
# - bb8
bb9[firstDead=2](<self>: TestRescue, <statTemp>$4: T.untyped):
    <returnMethodTemp>$2: T.untyped = <self>: TestRescue.take_arg(<statTemp>$4: T.untyped)
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: T.untyped
    <unconditional> -> bb1

}

method ::TestRescue#parse_rescue_mod {

bb0[firstDead=-1]():
    <self>: TestRescue = cast(<self>: NilClass, TestRescue);
    <exceptionValue>$3: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$3 -> (T.nilable(Exception) ? bb3 : bb4)

# backedges
# - bb6
# - bb7
# - bb8
# - bb9
bb1[firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0
# - bb4
bb3[firstDead=-1](<self>: TestRescue, <returnMethodTemp>$2: T.untyped, <exceptionValue>$3: Exception):
    <cfgAlias>$7: T.class_of(StandardError) = alias <C StandardError>
    <isaCheckTemp>$8: T::Boolean = <cfgAlias>$7: T.class_of(StandardError).===(<exceptionValue>$3: Exception)
    <isaCheckTemp>$8 -> (T::Boolean ? bb7 : bb8)

# backedges
# - bb0
bb4[firstDead=-1](<self>: TestRescue):
    <returnMethodTemp>$2: T.untyped = <self>: TestRescue.meth()
    <exceptionValue>$3: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$3 -> (T.nilable(Exception) ? bb3 : bb6)

# backedges
# - bb4
bb6[firstDead=-1](<returnMethodTemp>$2: T.untyped, <gotoDeadTemp>$10: NilClass):
    <gotoDeadTemp>$10 -> (NilClass ? bb1 : bb9)

# backedges
# - bb3
bb7[firstDead=-1](<self>: TestRescue, <exceptionValue>$3: StandardError):
    <exceptionValue>$3: NilClass = nil
    <keepForCfgTemp>$5: T.untyped = <keep-alive> <exceptionValue>$3
    <returnMethodTemp>$2: T.untyped = <self>: TestRescue.bar()
    <gotoDeadTemp>$10 -> (NilClass ? bb1 : bb9)

# backedges
# - bb3
bb8[firstDead=-1](<returnMethodTemp>$2: T.untyped):
    <gotoDeadTemp>$10: TrueClass = true
    <gotoDeadTemp>$10 -> (TrueClass ? bb1 : bb9)

# backedges
# - bb6
# - bb7
# - bb8
bb9[firstDead=1](<returnMethodTemp>$2: T.untyped):
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: T.untyped
    <unconditional> -> bb1

}

method ::TestRescue#parse_resbody_list_var {

bb0[firstDead=-1]():
    <self>: TestRescue = cast(<self>: NilClass, TestRescue);
    <exceptionValue>$3: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$3 -> (T.nilable(Exception) ? bb3 : bb4)

# backedges
# - bb6
# - bb7
# - bb8
# - bb9
bb1[firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0
# - bb4
bb3[firstDead=-1](<self>: TestRescue, <returnMethodTemp>$2: T.untyped, <exceptionValue>$3: Exception):
    <exceptionClassTemp>$6: T.untyped = <self>: TestRescue.foo()
    <isaCheckTemp>$8: T.untyped = <exceptionClassTemp>$6: T.untyped.===(<exceptionValue>$3: Exception)
    <isaCheckTemp>$8 -> (T.untyped ? bb7 : bb8)

# backedges
# - bb0
bb4[firstDead=-1](<self>: TestRescue):
    <returnMethodTemp>$2: T.untyped = <self>: TestRescue.meth()
    <exceptionValue>$3: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$3 -> (T.nilable(Exception) ? bb3 : bb6)

# backedges
# - bb4
bb6[firstDead=-1](<returnMethodTemp>$2: T.untyped, <gotoDeadTemp>$10: NilClass):
    <gotoDeadTemp>$10 -> (NilClass ? bb1 : bb9)

# backedges
# - bb3
bb7[firstDead=-1](<self>: TestRescue, <exceptionValue>$3: Exception):
    <exceptionValue>$3: NilClass = nil
    <keepForCfgTemp>$5: T.untyped = <keep-alive> <exceptionValue>$3
    <returnMethodTemp>$2: T.untyped = <self>: TestRescue.bar()
    <gotoDeadTemp>$10 -> (NilClass ? bb1 : bb9)

# backedges
# - bb3
bb8[firstDead=-1](<returnMethodTemp>$2: T.untyped):
    <gotoDeadTemp>$10: TrueClass = true
    <gotoDeadTemp>$10 -> (TrueClass ? bb1 : bb9)

# backedges
# - bb6
# - bb7
# - bb8
bb9[firstDead=1](<returnMethodTemp>$2: T.untyped):
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: T.untyped
    <unconditional> -> bb1

}

method ::TestRescue#parse_rescue_else_ensure {

bb0[firstDead=-1]():
    <self>: TestRescue = cast(<self>: NilClass, TestRescue);
    <exceptionValue>$3: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$3 -> (T.nilable(Exception) ? bb3 : bb4)

# backedges
# - bb6
# - bb9
bb1[firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0
# - bb4
bb3[firstDead=-1](<self>: TestRescue, <returnMethodTemp>$2: T.untyped, <exceptionValue>$3: Exception):
    <cfgAlias>$11: T.class_of(StandardError) = alias <C StandardError>
    <isaCheckTemp>$12: T::Boolean = <cfgAlias>$11: T.class_of(StandardError).===(<exceptionValue>$3: Exception)
    <isaCheckTemp>$12 -> (T::Boolean ? bb7 : bb8)

# backedges
# - bb0
bb4[firstDead=-1](<self>: TestRescue):
    <returnMethodTemp>$2: T.untyped = <self>: TestRescue.meth()
    <exceptionValue>$3: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$3 -> (T.nilable(Exception) ? bb3 : bb5)

# backedges
# - bb4
bb5[firstDead=-1](<self>: TestRescue, <exceptionValue>$3: NilClass):
    <returnMethodTemp>$2: T.untyped = <self>: TestRescue.foo()
    <unconditional> -> bb6

# backedges
# - bb5
# - bb7
# - bb8
bb6[firstDead=-1](<self>: TestRescue, <returnMethodTemp>$2: T.untyped, <exceptionValue>$3: T.nilable(Exception), <gotoDeadTemp>$14: T.nilable(TrueClass)):
    <cfgAlias>$7: T.class_of(T) = alias <C T>
    <rescueTemp>$2: T.untyped = <cfgAlias>$7: T.class_of(T).unsafe(<exceptionValue>$3: T.nilable(Exception))
    <throwAwayTemp>$15: T.untyped = <self>: TestRescue.bar()
    <gotoDeadTemp>$14 -> (T.nilable(TrueClass) ? bb1 : bb9)

# backedges
# - bb3
bb7[firstDead=-1](<self>: TestRescue, <exceptionValue>$3: StandardError):
    <exceptionValue>$3: NilClass = nil
    <keepForCfgTemp>$9: T.untyped = <keep-alive> <exceptionValue>$3
    <returnMethodTemp>$2: T.untyped = <self>: TestRescue.baz()
    <unconditional> -> bb6

# backedges
# - bb3
bb8[firstDead=-1](<self>: TestRescue, <returnMethodTemp>$2: T.untyped, <exceptionValue>$3: Exception):
    <gotoDeadTemp>$14: TrueClass = true
    <unconditional> -> bb6

# backedges
# - bb6
bb9[firstDead=1](<returnMethodTemp>$2: T.untyped):
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: T.untyped
    <unconditional> -> bb1

}

method ::TestRescue#parse_rescue {

bb0[firstDead=-1]():
    <self>: TestRescue = cast(<self>: NilClass, TestRescue);
    <exceptionValue>$3: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$3 -> (T.nilable(Exception) ? bb3 : bb4)

# backedges
# - bb6
# - bb7
# - bb8
# - bb9
bb1[firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0
# - bb4
bb3[firstDead=-1](<self>: TestRescue, <returnMethodTemp>$2: T.untyped, <exceptionValue>$3: Exception):
    <cfgAlias>$7: T.class_of(StandardError) = alias <C StandardError>
    <isaCheckTemp>$8: T::Boolean = <cfgAlias>$7: T.class_of(StandardError).===(<exceptionValue>$3: Exception)
    <isaCheckTemp>$8 -> (T::Boolean ? bb7 : bb8)

# backedges
# - bb0
bb4[firstDead=-1](<self>: TestRescue):
    <returnMethodTemp>$2: T.untyped = <self>: TestRescue.meth()
    <exceptionValue>$3: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$3 -> (T.nilable(Exception) ? bb3 : bb6)

# backedges
# - bb4
bb6[firstDead=-1](<returnMethodTemp>$2: T.untyped, <gotoDeadTemp>$10: NilClass):
    <gotoDeadTemp>$10 -> (NilClass ? bb1 : bb9)

# backedges
# - bb3
bb7[firstDead=-1](<self>: TestRescue, <exceptionValue>$3: StandardError):
    <exceptionValue>$3: NilClass = nil
    <keepForCfgTemp>$5: T.untyped = <keep-alive> <exceptionValue>$3
    <returnMethodTemp>$2: T.untyped = <self>: TestRescue.foo()
    <gotoDeadTemp>$10 -> (NilClass ? bb1 : bb9)

# backedges
# - bb3
bb8[firstDead=-1](<returnMethodTemp>$2: T.untyped):
    <gotoDeadTemp>$10: TrueClass = true
    <gotoDeadTemp>$10 -> (TrueClass ? bb1 : bb9)

# backedges
# - bb6
# - bb7
# - bb8
bb9[firstDead=1](<returnMethodTemp>$2: T.untyped):
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: T.untyped
    <unconditional> -> bb1

}

method ::TestRescue#parse_resbody_var {

bb0[firstDead=-1]():
    <self>: TestRescue = cast(<self>: NilClass, TestRescue);
    <exceptionValue>$3: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$3 -> (T.nilable(Exception) ? bb3 : bb4)

# backedges
# - bb6
# - bb7
# - bb8
# - bb9
bb1[firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0
# - bb4
bb3[firstDead=-1](<self>: TestRescue, <returnMethodTemp>$2: T.untyped, <exceptionValue>$3: Exception):
    <cfgAlias>$7: T.class_of(StandardError) = alias <C StandardError>
    <isaCheckTemp>$8: T::Boolean = <cfgAlias>$7: T.class_of(StandardError).===(<exceptionValue>$3: Exception)
    <isaCheckTemp>$8 -> (T::Boolean ? bb7 : bb8)

# backedges
# - bb0
bb4[firstDead=-1](<self>: TestRescue):
    <returnMethodTemp>$2: T.untyped = <self>: TestRescue.meth()
    <exceptionValue>$3: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$3 -> (T.nilable(Exception) ? bb3 : bb6)

# backedges
# - bb4
bb6[firstDead=-1](<returnMethodTemp>$2: T.untyped, <gotoDeadTemp>$10: NilClass):
    <gotoDeadTemp>$10 -> (NilClass ? bb1 : bb9)

# backedges
# - bb3
bb7[firstDead=-1](<self>: TestRescue, <exceptionValue>$3: StandardError):
    <exceptionValue>$3: NilClass = nil
    <keepForCfgTemp>$5: T.untyped = <keep-alive> <exceptionValue>$3
    <returnMethodTemp>$2: T.untyped = <self>: TestRescue.bar()
    <gotoDeadTemp>$10 -> (NilClass ? bb1 : bb9)

# backedges
# - bb3
bb8[firstDead=-1](<returnMethodTemp>$2: T.untyped):
    <gotoDeadTemp>$10: TrueClass = true
    <gotoDeadTemp>$10 -> (TrueClass ? bb1 : bb9)

# backedges
# - bb6
# - bb7
# - bb8
bb9[firstDead=1](<returnMethodTemp>$2: T.untyped):
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: T.untyped
    <unconditional> -> bb1

}

method ::TestRescue#parse_resbody_var_1 {

bb0[firstDead=-1]():
    @ex$10: T.nilable(StandardError) = alias @ex
    <self>: TestRescue = cast(<self>: NilClass, TestRescue);
    <exceptionValue>$3: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$3 -> (T.nilable(Exception) ? bb3 : bb4)

# backedges
# - bb6
# - bb7
# - bb8
# - bb9
bb1[firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0
# - bb4
bb3[firstDead=-1](<self>: TestRescue, <returnMethodTemp>$2: T.untyped, <exceptionValue>$3: Exception, @ex$10: T.nilable(StandardError)):
    <cfgAlias>$7: T.class_of(StandardError) = alias <C StandardError>
    <isaCheckTemp>$8: T::Boolean = <cfgAlias>$7: T.class_of(StandardError).===(<exceptionValue>$3: Exception)
    <isaCheckTemp>$8 -> (T::Boolean ? bb7 : bb8)

# backedges
# - bb0
bb4[firstDead=-1](<self>: TestRescue, @ex$10: T.nilable(StandardError)):
    <returnMethodTemp>$2: T.untyped = <self>: TestRescue.meth()
    <exceptionValue>$3: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$3 -> (T.nilable(Exception) ? bb3 : bb6)

# backedges
# - bb4
bb6[firstDead=-1](<returnMethodTemp>$2: T.untyped, <gotoDeadTemp>$12: NilClass):
    <gotoDeadTemp>$12 -> (NilClass ? bb1 : bb9)

# backedges
# - bb3
bb7[firstDead=-1](<self>: TestRescue, <exceptionValue>$3: StandardError, @ex$10: T.nilable(StandardError)):
    <rescueTemp>$2: StandardError = <exceptionValue>$3
    <exceptionValue>$3: NilClass = nil
    <keepForCfgTemp>$5: T.untyped = <keep-alive> <exceptionValue>$3
    @ex$10: StandardError = <rescueTemp>$2
    <returnMethodTemp>$2: T.untyped = <self>: TestRescue.bar()
    <gotoDeadTemp>$12 -> (NilClass ? bb1 : bb9)

# backedges
# - bb3
bb8[firstDead=-1](<returnMethodTemp>$2: T.untyped):
    <gotoDeadTemp>$12: TrueClass = true
    <gotoDeadTemp>$12 -> (TrueClass ? bb1 : bb9)

# backedges
# - bb6
# - bb7
# - bb8
bb9[firstDead=1](<returnMethodTemp>$2: T.untyped):
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: T.untyped
    <unconditional> -> bb1

}

method ::TestRescue#parse_rescue_mod_op_assign {

bb0[firstDead=-1]():
    <self>: TestRescue = cast(<self>: NilClass, TestRescue);
    <statTemp>$3: NilClass = foo
    <exceptionValue>$5: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$5 -> (T.nilable(Exception) ? bb3 : bb4)

# backedges
# - bb6
# - bb7
# - bb8
# - bb9
bb1[firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0
# - bb4
bb3[firstDead=-1](<self>: TestRescue, <statTemp>$3: NilClass, <statTemp>$4: T.untyped, <exceptionValue>$5: Exception):
    <cfgAlias>$9: T.class_of(StandardError) = alias <C StandardError>
    <isaCheckTemp>$10: T::Boolean = <cfgAlias>$9: T.class_of(StandardError).===(<exceptionValue>$5: Exception)
    <isaCheckTemp>$10 -> (T::Boolean ? bb7 : bb8)

# backedges
# - bb0
bb4[firstDead=-1](<self>: TestRescue, <statTemp>$3: NilClass):
    <statTemp>$4: T.untyped = <self>: TestRescue.meth()
    <exceptionValue>$5: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$5 -> (T.nilable(Exception) ? bb3 : bb6)

# backedges
# - bb4
bb6[firstDead=-1](<statTemp>$3: NilClass, <statTemp>$4: T.untyped, <gotoDeadTemp>$12: NilClass):
    <gotoDeadTemp>$12 -> (NilClass ? bb1 : bb9)

# backedges
# - bb3
bb7[firstDead=-1](<self>: TestRescue, <statTemp>$3: NilClass, <exceptionValue>$5: StandardError):
    <exceptionValue>$5: NilClass = nil
    <keepForCfgTemp>$7: T.untyped = <keep-alive> <exceptionValue>$5
    <statTemp>$4: T.untyped = <self>: TestRescue.bar()
    <gotoDeadTemp>$12 -> (NilClass ? bb1 : bb9)

# backedges
# - bb3
bb8[firstDead=-1](<statTemp>$3: NilClass, <statTemp>$4: T.untyped):
    <gotoDeadTemp>$12: TrueClass = true
    <gotoDeadTemp>$12 -> (TrueClass ? bb1 : bb9)

# backedges
# - bb6
# - bb7
# - bb8
bb9[firstDead=3](<statTemp>$3: NilClass, <statTemp>$4: T.untyped):
    foo: T.untyped = <statTemp>$3: NilClass.+(<statTemp>$4: T.untyped)
    <returnMethodTemp>$2: T.untyped = foo
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: T.untyped
    <unconditional> -> bb1

}

method ::TestRescue#parse_ruby_bug_12402 {

bb0[firstDead=-1]():
    <self>: TestRescue = cast(<self>: NilClass, TestRescue);
    <exceptionValue>$3: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$3 -> (T.nilable(Exception) ? bb3 : bb4)

# backedges
# - bb6
# - bb7
# - bb8
# - bb9
bb1[firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0
# - bb4
bb3[firstDead=-1](foo: NilClass, <exceptionValue>$3: Exception):
    <cfgAlias>$9: T.class_of(StandardError) = alias <C StandardError>
    <isaCheckTemp>$10: T::Boolean = <cfgAlias>$9: T.class_of(StandardError).===(<exceptionValue>$3: Exception)
    <isaCheckTemp>$10 -> (T::Boolean ? bb7 : bb8)

# backedges
# - bb0
bb4[firstDead=2](<self>: TestRescue):
    <statTemp>$5: T.untyped = <self>: TestRescue.bar()
    foo: T.noreturn = <self>: TestRescue.raise(<statTemp>$5: T.untyped)
    <exceptionValue>$3 = <get-current-exception>
    <exceptionValue>$3 -> (<nullptr> ? bb3 : bb6)

# backedges
# - bb4
bb6[firstDead=0](foo: NilClass, <gotoDeadTemp>$11: NilClass):
    <gotoDeadTemp>$11 -> (<nullptr> ? bb1 : bb9)

# backedges
# - bb3
bb7[firstDead=-1](<exceptionValue>$3: StandardError):
    <exceptionValue>$3: NilClass = nil
    <keepForCfgTemp>$7: T.untyped = <keep-alive> <exceptionValue>$3
    foo: NilClass = nil
    <gotoDeadTemp>$11 -> (NilClass ? bb1 : bb9)

# backedges
# - bb3
bb8[firstDead=-1](foo: NilClass):
    <gotoDeadTemp>$11: TrueClass = true
    <gotoDeadTemp>$11 -> (TrueClass ? bb1 : bb9)

# backedges
# - bb6
# - bb7
# - bb8
bb9[firstDead=2](foo: NilClass):
    <returnMethodTemp>$2: NilClass = foo
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

}

method ::TestRescue#parse_ruby_bug_12402_1 {

bb0[firstDead=-1]():
    <self>: TestRescue = cast(<self>: NilClass, TestRescue);
    <statTemp>$3: NilClass = foo
    <exceptionValue>$5: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$5 -> (T.nilable(Exception) ? bb3 : bb4)

# backedges
# - bb6
# - bb7
# - bb8
# - bb9
bb1[firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0
# - bb4
bb3[firstDead=-1](<statTemp>$3: NilClass, <statTemp>$4: NilClass, <exceptionValue>$5: Exception):
    <cfgAlias>$11: T.class_of(StandardError) = alias <C StandardError>
    <isaCheckTemp>$12: T::Boolean = <cfgAlias>$11: T.class_of(StandardError).===(<exceptionValue>$5: Exception)
    <isaCheckTemp>$12 -> (T::Boolean ? bb7 : bb8)

# backedges
# - bb0
bb4[firstDead=2](<self>: TestRescue, <statTemp>$3: NilClass):
    <statTemp>$7: T.untyped = <self>: TestRescue.bar()
    <statTemp>$4: T.noreturn = <self>: TestRescue.raise(<statTemp>$7: T.untyped)
    <exceptionValue>$5 = <get-current-exception>
    <exceptionValue>$5 -> (<nullptr> ? bb3 : bb6)

# backedges
# - bb4
bb6[firstDead=0](<statTemp>$3: NilClass, <statTemp>$4: NilClass, <gotoDeadTemp>$13: NilClass):
    <gotoDeadTemp>$13 -> (<nullptr> ? bb1 : bb9)

# backedges
# - bb3
bb7[firstDead=-1](<statTemp>$3: NilClass, <exceptionValue>$5: StandardError):
    <exceptionValue>$5: NilClass = nil
    <keepForCfgTemp>$9: T.untyped = <keep-alive> <exceptionValue>$5
    <statTemp>$4: NilClass = nil
    <gotoDeadTemp>$13 -> (NilClass ? bb1 : bb9)

# backedges
# - bb3
bb8[firstDead=-1](<statTemp>$3: NilClass, <statTemp>$4: NilClass):
    <gotoDeadTemp>$13: TrueClass = true
    <gotoDeadTemp>$13 -> (TrueClass ? bb1 : bb9)

# backedges
# - bb6
# - bb7
# - bb8
bb9[firstDead=3](<statTemp>$3: NilClass, <statTemp>$4: NilClass):
    foo: T.untyped = <statTemp>$3: NilClass.+(<statTemp>$4: NilClass)
    <returnMethodTemp>$2: T.untyped = foo
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: T.untyped
    <unconditional> -> bb1

}

method ::TestRescue#parse_ruby_bug_12402_2 {

bb0[firstDead=-1]():
    <self>: TestRescue = cast(<self>: NilClass, TestRescue);
    []$3: T.untyped = <self>: TestRescue.foo()
    []$4: Integer(0) = 0
    <statTemp>$9: T.untyped = []$3: T.untyped.[]([]$4: Integer(0))
    <exceptionValue>$13: T.nilable(Exception) = <get-current-exception>
    <exceptionValue>$13 -> (T.nilable(Exception) ? bb3 : bb4)

# backedges
# - bb6
# - bb7
# - bb8
# - bb9
bb1[firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0
# - bb4
bb3[firstDead=-1]([]$3: T.untyped, []$4: Integer(0), <statTemp>$9: T.untyped, <statTemp>$12: NilClass, <exceptionValue>$13: Exception):
    <cfgAlias>$19: T.class_of(StandardError) = alias <C StandardError>
    <isaCheckTemp>$20: T::Boolean = <cfgAlias>$19: T.class_of(StandardError).===(<exceptionValue>$13: Exception)
    <isaCheckTemp>$20 -> (T::Boolean ? bb7 : bb8)

# backedges
# - bb0
bb4[firstDead=2](<self>: TestRescue, []$3: T.untyped, []$4: Integer(0), <statTemp>$9: T.untyped):
    <statTemp>$15: T.untyped = <self>: TestRescue.bar()
    <statTemp>$12: T.noreturn = <self>: TestRescue.raise(<statTemp>$15: T.untyped)
    <exceptionValue>$13 = <get-current-exception>
    <exceptionValue>$13 -> (<nullptr> ? bb3 : bb6)

# backedges
# - bb4
bb6[firstDead=0]([]$3: NilClass, []$4: NilClass, <statTemp>$9: NilClass, <statTemp>$12: NilClass, <gotoDeadTemp>$21: NilClass):
    <gotoDeadTemp>$21 -> (<nullptr> ? bb1 : bb9)

# backedges
# - bb3
bb7[firstDead=-1]([]$3: T.untyped, []$4: Integer(0), <statTemp>$9: T.untyped, <exceptionValue>$13: StandardError):
    <exceptionValue>$13: NilClass = nil
    <keepForCfgTemp>$17: T.untyped = <keep-alive> <exceptionValue>$13
    <statTemp>$12: NilClass = nil
    <gotoDeadTemp>$21 -> (NilClass ? bb1 : bb9)

# backedges
# - bb3
bb8[firstDead=-1]([]$3: T.untyped, []$4: Integer(0), <statTemp>$9: T.untyped, <statTemp>$12: NilClass):
    <gotoDeadTemp>$21: TrueClass = true
    <gotoDeadTemp>$21 -> (TrueClass ? bb1 : bb9)

# backedges
# - bb6
# - bb7
# - bb8
bb9[firstDead=3]([]$3: T.untyped, []$4: Integer(0), <statTemp>$9: T.untyped, <statTemp>$12: NilClass):
    <statTemp>$8: T.untyped = <statTemp>$9: T.untyped.+(<statTemp>$12: NilClass)
    <returnMethodTemp>$2: T.untyped = []$3: T.untyped.[]=([]$4: Integer(0), <statTemp>$8: T.untyped)
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: T.untyped
    <unconditional> -> bb1

}

