digraph "rescue.rb"{
subgraph "cluster_::<constant:Object>#main" {
    label = "::<constant:Object>#main";
    color = blue;
    "bb::<constant:Object>#main_0" [shape = invhouse];
    "bb::<constant:Object>#main_1" [shape = parallelogram];

    "bb::<constant:Object>#main_0" [label = "block[id=0](<constant:StandardError>$10)
<constant:StandardError>$10 = alias <constant:StandardError> : <class:StandardError>
rescueTemp$4 = <unanalyzable> : untyped
rescueTemp$4"];

    "bb::<constant:Object>#main_0" -> "bb::<constant:Object>#main_3" [style="bold"];
    "bb::<constant:Object>#main_0" -> "bb::<constant:Object>#main_4" [style="tapered"];

    "bb::<constant:Object>#main_1" [label = "block[id=1]()
<unconditional>"];

    "bb::<constant:Object>#main_1" -> "bb::<constant:Object>#main_1" [style="bold"];
    "bb::<constant:Object>#main_3" [label = "block[id=3](rescueTemp$4, <constant:StandardError>$10)
rescueTemp$11 = rescueTemp$4.is_a?(<constant:StandardError>$10) : untyped
rescueTemp$11"];

    "bb::<constant:Object>#main_3" -> "bb::<constant:Object>#main_8" [style="bold"];
    "bb::<constant:Object>#main_3" -> "bb::<constant:Object>#main_1" [style="tapered"];

    "bb::<constant:Object>#main_4" [label = "block[id=4](returnMethodTemp$2)
statTemp$5 = self : Object
returnMethodTemp$2 = statTemp$5.a() : untyped
statTemp$6 = self : Object
returnMethodTemp$2 = statTemp$6.c() : untyped
<unconditional>"];

    "bb::<constant:Object>#main_4" -> "bb::<constant:Object>#main_6" [style="bold"];
    "bb::<constant:Object>#main_6" [label = "block[id=6](returnMethodTemp$2)
statTemp$8 = self : Object
rescueTemp$7 = statTemp$8.d() : untyped
returnMethodTemp$13 = return returnMethodTemp$2 : <bottom>
<unconditional>"];

    "bb::<constant:Object>#main_6" -> "bb::<constant:Object>#main_1" [style="bold"];
    "bb::<constant:Object>#main_8" [label = "block[id=8](returnMethodTemp$2, rescueTemp$4)
statTemp$12 = self : Object
returnMethodTemp$2 = statTemp$12.b() : untyped
<unconditional>"];

    "bb::<constant:Object>#main_8" -> "bb::<constant:Object>#main_6" [style="bold"];
}

subgraph "cluster_::<constant:Object>#a" {
    label = "::<constant:Object>#a";
    color = blue;
    "bb::<constant:Object>#a_0" [shape = invhouse];
    "bb::<constant:Object>#a_1" [shape = parallelogram];

    "bb::<constant:Object>#a_0" [label = "block[id=0]()
returnMethodTemp$4 = return returnMethodTemp$2 : <bottom>
<unconditional>"];

    "bb::<constant:Object>#a_0" -> "bb::<constant:Object>#a_1" [style="bold"];
    "bb::<constant:Object>#a_1" [label = "block[id=1]()
<unconditional>"];

    "bb::<constant:Object>#a_1" -> "bb::<constant:Object>#a_1" [style="bold"];
}

subgraph "cluster_::<constant:Object>#b" {
    label = "::<constant:Object>#b";
    color = blue;
    "bb::<constant:Object>#b_0" [shape = invhouse];
    "bb::<constant:Object>#b_1" [shape = parallelogram];

    "bb::<constant:Object>#b_0" [label = "block[id=0]()
returnMethodTemp$4 = return returnMethodTemp$2 : <bottom>
<unconditional>"];

    "bb::<constant:Object>#b_0" -> "bb::<constant:Object>#b_1" [style="bold"];
    "bb::<constant:Object>#b_1" [label = "block[id=1]()
<unconditional>"];

    "bb::<constant:Object>#b_1" -> "bb::<constant:Object>#b_1" [style="bold"];
}

subgraph "cluster_::<constant:Object>#c" {
    label = "::<constant:Object>#c";
    color = blue;
    "bb::<constant:Object>#c_0" [shape = invhouse];
    "bb::<constant:Object>#c_1" [shape = parallelogram];

    "bb::<constant:Object>#c_0" [label = "block[id=0]()
returnMethodTemp$4 = return returnMethodTemp$2 : <bottom>
<unconditional>"];

    "bb::<constant:Object>#c_0" -> "bb::<constant:Object>#c_1" [style="bold"];
    "bb::<constant:Object>#c_1" [label = "block[id=1]()
<unconditional>"];

    "bb::<constant:Object>#c_1" -> "bb::<constant:Object>#c_1" [style="bold"];
}

subgraph "cluster_::<constant:Object>#d" {
    label = "::<constant:Object>#d";
    color = blue;
    "bb::<constant:Object>#d_0" [shape = invhouse];
    "bb::<constant:Object>#d_1" [shape = parallelogram];

    "bb::<constant:Object>#d_0" [label = "block[id=0]()
returnMethodTemp$4 = return returnMethodTemp$2 : <bottom>
<unconditional>"];

    "bb::<constant:Object>#d_0" -> "bb::<constant:Object>#d_1" [style="bold"];
    "bb::<constant:Object>#d_1" [label = "block[id=1]()
<unconditional>"];

    "bb::<constant:Object>#d_1" -> "bb::<constant:Object>#d_1" [style="bold"];
}

}

