digraph "rescue.rb" {
subgraph "cluster_::Object#main" {
    label = "::Object#main";
    color = blue;
    "bb::Object#main_0" [shape = invhouse];
    "bb::Object#main_1" [shape = parallelogram];

    "bb::Object#main_0" [
        label = "block[id=0]()\l<U <self>>: Object = cast(<U <self>>: NilClass, Object);\l<U <rescueStartTemp>>$3: T.untyped = <unanalyzable>\l<U <rescueStartTemp>>$3: T.untyped\l"
    ];

    "bb::Object#main_0" -> "bb::Object#main_3" [style="bold"];
    "bb::Object#main_0" -> "bb::Object#main_4" [style="tapered"];

    "bb::Object#main_1" [
        label = "block[id=1]()\l<unconditional>\l"
    ];

    "bb::Object#main_1" -> "bb::Object#main_1" [style="bold"];
    "bb::Object#main_3" [
        label = "block[id=3](<U <returnMethodTemp>>$2: T.untyped, <U <self>>: Object)\l<D <U <rescueTemp>> $2>: T.untyped = <unanalyzable>\l<U <exceptionClassTemp>>$7: T.class_of(StandardError) = alias <C <U StandardError>>\l<U <isaCheckTemp>>$8: T.untyped = <D <U <rescueTemp>> $2>: T.untyped.<U is_a?>(<U <exceptionClassTemp>>$7: T.class_of(StandardError))\l<U <isaCheckTemp>>$8: T.untyped\l"
    ];

    "bb::Object#main_3" -> "bb::Object#main_8" [style="bold"];
    "bb::Object#main_3" -> "bb::Object#main_9" [style="tapered"];

    "bb::Object#main_4" [
        label = "block[id=4](<U <self>>: Object)\l<U <returnMethodTemp>>$2: T.untyped = <U <self>>: Object.<U a>()\l<U <returnMethodTemp>>$2: T.untyped = <U <self>>: Object.<U c>()\l<U <rescueEndTemp>>$6: T.untyped = <unanalyzable>\l<U <rescueEndTemp>>$6: T.untyped\l"
    ];

    "bb::Object#main_4" -> "bb::Object#main_3" [style="bold"];
    "bb::Object#main_4" -> "bb::Object#main_6" [style="tapered"];

    "bb::Object#main_6" [
        label = "block[id=6](<U <returnMethodTemp>>$2: T.untyped, <U <self>>: Object, <U <gotoDeadTemp>>$10: T.nilable(TrueClass))\l<U <throwAwayTemp>>$11: T.untyped = <U <self>>: Object.<U d>()\l<U <gotoDeadTemp>>$10: T.nilable(TrueClass)\l"
    ];

    "bb::Object#main_6" -> "bb::Object#main_1" [style="bold"];
    "bb::Object#main_6" -> "bb::Object#main_10" [style="tapered"];

    "bb::Object#main_8" [
        label = "block[id=8](<U <self>>: Object)\l<U <returnMethodTemp>>$2: T.untyped = <U <self>>: Object.<U b>()\l<unconditional>\l"
    ];

    "bb::Object#main_8" -> "bb::Object#main_6" [style="bold"];
    "bb::Object#main_9" [
        label = "block[id=9](<U <returnMethodTemp>>$2: T.untyped, <U <self>>: Object)\l<U <gotoDeadTemp>>$10: TrueClass(true) = true\l<unconditional>\l"
    ];

    "bb::Object#main_9" -> "bb::Object#main_6" [style="bold"];
    "bb::Object#main_10" [
        label = "block[id=10](<U <returnMethodTemp>>$2: T.untyped)\l<U <finalReturn>>: T.noreturn = return <U <returnMethodTemp>>$2: T.untyped\l<unconditional>\l"
    ];

    "bb::Object#main_10" -> "bb::Object#main_1" [style="bold"];
}

subgraph "cluster_::Object#a" {
    label = "::Object#a";
    color = blue;
    "bb::Object#a_0" [shape = invhouse];
    "bb::Object#a_1" [shape = parallelogram];

    "bb::Object#a_0" [
        label = "block[id=0]()\l<U <self>>: Object = cast(<U <self>>: NilClass, Object);\l<U <finalReturn>>: T.noreturn = return <U <returnMethodTemp>>$2: NilClass\l<unconditional>\l"
    ];

    "bb::Object#a_0" -> "bb::Object#a_1" [style="bold"];
    "bb::Object#a_1" [
        label = "block[id=1]()\l<unconditional>\l"
    ];

    "bb::Object#a_1" -> "bb::Object#a_1" [style="bold"];
}

subgraph "cluster_::Object#b" {
    label = "::Object#b";
    color = blue;
    "bb::Object#b_0" [shape = invhouse];
    "bb::Object#b_1" [shape = parallelogram];

    "bb::Object#b_0" [
        label = "block[id=0]()\l<U <self>>: Object = cast(<U <self>>: NilClass, Object);\l<U <finalReturn>>: T.noreturn = return <U <returnMethodTemp>>$2: NilClass\l<unconditional>\l"
    ];

    "bb::Object#b_0" -> "bb::Object#b_1" [style="bold"];
    "bb::Object#b_1" [
        label = "block[id=1]()\l<unconditional>\l"
    ];

    "bb::Object#b_1" -> "bb::Object#b_1" [style="bold"];
}

subgraph "cluster_::Object#c" {
    label = "::Object#c";
    color = blue;
    "bb::Object#c_0" [shape = invhouse];
    "bb::Object#c_1" [shape = parallelogram];

    "bb::Object#c_0" [
        label = "block[id=0]()\l<U <self>>: Object = cast(<U <self>>: NilClass, Object);\l<U <finalReturn>>: T.noreturn = return <U <returnMethodTemp>>$2: NilClass\l<unconditional>\l"
    ];

    "bb::Object#c_0" -> "bb::Object#c_1" [style="bold"];
    "bb::Object#c_1" [
        label = "block[id=1]()\l<unconditional>\l"
    ];

    "bb::Object#c_1" -> "bb::Object#c_1" [style="bold"];
}

subgraph "cluster_::Object#d" {
    label = "::Object#d";
    color = blue;
    "bb::Object#d_0" [shape = invhouse];
    "bb::Object#d_1" [shape = parallelogram];

    "bb::Object#d_0" [
        label = "block[id=0]()\l<U <self>>: Object = cast(<U <self>>: NilClass, Object);\l<U <finalReturn>>: T.noreturn = return <U <returnMethodTemp>>$2: NilClass\l<unconditional>\l"
    ];

    "bb::Object#d_0" -> "bb::Object#d_1" [style="bold"];
    "bb::Object#d_1" [
        label = "block[id=1]()\l<unconditional>\l"
    ];

    "bb::Object#d_1" -> "bb::Object#d_1" [style="bold"];
}

subgraph "cluster_::<Class:<root>>#<static-init>" {
    label = "::<Class:<root>>#<static-init>";
    color = blue;
    "bb::<Class:<root>>#<static-init>_0" [shape = invhouse];
    "bb::<Class:<root>>#<static-init>_1" [shape = parallelogram];

    "bb::<Class:<root>>#<static-init>_0" [
        label = "block[id=0]()\l<U <self>>: T.class_of(<root>) = cast(<U <self>>: NilClass, T.class_of(<root>));\l<U <statTemp>>$4: T.untyped = <U <self>>: T.class_of(<root>).<U foo>()\l<U <returnMethodTemp>>$2: NilClass = <U <self>>: T.class_of(<root>).<U puts>(<U <statTemp>>$4: T.untyped)\l<U <finalReturn>>: T.noreturn = return <U <returnMethodTemp>>$2: NilClass\l<unconditional>\l"
    ];

    "bb::<Class:<root>>#<static-init>_0" -> "bb::<Class:<root>>#<static-init>_1" [style="bold"];
    "bb::<Class:<root>>#<static-init>_1" [
        label = "block[id=1]()\l<unconditional>\l"
    ];

    "bb::<Class:<root>>#<static-init>_1" -> "bb::<Class:<root>>#<static-init>_1" [style="bold"];
}

}

