class <constant:<root>> < ::<constant:Object> () -> <Class:<root>> @ test/testdata/cfg/singleton_lazy.rb:2
  class <constant:A> < ::<constant:Object> () -> <Class:A> @ test/testdata/cfg/singleton_lazy.rb:2
  class <constant:Object> < ::<constant:BasicObject> (<constant:Kernel>) -> <Class:Object> @ rbi/stdlib.rbi:8300
    method main () @ test/testdata/cfg/singleton_lazy.rb:4
  class <singleton class:<constant:A>> < ::<singleton class:<constant:Object>> () @ test/testdata/cfg/singleton_lazy.rb:2
  method <static-init>$8 () @ test/testdata/cfg/singleton_lazy.rb:2

