class <constant:<root>> < ::<constant:Object> () -> <Class:<root>> @ test/testdata/cfg/singleton_lazy.rb:2
  class <constant:A> < ::<constant:Object> () -> <Class:A> @ test/testdata/cfg/singleton_lazy.rb:2
  class <constant:Object> < ::<constant:BasicObject> (<constant:Kernel>) -> <Class:Object> @ https://git.corp.stripe.com/stripe-internal/ruby-typer/tree/master/rbi/core.rbi#L8315
    method main () @ test/testdata/cfg/singleton_lazy.rb:4
  class <singleton class:<constant:A>> < ::<singleton class:<constant:Object>> () @ test/testdata/cfg/singleton_lazy.rb:2
  method <static-init>$9 () @ test/testdata/cfg/singleton_lazy.rb:2

