# @typed
# @typed
class Examples
  def i_like_ifs()
    if true
       # <ifTemp>$4: TrueClass(true)
      return 1
      # dead=1
      # <returnTemp>$5: Integer(1)
      #
      # <returnMethodTemp>$2: <bottom>
    else
      return 2 # error: This code is unreachable
    end
  end

    def i_like_exps()
      # <returnMethodTemp>$2: Integer(1)
      if (true)
          # <ifTemp>$4: TrueClass(true)
        1
        # <returnMethodTemp>$2: Integer(1)
      else
        2 # error: This code is unreachable
      end
      # dead=1
      # <returnMethodTemp>$2: Integer(1)
      #
      # <finalReturn>: <bottom>
    end

    def return_in_one_branch1()
      if (true)
          # <ifTemp>$4: TrueClass(true)
        return 1
        # dead=1
        # <returnTemp>$5: Integer(1)
        #
        # <returnMethodTemp>$2: <bottom>
      else
        2 # error: This code is unreachable
      end
    end

    def variables()
      if (true)
          # <ifTemp>$5: TrueClass(true)
        a = 1
            # a: Integer(1)
      else
        a = 2 # error: This code is unreachable
      end

          # a: Integer(1)
      if (false)
          # a: Integer(1)
          #
          # <ifTemp>$7: FalseClass(false)
            # a: Integer(1)
        b = 1 # not-yet-an-error: This code is unreachable
            # a: Integer(1)
            #
            # b: Integer(1)
      else
            # a: Integer(1)
        b = 2
            # a: Integer(1)
            #
            # b: Integer(2)
      end

      # b: Integer
      #
      # a: Integer(1)
      a + b
      # dead=1
      # b: Integer
      #
      # a: Integer(1)
      #
      # <returnMethodTemp>$2: Integer
      #
      # <finalReturn>: <bottom>
    end


    def variables_and_loop(cond)
      if (true)
          # <constant:nil>$10: NilClass
          #
          # <selfMethodTemp>$3: Examples
          #
          # cond: untyped
          #
          # <ifTemp>$5: TrueClass(true)
            # <constant:nil>$10: NilClass
            #
            # cond: untyped
        a = 1
            # <constant:nil>$10: NilClass
            #
            # cond: untyped
            #
            # a: Integer(1)
      else
        a = 2 # error: This code is unreachable
      end

            # <constant:nil>$10: NilClass
            #
            # b: NilClass
            #
            # cond: untyped
            #   Being truthy entails:
            #     <constant:nil>$10 to be NilClass
            #     cond to be untyped
            #     <debugEnvironmentTemp>$12 to be untyped
            #     a to be Integer(1)
            #   Being falsy entails:
            #     <constant:nil>$10 to be NilClass
            #     cond to be untyped
            #     <debugEnvironmentTemp>$12 to be untyped
            #     a to be Integer(1)
      while true
            # <constant:nil>$10: NilClass
            #
            # b: NilClass
            #
            # cond: untyped
            #   Being truthy entails:
            #     <constant:nil>$10 to be NilClass
            #     cond to be untyped
            #     <debugEnvironmentTemp>$12 to be untyped
            #     a to be Integer(1)
            #   Being falsy entails:
            #     <constant:nil>$10 to be NilClass
            #     cond to be untyped
            #     <debugEnvironmentTemp>$12 to be untyped
            #     a to be Integer(1)
            #
            # <whileTemp>$7: TrueClass(true)
        if (cond)
              # <constant:nil>$10: NilClass
              #
              # b: NilClass
              #
              # cond: untyped
              #   Being truthy entails:
              #     <constant:nil>$10 to be NilClass
              #     cond to be untyped
              #     <debugEnvironmentTemp>$12 to be untyped
              #     a to be Integer(1)
              #   Being falsy entails:
              #     <constant:nil>$10 to be NilClass
              #     cond to be untyped
              #     <debugEnvironmentTemp>$12 to be untyped
              #     a to be Integer(1)
          b = 1 # error: Changing type of pinned argument
              # <constant:nil>$10: NilClass
              #
              # b: untyped
              #
              # cond: untyped
              #   Being truthy entails:
              #     <constant:nil>$10 to be NilClass
              #     cond to be untyped
              #     <debugEnvironmentTemp>$12 to be untyped
              #     a to be Integer(1)
              #   Being falsy entails:
              #     <constant:nil>$10 to be NilClass
              #     cond to be untyped
              #     <debugEnvironmentTemp>$12 to be untyped
              #     a to be Integer(1)
        else
              # <constant:nil>$10: NilClass
              #
              # b: NilClass
              #
              # cond: untyped
              #   Being truthy entails:
              #     <constant:nil>$10 to be NilClass
              #     cond to be untyped
              #     <debugEnvironmentTemp>$12 to be untyped
              #     a to be Integer(1)
              #   Being falsy entails:
              #     <constant:nil>$10 to be NilClass
              #     cond to be untyped
              #     <debugEnvironmentTemp>$12 to be untyped
              #     a to be Integer(1)
          b = 2 # error: Changing type of pinned argument
              # <constant:nil>$10: NilClass
              #
              # b: untyped
              #
              # cond: untyped
              #   Being truthy entails:
              #     <constant:nil>$10 to be NilClass
              #     cond to be untyped
              #     <debugEnvironmentTemp>$12 to be untyped
              #     a to be Integer(1)
              #   Being falsy entails:
              #     <constant:nil>$10 to be NilClass
              #     cond to be untyped
              #     <debugEnvironmentTemp>$12 to be untyped
              #     a to be Integer(1)
        end
      end

      b # error: This code is unreachable
    end


    def variables_loop_if(cond)
                          # <constant:nil>$8: NilClass
                          #
                          # <selfMethodTemp>$3: Examples
                          #
                          # cond: untyped
            # <constant:nil>$8: NilClass
            #
            # b: NilClass
            #
            # cond: untyped
            #   Being truthy entails:
            #     <constant:nil>$8 to be NilClass
            #     <debugEnvironmentTemp>$9 to be untyped
            #     <selfMethodTemp>$3 to be Examples
            #     cond to be untyped
            #   Being falsy entails:
            #     <constant:nil>$8 to be NilClass
            #     <debugEnvironmentTemp>$9 to be untyped
            #     <selfMethodTemp>$3 to be Examples
            #     cond to be untyped
      while true
            # <constant:nil>$8: NilClass
            #
            # b: NilClass
            #
            # cond: untyped
            #   Being truthy entails:
            #     <constant:nil>$8 to be NilClass
            #     <debugEnvironmentTemp>$9 to be untyped
            #     <selfMethodTemp>$3 to be Examples
            #     cond to be untyped
            #   Being falsy entails:
            #     <constant:nil>$8 to be NilClass
            #     <debugEnvironmentTemp>$9 to be untyped
            #     <selfMethodTemp>$3 to be Examples
            #     cond to be untyped
            #
            # <whileTemp>$5: TrueClass(true)
        if (cond)
              # <constant:nil>$8: NilClass
              #
              # b: NilClass
              #
              # cond: untyped
              #   Being truthy entails:
              #     <constant:nil>$8 to be NilClass
              #     <debugEnvironmentTemp>$9 to be untyped
              #     <selfMethodTemp>$3 to be Examples
              #     cond to be untyped
              #   Being falsy entails:
              #     <constant:nil>$8 to be NilClass
              #     <debugEnvironmentTemp>$9 to be untyped
              #     <selfMethodTemp>$3 to be Examples
              #     cond to be untyped
          b = 1 # error: Changing type of pinned argument
              # <constant:nil>$8: NilClass
              #
              # b: untyped
              #
              # cond: untyped
              #   Being truthy entails:
              #     <constant:nil>$8 to be NilClass
              #     <debugEnvironmentTemp>$9 to be untyped
              #     <selfMethodTemp>$3 to be Examples
              #     cond to be untyped
              #   Being falsy entails:
              #     <constant:nil>$8 to be NilClass
              #     <debugEnvironmentTemp>$9 to be untyped
              #     <selfMethodTemp>$3 to be Examples
              #     cond to be untyped
        else
              # <constant:nil>$8: NilClass
              #
              # b: NilClass
              #
              # cond: untyped
              #   Being truthy entails:
              #     <constant:nil>$8 to be NilClass
              #     <debugEnvironmentTemp>$9 to be untyped
              #     <selfMethodTemp>$3 to be Examples
              #     cond to be untyped
              #   Being falsy entails:
              #     <constant:nil>$8 to be NilClass
              #     <debugEnvironmentTemp>$9 to be untyped
              #     <selfMethodTemp>$3 to be Examples
              #     cond to be untyped
          b = 2 # error: Changing type of pinned argument
              # <constant:nil>$8: NilClass
              #
              # b: untyped
              #
              # cond: untyped
              #   Being truthy entails:
              #     <constant:nil>$8 to be NilClass
              #     <debugEnvironmentTemp>$9 to be untyped
              #     <selfMethodTemp>$3 to be Examples
              #     cond to be untyped
              #   Being falsy entails:
              #     <constant:nil>$8 to be NilClass
              #     <debugEnvironmentTemp>$9 to be untyped
              #     <selfMethodTemp>$3 to be Examples
              #     cond to be untyped
        end
      end

      b # error: This code is unreachable
    end

    def take_arguments(i)
      # <returnMethodTemp>$2: untyped
      if(false)
         # <selfMethodTemp>$3: Examples
         #
         # i: untyped
         #
         # <ifTemp>$4: FalseClass(false)
       2 # not-yet-an-error: This code is unreachable
       # <returnMethodTemp>$2: Integer(2)
      else
       # i: untyped
       i
       # i: untyped
       #
       # <returnMethodTemp>$2: untyped
      end
      # dead=1
      # <returnMethodTemp>$2: untyped
      #
      # <finalReturn>: <bottom>
    end

end
