DefMethod {
  name = <U foo>
  args = Args {
    args = [
      Arg {
        name = <U a>
      }
      Optarg {
        name = <U b>
        default_ = Integer {
          val = "2"
        }
      }
      Kwarg {
        name = <U c>
      }
      Kwoptarg {
        name = <U d>
        default_ = Integer {
          val = "4"
        }
      }
      Blockarg {
        name = <U blk>
      }
    ]
  }
  body = NULL
}
