Begin {
  stmts = [
    DefMethod {
      name = <U foo>
      args = Params {
        args = [
          Kwarg {
            name = <U a>
          }
        ]
      }
      body = NULL
    }
    DefMethod {
      name = <U bar>
      args = Params {
        args = [
          Kwarg {
            name = <U a>
          }
          Kwarg {
            name = <U b>
          }
        ]
      }
      body = NULL
    }
  ]
}
