Begin {
  stmts = [
    DefMethod {
      name = <U foo>
      params = Params {
        params = [
          RestParam {
            name = <U a>
          }
        ]
      }
      body = NULL
    }
    DefMethod {
      name = <U foo>
      params = Params {
        params = [
          RestParam {
            name = <U <restargs>>
          }
        ]
      }
      body = NULL
    }
    DefMethod {
      name = <U foo>
      params = Params {
        params = [
          RestParam {
            name = <U a>
          }
          Param {
            name = <U b>
          }
          Param {
            name = <U c>
          }
        ]
      }
      body = NULL
    }
  ]
}
