Begin {
  stmts = [
    DefMethod {
      name = <U foo>
      params = Params {
        params = [
          Kwoptarg {
            name = <U a>
            default_ = Integer {
              val = "1"
            }
          }
        ]
      }
      body = NULL
    }
    DefMethod {
      name = <U bar>
      params = Params {
        params = [
          Kwoptarg {
            name = <U a>
            default_ = Integer {
              val = "1"
            }
          }
          Kwoptarg {
            name = <U b>
            default_ = Integer {
              val = "2"
            }
          }
        ]
      }
      body = NULL
    }
  ]
}
