ClassDef{
  kind = class
  name = EmptyTree
  symbol = <C <U <root>>>
  ancestors = [ConstantLit{
      symbol = (class ::<todo sym>)
      orig = nullptr
    }]
  rhs = [
    Send{
      flags = {}
      recv = ConstantLit{
        symbol = (module ::Kernel)
        orig = nullptr
      }
      fun = <U Rational>
      block = nullptr
      pos_args = 1
      args = [
        Literal{ value = "42.0" }
      ]
    }

    Send{
      flags = {}
      recv = ConstantLit{
        symbol = (module ::Kernel)
        orig = nullptr
      }
      fun = <U Rational>
      block = nullptr
      pos_args = 1
      args = [
        Literal{ value = "42.00000" }
      ]
    }
  ]
}
