#ifndef SORBET_CORE_STRICT_LEVEL_H
#define SORBET_CORE_STRICT_LEVEL_H

namespace sorbet {
namespace core {
enum class StrictLevel {
    // Temporary; A level defined as "whatever Stripe needs it to be right now".
    // Eventually this will be named "Ruby" and contain even fewer checks.
    Stripe = 0,

    // Normally the first level you transition your files to.
    Typed = 1,

    // Everything must be declared.
    Strict = 2,

    // Nothing can be T.untyped in the file. Basically Java.
    Strong = 3,

    // Custom levels which mirror another level with some tweaks.

    // Identical to Strict except allow constants to be undefined. Useful for
    // .rbi files that are written by scripts but you don't require people
    // update them when they delete a class.
    Autogenerated = 10,
};
}
} // namespace sorbet

#endif
