['~/.', '/etc/'].any? do |file|
  File.lstat(path = File.expand_path(file + 'bundle-gemfile-hook')) rescue next
  eval(File.read(path), binding, path); break true
end || source('https://rubygems.org/')

gemspec
