; ModuleID = 'payload'
source_filename = "llvm-link"
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"

%struct.rb_vm_struct = type { i64, %struct.rb_global_vm_lock_struct, %struct.rb_thread_struct*, %struct.rb_thread_struct*, i8*, i64, %union.pthread_mutex_t, %struct.list_head, %struct.list_head, %struct.list_head, %struct.list_head, i64, i32, i32, i8, i32, i64, [5 x i64], i64, i64, i64, i64, i64, i64, i64, %struct.st_table*, %struct.st_table*, %struct.anon.3, %struct.rb_hook_list_struct, %struct.st_table*, %struct.rb_postponed_job_struct*, i32, i32, %struct.list_head, %union.pthread_mutex_t, i64, i64, i64, i64, i64, i32, %struct.st_table*, %struct.rb_objspace*, %struct.rb_at_exit_list*, i64*, %struct.st_table*, %struct.rb_builtin_function*, i32, %struct.anon.4, [29 x i16] }
%struct.rb_global_vm_lock_struct = type { %struct.rb_thread_struct*, %union.pthread_mutex_t, %struct.list_head, %struct.rb_thread_struct*, i32, %union.pthread_cond_t, %union.pthread_cond_t, i32, i32 }
%union.pthread_cond_t = type { %struct.anon.2 }
%struct.anon.2 = type { i32, i32, i64, i64, i64, i8*, i32, i32 }
%struct.rb_thread_struct = type { %struct.list_node, i64, %struct.rb_vm_struct*, %struct.rb_execution_context_struct*, i64, %struct.rb_calling_info*, i64, i64, i64, i8, i8, i32, %struct.native_thread_data_struct, i8*, i64, i64, i64, i64, %union.pthread_mutex_t, %struct.rb_unblock_callback, i64, %struct.rb_mutex_struct*, %struct.rb_thread_list_struct*, %union.anon.7, i32, i64, %struct.rb_fiber_struct*, [5 x i8*], i64 }
%struct.list_node = type { %struct.list_node*, %struct.list_node* }
%struct.rb_execution_context_struct = type { i64*, i64, %struct.rb_control_frame_struct*, %struct.rb_vm_tag*, %struct.rb_vm_protect_tag*, i32, i32, %struct.rb_fiber_struct*, %struct.rb_thread_struct*, %struct.st_table*, i64, i64, i64*, i64, %struct.rb_ensure_list*, %struct.rb_trace_arg_struct*, i64, i64, i8, i8, i64, %struct.anon.5 }
%struct.rb_control_frame_struct = type { i64*, i64*, %struct.rb_iseq_struct*, i64, i64*, i8*, i64* }
%struct.rb_iseq_struct = type { i64, i64, %struct.rb_iseq_constant_body*, %union.anon.14 }
%struct.rb_iseq_constant_body = type { i32, i32, i64*, %struct.anon, %struct.rb_iseq_location_struct, %struct.iseq_insn_info, i64*, %struct.iseq_catch_table*, %struct.rb_iseq_struct*, %struct.rb_iseq_struct*, %union.iseq_inline_storage_entry*, %struct.rb_call_data*, %struct.anon.13, i32, i32, i32, i32, i32, i8, i64 }
%struct.anon = type { %struct.anon.0, i32, i32, i32, i32, i32, i32, i32, i64*, %struct.rb_iseq_param_keyword* }
%struct.anon.0 = type { i16, [2 x i8] }
%struct.rb_iseq_param_keyword = type { i32, i32, i32, i32, i64*, i64* }
%struct.rb_iseq_location_struct = type { i64, i64, i64, i64, i32, %struct.rb_code_location_struct }
%struct.rb_code_location_struct = type { %struct.rb_code_position_struct, %struct.rb_code_position_struct }
%struct.rb_code_position_struct = type { i32, i32 }
%struct.iseq_insn_info = type { %struct.iseq_insn_info_entry*, i32*, i32, %struct.succ_index_table* }
%struct.iseq_insn_info_entry = type opaque
%struct.succ_index_table = type opaque
%struct.iseq_catch_table = type opaque
%union.iseq_inline_storage_entry = type { %struct.iseq_inline_cache_entry }
%struct.iseq_inline_cache_entry = type { i64, %struct.rb_cref_struct*, i64 }
%struct.rb_cref_struct = type { i64, i64, i64, %struct.rb_cref_struct*, %struct.rb_scope_visi_struct }
%struct.rb_scope_visi_struct = type { i8, [3 x i8] }
%struct.rb_call_data = type { %struct.rb_call_cache, %struct.rb_call_info }
%struct.rb_call_cache = type { i64, [3 x i64], %struct.rb_callable_method_entry_struct*, i64, i64 (%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_calling_info*, %struct.rb_call_data*)*, %union.anon.12 }
%struct.rb_callable_method_entry_struct = type { i64, i64, %struct.rb_method_definition_struct*, i64, i64 }
%struct.rb_method_definition_struct = type { i64, %union.anon.10, i64, i64 }
%union.anon.10 = type { %struct.rb_method_cfunc_struct }
%struct.rb_method_cfunc_struct = type { i64 (...)*, i64 (i64, i32, i64*, i64 (...)*)*, i32 }
%union.anon.12 = type { i32 }
%struct.rb_call_info = type { i64, i32, i32 }
%struct.anon.13 = type { i64, i64, i64, i64* }
%union.anon.14 = type { %struct.anon.15 }
%struct.anon.15 = type { i64, i32 }
%struct.rb_vm_tag = type { i64, i64, [5 x i8*], %struct.rb_vm_tag*, i32 }
%struct.rb_vm_protect_tag = type { %struct.rb_vm_protect_tag* }
%struct.rb_ensure_list = type { %struct.rb_ensure_list*, %struct.rb_ensure_entry }
%struct.rb_ensure_entry = type { i64, i64 (i64)*, i64 }
%struct.rb_trace_arg_struct = type { i32, %struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, i64, i64, i64, i64, i64, i32, i32, i64 }
%struct.anon.5 = type { i64*, i64*, i64, [1 x %struct.__jmp_buf_tag] }
%struct.__jmp_buf_tag = type { [8 x i64], i32, %struct.__sigset_t }
%struct.__sigset_t = type { [16 x i64] }
%struct.rb_calling_info = type { i64, i64, i32, i32 }
%struct.native_thread_data_struct = type { %struct.list_head, %union.anon.6 }
%union.anon.6 = type { %union.pthread_cond_t }
%struct.rb_unblock_callback = type { void (i8*)*, i8* }
%struct.rb_mutex_struct = type opaque
%struct.rb_thread_list_struct = type { %struct.rb_thread_list_struct*, %struct.rb_thread_struct* }
%union.anon.7 = type { %struct.anon.8 }
%struct.anon.8 = type { i64, i64, i32 }
%struct.rb_fiber_struct = type opaque
%struct.anon.3 = type { [65 x i64] }
%struct.rb_hook_list_struct = type { %struct.rb_event_hook_struct*, i32, i32, i32 }
%struct.rb_event_hook_struct = type opaque
%struct.rb_postponed_job_struct = type opaque
%struct.list_head = type { %struct.list_node }
%union.pthread_mutex_t = type { %struct.__pthread_mutex_s }
%struct.__pthread_mutex_s = type { i32, i32, i32, i32, i32, i16, i16, %struct.__pthread_internal_list }
%struct.__pthread_internal_list = type { %struct.__pthread_internal_list*, %struct.__pthread_internal_list* }
%struct.rb_objspace = type opaque
%struct.rb_at_exit_list = type { void (%struct.rb_vm_struct*)*, %struct.rb_at_exit_list* }
%struct.st_table = type { i8, i8, i8, i32, %struct.st_hash_type*, i64, i64*, i64, i64, %struct.st_table_entry* }
%struct.st_hash_type = type { i32 (i64, i64)*, i64 (i64)* }
%struct.st_table_entry = type opaque
%struct.rb_builtin_function = type opaque
%struct.anon.4 = type { i64, i64, i64, i64 }
%struct.FunctionInlineCache = type { %struct.rb_kwarg_call_data }
%struct.rb_kwarg_call_data = type { %struct.rb_call_cache, %struct.rb_call_info_with_kwarg }
%struct.rb_call_info_with_kwarg = type { %struct.rb_call_info, %struct.rb_call_info_kw_arg* }
%struct.rb_call_info_kw_arg = type { i32, [1 x i64] }
%struct.RClass = type { %struct.iseq_inline_iv_cache_entry, i64, %struct.rb_classext_struct*, i64 }
%struct.iseq_inline_iv_cache_entry = type { i64, i64 }
%struct.rb_classext_struct = type { %struct.st_table*, %struct.st_table*, %struct.rb_id_table*, %struct.rb_id_table*, %struct.rb_id_table*, %struct.rb_subclass_entry*, %struct.rb_subclass_entry**, %struct.rb_subclass_entry**, i64, i64, i64 (i64)*, i64 }
%struct.rb_id_table = type opaque
%struct.rb_subclass_entry = type { i64, %struct.rb_subclass_entry* }

@ruby_current_vm_ptr = external local_unnamed_addr global %struct.rb_vm_struct*, align 8
@ruby_current_execution_context_ptr = external local_unnamed_addr global %struct.rb_execution_context_struct*, align 8
@sorbet_getVoidSingleton.name = internal constant [30 x i8] c"T::Private::Types::Void::VOID\00", align 16
@ruby_vm_global_constant_state = external local_unnamed_addr global i64, align 8
@rb_eRuntimeError = external local_unnamed_addr global i64, align 8
@.str.6 = private unnamed_addr constant [42 x i8] c"unimplemented super with a missing method\00", align 1
@.str.8 = private unnamed_addr constant [95 x i8] c"sorbet_getBuildSCMRevision: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@.str.9 = private unnamed_addr constant [93 x i8] c"sorbet_getIsReleaseBuild: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@"stackFramePrecomputed_func_<root>.<static-init>$152" = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@"rubyIdPrecomputed_<top (required)>" = internal unnamed_addr global i64 0, align 8
@"str_<top (required)>" = private unnamed_addr constant [17 x i8] c"<top (required)>\00", align 1
@"rubyStrFrozen_<top (required)>" = internal unnamed_addr global i64 0, align 8
@"rubyStrFrozen_test/testdata/compiler/abstract_static_methods.rb" = internal unnamed_addr global i64 0, align 8
@"str_test/testdata/compiler/abstract_static_methods.rb" = private unnamed_addr constant [50 x i8] c"test/testdata/compiler/abstract_static_methods.rb\00", align 1
@str_IFoo = private unnamed_addr constant [5 x i8] c"IFoo\00", align 1
@str_Foo = private unnamed_addr constant [4 x i8] c"Foo\00", align 1
@ic_foo = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_foo = internal unnamed_addr global i64 0, align 8
@str_foo = private unnamed_addr constant [4 x i8] c"foo\00", align 1
@ic_p = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_p = internal unnamed_addr global i64 0, align 8
@str_p = private unnamed_addr constant [2 x i8] c"p\00", align 1
@stackFramePrecomputed_func_IFoo.foo = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@rubyStrFrozen_foo = internal unnamed_addr global i64 0, align 8
@"<void-singleton>" = internal unnamed_addr global i64 0
@"stackFramePrecomputed_func_IFoo.<static-init>" = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@"stackFramePrecomputed_func_IFoo.<static-init>$block_1" = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@"rubyIdPrecomputed_block for" = internal unnamed_addr global i64 0, align 8
@"str_block for" = private unnamed_addr constant [10 x i8] c"block for\00", align 1
@"rubyStrFrozen_block for" = internal unnamed_addr global i64 0, align 8
@ic_sig = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_sig = internal unnamed_addr global i64 0, align 8
@str_sig = private unnamed_addr constant [4 x i8] c"sig\00", align 1
@ic_abstract = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_abstract = internal unnamed_addr global i64 0, align 8
@str_abstract = private unnamed_addr constant [9 x i8] c"abstract\00", align 1
@ic_void = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_void = internal unnamed_addr global i64 0, align 8
@str_void = private unnamed_addr constant [5 x i8] c"void\00", align 1
@"str_T::Sig" = private unnamed_addr constant [7 x i8] c"T::Sig\00", align 1
@ic_extend = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_extend = internal unnamed_addr global i64 0, align 8
@str_extend = private unnamed_addr constant [7 x i8] c"extend\00", align 1
@"str_T::Helpers" = private unnamed_addr constant [11 x i8] c"T::Helpers\00", align 1
@ic_extend.1 = internal global %struct.FunctionInlineCache zeroinitializer
@"ic_abstract!" = internal global %struct.FunctionInlineCache zeroinitializer
@"rubyIdPrecomputed_abstract!" = internal unnamed_addr global i64 0, align 8
@"str_abstract!" = private unnamed_addr constant [10 x i8] c"abstract!\00", align 1
@rubyIdPrecomputed_normal = internal unnamed_addr global i64 0, align 8
@str_normal = private unnamed_addr constant [7 x i8] c"normal\00", align 1
@ic_keep_self_def = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_keep_self_def = internal unnamed_addr global i64 0, align 8
@str_keep_self_def = private unnamed_addr constant [14 x i8] c"keep_self_def\00", align 1
@stackFramePrecomputed_func_Foo.foo = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@"rubyStrFrozen_Override!" = internal unnamed_addr global i64 0, align 8
@"str_Override!" = private unnamed_addr constant [10 x i8] c"Override!\00", align 1
@ic_p.2 = internal global %struct.FunctionInlineCache zeroinitializer
@"stackFramePrecomputed_func_Foo.<static-init>" = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@"stackFramePrecomputed_func_Foo.<static-init>$block_1" = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@ic_sig.3 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_override = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_override = internal unnamed_addr global i64 0, align 8
@str_override = private unnamed_addr constant [9 x i8] c"override\00", align 1
@ic_void.4 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_keep_self_def.5 = internal global %struct.FunctionInlineCache zeroinitializer
@rb_cObject = external local_unnamed_addr constant i64
@"guard_epoch_T::Sig" = linkonce local_unnamed_addr global i64 0
@"guarded_const_T::Sig" = linkonce local_unnamed_addr global i64 0
@"guard_epoch_T::Helpers" = linkonce local_unnamed_addr global i64 0
@"guarded_const_T::Helpers" = linkonce local_unnamed_addr global i64 0
@guard_epoch_IFoo = linkonce local_unnamed_addr global i64 0
@guarded_const_IFoo = linkonce local_unnamed_addr global i64 0
@guard_epoch_Foo = linkonce local_unnamed_addr global i64 0
@guarded_const_Foo = linkonce local_unnamed_addr global i64 0
@rb_mKernel = external local_unnamed_addr constant i64

; Function Attrs: noreturn
declare void @sorbet_raiseArity(i32, i32, i32) local_unnamed_addr #0

declare %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64, i64, i64, i64, %struct.rb_iseq_struct*, i32, i32, i32, i64*, i32, i32) local_unnamed_addr #1

declare i64 @sorbet_getConstant(i8*, i64) local_unnamed_addr #1

declare i64 @sorbet_readRealpath() local_unnamed_addr #1

declare void @sorbet_pushStaticInitFrame(i64) local_unnamed_addr #1

declare void @sorbet_popRubyStack() local_unnamed_addr #1

declare void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache*, i64, i32, i32, i32, i64*) local_unnamed_addr #1

declare i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache*, i64) local_unnamed_addr #1

declare void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_iseq_struct*) local_unnamed_addr #1

declare i64 @rb_define_class(i8*, i64) local_unnamed_addr #1

declare void @rb_define_singleton_sorbet_method(i64, i8*, i64 (i32, i64*, i64)*, i8*, i8*) local_unnamed_addr #1

declare i64 @rb_intern2(i8*, i64) local_unnamed_addr #1

declare i64 @rb_id2sym(i64) local_unnamed_addr #1

declare i64 @rb_fstring_new(i8*, i64) local_unnamed_addr #1

declare void @rb_gc_register_mark_object(i64) local_unnamed_addr #1

; Function Attrs: noreturn
declare void @rb_raise(i64, i8*, ...) local_unnamed_addr #0

declare %struct.rb_callable_method_entry_struct* @rb_vm_frame_method_entry(%struct.rb_control_frame_struct*) local_unnamed_addr #1

declare %struct.rb_callable_method_entry_struct* @rb_callable_method_entry(i64, i64) local_unnamed_addr #1

declare i64 @rb_vm_call_kw(%struct.rb_execution_context_struct*, i64, i64, i32, i64*, %struct.rb_callable_method_entry_struct*, i32) local_unnamed_addr #1

; Function Attrs: alwaysinline nounwind ssp uwtable
define noalias nonnull i8* @sorbet_allocateParamInfo() local_unnamed_addr #2 {
  %1 = tail call noalias nonnull i8* @ruby_xcalloc(i64 1, i64 64) #10
  ret i8* %1
}

; Function Attrs: allocsize(0,1)
declare noalias nonnull i8* @ruby_xcalloc(i64, i64) local_unnamed_addr #3

; Function Attrs: nounwind ssp uwtable
define weak i32 @sorbet_getIsReleaseBuild() local_unnamed_addr #4 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !4
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* getelementptr inbounds ([93 x i8], [93 x i8]* @.str.9, i64 0, i64 0)) #11
  unreachable
}

; Function Attrs: nounwind ssp uwtable
define weak i8* @sorbet_getBuildSCMRevision() local_unnamed_addr #4 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !4
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* getelementptr inbounds ([95 x i8], [95 x i8]* @.str.8, i64 0, i64 0)) #11
  unreachable
}

; Function Attrs: sspreq
define void @Init_abstract_static_methods() local_unnamed_addr #5 {
entry:
  %locals1.i.i = alloca [0 x i64], align 8
  %realpath = tail call i64 @sorbet_readRealpath()
  %0 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 16) #8
  store i64 %0, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %1 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_foo, i64 0, i64 0), i64 3) #8
  store i64 %1, i64* @rubyIdPrecomputed_foo, align 8
  %2 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([2 x i8], [2 x i8]* @str_p, i64 0, i64 0), i64 1) #8
  store i64 %2, i64* @rubyIdPrecomputed_p, align 8
  %3 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([10 x i8], [10 x i8]* @"str_block for", i64 0, i64 0), i64 9) #8
  store i64 %3, i64* @"rubyIdPrecomputed_block for", align 8
  %4 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_sig, i64 0, i64 0), i64 3) #8
  store i64 %4, i64* @rubyIdPrecomputed_sig, align 8
  %5 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([9 x i8], [9 x i8]* @str_abstract, i64 0, i64 0), i64 8) #8
  store i64 %5, i64* @rubyIdPrecomputed_abstract, align 8
  %6 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_void, i64 0, i64 0), i64 4) #8
  store i64 %6, i64* @rubyIdPrecomputed_void, align 8
  %7 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([7 x i8], [7 x i8]* @str_extend, i64 0, i64 0), i64 6) #8
  store i64 %7, i64* @rubyIdPrecomputed_extend, align 8
  %8 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([10 x i8], [10 x i8]* @"str_abstract!", i64 0, i64 0), i64 9) #8
  store i64 %8, i64* @"rubyIdPrecomputed_abstract!", align 8
  %9 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([7 x i8], [7 x i8]* @str_normal, i64 0, i64 0), i64 6) #8
  store i64 %9, i64* @rubyIdPrecomputed_normal, align 8
  %10 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([14 x i8], [14 x i8]* @str_keep_self_def, i64 0, i64 0), i64 13) #8
  store i64 %10, i64* @rubyIdPrecomputed_keep_self_def, align 8
  %11 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([9 x i8], [9 x i8]* @str_override, i64 0, i64 0), i64 8) #8
  store i64 %11, i64* @rubyIdPrecomputed_override, align 8
  %12 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 16) #8
  tail call void @rb_gc_register_mark_object(i64 %12) #8
  store i64 %12, i64* @"rubyStrFrozen_<top (required)>", align 8
  %13 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([50 x i8], [50 x i8]* @"str_test/testdata/compiler/abstract_static_methods.rb", i64 0, i64 0), i64 49) #8
  tail call void @rb_gc_register_mark_object(i64 %13) #8
  store i64 %13, i64* @"rubyStrFrozen_test/testdata/compiler/abstract_static_methods.rb", align 8
  %14 = bitcast [0 x i64]* %locals1.i.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 0, i8* nonnull %14)
  %"rubyId_<top (required)>.i.i" = load i64, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %"rubyStr_<top (required)>.i.i" = load i64, i64* @"rubyStrFrozen_<top (required)>", align 8
  %locals1.sub.i.i = getelementptr inbounds [0 x i64], [0 x i64]* %locals1.i.i, i64 0, i64 0
  %15 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_<top (required)>.i.i", i64 %"rubyId_<top (required)>.i.i", i64 %13, i64 %realpath, %struct.rb_iseq_struct* null, i32 1, i32 1, i32 22, i64* nonnull %locals1.sub.i.i, i32 0, i32 2)
  store %struct.rb_iseq_struct* %15, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_<root>.<static-init>$152", align 8
  call void @llvm.lifetime.end.p0i8(i64 0, i8* nonnull %14)
  %rubyId_foo.i = load i64, i64* @rubyIdPrecomputed_foo, align 8, !dbg !8
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_foo, i64 %rubyId_foo.i, i32 16, i32 0, i32 0, i64* null), !dbg !8
  %rubyId_p.i = load i64, i64* @rubyIdPrecomputed_p, align 8, !dbg !13
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_p, i64 %rubyId_p.i, i32 20, i32 1, i32 0, i64* null), !dbg !13
  %16 = call i64 @rb_fstring_new(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_foo, i64 0, i64 0), i64 3) #8
  call void @rb_gc_register_mark_object(i64 %16) #8
  store i64 %16, i64* @rubyStrFrozen_foo, align 8
  call void @llvm.lifetime.start.p0i8(i64 0, i8* nonnull %14)
  %rubyId_foo.i.i = load i64, i64* @rubyIdPrecomputed_foo, align 8
  %"rubyStr_test/testdata/compiler/abstract_static_methods.rb.i27.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/abstract_static_methods.rb", align 8
  %17 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 %16, i64 %rubyId_foo.i.i, i64 %"rubyStr_test/testdata/compiler/abstract_static_methods.rb.i27.i", i64 %realpath, %struct.rb_iseq_struct* null, i32 1, i32 11, i32 11, i64* nonnull %locals1.sub.i.i, i32 0, i32 1)
  store %struct.rb_iseq_struct* %17, %struct.rb_iseq_struct** @stackFramePrecomputed_func_IFoo.foo, align 8
  call void @llvm.lifetime.end.p0i8(i64 0, i8* nonnull %14)
  %18 = call i64 @sorbet_getConstant(i8* getelementptr inbounds ([30 x i8], [30 x i8]* @sorbet_getVoidSingleton.name, i64 0, i64 0), i64 30) #8
  store i64 %18, i64* @"<void-singleton>", align 8
  call void @llvm.lifetime.start.p0i8(i64 0, i8* nonnull %14)
  %"rubyId_<top (required)>.i30.i" = load i64, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %"rubyStr_<top (required)>.i31.i" = load i64, i64* @"rubyStrFrozen_<top (required)>", align 8
  %"rubyStr_test/testdata/compiler/abstract_static_methods.rb.i32.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/abstract_static_methods.rb", align 8
  %19 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_<top (required)>.i31.i", i64 %"rubyId_<top (required)>.i30.i", i64 %"rubyStr_test/testdata/compiler/abstract_static_methods.rb.i32.i", i64 %realpath, %struct.rb_iseq_struct* null, i32 1, i32 5, i32 5, i64* nonnull %locals1.sub.i.i, i32 0, i32 4)
  store %struct.rb_iseq_struct* %19, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_IFoo.<static-init>", align 8
  call void @llvm.lifetime.end.p0i8(i64 0, i8* nonnull %14)
  %20 = call i64 @rb_fstring_new(i8* getelementptr inbounds ([10 x i8], [10 x i8]* @"str_block for", i64 0, i64 0), i64 9) #8
  call void @rb_gc_register_mark_object(i64 %20) #8
  store i64 %20, i64* @"rubyStrFrozen_block for", align 8
  %stackFrame.i.i = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_IFoo.<static-init>", align 8
  %"rubyId_block for.i.i" = load i64, i64* @"rubyIdPrecomputed_block for", align 8
  %"rubyStr_test/testdata/compiler/abstract_static_methods.rb.i34.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/abstract_static_methods.rb", align 8
  %21 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 %20, i64 %"rubyId_block for.i.i", i64 %"rubyStr_test/testdata/compiler/abstract_static_methods.rb.i34.i", i64 %realpath, %struct.rb_iseq_struct* %stackFrame.i.i, i32 2, i32 5, i32 5, i64* null, i32 0, i32 4)
  store %struct.rb_iseq_struct* %21, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_IFoo.<static-init>$block_1", align 8
  %rubyId_sig.i = load i64, i64* @rubyIdPrecomputed_sig, align 8, !dbg !14
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_sig, i64 %rubyId_sig.i, i32 20, i32 1, i32 0, i64* null), !dbg !14
  %rubyId_abstract.i = load i64, i64* @rubyIdPrecomputed_abstract, align 8, !dbg !16
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_abstract, i64 %rubyId_abstract.i, i32 20, i32 0, i32 0, i64* null), !dbg !16
  %rubyId_void.i = load i64, i64* @rubyIdPrecomputed_void, align 8, !dbg !16
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_void, i64 %rubyId_void.i, i32 16, i32 0, i32 0, i64* null), !dbg !16
  %rubyId_extend.i = load i64, i64* @rubyIdPrecomputed_extend, align 8, !dbg !18
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_extend, i64 %rubyId_extend.i, i32 20, i32 1, i32 0, i64* null), !dbg !18
  %rubyId_extend9.i = load i64, i64* @rubyIdPrecomputed_extend, align 8, !dbg !19
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_extend.1, i64 %rubyId_extend9.i, i32 20, i32 1, i32 0, i64* null), !dbg !19
  %"rubyId_abstract!.i" = load i64, i64* @"rubyIdPrecomputed_abstract!", align 8, !dbg !20
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @"ic_abstract!", i64 %"rubyId_abstract!.i", i32 20, i32 0, i32 0, i64* null), !dbg !20
  %rubyId_keep_self_def.i = load i64, i64* @rubyIdPrecomputed_keep_self_def, align 8, !dbg !21
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_keep_self_def, i64 %rubyId_keep_self_def.i, i32 16, i32 3, i32 0, i64* null), !dbg !21
  call void @llvm.lifetime.start.p0i8(i64 0, i8* nonnull %14)
  %rubyId_foo.i36.i = load i64, i64* @rubyIdPrecomputed_foo, align 8
  %rubyStr_foo.i37.i = load i64, i64* @rubyStrFrozen_foo, align 8
  %"rubyStr_test/testdata/compiler/abstract_static_methods.rb.i38.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/abstract_static_methods.rb", align 8
  %22 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 %rubyStr_foo.i37.i, i64 %rubyId_foo.i36.i, i64 %"rubyStr_test/testdata/compiler/abstract_static_methods.rb.i38.i", i64 %realpath, %struct.rb_iseq_struct* null, i32 1, i32 17, i32 19, i64* nonnull %locals1.sub.i.i, i32 0, i32 2)
  store %struct.rb_iseq_struct* %22, %struct.rb_iseq_struct** @stackFramePrecomputed_func_Foo.foo, align 8
  call void @llvm.lifetime.end.p0i8(i64 0, i8* nonnull %14)
  %23 = call i64 @rb_fstring_new(i8* getelementptr inbounds ([10 x i8], [10 x i8]* @"str_Override!", i64 0, i64 0), i64 9) #8
  call void @rb_gc_register_mark_object(i64 %23) #8
  store i64 %23, i64* @"rubyStrFrozen_Override!", align 8
  %rubyId_p15.i = load i64, i64* @rubyIdPrecomputed_p, align 8, !dbg !22
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_p.2, i64 %rubyId_p15.i, i32 16, i32 1, i32 0, i64* null), !dbg !22
  call void @llvm.lifetime.start.p0i8(i64 0, i8* nonnull %14)
  %"rubyId_<top (required)>.i41.i" = load i64, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %"rubyStr_<top (required)>.i42.i" = load i64, i64* @"rubyStrFrozen_<top (required)>", align 8
  %"rubyStr_test/testdata/compiler/abstract_static_methods.rb.i43.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/abstract_static_methods.rb", align 8
  %24 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_<top (required)>.i42.i", i64 %"rubyId_<top (required)>.i41.i", i64 %"rubyStr_test/testdata/compiler/abstract_static_methods.rb.i43.i", i64 %realpath, %struct.rb_iseq_struct* null, i32 1, i32 14, i32 14, i64* nonnull %locals1.sub.i.i, i32 0, i32 4)
  store %struct.rb_iseq_struct* %24, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Foo.<static-init>", align 8
  call void @llvm.lifetime.end.p0i8(i64 0, i8* nonnull %14)
  %"rubyId_block for.i46.i" = load i64, i64* @"rubyIdPrecomputed_block for", align 8
  %"rubyStr_block for.i47.i" = load i64, i64* @"rubyStrFrozen_block for", align 8
  %"rubyStr_test/testdata/compiler/abstract_static_methods.rb.i48.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/abstract_static_methods.rb", align 8
  %25 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_block for.i47.i", i64 %"rubyId_block for.i46.i", i64 %"rubyStr_test/testdata/compiler/abstract_static_methods.rb.i48.i", i64 %realpath, %struct.rb_iseq_struct* %24, i32 2, i32 14, i32 14, i64* null, i32 0, i32 4)
  store %struct.rb_iseq_struct* %25, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Foo.<static-init>$block_1", align 8
  %rubyId_sig17.i = load i64, i64* @rubyIdPrecomputed_sig, align 8, !dbg !24
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_sig.3, i64 %rubyId_sig17.i, i32 20, i32 1, i32 0, i64* null), !dbg !24
  %rubyId_override.i = load i64, i64* @rubyIdPrecomputed_override, align 8, !dbg !26
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_override, i64 %rubyId_override.i, i32 20, i32 0, i32 0, i64* null), !dbg !26
  %rubyId_void22.i = load i64, i64* @rubyIdPrecomputed_void, align 8, !dbg !26
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_void.4, i64 %rubyId_void22.i, i32 16, i32 0, i32 0, i64* null), !dbg !26
  %rubyId_keep_self_def24.i = load i64, i64* @rubyIdPrecomputed_keep_self_def, align 8, !dbg !28
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_keep_self_def.5, i64 %rubyId_keep_self_def24.i, i32 16, i32 3, i32 0, i64* null), !dbg !28
  %26 = load %struct.rb_vm_struct*, %struct.rb_vm_struct** @ruby_current_vm_ptr, align 8, !tbaa !29
  %27 = getelementptr inbounds %struct.rb_vm_struct, %struct.rb_vm_struct* %26, i64 0, i32 18
  %28 = load i64, i64* %27, align 8, !tbaa !31
  %stackFrame.i = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_<root>.<static-init>$152", align 8
  %29 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !29
  %30 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %29, i64 0, i32 2
  %31 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %30, align 8, !tbaa !41
  %32 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %31, i64 0, i32 2
  store %struct.rb_iseq_struct* %stackFrame.i, %struct.rb_iseq_struct** %32, align 8, !tbaa !44
  %33 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %31, i64 0, i32 4
  %34 = load i64*, i64** %33, align 8, !tbaa !46
  %35 = load i64, i64* %34, align 8, !tbaa !4
  %36 = and i64 %35, -33
  store i64 %36, i64* %34, align 8, !tbaa !4
  call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* %29, %struct.rb_control_frame_struct* %31, %struct.rb_iseq_struct* %stackFrame.i) #8
  %37 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %31, i64 0, i32 0
  %38 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %32, align 8, !tbaa !44
  %39 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %38, i64 0, i32 2
  %40 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %39, align 8, !tbaa !47
  %41 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %40, i64 0, i32 2
  %42 = load i64*, i64** %41, align 8, !tbaa !49
  %43 = getelementptr inbounds i64, i64* %42, i64 5
  store i64* %43, i64** %37, align 8, !dbg !58, !tbaa !29
  %44 = load i64, i64* @rb_cObject, align 8, !dbg !59
  %45 = call i64 @rb_define_class(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_IFoo, i64 0, i64 0), i64 %44) #8, !dbg !59
  call void @sorbet_pushStaticInitFrame(i64 %45) #8, !dbg !59
  %stackFrame.i1.i = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_IFoo.<static-init>", align 8
  %46 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !29
  %47 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %46, i64 0, i32 2
  %48 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %47, align 8, !tbaa !41
  %49 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %48, i64 0, i32 2
  store %struct.rb_iseq_struct* %stackFrame.i1.i, %struct.rb_iseq_struct** %49, align 8, !tbaa !44
  %50 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %48, i64 0, i32 4
  %51 = load i64*, i64** %50, align 8, !tbaa !46
  %52 = load i64, i64* %51, align 8, !tbaa !4
  %53 = and i64 %52, -33
  store i64 %53, i64* %51, align 8, !tbaa !4
  call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* %46, %struct.rb_control_frame_struct* %48, %struct.rb_iseq_struct* %stackFrame.i1.i) #8
  %54 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %48, i64 0, i32 0
  %55 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %49, align 8, !tbaa !44
  %56 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %55, i64 0, i32 2
  %57 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %56, align 8, !tbaa !47
  %58 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %57, i64 0, i32 2
  %59 = load i64*, i64** %58, align 8, !tbaa !49
  %60 = getelementptr inbounds i64, i64* %59, i64 2, !dbg !60
  store i64* %60, i64** %54, align 8, !dbg !60, !tbaa !29
  %61 = load i64, i64* @"guard_epoch_T::Sig", align 8, !dbg !62
  %62 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !62, !tbaa !63
  %needTakeSlowPath = icmp eq i64 %61, %62, !dbg !62
  br i1 %needTakeSlowPath, label %64, label %63, !dbg !62, !prof !64

63:                                               ; preds = %entry
  call void @"const_recompute_T::Sig"(), !dbg !62
  br label %64, !dbg !62

64:                                               ; preds = %entry, %63
  %65 = load i64, i64* @"guarded_const_T::Sig", align 8, !dbg !62
  %66 = load i64, i64* @"guard_epoch_T::Sig", align 8, !dbg !62
  %67 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !62, !tbaa !63
  %guardUpdated = icmp eq i64 %66, %67, !dbg !62
  call void @llvm.assume(i1 %guardUpdated), !dbg !62
  %68 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !62, !tbaa !29
  %69 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %68, i64 0, i32 2, !dbg !62
  %70 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %69, align 8, !dbg !62, !tbaa !41
  %71 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %70, i64 0, i32 1, !dbg !62
  %72 = load i64*, i64** %71, align 8, !dbg !62, !tbaa !65
  %73 = getelementptr inbounds i64, i64* %72, i64 1, !dbg !62
  store i64 %45, i64* %72, align 8, !dbg !62, !tbaa !4
  %74 = getelementptr inbounds i64, i64* %72, i64 2, !dbg !62
  store i64* %74, i64** %71, align 8, !dbg !62, !tbaa !65
  store i64 %65, i64* %73, align 8, !dbg !62, !tbaa !4
  %send.i.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_extend, i64 0) #8, !dbg !62
  %75 = getelementptr inbounds i64, i64* %59, i64 3, !dbg !62
  store i64* %75, i64** %54, align 8, !dbg !62, !tbaa !29
  %76 = load i64, i64* @"guard_epoch_T::Helpers", align 8, !dbg !66
  %77 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !66, !tbaa !63
  %needTakeSlowPath3 = icmp eq i64 %76, %77, !dbg !66
  br i1 %needTakeSlowPath3, label %79, label %78, !dbg !66, !prof !64

78:                                               ; preds = %64
  call void @"const_recompute_T::Helpers"(), !dbg !66
  br label %79, !dbg !66

79:                                               ; preds = %64, %78
  %80 = load i64, i64* @"guarded_const_T::Helpers", align 8, !dbg !66
  %81 = load i64, i64* @"guard_epoch_T::Helpers", align 8, !dbg !66
  %82 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !66, !tbaa !63
  %guardUpdated4 = icmp eq i64 %81, %82, !dbg !66
  call void @llvm.assume(i1 %guardUpdated4), !dbg !66
  %83 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !66, !tbaa !29
  %84 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %83, i64 0, i32 2, !dbg !66
  %85 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %84, align 8, !dbg !66, !tbaa !41
  %86 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %85, i64 0, i32 1, !dbg !66
  %87 = load i64*, i64** %86, align 8, !dbg !66, !tbaa !65
  %88 = getelementptr inbounds i64, i64* %87, i64 1, !dbg !66
  store i64 %45, i64* %87, align 8, !dbg !66, !tbaa !4
  %89 = getelementptr inbounds i64, i64* %87, i64 2, !dbg !66
  store i64* %89, i64** %86, align 8, !dbg !66, !tbaa !65
  store i64 %80, i64* %88, align 8, !dbg !66, !tbaa !4
  %send40.i.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_extend.1, i64 0) #8, !dbg !66
  %90 = getelementptr inbounds i64, i64* %59, i64 4, !dbg !66
  store i64* %90, i64** %54, align 8, !dbg !66, !tbaa !29
  %91 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !67, !tbaa !29
  %92 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %91, i64 0, i32 2, !dbg !67
  %93 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %92, align 8, !dbg !67, !tbaa !41
  %94 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %93, i64 0, i32 1, !dbg !67
  %95 = load i64*, i64** %94, align 8, !dbg !67, !tbaa !65
  %96 = getelementptr inbounds i64, i64* %95, i64 1, !dbg !67
  store i64* %96, i64** %94, align 8, !dbg !67, !tbaa !65
  store i64 %45, i64* %95, align 8, !dbg !67, !tbaa !4
  %send44.i.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @"ic_abstract!", i64 0) #8, !dbg !67
  %97 = getelementptr inbounds i64, i64* %59, i64 7, !dbg !67
  store i64* %97, i64** %54, align 8, !dbg !67, !tbaa !29
  %rubyId_foo.i2.i = load i64, i64* @rubyIdPrecomputed_foo, align 8, !dbg !68
  %rawSym.i3.i = call i64 @rb_id2sym(i64 %rubyId_foo.i2.i) #8, !dbg !68
  %rubyId_normal.i4.i = load i64, i64* @rubyIdPrecomputed_normal, align 8, !dbg !68
  %rawSym45.i.i = call i64 @rb_id2sym(i64 %rubyId_normal.i4.i) #8, !dbg !68
  %98 = load i64, i64* @guard_epoch_IFoo, align 8, !dbg !68
  %99 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !68, !tbaa !63
  %needTakeSlowPath5 = icmp eq i64 %98, %99, !dbg !68
  br i1 %needTakeSlowPath5, label %101, label %100, !dbg !68, !prof !64

100:                                              ; preds = %79
  call void @const_recompute_IFoo(), !dbg !68
  br label %101, !dbg !68

101:                                              ; preds = %79, %100
  %102 = load i64, i64* @guarded_const_IFoo, align 8, !dbg !68
  %103 = load i64, i64* @guard_epoch_IFoo, align 8, !dbg !68
  %104 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !68, !tbaa !63
  %guardUpdated6 = icmp eq i64 %103, %104, !dbg !68
  call void @llvm.assume(i1 %guardUpdated6), !dbg !68
  %stackFrame471.i.i = load i8*, i8** bitcast (%struct.rb_iseq_struct** @stackFramePrecomputed_func_IFoo.foo to i8**), align 8, !dbg !68
  %105 = call noalias nonnull i8* @ruby_xcalloc(i64 1, i64 64) #10, !dbg !68
  %106 = bitcast i8* %105 to i16*, !dbg !68
  %107 = load i16, i16* %106, align 8, !dbg !68
  %108 = and i16 %107, -384, !dbg !68
  store i16 %108, i16* %106, align 8, !dbg !68
  %109 = getelementptr inbounds i8, i8* %105, i64 4, !dbg !68
  call void @llvm.memset.p0i8.i64(i8* nonnull align 4 %109, i8 0, i64 28, i1 false) #8, !dbg !68
  call void @rb_define_singleton_sorbet_method(i64 %102, i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_foo, i64 0, i64 0), i64 (i32, i64*, i64)* nonnull @func_IFoo.foo, i8* nonnull %105, i8* %stackFrame471.i.i) #8, !dbg !68
  call void @sorbet_popRubyStack() #8, !dbg !59
  %110 = getelementptr inbounds i64, i64* %42, i64 14, !dbg !59
  store i64* %110, i64** %37, align 8, !dbg !59, !tbaa !29
  %111 = call i64 @rb_define_class(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_Foo, i64 0, i64 0), i64 %102) #8, !dbg !69
  call void @sorbet_pushStaticInitFrame(i64 %111) #8, !dbg !69
  %stackFrame.i.i1 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Foo.<static-init>", align 8
  %112 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !29
  %113 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %112, i64 0, i32 2
  %114 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %113, align 8, !tbaa !41
  %115 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %114, i64 0, i32 2
  store %struct.rb_iseq_struct* %stackFrame.i.i1, %struct.rb_iseq_struct** %115, align 8, !tbaa !44
  %116 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %114, i64 0, i32 4
  %117 = load i64*, i64** %116, align 8, !tbaa !46
  %118 = load i64, i64* %117, align 8, !tbaa !4
  %119 = and i64 %118, -33
  store i64 %119, i64* %117, align 8, !tbaa !4
  call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* %112, %struct.rb_control_frame_struct* %114, %struct.rb_iseq_struct* %stackFrame.i.i1) #8
  %120 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %114, i64 0, i32 0
  %121 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %115, align 8, !tbaa !44
  %122 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %121, i64 0, i32 2
  %123 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %122, align 8, !tbaa !47
  %124 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %123, i64 0, i32 2
  %125 = load i64*, i64** %124, align 8, !tbaa !49
  %126 = getelementptr inbounds i64, i64* %125, i64 4, !dbg !70
  store i64* %126, i64** %120, align 8, !dbg !70, !tbaa !29
  %rubyId_foo.i.i2 = load i64, i64* @rubyIdPrecomputed_foo, align 8, !dbg !72
  %rawSym.i.i = call i64 @rb_id2sym(i64 %rubyId_foo.i.i2) #8, !dbg !72
  %rubyId_normal.i.i = load i64, i64* @rubyIdPrecomputed_normal, align 8, !dbg !72
  %rawSym20.i.i = call i64 @rb_id2sym(i64 %rubyId_normal.i.i) #8, !dbg !72
  %127 = load i64, i64* @guard_epoch_Foo, align 8, !dbg !72
  %128 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !72, !tbaa !63
  %needTakeSlowPath7 = icmp eq i64 %127, %128, !dbg !72
  br i1 %needTakeSlowPath7, label %130, label %129, !dbg !72, !prof !64

129:                                              ; preds = %101
  call void @const_recompute_Foo(), !dbg !72
  br label %130, !dbg !72

130:                                              ; preds = %101, %129
  %131 = load i64, i64* @guarded_const_Foo, align 8, !dbg !72
  %132 = load i64, i64* @guard_epoch_Foo, align 8, !dbg !72
  %133 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !72, !tbaa !63
  %guardUpdated8 = icmp eq i64 %132, %133, !dbg !72
  call void @llvm.assume(i1 %guardUpdated8), !dbg !72
  %stackFrame221.i.i = load i8*, i8** bitcast (%struct.rb_iseq_struct** @stackFramePrecomputed_func_Foo.foo to i8**), align 8, !dbg !72
  %134 = call noalias nonnull i8* @ruby_xcalloc(i64 1, i64 64) #10, !dbg !72
  %135 = bitcast i8* %134 to i16*, !dbg !72
  %136 = load i16, i16* %135, align 8, !dbg !72
  %137 = and i16 %136, -384, !dbg !72
  store i16 %137, i16* %135, align 8, !dbg !72
  %138 = getelementptr inbounds i8, i8* %134, i64 4, !dbg !72
  call void @llvm.memset.p0i8.i64(i8* nonnull align 4 %138, i8 0, i64 28, i1 false) #8, !dbg !72
  call void @rb_define_singleton_sorbet_method(i64 %131, i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_foo, i64 0, i64 0), i64 (i32, i64*, i64)* nonnull @func_Foo.foo, i8* nonnull %134, i8* %stackFrame221.i.i) #8, !dbg !72
  call void @sorbet_popRubyStack() #8, !dbg !69
  %139 = getelementptr inbounds i64, i64* %42, i64 22, !dbg !69
  store i64* %139, i64** %37, align 8, !dbg !69, !tbaa !29
  %140 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !8, !tbaa !29
  %141 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %140, i64 0, i32 2, !dbg !8
  %142 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %141, align 8, !dbg !8, !tbaa !41
  %143 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %142, i64 0, i32 1, !dbg !8
  %144 = load i64*, i64** %143, align 8, !dbg !8, !tbaa !65
  %145 = getelementptr inbounds i64, i64* %144, i64 1, !dbg !8
  store i64* %145, i64** %143, align 8, !dbg !8, !tbaa !65
  store i64 %131, i64* %144, align 8, !dbg !8, !tbaa !4
  %send.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_foo, i64 0) #8, !dbg !8
  %146 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !13, !tbaa !29
  %147 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %146, i64 0, i32 2, !dbg !13
  %148 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %147, align 8, !dbg !13, !tbaa !41
  %149 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %148, i64 0, i32 1, !dbg !13
  %150 = load i64*, i64** %149, align 8, !dbg !13, !tbaa !65
  %151 = getelementptr inbounds i64, i64* %150, i64 1, !dbg !13
  store i64 %28, i64* %150, align 8, !dbg !13, !tbaa !4
  %152 = getelementptr inbounds i64, i64* %150, i64 2, !dbg !13
  store i64* %152, i64** %149, align 8, !dbg !13, !tbaa !65
  store i64 %send.i, i64* %151, align 8, !dbg !13, !tbaa !4
  %send28.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_p, i64 0) #8, !dbg !13
  ret void
}

; Function Attrs: nounwind sspreq uwtable
define i64 @func_IFoo.foo(i32 %argc, i64* nocapture readnone %argArray, i64 %selfRaw) #6 !dbg !73 {
functionEntryInitializers:
  %0 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !29
  %1 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %0, i64 0, i32 2
  %2 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %1, align 8, !tbaa !41
  %3 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 0
  %4 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 2
  %5 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %4, align 8, !tbaa !44
  %6 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %5, i64 0, i32 2
  %7 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %6, align 8, !tbaa !47
  %8 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %7, i64 0, i32 2
  %9 = load i64*, i64** %8, align 8, !tbaa !49
  %10 = getelementptr inbounds i64, i64* %9, i64 1
  store i64* %10, i64** %3, align 8, !tbaa !29
  %tooManyArgs = icmp eq i32 %argc, 0, !dbg !74
  br i1 %tooManyArgs, label %fillRequiredArgs, label %argCountFailBlock, !dbg !74, !prof !75

argCountFailBlock:                                ; preds = %functionEntryInitializers
  tail call void @sorbet_raiseArity(i32 %argc, i32 0, i32 0) #8, !dbg !74
  unreachable, !dbg !74

fillRequiredArgs:                                 ; preds = %functionEntryInitializers
  %11 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !74, !tbaa !29
  %12 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %11, i64 0, i32 2, !dbg !74
  %13 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %12, align 8, !dbg !74, !tbaa !41, !noalias !76
  %14 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %13, i64 0, i32 3, !dbg !74
  %15 = load i64, i64* %14, align 8, !dbg !74, !tbaa !79, !noalias !76
  %16 = tail call %struct.rb_callable_method_entry_struct* @rb_vm_frame_method_entry(%struct.rb_control_frame_struct* %13) #8, !dbg !74, !noalias !76
  %17 = getelementptr inbounds %struct.rb_callable_method_entry_struct, %struct.rb_callable_method_entry_struct* %16, i64 0, i32 1, !dbg !74
  %18 = bitcast i64* %17 to %struct.RClass**, !dbg !74
  %19 = load %struct.RClass*, %struct.RClass** %18, align 8, !dbg !74, !tbaa !80, !noalias !76
  %20 = getelementptr inbounds %struct.RClass, %struct.RClass* %19, i64 0, i32 2, !dbg !74
  %21 = load %struct.rb_classext_struct*, %struct.rb_classext_struct** %20, align 8, !dbg !74, !tbaa !82, !noalias !76
  %22 = getelementptr inbounds %struct.rb_classext_struct, %struct.rb_classext_struct* %21, i64 0, i32 8, !dbg !74
  %23 = bitcast i64* %22 to %struct.RClass**, !dbg !74
  %24 = load %struct.RClass*, %struct.RClass** %23, align 8, !dbg !74, !tbaa !85, !noalias !76
  %25 = getelementptr inbounds %struct.RClass, %struct.RClass* %24, i64 0, i32 1, !dbg !74
  %26 = load i64, i64* %25, align 8, !dbg !74, !tbaa !87
  %27 = getelementptr inbounds %struct.rb_callable_method_entry_struct, %struct.rb_callable_method_entry_struct* %16, i64 0, i32 2, !dbg !74
  %28 = load %struct.rb_method_definition_struct*, %struct.rb_method_definition_struct** %27, align 8, !dbg !74, !tbaa !88, !noalias !76
  %29 = getelementptr inbounds %struct.rb_method_definition_struct, %struct.rb_method_definition_struct* %28, i64 0, i32 2, !dbg !74
  %30 = load i64, i64* %29, align 8, !dbg !74, !tbaa !89, !noalias !76
  %31 = tail call %struct.rb_callable_method_entry_struct* @rb_callable_method_entry(i64 %26, i64 %30) #8, !dbg !74, !noalias !76
  %32 = icmp eq %struct.rb_callable_method_entry_struct* %31, null, !dbg !74
  br i1 %32, label %33, label %sorbet_callSuper.exit, !dbg !74

33:                                               ; preds = %fillRequiredArgs
  %34 = load i64, i64* @rb_eRuntimeError, align 8, !dbg !74, !tbaa !4
  tail call void (i64, i8*, ...) @rb_raise(i64 %34, i8* getelementptr inbounds ([42 x i8], [42 x i8]* @.str.6, i64 0, i64 0)) #11, !dbg !74
  unreachable, !dbg !74

sorbet_callSuper.exit:                            ; preds = %fillRequiredArgs
  %35 = tail call i64 @rb_vm_call_kw(%struct.rb_execution_context_struct* %11, i64 %15, i64 %30, i32 0, i64* null, %struct.rb_callable_method_entry_struct* nonnull %31, i32 0) #8, !dbg !74
  %"<void-singleton>" = load i64, i64* @"<void-singleton>", align 8
  ret i64 %"<void-singleton>"
}

; Function Attrs: nounwind sspreq uwtable
define i64 @func_Foo.foo(i32 %argc, i64* nocapture readnone %argArray, i64 %selfRaw) #6 !dbg !23 {
functionEntryInitializers:
  %0 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !29
  %1 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %0, i64 0, i32 2
  %2 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %1, align 8, !tbaa !41
  %3 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 0
  %4 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 2
  %5 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %4, align 8, !tbaa !44
  %6 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %5, i64 0, i32 2
  %7 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %6, align 8, !tbaa !47
  %8 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %7, i64 0, i32 2
  %9 = load i64*, i64** %8, align 8, !tbaa !49
  %10 = getelementptr inbounds i64, i64* %9, i64 1
  store i64* %10, i64** %3, align 8, !tbaa !29
  %tooManyArgs = icmp eq i32 %argc, 0, !dbg !91
  br i1 %tooManyArgs, label %fillRequiredArgs, label %argCountFailBlock, !dbg !91, !prof !75

argCountFailBlock:                                ; preds = %functionEntryInitializers
  tail call void @sorbet_raiseArity(i32 %argc, i32 0, i32 0) #8, !dbg !91
  unreachable, !dbg !91

fillRequiredArgs:                                 ; preds = %functionEntryInitializers
  %11 = getelementptr inbounds i64, i64* %9, i64 2, !dbg !92
  store i64* %11, i64** %3, align 8, !dbg !92, !tbaa !29
  %"rubyStr_Override!" = load i64, i64* @"rubyStrFrozen_Override!", align 8, !dbg !93
  %12 = load i64, i64* @rb_mKernel, align 8, !dbg !22
  %13 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !22, !tbaa !29
  %14 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %13, i64 0, i32 2, !dbg !22
  %15 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %14, align 8, !dbg !22, !tbaa !41
  %16 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %15, i64 0, i32 1, !dbg !22
  %17 = load i64*, i64** %16, align 8, !dbg !22, !tbaa !65
  %18 = getelementptr inbounds i64, i64* %17, i64 1, !dbg !22
  store i64 %12, i64* %17, align 8, !dbg !22, !tbaa !4
  %19 = getelementptr inbounds i64, i64* %17, i64 2, !dbg !22
  store i64* %19, i64** %16, align 8, !dbg !22, !tbaa !65
  store i64 %"rubyStr_Override!", i64* %18, align 8, !dbg !22, !tbaa !4
  %send = tail call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_p.2, i64 0) #8, !dbg !22
  %"<void-singleton>" = load i64, i64* @"<void-singleton>", align 8
  ret i64 %"<void-singleton>"
}

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #7

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.end.p0i8(i64 immarg, i8* nocapture) #7

; Function Attrs: argmemonly nounwind
declare void @llvm.memset.p0i8.i64(i8* nocapture writeonly, i8, i64, i1 immarg) #7

; Function Attrs: nounwind
declare void @llvm.assume(i1) #8

; Function Attrs: ssp
define linkonce void @"const_recompute_T::Sig"() local_unnamed_addr #9 {
  %1 = tail call i64 @sorbet_getConstant(i8* getelementptr inbounds ([7 x i8], [7 x i8]* @"str_T::Sig", i64 0, i64 0), i64 6)
  store i64 %1, i64* @"guarded_const_T::Sig", align 8
  %2 = load i64, i64* @ruby_vm_global_constant_state, align 8, !tbaa !63
  store i64 %2, i64* @"guard_epoch_T::Sig", align 8
  ret void
}

; Function Attrs: ssp
define linkonce void @"const_recompute_T::Helpers"() local_unnamed_addr #9 {
  %1 = tail call i64 @sorbet_getConstant(i8* getelementptr inbounds ([11 x i8], [11 x i8]* @"str_T::Helpers", i64 0, i64 0), i64 10)
  store i64 %1, i64* @"guarded_const_T::Helpers", align 8
  %2 = load i64, i64* @ruby_vm_global_constant_state, align 8, !tbaa !63
  store i64 %2, i64* @"guard_epoch_T::Helpers", align 8
  ret void
}

; Function Attrs: ssp
define linkonce void @const_recompute_IFoo() local_unnamed_addr #9 {
  %1 = tail call i64 @sorbet_getConstant(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_IFoo, i64 0, i64 0), i64 4)
  store i64 %1, i64* @guarded_const_IFoo, align 8
  %2 = load i64, i64* @ruby_vm_global_constant_state, align 8, !tbaa !63
  store i64 %2, i64* @guard_epoch_IFoo, align 8
  ret void
}

; Function Attrs: ssp
define linkonce void @const_recompute_Foo() local_unnamed_addr #9 {
  %1 = tail call i64 @sorbet_getConstant(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_Foo, i64 0, i64 0), i64 3)
  store i64 %1, i64* @guarded_const_Foo, align 8
  %2 = load i64, i64* @ruby_vm_global_constant_state, align 8, !tbaa !63
  store i64 %2, i64* @guard_epoch_Foo, align 8
  ret void
}

attributes #0 = { noreturn }
attributes #1 = { "addedToSilenceEmptyAttrsError" }
attributes #2 = { alwaysinline nounwind ssp uwtable }
attributes #3 = { allocsize(0,1) }
attributes #4 = { nounwind ssp uwtable }
attributes #5 = { sspreq }
attributes #6 = { nounwind sspreq uwtable }
attributes #7 = { argmemonly nounwind }
attributes #8 = { nounwind }
attributes #9 = { ssp }
attributes #10 = { nounwind allocsize(0,1) }
attributes #11 = { noreturn nounwind }

!llvm.module.flags = !{!0}
!llvm.dbg.cu = !{!1}

!0 = !{i32 2, !"Debug Info Version", i32 3}
!1 = distinct !DICompileUnit(language: DW_LANG_C, file: !2, producer: "Sorbet LLVM", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, enums: !3)
!2 = !DIFile(filename: "test/testdata/compiler/abstract_static_methods.rb", directory: ".")
!3 = !{}
!4 = !{!5, !5, i64 0}
!5 = !{!"long", !6, i64 0}
!6 = !{!"omnipotent char", !7, i64 0}
!7 = !{!"Simple C/C++ TBAA"}
!8 = !DILocation(line: 22, column: 3, scope: !9)
!9 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.<static-init>$152", scope: null, file: !2, line: 5, type: !10, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!10 = !DISubroutineType(types: !11)
!11 = !{!12}
!12 = !DIBasicType(name: "VALUE", size: 64, encoding: DW_ATE_signed)
!13 = !DILocation(line: 22, column: 1, scope: !9)
!14 = !DILocation(line: 10, column: 3, scope: !15)
!15 = distinct !DISubprogram(name: "IFoo.<static-init>", linkageName: "func_IFoo.<static-init>L62", scope: null, file: !2, line: 5, type: !10, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!16 = !DILocation(line: 10, column: 8, scope: !17)
!17 = distinct !DISubprogram(name: "IFoo.<static-init>", linkageName: "func_IFoo.<static-init>L62$block_1", scope: !15, file: !2, line: 5, type: !10, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!18 = !DILocation(line: 6, column: 3, scope: !15)
!19 = !DILocation(line: 7, column: 3, scope: !15)
!20 = !DILocation(line: 8, column: 3, scope: !15)
!21 = !DILocation(line: 11, column: 3, scope: !15)
!22 = !DILocation(line: 18, column: 5, scope: !23)
!23 = distinct !DISubprogram(name: "Foo.foo", linkageName: "func_Foo.foo", scope: null, file: !2, line: 17, type: !10, scopeLine: 17, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!24 = !DILocation(line: 16, column: 3, scope: !25)
!25 = distinct !DISubprogram(name: "Foo.<static-init>", linkageName: "func_Foo.<static-init>L169", scope: null, file: !2, line: 14, type: !10, scopeLine: 14, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!26 = !DILocation(line: 16, column: 8, scope: !27)
!27 = distinct !DISubprogram(name: "Foo.<static-init>", linkageName: "func_Foo.<static-init>L169$block_1", scope: !25, file: !2, line: 14, type: !10, scopeLine: 14, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!28 = !DILocation(line: 17, column: 3, scope: !25)
!29 = !{!30, !30, i64 0}
!30 = !{!"any pointer", !6, i64 0}
!31 = !{!32, !5, i64 400}
!32 = !{!"rb_vm_struct", !5, i64 0, !33, i64 8, !30, i64 192, !30, i64 200, !30, i64 208, !37, i64 216, !6, i64 224, !34, i64 264, !34, i64 280, !34, i64 296, !34, i64 312, !5, i64 328, !36, i64 336, !36, i64 340, !36, i64 344, !36, i64 344, !36, i64 344, !36, i64 344, !36, i64 348, !5, i64 352, !6, i64 360, !5, i64 400, !5, i64 408, !5, i64 416, !5, i64 424, !5, i64 432, !5, i64 440, !5, i64 448, !30, i64 456, !30, i64 464, !38, i64 472, !39, i64 992, !30, i64 1016, !30, i64 1024, !36, i64 1032, !36, i64 1036, !34, i64 1040, !6, i64 1056, !5, i64 1096, !5, i64 1104, !5, i64 1112, !5, i64 1120, !5, i64 1128, !36, i64 1136, !30, i64 1144, !30, i64 1152, !30, i64 1160, !30, i64 1168, !30, i64 1176, !30, i64 1184, !36, i64 1192, !40, i64 1200, !6, i64 1232}
!33 = !{!"rb_global_vm_lock_struct", !30, i64 0, !6, i64 8, !34, i64 48, !30, i64 64, !36, i64 72, !6, i64 80, !6, i64 128, !36, i64 176, !36, i64 180}
!34 = !{!"list_head", !35, i64 0}
!35 = !{!"list_node", !30, i64 0, !30, i64 8}
!36 = !{!"int", !6, i64 0}
!37 = !{!"long long", !6, i64 0}
!38 = !{!"", !6, i64 0}
!39 = !{!"rb_hook_list_struct", !30, i64 0, !36, i64 8, !36, i64 12, !36, i64 16}
!40 = !{!"", !5, i64 0, !5, i64 8, !5, i64 16, !5, i64 24}
!41 = !{!42, !30, i64 16}
!42 = !{!"rb_execution_context_struct", !30, i64 0, !5, i64 8, !30, i64 16, !30, i64 24, !30, i64 32, !36, i64 40, !36, i64 44, !30, i64 48, !30, i64 56, !30, i64 64, !5, i64 72, !5, i64 80, !30, i64 88, !5, i64 96, !30, i64 104, !30, i64 112, !5, i64 120, !5, i64 128, !6, i64 136, !6, i64 137, !5, i64 144, !43, i64 152}
!43 = !{!"", !30, i64 0, !30, i64 8, !5, i64 16, !6, i64 24}
!44 = !{!45, !30, i64 16}
!45 = !{!"rb_control_frame_struct", !30, i64 0, !30, i64 8, !30, i64 16, !5, i64 24, !30, i64 32, !30, i64 40, !30, i64 48}
!46 = !{!45, !30, i64 32}
!47 = !{!48, !30, i64 16}
!48 = !{!"rb_iseq_struct", !5, i64 0, !5, i64 8, !30, i64 16, !6, i64 24}
!49 = !{!50, !30, i64 8}
!50 = !{!"rb_iseq_constant_body", !6, i64 0, !36, i64 4, !30, i64 8, !51, i64 16, !53, i64 64, !56, i64 120, !30, i64 152, !30, i64 160, !30, i64 168, !30, i64 176, !30, i64 184, !30, i64 192, !57, i64 200, !36, i64 232, !36, i64 236, !36, i64 240, !36, i64 244, !36, i64 248, !6, i64 252, !5, i64 256}
!51 = !{!"", !52, i64 0, !36, i64 4, !36, i64 8, !36, i64 12, !36, i64 16, !36, i64 20, !36, i64 24, !36, i64 28, !30, i64 32, !30, i64 40}
!52 = !{!"", !36, i64 0, !36, i64 0, !36, i64 0, !36, i64 0, !36, i64 0, !36, i64 0, !36, i64 0, !36, i64 0, !36, i64 1, !36, i64 1}
!53 = !{!"rb_iseq_location_struct", !5, i64 0, !5, i64 8, !5, i64 16, !5, i64 24, !36, i64 32, !54, i64 36}
!54 = !{!"rb_code_location_struct", !55, i64 0, !55, i64 8}
!55 = !{!"rb_code_position_struct", !36, i64 0, !36, i64 4}
!56 = !{!"iseq_insn_info", !30, i64 0, !30, i64 8, !36, i64 16, !30, i64 24}
!57 = !{!"", !5, i64 0, !5, i64 8, !5, i64 16, !30, i64 24}
!58 = !DILocation(line: 0, scope: !9)
!59 = !DILocation(line: 5, column: 1, scope: !9)
!60 = !DILocation(line: 10, column: 3, scope: !15, inlinedAt: !61)
!61 = distinct !DILocation(line: 5, column: 1, scope: !9)
!62 = !DILocation(line: 6, column: 3, scope: !15, inlinedAt: !61)
!63 = !{!37, !37, i64 0}
!64 = !{!"branch_weights", i32 10000, i32 1}
!65 = !{!45, !30, i64 8}
!66 = !DILocation(line: 7, column: 3, scope: !15, inlinedAt: !61)
!67 = !DILocation(line: 8, column: 3, scope: !15, inlinedAt: !61)
!68 = !DILocation(line: 11, column: 3, scope: !15, inlinedAt: !61)
!69 = !DILocation(line: 14, column: 1, scope: !9)
!70 = !DILocation(line: 16, column: 3, scope: !25, inlinedAt: !71)
!71 = distinct !DILocation(line: 14, column: 1, scope: !9)
!72 = !DILocation(line: 17, column: 3, scope: !25, inlinedAt: !71)
!73 = distinct !DISubprogram(name: "IFoo.foo", linkageName: "func_IFoo.foo", scope: null, file: !2, line: 11, type: !10, scopeLine: 11, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!74 = !DILocation(line: 11, column: 3, scope: !73)
!75 = !{!"branch_weights", i32 2000, i32 1}
!76 = !{!77}
!77 = distinct !{!77, !78, !"sorbet_callSuper: argument 0"}
!78 = distinct !{!78, !"sorbet_callSuper"}
!79 = !{!45, !5, i64 24}
!80 = !{!81, !5, i64 8}
!81 = !{!"rb_callable_method_entry_struct", !5, i64 0, !5, i64 8, !30, i64 16, !5, i64 24, !5, i64 32}
!82 = !{!83, !30, i64 24}
!83 = !{!"RClass", !84, i64 0, !5, i64 16, !30, i64 24, !37, i64 32}
!84 = !{!"RBasic", !5, i64 0, !5, i64 8}
!85 = !{!86, !5, i64 64}
!86 = !{!"rb_classext_struct", !30, i64 0, !30, i64 8, !30, i64 16, !30, i64 24, !30, i64 32, !30, i64 40, !30, i64 48, !30, i64 56, !5, i64 64, !5, i64 72, !30, i64 80, !5, i64 88}
!87 = !{!83, !5, i64 16}
!88 = !{!81, !30, i64 16}
!89 = !{!90, !5, i64 32}
!90 = !{!"rb_method_definition_struct", !6, i64 0, !36, i64 0, !36, i64 4, !6, i64 8, !5, i64 32, !5, i64 40}
!91 = !DILocation(line: 17, column: 3, scope: !23)
!92 = !DILocation(line: 0, scope: !23)
!93 = !DILocation(line: 18, column: 14, scope: !23)
