; ModuleID = 'payload'
source_filename = "llvm-link"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

%struct.rb_execution_context_struct = type { i64*, i64, %struct.rb_control_frame_struct*, %struct.rb_vm_tag*, %struct.rb_vm_protect_tag*, i32, i32, %struct.rb_fiber_struct*, %struct.rb_thread_struct*, %struct.st_table*, i64, i64, i64*, i64, %struct.rb_ensure_list*, %struct.rb_trace_arg_struct*, i64, i64, i8, i8, i64, %struct.anon.5 }
%struct.rb_control_frame_struct = type { i64*, i64*, %struct.rb_iseq_struct*, i64, i64*, i8*, i64* }
%struct.rb_iseq_struct = type { i64, i64, %struct.rb_iseq_constant_body*, %union.anon.14 }
%struct.rb_iseq_constant_body = type { i32, i32, i64*, %struct.anon, %struct.rb_iseq_location_struct, %struct.iseq_insn_info, i64*, %struct.iseq_catch_table*, %struct.rb_iseq_struct*, %struct.rb_iseq_struct*, %union.iseq_inline_storage_entry*, %struct.rb_call_data*, %struct.anon.13, i32, i32, i32, i32, i32, i8, i64 }
%struct.anon = type { %struct.anon.0, i32, i32, i32, i32, i32, i32, i32, i64*, %struct.rb_iseq_param_keyword* }
%struct.anon.0 = type { i16, [2 x i8] }
%struct.rb_iseq_param_keyword = type { i32, i32, i32, i32, i64*, i64* }
%struct.rb_iseq_location_struct = type { i64, i64, i64, i64, i32, %struct.rb_code_location_struct }
%struct.rb_code_location_struct = type { %struct.rb_code_position_struct, %struct.rb_code_position_struct }
%struct.rb_code_position_struct = type { i32, i32 }
%struct.iseq_insn_info = type { %struct.iseq_insn_info_entry*, i32*, i32, %struct.succ_index_table* }
%struct.iseq_insn_info_entry = type opaque
%struct.succ_index_table = type opaque
%struct.iseq_catch_table = type opaque
%union.iseq_inline_storage_entry = type { %struct.iseq_inline_cache_entry }
%struct.iseq_inline_cache_entry = type { i64, %struct.rb_cref_struct*, i64 }
%struct.rb_cref_struct = type { i64, i64, i64, %struct.rb_cref_struct*, %struct.rb_scope_visi_struct }
%struct.rb_scope_visi_struct = type { i8, [3 x i8] }
%struct.rb_call_data = type { %struct.rb_call_cache, %struct.rb_call_info }
%struct.rb_call_cache = type { i64, [3 x i64], %struct.rb_callable_method_entry_struct*, i64, i64 (%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_calling_info*, %struct.rb_call_data*)*, %union.anon.12 }
%struct.rb_callable_method_entry_struct = type { i64, i64, %struct.rb_method_definition_struct*, i64, i64 }
%struct.rb_method_definition_struct = type { i64, %union.anon.10, i64, i64 }
%union.anon.10 = type { %struct.rb_method_cfunc_struct }
%struct.rb_method_cfunc_struct = type { i64 (...)*, i64 (i64, i32, i64*, i64 (...)*)*, i32 }
%struct.rb_calling_info = type { i64, i64, i32, i32 }
%union.anon.12 = type { i32 }
%struct.rb_call_info = type { i64, i32, i32 }
%struct.anon.13 = type { i64, i64, i64, i64* }
%union.anon.14 = type { %struct.anon.15 }
%struct.anon.15 = type { i64, i32 }
%struct.rb_vm_tag = type { i64, i64, [5 x i8*], %struct.rb_vm_tag*, i32 }
%struct.rb_vm_protect_tag = type { %struct.rb_vm_protect_tag* }
%struct.rb_fiber_struct = type opaque
%struct.rb_thread_struct = type { %struct.list_node, i64, %struct.rb_vm_struct*, %struct.rb_execution_context_struct*, i64, %struct.rb_calling_info*, i64, i64, i64, i8, i8, i32, %struct.native_thread_data_struct, i8*, i64, i64, i64, i64, %union.pthread_mutex_t, %struct.rb_unblock_callback, i64, %struct.rb_mutex_struct*, %struct.rb_thread_list_struct*, %union.anon.7, i32, i64, %struct.rb_fiber_struct*, [5 x i8*], i64 }
%struct.list_node = type { %struct.list_node*, %struct.list_node* }
%struct.rb_vm_struct = type { i64, %struct.rb_global_vm_lock_struct, %struct.rb_thread_struct*, %struct.rb_thread_struct*, i8*, i64, %union.pthread_mutex_t, %struct.list_head, %struct.list_head, %struct.list_head, %struct.list_head, i64, i32, i32, i8, i32, i64, [5 x i64], i64, i64, i64, i64, i64, i64, i64, %struct.st_table*, %struct.st_table*, %struct.anon.3, %struct.rb_hook_list_struct, %struct.st_table*, %struct.rb_postponed_job_struct*, i32, i32, %struct.list_head, %union.pthread_mutex_t, i64, i64, i64, i64, i64, i32, %struct.st_table*, %struct.rb_objspace*, %struct.rb_at_exit_list*, i64*, %struct.st_table*, %struct.rb_builtin_function*, i32, %struct.anon.4, [29 x i16] }
%struct.rb_global_vm_lock_struct = type { %struct.rb_thread_struct*, %union.pthread_mutex_t, %struct.list_head, %struct.rb_thread_struct*, i32, %union.pthread_cond_t, %union.pthread_cond_t, i32, i32 }
%union.pthread_cond_t = type { %struct.anon.2 }
%struct.anon.2 = type { i32, i32, i64, i64, i64, i8*, i32, i32 }
%struct.anon.3 = type { [65 x i64] }
%struct.rb_hook_list_struct = type { %struct.rb_event_hook_struct*, i32, i32, i32 }
%struct.rb_event_hook_struct = type opaque
%struct.rb_postponed_job_struct = type opaque
%struct.list_head = type { %struct.list_node }
%struct.rb_objspace = type opaque
%struct.rb_at_exit_list = type { void (%struct.rb_vm_struct*)*, %struct.rb_at_exit_list* }
%struct.rb_builtin_function = type opaque
%struct.anon.4 = type { i64, i64, i64, i64 }
%struct.native_thread_data_struct = type { %struct.list_head, %union.anon.6 }
%union.anon.6 = type { %union.pthread_cond_t }
%union.pthread_mutex_t = type { %struct.__pthread_mutex_s }
%struct.__pthread_mutex_s = type { i32, i32, i32, i32, i32, i16, i16, %struct.__pthread_internal_list }
%struct.__pthread_internal_list = type { %struct.__pthread_internal_list*, %struct.__pthread_internal_list* }
%struct.rb_unblock_callback = type { void (i8*)*, i8* }
%struct.rb_mutex_struct = type opaque
%struct.rb_thread_list_struct = type { %struct.rb_thread_list_struct*, %struct.rb_thread_struct* }
%union.anon.7 = type { %struct.anon.8 }
%struct.anon.8 = type { i64, i64, i32 }
%struct.st_table = type { i8, i8, i8, i32, %struct.st_hash_type*, i64, i64*, i64, i64, %struct.st_table_entry* }
%struct.st_hash_type = type { i32 (i64, i64)*, i64 (i64)* }
%struct.st_table_entry = type opaque
%struct.rb_ensure_list = type { %struct.rb_ensure_list*, %struct.rb_ensure_entry }
%struct.rb_ensure_entry = type { i64, i64 (i64)*, i64 }
%struct.rb_trace_arg_struct = type { i32, %struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, i64, i64, i64, i64, i64, i32, i32, i64 }
%struct.anon.5 = type { i64*, i64*, i64, [1 x %struct.__jmp_buf_tag] }
%struct.__jmp_buf_tag = type { [8 x i64], i32, %struct.__sigset_t }
%struct.__sigset_t = type { [16 x i64] }
%struct.SorbetLineNumberInfo = type { i32, %struct.iseq_insn_info_entry*, i64* }
%struct.FunctionInlineCache = type { %struct.rb_kwarg_call_data }
%struct.rb_kwarg_call_data = type { %struct.rb_call_cache, %struct.rb_call_info_with_kwarg }
%struct.rb_call_info_with_kwarg = type { %struct.rb_call_info, %struct.rb_call_info_kw_arg* }
%struct.rb_call_info_kw_arg = type { i32, [1 x i64] }
%struct.rb_sorbet_param_struct = type { %struct.anon.0, i32, i32, i32, i32, i32, i32, i32, i64*, i32, i32, i32, i32, i64* }
%struct.vm_throw_data = type { i64, i64, i64, %struct.rb_control_frame_struct*, i32 }
%struct.iseq_inline_iv_cache_entry = type { i64, i64 }

@ruby_current_execution_context_ptr = external local_unnamed_addr global %struct.rb_execution_context_struct*, align 8
@ruby_current_vm_ptr = external local_unnamed_addr global %struct.rb_vm_struct*, align 8
@rb_eRuntimeError = external local_unnamed_addr global i64, align 8
@.str.10 = private unnamed_addr constant [95 x i8] c"sorbet_getBuildSCMRevision: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@.str.11 = private unnamed_addr constant [93 x i8] c"sorbet_getIsReleaseBuild: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@"stackFramePrecomputed_func_Object#take_arguments" = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@rubyIdPrecomputed_take_arguments = internal unnamed_addr global i64 0, align 8
@str_take_arguments = private unnamed_addr constant [15 x i8] c"take_arguments\00", align 1
@rubyStrFrozen_take_arguments = internal unnamed_addr global i64 0, align 8
@"rubyStrFrozen_test/testdata/compiler/all_arguments.rb" = internal unnamed_addr global i64 0, align 8
@"str_test/testdata/compiler/all_arguments.rb" = private unnamed_addr constant [40 x i8] c"test/testdata/compiler/all_arguments.rb\00", align 1
@iseqEncodedArray = internal global [32 x i64] zeroinitializer
@fileLineNumberInfo = internal global %struct.SorbetLineNumberInfo zeroinitializer
@rubyIdPrecomputed_d = internal unnamed_addr global i64 0, align 8
@str_d = private unnamed_addr constant [2 x i8] c"d\00", align 1
@rubyIdPrecomputed_e = internal unnamed_addr global i64 0, align 8
@str_e = private unnamed_addr constant [2 x i8] c"e\00", align 1
@"str_<build-array>" = private unnamed_addr constant [14 x i8] c"<build-array>\00", align 1
@ic_inspect = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_inspect = internal unnamed_addr global i64 0, align 8
@str_inspect = private unnamed_addr constant [8 x i8] c"inspect\00", align 1
@ic_puts = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_puts = internal unnamed_addr global i64 0, align 8
@str_puts = private unnamed_addr constant [5 x i8] c"puts\00", align 1
@"stackFramePrecomputed_func_<root>.<static-init>$152" = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@"rubyIdPrecomputed_<top (required)>" = internal unnamed_addr global i64 0, align 8
@"str_<top (required)>" = private unnamed_addr constant [17 x i8] c"<top (required)>\00", align 1
@rubyIdPrecomputed_normal = internal unnamed_addr global i64 0, align 8
@str_normal = private unnamed_addr constant [7 x i8] c"normal\00", align 1
@rubyIdPrecomputed_a = internal unnamed_addr global i64 0, align 8
@str_a = private unnamed_addr constant [2 x i8] c"a\00", align 1
@rubyIdPrecomputed_b = internal unnamed_addr global i64 0, align 8
@str_b = private unnamed_addr constant [2 x i8] c"b\00", align 1
@rubyIdPrecomputed_c = internal unnamed_addr global i64 0, align 8
@str_c = private unnamed_addr constant [2 x i8] c"c\00", align 1
@rubyIdPrecomputed_g = internal unnamed_addr global i64 0, align 8
@str_g = private unnamed_addr constant [2 x i8] c"g\00", align 1
@rubyIdPrecomputed_f = internal unnamed_addr global i64 0, align 8
@str_f = private unnamed_addr constant [2 x i8] c"f\00", align 1
@ic_keep_def = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_keep_def = internal unnamed_addr global i64 0, align 8
@str_keep_def = private unnamed_addr constant [9 x i8] c"keep_def\00", align 1
@ic_take_arguments = internal global %struct.FunctionInlineCache zeroinitializer
@ic_take_arguments.1 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_take_arguments.2 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_take_arguments.3 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_take_arguments.4 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_take_arguments.5 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_take_arguments.6 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_take_arguments.7 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_take_arguments.8 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_take_arguments.9 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_take_arguments.10 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_take_arguments.11 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_take_arguments.12 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_take_arguments.13 = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_baz = internal unnamed_addr global i64 0, align 8
@str_baz = private unnamed_addr constant [4 x i8] c"baz\00", align 1
@ic_take_arguments.14 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_take_arguments.15 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_take_arguments.16 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_take_arguments.17 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_take_arguments.18 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_take_arguments.19 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_take_arguments.20 = internal global %struct.FunctionInlineCache zeroinitializer
@rb_cObject = external local_unnamed_addr constant i64

; Function Attrs: noreturn
declare void @sorbet_raiseArity(i32, i32, i32) local_unnamed_addr #0

declare %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64, i64, i64, i64, %struct.rb_iseq_struct*, i32, i32, %struct.SorbetLineNumberInfo*, i64*, i32, i32) local_unnamed_addr #1

declare void @sorbet_initLineNumberInfo(%struct.SorbetLineNumberInfo*, i64*, i32) local_unnamed_addr #1

declare i64 @sorbet_readRealpath() local_unnamed_addr #1

declare void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache*, i64, i32, i32, i32, i64*) local_unnamed_addr #1

declare i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache*, i64) local_unnamed_addr #1

declare void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_iseq_struct*) local_unnamed_addr #1

; Function Attrs: nofree nosync nounwind readnone willreturn
declare i8* @llvm.frameaddress.p0i8(i32 immarg) #2

; Function Attrs: nofree nosync nounwind willreturn
declare i8* @llvm.stacksave() #3

; Function Attrs: nounwind
declare i32 @llvm.eh.sjlj.setjmp(i8*) #4

declare void @rb_vm_rewind_cfp(%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*) local_unnamed_addr #1

; Function Attrs: noreturn nounwind
declare void @llvm.eh.sjlj.longjmp(i8*) #5

declare i32 @rb_block_given_p() local_unnamed_addr #1

declare i64 @rb_block_proc() local_unnamed_addr #1

declare i64 @rb_intern(i8*) local_unnamed_addr #1

declare void @rb_add_method_sorbet(i64, i64, i64 (i32, i64*, i64, %struct.rb_control_frame_struct*)*, %struct.rb_sorbet_param_struct*, i32, i8*) local_unnamed_addr #1

declare i64 @rb_intern2(i8*, i64) local_unnamed_addr #1

declare i64 @rb_id2sym(i64) local_unnamed_addr #1

declare i64 @rb_ary_new_from_values(i64, i64*) local_unnamed_addr #1

declare i64 @rb_hash_new() local_unnamed_addr #1

declare i64 @rb_hash_dup(i64) local_unnamed_addr #1

declare i64 @rb_fstring_new(i8*, i64) local_unnamed_addr #1

declare void @rb_gc_register_mark_object(i64) local_unnamed_addr #1

; Function Attrs: noreturn
declare void @rb_raise(i64, i8*, ...) local_unnamed_addr #0

declare i64 @rb_ary_new() local_unnamed_addr #1

declare i64 @rb_hash_delete_entry(i64, i64) local_unnamed_addr #1

declare i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct*, i32) local_unnamed_addr #1

; Function Attrs: alwaysinline nounwind ssp uwtable
define noalias nonnull i8* @sorbet_allocateParamInfo() local_unnamed_addr #6 {
  %1 = tail call noalias nonnull i8* @ruby_xcalloc(i64 noundef 1, i64 noundef 64) #13
  ret i8* %1
}

; Function Attrs: allocsize(0,1)
declare noalias nonnull i8* @ruby_xcalloc(i64, i64) local_unnamed_addr #7

; Function Attrs: allocsize(0,1)
declare noalias nonnull i8* @ruby_xmalloc2(i64, i64) local_unnamed_addr #7

; Function Attrs: argmemonly nofree nosync nounwind willreturn
declare void @llvm.memcpy.p0i8.p0i8.i64(i8* noalias nocapture writeonly, i8* noalias nocapture readonly, i64, i1 immarg) #8

; Function Attrs: nounwind ssp uwtable
define weak i32 @sorbet_getIsReleaseBuild() local_unnamed_addr #9 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !4
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* noundef getelementptr inbounds ([93 x i8], [93 x i8]* @.str.11, i64 0, i64 0)) #5
  unreachable
}

; Function Attrs: nounwind ssp uwtable
define weak i8* @sorbet_getBuildSCMRevision() local_unnamed_addr #9 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !4
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* noundef getelementptr inbounds ([95 x i8], [95 x i8]* @.str.10, i64 0, i64 0)) #5
  unreachable
}

; Function Attrs: nounwind sspreq uwtable
define i64 @"func_Object#take_arguments"(i32 %argc, i64* %argArray, i64 %selfRaw, %struct.rb_control_frame_struct* nonnull align 8 dereferenceable(8) %cfp) #10 !dbg !8 {
functionEntryInitializers:
  %callArgs = alloca [8 x i64], align 8
  %ecTag = alloca %struct.rb_vm_tag, align 8
  %0 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %cfp, i64 0, i32 0
  store i64* getelementptr inbounds ([32 x i64], [32 x i64]* @iseqEncodedArray, i64 0, i64 4), i64** %0, align 8, !tbaa !12
  %1 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !12
  %2 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %ecTag, i64 0, i32 4
  store i32 0, i32* %2, align 8, !tbaa !14
  %3 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %ecTag, i64 0, i32 0
  store i64 52, i64* %3, align 8, !tbaa !16
  %4 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %1, i64 0, i32 3
  %5 = load %struct.rb_vm_tag*, %struct.rb_vm_tag** %4, align 8, !tbaa !17
  %6 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %ecTag, i64 0, i32 3
  store %struct.rb_vm_tag* %5, %struct.rb_vm_tag** %6, align 8, !tbaa !21
  %7 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %ecTag, i64 0, i32 2, i64 0
  %8 = tail call i8* @llvm.frameaddress.p0i8(i32 noundef 0) #14
  store i8* %8, i8** %7, align 8
  %9 = tail call i8* @llvm.stacksave() #14
  %10 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %ecTag, i64 0, i32 2, i64 2
  store i8* %9, i8** %10, align 8
  %11 = bitcast i8** %7 to i8*
  %12 = call i32 @llvm.eh.sjlj.setjmp(i8* nonnull align 8 %11) #4
  %13 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !12
  %14 = icmp eq i32 %12, 0
  %15 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %13, i64 0, i32 3
  br i1 %14, label %37, label %16

16:                                               ; preds = %functionEntryInitializers
  %17 = load %struct.rb_vm_tag*, %struct.rb_vm_tag** %15, align 8, !tbaa !17
  %18 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %17, i64 0, i32 4
  %19 = load i32, i32* %18, align 8, !tbaa !14
  store i32 0, i32* %18, align 8, !tbaa !14
  %20 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %13, i64 0, i32 16
  %21 = load i64, i64* %20, align 8, !tbaa !22
  %22 = inttoptr i64 %21 to %struct.vm_throw_data*
  %23 = icmp eq i32 %19, 1
  br i1 %23, label %24, label %29

24:                                               ; preds = %16
  %25 = getelementptr inbounds %struct.vm_throw_data, %struct.vm_throw_data* %22, i64 0, i32 3
  %26 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %25, align 8, !tbaa !23
  %27 = icmp eq %struct.rb_control_frame_struct* %26, %cfp
  br i1 %27, label %sorbet_processThrowReturnSetJmp.exit, label %.thread80

.thread80:                                        ; preds = %24
  %28 = load %struct.rb_vm_tag*, %struct.rb_vm_tag** %6, align 8, !tbaa !21
  store %struct.rb_vm_tag* %28, %struct.rb_vm_tag** %15, align 8, !tbaa !17
  br label %32

29:                                               ; preds = %16
  %30 = load %struct.rb_vm_tag*, %struct.rb_vm_tag** %6, align 8, !tbaa !21
  store %struct.rb_vm_tag* %30, %struct.rb_vm_tag** %15, align 8, !tbaa !17
  %31 = icmp eq i32 %19, 0
  br i1 %31, label %argumentSetup, label %32

32:                                               ; preds = %.thread80, %29
  %33 = phi %struct.rb_vm_tag* [ %28, %.thread80 ], [ %30, %29 ]
  %34 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %33, i64 0, i32 4
  store i32 %19, i32* %34, align 8, !tbaa !14
  %35 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %33, i64 0, i32 2, i64 0
  %36 = bitcast i8** %35 to i8*
  call void @llvm.eh.sjlj.longjmp(i8* nonnull %36) #5
  unreachable

37:                                               ; preds = %functionEntryInitializers
  store %struct.rb_vm_tag* %ecTag, %struct.rb_vm_tag** %15, align 8, !tbaa !17
  br label %argumentSetup

sorbet_processThrowReturnSetJmp.exit:             ; preds = %24
  call void @rb_vm_rewind_cfp(%struct.rb_execution_context_struct* nonnull %13, %struct.rb_control_frame_struct* nonnull %cfp) #4
  store i64 8, i64* %20, align 8, !tbaa !22
  %38 = getelementptr inbounds %struct.vm_throw_data, %struct.vm_throw_data* %22, i64 0, i32 2
  %39 = load i64, i64* %38, align 8, !tbaa !25
  %40 = load %struct.rb_vm_tag*, %struct.rb_vm_tag** %6, align 8, !tbaa !21
  store %struct.rb_vm_tag* %40, %struct.rb_vm_tag** %15, align 8, !tbaa !17
  %41 = icmp eq i64 %39, 52
  br i1 %41, label %argumentSetup, label %postProcess

argumentSetup:                                    ; preds = %29, %37, %sorbet_processThrowReturnSetJmp.exit
  %hashAttemptReadGuard = icmp ult i32 1, %argc, !dbg !26
  br i1 %hashAttemptReadGuard, label %argCountSecondCheckBlock.thread, label %argCountSecondCheckBlock, !dbg !26

postProcess:                                      ; preds = %sorbet_processThrowReturnSetJmp.exit, %86
  %"<returnValue>.sroa.0.0" = phi i64 [ %send54, %86 ], [ %39, %sorbet_processThrowReturnSetJmp.exit ]
  %42 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !12
  %43 = load %struct.rb_vm_tag*, %struct.rb_vm_tag** %6, align 8, !tbaa !21
  %44 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %42, i64 0, i32 3
  store %struct.rb_vm_tag* %43, %struct.rb_vm_tag** %44, align 8, !tbaa !17
  ret i64 %"<returnValue>.sroa.0.0"

argCountSecondCheckBlock.thread:                  ; preds = %argumentSetup
  %argsWithoutHashCount = sub nuw i32 %argc, 1, !dbg !26
  %45 = getelementptr i64, i64* %argArray, i32 %argsWithoutHashCount, !dbg !26
  %KWArgHash = load i64, i64* %45, align 8, !dbg !26
  %46 = and i64 %KWArgHash, 7, !dbg !26
  %47 = icmp ne i64 %46, 0, !dbg !26
  %48 = and i64 %KWArgHash, -9, !dbg !26
  %49 = icmp eq i64 %48, 0, !dbg !26
  %50 = or i1 %47, %49, !dbg !26
  br i1 %50, label %.thread, label %sorbet_isa_Hash.exit, !dbg !26

sorbet_isa_Hash.exit:                             ; preds = %argCountSecondCheckBlock.thread
  %51 = inttoptr i64 %KWArgHash to %struct.iseq_inline_iv_cache_entry*, !dbg !26
  %52 = getelementptr inbounds %struct.iseq_inline_iv_cache_entry, %struct.iseq_inline_iv_cache_entry* %51, i64 0, i32 0, !dbg !26
  %53 = load i64, i64* %52, align 8, !dbg !26, !tbaa !27
  %54 = and i64 %53, 31, !dbg !26
  %55 = icmp eq i64 %54, 8, !dbg !26
  br i1 %55, label %fillRequiredArgs, label %.thread, !dbg !26

.thread:                                          ; preds = %sorbet_isa_Hash.exit, %argCountSecondCheckBlock.thread
  br label %fillRequiredArgs, !dbg !26

argCountFailBlock:                                ; preds = %argCountSecondCheckBlock
  call void @sorbet_raiseArity(i32 noundef 0, i32 noundef 1, i32 noundef -1) #0, !dbg !26
  unreachable, !dbg !26

argCountSecondCheckBlock:                         ; preds = %argumentSetup
  %tooFewArgs = icmp ult i32 %argc, 1, !dbg !26
  br i1 %tooFewArgs, label %argCountFailBlock, label %fillRequiredArgs, !dbg !26, !prof !29

fillFromDefaultBlockDone1:                        ; preds = %sorbet_getMethodBlockAsProc.exit
  %56 = getelementptr i64, i64* %argArray, i32 1, !dbg !26
  %rawArg_b = load i64, i64* %56, align 8, !dbg !26
  %57 = icmp sgt i32 %argcPhi87, 2, !dbg !26
  br i1 %57, label %59, label %fillFromDefaultBlockDone1.thread, !dbg !26

fillFromDefaultBlockDone1.thread:                 ; preds = %sorbet_getMethodBlockAsProc.exit, %fillFromDefaultBlockDone1
  %"<argPresent>.sroa.0.093" = phi i64 [ 20, %fillFromDefaultBlockDone1 ], [ 0, %sorbet_getMethodBlockAsProc.exit ]
  %b.sroa.0.191 = phi i64 [ %rawArg_b, %fillFromDefaultBlockDone1 ], [ 8, %sorbet_getMethodBlockAsProc.exit ]
  %58 = call i64 @rb_ary_new() #4, !dbg !26
  br label %sorbet_readRestArgs.exit, !dbg !26

59:                                               ; preds = %fillFromDefaultBlockDone1
  %60 = sub nuw nsw i32 %argcPhi87, 2, !dbg !26
  %61 = zext i32 %60 to i64
  %62 = getelementptr inbounds i64, i64* %argArray, i64 2, !dbg !26
  %63 = call i64 @rb_ary_new_from_values(i64 %61, i64* nonnull %62) #4, !dbg !26
  br label %sorbet_readRestArgs.exit, !dbg !26

sorbet_readRestArgs.exit:                         ; preds = %fillFromDefaultBlockDone1.thread, %59
  %"<argPresent>.sroa.0.092" = phi i64 [ %"<argPresent>.sroa.0.093", %fillFromDefaultBlockDone1.thread ], [ 20, %59 ]
  %b.sroa.0.190 = phi i64 [ %b.sroa.0.191, %fillFromDefaultBlockDone1.thread ], [ %rawArg_b, %59 ]
  %64 = phi i64 [ %58, %fillFromDefaultBlockDone1.thread ], [ %63, %59 ], !dbg !26
  %rubyId_d = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !26
  %rawSym = call i64 @rb_id2sym(i64 %rubyId_d), !dbg !26
  %65 = icmp eq i64 %hashArgsPhi84, 52, !dbg !26
  br i1 %65, label %77, label %sorbet_getKWArg.exit76, !dbg !26

sorbet_getKWArg.exit76:                           ; preds = %sorbet_readRestArgs.exit
  %66 = call i64 @rb_hash_delete_entry(i64 %hashArgsPhi84, i64 %rawSym) #4, !dbg !26
  %67 = icmp eq i64 %66, 52, !dbg !26
  %68 = select i1 %67, i64 8, i64 %66, !dbg !26
  %rubyId_e = load i64, i64* @rubyIdPrecomputed_e, align 8, !dbg !26
  %rawSym20 = call i64 @rb_id2sym(i64 %rubyId_e), !dbg !26
  %69 = call i64 @rb_hash_delete_entry(i64 %hashArgsPhi84, i64 %rawSym20) #4, !dbg !26
  %70 = icmp eq i64 %69, 52, !dbg !26
  %e.sroa.0.1 = select i1 %70, i64 8, i64 %69, !dbg !26
  %71 = call i64 @rb_hash_dup(i64 %hashArgsPhi84) #4, !dbg !26
  br i1 %70, label %sorbet_readKWRestArgs.exit.thread, label %81

fillRequiredArgs:                                 ; preds = %.thread, %sorbet_isa_Hash.exit, %argCountSecondCheckBlock
  %argcPhi87 = phi i32 [ 1, %argCountSecondCheckBlock ], [ %argc, %.thread ], [ %argsWithoutHashCount, %sorbet_isa_Hash.exit ]
  %hashArgsPhi84 = phi i64 [ 52, %argCountSecondCheckBlock ], [ 52, %.thread ], [ %KWArgHash, %sorbet_isa_Hash.exit ]
  %rawArg_a = load i64, i64* %argArray, align 8, !dbg !26
  %72 = call i32 @rb_block_given_p() #4, !dbg !26
  %73 = icmp eq i32 %72, 0, !dbg !26
  br i1 %73, label %sorbet_getMethodBlockAsProc.exit, label %74, !dbg !26

74:                                               ; preds = %fillRequiredArgs
  %75 = call i64 @rb_block_proc() #4, !dbg !26
  br label %sorbet_getMethodBlockAsProc.exit, !dbg !26

sorbet_getMethodBlockAsProc.exit:                 ; preds = %fillRequiredArgs, %74
  %76 = phi i64 [ %75, %74 ], [ 8, %fillRequiredArgs ], !dbg !26
  %default0 = icmp eq i32 %argcPhi87, 1, !dbg !26
  br i1 %default0, label %fillFromDefaultBlockDone1.thread, label %fillFromDefaultBlockDone1, !dbg !26, !prof !29

77:                                               ; preds = %sorbet_readRestArgs.exit
  %rubyId_e105 = load i64, i64* @rubyIdPrecomputed_e, align 8, !dbg !26
  %rawSym20106 = call i64 @rb_id2sym(i64 %rubyId_e105), !dbg !26
  %78 = call i64 @rb_hash_new() #4, !dbg !26
  br label %sorbet_readKWRestArgs.exit.thread, !dbg !26

sorbet_readKWRestArgs.exit.thread:                ; preds = %77, %sorbet_getKWArg.exit76
  %.ph = phi i64 [ 8, %77 ], [ %68, %sorbet_getKWArg.exit76 ]
  %.ph119 = phi i64 [ %78, %77 ], [ %71, %sorbet_getKWArg.exit76 ]
  %79 = and i64 %"<argPresent>.sroa.0.092", -9, !dbg !30
  %80 = icmp ne i64 %79, 0, !dbg !30
  %b.sroa.0.0122 = select i1 %80, i64 %b.sroa.0.190, i64 3, !dbg !30
  br label %86, !dbg !31

81:                                               ; preds = %sorbet_getKWArg.exit76
  %"<argPresent>9.sroa.0.0112" = phi i64 [ 20, %sorbet_getKWArg.exit76 ]
  %e.sroa.0.1110 = phi i64 [ %e.sroa.0.1, %sorbet_getKWArg.exit76 ]
  %82 = phi i64 [ %68, %sorbet_getKWArg.exit76 ]
  %83 = phi i64 [ %71, %sorbet_getKWArg.exit76 ], !dbg !26
  %84 = and i64 %"<argPresent>.sroa.0.092", -9, !dbg !30
  %85 = icmp ne i64 %84, 0, !dbg !30
  %b.sroa.0.0 = select i1 %85, i64 %b.sroa.0.190, i64 3, !dbg !30
  br label %86, !dbg !31

86:                                               ; preds = %sorbet_readKWRestArgs.exit.thread, %81
  %b.sroa.0.0123 = phi i64 [ %b.sroa.0.0, %81 ], [ %b.sroa.0.0122, %sorbet_readKWRestArgs.exit.thread ]
  %87 = phi i64 [ %83, %81 ], [ %.ph119, %sorbet_readKWRestArgs.exit.thread ]
  %88 = phi i64 [ %82, %81 ], [ %.ph, %sorbet_readKWRestArgs.exit.thread ]
  %89 = phi i64 [ %e.sroa.0.1110, %81 ], [ 5, %sorbet_readKWRestArgs.exit.thread ]
  store i64* getelementptr inbounds ([32 x i64], [32 x i64]* @iseqEncodedArray, i64 0, i64 5), i64** %0, align 8, !dbg !32, !tbaa !12
  %callArgs0Addr = getelementptr [8 x i64], [8 x i64]* %callArgs, i32 0, i64 0, !dbg !33
  store i64 %rawArg_a, i64* %callArgs0Addr, align 8, !dbg !33
  %callArgs1Addr = getelementptr [8 x i64], [8 x i64]* %callArgs, i32 0, i64 1, !dbg !33
  store i64 %b.sroa.0.0123, i64* %callArgs1Addr, align 8, !dbg !33
  %callArgs2Addr = getelementptr [8 x i64], [8 x i64]* %callArgs, i32 0, i64 2, !dbg !33
  store i64 %64, i64* %callArgs2Addr, align 8, !dbg !33
  %callArgs3Addr = getelementptr [8 x i64], [8 x i64]* %callArgs, i32 0, i64 3, !dbg !33
  store i64 %88, i64* %callArgs3Addr, align 8, !dbg !33
  %callArgs4Addr = getelementptr [8 x i64], [8 x i64]* %callArgs, i32 0, i64 4, !dbg !33
  store i64 %89, i64* %callArgs4Addr, align 8, !dbg !33
  %callArgs5Addr = getelementptr [8 x i64], [8 x i64]* %callArgs, i32 0, i64 5, !dbg !33
  store i64 %87, i64* %callArgs5Addr, align 8, !dbg !33
  %callArgs6Addr = getelementptr [8 x i64], [8 x i64]* %callArgs, i32 0, i64 6, !dbg !33
  store i64 %76, i64* %callArgs6Addr, align 8, !dbg !33
  %90 = getelementptr [8 x i64], [8 x i64]* %callArgs, i64 0, i64 0, !dbg !33
  call void @llvm.experimental.noalias.scope.decl(metadata !34), !dbg !33
  %91 = call i64 @rb_ary_new_from_values(i64 noundef 7, i64* noundef nonnull %90) #4, !dbg !33
  %92 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %cfp, i64 0, i32 1, !dbg !33
  %93 = load i64*, i64** %92, align 8, !dbg !33, !tbaa !37
  %94 = getelementptr inbounds i64, i64* %93, i64 1, !dbg !33
  store i64* %94, i64** %92, align 8, !dbg !33, !tbaa !37
  store i64 %91, i64* %93, align 8, !dbg !33, !tbaa !4
  %send = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @ic_inspect, i64 0), !dbg !33
  %95 = load i64*, i64** %92, align 8, !dbg !39, !tbaa !37
  %96 = getelementptr inbounds i64, i64* %95, i64 1, !dbg !39
  store i64 %selfRaw, i64* %95, align 8, !dbg !39, !tbaa !4
  %97 = getelementptr inbounds i64, i64* %96, i64 1, !dbg !39
  store i64* %97, i64** %92, align 8, !dbg !39, !tbaa !37
  store i64 %send, i64* %96, align 8, !dbg !39, !tbaa !4
  %send54 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @ic_puts, i64 0), !dbg !39
  br label %postProcess, !dbg !39
}

; Function Attrs: nounwind sspreq uwtable
define internal fastcc void @"func_<root>.<static-init>$152"(i64 %selfRaw, %struct.rb_control_frame_struct* %cfp) unnamed_addr #10 !dbg !40 {
functionEntryInitializers:
  %ecTag = alloca %struct.rb_vm_tag, align 8
  %stackFrame = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_<root>.<static-init>$152", align 8
  %0 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !12
  %1 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %0, i64 0, i32 2
  %2 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %1, align 8, !tbaa !41
  %3 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 2
  store %struct.rb_iseq_struct* %stackFrame, %struct.rb_iseq_struct** %3, align 8, !tbaa !42
  %4 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 4
  %5 = load i64*, i64** %4, align 8, !tbaa !43
  %6 = load i64, i64* %5, align 8, !tbaa !4
  %7 = and i64 %6, -33
  store i64 %7, i64* %5, align 8, !tbaa !4
  tail call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* %0, %struct.rb_control_frame_struct* %2, %struct.rb_iseq_struct* %stackFrame) #4
  %8 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %cfp, i64 0, i32 0
  store i64* getelementptr inbounds ([32 x i64], [32 x i64]* @iseqEncodedArray, i64 0, i64 4), i64** %8, align 8, !tbaa !12
  %9 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !12
  %10 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %ecTag, i64 0, i32 4
  store i32 0, i32* %10, align 8, !tbaa !14
  %11 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %ecTag, i64 0, i32 0
  store i64 52, i64* %11, align 8, !tbaa !16
  %12 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %9, i64 0, i32 3
  %13 = load %struct.rb_vm_tag*, %struct.rb_vm_tag** %12, align 8, !tbaa !17
  %14 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %ecTag, i64 0, i32 3
  store %struct.rb_vm_tag* %13, %struct.rb_vm_tag** %14, align 8, !tbaa !21
  %15 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %ecTag, i64 0, i32 2, i64 0
  %16 = tail call i8* @llvm.frameaddress.p0i8(i32 noundef 0) #4
  store i8* %16, i8** %15, align 8
  %17 = tail call i8* @llvm.stacksave() #4
  %18 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %ecTag, i64 0, i32 2, i64 2
  store i8* %17, i8** %18, align 8
  %19 = bitcast i8** %15 to i8*
  %20 = call i32 @llvm.eh.sjlj.setjmp(i8* nonnull align 8 %19) #4
  %21 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !12
  %22 = icmp eq i32 %20, 0
  %23 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %21, i64 0, i32 3
  br i1 %22, label %45, label %24

24:                                               ; preds = %functionEntryInitializers
  %25 = load %struct.rb_vm_tag*, %struct.rb_vm_tag** %23, align 8, !tbaa !17
  %26 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %25, i64 0, i32 4
  %27 = load i32, i32* %26, align 8, !tbaa !14
  store i32 0, i32* %26, align 8, !tbaa !14
  %28 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %21, i64 0, i32 16
  %29 = load i64, i64* %28, align 8, !tbaa !22
  %30 = inttoptr i64 %29 to %struct.vm_throw_data*
  %31 = icmp eq i32 %27, 1
  br i1 %31, label %32, label %37

32:                                               ; preds = %24
  %33 = getelementptr inbounds %struct.vm_throw_data, %struct.vm_throw_data* %30, i64 0, i32 3
  %34 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %33, align 8, !tbaa !23
  %35 = icmp eq %struct.rb_control_frame_struct* %34, %cfp
  br i1 %35, label %sorbet_processThrowReturnSetJmp.exit, label %.thread1

.thread1:                                         ; preds = %32
  %36 = load %struct.rb_vm_tag*, %struct.rb_vm_tag** %14, align 8, !tbaa !21
  store %struct.rb_vm_tag* %36, %struct.rb_vm_tag** %23, align 8, !tbaa !17
  br label %40

37:                                               ; preds = %24
  %38 = load %struct.rb_vm_tag*, %struct.rb_vm_tag** %14, align 8, !tbaa !21
  store %struct.rb_vm_tag* %38, %struct.rb_vm_tag** %23, align 8, !tbaa !17
  %39 = icmp eq i32 %27, 0
  br i1 %39, label %fastSymCallIntrinsic_Static_keep_def, label %40

40:                                               ; preds = %.thread1, %37
  %41 = phi %struct.rb_vm_tag* [ %36, %.thread1 ], [ %38, %37 ]
  %42 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %41, i64 0, i32 4
  store i32 %27, i32* %42, align 8, !tbaa !14
  %43 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %41, i64 0, i32 2, i64 0
  %44 = bitcast i8** %43 to i8*
  call void @llvm.eh.sjlj.longjmp(i8* nonnull %44) #5
  unreachable

45:                                               ; preds = %functionEntryInitializers
  store %struct.rb_vm_tag* %ecTag, %struct.rb_vm_tag** %23, align 8, !tbaa !17
  br label %fastSymCallIntrinsic_Static_keep_def

sorbet_processThrowReturnSetJmp.exit:             ; preds = %32
  call void @rb_vm_rewind_cfp(%struct.rb_execution_context_struct* nonnull %21, %struct.rb_control_frame_struct* nonnull %cfp) #4
  store i64 8, i64* %28, align 8, !tbaa !22
  %46 = getelementptr inbounds %struct.vm_throw_data, %struct.vm_throw_data* %30, i64 0, i32 2
  %47 = load i64, i64* %46, align 8, !tbaa !25
  %48 = load %struct.rb_vm_tag*, %struct.rb_vm_tag** %14, align 8, !tbaa !21
  store %struct.rb_vm_tag* %48, %struct.rb_vm_tag** %23, align 8, !tbaa !17
  %49 = icmp eq i64 %47, 52
  br i1 %49, label %fastSymCallIntrinsic_Static_keep_def, label %postProcess

postProcess:                                      ; preds = %sorbet_processThrowReturnSetJmp.exit, %afterSend
  %50 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !12
  %51 = load %struct.rb_vm_tag*, %struct.rb_vm_tag** %14, align 8, !tbaa !21
  %52 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %50, i64 0, i32 3
  store %struct.rb_vm_tag* %51, %struct.rb_vm_tag** %52, align 8, !tbaa !17
  ret void

afterSend:                                        ; preds = %316, %sorbet_setupParamKeywords.exit
  store i64* getelementptr inbounds ([32 x i64], [32 x i64]* @iseqEncodedArray, i64 0, i64 8), i64** %8, align 8, !dbg !44, !tbaa !12
  %rubyId_d398 = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !45
  %rawSym399 = call i64 @rb_id2sym(i64 %rubyId_d398), !dbg !45
  %53 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %cfp, i64 0, i32 1, !dbg !46
  %54 = load i64*, i64** %53, align 8, !dbg !46, !tbaa !37
  %55 = getelementptr inbounds i64, i64* %54, i64 1, !dbg !46
  store i64 %selfRaw, i64* %54, align 8, !dbg !46, !tbaa !4
  %56 = getelementptr inbounds i64, i64* %55, i64 1, !dbg !46
  %57 = getelementptr inbounds i64, i64* %56, i64 1, !dbg !46
  %58 = getelementptr inbounds i64, i64* %57, i64 1, !dbg !46
  %59 = getelementptr inbounds i64, i64* %58, i64 1, !dbg !46
  %60 = bitcast i64* %55 to <4 x i64>*, !dbg !46
  store <4 x i64> <i64 -1, i64 -3, i64 -5, i64 -7>, <4 x i64>* %60, align 8, !dbg !46, !tbaa !4
  %61 = getelementptr inbounds i64, i64* %59, i64 1, !dbg !46
  %62 = getelementptr inbounds i64, i64* %61, i64 1, !dbg !46
  %63 = bitcast i64* %59 to <2 x i64>*, !dbg !46
  store <2 x i64> <i64 -9, i64 -11>, <2 x i64>* %63, align 8, !dbg !46, !tbaa !4
  %64 = getelementptr inbounds i64, i64* %62, i64 1, !dbg !46
  store i64 -13, i64* %62, align 8, !dbg !46, !tbaa !4
  %65 = getelementptr inbounds i64, i64* %64, i64 1, !dbg !46
  store i64* %65, i64** %53, align 8, !dbg !46, !tbaa !37
  store i64 -15, i64* %64, align 8, !dbg !46, !tbaa !4
  %send412 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @ic_take_arguments, i64 0), !dbg !46
  store i64* getelementptr inbounds ([32 x i64], [32 x i64]* @iseqEncodedArray, i64 0, i64 9), i64** %8, align 8, !dbg !46, !tbaa !12
  %rubyId_d419 = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !47
  %rawSym420 = call i64 @rb_id2sym(i64 %rubyId_d419), !dbg !47
  %66 = load i64*, i64** %53, align 8, !dbg !48, !tbaa !37
  %67 = getelementptr inbounds i64, i64* %66, i64 1, !dbg !48
  store i64 %selfRaw, i64* %66, align 8, !dbg !48, !tbaa !4
  %68 = getelementptr inbounds i64, i64* %67, i64 1, !dbg !48
  %69 = getelementptr inbounds i64, i64* %68, i64 1, !dbg !48
  %70 = getelementptr inbounds i64, i64* %69, i64 1, !dbg !48
  %71 = getelementptr inbounds i64, i64* %70, i64 1, !dbg !48
  %72 = bitcast i64* %67 to <4 x i64>*, !dbg !48
  store <4 x i64> <i64 -1, i64 -3, i64 -5, i64 -7>, <4 x i64>* %72, align 8, !dbg !48, !tbaa !4
  %73 = getelementptr inbounds i64, i64* %71, i64 1, !dbg !48
  %74 = getelementptr inbounds i64, i64* %73, i64 1, !dbg !48
  %75 = bitcast i64* %71 to <2 x i64>*, !dbg !48
  store <2 x i64> <i64 -9, i64 -11>, <2 x i64>* %75, align 8, !dbg !48, !tbaa !4
  %76 = getelementptr inbounds i64, i64* %74, i64 1, !dbg !48
  store i64* %76, i64** %53, align 8, !dbg !48, !tbaa !37
  store i64 -15, i64* %74, align 8, !dbg !48, !tbaa !4
  %send433 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.1, i64 0), !dbg !48
  store i64* getelementptr inbounds ([32 x i64], [32 x i64]* @iseqEncodedArray, i64 0, i64 10), i64** %8, align 8, !dbg !48, !tbaa !12
  %rubyId_d439 = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !49
  %rawSym440 = call i64 @rb_id2sym(i64 %rubyId_d439), !dbg !49
  %77 = load i64*, i64** %53, align 8, !dbg !50, !tbaa !37
  %78 = getelementptr inbounds i64, i64* %77, i64 1, !dbg !50
  store i64 %selfRaw, i64* %77, align 8, !dbg !50, !tbaa !4
  %79 = getelementptr inbounds i64, i64* %78, i64 1, !dbg !50
  %80 = getelementptr inbounds i64, i64* %79, i64 1, !dbg !50
  %81 = getelementptr inbounds i64, i64* %80, i64 1, !dbg !50
  %82 = getelementptr inbounds i64, i64* %81, i64 1, !dbg !50
  %83 = bitcast i64* %78 to <4 x i64>*, !dbg !50
  store <4 x i64> <i64 -1, i64 -3, i64 -5, i64 -7>, <4 x i64>* %83, align 8, !dbg !50, !tbaa !4
  %84 = getelementptr inbounds i64, i64* %82, i64 1, !dbg !50
  %85 = getelementptr inbounds i64, i64* %84, i64 1, !dbg !50
  store i64* %85, i64** %53, align 8, !dbg !50, !tbaa !37
  %86 = bitcast i64* %82 to <2 x i64>*, !dbg !50
  store <2 x i64> <i64 -9, i64 -15>, <2 x i64>* %86, align 8, !dbg !50, !tbaa !4
  %send452 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.2, i64 0), !dbg !50
  store i64* getelementptr inbounds ([32 x i64], [32 x i64]* @iseqEncodedArray, i64 0, i64 11), i64** %8, align 8, !dbg !50, !tbaa !12
  %rubyId_d457 = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !51
  %rawSym458 = call i64 @rb_id2sym(i64 %rubyId_d457), !dbg !51
  %87 = load i64*, i64** %53, align 8, !dbg !52, !tbaa !37
  %88 = getelementptr inbounds i64, i64* %87, i64 1, !dbg !52
  store i64 %selfRaw, i64* %87, align 8, !dbg !52, !tbaa !4
  %89 = getelementptr inbounds i64, i64* %88, i64 1, !dbg !52
  %90 = getelementptr inbounds i64, i64* %89, i64 1, !dbg !52
  %91 = getelementptr inbounds i64, i64* %90, i64 1, !dbg !52
  %92 = getelementptr inbounds i64, i64* %91, i64 1, !dbg !52
  %93 = bitcast i64* %88 to <4 x i64>*, !dbg !52
  store <4 x i64> <i64 -1, i64 -3, i64 -5, i64 -7>, <4 x i64>* %93, align 8, !dbg !52, !tbaa !4
  %94 = getelementptr inbounds i64, i64* %92, i64 1, !dbg !52
  store i64* %94, i64** %53, align 8, !dbg !52, !tbaa !37
  store i64 -15, i64* %92, align 8, !dbg !52, !tbaa !4
  %send469 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.3, i64 0), !dbg !52
  store i64* getelementptr inbounds ([32 x i64], [32 x i64]* @iseqEncodedArray, i64 0, i64 12), i64** %8, align 8, !dbg !52, !tbaa !12
  %rubyId_d473 = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !53
  %rawSym474 = call i64 @rb_id2sym(i64 %rubyId_d473), !dbg !53
  %95 = load i64*, i64** %53, align 8, !dbg !54, !tbaa !37
  %96 = getelementptr inbounds i64, i64* %95, i64 1, !dbg !54
  store i64 %selfRaw, i64* %95, align 8, !dbg !54, !tbaa !4
  %97 = getelementptr inbounds i64, i64* %96, i64 1, !dbg !54
  %98 = getelementptr inbounds i64, i64* %97, i64 1, !dbg !54
  %99 = getelementptr inbounds i64, i64* %98, i64 1, !dbg !54
  %100 = getelementptr inbounds i64, i64* %99, i64 1, !dbg !54
  store i64* %100, i64** %53, align 8, !dbg !54, !tbaa !37
  %101 = bitcast i64* %96 to <4 x i64>*, !dbg !54
  store <4 x i64> <i64 -1, i64 -3, i64 -5, i64 -15>, <4 x i64>* %101, align 8, !dbg !54, !tbaa !4
  %send484 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.4, i64 0), !dbg !54
  store i64* getelementptr inbounds ([32 x i64], [32 x i64]* @iseqEncodedArray, i64 0, i64 13), i64** %8, align 8, !dbg !54, !tbaa !12
  %rubyId_d487 = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !55
  %rawSym488 = call i64 @rb_id2sym(i64 %rubyId_d487), !dbg !55
  %102 = load i64*, i64** %53, align 8, !dbg !56, !tbaa !37
  %103 = getelementptr inbounds i64, i64* %102, i64 1, !dbg !56
  store i64 %selfRaw, i64* %102, align 8, !dbg !56, !tbaa !4
  %104 = getelementptr inbounds i64, i64* %103, i64 1, !dbg !56
  %105 = getelementptr inbounds i64, i64* %104, i64 1, !dbg !56
  %106 = bitcast i64* %103 to <2 x i64>*, !dbg !56
  store <2 x i64> <i64 -1, i64 -3>, <2 x i64>* %106, align 8, !dbg !56, !tbaa !4
  %107 = getelementptr inbounds i64, i64* %105, i64 1, !dbg !56
  store i64* %107, i64** %53, align 8, !dbg !56, !tbaa !37
  store i64 -15, i64* %105, align 8, !dbg !56, !tbaa !4
  %send497 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.5, i64 0), !dbg !56
  store i64* getelementptr inbounds ([32 x i64], [32 x i64]* @iseqEncodedArray, i64 0, i64 14), i64** %8, align 8, !dbg !56, !tbaa !12
  %rubyId_d499 = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !57
  %rawSym500 = call i64 @rb_id2sym(i64 %rubyId_d499), !dbg !57
  %108 = load i64*, i64** %53, align 8, !dbg !58, !tbaa !37
  %109 = getelementptr inbounds i64, i64* %108, i64 1, !dbg !58
  store i64 %selfRaw, i64* %108, align 8, !dbg !58, !tbaa !4
  %110 = getelementptr inbounds i64, i64* %109, i64 1, !dbg !58
  %111 = getelementptr inbounds i64, i64* %110, i64 1, !dbg !58
  store i64* %111, i64** %53, align 8, !dbg !58, !tbaa !37
  %112 = bitcast i64* %109 to <2 x i64>*, !dbg !58
  store <2 x i64> <i64 -1, i64 -15>, <2 x i64>* %112, align 8, !dbg !58, !tbaa !4
  %send508 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.6, i64 0), !dbg !58
  store i64* getelementptr inbounds ([32 x i64], [32 x i64]* @iseqEncodedArray, i64 0, i64 16), i64** %8, align 8, !dbg !58, !tbaa !12
  %rubyId_d516 = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !59
  %rawSym517 = call i64 @rb_id2sym(i64 %rubyId_d516), !dbg !59
  %rubyId_e519 = load i64, i64* @rubyIdPrecomputed_e, align 8, !dbg !60
  %rawSym520 = call i64 @rb_id2sym(i64 %rubyId_e519), !dbg !60
  %113 = load i64*, i64** %53, align 8, !dbg !61, !tbaa !37
  %114 = getelementptr inbounds i64, i64* %113, i64 1, !dbg !61
  store i64 %selfRaw, i64* %113, align 8, !dbg !61, !tbaa !4
  %115 = getelementptr inbounds i64, i64* %114, i64 1, !dbg !61
  %116 = getelementptr inbounds i64, i64* %115, i64 1, !dbg !61
  %117 = getelementptr inbounds i64, i64* %116, i64 1, !dbg !61
  %118 = getelementptr inbounds i64, i64* %117, i64 1, !dbg !61
  %119 = bitcast i64* %114 to <4 x i64>*, !dbg !61
  store <4 x i64> <i64 -1, i64 -3, i64 -5, i64 -7>, <4 x i64>* %119, align 8, !dbg !61, !tbaa !4
  %120 = getelementptr inbounds i64, i64* %118, i64 1, !dbg !61
  %121 = getelementptr inbounds i64, i64* %120, i64 1, !dbg !61
  %122 = bitcast i64* %118 to <2 x i64>*, !dbg !61
  store <2 x i64> <i64 -9, i64 -11>, <2 x i64>* %122, align 8, !dbg !61, !tbaa !4
  %123 = getelementptr inbounds i64, i64* %121, i64 1, !dbg !61
  store i64 -13, i64* %121, align 8, !dbg !61, !tbaa !4
  %124 = getelementptr inbounds i64, i64* %123, i64 1, !dbg !61
  store i64 -15, i64* %123, align 8, !dbg !61, !tbaa !4
  %125 = getelementptr inbounds i64, i64* %124, i64 1, !dbg !61
  store i64* %125, i64** %53, align 8, !dbg !61, !tbaa !37
  store i64 -17, i64* %124, align 8, !dbg !61, !tbaa !4
  %send535 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.7, i64 0), !dbg !61
  store i64* getelementptr inbounds ([32 x i64], [32 x i64]* @iseqEncodedArray, i64 0, i64 17), i64** %8, align 8, !dbg !61, !tbaa !12
  %rubyId_d542 = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !62
  %rawSym543 = call i64 @rb_id2sym(i64 %rubyId_d542), !dbg !62
  %rubyId_e545 = load i64, i64* @rubyIdPrecomputed_e, align 8, !dbg !63
  %rawSym546 = call i64 @rb_id2sym(i64 %rubyId_e545), !dbg !63
  %126 = load i64*, i64** %53, align 8, !dbg !64, !tbaa !37
  %127 = getelementptr inbounds i64, i64* %126, i64 1, !dbg !64
  store i64 %selfRaw, i64* %126, align 8, !dbg !64, !tbaa !4
  %128 = getelementptr inbounds i64, i64* %127, i64 1, !dbg !64
  %129 = getelementptr inbounds i64, i64* %128, i64 1, !dbg !64
  %130 = getelementptr inbounds i64, i64* %129, i64 1, !dbg !64
  %131 = getelementptr inbounds i64, i64* %130, i64 1, !dbg !64
  %132 = bitcast i64* %127 to <4 x i64>*, !dbg !64
  store <4 x i64> <i64 -1, i64 -3, i64 -5, i64 -7>, <4 x i64>* %132, align 8, !dbg !64, !tbaa !4
  %133 = getelementptr inbounds i64, i64* %131, i64 1, !dbg !64
  %134 = getelementptr inbounds i64, i64* %133, i64 1, !dbg !64
  %135 = bitcast i64* %131 to <2 x i64>*, !dbg !64
  store <2 x i64> <i64 -9, i64 -11>, <2 x i64>* %135, align 8, !dbg !64, !tbaa !4
  %136 = getelementptr inbounds i64, i64* %134, i64 1, !dbg !64
  store i64 -15, i64* %134, align 8, !dbg !64, !tbaa !4
  %137 = getelementptr inbounds i64, i64* %136, i64 1, !dbg !64
  store i64* %137, i64** %53, align 8, !dbg !64, !tbaa !37
  store i64 -17, i64* %136, align 8, !dbg !64, !tbaa !4
  %send560 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.8, i64 0), !dbg !64
  store i64* getelementptr inbounds ([32 x i64], [32 x i64]* @iseqEncodedArray, i64 0, i64 18), i64** %8, align 8, !dbg !64, !tbaa !12
  %rubyId_d566 = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !65
  %rawSym567 = call i64 @rb_id2sym(i64 %rubyId_d566), !dbg !65
  %rubyId_e569 = load i64, i64* @rubyIdPrecomputed_e, align 8, !dbg !66
  %rawSym570 = call i64 @rb_id2sym(i64 %rubyId_e569), !dbg !66
  %138 = load i64*, i64** %53, align 8, !dbg !67, !tbaa !37
  %139 = getelementptr inbounds i64, i64* %138, i64 1, !dbg !67
  store i64 %selfRaw, i64* %138, align 8, !dbg !67, !tbaa !4
  %140 = getelementptr inbounds i64, i64* %139, i64 1, !dbg !67
  %141 = getelementptr inbounds i64, i64* %140, i64 1, !dbg !67
  %142 = getelementptr inbounds i64, i64* %141, i64 1, !dbg !67
  %143 = getelementptr inbounds i64, i64* %142, i64 1, !dbg !67
  %144 = bitcast i64* %139 to <4 x i64>*, !dbg !67
  store <4 x i64> <i64 -1, i64 -3, i64 -5, i64 -7>, <4 x i64>* %144, align 8, !dbg !67, !tbaa !4
  %145 = getelementptr inbounds i64, i64* %143, i64 1, !dbg !67
  %146 = getelementptr inbounds i64, i64* %145, i64 1, !dbg !67
  %147 = bitcast i64* %143 to <2 x i64>*, !dbg !67
  store <2 x i64> <i64 -9, i64 -15>, <2 x i64>* %147, align 8, !dbg !67, !tbaa !4
  %148 = getelementptr inbounds i64, i64* %146, i64 1, !dbg !67
  store i64* %148, i64** %53, align 8, !dbg !67, !tbaa !37
  store i64 -17, i64* %146, align 8, !dbg !67, !tbaa !4
  %send583 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.9, i64 0), !dbg !67
  store i64* getelementptr inbounds ([32 x i64], [32 x i64]* @iseqEncodedArray, i64 0, i64 19), i64** %8, align 8, !dbg !67, !tbaa !12
  %rubyId_d588 = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !68
  %rawSym589 = call i64 @rb_id2sym(i64 %rubyId_d588), !dbg !68
  %rubyId_e591 = load i64, i64* @rubyIdPrecomputed_e, align 8, !dbg !69
  %rawSym592 = call i64 @rb_id2sym(i64 %rubyId_e591), !dbg !69
  %149 = load i64*, i64** %53, align 8, !dbg !70, !tbaa !37
  %150 = getelementptr inbounds i64, i64* %149, i64 1, !dbg !70
  store i64 %selfRaw, i64* %149, align 8, !dbg !70, !tbaa !4
  %151 = getelementptr inbounds i64, i64* %150, i64 1, !dbg !70
  %152 = getelementptr inbounds i64, i64* %151, i64 1, !dbg !70
  %153 = getelementptr inbounds i64, i64* %152, i64 1, !dbg !70
  %154 = getelementptr inbounds i64, i64* %153, i64 1, !dbg !70
  %155 = bitcast i64* %150 to <4 x i64>*, !dbg !70
  store <4 x i64> <i64 -1, i64 -3, i64 -5, i64 -7>, <4 x i64>* %155, align 8, !dbg !70, !tbaa !4
  %156 = getelementptr inbounds i64, i64* %154, i64 1, !dbg !70
  %157 = getelementptr inbounds i64, i64* %156, i64 1, !dbg !70
  store i64* %157, i64** %53, align 8, !dbg !70, !tbaa !37
  %158 = bitcast i64* %154 to <2 x i64>*, !dbg !70
  store <2 x i64> <i64 -15, i64 -17>, <2 x i64>* %158, align 8, !dbg !70, !tbaa !4
  %send604 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.10, i64 0), !dbg !70
  store i64* getelementptr inbounds ([32 x i64], [32 x i64]* @iseqEncodedArray, i64 0, i64 20), i64** %8, align 8, !dbg !70, !tbaa !12
  %rubyId_d608 = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !71
  %rawSym609 = call i64 @rb_id2sym(i64 %rubyId_d608), !dbg !71
  %rubyId_e611 = load i64, i64* @rubyIdPrecomputed_e, align 8, !dbg !72
  %rawSym612 = call i64 @rb_id2sym(i64 %rubyId_e611), !dbg !72
  %159 = load i64*, i64** %53, align 8, !dbg !73, !tbaa !37
  %160 = getelementptr inbounds i64, i64* %159, i64 1, !dbg !73
  store i64 %selfRaw, i64* %159, align 8, !dbg !73, !tbaa !4
  %161 = getelementptr inbounds i64, i64* %160, i64 1, !dbg !73
  %162 = getelementptr inbounds i64, i64* %161, i64 1, !dbg !73
  %163 = getelementptr inbounds i64, i64* %162, i64 1, !dbg !73
  %164 = getelementptr inbounds i64, i64* %163, i64 1, !dbg !73
  %165 = bitcast i64* %160 to <4 x i64>*, !dbg !73
  store <4 x i64> <i64 -1, i64 -3, i64 -5, i64 -15>, <4 x i64>* %165, align 8, !dbg !73, !tbaa !4
  %166 = getelementptr inbounds i64, i64* %164, i64 1, !dbg !73
  store i64* %166, i64** %53, align 8, !dbg !73, !tbaa !37
  store i64 -17, i64* %164, align 8, !dbg !73, !tbaa !4
  %send623 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.11, i64 0), !dbg !73
  store i64* getelementptr inbounds ([32 x i64], [32 x i64]* @iseqEncodedArray, i64 0, i64 21), i64** %8, align 8, !dbg !73, !tbaa !12
  %rubyId_d626 = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !74
  %rawSym627 = call i64 @rb_id2sym(i64 %rubyId_d626), !dbg !74
  %rubyId_e629 = load i64, i64* @rubyIdPrecomputed_e, align 8, !dbg !75
  %rawSym630 = call i64 @rb_id2sym(i64 %rubyId_e629), !dbg !75
  %167 = load i64*, i64** %53, align 8, !dbg !76, !tbaa !37
  %168 = getelementptr inbounds i64, i64* %167, i64 1, !dbg !76
  store i64 %selfRaw, i64* %167, align 8, !dbg !76, !tbaa !4
  %169 = getelementptr inbounds i64, i64* %168, i64 1, !dbg !76
  %170 = getelementptr inbounds i64, i64* %169, i64 1, !dbg !76
  %171 = getelementptr inbounds i64, i64* %170, i64 1, !dbg !76
  %172 = getelementptr inbounds i64, i64* %171, i64 1, !dbg !76
  store i64* %172, i64** %53, align 8, !dbg !76, !tbaa !37
  %173 = bitcast i64* %168 to <4 x i64>*, !dbg !76
  store <4 x i64> <i64 -1, i64 -3, i64 -15, i64 -17>, <4 x i64>* %173, align 8, !dbg !76, !tbaa !4
  %send640 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.12, i64 0), !dbg !76
  store i64* getelementptr inbounds ([32 x i64], [32 x i64]* @iseqEncodedArray, i64 0, i64 22), i64** %8, align 8, !dbg !76, !tbaa !12
  %rubyId_d642 = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !77
  %rawSym643 = call i64 @rb_id2sym(i64 %rubyId_d642), !dbg !77
  %rubyId_e645 = load i64, i64* @rubyIdPrecomputed_e, align 8, !dbg !78
  %rawSym646 = call i64 @rb_id2sym(i64 %rubyId_e645), !dbg !78
  %174 = load i64*, i64** %53, align 8, !dbg !79, !tbaa !37
  %175 = getelementptr inbounds i64, i64* %174, i64 1, !dbg !79
  store i64 %selfRaw, i64* %174, align 8, !dbg !79, !tbaa !4
  %176 = getelementptr inbounds i64, i64* %175, i64 1, !dbg !79
  %177 = getelementptr inbounds i64, i64* %176, i64 1, !dbg !79
  %178 = bitcast i64* %175 to <2 x i64>*, !dbg !79
  store <2 x i64> <i64 -1, i64 -15>, <2 x i64>* %178, align 8, !dbg !79, !tbaa !4
  %179 = getelementptr inbounds i64, i64* %177, i64 1, !dbg !79
  store i64* %179, i64** %53, align 8, !dbg !79, !tbaa !37
  store i64 -17, i64* %177, align 8, !dbg !79, !tbaa !4
  %send655 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.13, i64 0), !dbg !79
  store i64* getelementptr inbounds ([32 x i64], [32 x i64]* @iseqEncodedArray, i64 0, i64 24), i64** %8, align 8, !dbg !79, !tbaa !12
  %rubyId_d663 = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !80
  %rawSym664 = call i64 @rb_id2sym(i64 %rubyId_d663), !dbg !80
  %rubyId_e666 = load i64, i64* @rubyIdPrecomputed_e, align 8, !dbg !81
  %rawSym667 = call i64 @rb_id2sym(i64 %rubyId_e666), !dbg !81
  %rubyId_baz = load i64, i64* @rubyIdPrecomputed_baz, align 8, !dbg !82
  %rawSym669 = call i64 @rb_id2sym(i64 %rubyId_baz), !dbg !82
  %180 = load i64*, i64** %53, align 8, !dbg !83, !tbaa !37
  %181 = getelementptr inbounds i64, i64* %180, i64 1, !dbg !83
  store i64 %selfRaw, i64* %180, align 8, !dbg !83, !tbaa !4
  %182 = getelementptr inbounds i64, i64* %181, i64 1, !dbg !83
  %183 = getelementptr inbounds i64, i64* %182, i64 1, !dbg !83
  %184 = getelementptr inbounds i64, i64* %183, i64 1, !dbg !83
  %185 = getelementptr inbounds i64, i64* %184, i64 1, !dbg !83
  %186 = bitcast i64* %181 to <4 x i64>*, !dbg !83
  store <4 x i64> <i64 -1, i64 -3, i64 -5, i64 -7>, <4 x i64>* %186, align 8, !dbg !83, !tbaa !4
  %187 = getelementptr inbounds i64, i64* %185, i64 1, !dbg !83
  %188 = getelementptr inbounds i64, i64* %187, i64 1, !dbg !83
  %189 = bitcast i64* %185 to <2 x i64>*, !dbg !83
  store <2 x i64> <i64 -9, i64 -11>, <2 x i64>* %189, align 8, !dbg !83, !tbaa !4
  %190 = getelementptr inbounds i64, i64* %188, i64 1, !dbg !83
  store i64 -13, i64* %188, align 8, !dbg !83, !tbaa !4
  %191 = getelementptr inbounds i64, i64* %190, i64 1, !dbg !83
  store i64 -15, i64* %190, align 8, !dbg !83, !tbaa !4
  %192 = getelementptr inbounds i64, i64* %191, i64 1, !dbg !83
  store i64 -17, i64* %191, align 8, !dbg !83, !tbaa !4
  %193 = getelementptr inbounds i64, i64* %192, i64 1, !dbg !83
  store i64* %193, i64** %53, align 8, !dbg !83, !tbaa !37
  store i64 -19, i64* %192, align 8, !dbg !83, !tbaa !4
  %send685 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.14, i64 0), !dbg !83
  store i64* getelementptr inbounds ([32 x i64], [32 x i64]* @iseqEncodedArray, i64 0, i64 25), i64** %8, align 8, !dbg !83, !tbaa !12
  %rubyId_d692 = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !84
  %rawSym693 = call i64 @rb_id2sym(i64 %rubyId_d692), !dbg !84
  %rubyId_e695 = load i64, i64* @rubyIdPrecomputed_e, align 8, !dbg !85
  %rawSym696 = call i64 @rb_id2sym(i64 %rubyId_e695), !dbg !85
  %rubyId_baz698 = load i64, i64* @rubyIdPrecomputed_baz, align 8, !dbg !86
  %rawSym699 = call i64 @rb_id2sym(i64 %rubyId_baz698), !dbg !86
  %194 = load i64*, i64** %53, align 8, !dbg !87, !tbaa !37
  %195 = getelementptr inbounds i64, i64* %194, i64 1, !dbg !87
  store i64 %selfRaw, i64* %194, align 8, !dbg !87, !tbaa !4
  %196 = getelementptr inbounds i64, i64* %195, i64 1, !dbg !87
  %197 = getelementptr inbounds i64, i64* %196, i64 1, !dbg !87
  %198 = getelementptr inbounds i64, i64* %197, i64 1, !dbg !87
  %199 = getelementptr inbounds i64, i64* %198, i64 1, !dbg !87
  %200 = bitcast i64* %195 to <4 x i64>*, !dbg !87
  store <4 x i64> <i64 -1, i64 -3, i64 -5, i64 -7>, <4 x i64>* %200, align 8, !dbg !87, !tbaa !4
  %201 = getelementptr inbounds i64, i64* %199, i64 1, !dbg !87
  %202 = getelementptr inbounds i64, i64* %201, i64 1, !dbg !87
  %203 = bitcast i64* %199 to <2 x i64>*, !dbg !87
  store <2 x i64> <i64 -9, i64 -11>, <2 x i64>* %203, align 8, !dbg !87, !tbaa !4
  %204 = getelementptr inbounds i64, i64* %202, i64 1, !dbg !87
  store i64 -15, i64* %202, align 8, !dbg !87, !tbaa !4
  %205 = getelementptr inbounds i64, i64* %204, i64 1, !dbg !87
  store i64 -17, i64* %204, align 8, !dbg !87, !tbaa !4
  %206 = getelementptr inbounds i64, i64* %205, i64 1, !dbg !87
  store i64* %206, i64** %53, align 8, !dbg !87, !tbaa !37
  store i64 -19, i64* %205, align 8, !dbg !87, !tbaa !4
  %send714 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.15, i64 0), !dbg !87
  store i64* getelementptr inbounds ([32 x i64], [32 x i64]* @iseqEncodedArray, i64 0, i64 26), i64** %8, align 8, !dbg !87, !tbaa !12
  %rubyId_d720 = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !88
  %rawSym721 = call i64 @rb_id2sym(i64 %rubyId_d720), !dbg !88
  %rubyId_e723 = load i64, i64* @rubyIdPrecomputed_e, align 8, !dbg !89
  %rawSym724 = call i64 @rb_id2sym(i64 %rubyId_e723), !dbg !89
  %rubyId_baz726 = load i64, i64* @rubyIdPrecomputed_baz, align 8, !dbg !90
  %rawSym727 = call i64 @rb_id2sym(i64 %rubyId_baz726), !dbg !90
  %207 = load i64*, i64** %53, align 8, !dbg !91, !tbaa !37
  %208 = getelementptr inbounds i64, i64* %207, i64 1, !dbg !91
  store i64 %selfRaw, i64* %207, align 8, !dbg !91, !tbaa !4
  %209 = getelementptr inbounds i64, i64* %208, i64 1, !dbg !91
  %210 = getelementptr inbounds i64, i64* %209, i64 1, !dbg !91
  %211 = getelementptr inbounds i64, i64* %210, i64 1, !dbg !91
  %212 = getelementptr inbounds i64, i64* %211, i64 1, !dbg !91
  %213 = bitcast i64* %208 to <4 x i64>*, !dbg !91
  store <4 x i64> <i64 -1, i64 -3, i64 -5, i64 -7>, <4 x i64>* %213, align 8, !dbg !91, !tbaa !4
  %214 = getelementptr inbounds i64, i64* %212, i64 1, !dbg !91
  %215 = getelementptr inbounds i64, i64* %214, i64 1, !dbg !91
  %216 = bitcast i64* %212 to <2 x i64>*, !dbg !91
  store <2 x i64> <i64 -9, i64 -15>, <2 x i64>* %216, align 8, !dbg !91, !tbaa !4
  %217 = getelementptr inbounds i64, i64* %215, i64 1, !dbg !91
  store i64 -17, i64* %215, align 8, !dbg !91, !tbaa !4
  %218 = getelementptr inbounds i64, i64* %217, i64 1, !dbg !91
  store i64* %218, i64** %53, align 8, !dbg !91, !tbaa !37
  store i64 -19, i64* %217, align 8, !dbg !91, !tbaa !4
  %send741 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.16, i64 0), !dbg !91
  store i64* getelementptr inbounds ([32 x i64], [32 x i64]* @iseqEncodedArray, i64 0, i64 27), i64** %8, align 8, !dbg !91, !tbaa !12
  %rubyId_d746 = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !92
  %rawSym747 = call i64 @rb_id2sym(i64 %rubyId_d746), !dbg !92
  %rubyId_e749 = load i64, i64* @rubyIdPrecomputed_e, align 8, !dbg !93
  %rawSym750 = call i64 @rb_id2sym(i64 %rubyId_e749), !dbg !93
  %rubyId_baz752 = load i64, i64* @rubyIdPrecomputed_baz, align 8, !dbg !94
  %rawSym753 = call i64 @rb_id2sym(i64 %rubyId_baz752), !dbg !94
  %219 = load i64*, i64** %53, align 8, !dbg !95, !tbaa !37
  %220 = getelementptr inbounds i64, i64* %219, i64 1, !dbg !95
  store i64 %selfRaw, i64* %219, align 8, !dbg !95, !tbaa !4
  %221 = getelementptr inbounds i64, i64* %220, i64 1, !dbg !95
  %222 = getelementptr inbounds i64, i64* %221, i64 1, !dbg !95
  %223 = getelementptr inbounds i64, i64* %222, i64 1, !dbg !95
  %224 = getelementptr inbounds i64, i64* %223, i64 1, !dbg !95
  %225 = bitcast i64* %220 to <4 x i64>*, !dbg !95
  store <4 x i64> <i64 -1, i64 -3, i64 -5, i64 -7>, <4 x i64>* %225, align 8, !dbg !95, !tbaa !4
  %226 = getelementptr inbounds i64, i64* %224, i64 1, !dbg !95
  %227 = getelementptr inbounds i64, i64* %226, i64 1, !dbg !95
  %228 = bitcast i64* %224 to <2 x i64>*, !dbg !95
  store <2 x i64> <i64 -15, i64 -17>, <2 x i64>* %228, align 8, !dbg !95, !tbaa !4
  %229 = getelementptr inbounds i64, i64* %227, i64 1, !dbg !95
  store i64* %229, i64** %53, align 8, !dbg !95, !tbaa !37
  store i64 -19, i64* %227, align 8, !dbg !95, !tbaa !4
  %send766 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.17, i64 0), !dbg !95
  store i64* getelementptr inbounds ([32 x i64], [32 x i64]* @iseqEncodedArray, i64 0, i64 28), i64** %8, align 8, !dbg !95, !tbaa !12
  %rubyId_d770 = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !96
  %rawSym771 = call i64 @rb_id2sym(i64 %rubyId_d770), !dbg !96
  %rubyId_e773 = load i64, i64* @rubyIdPrecomputed_e, align 8, !dbg !97
  %rawSym774 = call i64 @rb_id2sym(i64 %rubyId_e773), !dbg !97
  %rubyId_baz776 = load i64, i64* @rubyIdPrecomputed_baz, align 8, !dbg !98
  %rawSym777 = call i64 @rb_id2sym(i64 %rubyId_baz776), !dbg !98
  %230 = load i64*, i64** %53, align 8, !dbg !99, !tbaa !37
  %231 = getelementptr inbounds i64, i64* %230, i64 1, !dbg !99
  store i64 %selfRaw, i64* %230, align 8, !dbg !99, !tbaa !4
  %232 = getelementptr inbounds i64, i64* %231, i64 1, !dbg !99
  %233 = getelementptr inbounds i64, i64* %232, i64 1, !dbg !99
  %234 = getelementptr inbounds i64, i64* %233, i64 1, !dbg !99
  %235 = getelementptr inbounds i64, i64* %234, i64 1, !dbg !99
  %236 = bitcast i64* %231 to <4 x i64>*, !dbg !99
  store <4 x i64> <i64 -1, i64 -3, i64 -5, i64 -15>, <4 x i64>* %236, align 8, !dbg !99, !tbaa !4
  %237 = getelementptr inbounds i64, i64* %235, i64 1, !dbg !99
  %238 = getelementptr inbounds i64, i64* %237, i64 1, !dbg !99
  store i64* %238, i64** %53, align 8, !dbg !99, !tbaa !37
  %239 = bitcast i64* %235 to <2 x i64>*, !dbg !99
  store <2 x i64> <i64 -17, i64 -19>, <2 x i64>* %239, align 8, !dbg !99, !tbaa !4
  %send789 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.18, i64 0), !dbg !99
  store i64* getelementptr inbounds ([32 x i64], [32 x i64]* @iseqEncodedArray, i64 0, i64 29), i64** %8, align 8, !dbg !99, !tbaa !12
  %rubyId_d792 = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !100
  %rawSym793 = call i64 @rb_id2sym(i64 %rubyId_d792), !dbg !100
  %rubyId_e795 = load i64, i64* @rubyIdPrecomputed_e, align 8, !dbg !101
  %rawSym796 = call i64 @rb_id2sym(i64 %rubyId_e795), !dbg !101
  %rubyId_baz798 = load i64, i64* @rubyIdPrecomputed_baz, align 8, !dbg !102
  %rawSym799 = call i64 @rb_id2sym(i64 %rubyId_baz798), !dbg !102
  %240 = load i64*, i64** %53, align 8, !dbg !103, !tbaa !37
  %241 = getelementptr inbounds i64, i64* %240, i64 1, !dbg !103
  store i64 %selfRaw, i64* %240, align 8, !dbg !103, !tbaa !4
  %242 = getelementptr inbounds i64, i64* %241, i64 1, !dbg !103
  %243 = getelementptr inbounds i64, i64* %242, i64 1, !dbg !103
  %244 = getelementptr inbounds i64, i64* %243, i64 1, !dbg !103
  %245 = getelementptr inbounds i64, i64* %244, i64 1, !dbg !103
  %246 = bitcast i64* %241 to <4 x i64>*, !dbg !103
  store <4 x i64> <i64 -1, i64 -3, i64 -15, i64 -17>, <4 x i64>* %246, align 8, !dbg !103, !tbaa !4
  %247 = getelementptr inbounds i64, i64* %245, i64 1, !dbg !103
  store i64* %247, i64** %53, align 8, !dbg !103, !tbaa !37
  store i64 -19, i64* %245, align 8, !dbg !103, !tbaa !4
  %send810 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.19, i64 0), !dbg !103
  store i64* getelementptr inbounds ([32 x i64], [32 x i64]* @iseqEncodedArray, i64 0, i64 30), i64** %8, align 8, !dbg !103, !tbaa !12
  %rubyId_d812 = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !104
  %rawSym813 = call i64 @rb_id2sym(i64 %rubyId_d812), !dbg !104
  %rubyId_e815 = load i64, i64* @rubyIdPrecomputed_e, align 8, !dbg !105
  %rawSym816 = call i64 @rb_id2sym(i64 %rubyId_e815), !dbg !105
  %rubyId_baz818 = load i64, i64* @rubyIdPrecomputed_baz, align 8, !dbg !106
  %rawSym819 = call i64 @rb_id2sym(i64 %rubyId_baz818), !dbg !106
  %248 = load i64*, i64** %53, align 8, !dbg !107, !tbaa !37
  %249 = getelementptr inbounds i64, i64* %248, i64 1, !dbg !107
  store i64 %selfRaw, i64* %248, align 8, !dbg !107, !tbaa !4
  %250 = getelementptr inbounds i64, i64* %249, i64 1, !dbg !107
  %251 = getelementptr inbounds i64, i64* %250, i64 1, !dbg !107
  %252 = getelementptr inbounds i64, i64* %251, i64 1, !dbg !107
  %253 = getelementptr inbounds i64, i64* %252, i64 1, !dbg !107
  store i64* %253, i64** %53, align 8, !dbg !107, !tbaa !37
  %254 = bitcast i64* %249 to <4 x i64>*, !dbg !107
  store <4 x i64> <i64 -1, i64 -15, i64 -17, i64 -19>, <4 x i64>* %254, align 8, !dbg !107, !tbaa !4
  %send829 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.20, i64 0), !dbg !107
  br label %postProcess, !dbg !107

fastSymCallIntrinsic_Static_keep_def:             ; preds = %37, %45, %sorbet_processThrowReturnSetJmp.exit
  store i64* getelementptr inbounds ([32 x i64], [32 x i64]* @iseqEncodedArray, i64 0, i64 4), i64** %8, align 8, !dbg !108, !tbaa !12
  %rubyId_take_arguments = load i64, i64* @rubyIdPrecomputed_take_arguments, align 8, !dbg !44
  %rawSym = call i64 @rb_id2sym(i64 %rubyId_take_arguments), !dbg !44
  %rubyId_normal = load i64, i64* @rubyIdPrecomputed_normal, align 8, !dbg !44
  %rawSym386 = call i64 @rb_id2sym(i64 %rubyId_normal), !dbg !44
  %255 = load i64, i64* @rb_cObject, align 8, !dbg !44
  %stackFrame387 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Object#take_arguments", align 8, !dbg !44
  %256 = call noalias nonnull i8* @ruby_xcalloc(i64 noundef 1, i64 noundef 64) #13, !dbg !44
  %257 = bitcast i8* %256 to i16*, !dbg !44
  %258 = load i16, i16* %257, align 8, !dbg !44
  %259 = and i16 %258, -384, !dbg !44
  %260 = or i16 %259, 119, !dbg !44
  store i16 %260, i16* %257, align 8, !dbg !44
  %261 = getelementptr inbounds i8, i8* %256, i64 8, !dbg !44
  %262 = bitcast i8* %261 to i32*, !dbg !44
  %263 = getelementptr inbounds i8, i8* %256, i64 12, !dbg !44
  %264 = bitcast i8* %263 to i32*, !dbg !44
  %265 = getelementptr inbounds i8, i8* %256, i64 16, !dbg !44
  %266 = getelementptr inbounds i8, i8* %256, i64 20, !dbg !44
  %267 = bitcast i8* %266 to i32*, !dbg !44
  store i32 0, i32* %267, align 4, !dbg !44, !tbaa !109
  %268 = getelementptr inbounds i8, i8* %256, i64 24, !dbg !44
  %269 = bitcast i8* %268 to i32*, !dbg !44
  store i32 0, i32* %269, align 8, !dbg !44, !tbaa !112
  %270 = getelementptr inbounds i8, i8* %256, i64 28, !dbg !44
  %271 = bitcast i8* %270 to i32*, !dbg !44
  store i32 3, i32* %271, align 4, !dbg !44, !tbaa !113
  %272 = getelementptr inbounds i8, i8* %256, i64 4, !dbg !44
  %273 = bitcast i8* %272 to i32*, !dbg !44
  %274 = bitcast i32* %273 to <4 x i32>*, !dbg !44
  store <4 x i32> <i32 7, i32 1, i32 1, i32 2>, <4 x i32>* %274, align 4, !dbg !44, !tbaa !114
  %positional_table = alloca i64, i32 4, align 8, !dbg !44
  %rubyId_a = load i64, i64* @rubyIdPrecomputed_a, align 8, !dbg !44
  store i64 %rubyId_a, i64* %positional_table, align 8, !dbg !44
  %rubyId_b = load i64, i64* @rubyIdPrecomputed_b, align 8, !dbg !44
  %275 = getelementptr i64, i64* %positional_table, i32 1, !dbg !44
  store i64 %rubyId_b, i64* %275, align 8, !dbg !44
  %rubyId_c = load i64, i64* @rubyIdPrecomputed_c, align 8, !dbg !44
  %276 = getelementptr i64, i64* %positional_table, i32 2, !dbg !44
  store i64 %rubyId_c, i64* %276, align 8, !dbg !44
  %rubyId_g = load i64, i64* @rubyIdPrecomputed_g, align 8, !dbg !44
  %277 = getelementptr i64, i64* %positional_table, i32 3, !dbg !44
  store i64 %rubyId_g, i64* %277, align 8, !dbg !44
  %278 = call noalias nonnull i8* @ruby_xmalloc2(i64 noundef 4, i64 noundef 8) #13, !dbg !44
  %279 = bitcast i64* %positional_table to i8*, !dbg !44
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* nocapture nonnull writeonly align 1 %278, i8* nocapture noundef nonnull readonly align 8 dereferenceable(24) %279, i64 noundef 32, i1 noundef false) #4, !dbg !44
  %280 = getelementptr inbounds i8, i8* %256, i64 32, !dbg !44
  %281 = bitcast i8* %280 to i8**, !dbg !44
  store i8* %278, i8** %281, align 8, !dbg !44, !tbaa !115
  %keyword_table = alloca i64, i32 3, align 8, !dbg !44
  %rubyId_d = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !44
  store i64 %rubyId_d, i64* %keyword_table, align 8, !dbg !44
  %rubyId_e = load i64, i64* @rubyIdPrecomputed_e, align 8, !dbg !44
  %282 = getelementptr i64, i64* %keyword_table, i32 1, !dbg !44
  store i64 %rubyId_e, i64* %282, align 8, !dbg !44
  %rubyId_f = load i64, i64* @rubyIdPrecomputed_f, align 8, !dbg !44
  %283 = getelementptr i64, i64* %keyword_table, i32 2, !dbg !44
  store i64 %rubyId_f, i64* %283, align 8, !dbg !44
  %284 = getelementptr inbounds i8, i8* %256, i64 40, !dbg !44
  %285 = bitcast i8* %284 to i32*, !dbg !44
  store i32 2, i32* %285, align 8, !dbg !44, !tbaa !116
  %286 = getelementptr inbounds i8, i8* %256, i64 44, !dbg !44
  %287 = bitcast i8* %286 to i32*, !dbg !44
  store i32 1, i32* %287, align 4, !dbg !44, !tbaa !117
  %288 = load i32, i32* %262, align 8, !dbg !44, !tbaa !118
  %289 = load i32, i32* %264, align 4, !dbg !44, !tbaa !119
  %290 = add i32 %288, 2, !dbg !44
  %291 = add i32 %290, %289, !dbg !44
  %292 = getelementptr inbounds i8, i8* %256, i64 48, !dbg !44
  %293 = bitcast i8* %292 to i32*, !dbg !44
  store i32 %291, i32* %293, align 8, !dbg !44, !tbaa !120
  %294 = load i16, i16* %257, align 8, !dbg !44
  %295 = and i16 %294, 32, !dbg !44
  %296 = icmp eq i16 %295, 0, !dbg !44
  br i1 %296, label %sorbet_setupParamKeywords.exit, label %297, !dbg !44

297:                                              ; preds = %fastSymCallIntrinsic_Static_keep_def
  %298 = add nsw i32 %291, 1, !dbg !44
  %299 = getelementptr inbounds i8, i8* %256, i64 52, !dbg !44
  %300 = bitcast i8* %299 to i32*, !dbg !44
  store i32 %298, i32* %300, align 4, !dbg !44, !tbaa !121
  br label %sorbet_setupParamKeywords.exit, !dbg !44

sorbet_setupParamKeywords.exit:                   ; preds = %fastSymCallIntrinsic_Static_keep_def, %297
  %301 = call noalias nonnull i8* @ruby_xmalloc2(i64 noundef 3, i64 noundef 8) #13, !dbg !44
  %302 = bitcast i64* %keyword_table to i8*, !dbg !44
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* nocapture nonnull writeonly align 1 %301, i8* nocapture noundef nonnull readonly align 8 dereferenceable(24) %302, i64 noundef 24, i1 noundef false) #4, !dbg !44
  %303 = getelementptr inbounds i8, i8* %256, i64 56, !dbg !44
  %304 = bitcast i8* %303 to i8**, !dbg !44
  store i8* %301, i8** %304, align 8, !dbg !44, !tbaa !122
  %305 = call i64 @rb_intern(i8* noundef getelementptr inbounds ([15 x i8], [15 x i8]* @str_take_arguments, i64 0, i64 0)) #4, !dbg !44
  %306 = bitcast i8* %256 to %struct.rb_sorbet_param_struct*, !dbg !44
  %307 = bitcast %struct.rb_iseq_struct* %stackFrame387 to i8*, !dbg !44
  call void @rb_add_method_sorbet(i64 %255, i64 %305, i64 (i32, i64*, i64, %struct.rb_control_frame_struct*)* noundef @"func_Object#take_arguments", %struct.rb_sorbet_param_struct* nonnull %306, i32 noundef 1, i8* %307) #4, !dbg !44
  %308 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !44, !tbaa !12
  %309 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %308, i64 0, i32 5, !dbg !44
  %310 = load i32, i32* %309, align 8, !dbg !44, !tbaa !123
  %311 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %308, i64 0, i32 6, !dbg !44
  %312 = load i32, i32* %311, align 4, !dbg !44, !tbaa !124
  %313 = xor i32 %312, -1, !dbg !44
  %314 = and i32 %313, %310, !dbg !44
  %315 = icmp eq i32 %314, 0, !dbg !44
  br i1 %315, label %afterSend, label %316, !dbg !44, !prof !125

316:                                              ; preds = %sorbet_setupParamKeywords.exit
  %317 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %308, i64 0, i32 8, !dbg !44
  %318 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %317, align 8, !dbg !44, !tbaa !126
  %319 = call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* %318, i32 noundef 0) #4, !dbg !44
  br label %afterSend, !dbg !44
}

; Function Attrs: ssp
define void @Init_all_arguments() local_unnamed_addr #11 {
entry:
  %locals.i165.i = alloca i64, i32 0, align 8
  %locals.i.i = alloca i64, i32 0, align 8
  %keywords.i = alloca i64, align 8, !dbg !46
  %keywords5.i = alloca i64, align 8, !dbg !48
  %keywords11.i = alloca i64, align 8, !dbg !50
  %keywords17.i = alloca i64, align 8, !dbg !52
  %keywords23.i = alloca i64, align 8, !dbg !54
  %keywords29.i = alloca i64, align 8, !dbg !56
  %keywords35.i = alloca i64, align 8, !dbg !58
  %keywords41.i = alloca i64, i32 2, align 8, !dbg !61
  %keywords48.i = alloca i64, i32 2, align 8, !dbg !64
  %keywords56.i = alloca i64, i32 2, align 8, !dbg !67
  %keywords64.i = alloca i64, i32 2, align 8, !dbg !70
  %keywords72.i = alloca i64, i32 2, align 8, !dbg !73
  %keywords80.i = alloca i64, i32 2, align 8, !dbg !76
  %keywords88.i = alloca i64, i32 2, align 8, !dbg !79
  %keywords96.i = alloca i64, i32 3, align 8, !dbg !83
  %keywords105.i = alloca i64, i32 3, align 8, !dbg !87
  %keywords115.i = alloca i64, i32 3, align 8, !dbg !91
  %keywords125.i = alloca i64, i32 3, align 8, !dbg !95
  %keywords135.i = alloca i64, i32 3, align 8, !dbg !99
  %keywords145.i = alloca i64, i32 3, align 8, !dbg !103
  %keywords155.i = alloca i64, i32 3, align 8, !dbg !107
  %realpath = tail call i64 @sorbet_readRealpath()
  %0 = bitcast i64* %keywords.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %0)
  %1 = bitcast i64* %keywords5.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %1)
  %2 = bitcast i64* %keywords11.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %2)
  %3 = bitcast i64* %keywords17.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %3)
  %4 = bitcast i64* %keywords23.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %4)
  %5 = bitcast i64* %keywords29.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %5)
  %6 = bitcast i64* %keywords35.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %6)
  %7 = bitcast i64* %keywords41.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 16, i8* nonnull %7)
  %8 = bitcast i64* %keywords48.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 16, i8* nonnull %8)
  %9 = bitcast i64* %keywords56.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 16, i8* nonnull %9)
  %10 = bitcast i64* %keywords64.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 16, i8* nonnull %10)
  %11 = bitcast i64* %keywords72.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 16, i8* nonnull %11)
  %12 = bitcast i64* %keywords80.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 16, i8* nonnull %12)
  %13 = bitcast i64* %keywords88.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 16, i8* nonnull %13)
  %14 = bitcast i64* %keywords96.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 24, i8* nonnull %14)
  %15 = bitcast i64* %keywords105.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 24, i8* nonnull %15)
  %16 = bitcast i64* %keywords115.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 24, i8* nonnull %16)
  %17 = bitcast i64* %keywords125.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 24, i8* nonnull %17)
  %18 = bitcast i64* %keywords135.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 24, i8* nonnull %18)
  %19 = bitcast i64* %keywords145.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 24, i8* nonnull %19)
  %20 = bitcast i64* %keywords155.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 24, i8* nonnull %20)
  %21 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([15 x i8], [15 x i8]* @str_take_arguments, i64 0, i64 0), i64 noundef 14) #4
  store i64 %21, i64* @rubyIdPrecomputed_take_arguments, align 8
  %22 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([2 x i8], [2 x i8]* @str_d, i64 0, i64 0), i64 noundef 1) #4
  store i64 %22, i64* @rubyIdPrecomputed_d, align 8
  %23 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([2 x i8], [2 x i8]* @str_e, i64 0, i64 0), i64 noundef 1) #4
  store i64 %23, i64* @rubyIdPrecomputed_e, align 8
  %24 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([14 x i8], [14 x i8]* @"str_<build-array>", i64 0, i64 0), i64 noundef 13) #4
  %25 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([8 x i8], [8 x i8]* @str_inspect, i64 0, i64 0), i64 noundef 7) #4
  store i64 %25, i64* @rubyIdPrecomputed_inspect, align 8
  %26 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([5 x i8], [5 x i8]* @str_puts, i64 0, i64 0), i64 noundef 4) #4
  store i64 %26, i64* @rubyIdPrecomputed_puts, align 8
  %27 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 noundef 16) #4
  store i64 %27, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %28 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([7 x i8], [7 x i8]* @str_normal, i64 0, i64 0), i64 noundef 6) #4
  store i64 %28, i64* @rubyIdPrecomputed_normal, align 8
  %29 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([2 x i8], [2 x i8]* @str_a, i64 0, i64 0), i64 noundef 1) #4
  store i64 %29, i64* @rubyIdPrecomputed_a, align 8
  %30 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([2 x i8], [2 x i8]* @str_b, i64 0, i64 0), i64 noundef 1) #4
  store i64 %30, i64* @rubyIdPrecomputed_b, align 8
  %31 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([2 x i8], [2 x i8]* @str_c, i64 0, i64 0), i64 noundef 1) #4
  store i64 %31, i64* @rubyIdPrecomputed_c, align 8
  %32 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([2 x i8], [2 x i8]* @str_g, i64 0, i64 0), i64 noundef 1) #4
  store i64 %32, i64* @rubyIdPrecomputed_g, align 8
  %33 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([2 x i8], [2 x i8]* @str_f, i64 0, i64 0), i64 noundef 1) #4
  store i64 %33, i64* @rubyIdPrecomputed_f, align 8
  %34 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([9 x i8], [9 x i8]* @str_keep_def, i64 0, i64 0), i64 noundef 8) #4
  store i64 %34, i64* @rubyIdPrecomputed_keep_def, align 8
  %35 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @str_baz, i64 0, i64 0), i64 noundef 3) #4
  store i64 %35, i64* @rubyIdPrecomputed_baz, align 8
  %36 = tail call i64 @rb_fstring_new(i8* noundef getelementptr inbounds ([15 x i8], [15 x i8]* @str_take_arguments, i64 0, i64 0), i64 noundef 14) #4
  tail call void @rb_gc_register_mark_object(i64 %36) #4
  store i64 %36, i64* @rubyStrFrozen_take_arguments, align 8
  %37 = tail call i64 @rb_fstring_new(i8* noundef getelementptr inbounds ([40 x i8], [40 x i8]* @"str_test/testdata/compiler/all_arguments.rb", i64 0, i64 0), i64 noundef 39) #4
  tail call void @rb_gc_register_mark_object(i64 %37) #4
  store i64 %37, i64* @"rubyStrFrozen_test/testdata/compiler/all_arguments.rb", align 8
  tail call void @sorbet_initLineNumberInfo(%struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef getelementptr inbounds ([32 x i64], [32 x i64]* @iseqEncodedArray, i32 0, i32 0), i32 noundef 32)
  %rubyId_take_arguments.i.i = load i64, i64* @rubyIdPrecomputed_take_arguments, align 8
  %rubyStr_take_arguments.i.i = load i64, i64* @rubyStrFrozen_take_arguments, align 8
  %"rubyStr_test/testdata/compiler/all_arguments.rb.i.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/all_arguments.rb", align 8
  %38 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 %rubyStr_take_arguments.i.i, i64 %rubyId_take_arguments.i.i, i64 %"rubyStr_test/testdata/compiler/all_arguments.rb.i.i", i64 %realpath, %struct.rb_iseq_struct* noundef null, i32 noundef 1, i32 noundef 4, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef nonnull %locals.i.i, i32 noundef 0, i32 noundef 8)
  store %struct.rb_iseq_struct* %38, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Object#take_arguments", align 8
  %rubyId_inspect.i = load i64, i64* @rubyIdPrecomputed_inspect, align 8, !dbg !33
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_inspect, i64 %rubyId_inspect.i, i32 noundef 16, i32 noundef 0, i32 noundef 0, i64* noundef null), !dbg !33
  %rubyId_puts.i = load i64, i64* @rubyIdPrecomputed_puts, align 8, !dbg !39
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_puts, i64 %rubyId_puts.i, i32 noundef 20, i32 noundef 1, i32 noundef 0, i64* noundef null), !dbg !39
  %39 = call i64 @rb_fstring_new(i8* noundef getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 noundef 16) #4
  call void @rb_gc_register_mark_object(i64 %39) #4
  %"rubyId_<top (required)>.i.i" = load i64, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %"rubyStr_test/testdata/compiler/all_arguments.rb.i164.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/all_arguments.rb", align 8
  %40 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 %39, i64 %"rubyId_<top (required)>.i.i", i64 %"rubyStr_test/testdata/compiler/all_arguments.rb.i164.i", i64 %realpath, %struct.rb_iseq_struct* noundef null, i32 noundef 0, i32 noundef 4, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef nonnull %locals.i165.i, i32 noundef 0, i32 noundef 11)
  store %struct.rb_iseq_struct* %40, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_<root>.<static-init>$152", align 8
  %rubyId_keep_def.i = load i64, i64* @rubyIdPrecomputed_keep_def, align 8, !dbg !44
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_keep_def, i64 %rubyId_keep_def.i, i32 noundef 16, i32 noundef 3, i32 noundef 0, i64* noundef null), !dbg !44
  %rubyId_take_arguments.i = load i64, i64* @rubyIdPrecomputed_take_arguments, align 8, !dbg !46
  %rubyId_d.i = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !46
  %41 = call i64 @rb_id2sym(i64 %rubyId_d.i) #4, !dbg !46
  store i64 %41, i64* %keywords.i, align 8, !dbg !46
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_take_arguments, i64 %rubyId_take_arguments.i, i32 noundef 68, i32 noundef 8, i32 noundef 1, i64* noundef nonnull %keywords.i), !dbg !46
  %rubyId_take_arguments4.i = load i64, i64* @rubyIdPrecomputed_take_arguments, align 8, !dbg !48
  %rubyId_d6.i = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !48
  %42 = call i64 @rb_id2sym(i64 %rubyId_d6.i) #4, !dbg !48
  store i64 %42, i64* %keywords5.i, align 8, !dbg !48
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.1, i64 %rubyId_take_arguments4.i, i32 noundef 68, i32 noundef 7, i32 noundef 1, i64* noundef nonnull %keywords5.i), !dbg !48
  %rubyId_take_arguments10.i = load i64, i64* @rubyIdPrecomputed_take_arguments, align 8, !dbg !50
  %rubyId_d12.i = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !50
  %43 = call i64 @rb_id2sym(i64 %rubyId_d12.i) #4, !dbg !50
  store i64 %43, i64* %keywords11.i, align 8, !dbg !50
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.2, i64 %rubyId_take_arguments10.i, i32 noundef 68, i32 noundef 6, i32 noundef 1, i64* noundef nonnull %keywords11.i), !dbg !50
  %rubyId_take_arguments16.i = load i64, i64* @rubyIdPrecomputed_take_arguments, align 8, !dbg !52
  %rubyId_d18.i = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !52
  %44 = call i64 @rb_id2sym(i64 %rubyId_d18.i) #4, !dbg !52
  store i64 %44, i64* %keywords17.i, align 8, !dbg !52
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.3, i64 %rubyId_take_arguments16.i, i32 noundef 68, i32 noundef 5, i32 noundef 1, i64* noundef nonnull %keywords17.i), !dbg !52
  %rubyId_take_arguments22.i = load i64, i64* @rubyIdPrecomputed_take_arguments, align 8, !dbg !54
  %rubyId_d24.i = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !54
  %45 = call i64 @rb_id2sym(i64 %rubyId_d24.i) #4, !dbg !54
  store i64 %45, i64* %keywords23.i, align 8, !dbg !54
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.4, i64 %rubyId_take_arguments22.i, i32 noundef 68, i32 noundef 4, i32 noundef 1, i64* noundef nonnull %keywords23.i), !dbg !54
  %rubyId_take_arguments28.i = load i64, i64* @rubyIdPrecomputed_take_arguments, align 8, !dbg !56
  %rubyId_d30.i = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !56
  %46 = call i64 @rb_id2sym(i64 %rubyId_d30.i) #4, !dbg !56
  store i64 %46, i64* %keywords29.i, align 8, !dbg !56
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.5, i64 %rubyId_take_arguments28.i, i32 noundef 68, i32 noundef 3, i32 noundef 1, i64* noundef nonnull %keywords29.i), !dbg !56
  %rubyId_take_arguments34.i = load i64, i64* @rubyIdPrecomputed_take_arguments, align 8, !dbg !58
  %rubyId_d36.i = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !58
  %47 = call i64 @rb_id2sym(i64 %rubyId_d36.i) #4, !dbg !58
  store i64 %47, i64* %keywords35.i, align 8, !dbg !58
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.6, i64 %rubyId_take_arguments34.i, i32 noundef 68, i32 noundef 2, i32 noundef 1, i64* noundef nonnull %keywords35.i), !dbg !58
  %rubyId_take_arguments40.i = load i64, i64* @rubyIdPrecomputed_take_arguments, align 8, !dbg !61
  %rubyId_d42.i = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !61
  %48 = call i64 @rb_id2sym(i64 %rubyId_d42.i) #4, !dbg !61
  store i64 %48, i64* %keywords41.i, align 8, !dbg !61
  %rubyId_e.i = load i64, i64* @rubyIdPrecomputed_e, align 8, !dbg !61
  %49 = call i64 @rb_id2sym(i64 %rubyId_e.i) #4, !dbg !61
  %50 = getelementptr i64, i64* %keywords41.i, i32 1, !dbg !61
  store i64 %49, i64* %50, align 8, !dbg !61
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.7, i64 %rubyId_take_arguments40.i, i32 noundef 68, i32 noundef 9, i32 noundef 2, i64* noundef nonnull %keywords41.i), !dbg !61
  %rubyId_take_arguments47.i = load i64, i64* @rubyIdPrecomputed_take_arguments, align 8, !dbg !64
  %rubyId_d49.i = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !64
  %51 = call i64 @rb_id2sym(i64 %rubyId_d49.i) #4, !dbg !64
  store i64 %51, i64* %keywords48.i, align 8, !dbg !64
  %rubyId_e51.i = load i64, i64* @rubyIdPrecomputed_e, align 8, !dbg !64
  %52 = call i64 @rb_id2sym(i64 %rubyId_e51.i) #4, !dbg !64
  %53 = getelementptr i64, i64* %keywords48.i, i32 1, !dbg !64
  store i64 %52, i64* %53, align 8, !dbg !64
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.8, i64 %rubyId_take_arguments47.i, i32 noundef 68, i32 noundef 8, i32 noundef 2, i64* noundef nonnull %keywords48.i), !dbg !64
  %rubyId_take_arguments55.i = load i64, i64* @rubyIdPrecomputed_take_arguments, align 8, !dbg !67
  %rubyId_d57.i = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !67
  %54 = call i64 @rb_id2sym(i64 %rubyId_d57.i) #4, !dbg !67
  store i64 %54, i64* %keywords56.i, align 8, !dbg !67
  %rubyId_e59.i = load i64, i64* @rubyIdPrecomputed_e, align 8, !dbg !67
  %55 = call i64 @rb_id2sym(i64 %rubyId_e59.i) #4, !dbg !67
  %56 = getelementptr i64, i64* %keywords56.i, i32 1, !dbg !67
  store i64 %55, i64* %56, align 8, !dbg !67
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.9, i64 %rubyId_take_arguments55.i, i32 noundef 68, i32 noundef 7, i32 noundef 2, i64* noundef nonnull %keywords56.i), !dbg !67
  %rubyId_take_arguments63.i = load i64, i64* @rubyIdPrecomputed_take_arguments, align 8, !dbg !70
  %rubyId_d65.i = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !70
  %57 = call i64 @rb_id2sym(i64 %rubyId_d65.i) #4, !dbg !70
  store i64 %57, i64* %keywords64.i, align 8, !dbg !70
  %rubyId_e67.i = load i64, i64* @rubyIdPrecomputed_e, align 8, !dbg !70
  %58 = call i64 @rb_id2sym(i64 %rubyId_e67.i) #4, !dbg !70
  %59 = getelementptr i64, i64* %keywords64.i, i32 1, !dbg !70
  store i64 %58, i64* %59, align 8, !dbg !70
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.10, i64 %rubyId_take_arguments63.i, i32 noundef 68, i32 noundef 6, i32 noundef 2, i64* noundef nonnull %keywords64.i), !dbg !70
  %rubyId_take_arguments71.i = load i64, i64* @rubyIdPrecomputed_take_arguments, align 8, !dbg !73
  %rubyId_d73.i = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !73
  %60 = call i64 @rb_id2sym(i64 %rubyId_d73.i) #4, !dbg !73
  store i64 %60, i64* %keywords72.i, align 8, !dbg !73
  %rubyId_e75.i = load i64, i64* @rubyIdPrecomputed_e, align 8, !dbg !73
  %61 = call i64 @rb_id2sym(i64 %rubyId_e75.i) #4, !dbg !73
  %62 = getelementptr i64, i64* %keywords72.i, i32 1, !dbg !73
  store i64 %61, i64* %62, align 8, !dbg !73
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.11, i64 %rubyId_take_arguments71.i, i32 noundef 68, i32 noundef 5, i32 noundef 2, i64* noundef nonnull %keywords72.i), !dbg !73
  %rubyId_take_arguments79.i = load i64, i64* @rubyIdPrecomputed_take_arguments, align 8, !dbg !76
  %rubyId_d81.i = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !76
  %63 = call i64 @rb_id2sym(i64 %rubyId_d81.i) #4, !dbg !76
  store i64 %63, i64* %keywords80.i, align 8, !dbg !76
  %rubyId_e83.i = load i64, i64* @rubyIdPrecomputed_e, align 8, !dbg !76
  %64 = call i64 @rb_id2sym(i64 %rubyId_e83.i) #4, !dbg !76
  %65 = getelementptr i64, i64* %keywords80.i, i32 1, !dbg !76
  store i64 %64, i64* %65, align 8, !dbg !76
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.12, i64 %rubyId_take_arguments79.i, i32 noundef 68, i32 noundef 4, i32 noundef 2, i64* noundef nonnull %keywords80.i), !dbg !76
  %rubyId_take_arguments87.i = load i64, i64* @rubyIdPrecomputed_take_arguments, align 8, !dbg !79
  %rubyId_d89.i = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !79
  %66 = call i64 @rb_id2sym(i64 %rubyId_d89.i) #4, !dbg !79
  store i64 %66, i64* %keywords88.i, align 8, !dbg !79
  %rubyId_e91.i = load i64, i64* @rubyIdPrecomputed_e, align 8, !dbg !79
  %67 = call i64 @rb_id2sym(i64 %rubyId_e91.i) #4, !dbg !79
  %68 = getelementptr i64, i64* %keywords88.i, i32 1, !dbg !79
  store i64 %67, i64* %68, align 8, !dbg !79
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.13, i64 %rubyId_take_arguments87.i, i32 noundef 68, i32 noundef 3, i32 noundef 2, i64* noundef nonnull %keywords88.i), !dbg !79
  %rubyId_take_arguments95.i = load i64, i64* @rubyIdPrecomputed_take_arguments, align 8, !dbg !83
  %rubyId_d97.i = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !83
  %69 = call i64 @rb_id2sym(i64 %rubyId_d97.i) #4, !dbg !83
  store i64 %69, i64* %keywords96.i, align 8, !dbg !83
  %rubyId_e99.i = load i64, i64* @rubyIdPrecomputed_e, align 8, !dbg !83
  %70 = call i64 @rb_id2sym(i64 %rubyId_e99.i) #4, !dbg !83
  %71 = getelementptr i64, i64* %keywords96.i, i32 1, !dbg !83
  store i64 %70, i64* %71, align 8, !dbg !83
  %rubyId_baz.i = load i64, i64* @rubyIdPrecomputed_baz, align 8, !dbg !83
  %72 = call i64 @rb_id2sym(i64 %rubyId_baz.i) #4, !dbg !83
  %73 = getelementptr i64, i64* %keywords96.i, i32 2, !dbg !83
  store i64 %72, i64* %73, align 8, !dbg !83
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.14, i64 %rubyId_take_arguments95.i, i32 noundef 68, i32 noundef 10, i32 noundef 3, i64* noundef nonnull %keywords96.i), !dbg !83
  %rubyId_take_arguments104.i = load i64, i64* @rubyIdPrecomputed_take_arguments, align 8, !dbg !87
  %rubyId_d106.i = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !87
  %74 = call i64 @rb_id2sym(i64 %rubyId_d106.i) #4, !dbg !87
  store i64 %74, i64* %keywords105.i, align 8, !dbg !87
  %rubyId_e108.i = load i64, i64* @rubyIdPrecomputed_e, align 8, !dbg !87
  %75 = call i64 @rb_id2sym(i64 %rubyId_e108.i) #4, !dbg !87
  %76 = getelementptr i64, i64* %keywords105.i, i32 1, !dbg !87
  store i64 %75, i64* %76, align 8, !dbg !87
  %rubyId_baz110.i = load i64, i64* @rubyIdPrecomputed_baz, align 8, !dbg !87
  %77 = call i64 @rb_id2sym(i64 %rubyId_baz110.i) #4, !dbg !87
  %78 = getelementptr i64, i64* %keywords105.i, i32 2, !dbg !87
  store i64 %77, i64* %78, align 8, !dbg !87
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.15, i64 %rubyId_take_arguments104.i, i32 noundef 68, i32 noundef 9, i32 noundef 3, i64* noundef nonnull %keywords105.i), !dbg !87
  %rubyId_take_arguments114.i = load i64, i64* @rubyIdPrecomputed_take_arguments, align 8, !dbg !91
  %rubyId_d116.i = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !91
  %79 = call i64 @rb_id2sym(i64 %rubyId_d116.i) #4, !dbg !91
  store i64 %79, i64* %keywords115.i, align 8, !dbg !91
  %rubyId_e118.i = load i64, i64* @rubyIdPrecomputed_e, align 8, !dbg !91
  %80 = call i64 @rb_id2sym(i64 %rubyId_e118.i) #4, !dbg !91
  %81 = getelementptr i64, i64* %keywords115.i, i32 1, !dbg !91
  store i64 %80, i64* %81, align 8, !dbg !91
  %rubyId_baz120.i = load i64, i64* @rubyIdPrecomputed_baz, align 8, !dbg !91
  %82 = call i64 @rb_id2sym(i64 %rubyId_baz120.i) #4, !dbg !91
  %83 = getelementptr i64, i64* %keywords115.i, i32 2, !dbg !91
  store i64 %82, i64* %83, align 8, !dbg !91
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.16, i64 %rubyId_take_arguments114.i, i32 noundef 68, i32 noundef 8, i32 noundef 3, i64* noundef nonnull %keywords115.i), !dbg !91
  %rubyId_take_arguments124.i = load i64, i64* @rubyIdPrecomputed_take_arguments, align 8, !dbg !95
  %rubyId_d126.i = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !95
  %84 = call i64 @rb_id2sym(i64 %rubyId_d126.i) #4, !dbg !95
  store i64 %84, i64* %keywords125.i, align 8, !dbg !95
  %rubyId_e128.i = load i64, i64* @rubyIdPrecomputed_e, align 8, !dbg !95
  %85 = call i64 @rb_id2sym(i64 %rubyId_e128.i) #4, !dbg !95
  %86 = getelementptr i64, i64* %keywords125.i, i32 1, !dbg !95
  store i64 %85, i64* %86, align 8, !dbg !95
  %rubyId_baz130.i = load i64, i64* @rubyIdPrecomputed_baz, align 8, !dbg !95
  %87 = call i64 @rb_id2sym(i64 %rubyId_baz130.i) #4, !dbg !95
  %88 = getelementptr i64, i64* %keywords125.i, i32 2, !dbg !95
  store i64 %87, i64* %88, align 8, !dbg !95
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.17, i64 %rubyId_take_arguments124.i, i32 noundef 68, i32 noundef 7, i32 noundef 3, i64* noundef nonnull %keywords125.i), !dbg !95
  %rubyId_take_arguments134.i = load i64, i64* @rubyIdPrecomputed_take_arguments, align 8, !dbg !99
  %rubyId_d136.i = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !99
  %89 = call i64 @rb_id2sym(i64 %rubyId_d136.i) #4, !dbg !99
  store i64 %89, i64* %keywords135.i, align 8, !dbg !99
  %rubyId_e138.i = load i64, i64* @rubyIdPrecomputed_e, align 8, !dbg !99
  %90 = call i64 @rb_id2sym(i64 %rubyId_e138.i) #4, !dbg !99
  %91 = getelementptr i64, i64* %keywords135.i, i32 1, !dbg !99
  store i64 %90, i64* %91, align 8, !dbg !99
  %rubyId_baz140.i = load i64, i64* @rubyIdPrecomputed_baz, align 8, !dbg !99
  %92 = call i64 @rb_id2sym(i64 %rubyId_baz140.i) #4, !dbg !99
  %93 = getelementptr i64, i64* %keywords135.i, i32 2, !dbg !99
  store i64 %92, i64* %93, align 8, !dbg !99
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.18, i64 %rubyId_take_arguments134.i, i32 noundef 68, i32 noundef 6, i32 noundef 3, i64* noundef nonnull %keywords135.i), !dbg !99
  %rubyId_take_arguments144.i = load i64, i64* @rubyIdPrecomputed_take_arguments, align 8, !dbg !103
  %rubyId_d146.i = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !103
  %94 = call i64 @rb_id2sym(i64 %rubyId_d146.i) #4, !dbg !103
  store i64 %94, i64* %keywords145.i, align 8, !dbg !103
  %rubyId_e148.i = load i64, i64* @rubyIdPrecomputed_e, align 8, !dbg !103
  %95 = call i64 @rb_id2sym(i64 %rubyId_e148.i) #4, !dbg !103
  %96 = getelementptr i64, i64* %keywords145.i, i32 1, !dbg !103
  store i64 %95, i64* %96, align 8, !dbg !103
  %rubyId_baz150.i = load i64, i64* @rubyIdPrecomputed_baz, align 8, !dbg !103
  %97 = call i64 @rb_id2sym(i64 %rubyId_baz150.i) #4, !dbg !103
  %98 = getelementptr i64, i64* %keywords145.i, i32 2, !dbg !103
  store i64 %97, i64* %98, align 8, !dbg !103
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.19, i64 %rubyId_take_arguments144.i, i32 noundef 68, i32 noundef 5, i32 noundef 3, i64* noundef nonnull %keywords145.i), !dbg !103
  %rubyId_take_arguments154.i = load i64, i64* @rubyIdPrecomputed_take_arguments, align 8, !dbg !107
  %rubyId_d156.i = load i64, i64* @rubyIdPrecomputed_d, align 8, !dbg !107
  %99 = call i64 @rb_id2sym(i64 %rubyId_d156.i) #4, !dbg !107
  store i64 %99, i64* %keywords155.i, align 8, !dbg !107
  %rubyId_e158.i = load i64, i64* @rubyIdPrecomputed_e, align 8, !dbg !107
  %100 = call i64 @rb_id2sym(i64 %rubyId_e158.i) #4, !dbg !107
  %101 = getelementptr i64, i64* %keywords155.i, i32 1, !dbg !107
  store i64 %100, i64* %101, align 8, !dbg !107
  %rubyId_baz160.i = load i64, i64* @rubyIdPrecomputed_baz, align 8, !dbg !107
  %102 = call i64 @rb_id2sym(i64 %rubyId_baz160.i) #4, !dbg !107
  %103 = getelementptr i64, i64* %keywords155.i, i32 2, !dbg !107
  store i64 %102, i64* %103, align 8, !dbg !107
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_take_arguments.20, i64 %rubyId_take_arguments154.i, i32 noundef 68, i32 noundef 4, i32 noundef 3, i64* noundef nonnull %keywords155.i), !dbg !107
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %0)
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %1)
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %2)
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %3)
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %4)
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %5)
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %6)
  call void @llvm.lifetime.end.p0i8(i64 16, i8* nonnull %7)
  call void @llvm.lifetime.end.p0i8(i64 16, i8* nonnull %8)
  call void @llvm.lifetime.end.p0i8(i64 16, i8* nonnull %9)
  call void @llvm.lifetime.end.p0i8(i64 16, i8* nonnull %10)
  call void @llvm.lifetime.end.p0i8(i64 16, i8* nonnull %11)
  call void @llvm.lifetime.end.p0i8(i64 16, i8* nonnull %12)
  call void @llvm.lifetime.end.p0i8(i64 16, i8* nonnull %13)
  call void @llvm.lifetime.end.p0i8(i64 24, i8* nonnull %14)
  call void @llvm.lifetime.end.p0i8(i64 24, i8* nonnull %15)
  call void @llvm.lifetime.end.p0i8(i64 24, i8* nonnull %16)
  call void @llvm.lifetime.end.p0i8(i64 24, i8* nonnull %17)
  call void @llvm.lifetime.end.p0i8(i64 24, i8* nonnull %18)
  call void @llvm.lifetime.end.p0i8(i64 24, i8* nonnull %19)
  call void @llvm.lifetime.end.p0i8(i64 24, i8* nonnull %20)
  %104 = load %struct.rb_vm_struct*, %struct.rb_vm_struct** @ruby_current_vm_ptr, align 8, !tbaa !12
  %105 = getelementptr inbounds %struct.rb_vm_struct, %struct.rb_vm_struct* %104, i64 0, i32 18
  %106 = load i64, i64* %105, align 8, !tbaa !127
  %107 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !12
  %108 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %107, i64 0, i32 2
  %109 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %108, align 8, !tbaa !41
  call fastcc void @"func_<root>.<static-init>$152"(i64 %106, %struct.rb_control_frame_struct* %109) #4
  ret void
}

; Function Attrs: inaccessiblememonly nofree nosync nounwind willreturn
declare void @llvm.experimental.noalias.scope.decl(metadata) #12

; Function Attrs: argmemonly nofree nosync nounwind willreturn
declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #8

; Function Attrs: argmemonly nofree nosync nounwind willreturn
declare void @llvm.lifetime.end.p0i8(i64 immarg, i8* nocapture) #8

attributes #0 = { noreturn }
attributes #1 = { "addedToSilenceEmptyAttrsError" }
attributes #2 = { nofree nosync nounwind readnone willreturn }
attributes #3 = { nofree nosync nounwind willreturn }
attributes #4 = { nounwind }
attributes #5 = { noreturn nounwind }
attributes #6 = { alwaysinline nounwind ssp uwtable }
attributes #7 = { allocsize(0,1) }
attributes #8 = { argmemonly nofree nosync nounwind willreturn }
attributes #9 = { nounwind ssp uwtable }
attributes #10 = { nounwind sspreq uwtable }
attributes #11 = { ssp }
attributes #12 = { inaccessiblememonly nofree nosync nounwind willreturn }
attributes #13 = { nounwind allocsize(0,1) }
attributes #14 = { nounwind willreturn }

!llvm.module.flags = !{!0}
!llvm.dbg.cu = !{!1}

!0 = !{i32 2, !"Debug Info Version", i32 3}
!1 = distinct !DICompileUnit(language: DW_LANG_C, file: !2, producer: "Sorbet LLVM", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, enums: !3)
!2 = !DIFile(filename: "test/testdata/compiler/all_arguments.rb", directory: ".")
!3 = !{}
!4 = !{!5, !5, i64 0}
!5 = !{!"long", !6, i64 0}
!6 = !{!"omnipotent char", !7, i64 0}
!7 = !{!"Simple C/C++ TBAA"}
!8 = distinct !DISubprogram(name: "Object#take_arguments", linkageName: "func_Object#take_arguments", scope: null, file: !2, line: 4, type: !9, scopeLine: 4, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!9 = !DISubroutineType(types: !10)
!10 = !{!11}
!11 = !DIBasicType(name: "VALUE", size: 64, encoding: DW_ATE_signed)
!12 = !{!13, !13, i64 0}
!13 = !{!"any pointer", !6, i64 0}
!14 = !{!15, !6, i64 64}
!15 = !{!"rb_vm_tag", !5, i64 0, !5, i64 8, !6, i64 16, !13, i64 56, !6, i64 64}
!16 = !{!15, !5, i64 0}
!17 = !{!18, !13, i64 24}
!18 = !{!"rb_execution_context_struct", !13, i64 0, !5, i64 8, !13, i64 16, !13, i64 24, !13, i64 32, !19, i64 40, !19, i64 44, !13, i64 48, !13, i64 56, !13, i64 64, !5, i64 72, !5, i64 80, !13, i64 88, !5, i64 96, !13, i64 104, !13, i64 112, !5, i64 120, !5, i64 128, !6, i64 136, !6, i64 137, !5, i64 144, !20, i64 152}
!19 = !{!"int", !6, i64 0}
!20 = !{!"", !13, i64 0, !13, i64 8, !5, i64 16, !6, i64 24}
!21 = !{!15, !13, i64 56}
!22 = !{!18, !5, i64 120}
!23 = !{!24, !13, i64 24}
!24 = !{!"vm_throw_data", !5, i64 0, !5, i64 8, !5, i64 16, !13, i64 24, !19, i64 32}
!25 = !{!24, !5, i64 16}
!26 = !DILocation(line: 4, column: 1, scope: !8)
!27 = !{!28, !5, i64 0}
!28 = !{!"RBasic", !5, i64 0, !5, i64 8}
!29 = !{!"branch_weights", i32 1, i32 2000}
!30 = !DILocation(line: 4, column: 23, scope: !8)
!31 = !DILocation(line: 4, column: 36, scope: !8)
!32 = !DILocation(line: 0, scope: !8)
!33 = !DILocation(line: 5, column: 10, scope: !8)
!34 = !{!35}
!35 = distinct !{!35, !36, !"sorbet_buildArrayIntrinsic: argument 0"}
!36 = distinct !{!36, !"sorbet_buildArrayIntrinsic"}
!37 = !{!38, !13, i64 8}
!38 = !{!"rb_control_frame_struct", !13, i64 0, !13, i64 8, !13, i64 16, !5, i64 24, !13, i64 32, !13, i64 40, !13, i64 48}
!39 = !DILocation(line: 5, column: 5, scope: !8)
!40 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.<static-init>$152", scope: null, file: !2, line: 4, type: !9, scopeLine: 4, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!41 = !{!18, !13, i64 16}
!42 = !{!38, !13, i64 16}
!43 = !{!38, !13, i64 32}
!44 = !DILocation(line: 4, column: 1, scope: !40)
!45 = !DILocation(line: 8, column: 44, scope: !40)
!46 = !DILocation(line: 8, column: 1, scope: !40)
!47 = !DILocation(line: 9, column: 40, scope: !40)
!48 = !DILocation(line: 9, column: 1, scope: !40)
!49 = !DILocation(line: 10, column: 36, scope: !40)
!50 = !DILocation(line: 10, column: 1, scope: !40)
!51 = !DILocation(line: 11, column: 32, scope: !40)
!52 = !DILocation(line: 11, column: 1, scope: !40)
!53 = !DILocation(line: 12, column: 28, scope: !40)
!54 = !DILocation(line: 12, column: 1, scope: !40)
!55 = !DILocation(line: 13, column: 24, scope: !40)
!56 = !DILocation(line: 13, column: 1, scope: !40)
!57 = !DILocation(line: 14, column: 20, scope: !40)
!58 = !DILocation(line: 14, column: 1, scope: !40)
!59 = !DILocation(line: 16, column: 44, scope: !40)
!60 = !DILocation(line: 16, column: 51, scope: !40)
!61 = !DILocation(line: 16, column: 1, scope: !40)
!62 = !DILocation(line: 17, column: 40, scope: !40)
!63 = !DILocation(line: 17, column: 47, scope: !40)
!64 = !DILocation(line: 17, column: 1, scope: !40)
!65 = !DILocation(line: 18, column: 36, scope: !40)
!66 = !DILocation(line: 18, column: 43, scope: !40)
!67 = !DILocation(line: 18, column: 1, scope: !40)
!68 = !DILocation(line: 19, column: 32, scope: !40)
!69 = !DILocation(line: 19, column: 39, scope: !40)
!70 = !DILocation(line: 19, column: 1, scope: !40)
!71 = !DILocation(line: 20, column: 28, scope: !40)
!72 = !DILocation(line: 20, column: 35, scope: !40)
!73 = !DILocation(line: 20, column: 1, scope: !40)
!74 = !DILocation(line: 21, column: 24, scope: !40)
!75 = !DILocation(line: 21, column: 31, scope: !40)
!76 = !DILocation(line: 21, column: 1, scope: !40)
!77 = !DILocation(line: 22, column: 20, scope: !40)
!78 = !DILocation(line: 22, column: 27, scope: !40)
!79 = !DILocation(line: 22, column: 1, scope: !40)
!80 = !DILocation(line: 24, column: 44, scope: !40)
!81 = !DILocation(line: 24, column: 51, scope: !40)
!82 = !DILocation(line: 24, column: 58, scope: !40)
!83 = !DILocation(line: 24, column: 1, scope: !40)
!84 = !DILocation(line: 25, column: 40, scope: !40)
!85 = !DILocation(line: 25, column: 47, scope: !40)
!86 = !DILocation(line: 25, column: 54, scope: !40)
!87 = !DILocation(line: 25, column: 1, scope: !40)
!88 = !DILocation(line: 26, column: 36, scope: !40)
!89 = !DILocation(line: 26, column: 43, scope: !40)
!90 = !DILocation(line: 26, column: 50, scope: !40)
!91 = !DILocation(line: 26, column: 1, scope: !40)
!92 = !DILocation(line: 27, column: 32, scope: !40)
!93 = !DILocation(line: 27, column: 39, scope: !40)
!94 = !DILocation(line: 27, column: 46, scope: !40)
!95 = !DILocation(line: 27, column: 1, scope: !40)
!96 = !DILocation(line: 28, column: 28, scope: !40)
!97 = !DILocation(line: 28, column: 35, scope: !40)
!98 = !DILocation(line: 28, column: 42, scope: !40)
!99 = !DILocation(line: 28, column: 1, scope: !40)
!100 = !DILocation(line: 29, column: 24, scope: !40)
!101 = !DILocation(line: 29, column: 31, scope: !40)
!102 = !DILocation(line: 29, column: 38, scope: !40)
!103 = !DILocation(line: 29, column: 1, scope: !40)
!104 = !DILocation(line: 30, column: 20, scope: !40)
!105 = !DILocation(line: 30, column: 27, scope: !40)
!106 = !DILocation(line: 30, column: 34, scope: !40)
!107 = !DILocation(line: 30, column: 1, scope: !40)
!108 = !DILocation(line: 0, scope: !40)
!109 = !{!110, !19, i64 20}
!110 = !{!"rb_sorbet_param_struct", !111, i64 0, !19, i64 4, !19, i64 8, !19, i64 12, !19, i64 16, !19, i64 20, !19, i64 24, !19, i64 28, !13, i64 32, !19, i64 40, !19, i64 44, !19, i64 48, !19, i64 52, !13, i64 56}
!111 = !{!"", !19, i64 0, !19, i64 0, !19, i64 0, !19, i64 0, !19, i64 0, !19, i64 0, !19, i64 0, !19, i64 0, !19, i64 1, !19, i64 1}
!112 = !{!110, !19, i64 24}
!113 = !{!110, !19, i64 28}
!114 = !{!19, !19, i64 0}
!115 = !{!110, !13, i64 32}
!116 = !{!110, !19, i64 40}
!117 = !{!110, !19, i64 44}
!118 = !{!110, !19, i64 8}
!119 = !{!110, !19, i64 12}
!120 = !{!110, !19, i64 48}
!121 = !{!110, !19, i64 52}
!122 = !{!110, !13, i64 56}
!123 = !{!18, !19, i64 40}
!124 = !{!18, !19, i64 44}
!125 = !{!"branch_weights", i32 2000, i32 1}
!126 = !{!18, !13, i64 56}
!127 = !{!128, !5, i64 400}
!128 = !{!"rb_vm_struct", !5, i64 0, !129, i64 8, !13, i64 192, !13, i64 200, !13, i64 208, !132, i64 216, !6, i64 224, !130, i64 264, !130, i64 280, !130, i64 296, !130, i64 312, !5, i64 328, !19, i64 336, !19, i64 340, !19, i64 344, !19, i64 344, !19, i64 344, !19, i64 344, !19, i64 348, !5, i64 352, !6, i64 360, !5, i64 400, !5, i64 408, !5, i64 416, !5, i64 424, !5, i64 432, !5, i64 440, !5, i64 448, !13, i64 456, !13, i64 464, !133, i64 472, !134, i64 992, !13, i64 1016, !13, i64 1024, !19, i64 1032, !19, i64 1036, !130, i64 1040, !6, i64 1056, !5, i64 1096, !5, i64 1104, !5, i64 1112, !5, i64 1120, !5, i64 1128, !19, i64 1136, !13, i64 1144, !13, i64 1152, !13, i64 1160, !13, i64 1168, !13, i64 1176, !13, i64 1184, !19, i64 1192, !135, i64 1200, !6, i64 1232}
!129 = !{!"rb_global_vm_lock_struct", !13, i64 0, !6, i64 8, !130, i64 48, !13, i64 64, !19, i64 72, !6, i64 80, !6, i64 128, !19, i64 176, !19, i64 180}
!130 = !{!"list_head", !131, i64 0}
!131 = !{!"list_node", !13, i64 0, !13, i64 8}
!132 = !{!"long long", !6, i64 0}
!133 = !{!"", !6, i64 0}
!134 = !{!"rb_hook_list_struct", !13, i64 0, !19, i64 8, !19, i64 12, !19, i64 16}
!135 = !{!"", !5, i64 0, !5, i64 8, !5, i64 16, !5, i64 24}
