; ModuleID = 'payload'
source_filename = "llvm-link"
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"

%struct.rb_vm_struct = type { i64, %struct.rb_global_vm_lock_struct, %struct.rb_thread_struct*, %struct.rb_thread_struct*, i8*, i64, %union.pthread_mutex_t, %union.anon.12, %union.anon.12, %union.anon.12, %union.anon.12, i64, i32, i8, i32, i64, [5 x i64], i64, i64, i64, i64, i64, i64, i64, %struct.st_table*, %struct.st_table*, %struct.anon.18, %struct.rb_hook_list_struct, %struct.st_table*, %struct.rb_postponed_job_struct*, i32, i32, %union.anon.12, %union.pthread_mutex_t, i64, i64, i64, i64, i64, i32, i64, %struct.rb_objspace*, %struct.rb_at_exit_list*, i64*, %struct.st_table*, %struct.anon.19, [28 x i16] }
%struct.rb_global_vm_lock_struct = type { %struct.rb_thread_struct*, %union.pthread_mutex_t, %union.anon.12, %struct.rb_thread_struct*, i32, %union.pthread_cond_t, %union.pthread_cond_t, i32, i32 }
%union.pthread_cond_t = type { %struct.anon.14 }
%struct.anon.14 = type { i32, i32, i64, i64, i64, i8*, i32, i32 }
%struct.rb_thread_struct = type { %struct.list_node, i64, %struct.rb_vm_struct*, %struct.rb_execution_context_struct*, i64, %struct.rb_calling_info*, i64, i64, i64, i8, i8, i32, %struct.native_thread_data_struct, i8*, i64, i64, i64, i64, %union.pthread_mutex_t, %struct.rb_unblock_callback, i64, %struct.rb_mutex_struct*, %struct.rb_thread_list_struct*, %union.anon.15, i32, i64, %struct.rb_fiber_struct*, [1 x %struct.__jmp_buf_tag], i64 }
%struct.list_node = type { %struct.list_node*, %struct.list_node* }
%struct.rb_execution_context_struct = type { i64*, i64, %struct.rb_control_frame_struct*, %struct.rb_vm_tag*, %struct.rb_vm_protect_tag*, i32, i32, %struct.rb_fiber_struct*, %struct.rb_thread_struct*, %struct.st_table*, i64, i64, i64*, i64, %struct.rb_ensure_list*, %struct.rb_trace_arg_struct*, i64, i64, i8, i8, i64, %struct.anon.11 }
%struct.rb_control_frame_struct = type { i64*, i64*, %struct.rb_iseq_struct*, i64, i64*, i8*, i64* }
%struct.rb_iseq_struct = type { i64, i64, %struct.rb_iseq_constant_body*, %union.anon.8 }
%struct.rb_iseq_constant_body = type { i32, i32, i64*, %struct.anon.1, %struct.rb_iseq_location_struct, %struct.iseq_insn_info, i64*, %struct.iseq_catch_table*, %struct.rb_iseq_struct*, %struct.rb_iseq_struct*, %union.iseq_inline_storage_entry*, %struct.rb_call_info*, %struct.rb_call_cache*, %struct.anon.7, i32, i32, i32, i32, i32, i64 (%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*)*, i64, %struct.rb_mjit_unit*, i8 }
%struct.anon.1 = type { %struct.anon.2, i32, i32, i32, i32, i32, i32, i32, i64*, %struct.rb_iseq_param_keyword* }
%struct.anon.2 = type { i8, [3 x i8] }
%struct.rb_iseq_param_keyword = type { i32, i32, i32, i32, i64*, i64* }
%struct.rb_iseq_location_struct = type { i64, i64, i64, i64, i32, %struct.rb_code_location_struct }
%struct.rb_code_location_struct = type { %struct.rb_code_position_struct, %struct.rb_code_position_struct }
%struct.rb_code_position_struct = type { i32, i32 }
%struct.iseq_insn_info = type { %struct.rb_code_position_struct*, i32*, i32, %struct.succ_index_table* }
%struct.succ_index_table = type opaque
%struct.iseq_catch_table = type opaque
%union.iseq_inline_storage_entry = type { %struct.iseq_inline_cache_entry }
%struct.iseq_inline_cache_entry = type { i64, %struct.rb_cref_struct*, %union.anon.0 }
%struct.rb_cref_struct = type { i64, i64, i64, %struct.rb_cref_struct*, %struct.anon.2 }
%union.anon.0 = type { i64 }
%struct.rb_call_info = type { i64, i32, i32 }
%struct.rb_call_cache = type { i64, i64, %struct.rb_callable_method_entry_struct*, i64 (%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_calling_info*, %struct.rb_call_info*, %struct.rb_call_cache*)*, %union.anon.6 }
%struct.rb_callable_method_entry_struct = type { i64, i64, %struct.rb_method_definition_struct*, i64, i64 }
%struct.rb_method_definition_struct = type { i64, %union.anon.5, i64 }
%union.anon.5 = type { %struct.rb_method_cfunc_struct }
%struct.rb_method_cfunc_struct = type { i64 (...)*, i64 (i64 (...)*, i64, i32, i64*)*, i32 }
%union.anon.6 = type { i32 }
%struct.anon.7 = type { i64, i64, i64, i64* }
%struct.rb_mjit_unit = type opaque
%union.anon.8 = type { %struct.anon.9 }
%struct.anon.9 = type { i64, i32 }
%struct.rb_vm_tag = type { i64, i64, [1 x %struct.__jmp_buf_tag], %struct.rb_vm_tag*, i32 }
%struct.rb_vm_protect_tag = type { %struct.rb_vm_protect_tag* }
%struct.rb_ensure_list = type { %struct.rb_ensure_list*, %struct.rb_ensure_entry }
%struct.rb_ensure_entry = type { i64, i64 (...)*, i64 }
%struct.rb_trace_arg_struct = type { i32, %struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, i64, i64, i64, i64, i64, i32, i32, i64 }
%struct.anon.11 = type { i64*, i64*, i64, [1 x %struct.__jmp_buf_tag] }
%struct.rb_calling_info = type { i64, i64, i32 }
%struct.native_thread_data_struct = type { %union.anon.12, %union.anon.13 }
%union.anon.13 = type { %union.pthread_cond_t }
%struct.rb_unblock_callback = type { void (i8*)*, i8* }
%struct.rb_mutex_struct = type opaque
%struct.rb_thread_list_struct = type { %struct.rb_thread_list_struct*, %struct.rb_thread_struct* }
%union.anon.15 = type { %struct.RBasic }
%struct.RBasic = type { i64, i64 }
%struct.rb_fiber_struct = type opaque
%struct.__jmp_buf_tag = type { [8 x i64], i32, %struct.__sigset_t }
%struct.__sigset_t = type { [16 x i64] }
%struct.anon.18 = type { [65 x i64], [65 x i8] }
%struct.rb_hook_list_struct = type { %struct.rb_event_hook_struct*, i32, i32, i32 }
%struct.rb_event_hook_struct = type opaque
%struct.rb_postponed_job_struct = type opaque
%union.anon.12 = type { %struct.list_node }
%union.pthread_mutex_t = type { %struct.__pthread_mutex_s }
%struct.__pthread_mutex_s = type { i32, i32, i32, i32, i32, i16, i16, %struct.__pthread_internal_list }
%struct.__pthread_internal_list = type { %struct.__pthread_internal_list*, %struct.__pthread_internal_list* }
%struct.rb_objspace = type opaque
%struct.rb_at_exit_list = type { void (%struct.rb_vm_struct*)*, %struct.rb_at_exit_list* }
%struct.st_table = type { i8, i8, i8, i32, %struct.st_hash_type*, i64, i64*, i64, i64, %struct.st_table_entry* }
%struct.st_hash_type = type { i32 (...)*, i64 (...)* }
%struct.st_table_entry = type opaque
%struct.anon.19 = type { i64, i64, i64, i64 }
%struct.FunctionInlineCache = type { %struct.rb_callable_method_entry_struct*, i64, i64 }

@rb_eRuntimeError = external local_unnamed_addr global i64, align 8
@.str.1 = private unnamed_addr constant [95 x i8] c"sorbet_getBuildSCMRevision: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@.str.2 = private unnamed_addr constant [93 x i8] c"sorbet_getIsReleaseBuild: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@ruby_current_vm_ptr = external local_unnamed_addr global %struct.rb_vm_struct*, align 8
@ruby_current_execution_context_ptr = external local_unnamed_addr global %struct.rb_execution_context_struct*, align 8
@.str.17 = private unnamed_addr constant [24 x i8] c"$__sorbet_ruby_realpath\00", align 1
@.str.18 = private unnamed_addr constant [63 x i8] c"Invalid '$__sorbet_ruby_realpath' when loading compiled module\00", align 1
@"stackFramePrecomputed_func_<root>.<static-init>$153" = internal unnamed_addr global i8* null, align 8
@"rubyIdPrecomputed_<top (required)>" = internal unnamed_addr global i64 0, align 8
@"str_<top (required)>" = private unnamed_addr constant [17 x i8] c"<top (required)>\00", align 1
@"rubyStrFrozen_<top (required)>" = internal unnamed_addr global i64 0, align 8
@"rubyStrFrozen_test/testdata/compiler/block_no_args_capture.rb" = internal unnamed_addr global i64 0, align 8
@"str_test/testdata/compiler/block_no_args_capture.rb" = private unnamed_addr constant [48 x i8] c"test/testdata/compiler/block_no_args_capture.rb\00", align 1
@"<static-init-locals-storage>" = internal global [2 x i64] zeroinitializer
@"rubyIdPrecomputed_<self>" = internal unnamed_addr global i64 0, align 8
@"str_<self>" = private unnamed_addr constant [7 x i8] c"<self>\00", align 1
@rubyIdPrecomputed_s = internal unnamed_addr global i64 0, align 8
@str_s = private unnamed_addr constant [2 x i8] c"s\00", align 1
@"stackFramePrecomputed_func_<root>.<static-init>$153$block_1" = internal unnamed_addr global i8* null, align 8
@"rubyIdPrecomputed_block for" = internal unnamed_addr global i64 0, align 8
@"str_block for" = private unnamed_addr constant [10 x i8] c"block for\00", align 1
@str_cast = private unnamed_addr constant [5 x i8] c"cast\00", align 1
@"str_T.class_of(<root>)" = private unnamed_addr constant [19 x i8] c"T.class_of(<root>)\00", align 1
@rubyStrFrozen_hi = internal unnamed_addr global i64 0, align 8
@str_hi = private unnamed_addr constant [3 x i8] c"hi\00", align 1
@rubyIdPrecomputed_times = internal unnamed_addr global i64 0, align 8
@str_times = private unnamed_addr constant [6 x i8] c"times\00", align 1
@ic_callFuncWithBlock_times = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_puts = internal unnamed_addr global i64 0, align 8
@str_puts = private unnamed_addr constant [5 x i8] c"puts\00", align 1
@ic_callFunc_puts = internal global %struct.FunctionInlineCache zeroinitializer
@rb_mKernel = external local_unnamed_addr constant i64

; Function Attrs: nounwind ssp uwtable
define weak i8* @sorbet_getBuildSCMRevision() local_unnamed_addr #0 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !4
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* getelementptr inbounds ([95 x i8], [95 x i8]* @.str.1, i64 0, i64 0)) #8
  unreachable
}

; Function Attrs: noreturn
declare void @rb_raise(i64, i8*, ...) local_unnamed_addr #1

; Function Attrs: nounwind ssp uwtable
define weak i32 @sorbet_getIsReleaseBuild() local_unnamed_addr #0 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !4
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* getelementptr inbounds ([93 x i8], [93 x i8]* @.str.2, i64 0, i64 0)) #8
  unreachable
}

declare i64 @rb_fstring_new(i8*, i64) local_unnamed_addr #2

declare void @rb_gc_register_mark_object(i64) local_unnamed_addr #2

declare void @rb_ary_detransient(i64) local_unnamed_addr #2

declare i64 @rb_intern2(i8*, i64) local_unnamed_addr #2

; Function Attrs: cold noreturn nounwind optsize ssp uwtable
declare void @sorbet_cast_failure(i64, i8*, i8*) local_unnamed_addr #3

; Function Attrs: nounwind ssp uwtable
declare i8* @sorbet_allocateRubyStackFrame(i64, i64, i64, i64, i8*, i32, i32, i32, i64* nocapture readonly, i32) local_unnamed_addr #0

declare i64 @rb_gv_get(i8*) local_unnamed_addr #2

declare i64 @rb_gv_set(i8*, i64) local_unnamed_addr #2

; Function Attrs: noinline nounwind ssp uwtable
define internal fastcc void @vm_env_write_slowpath(i64* nocapture, i32, i64) unnamed_addr #4 {
  %4 = getelementptr inbounds i64, i64* %0, i64 1
  %5 = load i64, i64* %4, align 8, !tbaa !4
  tail call void @rb_gc_writebarrier_remember(i64 %5) #9
  %6 = sext i32 %1 to i64
  %7 = getelementptr inbounds i64, i64* %0, i64 %6
  store i64 %2, i64* %7, align 8, !tbaa !4
  %8 = load i64, i64* %0, align 8, !tbaa !4
  %9 = and i64 %8, -9
  store i64 %9, i64* %0, align 8, !tbaa !4
  ret void
}

declare void @rb_gc_writebarrier_remember(i64) local_unnamed_addr #2

; Function Attrs: nounwind ssp uwtable
declare %struct.rb_control_frame_struct* @sorbet_setRubyStackFrame(i1 zeroext, i32, i8*) local_unnamed_addr #0

; Function Attrs: noinline nounwind ssp uwtable
declare i64 @sorbet_callFuncWithCache(i64, i64, i32, i64* noalias nocapture, %struct.FunctionInlineCache* nocapture) local_unnamed_addr #4

; Function Attrs: noinline nounwind ssp uwtable
declare i64 @sorbet_callFuncBlockWithCache(i64, i64, i32, i64* noalias nocapture, i64 (i64, i64, i32, i64*, i64)*, i64, %struct.FunctionInlineCache*) local_unnamed_addr #4

; Function Attrs: nounwind ssp
define internal i64 @"func_<root>.<static-init>$153$block_1"(i64 %firstYieldArgRaw, i64 %localsOffset, i32 %argc, i64* nocapture readonly %argArray, i64 %blockArg) #5 !dbg !8 {
functionEntryInitializers:
  %callArgs = alloca [1 x i64], align 8
  %"stackFrame_func_<root>.<static-init>$153$block_112" = load i64, i64* bitcast (i8** @"stackFramePrecomputed_func_<root>.<static-init>$153$block_1" to i64*), align 8
  %0 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !13
  %1 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %0, i64 0, i32 2
  %2 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %1, align 8, !tbaa !15
  %3 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 2
  %4 = bitcast %struct.rb_iseq_struct** %3 to i64*
  store i64 %"stackFrame_func_<root>.<static-init>$153$block_112", i64* %4, align 8, !tbaa !19
  %5 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 4
  %6 = load i64*, i64** %5, align 8, !tbaa !21
  %7 = load i64, i64* %6, align 8, !tbaa !4
  %8 = and i64 %7, -129
  store i64 %8, i64* %6, align 8, !tbaa !4
  %9 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 0
  %10 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %3, align 8, !tbaa !19
  %11 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %10, i64 0, i32 2
  %12 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %11, align 8, !tbaa !22
  %13 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %12, i64 0, i32 2
  %14 = load i64*, i64** %13, align 8, !tbaa !24
  %15 = getelementptr inbounds i64, i64* %14, i64 4
  store i64* %15, i64** %9, align 8, !tbaa !13
  %rubyId_puts = load i64, i64* @rubyIdPrecomputed_puts, align 8, !dbg !33
  %arrayExpansionSizeGuard = icmp eq i32 %argc, 1, !dbg !34
  br i1 %arrayExpansionSizeGuard, label %argArrayExpandArrayTest, label %.preheader.i, !dbg !34

argArrayExpandArrayTest:                          ; preds = %functionEntryInitializers
  %arg1_maybeExpandToFullArgs = load i64, i64* %argArray, align 8, !dbg !34
  %16 = and i64 %arg1_maybeExpandToFullArgs, 7, !dbg !34
  %17 = icmp ne i64 %16, 0, !dbg !34
  %18 = and i64 %arg1_maybeExpandToFullArgs, -9, !dbg !34
  %19 = icmp eq i64 %18, 0, !dbg !34
  %20 = or i1 %17, %19, !dbg !34
  br i1 %20, label %.preheader.i, label %sorbet_isa_Array.exit, !dbg !34

sorbet_isa_Array.exit:                            ; preds = %argArrayExpandArrayTest
  %21 = inttoptr i64 %arg1_maybeExpandToFullArgs to %struct.RBasic*, !dbg !34
  %22 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %21, i64 0, i32 0, !dbg !34
  %23 = load i64, i64* %22, align 8, !dbg !34, !tbaa !35
  %24 = and i64 %23, 33554463, !dbg !34
  %25 = icmp eq i64 %24, 33554439, !dbg !34
  br i1 %25, label %26, label %.preheader.i, !dbg !34

26:                                               ; preds = %sorbet_isa_Array.exit
  tail call void @rb_ary_detransient(i64 %arg1_maybeExpandToFullArgs) #9, !dbg !34
  br label %.preheader.i, !dbg !34

.preheader.i:                                     ; preds = %sorbet_isa_Array.exit, %functionEntryInitializers, %26, %argArrayExpandArrayTest
  %27 = getelementptr inbounds i64, i64* %14, i64 6, !dbg !37
  store i64* %27, i64** %9, align 8, !dbg !37, !tbaa !13
  %28 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !33, !tbaa !13
  %29 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %28, i64 0, i32 2, !dbg !33
  %30 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %29, align 8, !dbg !33, !tbaa !15
  %31 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %30, i64 0, i32 4, !dbg !33
  %32 = load i64*, i64** %31, align 8, !dbg !33, !tbaa !21
  %33 = getelementptr inbounds i64, i64* %32, i64 -1, !dbg !33
  %34 = load i64, i64* %33, align 8, !dbg !33, !tbaa !4
  %35 = and i64 %34, -4, !dbg !33
  %36 = getelementptr inbounds i64, i64* %14, i64 5
  %37 = inttoptr i64 %35 to i64*, !dbg !33
  %38 = shl i64 %localsOffset, 32, !dbg !33
  %39 = add i64 %38, 17179869184, !dbg !33
  %40 = ashr exact i64 %39, 32, !dbg !33
  %41 = sub nsw i64 0, %40, !dbg !33
  %42 = getelementptr inbounds i64, i64* %37, i64 %41, !dbg !33
  %43 = load i64, i64* %42, align 8, !dbg !33, !tbaa !4
  %callArgs0Addr = getelementptr inbounds [1 x i64], [1 x i64]* %callArgs, i64 0, i64 0, !dbg !33
  store i64 %43, i64* %callArgs0Addr, align 8, !dbg !33
  %44 = load i64, i64* @rb_mKernel, align 8, !dbg !33
  %callFunc_puts = call i64 @sorbet_callFuncWithCache(i64 %44, i64 %rubyId_puts, i32 1, i64* nonnull %callArgs0Addr, %struct.FunctionInlineCache* nonnull @ic_callFunc_puts), !dbg !33
  store i64* %36, i64** %9, align 8, !dbg !33, !tbaa !13
  ret i64 %callFunc_puts, !dbg !37
}

; Function Attrs: nounwind sspreq
define void @Init_block_no_args_capture() local_unnamed_addr #6 {
entry:
  %0 = tail call i64 @rb_gv_get(i8* getelementptr inbounds ([24 x i8], [24 x i8]* @.str.17, i64 0, i64 0)) #9
  %1 = and i64 %0, 7
  %2 = icmp ne i64 %1, 0
  %3 = and i64 %0, -9
  %4 = icmp eq i64 %3, 0
  %5 = or i1 %2, %4
  br i1 %5, label %12, label %6

6:                                                ; preds = %entry
  %7 = inttoptr i64 %0 to %struct.RBasic*
  %8 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %7, i64 0, i32 0
  %9 = load i64, i64* %8, align 8, !tbaa !35
  %10 = and i64 %9, 31
  %11 = icmp eq i64 %10, 5
  br i1 %11, label %sorbet_readRealpath.exit, label %12

12:                                               ; preds = %6, %entry
  %13 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !4
  tail call void (i64, i8*, ...) @rb_raise(i64 %13, i8* getelementptr inbounds ([63 x i8], [63 x i8]* @.str.18, i64 0, i64 0)) #8
  unreachable

sorbet_readRealpath.exit:                         ; preds = %6
  %14 = tail call i64 @rb_gv_set(i8* getelementptr inbounds ([24 x i8], [24 x i8]* @.str.17, i64 0, i64 0), i64 8) #9
  %15 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 16) #9
  store i64 %15, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %16 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([7 x i8], [7 x i8]* @"str_<self>", i64 0, i64 0), i64 6) #9
  store i64 %16, i64* @"rubyIdPrecomputed_<self>", align 8
  %17 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([2 x i8], [2 x i8]* @str_s, i64 0, i64 0), i64 1) #9
  store i64 %17, i64* @rubyIdPrecomputed_s, align 8
  %18 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([10 x i8], [10 x i8]* @"str_block for", i64 0, i64 0), i64 9) #9
  store i64 %18, i64* @"rubyIdPrecomputed_block for", align 8
  %19 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([6 x i8], [6 x i8]* @str_times, i64 0, i64 0), i64 5) #9
  store i64 %19, i64* @rubyIdPrecomputed_times, align 8
  %20 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_puts, i64 0, i64 0), i64 4) #9
  store i64 %20, i64* @rubyIdPrecomputed_puts, align 8
  %"rubyId_<self>.i" = load i64, i64* @"rubyIdPrecomputed_<self>", align 8
  store i64 %"rubyId_<self>.i", i64* getelementptr inbounds ([2 x i64], [2 x i64]* @"<static-init-locals-storage>", i64 0, i64 0), align 8
  %rubyId_s.i = load i64, i64* @rubyIdPrecomputed_s, align 8
  store i64 %rubyId_s.i, i64* getelementptr inbounds ([2 x i64], [2 x i64]* @"<static-init-locals-storage>", i64 0, i64 1), align 8
  %21 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 16) #9
  tail call void @rb_gc_register_mark_object(i64 %21) #9
  store i64 %21, i64* @"rubyStrFrozen_<top (required)>", align 8
  %22 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([48 x i8], [48 x i8]* @"str_test/testdata/compiler/block_no_args_capture.rb", i64 0, i64 0), i64 47) #9
  tail call void @rb_gc_register_mark_object(i64 %22) #9
  store i64 %22, i64* @"rubyStrFrozen_test/testdata/compiler/block_no_args_capture.rb", align 8
  %"rubyId_<top (required)>.i.i" = load i64, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %"rubyStr_<top (required)>.i.i" = load i64, i64* @"rubyStrFrozen_<top (required)>", align 8
  %23 = tail call i8* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_<top (required)>.i.i", i64 %"rubyId_<top (required)>.i.i", i64 %22, i64 %0, i8* null, i32 1, i32 1, i32 7, i64* getelementptr inbounds ([2 x i64], [2 x i64]* @"<static-init-locals-storage>", i64 0, i64 0), i32 2) #9
  store i8* %23, i8** @"stackFramePrecomputed_func_<root>.<static-init>$153", align 8
  %24 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([10 x i8], [10 x i8]* @"str_block for", i64 0, i64 0), i64 9) #9
  tail call void @rb_gc_register_mark_object(i64 %24) #9
  %"stackFrame_func_<root>.<static-init>$153.i.i" = load i8*, i8** @"stackFramePrecomputed_func_<root>.<static-init>$153", align 8
  %"rubyId_block for.i.i" = load i64, i64* @"rubyIdPrecomputed_block for", align 8
  %"rubyStr_test/testdata/compiler/block_no_args_capture.rb.i1.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/block_no_args_capture.rb", align 8
  %25 = tail call i8* @sorbet_allocateRubyStackFrame(i64 %24, i64 %"rubyId_block for.i.i", i64 %"rubyStr_test/testdata/compiler/block_no_args_capture.rb.i1.i", i64 %0, i8* %"stackFrame_func_<root>.<static-init>$153.i.i", i32 2, i32 1, i32 7, i64* null, i32 0) #9
  store i8* %25, i8** @"stackFramePrecomputed_func_<root>.<static-init>$153$block_1", align 8
  %26 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([3 x i8], [3 x i8]* @str_hi, i64 0, i64 0), i64 2) #9
  tail call void @rb_gc_register_mark_object(i64 %26) #9
  store i64 %26, i64* @rubyStrFrozen_hi, align 8
  %27 = load %struct.rb_vm_struct*, %struct.rb_vm_struct** @ruby_current_vm_ptr, align 8, !tbaa !13
  %28 = getelementptr inbounds %struct.rb_vm_struct, %struct.rb_vm_struct* %27, i64 0, i32 17
  %29 = load i64, i64* %28, align 8, !tbaa !38
  %"stackFrame_func_<root>.<static-init>$153.i" = load i8*, i8** @"stackFramePrecomputed_func_<root>.<static-init>$153", align 8
  %30 = tail call %struct.rb_control_frame_struct* @sorbet_setRubyStackFrame(i1 false, i32 1, i8* %"stackFrame_func_<root>.<static-init>$153.i") #9
  %31 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %30, i64 0, i32 0
  %32 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %30, i64 0, i32 2
  %33 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %32, align 8, !tbaa !19
  %34 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %33, i64 0, i32 2
  %35 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %34, align 8, !tbaa !22
  %36 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %35, i64 0, i32 2
  %37 = load i64*, i64** %36, align 8, !tbaa !24
  %38 = getelementptr inbounds i64, i64* %37, i64 4
  store i64* %38, i64** %31, align 8, !tbaa !13
  %rubyStr_hi.i = load i64, i64* @rubyStrFrozen_hi, align 8, !dbg !47
  %rubyId_times.i = load i64, i64* @rubyIdPrecomputed_times, align 8, !dbg !48
  %39 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !49, !tbaa !13
  %40 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %39, i64 0, i32 2, !dbg !49
  %41 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %40, align 8, !dbg !49, !tbaa !15
  %42 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %41, i64 0, i32 4, !dbg !49
  %43 = load i64*, i64** %42, align 8, !dbg !49, !tbaa !21
  %44 = load i64, i64* %43, align 8, !dbg !49, !tbaa !4
  %45 = and i64 %44, 8, !dbg !49
  %46 = icmp eq i64 %45, 0, !dbg !49
  br i1 %46, label %47, label %49, !dbg !49, !prof !50

47:                                               ; preds = %sorbet_readRealpath.exit
  %48 = getelementptr inbounds i64, i64* %43, i64 -3, !dbg !49
  store i64 %29, i64* %48, align 8, !dbg !49, !tbaa !4
  br label %sorbet_writeLocal.exit.i, !dbg !49

49:                                               ; preds = %sorbet_readRealpath.exit
  tail call fastcc void @vm_env_write_slowpath(i64* nonnull %43, i32 -3, i64 %29) #9, !dbg !49
  br label %sorbet_writeLocal.exit.i, !dbg !49

sorbet_writeLocal.exit.i:                         ; preds = %49, %47
  store i64* %38, i64** %31, align 8, !tbaa !13
  %50 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !49, !tbaa !13
  %51 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %50, i64 0, i32 2, !dbg !49
  %52 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %51, align 8, !dbg !49, !tbaa !15
  %53 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %52, i64 0, i32 4, !dbg !49
  %54 = load i64*, i64** %53, align 8, !dbg !49, !tbaa !21
  %55 = getelementptr inbounds i64, i64* %54, i64 -3, !dbg !49
  %56 = load i64, i64* %55, align 8, !dbg !49, !tbaa !4
  %57 = load %struct.rb_vm_struct*, %struct.rb_vm_struct** @ruby_current_vm_ptr, align 8, !dbg !49, !tbaa !13
  %58 = getelementptr inbounds %struct.rb_vm_struct, %struct.rb_vm_struct* %57, i64 0, i32 17, !dbg !49
  %59 = load i64, i64* %58, align 8, !dbg !49, !tbaa !38
  %60 = icmp eq i64 %59, %56, !dbg !49
  br i1 %60, label %typeTestSuccess.i, label %codeRepl, !dbg !49, !prof !50

typeTestSuccess.i:                                ; preds = %sorbet_writeLocal.exit.i
  %61 = load i64, i64* %54, align 8, !dbg !49, !tbaa !4
  %62 = and i64 %61, 8, !dbg !49
  %63 = icmp eq i64 %62, 0, !dbg !49
  br i1 %63, label %sorbet_writeLocal.exit17.i, label %64, !dbg !49, !prof !50

64:                                               ; preds = %typeTestSuccess.i
  tail call fastcc void @vm_env_write_slowpath(i64* nonnull %54, i32 -3, i64 %56) #9, !dbg !49
  br label %sorbet_writeLocal.exit17.i, !dbg !49

sorbet_writeLocal.exit17.i:                       ; preds = %64, %typeTestSuccess.i
  %65 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !47, !tbaa !13
  %66 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %65, i64 0, i32 2, !dbg !47
  %67 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %66, align 8, !dbg !47, !tbaa !15
  %68 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %67, i64 0, i32 4, !dbg !47
  %69 = load i64*, i64** %68, align 8, !dbg !47, !tbaa !21
  %70 = load i64, i64* %69, align 8, !dbg !47, !tbaa !4
  %71 = and i64 %70, 8, !dbg !47
  %72 = icmp eq i64 %71, 0, !dbg !47
  br i1 %72, label %73, label %75, !dbg !47, !prof !50

73:                                               ; preds = %sorbet_writeLocal.exit17.i
  %74 = getelementptr inbounds i64, i64* %69, i64 -4, !dbg !47
  store i64 %rubyStr_hi.i, i64* %74, align 8, !dbg !47, !tbaa !4
  br label %"func_<root>.<static-init>$153.exit", !dbg !47

75:                                               ; preds = %sorbet_writeLocal.exit17.i
  tail call fastcc void @vm_env_write_slowpath(i64* nonnull %69, i32 -4, i64 %rubyStr_hi.i) #9, !dbg !47
  br label %"func_<root>.<static-init>$153.exit", !dbg !47

codeRepl:                                         ; preds = %sorbet_writeLocal.exit.i
  tail call fastcc void @Init_block_no_args_capture.cold.1(i64 %56) #10
  unreachable

"func_<root>.<static-init>$153.exit":             ; preds = %73, %75
  %76 = getelementptr inbounds i64, i64* %37, i64 5, !dbg !47
  store i64* %76, i64** %31, align 8, !dbg !47, !tbaa !13
  %callFuncWithBlock_times.i = tail call i64 @sorbet_callFuncBlockWithCache(i64 21, i64 %rubyId_times.i, i32 0, i64* null, i64 (i64, i64, i32, i64*, i64)* nonnull @"func_<root>.<static-init>$153$block_1", i64 0, %struct.FunctionInlineCache* nonnull @ic_callFuncWithBlock_times) #9, !dbg !48
  store i64* %76, i64** %31, align 8, !tbaa !13
  ret void
}

; Function Attrs: cold minsize noreturn nounwind sspreq
define internal fastcc void @Init_block_no_args_capture.cold.1(i64) unnamed_addr #7 {
newFuncRoot:
  tail call void @sorbet_cast_failure(i64 %0, i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_cast, i64 0, i64 0), i8* getelementptr inbounds ([19 x i8], [19 x i8]* @"str_T.class_of(<root>)", i64 0, i64 0)) #9, !dbg !49
  unreachable, !dbg !49
}

attributes #0 = { nounwind ssp uwtable }
attributes #1 = { noreturn }
attributes #2 = { "addedToSilenceEmptyAttrsError" }
attributes #3 = { cold noreturn nounwind optsize ssp uwtable }
attributes #4 = { noinline nounwind ssp uwtable }
attributes #5 = { nounwind ssp }
attributes #6 = { nounwind sspreq }
attributes #7 = { cold minsize noreturn nounwind sspreq }
attributes #8 = { noreturn nounwind }
attributes #9 = { nounwind }
attributes #10 = { noinline }

!llvm.module.flags = !{!0}
!llvm.dbg.cu = !{!1}

!0 = !{i32 2, !"Debug Info Version", i32 3}
!1 = distinct !DICompileUnit(language: DW_LANG_C, file: !2, producer: "Sorbet LLVM", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, enums: !3)
!2 = !DIFile(filename: "test/testdata/compiler/block_no_args_capture.rb", directory: ".")
!3 = !{}
!4 = !{!5, !5, i64 0}
!5 = !{!"long", !6, i64 0}
!6 = !{!"omnipotent char", !7, i64 0}
!7 = !{!"Simple C/C++ TBAA"}
!8 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.<static-init>$153$block_1", scope: !9, file: !2, line: 4, type: !10, scopeLine: 4, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!9 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.<static-init>$153", scope: null, file: !2, line: 4, type: !10, scopeLine: 4, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!10 = !DISubroutineType(types: !11)
!11 = !{!12}
!12 = !DIBasicType(name: "VALUE", size: 64, encoding: DW_ATE_signed)
!13 = !{!14, !14, i64 0}
!14 = !{!"any pointer", !6, i64 0}
!15 = !{!16, !14, i64 16}
!16 = !{!"rb_execution_context_struct", !14, i64 0, !5, i64 8, !14, i64 16, !14, i64 24, !14, i64 32, !17, i64 40, !17, i64 44, !14, i64 48, !14, i64 56, !14, i64 64, !5, i64 72, !5, i64 80, !14, i64 88, !5, i64 96, !14, i64 104, !14, i64 112, !5, i64 120, !5, i64 128, !6, i64 136, !6, i64 137, !5, i64 144, !18, i64 152}
!17 = !{!"int", !6, i64 0}
!18 = !{!"", !14, i64 0, !14, i64 8, !5, i64 16, !6, i64 24}
!19 = !{!20, !14, i64 16}
!20 = !{!"rb_control_frame_struct", !14, i64 0, !14, i64 8, !14, i64 16, !5, i64 24, !14, i64 32, !14, i64 40, !14, i64 48}
!21 = !{!20, !14, i64 32}
!22 = !{!23, !14, i64 16}
!23 = !{!"rb_iseq_struct", !5, i64 0, !5, i64 8, !14, i64 16, !6, i64 24}
!24 = !{!25, !14, i64 8}
!25 = !{!"rb_iseq_constant_body", !6, i64 0, !17, i64 4, !14, i64 8, !26, i64 16, !28, i64 64, !31, i64 120, !14, i64 152, !14, i64 160, !14, i64 168, !14, i64 176, !14, i64 184, !14, i64 192, !14, i64 200, !32, i64 208, !17, i64 240, !17, i64 244, !17, i64 248, !17, i64 252, !17, i64 256, !14, i64 264, !5, i64 272, !14, i64 280, !6, i64 288}
!26 = !{!"", !27, i64 0, !17, i64 4, !17, i64 8, !17, i64 12, !17, i64 16, !17, i64 20, !17, i64 24, !17, i64 28, !14, i64 32, !14, i64 40}
!27 = !{!"", !17, i64 0, !17, i64 0, !17, i64 0, !17, i64 0, !17, i64 0, !17, i64 0, !17, i64 0, !17, i64 0}
!28 = !{!"rb_iseq_location_struct", !5, i64 0, !5, i64 8, !5, i64 16, !5, i64 24, !17, i64 32, !29, i64 36}
!29 = !{!"rb_code_location_struct", !30, i64 0, !30, i64 8}
!30 = !{!"rb_code_position_struct", !17, i64 0, !17, i64 4}
!31 = !{!"iseq_insn_info", !14, i64 0, !14, i64 8, !17, i64 16, !14, i64 24}
!32 = !{!"", !5, i64 0, !5, i64 8, !5, i64 16, !14, i64 24}
!33 = !DILocation(line: 6, column: 3, scope: !8)
!34 = !DILocation(line: 4, column: 1, scope: !8)
!35 = !{!36, !5, i64 0}
!36 = !{!"RBasic", !5, i64 0, !5, i64 8}
!37 = !DILocation(line: 5, column: 1, scope: !8)
!38 = !{!39, !5, i64 400}
!39 = !{!"rb_vm_struct", !5, i64 0, !40, i64 8, !14, i64 192, !14, i64 200, !14, i64 208, !43, i64 216, !6, i64 224, !41, i64 264, !41, i64 280, !41, i64 296, !41, i64 312, !5, i64 328, !17, i64 336, !17, i64 340, !17, i64 340, !17, i64 340, !17, i64 340, !17, i64 344, !5, i64 352, !6, i64 360, !5, i64 400, !5, i64 408, !5, i64 416, !5, i64 424, !5, i64 432, !5, i64 440, !5, i64 448, !14, i64 456, !14, i64 464, !44, i64 472, !45, i64 1064, !14, i64 1088, !14, i64 1096, !17, i64 1104, !17, i64 1108, !41, i64 1112, !6, i64 1128, !5, i64 1168, !5, i64 1176, !5, i64 1184, !5, i64 1192, !5, i64 1200, !17, i64 1208, !5, i64 1216, !14, i64 1224, !14, i64 1232, !14, i64 1240, !14, i64 1248, !46, i64 1256, !6, i64 1288}
!40 = !{!"rb_global_vm_lock_struct", !14, i64 0, !6, i64 8, !41, i64 48, !14, i64 64, !17, i64 72, !6, i64 80, !6, i64 128, !17, i64 176, !17, i64 180}
!41 = !{!"list_head", !42, i64 0}
!42 = !{!"list_node", !14, i64 0, !14, i64 8}
!43 = !{!"long long", !6, i64 0}
!44 = !{!"", !6, i64 0, !6, i64 520}
!45 = !{!"rb_hook_list_struct", !14, i64 0, !17, i64 8, !17, i64 12, !17, i64 16}
!46 = !{!"", !5, i64 0, !5, i64 8, !5, i64 16, !5, i64 24}
!47 = !DILocation(line: 4, column: 5, scope: !9)
!48 = !DILocation(line: 5, column: 1, scope: !9)
!49 = !DILocation(line: 4, column: 1, scope: !9)
!50 = !{!"branch_weights", i32 2000, i32 1}
