; ModuleID = 'payload'
source_filename = "llvm-link"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

%struct.rb_vm_struct = type { i64, %struct.rb_global_vm_lock_struct, %struct.rb_thread_struct*, %struct.rb_thread_struct*, i8*, i64, %union.pthread_mutex_t, %struct.list_head, %struct.list_head, %struct.list_head, %struct.list_head, i64, i32, i32, i8, i32, i64, [5 x i64], i64, i64, i64, i64, i64, i64, i64, %struct.st_table*, %struct.st_table*, %struct.anon.5, %struct.rb_hook_list_struct, %struct.st_table*, %struct.rb_postponed_job_struct*, i32, i32, %struct.list_head, %union.pthread_mutex_t, i64, i64, i64, i64, i64, i32, %struct.st_table*, %struct.rb_objspace*, %struct.rb_at_exit_list*, i64*, %struct.st_table*, %struct.rb_builtin_function*, i32, %struct.anon.6, [29 x i16] }
%struct.rb_global_vm_lock_struct = type { %struct.rb_thread_struct*, %union.pthread_mutex_t, %struct.list_head, %struct.rb_thread_struct*, i32, %union.pthread_cond_t, %union.pthread_cond_t, i32, i32 }
%union.pthread_cond_t = type { %struct.__pthread_cond_s }
%struct.__pthread_cond_s = type { %union.anon, %union.anon, [2 x i32], [2 x i32], i32, i32, [2 x i32] }
%union.anon = type { i64 }
%struct.rb_thread_struct = type { %struct.list_node, i64, %struct.rb_vm_struct*, %struct.rb_execution_context_struct*, i64, %struct.rb_calling_info*, i64, i64, i64, i8, i8, i32, %struct.native_thread_data_struct, i8*, i64, i64, i64, i64, %union.pthread_mutex_t, %struct.rb_unblock_callback, i64, %struct.rb_mutex_struct*, %struct.rb_thread_list_struct*, %union.anon.10, i32, i64, %struct.rb_fiber_struct*, [5 x i8*], i64 }
%struct.list_node = type { %struct.list_node*, %struct.list_node* }
%struct.rb_execution_context_struct = type { i64*, i64, %struct.rb_control_frame_struct*, %struct.rb_vm_tag*, %struct.rb_vm_protect_tag*, i32, i32, %struct.rb_fiber_struct*, %struct.rb_thread_struct*, %struct.st_table*, i64, i64, i64*, i64, %struct.rb_ensure_list*, %struct.rb_trace_arg_struct*, i64, i64, i8, i8, i64, %struct.anon.7 }
%struct.rb_control_frame_struct = type { i64*, i64*, %struct.rb_iseq_struct*, i64, i64*, i8*, i64* }
%struct.rb_iseq_struct = type { i64, i64, %struct.rb_iseq_constant_body*, %union.anon.17 }
%struct.rb_iseq_constant_body = type { i32, i32, i64*, %struct.anon, %struct.rb_iseq_location_struct, %struct.iseq_insn_info, i64*, %struct.iseq_catch_table*, %struct.rb_iseq_struct*, %struct.rb_iseq_struct*, %union.iseq_inline_storage_entry*, %struct.rb_call_data*, %struct.anon.16, i32, i32, i32, i32, i32, i8, i64 }
%struct.anon = type { %struct.anon.0, i32, i32, i32, i32, i32, i32, i32, i64*, %struct.rb_iseq_param_keyword* }
%struct.anon.0 = type { i16, [2 x i8] }
%struct.rb_iseq_param_keyword = type { i32, i32, i32, i32, i64*, i64* }
%struct.rb_iseq_location_struct = type { i64, i64, i64, i64, i32, %struct.rb_code_location_struct }
%struct.rb_code_location_struct = type { %struct.rb_code_position_struct, %struct.rb_code_position_struct }
%struct.rb_code_position_struct = type { i32, i32 }
%struct.iseq_insn_info = type { %struct.iseq_insn_info_entry*, i32*, i32, %struct.succ_index_table* }
%struct.iseq_insn_info_entry = type opaque
%struct.succ_index_table = type opaque
%struct.iseq_catch_table = type opaque
%union.iseq_inline_storage_entry = type { %struct.iseq_inline_cache_entry }
%struct.iseq_inline_cache_entry = type { i64, %struct.rb_cref_struct*, i64 }
%struct.rb_cref_struct = type { i64, i64, i64, %struct.rb_cref_struct*, %struct.rb_scope_visi_struct }
%struct.rb_scope_visi_struct = type { i8, [3 x i8] }
%struct.rb_call_data = type { %struct.rb_call_cache, %struct.rb_call_info }
%struct.rb_call_cache = type { i64, [3 x i64], %struct.rb_callable_method_entry_struct*, i64, i64 (%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_calling_info*, %struct.rb_call_data*)*, %union.anon.15 }
%struct.rb_callable_method_entry_struct = type { i64, i64, %struct.rb_method_definition_struct*, i64, i64 }
%struct.rb_method_definition_struct = type { i64, %union.anon.13, i64, i64 }
%union.anon.13 = type { %struct.rb_method_cfunc_struct }
%struct.rb_method_cfunc_struct = type { i64 (...)*, i64 (i64, i32, i64*, i64 (...)*)*, i32 }
%union.anon.15 = type { i32 }
%struct.rb_call_info = type { i64, i32, i32 }
%struct.anon.16 = type { i64, i64, i64, i64* }
%union.anon.17 = type { %struct.anon.18 }
%struct.anon.18 = type { i64, i32 }
%struct.rb_vm_tag = type { i64, i64, [5 x i8*], %struct.rb_vm_tag*, i32 }
%struct.rb_vm_protect_tag = type { %struct.rb_vm_protect_tag* }
%struct.rb_ensure_list = type { %struct.rb_ensure_list*, %struct.rb_ensure_entry }
%struct.rb_ensure_entry = type { i64, i64 (i64)*, i64 }
%struct.rb_trace_arg_struct = type { i32, %struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, i64, i64, i64, i64, i64, i32, i32, i64 }
%struct.anon.7 = type { i64*, i64*, i64, [1 x %struct.__jmp_buf_tag] }
%struct.__jmp_buf_tag = type { [8 x i64], i32, %struct.__sigset_t }
%struct.__sigset_t = type { [16 x i64] }
%struct.rb_calling_info = type { i64, i64, i32, i32 }
%struct.native_thread_data_struct = type { %struct.list_head, %union.anon.9 }
%union.anon.9 = type { %union.pthread_cond_t }
%struct.rb_unblock_callback = type { void (i8*)*, i8* }
%struct.rb_mutex_struct = type opaque
%struct.rb_thread_list_struct = type { %struct.rb_thread_list_struct*, %struct.rb_thread_struct* }
%union.anon.10 = type { %struct.anon.11 }
%struct.anon.11 = type { i64, i64, i32 }
%struct.rb_fiber_struct = type opaque
%struct.anon.5 = type { [65 x i64] }
%struct.rb_hook_list_struct = type { %struct.rb_event_hook_struct*, i32, i32, i32 }
%struct.rb_event_hook_struct = type opaque
%struct.rb_postponed_job_struct = type opaque
%struct.list_head = type { %struct.list_node }
%union.pthread_mutex_t = type { %struct.__pthread_mutex_s }
%struct.__pthread_mutex_s = type { i32, i32, i32, i32, i32, i16, i16, %struct.__pthread_internal_list }
%struct.__pthread_internal_list = type { %struct.__pthread_internal_list*, %struct.__pthread_internal_list* }
%struct.rb_objspace = type opaque
%struct.rb_at_exit_list = type { void (%struct.rb_vm_struct*)*, %struct.rb_at_exit_list* }
%struct.st_table = type { i8, i8, i8, i32, %struct.st_hash_type*, i64, i64*, i64, i64, %struct.st_table_entry* }
%struct.st_hash_type = type { i32 (i64, i64)*, i64 (i64)* }
%struct.st_table_entry = type opaque
%struct.rb_builtin_function = type opaque
%struct.anon.6 = type { i64, i64, i64, i64 }
%struct.SorbetLineNumberInfo = type { i32, %struct.iseq_insn_info_entry*, i64* }
%struct.FunctionInlineCache = type { %struct.rb_kwarg_call_data }
%struct.rb_kwarg_call_data = type { %struct.rb_call_cache, %struct.rb_call_info_with_kwarg }
%struct.rb_call_info_with_kwarg = type { %struct.rb_call_info, %struct.rb_call_info_kw_arg* }
%struct.rb_call_info_kw_arg = type { i32, [1 x i64] }
%struct.vm_ifunc = type { i64, i64, i64 (i64, i64, i32, i64*, i64)*, i8*, %struct.rb_code_position_struct }
%struct.rb_captured_block = type { i64, i64*, %union.anon.20 }
%union.anon.20 = type { %struct.rb_iseq_struct* }
%struct.iseq_inline_iv_cache_entry = type { i64, i64 }

@ruby_current_vm_ptr = external local_unnamed_addr global %struct.rb_vm_struct*, align 8
@ruby_current_execution_context_ptr = external local_unnamed_addr global %struct.rb_execution_context_struct*, align 8
@ruby_vm_global_constant_state = external local_unnamed_addr global i64, align 8
@rb_eRuntimeError = external local_unnamed_addr global i64, align 8
@.str.9 = private unnamed_addr constant [95 x i8] c"sorbet_getBuildSCMRevision: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@.str.10 = private unnamed_addr constant [93 x i8] c"sorbet_getIsReleaseBuild: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@"stackFramePrecomputed_func_<root>.17<static-init>$152" = unnamed_addr global %struct.rb_iseq_struct* null, align 8
@"rubyIdPrecomputed_<top (required)>" = internal unnamed_addr global i64 0, align 8
@"str_<top (required)>" = private unnamed_addr constant [17 x i8] c"<top (required)>\00", align 1
@"rubyStrFrozen_<top (required)>" = internal unnamed_addr global i64 0, align 8
@"rubyStrFrozen_test/testdata/compiler/block_type_checking.rb" = internal unnamed_addr global i64 0, align 8
@"str_test/testdata/compiler/block_type_checking.rb" = private unnamed_addr constant [46 x i8] c"test/testdata/compiler/block_type_checking.rb\00", align 1
@iseqEncodedArray = internal global [19 x i64] zeroinitializer
@fileLineNumberInfo = internal global %struct.SorbetLineNumberInfo zeroinitializer
@"stackFramePrecomputed_func_<root>.17<static-init>$152$block_1" = unnamed_addr global %struct.rb_iseq_struct* null, align 8
@"rubyIdPrecomputed_block in <top (required)>" = internal unnamed_addr global i64 0, align 8
@"str_block in <top (required)>" = private unnamed_addr constant [26 x i8] c"block in <top (required)>\00", align 1
@str_Foo = private unnamed_addr constant [4 x i8] c"Foo\00", align 1
@ic_new = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_new = internal unnamed_addr global i64 0, align 8
@str_new = private unnamed_addr constant [4 x i8] c"new\00", align 1
@ic_bar = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_bar = internal unnamed_addr global i64 0, align 8
@str_bar = private unnamed_addr constant [4 x i8] c"bar\00", align 1
@ic_p = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_p = internal unnamed_addr global i64 0, align 8
@str_p = private unnamed_addr constant [2 x i8] c"p\00", align 1
@"stackFramePrecomputed_func_Foo#3bar" = unnamed_addr global %struct.rb_iseq_struct* null, align 8
@"str_Parameter 'x'" = private unnamed_addr constant [14 x i8] c"Parameter 'x'\00", align 1
@str_Integer = private unnamed_addr constant [8 x i8] c"Integer\00", align 1
@"str_Parameter 'blk'" = private unnamed_addr constant [16 x i8] c"Parameter 'blk'\00", align 1
@"str_T.proc.returns(Integer)" = private unnamed_addr constant [24 x i8] c"T.proc.returns(Integer)\00", align 1
@"str_+" = private unnamed_addr constant [2 x i8] c"+\00", align 1
@"str_Return value" = private unnamed_addr constant [13 x i8] c"Return value\00", align 1
@"stackFramePrecomputed_func_Foo.13<static-init>" = unnamed_addr global %struct.rb_iseq_struct* null, align 8
@"rubyIdPrecomputed_<class:Foo>" = internal unnamed_addr global i64 0, align 8
@"str_<class:Foo>" = private unnamed_addr constant [12 x i8] c"<class:Foo>\00", align 1
@"stackFramePrecomputed_func_Foo.13<static-init>$block_1" = unnamed_addr global %struct.rb_iseq_struct* null, align 8
@"rubyIdPrecomputed_block in <class:Foo>" = internal unnamed_addr global i64 0, align 8
@"str_block in <class:Foo>" = private unnamed_addr constant [21 x i8] c"block in <class:Foo>\00", align 1
@rubyIdPrecomputed_x = internal unnamed_addr global i64 0, align 8
@str_x = private unnamed_addr constant [2 x i8] c"x\00", align 1
@rubyIdPrecomputed_blk = internal unnamed_addr global i64 0, align 8
@str_blk = private unnamed_addr constant [4 x i8] c"blk\00", align 1
@ic_proc = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_proc = internal unnamed_addr global i64 0, align 8
@str_proc = private unnamed_addr constant [5 x i8] c"proc\00", align 1
@str_T = private unnamed_addr constant [2 x i8] c"T\00", align 1
@ic_returns = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_returns = internal unnamed_addr global i64 0, align 8
@str_returns = private unnamed_addr constant [8 x i8] c"returns\00", align 1
@ic_params = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_params = internal unnamed_addr global i64 0, align 8
@str_params = private unnamed_addr constant [7 x i8] c"params\00", align 1
@ic_returns.1 = internal global %struct.FunctionInlineCache zeroinitializer
@"str_T::Sig" = private unnamed_addr constant [7 x i8] c"T::Sig\00", align 1
@ic_extend = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_extend = internal unnamed_addr global i64 0, align 8
@str_extend = private unnamed_addr constant [7 x i8] c"extend\00", align 1
@str_normal = private unnamed_addr constant [7 x i8] c"normal\00", align 1
@"guard_epoch_T::Sig" = linkonce local_unnamed_addr global i64 0
@"guarded_const_T::Sig" = linkonce local_unnamed_addr global i64 0
@guard_epoch_Foo = linkonce local_unnamed_addr global i64 0
@guarded_const_Foo = linkonce local_unnamed_addr global i64 0
@rb_cObject = external local_unnamed_addr constant i64
@guard_epoch_T = linkonce local_unnamed_addr global i64 0
@guarded_const_T = linkonce local_unnamed_addr global i64 0
@rb_cInteger = external local_unnamed_addr constant i64

; Function Attrs: nounwind readnone willreturn
declare i64 @rb_id2sym(i64) local_unnamed_addr #0

; Function Attrs: cold noreturn
declare void @sorbet_cast_failure(i64, i8*, i8*) local_unnamed_addr #1

; Function Attrs: noreturn
declare void @sorbet_raiseArity(i32, i32, i32) local_unnamed_addr #2

declare %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64, i64, i64, i64, %struct.rb_iseq_struct*, i32, i32, %struct.SorbetLineNumberInfo*, i64*, i32, i32) local_unnamed_addr #3

declare void @sorbet_initLineNumberInfo(%struct.SorbetLineNumberInfo*, i64*, i32) local_unnamed_addr #3

declare i64 @sorbet_getConstant(i8*, i64) local_unnamed_addr #3

declare i64 @sorbet_readRealpath() local_unnamed_addr #3

declare %struct.rb_control_frame_struct* @sorbet_pushStaticInitFrame(i64) local_unnamed_addr #3

declare void @sorbet_popFrame() local_unnamed_addr #3

declare void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache*, i64, i32, i32, i32, i64*) local_unnamed_addr #3

declare i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache*, i64) local_unnamed_addr #3

declare void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_iseq_struct*) local_unnamed_addr #3

declare i64 @sorbet_rb_int_plus_slowpath(i64, i64) local_unnamed_addr #3

declare void @sorbet_vm_register_sig(i64, i64, i64, i64, i64 (i64, i64, i32, i64*, i64)*) local_unnamed_addr #3

declare void @sorbet_vm_define_method(i64, i8*, i64 (i32, i64*, i64, %struct.rb_control_frame_struct*, i8*)*, i8*, %struct.rb_iseq_struct*, i1 zeroext) local_unnamed_addr #3

declare i64 @sorbet_vm_fstring_new(i8*, i64) local_unnamed_addr #3

declare i64 @sorbet_vm_callBlock(%struct.rb_control_frame_struct*, i32, i64* nocapture, i32) local_unnamed_addr #3

declare i32 @rb_block_given_p() local_unnamed_addr #3

declare i64 @rb_block_proc() local_unnamed_addr #3

declare i64 @rb_define_class(i8*, i64) local_unnamed_addr #3

declare i64 @rb_intern2(i8*, i64) local_unnamed_addr #3

declare void @rb_gc_register_mark_object(i64) local_unnamed_addr #3

; Function Attrs: noreturn
declare void @rb_raise(i64, i8*, ...) local_unnamed_addr #2

declare i64 @rb_int2big(i64) local_unnamed_addr #3

; Function Attrs: nofree nosync nounwind readnone speculatable willreturn
declare { i64, i1 } @llvm.sadd.with.overflow.i64(i64, i64) #4

declare i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct*, i32) local_unnamed_addr #3

declare %struct.vm_ifunc* @rb_vm_ifunc_new(i64 (i64, i64, i32, i64*, i64)*, i8*, i32, i32) local_unnamed_addr #3

; Function Attrs: allocsize(0,1)
declare noalias nonnull i8* @ruby_xcalloc(i64, i64) local_unnamed_addr #5

; Function Attrs: allocsize(0,1)
declare noalias nonnull i8* @ruby_xmalloc2(i64, i64) local_unnamed_addr #5

; Function Attrs: argmemonly nofree nosync nounwind willreturn
declare void @llvm.memcpy.p0i8.p0i8.i64(i8* noalias nocapture writeonly, i8* noalias nocapture readonly, i64, i1 immarg) #6

; Function Attrs: nounwind ssp uwtable
define weak i32 @sorbet_getIsReleaseBuild() local_unnamed_addr #7 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !6
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* noundef getelementptr inbounds ([93 x i8], [93 x i8]* @.str.10, i64 0, i64 0)) #16
  unreachable
}

; Function Attrs: nounwind ssp uwtable
define weak i8* @sorbet_getBuildSCMRevision() local_unnamed_addr #7 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !6
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* noundef getelementptr inbounds ([95 x i8], [95 x i8]* @.str.9, i64 0, i64 0)) #16
  unreachable
}

; Function Attrs: nofree nosync nounwind ssp willreturn
define internal noundef i64 @"func_<root>.17<static-init>$152$block_1"(i64 %firstYieldArgRaw, i64 %localsOffset, i32 %argc, i64* nocapture nofree readnone %argArray, i64 %blockArg) #8 !dbg !10 {
functionEntryInitializers:
  %0 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !15
  %1 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %0, i64 0, i32 2
  %2 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %1, align 8, !tbaa !17
  %stackFrame = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_<root>.17<static-init>$152$block_1", align 8
  %3 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 2
  store %struct.rb_iseq_struct* %stackFrame, %struct.rb_iseq_struct** %3, align 8, !tbaa !21
  %4 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 4
  %5 = load i64*, i64** %4, align 8, !tbaa !23
  %6 = load i64, i64* %5, align 8, !tbaa !6
  %7 = and i64 %6, -129
  store i64 %7, i64* %5, align 8, !tbaa !6
  %8 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 0
  store i64* getelementptr inbounds ([19 x i64], [19 x i64]* @iseqEncodedArray, i64 0, i64 15), i64** %8, align 8, !dbg !24, !tbaa !15
  ret i64 13, !dbg !25
}

; Function Attrs: nounwind sspreq uwtable
define internal fastcc void @"func_Foo.13<static-init>L62"(i64 %selfRaw, %struct.rb_control_frame_struct* %cfp) unnamed_addr #9 !dbg !26 {
functionEntryInitializers:
  %stackFrame = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Foo.13<static-init>", align 8
  %0 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !15
  %1 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %0, i64 0, i32 2
  %2 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %1, align 8, !tbaa !17
  %3 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 2
  store %struct.rb_iseq_struct* %stackFrame, %struct.rb_iseq_struct** %3, align 8, !tbaa !21
  %4 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 4
  %5 = load i64*, i64** %4, align 8, !tbaa !23
  %6 = load i64, i64* %5, align 8, !tbaa !6
  %7 = and i64 %6, -33
  store i64 %7, i64* %5, align 8, !tbaa !6
  tail call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* %0, %struct.rb_control_frame_struct* %2, %struct.rb_iseq_struct* %stackFrame) #17
  %8 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %cfp, i64 0, i32 0
  store i64* getelementptr inbounds ([19 x i64], [19 x i64]* @iseqEncodedArray, i64 0, i64 8), i64** %8, align 8, !dbg !27, !tbaa !15
  %rubyId_bar = load i64, i64* @rubyIdPrecomputed_bar, align 8, !dbg !28
  %rawSym = tail call i64 @rb_id2sym(i64 %rubyId_bar), !dbg !28
  tail call void @sorbet_vm_register_sig(i64 noundef 0, i64 %rawSym, i64 %selfRaw, i64 noundef 8, i64 (i64, i64, i32, i64*, i64)* noundef @"func_Foo.13<static-init>L62$block_1"), !dbg !28
  %9 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !28, !tbaa !15
  %10 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %9, i64 0, i32 5, !dbg !28
  %11 = load i32, i32* %10, align 8, !dbg !28, !tbaa !29
  %12 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %9, i64 0, i32 6, !dbg !28
  %13 = load i32, i32* %12, align 4, !dbg !28, !tbaa !30
  %14 = xor i32 %13, -1, !dbg !28
  %15 = and i32 %14, %11, !dbg !28
  %16 = icmp eq i32 %15, 0, !dbg !28
  br i1 %16, label %rb_vm_check_ints.exit1, label %17, !dbg !28, !prof !31

17:                                               ; preds = %functionEntryInitializers
  %18 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %9, i64 0, i32 8, !dbg !28
  %19 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %18, align 8, !dbg !28, !tbaa !32
  %20 = tail call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* %19, i32 noundef 0) #17, !dbg !28
  br label %rb_vm_check_ints.exit1, !dbg !28

rb_vm_check_ints.exit1:                           ; preds = %functionEntryInitializers, %17
  store i64* getelementptr inbounds ([19 x i64], [19 x i64]* @iseqEncodedArray, i64 0, i64 6), i64** %8, align 8, !dbg !28, !tbaa !15
  %21 = load i64, i64* @"guard_epoch_T::Sig", align 8, !dbg !33
  %22 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !33, !tbaa !34
  %needTakeSlowPath = icmp ne i64 %21, %22, !dbg !33
  br i1 %needTakeSlowPath, label %23, label %24, !dbg !33, !prof !36

23:                                               ; preds = %rb_vm_check_ints.exit1
  tail call void @"const_recompute_T::Sig"(), !dbg !33
  br label %24, !dbg !33

24:                                               ; preds = %rb_vm_check_ints.exit1, %23
  %25 = load i64, i64* @"guarded_const_T::Sig", align 8, !dbg !33
  %26 = load i64, i64* @"guard_epoch_T::Sig", align 8, !dbg !33
  %27 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !33, !tbaa !34
  %guardUpdated = icmp eq i64 %26, %27, !dbg !33
  tail call void @llvm.assume(i1 %guardUpdated), !dbg !33
  %28 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %cfp, i64 0, i32 1, !dbg !33
  %29 = load i64*, i64** %28, align 8, !dbg !33
  store i64 %selfRaw, i64* %29, align 8, !dbg !33, !tbaa !6
  %30 = getelementptr inbounds i64, i64* %29, i64 1, !dbg !33
  store i64 %25, i64* %30, align 8, !dbg !33, !tbaa !6
  %31 = getelementptr inbounds i64, i64* %30, i64 1, !dbg !33
  store i64* %31, i64** %28, align 8, !dbg !33
  %send = tail call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_extend, i64 0), !dbg !33
  store i64* getelementptr inbounds ([19 x i64], [19 x i64]* @iseqEncodedArray, i64 0, i64 9), i64** %8, align 8, !dbg !33, !tbaa !15
  %32 = load i64, i64* @guard_epoch_Foo, align 8, !dbg !37
  %33 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !37, !tbaa !34
  %needTakeSlowPath2 = icmp ne i64 %32, %33, !dbg !37
  br i1 %needTakeSlowPath2, label %34, label %35, !dbg !37, !prof !36

34:                                               ; preds = %24
  tail call void @const_recompute_Foo(), !dbg !37
  br label %35, !dbg !37

35:                                               ; preds = %24, %34
  %36 = load i64, i64* @guarded_const_Foo, align 8, !dbg !37
  %37 = load i64, i64* @guard_epoch_Foo, align 8, !dbg !37
  %38 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !37, !tbaa !34
  %guardUpdated3 = icmp eq i64 %37, %38, !dbg !37
  tail call void @llvm.assume(i1 %guardUpdated3), !dbg !37
  %stackFrame43 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Foo#3bar", align 8, !dbg !37
  %39 = tail call noalias nonnull i8* @ruby_xcalloc(i64 noundef 1, i64 noundef 64) #18, !dbg !37
  %40 = bitcast i8* %39 to i16*, !dbg !37
  %41 = load i16, i16* %40, align 8, !dbg !37
  %42 = and i16 %41, -384, !dbg !37
  %43 = or i16 %42, 65, !dbg !37
  store i16 %43, i16* %40, align 8, !dbg !37
  %44 = getelementptr inbounds i8, i8* %39, i64 8, !dbg !37
  %45 = bitcast i8* %44 to i32*, !dbg !37
  store i32 1, i32* %45, align 8, !dbg !37, !tbaa !38
  %46 = getelementptr inbounds i8, i8* %39, i64 12, !dbg !37
  %47 = bitcast i8* %46 to i32*, !dbg !37
  %48 = getelementptr inbounds i8, i8* %39, i64 28, !dbg !37
  %49 = bitcast i8* %48 to i32*, !dbg !37
  tail call void @llvm.memset.p0i8.i64(i8* nonnull align 4 %46, i8 0, i64 16, i1 false), !dbg !37
  store i32 1, i32* %49, align 4, !dbg !37, !tbaa !41
  %50 = getelementptr inbounds i8, i8* %39, i64 4, !dbg !37
  %51 = bitcast i8* %50 to i32*, !dbg !37
  store i32 2, i32* %51, align 4, !dbg !37, !tbaa !42
  %positional_table = alloca i64, i32 2, align 8, !dbg !37
  %rubyId_x = load i64, i64* @rubyIdPrecomputed_x, align 8, !dbg !37
  store i64 %rubyId_x, i64* %positional_table, align 8, !dbg !37
  %rubyId_blk = load i64, i64* @rubyIdPrecomputed_blk, align 8, !dbg !37
  %52 = getelementptr i64, i64* %positional_table, i32 1, !dbg !37
  store i64 %rubyId_blk, i64* %52, align 8, !dbg !37
  %53 = tail call noalias nonnull i8* @ruby_xmalloc2(i64 noundef 2, i64 noundef 8) #18, !dbg !37
  %54 = bitcast i64* %positional_table to i8*, !dbg !37
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* nocapture nonnull writeonly align 1 %53, i8* nocapture noundef nonnull readonly align 8 dereferenceable(16) %54, i64 noundef 16, i1 noundef false) #17, !dbg !37
  %55 = getelementptr inbounds i8, i8* %39, i64 32, !dbg !37
  %56 = bitcast i8* %55 to i8**, !dbg !37
  store i8* %53, i8** %56, align 8, !dbg !37, !tbaa !43
  tail call void @sorbet_vm_define_method(i64 %36, i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @str_bar, i64 0, i64 0), i64 (i32, i64*, i64, %struct.rb_control_frame_struct*, i8*)* noundef @"func_Foo#3bar", i8* nonnull %39, %struct.rb_iseq_struct* %stackFrame43, i1 noundef zeroext false) #17, !dbg !37
  %57 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !37, !tbaa !15
  %58 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %57, i64 0, i32 5, !dbg !37
  %59 = load i32, i32* %58, align 8, !dbg !37, !tbaa !29
  %60 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %57, i64 0, i32 6, !dbg !37
  %61 = load i32, i32* %60, align 4, !dbg !37, !tbaa !30
  %62 = xor i32 %61, -1, !dbg !37
  %63 = and i32 %62, %59, !dbg !37
  %64 = icmp eq i32 %63, 0, !dbg !37
  br i1 %64, label %rb_vm_check_ints.exit, label %65, !dbg !37, !prof !31

65:                                               ; preds = %35
  %66 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %57, i64 0, i32 8, !dbg !37
  %67 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %66, align 8, !dbg !37, !tbaa !32
  %68 = tail call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* %67, i32 noundef 0) #17, !dbg !37
  br label %rb_vm_check_ints.exit, !dbg !37

rb_vm_check_ints.exit:                            ; preds = %35, %65
  ret void
}

; Function Attrs: sspreq
define void @Init_block_type_checking() local_unnamed_addr #10 {
entry:
  %locals.i16.i = alloca i64, i32 0, align 8
  %locals.i14.i = alloca i64, i32 0, align 8
  %locals.i.i = alloca i64, i32 0, align 8
  %keywords.i = alloca i64, i32 2, align 8, !dbg !44
  %realpath = tail call i64 @sorbet_readRealpath()
  %0 = bitcast i64* %keywords.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 16, i8* nonnull %0)
  %1 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 noundef 16) #17
  store i64 %1, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %2 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([26 x i8], [26 x i8]* @"str_block in <top (required)>", i64 0, i64 0), i64 noundef 25) #17
  store i64 %2, i64* @"rubyIdPrecomputed_block in <top (required)>", align 8
  %3 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @str_new, i64 0, i64 0), i64 noundef 3) #17
  store i64 %3, i64* @rubyIdPrecomputed_new, align 8
  %4 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @str_bar, i64 0, i64 0), i64 noundef 3) #17
  store i64 %4, i64* @rubyIdPrecomputed_bar, align 8
  %5 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([2 x i8], [2 x i8]* @str_p, i64 0, i64 0), i64 noundef 1) #17
  store i64 %5, i64* @rubyIdPrecomputed_p, align 8
  %6 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([2 x i8], [2 x i8]* @"str_+", i64 0, i64 0), i64 noundef 1) #17
  %7 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([12 x i8], [12 x i8]* @"str_<class:Foo>", i64 0, i64 0), i64 noundef 11) #17
  store i64 %7, i64* @"rubyIdPrecomputed_<class:Foo>", align 8
  %8 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([21 x i8], [21 x i8]* @"str_block in <class:Foo>", i64 0, i64 0), i64 noundef 20) #17
  store i64 %8, i64* @"rubyIdPrecomputed_block in <class:Foo>", align 8
  %9 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([2 x i8], [2 x i8]* @str_x, i64 0, i64 0), i64 noundef 1) #17
  store i64 %9, i64* @rubyIdPrecomputed_x, align 8
  %10 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @str_blk, i64 0, i64 0), i64 noundef 3) #17
  store i64 %10, i64* @rubyIdPrecomputed_blk, align 8
  %11 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([5 x i8], [5 x i8]* @str_proc, i64 0, i64 0), i64 noundef 4) #17
  store i64 %11, i64* @rubyIdPrecomputed_proc, align 8
  %12 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([8 x i8], [8 x i8]* @str_returns, i64 0, i64 0), i64 noundef 7) #17
  store i64 %12, i64* @rubyIdPrecomputed_returns, align 8
  %13 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([7 x i8], [7 x i8]* @str_params, i64 0, i64 0), i64 noundef 6) #17
  store i64 %13, i64* @rubyIdPrecomputed_params, align 8
  %14 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([7 x i8], [7 x i8]* @str_extend, i64 0, i64 0), i64 noundef 6) #17
  store i64 %14, i64* @rubyIdPrecomputed_extend, align 8
  %15 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([7 x i8], [7 x i8]* @str_normal, i64 0, i64 0), i64 noundef 6) #17
  %16 = tail call i64 @sorbet_vm_fstring_new(i8* noundef getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 noundef 16) #17
  tail call void @rb_gc_register_mark_object(i64 %16) #17
  store i64 %16, i64* @"rubyStrFrozen_<top (required)>", align 8
  %17 = tail call i64 @sorbet_vm_fstring_new(i8* noundef getelementptr inbounds ([46 x i8], [46 x i8]* @"str_test/testdata/compiler/block_type_checking.rb", i64 0, i64 0), i64 noundef 45) #17
  tail call void @rb_gc_register_mark_object(i64 %17) #17
  store i64 %17, i64* @"rubyStrFrozen_test/testdata/compiler/block_type_checking.rb", align 8
  tail call void @sorbet_initLineNumberInfo(%struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef getelementptr inbounds ([19 x i64], [19 x i64]* @iseqEncodedArray, i32 0, i32 0), i32 noundef 19)
  %"rubyId_<top (required)>.i.i" = load i64, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %"rubyStr_<top (required)>.i.i" = load i64, i64* @"rubyStrFrozen_<top (required)>", align 8
  %"rubyStr_test/testdata/compiler/block_type_checking.rb.i.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/block_type_checking.rb", align 8
  %18 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_<top (required)>.i.i", i64 %"rubyId_<top (required)>.i.i", i64 %"rubyStr_test/testdata/compiler/block_type_checking.rb.i.i", i64 %realpath, %struct.rb_iseq_struct* noundef null, i32 noundef 0, i32 noundef 5, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef nonnull %locals.i.i, i32 noundef 0, i32 noundef 2)
  store %struct.rb_iseq_struct* %18, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_<root>.17<static-init>$152", align 8
  %19 = call i64 @sorbet_vm_fstring_new(i8* noundef getelementptr inbounds ([26 x i8], [26 x i8]* @"str_block in <top (required)>", i64 0, i64 0), i64 noundef 25) #17
  call void @rb_gc_register_mark_object(i64 %19) #17
  %stackFrame.i.i = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_<root>.17<static-init>$152", align 8
  %"rubyId_block in <top (required)>.i.i" = load i64, i64* @"rubyIdPrecomputed_block in <top (required)>", align 8
  %"rubyStr_test/testdata/compiler/block_type_checking.rb.i12.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/block_type_checking.rb", align 8
  %20 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 %19, i64 %"rubyId_block in <top (required)>.i.i", i64 %"rubyStr_test/testdata/compiler/block_type_checking.rb.i12.i", i64 %realpath, %struct.rb_iseq_struct* %stackFrame.i.i, i32 noundef 2, i32 noundef 5, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef null, i32 noundef 0, i32 noundef 2)
  store %struct.rb_iseq_struct* %20, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_<root>.17<static-init>$152$block_1", align 8
  %rubyId_new.i = load i64, i64* @rubyIdPrecomputed_new, align 8, !dbg !46
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_new, i64 %rubyId_new.i, i32 noundef 16, i32 noundef 0, i32 noundef 0, i64* noundef null), !dbg !46
  %rubyId_bar.i = load i64, i64* @rubyIdPrecomputed_bar, align 8, !dbg !46
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_bar, i64 %rubyId_bar.i, i32 noundef 16, i32 noundef 1, i32 noundef 0, i64* noundef null), !dbg !46
  %rubyId_p.i = load i64, i64* @rubyIdPrecomputed_p, align 8, !dbg !47
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_p, i64 %rubyId_p.i, i32 noundef 20, i32 noundef 1, i32 noundef 0, i64* noundef null), !dbg !47
  %21 = call i64 @sorbet_vm_fstring_new(i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @str_bar, i64 0, i64 0), i64 noundef 3) #17
  call void @rb_gc_register_mark_object(i64 %21) #17
  %rubyId_bar.i.i = load i64, i64* @rubyIdPrecomputed_bar, align 8
  %"rubyStr_test/testdata/compiler/block_type_checking.rb.i13.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/block_type_checking.rb", align 8
  %22 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 %21, i64 %rubyId_bar.i.i, i64 %"rubyStr_test/testdata/compiler/block_type_checking.rb.i13.i", i64 %realpath, %struct.rb_iseq_struct* noundef null, i32 noundef 1, i32 noundef 9, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef nonnull %locals.i14.i, i32 noundef 0, i32 noundef 2)
  store %struct.rb_iseq_struct* %22, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Foo#3bar", align 8
  %23 = call i64 @sorbet_vm_fstring_new(i8* noundef getelementptr inbounds ([12 x i8], [12 x i8]* @"str_<class:Foo>", i64 0, i64 0), i64 noundef 11) #17
  call void @rb_gc_register_mark_object(i64 %23) #17
  %"rubyId_<class:Foo>.i.i" = load i64, i64* @"rubyIdPrecomputed_<class:Foo>", align 8
  %"rubyStr_test/testdata/compiler/block_type_checking.rb.i15.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/block_type_checking.rb", align 8
  %24 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 %23, i64 %"rubyId_<class:Foo>.i.i", i64 %"rubyStr_test/testdata/compiler/block_type_checking.rb.i15.i", i64 %realpath, %struct.rb_iseq_struct* noundef null, i32 noundef 3, i32 noundef 5, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef nonnull %locals.i16.i, i32 noundef 0, i32 noundef 4)
  store %struct.rb_iseq_struct* %24, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Foo.13<static-init>", align 8
  %25 = call i64 @sorbet_vm_fstring_new(i8* noundef getelementptr inbounds ([21 x i8], [21 x i8]* @"str_block in <class:Foo>", i64 0, i64 0), i64 noundef 20) #17
  call void @rb_gc_register_mark_object(i64 %25) #17
  %stackFrame.i17.i = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Foo.13<static-init>", align 8
  %"rubyId_block in <class:Foo>.i.i" = load i64, i64* @"rubyIdPrecomputed_block in <class:Foo>", align 8
  %"rubyStr_test/testdata/compiler/block_type_checking.rb.i18.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/block_type_checking.rb", align 8
  %26 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 %25, i64 %"rubyId_block in <class:Foo>.i.i", i64 %"rubyStr_test/testdata/compiler/block_type_checking.rb.i18.i", i64 %realpath, %struct.rb_iseq_struct* %stackFrame.i17.i, i32 noundef 2, i32 noundef 5, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef null, i32 noundef 0, i32 noundef 4)
  store %struct.rb_iseq_struct* %26, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Foo.13<static-init>$block_1", align 8
  %rubyId_proc.i = load i64, i64* @rubyIdPrecomputed_proc, align 8, !dbg !48
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_proc, i64 %rubyId_proc.i, i32 noundef 16, i32 noundef 0, i32 noundef 0, i64* noundef null), !dbg !48
  %rubyId_returns.i = load i64, i64* @rubyIdPrecomputed_returns, align 8, !dbg !48
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_returns, i64 %rubyId_returns.i, i32 noundef 16, i32 noundef 1, i32 noundef 0, i64* noundef null), !dbg !48
  %rubyId_params.i = load i64, i64* @rubyIdPrecomputed_params, align 8, !dbg !44
  %rubyId_x.i = load i64, i64* @rubyIdPrecomputed_x, align 8, !dbg !44
  %27 = call i64 @rb_id2sym(i64 %rubyId_x.i) #19, !dbg !44
  store i64 %27, i64* %keywords.i, align 8, !dbg !44
  %rubyId_blk.i = load i64, i64* @rubyIdPrecomputed_blk, align 8, !dbg !44
  %28 = call i64 @rb_id2sym(i64 %rubyId_blk.i) #19, !dbg !44
  %29 = getelementptr i64, i64* %keywords.i, i32 1, !dbg !44
  store i64 %28, i64* %29, align 8, !dbg !44
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_params, i64 %rubyId_params.i, i32 noundef 68, i32 noundef 2, i32 noundef 2, i64* noundef nonnull align 8 %keywords.i), !dbg !44
  %rubyId_returns8.i = load i64, i64* @rubyIdPrecomputed_returns, align 8, !dbg !44
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_returns.1, i64 %rubyId_returns8.i, i32 noundef 16, i32 noundef 1, i32 noundef 0, i64* noundef null), !dbg !44
  %rubyId_extend.i = load i64, i64* @rubyIdPrecomputed_extend, align 8, !dbg !33
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_extend, i64 %rubyId_extend.i, i32 noundef 20, i32 noundef 1, i32 noundef 0, i64* noundef null), !dbg !33
  call void @llvm.lifetime.end.p0i8(i64 16, i8* nonnull %0)
  %30 = load %struct.rb_vm_struct*, %struct.rb_vm_struct** @ruby_current_vm_ptr, align 8, !tbaa !15
  %31 = getelementptr inbounds %struct.rb_vm_struct, %struct.rb_vm_struct* %30, i64 0, i32 18
  %32 = load i64, i64* %31, align 8, !tbaa !49
  %33 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !15
  %34 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %33, i64 0, i32 2
  %35 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %34, align 8, !tbaa !17
  %stackFrame.i = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_<root>.17<static-init>$152", align 8
  %36 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %35, i64 0, i32 2
  store %struct.rb_iseq_struct* %stackFrame.i, %struct.rb_iseq_struct** %36, align 8, !tbaa !21
  %37 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %35, i64 0, i32 4
  %38 = load i64*, i64** %37, align 8, !tbaa !23
  %39 = load i64, i64* %38, align 8, !tbaa !6
  %40 = and i64 %39, -33
  store i64 %40, i64* %38, align 8, !tbaa !6
  call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* %33, %struct.rb_control_frame_struct* %35, %struct.rb_iseq_struct* %stackFrame.i) #17
  %41 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %35, i64 0, i32 0
  store i64* getelementptr inbounds ([19 x i64], [19 x i64]* @iseqEncodedArray, i64 0, i64 5), i64** %41, align 8, !dbg !57, !tbaa !15
  %42 = load i64, i64* @rb_cObject, align 8, !dbg !58
  %43 = call i64 @rb_define_class(i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @str_Foo, i64 0, i64 0), i64 %42) #17, !dbg !58
  %44 = call %struct.rb_control_frame_struct* @sorbet_pushStaticInitFrame(i64 %43) #17, !dbg !58
  call fastcc void @"func_Foo.13<static-init>L62"(i64 %43, %struct.rb_control_frame_struct* %44) #17, !dbg !58
  call void @sorbet_popFrame() #17, !dbg !58
  store i64* getelementptr inbounds ([19 x i64], [19 x i64]* @iseqEncodedArray, i64 0, i64 15), i64** %41, align 8, !dbg !58, !tbaa !15
  %45 = load i64, i64* @guard_epoch_Foo, align 8, !dbg !46
  %46 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !46, !tbaa !34
  %needTakeSlowPath = icmp ne i64 %45, %46, !dbg !46
  br i1 %needTakeSlowPath, label %47, label %48, !dbg !46, !prof !36

47:                                               ; preds = %entry
  call void @const_recompute_Foo(), !dbg !46
  br label %48, !dbg !46

48:                                               ; preds = %entry, %47
  %49 = load i64, i64* @guarded_const_Foo, align 8, !dbg !46
  %50 = load i64, i64* @guard_epoch_Foo, align 8, !dbg !46
  %51 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !46, !tbaa !34
  %guardUpdated = icmp eq i64 %50, %51, !dbg !46
  call void @llvm.assume(i1 %guardUpdated), !dbg !46
  %52 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %35, i64 0, i32 1, !dbg !46
  %53 = load i64*, i64** %52, align 8, !dbg !46
  store i64 %49, i64* %53, align 8, !dbg !46, !tbaa !6
  %54 = getelementptr inbounds i64, i64* %53, i64 1, !dbg !46
  store i64* %54, i64** %52, align 8, !dbg !46
  %send = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_new, i64 0), !dbg !46
  %55 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %35, i64 0, i32 1, !dbg !46
  %56 = load i64*, i64** %55, align 8, !dbg !46
  store i64 %send, i64* %56, align 8, !dbg !46, !tbaa !6
  %57 = getelementptr inbounds i64, i64* %56, i64 1, !dbg !46
  store i64 11, i64* %57, align 8, !dbg !46, !tbaa !6
  %58 = getelementptr inbounds i64, i64* %57, i64 1, !dbg !46
  store i64* %58, i64** %55, align 8, !dbg !46
  %59 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !46, !tbaa !15
  %60 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %59, i64 0, i32 2, !dbg !46
  %61 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %60, align 8, !dbg !46, !tbaa !17
  %62 = call %struct.vm_ifunc* @rb_vm_ifunc_new(i64 (i64, i64, i32, i64*, i64)* @"func_<root>.17<static-init>$152$block_1", i8* null, i32 0, i32 0) #17, !dbg !46
  %63 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %61, i64 0, i32 3, !dbg !46
  %64 = bitcast i64* %63 to %struct.rb_captured_block*, !dbg !46
  %65 = getelementptr inbounds i64, i64* %63, i64 2, !dbg !46
  %66 = bitcast i64* %65 to %struct.vm_ifunc**, !dbg !46
  store %struct.vm_ifunc* %62, %struct.vm_ifunc** %66, align 8, !dbg !46, !tbaa !59
  %67 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %59, i64 0, i32 17, !dbg !46
  store i64 0, i64* %67, align 8, !dbg !46, !tbaa !60
  call void @llvm.experimental.noalias.scope.decl(metadata !61) #17, !dbg !46
  %68 = ptrtoint %struct.rb_captured_block* %64 to i64, !dbg !46
  %69 = or i64 %68, 3, !dbg !46
  %70 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_bar, i64 %69) #17, !dbg !46
  store i64* getelementptr inbounds ([19 x i64], [19 x i64]* @iseqEncodedArray, i64 0, i64 18), i64** %41, align 8, !dbg !46, !tbaa !15
  %71 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %35, i64 0, i32 1, !dbg !47
  %72 = load i64*, i64** %71, align 8, !dbg !47
  store i64 %32, i64* %72, align 8, !dbg !47, !tbaa !6
  %73 = getelementptr inbounds i64, i64* %72, i64 1, !dbg !47
  store i64 %70, i64* %73, align 8, !dbg !47, !tbaa !6
  %74 = getelementptr inbounds i64, i64* %73, i64 1, !dbg !47
  store i64* %74, i64** %71, align 8, !dbg !47
  %send2 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_p, i64 0), !dbg !47
  ret void
}

; Function Attrs: nounwind sspreq uwtable
define i64 @"func_Foo#3bar"(i32 %argc, i64* nocapture readonly %argArray, i64 %selfRaw, %struct.rb_control_frame_struct* nonnull align 8 dereferenceable(8) %cfp, i8* nocapture nofree readnone %0) #9 !dbg !64 {
functionEntryInitializers:
  %1 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %cfp, i64 0, i32 0
  store i64* getelementptr inbounds ([19 x i64], [19 x i64]* @iseqEncodedArray, i64 0, i64 9), i64** %1, align 8, !tbaa !15
  %tooManyArgs = icmp ugt i32 %argc, 1, !dbg !65
  %tooFewArgs = icmp ult i32 %argc, 1, !dbg !65
  %or.cond = or i1 %tooManyArgs, %tooFewArgs, !dbg !65
  br i1 %or.cond, label %argCountFailBlock, label %fillRequiredArgs, !dbg !65, !prof !66

argCountFailBlock:                                ; preds = %functionEntryInitializers
  tail call void @sorbet_raiseArity(i32 %argc, i32 noundef 1, i32 noundef 1) #20, !dbg !65
  unreachable, !dbg !65

fillRequiredArgs:                                 ; preds = %functionEntryInitializers
  %rawArg_x = load i64, i64* %argArray, align 8, !dbg !65
  %2 = tail call i32 @rb_block_given_p() #17, !dbg !65
  %3 = icmp eq i32 %2, 0, !dbg !65
  br i1 %3, label %sorbet_getMethodBlockAsProc.exit, label %4, !dbg !65

4:                                                ; preds = %fillRequiredArgs
  %5 = tail call i64 @rb_block_proc() #17, !dbg !65
  br label %sorbet_getMethodBlockAsProc.exit, !dbg !65

sorbet_getMethodBlockAsProc.exit:                 ; preds = %fillRequiredArgs, %4
  %6 = phi i64 [ %5, %4 ], [ 8, %fillRequiredArgs ], !dbg !65
  store i64* getelementptr inbounds ([19 x i64], [19 x i64]* @iseqEncodedArray, i64 0, i64 9), i64** %1, align 8, !dbg !67, !tbaa !15
  %7 = and i64 %rawArg_x, 1, !dbg !68
  %8 = icmp eq i64 %7, 0, !dbg !68
  br i1 %8, label %9, label %typeTestSuccess, !dbg !68, !prof !69

9:                                                ; preds = %sorbet_getMethodBlockAsProc.exit
  %10 = and i64 %rawArg_x, 7, !dbg !68
  %11 = icmp ne i64 %10, 0, !dbg !68
  %12 = and i64 %rawArg_x, -9, !dbg !68
  %13 = icmp eq i64 %12, 0, !dbg !68
  %14 = or i1 %11, %13, !dbg !68
  br i1 %14, label %codeRepl25, label %sorbet_isa_Integer.exit, !dbg !68

sorbet_isa_Integer.exit:                          ; preds = %9
  %15 = inttoptr i64 %rawArg_x to %struct.iseq_inline_iv_cache_entry*, !dbg !68
  %16 = getelementptr inbounds %struct.iseq_inline_iv_cache_entry, %struct.iseq_inline_iv_cache_entry* %15, i64 0, i32 0, !dbg !68
  %17 = load i64, i64* %16, align 8, !dbg !68, !tbaa !70
  %18 = and i64 %17, 31, !dbg !68
  %19 = icmp eq i64 %18, 10, !dbg !68
  br i1 %19, label %typeTestSuccess, label %codeRepl25, !dbg !68, !prof !31

typeTestSuccess:                                  ; preds = %sorbet_getMethodBlockAsProc.exit, %sorbet_isa_Integer.exit
  %20 = tail call i32 @rb_block_given_p() #17, !dbg !72
  %21 = icmp ne i32 %20, 0, !dbg !72
  br i1 %21, label %typeTestSuccess7, label %codeRepl24, !dbg !72, !prof !31

codeRepl25:                                       ; preds = %9, %sorbet_isa_Integer.exit
  tail call fastcc void @"func_Foo#3bar.cold.3"(i64 %rawArg_x) #21, !dbg !68
  unreachable

typeTestSuccess7:                                 ; preds = %typeTestSuccess
  store i64* getelementptr inbounds ([19 x i64], [19 x i64]* @iseqEncodedArray, i64 0, i64 10), i64** %1, align 8, !dbg !72, !tbaa !15
  %rawBlockSendResult = tail call i64 @sorbet_vm_callBlock(%struct.rb_control_frame_struct* nonnull %cfp, i32 noundef 0, i64* noundef null, i32 noundef 0), !dbg !73
  store i64* getelementptr inbounds ([19 x i64], [19 x i64]* @iseqEncodedArray, i64 0, i64 11), i64** %1, align 8, !dbg !73, !tbaa !15
  tail call void @llvm.experimental.noalias.scope.decl(metadata !74), !dbg !77
  %22 = and i64 %rawArg_x, 1, !dbg !77
  %23 = and i64 %22, %rawBlockSendResult, !dbg !77
  %24 = icmp eq i64 %23, 0, !dbg !77
  br i1 %24, label %34, label %25, !dbg !77, !prof !66

25:                                               ; preds = %typeTestSuccess7
  %26 = add nsw i64 %rawBlockSendResult, -1, !dbg !77
  %27 = tail call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %rawArg_x, i64 %26) #22, !dbg !77
  %28 = extractvalue { i64, i1 } %27, 1, !dbg !77
  %29 = extractvalue { i64, i1 } %27, 0, !dbg !77
  br i1 %28, label %30, label %sorbet_rb_int_plus.exit, !dbg !77

30:                                               ; preds = %25
  %31 = ashr i64 %29, 1, !dbg !77
  %32 = xor i64 %31, -9223372036854775808, !dbg !77
  %33 = tail call i64 @rb_int2big(i64 %32) #17, !dbg !77, !noalias !74
  br label %sorbet_rb_int_plus.exit, !dbg !77

34:                                               ; preds = %typeTestSuccess7
  %35 = tail call i64 @sorbet_rb_int_plus_slowpath(i64 %rawArg_x, i64 %rawBlockSendResult) #17, !dbg !77, !noalias !74
  br label %sorbet_rb_int_plus.exit, !dbg !77

sorbet_rb_int_plus.exit:                          ; preds = %30, %25, %34
  %36 = phi i64 [ %35, %34 ], [ %33, %30 ], [ %29, %25 ], !dbg !77
  %37 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !77, !tbaa !15
  %38 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %37, i64 0, i32 5, !dbg !77
  %39 = load i32, i32* %38, align 8, !dbg !77, !tbaa !29
  %40 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %37, i64 0, i32 6, !dbg !77
  %41 = load i32, i32* %40, align 4, !dbg !77, !tbaa !30
  %42 = xor i32 %41, -1, !dbg !77
  %43 = and i32 %42, %39, !dbg !77
  %44 = icmp eq i32 %43, 0, !dbg !77
  br i1 %44, label %rb_vm_check_ints.exit, label %45, !dbg !77, !prof !31

45:                                               ; preds = %sorbet_rb_int_plus.exit
  %46 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %37, i64 0, i32 8, !dbg !77
  %47 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %46, align 8, !dbg !77, !tbaa !32
  %48 = tail call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* %47, i32 noundef 0) #17, !dbg !77
  br label %rb_vm_check_ints.exit, !dbg !77

rb_vm_check_ints.exit:                            ; preds = %sorbet_rb_int_plus.exit, %45
  %49 = and i64 %36, 1
  %50 = icmp eq i64 %49, 0
  br i1 %50, label %51, label %typeTestSuccess17, !prof !69

51:                                               ; preds = %rb_vm_check_ints.exit
  %52 = and i64 %36, 7
  %53 = icmp ne i64 %52, 0
  %54 = and i64 %36, -9
  %55 = icmp eq i64 %54, 0
  %56 = or i1 %53, %55
  br i1 %56, label %codeRepl, label %sorbet_isa_Integer.exit26

sorbet_isa_Integer.exit26:                        ; preds = %51
  %57 = inttoptr i64 %36 to %struct.iseq_inline_iv_cache_entry*
  %58 = getelementptr inbounds %struct.iseq_inline_iv_cache_entry, %struct.iseq_inline_iv_cache_entry* %57, i64 0, i32 0
  %59 = load i64, i64* %58, align 8, !tbaa !70
  %60 = and i64 %59, 31
  %61 = icmp eq i64 %60, 10
  br i1 %61, label %typeTestSuccess17, label %codeRepl, !prof !31

codeRepl24:                                       ; preds = %typeTestSuccess
  tail call fastcc void @"func_Foo#3bar.cold.2"(i64 %6) #21, !dbg !72
  unreachable

typeTestSuccess17:                                ; preds = %rb_vm_check_ints.exit, %sorbet_isa_Integer.exit26
  ret i64 %36

codeRepl:                                         ; preds = %51, %sorbet_isa_Integer.exit26
  tail call fastcc void @"func_Foo#3bar.cold.1"(i64 %36) #21, !dbg !67
  unreachable
}

; Function Attrs: ssp
define internal i64 @"func_Foo.13<static-init>L62$block_1"(i64 %firstYieldArgRaw, i64 %localsOffset, i32 %argc, i64* nocapture nofree readnone %argArray, i64 %blockArg) #11 !dbg !45 {
functionEntryInitializers:
  %0 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !15
  %1 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %0, i64 0, i32 2
  %2 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %1, align 8, !tbaa !17
  %3 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 3
  %4 = load i64, i64* %3, align 8, !tbaa !78
  %stackFrame = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Foo.13<static-init>$block_1", align 8
  %5 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 2
  store %struct.rb_iseq_struct* %stackFrame, %struct.rb_iseq_struct** %5, align 8, !tbaa !21
  %6 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 4
  %7 = load i64*, i64** %6, align 8, !tbaa !23
  %8 = load i64, i64* %7, align 8, !tbaa !6
  %9 = and i64 %8, -129
  store i64 %9, i64* %7, align 8, !tbaa !6
  %10 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 0
  store i64* getelementptr inbounds ([19 x i64], [19 x i64]* @iseqEncodedArray, i64 0, i64 8), i64** %10, align 8, !tbaa !15
  %11 = load i64, i64* @guard_epoch_T, align 8, !dbg !48
  %12 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !48, !tbaa !34
  %needTakeSlowPath = icmp ne i64 %11, %12, !dbg !48
  br i1 %needTakeSlowPath, label %13, label %14, !dbg !48, !prof !36

13:                                               ; preds = %functionEntryInitializers
  tail call void @const_recompute_T(), !dbg !48
  br label %14, !dbg !48

14:                                               ; preds = %functionEntryInitializers, %13
  %15 = load i64, i64* @guarded_const_T, align 8, !dbg !48
  %16 = load i64, i64* @guard_epoch_T, align 8, !dbg !48
  %17 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !48, !tbaa !34
  %guardUpdated = icmp eq i64 %16, %17, !dbg !48
  tail call void @llvm.assume(i1 %guardUpdated), !dbg !48
  %18 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 1, !dbg !48
  %19 = load i64*, i64** %18, align 8, !dbg !48
  store i64 %15, i64* %19, align 8, !dbg !48, !tbaa !6
  %20 = getelementptr inbounds i64, i64* %19, i64 1, !dbg !48
  store i64* %20, i64** %18, align 8, !dbg !48
  %send = tail call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_proc, i64 0), !dbg !48
  %21 = load i64, i64* @rb_cInteger, align 8, !dbg !48
  %22 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 1, !dbg !48
  %23 = load i64*, i64** %22, align 8, !dbg !48
  store i64 %send, i64* %23, align 8, !dbg !48, !tbaa !6
  %24 = getelementptr inbounds i64, i64* %23, i64 1, !dbg !48
  store i64 %21, i64* %24, align 8, !dbg !48, !tbaa !6
  %25 = getelementptr inbounds i64, i64* %24, i64 1, !dbg !48
  store i64* %25, i64** %22, align 8, !dbg !48
  %send41 = tail call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_returns, i64 0), !dbg !48
  %26 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 1, !dbg !44
  %27 = load i64*, i64** %26, align 8, !dbg !44
  store i64 %4, i64* %27, align 8, !dbg !44, !tbaa !6
  %28 = getelementptr inbounds i64, i64* %27, i64 1, !dbg !44
  store i64 %21, i64* %28, align 8, !dbg !44, !tbaa !6
  %29 = getelementptr inbounds i64, i64* %28, i64 1, !dbg !44
  store i64 %send41, i64* %29, align 8, !dbg !44, !tbaa !6
  %30 = getelementptr inbounds i64, i64* %29, i64 1, !dbg !44
  store i64* %30, i64** %26, align 8, !dbg !44
  %send43 = tail call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_params, i64 0), !dbg !44
  %31 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 1, !dbg !44
  %32 = load i64*, i64** %31, align 8, !dbg !44
  store i64 %send43, i64* %32, align 8, !dbg !44, !tbaa !6
  %33 = getelementptr inbounds i64, i64* %32, i64 1, !dbg !44
  store i64 %21, i64* %33, align 8, !dbg !44, !tbaa !6
  %34 = getelementptr inbounds i64, i64* %33, i64 1, !dbg !44
  store i64* %34, i64** %31, align 8, !dbg !44
  %send45 = tail call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_returns.1, i64 0), !dbg !44
  ret i64 %send45, !dbg !79
}

; Function Attrs: inaccessiblememonly nofree nosync nounwind willreturn
declare void @llvm.experimental.noalias.scope.decl(metadata) #12

; Function Attrs: argmemonly nofree nosync nounwind willreturn writeonly
declare void @llvm.memset.p0i8.i64(i8* nocapture writeonly, i8, i64, i1 immarg) #13

; Function Attrs: argmemonly nofree nosync nounwind willreturn
declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #6

; Function Attrs: argmemonly nofree nosync nounwind willreturn
declare void @llvm.lifetime.end.p0i8(i64 immarg, i8* nocapture) #6

; Function Attrs: cold minsize noreturn nounwind sspreq uwtable
define internal fastcc void @"func_Foo#3bar.cold.1"(i64 %0) unnamed_addr #14 !dbg !80 {
newFuncRoot:
  tail call void @sorbet_cast_failure(i64 %0, i8* noundef getelementptr inbounds ([13 x i8], [13 x i8]* @"str_Return value", i64 0, i64 0), i8* noundef getelementptr inbounds ([8 x i8], [8 x i8]* @str_Integer, i64 0, i64 0)) #20
  unreachable
}

; Function Attrs: cold minsize noreturn nounwind sspreq uwtable
define internal fastcc void @"func_Foo#3bar.cold.2"(i64 %0) unnamed_addr #14 !dbg !82 {
newFuncRoot:
  tail call void @sorbet_cast_failure(i64 %0, i8* noundef getelementptr inbounds ([16 x i8], [16 x i8]* @"str_Parameter 'blk'", i64 0, i64 0), i8* noundef getelementptr inbounds ([24 x i8], [24 x i8]* @"str_T.proc.returns(Integer)", i64 0, i64 0)) #20, !dbg !83
  unreachable, !dbg !83
}

; Function Attrs: cold minsize noreturn nounwind sspreq uwtable
define internal fastcc void @"func_Foo#3bar.cold.3"(i64 %rawArg_x) unnamed_addr #14 !dbg !84 {
newFuncRoot:
  tail call void @sorbet_cast_failure(i64 %rawArg_x, i8* noundef getelementptr inbounds ([14 x i8], [14 x i8]* @"str_Parameter 'x'", i64 0, i64 0), i8* noundef getelementptr inbounds ([8 x i8], [8 x i8]* @str_Integer, i64 0, i64 0)) #20, !dbg !85
  unreachable, !dbg !85
}

; Function Attrs: nofree nosync nounwind willreturn
declare void @llvm.assume(i1 noundef) #15

; Function Attrs: ssp
define linkonce void @"const_recompute_T::Sig"() local_unnamed_addr #11 {
  %1 = tail call i64 @sorbet_getConstant(i8* getelementptr inbounds ([7 x i8], [7 x i8]* @"str_T::Sig", i64 0, i64 0), i64 6)
  store i64 %1, i64* @"guarded_const_T::Sig", align 8
  %2 = load i64, i64* @ruby_vm_global_constant_state, align 8, !tbaa !34
  store i64 %2, i64* @"guard_epoch_T::Sig", align 8
  ret void
}

; Function Attrs: ssp
define linkonce void @const_recompute_Foo() local_unnamed_addr #11 {
  %1 = tail call i64 @sorbet_getConstant(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_Foo, i64 0, i64 0), i64 3)
  store i64 %1, i64* @guarded_const_Foo, align 8
  %2 = load i64, i64* @ruby_vm_global_constant_state, align 8, !tbaa !34
  store i64 %2, i64* @guard_epoch_Foo, align 8
  ret void
}

; Function Attrs: ssp
define linkonce void @const_recompute_T() local_unnamed_addr #11 {
  %1 = tail call i64 @sorbet_getConstant(i8* getelementptr inbounds ([2 x i8], [2 x i8]* @str_T, i64 0, i64 0), i64 1)
  store i64 %1, i64* @guarded_const_T, align 8
  %2 = load i64, i64* @ruby_vm_global_constant_state, align 8, !tbaa !34
  store i64 %2, i64* @guard_epoch_T, align 8
  ret void
}

attributes #0 = { nounwind readnone willreturn "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #1 = { cold noreturn "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #2 = { noreturn "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #3 = { "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #4 = { nofree nosync nounwind readnone speculatable willreturn }
attributes #5 = { allocsize(0,1) "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #6 = { argmemonly nofree nosync nounwind willreturn }
attributes #7 = { nounwind ssp uwtable "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #8 = { nofree nosync nounwind ssp willreturn }
attributes #9 = { nounwind sspreq uwtable }
attributes #10 = { sspreq }
attributes #11 = { ssp }
attributes #12 = { inaccessiblememonly nofree nosync nounwind willreturn }
attributes #13 = { argmemonly nofree nosync nounwind willreturn writeonly }
attributes #14 = { cold minsize noreturn nounwind sspreq uwtable }
attributes #15 = { nofree nosync nounwind willreturn }
attributes #16 = { noreturn nounwind }
attributes #17 = { nounwind }
attributes #18 = { nounwind allocsize(0,1) }
attributes #19 = { nounwind readnone willreturn }
attributes #20 = { noreturn }
attributes #21 = { noinline }
attributes #22 = { nounwind willreturn }

!llvm.module.flags = !{!0, !1, !2}
!llvm.dbg.cu = !{!3}

!0 = !{i32 2, !"Debug Info Version", i32 3}
!1 = !{i32 4, !"cf-protection-return", i32 1}
!2 = !{i32 4, !"cf-protection-branch", i32 1}
!3 = distinct !DICompileUnit(language: DW_LANG_C, file: !4, producer: "Sorbet LLVM", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, enums: !5)
!4 = !DIFile(filename: "test/testdata/compiler/block_type_checking.rb", directory: ".")
!5 = !{}
!6 = !{!7, !7, i64 0}
!7 = !{!"long", !8, i64 0}
!8 = !{!"omnipotent char", !9, i64 0}
!9 = !{!"Simple C/C++ TBAA"}
!10 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.17<static-init>$152$block_1", scope: !11, file: !4, line: 5, type: !12, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !3, retainedNodes: !5)
!11 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.17<static-init>$152", scope: null, file: !4, line: 5, type: !12, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !3, retainedNodes: !5)
!12 = !DISubroutineType(types: !13)
!13 = !{!14}
!14 = !DIBasicType(name: "VALUE", size: 64, encoding: DW_ATE_signed)
!15 = !{!16, !16, i64 0}
!16 = !{!"any pointer", !8, i64 0}
!17 = !{!18, !16, i64 16}
!18 = !{!"rb_execution_context_struct", !16, i64 0, !7, i64 8, !16, i64 16, !16, i64 24, !16, i64 32, !19, i64 40, !19, i64 44, !16, i64 48, !16, i64 56, !16, i64 64, !7, i64 72, !7, i64 80, !16, i64 88, !7, i64 96, !16, i64 104, !16, i64 112, !7, i64 120, !7, i64 128, !8, i64 136, !8, i64 137, !7, i64 144, !20, i64 152}
!19 = !{!"int", !8, i64 0}
!20 = !{!"", !16, i64 0, !16, i64 8, !7, i64 16, !8, i64 24}
!21 = !{!22, !16, i64 16}
!22 = !{!"rb_control_frame_struct", !16, i64 0, !16, i64 8, !16, i64 16, !7, i64 24, !16, i64 32, !16, i64 40, !16, i64 48}
!23 = !{!22, !16, i64 32}
!24 = !DILocation(line: 16, column: 3, scope: !10)
!25 = !DILocation(line: 15, column: 10, scope: !10)
!26 = distinct !DISubprogram(name: "Foo.<static-init>", linkageName: "func_Foo.13<static-init>L62", scope: null, file: !4, line: 5, type: !12, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !3, retainedNodes: !5)
!27 = !DILocation(line: 0, scope: !26)
!28 = !DILocation(line: 8, column: 3, scope: !26)
!29 = !{!18, !19, i64 40}
!30 = !{!18, !19, i64 44}
!31 = !{!"branch_weights", i32 2000, i32 1}
!32 = !{!18, !16, i64 56}
!33 = !DILocation(line: 6, column: 3, scope: !26)
!34 = !{!35, !35, i64 0}
!35 = !{!"long long", !8, i64 0}
!36 = !{!"branch_weights", i32 1, i32 10000}
!37 = !DILocation(line: 9, column: 3, scope: !26)
!38 = !{!39, !19, i64 8}
!39 = !{!"rb_sorbet_param_struct", !40, i64 0, !19, i64 4, !19, i64 8, !19, i64 12, !19, i64 16, !19, i64 20, !19, i64 24, !19, i64 28, !16, i64 32, !19, i64 40, !19, i64 44, !19, i64 48, !19, i64 52, !16, i64 56}
!40 = !{!"", !19, i64 0, !19, i64 0, !19, i64 0, !19, i64 0, !19, i64 0, !19, i64 0, !19, i64 0, !19, i64 0, !19, i64 1, !19, i64 1}
!41 = !{!39, !19, i64 28}
!42 = !{!39, !19, i64 4}
!43 = !{!39, !16, i64 32}
!44 = !DILocation(line: 8, column: 8, scope: !45)
!45 = distinct !DISubprogram(name: "Foo.<static-init>", linkageName: "func_Foo.13<static-init>L62$block_1", scope: !26, file: !4, line: 5, type: !12, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !3, retainedNodes: !5)
!46 = !DILocation(line: 15, column: 10, scope: !11)
!47 = !DILocation(line: 18, column: 1, scope: !11)
!48 = !DILocation(line: 8, column: 32, scope: !45)
!49 = !{!50, !7, i64 400}
!50 = !{!"rb_vm_struct", !7, i64 0, !51, i64 8, !16, i64 192, !16, i64 200, !16, i64 208, !35, i64 216, !8, i64 224, !52, i64 264, !52, i64 280, !52, i64 296, !52, i64 312, !7, i64 328, !19, i64 336, !19, i64 340, !19, i64 344, !19, i64 344, !19, i64 344, !19, i64 344, !19, i64 348, !7, i64 352, !8, i64 360, !7, i64 400, !7, i64 408, !7, i64 416, !7, i64 424, !7, i64 432, !7, i64 440, !7, i64 448, !16, i64 456, !16, i64 464, !54, i64 472, !55, i64 992, !16, i64 1016, !16, i64 1024, !19, i64 1032, !19, i64 1036, !52, i64 1040, !8, i64 1056, !7, i64 1096, !7, i64 1104, !7, i64 1112, !7, i64 1120, !7, i64 1128, !19, i64 1136, !16, i64 1144, !16, i64 1152, !16, i64 1160, !16, i64 1168, !16, i64 1176, !16, i64 1184, !19, i64 1192, !56, i64 1200, !8, i64 1232}
!51 = !{!"rb_global_vm_lock_struct", !16, i64 0, !8, i64 8, !52, i64 48, !16, i64 64, !19, i64 72, !8, i64 80, !8, i64 128, !19, i64 176, !19, i64 180}
!52 = !{!"list_head", !53, i64 0}
!53 = !{!"list_node", !16, i64 0, !16, i64 8}
!54 = !{!"", !8, i64 0}
!55 = !{!"rb_hook_list_struct", !16, i64 0, !19, i64 8, !19, i64 12, !19, i64 16}
!56 = !{!"", !7, i64 0, !7, i64 8, !7, i64 16, !7, i64 24}
!57 = !DILocation(line: 0, scope: !11)
!58 = !DILocation(line: 5, column: 1, scope: !11)
!59 = !{!8, !8, i64 0}
!60 = !{!18, !7, i64 128}
!61 = !{!62}
!62 = distinct !{!62, !63, !"VM_BH_FROM_IFUNC_BLOCK: argument 0"}
!63 = distinct !{!63, !"VM_BH_FROM_IFUNC_BLOCK"}
!64 = distinct !DISubprogram(name: "Foo#bar", linkageName: "func_Foo#3bar", scope: null, file: !4, line: 9, type: !12, scopeLine: 9, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !3, retainedNodes: !5)
!65 = !DILocation(line: 9, column: 3, scope: !64)
!66 = !{!"branch_weights", i32 4001, i32 4000000}
!67 = !DILocation(line: 0, scope: !64)
!68 = !DILocation(line: 9, column: 11, scope: !64)
!69 = !{!"branch_weights", i32 1, i32 2000}
!70 = !{!71, !7, i64 0}
!71 = !{!"RBasic", !7, i64 0, !7, i64 8}
!72 = !DILocation(line: 9, column: 15, scope: !64)
!73 = !DILocation(line: 10, column: 9, scope: !64)
!74 = !{!75}
!75 = distinct !{!75, !76, !"sorbet_rb_int_plus: argument 0"}
!76 = distinct !{!76, !"sorbet_rb_int_plus"}
!77 = !DILocation(line: 11, column: 5, scope: !64)
!78 = !{!22, !7, i64 24}
!79 = !DILocation(line: 8, column: 3, scope: !45)
!80 = distinct !DISubprogram(name: "func_Foo#3bar.cold.1", linkageName: "func_Foo#3bar.cold.1", scope: null, file: !4, type: !81, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition | DISPFlagOptimized, unit: !3, retainedNodes: !5)
!81 = !DISubroutineType(types: !5)
!82 = distinct !DISubprogram(name: "func_Foo#3bar.cold.2", linkageName: "func_Foo#3bar.cold.2", scope: null, file: !4, type: !81, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition | DISPFlagOptimized, unit: !3, retainedNodes: !5)
!83 = !DILocation(line: 9, column: 15, scope: !82)
!84 = distinct !DISubprogram(name: "func_Foo#3bar.cold.3", linkageName: "func_Foo#3bar.cold.3", scope: null, file: !4, type: !81, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition | DISPFlagOptimized, unit: !3, retainedNodes: !5)
!85 = !DILocation(line: 9, column: 11, scope: !84)
