; ModuleID = 'payload'
source_filename = "llvm-link"
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"

%struct.rb_vm_struct = type { i64, %struct.rb_global_vm_lock_struct, %struct.rb_thread_struct*, %struct.rb_thread_struct*, i8*, i64, %union.pthread_mutex_t, %union.anon.12, %union.anon.12, %union.anon.12, %union.anon.12, i64, i32, i8, i32, i64, [5 x i64], i64, i64, i64, i64, i64, i64, i64, %struct.st_table*, %struct.st_table*, %struct.anon.18, %struct.rb_hook_list_struct, %struct.st_table*, %struct.rb_postponed_job_struct*, i32, i32, %union.anon.12, %union.pthread_mutex_t, i64, i64, i64, i64, i64, i32, i64, %struct.rb_objspace*, %struct.rb_at_exit_list*, i64*, %struct.st_table*, %struct.anon.19, [28 x i16] }
%struct.rb_global_vm_lock_struct = type { %struct.rb_thread_struct*, %union.pthread_mutex_t, %union.anon.12, %struct.rb_thread_struct*, i32, %union.pthread_cond_t, %union.pthread_cond_t, i32, i32 }
%union.pthread_cond_t = type { %struct.anon.14 }
%struct.anon.14 = type { i32, i32, i64, i64, i64, i8*, i32, i32 }
%struct.rb_thread_struct = type { %struct.list_node, i64, %struct.rb_vm_struct*, %struct.rb_execution_context_struct*, i64, %struct.rb_calling_info*, i64, i64, i64, i8, i8, i32, %struct.native_thread_data_struct, i8*, i64, i64, i64, i64, %union.pthread_mutex_t, %struct.rb_unblock_callback, i64, %struct.rb_mutex_struct*, %struct.rb_thread_list_struct*, %union.anon.15, i32, i64, %struct.rb_fiber_struct*, [1 x %struct.__jmp_buf_tag], i64 }
%struct.list_node = type { %struct.list_node*, %struct.list_node* }
%struct.rb_execution_context_struct = type { i64*, i64, %struct.rb_control_frame_struct*, %struct.rb_vm_tag*, %struct.rb_vm_protect_tag*, i32, i32, %struct.rb_fiber_struct*, %struct.rb_thread_struct*, %struct.st_table*, i64, i64, i64*, i64, %struct.rb_ensure_list*, %struct.rb_trace_arg_struct*, i64, i64, i8, i8, i64, %struct.anon.11 }
%struct.rb_control_frame_struct = type { i64*, i64*, %struct.rb_iseq_struct*, i64, i64*, i8*, i64* }
%struct.rb_iseq_struct = type { i64, i64, %struct.rb_iseq_constant_body*, %union.anon.8 }
%struct.rb_iseq_constant_body = type { i32, i32, i64*, %struct.anon.1, %struct.rb_iseq_location_struct, %struct.iseq_insn_info, i64*, %struct.iseq_catch_table*, %struct.rb_iseq_struct*, %struct.rb_iseq_struct*, %union.iseq_inline_storage_entry*, %struct.rb_call_info*, %struct.rb_call_cache*, %struct.anon.7, i32, i32, i32, i32, i32, i64 (%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*)*, i64, %struct.rb_mjit_unit*, i8 }
%struct.anon.1 = type { %struct.anon.2, i32, i32, i32, i32, i32, i32, i32, i64*, %struct.rb_iseq_param_keyword* }
%struct.anon.2 = type { i8, [3 x i8] }
%struct.rb_iseq_param_keyword = type { i32, i32, i32, i32, i64*, i64* }
%struct.rb_iseq_location_struct = type { i64, i64, i64, i64, i32, %struct.rb_code_location_struct }
%struct.rb_code_location_struct = type { %struct.rb_code_position_struct, %struct.rb_code_position_struct }
%struct.rb_code_position_struct = type { i32, i32 }
%struct.iseq_insn_info = type { %struct.rb_code_position_struct*, i32*, i32, %struct.succ_index_table* }
%struct.succ_index_table = type opaque
%struct.iseq_catch_table = type opaque
%union.iseq_inline_storage_entry = type { %struct.iseq_inline_cache_entry }
%struct.iseq_inline_cache_entry = type { i64, %struct.rb_cref_struct*, %union.anon.0 }
%struct.rb_cref_struct = type { i64, i64, i64, %struct.rb_cref_struct*, %struct.anon.2 }
%union.anon.0 = type { i64 }
%struct.rb_call_info = type { i64, i32, i32 }
%struct.rb_call_cache = type { i64, i64, %struct.rb_callable_method_entry_struct*, i64 (%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_calling_info*, %struct.rb_call_info*, %struct.rb_call_cache*)*, %union.anon.6 }
%struct.rb_callable_method_entry_struct = type { i64, i64, %struct.rb_method_definition_struct*, i64, i64 }
%struct.rb_method_definition_struct = type { i64, %union.anon.5, i64 }
%union.anon.5 = type { %struct.rb_method_cfunc_struct }
%struct.rb_method_cfunc_struct = type { i64 (...)*, i64 (i64 (...)*, i64, i32, i64*)*, i32 }
%union.anon.6 = type { i32 }
%struct.anon.7 = type { i64, i64, i64, i64* }
%struct.rb_mjit_unit = type opaque
%union.anon.8 = type { %struct.anon.9 }
%struct.anon.9 = type { i64, i32 }
%struct.rb_vm_tag = type { i64, i64, [1 x %struct.__jmp_buf_tag], %struct.rb_vm_tag*, i32 }
%struct.rb_vm_protect_tag = type { %struct.rb_vm_protect_tag* }
%struct.rb_ensure_list = type { %struct.rb_ensure_list*, %struct.rb_ensure_entry }
%struct.rb_ensure_entry = type { i64, i64 (...)*, i64 }
%struct.rb_trace_arg_struct = type { i32, %struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, i64, i64, i64, i64, i64, i32, i32, i64 }
%struct.anon.11 = type { i64*, i64*, i64, [1 x %struct.__jmp_buf_tag] }
%struct.rb_calling_info = type { i64, i64, i32 }
%struct.native_thread_data_struct = type { %union.anon.12, %union.anon.13 }
%union.anon.13 = type { %union.pthread_cond_t }
%struct.rb_unblock_callback = type { void (i8*)*, i8* }
%struct.rb_mutex_struct = type opaque
%struct.rb_thread_list_struct = type { %struct.rb_thread_list_struct*, %struct.rb_thread_struct* }
%union.anon.15 = type { %struct.RBasic }
%struct.RBasic = type { i64, i64 }
%struct.rb_fiber_struct = type opaque
%struct.__jmp_buf_tag = type { [8 x i64], i32, %struct.__sigset_t }
%struct.__sigset_t = type { [16 x i64] }
%struct.anon.18 = type { [65 x i64], [65 x i8] }
%struct.rb_hook_list_struct = type { %struct.rb_event_hook_struct*, i32, i32, i32 }
%struct.rb_event_hook_struct = type opaque
%struct.rb_postponed_job_struct = type opaque
%union.anon.12 = type { %struct.list_node }
%union.pthread_mutex_t = type { %struct.__pthread_mutex_s }
%struct.__pthread_mutex_s = type { i32, i32, i32, i32, i32, i16, i16, %struct.__pthread_internal_list }
%struct.__pthread_internal_list = type { %struct.__pthread_internal_list*, %struct.__pthread_internal_list* }
%struct.rb_objspace = type opaque
%struct.rb_at_exit_list = type { void (%struct.rb_vm_struct*)*, %struct.rb_at_exit_list* }
%struct.st_table = type { i8, i8, i8, i32, %struct.st_hash_type*, i64, i64*, i64, i64, %struct.st_table_entry* }
%struct.st_hash_type = type { i32 (...)*, i64 (...)* }
%struct.st_table_entry = type opaque
%struct.anon.19 = type { i64, i64, i64, i64 }

@rb_eRuntimeError = external local_unnamed_addr global i64, align 8
@.str.1 = private unnamed_addr constant [95 x i8] c"sorbet_getBuildSCMRevision: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@.str.2 = private unnamed_addr constant [93 x i8] c"sorbet_getIsReleaseBuild: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@ruby_current_vm_ptr = external local_unnamed_addr global %struct.rb_vm_struct*, align 8
@ruby_current_execution_context_ptr = external local_unnamed_addr global %struct.rb_execution_context_struct*, align 8
@.str.17 = private unnamed_addr constant [24 x i8] c"$__sorbet_ruby_realpath\00", align 1
@.str.18 = private unnamed_addr constant [63 x i8] c"Invalid '$__sorbet_ruby_realpath' when loading compiled module\00", align 1
@rb_cModule = external local_unnamed_addr constant i64, align 8
@"stackFramePrecomputed_func_<root>.<static-init>$153" = internal unnamed_addr global i8* null, align 8
@"rubyIdPrecomputed_<top (required)>" = internal unnamed_addr global i64 0, align 8
@"str_<top (required)>" = private unnamed_addr constant [17 x i8] c"<top (required)>\00", align 1
@"rubyStrFrozen_<top (required)>" = internal unnamed_addr global i64 0, align 8
@"rubyStrFrozen_test/testdata/compiler/call_final.rb" = internal unnamed_addr global i64 0, align 8
@"str_test/testdata/compiler/call_final.rb" = private unnamed_addr constant [37 x i8] c"test/testdata/compiler/call_final.rb\00", align 1
@str_cast = private unnamed_addr constant [5 x i8] c"cast\00", align 1
@"str_T.class_of(<root>)" = private unnamed_addr constant [19 x i8] c"T.class_of(<root>)\00", align 1
@str_A = private unnamed_addr constant [2 x i8] c"A\00", align 1
@str_B = private unnamed_addr constant [2 x i8] c"B\00", align 1
@stackFramePrecomputed_func_A.foo = internal unnamed_addr global i8* null, align 8
@rubyIdPrecomputed_foo = internal unnamed_addr global i64 0, align 8
@str_foo = private unnamed_addr constant [4 x i8] c"foo\00", align 1
@"str_T.class_of(A)" = private unnamed_addr constant [14 x i8] c"T.class_of(A)\00", align 1
@str_sig = private unnamed_addr constant [4 x i8] c"sig\00", align 1
@str_Integer = private unnamed_addr constant [8 x i8] c"Integer\00", align 1
@"stackFramePrecomputed_func_A.<static-init>" = internal unnamed_addr global i8* null, align 8
@"rubyIdPrecomputed_<self>" = internal unnamed_addr global i64 0, align 8
@"str_<self>" = private unnamed_addr constant [7 x i8] c"<self>\00", align 1
@"stackFramePrecomputed_func_A.<static-init>$block_1" = internal unnamed_addr global i8* null, align 8
@"rubyIdPrecomputed_block for" = internal unnamed_addr global i64 0, align 8
@"str_block for" = private unnamed_addr constant [10 x i8] c"block for\00", align 1
@rubyIdPrecomputed_final = internal unnamed_addr global i64 0, align 8
@str_final = private unnamed_addr constant [6 x i8] c"final\00", align 1
@str_n = private unnamed_addr constant [2 x i8] c"n\00", align 1
@"str_<build-keyword-args>" = private unnamed_addr constant [21 x i8] c"<build-keyword-args>\00", align 1
@str_params = private unnamed_addr constant [7 x i8] c"params\00", align 1
@str_returns = private unnamed_addr constant [8 x i8] c"returns\00", align 1
@str_keep_self_def = private unnamed_addr constant [14 x i8] c"keep_self_def\00", align 1
@"stackFramePrecomputed_func_B#caller" = internal unnamed_addr global i8* null, align 8
@rubyIdPrecomputed_caller = internal unnamed_addr global i64 0, align 8
@str_caller = private unnamed_addr constant [7 x i8] c"caller\00", align 1
@"stackFramePrecomputed_func_B.<static-init>" = internal unnamed_addr global i8* null, align 8
@"<static-init-locals-storage>.2" = internal global [1 x i64] zeroinitializer
@str_keep_def = private unnamed_addr constant [9 x i8] c"keep_def\00", align 1
@rb_cObject = external local_unnamed_addr constant i64
@guard_epoch_A = linkonce local_unnamed_addr global i64 0
@guarded_const_A = linkonce local_unnamed_addr global i64 0
@guard_epoch_B = linkonce local_unnamed_addr global i64 0
@guarded_const_B = linkonce local_unnamed_addr global i64 0

; Function Attrs: nounwind ssp uwtable
define weak i8* @sorbet_getBuildSCMRevision() local_unnamed_addr #0 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !4
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* getelementptr inbounds ([95 x i8], [95 x i8]* @.str.1, i64 0, i64 0)) #15
  unreachable
}

; Function Attrs: noreturn
declare void @rb_raise(i64, i8*, ...) local_unnamed_addr #1

; Function Attrs: nounwind ssp uwtable
define weak i32 @sorbet_getIsReleaseBuild() local_unnamed_addr #0 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !4
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* getelementptr inbounds ([93 x i8], [93 x i8]* @.str.2, i64 0, i64 0)) #15
  unreachable
}

declare i64 @rb_fstring_new(i8*, i64) local_unnamed_addr #2

declare void @rb_gc_register_mark_object(i64) local_unnamed_addr #2

declare i64 @rb_intern2(i8*, i64) local_unnamed_addr #2

declare i64 @rb_id2sym(i64) local_unnamed_addr #2

; Function Attrs: noinline nounwind ssp uwtable
declare i64 @sorbet_getConstant(i8*, i64) local_unnamed_addr #3

declare i64 @rb_define_class(i8*, i64) local_unnamed_addr #2

declare void @rb_define_method(i64, i8*, i64 (...)*, i32) local_unnamed_addr #2

declare void @rb_define_singleton_method(i64, i8*, i64 (...)*, i32) local_unnamed_addr #2

; Function Attrs: cold noreturn nounwind optsize ssp uwtable
declare void @sorbet_cast_failure(i64, i8*, i8*) local_unnamed_addr #4

; Function Attrs: noreturn nounwind ssp uwtable
declare void @sorbet_raiseArity(i32, i32, i32) local_unnamed_addr #5

; Function Attrs: inaccessiblememonly
declare i32 @ruby_stack_check() local_unnamed_addr #6

; Function Attrs: nounwind ssp uwtable
declare i8* @sorbet_allocateRubyStackFrame(i64, i64, i64, i64, i8*, i32, i32, i32, i64* nocapture readonly, i32) local_unnamed_addr #0

declare i64 @rb_gv_get(i8*) local_unnamed_addr #2

declare i64 @rb_gv_set(i8*, i64) local_unnamed_addr #2

; Function Attrs: noinline nounwind ssp uwtable
define internal fastcc void @vm_env_write_slowpath(i64* nocapture, i64) unnamed_addr #3 {
  %3 = getelementptr inbounds i64, i64* %0, i64 1
  %4 = load i64, i64* %3, align 8, !tbaa !4
  tail call void @rb_gc_writebarrier_remember(i64 %4) #14
  %5 = getelementptr inbounds i64, i64* %0, i64 -3
  store i64 %1, i64* %5, align 8, !tbaa !4
  %6 = load i64, i64* %0, align 8, !tbaa !4
  %7 = and i64 %6, -9
  store i64 %7, i64* %0, align 8, !tbaa !4
  ret void
}

declare void @rb_gc_writebarrier_remember(i64) local_unnamed_addr #2

; Function Attrs: nounwind ssp uwtable
declare %struct.rb_control_frame_struct* @sorbet_setRubyStackFrame(i1 zeroext, i32, i8*) local_unnamed_addr #0

; Function Attrs: nounwind readnone
declare i64 @rb_obj_is_kind_of(i64, i64) local_unnamed_addr #7

; Function Attrs: nounwind readnone
declare i64 @rb_class_inherited_p(i64, i64) local_unnamed_addr #7

; Function Attrs: alwaysinline norecurse nounwind readonly ssp uwtable
declare i64 @sorbet_getConstantEpoch() local_unnamed_addr #8

; Function Attrs: nounwind sspreq
define void @Init_call_final() local_unnamed_addr #9 {
entry:
  %locals1.i.i = alloca [0 x i64], align 8
  %0 = tail call i64 @rb_gv_get(i8* getelementptr inbounds ([24 x i8], [24 x i8]* @.str.17, i64 0, i64 0)) #14
  %1 = and i64 %0, 7
  %2 = icmp ne i64 %1, 0
  %3 = and i64 %0, -9
  %4 = icmp eq i64 %3, 0
  %5 = or i1 %2, %4
  br i1 %5, label %12, label %6

6:                                                ; preds = %entry
  %7 = inttoptr i64 %0 to %struct.RBasic*
  %8 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %7, i64 0, i32 0
  %9 = load i64, i64* %8, align 8, !tbaa !8
  %10 = and i64 %9, 31
  %11 = icmp eq i64 %10, 5
  br i1 %11, label %sorbet_readRealpath.exit, label %12

12:                                               ; preds = %6, %entry
  %13 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !4
  tail call void (i64, i8*, ...) @rb_raise(i64 %13, i8* getelementptr inbounds ([63 x i8], [63 x i8]* @.str.18, i64 0, i64 0)) #15
  unreachable

sorbet_readRealpath.exit:                         ; preds = %6
  %14 = tail call i64 @rb_gv_set(i8* getelementptr inbounds ([24 x i8], [24 x i8]* @.str.17, i64 0, i64 0), i64 8) #14
  %15 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 16) #14
  store i64 %15, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %16 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_foo, i64 0, i64 0), i64 3) #14
  store i64 %16, i64* @rubyIdPrecomputed_foo, align 8
  %17 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([7 x i8], [7 x i8]* @"str_<self>", i64 0, i64 0), i64 6) #14
  store i64 %17, i64* @"rubyIdPrecomputed_<self>", align 8
  %18 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([10 x i8], [10 x i8]* @"str_block for", i64 0, i64 0), i64 9) #14
  store i64 %18, i64* @"rubyIdPrecomputed_block for", align 8
  %19 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([6 x i8], [6 x i8]* @str_final, i64 0, i64 0), i64 5) #14
  store i64 %19, i64* @rubyIdPrecomputed_final, align 8
  %20 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_sig, i64 0, i64 0), i64 3) #14
  %21 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([2 x i8], [2 x i8]* @str_n, i64 0, i64 0), i64 1) #14
  %22 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([21 x i8], [21 x i8]* @"str_<build-keyword-args>", i64 0, i64 0), i64 20) #14
  %23 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([7 x i8], [7 x i8]* @str_params, i64 0, i64 0), i64 6) #14
  %24 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([8 x i8], [8 x i8]* @str_returns, i64 0, i64 0), i64 7) #14
  %25 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([14 x i8], [14 x i8]* @str_keep_self_def, i64 0, i64 0), i64 13) #14
  %26 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([7 x i8], [7 x i8]* @str_caller, i64 0, i64 0), i64 6) #14
  store i64 %26, i64* @rubyIdPrecomputed_caller, align 8
  %27 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([9 x i8], [9 x i8]* @str_keep_def, i64 0, i64 0), i64 8) #14
  %"rubyId_<self>.i" = load i64, i64* @"rubyIdPrecomputed_<self>", align 8
  store i64 %"rubyId_<self>.i", i64* getelementptr inbounds ([1 x i64], [1 x i64]* @"<static-init-locals-storage>.2", i64 0, i64 0), align 8
  %28 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 16) #14
  tail call void @rb_gc_register_mark_object(i64 %28) #14
  store i64 %28, i64* @"rubyStrFrozen_<top (required)>", align 8
  %29 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([37 x i8], [37 x i8]* @"str_test/testdata/compiler/call_final.rb", i64 0, i64 0), i64 36) #14
  tail call void @rb_gc_register_mark_object(i64 %29) #14
  store i64 %29, i64* @"rubyStrFrozen_test/testdata/compiler/call_final.rb", align 8
  %"rubyId_<top (required)>.i.i" = load i64, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %"rubyStr_<top (required)>.i.i" = load i64, i64* @"rubyStrFrozen_<top (required)>", align 8
  %30 = tail call i8* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_<top (required)>.i.i", i64 %"rubyId_<top (required)>.i.i", i64 %29, i64 %0, i8* null, i32 1, i32 1, i32 15, i64* getelementptr inbounds ([1 x i64], [1 x i64]* @"<static-init-locals-storage>.2", i64 0, i64 0), i32 1) #14
  store i8* %30, i8** @"stackFramePrecomputed_func_<root>.<static-init>$153", align 8
  %31 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_foo, i64 0, i64 0), i64 3) #14
  tail call void @rb_gc_register_mark_object(i64 %31) #14
  %32 = bitcast [0 x i64]* %locals1.i.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 0, i8* nonnull %32) #14
  %rubyId_foo.i.i = load i64, i64* @rubyIdPrecomputed_foo, align 8
  %"rubyStr_test/testdata/compiler/call_final.rb.i3.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/call_final.rb", align 8
  %locals1.sub.i.i = getelementptr inbounds [0 x i64], [0 x i64]* %locals1.i.i, i64 0, i64 0
  %33 = call i8* @sorbet_allocateRubyStackFrame(i64 %31, i64 %rubyId_foo.i.i, i64 %"rubyStr_test/testdata/compiler/call_final.rb.i3.i", i64 %0, i8* null, i32 1, i32 7, i32 9, i64* nonnull %locals1.sub.i.i, i32 0) #14
  store i8* %33, i8** @stackFramePrecomputed_func_A.foo, align 8
  call void @llvm.lifetime.end.p0i8(i64 0, i8* nonnull %32) #14
  %"rubyId_<top (required)>.i4.i" = load i64, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %"rubyStr_<top (required)>.i5.i" = load i64, i64* @"rubyStrFrozen_<top (required)>", align 8
  %"rubyStr_test/testdata/compiler/call_final.rb.i6.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/call_final.rb", align 8
  %34 = tail call i8* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_<top (required)>.i5.i", i64 %"rubyId_<top (required)>.i4.i", i64 %"rubyStr_test/testdata/compiler/call_final.rb.i6.i", i64 %0, i8* null, i32 1, i32 1, i32 5, i64* null, i32 0) #14
  store i8* %34, i8** @"stackFramePrecomputed_func_A.<static-init>", align 8
  %35 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([10 x i8], [10 x i8]* @"str_block for", i64 0, i64 0), i64 9) #14
  tail call void @rb_gc_register_mark_object(i64 %35) #14
  %"stackFrame_func_A.<static-init>.i.i" = load i8*, i8** @"stackFramePrecomputed_func_A.<static-init>", align 8
  %"rubyId_block for.i.i" = load i64, i64* @"rubyIdPrecomputed_block for", align 8
  %"rubyStr_test/testdata/compiler/call_final.rb.i7.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/call_final.rb", align 8
  %36 = tail call i8* @sorbet_allocateRubyStackFrame(i64 %35, i64 %"rubyId_block for.i.i", i64 %"rubyStr_test/testdata/compiler/call_final.rb.i7.i", i64 %0, i8* %"stackFrame_func_A.<static-init>.i.i", i32 2, i32 1, i32 5, i64* null, i32 0) #14
  store i8* %36, i8** @"stackFramePrecomputed_func_A.<static-init>$block_1", align 8
  %37 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([7 x i8], [7 x i8]* @str_caller, i64 0, i64 0), i64 6) #14
  tail call void @rb_gc_register_mark_object(i64 %37) #14
  call void @llvm.lifetime.start.p0i8(i64 0, i8* nonnull %32) #14
  %rubyId_caller.i.i = load i64, i64* @rubyIdPrecomputed_caller, align 8
  %"rubyStr_test/testdata/compiler/call_final.rb.i9.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/call_final.rb", align 8
  %38 = call i8* @sorbet_allocateRubyStackFrame(i64 %37, i64 %rubyId_caller.i.i, i64 %"rubyStr_test/testdata/compiler/call_final.rb.i9.i", i64 %0, i8* null, i32 1, i32 12, i32 14, i64* nonnull %locals1.sub.i.i, i32 0) #14
  store i8* %38, i8** @"stackFramePrecomputed_func_B#caller", align 8
  call void @llvm.lifetime.end.p0i8(i64 0, i8* nonnull %32) #14
  %"rubyId_<top (required)>.i11.i" = load i64, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %"rubyStr_<top (required)>.i12.i" = load i64, i64* @"rubyStrFrozen_<top (required)>", align 8
  %"rubyStr_test/testdata/compiler/call_final.rb.i13.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/call_final.rb", align 8
  %39 = tail call i8* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_<top (required)>.i12.i", i64 %"rubyId_<top (required)>.i11.i", i64 %"rubyStr_test/testdata/compiler/call_final.rb.i13.i", i64 %0, i8* null, i32 1, i32 1, i32 11, i64* null, i32 0) #14
  store i8* %39, i8** @"stackFramePrecomputed_func_B.<static-init>", align 8
  %40 = load %struct.rb_vm_struct*, %struct.rb_vm_struct** @ruby_current_vm_ptr, align 8, !tbaa !10
  %41 = getelementptr inbounds %struct.rb_vm_struct, %struct.rb_vm_struct* %40, i64 0, i32 17
  %42 = load i64, i64* %41, align 8, !tbaa !12
  %"stackFrame_func_<root>.<static-init>$153.i" = load i8*, i8** @"stackFramePrecomputed_func_<root>.<static-init>$153", align 8
  %43 = tail call %struct.rb_control_frame_struct* @sorbet_setRubyStackFrame(i1 false, i32 1, i8* %"stackFrame_func_<root>.<static-init>$153.i") #14
  %44 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %43, i64 0, i32 0
  %45 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %43, i64 0, i32 2
  %46 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %45, align 8, !tbaa !22
  %47 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %46, i64 0, i32 2
  %48 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %47, align 8, !tbaa !24
  %49 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %48, i64 0, i32 2
  %50 = load i64*, i64** %49, align 8, !tbaa !26
  %51 = getelementptr inbounds i64, i64* %50, i64 5
  store i64* %51, i64** %44, align 8, !tbaa !10
  %52 = load %struct.rb_vm_struct*, %struct.rb_vm_struct** @ruby_current_vm_ptr, align 8, !dbg !35, !tbaa !10
  %53 = getelementptr inbounds %struct.rb_vm_struct, %struct.rb_vm_struct* %52, i64 0, i32 17, !dbg !35
  %54 = load i64, i64* %53, align 8, !dbg !35, !tbaa !12
  %55 = icmp eq i64 %54, %42, !dbg !35
  br i1 %55, label %typeTestSuccess.i, label %codeRepl5, !dbg !35, !prof !40

typeTestSuccess.i:                                ; preds = %sorbet_readRealpath.exit
  %56 = load i64, i64* @rb_cObject, align 8, !dbg !35
  %57 = tail call i64 @rb_define_class(i8* getelementptr inbounds ([2 x i8], [2 x i8]* @str_A, i64 0, i64 0), i64 %56) #14, !dbg !35
  %58 = load i64, i64* @guard_epoch_A, align 8, !dbg !35
  %59 = tail call i64 @sorbet_getConstantEpoch(), !dbg !35
  %needTakeSlowPath = icmp eq i64 %58, %59, !dbg !35
  br i1 %needTakeSlowPath, label %61, label %60, !dbg !35, !prof !41

60:                                               ; preds = %typeTestSuccess.i
  tail call void @const_recompute_A() #14, !dbg !35
  br label %61, !dbg !35

61:                                               ; preds = %typeTestSuccess.i, %60
  %62 = load i64, i64* @guarded_const_A, align 8, !dbg !35
  %63 = load i64, i64* @guard_epoch_A, align 8, !dbg !35
  %64 = tail call i64 @sorbet_getConstantEpoch(), !dbg !35
  %guardUpdated = icmp eq i64 %63, %64, !dbg !35
  tail call void @llvm.assume(i1 %guardUpdated), !dbg !35
  %65 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !10
  %66 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %65, i64 0, i32 2
  %67 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %66, align 8, !tbaa !42
  %68 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %67, i64 0, i32 0
  %69 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %67, i64 0, i32 2
  %70 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %69, align 8, !tbaa !22
  %71 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %70, i64 0, i32 2
  %72 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %71, align 8, !tbaa !24
  %73 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %72, i64 0, i32 2
  %74 = load i64*, i64** %73, align 8, !tbaa !26
  %75 = getelementptr inbounds i64, i64* %74, i64 5
  store i64* %75, i64** %68, align 8, !tbaa !10
  %rubyId_final.i.i = load i64, i64* @rubyIdPrecomputed_final, align 8, !dbg !45
  %rubyId_foo.i.i1 = load i64, i64* @rubyIdPrecomputed_foo, align 8, !dbg !48
  %76 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !49, !tbaa !10
  %77 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %76, i64 0, i32 2, !dbg !49
  %78 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %77, align 8, !dbg !49, !tbaa !42
  %79 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %78, i64 0, i32 4, !dbg !49
  %80 = load i64*, i64** %79, align 8, !dbg !49, !tbaa !50
  %81 = load i64, i64* %80, align 8, !dbg !49, !tbaa !4
  %82 = and i64 %81, 8, !dbg !49
  %83 = icmp eq i64 %82, 0, !dbg !49
  br i1 %83, label %84, label %86, !dbg !49, !prof !40

84:                                               ; preds = %61
  %85 = getelementptr inbounds i64, i64* %80, i64 -3, !dbg !49
  store i64 %62, i64* %85, align 8, !dbg !49, !tbaa !4
  br label %sorbet_writeLocal.exit.i.i, !dbg !49

86:                                               ; preds = %61
  tail call fastcc void @vm_env_write_slowpath(i64* nonnull %80, i64 %62) #14, !dbg !49
  br label %sorbet_writeLocal.exit.i.i, !dbg !49

sorbet_writeLocal.exit.i.i:                       ; preds = %86, %84
  store i64* %75, i64** %68, align 8, !tbaa !10
  %87 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !49, !tbaa !10
  %88 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %87, i64 0, i32 2, !dbg !49
  %89 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %88, align 8, !dbg !49, !tbaa !42
  %90 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %89, i64 0, i32 4, !dbg !49
  %91 = load i64*, i64** %90, align 8, !dbg !49, !tbaa !50
  %92 = getelementptr inbounds i64, i64* %91, i64 -3, !dbg !49
  %93 = load i64, i64* %92, align 8, !dbg !49, !tbaa !4
  %94 = icmp eq i64 %93, %62, !dbg !49
  br i1 %94, label %typeTestSuccess.i.i, label %95, !dbg !49

95:                                               ; preds = %sorbet_writeLocal.exit.i.i
  %96 = load i64, i64* @rb_cModule, align 8, !dbg !49, !tbaa !4
  %97 = tail call i64 @rb_obj_is_kind_of(i64 %93, i64 %96) #7, !dbg !49
  %98 = icmp eq i64 %97, 0, !dbg !49
  br i1 %98, label %codeRepl, label %sorbet_isa_class_of.exit.i1.i, !dbg !49, !prof !51

sorbet_isa_class_of.exit.i1.i:                    ; preds = %95
  %99 = tail call i64 @rb_class_inherited_p(i64 %93, i64 %62) #7, !dbg !49
  %100 = icmp eq i64 %99, 0, !dbg !49
  br i1 %100, label %codeRepl, label %typeTestSuccess.i.i, !dbg !49, !prof !52

typeTestSuccess.i.i:                              ; preds = %sorbet_isa_class_of.exit.i1.i, %sorbet_writeLocal.exit.i.i
  %101 = load i64, i64* %91, align 8, !dbg !49, !tbaa !4
  %102 = and i64 %101, 8, !dbg !49
  %103 = icmp eq i64 %102, 0, !dbg !49
  br i1 %103, label %afterSend.i.i, label %104, !dbg !49, !prof !40

104:                                              ; preds = %typeTestSuccess.i.i
  tail call fastcc void @vm_env_write_slowpath(i64* nonnull %91, i64 %93) #14, !dbg !49
  br label %afterSend.i.i, !dbg !49

codeRepl:                                         ; preds = %95, %sorbet_isa_class_of.exit.i1.i
  tail call fastcc void @Init_call_final.cold.1(i64 %93) #16
  unreachable

afterSend.i.i:                                    ; preds = %104, %typeTestSuccess.i.i
  %105 = getelementptr inbounds i64, i64* %74, i64 6, !dbg !49
  store i64* %105, i64** %68, align 8, !dbg !49, !tbaa !10
  %rawSym.i3.i = tail call i64 @rb_id2sym(i64 %rubyId_final.i.i) #14, !dbg !45
  %106 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !10
  %107 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %106, i64 0, i32 2
  %108 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %107, align 8, !tbaa !42
  %109 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %108, i64 0, i32 4
  %110 = load i64*, i64** %109, align 8, !tbaa !50
  %111 = getelementptr inbounds i64, i64* %110, i64 -3
  %112 = load i64, i64* %111, align 8, !tbaa !4
  store i64* %105, i64** %68, align 8, !tbaa !10
  %113 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !53, !tbaa !10
  %114 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %113, i64 0, i32 2, !dbg !53
  %115 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %114, align 8, !dbg !53, !tbaa !42
  %116 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %115, i64 0, i32 4, !dbg !53
  %117 = load i64*, i64** %116, align 8, !dbg !53, !tbaa !50
  %118 = load i64, i64* %117, align 8, !dbg !53, !tbaa !4
  %119 = and i64 %118, 8, !dbg !53
  %120 = icmp eq i64 %119, 0, !dbg !53
  br i1 %120, label %121, label %123, !dbg !53, !prof !40

121:                                              ; preds = %afterSend.i.i
  %122 = getelementptr inbounds i64, i64* %117, i64 -3, !dbg !53
  store i64 %112, i64* %122, align 8, !dbg !53, !tbaa !4
  br label %"func_<root>.<static-init>$153.exit", !dbg !53

123:                                              ; preds = %afterSend.i.i
  tail call fastcc void @vm_env_write_slowpath(i64* nonnull %117, i64 %112) #14, !dbg !53
  br label %"func_<root>.<static-init>$153.exit", !dbg !53

codeRepl5:                                        ; preds = %sorbet_readRealpath.exit
  tail call fastcc void @Init_call_final.cold.2(i64 %42) #16
  unreachable

"func_<root>.<static-init>$153.exit":             ; preds = %121, %123
  %124 = getelementptr inbounds i64, i64* %74, i64 7, !dbg !53
  store i64* %124, i64** %68, align 8, !dbg !53, !tbaa !10
  %rawSym24.i.i = tail call i64 @rb_id2sym(i64 %rubyId_foo.i.i1) #14, !dbg !48
  tail call void @rb_define_singleton_method(i64 %62, i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_foo, i64 0, i64 0), i64 (...)* bitcast (i64 (i32, i64*, i64)* @func_A.foo to i64 (...)*), i32 -1) #14, !dbg !48
  %125 = getelementptr inbounds i64, i64* %50, i64 11
  store i64* %125, i64** %44, align 8, !tbaa !10
  %126 = tail call i64 @rb_define_class(i8* getelementptr inbounds ([2 x i8], [2 x i8]* @str_B, i64 0, i64 0), i64 %56) #14, !dbg !54
  %127 = load i64, i64* @guard_epoch_B, align 8, !dbg !54
  %128 = tail call i64 @sorbet_getConstantEpoch(), !dbg !54
  %needTakeSlowPath10 = icmp eq i64 %127, %128, !dbg !54
  br i1 %needTakeSlowPath10, label %130, label %129, !dbg !54, !prof !41

129:                                              ; preds = %"func_<root>.<static-init>$153.exit"
  tail call void @const_recompute_B() #14, !dbg !54
  br label %130, !dbg !54

130:                                              ; preds = %"func_<root>.<static-init>$153.exit", %129
  %131 = load i64, i64* @guarded_const_B, align 8, !dbg !54
  %132 = load i64, i64* @guard_epoch_B, align 8, !dbg !54
  %133 = tail call i64 @sorbet_getConstantEpoch(), !dbg !54
  %guardUpdated11 = icmp eq i64 %132, %133, !dbg !54
  tail call void @llvm.assume(i1 %guardUpdated11), !dbg !54
  %134 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !10
  %135 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %134, i64 0, i32 2
  %136 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %135, align 8, !tbaa !42
  %137 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %136, i64 0, i32 0
  %138 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %136, i64 0, i32 2
  %139 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %138, align 8, !tbaa !22
  %140 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %139, i64 0, i32 2
  %141 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %140, align 8, !tbaa !24
  %142 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %141, i64 0, i32 2
  %143 = load i64*, i64** %142, align 8, !tbaa !26
  %rubyId_caller.i.i2 = load i64, i64* @rubyIdPrecomputed_caller, align 8, !dbg !55
  %144 = getelementptr inbounds i64, i64* %143, i64 12, !dbg !58
  store i64* %144, i64** %137, align 8, !dbg !58, !tbaa !10
  %rawSym.i.i = tail call i64 @rb_id2sym(i64 %rubyId_caller.i.i2) #14, !dbg !55
  tail call void @rb_define_method(i64 %131, i8* getelementptr inbounds ([7 x i8], [7 x i8]* @str_caller, i64 0, i64 0), i64 (...)* bitcast (i64 (i32, i64*, i64)* @"func_B#caller" to i64 (...)*), i32 -1) #14, !dbg !55
  ret void
}

; Function Attrs: nounwind sspreq uwtable
define i64 @func_A.foo(i32 %argc, i64* nocapture readonly %argArray, i64 %selfRaw) #10 !dbg !59 {
functionEntryInitializers:
  %stackFrame_func_A.foo = load i8*, i8** @stackFramePrecomputed_func_A.foo, align 8
  %0 = tail call %struct.rb_control_frame_struct* @sorbet_setRubyStackFrame(i1 false, i32 1, i8* %stackFrame_func_A.foo)
  %1 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %0, i64 0, i32 0
  %2 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %0, i64 0, i32 2
  %3 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %2, align 8, !tbaa !22
  %4 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %3, i64 0, i32 2
  %5 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %4, align 8, !tbaa !24
  %6 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %5, i64 0, i32 2
  %7 = load i64*, i64** %6, align 8, !tbaa !26
  %8 = getelementptr inbounds i64, i64* %7, i64 1
  store i64* %8, i64** %1, align 8, !tbaa !10
  %9 = icmp eq i32 %argc, 1, !dbg !60
  br i1 %9, label %fillRequiredArgs, label %argCountFailBlock, !dbg !60, !prof !61

argCountFailBlock:                                ; preds = %functionEntryInitializers
  tail call void @sorbet_raiseArity(i32 %argc, i32 1, i32 1), !dbg !60
  unreachable, !dbg !60

fillRequiredArgs:                                 ; preds = %functionEntryInitializers
  %rawArg_n = load i64, i64* %argArray, align 8, !dbg !60
  %10 = load i64, i64* @guard_epoch_A, align 8, !dbg !60
  %11 = tail call i64 @sorbet_getConstantEpoch(), !dbg !60
  %needTakeSlowPath = icmp eq i64 %10, %11, !dbg !60
  br i1 %needTakeSlowPath, label %13, label %12, !dbg !60, !prof !41

12:                                               ; preds = %fillRequiredArgs
  tail call void @const_recompute_A() #14, !dbg !60
  br label %13, !dbg !60

13:                                               ; preds = %fillRequiredArgs, %12
  %14 = load i64, i64* @guarded_const_A, align 8, !dbg !60
  %15 = load i64, i64* @guard_epoch_A, align 8, !dbg !60
  %16 = tail call i64 @sorbet_getConstantEpoch(), !dbg !60
  %guardUpdated = icmp eq i64 %15, %16, !dbg !60
  tail call void @llvm.assume(i1 %guardUpdated), !dbg !60
  %17 = icmp eq i64 %14, %selfRaw, !dbg !60
  br i1 %17, label %typeTestSuccess, label %18, !dbg !60

18:                                               ; preds = %13
  %19 = load i64, i64* @rb_cModule, align 8, !dbg !60, !tbaa !4
  %20 = tail call i64 @rb_obj_is_kind_of(i64 %selfRaw, i64 %19) #7, !dbg !60
  %21 = icmp eq i64 %20, 0, !dbg !60
  br i1 %21, label %codeRepl19, label %sorbet_isa_class_of.exit, !dbg !60, !prof !51

sorbet_isa_class_of.exit:                         ; preds = %18
  %22 = tail call i64 @rb_class_inherited_p(i64 %selfRaw, i64 %14) #7, !dbg !60
  %23 = icmp eq i64 %22, 0, !dbg !60
  br i1 %23, label %codeRepl19, label %typeTestSuccess, !dbg !60, !prof !52

typeTestSuccess:                                  ; preds = %sorbet_isa_class_of.exit, %13
  %24 = and i64 %rawArg_n, 1, !dbg !62
  %25 = icmp eq i64 %24, 0, !dbg !62
  br i1 %25, label %codeRepl, label %typeTestSuccess6, !dbg !62, !prof !52

codeRepl19:                                       ; preds = %18, %sorbet_isa_class_of.exit
  tail call fastcc void @func_A.foo.cold.2(i64 %selfRaw) #16, !dbg !60
  unreachable

typeTestSuccess6:                                 ; preds = %typeTestSuccess
  %26 = getelementptr inbounds i64, i64* %7, i64 2, !dbg !62
  store i64* %26, i64** %1, align 8, !dbg !62, !tbaa !10
  ret i64 %rawArg_n

codeRepl:                                         ; preds = %typeTestSuccess
  tail call fastcc void @func_A.foo.cold.1(i64 %rawArg_n) #16, !dbg !62
  unreachable
}

; Function Attrs: nounwind sspreq uwtable
define i64 @"func_B#caller"(i32 %argc, i64* nocapture readonly %argArray, i64 %selfRaw) #10 !dbg !63 {
functionEntryInitializers:
  %callArgs = alloca [1 x i64], align 8
  %"stackFrame_func_B#caller" = load i8*, i8** @"stackFramePrecomputed_func_B#caller", align 8
  %0 = tail call %struct.rb_control_frame_struct* @sorbet_setRubyStackFrame(i1 false, i32 1, i8* %"stackFrame_func_B#caller")
  %1 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %0, i64 0, i32 0
  %2 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %0, i64 0, i32 2
  %3 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %2, align 8, !tbaa !22
  %4 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %3, i64 0, i32 2
  %5 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %4, align 8, !tbaa !24
  %6 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %5, i64 0, i32 2
  %7 = load i64*, i64** %6, align 8, !tbaa !26
  %8 = getelementptr inbounds i64, i64* %7, i64 1
  store i64* %8, i64** %1, align 8, !tbaa !10
  %9 = icmp eq i32 %argc, 1, !dbg !64
  br i1 %9, label %fillRequiredArgs, label %argCountFailBlock, !dbg !64, !prof !61

argCountFailBlock:                                ; preds = %functionEntryInitializers
  tail call void @sorbet_raiseArity(i32 %argc, i32 1, i32 1), !dbg !64
  unreachable, !dbg !64

fillRequiredArgs:                                 ; preds = %functionEntryInitializers
  %10 = load i64, i64* @guard_epoch_B, align 8, !dbg !64
  %11 = tail call i64 @sorbet_getConstantEpoch(), !dbg !64
  %needTakeSlowPath = icmp eq i64 %10, %11, !dbg !64
  br i1 %needTakeSlowPath, label %13, label %12, !dbg !64, !prof !41

12:                                               ; preds = %fillRequiredArgs
  tail call void @const_recompute_B() #14, !dbg !64
  br label %13, !dbg !64

13:                                               ; preds = %fillRequiredArgs, %12
  %14 = load i64, i64* @guarded_const_B, align 8, !dbg !64
  %15 = load i64, i64* @guard_epoch_B, align 8, !dbg !64
  %16 = tail call i64 @sorbet_getConstantEpoch(), !dbg !64
  %guardUpdated = icmp eq i64 %15, %16, !dbg !64
  tail call void @llvm.assume(i1 %guardUpdated), !dbg !64
  %17 = tail call i64 @rb_obj_is_kind_of(i64 %selfRaw, i64 %14) #7, !dbg !64
  %18 = icmp eq i64 %17, 20, !dbg !64
  br i1 %18, label %afterCallFinal_foo, label %codeRepl, !dbg !64, !prof !40

codeRepl:                                         ; preds = %13
  tail call fastcc void @"func_B#caller.cold.1"(i64 %selfRaw) #16, !dbg !64
  unreachable

afterCallFinal_foo:                               ; preds = %13
  %rawArg_a = load i64, i64* %argArray, align 8, !dbg !64
  %19 = getelementptr inbounds i64, i64* %7, i64 2, !dbg !65
  store i64* %19, i64** %1, align 8, !dbg !65, !tbaa !10
  %20 = load i64, i64* @guard_epoch_A, align 8, !dbg !66
  %21 = tail call i64 @sorbet_getConstantEpoch(), !dbg !66
  %needTakeSlowPath17 = icmp eq i64 %20, %21, !dbg !66
  br i1 %needTakeSlowPath17, label %23, label %22, !dbg !66, !prof !41

22:                                               ; preds = %afterCallFinal_foo
  tail call void @const_recompute_A() #14, !dbg !66
  br label %23, !dbg !66

23:                                               ; preds = %afterCallFinal_foo, %22
  %24 = load i64, i64* @guarded_const_A, align 8, !dbg !66
  %25 = load i64, i64* @guard_epoch_A, align 8, !dbg !66
  %26 = tail call i64 @sorbet_getConstantEpoch(), !dbg !66
  %guardUpdated18 = icmp eq i64 %25, %26, !dbg !66
  tail call void @llvm.assume(i1 %guardUpdated18), !dbg !66
  %callArgs0Addr = getelementptr inbounds [1 x i64], [1 x i64]* %callArgs, i64 0, i64 0, !dbg !66
  store i64 %rawArg_a, i64* %callArgs0Addr, align 8, !dbg !66
  %27 = tail call i32 @ruby_stack_check() #14, !dbg !66
  %directSendResult = call i64 @func_A.foo(i32 1, i64* nonnull %callArgs0Addr, i64 %24), !dbg !66
  ret i64 %directSendResult
}

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #11

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.end.p0i8(i64 immarg, i8* nocapture) #11

; Function Attrs: cold minsize noreturn nounwind sspreq
define internal fastcc void @Init_call_final.cold.1(i64) unnamed_addr #12 {
newFuncRoot:
  tail call void @sorbet_cast_failure(i64 %0, i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_cast, i64 0, i64 0), i8* getelementptr inbounds ([14 x i8], [14 x i8]* @"str_T.class_of(A)", i64 0, i64 0)) #14, !dbg !49
  unreachable, !dbg !49
}

; Function Attrs: cold minsize noreturn nounwind sspreq
define internal fastcc void @Init_call_final.cold.2(i64) unnamed_addr #12 {
newFuncRoot:
  tail call void @sorbet_cast_failure(i64 %0, i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_cast, i64 0, i64 0), i8* getelementptr inbounds ([19 x i8], [19 x i8]* @"str_T.class_of(<root>)", i64 0, i64 0)) #14, !dbg !35
  unreachable, !dbg !35
}

; Function Attrs: cold minsize noreturn nounwind sspreq uwtable
define internal fastcc void @func_A.foo.cold.1(i64 %rawArg_n) unnamed_addr #13 {
newFuncRoot:
  tail call void @sorbet_cast_failure(i64 %rawArg_n, i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_sig, i64 0, i64 0), i8* getelementptr inbounds ([8 x i8], [8 x i8]* @str_Integer, i64 0, i64 0)), !dbg !62
  unreachable, !dbg !62
}

; Function Attrs: cold minsize noreturn nounwind sspreq uwtable
define internal fastcc void @func_A.foo.cold.2(i64 %selfRaw) unnamed_addr #13 {
newFuncRoot:
  tail call void @sorbet_cast_failure(i64 %selfRaw, i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_cast, i64 0, i64 0), i8* getelementptr inbounds ([14 x i8], [14 x i8]* @"str_T.class_of(A)", i64 0, i64 0)), !dbg !60
  unreachable, !dbg !60
}

; Function Attrs: cold minsize noreturn nounwind sspreq uwtable
define internal fastcc void @"func_B#caller.cold.1"(i64 %selfRaw) unnamed_addr #13 {
newFuncRoot:
  tail call void @sorbet_cast_failure(i64 %selfRaw, i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_cast, i64 0, i64 0), i8* getelementptr inbounds ([2 x i8], [2 x i8]* @str_B, i64 0, i64 0)), !dbg !64
  unreachable, !dbg !64
}

; Function Attrs: nounwind
declare void @llvm.assume(i1) #14

define linkonce void @const_recompute_A() local_unnamed_addr {
  %1 = tail call i64 @sorbet_getConstant(i8* getelementptr inbounds ([2 x i8], [2 x i8]* @str_A, i64 0, i64 0), i64 1)
  store i64 %1, i64* @guarded_const_A, align 8
  %2 = tail call i64 @sorbet_getConstantEpoch()
  store i64 %2, i64* @guard_epoch_A, align 8
  ret void
}

define linkonce void @const_recompute_B() local_unnamed_addr {
  %1 = tail call i64 @sorbet_getConstant(i8* getelementptr inbounds ([2 x i8], [2 x i8]* @str_B, i64 0, i64 0), i64 1)
  store i64 %1, i64* @guarded_const_B, align 8
  %2 = tail call i64 @sorbet_getConstantEpoch()
  store i64 %2, i64* @guard_epoch_B, align 8
  ret void
}

attributes #0 = { nounwind ssp uwtable }
attributes #1 = { noreturn }
attributes #2 = { "addedToSilenceEmptyAttrsError" }
attributes #3 = { noinline nounwind ssp uwtable }
attributes #4 = { cold noreturn nounwind optsize ssp uwtable }
attributes #5 = { noreturn nounwind ssp uwtable }
attributes #6 = { inaccessiblememonly "addedToSilenceEmptyAttrsError" }
attributes #7 = { nounwind readnone }
attributes #8 = { alwaysinline norecurse nounwind readonly ssp uwtable }
attributes #9 = { nounwind sspreq }
attributes #10 = { nounwind sspreq uwtable }
attributes #11 = { argmemonly nounwind }
attributes #12 = { cold minsize noreturn nounwind sspreq }
attributes #13 = { cold minsize noreturn nounwind sspreq uwtable }
attributes #14 = { nounwind }
attributes #15 = { noreturn nounwind }
attributes #16 = { noinline }

!llvm.module.flags = !{!0}
!llvm.dbg.cu = !{!1}

!0 = !{i32 2, !"Debug Info Version", i32 3}
!1 = distinct !DICompileUnit(language: DW_LANG_C, file: !2, producer: "Sorbet LLVM", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, enums: !3)
!2 = !DIFile(filename: "test/testdata/compiler/call_final.rb", directory: ".")
!3 = !{}
!4 = !{!5, !5, i64 0}
!5 = !{!"long", !6, i64 0}
!6 = !{!"omnipotent char", !7, i64 0}
!7 = !{!"Simple C/C++ TBAA"}
!8 = !{!9, !5, i64 0}
!9 = !{!"RBasic", !5, i64 0, !5, i64 8}
!10 = !{!11, !11, i64 0}
!11 = !{!"any pointer", !6, i64 0}
!12 = !{!13, !5, i64 400}
!13 = !{!"rb_vm_struct", !5, i64 0, !14, i64 8, !11, i64 192, !11, i64 200, !11, i64 208, !18, i64 216, !6, i64 224, !15, i64 264, !15, i64 280, !15, i64 296, !15, i64 312, !5, i64 328, !17, i64 336, !17, i64 340, !17, i64 340, !17, i64 340, !17, i64 340, !17, i64 344, !5, i64 352, !6, i64 360, !5, i64 400, !5, i64 408, !5, i64 416, !5, i64 424, !5, i64 432, !5, i64 440, !5, i64 448, !11, i64 456, !11, i64 464, !19, i64 472, !20, i64 1064, !11, i64 1088, !11, i64 1096, !17, i64 1104, !17, i64 1108, !15, i64 1112, !6, i64 1128, !5, i64 1168, !5, i64 1176, !5, i64 1184, !5, i64 1192, !5, i64 1200, !17, i64 1208, !5, i64 1216, !11, i64 1224, !11, i64 1232, !11, i64 1240, !11, i64 1248, !21, i64 1256, !6, i64 1288}
!14 = !{!"rb_global_vm_lock_struct", !11, i64 0, !6, i64 8, !15, i64 48, !11, i64 64, !17, i64 72, !6, i64 80, !6, i64 128, !17, i64 176, !17, i64 180}
!15 = !{!"list_head", !16, i64 0}
!16 = !{!"list_node", !11, i64 0, !11, i64 8}
!17 = !{!"int", !6, i64 0}
!18 = !{!"long long", !6, i64 0}
!19 = !{!"", !6, i64 0, !6, i64 520}
!20 = !{!"rb_hook_list_struct", !11, i64 0, !17, i64 8, !17, i64 12, !17, i64 16}
!21 = !{!"", !5, i64 0, !5, i64 8, !5, i64 16, !5, i64 24}
!22 = !{!23, !11, i64 16}
!23 = !{!"rb_control_frame_struct", !11, i64 0, !11, i64 8, !11, i64 16, !5, i64 24, !11, i64 32, !11, i64 40, !11, i64 48}
!24 = !{!25, !11, i64 16}
!25 = !{!"rb_iseq_struct", !5, i64 0, !5, i64 8, !11, i64 16, !6, i64 24}
!26 = !{!27, !11, i64 8}
!27 = !{!"rb_iseq_constant_body", !6, i64 0, !17, i64 4, !11, i64 8, !28, i64 16, !30, i64 64, !33, i64 120, !11, i64 152, !11, i64 160, !11, i64 168, !11, i64 176, !11, i64 184, !11, i64 192, !11, i64 200, !34, i64 208, !17, i64 240, !17, i64 244, !17, i64 248, !17, i64 252, !17, i64 256, !11, i64 264, !5, i64 272, !11, i64 280, !6, i64 288}
!28 = !{!"", !29, i64 0, !17, i64 4, !17, i64 8, !17, i64 12, !17, i64 16, !17, i64 20, !17, i64 24, !17, i64 28, !11, i64 32, !11, i64 40}
!29 = !{!"", !17, i64 0, !17, i64 0, !17, i64 0, !17, i64 0, !17, i64 0, !17, i64 0, !17, i64 0, !17, i64 0}
!30 = !{!"rb_iseq_location_struct", !5, i64 0, !5, i64 8, !5, i64 16, !5, i64 24, !17, i64 32, !31, i64 36}
!31 = !{!"rb_code_location_struct", !32, i64 0, !32, i64 8}
!32 = !{!"rb_code_position_struct", !17, i64 0, !17, i64 4}
!33 = !{!"iseq_insn_info", !11, i64 0, !11, i64 8, !17, i64 16, !11, i64 24}
!34 = !{!"", !5, i64 0, !5, i64 8, !5, i64 16, !11, i64 24}
!35 = !DILocation(line: 5, column: 1, scope: !36)
!36 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.<static-init>$153", scope: null, file: !2, line: 5, type: !37, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!37 = !DISubroutineType(types: !38)
!38 = !{!39}
!39 = !DIBasicType(name: "VALUE", size: 64, encoding: DW_ATE_signed)
!40 = !{!"branch_weights", i32 2000, i32 1}
!41 = !{!"branch_weights", i32 10000, i32 1}
!42 = !{!43, !11, i64 16}
!43 = !{!"rb_execution_context_struct", !11, i64 0, !5, i64 8, !11, i64 16, !11, i64 24, !11, i64 32, !17, i64 40, !17, i64 44, !11, i64 48, !11, i64 56, !11, i64 64, !5, i64 72, !5, i64 80, !11, i64 88, !5, i64 96, !11, i64 104, !11, i64 112, !5, i64 120, !5, i64 128, !6, i64 136, !6, i64 137, !5, i64 144, !44, i64 152}
!44 = !{!"", !11, i64 0, !11, i64 8, !5, i64 16, !6, i64 24}
!45 = !DILocation(line: 6, column: 30, scope: !46, inlinedAt: !47)
!46 = distinct !DISubprogram(name: "A.<static-init>", linkageName: "func_A.<static-init>L78", scope: null, file: !2, line: 5, type: !37, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!47 = distinct !DILocation(line: 5, column: 1, scope: !36)
!48 = !DILocation(line: 7, column: 3, scope: !46, inlinedAt: !47)
!49 = !DILocation(line: 5, column: 1, scope: !46, inlinedAt: !47)
!50 = !{!23, !11, i64 32}
!51 = !{!"branch_weights", i32 1073205, i32 2146410443}
!52 = !{!"branch_weights", i32 1, i32 2000}
!53 = !DILocation(line: 6, column: 3, scope: !46, inlinedAt: !47)
!54 = !DILocation(line: 11, column: 1, scope: !36)
!55 = !DILocation(line: 12, column: 1, scope: !56, inlinedAt: !57)
!56 = distinct !DISubprogram(name: "B.<static-init>", linkageName: "func_B.<static-init>L198", scope: null, file: !2, line: 11, type: !37, scopeLine: 11, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!57 = distinct !DILocation(line: 11, column: 1, scope: !36)
!58 = !DILocation(line: 11, column: 1, scope: !56, inlinedAt: !57)
!59 = distinct !DISubprogram(name: "A.foo", linkageName: "func_A.foo", scope: null, file: !2, line: 7, type: !37, scopeLine: 7, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!60 = !DILocation(line: 7, column: 3, scope: !59)
!61 = !{!"branch_weights", i32 4000000, i32 4001}
!62 = !DILocation(line: 7, column: 16, scope: !59)
!63 = distinct !DISubprogram(name: "B#caller", linkageName: "func_B#caller", scope: null, file: !2, line: 12, type: !37, scopeLine: 12, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!64 = !DILocation(line: 12, column: 1, scope: !63)
!65 = !DILocation(line: 12, column: 12, scope: !63)
!66 = !DILocation(line: 13, column: 3, scope: !63)
