; ModuleID = 'payload'
source_filename = "llvm-link"
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"

%struct.rb_vm_struct = type { i64, %struct.rb_global_vm_lock_struct, %struct.rb_thread_struct*, %struct.rb_thread_struct*, i8*, i64, %union.pthread_mutex_t, %union.anon.12, %union.anon.12, %union.anon.12, %union.anon.12, i64, i32, i8, i32, i64, [5 x i64], i64, i64, i64, i64, i64, i64, i64, %struct.st_table*, %struct.st_table*, %struct.anon.18, %struct.rb_hook_list_struct, %struct.st_table*, %struct.rb_postponed_job_struct*, i32, i32, %union.anon.12, %union.pthread_mutex_t, i64, i64, i64, i64, i64, i32, i64, %struct.rb_objspace*, %struct.rb_at_exit_list*, i64*, %struct.st_table*, %struct.anon.19, [28 x i16] }
%struct.rb_global_vm_lock_struct = type { %struct.rb_thread_struct*, %union.pthread_mutex_t, %union.anon.12, %struct.rb_thread_struct*, i32, %union.pthread_cond_t, %union.pthread_cond_t, i32, i32 }
%union.pthread_cond_t = type { %struct.anon.14 }
%struct.anon.14 = type { i32, i32, i64, i64, i64, i8*, i32, i32 }
%struct.rb_thread_struct = type { %struct.list_node, i64, %struct.rb_vm_struct*, %struct.rb_execution_context_struct*, i64, %struct.rb_calling_info*, i64, i64, i64, i8, i8, i32, %struct.native_thread_data_struct, i8*, i64, i64, i64, i64, %union.pthread_mutex_t, %struct.rb_unblock_callback, i64, %struct.rb_mutex_struct*, %struct.rb_thread_list_struct*, %union.anon.15, i32, i64, %struct.rb_fiber_struct*, [1 x %struct.__jmp_buf_tag], i64 }
%struct.list_node = type { %struct.list_node*, %struct.list_node* }
%struct.rb_execution_context_struct = type { i64*, i64, %struct.rb_control_frame_struct*, %struct.rb_vm_tag*, %struct.rb_vm_protect_tag*, i32, i32, %struct.rb_fiber_struct*, %struct.rb_thread_struct*, %struct.st_table*, i64, i64, i64*, i64, %struct.rb_ensure_list*, %struct.rb_trace_arg_struct*, i64, i64, i8, i8, i64, %struct.anon.11 }
%struct.rb_control_frame_struct = type { i64*, i64*, %struct.rb_iseq_struct*, i64, i64*, i8*, i64* }
%struct.rb_iseq_struct = type { i64, i64, %struct.rb_iseq_constant_body*, %union.anon.8 }
%struct.rb_iseq_constant_body = type { i32, i32, i64*, %struct.anon.1, %struct.rb_iseq_location_struct, %struct.iseq_insn_info, i64*, %struct.iseq_catch_table*, %struct.rb_iseq_struct*, %struct.rb_iseq_struct*, %union.iseq_inline_storage_entry*, %struct.rb_call_info*, %struct.rb_call_cache*, %struct.anon.7, i32, i32, i32, i32, i32, i64 (%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*)*, i64, %struct.rb_mjit_unit*, i8 }
%struct.anon.1 = type { %struct.anon.2, i32, i32, i32, i32, i32, i32, i32, i64*, %struct.rb_iseq_param_keyword* }
%struct.anon.2 = type { i8, [3 x i8] }
%struct.rb_iseq_param_keyword = type { i32, i32, i32, i32, i64*, i64* }
%struct.rb_iseq_location_struct = type { i64, i64, i64, i64, i32, %struct.rb_code_location_struct }
%struct.rb_code_location_struct = type { %struct.rb_code_position_struct, %struct.rb_code_position_struct }
%struct.rb_code_position_struct = type { i32, i32 }
%struct.iseq_insn_info = type { %struct.rb_code_position_struct*, i32*, i32, %struct.succ_index_table* }
%struct.succ_index_table = type opaque
%struct.iseq_catch_table = type opaque
%union.iseq_inline_storage_entry = type { %struct.iseq_inline_cache_entry }
%struct.iseq_inline_cache_entry = type { i64, %struct.rb_cref_struct*, %union.anon.0 }
%struct.rb_cref_struct = type { i64, i64, i64, %struct.rb_cref_struct*, %struct.anon.2 }
%union.anon.0 = type { i64 }
%struct.rb_call_info = type { i64, i32, i32 }
%struct.rb_call_cache = type { i64, i64, %struct.rb_callable_method_entry_struct*, i64 (%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_calling_info*, %struct.rb_call_info*, %struct.rb_call_cache*)*, %union.anon.6 }
%struct.rb_callable_method_entry_struct = type { i64, i64, %struct.rb_method_definition_struct*, i64, i64 }
%struct.rb_method_definition_struct = type { i64, %union.anon.5, i64 }
%union.anon.5 = type { %struct.rb_method_cfunc_struct }
%struct.rb_method_cfunc_struct = type { i64 (...)*, i64 (i64 (...)*, i64, i32, i64*)*, i32 }
%union.anon.6 = type { i32 }
%struct.anon.7 = type { i64, i64, i64, i64* }
%struct.rb_mjit_unit = type opaque
%union.anon.8 = type { %struct.anon.9 }
%struct.anon.9 = type { i64, i32 }
%struct.rb_vm_tag = type { i64, i64, [1 x %struct.__jmp_buf_tag], %struct.rb_vm_tag*, i32 }
%struct.rb_vm_protect_tag = type { %struct.rb_vm_protect_tag* }
%struct.rb_ensure_list = type { %struct.rb_ensure_list*, %struct.rb_ensure_entry }
%struct.rb_ensure_entry = type { i64, i64 (...)*, i64 }
%struct.rb_trace_arg_struct = type { i32, %struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, i64, i64, i64, i64, i64, i32, i32, i64 }
%struct.anon.11 = type { i64*, i64*, i64, [1 x %struct.__jmp_buf_tag] }
%struct.rb_calling_info = type { i64, i64, i32 }
%struct.native_thread_data_struct = type { %union.anon.12, %union.anon.13 }
%union.anon.13 = type { %union.pthread_cond_t }
%struct.rb_unblock_callback = type { void (i8*)*, i8* }
%struct.rb_mutex_struct = type opaque
%struct.rb_thread_list_struct = type { %struct.rb_thread_list_struct*, %struct.rb_thread_struct* }
%union.anon.15 = type { %struct.RBasic }
%struct.RBasic = type { i64, i64 }
%struct.rb_fiber_struct = type opaque
%struct.__jmp_buf_tag = type { [8 x i64], i32, %struct.__sigset_t }
%struct.__sigset_t = type { [16 x i64] }
%struct.anon.18 = type { [65 x i64], [65 x i8] }
%struct.rb_hook_list_struct = type { %struct.rb_event_hook_struct*, i32, i32, i32 }
%struct.rb_event_hook_struct = type opaque
%struct.rb_postponed_job_struct = type opaque
%union.anon.12 = type { %struct.list_node }
%union.pthread_mutex_t = type { %struct.__pthread_mutex_s }
%struct.__pthread_mutex_s = type { i32, i32, i32, i32, i32, i16, i16, %struct.__pthread_internal_list }
%struct.__pthread_internal_list = type { %struct.__pthread_internal_list*, %struct.__pthread_internal_list* }
%struct.rb_objspace = type opaque
%struct.rb_at_exit_list = type { void (%struct.rb_vm_struct*)*, %struct.rb_at_exit_list* }
%struct.st_table = type { i8, i8, i8, i32, %struct.st_hash_type*, i64, i64*, i64, i64, %struct.st_table_entry* }
%struct.st_hash_type = type { i32 (...)*, i64 (...)* }
%struct.st_table_entry = type opaque
%struct.anon.19 = type { i64, i64, i64, i64 }
%struct.FunctionInlineCache = type { %struct.rb_callable_method_entry_struct*, i64, i64 }

@rb_eRuntimeError = external local_unnamed_addr global i64, align 8
@.str.1 = private unnamed_addr constant [95 x i8] c"sorbet_getBuildSCMRevision: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@.str.2 = private unnamed_addr constant [93 x i8] c"sorbet_getIsReleaseBuild: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@ruby_current_vm_ptr = external local_unnamed_addr global %struct.rb_vm_struct*, align 8
@.str.17 = private unnamed_addr constant [24 x i8] c"$__sorbet_ruby_realpath\00", align 1
@.str.18 = private unnamed_addr constant [63 x i8] c"Invalid '$__sorbet_ruby_realpath' when loading compiled module\00", align 1
@"stackFramePrecomputed_func_Object#fooAll" = internal unnamed_addr global i8* null, align 8
@rubyIdPrecomputed_fooAll = internal unnamed_addr global i64 0, align 8
@str_fooAll = private unnamed_addr constant [7 x i8] c"fooAll\00", align 1
@rubyStrFrozen_fooAll = internal unnamed_addr global i64 0, align 8
@"rubyStrFrozen_test/testdata/compiler/casts.rb" = internal unnamed_addr global i64 0, align 8
@"str_test/testdata/compiler/casts.rb" = private unnamed_addr constant [32 x i8] c"test/testdata/compiler/casts.rb\00", align 1
@str_Object = private unnamed_addr constant [7 x i8] c"Object\00", align 1
@str_cast = private unnamed_addr constant [5 x i8] c"cast\00", align 1
@str_Kernel = private unnamed_addr constant [7 x i8] c"Kernel\00", align 1
@str_T = private unnamed_addr constant [2 x i8] c"T\00", align 1
@ic_call_via_vm_all = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_all = internal unnamed_addr global i64 0, align 8
@str_all = private unnamed_addr constant [4 x i8] c"all\00", align 1
@"stackFramePrecomputed_func_Object#fooAny1" = internal unnamed_addr global i8* null, align 8
@rubyIdPrecomputed_fooAny1 = internal unnamed_addr global i64 0, align 8
@str_fooAny1 = private unnamed_addr constant [8 x i8] c"fooAny1\00", align 1
@str_Integer = private unnamed_addr constant [8 x i8] c"Integer\00", align 1
@ic_call_via_vm_any = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_any = internal unnamed_addr global i64 0, align 8
@str_any = private unnamed_addr constant [4 x i8] c"any\00", align 1
@"str_T.any(Integer, Float)" = private unnamed_addr constant [22 x i8] c"T.any(Integer, Float)\00", align 1
@"stackFramePrecomputed_func_Object#fooAny2" = internal unnamed_addr global i8* null, align 8
@rubyIdPrecomputed_fooAny2 = internal unnamed_addr global i64 0, align 8
@str_fooAny2 = private unnamed_addr constant [8 x i8] c"fooAny2\00", align 1
@ic_call_via_vm_any.1 = internal global %struct.FunctionInlineCache zeroinitializer
@"str_T.any(Float, Integer)" = private unnamed_addr constant [22 x i8] c"T.any(Float, Integer)\00", align 1
@"stackFramePrecomputed_func_Object#fooInt" = internal unnamed_addr global i8* null, align 8
@rubyIdPrecomputed_fooInt = internal unnamed_addr global i64 0, align 8
@str_fooInt = private unnamed_addr constant [7 x i8] c"fooInt\00", align 1
@"str_+" = private unnamed_addr constant [2 x i8] c"+\00", align 1
@"stackFramePrecomputed_func_Object#fooArray" = internal unnamed_addr global i8* null, align 8
@rubyIdPrecomputed_fooArray = internal unnamed_addr global i64 0, align 8
@str_fooArray = private unnamed_addr constant [9 x i8] c"fooArray\00", align 1
@"str_T::Array" = private unnamed_addr constant [9 x i8] c"T::Array\00", align 1
@"ic_call_via_vm_[]" = internal global %struct.FunctionInlineCache zeroinitializer
@"rubyIdPrecomputed_[]" = internal unnamed_addr global i64 0, align 8
@"str_[]" = private unnamed_addr constant [3 x i8] c"[]\00", align 1
@"str_T::Array[Integer]" = private unnamed_addr constant [18 x i8] c"T::Array[Integer]\00", align 1
@"stackFramePrecomputed_func_<root>.<static-init>$153" = internal unnamed_addr global i8* null, align 8
@"rubyIdPrecomputed_<top (required)>" = internal unnamed_addr global i64 0, align 8
@"str_<top (required)>" = private unnamed_addr constant [17 x i8] c"<top (required)>\00", align 1
@"<static-init-locals-storage>" = internal global [0 x i64] zeroinitializer
@"str_T.class_of(<root>)" = private unnamed_addr constant [19 x i8] c"T.class_of(<root>)\00", align 1
@str_keep_def = private unnamed_addr constant [9 x i8] c"keep_def\00", align 1
@ic_call_via_vm_fooInt = internal global %struct.FunctionInlineCache zeroinitializer
@ic_call_via_vm_puts = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_puts = internal unnamed_addr global i64 0, align 8
@str_puts = private unnamed_addr constant [5 x i8] c"puts\00", align 1
@ic_call_via_vm_fooAny1 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_call_via_vm_puts.6 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_call_via_vm_fooAny2 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_call_via_vm_puts.7 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_call_via_vm_fooAll = internal global %struct.FunctionInlineCache zeroinitializer
@ic_call_via_vm_puts.8 = internal global %struct.FunctionInlineCache zeroinitializer
@"str_<build-array>" = private unnamed_addr constant [14 x i8] c"<build-array>\00", align 1
@ic_call_via_vm_fooArray = internal global %struct.FunctionInlineCache zeroinitializer
@ic_call_via_vm_puts.9 = internal global %struct.FunctionInlineCache zeroinitializer
@rb_cObject = external local_unnamed_addr constant i64
@rb_cBasicObject = external local_unnamed_addr constant i64
@rb_mKernel = external local_unnamed_addr constant i64
@guard_epoch_T = linkonce local_unnamed_addr global i64 0
@guarded_const_T = linkonce local_unnamed_addr global i64 0
@rb_cInteger = external local_unnamed_addr constant i64
@rb_cFloat = external local_unnamed_addr constant i64
@"guard_epoch_T::Array" = linkonce local_unnamed_addr global i64 0
@"guarded_const_T::Array" = linkonce local_unnamed_addr global i64 0

; Function Attrs: nounwind ssp uwtable
define weak i8* @sorbet_getBuildSCMRevision() local_unnamed_addr #0 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !4
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* getelementptr inbounds ([95 x i8], [95 x i8]* @.str.1, i64 0, i64 0)) #15
  unreachable
}

; Function Attrs: noreturn
declare void @rb_raise(i64, i8*, ...) local_unnamed_addr #1

; Function Attrs: nounwind ssp uwtable
define weak i32 @sorbet_getIsReleaseBuild() local_unnamed_addr #0 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !4
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* getelementptr inbounds ([93 x i8], [93 x i8]* @.str.2, i64 0, i64 0)) #15
  unreachable
}

declare i64 @rb_fstring_new(i8*, i64) local_unnamed_addr #2

declare void @rb_gc_register_mark_object(i64) local_unnamed_addr #2

declare i64 @rb_ary_new_from_values(i64, i64*) local_unnamed_addr #2

declare i64 @rb_intern2(i8*, i64) local_unnamed_addr #2

declare i64 @rb_id2sym(i64) local_unnamed_addr #2

; Function Attrs: noinline nounwind ssp uwtable
declare i64 @sorbet_getConstant(i8*, i64) local_unnamed_addr #3

declare void @rb_define_method(i64, i8*, i64 (...)*, i32) local_unnamed_addr #2

; Function Attrs: cold noreturn nounwind optsize ssp uwtable
declare void @sorbet_cast_failure(i64, i8*, i8*) local_unnamed_addr #4

; Function Attrs: noreturn nounwind ssp uwtable
declare void @sorbet_raiseArity(i32, i32, i32) local_unnamed_addr #5

; Function Attrs: nounwind ssp uwtable
declare i8* @sorbet_allocateRubyStackFrame(i64, i64, i64, i64, i8*, i32, i32, i32, i64* nocapture readonly, i32) local_unnamed_addr #0

declare i64 @rb_gv_get(i8*) local_unnamed_addr #2

declare i64 @rb_gv_set(i8*, i64) local_unnamed_addr #2

; Function Attrs: nounwind ssp uwtable
declare %struct.rb_control_frame_struct* @sorbet_setRubyStackFrame(i1 zeroext, i32, i8*) local_unnamed_addr #0

; Function Attrs: nounwind readnone
declare i64 @rb_obj_is_kind_of(i64, i64) local_unnamed_addr #6

; Function Attrs: nounwind readnone speculatable
declare { i64, i1 } @llvm.sadd.with.overflow.i64(i64, i64) #7

declare i64 @rb_int2big(i64) local_unnamed_addr #2

; Function Attrs: alwaysinline norecurse nounwind readonly ssp uwtable
declare i64 @sorbet_getConstantEpoch() local_unnamed_addr #8

; Function Attrs: noinline nounwind ssp uwtable
declare i64 @sorbet_callFunc(i64, i64, i32, i64* noalias nocapture, %struct.FunctionInlineCache* nocapture) local_unnamed_addr #3

; Function Attrs: nounwind sspreq uwtable
define i64 @"func_Object#fooAll"(i32 %argc, i64* nocapture readonly %argArray, i64 %selfRaw) #9 !dbg !8 {
functionEntryInitializers:
  %callArgs = alloca [2 x i64], align 8
  %"stackFrame_func_Object#fooAll" = load i8*, i8** @"stackFramePrecomputed_func_Object#fooAll", align 8
  %0 = tail call %struct.rb_control_frame_struct* @sorbet_setRubyStackFrame(i1 false, i32 1, i8* %"stackFrame_func_Object#fooAll")
  %1 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %0, i64 0, i32 0
  %2 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %0, i64 0, i32 2
  %3 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %2, align 8, !tbaa !12
  %4 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %3, i64 0, i32 2
  %5 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %4, align 8, !tbaa !15
  %6 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %5, i64 0, i32 2
  %7 = load i64*, i64** %6, align 8, !tbaa !17
  %8 = getelementptr inbounds i64, i64* %7, i64 1
  store i64* %8, i64** %1, align 8, !tbaa !27
  %rubyId_all = load i64, i64* @rubyIdPrecomputed_all, align 8, !dbg !28
  %9 = icmp eq i32 %argc, 1, !dbg !29
  br i1 %9, label %fillRequiredArgs, label %argCountFailBlock, !dbg !29, !prof !30

argCountFailBlock:                                ; preds = %functionEntryInitializers
  tail call void @sorbet_raiseArity(i32 %argc, i32 1, i32 1), !dbg !29
  unreachable, !dbg !29

fillRequiredArgs:                                 ; preds = %functionEntryInitializers
  %rawArg_arg = load i64, i64* %argArray, align 8, !dbg !29
  %10 = load i64, i64* @rb_cObject, align 8, !dbg !29
  %11 = tail call i64 @rb_obj_is_kind_of(i64 %selfRaw, i64 %10) #6, !dbg !29
  %12 = icmp eq i64 %11, 20, !dbg !29
  br i1 %12, label %typeTestSuccess, label %codeRepl30, !dbg !29, !prof !31

typeTestSuccess:                                  ; preds = %fillRequiredArgs
  %13 = getelementptr inbounds i64, i64* %7, i64 2
  store i64* %13, i64** %1, align 8, !tbaa !27
  %14 = load i64, i64* @rb_cBasicObject, align 8, !dbg !28
  %callArgs0Addr = getelementptr inbounds [2 x i64], [2 x i64]* %callArgs, i64 0, i64 0, !dbg !28
  store i64 %14, i64* %callArgs0Addr, align 8, !dbg !28
  %15 = load i64, i64* @rb_mKernel, align 8, !dbg !28
  %callArgs1Addr = getelementptr inbounds [2 x i64], [2 x i64]* %callArgs, i64 0, i64 1, !dbg !28
  store i64 %15, i64* %callArgs1Addr, align 8, !dbg !28
  %16 = load i64, i64* @guard_epoch_T, align 8, !dbg !28
  %17 = tail call i64 @sorbet_getConstantEpoch(), !dbg !28
  %needTakeSlowPath = icmp eq i64 %16, %17, !dbg !28
  br i1 %needTakeSlowPath, label %19, label %18, !dbg !28, !prof !32

18:                                               ; preds = %typeTestSuccess
  tail call void @const_recompute_T() #14, !dbg !28
  br label %19, !dbg !28

19:                                               ; preds = %typeTestSuccess, %18
  %20 = load i64, i64* @guarded_const_T, align 8, !dbg !28
  %21 = load i64, i64* @guard_epoch_T, align 8, !dbg !28
  %22 = tail call i64 @sorbet_getConstantEpoch(), !dbg !28
  %guardUpdated = icmp eq i64 %21, %22, !dbg !28
  tail call void @llvm.assume(i1 %guardUpdated), !dbg !28
  %call_via_vm_all = call i64 @sorbet_callFunc(i64 %20, i64 %rubyId_all, i32 2, i64* nonnull %callArgs0Addr, %struct.FunctionInlineCache* nonnull @ic_call_via_vm_all), !dbg !28
  %23 = tail call i64 @rb_obj_is_kind_of(i64 %rawArg_arg, i64 %15) #6, !dbg !33
  %24 = icmp eq i64 %23, 20, !dbg !33
  br i1 %24, label %typeTestSuccess21, label %codeRepl, !dbg !33, !prof !31

codeRepl30:                                       ; preds = %fillRequiredArgs
  tail call fastcc void @"func_Object#fooAll.cold.2"(i64 %selfRaw) #16, !dbg !29
  unreachable

typeTestSuccess21:                                ; preds = %19
  ret i64 %rawArg_arg

codeRepl:                                         ; preds = %19
  tail call fastcc void @"func_Object#fooAll.cold.1"(i64 %rawArg_arg) #16, !dbg !33
  unreachable
}

; Function Attrs: nounwind sspreq uwtable
define i64 @"func_Object#fooAny1"(i32 %argc, i64* nocapture readonly %argArray, i64 %selfRaw) #9 !dbg !34 {
functionEntryInitializers:
  %callArgs = alloca [2 x i64], align 8
  %"stackFrame_func_Object#fooAny1" = load i8*, i8** @"stackFramePrecomputed_func_Object#fooAny1", align 8
  %0 = tail call %struct.rb_control_frame_struct* @sorbet_setRubyStackFrame(i1 false, i32 1, i8* %"stackFrame_func_Object#fooAny1")
  %1 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %0, i64 0, i32 0
  %2 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %0, i64 0, i32 2
  %3 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %2, align 8, !tbaa !12
  %4 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %3, i64 0, i32 2
  %5 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %4, align 8, !tbaa !15
  %6 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %5, i64 0, i32 2
  %7 = load i64*, i64** %6, align 8, !tbaa !17
  %8 = getelementptr inbounds i64, i64* %7, i64 1
  store i64* %8, i64** %1, align 8, !tbaa !27
  %rubyId_any = load i64, i64* @rubyIdPrecomputed_any, align 8, !dbg !35
  %9 = icmp eq i32 %argc, 1, !dbg !36
  br i1 %9, label %fillRequiredArgs, label %argCountFailBlock, !dbg !36, !prof !30

argCountFailBlock:                                ; preds = %functionEntryInitializers
  tail call void @sorbet_raiseArity(i32 %argc, i32 1, i32 1), !dbg !36
  unreachable, !dbg !36

fillRequiredArgs:                                 ; preds = %functionEntryInitializers
  %rawArg_arg = load i64, i64* %argArray, align 8, !dbg !36
  %10 = load i64, i64* @rb_cObject, align 8, !dbg !36
  %11 = tail call i64 @rb_obj_is_kind_of(i64 %selfRaw, i64 %10) #6, !dbg !36
  %12 = icmp eq i64 %11, 20, !dbg !36
  br i1 %12, label %typeTestSuccess, label %codeRepl34, !dbg !36, !prof !31

typeTestSuccess:                                  ; preds = %fillRequiredArgs
  %13 = getelementptr inbounds i64, i64* %7, i64 2
  store i64* %13, i64** %1, align 8, !tbaa !27
  %14 = load i64, i64* @rb_cInteger, align 8, !dbg !35
  %callArgs0Addr = getelementptr inbounds [2 x i64], [2 x i64]* %callArgs, i64 0, i64 0, !dbg !35
  store i64 %14, i64* %callArgs0Addr, align 8, !dbg !35
  %15 = load i64, i64* @rb_cFloat, align 8, !dbg !35
  %callArgs1Addr = getelementptr inbounds [2 x i64], [2 x i64]* %callArgs, i64 0, i64 1, !dbg !35
  store i64 %15, i64* %callArgs1Addr, align 8, !dbg !35
  %16 = load i64, i64* @guard_epoch_T, align 8, !dbg !35
  %17 = tail call i64 @sorbet_getConstantEpoch(), !dbg !35
  %needTakeSlowPath = icmp eq i64 %16, %17, !dbg !35
  br i1 %needTakeSlowPath, label %19, label %18, !dbg !35, !prof !32

18:                                               ; preds = %typeTestSuccess
  tail call void @const_recompute_T() #14, !dbg !35
  br label %19, !dbg !35

19:                                               ; preds = %typeTestSuccess, %18
  %20 = load i64, i64* @guarded_const_T, align 8, !dbg !35
  %21 = load i64, i64* @guard_epoch_T, align 8, !dbg !35
  %22 = tail call i64 @sorbet_getConstantEpoch(), !dbg !35
  %guardUpdated = icmp eq i64 %21, %22, !dbg !35
  tail call void @llvm.assume(i1 %guardUpdated), !dbg !35
  %call_via_vm_any = call i64 @sorbet_callFunc(i64 %20, i64 %rubyId_any, i32 2, i64* nonnull %callArgs0Addr, %struct.FunctionInlineCache* nonnull @ic_call_via_vm_any), !dbg !35
  %23 = and i64 %rawArg_arg, 1, !dbg !37
  %24 = icmp ne i64 %23, 0, !dbg !37
  %25 = and i64 %rawArg_arg, 3, !dbg !37
  %26 = icmp eq i64 %25, 2, !dbg !37
  %or.cond = or i1 %24, %26, !dbg !37
  br i1 %or.cond, label %typeTestSuccess21, label %27, !dbg !37

codeRepl34:                                       ; preds = %fillRequiredArgs
  tail call void @sorbet_cast_failure(i64 %selfRaw, i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_cast, i64 0, i64 0), i8* getelementptr inbounds ([7 x i8], [7 x i8]* @str_Object, i64 0, i64 0)) #14, !dbg !38
  unreachable, !dbg !38

27:                                               ; preds = %19
  %28 = and i64 %rawArg_arg, 7, !dbg !37
  %29 = icmp ne i64 %28, 0, !dbg !37
  %30 = and i64 %rawArg_arg, -9, !dbg !37
  %31 = icmp eq i64 %30, 0, !dbg !37
  %32 = or i1 %29, %31, !dbg !37
  br i1 %32, label %codeRepl, label %orContinue, !dbg !37, !prof !40

orContinue:                                       ; preds = %27
  %33 = inttoptr i64 %rawArg_arg to %struct.RBasic*, !dbg !37
  %34 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %33, i64 0, i32 0, !dbg !37
  %35 = load i64, i64* %34, align 8, !dbg !37, !tbaa !41
  %36 = and i64 %35, 31, !dbg !37
  %37 = icmp eq i64 %36, 4, !dbg !37
  br i1 %37, label %typeTestSuccess21, label %codeRepl, !dbg !37, !prof !31

typeTestSuccess21:                                ; preds = %19, %orContinue
  ret i64 %rawArg_arg

codeRepl:                                         ; preds = %orContinue, %27
  tail call fastcc void @"func_Object#fooAny1.cold.1"(i64 %rawArg_arg) #16, !dbg !37
  unreachable
}

; Function Attrs: nounwind sspreq uwtable
define i64 @"func_Object#fooAny2"(i32 %argc, i64* nocapture readonly %argArray, i64 %selfRaw) #9 !dbg !43 {
functionEntryInitializers:
  %callArgs = alloca [2 x i64], align 8
  %"stackFrame_func_Object#fooAny2" = load i8*, i8** @"stackFramePrecomputed_func_Object#fooAny2", align 8
  %0 = tail call %struct.rb_control_frame_struct* @sorbet_setRubyStackFrame(i1 false, i32 1, i8* %"stackFrame_func_Object#fooAny2")
  %1 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %0, i64 0, i32 0
  %2 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %0, i64 0, i32 2
  %3 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %2, align 8, !tbaa !12
  %4 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %3, i64 0, i32 2
  %5 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %4, align 8, !tbaa !15
  %6 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %5, i64 0, i32 2
  %7 = load i64*, i64** %6, align 8, !tbaa !17
  %8 = getelementptr inbounds i64, i64* %7, i64 1
  store i64* %8, i64** %1, align 8, !tbaa !27
  %rubyId_any = load i64, i64* @rubyIdPrecomputed_any, align 8, !dbg !44
  %9 = icmp eq i32 %argc, 1, !dbg !45
  br i1 %9, label %fillRequiredArgs, label %argCountFailBlock, !dbg !45, !prof !30

argCountFailBlock:                                ; preds = %functionEntryInitializers
  tail call void @sorbet_raiseArity(i32 %argc, i32 1, i32 1), !dbg !45
  unreachable, !dbg !45

fillRequiredArgs:                                 ; preds = %functionEntryInitializers
  %rawArg_arg = load i64, i64* %argArray, align 8, !dbg !45
  %10 = load i64, i64* @rb_cObject, align 8, !dbg !45
  %11 = tail call i64 @rb_obj_is_kind_of(i64 %selfRaw, i64 %10) #6, !dbg !45
  %12 = icmp eq i64 %11, 20, !dbg !45
  br i1 %12, label %typeTestSuccess, label %codeRepl32, !dbg !45, !prof !31

typeTestSuccess:                                  ; preds = %fillRequiredArgs
  %13 = getelementptr inbounds i64, i64* %7, i64 2
  store i64* %13, i64** %1, align 8, !tbaa !27
  %14 = load i64, i64* @rb_cFloat, align 8, !dbg !44
  %callArgs0Addr = getelementptr inbounds [2 x i64], [2 x i64]* %callArgs, i64 0, i64 0, !dbg !44
  store i64 %14, i64* %callArgs0Addr, align 8, !dbg !44
  %15 = load i64, i64* @rb_cInteger, align 8, !dbg !44
  %callArgs1Addr = getelementptr inbounds [2 x i64], [2 x i64]* %callArgs, i64 0, i64 1, !dbg !44
  store i64 %15, i64* %callArgs1Addr, align 8, !dbg !44
  %16 = load i64, i64* @guard_epoch_T, align 8, !dbg !44
  %17 = tail call i64 @sorbet_getConstantEpoch(), !dbg !44
  %needTakeSlowPath = icmp eq i64 %16, %17, !dbg !44
  br i1 %needTakeSlowPath, label %19, label %18, !dbg !44, !prof !32

18:                                               ; preds = %typeTestSuccess
  tail call void @const_recompute_T() #14, !dbg !44
  br label %19, !dbg !44

19:                                               ; preds = %typeTestSuccess, %18
  %20 = load i64, i64* @guarded_const_T, align 8, !dbg !44
  %21 = load i64, i64* @guard_epoch_T, align 8, !dbg !44
  %22 = tail call i64 @sorbet_getConstantEpoch(), !dbg !44
  %guardUpdated = icmp eq i64 %21, %22, !dbg !44
  tail call void @llvm.assume(i1 %guardUpdated), !dbg !44
  %call_via_vm_any = call i64 @sorbet_callFunc(i64 %20, i64 %rubyId_any, i32 2, i64* nonnull %callArgs0Addr, %struct.FunctionInlineCache* nonnull @ic_call_via_vm_any.1), !dbg !44
  %23 = and i64 %rawArg_arg, 3, !dbg !46
  %24 = icmp eq i64 %23, 2, !dbg !46
  br i1 %24, label %typeTestSuccess21, label %25, !dbg !46

25:                                               ; preds = %19
  %26 = and i64 %rawArg_arg, 7, !dbg !46
  %27 = icmp ne i64 %26, 0, !dbg !46
  %28 = and i64 %rawArg_arg, -9, !dbg !46
  %29 = icmp eq i64 %28, 0, !dbg !46
  %30 = or i1 %27, %29, !dbg !46
  br i1 %30, label %orContinue, label %sorbet_isa_Float.exit, !dbg !46

sorbet_isa_Float.exit:                            ; preds = %25
  %31 = inttoptr i64 %rawArg_arg to %struct.RBasic*, !dbg !46
  %32 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %31, i64 0, i32 0, !dbg !46
  %33 = load i64, i64* %32, align 8, !dbg !46, !tbaa !41
  %34 = and i64 %33, 31, !dbg !46
  %35 = icmp eq i64 %34, 4, !dbg !46
  br i1 %35, label %typeTestSuccess21, label %orContinue, !dbg !46

codeRepl32:                                       ; preds = %fillRequiredArgs
  tail call void @sorbet_cast_failure(i64 %selfRaw, i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_cast, i64 0, i64 0), i8* getelementptr inbounds ([7 x i8], [7 x i8]* @str_Object, i64 0, i64 0)) #14, !dbg !47
  unreachable, !dbg !47

orContinue:                                       ; preds = %25, %sorbet_isa_Float.exit
  %36 = and i64 %rawArg_arg, 1, !dbg !46
  %37 = icmp eq i64 %36, 0, !dbg !46
  br i1 %37, label %codeRepl, label %typeTestSuccess21, !dbg !46, !prof !49

typeTestSuccess21:                                ; preds = %orContinue, %19, %sorbet_isa_Float.exit
  ret i64 %rawArg_arg

codeRepl:                                         ; preds = %orContinue
  tail call fastcc void @"func_Object#fooAny2.cold.1"(i64 %rawArg_arg) #16, !dbg !46
  unreachable
}

; Function Attrs: nounwind sspreq uwtable
define i64 @"func_Object#fooInt"(i32 %argc, i64* nocapture readonly %argArray, i64 %selfRaw) #9 !dbg !50 {
functionEntryInitializers:
  %"stackFrame_func_Object#fooInt" = load i8*, i8** @"stackFramePrecomputed_func_Object#fooInt", align 8
  %0 = tail call %struct.rb_control_frame_struct* @sorbet_setRubyStackFrame(i1 false, i32 1, i8* %"stackFrame_func_Object#fooInt")
  %1 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %0, i64 0, i32 0
  %2 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %0, i64 0, i32 2
  %3 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %2, align 8, !tbaa !12
  %4 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %3, i64 0, i32 2
  %5 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %4, align 8, !tbaa !15
  %6 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %5, i64 0, i32 2
  %7 = load i64*, i64** %6, align 8, !tbaa !17
  %8 = getelementptr inbounds i64, i64* %7, i64 1
  store i64* %8, i64** %1, align 8, !tbaa !27
  %9 = icmp eq i32 %argc, 1, !dbg !51
  br i1 %9, label %fillRequiredArgs, label %argCountFailBlock, !dbg !51, !prof !30

argCountFailBlock:                                ; preds = %functionEntryInitializers
  tail call void @sorbet_raiseArity(i32 %argc, i32 1, i32 1), !dbg !51
  unreachable, !dbg !51

fillRequiredArgs:                                 ; preds = %functionEntryInitializers
  %rawArg_arg = load i64, i64* %argArray, align 8, !dbg !51
  %10 = load i64, i64* @rb_cObject, align 8, !dbg !51
  %11 = tail call i64 @rb_obj_is_kind_of(i64 %selfRaw, i64 %10) #6, !dbg !51
  %12 = icmp eq i64 %11, 20, !dbg !51
  br i1 %12, label %typeTestSuccess, label %codeRepl52, !dbg !51, !prof !31

typeTestSuccess:                                  ; preds = %fillRequiredArgs
  %13 = getelementptr inbounds i64, i64* %7, i64 2
  store i64* %13, i64** %1, align 8, !tbaa !27
  %14 = and i64 %rawArg_arg, 1, !dbg !52
  %15 = icmp eq i64 %14, 0, !dbg !52
  br i1 %15, label %codeRepl, label %typeTestSuccess33, !dbg !52, !prof !49

codeRepl52:                                       ; preds = %fillRequiredArgs
  tail call void @sorbet_cast_failure(i64 %selfRaw, i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_cast, i64 0, i64 0), i8* getelementptr inbounds ([7 x i8], [7 x i8]* @str_Object, i64 0, i64 0)) #14, !dbg !53
  unreachable, !dbg !53

codeRepl:                                         ; preds = %typeTestSuccess
  tail call fastcc void @"func_Object#fooInt.cold.1"(i64 %rawArg_arg) #16, !dbg !52
  unreachable

typeTestSuccess33:                                ; preds = %typeTestSuccess
  %16 = add nsw i64 %rawArg_arg, -1, !dbg !52
  %17 = tail call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %rawArg_arg, i64 %16) #14, !dbg !52
  %18 = extractvalue { i64, i1 } %17, 1, !dbg !52
  %19 = extractvalue { i64, i1 } %17, 0, !dbg !52
  br i1 %18, label %20, label %sorbet_rb_int_plus.exit, !dbg !52

20:                                               ; preds = %typeTestSuccess33
  %21 = ashr i64 %19, 1, !dbg !52
  %22 = xor i64 %21, -9223372036854775808, !dbg !52
  %23 = tail call i64 @rb_int2big(i64 %22) #14, !dbg !52
  br label %sorbet_rb_int_plus.exit, !dbg !52

sorbet_rb_int_plus.exit:                          ; preds = %20, %typeTestSuccess33
  %24 = phi i64 [ %23, %20 ], [ %19, %typeTestSuccess33 ], !dbg !52
  ret i64 %24
}

; Function Attrs: nounwind sspreq uwtable
define i64 @"func_Object#fooArray"(i32 %argc, i64* nocapture readonly %argArray, i64 %selfRaw) #9 !dbg !55 {
functionEntryInitializers:
  %callArgs = alloca [1 x i64], align 8
  %"stackFrame_func_Object#fooArray" = load i8*, i8** @"stackFramePrecomputed_func_Object#fooArray", align 8
  %0 = tail call %struct.rb_control_frame_struct* @sorbet_setRubyStackFrame(i1 false, i32 1, i8* %"stackFrame_func_Object#fooArray")
  %1 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %0, i64 0, i32 0
  %2 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %0, i64 0, i32 2
  %3 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %2, align 8, !tbaa !12
  %4 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %3, i64 0, i32 2
  %5 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %4, align 8, !tbaa !15
  %6 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %5, i64 0, i32 2
  %7 = load i64*, i64** %6, align 8, !tbaa !17
  %8 = getelementptr inbounds i64, i64* %7, i64 1
  store i64* %8, i64** %1, align 8, !tbaa !27
  %"rubyId_[]" = load i64, i64* @"rubyIdPrecomputed_[]", align 8, !dbg !56
  %9 = icmp eq i32 %argc, 1, !dbg !57
  br i1 %9, label %fillRequiredArgs, label %argCountFailBlock, !dbg !57, !prof !30

argCountFailBlock:                                ; preds = %functionEntryInitializers
  tail call void @sorbet_raiseArity(i32 %argc, i32 1, i32 1), !dbg !57
  unreachable, !dbg !57

fillRequiredArgs:                                 ; preds = %functionEntryInitializers
  %rawArg_arg = load i64, i64* %argArray, align 8, !dbg !57
  %10 = load i64, i64* @rb_cObject, align 8, !dbg !57
  %11 = tail call i64 @rb_obj_is_kind_of(i64 %selfRaw, i64 %10) #6, !dbg !57
  %12 = icmp eq i64 %11, 20, !dbg !57
  br i1 %12, label %typeTestSuccess, label %codeRepl30, !dbg !57, !prof !31

typeTestSuccess:                                  ; preds = %fillRequiredArgs
  %13 = getelementptr inbounds i64, i64* %7, i64 2
  store i64* %13, i64** %1, align 8, !tbaa !27
  %14 = load i64, i64* @rb_cInteger, align 8, !dbg !56
  %callArgs0Addr = getelementptr inbounds [1 x i64], [1 x i64]* %callArgs, i64 0, i64 0, !dbg !56
  store i64 %14, i64* %callArgs0Addr, align 8, !dbg !56
  %15 = load i64, i64* @"guard_epoch_T::Array", align 8, !dbg !56
  %16 = tail call i64 @sorbet_getConstantEpoch(), !dbg !56
  %needTakeSlowPath = icmp eq i64 %15, %16, !dbg !56
  br i1 %needTakeSlowPath, label %18, label %17, !dbg !56, !prof !32

17:                                               ; preds = %typeTestSuccess
  tail call void @"const_recompute_T::Array"() #14, !dbg !56
  br label %18, !dbg !56

18:                                               ; preds = %typeTestSuccess, %17
  %19 = load i64, i64* @"guarded_const_T::Array", align 8, !dbg !56
  %20 = load i64, i64* @"guard_epoch_T::Array", align 8, !dbg !56
  %21 = tail call i64 @sorbet_getConstantEpoch(), !dbg !56
  %guardUpdated = icmp eq i64 %20, %21, !dbg !56
  tail call void @llvm.assume(i1 %guardUpdated), !dbg !56
  %"call_via_vm_[]" = call i64 @sorbet_callFunc(i64 %19, i64 %"rubyId_[]", i32 1, i64* nonnull %callArgs0Addr, %struct.FunctionInlineCache* nonnull @"ic_call_via_vm_[]"), !dbg !56
  %22 = and i64 %rawArg_arg, 7, !dbg !58
  %23 = icmp ne i64 %22, 0, !dbg !58
  %24 = and i64 %rawArg_arg, -9, !dbg !58
  %25 = icmp eq i64 %24, 0, !dbg !58
  %26 = or i1 %23, %25, !dbg !58
  br i1 %26, label %codeRepl, label %sorbet_isa_Array.exit, !dbg !58, !prof !40

sorbet_isa_Array.exit:                            ; preds = %18
  %27 = inttoptr i64 %rawArg_arg to %struct.RBasic*, !dbg !58
  %28 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %27, i64 0, i32 0, !dbg !58
  %29 = load i64, i64* %28, align 8, !dbg !58, !tbaa !41
  %30 = and i64 %29, 31, !dbg !58
  %31 = icmp eq i64 %30, 7, !dbg !58
  br i1 %31, label %typeTestSuccess21, label %codeRepl, !dbg !58, !prof !31

codeRepl30:                                       ; preds = %fillRequiredArgs
  tail call void @sorbet_cast_failure(i64 %selfRaw, i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_cast, i64 0, i64 0), i8* getelementptr inbounds ([7 x i8], [7 x i8]* @str_Object, i64 0, i64 0)) #14, !dbg !59
  unreachable, !dbg !59

typeTestSuccess21:                                ; preds = %sorbet_isa_Array.exit
  ret i64 %rawArg_arg

codeRepl:                                         ; preds = %sorbet_isa_Array.exit, %18
  tail call fastcc void @"func_Object#fooArray.cold.1"(i64 %rawArg_arg) #16, !dbg !58
  unreachable
}

; Function Attrs: nounwind sspreq
define void @Init_casts() local_unnamed_addr #10 {
entry:
  %locals1.i.i = alloca [0 x i64], align 8
  %callArgs.i = alloca [2 x i64], align 8
  %0 = tail call i64 @rb_gv_get(i8* getelementptr inbounds ([24 x i8], [24 x i8]* @.str.17, i64 0, i64 0)) #14
  %1 = and i64 %0, 7
  %2 = icmp ne i64 %1, 0
  %3 = and i64 %0, -9
  %4 = icmp eq i64 %3, 0
  %5 = or i1 %2, %4
  br i1 %5, label %12, label %6

6:                                                ; preds = %entry
  %7 = inttoptr i64 %0 to %struct.RBasic*
  %8 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %7, i64 0, i32 0
  %9 = load i64, i64* %8, align 8, !tbaa !41
  %10 = and i64 %9, 31
  %11 = icmp eq i64 %10, 5
  br i1 %11, label %sorbet_readRealpath.exit, label %12

12:                                               ; preds = %6, %entry
  %13 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !4
  tail call void (i64, i8*, ...) @rb_raise(i64 %13, i8* getelementptr inbounds ([63 x i8], [63 x i8]* @.str.18, i64 0, i64 0)) #15
  unreachable

sorbet_readRealpath.exit:                         ; preds = %6
  %14 = tail call i64 @rb_gv_set(i8* getelementptr inbounds ([24 x i8], [24 x i8]* @.str.17, i64 0, i64 0), i64 8) #14
  %15 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([7 x i8], [7 x i8]* @str_fooAll, i64 0, i64 0), i64 6) #14
  store i64 %15, i64* @rubyIdPrecomputed_fooAll, align 8
  %16 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_all, i64 0, i64 0), i64 3) #14
  store i64 %16, i64* @rubyIdPrecomputed_all, align 8
  %17 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([8 x i8], [8 x i8]* @str_fooAny1, i64 0, i64 0), i64 7) #14
  store i64 %17, i64* @rubyIdPrecomputed_fooAny1, align 8
  %18 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_any, i64 0, i64 0), i64 3) #14
  store i64 %18, i64* @rubyIdPrecomputed_any, align 8
  %19 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([8 x i8], [8 x i8]* @str_fooAny2, i64 0, i64 0), i64 7) #14
  store i64 %19, i64* @rubyIdPrecomputed_fooAny2, align 8
  %20 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([7 x i8], [7 x i8]* @str_fooInt, i64 0, i64 0), i64 6) #14
  store i64 %20, i64* @rubyIdPrecomputed_fooInt, align 8
  %21 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([2 x i8], [2 x i8]* @"str_+", i64 0, i64 0), i64 1) #14
  %22 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([9 x i8], [9 x i8]* @str_fooArray, i64 0, i64 0), i64 8) #14
  store i64 %22, i64* @rubyIdPrecomputed_fooArray, align 8
  %23 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([3 x i8], [3 x i8]* @"str_[]", i64 0, i64 0), i64 2) #14
  store i64 %23, i64* @"rubyIdPrecomputed_[]", align 8
  %24 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 16) #14
  store i64 %24, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %25 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([9 x i8], [9 x i8]* @str_keep_def, i64 0, i64 0), i64 8) #14
  %26 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_puts, i64 0, i64 0), i64 4) #14
  store i64 %26, i64* @rubyIdPrecomputed_puts, align 8
  %27 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([14 x i8], [14 x i8]* @"str_<build-array>", i64 0, i64 0), i64 13) #14
  %28 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([7 x i8], [7 x i8]* @str_fooAll, i64 0, i64 0), i64 6) #14
  tail call void @rb_gc_register_mark_object(i64 %28) #14
  store i64 %28, i64* @rubyStrFrozen_fooAll, align 8
  %29 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([32 x i8], [32 x i8]* @"str_test/testdata/compiler/casts.rb", i64 0, i64 0), i64 31) #14
  tail call void @rb_gc_register_mark_object(i64 %29) #14
  store i64 %29, i64* @"rubyStrFrozen_test/testdata/compiler/casts.rb", align 8
  %30 = bitcast [0 x i64]* %locals1.i.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 0, i8* nonnull %30) #14
  %rubyId_fooAll.i.i = load i64, i64* @rubyIdPrecomputed_fooAll, align 8
  %rubyStr_fooAll.i.i = load i64, i64* @rubyStrFrozen_fooAll, align 8
  %locals1.sub.i.i = getelementptr inbounds [0 x i64], [0 x i64]* %locals1.i.i, i64 0, i64 0
  %31 = call i8* @sorbet_allocateRubyStackFrame(i64 %rubyStr_fooAll.i.i, i64 %rubyId_fooAll.i.i, i64 %29, i64 %0, i8* null, i32 1, i32 5, i32 7, i64* nonnull %locals1.sub.i.i, i32 0) #14
  store i8* %31, i8** @"stackFramePrecomputed_func_Object#fooAll", align 8
  call void @llvm.lifetime.end.p0i8(i64 0, i8* nonnull %30) #14
  %32 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([8 x i8], [8 x i8]* @str_fooAny1, i64 0, i64 0), i64 7) #14
  tail call void @rb_gc_register_mark_object(i64 %32) #14
  call void @llvm.lifetime.start.p0i8(i64 0, i8* nonnull %30) #14
  %rubyId_fooAny1.i.i = load i64, i64* @rubyIdPrecomputed_fooAny1, align 8
  %"rubyStr_test/testdata/compiler/casts.rb.i2.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/casts.rb", align 8
  %33 = call i8* @sorbet_allocateRubyStackFrame(i64 %32, i64 %rubyId_fooAny1.i.i, i64 %"rubyStr_test/testdata/compiler/casts.rb.i2.i", i64 %0, i8* null, i32 1, i32 9, i32 11, i64* nonnull %locals1.sub.i.i, i32 0) #14
  store i8* %33, i8** @"stackFramePrecomputed_func_Object#fooAny1", align 8
  call void @llvm.lifetime.end.p0i8(i64 0, i8* nonnull %30) #14
  %34 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([8 x i8], [8 x i8]* @str_fooAny2, i64 0, i64 0), i64 7) #14
  tail call void @rb_gc_register_mark_object(i64 %34) #14
  call void @llvm.lifetime.start.p0i8(i64 0, i8* nonnull %30) #14
  %rubyId_fooAny2.i.i = load i64, i64* @rubyIdPrecomputed_fooAny2, align 8
  %"rubyStr_test/testdata/compiler/casts.rb.i5.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/casts.rb", align 8
  %35 = call i8* @sorbet_allocateRubyStackFrame(i64 %34, i64 %rubyId_fooAny2.i.i, i64 %"rubyStr_test/testdata/compiler/casts.rb.i5.i", i64 %0, i8* null, i32 1, i32 13, i32 15, i64* nonnull %locals1.sub.i.i, i32 0) #14
  store i8* %35, i8** @"stackFramePrecomputed_func_Object#fooAny2", align 8
  call void @llvm.lifetime.end.p0i8(i64 0, i8* nonnull %30) #14
  %36 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([7 x i8], [7 x i8]* @str_fooInt, i64 0, i64 0), i64 6) #14
  tail call void @rb_gc_register_mark_object(i64 %36) #14
  call void @llvm.lifetime.start.p0i8(i64 0, i8* nonnull %30) #14
  %rubyId_fooInt.i.i = load i64, i64* @rubyIdPrecomputed_fooInt, align 8
  %"rubyStr_test/testdata/compiler/casts.rb.i8.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/casts.rb", align 8
  %37 = call i8* @sorbet_allocateRubyStackFrame(i64 %36, i64 %rubyId_fooInt.i.i, i64 %"rubyStr_test/testdata/compiler/casts.rb.i8.i", i64 %0, i8* null, i32 1, i32 17, i32 19, i64* nonnull %locals1.sub.i.i, i32 0) #14
  store i8* %37, i8** @"stackFramePrecomputed_func_Object#fooInt", align 8
  call void @llvm.lifetime.end.p0i8(i64 0, i8* nonnull %30) #14
  %38 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([9 x i8], [9 x i8]* @str_fooArray, i64 0, i64 0), i64 8) #14
  tail call void @rb_gc_register_mark_object(i64 %38) #14
  call void @llvm.lifetime.start.p0i8(i64 0, i8* nonnull %30) #14
  %rubyId_fooArray.i.i = load i64, i64* @rubyIdPrecomputed_fooArray, align 8
  %"rubyStr_test/testdata/compiler/casts.rb.i11.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/casts.rb", align 8
  %39 = call i8* @sorbet_allocateRubyStackFrame(i64 %38, i64 %rubyId_fooArray.i.i, i64 %"rubyStr_test/testdata/compiler/casts.rb.i11.i", i64 %0, i8* null, i32 1, i32 21, i32 23, i64* nonnull %locals1.sub.i.i, i32 0) #14
  store i8* %39, i8** @"stackFramePrecomputed_func_Object#fooArray", align 8
  call void @llvm.lifetime.end.p0i8(i64 0, i8* nonnull %30) #14
  %40 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 16) #14
  tail call void @rb_gc_register_mark_object(i64 %40) #14
  %"rubyId_<top (required)>.i.i" = load i64, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %"rubyStr_test/testdata/compiler/casts.rb.i13.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/casts.rb", align 8
  %41 = tail call i8* @sorbet_allocateRubyStackFrame(i64 %40, i64 %"rubyId_<top (required)>.i.i", i64 %"rubyStr_test/testdata/compiler/casts.rb.i13.i", i64 %0, i8* null, i32 1, i32 1, i32 29, i64* getelementptr inbounds ([0 x i64], [0 x i64]* @"<static-init-locals-storage>", i64 0, i64 0), i32 0) #14
  store i8* %41, i8** @"stackFramePrecomputed_func_<root>.<static-init>$153", align 8
  %42 = load %struct.rb_vm_struct*, %struct.rb_vm_struct** @ruby_current_vm_ptr, align 8, !tbaa !27
  %43 = getelementptr inbounds %struct.rb_vm_struct, %struct.rb_vm_struct* %42, i64 0, i32 17
  %44 = load i64, i64* %43, align 8, !tbaa !61
  %45 = bitcast [2 x i64]* %callArgs.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 16, i8* nonnull %45)
  %46 = tail call %struct.rb_control_frame_struct* @sorbet_setRubyStackFrame(i1 false, i32 1, i8* %41) #14
  %47 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %46, i64 0, i32 0
  %48 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %46, i64 0, i32 2
  %49 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %48, align 8, !tbaa !12
  %50 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %49, i64 0, i32 2
  %51 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %50, align 8, !tbaa !15
  %52 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %51, i64 0, i32 2
  %53 = load i64*, i64** %52, align 8, !tbaa !17
  %54 = getelementptr inbounds i64, i64* %53, i64 5
  store i64* %54, i64** %47, align 8, !tbaa !27
  %rubyId_fooAll.i = load i64, i64* @rubyIdPrecomputed_fooAll, align 8, !dbg !70
  %rubyId_fooAny1.i = load i64, i64* @rubyIdPrecomputed_fooAny1, align 8, !dbg !72
  %rubyId_fooAny2.i = load i64, i64* @rubyIdPrecomputed_fooAny2, align 8, !dbg !73
  %rubyId_fooInt.i = load i64, i64* @rubyIdPrecomputed_fooInt, align 8, !dbg !74
  %rubyId_fooArray.i = load i64, i64* @rubyIdPrecomputed_fooArray, align 8, !dbg !75
  %rubyId_puts.i = load i64, i64* @rubyIdPrecomputed_puts, align 8, !dbg !76
  %55 = load %struct.rb_vm_struct*, %struct.rb_vm_struct** @ruby_current_vm_ptr, align 8, !dbg !70, !tbaa !27
  %56 = getelementptr inbounds %struct.rb_vm_struct, %struct.rb_vm_struct* %55, i64 0, i32 17, !dbg !70
  %57 = load i64, i64* %56, align 8, !dbg !70, !tbaa !61
  %58 = icmp eq i64 %57, %44, !dbg !70
  br i1 %58, label %"func_<root>.<static-init>$153.exit", label %codeRepl, !dbg !70, !prof !31

codeRepl:                                         ; preds = %sorbet_readRealpath.exit
  tail call fastcc void @Init_casts.cold.1(i64 %44) #16
  unreachable

"func_<root>.<static-init>$153.exit":             ; preds = %sorbet_readRealpath.exit
  %rawSym.i = tail call i64 @rb_id2sym(i64 %rubyId_fooAll.i) #14, !dbg !70
  %59 = load i64, i64* @rb_cObject, align 8, !dbg !70
  tail call void @rb_define_method(i64 %59, i8* getelementptr inbounds ([7 x i8], [7 x i8]* @str_fooAll, i64 0, i64 0), i64 (...)* bitcast (i64 (i32, i64*, i64)* @"func_Object#fooAll" to i64 (...)*), i32 -1) #14, !dbg !70
  %60 = getelementptr inbounds i64, i64* %53, i64 9, !dbg !70
  store i64* %60, i64** %47, align 8, !dbg !70, !tbaa !27
  %rawSym67.i = tail call i64 @rb_id2sym(i64 %rubyId_fooAny1.i) #14, !dbg !72
  tail call void @rb_define_method(i64 %59, i8* getelementptr inbounds ([8 x i8], [8 x i8]* @str_fooAny1, i64 0, i64 0), i64 (...)* bitcast (i64 (i32, i64*, i64)* @"func_Object#fooAny1" to i64 (...)*), i32 -1) #14, !dbg !72
  %61 = getelementptr inbounds i64, i64* %53, i64 13, !dbg !72
  store i64* %61, i64** %47, align 8, !dbg !72, !tbaa !27
  %rawSym79.i = tail call i64 @rb_id2sym(i64 %rubyId_fooAny2.i) #14, !dbg !73
  tail call void @rb_define_method(i64 %59, i8* getelementptr inbounds ([8 x i8], [8 x i8]* @str_fooAny2, i64 0, i64 0), i64 (...)* bitcast (i64 (i32, i64*, i64)* @"func_Object#fooAny2" to i64 (...)*), i32 -1) #14, !dbg !73
  %62 = getelementptr inbounds i64, i64* %53, i64 17, !dbg !73
  store i64* %62, i64** %47, align 8, !dbg !73, !tbaa !27
  %rawSym91.i = tail call i64 @rb_id2sym(i64 %rubyId_fooInt.i) #14, !dbg !74
  tail call void @rb_define_method(i64 %59, i8* getelementptr inbounds ([7 x i8], [7 x i8]* @str_fooInt, i64 0, i64 0), i64 (...)* bitcast (i64 (i32, i64*, i64)* @"func_Object#fooInt" to i64 (...)*), i32 -1) #14, !dbg !74
  %63 = getelementptr inbounds i64, i64* %53, i64 21, !dbg !74
  store i64* %63, i64** %47, align 8, !dbg !74, !tbaa !27
  %rawSym103.i = tail call i64 @rb_id2sym(i64 %rubyId_fooArray.i) #14, !dbg !75
  tail call void @rb_define_method(i64 %59, i8* getelementptr inbounds ([9 x i8], [9 x i8]* @str_fooArray, i64 0, i64 0), i64 (...)* bitcast (i64 (i32, i64*, i64)* @"func_Object#fooArray" to i64 (...)*), i32 -1) #14, !dbg !75
  %64 = getelementptr inbounds i64, i64* %53, i64 25, !dbg !75
  store i64* %64, i64** %47, align 8, !dbg !75, !tbaa !27
  %callArgs0Addr117.i = getelementptr inbounds [2 x i64], [2 x i64]* %callArgs.i, i64 0, i64 0, !dbg !77
  store i64 5, i64* %callArgs0Addr117.i, align 8, !dbg !77
  %call_via_vm_fooInt.i = call i64 @sorbet_callFunc(i64 %44, i64 %rubyId_fooInt.i, i32 1, i64* nonnull %callArgs0Addr117.i, %struct.FunctionInlineCache* nonnull @ic_call_via_vm_fooInt) #14, !dbg !77
  store i64 %call_via_vm_fooInt.i, i64* %callArgs0Addr117.i, align 8, !dbg !76
  %call_via_vm_puts.i = call i64 @sorbet_callFunc(i64 %44, i64 %rubyId_puts.i, i32 1, i64* nonnull %callArgs0Addr117.i, %struct.FunctionInlineCache* nonnull @ic_call_via_vm_puts) #14, !dbg !76
  %65 = getelementptr inbounds i64, i64* %53, i64 26, !dbg !76
  store i64* %65, i64** %47, align 8, !dbg !76, !tbaa !27
  store i64 5, i64* %callArgs0Addr117.i, align 8, !dbg !78
  %call_via_vm_fooAny1.i = call i64 @sorbet_callFunc(i64 %44, i64 %rubyId_fooAny1.i, i32 1, i64* nonnull %callArgs0Addr117.i, %struct.FunctionInlineCache* nonnull @ic_call_via_vm_fooAny1) #14, !dbg !78
  store i64 %call_via_vm_fooAny1.i, i64* %callArgs0Addr117.i, align 8, !dbg !79
  %call_via_vm_puts136.i = call i64 @sorbet_callFunc(i64 %44, i64 %rubyId_puts.i, i32 1, i64* nonnull %callArgs0Addr117.i, %struct.FunctionInlineCache* nonnull @ic_call_via_vm_puts.6) #14, !dbg !79
  %66 = getelementptr inbounds i64, i64* %53, i64 27, !dbg !79
  store i64* %66, i64** %47, align 8, !dbg !79, !tbaa !27
  store i64 5, i64* %callArgs0Addr117.i, align 8, !dbg !80
  %call_via_vm_fooAny2.i = call i64 @sorbet_callFunc(i64 %44, i64 %rubyId_fooAny2.i, i32 1, i64* nonnull %callArgs0Addr117.i, %struct.FunctionInlineCache* nonnull @ic_call_via_vm_fooAny2) #14, !dbg !80
  store i64 %call_via_vm_fooAny2.i, i64* %callArgs0Addr117.i, align 8, !dbg !81
  %call_via_vm_puts149.i = call i64 @sorbet_callFunc(i64 %44, i64 %rubyId_puts.i, i32 1, i64* nonnull %callArgs0Addr117.i, %struct.FunctionInlineCache* nonnull @ic_call_via_vm_puts.7) #14, !dbg !81
  %67 = getelementptr inbounds i64, i64* %53, i64 28, !dbg !81
  store i64* %67, i64** %47, align 8, !dbg !81, !tbaa !27
  store i64 5, i64* %callArgs0Addr117.i, align 8, !dbg !82
  %call_via_vm_fooAll.i = call i64 @sorbet_callFunc(i64 %44, i64 %rubyId_fooAll.i, i32 1, i64* nonnull %callArgs0Addr117.i, %struct.FunctionInlineCache* nonnull @ic_call_via_vm_fooAll) #14, !dbg !82
  store i64 %call_via_vm_fooAll.i, i64* %callArgs0Addr117.i, align 8, !dbg !83
  %call_via_vm_puts162.i = call i64 @sorbet_callFunc(i64 %44, i64 %rubyId_puts.i, i32 1, i64* nonnull %callArgs0Addr117.i, %struct.FunctionInlineCache* nonnull @ic_call_via_vm_puts.8) #14, !dbg !83
  %68 = getelementptr inbounds i64, i64* %53, i64 29, !dbg !83
  store i64* %68, i64** %47, align 8, !dbg !83, !tbaa !27
  store i64 5, i64* %callArgs0Addr117.i, align 8, !dbg !84
  %69 = call i64 @rb_ary_new_from_values(i64 1, i64* nonnull %callArgs0Addr117.i) #14, !dbg !84
  store i64 %69, i64* %callArgs0Addr117.i, align 8, !dbg !85
  %call_via_vm_fooArray.i = call i64 @sorbet_callFunc(i64 %44, i64 %rubyId_fooArray.i, i32 1, i64* nonnull %callArgs0Addr117.i, %struct.FunctionInlineCache* nonnull @ic_call_via_vm_fooArray) #14, !dbg !85
  store i64 %call_via_vm_fooArray.i, i64* %callArgs0Addr117.i, align 8, !dbg !86
  %call_via_vm_puts179.i = call i64 @sorbet_callFunc(i64 %44, i64 %rubyId_puts.i, i32 1, i64* nonnull %callArgs0Addr117.i, %struct.FunctionInlineCache* nonnull @ic_call_via_vm_puts.9) #14, !dbg !86
  call void @llvm.lifetime.end.p0i8(i64 16, i8* nonnull %45)
  ret void
}

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #11

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.end.p0i8(i64 immarg, i8* nocapture) #11

; Function Attrs: cold minsize noreturn nounwind sspreq uwtable
define internal fastcc void @"func_Object#fooAll.cold.1"(i64 %rawArg_arg) unnamed_addr #12 {
newFuncRoot:
  tail call void @sorbet_cast_failure(i64 %rawArg_arg, i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_cast, i64 0, i64 0), i8* getelementptr inbounds ([7 x i8], [7 x i8]* @str_Kernel, i64 0, i64 0)), !dbg !33
  unreachable, !dbg !33
}

; Function Attrs: cold minsize noreturn nounwind sspreq uwtable
define internal fastcc void @"func_Object#fooAll.cold.2"(i64 %selfRaw) unnamed_addr #12 {
newFuncRoot:
  tail call void @sorbet_cast_failure(i64 %selfRaw, i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_cast, i64 0, i64 0), i8* getelementptr inbounds ([7 x i8], [7 x i8]* @str_Object, i64 0, i64 0)), !dbg !29
  unreachable, !dbg !29
}

; Function Attrs: cold minsize noreturn nounwind sspreq uwtable
define internal fastcc void @"func_Object#fooAny1.cold.1"(i64 %rawArg_arg) unnamed_addr #12 {
newFuncRoot:
  tail call void @sorbet_cast_failure(i64 %rawArg_arg, i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_cast, i64 0, i64 0), i8* getelementptr inbounds ([22 x i8], [22 x i8]* @"str_T.any(Integer, Float)", i64 0, i64 0)), !dbg !37
  unreachable, !dbg !37
}

; Function Attrs: cold minsize noreturn nounwind sspreq uwtable
define internal fastcc void @"func_Object#fooAny2.cold.1"(i64 %rawArg_arg) unnamed_addr #12 {
newFuncRoot:
  tail call void @sorbet_cast_failure(i64 %rawArg_arg, i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_cast, i64 0, i64 0), i8* getelementptr inbounds ([22 x i8], [22 x i8]* @"str_T.any(Float, Integer)", i64 0, i64 0)), !dbg !46
  unreachable, !dbg !46
}

; Function Attrs: cold minsize noreturn nounwind sspreq uwtable
define internal fastcc void @"func_Object#fooInt.cold.1"(i64 %rawArg_arg) unnamed_addr #12 {
newFuncRoot:
  tail call void @sorbet_cast_failure(i64 %rawArg_arg, i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_cast, i64 0, i64 0), i8* getelementptr inbounds ([8 x i8], [8 x i8]* @str_Integer, i64 0, i64 0)), !dbg !52
  unreachable, !dbg !52
}

; Function Attrs: cold minsize noreturn nounwind sspreq uwtable
define internal fastcc void @"func_Object#fooArray.cold.1"(i64 %rawArg_arg) unnamed_addr #12 {
newFuncRoot:
  tail call void @sorbet_cast_failure(i64 %rawArg_arg, i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_cast, i64 0, i64 0), i8* getelementptr inbounds ([18 x i8], [18 x i8]* @"str_T::Array[Integer]", i64 0, i64 0)), !dbg !58
  unreachable, !dbg !58
}

; Function Attrs: cold minsize noreturn nounwind sspreq
define internal fastcc void @Init_casts.cold.1(i64) unnamed_addr #13 {
newFuncRoot:
  tail call void @sorbet_cast_failure(i64 %0, i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_cast, i64 0, i64 0), i8* getelementptr inbounds ([19 x i8], [19 x i8]* @"str_T.class_of(<root>)", i64 0, i64 0)) #14, !dbg !70
  unreachable, !dbg !70
}

; Function Attrs: nounwind
declare void @llvm.assume(i1) #14

define linkonce void @const_recompute_T() local_unnamed_addr {
  %1 = tail call i64 @sorbet_getConstant(i8* getelementptr inbounds ([2 x i8], [2 x i8]* @str_T, i64 0, i64 0), i64 1)
  store i64 %1, i64* @guarded_const_T, align 8
  %2 = tail call i64 @sorbet_getConstantEpoch()
  store i64 %2, i64* @guard_epoch_T, align 8
  ret void
}

define linkonce void @"const_recompute_T::Array"() local_unnamed_addr {
  %1 = tail call i64 @sorbet_getConstant(i8* getelementptr inbounds ([9 x i8], [9 x i8]* @"str_T::Array", i64 0, i64 0), i64 8)
  store i64 %1, i64* @"guarded_const_T::Array", align 8
  %2 = tail call i64 @sorbet_getConstantEpoch()
  store i64 %2, i64* @"guard_epoch_T::Array", align 8
  ret void
}

attributes #0 = { nounwind ssp uwtable }
attributes #1 = { noreturn }
attributes #2 = { "addedToSilenceEmptyAttrsError" }
attributes #3 = { noinline nounwind ssp uwtable }
attributes #4 = { cold noreturn nounwind optsize ssp uwtable }
attributes #5 = { noreturn nounwind ssp uwtable }
attributes #6 = { nounwind readnone }
attributes #7 = { nounwind readnone speculatable }
attributes #8 = { alwaysinline norecurse nounwind readonly ssp uwtable }
attributes #9 = { nounwind sspreq uwtable }
attributes #10 = { nounwind sspreq }
attributes #11 = { argmemonly nounwind }
attributes #12 = { cold minsize noreturn nounwind sspreq uwtable }
attributes #13 = { cold minsize noreturn nounwind sspreq }
attributes #14 = { nounwind }
attributes #15 = { noreturn nounwind }
attributes #16 = { noinline }

!llvm.module.flags = !{!0}
!llvm.dbg.cu = !{!1}

!0 = !{i32 2, !"Debug Info Version", i32 3}
!1 = distinct !DICompileUnit(language: DW_LANG_C, file: !2, producer: "Sorbet LLVM", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, enums: !3)
!2 = !DIFile(filename: "test/testdata/compiler/casts.rb", directory: ".")
!3 = !{}
!4 = !{!5, !5, i64 0}
!5 = !{!"long", !6, i64 0}
!6 = !{!"omnipotent char", !7, i64 0}
!7 = !{!"Simple C/C++ TBAA"}
!8 = distinct !DISubprogram(name: "Object#fooAll", linkageName: "func_Object#fooAll", scope: null, file: !2, line: 5, type: !9, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!9 = !DISubroutineType(types: !10)
!10 = !{!11}
!11 = !DIBasicType(name: "VALUE", size: 64, encoding: DW_ATE_signed)
!12 = !{!13, !14, i64 16}
!13 = !{!"rb_control_frame_struct", !14, i64 0, !14, i64 8, !14, i64 16, !5, i64 24, !14, i64 32, !14, i64 40, !14, i64 48}
!14 = !{!"any pointer", !6, i64 0}
!15 = !{!16, !14, i64 16}
!16 = !{!"rb_iseq_struct", !5, i64 0, !5, i64 8, !14, i64 16, !6, i64 24}
!17 = !{!18, !14, i64 8}
!18 = !{!"rb_iseq_constant_body", !6, i64 0, !19, i64 4, !14, i64 8, !20, i64 16, !22, i64 64, !25, i64 120, !14, i64 152, !14, i64 160, !14, i64 168, !14, i64 176, !14, i64 184, !14, i64 192, !14, i64 200, !26, i64 208, !19, i64 240, !19, i64 244, !19, i64 248, !19, i64 252, !19, i64 256, !14, i64 264, !5, i64 272, !14, i64 280, !6, i64 288}
!19 = !{!"int", !6, i64 0}
!20 = !{!"", !21, i64 0, !19, i64 4, !19, i64 8, !19, i64 12, !19, i64 16, !19, i64 20, !19, i64 24, !19, i64 28, !14, i64 32, !14, i64 40}
!21 = !{!"", !19, i64 0, !19, i64 0, !19, i64 0, !19, i64 0, !19, i64 0, !19, i64 0, !19, i64 0, !19, i64 0}
!22 = !{!"rb_iseq_location_struct", !5, i64 0, !5, i64 8, !5, i64 16, !5, i64 24, !19, i64 32, !23, i64 36}
!23 = !{!"rb_code_location_struct", !24, i64 0, !24, i64 8}
!24 = !{!"rb_code_position_struct", !19, i64 0, !19, i64 4}
!25 = !{!"iseq_insn_info", !14, i64 0, !14, i64 8, !19, i64 16, !14, i64 24}
!26 = !{!"", !5, i64 0, !5, i64 8, !5, i64 16, !14, i64 24}
!27 = !{!14, !14, i64 0}
!28 = !DILocation(line: 6, column: 15, scope: !8)
!29 = !DILocation(line: 5, column: 1, scope: !8)
!30 = !{!"branch_weights", i32 4000000, i32 4001}
!31 = !{!"branch_weights", i32 2000, i32 1}
!32 = !{!"branch_weights", i32 10000, i32 1}
!33 = !DILocation(line: 6, column: 3, scope: !8)
!34 = distinct !DISubprogram(name: "Object#fooAny1", linkageName: "func_Object#fooAny1", scope: null, file: !2, line: 9, type: !9, scopeLine: 9, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!35 = !DILocation(line: 10, column: 15, scope: !34)
!36 = !DILocation(line: 9, column: 1, scope: !34)
!37 = !DILocation(line: 10, column: 3, scope: !34)
!38 = !DILocation(line: 5, column: 1, scope: !8, inlinedAt: !39)
!39 = distinct !DILocation(line: 9, column: 1, scope: !34)
!40 = !{!"branch_weights", i32 1073205, i32 2146410443}
!41 = !{!42, !5, i64 0}
!42 = !{!"RBasic", !5, i64 0, !5, i64 8}
!43 = distinct !DISubprogram(name: "Object#fooAny2", linkageName: "func_Object#fooAny2", scope: null, file: !2, line: 13, type: !9, scopeLine: 13, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!44 = !DILocation(line: 14, column: 15, scope: !43)
!45 = !DILocation(line: 13, column: 1, scope: !43)
!46 = !DILocation(line: 14, column: 3, scope: !43)
!47 = !DILocation(line: 5, column: 1, scope: !8, inlinedAt: !48)
!48 = distinct !DILocation(line: 13, column: 1, scope: !43)
!49 = !{!"branch_weights", i32 1, i32 2000}
!50 = distinct !DISubprogram(name: "Object#fooInt", linkageName: "func_Object#fooInt", scope: null, file: !2, line: 17, type: !9, scopeLine: 17, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!51 = !DILocation(line: 17, column: 1, scope: !50)
!52 = !DILocation(line: 18, column: 3, scope: !50)
!53 = !DILocation(line: 5, column: 1, scope: !8, inlinedAt: !54)
!54 = distinct !DILocation(line: 17, column: 1, scope: !50)
!55 = distinct !DISubprogram(name: "Object#fooArray", linkageName: "func_Object#fooArray", scope: null, file: !2, line: 21, type: !9, scopeLine: 21, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!56 = !DILocation(line: 22, column: 15, scope: !55)
!57 = !DILocation(line: 21, column: 1, scope: !55)
!58 = !DILocation(line: 22, column: 3, scope: !55)
!59 = !DILocation(line: 5, column: 1, scope: !8, inlinedAt: !60)
!60 = distinct !DILocation(line: 21, column: 1, scope: !55)
!61 = !{!62, !5, i64 400}
!62 = !{!"rb_vm_struct", !5, i64 0, !63, i64 8, !14, i64 192, !14, i64 200, !14, i64 208, !66, i64 216, !6, i64 224, !64, i64 264, !64, i64 280, !64, i64 296, !64, i64 312, !5, i64 328, !19, i64 336, !19, i64 340, !19, i64 340, !19, i64 340, !19, i64 340, !19, i64 344, !5, i64 352, !6, i64 360, !5, i64 400, !5, i64 408, !5, i64 416, !5, i64 424, !5, i64 432, !5, i64 440, !5, i64 448, !14, i64 456, !14, i64 464, !67, i64 472, !68, i64 1064, !14, i64 1088, !14, i64 1096, !19, i64 1104, !19, i64 1108, !64, i64 1112, !6, i64 1128, !5, i64 1168, !5, i64 1176, !5, i64 1184, !5, i64 1192, !5, i64 1200, !19, i64 1208, !5, i64 1216, !14, i64 1224, !14, i64 1232, !14, i64 1240, !14, i64 1248, !69, i64 1256, !6, i64 1288}
!63 = !{!"rb_global_vm_lock_struct", !14, i64 0, !6, i64 8, !64, i64 48, !14, i64 64, !19, i64 72, !6, i64 80, !6, i64 128, !19, i64 176, !19, i64 180}
!64 = !{!"list_head", !65, i64 0}
!65 = !{!"list_node", !14, i64 0, !14, i64 8}
!66 = !{!"long long", !6, i64 0}
!67 = !{!"", !6, i64 0, !6, i64 520}
!68 = !{!"rb_hook_list_struct", !14, i64 0, !19, i64 8, !19, i64 12, !19, i64 16}
!69 = !{!"", !5, i64 0, !5, i64 8, !5, i64 16, !5, i64 24}
!70 = !DILocation(line: 5, column: 1, scope: !71)
!71 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.<static-init>$153", scope: null, file: !2, line: 5, type: !9, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!72 = !DILocation(line: 9, column: 1, scope: !71)
!73 = !DILocation(line: 13, column: 1, scope: !71)
!74 = !DILocation(line: 17, column: 1, scope: !71)
!75 = !DILocation(line: 21, column: 1, scope: !71)
!76 = !DILocation(line: 25, column: 1, scope: !71)
!77 = !DILocation(line: 25, column: 6, scope: !71)
!78 = !DILocation(line: 26, column: 6, scope: !71)
!79 = !DILocation(line: 26, column: 1, scope: !71)
!80 = !DILocation(line: 27, column: 6, scope: !71)
!81 = !DILocation(line: 27, column: 1, scope: !71)
!82 = !DILocation(line: 28, column: 6, scope: !71)
!83 = !DILocation(line: 28, column: 1, scope: !71)
!84 = !DILocation(line: 29, column: 15, scope: !71)
!85 = !DILocation(line: 29, column: 6, scope: !71)
!86 = !DILocation(line: 29, column: 1, scope: !71)
