; ModuleID = 'payload'
source_filename = "llvm-link"
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"

%struct.rb_vm_struct = type { i64, %struct.rb_global_vm_lock_struct, %struct.rb_thread_struct*, %struct.rb_thread_struct*, i8*, i64, %union.pthread_mutex_t, %struct.list_head, %struct.list_head, %struct.list_head, %struct.list_head, i64, i32, i32, i8, i32, i64, [5 x i64], i64, i64, i64, i64, i64, i64, i64, %struct.st_table*, %struct.st_table*, %struct.anon.3, %struct.rb_hook_list_struct, %struct.st_table*, %struct.rb_postponed_job_struct*, i32, i32, %struct.list_head, %union.pthread_mutex_t, i64, i64, i64, i64, i64, i32, %struct.st_table*, %struct.rb_objspace*, %struct.rb_at_exit_list*, i64*, %struct.st_table*, %struct.rb_builtin_function*, i32, %struct.anon.4, [29 x i16] }
%struct.rb_global_vm_lock_struct = type { %struct.rb_thread_struct*, %union.pthread_mutex_t, %struct.list_head, %struct.rb_thread_struct*, i32, %union.pthread_cond_t, %union.pthread_cond_t, i32, i32 }
%union.pthread_cond_t = type { %struct.anon.2 }
%struct.anon.2 = type { i32, i32, i64, i64, i64, i8*, i32, i32 }
%struct.rb_thread_struct = type { %struct.list_node, i64, %struct.rb_vm_struct*, %struct.rb_execution_context_struct*, i64, %struct.rb_calling_info*, i64, i64, i64, i8, i8, i32, %struct.native_thread_data_struct, i8*, i64, i64, i64, i64, %union.pthread_mutex_t, %struct.rb_unblock_callback, i64, %struct.rb_mutex_struct*, %struct.rb_thread_list_struct*, %union.anon.8, i32, i64, %struct.rb_fiber_struct*, [5 x i8*], i64 }
%struct.list_node = type { %struct.list_node*, %struct.list_node* }
%struct.rb_execution_context_struct = type { i64*, i64, %struct.rb_control_frame_struct*, %struct.rb_vm_tag*, %struct.rb_vm_protect_tag*, i32, i32, %struct.rb_fiber_struct*, %struct.rb_thread_struct*, %struct.st_table*, i64, i64, i64*, i64, %struct.rb_ensure_list*, %struct.rb_trace_arg_struct*, i64, i64, i8, i8, i64, %struct.anon.5 }
%struct.rb_control_frame_struct = type { i64*, i64*, %struct.rb_iseq_struct*, i64, i64*, i8*, i64* }
%struct.rb_iseq_struct = type { i64, i64, %struct.rb_iseq_constant_body*, %union.anon.12 }
%struct.rb_iseq_constant_body = type { i32, i32, i64*, %struct.anon, %struct.rb_iseq_location_struct, %struct.iseq_insn_info, i64*, %struct.iseq_catch_table*, %struct.rb_iseq_struct*, %struct.rb_iseq_struct*, %union.iseq_inline_storage_entry*, %struct.rb_call_data*, %struct.anon.11, i32, i32, i32, i32, i32, i8, i64 }
%struct.anon = type { %struct.anon.0, i32, i32, i32, i32, i32, i32, i32, i64*, %struct.rb_iseq_param_keyword* }
%struct.anon.0 = type { i16, [2 x i8] }
%struct.rb_iseq_param_keyword = type { i32, i32, i32, i32, i64*, i64* }
%struct.rb_iseq_location_struct = type { i64, i64, i64, i64, i32, %struct.rb_code_location_struct }
%struct.rb_code_location_struct = type { %struct.rb_code_position_struct, %struct.rb_code_position_struct }
%struct.rb_code_position_struct = type { i32, i32 }
%struct.iseq_insn_info = type { %struct.iseq_insn_info_entry*, i32*, i32, %struct.succ_index_table* }
%struct.iseq_insn_info_entry = type opaque
%struct.succ_index_table = type opaque
%struct.iseq_catch_table = type opaque
%union.iseq_inline_storage_entry = type { %struct.iseq_inline_cache_entry }
%struct.iseq_inline_cache_entry = type { i64, %struct.rb_cref_struct*, i64 }
%struct.rb_cref_struct = type { i64, i64, i64, %struct.rb_cref_struct*, %struct.rb_scope_visi_struct }
%struct.rb_scope_visi_struct = type { i8, [3 x i8] }
%struct.rb_call_data = type { %struct.rb_call_cache, %struct.rb_call_info }
%struct.rb_call_cache = type { i64, [3 x i64], %struct.rb_callable_method_entry_struct*, i64, i64 (%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_calling_info*, %struct.rb_call_data*)*, %union.anon.15 }
%struct.rb_callable_method_entry_struct = type { i64, i64, %struct.rb_method_definition_struct*, i64, i64 }
%struct.rb_method_definition_struct = type { i64, %union.anon, i64, i64 }
%union.anon = type { %struct.rb_method_cfunc_struct }
%struct.rb_method_cfunc_struct = type { i64 (...)*, i64 (i64, i32, i64*, i64 (...)*)*, i32 }
%union.anon.15 = type { i32 }
%struct.rb_call_info = type { i64, i32, i32 }
%struct.anon.11 = type { i64, i64, i64, i64* }
%union.anon.12 = type { %struct.anon.13 }
%struct.anon.13 = type { i64, i32 }
%struct.rb_vm_tag = type { i64, i64, [5 x i8*], %struct.rb_vm_tag*, i32 }
%struct.rb_vm_protect_tag = type { %struct.rb_vm_protect_tag* }
%struct.rb_ensure_list = type { %struct.rb_ensure_list*, %struct.rb_ensure_entry }
%struct.rb_ensure_entry = type { i64, i64 (i64)*, i64 }
%struct.rb_trace_arg_struct = type { i32, %struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, i64, i64, i64, i64, i64, i32, i32, i64 }
%struct.anon.5 = type { i64*, i64*, i64, [1 x %struct.__jmp_buf_tag] }
%struct.__jmp_buf_tag = type { [8 x i64], i32, %struct.__sigset_t }
%struct.__sigset_t = type { [16 x i64] }
%struct.rb_calling_info = type { i64, i64, i32, i32 }
%struct.native_thread_data_struct = type { %struct.list_head, %union.anon.7 }
%union.anon.7 = type { %union.pthread_cond_t }
%struct.rb_unblock_callback = type { void (i8*)*, i8* }
%struct.rb_mutex_struct = type opaque
%struct.rb_thread_list_struct = type { %struct.rb_thread_list_struct*, %struct.rb_thread_struct* }
%union.anon.8 = type { %struct.anon.9 }
%struct.anon.9 = type { i64, i64, i32 }
%struct.rb_fiber_struct = type opaque
%struct.anon.3 = type { [65 x i64] }
%struct.rb_hook_list_struct = type { %struct.rb_event_hook_struct*, i32, i32, i32 }
%struct.rb_event_hook_struct = type opaque
%struct.rb_postponed_job_struct = type opaque
%struct.list_head = type { %struct.list_node }
%union.pthread_mutex_t = type { %struct.__pthread_mutex_s }
%struct.__pthread_mutex_s = type { i32, i32, i32, i32, i32, i16, i16, %struct.__pthread_internal_list }
%struct.__pthread_internal_list = type { %struct.__pthread_internal_list*, %struct.__pthread_internal_list* }
%struct.rb_objspace = type opaque
%struct.rb_at_exit_list = type { void (%struct.rb_vm_struct*)*, %struct.rb_at_exit_list* }
%struct.st_table = type { i8, i8, i8, i32, %struct.st_hash_type*, i64, i64*, i64, i64, %struct.st_table_entry* }
%struct.st_hash_type = type { i32 (i64, i64)*, i64 (i64)* }
%struct.st_table_entry = type opaque
%struct.rb_builtin_function = type opaque
%struct.anon.4 = type { i64, i64, i64, i64 }
%struct.FunctionInlineCache = type { %struct.rb_kwarg_call_data }
%struct.rb_kwarg_call_data = type { %struct.rb_call_cache, %struct.rb_call_info_with_kwarg }
%struct.rb_call_info_with_kwarg = type { %struct.rb_call_info, %struct.rb_call_info_kw_arg* }
%struct.rb_call_info_kw_arg = type { i32, [1 x i64] }
%struct.RBasic = type { i64, i64 }

@ruby_current_vm_ptr = external local_unnamed_addr global %struct.rb_vm_struct*, align 8
@ruby_vm_global_constant_state = external local_unnamed_addr global i64, align 8
@ruby_current_execution_context_ptr = external local_unnamed_addr global %struct.rb_execution_context_struct*, align 8
@rb_eRuntimeError = external local_unnamed_addr global i64, align 8
@.str.7 = private unnamed_addr constant [95 x i8] c"sorbet_getBuildSCMRevision: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@.str.8 = private unnamed_addr constant [93 x i8] c"sorbet_getIsReleaseBuild: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@"stackFramePrecomputed_func_Object#plus" = internal unnamed_addr global i8* null, align 8
@rubyIdPrecomputed_plus = internal unnamed_addr global i64 0, align 8
@str_plus = private unnamed_addr constant [5 x i8] c"plus\00", align 1
@rubyStrFrozen_plus = internal unnamed_addr global i64 0, align 8
@"rubyStrFrozen_test/testdata/compiler/float-intrinsics.rb" = internal unnamed_addr global i64 0, align 8
@"str_test/testdata/compiler/float-intrinsics.rb" = private unnamed_addr constant [43 x i8] c"test/testdata/compiler/float-intrinsics.rb\00", align 1
@str_sig = private unnamed_addr constant [4 x i8] c"sig\00", align 1
@str_Float = private unnamed_addr constant [6 x i8] c"Float\00", align 1
@"rubyIdPrecomputed_+" = internal unnamed_addr global i64 0, align 8
@"str_+" = private unnamed_addr constant [2 x i8] c"+\00", align 1
@"ic_+" = internal global %struct.FunctionInlineCache zeroinitializer
@"str_Return value" = private unnamed_addr constant [13 x i8] c"Return value\00", align 1
@"stackFramePrecomputed_func_Object#minus" = internal unnamed_addr global i8* null, align 8
@rubyIdPrecomputed_minus = internal unnamed_addr global i64 0, align 8
@str_minus = private unnamed_addr constant [6 x i8] c"minus\00", align 1
@ic_- = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_- = internal unnamed_addr global i64 0, align 8
@str_- = private unnamed_addr constant [2 x i8] c"-\00", align 1
@"stackFramePrecomputed_func_Object#lt" = internal unnamed_addr global i8* null, align 8
@rubyIdPrecomputed_lt = internal unnamed_addr global i64 0, align 8
@str_lt = private unnamed_addr constant [3 x i8] c"lt\00", align 1
@"rubyIdPrecomputed_<" = internal unnamed_addr global i64 0, align 8
@"str_<" = private unnamed_addr constant [2 x i8] c"<\00", align 1
@"ic_<" = internal global %struct.FunctionInlineCache zeroinitializer
@"str_T::Boolean" = private unnamed_addr constant [11 x i8] c"T::Boolean\00", align 1
@"stackFramePrecomputed_func_Object#lte" = internal unnamed_addr global i8* null, align 8
@rubyIdPrecomputed_lte = internal unnamed_addr global i64 0, align 8
@str_lte = private unnamed_addr constant [4 x i8] c"lte\00", align 1
@"rubyIdPrecomputed_<=" = internal unnamed_addr global i64 0, align 8
@"str_<=" = private unnamed_addr constant [3 x i8] c"<=\00", align 1
@"ic_<=" = internal global %struct.FunctionInlineCache zeroinitializer
@"stackFramePrecomputed_func_<root>.<static-init>$152" = internal unnamed_addr global i8* null, align 8
@"rubyIdPrecomputed_<top (required)>" = internal unnamed_addr global i64 0, align 8
@"str_<top (required)>" = private unnamed_addr constant [17 x i8] c"<top (required)>\00", align 1
@"<static-init-locals-storage>" = internal global [2 x i64] zeroinitializer
@"rubyIdPrecomputed_<self>" = internal unnamed_addr global i64 0, align 8
@"str_<self>" = private unnamed_addr constant [7 x i8] c"<self>\00", align 1
@"rubyIdPrecomputed_<block-call>" = internal unnamed_addr global i64 0, align 8
@"str_<block-call>" = private unnamed_addr constant [13 x i8] c"<block-call>\00", align 1
@"stackFramePrecomputed_func_<root>.<static-init>$152$block_1" = internal unnamed_addr global i8* null, align 8
@"rubyIdPrecomputed_block for" = internal unnamed_addr global i64 0, align 8
@"str_block for" = private unnamed_addr constant [10 x i8] c"block for\00", align 1
@"rubyStrFrozen_block for" = internal unnamed_addr global i64 0, align 8
@"stackFramePrecomputed_func_<root>.<static-init>$152$block_2" = internal unnamed_addr global i8* null, align 8
@"stackFramePrecomputed_func_<root>.<static-init>$152$block_3" = internal unnamed_addr global i8* null, align 8
@"stackFramePrecomputed_func_<root>.<static-init>$152$block_4" = internal unnamed_addr global i8* null, align 8
@ic_sig = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_sig = internal unnamed_addr global i64 0, align 8
@rubyIdPrecomputed_x = internal unnamed_addr global i64 0, align 8
@str_x = private unnamed_addr constant [2 x i8] c"x\00", align 1
@rubyIdPrecomputed_y = internal unnamed_addr global i64 0, align 8
@str_y = private unnamed_addr constant [2 x i8] c"y\00", align 1
@ic_untyped = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_untyped = internal unnamed_addr global i64 0, align 8
@str_untyped = private unnamed_addr constant [8 x i8] c"untyped\00", align 1
@ic_params = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_params = internal unnamed_addr global i64 0, align 8
@str_params = private unnamed_addr constant [7 x i8] c"params\00", align 1
@ic_untyped.1 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_returns = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_returns = internal unnamed_addr global i64 0, align 8
@str_returns = private unnamed_addr constant [8 x i8] c"returns\00", align 1
@ic_sig.2 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_untyped.3 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_params.4 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_untyped.5 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_returns.6 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_sig.7 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_untyped.8 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_params.9 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_returns.10 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_sig.11 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_untyped.12 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_params.13 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_returns.14 = internal global %struct.FunctionInlineCache zeroinitializer
@"str_T::Sig" = private unnamed_addr constant [7 x i8] c"T::Sig\00", align 1
@ic_extend = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_extend = internal unnamed_addr global i64 0, align 8
@str_extend = private unnamed_addr constant [7 x i8] c"extend\00", align 1
@rubyIdPrecomputed_normal = internal unnamed_addr global i64 0, align 8
@str_normal = private unnamed_addr constant [7 x i8] c"normal\00", align 1
@ic_keep_def = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_keep_def = internal unnamed_addr global i64 0, align 8
@str_keep_def = private unnamed_addr constant [9 x i8] c"keep_def\00", align 1
@ic_keep_def.15 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_keep_def.16 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_keep_def.17 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_plus = internal global %struct.FunctionInlineCache zeroinitializer
@ic_p = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_p = internal unnamed_addr global i64 0, align 8
@str_p = private unnamed_addr constant [2 x i8] c"p\00", align 1
@ic_minus = internal global %struct.FunctionInlineCache zeroinitializer
@ic_p.18 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_lt = internal global %struct.FunctionInlineCache zeroinitializer
@ic_p.19 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_lt.20 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_p.21 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_lte = internal global %struct.FunctionInlineCache zeroinitializer
@ic_p.22 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_lte.23 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_p.24 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_lte.25 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_p.26 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_plus.27 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_p.28 = internal global %struct.FunctionInlineCache zeroinitializer
@rubyStrFrozen_8.9 = internal unnamed_addr global i64 0, align 8
@str_8.9 = private unnamed_addr constant [4 x i8] c"8.9\00", align 1
@ic_Rational = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_Rational = internal unnamed_addr global i64 0, align 8
@str_Rational = private unnamed_addr constant [9 x i8] c"Rational\00", align 1
@ic_plus.29 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_p.30 = internal global %struct.FunctionInlineCache zeroinitializer
@rubyStrFrozen_5 = internal unnamed_addr global i64 0, align 8
@str_5 = private unnamed_addr constant [2 x i8] c"5\00", align 1
@ic_Complex = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_Complex = internal unnamed_addr global i64 0, align 8
@str_Complex = private unnamed_addr constant [8 x i8] c"Complex\00", align 1
@ic_plus.31 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_p.32 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_minus.33 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_p.34 = internal global %struct.FunctionInlineCache zeroinitializer
@rubyStrFrozen_15.4 = internal unnamed_addr global i64 0, align 8
@str_15.4 = private unnamed_addr constant [5 x i8] c"15.4\00", align 1
@ic_Rational.35 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_minus.36 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_p.37 = internal global %struct.FunctionInlineCache zeroinitializer
@rubyStrFrozen_18 = internal unnamed_addr global i64 0, align 8
@str_18 = private unnamed_addr constant [3 x i8] c"18\00", align 1
@ic_Complex.38 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_minus.39 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_p.40 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_lt.41 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_p.42 = internal global %struct.FunctionInlineCache zeroinitializer
@rubyStrFrozen_25.4 = internal unnamed_addr global i64 0, align 8
@str_25.4 = private unnamed_addr constant [5 x i8] c"25.4\00", align 1
@ic_Rational.43 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_lt.44 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_p.45 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_lte.46 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_p.47 = internal global %struct.FunctionInlineCache zeroinitializer
@rubyStrFrozen_5.923 = internal unnamed_addr global i64 0, align 8
@str_5.923 = private unnamed_addr constant [6 x i8] c"5.923\00", align 1
@ic_Rational.48 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_lte.49 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_p.50 = internal global %struct.FunctionInlineCache zeroinitializer
@"guard_epoch_T::Sig" = linkonce local_unnamed_addr global i64 0
@"guarded_const_T::Sig" = linkonce local_unnamed_addr global i64 0
@rb_cObject = external local_unnamed_addr constant i64
@rb_mKernel = external local_unnamed_addr constant i64

declare i64 @rb_float_plus(i64, i64) local_unnamed_addr #0

declare i64 @sorbet_flo_lt(i64, i64) local_unnamed_addr #0

declare i64 @sorbet_flo_le(i64, i64) local_unnamed_addr #0

; Function Attrs: cold noreturn
declare void @sorbet_cast_failure(i64, i8*, i8*) local_unnamed_addr #1

; Function Attrs: noreturn
declare void @sorbet_raiseArity(i32, i32, i32) local_unnamed_addr #2

declare i8* @sorbet_allocateRubyStackFrame(i64, i64, i64, i64, i8*, i32, i32, i32, i64*, i32, i32) local_unnamed_addr #0

declare i64 @sorbet_getConstant(i8*, i64) local_unnamed_addr #0

declare i64 @sorbet_readRealpath() local_unnamed_addr #0

declare void @sorbet_vm_env_write_slowpath(i64*, i32, i64) local_unnamed_addr #0

declare void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache*, i64, i32, i32, i32, i64*) local_unnamed_addr #0

declare i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache*, i64) local_unnamed_addr #0

declare void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_iseq_struct*) local_unnamed_addr #0

declare extern_weak void @rb_define_method(i64, i8*, i64 (...)*, i32) local_unnamed_addr #0

declare i64 @rb_intern2(i8*, i64) local_unnamed_addr #0

declare i64 @rb_id2sym(i64) local_unnamed_addr #0

declare i64 @rb_fstring_new(i8*, i64) local_unnamed_addr #0

declare void @rb_gc_register_mark_object(i64) local_unnamed_addr #0

; Function Attrs: noreturn
declare void @rb_raise(i64, i8*, ...) local_unnamed_addr #2

; Function Attrs: nounwind ssp uwtable
define weak i32 @sorbet_getIsReleaseBuild() local_unnamed_addr #3 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !4
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* getelementptr inbounds ([93 x i8], [93 x i8]* @.str.8, i64 0, i64 0)) #10
  unreachable
}

; Function Attrs: nounwind ssp uwtable
define weak i8* @sorbet_getBuildSCMRevision() local_unnamed_addr #3 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !4
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* getelementptr inbounds ([95 x i8], [95 x i8]* @.str.7, i64 0, i64 0)) #10
  unreachable
}

; Function Attrs: nounwind sspreq uwtable
define i64 @"func_Object#plus"(i32 %argc, i64* nocapture readonly %argArray, i64 %selfRaw) #4 !dbg !8 {
functionEntryInitializers:
  %"stackFrame_func_Object#plus" = load i8*, i8** @"stackFramePrecomputed_func_Object#plus", align 8
  %0 = bitcast i8* %"stackFrame_func_Object#plus" to %struct.rb_iseq_struct*
  %1 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !12
  %2 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %1, i64 0, i32 2
  %3 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %2, align 8, !tbaa !14
  %4 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 2
  %5 = bitcast %struct.rb_iseq_struct** %4 to i8**
  store i8* %"stackFrame_func_Object#plus", i8** %5, align 8, !tbaa !18
  %6 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 4
  %7 = load i64*, i64** %6, align 8, !tbaa !20
  %8 = load i64, i64* %7, align 8, !tbaa !4
  %9 = and i64 %8, -129
  store i64 %9, i64* %7, align 8, !tbaa !4
  tail call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* %1, %struct.rb_control_frame_struct* nonnull %3, %struct.rb_iseq_struct* %0) #8
  %10 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 0
  %11 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %4, align 8, !tbaa !18
  %12 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %11, i64 0, i32 2
  %13 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %12, align 8, !tbaa !21
  %14 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %13, i64 0, i32 2
  %15 = load i64*, i64** %14, align 8, !tbaa !23
  %16 = getelementptr inbounds i64, i64* %15, i64 1
  store i64* %16, i64** %10, align 8, !tbaa !12
  %17 = icmp eq i32 %argc, 2, !dbg !32
  br i1 %17, label %fillRequiredArgs, label %argCountFailBlock, !dbg !32, !prof !33

argCountFailBlock:                                ; preds = %functionEntryInitializers
  tail call void @sorbet_raiseArity(i32 %argc, i32 2, i32 2) #8, !dbg !32
  unreachable, !dbg !32

fillRequiredArgs:                                 ; preds = %functionEntryInitializers
  %rawArg_x = load i64, i64* %argArray, align 8, !dbg !32
  %18 = getelementptr i64, i64* %argArray, i64 1, !dbg !32
  %rawArg_y = load i64, i64* %18, align 8, !dbg !32
  %19 = and i64 %rawArg_x, 3, !dbg !34
  %20 = icmp eq i64 %19, 2, !dbg !34
  br i1 %20, label %typeTestSuccess17, label %21, !dbg !34

21:                                               ; preds = %fillRequiredArgs
  %22 = and i64 %rawArg_x, 7, !dbg !34
  %23 = icmp ne i64 %22, 0, !dbg !34
  %24 = and i64 %rawArg_x, -9, !dbg !34
  %25 = icmp eq i64 %24, 0, !dbg !34
  %26 = or i1 %23, %25, !dbg !34
  br i1 %26, label %codeRepl, label %sorbet_isa_Float.exit, !dbg !34, !prof !35

sorbet_isa_Float.exit:                            ; preds = %21
  %27 = inttoptr i64 %rawArg_x to %struct.RBasic*, !dbg !34
  %28 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %27, i64 0, i32 0, !dbg !34
  %29 = load i64, i64* %28, align 8, !dbg !34, !tbaa !36
  %30 = and i64 %29, 31, !dbg !34
  %31 = icmp eq i64 %30, 4, !dbg !34
  br i1 %31, label %typeTestSuccess17, label %codeRepl, !dbg !34, !prof !38

codeRepl:                                         ; preds = %sorbet_isa_Float.exit, %21
  tail call void @sorbet_cast_failure(i64 %rawArg_x, i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_sig, i64 0, i64 0), i8* getelementptr inbounds ([6 x i8], [6 x i8]* @str_Float, i64 0, i64 0)) #8, !dbg !39
  unreachable, !dbg !39

typeTestSuccess17:                                ; preds = %fillRequiredArgs, %sorbet_isa_Float.exit
  %32 = getelementptr inbounds i64, i64* %15, i64 2, !dbg !42
  store i64* %32, i64** %10, align 8, !dbg !42, !tbaa !12
  %33 = tail call i64 @rb_float_plus(i64 %rawArg_x, i64 %rawArg_y) #8, !dbg !43, !noalias !44
  ret i64 %33
}

; Function Attrs: nounwind sspreq uwtable
define i64 @"func_Object#minus"(i32 %argc, i64* nocapture readonly %argArray, i64 %selfRaw) #4 !dbg !47 {
functionEntryInitializers:
  %"stackFrame_func_Object#minus" = load i8*, i8** @"stackFramePrecomputed_func_Object#minus", align 8
  %0 = bitcast i8* %"stackFrame_func_Object#minus" to %struct.rb_iseq_struct*
  %1 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !12
  %2 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %1, i64 0, i32 2
  %3 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %2, align 8, !tbaa !14
  %4 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 2
  %5 = bitcast %struct.rb_iseq_struct** %4 to i8**
  store i8* %"stackFrame_func_Object#minus", i8** %5, align 8, !tbaa !18
  %6 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 4
  %7 = load i64*, i64** %6, align 8, !tbaa !20
  %8 = load i64, i64* %7, align 8, !tbaa !4
  %9 = and i64 %8, -129
  store i64 %9, i64* %7, align 8, !tbaa !4
  tail call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* %1, %struct.rb_control_frame_struct* nonnull %3, %struct.rb_iseq_struct* %0) #8
  %10 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 0
  %11 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %4, align 8, !tbaa !18
  %12 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %11, i64 0, i32 2
  %13 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %12, align 8, !tbaa !21
  %14 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %13, i64 0, i32 2
  %15 = load i64*, i64** %14, align 8, !tbaa !23
  %16 = getelementptr inbounds i64, i64* %15, i64 1
  store i64* %16, i64** %10, align 8, !tbaa !12
  %17 = icmp eq i32 %argc, 2, !dbg !48
  br i1 %17, label %fillRequiredArgs, label %argCountFailBlock, !dbg !48, !prof !33

argCountFailBlock:                                ; preds = %functionEntryInitializers
  tail call void @sorbet_raiseArity(i32 %argc, i32 2, i32 2) #8, !dbg !48
  unreachable, !dbg !48

fillRequiredArgs:                                 ; preds = %functionEntryInitializers
  %18 = bitcast i64* %argArray to <2 x i64>*, !dbg !48
  %19 = load <2 x i64>, <2 x i64>* %18, align 8, !dbg !48
  %20 = extractelement <2 x i64> %19, i32 0, !dbg !49
  %21 = and i64 %20, 3, !dbg !49
  %22 = icmp eq i64 %21, 2, !dbg !49
  br i1 %22, label %typeTestSuccess14, label %23, !dbg !49

23:                                               ; preds = %fillRequiredArgs
  %24 = and i64 %20, 7, !dbg !49
  %25 = icmp ne i64 %24, 0, !dbg !49
  %26 = and i64 %20, -9, !dbg !49
  %27 = icmp eq i64 %26, 0, !dbg !49
  %28 = or i1 %25, %27, !dbg !49
  br i1 %28, label %codeRepl, label %sorbet_isa_Float.exit, !dbg !49, !prof !35

sorbet_isa_Float.exit:                            ; preds = %23
  %29 = inttoptr i64 %20 to %struct.RBasic*, !dbg !49
  %30 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %29, i64 0, i32 0, !dbg !49
  %31 = load i64, i64* %30, align 8, !dbg !49, !tbaa !36
  %32 = and i64 %31, 31, !dbg !49
  %33 = icmp eq i64 %32, 4, !dbg !49
  br i1 %33, label %typeTestSuccess14, label %codeRepl, !dbg !49, !prof !38

codeRepl:                                         ; preds = %sorbet_isa_Float.exit, %23
  tail call void @sorbet_cast_failure(i64 %20, i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_sig, i64 0, i64 0), i8* getelementptr inbounds ([6 x i8], [6 x i8]* @str_Float, i64 0, i64 0)) #8, !dbg !50
  unreachable, !dbg !50

typeTestSuccess14:                                ; preds = %fillRequiredArgs, %sorbet_isa_Float.exit
  %34 = getelementptr inbounds i64, i64* %15, i64 2, !dbg !52
  store i64* %34, i64** %10, align 8, !dbg !52, !tbaa !12
  %35 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !53, !tbaa !12
  %36 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %35, i64 0, i32 2, !dbg !53
  %37 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %36, align 8, !dbg !53, !tbaa !14
  %38 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %37, i64 0, i32 1, !dbg !53
  %39 = load i64*, i64** %38, align 8, !dbg !53, !tbaa !54
  %40 = getelementptr inbounds i64, i64* %39, i64 2, !dbg !53
  store i64* %40, i64** %38, align 8, !dbg !53, !tbaa !54
  %41 = bitcast i64* %39 to <2 x i64>*, !dbg !53
  store <2 x i64> %19, <2 x i64>* %41, align 8, !dbg !53, !tbaa !4
  %send = tail call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_-, i64 0) #8, !dbg !53
  ret i64 %send
}

; Function Attrs: nounwind sspreq uwtable
define i64 @"func_Object#lt"(i32 %argc, i64* nocapture readonly %argArray, i64 %selfRaw) #4 !dbg !40 {
functionEntryInitializers:
  %"stackFrame_func_Object#lt" = load i8*, i8** @"stackFramePrecomputed_func_Object#lt", align 8
  %0 = bitcast i8* %"stackFrame_func_Object#lt" to %struct.rb_iseq_struct*
  %1 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !12
  %2 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %1, i64 0, i32 2
  %3 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %2, align 8, !tbaa !14
  %4 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 2
  %5 = bitcast %struct.rb_iseq_struct** %4 to i8**
  store i8* %"stackFrame_func_Object#lt", i8** %5, align 8, !tbaa !18
  %6 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 4
  %7 = load i64*, i64** %6, align 8, !tbaa !20
  %8 = load i64, i64* %7, align 8, !tbaa !4
  %9 = and i64 %8, -129
  store i64 %9, i64* %7, align 8, !tbaa !4
  tail call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* %1, %struct.rb_control_frame_struct* nonnull %3, %struct.rb_iseq_struct* %0) #8
  %10 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 0
  %11 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %4, align 8, !tbaa !18
  %12 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %11, i64 0, i32 2
  %13 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %12, align 8, !tbaa !21
  %14 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %13, i64 0, i32 2
  %15 = load i64*, i64** %14, align 8, !tbaa !23
  %16 = getelementptr inbounds i64, i64* %15, i64 1
  store i64* %16, i64** %10, align 8, !tbaa !12
  %17 = icmp eq i32 %argc, 2, !dbg !55
  br i1 %17, label %fillRequiredArgs, label %argCountFailBlock, !dbg !55, !prof !33

argCountFailBlock:                                ; preds = %functionEntryInitializers
  tail call void @sorbet_raiseArity(i32 %argc, i32 2, i32 2) #8, !dbg !55
  unreachable, !dbg !55

fillRequiredArgs:                                 ; preds = %functionEntryInitializers
  %rawArg_x = load i64, i64* %argArray, align 8, !dbg !55
  %18 = getelementptr i64, i64* %argArray, i64 1, !dbg !55
  %rawArg_y = load i64, i64* %18, align 8, !dbg !55
  %19 = and i64 %rawArg_x, 3, !dbg !56
  %20 = icmp eq i64 %19, 2, !dbg !56
  br i1 %20, label %typeTestSuccess8, label %21, !dbg !56

21:                                               ; preds = %fillRequiredArgs
  %22 = and i64 %rawArg_x, 7, !dbg !56
  %23 = icmp ne i64 %22, 0, !dbg !56
  %24 = and i64 %rawArg_x, -9, !dbg !56
  %25 = icmp eq i64 %24, 0, !dbg !56
  %26 = or i1 %23, %25, !dbg !56
  br i1 %26, label %codeRepl30, label %sorbet_isa_Float.exit, !dbg !56, !prof !35

sorbet_isa_Float.exit:                            ; preds = %21
  %27 = inttoptr i64 %rawArg_x to %struct.RBasic*, !dbg !56
  %28 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %27, i64 0, i32 0, !dbg !56
  %29 = load i64, i64* %28, align 8, !dbg !56, !tbaa !36
  %30 = and i64 %29, 31, !dbg !56
  %31 = icmp eq i64 %30, 4, !dbg !56
  br i1 %31, label %typeTestSuccess8, label %codeRepl30, !dbg !56, !prof !38

codeRepl30:                                       ; preds = %sorbet_isa_Float.exit, %21
  tail call fastcc void @"func_Object#lt.cold.2"(i64 %rawArg_x) #11, !dbg !56
  unreachable

typeTestSuccess8:                                 ; preds = %fillRequiredArgs, %sorbet_isa_Float.exit
  %32 = getelementptr inbounds i64, i64* %15, i64 2, !dbg !57
  store i64* %32, i64** %10, align 8, !dbg !57, !tbaa !12
  %33 = tail call i64 @sorbet_flo_lt(i64 %rawArg_x, i64 %rawArg_y) #8, !dbg !58, !noalias !59
  switch i64 %33, label %codeRepl [
    i64 20, label %typeTestSuccess17
    i64 0, label %typeTestSuccess17
  ], !prof !62

typeTestSuccess17:                                ; preds = %typeTestSuccess8, %typeTestSuccess8
  ret i64 %33

codeRepl:                                         ; preds = %typeTestSuccess8
  tail call fastcc void @"func_Object#lt.cold.1"(i64 %33) #11
  unreachable
}

; Function Attrs: nounwind sspreq uwtable
define i64 @"func_Object#lte"(i32 %argc, i64* nocapture readonly %argArray, i64 %selfRaw) #4 !dbg !63 {
functionEntryInitializers:
  %"stackFrame_func_Object#lte" = load i8*, i8** @"stackFramePrecomputed_func_Object#lte", align 8
  %0 = bitcast i8* %"stackFrame_func_Object#lte" to %struct.rb_iseq_struct*
  %1 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !12
  %2 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %1, i64 0, i32 2
  %3 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %2, align 8, !tbaa !14
  %4 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 2
  %5 = bitcast %struct.rb_iseq_struct** %4 to i8**
  store i8* %"stackFrame_func_Object#lte", i8** %5, align 8, !tbaa !18
  %6 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 4
  %7 = load i64*, i64** %6, align 8, !tbaa !20
  %8 = load i64, i64* %7, align 8, !tbaa !4
  %9 = and i64 %8, -129
  store i64 %9, i64* %7, align 8, !tbaa !4
  tail call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* %1, %struct.rb_control_frame_struct* nonnull %3, %struct.rb_iseq_struct* %0) #8
  %10 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 0
  %11 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %4, align 8, !tbaa !18
  %12 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %11, i64 0, i32 2
  %13 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %12, align 8, !tbaa !21
  %14 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %13, i64 0, i32 2
  %15 = load i64*, i64** %14, align 8, !tbaa !23
  %16 = getelementptr inbounds i64, i64* %15, i64 1
  store i64* %16, i64** %10, align 8, !tbaa !12
  %17 = icmp eq i32 %argc, 2, !dbg !64
  br i1 %17, label %fillRequiredArgs, label %argCountFailBlock, !dbg !64, !prof !33

argCountFailBlock:                                ; preds = %functionEntryInitializers
  tail call void @sorbet_raiseArity(i32 %argc, i32 2, i32 2) #8, !dbg !64
  unreachable, !dbg !64

fillRequiredArgs:                                 ; preds = %functionEntryInitializers
  %rawArg_x = load i64, i64* %argArray, align 8, !dbg !64
  %18 = getelementptr i64, i64* %argArray, i64 1, !dbg !64
  %rawArg_y = load i64, i64* %18, align 8, !dbg !64
  %19 = and i64 %rawArg_x, 3, !dbg !65
  %20 = icmp eq i64 %19, 2, !dbg !65
  br i1 %20, label %typeTestSuccess8, label %21, !dbg !65

21:                                               ; preds = %fillRequiredArgs
  %22 = and i64 %rawArg_x, 7, !dbg !65
  %23 = icmp ne i64 %22, 0, !dbg !65
  %24 = and i64 %rawArg_x, -9, !dbg !65
  %25 = icmp eq i64 %24, 0, !dbg !65
  %26 = or i1 %23, %25, !dbg !65
  br i1 %26, label %codeRepl30, label %sorbet_isa_Float.exit, !dbg !65, !prof !35

sorbet_isa_Float.exit:                            ; preds = %21
  %27 = inttoptr i64 %rawArg_x to %struct.RBasic*, !dbg !65
  %28 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %27, i64 0, i32 0, !dbg !65
  %29 = load i64, i64* %28, align 8, !dbg !65, !tbaa !36
  %30 = and i64 %29, 31, !dbg !65
  %31 = icmp eq i64 %30, 4, !dbg !65
  br i1 %31, label %typeTestSuccess8, label %codeRepl30, !dbg !65, !prof !38

codeRepl30:                                       ; preds = %sorbet_isa_Float.exit, %21
  tail call void @sorbet_cast_failure(i64 %rawArg_x, i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_sig, i64 0, i64 0), i8* getelementptr inbounds ([6 x i8], [6 x i8]* @str_Float, i64 0, i64 0)) #8, !dbg !66
  unreachable, !dbg !66

typeTestSuccess8:                                 ; preds = %fillRequiredArgs, %sorbet_isa_Float.exit
  %32 = getelementptr inbounds i64, i64* %15, i64 2, !dbg !68
  store i64* %32, i64** %10, align 8, !dbg !68, !tbaa !12
  %33 = tail call i64 @sorbet_flo_le(i64 %rawArg_x, i64 %rawArg_y) #8, !dbg !69, !noalias !70
  switch i64 %33, label %codeRepl [
    i64 20, label %typeTestSuccess17
    i64 0, label %typeTestSuccess17
  ], !prof !62

typeTestSuccess17:                                ; preds = %typeTestSuccess8, %typeTestSuccess8
  ret i64 %33

codeRepl:                                         ; preds = %typeTestSuccess8
  tail call void @sorbet_cast_failure(i64 %33, i8* getelementptr inbounds ([13 x i8], [13 x i8]* @"str_Return value", i64 0, i64 0), i8* getelementptr inbounds ([11 x i8], [11 x i8]* @"str_T::Boolean", i64 0, i64 0)) #8
  unreachable
}

; Function Attrs: sspreq
define void @Init_float-intrinsics() local_unnamed_addr #5 {
entry:
  %locals1.i.i = alloca [0 x i64], align 8
  %keywords174.i = alloca [2 x i64], align 8, !dbg !73
  %keywords17175.i = alloca [2 x i64], align 8, !dbg !76
  %keywords34176.i = alloca [2 x i64], align 8, !dbg !78
  %keywords49177.i = alloca [2 x i64], align 8, !dbg !80
  %realpath = tail call i64 @sorbet_readRealpath()
  %0 = bitcast [2 x i64]* %keywords174.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 16, i8* nonnull %0)
  %1 = bitcast [2 x i64]* %keywords17175.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 16, i8* nonnull %1)
  %2 = bitcast [2 x i64]* %keywords34176.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 16, i8* nonnull %2)
  %3 = bitcast [2 x i64]* %keywords49177.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 16, i8* nonnull %3)
  %4 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_plus, i64 0, i64 0), i64 4) #8
  store i64 %4, i64* @rubyIdPrecomputed_plus, align 8
  %5 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([2 x i8], [2 x i8]* @"str_+", i64 0, i64 0), i64 1) #8
  store i64 %5, i64* @"rubyIdPrecomputed_+", align 8
  %6 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([6 x i8], [6 x i8]* @str_minus, i64 0, i64 0), i64 5) #8
  store i64 %6, i64* @rubyIdPrecomputed_minus, align 8
  %7 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([2 x i8], [2 x i8]* @str_-, i64 0, i64 0), i64 1) #8
  store i64 %7, i64* @rubyIdPrecomputed_-, align 8
  %8 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([3 x i8], [3 x i8]* @str_lt, i64 0, i64 0), i64 2) #8
  store i64 %8, i64* @rubyIdPrecomputed_lt, align 8
  %9 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([2 x i8], [2 x i8]* @"str_<", i64 0, i64 0), i64 1) #8
  store i64 %9, i64* @"rubyIdPrecomputed_<", align 8
  %10 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_lte, i64 0, i64 0), i64 3) #8
  store i64 %10, i64* @rubyIdPrecomputed_lte, align 8
  %11 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([3 x i8], [3 x i8]* @"str_<=", i64 0, i64 0), i64 2) #8
  store i64 %11, i64* @"rubyIdPrecomputed_<=", align 8
  %12 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 16) #8
  store i64 %12, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %13 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([7 x i8], [7 x i8]* @"str_<self>", i64 0, i64 0), i64 6) #8
  store i64 %13, i64* @"rubyIdPrecomputed_<self>", align 8
  %14 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([13 x i8], [13 x i8]* @"str_<block-call>", i64 0, i64 0), i64 12) #8
  store i64 %14, i64* @"rubyIdPrecomputed_<block-call>", align 8
  %15 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([10 x i8], [10 x i8]* @"str_block for", i64 0, i64 0), i64 9) #8
  store i64 %15, i64* @"rubyIdPrecomputed_block for", align 8
  %16 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_sig, i64 0, i64 0), i64 3) #8
  store i64 %16, i64* @rubyIdPrecomputed_sig, align 8
  %17 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([2 x i8], [2 x i8]* @str_x, i64 0, i64 0), i64 1) #8
  store i64 %17, i64* @rubyIdPrecomputed_x, align 8
  %18 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([2 x i8], [2 x i8]* @str_y, i64 0, i64 0), i64 1) #8
  store i64 %18, i64* @rubyIdPrecomputed_y, align 8
  %19 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([8 x i8], [8 x i8]* @str_untyped, i64 0, i64 0), i64 7) #8
  store i64 %19, i64* @rubyIdPrecomputed_untyped, align 8
  %20 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([7 x i8], [7 x i8]* @str_params, i64 0, i64 0), i64 6) #8
  store i64 %20, i64* @rubyIdPrecomputed_params, align 8
  %21 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([8 x i8], [8 x i8]* @str_returns, i64 0, i64 0), i64 7) #8
  store i64 %21, i64* @rubyIdPrecomputed_returns, align 8
  %22 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([7 x i8], [7 x i8]* @str_extend, i64 0, i64 0), i64 6) #8
  store i64 %22, i64* @rubyIdPrecomputed_extend, align 8
  %23 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([7 x i8], [7 x i8]* @str_normal, i64 0, i64 0), i64 6) #8
  store i64 %23, i64* @rubyIdPrecomputed_normal, align 8
  %24 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([9 x i8], [9 x i8]* @str_keep_def, i64 0, i64 0), i64 8) #8
  store i64 %24, i64* @rubyIdPrecomputed_keep_def, align 8
  %25 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([2 x i8], [2 x i8]* @str_p, i64 0, i64 0), i64 1) #8
  store i64 %25, i64* @rubyIdPrecomputed_p, align 8
  %26 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([9 x i8], [9 x i8]* @str_Rational, i64 0, i64 0), i64 8) #8
  store i64 %26, i64* @rubyIdPrecomputed_Rational, align 8
  %27 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([8 x i8], [8 x i8]* @str_Complex, i64 0, i64 0), i64 7) #8
  store i64 %27, i64* @rubyIdPrecomputed_Complex, align 8
  %"rubyId_<self>.i" = load i64, i64* @"rubyIdPrecomputed_<self>", align 8
  store i64 %"rubyId_<self>.i", i64* getelementptr inbounds ([2 x i64], [2 x i64]* @"<static-init-locals-storage>", i64 0, i64 0), align 8
  %"rubyId_<block-call>.i" = load i64, i64* @"rubyIdPrecomputed_<block-call>", align 8
  store i64 %"rubyId_<block-call>.i", i64* getelementptr inbounds ([2 x i64], [2 x i64]* @"<static-init-locals-storage>", i64 0, i64 1), align 8
  %28 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_plus, i64 0, i64 0), i64 4) #8
  tail call void @rb_gc_register_mark_object(i64 %28) #8
  store i64 %28, i64* @rubyStrFrozen_plus, align 8
  %29 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([43 x i8], [43 x i8]* @"str_test/testdata/compiler/float-intrinsics.rb", i64 0, i64 0), i64 42) #8
  tail call void @rb_gc_register_mark_object(i64 %29) #8
  store i64 %29, i64* @"rubyStrFrozen_test/testdata/compiler/float-intrinsics.rb", align 8
  %30 = bitcast [0 x i64]* %locals1.i.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 0, i8* nonnull %30)
  %rubyId_plus.i.i = load i64, i64* @rubyIdPrecomputed_plus, align 8
  %rubyStr_plus.i.i = load i64, i64* @rubyStrFrozen_plus, align 8
  %locals1.sub.i.i = getelementptr inbounds [0 x i64], [0 x i64]* %locals1.i.i, i64 0, i64 0
  %31 = call i8* @sorbet_allocateRubyStackFrame(i64 %rubyStr_plus.i.i, i64 %rubyId_plus.i.i, i64 %29, i64 %realpath, i8* null, i32 1, i32 8, i32 10, i64* nonnull %locals1.sub.i.i, i32 0, i32 2)
  store i8* %31, i8** @"stackFramePrecomputed_func_Object#plus", align 8
  call void @llvm.lifetime.end.p0i8(i64 0, i8* nonnull %30)
  %"rubyId_+.i" = load i64, i64* @"rubyIdPrecomputed_+", align 8, !dbg !43
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @"ic_+", i64 %"rubyId_+.i", i32 16, i32 1, i32 0, i64* null), !dbg !43
  %32 = call i64 @rb_fstring_new(i8* getelementptr inbounds ([6 x i8], [6 x i8]* @str_minus, i64 0, i64 0), i64 5) #8
  call void @rb_gc_register_mark_object(i64 %32) #8
  call void @llvm.lifetime.start.p0i8(i64 0, i8* nonnull %30)
  %rubyId_minus.i.i = load i64, i64* @rubyIdPrecomputed_minus, align 8
  %"rubyStr_test/testdata/compiler/float-intrinsics.rb.i179.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/float-intrinsics.rb", align 8
  %33 = call i8* @sorbet_allocateRubyStackFrame(i64 %32, i64 %rubyId_minus.i.i, i64 %"rubyStr_test/testdata/compiler/float-intrinsics.rb.i179.i", i64 %realpath, i8* null, i32 1, i32 13, i32 15, i64* nonnull %locals1.sub.i.i, i32 0, i32 2)
  store i8* %33, i8** @"stackFramePrecomputed_func_Object#minus", align 8
  call void @llvm.lifetime.end.p0i8(i64 0, i8* nonnull %30)
  %rubyId_-.i = load i64, i64* @rubyIdPrecomputed_-, align 8, !dbg !53
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_-, i64 %rubyId_-.i, i32 16, i32 1, i32 0, i64* null), !dbg !53
  %34 = call i64 @rb_fstring_new(i8* getelementptr inbounds ([3 x i8], [3 x i8]* @str_lt, i64 0, i64 0), i64 2) #8
  call void @rb_gc_register_mark_object(i64 %34) #8
  call void @llvm.lifetime.start.p0i8(i64 0, i8* nonnull %30)
  %rubyId_lt.i.i = load i64, i64* @rubyIdPrecomputed_lt, align 8
  %"rubyStr_test/testdata/compiler/float-intrinsics.rb.i182.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/float-intrinsics.rb", align 8
  %35 = call i8* @sorbet_allocateRubyStackFrame(i64 %34, i64 %rubyId_lt.i.i, i64 %"rubyStr_test/testdata/compiler/float-intrinsics.rb.i182.i", i64 %realpath, i8* null, i32 1, i32 18, i32 20, i64* nonnull %locals1.sub.i.i, i32 0, i32 2)
  store i8* %35, i8** @"stackFramePrecomputed_func_Object#lt", align 8
  call void @llvm.lifetime.end.p0i8(i64 0, i8* nonnull %30)
  %"rubyId_<.i" = load i64, i64* @"rubyIdPrecomputed_<", align 8, !dbg !58
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @"ic_<", i64 %"rubyId_<.i", i32 16, i32 1, i32 0, i64* null), !dbg !58
  %36 = call i64 @rb_fstring_new(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_lte, i64 0, i64 0), i64 3) #8
  call void @rb_gc_register_mark_object(i64 %36) #8
  call void @llvm.lifetime.start.p0i8(i64 0, i8* nonnull %30)
  %rubyId_lte.i.i = load i64, i64* @rubyIdPrecomputed_lte, align 8
  %"rubyStr_test/testdata/compiler/float-intrinsics.rb.i185.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/float-intrinsics.rb", align 8
  %37 = call i8* @sorbet_allocateRubyStackFrame(i64 %36, i64 %rubyId_lte.i.i, i64 %"rubyStr_test/testdata/compiler/float-intrinsics.rb.i185.i", i64 %realpath, i8* null, i32 1, i32 23, i32 25, i64* nonnull %locals1.sub.i.i, i32 0, i32 2)
  store i8* %37, i8** @"stackFramePrecomputed_func_Object#lte", align 8
  call void @llvm.lifetime.end.p0i8(i64 0, i8* nonnull %30)
  %"rubyId_<=.i" = load i64, i64* @"rubyIdPrecomputed_<=", align 8, !dbg !69
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @"ic_<=", i64 %"rubyId_<=.i", i32 16, i32 1, i32 0, i64* null), !dbg !69
  %38 = call i64 @rb_fstring_new(i8* getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 16) #8
  call void @rb_gc_register_mark_object(i64 %38) #8
  %"rubyId_<top (required)>.i.i" = load i64, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %"rubyStr_test/testdata/compiler/float-intrinsics.rb.i187.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/float-intrinsics.rb", align 8
  %39 = call i8* @sorbet_allocateRubyStackFrame(i64 %38, i64 %"rubyId_<top (required)>.i.i", i64 %"rubyStr_test/testdata/compiler/float-intrinsics.rb.i187.i", i64 %realpath, i8* null, i32 1, i32 1, i32 48, i64* getelementptr inbounds ([2 x i64], [2 x i64]* @"<static-init-locals-storage>", i64 0, i64 0), i32 2, i32 4)
  store i8* %39, i8** @"stackFramePrecomputed_func_<root>.<static-init>$152", align 8
  %40 = call i64 @rb_fstring_new(i8* getelementptr inbounds ([10 x i8], [10 x i8]* @"str_block for", i64 0, i64 0), i64 9) #8
  call void @rb_gc_register_mark_object(i64 %40) #8
  store i64 %40, i64* @"rubyStrFrozen_block for", align 8
  %"stackFrame_func_<root>.<static-init>$152.i.i" = load i8*, i8** @"stackFramePrecomputed_func_<root>.<static-init>$152", align 8
  %"rubyId_block for.i.i" = load i64, i64* @"rubyIdPrecomputed_block for", align 8
  %"rubyStr_test/testdata/compiler/float-intrinsics.rb.i188.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/float-intrinsics.rb", align 8
  %41 = call i8* @sorbet_allocateRubyStackFrame(i64 %40, i64 %"rubyId_block for.i.i", i64 %"rubyStr_test/testdata/compiler/float-intrinsics.rb.i188.i", i64 %realpath, i8* %"stackFrame_func_<root>.<static-init>$152.i.i", i32 2, i32 1, i32 48, i64* null, i32 0, i32 4)
  store i8* %41, i8** @"stackFramePrecomputed_func_<root>.<static-init>$152$block_1", align 8
  %"stackFrame_func_<root>.<static-init>$152.i189.i" = load i8*, i8** @"stackFramePrecomputed_func_<root>.<static-init>$152", align 8
  %"rubyId_block for.i190.i" = load i64, i64* @"rubyIdPrecomputed_block for", align 8
  %"rubyStr_block for.i191.i" = load i64, i64* @"rubyStrFrozen_block for", align 8
  %"rubyStr_test/testdata/compiler/float-intrinsics.rb.i192.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/float-intrinsics.rb", align 8
  %42 = call i8* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_block for.i191.i", i64 %"rubyId_block for.i190.i", i64 %"rubyStr_test/testdata/compiler/float-intrinsics.rb.i192.i", i64 %realpath, i8* %"stackFrame_func_<root>.<static-init>$152.i189.i", i32 2, i32 1, i32 48, i64* null, i32 0, i32 4)
  store i8* %42, i8** @"stackFramePrecomputed_func_<root>.<static-init>$152$block_2", align 8
  %"stackFrame_func_<root>.<static-init>$152.i193.i" = load i8*, i8** @"stackFramePrecomputed_func_<root>.<static-init>$152", align 8
  %"rubyId_block for.i194.i" = load i64, i64* @"rubyIdPrecomputed_block for", align 8
  %"rubyStr_block for.i195.i" = load i64, i64* @"rubyStrFrozen_block for", align 8
  %"rubyStr_test/testdata/compiler/float-intrinsics.rb.i196.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/float-intrinsics.rb", align 8
  %43 = call i8* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_block for.i195.i", i64 %"rubyId_block for.i194.i", i64 %"rubyStr_test/testdata/compiler/float-intrinsics.rb.i196.i", i64 %realpath, i8* %"stackFrame_func_<root>.<static-init>$152.i193.i", i32 2, i32 1, i32 48, i64* null, i32 0, i32 4)
  store i8* %43, i8** @"stackFramePrecomputed_func_<root>.<static-init>$152$block_3", align 8
  %"stackFrame_func_<root>.<static-init>$152.i197.i" = load i8*, i8** @"stackFramePrecomputed_func_<root>.<static-init>$152", align 8
  %"rubyId_block for.i198.i" = load i64, i64* @"rubyIdPrecomputed_block for", align 8
  %"rubyStr_block for.i199.i" = load i64, i64* @"rubyStrFrozen_block for", align 8
  %"rubyStr_test/testdata/compiler/float-intrinsics.rb.i200.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/float-intrinsics.rb", align 8
  %44 = call i8* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_block for.i199.i", i64 %"rubyId_block for.i198.i", i64 %"rubyStr_test/testdata/compiler/float-intrinsics.rb.i200.i", i64 %realpath, i8* %"stackFrame_func_<root>.<static-init>$152.i197.i", i32 2, i32 1, i32 48, i64* null, i32 0, i32 4)
  store i8* %44, i8** @"stackFramePrecomputed_func_<root>.<static-init>$152$block_4", align 8
  %rubyId_sig.i = load i64, i64* @rubyIdPrecomputed_sig, align 8, !dbg !82
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_sig, i64 %rubyId_sig.i, i32 20, i32 1, i32 0, i64* null), !dbg !82
  %rubyId_untyped.i = load i64, i64* @rubyIdPrecomputed_untyped, align 8, !dbg !83
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_untyped, i64 %rubyId_untyped.i, i32 16, i32 0, i32 0, i64* null), !dbg !83
  %rubyId_params.i = load i64, i64* @rubyIdPrecomputed_params, align 8, !dbg !73
  %keywords174.sub.i = getelementptr inbounds [2 x i64], [2 x i64]* %keywords174.i, i64 0, i64 0
  %rubyId_x.i = load i64, i64* @rubyIdPrecomputed_x, align 8, !dbg !73
  %45 = call i64 @rb_id2sym(i64 %rubyId_x.i) #8, !dbg !73
  store i64 %45, i64* %keywords174.sub.i, align 8, !dbg !73
  %rubyId_y.i = load i64, i64* @rubyIdPrecomputed_y, align 8, !dbg !73
  %46 = call i64 @rb_id2sym(i64 %rubyId_y.i) #8, !dbg !73
  %47 = getelementptr inbounds [2 x i64], [2 x i64]* %keywords174.i, i64 0, i64 1, !dbg !73
  store i64 %46, i64* %47, align 8, !dbg !73
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_params, i64 %rubyId_params.i, i32 68, i32 2, i32 2, i64* nonnull %keywords174.sub.i), !dbg !73
  %rubyId_untyped8.i = load i64, i64* @rubyIdPrecomputed_untyped, align 8, !dbg !84
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_untyped.1, i64 %rubyId_untyped8.i, i32 16, i32 0, i32 0, i64* null), !dbg !84
  %rubyId_returns.i = load i64, i64* @rubyIdPrecomputed_returns, align 8, !dbg !73
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_returns, i64 %rubyId_returns.i, i32 16, i32 1, i32 0, i64* null), !dbg !73
  %rubyId_sig11.i = load i64, i64* @rubyIdPrecomputed_sig, align 8, !dbg !85
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_sig.2, i64 %rubyId_sig11.i, i32 20, i32 1, i32 0, i64* null), !dbg !85
  %rubyId_untyped14.i = load i64, i64* @rubyIdPrecomputed_untyped, align 8, !dbg !86
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_untyped.3, i64 %rubyId_untyped14.i, i32 16, i32 0, i32 0, i64* null), !dbg !86
  %rubyId_params16.i = load i64, i64* @rubyIdPrecomputed_params, align 8, !dbg !76
  %keywords17175.sub.i = getelementptr inbounds [2 x i64], [2 x i64]* %keywords17175.i, i64 0, i64 0
  %rubyId_x18.i = load i64, i64* @rubyIdPrecomputed_x, align 8, !dbg !76
  %48 = call i64 @rb_id2sym(i64 %rubyId_x18.i) #8, !dbg !76
  store i64 %48, i64* %keywords17175.sub.i, align 8, !dbg !76
  %rubyId_y20.i = load i64, i64* @rubyIdPrecomputed_y, align 8, !dbg !76
  %49 = call i64 @rb_id2sym(i64 %rubyId_y20.i) #8, !dbg !76
  %50 = getelementptr inbounds [2 x i64], [2 x i64]* %keywords17175.i, i64 0, i64 1, !dbg !76
  store i64 %49, i64* %50, align 8, !dbg !76
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_params.4, i64 %rubyId_params16.i, i32 68, i32 2, i32 2, i64* nonnull %keywords17175.sub.i), !dbg !76
  %rubyId_untyped24.i = load i64, i64* @rubyIdPrecomputed_untyped, align 8, !dbg !87
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_untyped.5, i64 %rubyId_untyped24.i, i32 16, i32 0, i32 0, i64* null), !dbg !87
  %rubyId_returns26.i = load i64, i64* @rubyIdPrecomputed_returns, align 8, !dbg !76
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_returns.6, i64 %rubyId_returns26.i, i32 16, i32 1, i32 0, i64* null), !dbg !76
  %rubyId_sig28.i = load i64, i64* @rubyIdPrecomputed_sig, align 8, !dbg !88
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_sig.7, i64 %rubyId_sig28.i, i32 20, i32 1, i32 0, i64* null), !dbg !88
  %rubyId_untyped31.i = load i64, i64* @rubyIdPrecomputed_untyped, align 8, !dbg !89
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_untyped.8, i64 %rubyId_untyped31.i, i32 16, i32 0, i32 0, i64* null), !dbg !89
  %rubyId_params33.i = load i64, i64* @rubyIdPrecomputed_params, align 8, !dbg !78
  %keywords34176.sub.i = getelementptr inbounds [2 x i64], [2 x i64]* %keywords34176.i, i64 0, i64 0
  %rubyId_x35.i = load i64, i64* @rubyIdPrecomputed_x, align 8, !dbg !78
  %51 = call i64 @rb_id2sym(i64 %rubyId_x35.i) #8, !dbg !78
  store i64 %51, i64* %keywords34176.sub.i, align 8, !dbg !78
  %rubyId_y37.i = load i64, i64* @rubyIdPrecomputed_y, align 8, !dbg !78
  %52 = call i64 @rb_id2sym(i64 %rubyId_y37.i) #8, !dbg !78
  %53 = getelementptr inbounds [2 x i64], [2 x i64]* %keywords34176.i, i64 0, i64 1, !dbg !78
  store i64 %52, i64* %53, align 8, !dbg !78
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_params.9, i64 %rubyId_params33.i, i32 68, i32 2, i32 2, i64* nonnull %keywords34176.sub.i), !dbg !78
  %rubyId_returns41.i = load i64, i64* @rubyIdPrecomputed_returns, align 8, !dbg !78
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_returns.10, i64 %rubyId_returns41.i, i32 16, i32 1, i32 0, i64* null), !dbg !78
  %rubyId_sig43.i = load i64, i64* @rubyIdPrecomputed_sig, align 8, !dbg !90
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_sig.11, i64 %rubyId_sig43.i, i32 20, i32 1, i32 0, i64* null), !dbg !90
  %rubyId_untyped46.i = load i64, i64* @rubyIdPrecomputed_untyped, align 8, !dbg !91
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_untyped.12, i64 %rubyId_untyped46.i, i32 16, i32 0, i32 0, i64* null), !dbg !91
  %rubyId_params48.i = load i64, i64* @rubyIdPrecomputed_params, align 8, !dbg !80
  %keywords49177.sub.i = getelementptr inbounds [2 x i64], [2 x i64]* %keywords49177.i, i64 0, i64 0
  %rubyId_x50.i = load i64, i64* @rubyIdPrecomputed_x, align 8, !dbg !80
  %54 = call i64 @rb_id2sym(i64 %rubyId_x50.i) #8, !dbg !80
  store i64 %54, i64* %keywords49177.sub.i, align 8, !dbg !80
  %rubyId_y52.i = load i64, i64* @rubyIdPrecomputed_y, align 8, !dbg !80
  %55 = call i64 @rb_id2sym(i64 %rubyId_y52.i) #8, !dbg !80
  %56 = getelementptr inbounds [2 x i64], [2 x i64]* %keywords49177.i, i64 0, i64 1, !dbg !80
  store i64 %55, i64* %56, align 8, !dbg !80
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_params.13, i64 %rubyId_params48.i, i32 68, i32 2, i32 2, i64* nonnull %keywords49177.sub.i), !dbg !80
  %rubyId_returns56.i = load i64, i64* @rubyIdPrecomputed_returns, align 8, !dbg !80
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_returns.14, i64 %rubyId_returns56.i, i32 16, i32 1, i32 0, i64* null), !dbg !80
  %rubyId_extend.i = load i64, i64* @rubyIdPrecomputed_extend, align 8, !dbg !92
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_extend, i64 %rubyId_extend.i, i32 20, i32 1, i32 0, i64* null), !dbg !92
  %rubyId_keep_def.i = load i64, i64* @rubyIdPrecomputed_keep_def, align 8, !dbg !93
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_keep_def, i64 %rubyId_keep_def.i, i32 16, i32 3, i32 0, i64* null), !dbg !93
  %rubyId_keep_def61.i = load i64, i64* @rubyIdPrecomputed_keep_def, align 8, !dbg !94
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_keep_def.15, i64 %rubyId_keep_def61.i, i32 16, i32 3, i32 0, i64* null), !dbg !94
  %rubyId_keep_def63.i = load i64, i64* @rubyIdPrecomputed_keep_def, align 8, !dbg !95
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_keep_def.16, i64 %rubyId_keep_def63.i, i32 16, i32 3, i32 0, i64* null), !dbg !95
  %rubyId_keep_def65.i = load i64, i64* @rubyIdPrecomputed_keep_def, align 8, !dbg !96
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_keep_def.17, i64 %rubyId_keep_def65.i, i32 16, i32 3, i32 0, i64* null), !dbg !96
  %rubyId_plus.i = load i64, i64* @rubyIdPrecomputed_plus, align 8, !dbg !97
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_plus, i64 %rubyId_plus.i, i32 20, i32 2, i32 0, i64* null), !dbg !97
  %rubyId_p.i = load i64, i64* @rubyIdPrecomputed_p, align 8, !dbg !98
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_p, i64 %rubyId_p.i, i32 20, i32 1, i32 0, i64* null), !dbg !98
  %rubyId_minus.i = load i64, i64* @rubyIdPrecomputed_minus, align 8, !dbg !99
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_minus, i64 %rubyId_minus.i, i32 20, i32 2, i32 0, i64* null), !dbg !99
  %rubyId_p73.i = load i64, i64* @rubyIdPrecomputed_p, align 8, !dbg !100
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_p.18, i64 %rubyId_p73.i, i32 20, i32 1, i32 0, i64* null), !dbg !100
  %rubyId_lt.i = load i64, i64* @rubyIdPrecomputed_lt, align 8, !dbg !101
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_lt, i64 %rubyId_lt.i, i32 20, i32 2, i32 0, i64* null), !dbg !101
  %rubyId_p78.i = load i64, i64* @rubyIdPrecomputed_p, align 8, !dbg !102
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_p.19, i64 %rubyId_p78.i, i32 20, i32 1, i32 0, i64* null), !dbg !102
  %rubyId_lt81.i = load i64, i64* @rubyIdPrecomputed_lt, align 8, !dbg !103
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_lt.20, i64 %rubyId_lt81.i, i32 20, i32 2, i32 0, i64* null), !dbg !103
  %rubyId_p84.i = load i64, i64* @rubyIdPrecomputed_p, align 8, !dbg !104
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_p.21, i64 %rubyId_p84.i, i32 20, i32 1, i32 0, i64* null), !dbg !104
  %rubyId_lte.i = load i64, i64* @rubyIdPrecomputed_lte, align 8, !dbg !105
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_lte, i64 %rubyId_lte.i, i32 20, i32 2, i32 0, i64* null), !dbg !105
  %rubyId_p89.i = load i64, i64* @rubyIdPrecomputed_p, align 8, !dbg !106
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_p.22, i64 %rubyId_p89.i, i32 20, i32 1, i32 0, i64* null), !dbg !106
  %rubyId_lte92.i = load i64, i64* @rubyIdPrecomputed_lte, align 8, !dbg !107
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_lte.23, i64 %rubyId_lte92.i, i32 20, i32 2, i32 0, i64* null), !dbg !107
  %rubyId_p95.i = load i64, i64* @rubyIdPrecomputed_p, align 8, !dbg !108
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_p.24, i64 %rubyId_p95.i, i32 20, i32 1, i32 0, i64* null), !dbg !108
  %rubyId_lte98.i = load i64, i64* @rubyIdPrecomputed_lte, align 8, !dbg !109
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_lte.25, i64 %rubyId_lte98.i, i32 20, i32 2, i32 0, i64* null), !dbg !109
  %rubyId_p101.i = load i64, i64* @rubyIdPrecomputed_p, align 8, !dbg !110
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_p.26, i64 %rubyId_p101.i, i32 20, i32 1, i32 0, i64* null), !dbg !110
  %rubyId_plus104.i = load i64, i64* @rubyIdPrecomputed_plus, align 8, !dbg !111
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_plus.27, i64 %rubyId_plus104.i, i32 20, i32 2, i32 0, i64* null), !dbg !111
  %rubyId_p107.i = load i64, i64* @rubyIdPrecomputed_p, align 8, !dbg !112
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_p.28, i64 %rubyId_p107.i, i32 20, i32 1, i32 0, i64* null), !dbg !112
  %57 = call i64 @rb_fstring_new(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_8.9, i64 0, i64 0), i64 3) #8
  call void @rb_gc_register_mark_object(i64 %57) #8
  store i64 %57, i64* @rubyStrFrozen_8.9, align 8
  %rubyId_Rational.i = load i64, i64* @rubyIdPrecomputed_Rational, align 8, !dbg !113
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_Rational, i64 %rubyId_Rational.i, i32 16, i32 1, i32 0, i64* null), !dbg !113
  %rubyId_plus111.i = load i64, i64* @rubyIdPrecomputed_plus, align 8, !dbg !114
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_plus.29, i64 %rubyId_plus111.i, i32 20, i32 2, i32 0, i64* null), !dbg !114
  %rubyId_p114.i = load i64, i64* @rubyIdPrecomputed_p, align 8, !dbg !115
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_p.30, i64 %rubyId_p114.i, i32 20, i32 1, i32 0, i64* null), !dbg !115
  %58 = call i64 @rb_fstring_new(i8* getelementptr inbounds ([2 x i8], [2 x i8]* @str_5, i64 0, i64 0), i64 1) #8
  call void @rb_gc_register_mark_object(i64 %58) #8
  store i64 %58, i64* @rubyStrFrozen_5, align 8
  %rubyId_Complex.i = load i64, i64* @rubyIdPrecomputed_Complex, align 8, !dbg !116
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_Complex, i64 %rubyId_Complex.i, i32 16, i32 2, i32 0, i64* null), !dbg !116
  %rubyId_plus118.i = load i64, i64* @rubyIdPrecomputed_plus, align 8, !dbg !117
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_plus.31, i64 %rubyId_plus118.i, i32 20, i32 2, i32 0, i64* null), !dbg !117
  %rubyId_p121.i = load i64, i64* @rubyIdPrecomputed_p, align 8, !dbg !118
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_p.32, i64 %rubyId_p121.i, i32 20, i32 1, i32 0, i64* null), !dbg !118
  %rubyId_minus124.i = load i64, i64* @rubyIdPrecomputed_minus, align 8, !dbg !119
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_minus.33, i64 %rubyId_minus124.i, i32 20, i32 2, i32 0, i64* null), !dbg !119
  %rubyId_p127.i = load i64, i64* @rubyIdPrecomputed_p, align 8, !dbg !120
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_p.34, i64 %rubyId_p127.i, i32 20, i32 1, i32 0, i64* null), !dbg !120
  %59 = call i64 @rb_fstring_new(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_15.4, i64 0, i64 0), i64 4) #8
  call void @rb_gc_register_mark_object(i64 %59) #8
  store i64 %59, i64* @rubyStrFrozen_15.4, align 8
  %rubyId_Rational130.i = load i64, i64* @rubyIdPrecomputed_Rational, align 8, !dbg !121
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_Rational.35, i64 %rubyId_Rational130.i, i32 16, i32 1, i32 0, i64* null), !dbg !121
  %rubyId_minus132.i = load i64, i64* @rubyIdPrecomputed_minus, align 8, !dbg !122
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_minus.36, i64 %rubyId_minus132.i, i32 20, i32 2, i32 0, i64* null), !dbg !122
  %rubyId_p135.i = load i64, i64* @rubyIdPrecomputed_p, align 8, !dbg !123
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_p.37, i64 %rubyId_p135.i, i32 20, i32 1, i32 0, i64* null), !dbg !123
  %60 = call i64 @rb_fstring_new(i8* getelementptr inbounds ([3 x i8], [3 x i8]* @str_18, i64 0, i64 0), i64 2) #8
  call void @rb_gc_register_mark_object(i64 %60) #8
  store i64 %60, i64* @rubyStrFrozen_18, align 8
  %rubyId_Complex138.i = load i64, i64* @rubyIdPrecomputed_Complex, align 8, !dbg !124
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_Complex.38, i64 %rubyId_Complex138.i, i32 16, i32 2, i32 0, i64* null), !dbg !124
  %rubyId_minus140.i = load i64, i64* @rubyIdPrecomputed_minus, align 8, !dbg !125
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_minus.39, i64 %rubyId_minus140.i, i32 20, i32 2, i32 0, i64* null), !dbg !125
  %rubyId_p143.i = load i64, i64* @rubyIdPrecomputed_p, align 8, !dbg !126
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_p.40, i64 %rubyId_p143.i, i32 20, i32 1, i32 0, i64* null), !dbg !126
  %rubyId_lt146.i = load i64, i64* @rubyIdPrecomputed_lt, align 8, !dbg !127
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_lt.41, i64 %rubyId_lt146.i, i32 20, i32 2, i32 0, i64* null), !dbg !127
  %rubyId_p149.i = load i64, i64* @rubyIdPrecomputed_p, align 8, !dbg !128
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_p.42, i64 %rubyId_p149.i, i32 20, i32 1, i32 0, i64* null), !dbg !128
  %61 = call i64 @rb_fstring_new(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_25.4, i64 0, i64 0), i64 4) #8
  call void @rb_gc_register_mark_object(i64 %61) #8
  store i64 %61, i64* @rubyStrFrozen_25.4, align 8
  %rubyId_Rational152.i = load i64, i64* @rubyIdPrecomputed_Rational, align 8, !dbg !129
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_Rational.43, i64 %rubyId_Rational152.i, i32 16, i32 1, i32 0, i64* null), !dbg !129
  %rubyId_lt154.i = load i64, i64* @rubyIdPrecomputed_lt, align 8, !dbg !130
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_lt.44, i64 %rubyId_lt154.i, i32 20, i32 2, i32 0, i64* null), !dbg !130
  %rubyId_p157.i = load i64, i64* @rubyIdPrecomputed_p, align 8, !dbg !131
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_p.45, i64 %rubyId_p157.i, i32 20, i32 1, i32 0, i64* null), !dbg !131
  %rubyId_lte160.i = load i64, i64* @rubyIdPrecomputed_lte, align 8, !dbg !132
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_lte.46, i64 %rubyId_lte160.i, i32 20, i32 2, i32 0, i64* null), !dbg !132
  %rubyId_p163.i = load i64, i64* @rubyIdPrecomputed_p, align 8, !dbg !133
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_p.47, i64 %rubyId_p163.i, i32 20, i32 1, i32 0, i64* null), !dbg !133
  %62 = call i64 @rb_fstring_new(i8* getelementptr inbounds ([6 x i8], [6 x i8]* @str_5.923, i64 0, i64 0), i64 5) #8
  call void @rb_gc_register_mark_object(i64 %62) #8
  store i64 %62, i64* @rubyStrFrozen_5.923, align 8
  %rubyId_Rational166.i = load i64, i64* @rubyIdPrecomputed_Rational, align 8, !dbg !134
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_Rational.48, i64 %rubyId_Rational166.i, i32 16, i32 1, i32 0, i64* null), !dbg !134
  %rubyId_lte168.i = load i64, i64* @rubyIdPrecomputed_lte, align 8, !dbg !135
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_lte.49, i64 %rubyId_lte168.i, i32 20, i32 2, i32 0, i64* null), !dbg !135
  %rubyId_p171.i = load i64, i64* @rubyIdPrecomputed_p, align 8, !dbg !136
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* nonnull @ic_p.50, i64 %rubyId_p171.i, i32 20, i32 1, i32 0, i64* null), !dbg !136
  call void @llvm.lifetime.end.p0i8(i64 16, i8* nonnull %0)
  call void @llvm.lifetime.end.p0i8(i64 16, i8* nonnull %1)
  call void @llvm.lifetime.end.p0i8(i64 16, i8* nonnull %2)
  call void @llvm.lifetime.end.p0i8(i64 16, i8* nonnull %3)
  %63 = load %struct.rb_vm_struct*, %struct.rb_vm_struct** @ruby_current_vm_ptr, align 8, !tbaa !12
  %64 = getelementptr inbounds %struct.rb_vm_struct, %struct.rb_vm_struct* %63, i64 0, i32 18
  %65 = load i64, i64* %64, align 8, !tbaa !137
  %"stackFrame_func_<root>.<static-init>$152.i" = load i8*, i8** @"stackFramePrecomputed_func_<root>.<static-init>$152", align 8
  %66 = bitcast i8* %"stackFrame_func_<root>.<static-init>$152.i" to %struct.rb_iseq_struct*
  %67 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !12
  %68 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %67, i64 0, i32 2
  %69 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %68, align 8, !tbaa !14
  %70 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %69, i64 0, i32 2
  %71 = bitcast %struct.rb_iseq_struct** %70 to i8**
  store i8* %"stackFrame_func_<root>.<static-init>$152.i", i8** %71, align 8, !tbaa !18
  %72 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %69, i64 0, i32 4
  %73 = load i64*, i64** %72, align 8, !tbaa !20
  %74 = load i64, i64* %73, align 8, !tbaa !4
  %75 = and i64 %74, -129
  store i64 %75, i64* %73, align 8, !tbaa !4
  call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* %67, %struct.rb_control_frame_struct* nonnull %69, %struct.rb_iseq_struct* %66) #8
  %76 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %69, i64 0, i32 0
  %77 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %70, align 8, !tbaa !18
  %78 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %77, i64 0, i32 2
  %79 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %78, align 8, !tbaa !21
  %80 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %79, i64 0, i32 2
  %81 = load i64*, i64** %80, align 8, !tbaa !23
  %82 = getelementptr inbounds i64, i64* %81, i64 5
  store i64* %82, i64** %76, align 8, !tbaa !12
  %83 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !92, !tbaa !12
  %84 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %83, i64 0, i32 2, !dbg !92
  %85 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %84, align 8, !dbg !92, !tbaa !14
  %86 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %85, i64 0, i32 4, !dbg !92
  %87 = load i64*, i64** %86, align 8, !dbg !92, !tbaa !20
  %88 = load i64, i64* %87, align 8, !dbg !92, !tbaa !4
  %89 = and i64 %88, 8, !dbg !92
  %90 = icmp eq i64 %89, 0, !dbg !92
  br i1 %90, label %91, label %93, !dbg !92, !prof !38

91:                                               ; preds = %entry
  %92 = getelementptr inbounds i64, i64* %87, i64 -3, !dbg !92
  store i64 %65, i64* %92, align 8, !dbg !92, !tbaa !4
  br label %sorbet_writeLocal.exit.i, !dbg !92

93:                                               ; preds = %entry
  call void @sorbet_vm_env_write_slowpath(i64* nonnull %87, i32 -3, i64 %65) #8, !dbg !92
  br label %sorbet_writeLocal.exit.i, !dbg !92

sorbet_writeLocal.exit.i:                         ; preds = %93, %91
  %94 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !146, !tbaa !12
  %95 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %94, i64 0, i32 2, !dbg !146
  %96 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %95, align 8, !dbg !146, !tbaa !14
  %97 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %96, i64 0, i32 4, !dbg !146
  %98 = load i64*, i64** %97, align 8, !dbg !146, !tbaa !20
  %99 = load i64, i64* %98, align 8, !dbg !146, !tbaa !4
  %100 = and i64 %99, 8, !dbg !146
  %101 = icmp eq i64 %100, 0, !dbg !146
  br i1 %101, label %afterSend235.critedge.i, label %102, !dbg !146, !prof !38

102:                                              ; preds = %sorbet_writeLocal.exit.i
  %103 = getelementptr inbounds i64, i64* %98, i64 -3, !dbg !146
  %104 = load i64, i64* %103, align 8, !dbg !146, !tbaa !4
  call void @sorbet_vm_env_write_slowpath(i64* nonnull %98, i32 -3, i64 %104) #8, !dbg !146
  br label %afterSend235.critedge.i, !dbg !146

afterSend235.critedge.i:                          ; preds = %102, %sorbet_writeLocal.exit.i
  %105 = getelementptr inbounds i64, i64* %81, i64 7, !dbg !146
  store i64* %105, i64** %76, align 8, !dbg !146, !tbaa !12
  %106 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !146, !tbaa !12
  %107 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %106, i64 0, i32 2, !dbg !146
  %108 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %107, align 8, !dbg !146, !tbaa !14
  %109 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %108, i64 0, i32 4, !dbg !146
  %110 = load i64*, i64** %109, align 8, !dbg !146, !tbaa !20
  %111 = load i64, i64* %110, align 8, !dbg !82, !tbaa !4
  %112 = and i64 %111, 8, !dbg !82
  %113 = icmp eq i64 %112, 0, !dbg !82
  br i1 %113, label %afterSend235.i, label %114, !dbg !82, !prof !38

114:                                              ; preds = %afterSend235.critedge.i
  %115 = getelementptr inbounds i64, i64* %110, i64 -3, !dbg !146
  %116 = load i64, i64* %115, align 8, !dbg !146, !tbaa !4
  call void @sorbet_vm_env_write_slowpath(i64* nonnull %110, i32 -3, i64 %116) #8, !dbg !82
  br label %afterSend235.i, !dbg !82

afterSend235.i:                                   ; preds = %114, %afterSend235.critedge.i
  %117 = getelementptr inbounds i64, i64* %81, i64 12, !dbg !82
  store i64* %117, i64** %76, align 8, !dbg !82, !tbaa !12
  %118 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !146, !tbaa !12
  %119 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %118, i64 0, i32 2, !dbg !146
  %120 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %119, align 8, !dbg !146, !tbaa !14
  %121 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %120, i64 0, i32 4, !dbg !146
  %122 = load i64*, i64** %121, align 8, !dbg !146, !tbaa !20
  %123 = load i64, i64* %122, align 8, !dbg !85, !tbaa !4
  %124 = and i64 %123, 8, !dbg !85
  %125 = icmp eq i64 %124, 0, !dbg !85
  br i1 %125, label %afterSend251.critedge.i, label %126, !dbg !85, !prof !38

126:                                              ; preds = %afterSend235.i
  %127 = getelementptr inbounds i64, i64* %122, i64 -3, !dbg !146
  %128 = load i64, i64* %127, align 8, !dbg !146, !tbaa !4
  call void @sorbet_vm_env_write_slowpath(i64* nonnull %122, i32 -3, i64 %128) #8, !dbg !85
  br label %afterSend251.critedge.i, !dbg !85

afterSend251.critedge.i:                          ; preds = %126, %afterSend235.i
  %129 = getelementptr inbounds i64, i64* %81, i64 17, !dbg !85
  store i64* %129, i64** %76, align 8, !dbg !85, !tbaa !12
  %130 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !146, !tbaa !12
  %131 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %130, i64 0, i32 2, !dbg !146
  %132 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %131, align 8, !dbg !146, !tbaa !14
  %133 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %132, i64 0, i32 4, !dbg !146
  %134 = load i64*, i64** %133, align 8, !dbg !146, !tbaa !20
  %135 = load i64, i64* %134, align 8, !dbg !88, !tbaa !4
  %136 = and i64 %135, 8, !dbg !88
  %137 = icmp eq i64 %136, 0, !dbg !88
  br i1 %137, label %afterSend251.i, label %138, !dbg !88, !prof !38

138:                                              ; preds = %afterSend251.critedge.i
  %139 = getelementptr inbounds i64, i64* %134, i64 -3, !dbg !146
  %140 = load i64, i64* %139, align 8, !dbg !146, !tbaa !4
  call void @sorbet_vm_env_write_slowpath(i64* nonnull %134, i32 -3, i64 %140) #8, !dbg !88
  br label %afterSend251.i, !dbg !88

afterSend251.i:                                   ; preds = %138, %afterSend251.critedge.i
  %141 = getelementptr inbounds i64, i64* %81, i64 22, !dbg !88
  store i64* %141, i64** %76, align 8, !dbg !88, !tbaa !12
  %142 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !146, !tbaa !12
  %143 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %142, i64 0, i32 2, !dbg !146
  %144 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %143, align 8, !dbg !146, !tbaa !14
  %145 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %144, i64 0, i32 4, !dbg !146
  %146 = load i64*, i64** %145, align 8, !dbg !146, !tbaa !20
  %147 = load i64, i64* %146, align 8, !dbg !90, !tbaa !4
  %148 = and i64 %147, 8, !dbg !90
  %149 = icmp eq i64 %148, 0, !dbg !90
  br i1 %149, label %"func_<root>.<static-init>$152.exit", label %150, !dbg !90, !prof !38

150:                                              ; preds = %afterSend251.i
  %151 = getelementptr inbounds i64, i64* %146, i64 -3, !dbg !146
  %152 = load i64, i64* %151, align 8, !dbg !146, !tbaa !4
  call void @sorbet_vm_env_write_slowpath(i64* nonnull %146, i32 -3, i64 %152) #8, !dbg !90
  br label %"func_<root>.<static-init>$152.exit", !dbg !90

"func_<root>.<static-init>$152.exit":             ; preds = %afterSend251.i, %150
  store i64* %82, i64** %76, align 8, !dbg !90, !tbaa !12
  %153 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !92, !tbaa !12
  %154 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %153, i64 0, i32 2, !dbg !92
  %155 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %154, align 8, !dbg !92, !tbaa !14
  %156 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %155, i64 0, i32 4, !dbg !92
  %157 = load i64*, i64** %156, align 8, !dbg !92, !tbaa !20
  %158 = getelementptr inbounds i64, i64* %157, i64 -3, !dbg !92
  %159 = load i64, i64* %158, align 8, !dbg !92, !tbaa !4
  %160 = load i64, i64* @"guard_epoch_T::Sig", align 8, !dbg !92
  %161 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !92, !tbaa !147
  %needTakeSlowPath = icmp eq i64 %160, %161, !dbg !92
  br i1 %needTakeSlowPath, label %163, label %162, !dbg !92, !prof !148

162:                                              ; preds = %"func_<root>.<static-init>$152.exit"
  call void @"const_recompute_T::Sig"(), !dbg !92
  br label %163, !dbg !92

163:                                              ; preds = %"func_<root>.<static-init>$152.exit", %162
  %164 = load i64, i64* @"guarded_const_T::Sig", align 8, !dbg !92
  %165 = load i64, i64* @"guard_epoch_T::Sig", align 8, !dbg !92
  %166 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !92, !tbaa !147
  %guardUpdated = icmp eq i64 %165, %166, !dbg !92
  call void @llvm.assume(i1 %guardUpdated), !dbg !92
  %167 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %155, i64 0, i32 1, !dbg !92
  %168 = load i64*, i64** %167, align 8, !dbg !92, !tbaa !54
  %169 = getelementptr inbounds i64, i64* %168, i64 1, !dbg !92
  store i64 %159, i64* %168, align 8, !dbg !92, !tbaa !4
  %170 = getelementptr inbounds i64, i64* %168, i64 2, !dbg !92
  store i64* %170, i64** %167, align 8, !dbg !92, !tbaa !54
  store i64 %164, i64* %169, align 8, !dbg !92, !tbaa !4
  %send.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_extend, i64 0) #8, !dbg !92
  %171 = getelementptr inbounds i64, i64* %81, i64 8, !dbg !92
  store i64* %171, i64** %76, align 8, !dbg !92, !tbaa !12
  %rubyId_plus.i1 = load i64, i64* @rubyIdPrecomputed_plus, align 8, !dbg !93
  %rawSym.i = call i64 @rb_id2sym(i64 %rubyId_plus.i1) #8, !dbg !93
  %rubyId_normal.i = load i64, i64* @rubyIdPrecomputed_normal, align 8, !dbg !93
  %rawSym260.i = call i64 @rb_id2sym(i64 %rubyId_normal.i) #8, !dbg !93
  %172 = load i64, i64* @rb_cObject, align 8, !dbg !93
  call void @rb_define_method(i64 %172, i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_plus, i64 0, i64 0), i64 (...)* bitcast (i64 (i32, i64*, i64)* @"func_Object#plus" to i64 (...)*), i32 -1) #8, !dbg !93
  %173 = getelementptr inbounds i64, i64* %81, i64 13, !dbg !93
  store i64* %173, i64** %76, align 8, !dbg !93, !tbaa !12
  %rubyId_minus.i2 = load i64, i64* @rubyIdPrecomputed_minus, align 8, !dbg !94
  %rawSym267.i = call i64 @rb_id2sym(i64 %rubyId_minus.i2) #8, !dbg !94
  %rubyId_normal268.i = load i64, i64* @rubyIdPrecomputed_normal, align 8, !dbg !94
  %rawSym269.i = call i64 @rb_id2sym(i64 %rubyId_normal268.i) #8, !dbg !94
  call void @rb_define_method(i64 %172, i8* getelementptr inbounds ([6 x i8], [6 x i8]* @str_minus, i64 0, i64 0), i64 (...)* bitcast (i64 (i32, i64*, i64)* @"func_Object#minus" to i64 (...)*), i32 -1) #8, !dbg !94
  %174 = getelementptr inbounds i64, i64* %81, i64 18, !dbg !94
  store i64* %174, i64** %76, align 8, !dbg !94, !tbaa !12
  %rubyId_lt.i3 = load i64, i64* @rubyIdPrecomputed_lt, align 8, !dbg !95
  %rawSym279.i = call i64 @rb_id2sym(i64 %rubyId_lt.i3) #8, !dbg !95
  %rubyId_normal280.i = load i64, i64* @rubyIdPrecomputed_normal, align 8, !dbg !95
  %rawSym281.i = call i64 @rb_id2sym(i64 %rubyId_normal280.i) #8, !dbg !95
  call void @rb_define_method(i64 %172, i8* getelementptr inbounds ([3 x i8], [3 x i8]* @str_lt, i64 0, i64 0), i64 (...)* bitcast (i64 (i32, i64*, i64)* @"func_Object#lt" to i64 (...)*), i32 -1) #8, !dbg !95
  %175 = getelementptr inbounds i64, i64* %81, i64 23, !dbg !95
  store i64* %175, i64** %76, align 8, !dbg !95, !tbaa !12
  %rubyId_lte.i4 = load i64, i64* @rubyIdPrecomputed_lte, align 8, !dbg !96
  %rawSym291.i = call i64 @rb_id2sym(i64 %rubyId_lte.i4) #8, !dbg !96
  %rubyId_normal292.i = load i64, i64* @rubyIdPrecomputed_normal, align 8, !dbg !96
  %rawSym293.i = call i64 @rb_id2sym(i64 %rubyId_normal292.i) #8, !dbg !96
  call void @rb_define_method(i64 %172, i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_lte, i64 0, i64 0), i64 (...)* bitcast (i64 (i32, i64*, i64)* @"func_Object#lte" to i64 (...)*), i32 -1) #8, !dbg !96
  %176 = getelementptr inbounds i64, i64* %81, i64 27, !dbg !96
  store i64* %176, i64** %76, align 8, !dbg !96, !tbaa !12
  %177 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !97, !tbaa !12
  %178 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %177, i64 0, i32 2, !dbg !97
  %179 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %178, align 8, !dbg !97, !tbaa !14
  %180 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %179, i64 0, i32 4, !dbg !97
  %181 = load i64*, i64** %180, align 8, !dbg !97, !tbaa !20
  %182 = getelementptr inbounds i64, i64* %181, i64 -3, !dbg !97
  %183 = load i64, i64* %182, align 8, !dbg !97, !tbaa !4
  %184 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %179, i64 0, i32 1, !dbg !97
  %185 = load i64*, i64** %184, align 8, !dbg !97, !tbaa !54
  %186 = getelementptr inbounds i64, i64* %185, i64 1, !dbg !97
  store i64 %183, i64* %185, align 8, !dbg !97, !tbaa !4
  %187 = getelementptr inbounds i64, i64* %185, i64 3, !dbg !97
  store i64* %187, i64** %184, align 8, !dbg !97, !tbaa !54
  %188 = bitcast i64* %186 to <2 x i64>*, !dbg !97
  store <2 x i64> <i64 45035996273704962, i64 54043195528445954>, <2 x i64>* %188, align 8, !dbg !97, !tbaa !4
  %send308.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_plus, i64 0) #8, !dbg !97
  %189 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !98, !tbaa !12
  %190 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %189, i64 0, i32 2, !dbg !98
  %191 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %190, align 8, !dbg !98, !tbaa !14
  %192 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %191, i64 0, i32 4, !dbg !98
  %193 = load i64*, i64** %192, align 8, !dbg !98, !tbaa !20
  %194 = getelementptr inbounds i64, i64* %193, i64 -3, !dbg !98
  %195 = load i64, i64* %194, align 8, !dbg !98, !tbaa !4
  %196 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %191, i64 0, i32 1, !dbg !98
  %197 = load i64*, i64** %196, align 8, !dbg !98, !tbaa !54
  %198 = getelementptr inbounds i64, i64* %197, i64 1, !dbg !98
  store i64 %195, i64* %197, align 8, !dbg !98, !tbaa !4
  %199 = getelementptr inbounds i64, i64* %197, i64 2, !dbg !98
  store i64* %199, i64** %196, align 8, !dbg !98, !tbaa !54
  store i64 %send308.i, i64* %198, align 8, !dbg !98, !tbaa !4
  %send312.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_p, i64 0) #8, !dbg !98
  %200 = getelementptr inbounds i64, i64* %81, i64 28, !dbg !98
  store i64* %200, i64** %76, align 8, !dbg !98, !tbaa !12
  %201 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !99, !tbaa !12
  %202 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %201, i64 0, i32 2, !dbg !99
  %203 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %202, align 8, !dbg !99, !tbaa !14
  %204 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %203, i64 0, i32 4, !dbg !99
  %205 = load i64*, i64** %204, align 8, !dbg !99, !tbaa !20
  %206 = getelementptr inbounds i64, i64* %205, i64 -3, !dbg !99
  %207 = load i64, i64* %206, align 8, !dbg !99, !tbaa !4
  %208 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %203, i64 0, i32 1, !dbg !99
  %209 = load i64*, i64** %208, align 8, !dbg !99, !tbaa !54
  %210 = getelementptr inbounds i64, i64* %209, i64 1, !dbg !99
  store i64 %207, i64* %209, align 8, !dbg !99, !tbaa !4
  %211 = getelementptr inbounds i64, i64* %209, i64 3, !dbg !99
  store i64* %211, i64** %208, align 8, !dbg !99, !tbaa !54
  %212 = bitcast i64* %210 to <2 x i64>*, !dbg !99
  store <2 x i64> <i64 146704757861593906, i64 194442913911721170>, <2 x i64>* %212, align 8, !dbg !99, !tbaa !4
  %send319.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_minus, i64 0) #8, !dbg !99
  %213 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !100, !tbaa !12
  %214 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %213, i64 0, i32 2, !dbg !100
  %215 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %214, align 8, !dbg !100, !tbaa !14
  %216 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %215, i64 0, i32 4, !dbg !100
  %217 = load i64*, i64** %216, align 8, !dbg !100, !tbaa !20
  %218 = getelementptr inbounds i64, i64* %217, i64 -3, !dbg !100
  %219 = load i64, i64* %218, align 8, !dbg !100, !tbaa !4
  %220 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %215, i64 0, i32 1, !dbg !100
  %221 = load i64*, i64** %220, align 8, !dbg !100, !tbaa !54
  %222 = getelementptr inbounds i64, i64* %221, i64 1, !dbg !100
  store i64 %219, i64* %221, align 8, !dbg !100, !tbaa !4
  %223 = getelementptr inbounds i64, i64* %221, i64 2, !dbg !100
  store i64* %223, i64** %220, align 8, !dbg !100, !tbaa !54
  store i64 %send319.i, i64* %222, align 8, !dbg !100, !tbaa !4
  %send324.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_p.18, i64 0) #8, !dbg !100
  %224 = getelementptr inbounds i64, i64* %81, i64 29, !dbg !100
  store i64* %224, i64** %76, align 8, !dbg !100, !tbaa !12
  %225 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !101, !tbaa !12
  %226 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %225, i64 0, i32 2, !dbg !101
  %227 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %226, align 8, !dbg !101, !tbaa !14
  %228 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %227, i64 0, i32 4, !dbg !101
  %229 = load i64*, i64** %228, align 8, !dbg !101, !tbaa !20
  %230 = getelementptr inbounds i64, i64* %229, i64 -3, !dbg !101
  %231 = load i64, i64* %230, align 8, !dbg !101, !tbaa !4
  %232 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %227, i64 0, i32 1, !dbg !101
  %233 = load i64*, i64** %232, align 8, !dbg !101, !tbaa !54
  %234 = getelementptr inbounds i64, i64* %233, i64 1, !dbg !101
  store i64 %231, i64* %233, align 8, !dbg !101, !tbaa !4
  %235 = getelementptr inbounds i64, i64* %233, i64 3, !dbg !101
  store i64* %235, i64** %232, align 8, !dbg !101, !tbaa !54
  %236 = bitcast i64* %234 to <2 x i64>*, !dbg !101
  store <2 x i64> <i64 193204424014194282, i64 53142475602971858>, <2 x i64>* %236, align 8, !dbg !101, !tbaa !4
  %send331.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_lt, i64 0) #8, !dbg !101
  %237 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !102, !tbaa !12
  %238 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %237, i64 0, i32 2, !dbg !102
  %239 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %238, align 8, !dbg !102, !tbaa !14
  %240 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %239, i64 0, i32 4, !dbg !102
  %241 = load i64*, i64** %240, align 8, !dbg !102, !tbaa !20
  %242 = getelementptr inbounds i64, i64* %241, i64 -3, !dbg !102
  %243 = load i64, i64* %242, align 8, !dbg !102, !tbaa !4
  %244 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %239, i64 0, i32 1, !dbg !102
  %245 = load i64*, i64** %244, align 8, !dbg !102, !tbaa !54
  %246 = getelementptr inbounds i64, i64* %245, i64 1, !dbg !102
  store i64 %243, i64* %245, align 8, !dbg !102, !tbaa !4
  %247 = getelementptr inbounds i64, i64* %245, i64 2, !dbg !102
  store i64* %247, i64** %244, align 8, !dbg !102, !tbaa !54
  store i64 %send331.i, i64* %246, align 8, !dbg !102, !tbaa !4
  %send336.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_p.19, i64 0) #8, !dbg !102
  %248 = getelementptr inbounds i64, i64* %81, i64 30, !dbg !102
  store i64* %248, i64** %76, align 8, !dbg !102, !tbaa !12
  %249 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !103, !tbaa !12
  %250 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %249, i64 0, i32 2, !dbg !103
  %251 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %250, align 8, !dbg !103, !tbaa !14
  %252 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %251, i64 0, i32 4, !dbg !103
  %253 = load i64*, i64** %252, align 8, !dbg !103, !tbaa !20
  %254 = getelementptr inbounds i64, i64* %253, i64 -3, !dbg !103
  %255 = load i64, i64* %254, align 8, !dbg !103, !tbaa !4
  %256 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %251, i64 0, i32 1, !dbg !103
  %257 = load i64*, i64** %256, align 8, !dbg !103, !tbaa !54
  %258 = getelementptr inbounds i64, i64* %257, i64 1, !dbg !103
  store i64 %255, i64* %257, align 8, !dbg !103, !tbaa !4
  %259 = getelementptr inbounds i64, i64* %257, i64 3, !dbg !103
  store i64* %259, i64** %256, align 8, !dbg !103, !tbaa !54
  %260 = bitcast i64* %258 to <2 x i64>*, !dbg !103
  store <2 x i64> <i64 61248954932238746, i64 133982088914272258>, <2 x i64>* %260, align 8, !dbg !103, !tbaa !4
  %send344.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_lt.20, i64 0) #8, !dbg !103
  %261 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !104, !tbaa !12
  %262 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %261, i64 0, i32 2, !dbg !104
  %263 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %262, align 8, !dbg !104, !tbaa !14
  %264 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %263, i64 0, i32 4, !dbg !104
  %265 = load i64*, i64** %264, align 8, !dbg !104, !tbaa !20
  %266 = getelementptr inbounds i64, i64* %265, i64 -3, !dbg !104
  %267 = load i64, i64* %266, align 8, !dbg !104, !tbaa !4
  %268 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %263, i64 0, i32 1, !dbg !104
  %269 = load i64*, i64** %268, align 8, !dbg !104, !tbaa !54
  %270 = getelementptr inbounds i64, i64* %269, i64 1, !dbg !104
  store i64 %267, i64* %269, align 8, !dbg !104, !tbaa !4
  %271 = getelementptr inbounds i64, i64* %269, i64 2, !dbg !104
  store i64* %271, i64** %268, align 8, !dbg !104, !tbaa !54
  store i64 %send344.i, i64* %270, align 8, !dbg !104, !tbaa !4
  %send349.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_p.21, i64 0) #8, !dbg !104
  %272 = getelementptr inbounds i64, i64* %81, i64 31, !dbg !104
  store i64* %272, i64** %76, align 8, !dbg !104, !tbaa !12
  %273 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !105, !tbaa !12
  %274 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %273, i64 0, i32 2, !dbg !105
  %275 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %274, align 8, !dbg !105, !tbaa !14
  %276 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %275, i64 0, i32 4, !dbg !105
  %277 = load i64*, i64** %276, align 8, !dbg !105, !tbaa !20
  %278 = getelementptr inbounds i64, i64* %277, i64 -3, !dbg !105
  %279 = load i64, i64* %278, align 8, !dbg !105, !tbaa !4
  %280 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %275, i64 0, i32 1, !dbg !105
  %281 = load i64*, i64** %280, align 8, !dbg !105, !tbaa !54
  %282 = getelementptr inbounds i64, i64* %281, i64 1, !dbg !105
  store i64 %279, i64* %281, align 8, !dbg !105, !tbaa !4
  %283 = getelementptr inbounds i64, i64* %281, i64 3, !dbg !105
  store i64* %283, i64** %280, align 8, !dbg !105, !tbaa !54
  %284 = bitcast i64* %282 to <2 x i64>*, !dbg !105
  store <2 x i64> <i64 180200280090161970, i64 155261597153597850>, <2 x i64>* %284, align 8, !dbg !105, !tbaa !4
  %send356.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_lte, i64 0) #8, !dbg !105
  %285 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !106, !tbaa !12
  %286 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %285, i64 0, i32 2, !dbg !106
  %287 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %286, align 8, !dbg !106, !tbaa !14
  %288 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %287, i64 0, i32 4, !dbg !106
  %289 = load i64*, i64** %288, align 8, !dbg !106, !tbaa !20
  %290 = getelementptr inbounds i64, i64* %289, i64 -3, !dbg !106
  %291 = load i64, i64* %290, align 8, !dbg !106, !tbaa !4
  %292 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %287, i64 0, i32 1, !dbg !106
  %293 = load i64*, i64** %292, align 8, !dbg !106, !tbaa !54
  %294 = getelementptr inbounds i64, i64* %293, i64 1, !dbg !106
  store i64 %291, i64* %293, align 8, !dbg !106, !tbaa !4
  %295 = getelementptr inbounds i64, i64* %293, i64 2, !dbg !106
  store i64* %295, i64** %292, align 8, !dbg !106, !tbaa !54
  store i64 %send356.i, i64* %294, align 8, !dbg !106, !tbaa !4
  %send361.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_p.22, i64 0) #8, !dbg !106
  %296 = getelementptr inbounds i64, i64* %81, i64 32, !dbg !106
  store i64* %296, i64** %76, align 8, !dbg !106, !tbaa !12
  %297 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !107, !tbaa !12
  %298 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %297, i64 0, i32 2, !dbg !107
  %299 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %298, align 8, !dbg !107, !tbaa !14
  %300 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %299, i64 0, i32 4, !dbg !107
  %301 = load i64*, i64** %300, align 8, !dbg !107, !tbaa !20
  %302 = getelementptr inbounds i64, i64* %301, i64 -3, !dbg !107
  %303 = load i64, i64* %302, align 8, !dbg !107, !tbaa !4
  %304 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %299, i64 0, i32 1, !dbg !107
  %305 = load i64*, i64** %304, align 8, !dbg !107, !tbaa !54
  %306 = getelementptr inbounds i64, i64* %305, i64 1, !dbg !107
  store i64 %303, i64* %305, align 8, !dbg !107, !tbaa !4
  %307 = getelementptr inbounds i64, i64* %305, i64 3, !dbg !107
  store i64* %307, i64** %304, align 8, !dbg !107, !tbaa !54
  %308 = bitcast i64* %306 to <2 x i64>*, !dbg !107
  store <2 x i64> <i64 57646075230342354, i64 155261597153597850>, <2 x i64>* %308, align 8, !dbg !107, !tbaa !4
  %send369.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_lte.23, i64 0) #8, !dbg !107
  %309 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !108, !tbaa !12
  %310 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %309, i64 0, i32 2, !dbg !108
  %311 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %310, align 8, !dbg !108, !tbaa !14
  %312 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %311, i64 0, i32 4, !dbg !108
  %313 = load i64*, i64** %312, align 8, !dbg !108, !tbaa !20
  %314 = getelementptr inbounds i64, i64* %313, i64 -3, !dbg !108
  %315 = load i64, i64* %314, align 8, !dbg !108, !tbaa !4
  %316 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %311, i64 0, i32 1, !dbg !108
  %317 = load i64*, i64** %316, align 8, !dbg !108, !tbaa !54
  %318 = getelementptr inbounds i64, i64* %317, i64 1, !dbg !108
  store i64 %315, i64* %317, align 8, !dbg !108, !tbaa !4
  %319 = getelementptr inbounds i64, i64* %317, i64 2, !dbg !108
  store i64* %319, i64** %316, align 8, !dbg !108, !tbaa !54
  store i64 %send369.i, i64* %318, align 8, !dbg !108, !tbaa !4
  %send374.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_p.24, i64 0) #8, !dbg !108
  %320 = getelementptr inbounds i64, i64* %81, i64 33, !dbg !108
  store i64* %320, i64** %76, align 8, !dbg !108, !tbaa !12
  %321 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !109, !tbaa !12
  %322 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %321, i64 0, i32 2, !dbg !109
  %323 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %322, align 8, !dbg !109, !tbaa !14
  %324 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %323, i64 0, i32 4, !dbg !109
  %325 = load i64*, i64** %324, align 8, !dbg !109, !tbaa !20
  %326 = getelementptr inbounds i64, i64* %325, i64 -3, !dbg !109
  %327 = load i64, i64* %326, align 8, !dbg !109, !tbaa !4
  %328 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %323, i64 0, i32 1, !dbg !109
  %329 = load i64*, i64** %328, align 8, !dbg !109, !tbaa !54
  %330 = getelementptr inbounds i64, i64* %329, i64 1, !dbg !109
  store i64 %327, i64* %329, align 8, !dbg !109, !tbaa !4
  %331 = getelementptr inbounds i64, i64* %329, i64 3, !dbg !109
  store i64* %331, i64** %328, align 8, !dbg !109, !tbaa !54
  %332 = bitcast i64* %330 to <2 x i64>*, !dbg !109
  store <2 x i64> <i64 75660473739824338, i64 75660473739824338>, <2 x i64>* %332, align 8, !dbg !109, !tbaa !4
  %send382.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_lte.25, i64 0) #8, !dbg !109
  %333 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !110, !tbaa !12
  %334 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %333, i64 0, i32 2, !dbg !110
  %335 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %334, align 8, !dbg !110, !tbaa !14
  %336 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %335, i64 0, i32 4, !dbg !110
  %337 = load i64*, i64** %336, align 8, !dbg !110, !tbaa !20
  %338 = getelementptr inbounds i64, i64* %337, i64 -3, !dbg !110
  %339 = load i64, i64* %338, align 8, !dbg !110, !tbaa !4
  %340 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %335, i64 0, i32 1, !dbg !110
  %341 = load i64*, i64** %340, align 8, !dbg !110, !tbaa !54
  %342 = getelementptr inbounds i64, i64* %341, i64 1, !dbg !110
  store i64 %339, i64* %341, align 8, !dbg !110, !tbaa !4
  %343 = getelementptr inbounds i64, i64* %341, i64 2, !dbg !110
  store i64* %343, i64** %340, align 8, !dbg !110, !tbaa !54
  store i64 %send382.i, i64* %342, align 8, !dbg !110, !tbaa !4
  %send387.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_p.26, i64 0) #8, !dbg !110
  %344 = getelementptr inbounds i64, i64* %81, i64 36, !dbg !110
  store i64* %344, i64** %76, align 8, !dbg !110, !tbaa !12
  %345 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !111, !tbaa !12
  %346 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %345, i64 0, i32 2, !dbg !111
  %347 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %346, align 8, !dbg !111, !tbaa !14
  %348 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %347, i64 0, i32 4, !dbg !111
  %349 = load i64*, i64** %348, align 8, !dbg !111, !tbaa !20
  %350 = getelementptr inbounds i64, i64* %349, i64 -3, !dbg !111
  %351 = load i64, i64* %350, align 8, !dbg !111, !tbaa !4
  %352 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %347, i64 0, i32 1, !dbg !111
  %353 = load i64*, i64** %352, align 8, !dbg !111, !tbaa !54
  %354 = getelementptr inbounds i64, i64* %353, i64 1, !dbg !111
  store i64 %351, i64* %353, align 8, !dbg !111, !tbaa !4
  %355 = getelementptr inbounds i64, i64* %353, i64 3, !dbg !111
  store i64* %355, i64** %352, align 8, !dbg !111, !tbaa !54
  %356 = bitcast i64* %354 to <2 x i64>*, !dbg !111
  store <2 x i64> <i64 45035996273704962, i64 17>, <2 x i64>* %356, align 8, !dbg !111, !tbaa !4
  %send394.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_plus.27, i64 0) #8, !dbg !111
  %357 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !112, !tbaa !12
  %358 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %357, i64 0, i32 2, !dbg !112
  %359 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %358, align 8, !dbg !112, !tbaa !14
  %360 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %359, i64 0, i32 4, !dbg !112
  %361 = load i64*, i64** %360, align 8, !dbg !112, !tbaa !20
  %362 = getelementptr inbounds i64, i64* %361, i64 -3, !dbg !112
  %363 = load i64, i64* %362, align 8, !dbg !112, !tbaa !4
  %364 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %359, i64 0, i32 1, !dbg !112
  %365 = load i64*, i64** %364, align 8, !dbg !112, !tbaa !54
  %366 = getelementptr inbounds i64, i64* %365, i64 1, !dbg !112
  store i64 %363, i64* %365, align 8, !dbg !112, !tbaa !4
  %367 = getelementptr inbounds i64, i64* %365, i64 2, !dbg !112
  store i64* %367, i64** %364, align 8, !dbg !112, !tbaa !54
  store i64 %send394.i, i64* %366, align 8, !dbg !112, !tbaa !4
  %send399.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_p.28, i64 0) #8, !dbg !112
  %368 = getelementptr inbounds i64, i64* %81, i64 37, !dbg !112
  store i64* %368, i64** %76, align 8, !dbg !112, !tbaa !12
  %rubyStr_8.9.i = load i64, i64* @rubyStrFrozen_8.9, align 8, !dbg !113
  %369 = load i64, i64* @rb_mKernel, align 8, !dbg !113
  %370 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !113, !tbaa !12
  %371 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %370, i64 0, i32 2, !dbg !113
  %372 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %371, align 8, !dbg !113, !tbaa !14
  %373 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %372, i64 0, i32 1, !dbg !113
  %374 = load i64*, i64** %373, align 8, !dbg !113, !tbaa !54
  %375 = getelementptr inbounds i64, i64* %374, i64 1, !dbg !113
  store i64 %369, i64* %374, align 8, !dbg !113, !tbaa !4
  %376 = getelementptr inbounds i64, i64* %374, i64 2, !dbg !113
  store i64* %376, i64** %373, align 8, !dbg !113, !tbaa !54
  store i64 %rubyStr_8.9.i, i64* %375, align 8, !dbg !113, !tbaa !4
  %send404.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_Rational, i64 0) #8, !dbg !113
  %377 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !114, !tbaa !12
  %378 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %377, i64 0, i32 2, !dbg !114
  %379 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %378, align 8, !dbg !114, !tbaa !14
  %380 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %379, i64 0, i32 4, !dbg !114
  %381 = load i64*, i64** %380, align 8, !dbg !114, !tbaa !20
  %382 = getelementptr inbounds i64, i64* %381, i64 -3, !dbg !114
  %383 = load i64, i64* %382, align 8, !dbg !114, !tbaa !4
  %384 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %379, i64 0, i32 1, !dbg !114
  %385 = load i64*, i64** %384, align 8, !dbg !114, !tbaa !54
  %386 = getelementptr inbounds i64, i64* %385, i64 1, !dbg !114
  store i64 %383, i64* %385, align 8, !dbg !114, !tbaa !4
  %387 = getelementptr inbounds i64, i64* %385, i64 2, !dbg !114
  store i64 36028797018963970, i64* %386, align 8, !dbg !114, !tbaa !4
  %388 = getelementptr inbounds i64, i64* %385, i64 3, !dbg !114
  store i64* %388, i64** %384, align 8, !dbg !114, !tbaa !54
  store i64 %send404.i, i64* %387, align 8, !dbg !114, !tbaa !4
  %send410.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_plus.29, i64 0) #8, !dbg !114
  %389 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !115, !tbaa !12
  %390 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %389, i64 0, i32 2, !dbg !115
  %391 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %390, align 8, !dbg !115, !tbaa !14
  %392 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %391, i64 0, i32 4, !dbg !115
  %393 = load i64*, i64** %392, align 8, !dbg !115, !tbaa !20
  %394 = getelementptr inbounds i64, i64* %393, i64 -3, !dbg !115
  %395 = load i64, i64* %394, align 8, !dbg !115, !tbaa !4
  %396 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %391, i64 0, i32 1, !dbg !115
  %397 = load i64*, i64** %396, align 8, !dbg !115, !tbaa !54
  %398 = getelementptr inbounds i64, i64* %397, i64 1, !dbg !115
  store i64 %395, i64* %397, align 8, !dbg !115, !tbaa !4
  %399 = getelementptr inbounds i64, i64* %397, i64 2, !dbg !115
  store i64* %399, i64** %396, align 8, !dbg !115, !tbaa !54
  store i64 %send410.i, i64* %398, align 8, !dbg !115, !tbaa !4
  %send415.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_p.30, i64 0) #8, !dbg !115
  %400 = getelementptr inbounds i64, i64* %81, i64 38, !dbg !115
  store i64* %400, i64** %76, align 8, !dbg !115, !tbaa !12
  %rubyStr_5.i = load i64, i64* @rubyStrFrozen_5, align 8, !dbg !116
  %401 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !116, !tbaa !12
  %402 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %401, i64 0, i32 2, !dbg !116
  %403 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %402, align 8, !dbg !116, !tbaa !14
  %404 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %403, i64 0, i32 1, !dbg !116
  %405 = load i64*, i64** %404, align 8, !dbg !116, !tbaa !54
  %406 = getelementptr inbounds i64, i64* %405, i64 1, !dbg !116
  store i64 %369, i64* %405, align 8, !dbg !116, !tbaa !4
  %407 = getelementptr inbounds i64, i64* %405, i64 2, !dbg !116
  store i64 1, i64* %406, align 8, !dbg !116, !tbaa !4
  %408 = getelementptr inbounds i64, i64* %405, i64 3, !dbg !116
  store i64* %408, i64** %404, align 8, !dbg !116, !tbaa !54
  store i64 %rubyStr_5.i, i64* %407, align 8, !dbg !116, !tbaa !4
  %send422.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_Complex, i64 0) #8, !dbg !116
  %409 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !117, !tbaa !12
  %410 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %409, i64 0, i32 2, !dbg !117
  %411 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %410, align 8, !dbg !117, !tbaa !14
  %412 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %411, i64 0, i32 4, !dbg !117
  %413 = load i64*, i64** %412, align 8, !dbg !117, !tbaa !20
  %414 = getelementptr inbounds i64, i64* %413, i64 -3, !dbg !117
  %415 = load i64, i64* %414, align 8, !dbg !117, !tbaa !4
  %416 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %411, i64 0, i32 1, !dbg !117
  %417 = load i64*, i64** %416, align 8, !dbg !117, !tbaa !54
  %418 = getelementptr inbounds i64, i64* %417, i64 1, !dbg !117
  store i64 %415, i64* %417, align 8, !dbg !117, !tbaa !4
  %419 = getelementptr inbounds i64, i64* %417, i64 2, !dbg !117
  store i64 36028797018963970, i64* %418, align 8, !dbg !117, !tbaa !4
  %420 = getelementptr inbounds i64, i64* %417, i64 3, !dbg !117
  store i64* %420, i64** %416, align 8, !dbg !117, !tbaa !54
  store i64 %send422.i, i64* %419, align 8, !dbg !117, !tbaa !4
  %send428.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_plus.31, i64 0) #8, !dbg !117
  %421 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !118, !tbaa !12
  %422 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %421, i64 0, i32 2, !dbg !118
  %423 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %422, align 8, !dbg !118, !tbaa !14
  %424 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %423, i64 0, i32 4, !dbg !118
  %425 = load i64*, i64** %424, align 8, !dbg !118, !tbaa !20
  %426 = getelementptr inbounds i64, i64* %425, i64 -3, !dbg !118
  %427 = load i64, i64* %426, align 8, !dbg !118, !tbaa !4
  %428 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %423, i64 0, i32 1, !dbg !118
  %429 = load i64*, i64** %428, align 8, !dbg !118, !tbaa !54
  %430 = getelementptr inbounds i64, i64* %429, i64 1, !dbg !118
  store i64 %427, i64* %429, align 8, !dbg !118, !tbaa !4
  %431 = getelementptr inbounds i64, i64* %429, i64 2, !dbg !118
  store i64* %431, i64** %428, align 8, !dbg !118, !tbaa !54
  store i64 %send428.i, i64* %430, align 8, !dbg !118, !tbaa !4
  %send433.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_p.32, i64 0) #8, !dbg !118
  %432 = getelementptr inbounds i64, i64* %81, i64 40, !dbg !118
  store i64* %432, i64** %76, align 8, !dbg !118, !tbaa !12
  %433 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !119, !tbaa !12
  %434 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %433, i64 0, i32 2, !dbg !119
  %435 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %434, align 8, !dbg !119, !tbaa !14
  %436 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %435, i64 0, i32 4, !dbg !119
  %437 = load i64*, i64** %436, align 8, !dbg !119, !tbaa !20
  %438 = getelementptr inbounds i64, i64* %437, i64 -3, !dbg !119
  %439 = load i64, i64* %438, align 8, !dbg !119, !tbaa !4
  %440 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %435, i64 0, i32 1, !dbg !119
  %441 = load i64*, i64** %440, align 8, !dbg !119, !tbaa !54
  %442 = getelementptr inbounds i64, i64* %441, i64 1, !dbg !119
  store i64 %439, i64* %441, align 8, !dbg !119, !tbaa !4
  %443 = getelementptr inbounds i64, i64* %441, i64 3, !dbg !119
  store i64* %443, i64** %440, align 8, !dbg !119, !tbaa !54
  %444 = bitcast i64* %442 to <2 x i64>*, !dbg !119
  store <2 x i64> <i64 199678348478539370, i64 7>, <2 x i64>* %444, align 8, !dbg !119, !tbaa !4
  %send441.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_minus.33, i64 0) #8, !dbg !119
  %445 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !120, !tbaa !12
  %446 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %445, i64 0, i32 2, !dbg !120
  %447 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %446, align 8, !dbg !120, !tbaa !14
  %448 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %447, i64 0, i32 4, !dbg !120
  %449 = load i64*, i64** %448, align 8, !dbg !120, !tbaa !20
  %450 = getelementptr inbounds i64, i64* %449, i64 -3, !dbg !120
  %451 = load i64, i64* %450, align 8, !dbg !120, !tbaa !4
  %452 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %447, i64 0, i32 1, !dbg !120
  %453 = load i64*, i64** %452, align 8, !dbg !120, !tbaa !54
  %454 = getelementptr inbounds i64, i64* %453, i64 1, !dbg !120
  store i64 %451, i64* %453, align 8, !dbg !120, !tbaa !4
  %455 = getelementptr inbounds i64, i64* %453, i64 2, !dbg !120
  store i64* %455, i64** %452, align 8, !dbg !120, !tbaa !54
  store i64 %send441.i, i64* %454, align 8, !dbg !120, !tbaa !4
  %send446.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_p.34, i64 0) #8, !dbg !120
  %456 = getelementptr inbounds i64, i64* %81, i64 41, !dbg !120
  store i64* %456, i64** %76, align 8, !dbg !120, !tbaa !12
  %rubyStr_15.4.i = load i64, i64* @rubyStrFrozen_15.4, align 8, !dbg !121
  %457 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !121, !tbaa !12
  %458 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %457, i64 0, i32 2, !dbg !121
  %459 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %458, align 8, !dbg !121, !tbaa !14
  %460 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %459, i64 0, i32 1, !dbg !121
  %461 = load i64*, i64** %460, align 8, !dbg !121, !tbaa !54
  %462 = getelementptr inbounds i64, i64* %461, i64 1, !dbg !121
  store i64 %369, i64* %461, align 8, !dbg !121, !tbaa !4
  %463 = getelementptr inbounds i64, i64* %461, i64 2, !dbg !121
  store i64* %463, i64** %460, align 8, !dbg !121, !tbaa !54
  store i64 %rubyStr_15.4.i, i64* %462, align 8, !dbg !121, !tbaa !4
  %send452.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_Rational.35, i64 0) #8, !dbg !121
  %464 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !122, !tbaa !12
  %465 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %464, i64 0, i32 2, !dbg !122
  %466 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %465, align 8, !dbg !122, !tbaa !14
  %467 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %466, i64 0, i32 4, !dbg !122
  %468 = load i64*, i64** %467, align 8, !dbg !122, !tbaa !20
  %469 = getelementptr inbounds i64, i64* %468, i64 -3, !dbg !122
  %470 = load i64, i64* %469, align 8, !dbg !122, !tbaa !4
  %471 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %466, i64 0, i32 1, !dbg !122
  %472 = load i64*, i64** %471, align 8, !dbg !122, !tbaa !54
  %473 = getelementptr inbounds i64, i64* %472, i64 1, !dbg !122
  store i64 %470, i64* %472, align 8, !dbg !122, !tbaa !4
  %474 = getelementptr inbounds i64, i64* %472, i64 2, !dbg !122
  store i64 199622053483197234, i64* %473, align 8, !dbg !122, !tbaa !4
  %475 = getelementptr inbounds i64, i64* %472, i64 3, !dbg !122
  store i64* %475, i64** %471, align 8, !dbg !122, !tbaa !54
  store i64 %send452.i, i64* %474, align 8, !dbg !122, !tbaa !4
  %send458.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_minus.36, i64 0) #8, !dbg !122
  %476 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !123, !tbaa !12
  %477 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %476, i64 0, i32 2, !dbg !123
  %478 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %477, align 8, !dbg !123, !tbaa !14
  %479 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %478, i64 0, i32 4, !dbg !123
  %480 = load i64*, i64** %479, align 8, !dbg !123, !tbaa !20
  %481 = getelementptr inbounds i64, i64* %480, i64 -3, !dbg !123
  %482 = load i64, i64* %481, align 8, !dbg !123, !tbaa !4
  %483 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %478, i64 0, i32 1, !dbg !123
  %484 = load i64*, i64** %483, align 8, !dbg !123, !tbaa !54
  %485 = getelementptr inbounds i64, i64* %484, i64 1, !dbg !123
  store i64 %482, i64* %484, align 8, !dbg !123, !tbaa !4
  %486 = getelementptr inbounds i64, i64* %484, i64 2, !dbg !123
  store i64* %486, i64** %483, align 8, !dbg !123, !tbaa !54
  store i64 %send458.i, i64* %485, align 8, !dbg !123, !tbaa !4
  %send463.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_p.37, i64 0) #8, !dbg !123
  %487 = getelementptr inbounds i64, i64* %81, i64 42, !dbg !123
  store i64* %487, i64** %76, align 8, !dbg !123, !tbaa !12
  %rubyStr_18.i = load i64, i64* @rubyStrFrozen_18, align 8, !dbg !124
  %488 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !124, !tbaa !12
  %489 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %488, i64 0, i32 2, !dbg !124
  %490 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %489, align 8, !dbg !124, !tbaa !14
  %491 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %490, i64 0, i32 1, !dbg !124
  %492 = load i64*, i64** %491, align 8, !dbg !124, !tbaa !54
  %493 = getelementptr inbounds i64, i64* %492, i64 1, !dbg !124
  store i64 %369, i64* %492, align 8, !dbg !124, !tbaa !4
  %494 = getelementptr inbounds i64, i64* %492, i64 2, !dbg !124
  store i64 1, i64* %493, align 8, !dbg !124, !tbaa !4
  %495 = getelementptr inbounds i64, i64* %492, i64 3, !dbg !124
  store i64* %495, i64** %491, align 8, !dbg !124, !tbaa !54
  store i64 %rubyStr_18.i, i64* %494, align 8, !dbg !124, !tbaa !4
  %send471.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_Complex.38, i64 0) #8, !dbg !124
  %496 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !125, !tbaa !12
  %497 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %496, i64 0, i32 2, !dbg !125
  %498 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %497, align 8, !dbg !125, !tbaa !14
  %499 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %498, i64 0, i32 4, !dbg !125
  %500 = load i64*, i64** %499, align 8, !dbg !125, !tbaa !20
  %501 = getelementptr inbounds i64, i64* %500, i64 -3, !dbg !125
  %502 = load i64, i64* %501, align 8, !dbg !125, !tbaa !4
  %503 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %498, i64 0, i32 1, !dbg !125
  %504 = load i64*, i64** %503, align 8, !dbg !125, !tbaa !54
  %505 = getelementptr inbounds i64, i64* %504, i64 1, !dbg !125
  store i64 %502, i64* %504, align 8, !dbg !125, !tbaa !4
  %506 = getelementptr inbounds i64, i64* %504, i64 2, !dbg !125
  store i64 199565758487855106, i64* %505, align 8, !dbg !125, !tbaa !4
  %507 = getelementptr inbounds i64, i64* %504, i64 3, !dbg !125
  store i64* %507, i64** %503, align 8, !dbg !125, !tbaa !54
  store i64 %send471.i, i64* %506, align 8, !dbg !125, !tbaa !4
  %send477.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_minus.39, i64 0) #8, !dbg !125
  %508 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !126, !tbaa !12
  %509 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %508, i64 0, i32 2, !dbg !126
  %510 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %509, align 8, !dbg !126, !tbaa !14
  %511 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %510, i64 0, i32 4, !dbg !126
  %512 = load i64*, i64** %511, align 8, !dbg !126, !tbaa !20
  %513 = getelementptr inbounds i64, i64* %512, i64 -3, !dbg !126
  %514 = load i64, i64* %513, align 8, !dbg !126, !tbaa !4
  %515 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %510, i64 0, i32 1, !dbg !126
  %516 = load i64*, i64** %515, align 8, !dbg !126, !tbaa !54
  %517 = getelementptr inbounds i64, i64* %516, i64 1, !dbg !126
  store i64 %514, i64* %516, align 8, !dbg !126, !tbaa !4
  %518 = getelementptr inbounds i64, i64* %516, i64 2, !dbg !126
  store i64* %518, i64** %515, align 8, !dbg !126, !tbaa !54
  store i64 %send477.i, i64* %517, align 8, !dbg !126, !tbaa !4
  %send482.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_p.40, i64 0) #8, !dbg !126
  %519 = getelementptr inbounds i64, i64* %81, i64 44, !dbg !126
  store i64* %519, i64** %76, align 8, !dbg !126, !tbaa !12
  %520 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !127, !tbaa !12
  %521 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %520, i64 0, i32 2, !dbg !127
  %522 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %521, align 8, !dbg !127, !tbaa !14
  %523 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %522, i64 0, i32 4, !dbg !127
  %524 = load i64*, i64** %523, align 8, !dbg !127, !tbaa !20
  %525 = getelementptr inbounds i64, i64* %524, i64 -3, !dbg !127
  %526 = load i64, i64* %525, align 8, !dbg !127, !tbaa !4
  %527 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %522, i64 0, i32 1, !dbg !127
  %528 = load i64*, i64** %527, align 8, !dbg !127, !tbaa !54
  %529 = getelementptr inbounds i64, i64* %528, i64 1, !dbg !127
  store i64 %526, i64* %528, align 8, !dbg !127, !tbaa !4
  %530 = getelementptr inbounds i64, i64* %528, i64 3, !dbg !127
  store i64* %530, i64** %527, align 8, !dbg !127, !tbaa !54
  %531 = bitcast i64* %529 to <2 x i64>*, !dbg !127
  store <2 x i64> <i64 113040350646999450, i64 13>, <2 x i64>* %531, align 8, !dbg !127, !tbaa !4
  %send490.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_lt.41, i64 0) #8, !dbg !127
  %532 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !128, !tbaa !12
  %533 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %532, i64 0, i32 2, !dbg !128
  %534 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %533, align 8, !dbg !128, !tbaa !14
  %535 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %534, i64 0, i32 4, !dbg !128
  %536 = load i64*, i64** %535, align 8, !dbg !128, !tbaa !20
  %537 = getelementptr inbounds i64, i64* %536, i64 -3, !dbg !128
  %538 = load i64, i64* %537, align 8, !dbg !128, !tbaa !4
  %539 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %534, i64 0, i32 1, !dbg !128
  %540 = load i64*, i64** %539, align 8, !dbg !128, !tbaa !54
  %541 = getelementptr inbounds i64, i64* %540, i64 1, !dbg !128
  store i64 %538, i64* %540, align 8, !dbg !128, !tbaa !4
  %542 = getelementptr inbounds i64, i64* %540, i64 2, !dbg !128
  store i64* %542, i64** %539, align 8, !dbg !128, !tbaa !54
  store i64 %send490.i, i64* %541, align 8, !dbg !128, !tbaa !4
  %send495.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_p.42, i64 0) #8, !dbg !128
  %543 = getelementptr inbounds i64, i64* %81, i64 45, !dbg !128
  store i64* %543, i64** %76, align 8, !dbg !128, !tbaa !12
  %rubyStr_25.4.i = load i64, i64* @rubyStrFrozen_25.4, align 8, !dbg !129
  %544 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !129, !tbaa !12
  %545 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %544, i64 0, i32 2, !dbg !129
  %546 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %545, align 8, !dbg !129, !tbaa !14
  %547 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %546, i64 0, i32 1, !dbg !129
  %548 = load i64*, i64** %547, align 8, !dbg !129, !tbaa !54
  %549 = getelementptr inbounds i64, i64* %548, i64 1, !dbg !129
  store i64 %369, i64* %548, align 8, !dbg !129, !tbaa !4
  %550 = getelementptr inbounds i64, i64* %548, i64 2, !dbg !129
  store i64* %550, i64** %547, align 8, !dbg !129, !tbaa !54
  store i64 %rubyStr_25.4.i, i64* %549, align 8, !dbg !129, !tbaa !4
  %send501.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_Rational.43, i64 0) #8, !dbg !129
  %551 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !130, !tbaa !12
  %552 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %551, i64 0, i32 2, !dbg !130
  %553 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %552, align 8, !dbg !130, !tbaa !14
  %554 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %553, i64 0, i32 4, !dbg !130
  %555 = load i64*, i64** %554, align 8, !dbg !130, !tbaa !20
  %556 = getelementptr inbounds i64, i64* %555, i64 -3, !dbg !130
  %557 = load i64, i64* %556, align 8, !dbg !130, !tbaa !4
  %558 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %553, i64 0, i32 1, !dbg !130
  %559 = load i64*, i64** %558, align 8, !dbg !130, !tbaa !54
  %560 = getelementptr inbounds i64, i64* %559, i64 1, !dbg !130
  store i64 %557, i64* %559, align 8, !dbg !130, !tbaa !4
  %561 = getelementptr inbounds i64, i64* %559, i64 2, !dbg !130
  store i64 113040350646999450, i64* %560, align 8, !dbg !130, !tbaa !4
  %562 = getelementptr inbounds i64, i64* %559, i64 3, !dbg !130
  store i64* %562, i64** %558, align 8, !dbg !130, !tbaa !54
  store i64 %send501.i, i64* %561, align 8, !dbg !130, !tbaa !4
  %send507.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_lt.44, i64 0) #8, !dbg !130
  %563 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !131, !tbaa !12
  %564 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %563, i64 0, i32 2, !dbg !131
  %565 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %564, align 8, !dbg !131, !tbaa !14
  %566 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %565, i64 0, i32 4, !dbg !131
  %567 = load i64*, i64** %566, align 8, !dbg !131, !tbaa !20
  %568 = getelementptr inbounds i64, i64* %567, i64 -3, !dbg !131
  %569 = load i64, i64* %568, align 8, !dbg !131, !tbaa !4
  %570 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %565, i64 0, i32 1, !dbg !131
  %571 = load i64*, i64** %570, align 8, !dbg !131, !tbaa !54
  %572 = getelementptr inbounds i64, i64* %571, i64 1, !dbg !131
  store i64 %569, i64* %571, align 8, !dbg !131, !tbaa !4
  %573 = getelementptr inbounds i64, i64* %571, i64 2, !dbg !131
  store i64* %573, i64** %570, align 8, !dbg !131, !tbaa !54
  store i64 %send507.i, i64* %572, align 8, !dbg !131, !tbaa !4
  %send512.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_p.45, i64 0) #8, !dbg !131
  %574 = getelementptr inbounds i64, i64* %81, i64 47, !dbg !131
  store i64* %574, i64** %76, align 8, !dbg !131, !tbaa !12
  %575 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !132, !tbaa !12
  %576 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %575, i64 0, i32 2, !dbg !132
  %577 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %576, align 8, !dbg !132, !tbaa !14
  %578 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %577, i64 0, i32 4, !dbg !132
  %579 = load i64*, i64** %578, align 8, !dbg !132, !tbaa !20
  %580 = getelementptr inbounds i64, i64* %579, i64 -3, !dbg !132
  %581 = load i64, i64* %580, align 8, !dbg !132, !tbaa !4
  %582 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %577, i64 0, i32 1, !dbg !132
  %583 = load i64*, i64** %582, align 8, !dbg !132, !tbaa !54
  %584 = getelementptr inbounds i64, i64* %583, i64 1, !dbg !132
  store i64 %581, i64* %583, align 8, !dbg !132, !tbaa !4
  %585 = getelementptr inbounds i64, i64* %583, i64 3, !dbg !132
  store i64* %585, i64** %582, align 8, !dbg !132, !tbaa !54
  %586 = bitcast i64* %584 to <2 x i64>*, !dbg !132
  store <2 x i64> <i64 113040350646999450, i64 41>, <2 x i64>* %586, align 8, !dbg !132, !tbaa !4
  %send520.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_lte.46, i64 0) #8, !dbg !132
  %587 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !133, !tbaa !12
  %588 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %587, i64 0, i32 2, !dbg !133
  %589 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %588, align 8, !dbg !133, !tbaa !14
  %590 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %589, i64 0, i32 4, !dbg !133
  %591 = load i64*, i64** %590, align 8, !dbg !133, !tbaa !20
  %592 = getelementptr inbounds i64, i64* %591, i64 -3, !dbg !133
  %593 = load i64, i64* %592, align 8, !dbg !133, !tbaa !4
  %594 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %589, i64 0, i32 1, !dbg !133
  %595 = load i64*, i64** %594, align 8, !dbg !133, !tbaa !54
  %596 = getelementptr inbounds i64, i64* %595, i64 1, !dbg !133
  store i64 %593, i64* %595, align 8, !dbg !133, !tbaa !4
  %597 = getelementptr inbounds i64, i64* %595, i64 2, !dbg !133
  store i64* %597, i64** %594, align 8, !dbg !133, !tbaa !54
  store i64 %send520.i, i64* %596, align 8, !dbg !133, !tbaa !4
  %send525.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_p.47, i64 0) #8, !dbg !133
  %598 = getelementptr inbounds i64, i64* %81, i64 48, !dbg !133
  store i64* %598, i64** %76, align 8, !dbg !133, !tbaa !12
  %rubyStr_5.923.i = load i64, i64* @rubyStrFrozen_5.923, align 8, !dbg !134
  %599 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !134, !tbaa !12
  %600 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %599, i64 0, i32 2, !dbg !134
  %601 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %600, align 8, !dbg !134, !tbaa !14
  %602 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %601, i64 0, i32 1, !dbg !134
  %603 = load i64*, i64** %602, align 8, !dbg !134, !tbaa !54
  %604 = getelementptr inbounds i64, i64* %603, i64 1, !dbg !134
  store i64 %369, i64* %603, align 8, !dbg !134, !tbaa !4
  %605 = getelementptr inbounds i64, i64* %603, i64 2, !dbg !134
  store i64* %605, i64** %602, align 8, !dbg !134, !tbaa !54
  store i64 %rubyStr_5.923.i, i64* %604, align 8, !dbg !134, !tbaa !4
  %send531.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_Rational.48, i64 0) #8, !dbg !134
  %606 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !135, !tbaa !12
  %607 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %606, i64 0, i32 2, !dbg !135
  %608 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %607, align 8, !dbg !135, !tbaa !14
  %609 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %608, i64 0, i32 4, !dbg !135
  %610 = load i64*, i64** %609, align 8, !dbg !135, !tbaa !20
  %611 = getelementptr inbounds i64, i64* %610, i64 -3, !dbg !135
  %612 = load i64, i64* %611, align 8, !dbg !135, !tbaa !4
  %613 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %608, i64 0, i32 1, !dbg !135
  %614 = load i64*, i64** %613, align 8, !dbg !135, !tbaa !54
  %615 = getelementptr inbounds i64, i64* %614, i64 1, !dbg !135
  store i64 %612, i64* %614, align 8, !dbg !135, !tbaa !4
  %616 = getelementptr inbounds i64, i64* %614, i64 2, !dbg !135
  store i64 113040350646999450, i64* %615, align 8, !dbg !135, !tbaa !4
  %617 = getelementptr inbounds i64, i64* %614, i64 3, !dbg !135
  store i64* %617, i64** %613, align 8, !dbg !135, !tbaa !54
  store i64 %send531.i, i64* %616, align 8, !dbg !135, !tbaa !4
  %send537.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_lte.49, i64 0) #8, !dbg !135
  %618 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !136, !tbaa !12
  %619 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %618, i64 0, i32 2, !dbg !136
  %620 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %619, align 8, !dbg !136, !tbaa !14
  %621 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %620, i64 0, i32 4, !dbg !136
  %622 = load i64*, i64** %621, align 8, !dbg !136, !tbaa !20
  %623 = getelementptr inbounds i64, i64* %622, i64 -3, !dbg !136
  %624 = load i64, i64* %623, align 8, !dbg !136, !tbaa !4
  %625 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %620, i64 0, i32 1, !dbg !136
  %626 = load i64*, i64** %625, align 8, !dbg !136, !tbaa !54
  %627 = getelementptr inbounds i64, i64* %626, i64 1, !dbg !136
  store i64 %624, i64* %626, align 8, !dbg !136, !tbaa !4
  %628 = getelementptr inbounds i64, i64* %626, i64 2, !dbg !136
  store i64* %628, i64** %625, align 8, !dbg !136, !tbaa !54
  store i64 %send537.i, i64* %627, align 8, !dbg !136, !tbaa !4
  %send542.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* nonnull @ic_p.50, i64 0) #8, !dbg !136
  ret void
}

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #6

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.end.p0i8(i64 immarg, i8* nocapture) #6

; Function Attrs: cold minsize noreturn nounwind sspreq uwtable
define internal fastcc void @"func_Object#lt.cold.1"(i64) unnamed_addr #7 {
newFuncRoot:
  tail call void @sorbet_cast_failure(i64 %0, i8* getelementptr inbounds ([13 x i8], [13 x i8]* @"str_Return value", i64 0, i64 0), i8* getelementptr inbounds ([11 x i8], [11 x i8]* @"str_T::Boolean", i64 0, i64 0)) #8
  unreachable
}

; Function Attrs: cold minsize noreturn nounwind sspreq uwtable
define internal fastcc void @"func_Object#lt.cold.2"(i64 %rawArg_x) unnamed_addr #7 {
newFuncRoot:
  tail call void @sorbet_cast_failure(i64 %rawArg_x, i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_sig, i64 0, i64 0), i8* getelementptr inbounds ([6 x i8], [6 x i8]* @str_Float, i64 0, i64 0)) #8, !dbg !56
  unreachable, !dbg !56
}

; Function Attrs: nounwind
declare void @llvm.assume(i1) #8

; Function Attrs: ssp
define linkonce void @"const_recompute_T::Sig"() local_unnamed_addr #9 {
  %1 = tail call i64 @sorbet_getConstant(i8* getelementptr inbounds ([7 x i8], [7 x i8]* @"str_T::Sig", i64 0, i64 0), i64 6)
  store i64 %1, i64* @"guarded_const_T::Sig", align 8
  %2 = load i64, i64* @ruby_vm_global_constant_state, align 8, !tbaa !147
  store i64 %2, i64* @"guard_epoch_T::Sig", align 8
  ret void
}

attributes #0 = { "addedToSilenceEmptyAttrsError" }
attributes #1 = { cold noreturn }
attributes #2 = { noreturn }
attributes #3 = { nounwind ssp uwtable }
attributes #4 = { nounwind sspreq uwtable }
attributes #5 = { sspreq }
attributes #6 = { argmemonly nounwind }
attributes #7 = { cold minsize noreturn nounwind sspreq uwtable }
attributes #8 = { nounwind }
attributes #9 = { ssp }
attributes #10 = { noreturn nounwind }
attributes #11 = { noinline }

!llvm.module.flags = !{!0}
!llvm.dbg.cu = !{!1}

!0 = !{i32 2, !"Debug Info Version", i32 3}
!1 = distinct !DICompileUnit(language: DW_LANG_C, file: !2, producer: "Sorbet LLVM", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, enums: !3)
!2 = !DIFile(filename: "test/testdata/compiler/float-intrinsics.rb", directory: ".")
!3 = !{}
!4 = !{!5, !5, i64 0}
!5 = !{!"long", !6, i64 0}
!6 = !{!"omnipotent char", !7, i64 0}
!7 = !{!"Simple C/C++ TBAA"}
!8 = distinct !DISubprogram(name: "Object#plus", linkageName: "func_Object#plus", scope: null, file: !2, line: 8, type: !9, scopeLine: 8, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!9 = !DISubroutineType(types: !10)
!10 = !{!11}
!11 = !DIBasicType(name: "VALUE", size: 64, encoding: DW_ATE_signed)
!12 = !{!13, !13, i64 0}
!13 = !{!"any pointer", !6, i64 0}
!14 = !{!15, !13, i64 16}
!15 = !{!"rb_execution_context_struct", !13, i64 0, !5, i64 8, !13, i64 16, !13, i64 24, !13, i64 32, !16, i64 40, !16, i64 44, !13, i64 48, !13, i64 56, !13, i64 64, !5, i64 72, !5, i64 80, !13, i64 88, !5, i64 96, !13, i64 104, !13, i64 112, !5, i64 120, !5, i64 128, !6, i64 136, !6, i64 137, !5, i64 144, !17, i64 152}
!16 = !{!"int", !6, i64 0}
!17 = !{!"", !13, i64 0, !13, i64 8, !5, i64 16, !6, i64 24}
!18 = !{!19, !13, i64 16}
!19 = !{!"rb_control_frame_struct", !13, i64 0, !13, i64 8, !13, i64 16, !5, i64 24, !13, i64 32, !13, i64 40, !13, i64 48}
!20 = !{!19, !13, i64 32}
!21 = !{!22, !13, i64 16}
!22 = !{!"rb_iseq_struct", !5, i64 0, !5, i64 8, !13, i64 16, !6, i64 24}
!23 = !{!24, !13, i64 8}
!24 = !{!"rb_iseq_constant_body", !6, i64 0, !16, i64 4, !13, i64 8, !25, i64 16, !27, i64 64, !30, i64 120, !13, i64 152, !13, i64 160, !13, i64 168, !13, i64 176, !13, i64 184, !13, i64 192, !31, i64 200, !16, i64 232, !16, i64 236, !16, i64 240, !16, i64 244, !16, i64 248, !6, i64 252, !5, i64 256}
!25 = !{!"", !26, i64 0, !16, i64 4, !16, i64 8, !16, i64 12, !16, i64 16, !16, i64 20, !16, i64 24, !16, i64 28, !13, i64 32, !13, i64 40}
!26 = !{!"", !16, i64 0, !16, i64 0, !16, i64 0, !16, i64 0, !16, i64 0, !16, i64 0, !16, i64 0, !16, i64 0, !16, i64 1, !16, i64 1}
!27 = !{!"rb_iseq_location_struct", !5, i64 0, !5, i64 8, !5, i64 16, !5, i64 24, !16, i64 32, !28, i64 36}
!28 = !{!"rb_code_location_struct", !29, i64 0, !29, i64 8}
!29 = !{!"rb_code_position_struct", !16, i64 0, !16, i64 4}
!30 = !{!"iseq_insn_info", !13, i64 0, !13, i64 8, !16, i64 16, !13, i64 24}
!31 = !{!"", !5, i64 0, !5, i64 8, !5, i64 16, !13, i64 24}
!32 = !DILocation(line: 8, column: 1, scope: !8)
!33 = !{!"branch_weights", i32 4000000, i32 4001}
!34 = !DILocation(line: 8, column: 10, scope: !8)
!35 = !{!"branch_weights", i32 1073205, i32 2146410443}
!36 = !{!37, !5, i64 0}
!37 = !{!"RBasic", !5, i64 0, !5, i64 8}
!38 = !{!"branch_weights", i32 2000, i32 1}
!39 = !DILocation(line: 18, column: 8, scope: !40, inlinedAt: !41)
!40 = distinct !DISubprogram(name: "Object#lt", linkageName: "func_Object#lt", scope: null, file: !2, line: 18, type: !9, scopeLine: 18, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!41 = distinct !DILocation(line: 8, column: 10, scope: !8)
!42 = !DILocation(line: 8, column: 13, scope: !8)
!43 = !DILocation(line: 9, column: 3, scope: !8)
!44 = !{!45}
!45 = distinct !{!45, !46, !"sorbet_int_rb_float_plus: argument 0"}
!46 = distinct !{!46, !"sorbet_int_rb_float_plus"}
!47 = distinct !DISubprogram(name: "Object#minus", linkageName: "func_Object#minus", scope: null, file: !2, line: 13, type: !9, scopeLine: 13, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!48 = !DILocation(line: 13, column: 1, scope: !47)
!49 = !DILocation(line: 13, column: 11, scope: !47)
!50 = !DILocation(line: 18, column: 8, scope: !40, inlinedAt: !51)
!51 = distinct !DILocation(line: 13, column: 11, scope: !47)
!52 = !DILocation(line: 13, column: 14, scope: !47)
!53 = !DILocation(line: 14, column: 3, scope: !47)
!54 = !{!19, !13, i64 8}
!55 = !DILocation(line: 18, column: 1, scope: !40)
!56 = !DILocation(line: 18, column: 8, scope: !40)
!57 = !DILocation(line: 18, column: 11, scope: !40)
!58 = !DILocation(line: 19, column: 3, scope: !40)
!59 = !{!60}
!60 = distinct !{!60, !61, !"sorbet_int_flo_lt: argument 0"}
!61 = distinct !{!61, !"sorbet_int_flo_lt"}
!62 = !{!"branch_weights", i32 1, i32 2001, i32 2000}
!63 = distinct !DISubprogram(name: "Object#lte", linkageName: "func_Object#lte", scope: null, file: !2, line: 23, type: !9, scopeLine: 23, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!64 = !DILocation(line: 23, column: 1, scope: !63)
!65 = !DILocation(line: 23, column: 9, scope: !63)
!66 = !DILocation(line: 18, column: 8, scope: !40, inlinedAt: !67)
!67 = distinct !DILocation(line: 23, column: 9, scope: !63)
!68 = !DILocation(line: 23, column: 12, scope: !63)
!69 = !DILocation(line: 24, column: 3, scope: !63)
!70 = !{!71}
!71 = distinct !{!71, !72, !"sorbet_int_flo_le: argument 0"}
!72 = distinct !{!72, !"sorbet_int_flo_le"}
!73 = !DILocation(line: 7, column: 6, scope: !74)
!74 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.<static-init>$152$block_1", scope: !75, file: !2, line: 5, type: !9, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!75 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.<static-init>$152", scope: null, file: !2, line: 5, type: !9, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!76 = !DILocation(line: 12, column: 6, scope: !77)
!77 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.<static-init>$152$block_2", scope: !75, file: !2, line: 5, type: !9, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!78 = !DILocation(line: 17, column: 6, scope: !79)
!79 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.<static-init>$152$block_3", scope: !75, file: !2, line: 5, type: !9, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!80 = !DILocation(line: 22, column: 6, scope: !81)
!81 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.<static-init>$152$block_4", scope: !75, file: !2, line: 5, type: !9, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!82 = !DILocation(line: 7, column: 1, scope: !75)
!83 = !DILocation(line: 7, column: 26, scope: !74)
!84 = !DILocation(line: 7, column: 45, scope: !74)
!85 = !DILocation(line: 12, column: 1, scope: !75)
!86 = !DILocation(line: 12, column: 26, scope: !77)
!87 = !DILocation(line: 12, column: 45, scope: !77)
!88 = !DILocation(line: 17, column: 1, scope: !75)
!89 = !DILocation(line: 17, column: 26, scope: !79)
!90 = !DILocation(line: 22, column: 1, scope: !75)
!91 = !DILocation(line: 22, column: 26, scope: !81)
!92 = !DILocation(line: 5, column: 1, scope: !75)
!93 = !DILocation(line: 8, column: 1, scope: !75)
!94 = !DILocation(line: 13, column: 1, scope: !75)
!95 = !DILocation(line: 18, column: 1, scope: !75)
!96 = !DILocation(line: 23, column: 1, scope: !75)
!97 = !DILocation(line: 27, column: 3, scope: !75)
!98 = !DILocation(line: 27, column: 1, scope: !75)
!99 = !DILocation(line: 28, column: 3, scope: !75)
!100 = !DILocation(line: 28, column: 1, scope: !75)
!101 = !DILocation(line: 29, column: 3, scope: !75)
!102 = !DILocation(line: 29, column: 1, scope: !75)
!103 = !DILocation(line: 30, column: 3, scope: !75)
!104 = !DILocation(line: 30, column: 1, scope: !75)
!105 = !DILocation(line: 31, column: 3, scope: !75)
!106 = !DILocation(line: 31, column: 1, scope: !75)
!107 = !DILocation(line: 32, column: 3, scope: !75)
!108 = !DILocation(line: 32, column: 1, scope: !75)
!109 = !DILocation(line: 33, column: 3, scope: !75)
!110 = !DILocation(line: 33, column: 1, scope: !75)
!111 = !DILocation(line: 36, column: 3, scope: !75)
!112 = !DILocation(line: 36, column: 1, scope: !75)
!113 = !DILocation(line: 37, column: 13, scope: !75)
!114 = !DILocation(line: 37, column: 3, scope: !75)
!115 = !DILocation(line: 37, column: 1, scope: !75)
!116 = !DILocation(line: 38, column: 13, scope: !75)
!117 = !DILocation(line: 38, column: 3, scope: !75)
!118 = !DILocation(line: 38, column: 1, scope: !75)
!119 = !DILocation(line: 40, column: 3, scope: !75)
!120 = !DILocation(line: 40, column: 1, scope: !75)
!121 = !DILocation(line: 41, column: 15, scope: !75)
!122 = !DILocation(line: 41, column: 3, scope: !75)
!123 = !DILocation(line: 41, column: 1, scope: !75)
!124 = !DILocation(line: 42, column: 15, scope: !75)
!125 = !DILocation(line: 42, column: 3, scope: !75)
!126 = !DILocation(line: 42, column: 1, scope: !75)
!127 = !DILocation(line: 44, column: 3, scope: !75)
!128 = !DILocation(line: 44, column: 1, scope: !75)
!129 = !DILocation(line: 45, column: 12, scope: !75)
!130 = !DILocation(line: 45, column: 3, scope: !75)
!131 = !DILocation(line: 45, column: 1, scope: !75)
!132 = !DILocation(line: 47, column: 3, scope: !75)
!133 = !DILocation(line: 47, column: 1, scope: !75)
!134 = !DILocation(line: 48, column: 13, scope: !75)
!135 = !DILocation(line: 48, column: 3, scope: !75)
!136 = !DILocation(line: 48, column: 1, scope: !75)
!137 = !{!138, !5, i64 400}
!138 = !{!"rb_vm_struct", !5, i64 0, !139, i64 8, !13, i64 192, !13, i64 200, !13, i64 208, !142, i64 216, !6, i64 224, !140, i64 264, !140, i64 280, !140, i64 296, !140, i64 312, !5, i64 328, !16, i64 336, !16, i64 340, !16, i64 344, !16, i64 344, !16, i64 344, !16, i64 344, !16, i64 348, !5, i64 352, !6, i64 360, !5, i64 400, !5, i64 408, !5, i64 416, !5, i64 424, !5, i64 432, !5, i64 440, !5, i64 448, !13, i64 456, !13, i64 464, !143, i64 472, !144, i64 992, !13, i64 1016, !13, i64 1024, !16, i64 1032, !16, i64 1036, !140, i64 1040, !6, i64 1056, !5, i64 1096, !5, i64 1104, !5, i64 1112, !5, i64 1120, !5, i64 1128, !16, i64 1136, !13, i64 1144, !13, i64 1152, !13, i64 1160, !13, i64 1168, !13, i64 1176, !13, i64 1184, !16, i64 1192, !145, i64 1200, !6, i64 1232}
!139 = !{!"rb_global_vm_lock_struct", !13, i64 0, !6, i64 8, !140, i64 48, !13, i64 64, !16, i64 72, !6, i64 80, !6, i64 128, !16, i64 176, !16, i64 180}
!140 = !{!"list_head", !141, i64 0}
!141 = !{!"list_node", !13, i64 0, !13, i64 8}
!142 = !{!"long long", !6, i64 0}
!143 = !{!"", !6, i64 0}
!144 = !{!"rb_hook_list_struct", !13, i64 0, !16, i64 8, !16, i64 12, !16, i64 16}
!145 = !{!"", !5, i64 0, !5, i64 8, !5, i64 16, !5, i64 24}
!146 = !DILocation(line: 0, scope: !75)
!147 = !{!142, !142, i64 0}
!148 = !{!"branch_weights", i32 10000, i32 1}
