; ModuleID = 'payload'
source_filename = "llvm-link"
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"

%struct.rb_vm_struct = type { i64, %struct.rb_global_vm_lock_struct, %struct.rb_thread_struct*, %struct.rb_thread_struct*, i8*, i64, %union.pthread_mutex_t, %struct.list_head, %struct.list_head, %struct.list_head, %struct.list_head, i64, i32, i8, i32, i64, [5 x i64], i64, i64, i64, i64, i64, i64, i64, %struct.st_table*, %struct.st_table*, %struct.anon.3, %struct.rb_hook_list_struct, %struct.st_table*, %struct.rb_postponed_job_struct*, i32, i32, %struct.list_head, %union.pthread_mutex_t, i64, i64, i64, i64, i64, i32, i64, %struct.rb_objspace*, %struct.rb_at_exit_list*, i64*, %struct.st_table*, %struct.anon.4, [28 x i16] }
%struct.rb_global_vm_lock_struct = type { %struct.rb_thread_struct*, %union.pthread_mutex_t, %struct.list_head, %struct.rb_thread_struct*, i32, %union.pthread_cond_t, %union.pthread_cond_t, i32, i32 }
%union.pthread_cond_t = type { %struct.anon.2 }
%struct.anon.2 = type { i32, i32, i64, i64, i64, i8*, i32, i32 }
%struct.rb_thread_struct = type { %struct.list_node, i64, %struct.rb_vm_struct*, %struct.rb_execution_context_struct*, i64, %struct.rb_calling_info*, i64, i64, i64, i8, i8, i32, %struct.native_thread_data_struct, i8*, i64, i64, i64, i64, %union.pthread_mutex_t, %struct.rb_unblock_callback, i64, %struct.rb_mutex_struct*, %struct.rb_thread_list_struct*, %union.anon.8, i32, i64, %struct.rb_fiber_struct*, [1 x %struct.__jmp_buf_tag], i64 }
%struct.list_node = type { %struct.list_node*, %struct.list_node* }
%struct.rb_execution_context_struct = type { i64*, i64, %struct.rb_control_frame_struct*, %struct.rb_vm_tag*, %struct.rb_vm_protect_tag*, i32, i32, %struct.rb_fiber_struct*, %struct.rb_thread_struct*, %struct.st_table*, i64, i64, i64*, i64, %struct.rb_ensure_list*, %struct.rb_trace_arg_struct*, i64, i64, i8, i8, i64, %struct.anon.5 }
%struct.rb_control_frame_struct = type { i64*, i64*, %struct.rb_iseq_struct*, i64, i64*, i8*, i64* }
%struct.rb_iseq_struct = type { i64, i64, %struct.rb_iseq_constant_body*, %union.anon.14 }
%struct.rb_iseq_constant_body = type { i32, i32, i64*, %struct.anon, %struct.rb_iseq_location_struct, %struct.iseq_insn_info, i64*, %struct.iseq_catch_table*, %struct.rb_iseq_struct*, %struct.rb_iseq_struct*, %union.iseq_inline_storage_entry*, %struct.rb_call_info*, %struct.rb_call_cache*, %struct.anon.13, i32, i32, i32, i32, i32, i64 (%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*)*, i64, %struct.rb_mjit_unit*, i8 }
%struct.anon = type { %struct.anon.0, i32, i32, i32, i32, i32, i32, i32, i64*, %struct.rb_iseq_param_keyword* }
%struct.anon.0 = type { i8, [3 x i8] }
%struct.rb_iseq_param_keyword = type { i32, i32, i32, i32, i64*, i64* }
%struct.rb_iseq_location_struct = type { i64, i64, i64, i64, i32, %struct.rb_code_location_struct }
%struct.rb_code_location_struct = type { %struct.rb_code_position_struct, %struct.rb_code_position_struct }
%struct.rb_code_position_struct = type { i32, i32 }
%struct.iseq_insn_info = type { %struct.iseq_insn_info_entry*, i32*, i32, %struct.succ_index_table* }
%struct.iseq_insn_info_entry = type opaque
%struct.succ_index_table = type opaque
%struct.iseq_catch_table = type opaque
%union.iseq_inline_storage_entry = type { %struct.iseq_inline_cache_entry }
%struct.iseq_inline_cache_entry = type { i64, %struct.rb_cref_struct*, %union.anon.11 }
%struct.rb_cref_struct = type { i64, i64, i64, %struct.rb_cref_struct*, %struct.anon.0 }
%union.anon.11 = type { i64 }
%struct.rb_call_info = type { i64, i32, i32 }
%struct.rb_call_cache = type { i64, i64, %struct.rb_callable_method_entry_struct*, i64 (%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_calling_info*, %struct.rb_call_info*, %struct.rb_call_cache*)*, %union.anon.12 }
%struct.rb_callable_method_entry_struct = type { i64, i64, %struct.rb_method_definition_struct*, i64, i64 }
%struct.rb_method_definition_struct = type { i64, %union.anon, i64 }
%union.anon = type { %struct.rb_method_cfunc_struct }
%struct.rb_method_cfunc_struct = type { i64 (...)*, i64 (i64 (...)*, i64, i32, i64*)*, i32 }
%union.anon.12 = type { i32 }
%struct.anon.13 = type { i64, i64, i64, i64* }
%struct.rb_mjit_unit = type opaque
%union.anon.14 = type { %struct.anon.15 }
%struct.anon.15 = type { i64, i32 }
%struct.rb_vm_tag = type { i64, i64, [1 x %struct.__jmp_buf_tag], %struct.rb_vm_tag*, i32 }
%struct.rb_vm_protect_tag = type { %struct.rb_vm_protect_tag* }
%struct.rb_ensure_list = type { %struct.rb_ensure_list*, %struct.rb_ensure_entry }
%struct.rb_ensure_entry = type { i64, i64 (...)*, i64 }
%struct.rb_trace_arg_struct = type { i32, %struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, i64, i64, i64, i64, i64, i32, i32, i64 }
%struct.anon.5 = type { i64*, i64*, i64, [1 x %struct.__jmp_buf_tag] }
%struct.rb_calling_info = type { i64, i64, i32 }
%struct.native_thread_data_struct = type { %struct.list_head, %union.anon.7 }
%union.anon.7 = type { %union.pthread_cond_t }
%struct.rb_unblock_callback = type { void (i8*)*, i8* }
%struct.rb_mutex_struct = type opaque
%struct.rb_thread_list_struct = type { %struct.rb_thread_list_struct*, %struct.rb_thread_struct* }
%union.anon.8 = type { %struct.anon.9 }
%struct.anon.9 = type { i64, i64 }
%struct.rb_fiber_struct = type opaque
%struct.__jmp_buf_tag = type { [8 x i64], i32, %struct.__sigset_t }
%struct.__sigset_t = type { [16 x i64] }
%struct.anon.3 = type { [65 x i64], [65 x i8] }
%struct.rb_hook_list_struct = type { %struct.rb_event_hook_struct*, i32, i32, i32 }
%struct.rb_event_hook_struct = type opaque
%struct.rb_postponed_job_struct = type opaque
%struct.list_head = type { %struct.list_node }
%union.pthread_mutex_t = type { %struct.__pthread_mutex_s }
%struct.__pthread_mutex_s = type { i32, i32, i32, i32, i32, i16, i16, %struct.__pthread_internal_list }
%struct.__pthread_internal_list = type { %struct.__pthread_internal_list*, %struct.__pthread_internal_list* }
%struct.rb_objspace = type opaque
%struct.rb_at_exit_list = type { void (%struct.rb_vm_struct*)*, %struct.rb_at_exit_list* }
%struct.st_table = type { i8, i8, i8, i32, %struct.st_hash_type*, i64, i64*, i64, i64, %struct.st_table_entry* }
%struct.st_hash_type = type { i32 (...)*, i64 (...)* }
%struct.st_table_entry = type opaque
%struct.anon.4 = type { i64, i64, i64, i64 }
%struct.FunctionInlineCache = type { %struct.rb_callable_method_entry_struct*, i64, i64 }

@ruby_current_vm_ptr = external local_unnamed_addr global %struct.rb_vm_struct*, align 8
@ruby_vm_global_constant_state = external local_unnamed_addr global i64, align 8
@ruby_current_execution_context_ptr = external local_unnamed_addr global %struct.rb_execution_context_struct*, align 8
@rb_eRuntimeError = external local_unnamed_addr global i64, align 8
@.str.6 = private unnamed_addr constant [95 x i8] c"sorbet_getBuildSCMRevision: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@.str.7 = private unnamed_addr constant [93 x i8] c"sorbet_getIsReleaseBuild: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@"stackFramePrecomputed_func_<root>.<static-init>$153" = internal unnamed_addr global i8* null, align 8
@"rubyIdPrecomputed_<top (required)>" = internal unnamed_addr global i64 0, align 8
@"str_<top (required)>" = private unnamed_addr constant [17 x i8] c"<top (required)>\00", align 1
@"rubyStrFrozen_<top (required)>" = internal unnamed_addr global i64 0, align 8
@"rubyStrFrozen_test/testdata/compiler/instancefields.rb" = internal unnamed_addr global i64 0, align 8
@"str_test/testdata/compiler/instancefields.rb" = private unnamed_addr constant [41 x i8] c"test/testdata/compiler/instancefields.rb\00", align 1
@str_A = private unnamed_addr constant [2 x i8] c"A\00", align 1
@rubyIdPrecomputed_new = internal unnamed_addr global i64 0, align 8
@str_new = private unnamed_addr constant [4 x i8] c"new\00", align 1
@ic_callFunc_new = internal global %struct.FunctionInlineCache zeroinitializer
@ic_callFunc_new.1 = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_read = internal unnamed_addr global i64 0, align 8
@str_read = private unnamed_addr constant [5 x i8] c"read\00", align 1
@ic_callFunc_read = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_puts = internal unnamed_addr global i64 0, align 8
@str_puts = private unnamed_addr constant [5 x i8] c"puts\00", align 1
@ic_callFunc_puts = internal global %struct.FunctionInlineCache zeroinitializer
@rubyStrFrozen_value = internal unnamed_addr global i64 0, align 8
@str_value = private unnamed_addr constant [6 x i8] c"value\00", align 1
@rubyIdPrecomputed_write = internal unnamed_addr global i64 0, align 8
@str_write = private unnamed_addr constant [6 x i8] c"write\00", align 1
@ic_callFunc_write = internal global %struct.FunctionInlineCache zeroinitializer
@ic_callFunc_read.2 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_callFunc_puts.3 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_callFunc_read.4 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_callFunc_puts.5 = internal global %struct.FunctionInlineCache zeroinitializer
@"stackFramePrecomputed_func_A#write" = internal unnamed_addr global i8* null, align 8
@"rubyIdPrecomputed_@f" = internal unnamed_addr global i64 0, align 8
@"str_@f" = private unnamed_addr constant [3 x i8] c"@f\00", align 1
@"stackFramePrecomputed_func_A#read" = internal unnamed_addr global i8* null, align 8
@"stackFramePrecomputed_func_A.<static-init>" = internal unnamed_addr global i8* null, align 8
@"<static-init-locals-storage>.6" = internal global [0 x i64] zeroinitializer
@str_keep_def = private unnamed_addr constant [9 x i8] c"keep_def\00", align 1
@rb_cObject = external local_unnamed_addr constant i64
@guard_epoch_A = linkonce local_unnamed_addr global i64 0
@guarded_const_A = linkonce local_unnamed_addr global i64 0

; Function Attrs: noreturn
declare void @sorbet_raiseArity(i32, i32, i32) local_unnamed_addr #0

declare i8* @sorbet_allocateRubyStackFrame(i64, i64, i64, i64, i8*, i32, i32, i32, i64*, i32) local_unnamed_addr #1

declare i64 @sorbet_getConstant(i8*, i64) local_unnamed_addr #1

declare i64 @sorbet_readRealpath() local_unnamed_addr #1

declare i64 @sorbet_callFuncWithCache(i64, i64, i32, i64* nocapture, i32, %struct.FunctionInlineCache*) local_unnamed_addr #1

declare void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_iseq_struct*) local_unnamed_addr #1

declare i64 @rb_define_class(i8*, i64) local_unnamed_addr #1

declare void @rb_define_method(i64, i8*, i64 (...)*, i32) local_unnamed_addr #1

declare i64 @rb_ivar_get(i64, i64) local_unnamed_addr #1

declare i64 @rb_ivar_set(i64, i64, i64) local_unnamed_addr #1

declare i64 @rb_intern2(i8*, i64) local_unnamed_addr #1

declare i64 @rb_id2sym(i64) local_unnamed_addr #1

declare i64 @rb_fstring_new(i8*, i64) local_unnamed_addr #1

declare void @rb_gc_register_mark_object(i64) local_unnamed_addr #1

; Function Attrs: noreturn
declare void @rb_raise(i64, i8*, ...) local_unnamed_addr #0

; Function Attrs: nounwind ssp uwtable
define weak i32 @sorbet_getIsReleaseBuild() local_unnamed_addr #2 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !4
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* getelementptr inbounds ([93 x i8], [93 x i8]* @.str.7, i64 0, i64 0)) #8
  unreachable
}

; Function Attrs: nounwind ssp uwtable
define weak i8* @sorbet_getBuildSCMRevision() local_unnamed_addr #2 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !4
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* getelementptr inbounds ([95 x i8], [95 x i8]* @.str.6, i64 0, i64 0)) #8
  unreachable
}

; Function Attrs: sspreq
define void @Init_instancefields() local_unnamed_addr #3 {
entry:
  %locals1.i.i = alloca [0 x i64], align 8
  %callArgs.i = alloca [1 x i64], align 8
  %realpath = tail call i64 @sorbet_readRealpath()
  %0 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 16) #6
  store i64 %0, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %1 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_new, i64 0, i64 0), i64 3) #6
  store i64 %1, i64* @rubyIdPrecomputed_new, align 8
  %2 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_read, i64 0, i64 0), i64 4) #6
  store i64 %2, i64* @rubyIdPrecomputed_read, align 8
  %3 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_puts, i64 0, i64 0), i64 4) #6
  store i64 %3, i64* @rubyIdPrecomputed_puts, align 8
  %4 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([6 x i8], [6 x i8]* @str_write, i64 0, i64 0), i64 5) #6
  store i64 %4, i64* @rubyIdPrecomputed_write, align 8
  %5 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([3 x i8], [3 x i8]* @"str_@f", i64 0, i64 0), i64 2) #6
  store i64 %5, i64* @"rubyIdPrecomputed_@f", align 8
  %6 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([9 x i8], [9 x i8]* @str_keep_def, i64 0, i64 0), i64 8) #6
  %7 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 16) #6
  tail call void @rb_gc_register_mark_object(i64 %7) #6
  store i64 %7, i64* @"rubyStrFrozen_<top (required)>", align 8
  %8 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([41 x i8], [41 x i8]* @"str_test/testdata/compiler/instancefields.rb", i64 0, i64 0), i64 40) #6
  tail call void @rb_gc_register_mark_object(i64 %8) #6
  store i64 %8, i64* @"rubyStrFrozen_test/testdata/compiler/instancefields.rb", align 8
  %"rubyId_<top (required)>.i.i" = load i64, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %"rubyStr_<top (required)>.i.i" = load i64, i64* @"rubyStrFrozen_<top (required)>", align 8
  %9 = tail call i8* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_<top (required)>.i.i", i64 %"rubyId_<top (required)>.i.i", i64 %8, i64 %realpath, i8* null, i32 1, i32 1, i32 19, i64* getelementptr inbounds ([0 x i64], [0 x i64]* @"<static-init-locals-storage>.6", i64 0, i64 0), i32 0)
  store i8* %9, i8** @"stackFramePrecomputed_func_<root>.<static-init>$153", align 8
  %10 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([6 x i8], [6 x i8]* @str_value, i64 0, i64 0), i64 5) #6
  tail call void @rb_gc_register_mark_object(i64 %10) #6
  store i64 %10, i64* @rubyStrFrozen_value, align 8
  %11 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([6 x i8], [6 x i8]* @str_write, i64 0, i64 0), i64 5) #6
  tail call void @rb_gc_register_mark_object(i64 %11) #6
  %12 = bitcast [0 x i64]* %locals1.i.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 0, i8* nonnull %12)
  %rubyId_write.i.i = load i64, i64* @rubyIdPrecomputed_write, align 8
  %"rubyStr_test/testdata/compiler/instancefields.rb.i2.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/instancefields.rb", align 8
  %locals1.sub.i.i = getelementptr inbounds [0 x i64], [0 x i64]* %locals1.i.i, i64 0, i64 0
  %13 = call i8* @sorbet_allocateRubyStackFrame(i64 %11, i64 %rubyId_write.i.i, i64 %"rubyStr_test/testdata/compiler/instancefields.rb.i2.i", i64 %realpath, i8* null, i32 1, i32 6, i32 8, i64* nonnull %locals1.sub.i.i, i32 0)
  store i8* %13, i8** @"stackFramePrecomputed_func_A#write", align 8
  call void @llvm.lifetime.end.p0i8(i64 0, i8* nonnull %12)
  %14 = call i64 @rb_fstring_new(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_read, i64 0, i64 0), i64 4) #6
  call void @rb_gc_register_mark_object(i64 %14) #6
  call void @llvm.lifetime.start.p0i8(i64 0, i8* nonnull %12)
  %rubyId_read.i.i = load i64, i64* @rubyIdPrecomputed_read, align 8
  %"rubyStr_test/testdata/compiler/instancefields.rb.i4.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/instancefields.rb", align 8
  %15 = call i8* @sorbet_allocateRubyStackFrame(i64 %14, i64 %rubyId_read.i.i, i64 %"rubyStr_test/testdata/compiler/instancefields.rb.i4.i", i64 %realpath, i8* null, i32 1, i32 9, i32 11, i64* nonnull %locals1.sub.i.i, i32 0)
  store i8* %15, i8** @"stackFramePrecomputed_func_A#read", align 8
  call void @llvm.lifetime.end.p0i8(i64 0, i8* nonnull %12)
  %"rubyId_<top (required)>.i6.i" = load i64, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %"rubyStr_<top (required)>.i7.i" = load i64, i64* @"rubyStrFrozen_<top (required)>", align 8
  %"rubyStr_test/testdata/compiler/instancefields.rb.i8.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/instancefields.rb", align 8
  %16 = call i8* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_<top (required)>.i7.i", i64 %"rubyId_<top (required)>.i6.i", i64 %"rubyStr_test/testdata/compiler/instancefields.rb.i8.i", i64 %realpath, i8* null, i32 1, i32 1, i32 5, i64* null, i32 0)
  store i8* %16, i8** @"stackFramePrecomputed_func_A.<static-init>", align 8
  %17 = load %struct.rb_vm_struct*, %struct.rb_vm_struct** @ruby_current_vm_ptr, align 8, !tbaa !8
  %18 = getelementptr inbounds %struct.rb_vm_struct, %struct.rb_vm_struct* %17, i64 0, i32 17
  %19 = load i64, i64* %18, align 8, !tbaa !10
  %20 = bitcast [1 x i64]* %callArgs.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %20)
  %"stackFrame_func_<root>.<static-init>$153.i" = load i8*, i8** @"stackFramePrecomputed_func_<root>.<static-init>$153", align 8
  %21 = bitcast i8* %"stackFrame_func_<root>.<static-init>$153.i" to %struct.rb_iseq_struct*
  %22 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !8
  %23 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %22, i64 0, i32 2
  %24 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %23, align 8, !tbaa !20
  %25 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %24, i64 0, i32 2
  %26 = bitcast %struct.rb_iseq_struct** %25 to i8**
  store i8* %"stackFrame_func_<root>.<static-init>$153.i", i8** %26, align 8, !tbaa !23
  %27 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %24, i64 0, i32 4
  %28 = load i64*, i64** %27, align 8, !tbaa !25
  %29 = load i64, i64* %28, align 8, !tbaa !4
  %30 = and i64 %29, -129
  store i64 %30, i64* %28, align 8, !tbaa !4
  call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* %22, %struct.rb_control_frame_struct* nonnull %24, %struct.rb_iseq_struct* %21) #6
  %31 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %24, i64 0, i32 0
  %32 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %25, align 8, !tbaa !23
  %33 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %32, i64 0, i32 2
  %34 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %33, align 8, !tbaa !26
  %35 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %34, i64 0, i32 2
  %36 = load i64*, i64** %35, align 8, !tbaa !28
  %37 = getelementptr inbounds i64, i64* %36, i64 5
  store i64* %37, i64** %31, align 8, !tbaa !8
  %38 = load i64, i64* @rb_cObject, align 8, !dbg !37
  %39 = call i64 @rb_define_class(i8* getelementptr inbounds ([2 x i8], [2 x i8]* @str_A, i64 0, i64 0), i64 %38) #6, !dbg !37
  %40 = load i64, i64* @guard_epoch_A, align 8, !dbg !37
  %41 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !37, !tbaa !42
  %needTakeSlowPath = icmp eq i64 %40, %41, !dbg !37
  br i1 %needTakeSlowPath, label %43, label %42, !dbg !37, !prof !43

42:                                               ; preds = %entry
  call void @const_recompute_A(), !dbg !37
  br label %43, !dbg !37

43:                                               ; preds = %entry, %42
  %44 = load i64, i64* @guarded_const_A, align 8, !dbg !37
  %45 = load i64, i64* @guard_epoch_A, align 8, !dbg !37
  %46 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !37, !tbaa !42
  %guardUpdated = icmp eq i64 %45, %46, !dbg !37
  call void @llvm.assume(i1 %guardUpdated), !dbg !37
  %47 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !8
  %48 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %47, i64 0, i32 2
  %49 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %48, align 8, !tbaa !20
  %50 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %49, i64 0, i32 0
  %51 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %49, i64 0, i32 2
  %52 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %51, align 8, !tbaa !23
  %53 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %52, i64 0, i32 2
  %54 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %53, align 8, !tbaa !26
  %55 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %54, i64 0, i32 2
  %56 = load i64*, i64** %55, align 8, !tbaa !28
  %57 = getelementptr inbounds i64, i64* %56, i64 6, !dbg !44
  store i64* %57, i64** %50, align 8, !dbg !44, !tbaa !8
  %rubyId_write.i.i1 = load i64, i64* @rubyIdPrecomputed_write, align 8, !dbg !47
  %rawSym.i.i = call i64 @rb_id2sym(i64 %rubyId_write.i.i1) #6, !dbg !47
  call void @rb_define_method(i64 %44, i8* getelementptr inbounds ([6 x i8], [6 x i8]* @str_write, i64 0, i64 0), i64 (...)* bitcast (i64 (i32, i64*, i64)* @"func_A#write" to i64 (...)*), i32 -1) #6, !dbg !47
  %58 = getelementptr inbounds i64, i64* %56, i64 9, !dbg !47
  store i64* %58, i64** %50, align 8, !dbg !47, !tbaa !8
  %rubyId_read.i.i2 = load i64, i64* @rubyIdPrecomputed_read, align 8, !dbg !48
  %rawSym17.i.i = call i64 @rb_id2sym(i64 %rubyId_read.i.i2) #6, !dbg !48
  call void @rb_define_method(i64 %44, i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_read, i64 0, i64 0), i64 (...)* bitcast (i64 (i32, i64*, i64)* @"func_A#read" to i64 (...)*), i32 -1) #6, !dbg !48
  %59 = getelementptr inbounds i64, i64* %36, i64 14
  store i64* %59, i64** %31, align 8, !tbaa !8
  %rubyId_new.i = load i64, i64* @rubyIdPrecomputed_new, align 8, !dbg !49
  %callFunc_new.i = call i64 @sorbet_callFuncWithCache(i64 %44, i64 %rubyId_new.i, i32 0, i64* null, i32 0, %struct.FunctionInlineCache* nonnull @ic_callFunc_new) #6, !dbg !49
  %60 = getelementptr inbounds i64, i64* %36, i64 15, !dbg !49
  store i64* %60, i64** %31, align 8, !dbg !49, !tbaa !8
  %rubyId_new42.i = load i64, i64* @rubyIdPrecomputed_new, align 8, !dbg !50
  %callFunc_new43.i = call i64 @sorbet_callFuncWithCache(i64 %44, i64 %rubyId_new42.i, i32 0, i64* null, i32 0, %struct.FunctionInlineCache* nonnull @ic_callFunc_new.1) #6, !dbg !50
  %61 = getelementptr inbounds i64, i64* %36, i64 16, !dbg !50
  store i64* %61, i64** %31, align 8, !dbg !50, !tbaa !8
  %rubyId_read.i = load i64, i64* @rubyIdPrecomputed_read, align 8, !dbg !51
  %callFunc_read.i = call i64 @sorbet_callFuncWithCache(i64 %callFunc_new.i, i64 %rubyId_read.i, i32 0, i64* null, i32 0, %struct.FunctionInlineCache* nonnull @ic_callFunc_read) #6, !dbg !51
  %callArgs0Addr.i = getelementptr inbounds [1 x i64], [1 x i64]* %callArgs.i, i64 0, i64 0, !dbg !52
  store i64 %callFunc_read.i, i64* %callArgs0Addr.i, align 8, !dbg !52
  %rubyId_puts.i = load i64, i64* @rubyIdPrecomputed_puts, align 8, !dbg !52
  %callFunc_puts.i = call i64 @sorbet_callFuncWithCache(i64 %19, i64 %rubyId_puts.i, i32 1, i64* nonnull %callArgs0Addr.i, i32 0, %struct.FunctionInlineCache* nonnull @ic_callFunc_puts) #6, !dbg !52
  %62 = getelementptr inbounds i64, i64* %36, i64 17, !dbg !52
  store i64* %62, i64** %31, align 8, !dbg !52, !tbaa !8
  %rubyStr_value.i = load i64, i64* @rubyStrFrozen_value, align 8, !dbg !53
  store i64 %rubyStr_value.i, i64* %callArgs0Addr.i, align 8, !dbg !54
  %rubyId_write.i = load i64, i64* @rubyIdPrecomputed_write, align 8, !dbg !54
  %callFunc_write.i = call i64 @sorbet_callFuncWithCache(i64 %callFunc_new.i, i64 %rubyId_write.i, i32 1, i64* nonnull %callArgs0Addr.i, i32 0, %struct.FunctionInlineCache* nonnull @ic_callFunc_write) #6, !dbg !54
  %63 = getelementptr inbounds i64, i64* %36, i64 18, !dbg !54
  store i64* %63, i64** %31, align 8, !dbg !54, !tbaa !8
  %rubyId_read56.i = load i64, i64* @rubyIdPrecomputed_read, align 8, !dbg !55
  %callFunc_read57.i = call i64 @sorbet_callFuncWithCache(i64 %callFunc_new.i, i64 %rubyId_read56.i, i32 0, i64* null, i32 0, %struct.FunctionInlineCache* nonnull @ic_callFunc_read.2) #6, !dbg !55
  store i64 %callFunc_read57.i, i64* %callArgs0Addr.i, align 8, !dbg !56
  %rubyId_puts63.i = load i64, i64* @rubyIdPrecomputed_puts, align 8, !dbg !56
  %callFunc_puts64.i = call i64 @sorbet_callFuncWithCache(i64 %19, i64 %rubyId_puts63.i, i32 1, i64* nonnull %callArgs0Addr.i, i32 0, %struct.FunctionInlineCache* nonnull @ic_callFunc_puts.3) #6, !dbg !56
  %64 = getelementptr inbounds i64, i64* %36, i64 19, !dbg !56
  store i64* %64, i64** %31, align 8, !dbg !56, !tbaa !8
  %rubyId_read68.i = load i64, i64* @rubyIdPrecomputed_read, align 8, !dbg !57
  %callFunc_read69.i = call i64 @sorbet_callFuncWithCache(i64 %callFunc_new43.i, i64 %rubyId_read68.i, i32 0, i64* null, i32 0, %struct.FunctionInlineCache* nonnull @ic_callFunc_read.4) #6, !dbg !57
  store i64 %callFunc_read69.i, i64* %callArgs0Addr.i, align 8, !dbg !58
  %rubyId_puts75.i = load i64, i64* @rubyIdPrecomputed_puts, align 8, !dbg !58
  %callFunc_puts76.i = call i64 @sorbet_callFuncWithCache(i64 %19, i64 %rubyId_puts75.i, i32 1, i64* nonnull %callArgs0Addr.i, i32 0, %struct.FunctionInlineCache* nonnull @ic_callFunc_puts.5) #6, !dbg !58
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %20)
  ret void
}

; Function Attrs: nounwind sspreq uwtable
define i64 @"func_A#write"(i32 %argc, i64* nocapture readonly %argArray, i64 %selfRaw) #4 !dbg !59 {
functionEntryInitializers:
  %"stackFrame_func_A#write" = load i8*, i8** @"stackFramePrecomputed_func_A#write", align 8
  %0 = bitcast i8* %"stackFrame_func_A#write" to %struct.rb_iseq_struct*
  %1 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !8
  %2 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %1, i64 0, i32 2
  %3 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %2, align 8, !tbaa !20
  %4 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 2
  %5 = bitcast %struct.rb_iseq_struct** %4 to i8**
  store i8* %"stackFrame_func_A#write", i8** %5, align 8, !tbaa !23
  %6 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 4
  %7 = load i64*, i64** %6, align 8, !tbaa !25
  %8 = load i64, i64* %7, align 8, !tbaa !4
  %9 = and i64 %8, -129
  store i64 %9, i64* %7, align 8, !tbaa !4
  tail call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* %1, %struct.rb_control_frame_struct* nonnull %3, %struct.rb_iseq_struct* %0) #6
  %10 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 0
  %11 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %4, align 8, !tbaa !23
  %12 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %11, i64 0, i32 2
  %13 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %12, align 8, !tbaa !26
  %14 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %13, i64 0, i32 2
  %15 = load i64*, i64** %14, align 8, !tbaa !28
  %16 = getelementptr inbounds i64, i64* %15, i64 1
  store i64* %16, i64** %10, align 8, !tbaa !8
  %17 = icmp eq i32 %argc, 1, !dbg !60
  br i1 %17, label %fillRequiredArgs, label %argCountFailBlock, !dbg !60, !prof !61

argCountFailBlock:                                ; preds = %functionEntryInitializers
  tail call void @sorbet_raiseArity(i32 %argc, i32 1, i32 1) #6, !dbg !60
  unreachable, !dbg !60

fillRequiredArgs:                                 ; preds = %functionEntryInitializers
  %rawArg_v = load i64, i64* %argArray, align 8, !dbg !60
  %18 = getelementptr inbounds i64, i64* %15, i64 2, !dbg !62
  store i64* %18, i64** %10, align 8, !dbg !62, !tbaa !8
  %"rubyId_@f" = load i64, i64* @"rubyIdPrecomputed_@f", align 8, !dbg !63
  %19 = tail call i64 @rb_ivar_set(i64 %selfRaw, i64 %"rubyId_@f", i64 %rawArg_v) #6, !dbg !63
  %"rubyId_@f10" = load i64, i64* @"rubyIdPrecomputed_@f", align 8, !dbg !64
  %20 = tail call i64 @rb_ivar_get(i64 %selfRaw, i64 %"rubyId_@f10") #6, !dbg !64
  ret i64 %20
}

; Function Attrs: nounwind sspreq uwtable
define i64 @"func_A#read"(i32 %argc, i64* nocapture readnone %argArray, i64 %selfRaw) #4 !dbg !65 {
functionEntryInitializers:
  %"stackFrame_func_A#read" = load i8*, i8** @"stackFramePrecomputed_func_A#read", align 8
  %0 = bitcast i8* %"stackFrame_func_A#read" to %struct.rb_iseq_struct*
  %1 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !8
  %2 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %1, i64 0, i32 2
  %3 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %2, align 8, !tbaa !20
  %4 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 2
  %5 = bitcast %struct.rb_iseq_struct** %4 to i8**
  store i8* %"stackFrame_func_A#read", i8** %5, align 8, !tbaa !23
  %6 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 4
  %7 = load i64*, i64** %6, align 8, !tbaa !25
  %8 = load i64, i64* %7, align 8, !tbaa !4
  %9 = and i64 %8, -129
  store i64 %9, i64* %7, align 8, !tbaa !4
  tail call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* %1, %struct.rb_control_frame_struct* nonnull %3, %struct.rb_iseq_struct* %0) #6
  %10 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 0
  %11 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %4, align 8, !tbaa !23
  %12 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %11, i64 0, i32 2
  %13 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %12, align 8, !tbaa !26
  %14 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %13, i64 0, i32 2
  %15 = load i64*, i64** %14, align 8, !tbaa !28
  %16 = getelementptr inbounds i64, i64* %15, i64 1
  store i64* %16, i64** %10, align 8, !tbaa !8
  %tooManyArgs = icmp eq i32 %argc, 0, !dbg !66
  br i1 %tooManyArgs, label %fillRequiredArgs, label %argCountFailBlock, !dbg !66, !prof !67

argCountFailBlock:                                ; preds = %functionEntryInitializers
  tail call void @sorbet_raiseArity(i32 %argc, i32 0, i32 0) #6, !dbg !66
  unreachable, !dbg !66

fillRequiredArgs:                                 ; preds = %functionEntryInitializers
  %17 = getelementptr inbounds i64, i64* %15, i64 2, !dbg !66
  store i64* %17, i64** %10, align 8, !dbg !66, !tbaa !8
  %"rubyId_@f" = load i64, i64* @"rubyIdPrecomputed_@f", align 8, !dbg !68
  %18 = tail call i64 @rb_ivar_get(i64 %selfRaw, i64 %"rubyId_@f") #6, !dbg !68
  ret i64 %18
}

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #5

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.end.p0i8(i64 immarg, i8* nocapture) #5

; Function Attrs: nounwind
declare void @llvm.assume(i1) #6

; Function Attrs: ssp
define linkonce void @const_recompute_A() local_unnamed_addr #7 {
  %1 = tail call i64 @sorbet_getConstant(i8* getelementptr inbounds ([2 x i8], [2 x i8]* @str_A, i64 0, i64 0), i64 1)
  store i64 %1, i64* @guarded_const_A, align 8
  %2 = load i64, i64* @ruby_vm_global_constant_state, align 8, !tbaa !42
  store i64 %2, i64* @guard_epoch_A, align 8
  ret void
}

attributes #0 = { noreturn }
attributes #1 = { "addedToSilenceEmptyAttrsError" }
attributes #2 = { nounwind ssp uwtable }
attributes #3 = { sspreq }
attributes #4 = { nounwind sspreq uwtable }
attributes #5 = { argmemonly nounwind }
attributes #6 = { nounwind }
attributes #7 = { ssp }
attributes #8 = { noreturn nounwind }

!llvm.module.flags = !{!0}
!llvm.dbg.cu = !{!1}

!0 = !{i32 2, !"Debug Info Version", i32 3}
!1 = distinct !DICompileUnit(language: DW_LANG_C, file: !2, producer: "Sorbet LLVM", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, enums: !3)
!2 = !DIFile(filename: "test/testdata/compiler/instancefields.rb", directory: ".")
!3 = !{}
!4 = !{!5, !5, i64 0}
!5 = !{!"long", !6, i64 0}
!6 = !{!"omnipotent char", !7, i64 0}
!7 = !{!"Simple C/C++ TBAA"}
!8 = !{!9, !9, i64 0}
!9 = !{!"any pointer", !6, i64 0}
!10 = !{!11, !5, i64 400}
!11 = !{!"rb_vm_struct", !5, i64 0, !12, i64 8, !9, i64 192, !9, i64 200, !9, i64 208, !16, i64 216, !6, i64 224, !13, i64 264, !13, i64 280, !13, i64 296, !13, i64 312, !5, i64 328, !15, i64 336, !15, i64 340, !15, i64 340, !15, i64 340, !15, i64 340, !15, i64 344, !5, i64 352, !6, i64 360, !5, i64 400, !5, i64 408, !5, i64 416, !5, i64 424, !5, i64 432, !5, i64 440, !5, i64 448, !9, i64 456, !9, i64 464, !17, i64 472, !18, i64 1064, !9, i64 1088, !9, i64 1096, !15, i64 1104, !15, i64 1108, !13, i64 1112, !6, i64 1128, !5, i64 1168, !5, i64 1176, !5, i64 1184, !5, i64 1192, !5, i64 1200, !15, i64 1208, !5, i64 1216, !9, i64 1224, !9, i64 1232, !9, i64 1240, !9, i64 1248, !19, i64 1256, !6, i64 1288}
!12 = !{!"rb_global_vm_lock_struct", !9, i64 0, !6, i64 8, !13, i64 48, !9, i64 64, !15, i64 72, !6, i64 80, !6, i64 128, !15, i64 176, !15, i64 180}
!13 = !{!"list_head", !14, i64 0}
!14 = !{!"list_node", !9, i64 0, !9, i64 8}
!15 = !{!"int", !6, i64 0}
!16 = !{!"long long", !6, i64 0}
!17 = !{!"", !6, i64 0, !6, i64 520}
!18 = !{!"rb_hook_list_struct", !9, i64 0, !15, i64 8, !15, i64 12, !15, i64 16}
!19 = !{!"", !5, i64 0, !5, i64 8, !5, i64 16, !5, i64 24}
!20 = !{!21, !9, i64 16}
!21 = !{!"rb_execution_context_struct", !9, i64 0, !5, i64 8, !9, i64 16, !9, i64 24, !9, i64 32, !15, i64 40, !15, i64 44, !9, i64 48, !9, i64 56, !9, i64 64, !5, i64 72, !5, i64 80, !9, i64 88, !5, i64 96, !9, i64 104, !9, i64 112, !5, i64 120, !5, i64 128, !6, i64 136, !6, i64 137, !5, i64 144, !22, i64 152}
!22 = !{!"", !9, i64 0, !9, i64 8, !5, i64 16, !6, i64 24}
!23 = !{!24, !9, i64 16}
!24 = !{!"rb_control_frame_struct", !9, i64 0, !9, i64 8, !9, i64 16, !5, i64 24, !9, i64 32, !9, i64 40, !9, i64 48}
!25 = !{!24, !9, i64 32}
!26 = !{!27, !9, i64 16}
!27 = !{!"rb_iseq_struct", !5, i64 0, !5, i64 8, !9, i64 16, !6, i64 24}
!28 = !{!29, !9, i64 8}
!29 = !{!"rb_iseq_constant_body", !6, i64 0, !15, i64 4, !9, i64 8, !30, i64 16, !32, i64 64, !35, i64 120, !9, i64 152, !9, i64 160, !9, i64 168, !9, i64 176, !9, i64 184, !9, i64 192, !9, i64 200, !36, i64 208, !15, i64 240, !15, i64 244, !15, i64 248, !15, i64 252, !15, i64 256, !9, i64 264, !5, i64 272, !9, i64 280, !6, i64 288}
!30 = !{!"", !31, i64 0, !15, i64 4, !15, i64 8, !15, i64 12, !15, i64 16, !15, i64 20, !15, i64 24, !15, i64 28, !9, i64 32, !9, i64 40}
!31 = !{!"", !15, i64 0, !15, i64 0, !15, i64 0, !15, i64 0, !15, i64 0, !15, i64 0, !15, i64 0, !15, i64 0}
!32 = !{!"rb_iseq_location_struct", !5, i64 0, !5, i64 8, !5, i64 16, !5, i64 24, !15, i64 32, !33, i64 36}
!33 = !{!"rb_code_location_struct", !34, i64 0, !34, i64 8}
!34 = !{!"rb_code_position_struct", !15, i64 0, !15, i64 4}
!35 = !{!"iseq_insn_info", !9, i64 0, !9, i64 8, !15, i64 16, !9, i64 24}
!36 = !{!"", !5, i64 0, !5, i64 8, !5, i64 16, !9, i64 24}
!37 = !DILocation(line: 5, column: 1, scope: !38)
!38 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.<static-init>$153", scope: null, file: !2, line: 5, type: !39, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!39 = !DISubroutineType(types: !40)
!40 = !{!41}
!41 = !DIBasicType(name: "VALUE", size: 64, encoding: DW_ATE_signed)
!42 = !{!16, !16, i64 0}
!43 = !{!"branch_weights", i32 10000, i32 1}
!44 = !DILocation(line: 5, column: 1, scope: !45, inlinedAt: !46)
!45 = distinct !DISubprogram(name: "A.<static-init>", linkageName: "func_A.<static-init>L62", scope: null, file: !2, line: 5, type: !39, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!46 = distinct !DILocation(line: 5, column: 1, scope: !38)
!47 = !DILocation(line: 6, column: 3, scope: !45, inlinedAt: !46)
!48 = !DILocation(line: 9, column: 3, scope: !45, inlinedAt: !46)
!49 = !DILocation(line: 14, column: 5, scope: !38)
!50 = !DILocation(line: 15, column: 5, scope: !38)
!51 = !DILocation(line: 16, column: 6, scope: !38)
!52 = !DILocation(line: 16, column: 1, scope: !38)
!53 = !DILocation(line: 17, column: 9, scope: !38)
!54 = !DILocation(line: 17, column: 1, scope: !38)
!55 = !DILocation(line: 18, column: 6, scope: !38)
!56 = !DILocation(line: 18, column: 1, scope: !38)
!57 = !DILocation(line: 19, column: 6, scope: !38)
!58 = !DILocation(line: 19, column: 1, scope: !38)
!59 = distinct !DISubprogram(name: "A#write", linkageName: "func_A#write", scope: null, file: !2, line: 6, type: !39, scopeLine: 6, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!60 = !DILocation(line: 6, column: 3, scope: !59)
!61 = !{!"branch_weights", i32 4000000, i32 4001}
!62 = !DILocation(line: 6, column: 13, scope: !59)
!63 = !DILocation(line: 7, column: 10, scope: !59)
!64 = !DILocation(line: 7, column: 5, scope: !59)
!65 = distinct !DISubprogram(name: "A#read", linkageName: "func_A#read", scope: null, file: !2, line: 9, type: !39, scopeLine: 9, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!66 = !DILocation(line: 9, column: 3, scope: !65)
!67 = !{!"branch_weights", i32 2000, i32 1}
!68 = !DILocation(line: 10, column: 5, scope: !65)
