; ModuleID = 'payload'
source_filename = "llvm-link"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

%struct.rb_vm_struct = type { i64, %struct.rb_global_vm_lock_struct, %struct.rb_thread_struct*, %struct.rb_thread_struct*, i8*, i64, %union.pthread_mutex_t, %struct.list_head, %struct.list_head, %struct.list_head, %struct.list_head, i64, i32, i32, i8, i32, i64, [5 x i64], i64, i64, i64, i64, i64, i64, i64, %struct.st_table*, %struct.st_table*, %struct.anon.3, %struct.rb_hook_list_struct, %struct.st_table*, %struct.rb_postponed_job_struct*, i32, i32, %struct.list_head, %union.pthread_mutex_t, i64, i64, i64, i64, i64, i32, %struct.st_table*, %struct.rb_objspace*, %struct.rb_at_exit_list*, i64*, %struct.st_table*, %struct.rb_builtin_function*, i32, %struct.anon.4, [29 x i16] }
%struct.rb_global_vm_lock_struct = type { %struct.rb_thread_struct*, %union.pthread_mutex_t, %struct.list_head, %struct.rb_thread_struct*, i32, %union.pthread_cond_t, %union.pthread_cond_t, i32, i32 }
%union.pthread_cond_t = type { %struct.anon.2 }
%struct.anon.2 = type { i32, i32, i64, i64, i64, i8*, i32, i32 }
%struct.rb_thread_struct = type { %struct.list_node, i64, %struct.rb_vm_struct*, %struct.rb_execution_context_struct*, i64, %struct.rb_calling_info*, i64, i64, i64, i8, i8, i32, %struct.native_thread_data_struct, i8*, i64, i64, i64, i64, %union.pthread_mutex_t, %struct.rb_unblock_callback, i64, %struct.rb_mutex_struct*, %struct.rb_thread_list_struct*, %union.anon.7, i32, i64, %struct.rb_fiber_struct*, [5 x i8*], i64 }
%struct.list_node = type { %struct.list_node*, %struct.list_node* }
%struct.rb_execution_context_struct = type { i64*, i64, %struct.rb_control_frame_struct*, %struct.rb_vm_tag*, %struct.rb_vm_protect_tag*, i32, i32, %struct.rb_fiber_struct*, %struct.rb_thread_struct*, %struct.st_table*, i64, i64, i64*, i64, %struct.rb_ensure_list*, %struct.rb_trace_arg_struct*, i64, i64, i8, i8, i64, %struct.anon.5 }
%struct.rb_control_frame_struct = type { i64*, i64*, %struct.rb_iseq_struct*, i64, i64*, i8*, i64* }
%struct.rb_iseq_struct = type { i64, i64, %struct.rb_iseq_constant_body*, %union.anon.14 }
%struct.rb_iseq_constant_body = type { i32, i32, i64*, %struct.anon, %struct.rb_iseq_location_struct, %struct.iseq_insn_info, i64*, %struct.iseq_catch_table*, %struct.rb_iseq_struct*, %struct.rb_iseq_struct*, %union.iseq_inline_storage_entry*, %struct.rb_call_data*, %struct.anon.13, i32, i32, i32, i32, i32, i8, i64 }
%struct.anon = type { %struct.anon.0, i32, i32, i32, i32, i32, i32, i32, i64*, %struct.rb_iseq_param_keyword* }
%struct.anon.0 = type { i16, [2 x i8] }
%struct.rb_iseq_param_keyword = type { i32, i32, i32, i32, i64*, i64* }
%struct.rb_iseq_location_struct = type { i64, i64, i64, i64, i32, %struct.rb_code_location_struct }
%struct.rb_code_location_struct = type { %struct.rb_code_position_struct, %struct.rb_code_position_struct }
%struct.rb_code_position_struct = type { i32, i32 }
%struct.iseq_insn_info = type { %struct.iseq_insn_info_entry*, i32*, i32, %struct.succ_index_table* }
%struct.iseq_insn_info_entry = type opaque
%struct.succ_index_table = type opaque
%struct.iseq_catch_table = type opaque
%union.iseq_inline_storage_entry = type { %struct.iseq_inline_cache_entry }
%struct.iseq_inline_cache_entry = type { i64, %struct.rb_cref_struct*, i64 }
%struct.rb_cref_struct = type { i64, i64, i64, %struct.rb_cref_struct*, %struct.rb_scope_visi_struct }
%struct.rb_scope_visi_struct = type { i8, [3 x i8] }
%struct.rb_call_data = type { %struct.rb_call_cache, %struct.rb_call_info }
%struct.rb_call_cache = type { i64, [3 x i64], %struct.rb_callable_method_entry_struct*, i64, i64 (%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_calling_info*, %struct.rb_call_data*)*, %union.anon.12 }
%struct.rb_callable_method_entry_struct = type { i64, i64, %struct.rb_method_definition_struct*, i64, i64 }
%struct.rb_method_definition_struct = type { i64, %union.anon.10, i64, i64 }
%union.anon.10 = type { %struct.rb_method_cfunc_struct }
%struct.rb_method_cfunc_struct = type { i64 (...)*, i64 (i64, i32, i64*, i64 (...)*)*, i32 }
%union.anon.12 = type { i32 }
%struct.rb_call_info = type { i64, i32, i32 }
%struct.anon.13 = type { i64, i64, i64, i64* }
%union.anon.14 = type { %struct.anon.15 }
%struct.anon.15 = type { i64, i32 }
%struct.rb_vm_tag = type { i64, i64, [5 x i8*], %struct.rb_vm_tag*, i32 }
%struct.rb_vm_protect_tag = type { %struct.rb_vm_protect_tag* }
%struct.rb_ensure_list = type { %struct.rb_ensure_list*, %struct.rb_ensure_entry }
%struct.rb_ensure_entry = type { i64, i64 (i64)*, i64 }
%struct.rb_trace_arg_struct = type { i32, %struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, i64, i64, i64, i64, i64, i32, i32, i64 }
%struct.anon.5 = type { i64*, i64*, i64, [1 x %struct.__jmp_buf_tag] }
%struct.__jmp_buf_tag = type { [8 x i64], i32, %struct.__sigset_t }
%struct.__sigset_t = type { [16 x i64] }
%struct.rb_calling_info = type { i64, i64, i32, i32 }
%struct.native_thread_data_struct = type { %struct.list_head, %union.anon.6 }
%union.anon.6 = type { %union.pthread_cond_t }
%struct.rb_unblock_callback = type { void (i8*)*, i8* }
%struct.rb_mutex_struct = type opaque
%struct.rb_thread_list_struct = type { %struct.rb_thread_list_struct*, %struct.rb_thread_struct* }
%union.anon.7 = type { %struct.anon.8 }
%struct.anon.8 = type { i64, i64, i32 }
%struct.rb_fiber_struct = type opaque
%struct.anon.3 = type { [65 x i64] }
%struct.rb_hook_list_struct = type { %struct.rb_event_hook_struct*, i32, i32, i32 }
%struct.rb_event_hook_struct = type opaque
%struct.rb_postponed_job_struct = type opaque
%struct.list_head = type { %struct.list_node }
%union.pthread_mutex_t = type { %struct.__pthread_mutex_s }
%struct.__pthread_mutex_s = type { i32, i32, i32, i32, i32, i16, i16, %struct.__pthread_internal_list }
%struct.__pthread_internal_list = type { %struct.__pthread_internal_list*, %struct.__pthread_internal_list* }
%struct.rb_objspace = type opaque
%struct.rb_at_exit_list = type { void (%struct.rb_vm_struct*)*, %struct.rb_at_exit_list* }
%struct.st_table = type { i8, i8, i8, i32, %struct.st_hash_type*, i64, i64*, i64, i64, %struct.st_table_entry* }
%struct.st_hash_type = type { i32 (i64, i64)*, i64 (i64)* }
%struct.st_table_entry = type opaque
%struct.rb_builtin_function = type opaque
%struct.anon.4 = type { i64, i64, i64, i64 }
%struct.SorbetLineNumberInfo = type { i32, %struct.iseq_insn_info_entry*, i64* }
%struct.FunctionInlineCache = type { %struct.rb_kwarg_call_data }
%struct.rb_kwarg_call_data = type { %struct.rb_call_cache, %struct.rb_call_info_with_kwarg }
%struct.rb_call_info_with_kwarg = type { %struct.rb_call_info, %struct.rb_call_info_kw_arg* }
%struct.rb_call_info_kw_arg = type { i32, [1 x i64] }

@ruby_current_vm_ptr = external local_unnamed_addr global %struct.rb_vm_struct*, align 8
@ruby_current_execution_context_ptr = external local_unnamed_addr global %struct.rb_execution_context_struct*, align 8
@rb_eRuntimeError = external local_unnamed_addr global i64, align 8
@.str.9 = private unnamed_addr constant [95 x i8] c"sorbet_getBuildSCMRevision: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@.str.10 = private unnamed_addr constant [93 x i8] c"sorbet_getIsReleaseBuild: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@"stackFramePrecomputed_func_<root>.<static-init>$151" = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@"rubyIdPrecomputed_<top (required)>" = internal unnamed_addr global i64 0, align 8
@"str_<top (required)>" = private unnamed_addr constant [17 x i8] c"<top (required)>\00", align 1
@"rubyStrFrozen_<top (required)>" = internal unnamed_addr global i64 0, align 8
@"rubyStrFrozen_test/testdata/compiler/literal_hash.rb" = internal unnamed_addr global i64 0, align 8
@"str_test/testdata/compiler/literal_hash.rb" = private unnamed_addr constant [39 x i8] c"test/testdata/compiler/literal_hash.rb\00", align 1
@iseqEncodedArray = internal global [15 x i64] zeroinitializer
@fileLineNumberInfo = internal global %struct.SorbetLineNumberInfo zeroinitializer
@rubyStrFrozen_foo = internal unnamed_addr global i64 0, align 8
@str_foo = private unnamed_addr constant [4 x i8] c"foo\00", align 1
@rubyStrFrozen_bar = internal unnamed_addr global i64 0, align 8
@str_bar = private unnamed_addr constant [4 x i8] c"bar\00", align 1
@rubyStrFrozen_baz = internal unnamed_addr global i64 0, align 8
@str_baz = private unnamed_addr constant [4 x i8] c"baz\00", align 1
@rubyStrFrozen_quux = internal unnamed_addr global i64 0, align 8
@str_quux = private unnamed_addr constant [5 x i8] c"quux\00", align 1
@rubyStrFrozen_wat = internal unnamed_addr global i64 0, align 8
@str_wat = private unnamed_addr constant [4 x i8] c"wat\00", align 1
@rubyStrFrozen_how = internal unnamed_addr global i64 0, align 8
@str_how = private unnamed_addr constant [4 x i8] c"how\00", align 1
@rubyStrFrozen_unknown = internal unnamed_addr global i64 0, align 8
@str_unknown = private unnamed_addr constant [8 x i8] c"unknown\00", align 1
@rubyIdPrecomputed_do = internal unnamed_addr global i64 0, align 8
@str_do = private unnamed_addr constant [3 x i8] c"do\00", align 1
@rubyStrFrozen_magic = internal unnamed_addr global i64 0, align 8
@str_magic = private unnamed_addr constant [6 x i8] c"magic\00", align 1
@ruby_hashLiteral1 = internal unnamed_addr global i64 0, align 8
@str_one = private unnamed_addr constant [4 x i8] c"one\00", align 1
@ruby_hashLiteral2 = internal unnamed_addr global i64 0, align 8
@str_two = private unnamed_addr constant [4 x i8] c"two\00", align 1
@ruby_hashLiteral3 = internal unnamed_addr global i64 0, align 8
@str_true = private unnamed_addr constant [5 x i8] c"true\00", align 1
@ruby_hashLiteral4 = internal unnamed_addr global i64 0, align 8
@str_false = private unnamed_addr constant [6 x i8] c"false\00", align 1
@ruby_hashLiteral5 = internal unnamed_addr global i64 0, align 8
@str_nil = private unnamed_addr constant [4 x i8] c"nil\00", align 1
@ruby_hashLiteral6 = internal unnamed_addr global i64 0, align 8
@rubyIdPrecomputed_symbol = internal unnamed_addr global i64 0, align 8
@str_symbol = private unnamed_addr constant [7 x i8] c"symbol\00", align 1
@rubyStrFrozen_symbol = internal unnamed_addr global i64 0, align 8
@ruby_hashLiteral7 = internal unnamed_addr global i64 0, align 8
@ic_puts = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_puts = internal unnamed_addr global i64 0, align 8
@str_puts = private unnamed_addr constant [5 x i8] c"puts\00", align 1

declare i64 @rb_id2sym(i64) local_unnamed_addr #0

declare %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64, i64, i64, i64, %struct.rb_iseq_struct*, i32, i32, %struct.SorbetLineNumberInfo*, i64*, i32, i32) local_unnamed_addr #0

declare void @sorbet_initLineNumberInfo(%struct.SorbetLineNumberInfo*, i64*, i32) local_unnamed_addr #0

declare i64 @sorbet_readRealpath() local_unnamed_addr #0

declare void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache*, i64, i32, i32, i32, i64*) local_unnamed_addr #0

declare i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache*, i64) local_unnamed_addr #0

declare void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_iseq_struct*) local_unnamed_addr #0

declare i64 @sorbet_globalConstRegister(i64) local_unnamed_addr #0

declare i64 @sorbet_globalConstDupHash(i64) local_unnamed_addr #0

declare i64 @rb_intern2(i8*, i64) local_unnamed_addr #0

declare i64 @rb_hash_new_with_size(i64) local_unnamed_addr #0

declare void @rb_hash_bulk_insert(i64, i64*, i64) local_unnamed_addr #0

declare i64 @rb_fstring_new(i8*, i64) local_unnamed_addr #0

declare void @rb_gc_register_mark_object(i64) local_unnamed_addr #0

; Function Attrs: noreturn
declare void @rb_raise(i64, i8*, ...) local_unnamed_addr #1

; Function Attrs: nounwind ssp uwtable
define weak i32 @sorbet_getIsReleaseBuild() local_unnamed_addr #2 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !4
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* noundef getelementptr inbounds ([93 x i8], [93 x i8]* @.str.10, i64 0, i64 0)) #5
  unreachable
}

; Function Attrs: nounwind ssp uwtable
define weak i8* @sorbet_getBuildSCMRevision() local_unnamed_addr #2 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !4
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* noundef getelementptr inbounds ([95 x i8], [95 x i8]* @.str.9, i64 0, i64 0)) #5
  unreachable
}

; Function Attrs: sspreq
define void @Init_literal_hash() local_unnamed_addr #3 {
entry:
  %argArray.i1.i = alloca [2 x i64], align 8
  %argArray.i.i = alloca [14 x i64], align 8
  %locals.i.i = alloca i64, i32 0, align 8
  %realpath = tail call i64 @sorbet_readRealpath()
  %0 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 noundef 16) #6
  store i64 %0, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %1 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([3 x i8], [3 x i8]* @str_do, i64 0, i64 0), i64 noundef 2) #6
  store i64 %1, i64* @rubyIdPrecomputed_do, align 8
  %2 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([7 x i8], [7 x i8]* @str_symbol, i64 0, i64 0), i64 noundef 6) #6
  store i64 %2, i64* @rubyIdPrecomputed_symbol, align 8
  %3 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([5 x i8], [5 x i8]* @str_puts, i64 0, i64 0), i64 noundef 4) #6
  store i64 %3, i64* @rubyIdPrecomputed_puts, align 8
  %4 = tail call i64 @rb_fstring_new(i8* noundef getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 noundef 16) #6
  tail call void @rb_gc_register_mark_object(i64 %4) #6
  store i64 %4, i64* @"rubyStrFrozen_<top (required)>", align 8
  %5 = tail call i64 @rb_fstring_new(i8* noundef getelementptr inbounds ([39 x i8], [39 x i8]* @"str_test/testdata/compiler/literal_hash.rb", i64 0, i64 0), i64 noundef 38) #6
  tail call void @rb_gc_register_mark_object(i64 %5) #6
  store i64 %5, i64* @"rubyStrFrozen_test/testdata/compiler/literal_hash.rb", align 8
  tail call void @sorbet_initLineNumberInfo(%struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef getelementptr inbounds ([15 x i64], [15 x i64]* @iseqEncodedArray, i32 0, i32 0), i32 noundef 15)
  %"rubyId_<top (required)>.i.i" = load i64, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %"rubyStr_<top (required)>.i.i" = load i64, i64* @"rubyStrFrozen_<top (required)>", align 8
  %"rubyStr_test/testdata/compiler/literal_hash.rb.i.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/literal_hash.rb", align 8
  %6 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_<top (required)>.i.i", i64 %"rubyId_<top (required)>.i.i", i64 %"rubyStr_test/testdata/compiler/literal_hash.rb.i.i", i64 %realpath, %struct.rb_iseq_struct* noundef null, i32 noundef 0, i32 noundef 6, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef nonnull %locals.i.i, i32 noundef 0, i32 noundef 15)
  store %struct.rb_iseq_struct* %6, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_<root>.<static-init>$151", align 8
  %7 = call i64 @rb_fstring_new(i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @str_foo, i64 0, i64 0), i64 noundef 3) #6
  call void @rb_gc_register_mark_object(i64 %7) #6
  store i64 %7, i64* @rubyStrFrozen_foo, align 8
  %8 = call i64 @rb_fstring_new(i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @str_bar, i64 0, i64 0), i64 noundef 3) #6
  call void @rb_gc_register_mark_object(i64 %8) #6
  store i64 %8, i64* @rubyStrFrozen_bar, align 8
  %9 = call i64 @rb_fstring_new(i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @str_baz, i64 0, i64 0), i64 noundef 3) #6
  call void @rb_gc_register_mark_object(i64 %9) #6
  store i64 %9, i64* @rubyStrFrozen_baz, align 8
  %10 = call i64 @rb_fstring_new(i8* noundef getelementptr inbounds ([5 x i8], [5 x i8]* @str_quux, i64 0, i64 0), i64 noundef 4) #6
  call void @rb_gc_register_mark_object(i64 %10) #6
  store i64 %10, i64* @rubyStrFrozen_quux, align 8
  %11 = call i64 @rb_fstring_new(i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @str_wat, i64 0, i64 0), i64 noundef 3) #6
  call void @rb_gc_register_mark_object(i64 %11) #6
  store i64 %11, i64* @rubyStrFrozen_wat, align 8
  %12 = call i64 @rb_fstring_new(i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @str_how, i64 0, i64 0), i64 noundef 3) #6
  call void @rb_gc_register_mark_object(i64 %12) #6
  store i64 %12, i64* @rubyStrFrozen_how, align 8
  %13 = call i64 @rb_fstring_new(i8* noundef getelementptr inbounds ([8 x i8], [8 x i8]* @str_unknown, i64 0, i64 0), i64 noundef 7) #6
  call void @rb_gc_register_mark_object(i64 %13) #6
  store i64 %13, i64* @rubyStrFrozen_unknown, align 8
  %14 = call i64 @rb_fstring_new(i8* noundef getelementptr inbounds ([6 x i8], [6 x i8]* @str_magic, i64 0, i64 0), i64 noundef 5) #6
  call void @rb_gc_register_mark_object(i64 %14) #6
  store i64 %14, i64* @rubyStrFrozen_magic, align 8
  %15 = bitcast [14 x i64]* %argArray.i.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 112, i8* nonnull %15)
  %rubyStr_foo.i.i = load i64, i64* @rubyStrFrozen_foo, align 8
  %hashArgs0Addr.i.i = getelementptr [14 x i64], [14 x i64]* %argArray.i.i, i32 0, i64 0
  store i64 %rubyStr_foo.i.i, i64* %hashArgs0Addr.i.i, align 8
  %hashArgs1Addr.i.i = getelementptr [14 x i64], [14 x i64]* %argArray.i.i, i32 0, i64 1
  store i64 3, i64* %hashArgs1Addr.i.i, align 8
  %rubyStr_bar.i.i = load i64, i64* @rubyStrFrozen_bar, align 8
  %hashArgs2Addr.i.i = getelementptr [14 x i64], [14 x i64]* %argArray.i.i, i32 0, i64 2
  store i64 %rubyStr_bar.i.i, i64* %hashArgs2Addr.i.i, align 8
  %hashArgs3Addr.i.i = getelementptr [14 x i64], [14 x i64]* %argArray.i.i, i32 0, i64 3
  store i64 2, i64* %hashArgs3Addr.i.i, align 8
  %rubyStr_baz.i.i = load i64, i64* @rubyStrFrozen_baz, align 8
  %hashArgs4Addr.i.i = getelementptr [14 x i64], [14 x i64]* %argArray.i.i, i32 0, i64 4
  store i64 %rubyStr_baz.i.i, i64* %hashArgs4Addr.i.i, align 8
  %hashArgs5Addr.i.i = getelementptr [14 x i64], [14 x i64]* %argArray.i.i, i32 0, i64 5
  store i64 20, i64* %hashArgs5Addr.i.i, align 8
  %rubyStr_quux.i.i = load i64, i64* @rubyStrFrozen_quux, align 8
  %hashArgs6Addr.i.i = getelementptr [14 x i64], [14 x i64]* %argArray.i.i, i32 0, i64 6
  store i64 %rubyStr_quux.i.i, i64* %hashArgs6Addr.i.i, align 8
  %hashArgs7Addr.i.i = getelementptr [14 x i64], [14 x i64]* %argArray.i.i, i32 0, i64 7
  store i64 0, i64* %hashArgs7Addr.i.i, align 8
  %rubyStr_wat.i.i = load i64, i64* @rubyStrFrozen_wat, align 8
  %hashArgs8Addr.i.i = getelementptr [14 x i64], [14 x i64]* %argArray.i.i, i32 0, i64 8
  store i64 %rubyStr_wat.i.i, i64* %hashArgs8Addr.i.i, align 8
  %hashArgs9Addr.i.i = getelementptr [14 x i64], [14 x i64]* %argArray.i.i, i32 0, i64 9
  store i64 8, i64* %hashArgs9Addr.i.i, align 8
  %rubyStr_how.i.i = load i64, i64* @rubyStrFrozen_how, align 8
  %hashArgs10Addr.i.i = getelementptr [14 x i64], [14 x i64]* %argArray.i.i, i32 0, i64 10
  store i64 %rubyStr_how.i.i, i64* %hashArgs10Addr.i.i, align 8
  %rubyStr_unknown.i.i = load i64, i64* @rubyStrFrozen_unknown, align 8
  %hashArgs11Addr.i.i = getelementptr [14 x i64], [14 x i64]* %argArray.i.i, i32 0, i64 11
  store i64 %rubyStr_unknown.i.i, i64* %hashArgs11Addr.i.i, align 8
  %rubyId_do.i.i = load i64, i64* @rubyIdPrecomputed_do, align 8
  %rawSym.i.i = call i64 @rb_id2sym(i64 %rubyId_do.i.i)
  %hashArgs12Addr.i.i = getelementptr [14 x i64], [14 x i64]* %argArray.i.i, i32 0, i64 12
  store i64 %rawSym.i.i, i64* %hashArgs12Addr.i.i, align 8
  %rubyStr_magic.i.i = load i64, i64* @rubyStrFrozen_magic, align 8
  %hashArgs13Addr.i.i = getelementptr [14 x i64], [14 x i64]* %argArray.i.i, i32 0, i64 13
  store i64 %rubyStr_magic.i.i, i64* %hashArgs13Addr.i.i, align 8
  %16 = getelementptr [14 x i64], [14 x i64]* %argArray.i.i, i64 0, i64 0
  %17 = call i64 @rb_hash_new_with_size(i64 noundef 7) #6
  call void @rb_hash_bulk_insert(i64 noundef 14, i64* noundef nonnull %16, i64 %17) #6
  %18 = call i64 @sorbet_globalConstRegister(i64 %17) #6
  store i64 %18, i64* @ruby_hashLiteral1, align 8
  call void @llvm.lifetime.end.p0i8(i64 112, i8* nonnull %15)
  %19 = call i64 @rb_fstring_new(i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @str_one, i64 0, i64 0), i64 noundef 3) #6
  call void @rb_gc_register_mark_object(i64 %19) #6
  %20 = bitcast [2 x i64]* %argArray.i1.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 16, i8* nonnull %20)
  %hashArgs0Addr.i2.i = getelementptr [2 x i64], [2 x i64]* %argArray.i1.i, i32 0, i64 0
  store i64 3, i64* %hashArgs0Addr.i2.i, align 8
  %hashArgs1Addr.i3.i = getelementptr [2 x i64], [2 x i64]* %argArray.i1.i, i32 0, i64 1
  store i64 %19, i64* %hashArgs1Addr.i3.i, align 8
  %21 = getelementptr [2 x i64], [2 x i64]* %argArray.i1.i, i64 0, i64 0
  %22 = call i64 @rb_hash_new_with_size(i64 noundef 1) #6
  call void @rb_hash_bulk_insert(i64 noundef 2, i64* noundef nonnull %21, i64 %22) #6
  %23 = call i64 @sorbet_globalConstRegister(i64 %22) #6
  store i64 %23, i64* @ruby_hashLiteral2, align 8
  call void @llvm.lifetime.end.p0i8(i64 16, i8* nonnull %20)
  %24 = call i64 @rb_fstring_new(i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @str_two, i64 0, i64 0), i64 noundef 3) #6
  call void @rb_gc_register_mark_object(i64 %24) #6
  call void @llvm.lifetime.start.p0i8(i64 16, i8* nonnull %20)
  store i64 2, i64* %hashArgs0Addr.i2.i, align 8
  store i64 %24, i64* %hashArgs1Addr.i3.i, align 8
  %25 = call i64 @rb_hash_new_with_size(i64 noundef 1) #6
  call void @rb_hash_bulk_insert(i64 noundef 2, i64* noundef nonnull %21, i64 %25) #6
  %26 = call i64 @sorbet_globalConstRegister(i64 %25) #6
  store i64 %26, i64* @ruby_hashLiteral3, align 8
  call void @llvm.lifetime.end.p0i8(i64 16, i8* nonnull %20)
  %27 = call i64 @rb_fstring_new(i8* noundef getelementptr inbounds ([5 x i8], [5 x i8]* @str_true, i64 0, i64 0), i64 noundef 4) #6
  call void @rb_gc_register_mark_object(i64 %27) #6
  call void @llvm.lifetime.start.p0i8(i64 16, i8* nonnull %20)
  store i64 20, i64* %hashArgs0Addr.i2.i, align 8
  store i64 %27, i64* %hashArgs1Addr.i3.i, align 8
  %28 = call i64 @rb_hash_new_with_size(i64 noundef 1) #6
  call void @rb_hash_bulk_insert(i64 noundef 2, i64* noundef nonnull %21, i64 %28) #6
  %29 = call i64 @sorbet_globalConstRegister(i64 %28) #6
  store i64 %29, i64* @ruby_hashLiteral4, align 8
  call void @llvm.lifetime.end.p0i8(i64 16, i8* nonnull %20)
  %30 = call i64 @rb_fstring_new(i8* noundef getelementptr inbounds ([6 x i8], [6 x i8]* @str_false, i64 0, i64 0), i64 noundef 5) #6
  call void @rb_gc_register_mark_object(i64 %30) #6
  call void @llvm.lifetime.start.p0i8(i64 16, i8* nonnull %20)
  store i64 0, i64* %hashArgs0Addr.i2.i, align 8
  store i64 %30, i64* %hashArgs1Addr.i3.i, align 8
  %31 = call i64 @rb_hash_new_with_size(i64 noundef 1) #6
  call void @rb_hash_bulk_insert(i64 noundef 2, i64* noundef nonnull %21, i64 %31) #6
  %32 = call i64 @sorbet_globalConstRegister(i64 %31) #6
  store i64 %32, i64* @ruby_hashLiteral5, align 8
  call void @llvm.lifetime.end.p0i8(i64 16, i8* nonnull %20)
  %33 = call i64 @rb_fstring_new(i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @str_nil, i64 0, i64 0), i64 noundef 3) #6
  call void @rb_gc_register_mark_object(i64 %33) #6
  call void @llvm.lifetime.start.p0i8(i64 16, i8* nonnull %20)
  store i64 8, i64* %hashArgs0Addr.i2.i, align 8
  store i64 %33, i64* %hashArgs1Addr.i3.i, align 8
  %34 = call i64 @rb_hash_new_with_size(i64 noundef 1) #6
  call void @rb_hash_bulk_insert(i64 noundef 2, i64* noundef nonnull %21, i64 %34) #6
  %35 = call i64 @sorbet_globalConstRegister(i64 %34) #6
  store i64 %35, i64* @ruby_hashLiteral6, align 8
  call void @llvm.lifetime.end.p0i8(i64 16, i8* nonnull %20)
  %36 = call i64 @rb_fstring_new(i8* noundef getelementptr inbounds ([7 x i8], [7 x i8]* @str_symbol, i64 0, i64 0), i64 noundef 6) #6
  call void @rb_gc_register_mark_object(i64 %36) #6
  store i64 %36, i64* @rubyStrFrozen_symbol, align 8
  call void @llvm.lifetime.start.p0i8(i64 16, i8* nonnull %20)
  %rubyId_symbol.i.i = load i64, i64* @rubyIdPrecomputed_symbol, align 8
  %rawSym.i17.i = call i64 @rb_id2sym(i64 %rubyId_symbol.i.i)
  store i64 %rawSym.i17.i, i64* %hashArgs0Addr.i2.i, align 8
  %rubyStr_symbol.i.i = load i64, i64* @rubyStrFrozen_symbol, align 8
  store i64 %rubyStr_symbol.i.i, i64* %hashArgs1Addr.i3.i, align 8
  %37 = call i64 @rb_hash_new_with_size(i64 noundef 1) #6
  call void @rb_hash_bulk_insert(i64 noundef 2, i64* noundef nonnull %21, i64 %37) #6
  %38 = call i64 @sorbet_globalConstRegister(i64 %37) #6
  store i64 %38, i64* @ruby_hashLiteral7, align 8
  call void @llvm.lifetime.end.p0i8(i64 16, i8* nonnull %20)
  %rubyId_puts.i = load i64, i64* @rubyIdPrecomputed_puts, align 8, !dbg !8
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_puts, i64 %rubyId_puts.i, i32 noundef 20, i32 noundef 7, i32 noundef 0, i64* noundef null), !dbg !8
  %39 = load %struct.rb_vm_struct*, %struct.rb_vm_struct** @ruby_current_vm_ptr, align 8, !tbaa !13
  %40 = getelementptr inbounds %struct.rb_vm_struct, %struct.rb_vm_struct* %39, i64 0, i32 18
  %41 = load i64, i64* %40, align 8, !tbaa !15
  %42 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !13
  %43 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %42, i64 0, i32 2
  %44 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %43, align 8, !tbaa !25
  %stackFrame.i = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_<root>.<static-init>$151", align 8
  %45 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %44, i64 0, i32 2
  store %struct.rb_iseq_struct* %stackFrame.i, %struct.rb_iseq_struct** %45, align 8, !tbaa !28
  %46 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %44, i64 0, i32 4
  %47 = load i64*, i64** %46, align 8, !tbaa !30
  %48 = load i64, i64* %47, align 8, !tbaa !4
  %49 = and i64 %48, -33
  store i64 %49, i64* %47, align 8, !tbaa !4
  call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* %42, %struct.rb_control_frame_struct* %44, %struct.rb_iseq_struct* %stackFrame.i) #6
  %50 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %44, i64 0, i32 0
  store i64* getelementptr inbounds ([15 x i64], [15 x i64]* @iseqEncodedArray, i64 0, i64 6), i64** %50, align 8, !dbg !31, !tbaa !13
  %rubyId_do.i = load i64, i64* @rubyIdPrecomputed_do, align 8, !dbg !32
  %rawSym.i = call i64 @rb_id2sym(i64 %rubyId_do.i) #6, !dbg !32
  %hashLiteral.i = load i64, i64* @ruby_hashLiteral1, align 8, !dbg !33
  %duplicatedHash.i = call i64 @sorbet_globalConstDupHash(i64 %hashLiteral.i) #6, !dbg !33
  store i64* getelementptr inbounds ([15 x i64], [15 x i64]* @iseqEncodedArray, i64 0, i64 8), i64** %50, align 8, !dbg !33, !tbaa !13
  %hashLiteral81.i = load i64, i64* @ruby_hashLiteral2, align 8, !dbg !34
  %duplicatedHash82.i = call i64 @sorbet_globalConstDupHash(i64 %hashLiteral81.i) #6, !dbg !34
  store i64* getelementptr inbounds ([15 x i64], [15 x i64]* @iseqEncodedArray, i64 0, i64 9), i64** %50, align 8, !dbg !34, !tbaa !13
  %hashLiteral88.i = load i64, i64* @ruby_hashLiteral3, align 8, !dbg !35
  %duplicatedHash89.i = call i64 @sorbet_globalConstDupHash(i64 %hashLiteral88.i) #6, !dbg !35
  store i64* getelementptr inbounds ([15 x i64], [15 x i64]* @iseqEncodedArray, i64 0, i64 10), i64** %50, align 8, !dbg !35, !tbaa !13
  %hashLiteral95.i = load i64, i64* @ruby_hashLiteral4, align 8, !dbg !36
  %duplicatedHash96.i = call i64 @sorbet_globalConstDupHash(i64 %hashLiteral95.i) #6, !dbg !36
  store i64* getelementptr inbounds ([15 x i64], [15 x i64]* @iseqEncodedArray, i64 0, i64 11), i64** %50, align 8, !dbg !36, !tbaa !13
  %hashLiteral102.i = load i64, i64* @ruby_hashLiteral5, align 8, !dbg !37
  %duplicatedHash103.i = call i64 @sorbet_globalConstDupHash(i64 %hashLiteral102.i) #6, !dbg !37
  store i64* getelementptr inbounds ([15 x i64], [15 x i64]* @iseqEncodedArray, i64 0, i64 12), i64** %50, align 8, !dbg !37, !tbaa !13
  %hashLiteral109.i = load i64, i64* @ruby_hashLiteral6, align 8, !dbg !38
  %duplicatedHash110.i = call i64 @sorbet_globalConstDupHash(i64 %hashLiteral109.i) #6, !dbg !38
  store i64* getelementptr inbounds ([15 x i64], [15 x i64]* @iseqEncodedArray, i64 0, i64 13), i64** %50, align 8, !dbg !38, !tbaa !13
  %rubyId_symbol.i = load i64, i64* @rubyIdPrecomputed_symbol, align 8, !dbg !39
  %rawSym111.i = call i64 @rb_id2sym(i64 %rubyId_symbol.i) #6, !dbg !39
  %hashLiteral116.i = load i64, i64* @ruby_hashLiteral7, align 8, !dbg !40
  %duplicatedHash117.i = call i64 @sorbet_globalConstDupHash(i64 %hashLiteral116.i) #6, !dbg !40
  store i64* getelementptr inbounds ([15 x i64], [15 x i64]* @iseqEncodedArray, i64 0, i64 14), i64** %50, align 8, !dbg !40, !tbaa !13
  %51 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %44, i64 0, i32 1, !dbg !8
  %52 = load i64*, i64** %51, align 8, !dbg !8
  store i64 %41, i64* %52, align 8, !dbg !8, !tbaa !4
  %53 = getelementptr inbounds i64, i64* %52, i64 1, !dbg !8
  store i64 %duplicatedHash.i, i64* %53, align 8, !dbg !8, !tbaa !4
  %54 = getelementptr inbounds i64, i64* %53, i64 1, !dbg !8
  store i64 %duplicatedHash82.i, i64* %54, align 8, !dbg !8, !tbaa !4
  %55 = getelementptr inbounds i64, i64* %54, i64 1, !dbg !8
  store i64 %duplicatedHash89.i, i64* %55, align 8, !dbg !8, !tbaa !4
  %56 = getelementptr inbounds i64, i64* %55, i64 1, !dbg !8
  store i64 %duplicatedHash96.i, i64* %56, align 8, !dbg !8, !tbaa !4
  %57 = getelementptr inbounds i64, i64* %56, i64 1, !dbg !8
  store i64 %duplicatedHash103.i, i64* %57, align 8, !dbg !8, !tbaa !4
  %58 = getelementptr inbounds i64, i64* %57, i64 1, !dbg !8
  store i64 %duplicatedHash110.i, i64* %58, align 8, !dbg !8, !tbaa !4
  %59 = getelementptr inbounds i64, i64* %58, i64 1, !dbg !8
  store i64 %duplicatedHash117.i, i64* %59, align 8, !dbg !8, !tbaa !4
  %60 = getelementptr inbounds i64, i64* %59, i64 1, !dbg !8
  store i64* %60, i64** %51, align 8, !dbg !8
  %send = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_puts, i64 0), !dbg !8
  ret void
}

; Function Attrs: argmemonly nofree nosync nounwind willreturn
declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #4

; Function Attrs: argmemonly nofree nosync nounwind willreturn
declare void @llvm.lifetime.end.p0i8(i64 immarg, i8* nocapture) #4

attributes #0 = { "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #1 = { noreturn "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #2 = { nounwind ssp uwtable "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #3 = { sspreq }
attributes #4 = { argmemonly nofree nosync nounwind willreturn }
attributes #5 = { noreturn nounwind }
attributes #6 = { nounwind }

!llvm.module.flags = !{!0}
!llvm.dbg.cu = !{!1}

!0 = !{i32 2, !"Debug Info Version", i32 3}
!1 = distinct !DICompileUnit(language: DW_LANG_C, file: !2, producer: "Sorbet LLVM", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, enums: !3)
!2 = !DIFile(filename: "test/testdata/compiler/literal_hash.rb", directory: ".")
!3 = !{}
!4 = !{!5, !5, i64 0}
!5 = !{!"long", !6, i64 0}
!6 = !{!"omnipotent char", !7, i64 0}
!7 = !{!"Simple C/C++ TBAA"}
!8 = !DILocation(line: 14, column: 1, scope: !9)
!9 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.<static-init>$151", scope: null, file: !2, line: 6, type: !10, scopeLine: 6, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!10 = !DISubroutineType(types: !11)
!11 = !{!12}
!12 = !DIBasicType(name: "VALUE", size: 64, encoding: DW_ATE_signed)
!13 = !{!14, !14, i64 0}
!14 = !{!"any pointer", !6, i64 0}
!15 = !{!16, !5, i64 400}
!16 = !{!"rb_vm_struct", !5, i64 0, !17, i64 8, !14, i64 192, !14, i64 200, !14, i64 208, !21, i64 216, !6, i64 224, !18, i64 264, !18, i64 280, !18, i64 296, !18, i64 312, !5, i64 328, !20, i64 336, !20, i64 340, !20, i64 344, !20, i64 344, !20, i64 344, !20, i64 344, !20, i64 348, !5, i64 352, !6, i64 360, !5, i64 400, !5, i64 408, !5, i64 416, !5, i64 424, !5, i64 432, !5, i64 440, !5, i64 448, !14, i64 456, !14, i64 464, !22, i64 472, !23, i64 992, !14, i64 1016, !14, i64 1024, !20, i64 1032, !20, i64 1036, !18, i64 1040, !6, i64 1056, !5, i64 1096, !5, i64 1104, !5, i64 1112, !5, i64 1120, !5, i64 1128, !20, i64 1136, !14, i64 1144, !14, i64 1152, !14, i64 1160, !14, i64 1168, !14, i64 1176, !14, i64 1184, !20, i64 1192, !24, i64 1200, !6, i64 1232}
!17 = !{!"rb_global_vm_lock_struct", !14, i64 0, !6, i64 8, !18, i64 48, !14, i64 64, !20, i64 72, !6, i64 80, !6, i64 128, !20, i64 176, !20, i64 180}
!18 = !{!"list_head", !19, i64 0}
!19 = !{!"list_node", !14, i64 0, !14, i64 8}
!20 = !{!"int", !6, i64 0}
!21 = !{!"long long", !6, i64 0}
!22 = !{!"", !6, i64 0}
!23 = !{!"rb_hook_list_struct", !14, i64 0, !20, i64 8, !20, i64 12, !20, i64 16}
!24 = !{!"", !5, i64 0, !5, i64 8, !5, i64 16, !5, i64 24}
!25 = !{!26, !14, i64 16}
!26 = !{!"rb_execution_context_struct", !14, i64 0, !5, i64 8, !14, i64 16, !14, i64 24, !14, i64 32, !20, i64 40, !20, i64 44, !14, i64 48, !14, i64 56, !14, i64 64, !5, i64 72, !5, i64 80, !14, i64 88, !5, i64 96, !14, i64 104, !14, i64 112, !5, i64 120, !5, i64 128, !6, i64 136, !6, i64 137, !5, i64 144, !27, i64 152}
!27 = !{!"", !14, i64 0, !14, i64 8, !5, i64 16, !6, i64 24}
!28 = !{!29, !14, i64 16}
!29 = !{!"rb_control_frame_struct", !14, i64 0, !14, i64 8, !14, i64 16, !5, i64 24, !14, i64 32, !14, i64 40, !14, i64 48}
!30 = !{!29, !14, i64 32}
!31 = !DILocation(line: 0, scope: !9)
!32 = !DILocation(line: 6, column: 99, scope: !9)
!33 = !DILocation(line: 6, column: 5, scope: !9)
!34 = !DILocation(line: 8, column: 5, scope: !9)
!35 = !DILocation(line: 9, column: 5, scope: !9)
!36 = !DILocation(line: 10, column: 5, scope: !9)
!37 = !DILocation(line: 11, column: 5, scope: !9)
!38 = !DILocation(line: 12, column: 5, scope: !9)
!39 = !DILocation(line: 13, column: 7, scope: !9)
!40 = !DILocation(line: 13, column: 5, scope: !9)
