; ModuleID = 'payload'
source_filename = "llvm-link"
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"

%struct.rb_vm_struct = type { i64, %struct.rb_global_vm_lock_struct, %struct.rb_thread_struct*, %struct.rb_thread_struct*, i8*, i64, %union.pthread_mutex_t, %struct.list_head, %struct.list_head, %struct.list_head, %struct.list_head, i64, i32, i8, i32, i64, [5 x i64], i64, i64, i64, i64, i64, i64, i64, %struct.st_table*, %struct.st_table*, %struct.anon.3, %struct.rb_hook_list_struct, %struct.st_table*, %struct.rb_postponed_job_struct*, i32, i32, %struct.list_head, %union.pthread_mutex_t, i64, i64, i64, i64, i64, i32, i64, %struct.rb_objspace*, %struct.rb_at_exit_list*, i64*, %struct.st_table*, %struct.anon.4, [28 x i16] }
%struct.rb_global_vm_lock_struct = type { %struct.rb_thread_struct*, %union.pthread_mutex_t, %struct.list_head, %struct.rb_thread_struct*, i32, %union.pthread_cond_t, %union.pthread_cond_t, i32, i32 }
%union.pthread_cond_t = type { %struct.anon.2 }
%struct.anon.2 = type { i32, i32, i64, i64, i64, i8*, i32, i32 }
%struct.rb_thread_struct = type { %struct.list_node, i64, %struct.rb_vm_struct*, %struct.rb_execution_context_struct*, i64, %struct.rb_calling_info*, i64, i64, i64, i8, i8, i32, %struct.native_thread_data_struct, i8*, i64, i64, i64, i64, %union.pthread_mutex_t, %struct.rb_unblock_callback, i64, %struct.rb_mutex_struct*, %struct.rb_thread_list_struct*, %union.anon.8, i32, i64, %struct.rb_fiber_struct*, [1 x %struct.__jmp_buf_tag], i64 }
%struct.list_node = type { %struct.list_node*, %struct.list_node* }
%struct.rb_execution_context_struct = type { i64*, i64, %struct.rb_control_frame_struct*, %struct.rb_vm_tag*, %struct.rb_vm_protect_tag*, i32, i32, %struct.rb_fiber_struct*, %struct.rb_thread_struct*, %struct.st_table*, i64, i64, i64*, i64, %struct.rb_ensure_list*, %struct.rb_trace_arg_struct*, i64, i64, i8, i8, i64, %struct.anon.5 }
%struct.rb_control_frame_struct = type { i64*, i64*, %struct.rb_iseq_struct*, i64, i64*, i8*, i64* }
%struct.rb_iseq_struct = type { i64, i64, %struct.rb_iseq_constant_body*, %union.anon.14 }
%struct.rb_iseq_constant_body = type { i32, i32, i64*, %struct.anon, %struct.rb_iseq_location_struct, %struct.iseq_insn_info, i64*, %struct.iseq_catch_table*, %struct.rb_iseq_struct*, %struct.rb_iseq_struct*, %union.iseq_inline_storage_entry*, %struct.rb_call_info*, %struct.rb_call_cache*, %struct.anon.13, i32, i32, i32, i32, i32, i64 (%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*)*, i64, %struct.rb_mjit_unit*, i8 }
%struct.anon = type { %struct.anon.0, i32, i32, i32, i32, i32, i32, i32, i64*, %struct.rb_iseq_param_keyword* }
%struct.anon.0 = type { i8, [3 x i8] }
%struct.rb_iseq_param_keyword = type { i32, i32, i32, i32, i64*, i64* }
%struct.rb_iseq_location_struct = type { i64, i64, i64, i64, i32, %struct.rb_code_location_struct }
%struct.rb_code_location_struct = type { %struct.rb_code_position_struct, %struct.rb_code_position_struct }
%struct.rb_code_position_struct = type { i32, i32 }
%struct.iseq_insn_info = type { %struct.iseq_insn_info_entry*, i32*, i32, %struct.succ_index_table* }
%struct.iseq_insn_info_entry = type opaque
%struct.succ_index_table = type opaque
%struct.iseq_catch_table = type opaque
%union.iseq_inline_storage_entry = type { %struct.iseq_inline_cache_entry }
%struct.iseq_inline_cache_entry = type { i64, %struct.rb_cref_struct*, %union.anon.11 }
%struct.rb_cref_struct = type { i64, i64, i64, %struct.rb_cref_struct*, %struct.anon.0 }
%union.anon.11 = type { i64 }
%struct.rb_call_info = type { i64, i32, i32 }
%struct.rb_call_cache = type { i64, i64, %struct.rb_callable_method_entry_struct*, i64 (%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_calling_info*, %struct.rb_call_info*, %struct.rb_call_cache*)*, %union.anon.12 }
%struct.rb_callable_method_entry_struct = type { i64, i64, %struct.rb_method_definition_struct*, i64, i64 }
%struct.rb_method_definition_struct = type { i64, %union.anon, i64 }
%union.anon = type { %struct.rb_method_cfunc_struct }
%struct.rb_method_cfunc_struct = type { i64 (...)*, i64 (i64 (...)*, i64, i32, i64*)*, i32 }
%union.anon.12 = type { i32 }
%struct.anon.13 = type { i64, i64, i64, i64* }
%struct.rb_mjit_unit = type opaque
%union.anon.14 = type { %struct.anon.15 }
%struct.anon.15 = type { i64, i32 }
%struct.rb_vm_tag = type { i64, i64, [1 x %struct.__jmp_buf_tag], %struct.rb_vm_tag*, i32 }
%struct.rb_vm_protect_tag = type { %struct.rb_vm_protect_tag* }
%struct.rb_ensure_list = type { %struct.rb_ensure_list*, %struct.rb_ensure_entry }
%struct.rb_ensure_entry = type { i64, i64 (...)*, i64 }
%struct.rb_trace_arg_struct = type { i32, %struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, i64, i64, i64, i64, i64, i32, i32, i64 }
%struct.anon.5 = type { i64*, i64*, i64, [1 x %struct.__jmp_buf_tag] }
%struct.rb_calling_info = type { i64, i64, i32 }
%struct.native_thread_data_struct = type { %struct.list_head, %union.anon.7 }
%union.anon.7 = type { %union.pthread_cond_t }
%struct.rb_unblock_callback = type { void (i8*)*, i8* }
%struct.rb_mutex_struct = type opaque
%struct.rb_thread_list_struct = type { %struct.rb_thread_list_struct*, %struct.rb_thread_struct* }
%union.anon.8 = type { %struct.anon.9 }
%struct.anon.9 = type { i64, i64 }
%struct.rb_fiber_struct = type opaque
%struct.__jmp_buf_tag = type { [8 x i64], i32, %struct.__sigset_t }
%struct.__sigset_t = type { [16 x i64] }
%struct.anon.3 = type { [65 x i64], [65 x i8] }
%struct.rb_hook_list_struct = type { %struct.rb_event_hook_struct*, i32, i32, i32 }
%struct.rb_event_hook_struct = type opaque
%struct.rb_postponed_job_struct = type opaque
%struct.list_head = type { %struct.list_node }
%union.pthread_mutex_t = type { %struct.__pthread_mutex_s }
%struct.__pthread_mutex_s = type { i32, i32, i32, i32, i32, i16, i16, %struct.__pthread_internal_list }
%struct.__pthread_internal_list = type { %struct.__pthread_internal_list*, %struct.__pthread_internal_list* }
%struct.rb_objspace = type opaque
%struct.rb_at_exit_list = type { void (%struct.rb_vm_struct*)*, %struct.rb_at_exit_list* }
%struct.st_table = type { i8, i8, i8, i32, %struct.st_hash_type*, i64, i64*, i64, i64, %struct.st_table_entry* }
%struct.st_hash_type = type { i32 (...)*, i64 (...)* }
%struct.st_table_entry = type opaque
%struct.anon.4 = type { i64, i64, i64, i64 }
%struct.FunctionInlineCache = type { %struct.rb_callable_method_entry_struct*, i64, i64 }
%struct.sorbet_iterMethodArg = type { i64, i64, i32, i64*, i32, %struct.FunctionInlineCache* }

@ruby_current_vm_ptr = external local_unnamed_addr global %struct.rb_vm_struct*, align 8
@ruby_current_execution_context_ptr = external local_unnamed_addr global %struct.rb_execution_context_struct*, align 8
@rb_eRuntimeError = external local_unnamed_addr global i64, align 8
@.str.6 = private unnamed_addr constant [95 x i8] c"sorbet_getBuildSCMRevision: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@.str.7 = private unnamed_addr constant [93 x i8] c"sorbet_getIsReleaseBuild: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@"stackFramePrecomputed_func_Object#foo" = internal unnamed_addr global i8* null, align 8
@rubyIdPrecomputed_foo = internal unnamed_addr global i64 0, align 8
@str_foo = private unnamed_addr constant [4 x i8] c"foo\00", align 1
@rubyStrFrozen_foo = internal unnamed_addr global i64 0, align 8
@"rubyStrFrozen_test/testdata/compiler/method_with_block.rb" = internal unnamed_addr global i64 0, align 8
@"str_test/testdata/compiler/method_with_block.rb" = private unnamed_addr constant [44 x i8] c"test/testdata/compiler/method_with_block.rb\00", align 1
@rubyIdPrecomputed_call = internal unnamed_addr global i64 0, align 8
@str_call = private unnamed_addr constant [5 x i8] c"call\00", align 1
@ic_callFunc_call = internal global %struct.FunctionInlineCache zeroinitializer
@"stackFramePrecomputed_func_Object#boo" = internal unnamed_addr global i8* null, align 8
@rubyIdPrecomputed_boo = internal unnamed_addr global i64 0, align 8
@str_boo = private unnamed_addr constant [4 x i8] c"boo\00", align 1
@ic_callFunc_call.1 = internal global %struct.FunctionInlineCache zeroinitializer
@"stackFramePrecomputed_func_Object#bar" = internal unnamed_addr global i8* null, align 8
@rubyIdPrecomputed_bar = internal unnamed_addr global i64 0, align 8
@str_bar = private unnamed_addr constant [4 x i8] c"bar\00", align 1
@rubyStrFrozen_bar = internal unnamed_addr global i64 0, align 8
@rubyIdPrecomputed_to_proc = internal unnamed_addr global i64 0, align 8
@str_to_proc = private unnamed_addr constant [8 x i8] c"to_proc\00", align 1
@ic_callFunc_to_proc = internal global %struct.FunctionInlineCache zeroinitializer
@ic_callWithProcfoo = internal global %struct.FunctionInlineCache zeroinitializer
@"stackFramePrecomputed_func_Object#baz" = internal unnamed_addr global i8* null, align 8
@rubyIdPrecomputed_baz = internal unnamed_addr global i64 0, align 8
@str_baz = private unnamed_addr constant [4 x i8] c"baz\00", align 1
@rubyStrFrozen_baz = internal unnamed_addr global i64 0, align 8
@ic_callFunc_call.2 = internal global %struct.FunctionInlineCache zeroinitializer
@"stackFramePrecomputed_func_<root>.<static-init>$153" = internal unnamed_addr global i8* null, align 8
@"rubyIdPrecomputed_<top (required)>" = internal unnamed_addr global i64 0, align 8
@"str_<top (required)>" = private unnamed_addr constant [17 x i8] c"<top (required)>\00", align 1
@"<static-init-locals-storage>" = internal global [2 x i64] zeroinitializer
@"rubyIdPrecomputed_<self>" = internal unnamed_addr global i64 0, align 8
@"str_<self>" = private unnamed_addr constant [7 x i8] c"<self>\00", align 1
@"rubyIdPrecomputed_<block-call>" = internal unnamed_addr global i64 0, align 8
@"str_<block-call>" = private unnamed_addr constant [13 x i8] c"<block-call>\00", align 1
@"stackFramePrecomputed_func_<root>.<static-init>$153$block_1" = internal unnamed_addr global i8* null, align 8
@"rubyIdPrecomputed_block for" = internal unnamed_addr global i64 0, align 8
@"str_block for" = private unnamed_addr constant [10 x i8] c"block for\00", align 1
@"rubyStrFrozen_block for" = internal unnamed_addr global i64 0, align 8
@"stackFramePrecomputed_func_<root>.<static-init>$153$block_2" = internal unnamed_addr global i8* null, align 8
@"stackFramePrecomputed_func_<root>.<static-init>$153$block_3" = internal unnamed_addr global i8* null, align 8
@"stackFramePrecomputed_func_<root>.<static-init>$153$block_4" = internal unnamed_addr global i8* null, align 8
@str_keep_def = private unnamed_addr constant [9 x i8] c"keep_def\00", align 1
@ic_callFuncWithBlock_foo = internal global %struct.FunctionInlineCache zeroinitializer
@rubyStrFrozen_heey = internal unnamed_addr global i64 0, align 8
@str_heey = private unnamed_addr constant [5 x i8] c"heey\00", align 1
@rubyIdPrecomputed_puts = internal unnamed_addr global i64 0, align 8
@str_puts = private unnamed_addr constant [5 x i8] c"puts\00", align 1
@ic_callFunc_puts = internal global %struct.FunctionInlineCache zeroinitializer
@ic_callFuncWithBlock_boo = internal global %struct.FunctionInlineCache zeroinitializer
@rubyStrFrozen_boohey = internal unnamed_addr global i64 0, align 8
@str_boohey = private unnamed_addr constant [7 x i8] c"boohey\00", align 1
@ic_callFunc_puts.6 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_callFuncWithBlock_bar = internal global %struct.FunctionInlineCache zeroinitializer
@ic_callFunc_puts.7 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_callFuncWithBlock_baz = internal global %struct.FunctionInlineCache zeroinitializer
@rb_cObject = external local_unnamed_addr constant i64

; Function Attrs: noreturn
declare void @sorbet_raiseArity(i32, i32, i32) local_unnamed_addr #0

declare i8* @sorbet_allocateRubyStackFrame(i64, i64, i64, i64, i8*, i32, i32, i32, i64*, i32) local_unnamed_addr #1

declare i64 @sorbet_readRealpath() local_unnamed_addr #1

declare void @sorbet_vm_env_write_slowpath(i64*, i32, i64) local_unnamed_addr #1

declare i64 @sorbet_callFuncWithCache(i64, i64, i32, i64* nocapture, i32, %struct.FunctionInlineCache*) local_unnamed_addr #1

declare void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_iseq_struct*) local_unnamed_addr #1

declare i32 @rb_block_given_p() local_unnamed_addr #1

declare i64 @rb_block_proc() local_unnamed_addr #1

declare void @rb_define_method(i64, i8*, i64 (...)*, i32) local_unnamed_addr #1

declare i64 @rb_intern2(i8*, i64) local_unnamed_addr #1

declare i64 @rb_id2sym(i64) local_unnamed_addr #1

declare void @rb_ary_detransient(i64) local_unnamed_addr #1

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #2

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.end.p0i8(i64 immarg, i8* nocapture) #2

declare i64 @rb_fstring_new(i8*, i64) local_unnamed_addr #1

declare void @rb_gc_register_mark_object(i64) local_unnamed_addr #1

; Function Attrs: noreturn
declare void @rb_raise(i64, i8*, ...) local_unnamed_addr #0

; Function Attrs: nounwind ssp uwtable
define internal i64 @sorbet_iterMethod(i64) #3 {
  %2 = inttoptr i64 %0 to %struct.sorbet_iterMethodArg*
  %3 = getelementptr inbounds %struct.sorbet_iterMethodArg, %struct.sorbet_iterMethodArg* %2, i64 0, i32 0
  %4 = load i64, i64* %3, align 8, !tbaa !4
  %5 = getelementptr inbounds %struct.sorbet_iterMethodArg, %struct.sorbet_iterMethodArg* %2, i64 0, i32 1
  %6 = load i64, i64* %5, align 8, !tbaa !11
  %7 = getelementptr inbounds %struct.sorbet_iterMethodArg, %struct.sorbet_iterMethodArg* %2, i64 0, i32 2
  %8 = load i32, i32* %7, align 8, !tbaa !12
  %9 = getelementptr inbounds %struct.sorbet_iterMethodArg, %struct.sorbet_iterMethodArg* %2, i64 0, i32 3
  %10 = load i64*, i64** %9, align 8, !tbaa !13
  %11 = getelementptr inbounds %struct.sorbet_iterMethodArg, %struct.sorbet_iterMethodArg* %2, i64 0, i32 4
  %12 = load i32, i32* %11, align 8, !tbaa !14
  %13 = getelementptr inbounds %struct.sorbet_iterMethodArg, %struct.sorbet_iterMethodArg* %2, i64 0, i32 5
  %14 = load %struct.FunctionInlineCache*, %struct.FunctionInlineCache** %13, align 8, !tbaa !15
  %15 = tail call i64 @sorbet_callFuncWithCache(i64 %4, i64 %6, i32 %8, i64* nocapture %10, i32 %12, %struct.FunctionInlineCache* %14) #8
  ret i64 %15
}

declare i64 @rb_iterate(i64 (i64)*, i64, i64 (...)*, i64) local_unnamed_addr #1

; Function Attrs: nounwind ssp uwtable
define weak i32 @sorbet_getIsReleaseBuild() local_unnamed_addr #3 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !16
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* getelementptr inbounds ([93 x i8], [93 x i8]* @.str.7, i64 0, i64 0)) #9
  unreachable
}

; Function Attrs: nounwind ssp uwtable
define weak i8* @sorbet_getBuildSCMRevision() local_unnamed_addr #3 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !16
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* getelementptr inbounds ([95 x i8], [95 x i8]* @.str.6, i64 0, i64 0)) #9
  unreachable
}

; Function Attrs: nounwind sspreq uwtable
define i64 @"func_Object#foo"(i32 %argc, i64* nocapture readnone %argArray, i64 %selfRaw) #4 !dbg !17 {
functionEntryInitializers:
  %"stackFrame_func_Object#foo" = load i8*, i8** @"stackFramePrecomputed_func_Object#foo", align 8
  %0 = bitcast i8* %"stackFrame_func_Object#foo" to %struct.rb_iseq_struct*
  %1 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !21
  %2 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %1, i64 0, i32 2
  %3 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %2, align 8, !tbaa !22
  %4 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 2
  %5 = bitcast %struct.rb_iseq_struct** %4 to i8**
  store i8* %"stackFrame_func_Object#foo", i8** %5, align 8, !tbaa !25
  %6 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 4
  %7 = load i64*, i64** %6, align 8, !tbaa !27
  %8 = load i64, i64* %7, align 8, !tbaa !16
  %9 = and i64 %8, -129
  store i64 %9, i64* %7, align 8, !tbaa !16
  tail call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* %1, %struct.rb_control_frame_struct* nonnull %3, %struct.rb_iseq_struct* %0) #8
  %10 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 0
  %11 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %4, align 8, !tbaa !25
  %12 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %11, i64 0, i32 2
  %13 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %12, align 8, !tbaa !28
  %14 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %13, i64 0, i32 2
  %15 = load i64*, i64** %14, align 8, !tbaa !30
  %16 = getelementptr inbounds i64, i64* %15, i64 1
  store i64* %16, i64** %10, align 8, !tbaa !21
  %tooManyArgs = icmp eq i32 %argc, 0, !dbg !39
  br i1 %tooManyArgs, label %fillRequiredArgs, label %argCountFailBlock, !dbg !39, !prof !40

argCountFailBlock:                                ; preds = %functionEntryInitializers
  tail call void @sorbet_raiseArity(i32 %argc, i32 0, i32 0) #8, !dbg !39
  unreachable, !dbg !39

fillRequiredArgs:                                 ; preds = %functionEntryInitializers
  %17 = tail call i32 @rb_block_given_p() #8, !dbg !39
  %18 = icmp eq i32 %17, 0, !dbg !39
  br i1 %18, label %sorbet_getMethodBlockAsProc.exit, label %19, !dbg !39

19:                                               ; preds = %fillRequiredArgs
  %20 = tail call i64 @rb_block_proc() #8, !dbg !39
  br label %sorbet_getMethodBlockAsProc.exit, !dbg !39

sorbet_getMethodBlockAsProc.exit:                 ; preds = %fillRequiredArgs, %19
  %21 = phi i64 [ %20, %19 ], [ 8, %fillRequiredArgs ], !dbg !39
  %22 = getelementptr inbounds i64, i64* %15, i64 2
  store i64* %22, i64** %10, align 8, !tbaa !21
  %rubyId_call = load i64, i64* @rubyIdPrecomputed_call, align 8, !dbg !41
  %callFunc_call = tail call i64 @sorbet_callFuncWithCache(i64 %21, i64 %rubyId_call, i32 0, i64* null, i32 0, %struct.FunctionInlineCache* nonnull @ic_callFunc_call) #8, !dbg !41
  ret i64 %callFunc_call
}

; Function Attrs: nounwind sspreq uwtable
define i64 @"func_Object#boo"(i32 %argc, i64* nocapture readnone %argArray, i64 %selfRaw) #4 !dbg !42 {
functionEntryInitializers:
  %"stackFrame_func_Object#boo" = load i8*, i8** @"stackFramePrecomputed_func_Object#boo", align 8
  %0 = bitcast i8* %"stackFrame_func_Object#boo" to %struct.rb_iseq_struct*
  %1 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !21
  %2 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %1, i64 0, i32 2
  %3 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %2, align 8, !tbaa !22
  %4 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 2
  %5 = bitcast %struct.rb_iseq_struct** %4 to i8**
  store i8* %"stackFrame_func_Object#boo", i8** %5, align 8, !tbaa !25
  %6 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 4
  %7 = load i64*, i64** %6, align 8, !tbaa !27
  %8 = load i64, i64* %7, align 8, !tbaa !16
  %9 = and i64 %8, -129
  store i64 %9, i64* %7, align 8, !tbaa !16
  tail call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* %1, %struct.rb_control_frame_struct* nonnull %3, %struct.rb_iseq_struct* %0) #8
  %10 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 0
  %11 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %4, align 8, !tbaa !25
  %12 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %11, i64 0, i32 2
  %13 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %12, align 8, !tbaa !28
  %14 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %13, i64 0, i32 2
  %15 = load i64*, i64** %14, align 8, !tbaa !30
  %16 = getelementptr inbounds i64, i64* %15, i64 1
  store i64* %16, i64** %10, align 8, !tbaa !21
  %tooManyArgs = icmp eq i32 %argc, 0, !dbg !43
  br i1 %tooManyArgs, label %fillRequiredArgs, label %argCountFailBlock, !dbg !43, !prof !40

argCountFailBlock:                                ; preds = %functionEntryInitializers
  tail call void @sorbet_raiseArity(i32 %argc, i32 0, i32 0) #8, !dbg !43
  unreachable, !dbg !43

fillRequiredArgs:                                 ; preds = %functionEntryInitializers
  %17 = tail call i32 @rb_block_given_p() #8, !dbg !43
  %18 = icmp eq i32 %17, 0, !dbg !43
  br i1 %18, label %sorbet_getMethodBlockAsProc.exit, label %19, !dbg !43

19:                                               ; preds = %fillRequiredArgs
  %20 = tail call i64 @rb_block_proc() #8, !dbg !43
  br label %sorbet_getMethodBlockAsProc.exit, !dbg !43

sorbet_getMethodBlockAsProc.exit:                 ; preds = %fillRequiredArgs, %19
  %21 = phi i64 [ %20, %19 ], [ 8, %fillRequiredArgs ], !dbg !43
  %22 = getelementptr inbounds i64, i64* %15, i64 2, !dbg !44
  store i64* %22, i64** %10, align 8, !dbg !44, !tbaa !21
  %rubyId_call = load i64, i64* @rubyIdPrecomputed_call, align 8, !dbg !45
  %callFunc_call = tail call i64 @sorbet_callFuncWithCache(i64 %21, i64 %rubyId_call, i32 0, i64* null, i32 0, %struct.FunctionInlineCache* nonnull @ic_callFunc_call.1) #8, !dbg !45
  ret i64 %callFunc_call
}

; Function Attrs: nounwind sspreq uwtable
define i64 @"func_Object#bar"(i32 %argc, i64* nocapture readnone %argArray, i64 %selfRaw) #4 !dbg !46 {
functionEntryInitializers:
  %"stackFrame_func_Object#bar" = load i8*, i8** @"stackFramePrecomputed_func_Object#bar", align 8
  %0 = bitcast i8* %"stackFrame_func_Object#bar" to %struct.rb_iseq_struct*
  %1 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !21
  %2 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %1, i64 0, i32 2
  %3 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %2, align 8, !tbaa !22
  %4 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 2
  %5 = bitcast %struct.rb_iseq_struct** %4 to i8**
  store i8* %"stackFrame_func_Object#bar", i8** %5, align 8, !tbaa !25
  %6 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 4
  %7 = load i64*, i64** %6, align 8, !tbaa !27
  %8 = load i64, i64* %7, align 8, !tbaa !16
  %9 = and i64 %8, -129
  store i64 %9, i64* %7, align 8, !tbaa !16
  tail call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* %1, %struct.rb_control_frame_struct* nonnull %3, %struct.rb_iseq_struct* %0) #8
  %10 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 0
  %11 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %4, align 8, !tbaa !25
  %12 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %11, i64 0, i32 2
  %13 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %12, align 8, !tbaa !28
  %14 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %13, i64 0, i32 2
  %15 = load i64*, i64** %14, align 8, !tbaa !30
  %16 = getelementptr inbounds i64, i64* %15, i64 1
  store i64* %16, i64** %10, align 8, !tbaa !21
  %tooManyArgs = icmp eq i32 %argc, 0, !dbg !47
  br i1 %tooManyArgs, label %fillRequiredArgs, label %argCountFailBlock, !dbg !47, !prof !40

argCountFailBlock:                                ; preds = %functionEntryInitializers
  tail call void @sorbet_raiseArity(i32 %argc, i32 0, i32 0) #8, !dbg !47
  unreachable, !dbg !47

fillRequiredArgs:                                 ; preds = %functionEntryInitializers
  %17 = tail call i32 @rb_block_given_p() #8, !dbg !47
  %18 = icmp eq i32 %17, 0, !dbg !47
  br i1 %18, label %sorbet_getMethodBlockAsProc.exit, label %19, !dbg !47

19:                                               ; preds = %fillRequiredArgs
  %20 = tail call i64 @rb_block_proc() #8, !dbg !47
  br label %sorbet_getMethodBlockAsProc.exit, !dbg !47

sorbet_getMethodBlockAsProc.exit:                 ; preds = %fillRequiredArgs, %19
  %21 = phi i64 [ %20, %19 ], [ 8, %fillRequiredArgs ], !dbg !47
  %22 = getelementptr inbounds i64, i64* %15, i64 2, !dbg !48
  store i64* %22, i64** %10, align 8, !dbg !48, !tbaa !21
  %rubyId_foo = load i64, i64* @rubyIdPrecomputed_foo, align 8, !dbg !49
  %rawSym = tail call i64 @rb_id2sym(i64 %rubyId_foo) #8, !dbg !49
  %rubyId_foo8 = load i64, i64* @rubyIdPrecomputed_foo, align 8, !dbg !49
  %rubyId_to_proc = load i64, i64* @rubyIdPrecomputed_to_proc, align 8, !dbg !49
  %callFunc_to_proc = tail call i64 @sorbet_callFuncWithCache(i64 %21, i64 %rubyId_to_proc, i32 0, i64* null, i32 0, %struct.FunctionInlineCache* nonnull @ic_callFunc_to_proc) #8, !dbg !49
  %23 = icmp eq i64 %callFunc_to_proc, 8, !dbg !49
  br i1 %23, label %sorbet_callFuncProcWithCache.exit, label %24, !dbg !49

24:                                               ; preds = %sorbet_getMethodBlockAsProc.exit
  %25 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !49, !tbaa !21
  %26 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %25, i64 0, i32 17, !dbg !49
  store i64 %callFunc_to_proc, i64* %26, align 8, !dbg !49, !tbaa !50, !noalias !51
  br label %sorbet_callFuncProcWithCache.exit, !dbg !49

sorbet_callFuncProcWithCache.exit:                ; preds = %sorbet_getMethodBlockAsProc.exit, %24
  %27 = tail call i64 @sorbet_callFuncWithCache(i64 %selfRaw, i64 %rubyId_foo8, i32 0, i64* nocapture null, i32 0, %struct.FunctionInlineCache* nonnull @ic_callWithProcfoo) #8, !dbg !49
  ret i64 %27
}

; Function Attrs: nounwind sspreq uwtable
define i64 @"func_Object#baz"(i32 %argc, i64* nocapture readnone %argArray, i64 %selfRaw) #4 !dbg !54 {
functionEntryInitializers:
  %callArgs = alloca [1 x i64], align 8
  %"stackFrame_func_Object#baz" = load i8*, i8** @"stackFramePrecomputed_func_Object#baz", align 8
  %0 = bitcast i8* %"stackFrame_func_Object#baz" to %struct.rb_iseq_struct*
  %1 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !21
  %2 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %1, i64 0, i32 2
  %3 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %2, align 8, !tbaa !22
  %4 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 2
  %5 = bitcast %struct.rb_iseq_struct** %4 to i8**
  store i8* %"stackFrame_func_Object#baz", i8** %5, align 8, !tbaa !25
  %6 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 4
  %7 = load i64*, i64** %6, align 8, !tbaa !27
  %8 = load i64, i64* %7, align 8, !tbaa !16
  %9 = and i64 %8, -129
  store i64 %9, i64* %7, align 8, !tbaa !16
  tail call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* %1, %struct.rb_control_frame_struct* nonnull %3, %struct.rb_iseq_struct* %0) #8
  %10 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %3, i64 0, i32 0
  %11 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %4, align 8, !tbaa !25
  %12 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %11, i64 0, i32 2
  %13 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %12, align 8, !tbaa !28
  %14 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %13, i64 0, i32 2
  %15 = load i64*, i64** %14, align 8, !tbaa !30
  %16 = getelementptr inbounds i64, i64* %15, i64 1
  store i64* %16, i64** %10, align 8, !tbaa !21
  %tooManyArgs = icmp eq i32 %argc, 0, !dbg !55
  br i1 %tooManyArgs, label %fillRequiredArgs, label %argCountFailBlock, !dbg !55, !prof !40

argCountFailBlock:                                ; preds = %functionEntryInitializers
  tail call void @sorbet_raiseArity(i32 %argc, i32 0, i32 0) #8, !dbg !55
  unreachable, !dbg !55

fillRequiredArgs:                                 ; preds = %functionEntryInitializers
  %17 = tail call i32 @rb_block_given_p() #8, !dbg !55
  %18 = icmp eq i32 %17, 0, !dbg !55
  br i1 %18, label %sorbet_getMethodBlockAsProc.exit, label %19, !dbg !55

19:                                               ; preds = %fillRequiredArgs
  %20 = tail call i64 @rb_block_proc() #8, !dbg !55
  br label %sorbet_getMethodBlockAsProc.exit, !dbg !55

sorbet_getMethodBlockAsProc.exit:                 ; preds = %fillRequiredArgs, %19
  %21 = phi i64 [ %20, %19 ], [ 8, %fillRequiredArgs ], !dbg !55
  %22 = getelementptr inbounds i64, i64* %15, i64 2, !dbg !56
  store i64* %22, i64** %10, align 8, !dbg !56, !tbaa !21
  %rubyStr_baz = load i64, i64* @rubyStrFrozen_baz, align 8, !dbg !57
  %callArgs0Addr = getelementptr inbounds [1 x i64], [1 x i64]* %callArgs, i64 0, i64 0, !dbg !58
  store i64 %rubyStr_baz, i64* %callArgs0Addr, align 8, !dbg !58
  %rubyId_call = load i64, i64* @rubyIdPrecomputed_call, align 8, !dbg !58
  %callFunc_call = call i64 @sorbet_callFuncWithCache(i64 %21, i64 %rubyId_call, i32 1, i64* nonnull %callArgs0Addr, i32 0, %struct.FunctionInlineCache* nonnull @ic_callFunc_call.2) #8, !dbg !58
  ret i64 %callFunc_call
}

; Function Attrs: ssp
define internal i64 @"func_<root>.<static-init>$153$block_1"(i64 %firstYieldArgRaw, i64 %localsOffset, i32 %argc, i64* nocapture readonly %argArray, i64 %blockArg) #5 !dbg !59 {
functionEntryInitializers:
  %callArgs = alloca [2 x i64], align 8
  %"stackFrame_func_<root>.<static-init>$153$block_112" = load i64, i64* bitcast (i8** @"stackFramePrecomputed_func_<root>.<static-init>$153$block_1" to i64*), align 8
  %0 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !21
  %1 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %0, i64 0, i32 2
  %2 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %1, align 8, !tbaa !22
  %3 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 2
  %4 = bitcast %struct.rb_iseq_struct** %3 to i64*
  store i64 %"stackFrame_func_<root>.<static-init>$153$block_112", i64* %4, align 8, !tbaa !25
  %5 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 4
  %6 = load i64*, i64** %5, align 8, !tbaa !27
  %7 = load i64, i64* %6, align 8, !tbaa !16
  %8 = and i64 %7, -129
  store i64 %8, i64* %6, align 8, !tbaa !16
  %9 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 0
  %10 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %3, align 8, !tbaa !25
  %11 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %10, i64 0, i32 2
  %12 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %11, align 8, !tbaa !28
  %13 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %12, i64 0, i32 2
  %14 = load i64*, i64** %13, align 8, !tbaa !30
  %15 = getelementptr inbounds i64, i64* %14, i64 5
  store i64* %15, i64** %9, align 8, !tbaa !21
  %arrayExpansionSizeGuard = icmp eq i32 %argc, 1, !dbg !61
  br i1 %arrayExpansionSizeGuard, label %argArrayExpandArrayTest, label %.preheader.i, !dbg !61

argArrayExpandArrayTest:                          ; preds = %functionEntryInitializers
  %arg1_maybeExpandToFullArgs = load i64, i64* %argArray, align 8, !dbg !61
  %16 = and i64 %arg1_maybeExpandToFullArgs, 7, !dbg !61
  %17 = icmp ne i64 %16, 0, !dbg !61
  %18 = and i64 %arg1_maybeExpandToFullArgs, -9, !dbg !61
  %19 = icmp eq i64 %18, 0, !dbg !61
  %20 = or i1 %17, %19, !dbg !61
  br i1 %20, label %.preheader.i, label %sorbet_isa_Array.exit, !dbg !61

sorbet_isa_Array.exit:                            ; preds = %argArrayExpandArrayTest
  %21 = inttoptr i64 %arg1_maybeExpandToFullArgs to %struct.anon.9*, !dbg !61
  %22 = getelementptr inbounds %struct.anon.9, %struct.anon.9* %21, i64 0, i32 0, !dbg !61
  %23 = load i64, i64* %22, align 8, !dbg !61, !tbaa !62
  %24 = and i64 %23, 33554463, !dbg !61
  %25 = icmp eq i64 %24, 33554439, !dbg !61
  br i1 %25, label %26, label %.preheader.i, !dbg !61

26:                                               ; preds = %sorbet_isa_Array.exit
  tail call void @rb_ary_detransient(i64 %arg1_maybeExpandToFullArgs) #8, !dbg !61
  br label %.preheader.i, !dbg !61

.preheader.i:                                     ; preds = %sorbet_isa_Array.exit, %functionEntryInitializers, %26, %argArrayExpandArrayTest
  %27 = getelementptr inbounds i64, i64* %14, i64 22, !dbg !64
  store i64* %27, i64** %9, align 8, !dbg !64, !tbaa !21
  %rubyStr_heey = load i64, i64* @rubyStrFrozen_heey, align 8, !dbg !65
  %callArgs0Addr = getelementptr inbounds [2 x i64], [2 x i64]* %callArgs, i64 0, i64 0, !dbg !66
  store i64 %rubyStr_heey, i64* %callArgs0Addr, align 8, !dbg !66
  %28 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !66, !tbaa !21
  %29 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %28, i64 0, i32 2, !dbg !66
  %30 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %29, align 8, !dbg !66, !tbaa !22
  %31 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %30, i64 0, i32 4, !dbg !66
  %32 = load i64*, i64** %31, align 8, !dbg !66, !tbaa !27
  %33 = getelementptr inbounds i64, i64* %32, i64 -1, !dbg !66
  %34 = load i64, i64* %33, align 8, !dbg !66, !tbaa !16
  %35 = and i64 %34, -4, !dbg !66
  %36 = inttoptr i64 %35 to i64*, !dbg !66
  %37 = shl i64 %localsOffset, 32, !dbg !66
  %38 = add i64 %37, 12884901888, !dbg !66
  %39 = ashr exact i64 %38, 32, !dbg !66
  %40 = sub nsw i64 0, %39, !dbg !66
  %41 = getelementptr inbounds i64, i64* %36, i64 %40, !dbg !66
  %42 = load i64, i64* %41, align 8, !dbg !66, !tbaa !16
  %rubyId_puts = load i64, i64* @rubyIdPrecomputed_puts, align 8, !dbg !66
  %callFunc_puts = call i64 @sorbet_callFuncWithCache(i64 %42, i64 %rubyId_puts, i32 1, i64* nonnull %callArgs0Addr, i32 0, %struct.FunctionInlineCache* nonnull @ic_callFunc_puts), !dbg !66
  %43 = getelementptr inbounds i64, i64* %14, i64 21, !dbg !66
  store i64* %43, i64** %9, align 8, !dbg !66, !tbaa !21
  ret i64 %callFunc_puts, !dbg !64
}

; Function Attrs: ssp
define internal i64 @"func_<root>.<static-init>$153$block_2"(i64 %firstYieldArgRaw, i64 %localsOffset, i32 %argc, i64* nocapture readonly %argArray, i64 %blockArg) #5 !dbg !67 {
functionEntryInitializers:
  %callArgs = alloca [2 x i64], align 8
  %"stackFrame_func_<root>.<static-init>$153$block_212" = load i64, i64* bitcast (i8** @"stackFramePrecomputed_func_<root>.<static-init>$153$block_2" to i64*), align 8
  %0 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !21
  %1 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %0, i64 0, i32 2
  %2 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %1, align 8, !tbaa !22
  %3 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 2
  %4 = bitcast %struct.rb_iseq_struct** %3 to i64*
  store i64 %"stackFrame_func_<root>.<static-init>$153$block_212", i64* %4, align 8, !tbaa !25
  %5 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 4
  %6 = load i64*, i64** %5, align 8, !tbaa !27
  %7 = load i64, i64* %6, align 8, !tbaa !16
  %8 = and i64 %7, -129
  store i64 %8, i64* %6, align 8, !tbaa !16
  %9 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 0
  %10 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %3, align 8, !tbaa !25
  %11 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %10, i64 0, i32 2
  %12 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %11, align 8, !tbaa !28
  %13 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %12, i64 0, i32 2
  %14 = load i64*, i64** %13, align 8, !tbaa !30
  %15 = getelementptr inbounds i64, i64* %14, i64 5
  store i64* %15, i64** %9, align 8, !tbaa !21
  %arrayExpansionSizeGuard = icmp eq i32 %argc, 1, !dbg !68
  br i1 %arrayExpansionSizeGuard, label %argArrayExpandArrayTest, label %.preheader.i, !dbg !68

argArrayExpandArrayTest:                          ; preds = %functionEntryInitializers
  %arg1_maybeExpandToFullArgs = load i64, i64* %argArray, align 8, !dbg !68
  %16 = and i64 %arg1_maybeExpandToFullArgs, 7, !dbg !68
  %17 = icmp ne i64 %16, 0, !dbg !68
  %18 = and i64 %arg1_maybeExpandToFullArgs, -9, !dbg !68
  %19 = icmp eq i64 %18, 0, !dbg !68
  %20 = or i1 %17, %19, !dbg !68
  br i1 %20, label %.preheader.i, label %sorbet_isa_Array.exit, !dbg !68

sorbet_isa_Array.exit:                            ; preds = %argArrayExpandArrayTest
  %21 = inttoptr i64 %arg1_maybeExpandToFullArgs to %struct.anon.9*, !dbg !68
  %22 = getelementptr inbounds %struct.anon.9, %struct.anon.9* %21, i64 0, i32 0, !dbg !68
  %23 = load i64, i64* %22, align 8, !dbg !68, !tbaa !62
  %24 = and i64 %23, 33554463, !dbg !68
  %25 = icmp eq i64 %24, 33554439, !dbg !68
  br i1 %25, label %26, label %.preheader.i, !dbg !68

26:                                               ; preds = %sorbet_isa_Array.exit
  tail call void @rb_ary_detransient(i64 %arg1_maybeExpandToFullArgs) #8, !dbg !68
  br label %.preheader.i, !dbg !68

.preheader.i:                                     ; preds = %sorbet_isa_Array.exit, %functionEntryInitializers, %26, %argArrayExpandArrayTest
  %27 = getelementptr inbounds i64, i64* %14, i64 26, !dbg !69
  store i64* %27, i64** %9, align 8, !dbg !69, !tbaa !21
  %rubyStr_boohey = load i64, i64* @rubyStrFrozen_boohey, align 8, !dbg !70
  %callArgs0Addr = getelementptr inbounds [2 x i64], [2 x i64]* %callArgs, i64 0, i64 0, !dbg !71
  store i64 %rubyStr_boohey, i64* %callArgs0Addr, align 8, !dbg !71
  %28 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !71, !tbaa !21
  %29 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %28, i64 0, i32 2, !dbg !71
  %30 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %29, align 8, !dbg !71, !tbaa !22
  %31 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %30, i64 0, i32 4, !dbg !71
  %32 = load i64*, i64** %31, align 8, !dbg !71, !tbaa !27
  %33 = getelementptr inbounds i64, i64* %32, i64 -1, !dbg !71
  %34 = load i64, i64* %33, align 8, !dbg !71, !tbaa !16
  %35 = and i64 %34, -4, !dbg !71
  %36 = inttoptr i64 %35 to i64*, !dbg !71
  %37 = shl i64 %localsOffset, 32, !dbg !71
  %38 = add i64 %37, 12884901888, !dbg !71
  %39 = ashr exact i64 %38, 32, !dbg !71
  %40 = sub nsw i64 0, %39, !dbg !71
  %41 = getelementptr inbounds i64, i64* %36, i64 %40, !dbg !71
  %42 = load i64, i64* %41, align 8, !dbg !71, !tbaa !16
  %rubyId_puts = load i64, i64* @rubyIdPrecomputed_puts, align 8, !dbg !71
  %callFunc_puts = call i64 @sorbet_callFuncWithCache(i64 %42, i64 %rubyId_puts, i32 1, i64* nonnull %callArgs0Addr, i32 0, %struct.FunctionInlineCache* nonnull @ic_callFunc_puts.6), !dbg !71
  %43 = getelementptr inbounds i64, i64* %14, i64 25, !dbg !71
  store i64* %43, i64** %9, align 8, !dbg !71, !tbaa !21
  ret i64 %callFunc_puts, !dbg !69
}

; Function Attrs: ssp
define internal i64 @"func_<root>.<static-init>$153$block_3"(i64 %firstYieldArgRaw, i64 %localsOffset, i32 %argc, i64* nocapture readonly %argArray, i64 %blockArg) #5 !dbg !72 {
functionEntryInitializers:
  %callArgs = alloca [2 x i64], align 8
  %"stackFrame_func_<root>.<static-init>$153$block_312" = load i64, i64* bitcast (i8** @"stackFramePrecomputed_func_<root>.<static-init>$153$block_3" to i64*), align 8
  %0 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !21
  %1 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %0, i64 0, i32 2
  %2 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %1, align 8, !tbaa !22
  %3 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 2
  %4 = bitcast %struct.rb_iseq_struct** %3 to i64*
  store i64 %"stackFrame_func_<root>.<static-init>$153$block_312", i64* %4, align 8, !tbaa !25
  %5 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 4
  %6 = load i64*, i64** %5, align 8, !tbaa !27
  %7 = load i64, i64* %6, align 8, !tbaa !16
  %8 = and i64 %7, -129
  store i64 %8, i64* %6, align 8, !tbaa !16
  %9 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 0
  %10 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %3, align 8, !tbaa !25
  %11 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %10, i64 0, i32 2
  %12 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %11, align 8, !tbaa !28
  %13 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %12, i64 0, i32 2
  %14 = load i64*, i64** %13, align 8, !tbaa !30
  %15 = getelementptr inbounds i64, i64* %14, i64 5
  store i64* %15, i64** %9, align 8, !tbaa !21
  %arrayExpansionSizeGuard = icmp eq i32 %argc, 1, !dbg !73
  br i1 %arrayExpansionSizeGuard, label %argArrayExpandArrayTest, label %.preheader.i, !dbg !73

argArrayExpandArrayTest:                          ; preds = %functionEntryInitializers
  %arg1_maybeExpandToFullArgs = load i64, i64* %argArray, align 8, !dbg !73
  %16 = and i64 %arg1_maybeExpandToFullArgs, 7, !dbg !73
  %17 = icmp ne i64 %16, 0, !dbg !73
  %18 = and i64 %arg1_maybeExpandToFullArgs, -9, !dbg !73
  %19 = icmp eq i64 %18, 0, !dbg !73
  %20 = or i1 %17, %19, !dbg !73
  br i1 %20, label %.preheader.i, label %sorbet_isa_Array.exit, !dbg !73

sorbet_isa_Array.exit:                            ; preds = %argArrayExpandArrayTest
  %21 = inttoptr i64 %arg1_maybeExpandToFullArgs to %struct.anon.9*, !dbg !73
  %22 = getelementptr inbounds %struct.anon.9, %struct.anon.9* %21, i64 0, i32 0, !dbg !73
  %23 = load i64, i64* %22, align 8, !dbg !73, !tbaa !62
  %24 = and i64 %23, 33554463, !dbg !73
  %25 = icmp eq i64 %24, 33554439, !dbg !73
  br i1 %25, label %26, label %.preheader.i, !dbg !73

26:                                               ; preds = %sorbet_isa_Array.exit
  tail call void @rb_ary_detransient(i64 %arg1_maybeExpandToFullArgs) #8, !dbg !73
  br label %.preheader.i, !dbg !73

.preheader.i:                                     ; preds = %sorbet_isa_Array.exit, %functionEntryInitializers, %26, %argArrayExpandArrayTest
  %27 = getelementptr inbounds i64, i64* %14, i64 30, !dbg !74
  store i64* %27, i64** %9, align 8, !dbg !74, !tbaa !21
  %rubyStr_bar = load i64, i64* @rubyStrFrozen_bar, align 8, !dbg !75
  %callArgs0Addr = getelementptr inbounds [2 x i64], [2 x i64]* %callArgs, i64 0, i64 0, !dbg !76
  store i64 %rubyStr_bar, i64* %callArgs0Addr, align 8, !dbg !76
  %28 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !76, !tbaa !21
  %29 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %28, i64 0, i32 2, !dbg !76
  %30 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %29, align 8, !dbg !76, !tbaa !22
  %31 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %30, i64 0, i32 4, !dbg !76
  %32 = load i64*, i64** %31, align 8, !dbg !76, !tbaa !27
  %33 = getelementptr inbounds i64, i64* %32, i64 -1, !dbg !76
  %34 = load i64, i64* %33, align 8, !dbg !76, !tbaa !16
  %35 = and i64 %34, -4, !dbg !76
  %36 = inttoptr i64 %35 to i64*, !dbg !76
  %37 = shl i64 %localsOffset, 32, !dbg !76
  %38 = add i64 %37, 12884901888, !dbg !76
  %39 = ashr exact i64 %38, 32, !dbg !76
  %40 = sub nsw i64 0, %39, !dbg !76
  %41 = getelementptr inbounds i64, i64* %36, i64 %40, !dbg !76
  %42 = load i64, i64* %41, align 8, !dbg !76, !tbaa !16
  %rubyId_puts = load i64, i64* @rubyIdPrecomputed_puts, align 8, !dbg !76
  %callFunc_puts = call i64 @sorbet_callFuncWithCache(i64 %42, i64 %rubyId_puts, i32 1, i64* nonnull %callArgs0Addr, i32 0, %struct.FunctionInlineCache* nonnull @ic_callFunc_puts.7), !dbg !76
  %43 = getelementptr inbounds i64, i64* %14, i64 29, !dbg !76
  store i64* %43, i64** %9, align 8, !dbg !76, !tbaa !21
  ret i64 %callFunc_puts, !dbg !74
}

; Function Attrs: nounwind ssp
define internal i64 @"func_<root>.<static-init>$153$block_4"(i64 %firstYieldArgRaw, i64 %localsOffset, i32 %argc, i64* nocapture readonly %argArray, i64 %blockArg) #6 !dbg !77 {
functionEntryInitializers:
  %"stackFrame_func_<root>.<static-init>$153$block_46" = load i64, i64* bitcast (i8** @"stackFramePrecomputed_func_<root>.<static-init>$153$block_4" to i64*), align 8
  %0 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !21
  %1 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %0, i64 0, i32 2
  %2 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %1, align 8, !tbaa !22
  %3 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 2
  %4 = bitcast %struct.rb_iseq_struct** %3 to i64*
  store i64 %"stackFrame_func_<root>.<static-init>$153$block_46", i64* %4, align 8, !tbaa !25
  %5 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 4
  %6 = load i64*, i64** %5, align 8, !tbaa !27
  %7 = load i64, i64* %6, align 8, !tbaa !16
  %8 = and i64 %7, -129
  store i64 %8, i64* %6, align 8, !tbaa !16
  %9 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 0
  %10 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %3, align 8, !tbaa !25
  %11 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %10, i64 0, i32 2
  %12 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %11, align 8, !tbaa !28
  %13 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %12, i64 0, i32 2
  %14 = load i64*, i64** %13, align 8, !tbaa !30
  %15 = getelementptr inbounds i64, i64* %14, i64 5
  store i64* %15, i64** %9, align 8, !tbaa !21
  %arrayExpansionSizeGuard = icmp eq i32 %argc, 1, !dbg !78
  br i1 %arrayExpansionSizeGuard, label %argArrayExpandArrayTest, label %fillRequiredArgs, !dbg !78

argArrayExpandArrayTest:                          ; preds = %functionEntryInitializers
  %arg1_maybeExpandToFullArgs = load i64, i64* %argArray, align 8, !dbg !78
  %16 = and i64 %arg1_maybeExpandToFullArgs, 7, !dbg !78
  %17 = icmp ne i64 %16, 0, !dbg !78
  %18 = and i64 %arg1_maybeExpandToFullArgs, -9, !dbg !78
  %19 = icmp eq i64 %18, 0, !dbg !78
  %20 = or i1 %17, %19, !dbg !78
  br i1 %20, label %fillRequiredArgs, label %sorbet_isa_Array.exit, !dbg !78

sorbet_isa_Array.exit:                            ; preds = %argArrayExpandArrayTest
  %21 = inttoptr i64 %arg1_maybeExpandToFullArgs to %struct.anon.9*, !dbg !78
  %22 = getelementptr inbounds %struct.anon.9, %struct.anon.9* %21, i64 0, i32 0, !dbg !78
  %23 = load i64, i64* %22, align 8, !dbg !78, !tbaa !62
  %24 = and i64 %23, 33554463, !dbg !78
  %25 = icmp eq i64 %24, 33554439, !dbg !78
  br i1 %25, label %26, label %fillRequiredArgs, !dbg !78

26:                                               ; preds = %sorbet_isa_Array.exit
  tail call void @rb_ary_detransient(i64 %arg1_maybeExpandToFullArgs) #8, !dbg !78
  br label %fillRequiredArgs, !dbg !78

fillRequiredArgs:                                 ; preds = %sorbet_isa_Array.exit, %argArrayExpandArrayTest, %26, %functionEntryInitializers
  %27 = getelementptr inbounds i64, i64* %14, i64 33
  store i64* %27, i64** %9, align 8, !tbaa !21
  ret i64 8, !dbg !79
}

; Function Attrs: sspreq
define void @Init_method_with_block() local_unnamed_addr #7 {
entry:
  %locals1.i.i = alloca [0 x i64], align 8
  %0 = alloca %struct.sorbet_iterMethodArg, align 8
  %1 = alloca %struct.sorbet_iterMethodArg, align 8
  %2 = alloca %struct.sorbet_iterMethodArg, align 8
  %3 = alloca %struct.sorbet_iterMethodArg, align 8
  %realpath = tail call i64 @sorbet_readRealpath()
  %4 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_foo, i64 0, i64 0), i64 3) #8
  store i64 %4, i64* @rubyIdPrecomputed_foo, align 8
  %5 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_call, i64 0, i64 0), i64 4) #8
  store i64 %5, i64* @rubyIdPrecomputed_call, align 8
  %6 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_boo, i64 0, i64 0), i64 3) #8
  store i64 %6, i64* @rubyIdPrecomputed_boo, align 8
  %7 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_bar, i64 0, i64 0), i64 3) #8
  store i64 %7, i64* @rubyIdPrecomputed_bar, align 8
  %8 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([8 x i8], [8 x i8]* @str_to_proc, i64 0, i64 0), i64 7) #8
  store i64 %8, i64* @rubyIdPrecomputed_to_proc, align 8
  %9 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_baz, i64 0, i64 0), i64 3) #8
  store i64 %9, i64* @rubyIdPrecomputed_baz, align 8
  %10 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 16) #8
  store i64 %10, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %11 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([7 x i8], [7 x i8]* @"str_<self>", i64 0, i64 0), i64 6) #8
  store i64 %11, i64* @"rubyIdPrecomputed_<self>", align 8
  %12 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([13 x i8], [13 x i8]* @"str_<block-call>", i64 0, i64 0), i64 12) #8
  store i64 %12, i64* @"rubyIdPrecomputed_<block-call>", align 8
  %13 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([10 x i8], [10 x i8]* @"str_block for", i64 0, i64 0), i64 9) #8
  store i64 %13, i64* @"rubyIdPrecomputed_block for", align 8
  %14 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([9 x i8], [9 x i8]* @str_keep_def, i64 0, i64 0), i64 8) #8
  %15 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_puts, i64 0, i64 0), i64 4) #8
  store i64 %15, i64* @rubyIdPrecomputed_puts, align 8
  %"rubyId_<self>.i" = load i64, i64* @"rubyIdPrecomputed_<self>", align 8
  store i64 %"rubyId_<self>.i", i64* getelementptr inbounds ([2 x i64], [2 x i64]* @"<static-init-locals-storage>", i64 0, i64 0), align 8
  %"rubyId_<block-call>.i" = load i64, i64* @"rubyIdPrecomputed_<block-call>", align 8
  store i64 %"rubyId_<block-call>.i", i64* getelementptr inbounds ([2 x i64], [2 x i64]* @"<static-init-locals-storage>", i64 0, i64 1), align 8
  %16 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_foo, i64 0, i64 0), i64 3) #8
  tail call void @rb_gc_register_mark_object(i64 %16) #8
  store i64 %16, i64* @rubyStrFrozen_foo, align 8
  %17 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([44 x i8], [44 x i8]* @"str_test/testdata/compiler/method_with_block.rb", i64 0, i64 0), i64 43) #8
  tail call void @rb_gc_register_mark_object(i64 %17) #8
  store i64 %17, i64* @"rubyStrFrozen_test/testdata/compiler/method_with_block.rb", align 8
  %18 = bitcast [0 x i64]* %locals1.i.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 0, i8* nonnull %18)
  %rubyId_foo.i.i = load i64, i64* @rubyIdPrecomputed_foo, align 8
  %rubyStr_foo.i.i = load i64, i64* @rubyStrFrozen_foo, align 8
  %locals1.sub.i.i = getelementptr inbounds [0 x i64], [0 x i64]* %locals1.i.i, i64 0, i64 0
  %19 = call i8* @sorbet_allocateRubyStackFrame(i64 %rubyStr_foo.i.i, i64 %rubyId_foo.i.i, i64 %17, i64 %realpath, i8* null, i32 1, i32 5, i32 7, i64* nonnull %locals1.sub.i.i, i32 0)
  store i8* %19, i8** @"stackFramePrecomputed_func_Object#foo", align 8
  call void @llvm.lifetime.end.p0i8(i64 0, i8* nonnull %18)
  %20 = call i64 @rb_fstring_new(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_boo, i64 0, i64 0), i64 3) #8
  call void @rb_gc_register_mark_object(i64 %20) #8
  call void @llvm.lifetime.start.p0i8(i64 0, i8* nonnull %18)
  %rubyId_boo.i.i = load i64, i64* @rubyIdPrecomputed_boo, align 8
  %"rubyStr_test/testdata/compiler/method_with_block.rb.i2.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/method_with_block.rb", align 8
  %21 = call i8* @sorbet_allocateRubyStackFrame(i64 %20, i64 %rubyId_boo.i.i, i64 %"rubyStr_test/testdata/compiler/method_with_block.rb.i2.i", i64 %realpath, i8* null, i32 1, i32 9, i32 11, i64* nonnull %locals1.sub.i.i, i32 0)
  store i8* %21, i8** @"stackFramePrecomputed_func_Object#boo", align 8
  call void @llvm.lifetime.end.p0i8(i64 0, i8* nonnull %18)
  %22 = call i64 @rb_fstring_new(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_bar, i64 0, i64 0), i64 3) #8
  call void @rb_gc_register_mark_object(i64 %22) #8
  store i64 %22, i64* @rubyStrFrozen_bar, align 8
  call void @llvm.lifetime.start.p0i8(i64 0, i8* nonnull %18)
  %rubyId_bar.i.i = load i64, i64* @rubyIdPrecomputed_bar, align 8
  %"rubyStr_test/testdata/compiler/method_with_block.rb.i5.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/method_with_block.rb", align 8
  %23 = call i8* @sorbet_allocateRubyStackFrame(i64 %22, i64 %rubyId_bar.i.i, i64 %"rubyStr_test/testdata/compiler/method_with_block.rb.i5.i", i64 %realpath, i8* null, i32 1, i32 13, i32 15, i64* nonnull %locals1.sub.i.i, i32 0)
  store i8* %23, i8** @"stackFramePrecomputed_func_Object#bar", align 8
  call void @llvm.lifetime.end.p0i8(i64 0, i8* nonnull %18)
  %24 = call i64 @rb_fstring_new(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_baz, i64 0, i64 0), i64 3) #8
  call void @rb_gc_register_mark_object(i64 %24) #8
  store i64 %24, i64* @rubyStrFrozen_baz, align 8
  call void @llvm.lifetime.start.p0i8(i64 0, i8* nonnull %18)
  %rubyId_baz.i.i = load i64, i64* @rubyIdPrecomputed_baz, align 8
  %"rubyStr_test/testdata/compiler/method_with_block.rb.i8.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/method_with_block.rb", align 8
  %25 = call i8* @sorbet_allocateRubyStackFrame(i64 %24, i64 %rubyId_baz.i.i, i64 %"rubyStr_test/testdata/compiler/method_with_block.rb.i8.i", i64 %realpath, i8* null, i32 1, i32 17, i32 19, i64* nonnull %locals1.sub.i.i, i32 0)
  store i8* %25, i8** @"stackFramePrecomputed_func_Object#baz", align 8
  call void @llvm.lifetime.end.p0i8(i64 0, i8* nonnull %18)
  %26 = call i64 @rb_fstring_new(i8* getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 16) #8
  call void @rb_gc_register_mark_object(i64 %26) #8
  %"rubyId_<top (required)>.i.i" = load i64, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %"rubyStr_test/testdata/compiler/method_with_block.rb.i10.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/method_with_block.rb", align 8
  %27 = call i8* @sorbet_allocateRubyStackFrame(i64 %26, i64 %"rubyId_<top (required)>.i.i", i64 %"rubyStr_test/testdata/compiler/method_with_block.rb.i10.i", i64 %realpath, i8* null, i32 1, i32 1, i32 34, i64* getelementptr inbounds ([2 x i64], [2 x i64]* @"<static-init-locals-storage>", i64 0, i64 0), i32 2)
  store i8* %27, i8** @"stackFramePrecomputed_func_<root>.<static-init>$153", align 8
  %28 = call i64 @rb_fstring_new(i8* getelementptr inbounds ([10 x i8], [10 x i8]* @"str_block for", i64 0, i64 0), i64 9) #8
  call void @rb_gc_register_mark_object(i64 %28) #8
  store i64 %28, i64* @"rubyStrFrozen_block for", align 8
  %"stackFrame_func_<root>.<static-init>$153.i.i" = load i8*, i8** @"stackFramePrecomputed_func_<root>.<static-init>$153", align 8
  %"rubyId_block for.i.i" = load i64, i64* @"rubyIdPrecomputed_block for", align 8
  %"rubyStr_test/testdata/compiler/method_with_block.rb.i11.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/method_with_block.rb", align 8
  %29 = call i8* @sorbet_allocateRubyStackFrame(i64 %28, i64 %"rubyId_block for.i.i", i64 %"rubyStr_test/testdata/compiler/method_with_block.rb.i11.i", i64 %realpath, i8* %"stackFrame_func_<root>.<static-init>$153.i.i", i32 2, i32 1, i32 34, i64* null, i32 0)
  store i8* %29, i8** @"stackFramePrecomputed_func_<root>.<static-init>$153$block_1", align 8
  %"stackFrame_func_<root>.<static-init>$153.i12.i" = load i8*, i8** @"stackFramePrecomputed_func_<root>.<static-init>$153", align 8
  %"rubyId_block for.i13.i" = load i64, i64* @"rubyIdPrecomputed_block for", align 8
  %"rubyStr_block for.i14.i" = load i64, i64* @"rubyStrFrozen_block for", align 8
  %"rubyStr_test/testdata/compiler/method_with_block.rb.i15.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/method_with_block.rb", align 8
  %30 = call i8* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_block for.i14.i", i64 %"rubyId_block for.i13.i", i64 %"rubyStr_test/testdata/compiler/method_with_block.rb.i15.i", i64 %realpath, i8* %"stackFrame_func_<root>.<static-init>$153.i12.i", i32 2, i32 1, i32 34, i64* null, i32 0)
  store i8* %30, i8** @"stackFramePrecomputed_func_<root>.<static-init>$153$block_2", align 8
  %"stackFrame_func_<root>.<static-init>$153.i16.i" = load i8*, i8** @"stackFramePrecomputed_func_<root>.<static-init>$153", align 8
  %"rubyId_block for.i17.i" = load i64, i64* @"rubyIdPrecomputed_block for", align 8
  %"rubyStr_block for.i18.i" = load i64, i64* @"rubyStrFrozen_block for", align 8
  %"rubyStr_test/testdata/compiler/method_with_block.rb.i19.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/method_with_block.rb", align 8
  %31 = call i8* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_block for.i18.i", i64 %"rubyId_block for.i17.i", i64 %"rubyStr_test/testdata/compiler/method_with_block.rb.i19.i", i64 %realpath, i8* %"stackFrame_func_<root>.<static-init>$153.i16.i", i32 2, i32 1, i32 34, i64* null, i32 0)
  store i8* %31, i8** @"stackFramePrecomputed_func_<root>.<static-init>$153$block_3", align 8
  %"stackFrame_func_<root>.<static-init>$153.i20.i" = load i8*, i8** @"stackFramePrecomputed_func_<root>.<static-init>$153", align 8
  %"rubyId_block for.i21.i" = load i64, i64* @"rubyIdPrecomputed_block for", align 8
  %"rubyStr_block for.i22.i" = load i64, i64* @"rubyStrFrozen_block for", align 8
  %"rubyStr_test/testdata/compiler/method_with_block.rb.i23.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/method_with_block.rb", align 8
  %32 = call i8* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_block for.i22.i", i64 %"rubyId_block for.i21.i", i64 %"rubyStr_test/testdata/compiler/method_with_block.rb.i23.i", i64 %realpath, i8* %"stackFrame_func_<root>.<static-init>$153.i20.i", i32 2, i32 1, i32 34, i64* null, i32 0)
  store i8* %32, i8** @"stackFramePrecomputed_func_<root>.<static-init>$153$block_4", align 8
  %33 = call i64 @rb_fstring_new(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_heey, i64 0, i64 0), i64 4) #8
  call void @rb_gc_register_mark_object(i64 %33) #8
  store i64 %33, i64* @rubyStrFrozen_heey, align 8
  %34 = call i64 @rb_fstring_new(i8* getelementptr inbounds ([7 x i8], [7 x i8]* @str_boohey, i64 0, i64 0), i64 6) #8
  call void @rb_gc_register_mark_object(i64 %34) #8
  store i64 %34, i64* @rubyStrFrozen_boohey, align 8
  %35 = load %struct.rb_vm_struct*, %struct.rb_vm_struct** @ruby_current_vm_ptr, align 8, !tbaa !21
  %36 = getelementptr inbounds %struct.rb_vm_struct, %struct.rb_vm_struct* %35, i64 0, i32 17
  %37 = load i64, i64* %36, align 8, !tbaa !80
  %"stackFrame_func_<root>.<static-init>$153.i" = load i8*, i8** @"stackFramePrecomputed_func_<root>.<static-init>$153", align 8
  %38 = bitcast i8* %"stackFrame_func_<root>.<static-init>$153.i" to %struct.rb_iseq_struct*
  %39 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !21
  %40 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %39, i64 0, i32 2
  %41 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %40, align 8, !tbaa !22
  %42 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %41, i64 0, i32 2
  %43 = bitcast %struct.rb_iseq_struct** %42 to i8**
  store i8* %"stackFrame_func_<root>.<static-init>$153.i", i8** %43, align 8, !tbaa !25
  %44 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %41, i64 0, i32 4
  %45 = load i64*, i64** %44, align 8, !tbaa !27
  %46 = load i64, i64* %45, align 8, !tbaa !16
  %47 = and i64 %46, -129
  store i64 %47, i64* %45, align 8, !tbaa !16
  call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* %39, %struct.rb_control_frame_struct* nonnull %41, %struct.rb_iseq_struct* %38) #8
  %48 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %41, i64 0, i32 0
  %49 = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** %42, align 8, !tbaa !25
  %50 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %49, i64 0, i32 2
  %51 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %50, align 8, !tbaa !28
  %52 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %51, i64 0, i32 2
  %53 = load i64*, i64** %52, align 8, !tbaa !30
  %54 = getelementptr inbounds i64, i64* %53, i64 5
  store i64* %54, i64** %48, align 8, !tbaa !21
  %55 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !89, !tbaa !21
  %56 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %55, i64 0, i32 2, !dbg !89
  %57 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %56, align 8, !dbg !89, !tbaa !22
  %58 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %57, i64 0, i32 4, !dbg !89
  %59 = load i64*, i64** %58, align 8, !dbg !89, !tbaa !27
  %60 = load i64, i64* %59, align 8, !dbg !89, !tbaa !16
  %61 = and i64 %60, 8, !dbg !89
  %62 = icmp eq i64 %61, 0, !dbg !89
  br i1 %62, label %63, label %65, !dbg !89, !prof !40

63:                                               ; preds = %entry
  %64 = getelementptr inbounds i64, i64* %59, i64 -3, !dbg !89
  store i64 %37, i64* %64, align 8, !dbg !89, !tbaa !16
  br label %sorbet_writeLocal.exit.i, !dbg !89

65:                                               ; preds = %entry
  call void @sorbet_vm_env_write_slowpath(i64* nonnull %59, i32 -3, i64 %37) #8, !dbg !89
  br label %sorbet_writeLocal.exit.i, !dbg !89

sorbet_writeLocal.exit.i:                         ; preds = %65, %63
  store i64* %54, i64** %48, align 8, !tbaa !21
  %66 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !89, !tbaa !21
  %67 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %66, i64 0, i32 2, !dbg !89
  %68 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %67, align 8, !dbg !89, !tbaa !22
  %69 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %68, i64 0, i32 4, !dbg !89
  %70 = load i64*, i64** %69, align 8, !dbg !89, !tbaa !27
  %71 = load i64, i64* %70, align 8, !dbg !89, !tbaa !16
  %72 = and i64 %71, 8, !dbg !89
  %73 = icmp eq i64 %72, 0, !dbg !89
  br i1 %73, label %afterSend71.i, label %74, !dbg !89, !prof !40

74:                                               ; preds = %sorbet_writeLocal.exit.i
  %75 = getelementptr inbounds i64, i64* %70, i64 -3, !dbg !89
  %76 = load i64, i64* %75, align 8, !dbg !89, !tbaa !16
  call void @sorbet_vm_env_write_slowpath(i64* nonnull %70, i32 -3, i64 %76) #8, !dbg !89
  br label %afterSend71.i, !dbg !89

afterSend71.i:                                    ; preds = %74, %sorbet_writeLocal.exit.i
  %rubyId_foo.i = load i64, i64* @rubyIdPrecomputed_foo, align 8, !dbg !89
  %rawSym.i = call i64 @rb_id2sym(i64 %rubyId_foo.i) #8, !dbg !89
  %77 = load i64, i64* @rb_cObject, align 8, !dbg !89
  call void @rb_define_method(i64 %77, i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_foo, i64 0, i64 0), i64 (...)* bitcast (i64 (i32, i64*, i64)* @"func_Object#foo" to i64 (...)*), i32 -1) #8, !dbg !89
  %78 = getelementptr inbounds i64, i64* %53, i64 9, !dbg !89
  store i64* %78, i64** %48, align 8, !dbg !89, !tbaa !21
  %rubyId_boo.i = load i64, i64* @rubyIdPrecomputed_boo, align 8, !dbg !90
  %rawSym48.i = call i64 @rb_id2sym(i64 %rubyId_boo.i) #8, !dbg !90
  call void @rb_define_method(i64 %77, i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_boo, i64 0, i64 0), i64 (...)* bitcast (i64 (i32, i64*, i64)* @"func_Object#boo" to i64 (...)*), i32 -1) #8, !dbg !90
  %79 = getelementptr inbounds i64, i64* %53, i64 13, !dbg !90
  store i64* %79, i64** %48, align 8, !dbg !90, !tbaa !21
  %rubyId_bar.i = load i64, i64* @rubyIdPrecomputed_bar, align 8, !dbg !91
  %rawSym59.i = call i64 @rb_id2sym(i64 %rubyId_bar.i) #8, !dbg !91
  call void @rb_define_method(i64 %77, i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_bar, i64 0, i64 0), i64 (...)* bitcast (i64 (i32, i64*, i64)* @"func_Object#bar" to i64 (...)*), i32 -1) #8, !dbg !91
  %80 = getelementptr inbounds i64, i64* %53, i64 17, !dbg !91
  store i64* %80, i64** %48, align 8, !dbg !91, !tbaa !21
  %rubyId_baz.i = load i64, i64* @rubyIdPrecomputed_baz, align 8, !dbg !92
  %rawSym70.i = call i64 @rb_id2sym(i64 %rubyId_baz.i) #8, !dbg !92
  call void @rb_define_method(i64 %77, i8* getelementptr inbounds ([4 x i8], [4 x i8]* @str_baz, i64 0, i64 0), i64 (...)* bitcast (i64 (i32, i64*, i64)* @"func_Object#baz" to i64 (...)*), i32 -1) #8, !dbg !92
  %81 = getelementptr inbounds i64, i64* %53, i64 21, !dbg !92
  store i64* %81, i64** %48, align 8, !dbg !92, !tbaa !21
  %82 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !93, !tbaa !21
  %83 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %82, i64 0, i32 2, !dbg !93
  %84 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %83, align 8, !dbg !93, !tbaa !22
  %85 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %84, i64 0, i32 4, !dbg !93
  %86 = load i64*, i64** %85, align 8, !dbg !93, !tbaa !27
  %87 = getelementptr inbounds i64, i64* %86, i64 -3, !dbg !93
  %88 = load i64, i64* %87, align 8, !dbg !93, !tbaa !16
  %rubyId_foo82.i = load i64, i64* @rubyIdPrecomputed_foo, align 8, !dbg !93
  %89 = bitcast %struct.sorbet_iterMethodArg* %3 to i8*, !dbg !93
  call void @llvm.lifetime.start.p0i8(i64 48, i8* nonnull %89) #8, !dbg !93, !noalias !94
  %90 = getelementptr inbounds %struct.sorbet_iterMethodArg, %struct.sorbet_iterMethodArg* %3, i64 0, i32 0, !dbg !93
  store i64 %88, i64* %90, align 8, !dbg !93, !tbaa !4, !noalias !94
  %91 = getelementptr inbounds %struct.sorbet_iterMethodArg, %struct.sorbet_iterMethodArg* %3, i64 0, i32 1, !dbg !93
  store i64 %rubyId_foo82.i, i64* %91, align 8, !dbg !93, !tbaa !11, !noalias !94
  %92 = getelementptr inbounds %struct.sorbet_iterMethodArg, %struct.sorbet_iterMethodArg* %3, i64 0, i32 2, !dbg !93
  store i32 0, i32* %92, align 8, !dbg !93, !tbaa !12, !noalias !94
  %93 = getelementptr inbounds %struct.sorbet_iterMethodArg, %struct.sorbet_iterMethodArg* %3, i64 0, i32 3, !dbg !93
  store i64* null, i64** %93, align 8, !dbg !93, !tbaa !13, !noalias !94
  %94 = getelementptr inbounds %struct.sorbet_iterMethodArg, %struct.sorbet_iterMethodArg* %3, i64 0, i32 4, !dbg !93
  store i32 0, i32* %94, align 8, !dbg !93, !tbaa !14, !noalias !94
  %95 = getelementptr inbounds %struct.sorbet_iterMethodArg, %struct.sorbet_iterMethodArg* %3, i64 0, i32 5, !dbg !93
  store %struct.FunctionInlineCache* @ic_callFuncWithBlock_foo, %struct.FunctionInlineCache** %95, align 8, !dbg !93, !tbaa !15, !noalias !94
  %96 = ptrtoint %struct.sorbet_iterMethodArg* %3 to i64, !dbg !93
  %97 = call i64 @rb_iterate(i64 (i64)* nonnull @sorbet_iterMethod, i64 %96, i64 (...)* bitcast (i64 (i64, i64, i32, i64*, i64)* @"func_<root>.<static-init>$153$block_1" to i64 (...)*), i64 0) #8, !dbg !93
  call void @llvm.lifetime.end.p0i8(i64 48, i8* nonnull %89) #8, !dbg !93, !noalias !94
  %98 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !21
  %99 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %98, i64 0, i32 2
  %100 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %99, align 8, !tbaa !22
  %101 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %100, i64 0, i32 4
  %102 = load i64*, i64** %101, align 8, !tbaa !27
  %103 = getelementptr inbounds i64, i64* %102, i64 -3
  %104 = load i64, i64* %103, align 8, !tbaa !16
  store i64* %81, i64** %48, align 8, !tbaa !21
  %105 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !93, !tbaa !21
  %106 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %105, i64 0, i32 2, !dbg !93
  %107 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %106, align 8, !dbg !93, !tbaa !22
  %108 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %107, i64 0, i32 4, !dbg !93
  %109 = load i64*, i64** %108, align 8, !dbg !93, !tbaa !27
  %110 = load i64, i64* %109, align 8, !dbg !93, !tbaa !16
  %111 = and i64 %110, 8, !dbg !93
  %112 = icmp eq i64 %111, 0, !dbg !93
  br i1 %112, label %113, label %115, !dbg !93, !prof !40

113:                                              ; preds = %afterSend71.i
  %114 = getelementptr inbounds i64, i64* %109, i64 -3, !dbg !93
  store i64 %104, i64* %114, align 8, !dbg !93, !tbaa !16
  br label %sorbet_writeLocal.exit127.i, !dbg !93

115:                                              ; preds = %afterSend71.i
  call void @sorbet_vm_env_write_slowpath(i64* nonnull %109, i32 -3, i64 %104) #8, !dbg !93
  br label %sorbet_writeLocal.exit127.i, !dbg !93

sorbet_writeLocal.exit127.i:                      ; preds = %115, %113
  %116 = getelementptr inbounds i64, i64* %53, i64 25, !dbg !93
  store i64* %116, i64** %48, align 8, !dbg !93, !tbaa !21
  %117 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !97, !tbaa !21
  %118 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %117, i64 0, i32 2, !dbg !97
  %119 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %118, align 8, !dbg !97, !tbaa !22
  %120 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %119, i64 0, i32 4, !dbg !97
  %121 = load i64*, i64** %120, align 8, !dbg !97, !tbaa !27
  %122 = getelementptr inbounds i64, i64* %121, i64 -3, !dbg !97
  %123 = load i64, i64* %122, align 8, !dbg !97, !tbaa !16
  %rubyId_boo86.i = load i64, i64* @rubyIdPrecomputed_boo, align 8, !dbg !97
  %124 = bitcast %struct.sorbet_iterMethodArg* %2 to i8*, !dbg !97
  call void @llvm.lifetime.start.p0i8(i64 48, i8* nonnull %124) #8, !dbg !97, !noalias !98
  %125 = getelementptr inbounds %struct.sorbet_iterMethodArg, %struct.sorbet_iterMethodArg* %2, i64 0, i32 0, !dbg !97
  store i64 %123, i64* %125, align 8, !dbg !97, !tbaa !4, !noalias !98
  %126 = getelementptr inbounds %struct.sorbet_iterMethodArg, %struct.sorbet_iterMethodArg* %2, i64 0, i32 1, !dbg !97
  store i64 %rubyId_boo86.i, i64* %126, align 8, !dbg !97, !tbaa !11, !noalias !98
  %127 = getelementptr inbounds %struct.sorbet_iterMethodArg, %struct.sorbet_iterMethodArg* %2, i64 0, i32 2, !dbg !97
  store i32 0, i32* %127, align 8, !dbg !97, !tbaa !12, !noalias !98
  %128 = getelementptr inbounds %struct.sorbet_iterMethodArg, %struct.sorbet_iterMethodArg* %2, i64 0, i32 3, !dbg !97
  store i64* null, i64** %128, align 8, !dbg !97, !tbaa !13, !noalias !98
  %129 = getelementptr inbounds %struct.sorbet_iterMethodArg, %struct.sorbet_iterMethodArg* %2, i64 0, i32 4, !dbg !97
  store i32 0, i32* %129, align 8, !dbg !97, !tbaa !14, !noalias !98
  %130 = getelementptr inbounds %struct.sorbet_iterMethodArg, %struct.sorbet_iterMethodArg* %2, i64 0, i32 5, !dbg !97
  store %struct.FunctionInlineCache* @ic_callFuncWithBlock_boo, %struct.FunctionInlineCache** %130, align 8, !dbg !97, !tbaa !15, !noalias !98
  %131 = ptrtoint %struct.sorbet_iterMethodArg* %2 to i64, !dbg !97
  %132 = call i64 @rb_iterate(i64 (i64)* nonnull @sorbet_iterMethod, i64 %131, i64 (...)* bitcast (i64 (i64, i64, i32, i64*, i64)* @"func_<root>.<static-init>$153$block_2" to i64 (...)*), i64 0) #8, !dbg !97
  call void @llvm.lifetime.end.p0i8(i64 48, i8* nonnull %124) #8, !dbg !97, !noalias !98
  %133 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !21
  %134 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %133, i64 0, i32 2
  %135 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %134, align 8, !tbaa !22
  %136 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %135, i64 0, i32 4
  %137 = load i64*, i64** %136, align 8, !tbaa !27
  %138 = getelementptr inbounds i64, i64* %137, i64 -3
  %139 = load i64, i64* %138, align 8, !tbaa !16
  store i64* %116, i64** %48, align 8, !tbaa !21
  %140 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !97, !tbaa !21
  %141 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %140, i64 0, i32 2, !dbg !97
  %142 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %141, align 8, !dbg !97, !tbaa !22
  %143 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %142, i64 0, i32 4, !dbg !97
  %144 = load i64*, i64** %143, align 8, !dbg !97, !tbaa !27
  %145 = load i64, i64* %144, align 8, !dbg !97, !tbaa !16
  %146 = and i64 %145, 8, !dbg !97
  %147 = icmp eq i64 %146, 0, !dbg !97
  br i1 %147, label %148, label %150, !dbg !97, !prof !40

148:                                              ; preds = %sorbet_writeLocal.exit127.i
  %149 = getelementptr inbounds i64, i64* %144, i64 -3, !dbg !97
  store i64 %139, i64* %149, align 8, !dbg !97, !tbaa !16
  br label %sorbet_writeLocal.exit128.i, !dbg !97

150:                                              ; preds = %sorbet_writeLocal.exit127.i
  call void @sorbet_vm_env_write_slowpath(i64* nonnull %144, i32 -3, i64 %139) #8, !dbg !97
  br label %sorbet_writeLocal.exit128.i, !dbg !97

sorbet_writeLocal.exit128.i:                      ; preds = %150, %148
  %151 = getelementptr inbounds i64, i64* %53, i64 29, !dbg !97
  store i64* %151, i64** %48, align 8, !dbg !97, !tbaa !21
  %152 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !101, !tbaa !21
  %153 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %152, i64 0, i32 2, !dbg !101
  %154 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %153, align 8, !dbg !101, !tbaa !22
  %155 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %154, i64 0, i32 4, !dbg !101
  %156 = load i64*, i64** %155, align 8, !dbg !101, !tbaa !27
  %157 = getelementptr inbounds i64, i64* %156, i64 -3, !dbg !101
  %158 = load i64, i64* %157, align 8, !dbg !101, !tbaa !16
  %rubyId_bar90.i = load i64, i64* @rubyIdPrecomputed_bar, align 8, !dbg !101
  %159 = bitcast %struct.sorbet_iterMethodArg* %1 to i8*, !dbg !101
  call void @llvm.lifetime.start.p0i8(i64 48, i8* nonnull %159) #8, !dbg !101, !noalias !102
  %160 = getelementptr inbounds %struct.sorbet_iterMethodArg, %struct.sorbet_iterMethodArg* %1, i64 0, i32 0, !dbg !101
  store i64 %158, i64* %160, align 8, !dbg !101, !tbaa !4, !noalias !102
  %161 = getelementptr inbounds %struct.sorbet_iterMethodArg, %struct.sorbet_iterMethodArg* %1, i64 0, i32 1, !dbg !101
  store i64 %rubyId_bar90.i, i64* %161, align 8, !dbg !101, !tbaa !11, !noalias !102
  %162 = getelementptr inbounds %struct.sorbet_iterMethodArg, %struct.sorbet_iterMethodArg* %1, i64 0, i32 2, !dbg !101
  store i32 0, i32* %162, align 8, !dbg !101, !tbaa !12, !noalias !102
  %163 = getelementptr inbounds %struct.sorbet_iterMethodArg, %struct.sorbet_iterMethodArg* %1, i64 0, i32 3, !dbg !101
  store i64* null, i64** %163, align 8, !dbg !101, !tbaa !13, !noalias !102
  %164 = getelementptr inbounds %struct.sorbet_iterMethodArg, %struct.sorbet_iterMethodArg* %1, i64 0, i32 4, !dbg !101
  store i32 0, i32* %164, align 8, !dbg !101, !tbaa !14, !noalias !102
  %165 = getelementptr inbounds %struct.sorbet_iterMethodArg, %struct.sorbet_iterMethodArg* %1, i64 0, i32 5, !dbg !101
  store %struct.FunctionInlineCache* @ic_callFuncWithBlock_bar, %struct.FunctionInlineCache** %165, align 8, !dbg !101, !tbaa !15, !noalias !102
  %166 = ptrtoint %struct.sorbet_iterMethodArg* %1 to i64, !dbg !101
  %167 = call i64 @rb_iterate(i64 (i64)* nonnull @sorbet_iterMethod, i64 %166, i64 (...)* bitcast (i64 (i64, i64, i32, i64*, i64)* @"func_<root>.<static-init>$153$block_3" to i64 (...)*), i64 0) #8, !dbg !101
  call void @llvm.lifetime.end.p0i8(i64 48, i8* nonnull %159) #8, !dbg !101, !noalias !102
  %168 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !21
  %169 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %168, i64 0, i32 2
  %170 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %169, align 8, !tbaa !22
  %171 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %170, i64 0, i32 4
  %172 = load i64*, i64** %171, align 8, !tbaa !27
  %173 = getelementptr inbounds i64, i64* %172, i64 -3
  %174 = load i64, i64* %173, align 8, !tbaa !16
  store i64* %151, i64** %48, align 8, !tbaa !21
  %175 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !101, !tbaa !21
  %176 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %175, i64 0, i32 2, !dbg !101
  %177 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %176, align 8, !dbg !101, !tbaa !22
  %178 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %177, i64 0, i32 4, !dbg !101
  %179 = load i64*, i64** %178, align 8, !dbg !101, !tbaa !27
  %180 = load i64, i64* %179, align 8, !dbg !101, !tbaa !16
  %181 = and i64 %180, 8, !dbg !101
  %182 = icmp eq i64 %181, 0, !dbg !101
  br i1 %182, label %183, label %185, !dbg !101, !prof !40

183:                                              ; preds = %sorbet_writeLocal.exit128.i
  %184 = getelementptr inbounds i64, i64* %179, i64 -3, !dbg !101
  store i64 %174, i64* %184, align 8, !dbg !101, !tbaa !16
  br label %"func_<root>.<static-init>$153.exit", !dbg !101

185:                                              ; preds = %sorbet_writeLocal.exit128.i
  call void @sorbet_vm_env_write_slowpath(i64* nonnull %179, i32 -3, i64 %174) #8, !dbg !101
  br label %"func_<root>.<static-init>$153.exit", !dbg !101

"func_<root>.<static-init>$153.exit":             ; preds = %183, %185
  %186 = getelementptr inbounds i64, i64* %53, i64 33, !dbg !101
  store i64* %186, i64** %48, align 8, !dbg !101, !tbaa !21
  %187 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !105, !tbaa !21
  %188 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %187, i64 0, i32 2, !dbg !105
  %189 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %188, align 8, !dbg !105, !tbaa !22
  %190 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %189, i64 0, i32 4, !dbg !105
  %191 = load i64*, i64** %190, align 8, !dbg !105, !tbaa !27
  %192 = getelementptr inbounds i64, i64* %191, i64 -3, !dbg !105
  %193 = load i64, i64* %192, align 8, !dbg !105, !tbaa !16
  %rubyId_baz94.i = load i64, i64* @rubyIdPrecomputed_baz, align 8, !dbg !105
  %194 = bitcast %struct.sorbet_iterMethodArg* %0 to i8*, !dbg !105
  call void @llvm.lifetime.start.p0i8(i64 48, i8* nonnull %194) #8, !dbg !105, !noalias !106
  %195 = getelementptr inbounds %struct.sorbet_iterMethodArg, %struct.sorbet_iterMethodArg* %0, i64 0, i32 0, !dbg !105
  store i64 %193, i64* %195, align 8, !dbg !105, !tbaa !4, !noalias !106
  %196 = getelementptr inbounds %struct.sorbet_iterMethodArg, %struct.sorbet_iterMethodArg* %0, i64 0, i32 1, !dbg !105
  store i64 %rubyId_baz94.i, i64* %196, align 8, !dbg !105, !tbaa !11, !noalias !106
  %197 = getelementptr inbounds %struct.sorbet_iterMethodArg, %struct.sorbet_iterMethodArg* %0, i64 0, i32 2, !dbg !105
  store i32 0, i32* %197, align 8, !dbg !105, !tbaa !12, !noalias !106
  %198 = getelementptr inbounds %struct.sorbet_iterMethodArg, %struct.sorbet_iterMethodArg* %0, i64 0, i32 3, !dbg !105
  store i64* null, i64** %198, align 8, !dbg !105, !tbaa !13, !noalias !106
  %199 = getelementptr inbounds %struct.sorbet_iterMethodArg, %struct.sorbet_iterMethodArg* %0, i64 0, i32 4, !dbg !105
  store i32 0, i32* %199, align 8, !dbg !105, !tbaa !14, !noalias !106
  %200 = getelementptr inbounds %struct.sorbet_iterMethodArg, %struct.sorbet_iterMethodArg* %0, i64 0, i32 5, !dbg !105
  store %struct.FunctionInlineCache* @ic_callFuncWithBlock_baz, %struct.FunctionInlineCache** %200, align 8, !dbg !105, !tbaa !15, !noalias !106
  %201 = ptrtoint %struct.sorbet_iterMethodArg* %0 to i64, !dbg !105
  %202 = call i64 @rb_iterate(i64 (i64)* nonnull @sorbet_iterMethod, i64 %201, i64 (...)* bitcast (i64 (i64, i64, i32, i64*, i64)* @"func_<root>.<static-init>$153$block_4" to i64 (...)*), i64 0) #8, !dbg !105
  call void @llvm.lifetime.end.p0i8(i64 48, i8* nonnull %194) #8, !dbg !105, !noalias !106
  store i64* %186, i64** %48, align 8, !tbaa !21
  ret void
}

attributes #0 = { noreturn }
attributes #1 = { "addedToSilenceEmptyAttrsError" }
attributes #2 = { argmemonly nounwind }
attributes #3 = { nounwind ssp uwtable }
attributes #4 = { nounwind sspreq uwtable }
attributes #5 = { ssp }
attributes #6 = { nounwind ssp }
attributes #7 = { sspreq }
attributes #8 = { nounwind }
attributes #9 = { noreturn nounwind }

!llvm.module.flags = !{!0}
!llvm.dbg.cu = !{!1}

!0 = !{i32 2, !"Debug Info Version", i32 3}
!1 = distinct !DICompileUnit(language: DW_LANG_C, file: !2, producer: "Sorbet LLVM", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, enums: !3)
!2 = !DIFile(filename: "test/testdata/compiler/method_with_block.rb", directory: ".")
!3 = !{}
!4 = !{!5, !6, i64 0}
!5 = !{!"sorbet_iterMethodArg", !6, i64 0, !6, i64 8, !9, i64 16, !10, i64 24, !9, i64 32, !10, i64 40}
!6 = !{!"long", !7, i64 0}
!7 = !{!"omnipotent char", !8, i64 0}
!8 = !{!"Simple C/C++ TBAA"}
!9 = !{!"int", !7, i64 0}
!10 = !{!"any pointer", !7, i64 0}
!11 = !{!5, !6, i64 8}
!12 = !{!5, !9, i64 16}
!13 = !{!5, !10, i64 24}
!14 = !{!5, !9, i64 32}
!15 = !{!5, !10, i64 40}
!16 = !{!6, !6, i64 0}
!17 = distinct !DISubprogram(name: "Object#foo", linkageName: "func_Object#foo", scope: null, file: !2, line: 5, type: !18, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!18 = !DISubroutineType(types: !19)
!19 = !{!20}
!20 = !DIBasicType(name: "VALUE", size: 64, encoding: DW_ATE_signed)
!21 = !{!10, !10, i64 0}
!22 = !{!23, !10, i64 16}
!23 = !{!"rb_execution_context_struct", !10, i64 0, !6, i64 8, !10, i64 16, !10, i64 24, !10, i64 32, !9, i64 40, !9, i64 44, !10, i64 48, !10, i64 56, !10, i64 64, !6, i64 72, !6, i64 80, !10, i64 88, !6, i64 96, !10, i64 104, !10, i64 112, !6, i64 120, !6, i64 128, !7, i64 136, !7, i64 137, !6, i64 144, !24, i64 152}
!24 = !{!"", !10, i64 0, !10, i64 8, !6, i64 16, !7, i64 24}
!25 = !{!26, !10, i64 16}
!26 = !{!"rb_control_frame_struct", !10, i64 0, !10, i64 8, !10, i64 16, !6, i64 24, !10, i64 32, !10, i64 40, !10, i64 48}
!27 = !{!26, !10, i64 32}
!28 = !{!29, !10, i64 16}
!29 = !{!"rb_iseq_struct", !6, i64 0, !6, i64 8, !10, i64 16, !7, i64 24}
!30 = !{!31, !10, i64 8}
!31 = !{!"rb_iseq_constant_body", !7, i64 0, !9, i64 4, !10, i64 8, !32, i64 16, !34, i64 64, !37, i64 120, !10, i64 152, !10, i64 160, !10, i64 168, !10, i64 176, !10, i64 184, !10, i64 192, !10, i64 200, !38, i64 208, !9, i64 240, !9, i64 244, !9, i64 248, !9, i64 252, !9, i64 256, !10, i64 264, !6, i64 272, !10, i64 280, !7, i64 288}
!32 = !{!"", !33, i64 0, !9, i64 4, !9, i64 8, !9, i64 12, !9, i64 16, !9, i64 20, !9, i64 24, !9, i64 28, !10, i64 32, !10, i64 40}
!33 = !{!"", !9, i64 0, !9, i64 0, !9, i64 0, !9, i64 0, !9, i64 0, !9, i64 0, !9, i64 0, !9, i64 0}
!34 = !{!"rb_iseq_location_struct", !6, i64 0, !6, i64 8, !6, i64 16, !6, i64 24, !9, i64 32, !35, i64 36}
!35 = !{!"rb_code_location_struct", !36, i64 0, !36, i64 8}
!36 = !{!"rb_code_position_struct", !9, i64 0, !9, i64 4}
!37 = !{!"iseq_insn_info", !10, i64 0, !10, i64 8, !9, i64 16, !10, i64 24}
!38 = !{!"", !6, i64 0, !6, i64 8, !6, i64 16, !10, i64 24}
!39 = !DILocation(line: 5, column: 1, scope: !17)
!40 = !{!"branch_weights", i32 2000, i32 1}
!41 = !DILocation(line: 6, column: 3, scope: !17)
!42 = distinct !DISubprogram(name: "Object#boo", linkageName: "func_Object#boo", scope: null, file: !2, line: 9, type: !18, scopeLine: 9, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!43 = !DILocation(line: 9, column: 1, scope: !42)
!44 = !DILocation(line: 9, column: 10, scope: !42)
!45 = !DILocation(line: 10, column: 3, scope: !42)
!46 = distinct !DISubprogram(name: "Object#bar", linkageName: "func_Object#bar", scope: null, file: !2, line: 13, type: !18, scopeLine: 13, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!47 = !DILocation(line: 13, column: 1, scope: !46)
!48 = !DILocation(line: 13, column: 10, scope: !46)
!49 = !DILocation(line: 14, column: 3, scope: !46)
!50 = !{!23, !6, i64 128}
!51 = !{!52}
!52 = distinct !{!52, !53, !"sorbet_callFuncProcWithCache: argument 0"}
!53 = distinct !{!53, !"sorbet_callFuncProcWithCache"}
!54 = distinct !DISubprogram(name: "Object#baz", linkageName: "func_Object#baz", scope: null, file: !2, line: 17, type: !18, scopeLine: 17, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!55 = !DILocation(line: 17, column: 1, scope: !54)
!56 = !DILocation(line: 17, column: 10, scope: !54)
!57 = !DILocation(line: 18, column: 12, scope: !54)
!58 = !DILocation(line: 18, column: 3, scope: !54)
!59 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.<static-init>$153$block_1", scope: !60, file: !2, line: 5, type: !18, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!60 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.<static-init>$153", scope: null, file: !2, line: 5, type: !18, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!61 = !DILocation(line: 5, column: 1, scope: !59)
!62 = !{!63, !6, i64 0}
!63 = !{!"RBasic", !6, i64 0, !6, i64 8}
!64 = !DILocation(line: 21, column: 1, scope: !59)
!65 = !DILocation(line: 22, column: 8, scope: !59)
!66 = !DILocation(line: 22, column: 3, scope: !59)
!67 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.<static-init>$153$block_2", scope: !60, file: !2, line: 5, type: !18, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!68 = !DILocation(line: 5, column: 1, scope: !67)
!69 = !DILocation(line: 25, column: 1, scope: !67)
!70 = !DILocation(line: 26, column: 8, scope: !67)
!71 = !DILocation(line: 26, column: 3, scope: !67)
!72 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.<static-init>$153$block_3", scope: !60, file: !2, line: 5, type: !18, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!73 = !DILocation(line: 5, column: 1, scope: !72)
!74 = !DILocation(line: 29, column: 1, scope: !72)
!75 = !DILocation(line: 30, column: 8, scope: !72)
!76 = !DILocation(line: 30, column: 3, scope: !72)
!77 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.<static-init>$153$block_4", scope: !60, file: !2, line: 5, type: !18, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!78 = !DILocation(line: 5, column: 1, scope: !77)
!79 = !DILocation(line: 33, column: 1, scope: !77)
!80 = !{!81, !6, i64 400}
!81 = !{!"rb_vm_struct", !6, i64 0, !82, i64 8, !10, i64 192, !10, i64 200, !10, i64 208, !85, i64 216, !7, i64 224, !83, i64 264, !83, i64 280, !83, i64 296, !83, i64 312, !6, i64 328, !9, i64 336, !9, i64 340, !9, i64 340, !9, i64 340, !9, i64 340, !9, i64 344, !6, i64 352, !7, i64 360, !6, i64 400, !6, i64 408, !6, i64 416, !6, i64 424, !6, i64 432, !6, i64 440, !6, i64 448, !10, i64 456, !10, i64 464, !86, i64 472, !87, i64 1064, !10, i64 1088, !10, i64 1096, !9, i64 1104, !9, i64 1108, !83, i64 1112, !7, i64 1128, !6, i64 1168, !6, i64 1176, !6, i64 1184, !6, i64 1192, !6, i64 1200, !9, i64 1208, !6, i64 1216, !10, i64 1224, !10, i64 1232, !10, i64 1240, !10, i64 1248, !88, i64 1256, !7, i64 1288}
!82 = !{!"rb_global_vm_lock_struct", !10, i64 0, !7, i64 8, !83, i64 48, !10, i64 64, !9, i64 72, !7, i64 80, !7, i64 128, !9, i64 176, !9, i64 180}
!83 = !{!"list_head", !84, i64 0}
!84 = !{!"list_node", !10, i64 0, !10, i64 8}
!85 = !{!"long long", !7, i64 0}
!86 = !{!"", !7, i64 0, !7, i64 520}
!87 = !{!"rb_hook_list_struct", !10, i64 0, !9, i64 8, !9, i64 12, !9, i64 16}
!88 = !{!"", !6, i64 0, !6, i64 8, !6, i64 16, !6, i64 24}
!89 = !DILocation(line: 5, column: 1, scope: !60)
!90 = !DILocation(line: 9, column: 1, scope: !60)
!91 = !DILocation(line: 13, column: 1, scope: !60)
!92 = !DILocation(line: 17, column: 1, scope: !60)
!93 = !DILocation(line: 21, column: 1, scope: !60)
!94 = !{!95}
!95 = distinct !{!95, !96, !"sorbet_callFuncBlockWithCache: argument 0"}
!96 = distinct !{!96, !"sorbet_callFuncBlockWithCache"}
!97 = !DILocation(line: 25, column: 1, scope: !60)
!98 = !{!99}
!99 = distinct !{!99, !100, !"sorbet_callFuncBlockWithCache: argument 0"}
!100 = distinct !{!100, !"sorbet_callFuncBlockWithCache"}
!101 = !DILocation(line: 29, column: 1, scope: !60)
!102 = !{!103}
!103 = distinct !{!103, !104, !"sorbet_callFuncBlockWithCache: argument 0"}
!104 = distinct !{!104, !"sorbet_callFuncBlockWithCache"}
!105 = !DILocation(line: 33, column: 1, scope: !60)
!106 = !{!107}
!107 = distinct !{!107, !108, !"sorbet_callFuncBlockWithCache: argument 0"}
!108 = distinct !{!108, !"sorbet_callFuncBlockWithCache"}
