; ModuleID = 'payload'
source_filename = "llvm-link"
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"

%struct.rb_vm_struct = type { i64, %struct.rb_global_vm_lock_struct, %struct.rb_thread_struct*, %struct.rb_thread_struct*, i8*, i64, %union.pthread_mutex_t, %union.anon.12, %union.anon.12, %union.anon.12, %union.anon.12, i64, i32, i8, i32, i64, [5 x i64], i64, i64, i64, i64, i64, i64, i64, %struct.st_table*, %struct.st_table*, %struct.anon.18, %struct.rb_hook_list_struct, %struct.st_table*, %struct.rb_postponed_job_struct*, i32, i32, %union.anon.12, %union.pthread_mutex_t, i64, i64, i64, i64, i64, i32, i64, %struct.rb_objspace*, %struct.rb_at_exit_list*, i64*, %struct.st_table*, %struct.anon.19, [28 x i16] }
%struct.rb_global_vm_lock_struct = type { %struct.rb_thread_struct*, %union.pthread_mutex_t, %union.anon.12, %struct.rb_thread_struct*, i32, %union.pthread_cond_t, %union.pthread_cond_t, i32, i32 }
%union.pthread_cond_t = type { %struct.anon.14 }
%struct.anon.14 = type { i32, i32, i64, i64, i64, i8*, i32, i32 }
%struct.rb_thread_struct = type { %struct.list_node, i64, %struct.rb_vm_struct*, %struct.rb_execution_context_struct*, i64, %struct.rb_calling_info*, i64, i64, i64, i8, i8, i32, %struct.native_thread_data_struct, i8*, i64, i64, i64, i64, %union.pthread_mutex_t, %struct.rb_unblock_callback, i64, %struct.rb_mutex_struct*, %struct.rb_thread_list_struct*, %union.anon.15, i32, i64, %struct.rb_fiber_struct*, [1 x %struct.__jmp_buf_tag], i64 }
%struct.list_node = type { %struct.list_node*, %struct.list_node* }
%struct.rb_execution_context_struct = type { i64*, i64, %struct.rb_control_frame_struct*, %struct.rb_vm_tag*, %struct.rb_vm_protect_tag*, i32, i32, %struct.rb_fiber_struct*, %struct.rb_thread_struct*, %struct.st_table*, i64, i64, i64*, i64, %struct.rb_ensure_list*, %struct.rb_trace_arg_struct*, i64, i64, i8, i8, i64, %struct.anon.11 }
%struct.rb_control_frame_struct = type { i64*, i64*, %struct.rb_iseq_struct*, i64, i64*, i8*, i64* }
%struct.rb_iseq_struct = type { i64, i64, %struct.rb_iseq_constant_body*, %union.anon.8 }
%struct.rb_iseq_constant_body = type { i32, i32, i64*, %struct.anon.1, %struct.rb_iseq_location_struct, %struct.iseq_insn_info, i64*, %struct.iseq_catch_table*, %struct.rb_iseq_struct*, %struct.rb_iseq_struct*, %union.iseq_inline_storage_entry*, %struct.rb_call_info*, %struct.rb_call_cache*, %struct.anon.7, i32, i32, i32, i32, i32, i64 (%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*)*, i64, %struct.rb_mjit_unit*, i8 }
%struct.anon.1 = type { %struct.anon.2, i32, i32, i32, i32, i32, i32, i32, i64*, %struct.rb_iseq_param_keyword* }
%struct.anon.2 = type { i8, [3 x i8] }
%struct.rb_iseq_param_keyword = type { i32, i32, i32, i32, i64*, i64* }
%struct.rb_iseq_location_struct = type { i64, i64, i64, i64, i32, %struct.rb_code_location_struct }
%struct.rb_code_location_struct = type { %struct.rb_code_position_struct, %struct.rb_code_position_struct }
%struct.rb_code_position_struct = type { i32, i32 }
%struct.iseq_insn_info = type { %struct.rb_code_position_struct*, i32*, i32, %struct.succ_index_table* }
%struct.succ_index_table = type opaque
%struct.iseq_catch_table = type opaque
%union.iseq_inline_storage_entry = type { %struct.iseq_inline_cache_entry }
%struct.iseq_inline_cache_entry = type { i64, %struct.rb_cref_struct*, %union.anon.0 }
%struct.rb_cref_struct = type { i64, i64, i64, %struct.rb_cref_struct*, %struct.anon.2 }
%union.anon.0 = type { i64 }
%struct.rb_call_info = type { i64, i32, i32 }
%struct.rb_call_cache = type { i64, i64, %struct.rb_callable_method_entry_struct*, i64 (%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_calling_info*, %struct.rb_call_info*, %struct.rb_call_cache*)*, %union.anon.6 }
%struct.rb_callable_method_entry_struct = type { i64, i64, %struct.rb_method_definition_struct*, i64, i64 }
%struct.rb_method_definition_struct = type { i64, %union.anon.5, i64 }
%union.anon.5 = type { %struct.rb_method_cfunc_struct }
%struct.rb_method_cfunc_struct = type { i64 (...)*, i64 (i64 (...)*, i64, i32, i64*)*, i32 }
%union.anon.6 = type { i32 }
%struct.anon.7 = type { i64, i64, i64, i64* }
%struct.rb_mjit_unit = type opaque
%union.anon.8 = type { %struct.anon.9 }
%struct.anon.9 = type { i64, i32 }
%struct.rb_vm_tag = type { i64, i64, [1 x %struct.__jmp_buf_tag], %struct.rb_vm_tag*, i32 }
%struct.rb_vm_protect_tag = type { %struct.rb_vm_protect_tag* }
%struct.rb_ensure_list = type { %struct.rb_ensure_list*, %struct.rb_ensure_entry }
%struct.rb_ensure_entry = type { i64, i64 (...)*, i64 }
%struct.rb_trace_arg_struct = type { i32, %struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, i64, i64, i64, i64, i64, i32, i32, i64 }
%struct.anon.11 = type { i64*, i64*, i64, [1 x %struct.__jmp_buf_tag] }
%struct.rb_calling_info = type { i64, i64, i32 }
%struct.native_thread_data_struct = type { %union.anon.12, %union.anon.13 }
%union.anon.13 = type { %union.pthread_cond_t }
%struct.rb_unblock_callback = type { void (i8*)*, i8* }
%struct.rb_mutex_struct = type opaque
%struct.rb_thread_list_struct = type { %struct.rb_thread_list_struct*, %struct.rb_thread_struct* }
%union.anon.15 = type { %struct.RBasic }
%struct.RBasic = type { i64, i64 }
%struct.rb_fiber_struct = type opaque
%struct.__jmp_buf_tag = type { [8 x i64], i32, %struct.__sigset_t }
%struct.__sigset_t = type { [16 x i64] }
%struct.anon.18 = type { [65 x i64], [65 x i8] }
%struct.rb_hook_list_struct = type { %struct.rb_event_hook_struct*, i32, i32, i32 }
%struct.rb_event_hook_struct = type opaque
%struct.rb_postponed_job_struct = type opaque
%union.anon.12 = type { %struct.list_node }
%union.pthread_mutex_t = type { %struct.__pthread_mutex_s }
%struct.__pthread_mutex_s = type { i32, i32, i32, i32, i32, i16, i16, %struct.__pthread_internal_list }
%struct.__pthread_internal_list = type { %struct.__pthread_internal_list*, %struct.__pthread_internal_list* }
%struct.rb_objspace = type opaque
%struct.rb_at_exit_list = type { void (%struct.rb_vm_struct*)*, %struct.rb_at_exit_list* }
%struct.st_table = type { i8, i8, i8, i32, %struct.st_hash_type*, i64, i64*, i64, i64, %struct.st_table_entry* }
%struct.st_hash_type = type { i32 (...)*, i64 (...)* }
%struct.st_table_entry = type opaque
%struct.anon.19 = type { i64, i64, i64, i64 }
%struct.FunctionInlineCache = type { %struct.rb_callable_method_entry_struct*, i64, i64 }

@rb_eRuntimeError = external local_unnamed_addr global i64, align 8
@.str.1 = private unnamed_addr constant [95 x i8] c"sorbet_getBuildSCMRevision: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@.str.2 = private unnamed_addr constant [93 x i8] c"sorbet_getIsReleaseBuild: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@ruby_current_vm_ptr = external local_unnamed_addr global %struct.rb_vm_struct*, align 8
@ruby_current_execution_context_ptr = external local_unnamed_addr global %struct.rb_execution_context_struct*, align 8
@.str.17 = private unnamed_addr constant [24 x i8] c"$__sorbet_ruby_realpath\00", align 1
@.str.18 = private unnamed_addr constant [63 x i8] c"Invalid '$__sorbet_ruby_realpath' when loading compiled module\00", align 1
@"stackFramePrecomputed_func_Object#hello" = internal unnamed_addr global i8* null, align 8
@rubyIdPrecomputed_hello = internal unnamed_addr global i64 0, align 8
@str_hello = private unnamed_addr constant [6 x i8] c"hello\00", align 1
@rubyStrFrozen_hello = internal unnamed_addr global i64 0, align 8
@"rubyStrFrozen_test/testdata/compiler/method.rb" = internal unnamed_addr global i64 0, align 8
@"str_test/testdata/compiler/method.rb" = private unnamed_addr constant [33 x i8] c"test/testdata/compiler/method.rb\00", align 1
@str_Object = private unnamed_addr constant [7 x i8] c"Object\00", align 1
@str_cast = private unnamed_addr constant [5 x i8] c"cast\00", align 1
@"rubyIdPrecomputed_<" = internal unnamed_addr global i64 0, align 8
@"str_<" = private unnamed_addr constant [2 x i8] c"<\00", align 1
@"ic_call_via_vm_<" = internal global %struct.FunctionInlineCache zeroinitializer
@"rubyStrFrozen_hello " = internal unnamed_addr global i64 0, align 8
@"str_hello " = private unnamed_addr constant [7 x i8] c"hello \00", align 1
@"rubyIdPrecomputed_+" = internal unnamed_addr global i64 0, align 8
@"str_+" = private unnamed_addr constant [2 x i8] c"+\00", align 1
@"ic_call_via_vm_+" = internal global %struct.FunctionInlineCache zeroinitializer
@ic_call_via_vm_puts = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_puts = internal unnamed_addr global i64 0, align 8
@str_puts = private unnamed_addr constant [5 x i8] c"puts\00", align 1
@"ic_call_via_vm_+.1" = internal global %struct.FunctionInlineCache zeroinitializer
@"stackFramePrecomputed_func_<root>.<static-init>$153" = internal unnamed_addr global i8* null, align 8
@"rubyIdPrecomputed_<top (required)>" = internal unnamed_addr global i64 0, align 8
@"str_<top (required)>" = private unnamed_addr constant [17 x i8] c"<top (required)>\00", align 1
@"str_T.class_of(<root>)" = private unnamed_addr constant [19 x i8] c"T.class_of(<root>)\00", align 1
@str_keep_def = private unnamed_addr constant [9 x i8] c"keep_def\00", align 1
@rubyStrFrozen_sorbet = internal unnamed_addr global i64 0, align 8
@str_sorbet = private unnamed_addr constant [7 x i8] c"sorbet\00", align 1
@ic_call_via_vm_hello = internal global %struct.FunctionInlineCache zeroinitializer
@rb_cObject = external local_unnamed_addr constant i64

declare i64 @rb_str_plus(i64, i64) local_unnamed_addr #0

; Function Attrs: nounwind ssp uwtable
define weak i8* @sorbet_getBuildSCMRevision() local_unnamed_addr #1 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !4
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* getelementptr inbounds ([95 x i8], [95 x i8]* @.str.1, i64 0, i64 0)) #13
  unreachable
}

; Function Attrs: noreturn
declare void @rb_raise(i64, i8*, ...) local_unnamed_addr #2

; Function Attrs: nounwind ssp uwtable
define weak i32 @sorbet_getIsReleaseBuild() local_unnamed_addr #1 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !4
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* getelementptr inbounds ([93 x i8], [93 x i8]* @.str.2, i64 0, i64 0)) #13
  unreachable
}

declare i64 @rb_fstring_new(i8*, i64) local_unnamed_addr #0

declare void @rb_gc_register_mark_object(i64) local_unnamed_addr #0

declare i64 @rb_intern2(i8*, i64) local_unnamed_addr #0

declare i64 @rb_id2sym(i64) local_unnamed_addr #0

declare void @rb_define_method(i64, i8*, i64 (...)*, i32) local_unnamed_addr #0

; Function Attrs: cold noreturn nounwind optsize ssp uwtable
declare void @sorbet_cast_failure(i64, i8*, i8*) local_unnamed_addr #3

; Function Attrs: noreturn nounwind ssp uwtable
declare void @sorbet_raiseArity(i32, i32, i32) local_unnamed_addr #4

; Function Attrs: nounwind ssp uwtable
declare i8* @sorbet_allocateRubyStackFrame(i64, i64, i64, i64, i8*, i32, i32, i32) local_unnamed_addr #1

declare i64 @rb_gv_get(i8*) local_unnamed_addr #0

declare i64 @rb_gv_set(i8*, i64) local_unnamed_addr #0

declare %struct.rb_control_frame_struct* @rb_vm_push_frame(%struct.rb_execution_context_struct*, %struct.rb_iseq_struct*, i64, i64, i64, i64, i64*, i64*, i32, i32) local_unnamed_addr #0

declare i64 @rb_errinfo() local_unnamed_addr #0

; Function Attrs: nounwind readnone
declare i64 @rb_obj_is_kind_of(i64, i64) local_unnamed_addr #5

; Function Attrs: nounwind readnone speculatable
declare { i64, i1 } @llvm.sadd.with.overflow.i64(i64, i64) #6

declare i64 @rb_int2big(i64) local_unnamed_addr #0

; Function Attrs: noinline nounwind ssp uwtable
declare i64 @sorbet_callFunc(i64, i64, i32, i64* noalias nocapture, %struct.FunctionInlineCache* nocapture) local_unnamed_addr #7

; Function Attrs: nounwind sspreq uwtable
define i64 @"func_Object#hello"(i32 %argc, i64* nocapture readonly %argArray, i64 %selfRaw) #8 !dbg !8 {
functionEntryInitializers:
  %callArgs = alloca [1 x i64], align 8
  %"stackFrame_func_Object#hello" = load i8*, i8** @"stackFramePrecomputed_func_Object#hello", align 8
  %0 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !12
  %1 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %0, i64 0, i32 2
  %2 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %1, align 8, !tbaa !14
  %3 = getelementptr inbounds i8, i8* %"stackFrame_func_Object#hello", i64 16
  %4 = bitcast i8* %3 to %struct.rb_iseq_constant_body**
  %5 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %4, align 8, !tbaa !18
  %6 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %5, i64 0, i32 0
  %7 = load i32, i32* %6, align 8, !tbaa !20
  %8 = and i32 %7, -2
  %9 = icmp eq i32 %8, 4
  br i1 %9, label %10, label %36

10:                                               ; preds = %functionEntryInitializers
  %11 = bitcast i8* %"stackFrame_func_Object#hello" to %struct.rb_iseq_struct*
  %12 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 3
  %13 = load i64, i64* %12, align 8, !tbaa !29
  %14 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 1
  %15 = load i64*, i64** %14, align 8, !tbaa !31
  %16 = getelementptr inbounds i64, i64* %15, i64 1
  %17 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %5, i64 0, i32 14
  %18 = load i32, i32* %17, align 8, !tbaa !32
  %19 = add i32 %18, -1
  %20 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 4
  %21 = bitcast i64** %20 to i64*
  %22 = load i64, i64* %21, align 8, !tbaa !33
  %23 = or i64 %22, 1
  %24 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %5, i64 0, i32 2
  %25 = load i64*, i64** %24, align 8, !tbaa !34
  %26 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %5, i64 0, i32 18
  %27 = load i32, i32* %26, align 8, !tbaa !35
  %28 = tail call %struct.rb_control_frame_struct* @rb_vm_push_frame(%struct.rb_execution_context_struct* %0, %struct.rb_iseq_struct* %11, i64 2022178817, i64 %13, i64 %23, i64 0, i64* %25, i64* nonnull %16, i32 %19, i32 %27) #14
  %29 = tail call i64 @rb_errinfo() #14
  %30 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !12
  %31 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %30, i64 0, i32 2
  %32 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %31, align 8, !tbaa !14
  %33 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %32, i64 0, i32 4
  %34 = load i64*, i64** %33, align 8, !tbaa !33
  %35 = getelementptr inbounds i64, i64* %34, i64 -3
  store i64 %29, i64* %35, align 8, !tbaa !4
  br label %sorbet_setRubyStackFrame.exit

36:                                               ; preds = %functionEntryInitializers
  %37 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 2
  %38 = bitcast %struct.rb_iseq_struct** %37 to i8**
  store i8* %"stackFrame_func_Object#hello", i8** %38, align 8, !tbaa !36
  %39 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 4
  %40 = load i64*, i64** %39, align 8, !tbaa !33
  %41 = load i64, i64* %40, align 8, !tbaa !4
  %42 = and i64 %41, -129
  store i64 %42, i64* %40, align 8, !tbaa !4
  br label %sorbet_setRubyStackFrame.exit

sorbet_setRubyStackFrame.exit:                    ; preds = %10, %36
  %43 = phi %struct.rb_control_frame_struct* [ %28, %10 ], [ %2, %36 ]
  %44 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %43, i64 0, i32 0
  %45 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %4, align 8, !tbaa !18
  %46 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %45, i64 0, i32 2
  %47 = load i64*, i64** %46, align 8, !tbaa !34
  %48 = getelementptr inbounds i64, i64* %47, i64 1
  store i64* %48, i64** %44, align 8, !tbaa !12
  %"rubyId_<" = load i64, i64* @"rubyIdPrecomputed_<", align 8, !dbg !37
  %"rubyStr_hello " = load i64, i64* @"rubyStrFrozen_hello ", align 8, !dbg !38
  %"rubyId_+" = load i64, i64* @"rubyIdPrecomputed_+", align 8, !dbg !38
  %rubyId_puts = load i64, i64* @rubyIdPrecomputed_puts, align 8, !dbg !39
  %49 = icmp eq i32 %argc, 1, !dbg !40
  br i1 %49, label %fillRequiredArgs, label %argCountFailBlock, !dbg !40, !prof !41

BB2:                                              ; preds = %typeTestSuccess, %BB2.backedge
  %i.sroa.0.0 = phi i64 [ %i.sroa.0.0.be, %BB2.backedge ], [ 1, %typeTestSuccess ], !dbg !42
  store i64* %59, i64** %44, align 8, !tbaa !12
  %50 = and i64 %i.sroa.0.0, 1, !dbg !37
  %51 = icmp ne i64 %50, 0, !dbg !37
  store i64 21, i64* %callArgs0Addr, align 8, !dbg !37
  br i1 %51, label %"fastSymCallIntrinsic_Integer_<", label %"alternativeCallIntrinsic_Integer_<", !dbg !37, !prof !43

BB3:                                              ; preds = %afterSend, %afterSend.us
  store i64* %48, i64** %44, align 8, !dbg !44, !tbaa !12
  ret i64 8

BB5:                                              ; preds = %afterSend
  store i64* %60, i64** %44, align 8, !tbaa !12
  %52 = load i64, i64* %67, align 8, !dbg !38, !tbaa !45
  %53 = and i64 %52, 31, !dbg !38
  %54 = icmp eq i64 %53, 5, !dbg !38
  store i64 %rawArg_name, i64* %callArgs0Addr, align 8, !dbg !38
  br i1 %54, label %"fastSymCallIntrinsic_String_+", label %"alternativeCallIntrinsic_String_+", !dbg !38, !prof !43

argCountFailBlock:                                ; preds = %sorbet_setRubyStackFrame.exit
  tail call void @sorbet_raiseArity(i32 %argc, i32 1, i32 1), !dbg !40
  unreachable, !dbg !40

fillRequiredArgs:                                 ; preds = %sorbet_setRubyStackFrame.exit
  %rawArg_name = load i64, i64* %argArray, align 8, !dbg !40
  %55 = load i64, i64* @rb_cObject, align 8, !dbg !40
  %56 = tail call i64 @rb_obj_is_kind_of(i64 %selfRaw, i64 %55) #5, !dbg !40
  %57 = icmp eq i64 %56, 20, !dbg !40
  br i1 %57, label %typeTestSuccess, label %codeRepl, !dbg !40, !prof !43

typeTestSuccess:                                  ; preds = %fillRequiredArgs
  %58 = getelementptr inbounds i64, i64* %47, i64 2, !dbg !47
  store i64* %58, i64** %44, align 8, !dbg !47, !tbaa !12
  %59 = getelementptr inbounds i64, i64* %47, i64 3
  %callArgs0Addr = getelementptr inbounds [1 x i64], [1 x i64]* %callArgs, i64 0, i64 0, !dbg !42
  %60 = getelementptr inbounds i64, i64* %47, i64 4
  %61 = and i64 %"rubyStr_hello ", 7, !dbg !42
  %62 = icmp ne i64 %61, 0, !dbg !42
  %63 = and i64 %"rubyStr_hello ", -9, !dbg !42
  %64 = icmp eq i64 %63, 0, !dbg !42
  %65 = or i1 %62, %64, !dbg !42
  %66 = inttoptr i64 %"rubyStr_hello " to %struct.RBasic*, !dbg !42
  %67 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %66, i64 0, i32 0, !dbg !42
  %68 = getelementptr inbounds i64, i64* %47, i64 5, !dbg !42
  br i1 %65, label %BB2.us, label %BB2, !dbg !48, !prof !49

BB2.us:                                           ; preds = %typeTestSuccess, %BB2.us.backedge
  %i.sroa.0.0.us = phi i64 [ %i.sroa.0.0.us.be, %BB2.us.backedge ], [ 1, %typeTestSuccess ], !dbg !42
  store i64* %59, i64** %44, align 8, !tbaa !12
  %69 = and i64 %i.sroa.0.0.us, 1, !dbg !37
  %70 = icmp ne i64 %69, 0, !dbg !37
  store i64 21, i64* %callArgs0Addr, align 8, !dbg !37
  br i1 %70, label %"fastSymCallIntrinsic_Integer_<.us", label %"alternativeCallIntrinsic_Integer_<.us", !dbg !37, !prof !43

"alternativeCallIntrinsic_Integer_<.us":          ; preds = %BB2.us
  %"call_via_vm_<.us" = call i64 @sorbet_callFunc(i64 %i.sroa.0.0.us, i64 %"rubyId_<", i32 1, i64* nonnull %callArgs0Addr, %struct.FunctionInlineCache* nonnull @"ic_call_via_vm_<"), !dbg !37
  br label %afterSend.us, !dbg !37

"fastSymCallIntrinsic_Integer_<.us":              ; preds = %BB2.us
  %71 = icmp slt i64 %i.sroa.0.0.us, 20, !dbg !37
  %72 = select i1 %71, i64 20, i64 0, !dbg !37
  br label %afterSend.us, !dbg !37

afterSend.us:                                     ; preds = %"fastSymCallIntrinsic_Integer_<.us", %"alternativeCallIntrinsic_Integer_<.us"
  %"symIntrinsicRawPhi_<.us" = phi i64 [ %"call_via_vm_<.us", %"alternativeCallIntrinsic_Integer_<.us" ], [ %72, %"fastSymCallIntrinsic_Integer_<.us" ], !dbg !37
  %73 = and i64 %"symIntrinsicRawPhi_<.us", -9, !dbg !37
  %74 = icmp eq i64 %73, 0, !dbg !37
  br i1 %74, label %BB3, label %BB5.us, !dbg !37

BB5.us:                                           ; preds = %afterSend.us
  store i64* %60, i64** %44, align 8, !tbaa !12
  store i64 %rawArg_name, i64* %callArgs0Addr, align 8, !dbg !38
  %"call_via_vm_+.us" = call i64 @sorbet_callFunc(i64 %"rubyStr_hello ", i64 %"rubyId_+", i32 1, i64* nonnull %callArgs0Addr, %struct.FunctionInlineCache* nonnull @"ic_call_via_vm_+"), !dbg !38
  store i64 %"call_via_vm_+.us", i64* %callArgs0Addr, align 8, !dbg !39
  %call_via_vm_puts.us = call i64 @sorbet_callFunc(i64 %selfRaw, i64 %rubyId_puts, i32 1, i64* nonnull %callArgs0Addr, %struct.FunctionInlineCache* nonnull @ic_call_via_vm_puts), !dbg !39
  store i64* %68, i64** %44, align 8, !dbg !39, !tbaa !12
  store i64 3, i64* %callArgs0Addr, align 8, !dbg !50
  br i1 %70, label %"fastSymCallIntrinsic_Integer_+.us", label %"alternativeCallIntrinsic_Integer_+.us", !dbg !50

"alternativeCallIntrinsic_Integer_+.us":          ; preds = %BB5.us
  %"call_via_vm_+58.us" = call i64 @sorbet_callFunc(i64 %i.sroa.0.0.us, i64 %"rubyId_+", i32 1, i64* nonnull %callArgs0Addr, %struct.FunctionInlineCache* nonnull @"ic_call_via_vm_+.1"), !dbg !50
  br label %BB2.us.backedge, !dbg !50

"fastSymCallIntrinsic_Integer_+.us":              ; preds = %BB5.us
  %75 = tail call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %i.sroa.0.0.us, i64 2) #14, !dbg !50
  %76 = extractvalue { i64, i1 } %75, 1, !dbg !50
  %77 = extractvalue { i64, i1 } %75, 0, !dbg !50
  br i1 %76, label %78, label %BB2.us.backedge, !dbg !50

78:                                               ; preds = %"fastSymCallIntrinsic_Integer_+.us"
  %79 = ashr i64 %77, 1, !dbg !50
  %80 = xor i64 %79, -9223372036854775808, !dbg !50
  %81 = tail call i64 @rb_int2big(i64 %80) #14, !dbg !50
  br label %BB2.us.backedge, !dbg !50

BB2.us.backedge:                                  ; preds = %78, %"fastSymCallIntrinsic_Integer_+.us", %"alternativeCallIntrinsic_Integer_+.us"
  %i.sroa.0.0.us.be = phi i64 [ %"call_via_vm_+58.us", %"alternativeCallIntrinsic_Integer_+.us" ], [ %81, %78 ], [ %77, %"fastSymCallIntrinsic_Integer_+.us" ]
  br label %BB2.us

codeRepl:                                         ; preds = %fillRequiredArgs
  tail call fastcc void @"func_Object#hello.cold.1"(i64 %selfRaw) #15, !dbg !40
  unreachable

afterSend:                                        ; preds = %"fastSymCallIntrinsic_Integer_<", %"alternativeCallIntrinsic_Integer_<"
  %"symIntrinsicRawPhi_<" = phi i64 [ %"call_via_vm_<", %"alternativeCallIntrinsic_Integer_<" ], [ %85, %"fastSymCallIntrinsic_Integer_<" ], !dbg !37
  %82 = and i64 %"symIntrinsicRawPhi_<", -9, !dbg !37
  %83 = icmp eq i64 %82, 0, !dbg !37
  br i1 %83, label %BB3, label %BB5, !dbg !37

"alternativeCallIntrinsic_Integer_<":             ; preds = %BB2
  %"call_via_vm_<" = call i64 @sorbet_callFunc(i64 %i.sroa.0.0, i64 %"rubyId_<", i32 1, i64* nonnull %callArgs0Addr, %struct.FunctionInlineCache* nonnull @"ic_call_via_vm_<"), !dbg !37
  br label %afterSend, !dbg !37

"fastSymCallIntrinsic_Integer_<":                 ; preds = %BB2
  %84 = icmp slt i64 %i.sroa.0.0, 20, !dbg !37
  %85 = select i1 %84, i64 20, i64 0, !dbg !37
  br label %afterSend, !dbg !37

afterSend30:                                      ; preds = %"alternativeCallIntrinsic_String_+", %"fastSymCallIntrinsic_String_+"
  %"symIntrinsicRawPhi_+" = phi i64 [ %86, %"fastSymCallIntrinsic_String_+" ], [ %"call_via_vm_+", %"alternativeCallIntrinsic_String_+" ], !dbg !38
  store i64 %"symIntrinsicRawPhi_+", i64* %callArgs0Addr, align 8, !dbg !39
  %call_via_vm_puts = call i64 @sorbet_callFunc(i64 %selfRaw, i64 %rubyId_puts, i32 1, i64* nonnull %callArgs0Addr, %struct.FunctionInlineCache* nonnull @ic_call_via_vm_puts), !dbg !39
  store i64* %68, i64** %44, align 8, !dbg !39, !tbaa !12
  store i64 3, i64* %callArgs0Addr, align 8, !dbg !50
  br i1 %51, label %"fastSymCallIntrinsic_Integer_+", label %"alternativeCallIntrinsic_Integer_+", !dbg !50

"alternativeCallIntrinsic_String_+":              ; preds = %BB5
  %"call_via_vm_+" = call i64 @sorbet_callFunc(i64 %"rubyStr_hello ", i64 %"rubyId_+", i32 1, i64* nonnull %callArgs0Addr, %struct.FunctionInlineCache* nonnull @"ic_call_via_vm_+"), !dbg !38
  br label %afterSend30, !dbg !38

"fastSymCallIntrinsic_String_+":                  ; preds = %BB5
  %86 = tail call i64 @rb_str_plus(i64 %"rubyStr_hello ", i64 %rawArg_name) #14, !dbg !38, !noalias !51
  br label %afterSend30, !dbg !38

"alternativeCallIntrinsic_Integer_+":             ; preds = %afterSend30
  %"call_via_vm_+58" = call i64 @sorbet_callFunc(i64 %i.sroa.0.0, i64 %"rubyId_+", i32 1, i64* nonnull %callArgs0Addr, %struct.FunctionInlineCache* nonnull @"ic_call_via_vm_+.1"), !dbg !50
  br label %BB2.backedge, !dbg !50

"fastSymCallIntrinsic_Integer_+":                 ; preds = %afterSend30
  %87 = tail call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %i.sroa.0.0, i64 2) #14, !dbg !50
  %88 = extractvalue { i64, i1 } %87, 1, !dbg !50
  %89 = extractvalue { i64, i1 } %87, 0, !dbg !50
  br i1 %88, label %90, label %BB2.backedge, !dbg !50

90:                                               ; preds = %"fastSymCallIntrinsic_Integer_+"
  %91 = ashr i64 %89, 1, !dbg !50
  %92 = xor i64 %91, -9223372036854775808, !dbg !50
  %93 = tail call i64 @rb_int2big(i64 %92) #14, !dbg !50
  br label %BB2.backedge, !dbg !50

BB2.backedge:                                     ; preds = %90, %"fastSymCallIntrinsic_Integer_+", %"alternativeCallIntrinsic_Integer_+"
  %i.sroa.0.0.be = phi i64 [ %"call_via_vm_+58", %"alternativeCallIntrinsic_Integer_+" ], [ %93, %90 ], [ %89, %"fastSymCallIntrinsic_Integer_+" ]
  br label %BB2
}

; Function Attrs: nounwind sspreq
define void @Init_method() local_unnamed_addr #9 {
entry:
  %callArgs.i = alloca [2 x i64], align 8
  %0 = tail call i64 @rb_gv_get(i8* getelementptr inbounds ([24 x i8], [24 x i8]* @.str.17, i64 0, i64 0)) #14
  %1 = and i64 %0, 7
  %2 = icmp ne i64 %1, 0
  %3 = and i64 %0, -9
  %4 = icmp eq i64 %3, 0
  %5 = or i1 %2, %4
  br i1 %5, label %12, label %6

6:                                                ; preds = %entry
  %7 = inttoptr i64 %0 to %struct.RBasic*
  %8 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %7, i64 0, i32 0
  %9 = load i64, i64* %8, align 8, !tbaa !45
  %10 = and i64 %9, 31
  %11 = icmp eq i64 %10, 5
  br i1 %11, label %sorbet_readRealpath.exit, label %12

12:                                               ; preds = %6, %entry
  %13 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !4
  tail call void (i64, i8*, ...) @rb_raise(i64 %13, i8* getelementptr inbounds ([63 x i8], [63 x i8]* @.str.18, i64 0, i64 0)) #13
  unreachable

sorbet_readRealpath.exit:                         ; preds = %6
  %14 = tail call i64 @rb_gv_set(i8* getelementptr inbounds ([24 x i8], [24 x i8]* @.str.17, i64 0, i64 0), i64 8) #14
  %15 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([6 x i8], [6 x i8]* @str_hello, i64 0, i64 0), i64 5) #14
  store i64 %15, i64* @rubyIdPrecomputed_hello, align 8
  %16 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([6 x i8], [6 x i8]* @str_hello, i64 0, i64 0), i64 5) #14
  tail call void @rb_gc_register_mark_object(i64 %16) #14
  store i64 %16, i64* @rubyStrFrozen_hello, align 8
  %17 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([33 x i8], [33 x i8]* @"str_test/testdata/compiler/method.rb", i64 0, i64 0), i64 32) #14
  tail call void @rb_gc_register_mark_object(i64 %17) #14
  store i64 %17, i64* @"rubyStrFrozen_test/testdata/compiler/method.rb", align 8
  %rubyId_hello.i.i = load i64, i64* @rubyIdPrecomputed_hello, align 8
  %rubyStr_hello.i.i = load i64, i64* @rubyStrFrozen_hello, align 8
  %18 = tail call i8* @sorbet_allocateRubyStackFrame(i64 %rubyStr_hello.i.i, i64 %rubyId_hello.i.i, i64 %17, i64 %0, i8* null, i32 1, i32 4, i32 10) #14
  store i8* %18, i8** @"stackFramePrecomputed_func_Object#hello", align 8
  %19 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([2 x i8], [2 x i8]* @"str_<", i64 0, i64 0), i64 1) #14
  store i64 %19, i64* @"rubyIdPrecomputed_<", align 8
  %20 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([7 x i8], [7 x i8]* @"str_hello ", i64 0, i64 0), i64 6) #14
  tail call void @rb_gc_register_mark_object(i64 %20) #14
  store i64 %20, i64* @"rubyStrFrozen_hello ", align 8
  %21 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([2 x i8], [2 x i8]* @"str_+", i64 0, i64 0), i64 1) #14
  store i64 %21, i64* @"rubyIdPrecomputed_+", align 8
  %22 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_puts, i64 0, i64 0), i64 4) #14
  store i64 %22, i64* @rubyIdPrecomputed_puts, align 8
  %23 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 16) #14
  store i64 %23, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %24 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 16) #14
  tail call void @rb_gc_register_mark_object(i64 %24) #14
  %"rubyId_<top (required)>.i.i" = load i64, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %"rubyStr_test/testdata/compiler/method.rb.i1.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/method.rb", align 8
  %25 = tail call i8* @sorbet_allocateRubyStackFrame(i64 %24, i64 %"rubyId_<top (required)>.i.i", i64 %"rubyStr_test/testdata/compiler/method.rb.i1.i", i64 %0, i8* null, i32 1, i32 4, i32 11) #14
  store i8* %25, i8** @"stackFramePrecomputed_func_<root>.<static-init>$153", align 8
  %26 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([9 x i8], [9 x i8]* @str_keep_def, i64 0, i64 0), i64 8) #14
  %27 = tail call i64 @rb_fstring_new(i8* getelementptr inbounds ([7 x i8], [7 x i8]* @str_sorbet, i64 0, i64 0), i64 6) #14
  tail call void @rb_gc_register_mark_object(i64 %27) #14
  store i64 %27, i64* @rubyStrFrozen_sorbet, align 8
  %28 = load %struct.rb_vm_struct*, %struct.rb_vm_struct** @ruby_current_vm_ptr, align 8, !tbaa !12
  %29 = getelementptr inbounds %struct.rb_vm_struct, %struct.rb_vm_struct* %28, i64 0, i32 17
  %30 = load i64, i64* %29, align 8, !tbaa !54
  %31 = bitcast [2 x i64]* %callArgs.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 16, i8* nonnull %31)
  %"stackFrame_func_<root>.<static-init>$153.i" = load i8*, i8** @"stackFramePrecomputed_func_<root>.<static-init>$153", align 8
  %32 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !12
  %33 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %32, i64 0, i32 2
  %34 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %33, align 8, !tbaa !14
  %35 = getelementptr inbounds i8, i8* %"stackFrame_func_<root>.<static-init>$153.i", i64 16
  %36 = bitcast i8* %35 to %struct.rb_iseq_constant_body**
  %37 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %36, align 8, !tbaa !18
  %38 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %37, i64 0, i32 0
  %39 = load i32, i32* %38, align 8, !tbaa !20
  %40 = and i32 %39, -2
  %41 = icmp eq i32 %40, 4
  br i1 %41, label %42, label %68

42:                                               ; preds = %sorbet_readRealpath.exit
  %43 = bitcast i8* %"stackFrame_func_<root>.<static-init>$153.i" to %struct.rb_iseq_struct*
  %44 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %34, i64 0, i32 3
  %45 = load i64, i64* %44, align 8, !tbaa !29
  %46 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %34, i64 0, i32 1
  %47 = load i64*, i64** %46, align 8, !tbaa !31
  %48 = getelementptr inbounds i64, i64* %47, i64 1
  %49 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %37, i64 0, i32 14
  %50 = load i32, i32* %49, align 8, !tbaa !32
  %51 = add i32 %50, -1
  %52 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %34, i64 0, i32 4
  %53 = bitcast i64** %52 to i64*
  %54 = load i64, i64* %53, align 8, !tbaa !33
  %55 = or i64 %54, 1
  %56 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %37, i64 0, i32 2
  %57 = load i64*, i64** %56, align 8, !tbaa !34
  %58 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %37, i64 0, i32 18
  %59 = load i32, i32* %58, align 8, !tbaa !35
  %60 = tail call %struct.rb_control_frame_struct* @rb_vm_push_frame(%struct.rb_execution_context_struct* %32, %struct.rb_iseq_struct* %43, i64 2022178817, i64 %45, i64 %55, i64 0, i64* %57, i64* nonnull %48, i32 %51, i32 %59) #14
  %61 = tail call i64 @rb_errinfo() #14
  %62 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !12
  %63 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %62, i64 0, i32 2
  %64 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %63, align 8, !tbaa !14
  %65 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %64, i64 0, i32 4
  %66 = load i64*, i64** %65, align 8, !tbaa !33
  %67 = getelementptr inbounds i64, i64* %66, i64 -3
  store i64 %61, i64* %67, align 8, !tbaa !4
  br label %sorbet_setRubyStackFrame.exit.i

68:                                               ; preds = %sorbet_readRealpath.exit
  %69 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %34, i64 0, i32 2
  %70 = bitcast %struct.rb_iseq_struct** %69 to i8**
  store i8* %"stackFrame_func_<root>.<static-init>$153.i", i8** %70, align 8, !tbaa !36
  %71 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %34, i64 0, i32 4
  %72 = load i64*, i64** %71, align 8, !tbaa !33
  %73 = load i64, i64* %72, align 8, !tbaa !4
  %74 = and i64 %73, -129
  store i64 %74, i64* %72, align 8, !tbaa !4
  br label %sorbet_setRubyStackFrame.exit.i

sorbet_setRubyStackFrame.exit.i:                  ; preds = %68, %42
  %75 = phi %struct.rb_control_frame_struct* [ %60, %42 ], [ %34, %68 ]
  %76 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %75, i64 0, i32 0
  %77 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %36, align 8, !tbaa !18
  %78 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %77, i64 0, i32 2
  %79 = load i64*, i64** %78, align 8, !tbaa !34
  %80 = getelementptr inbounds i64, i64* %79, i64 1
  store i64* %80, i64** %76, align 8, !tbaa !12
  %rubyId_hello.i = load i64, i64* @rubyIdPrecomputed_hello, align 8, !dbg !63
  %81 = load %struct.rb_vm_struct*, %struct.rb_vm_struct** @ruby_current_vm_ptr, align 8, !dbg !63, !tbaa !12
  %82 = getelementptr inbounds %struct.rb_vm_struct, %struct.rb_vm_struct* %81, i64 0, i32 17, !dbg !63
  %83 = load i64, i64* %82, align 8, !dbg !63, !tbaa !54
  %84 = icmp eq i64 %83, %30, !dbg !63
  br i1 %84, label %"func_<root>.<static-init>$153.exit", label %codeRepl, !dbg !63, !prof !43

codeRepl:                                         ; preds = %sorbet_setRubyStackFrame.exit.i
  tail call fastcc void @Init_method.cold.1(i64 %30) #15
  unreachable

"func_<root>.<static-init>$153.exit":             ; preds = %sorbet_setRubyStackFrame.exit.i
  %rubyStr_sorbet.i = load i64, i64* @rubyStrFrozen_sorbet, align 8, !dbg !65
  %rawSym.i = tail call i64 @rb_id2sym(i64 %rubyId_hello.i) #14, !dbg !63
  %85 = load i64, i64* @rb_cObject, align 8, !dbg !63
  tail call void @rb_define_method(i64 %85, i8* getelementptr inbounds ([6 x i8], [6 x i8]* @str_hello, i64 0, i64 0), i64 (...)* bitcast (i64 (i32, i64*, i64)* @"func_Object#hello" to i64 (...)*), i32 -1) #14, !dbg !63
  %86 = getelementptr inbounds i64, i64* %79, i64 8, !dbg !63
  store i64* %86, i64** %76, align 8, !dbg !63, !tbaa !12
  %callArgs0Addr19.i = getelementptr inbounds [2 x i64], [2 x i64]* %callArgs.i, i64 0, i64 0, !dbg !66
  store i64 %rubyStr_sorbet.i, i64* %callArgs0Addr19.i, align 8, !dbg !66
  %call_via_vm_hello.i = call i64 @sorbet_callFunc(i64 %30, i64 %rubyId_hello.i, i32 1, i64* nonnull %callArgs0Addr19.i, %struct.FunctionInlineCache* nonnull @ic_call_via_vm_hello) #14, !dbg !66
  call void @llvm.lifetime.end.p0i8(i64 16, i8* nonnull %31)
  ret void
}

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #10

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.end.p0i8(i64 immarg, i8* nocapture) #10

; Function Attrs: cold minsize noreturn nounwind sspreq uwtable
define internal fastcc void @"func_Object#hello.cold.1"(i64 %selfRaw) unnamed_addr #11 {
newFuncRoot:
  tail call void @sorbet_cast_failure(i64 %selfRaw, i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_cast, i64 0, i64 0), i8* getelementptr inbounds ([7 x i8], [7 x i8]* @str_Object, i64 0, i64 0)), !dbg !40
  unreachable, !dbg !40
}

; Function Attrs: cold minsize noreturn nounwind sspreq
define internal fastcc void @Init_method.cold.1(i64) unnamed_addr #12 {
newFuncRoot:
  tail call void @sorbet_cast_failure(i64 %0, i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_cast, i64 0, i64 0), i8* getelementptr inbounds ([19 x i8], [19 x i8]* @"str_T.class_of(<root>)", i64 0, i64 0)) #14, !dbg !63
  unreachable, !dbg !63
}

attributes #0 = { "addedToSilenceEmptyAttrsError" }
attributes #1 = { nounwind ssp uwtable }
attributes #2 = { noreturn }
attributes #3 = { cold noreturn nounwind optsize ssp uwtable }
attributes #4 = { noreturn nounwind ssp uwtable }
attributes #5 = { nounwind readnone }
attributes #6 = { nounwind readnone speculatable }
attributes #7 = { noinline nounwind ssp uwtable }
attributes #8 = { nounwind sspreq uwtable }
attributes #9 = { nounwind sspreq }
attributes #10 = { argmemonly nounwind }
attributes #11 = { cold minsize noreturn nounwind sspreq uwtable }
attributes #12 = { cold minsize noreturn nounwind sspreq }
attributes #13 = { noreturn nounwind }
attributes #14 = { nounwind }
attributes #15 = { noinline }

!llvm.module.flags = !{!0}
!llvm.dbg.cu = !{!1}

!0 = !{i32 2, !"Debug Info Version", i32 3}
!1 = distinct !DICompileUnit(language: DW_LANG_C, file: !2, producer: "Sorbet LLVM", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, enums: !3)
!2 = !DIFile(filename: "test/testdata/compiler/method.rb", directory: ".")
!3 = !{}
!4 = !{!5, !5, i64 0}
!5 = !{!"long", !6, i64 0}
!6 = !{!"omnipotent char", !7, i64 0}
!7 = !{!"Simple C/C++ TBAA"}
!8 = distinct !DISubprogram(name: "Object#hello", linkageName: "func_Object#hello", scope: null, file: !2, line: 4, type: !9, scopeLine: 4, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!9 = !DISubroutineType(types: !10)
!10 = !{!11}
!11 = !DIBasicType(name: "VALUE", size: 64, encoding: DW_ATE_signed)
!12 = !{!13, !13, i64 0}
!13 = !{!"any pointer", !6, i64 0}
!14 = !{!15, !13, i64 16}
!15 = !{!"rb_execution_context_struct", !13, i64 0, !5, i64 8, !13, i64 16, !13, i64 24, !13, i64 32, !16, i64 40, !16, i64 44, !13, i64 48, !13, i64 56, !13, i64 64, !5, i64 72, !5, i64 80, !13, i64 88, !5, i64 96, !13, i64 104, !13, i64 112, !5, i64 120, !5, i64 128, !6, i64 136, !6, i64 137, !5, i64 144, !17, i64 152}
!16 = !{!"int", !6, i64 0}
!17 = !{!"", !13, i64 0, !13, i64 8, !5, i64 16, !6, i64 24}
!18 = !{!19, !13, i64 16}
!19 = !{!"rb_iseq_struct", !5, i64 0, !5, i64 8, !13, i64 16, !6, i64 24}
!20 = !{!21, !6, i64 0}
!21 = !{!"rb_iseq_constant_body", !6, i64 0, !16, i64 4, !13, i64 8, !22, i64 16, !24, i64 64, !27, i64 120, !13, i64 152, !13, i64 160, !13, i64 168, !13, i64 176, !13, i64 184, !13, i64 192, !13, i64 200, !28, i64 208, !16, i64 240, !16, i64 244, !16, i64 248, !16, i64 252, !16, i64 256, !13, i64 264, !5, i64 272, !13, i64 280, !6, i64 288}
!22 = !{!"", !23, i64 0, !16, i64 4, !16, i64 8, !16, i64 12, !16, i64 16, !16, i64 20, !16, i64 24, !16, i64 28, !13, i64 32, !13, i64 40}
!23 = !{!"", !16, i64 0, !16, i64 0, !16, i64 0, !16, i64 0, !16, i64 0, !16, i64 0, !16, i64 0, !16, i64 0}
!24 = !{!"rb_iseq_location_struct", !5, i64 0, !5, i64 8, !5, i64 16, !5, i64 24, !16, i64 32, !25, i64 36}
!25 = !{!"rb_code_location_struct", !26, i64 0, !26, i64 8}
!26 = !{!"rb_code_position_struct", !16, i64 0, !16, i64 4}
!27 = !{!"iseq_insn_info", !13, i64 0, !13, i64 8, !16, i64 16, !13, i64 24}
!28 = !{!"", !5, i64 0, !5, i64 8, !5, i64 16, !13, i64 24}
!29 = !{!30, !5, i64 24}
!30 = !{!"rb_control_frame_struct", !13, i64 0, !13, i64 8, !13, i64 16, !5, i64 24, !13, i64 32, !13, i64 40, !13, i64 48}
!31 = !{!30, !13, i64 8}
!32 = !{!21, !16, i64 240}
!33 = !{!30, !13, i64 32}
!34 = !{!21, !13, i64 8}
!35 = !{!21, !16, i64 256}
!36 = !{!30, !13, i64 16}
!37 = !DILocation(line: 6, column: 11, scope: !8)
!38 = !DILocation(line: 7, column: 11, scope: !8)
!39 = !DILocation(line: 7, column: 6, scope: !8)
!40 = !DILocation(line: 4, column: 1, scope: !8)
!41 = !{!"branch_weights", i32 4000000, i32 4001}
!42 = !DILocation(line: 0, scope: !8)
!43 = !{!"branch_weights", i32 2000, i32 1}
!44 = !DILocation(line: 6, column: 4, scope: !8)
!45 = !{!46, !5, i64 0}
!46 = !{!"RBasic", !5, i64 0, !5, i64 8}
!47 = !DILocation(line: 4, column: 11, scope: !8)
!48 = !DILocation(line: 5, column: 8, scope: !8)
!49 = !{!"branch_weights", i32 1073205, i32 2146410443}
!50 = !DILocation(line: 8, column: 6, scope: !8)
!51 = !{!52}
!52 = distinct !{!52, !53, !"sorbet_int_rb_str_plus: argument 0"}
!53 = distinct !{!53, !"sorbet_int_rb_str_plus"}
!54 = !{!55, !5, i64 400}
!55 = !{!"rb_vm_struct", !5, i64 0, !56, i64 8, !13, i64 192, !13, i64 200, !13, i64 208, !59, i64 216, !6, i64 224, !57, i64 264, !57, i64 280, !57, i64 296, !57, i64 312, !5, i64 328, !16, i64 336, !16, i64 340, !16, i64 340, !16, i64 340, !16, i64 340, !16, i64 344, !5, i64 352, !6, i64 360, !5, i64 400, !5, i64 408, !5, i64 416, !5, i64 424, !5, i64 432, !5, i64 440, !5, i64 448, !13, i64 456, !13, i64 464, !60, i64 472, !61, i64 1064, !13, i64 1088, !13, i64 1096, !16, i64 1104, !16, i64 1108, !57, i64 1112, !6, i64 1128, !5, i64 1168, !5, i64 1176, !5, i64 1184, !5, i64 1192, !5, i64 1200, !16, i64 1208, !5, i64 1216, !13, i64 1224, !13, i64 1232, !13, i64 1240, !13, i64 1248, !62, i64 1256, !6, i64 1288}
!56 = !{!"rb_global_vm_lock_struct", !13, i64 0, !6, i64 8, !57, i64 48, !13, i64 64, !16, i64 72, !6, i64 80, !6, i64 128, !16, i64 176, !16, i64 180}
!57 = !{!"list_head", !58, i64 0}
!58 = !{!"list_node", !13, i64 0, !13, i64 8}
!59 = !{!"long long", !6, i64 0}
!60 = !{!"", !6, i64 0, !6, i64 520}
!61 = !{!"rb_hook_list_struct", !13, i64 0, !16, i64 8, !16, i64 12, !16, i64 16}
!62 = !{!"", !5, i64 0, !5, i64 8, !5, i64 16, !5, i64 24}
!63 = !DILocation(line: 4, column: 1, scope: !64)
!64 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.<static-init>$153", scope: null, file: !2, line: 4, type: !9, scopeLine: 4, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!65 = !DILocation(line: 11, column: 7, scope: !64)
!66 = !DILocation(line: 11, column: 1, scope: !64)
