; ModuleID = 'payload'
source_filename = "llvm-link"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

%struct.rb_execution_context_struct = type { i64*, i64, %struct.rb_control_frame_struct*, %struct.rb_vm_tag*, %struct.rb_vm_protect_tag*, i32, i32, %struct.rb_fiber_struct*, %struct.rb_thread_struct*, %struct.st_table*, i64, i64, i64*, i64, %struct.rb_ensure_list*, %struct.rb_trace_arg_struct*, i64, i64, i8, i8, i64, %struct.anon.5 }
%struct.rb_control_frame_struct = type { i64*, i64*, %struct.rb_iseq_struct*, i64, i64*, i8*, i64* }
%struct.rb_iseq_struct = type { i64, i64, %struct.rb_iseq_constant_body*, %union.anon.14 }
%struct.rb_iseq_constant_body = type { i32, i32, i64*, %struct.anon, %struct.rb_iseq_location_struct, %struct.iseq_insn_info, i64*, %struct.iseq_catch_table*, %struct.rb_iseq_struct*, %struct.rb_iseq_struct*, %union.iseq_inline_storage_entry*, %struct.rb_call_data*, %struct.anon.13, i32, i32, i32, i32, i32, i8, i64 }
%struct.anon = type { %struct.anon.0, i32, i32, i32, i32, i32, i32, i32, i64*, %struct.rb_iseq_param_keyword* }
%struct.anon.0 = type { i16, [2 x i8] }
%struct.rb_iseq_param_keyword = type { i32, i32, i32, i32, i64*, i64* }
%struct.rb_iseq_location_struct = type { i64, i64, i64, i64, i32, %struct.rb_code_location_struct }
%struct.rb_code_location_struct = type { %struct.rb_code_position_struct, %struct.rb_code_position_struct }
%struct.rb_code_position_struct = type { i32, i32 }
%struct.iseq_insn_info = type { %struct.iseq_insn_info_entry*, i32*, i32, %struct.succ_index_table* }
%struct.iseq_insn_info_entry = type opaque
%struct.succ_index_table = type opaque
%struct.iseq_catch_table = type opaque
%union.iseq_inline_storage_entry = type { %struct.iseq_inline_cache_entry }
%struct.iseq_inline_cache_entry = type { i64, %struct.rb_cref_struct*, i64 }
%struct.rb_cref_struct = type { i64, i64, i64, %struct.rb_cref_struct*, %struct.rb_scope_visi_struct }
%struct.rb_scope_visi_struct = type { i8, [3 x i8] }
%struct.rb_call_data = type { %struct.rb_call_cache, %struct.rb_call_info }
%struct.rb_call_cache = type { i64, [3 x i64], %struct.rb_callable_method_entry_struct*, i64, i64 (%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_calling_info*, %struct.rb_call_data*)*, %union.anon.12 }
%struct.rb_callable_method_entry_struct = type { i64, i64, %struct.rb_method_definition_struct*, i64, i64 }
%struct.rb_method_definition_struct = type { i64, %union.anon.10, i64, i64 }
%union.anon.10 = type { %struct.rb_method_cfunc_struct }
%struct.rb_method_cfunc_struct = type { i64 (...)*, i64 (i64, i32, i64*, i64 (...)*)*, i32 }
%struct.rb_calling_info = type { i64, i64, i32, i32 }
%union.anon.12 = type { i32 }
%struct.rb_call_info = type { i64, i32, i32 }
%struct.anon.13 = type { i64, i64, i64, i64* }
%union.anon.14 = type { %struct.anon.15 }
%struct.anon.15 = type { i64, i32 }
%struct.rb_vm_tag = type { i64, i64, [5 x i8*], %struct.rb_vm_tag*, i32 }
%struct.rb_vm_protect_tag = type { %struct.rb_vm_protect_tag* }
%struct.rb_fiber_struct = type opaque
%struct.rb_thread_struct = type { %struct.list_node, i64, %struct.rb_vm_struct*, %struct.rb_execution_context_struct*, i64, %struct.rb_calling_info*, i64, i64, i64, i8, i8, i32, %struct.native_thread_data_struct, i8*, i64, i64, i64, i64, %union.pthread_mutex_t, %struct.rb_unblock_callback, i64, %struct.rb_mutex_struct*, %struct.rb_thread_list_struct*, %union.anon.7, i32, i64, %struct.rb_fiber_struct*, [5 x i8*], i64 }
%struct.list_node = type { %struct.list_node*, %struct.list_node* }
%struct.rb_vm_struct = type { i64, %struct.rb_global_vm_lock_struct, %struct.rb_thread_struct*, %struct.rb_thread_struct*, i8*, i64, %union.pthread_mutex_t, %struct.list_head, %struct.list_head, %struct.list_head, %struct.list_head, i64, i32, i32, i8, i32, i64, [5 x i64], i64, i64, i64, i64, i64, i64, i64, %struct.st_table*, %struct.st_table*, %struct.anon.3, %struct.rb_hook_list_struct, %struct.st_table*, %struct.rb_postponed_job_struct*, i32, i32, %struct.list_head, %union.pthread_mutex_t, i64, i64, i64, i64, i64, i32, %struct.st_table*, %struct.rb_objspace*, %struct.rb_at_exit_list*, i64*, %struct.st_table*, %struct.rb_builtin_function*, i32, %struct.anon.4, [29 x i16] }
%struct.rb_global_vm_lock_struct = type { %struct.rb_thread_struct*, %union.pthread_mutex_t, %struct.list_head, %struct.rb_thread_struct*, i32, %union.pthread_cond_t, %union.pthread_cond_t, i32, i32 }
%union.pthread_cond_t = type { %struct.anon.2 }
%struct.anon.2 = type { i32, i32, i64, i64, i64, i8*, i32, i32 }
%struct.anon.3 = type { [65 x i64] }
%struct.rb_hook_list_struct = type { %struct.rb_event_hook_struct*, i32, i32, i32 }
%struct.rb_event_hook_struct = type opaque
%struct.rb_postponed_job_struct = type opaque
%struct.list_head = type { %struct.list_node }
%struct.rb_objspace = type opaque
%struct.rb_at_exit_list = type { void (%struct.rb_vm_struct*)*, %struct.rb_at_exit_list* }
%struct.rb_builtin_function = type opaque
%struct.anon.4 = type { i64, i64, i64, i64 }
%struct.native_thread_data_struct = type { %struct.list_head, %union.anon.6 }
%union.anon.6 = type { %union.pthread_cond_t }
%union.pthread_mutex_t = type { %struct.__pthread_mutex_s }
%struct.__pthread_mutex_s = type { i32, i32, i32, i32, i32, i16, i16, %struct.__pthread_internal_list }
%struct.__pthread_internal_list = type { %struct.__pthread_internal_list*, %struct.__pthread_internal_list* }
%struct.rb_unblock_callback = type { void (i8*)*, i8* }
%struct.rb_mutex_struct = type opaque
%struct.rb_thread_list_struct = type { %struct.rb_thread_list_struct*, %struct.rb_thread_struct* }
%union.anon.7 = type { %struct.anon.8 }
%struct.anon.8 = type { i64, i64, i32 }
%struct.st_table = type { i8, i8, i8, i32, %struct.st_hash_type*, i64, i64*, i64, i64, %struct.st_table_entry* }
%struct.st_hash_type = type { i32 (i64, i64)*, i64 (i64)* }
%struct.st_table_entry = type opaque
%struct.rb_ensure_list = type { %struct.rb_ensure_list*, %struct.rb_ensure_entry }
%struct.rb_ensure_entry = type { i64, i64 (i64)*, i64 }
%struct.rb_trace_arg_struct = type { i32, %struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, i64, i64, i64, i64, i64, i32, i32, i64 }
%struct.anon.5 = type { i64*, i64*, i64, [1 x %struct.__jmp_buf_tag] }
%struct.__jmp_buf_tag = type { [8 x i64], i32, %struct.__sigset_t }
%struct.__sigset_t = type { [16 x i64] }
%struct.SorbetLineNumberInfo = type { i32, %struct.iseq_insn_info_entry*, i64* }
%struct.FunctionInlineCache = type { %struct.rb_kwarg_call_data }
%struct.rb_kwarg_call_data = type { %struct.rb_call_cache, %struct.rb_call_info_with_kwarg }
%struct.rb_call_info_with_kwarg = type { %struct.rb_call_info, %struct.rb_call_info_kw_arg* }
%struct.rb_call_info_kw_arg = type { i32, [1 x i64] }
%struct.vm_throw_data = type { i64, i64, i64, %struct.rb_control_frame_struct*, i32 }

@ruby_current_execution_context_ptr = external local_unnamed_addr global %struct.rb_execution_context_struct*, align 8
@ruby_current_vm_ptr = external local_unnamed_addr global %struct.rb_vm_struct*, align 8
@.str.7 = private unnamed_addr constant [8 x i8] c"to_proc\00", align 1
@sorbet_makeBlockHandlerProc.rb_funcallv_data = internal global %struct.rb_call_data zeroinitializer, align 8
@rb_eRuntimeError = external local_unnamed_addr global i64, align 8
@.str.10 = private unnamed_addr constant [95 x i8] c"sorbet_getBuildSCMRevision: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@.str.11 = private unnamed_addr constant [93 x i8] c"sorbet_getIsReleaseBuild: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@"stackFramePrecomputed_func_<root>.<static-init>$152" = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@"rubyIdPrecomputed_<top (required)>" = internal unnamed_addr global i64 0, align 8
@"str_<top (required)>" = private unnamed_addr constant [17 x i8] c"<top (required)>\00", align 1
@"rubyStrFrozen_<top (required)>" = internal unnamed_addr global i64 0, align 8
@"rubyStrFrozen_test/testdata/compiler/send_with_block_param.rb" = internal unnamed_addr global i64 0, align 8
@"str_test/testdata/compiler/send_with_block_param.rb" = private unnamed_addr constant [48 x i8] c"test/testdata/compiler/send_with_block_param.rb\00", align 1
@iseqEncodedArray = internal global [7 x i64] zeroinitializer
@fileLineNumberInfo = internal global %struct.SorbetLineNumberInfo zeroinitializer
@ruby_hashLiteral1 = internal unnamed_addr global i64 0, align 8
@rubyIdPrecomputed_unsafe = internal unnamed_addr global i64 0, align 8
@str_unsafe = private unnamed_addr constant [7 x i8] c"unsafe\00", align 1
@ic_unsafe = internal global %struct.FunctionInlineCache zeroinitializer
@"str_<build-array>" = private unnamed_addr constant [14 x i8] c"<build-array>\00", align 1
@rubyIdPrecomputed_map = internal unnamed_addr global i64 0, align 8
@str_map = private unnamed_addr constant [4 x i8] c"map\00", align 1
@ic_map = internal global %struct.FunctionInlineCache zeroinitializer
@ic_puts = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_puts = internal unnamed_addr global i64 0, align 8
@str_puts = private unnamed_addr constant [5 x i8] c"puts\00", align 1

declare %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64, i64, i64, i64, %struct.rb_iseq_struct*, i32, i32, %struct.SorbetLineNumberInfo*, i64*, i32, i32) local_unnamed_addr #0

declare void @sorbet_initLineNumberInfo(%struct.SorbetLineNumberInfo*, i64*, i32) local_unnamed_addr #0

declare i64 @sorbet_readRealpath() local_unnamed_addr #0

declare void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache*, i64, i32, i32, i32, i64*) local_unnamed_addr #0

declare i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache*, i64) local_unnamed_addr #0

declare void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_iseq_struct*) local_unnamed_addr #0

declare i64 @sorbet_globalConstRegister(i64) local_unnamed_addr #0

declare i64 @sorbet_globalConstDupHash(i64) local_unnamed_addr #0

; Function Attrs: nofree nosync nounwind readnone willreturn
declare i8* @llvm.frameaddress.p0i8(i32 immarg) #1

; Function Attrs: nofree nosync nounwind willreturn
declare i8* @llvm.stacksave() #2

; Function Attrs: nounwind
declare i32 @llvm.eh.sjlj.setjmp(i8*) #3

declare void @rb_vm_rewind_cfp(%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*) local_unnamed_addr #0

; Function Attrs: noreturn nounwind
declare void @llvm.eh.sjlj.longjmp(i8*) #4

declare i64 @rb_intern2(i8*, i64) local_unnamed_addr #0

declare i64 @rb_id2sym(i64) local_unnamed_addr #0

declare i64 @rb_ary_new_from_values(i64, i64*) local_unnamed_addr #0

declare i64 @rb_hash_new_with_size(i64) local_unnamed_addr #0

declare void @rb_hash_bulk_insert(i64, i64*, i64) local_unnamed_addr #0

declare i64 @rb_funcallv_with_cc(%struct.rb_call_data*, i64, i64, i32, i64*) local_unnamed_addr #0

declare i64 @rb_fstring_new(i8*, i64) local_unnamed_addr #0

declare void @rb_gc_register_mark_object(i64) local_unnamed_addr #0

; Function Attrs: noreturn
declare void @rb_raise(i64, i8*, ...) local_unnamed_addr #5

declare i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct*, i32) local_unnamed_addr #0

; Function Attrs: alwaysinline nounwind ssp uwtable
define noalias nonnull i8* @sorbet_allocateParamInfo() local_unnamed_addr #6 {
  %1 = tail call noalias nonnull i8* @ruby_xcalloc(i64 noundef 1, i64 noundef 64) #12
  ret i8* %1
}

; Function Attrs: allocsize(0,1)
declare noalias nonnull i8* @ruby_xcalloc(i64, i64) local_unnamed_addr #7

; Function Attrs: nounwind ssp uwtable
define weak i32 @sorbet_getIsReleaseBuild() local_unnamed_addr #8 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !4
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* noundef getelementptr inbounds ([93 x i8], [93 x i8]* @.str.11, i64 0, i64 0)) #4
  unreachable
}

; Function Attrs: nounwind ssp uwtable
define weak i8* @sorbet_getBuildSCMRevision() local_unnamed_addr #8 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !4
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* noundef getelementptr inbounds ([95 x i8], [95 x i8]* @.str.10, i64 0, i64 0)) #4
  unreachable
}

; Function Attrs: sspreq
define void @Init_send_with_block_param() local_unnamed_addr #9 {
entry:
  %callArgs.i = alloca [4 x i64], align 8
  %ecTag.i = alloca %struct.rb_vm_tag, align 8
  %argArray.i.i = alloca [2 x i64], align 8
  %locals.i.i = alloca i64, i32 0, align 8
  %realpath = tail call i64 @sorbet_readRealpath()
  %0 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 noundef 16) #3
  store i64 %0, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %1 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([7 x i8], [7 x i8]* @str_unsafe, i64 0, i64 0), i64 noundef 6) #3
  store i64 %1, i64* @rubyIdPrecomputed_unsafe, align 8
  %2 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([14 x i8], [14 x i8]* @"str_<build-array>", i64 0, i64 0), i64 noundef 13) #3
  %3 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @str_map, i64 0, i64 0), i64 noundef 3) #3
  store i64 %3, i64* @rubyIdPrecomputed_map, align 8
  %4 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([5 x i8], [5 x i8]* @str_puts, i64 0, i64 0), i64 noundef 4) #3
  store i64 %4, i64* @rubyIdPrecomputed_puts, align 8
  %5 = tail call i64 @rb_fstring_new(i8* noundef getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 noundef 16) #3
  tail call void @rb_gc_register_mark_object(i64 %5) #3
  store i64 %5, i64* @"rubyStrFrozen_<top (required)>", align 8
  %6 = tail call i64 @rb_fstring_new(i8* noundef getelementptr inbounds ([48 x i8], [48 x i8]* @"str_test/testdata/compiler/send_with_block_param.rb", i64 0, i64 0), i64 noundef 47) #3
  tail call void @rb_gc_register_mark_object(i64 %6) #3
  store i64 %6, i64* @"rubyStrFrozen_test/testdata/compiler/send_with_block_param.rb", align 8
  tail call void @sorbet_initLineNumberInfo(%struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef getelementptr inbounds ([7 x i64], [7 x i64]* @iseqEncodedArray, i32 0, i32 0), i32 noundef 7)
  %"rubyId_<top (required)>.i.i" = load i64, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %"rubyStr_<top (required)>.i.i" = load i64, i64* @"rubyStrFrozen_<top (required)>", align 8
  %"rubyStr_test/testdata/compiler/send_with_block_param.rb.i.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/send_with_block_param.rb", align 8
  %7 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_<top (required)>.i.i", i64 %"rubyId_<top (required)>.i.i", i64 %"rubyStr_test/testdata/compiler/send_with_block_param.rb.i.i", i64 %realpath, %struct.rb_iseq_struct* noundef null, i32 noundef 0, i32 noundef 4, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef nonnull %locals.i.i, i32 noundef 0, i32 noundef 4)
  store %struct.rb_iseq_struct* %7, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_<root>.<static-init>$152", align 8
  %8 = bitcast [2 x i64]* %argArray.i.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 16, i8* nonnull %8)
  %hashArgs0Addr.i.i = getelementptr [2 x i64], [2 x i64]* %argArray.i.i, i32 0, i64 0
  %9 = bitcast i64* %hashArgs0Addr.i.i to <2 x i64>*
  store <2 x i64> <i64 3, i64 5>, <2 x i64>* %9, align 8
  %10 = getelementptr [2 x i64], [2 x i64]* %argArray.i.i, i64 0, i64 0
  %11 = call i64 @rb_hash_new_with_size(i64 noundef 1) #3
  call void @rb_hash_bulk_insert(i64 noundef 2, i64* noundef nonnull %10, i64 %11) #3
  %12 = call i64 @sorbet_globalConstRegister(i64 %11) #3
  store i64 %12, i64* @ruby_hashLiteral1, align 8
  call void @llvm.lifetime.end.p0i8(i64 16, i8* nonnull %8)
  %rubyId_unsafe.i = load i64, i64* @rubyIdPrecomputed_unsafe, align 8, !dbg !8
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_unsafe, i64 %rubyId_unsafe.i, i32 noundef 16, i32 noundef 1, i32 noundef 0, i64* noundef null), !dbg !8
  %rubyId_map.i = load i64, i64* @rubyIdPrecomputed_map, align 8, !dbg !13
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_map, i64 %rubyId_map.i, i32 noundef 16, i32 noundef 0, i32 noundef 0, i64* noundef null), !dbg !13
  %rubyId_puts.i = load i64, i64* @rubyIdPrecomputed_puts, align 8, !dbg !14
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_puts, i64 %rubyId_puts.i, i32 noundef 20, i32 noundef 1, i32 noundef 0, i64* noundef null), !dbg !14
  %13 = load %struct.rb_vm_struct*, %struct.rb_vm_struct** @ruby_current_vm_ptr, align 8, !tbaa !15
  %14 = getelementptr inbounds %struct.rb_vm_struct, %struct.rb_vm_struct* %13, i64 0, i32 18
  %15 = load i64, i64* %14, align 8, !tbaa !17
  %16 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !15
  %17 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %16, i64 0, i32 2
  %18 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %17, align 8, !tbaa !27
  %19 = bitcast [4 x i64]* %callArgs.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 32, i8* nonnull %19)
  %20 = bitcast %struct.rb_vm_tag* %ecTag.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 72, i8* nonnull %20)
  %stackFrame.i = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_<root>.<static-init>$152", align 8
  %21 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %17, align 8, !tbaa !27
  %22 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %21, i64 0, i32 2
  store %struct.rb_iseq_struct* %stackFrame.i, %struct.rb_iseq_struct** %22, align 8, !tbaa !30
  %23 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %21, i64 0, i32 4
  %24 = load i64*, i64** %23, align 8, !tbaa !32
  %25 = load i64, i64* %24, align 8, !tbaa !4
  %26 = and i64 %25, -33
  store i64 %26, i64* %24, align 8, !tbaa !4
  call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* %16, %struct.rb_control_frame_struct* %21, %struct.rb_iseq_struct* %stackFrame.i) #3
  %27 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %18, i64 0, i32 0
  store i64* getelementptr inbounds ([7 x i64], [7 x i64]* @iseqEncodedArray, i64 0, i64 4), i64** %27, align 8, !tbaa !15
  %28 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !15
  %29 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %ecTag.i, i64 0, i32 4
  store i32 0, i32* %29, align 8, !tbaa !33
  %30 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %ecTag.i, i64 0, i32 0
  store i64 52, i64* %30, align 8, !tbaa !35
  %31 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %28, i64 0, i32 3
  %32 = load %struct.rb_vm_tag*, %struct.rb_vm_tag** %31, align 8, !tbaa !36
  %33 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %ecTag.i, i64 0, i32 3
  store %struct.rb_vm_tag* %32, %struct.rb_vm_tag** %33, align 8, !tbaa !37
  %34 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %ecTag.i, i64 0, i32 2, i64 0
  %35 = call i8* @llvm.frameaddress.p0i8(i32 noundef 0) #3
  store i8* %35, i8** %34, align 8
  %36 = call i8* @llvm.stacksave() #3
  %37 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %ecTag.i, i64 0, i32 2, i64 2
  store i8* %36, i8** %37, align 8
  %38 = bitcast i8** %34 to i8*
  %39 = call i32 @llvm.eh.sjlj.setjmp(i8* nonnull align 8 %38) #3
  %40 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !15
  %41 = icmp eq i32 %39, 0
  %42 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %40, i64 0, i32 3
  br i1 %41, label %64, label %43

43:                                               ; preds = %entry
  %44 = load %struct.rb_vm_tag*, %struct.rb_vm_tag** %42, align 8, !tbaa !36
  %45 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %44, i64 0, i32 4
  %46 = load i32, i32* %45, align 8, !tbaa !33
  store i32 0, i32* %45, align 8, !tbaa !33
  %47 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %40, i64 0, i32 16
  %48 = load i64, i64* %47, align 8, !tbaa !38
  %49 = inttoptr i64 %48 to %struct.vm_throw_data*
  %50 = icmp eq i32 %46, 1
  br i1 %50, label %51, label %56

51:                                               ; preds = %43
  %52 = getelementptr inbounds %struct.vm_throw_data, %struct.vm_throw_data* %49, i64 0, i32 3
  %53 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %52, align 8, !tbaa !39
  %54 = icmp eq %struct.rb_control_frame_struct* %53, %18
  br i1 %54, label %sorbet_processThrowReturnSetJmp.exit.i, label %.thread1.i

.thread1.i:                                       ; preds = %51
  %55 = load %struct.rb_vm_tag*, %struct.rb_vm_tag** %33, align 8, !tbaa !37
  store %struct.rb_vm_tag* %55, %struct.rb_vm_tag** %42, align 8, !tbaa !36
  br label %59

56:                                               ; preds = %43
  %57 = load %struct.rb_vm_tag*, %struct.rb_vm_tag** %33, align 8, !tbaa !37
  store %struct.rb_vm_tag* %57, %struct.rb_vm_tag** %42, align 8, !tbaa !36
  %58 = icmp eq i32 %46, 0
  br i1 %58, label %fastSymCallIntrinsic_T_unsafe.i, label %59

59:                                               ; preds = %56, %.thread1.i
  %60 = phi %struct.rb_vm_tag* [ %55, %.thread1.i ], [ %57, %56 ]
  %61 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %60, i64 0, i32 4
  store i32 %46, i32* %61, align 8, !tbaa !33
  %62 = getelementptr inbounds %struct.rb_vm_tag, %struct.rb_vm_tag* %60, i64 0, i32 2, i64 0
  %63 = bitcast i8** %62 to i8*
  call void @llvm.eh.sjlj.longjmp(i8* nonnull %63) #4
  unreachable

64:                                               ; preds = %entry
  store %struct.rb_vm_tag* %ecTag.i, %struct.rb_vm_tag** %42, align 8, !tbaa !36
  br label %fastSymCallIntrinsic_T_unsafe.i

sorbet_processThrowReturnSetJmp.exit.i:           ; preds = %51
  call void @rb_vm_rewind_cfp(%struct.rb_execution_context_struct* nonnull %40, %struct.rb_control_frame_struct* nonnull %18) #3
  store i64 8, i64* %47, align 8, !tbaa !38
  %65 = getelementptr inbounds %struct.vm_throw_data, %struct.vm_throw_data* %49, i64 0, i32 2
  %66 = load i64, i64* %65, align 8, !tbaa !41
  %67 = load %struct.rb_vm_tag*, %struct.rb_vm_tag** %33, align 8, !tbaa !37
  store %struct.rb_vm_tag* %67, %struct.rb_vm_tag** %42, align 8, !tbaa !36
  %68 = icmp eq i64 %66, 52
  br i1 %68, label %fastSymCallIntrinsic_T_unsafe.i, label %"func_<root>.<static-init>$152.exit"

afterSend24.i:                                    ; preds = %88, %fastSymCallIntrinsic_T_unsafe.i
  store i64* getelementptr inbounds ([7 x i64], [7 x i64]* @iseqEncodedArray, i64 0, i64 6), i64** %27, align 8, !dbg !8, !tbaa !15
  store i64 3, i64* %callArgs0Addr.i, align 8, !dbg !13
  call void @llvm.experimental.noalias.scope.decl(metadata !42) #3, !dbg !13
  %69 = call i64 @rb_ary_new_from_values(i64 noundef 1, i64* noundef nonnull %78) #3, !dbg !13
  %rubyId_map.i1 = load i64, i64* @rubyIdPrecomputed_map, align 8, !dbg !13
  %rawSym.i = call i64 @rb_id2sym(i64 %rubyId_map.i1) #3, !dbg !13
  %70 = call i64 @rb_intern2(i8* noundef getelementptr inbounds ([8 x i8], [8 x i8]* @.str.7, i64 0, i64 0), i64 noundef 7) #3, !dbg !13
  %71 = call i64 @rb_funcallv_with_cc(%struct.rb_call_data* noundef nonnull @sorbet_makeBlockHandlerProc.rb_funcallv_data, i64 %79, i64 %70, i32 noundef 0, i64* noundef null) #3, !dbg !13
  %72 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %18, i64 0, i32 1, !dbg !13
  %73 = load i64*, i64** %72, align 8, !dbg !13, !tbaa !45
  %74 = getelementptr inbounds i64, i64* %73, i64 1, !dbg !13
  store i64* %74, i64** %72, align 8, !dbg !13, !tbaa !45
  store i64 %69, i64* %73, align 8, !dbg !13, !tbaa !4
  %send36.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @ic_map, i64 %71) #3, !dbg !13
  %75 = load i64*, i64** %72, align 8, !dbg !14, !tbaa !45
  %76 = getelementptr inbounds i64, i64* %75, i64 1, !dbg !14
  store i64 %15, i64* %75, align 8, !dbg !14, !tbaa !4
  %77 = getelementptr inbounds i64, i64* %76, i64 1, !dbg !14
  store i64* %77, i64** %72, align 8, !dbg !14, !tbaa !45
  store i64 %send36.i, i64* %76, align 8, !dbg !14, !tbaa !4
  %send41.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @ic_puts, i64 0) #3, !dbg !14
  br label %"func_<root>.<static-init>$152.exit", !dbg !14

fastSymCallIntrinsic_T_unsafe.i:                  ; preds = %sorbet_processThrowReturnSetJmp.exit.i, %64, %56
  store i64* getelementptr inbounds ([7 x i64], [7 x i64]* @iseqEncodedArray, i64 0, i64 4), i64** %27, align 8, !dbg !46, !tbaa !15
  %hashLiteral.i = load i64, i64* @ruby_hashLiteral1, align 8, !dbg !47
  %duplicatedHash.i = call i64 @sorbet_globalConstDupHash(i64 %hashLiteral.i) #3, !dbg !47
  %callArgs0Addr.i = getelementptr [4 x i64], [4 x i64]* %callArgs.i, i32 0, i64 0, !dbg !8
  store i64 %duplicatedHash.i, i64* %callArgs0Addr.i, align 8, !dbg !8
  %78 = getelementptr [4 x i64], [4 x i64]* %callArgs.i, i64 0, i64 0, !dbg !8
  call void @llvm.experimental.noalias.scope.decl(metadata !48) #3, !dbg !8
  %79 = load i64, i64* %78, align 8, !dbg !8, !tbaa !4, !alias.scope !48
  %80 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !8, !tbaa !15
  %81 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %80, i64 0, i32 5, !dbg !8
  %82 = load i32, i32* %81, align 8, !dbg !8, !tbaa !51
  %83 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %80, i64 0, i32 6, !dbg !8
  %84 = load i32, i32* %83, align 4, !dbg !8, !tbaa !52
  %85 = xor i32 %84, -1, !dbg !8
  %86 = and i32 %85, %82, !dbg !8
  %87 = icmp eq i32 %86, 0, !dbg !8
  br i1 %87, label %afterSend24.i, label %88, !dbg !8, !prof !53

88:                                               ; preds = %fastSymCallIntrinsic_T_unsafe.i
  %89 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %80, i64 0, i32 8, !dbg !8
  %90 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %89, align 8, !dbg !8, !tbaa !54
  %91 = call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* %90, i32 noundef 0) #3, !dbg !8
  br label %afterSend24.i, !dbg !8

"func_<root>.<static-init>$152.exit":             ; preds = %sorbet_processThrowReturnSetJmp.exit.i, %afterSend24.i
  %92 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !15
  %93 = load %struct.rb_vm_tag*, %struct.rb_vm_tag** %33, align 8, !tbaa !37
  %94 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %92, i64 0, i32 3
  store %struct.rb_vm_tag* %93, %struct.rb_vm_tag** %94, align 8, !tbaa !36
  call void @llvm.lifetime.end.p0i8(i64 32, i8* nonnull %19)
  call void @llvm.lifetime.end.p0i8(i64 72, i8* nonnull %20)
  ret void
}

; Function Attrs: inaccessiblememonly nofree nosync nounwind willreturn
declare void @llvm.experimental.noalias.scope.decl(metadata) #10

; Function Attrs: argmemonly nofree nosync nounwind willreturn
declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #11

; Function Attrs: argmemonly nofree nosync nounwind willreturn
declare void @llvm.lifetime.end.p0i8(i64 immarg, i8* nocapture) #11

attributes #0 = { "addedToSilenceEmptyAttrsError" }
attributes #1 = { nofree nosync nounwind readnone willreturn }
attributes #2 = { nofree nosync nounwind willreturn }
attributes #3 = { nounwind }
attributes #4 = { noreturn nounwind }
attributes #5 = { noreturn }
attributes #6 = { alwaysinline nounwind ssp uwtable }
attributes #7 = { allocsize(0,1) }
attributes #8 = { nounwind ssp uwtable }
attributes #9 = { sspreq }
attributes #10 = { inaccessiblememonly nofree nosync nounwind willreturn }
attributes #11 = { argmemonly nofree nosync nounwind willreturn }
attributes #12 = { nounwind allocsize(0,1) }

!llvm.module.flags = !{!0}
!llvm.dbg.cu = !{!1}

!0 = !{i32 2, !"Debug Info Version", i32 3}
!1 = distinct !DICompileUnit(language: DW_LANG_C, file: !2, producer: "Sorbet LLVM", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, enums: !3)
!2 = !DIFile(filename: "test/testdata/compiler/send_with_block_param.rb", directory: ".")
!3 = !{}
!4 = !{!5, !5, i64 0}
!5 = !{!"long", !6, i64 0}
!6 = !{!"omnipotent char", !7, i64 0}
!7 = !{!"Simple C/C++ TBAA"}
!8 = !DILocation(line: 4, column: 5, scope: !9)
!9 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.<static-init>$152", scope: null, file: !2, line: 4, type: !10, scopeLine: 4, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!10 = !DISubroutineType(types: !11)
!11 = !{!12}
!12 = !DIBasicType(name: "VALUE", size: 64, encoding: DW_ATE_signed)
!13 = !DILocation(line: 6, column: 6, scope: !9)
!14 = !DILocation(line: 6, column: 1, scope: !9)
!15 = !{!16, !16, i64 0}
!16 = !{!"any pointer", !6, i64 0}
!17 = !{!18, !5, i64 400}
!18 = !{!"rb_vm_struct", !5, i64 0, !19, i64 8, !16, i64 192, !16, i64 200, !16, i64 208, !23, i64 216, !6, i64 224, !20, i64 264, !20, i64 280, !20, i64 296, !20, i64 312, !5, i64 328, !22, i64 336, !22, i64 340, !22, i64 344, !22, i64 344, !22, i64 344, !22, i64 344, !22, i64 348, !5, i64 352, !6, i64 360, !5, i64 400, !5, i64 408, !5, i64 416, !5, i64 424, !5, i64 432, !5, i64 440, !5, i64 448, !16, i64 456, !16, i64 464, !24, i64 472, !25, i64 992, !16, i64 1016, !16, i64 1024, !22, i64 1032, !22, i64 1036, !20, i64 1040, !6, i64 1056, !5, i64 1096, !5, i64 1104, !5, i64 1112, !5, i64 1120, !5, i64 1128, !22, i64 1136, !16, i64 1144, !16, i64 1152, !16, i64 1160, !16, i64 1168, !16, i64 1176, !16, i64 1184, !22, i64 1192, !26, i64 1200, !6, i64 1232}
!19 = !{!"rb_global_vm_lock_struct", !16, i64 0, !6, i64 8, !20, i64 48, !16, i64 64, !22, i64 72, !6, i64 80, !6, i64 128, !22, i64 176, !22, i64 180}
!20 = !{!"list_head", !21, i64 0}
!21 = !{!"list_node", !16, i64 0, !16, i64 8}
!22 = !{!"int", !6, i64 0}
!23 = !{!"long long", !6, i64 0}
!24 = !{!"", !6, i64 0}
!25 = !{!"rb_hook_list_struct", !16, i64 0, !22, i64 8, !22, i64 12, !22, i64 16}
!26 = !{!"", !5, i64 0, !5, i64 8, !5, i64 16, !5, i64 24}
!27 = !{!28, !16, i64 16}
!28 = !{!"rb_execution_context_struct", !16, i64 0, !5, i64 8, !16, i64 16, !16, i64 24, !16, i64 32, !22, i64 40, !22, i64 44, !16, i64 48, !16, i64 56, !16, i64 64, !5, i64 72, !5, i64 80, !16, i64 88, !5, i64 96, !16, i64 104, !16, i64 112, !5, i64 120, !5, i64 128, !6, i64 136, !6, i64 137, !5, i64 144, !29, i64 152}
!29 = !{!"", !16, i64 0, !16, i64 8, !5, i64 16, !6, i64 24}
!30 = !{!31, !16, i64 16}
!31 = !{!"rb_control_frame_struct", !16, i64 0, !16, i64 8, !16, i64 16, !5, i64 24, !16, i64 32, !16, i64 40, !16, i64 48}
!32 = !{!31, !16, i64 32}
!33 = !{!34, !6, i64 64}
!34 = !{!"rb_vm_tag", !5, i64 0, !5, i64 8, !6, i64 16, !16, i64 56, !6, i64 64}
!35 = !{!34, !5, i64 0}
!36 = !{!28, !16, i64 24}
!37 = !{!34, !16, i64 56}
!38 = !{!28, !5, i64 120}
!39 = !{!40, !16, i64 24}
!40 = !{!"vm_throw_data", !5, i64 0, !5, i64 8, !5, i64 16, !16, i64 24, !22, i64 32}
!41 = !{!40, !5, i64 16}
!42 = !{!43}
!43 = distinct !{!43, !44, !"sorbet_buildArrayIntrinsic: argument 0"}
!44 = distinct !{!44, !"sorbet_buildArrayIntrinsic"}
!45 = !{!31, !16, i64 8}
!46 = !DILocation(line: 0, scope: !9)
!47 = !DILocation(line: 4, column: 14, scope: !9)
!48 = !{!49}
!49 = distinct !{!49, !50, !"sorbet_T_unsafe: argument 0"}
!50 = distinct !{!50, !"sorbet_T_unsafe"}
!51 = !{!28, !22, i64 40}
!52 = !{!28, !22, i64 44}
!53 = !{!"branch_weights", i32 2000, i32 1}
!54 = !{!28, !16, i64 56}
