; ModuleID = 'payload'
source_filename = "llvm-link"
target datalayout = "e-m:o-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

%struct.rb_data_type_struct = type { i8*, %struct.anon.19, %struct.rb_data_type_struct*, i8*, i64 }
%struct.anon.19 = type { void (i8*)*, void (i8*)*, i64 (i8*)*, [2 x i8*] }
%struct.rb_execution_context_struct = type { i64*, i64, %struct.rb_control_frame_struct*, %struct.rb_vm_tag*, %struct.rb_vm_protect_tag*, i32, i32, %struct.rb_fiber_struct*, %struct.rb_thread_struct*, %struct.st_table*, i64, i64, i64*, i64, %struct.rb_ensure_list*, %struct.rb_trace_arg_struct*, i64, i64, i8, i8, i64, %struct.anon.18 }
%struct.rb_control_frame_struct = type { i64*, i64*, %struct.rb_iseq_struct*, i64, i64*, i8*, i64* }
%struct.rb_iseq_struct = type { i64, i64, %struct.rb_iseq_constant_body*, %union.anon.15 }
%struct.rb_iseq_constant_body = type { i32, i32, i64*, %struct.anon.1, %struct.rb_iseq_location_struct, %struct.iseq_insn_info, i64*, %struct.iseq_catch_table*, %struct.rb_iseq_struct*, %struct.rb_iseq_struct*, %union.iseq_inline_storage_entry*, %struct.rb_call_info*, %struct.rb_call_cache*, %struct.anon.14, i32, i32, i32, i32, i32, i8 }
%struct.anon.1 = type { %struct.anon.2, i32, i32, i32, i32, i32, i32, i32, i64*, %struct.rb_iseq_param_keyword* }
%struct.anon.2 = type { i8, [3 x i8] }
%struct.rb_iseq_param_keyword = type { i32, i32, i32, i32, i64*, i64* }
%struct.rb_iseq_location_struct = type { i64, i64, i64, i64, i32, %struct.rb_code_location_struct }
%struct.rb_code_location_struct = type { %struct.rb_code_position_struct, %struct.rb_code_position_struct }
%struct.rb_code_position_struct = type { i32, i32 }
%struct.iseq_insn_info = type { %struct.rb_code_position_struct*, i32*, i32, %struct.succ_index_table* }
%struct.succ_index_table = type opaque
%struct.iseq_catch_table = type opaque
%union.iseq_inline_storage_entry = type { %struct.iseq_inline_cache_entry }
%struct.iseq_inline_cache_entry = type { i64, %struct.rb_cref_struct*, %union.anon.0 }
%struct.rb_cref_struct = type { i64, i64, i64, %struct.rb_cref_struct*, %struct.anon.2 }
%union.anon.0 = type { i64 }
%struct.rb_call_info = type { i64, i32, i32 }
%struct.rb_call_cache = type { i64, i64, %struct.rb_callable_method_entry_struct*, i64 (%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_calling_info*, %struct.rb_call_info*, %struct.rb_call_cache*)*, %union.anon.13 }
%struct.rb_callable_method_entry_struct = type { i64, i64, %struct.rb_method_definition_struct*, i64, i64 }
%struct.rb_method_definition_struct = type { i64, %union.anon.12, i64 }
%union.anon.12 = type { %struct.rb_method_cfunc_struct }
%struct.rb_method_cfunc_struct = type { i64 (...)*, i64 (i64 (...)*, i64, i32, i64*)*, i32 }
%struct.rb_calling_info = type { i64, i64, i32 }
%union.anon.13 = type { i32 }
%struct.anon.14 = type { i64, i64, i64, i64* }
%union.anon.15 = type { %struct.anon.16 }
%struct.anon.16 = type { i64, i32 }
%struct.rb_vm_tag = type { i64, i64, [38 x i32], %struct.rb_vm_tag*, i32 }
%struct.rb_vm_protect_tag = type { %struct.rb_vm_protect_tag* }
%struct.rb_fiber_struct = type opaque
%struct.rb_thread_struct = type { %struct.list_node, i64, %struct.rb_vm_struct*, %struct.rb_execution_context_struct*, i64, %struct.rb_calling_info*, i64, i64, %struct._opaque_pthread_t*, i8, i8, i32, %struct.native_thread_data_struct, i8*, i64, i64, i64, i64, %struct._opaque_pthread_mutex_t, %struct.rb_unblock_callback, i64, %struct.rb_mutex_struct*, %struct.rb_thread_list_struct*, %union.anon.8, i32, i64, %struct.rb_fiber_struct*, [38 x i32], i64 }
%struct.list_node = type { %struct.list_node*, %struct.list_node* }
%struct.rb_vm_struct = type { i64, %struct.rb_global_vm_lock_struct, %struct.rb_thread_struct*, %struct.rb_thread_struct*, i8*, i64, %struct._opaque_pthread_mutex_t, %struct.list_head, %struct.list_head, %struct.list_head, %struct.list_head, i64, i32, i8, i32, i64, [5 x i64], i64, i64, i64, i64, i64, i64, i64, %struct.st_table*, %struct.st_table*, %struct.anon.4, %struct.rb_hook_list_struct, %struct.st_table*, %struct.rb_postponed_job_struct*, i32, i32, %struct.list_head, %struct._opaque_pthread_mutex_t, i64, i64, i64, i64, i64, i32, i64, %struct.rb_objspace*, %struct.rb_at_exit_list*, i64*, %struct.st_table*, %struct.anon.5, [28 x i16] }
%struct.rb_global_vm_lock_struct = type { %struct.rb_thread_struct*, %struct._opaque_pthread_mutex_t, %struct.list_head, %struct.rb_thread_struct*, i32, %struct._opaque_pthread_cond_t, %struct._opaque_pthread_cond_t, i32, i32 }
%struct._opaque_pthread_cond_t = type { i64, [40 x i8] }
%struct.anon.4 = type { [32 x i64], [32 x i8] }
%struct.rb_hook_list_struct = type { %struct.rb_event_hook_struct*, i32, i32, i32 }
%struct.rb_event_hook_struct = type opaque
%struct.rb_postponed_job_struct = type opaque
%struct.list_head = type { %struct.list_node }
%struct.rb_objspace = type opaque
%struct.rb_at_exit_list = type { void (%struct.rb_vm_struct*)*, %struct.rb_at_exit_list* }
%struct.anon.5 = type { i64, i64, i64, i64 }
%struct._opaque_pthread_t = type { i64, %struct.__darwin_pthread_handler_rec*, [8176 x i8] }
%struct.__darwin_pthread_handler_rec = type { void (i8*)*, i8*, %struct.__darwin_pthread_handler_rec* }
%struct.native_thread_data_struct = type { %struct.list_head, %struct.anon.7 }
%struct.anon.7 = type { %struct._opaque_pthread_cond_t, %struct._opaque_pthread_cond_t }
%struct._opaque_pthread_mutex_t = type { i64, [56 x i8] }
%struct.rb_unblock_callback = type { void (i8*)*, i8* }
%struct.rb_mutex_struct = type opaque
%struct.rb_thread_list_struct = type { %struct.rb_thread_list_struct*, %struct.rb_thread_struct* }
%union.anon.8 = type { %struct.RBasic }
%struct.RBasic = type { i64, i64 }
%struct.st_table = type { i8, i8, i8, i32, %struct.st_hash_type*, i64, i64*, i64, i64, %struct.st_table_entry* }
%struct.st_hash_type = type { i32 (...)*, i64 (...)* }
%struct.st_table_entry = type opaque
%struct.rb_ensure_list = type { %struct.rb_ensure_list*, %struct.rb_ensure_entry }
%struct.rb_ensure_entry = type { i64, i64 (...)*, i64 }
%struct.rb_trace_arg_struct = type { i32, %struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, i64, i64, i64, i64, i64, i32, i32, i64 }
%struct.anon.18 = type { i64*, i64*, i64, [37 x i32] }
%struct.RString = type { %struct.RBasic, %union.anon }
%union.anon = type { %struct.anon }
%struct.anon = type { i64, i8*, %union.anon.0 }
%struct.rb_ast_body_struct = type { %struct.RNode*, i64, i32 }
%struct.RNode = type { i64, %union.anon.20, %union.anon.20, %union.anon.20, %struct.rb_code_location_struct, i32 }
%union.anon.20 = type { %struct.RNode* }
%struct.RArray = type { %struct.RBasic, %union.anon.26 }
%union.anon.26 = type { %struct.anon.27 }
%struct.anon.27 = type { i64, %union.anon.0, i64* }

@closureInfo = local_unnamed_addr constant %struct.rb_data_type_struct { i8* getelementptr inbounds ([16 x i8], [16 x i8]* @.str.10, i32 0, i32 0), %struct.anon.19 { void (i8*)* @sorbet_Closure_mark, void (i8*)* inttoptr (i64 -1 to void (i8*)*), i64 (i8*)* @sorbet_Closure_size, [2 x i8*] zeroinitializer }, %struct.rb_data_type_struct* null, i8* null, i64 1 }, align 8
@.str.10 = private unnamed_addr constant [16 x i8] c"CompiledClosure\00", align 1
@.str = private unnamed_addr constant [5 x i8] c"%li\0B\00", align 1
@ruby_current_execution_context_ptr = external local_unnamed_addr global %struct.rb_execution_context_struct*, align 8
@rb_cObject = external local_unnamed_addr constant i64, align 8
@"stackFramePrecomputed_func_<root>.<static-init>$111" = internal unnamed_addr global i8* null, align 8
@"rubyIdPrecomputed_<top (required)>" = internal unnamed_addr global i64 0, align 8
@"str_<top (required)>" = private unnamed_addr constant [17 x i8] c"<top (required)>\00", align 1
@"str_test/testdata/compiler/splat.rb" = private unnamed_addr constant [32 x i8] c"test/testdata/compiler/splat.rb\00", align 1
@"rubyIdPrecomputed_[]" = internal unnamed_addr global i64 0, align 8
@"str_[]" = private unnamed_addr constant [3 x i8] c"[]\00", align 1
@rubyIdPrecomputed_puts = internal unnamed_addr global i64 0, align 8
@str_puts = private unnamed_addr constant [5 x i8] c"puts\00", align 1
@llvm.global_ctors = appending global [4 x { i32, void ()*, i8* }] [{ i32, void ()*, i8* } { i32 0, void ()* @"Constr_rubyIdPrecomputed_<top (required)>", i8* bitcast (i64* @"rubyIdPrecomputed_<top (required)>" to i8*) }, { i32, void ()*, i8* } { i32 0, void ()* @"Constr_stackFramePrecomputed_func_<root>.<static-init>$111", i8* bitcast (i8** @"stackFramePrecomputed_func_<root>.<static-init>$111" to i8*) }, { i32, void ()*, i8* } { i32 0, void ()* @"Constr_rubyIdPrecomputed_[]", i8* bitcast (i64* @"rubyIdPrecomputed_[]" to i8*) }, { i32, void ()*, i8* } { i32 0, void ()* @Constr_rubyIdPrecomputed_puts, i8* bitcast (i64* @rubyIdPrecomputed_puts to i8*) }]

declare i64 @rb_ary_push(i64, i64) local_unnamed_addr #0

; Function Attrs: nounwind ssp uwtable
define internal void @sorbet_Closure_mark(i8* %0) #1 {
  %2 = bitcast i8* %0 to i32*
  %3 = load i32, i32* %2, align 8, !tbaa !0
  %4 = sext i32 %3 to i64
  %5 = getelementptr inbounds i8, i8* %0, i64 8
  %6 = bitcast i8* %5 to i64*
  tail call void @rb_gc_mark_values(i64 %4, i64* nonnull %6) #7
  ret void
}

; Function Attrs: norecurse nounwind readnone ssp uwtable
define internal i64 @sorbet_Closure_size(i8* nocapture readonly %0) #2 {
  %2 = bitcast i8* %0 to i32*
  %3 = load i32, i32* %2, align 8, !tbaa !0
  %4 = sext i32 %3 to i64
  %5 = shl nsw i64 %4, 3
  %6 = add nsw i64 %5, 8
  ret i64 %6
}

declare void @rb_gc_mark_values(i64, i64*) local_unnamed_addr #0

; Function Attrs: nounwind ssp uwtable
define weak i8* @dbg_pi(i64 %0) local_unnamed_addr #1 {
  %2 = tail call i8* @rb_id2name(i64 %0) #7
  ret i8* %2
}

declare i8* @rb_id2name(i64) local_unnamed_addr #0

; Function Attrs: nounwind ssp uwtable
define weak i8* @dbg_p(i64 %0) local_unnamed_addr #1 {
  %2 = tail call i64 (i8*, ...) @rb_sprintf(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @.str, i64 0, i64 0), i64 %0) #7
  %3 = inttoptr i64 %2 to %struct.RBasic*
  %4 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %3, i64 0, i32 0
  %5 = load i64, i64* %4, align 8, !tbaa !4
  %6 = and i64 %5, 8192
  %7 = icmp eq i64 %6, 0
  %8 = tail call i64 (i8*, ...) @rb_sprintf(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @.str, i64 0, i64 0), i64 %0) #7
  %9 = inttoptr i64 %8 to %struct.RString*
  br i1 %7, label %10, label %13

10:                                               ; preds = %1
  %11 = getelementptr inbounds %struct.RString, %struct.RString* %9, i64 0, i32 1
  %12 = bitcast %union.anon* %11 to i8*
  br label %16

13:                                               ; preds = %1
  %14 = getelementptr inbounds %struct.RString, %struct.RString* %9, i64 0, i32 1, i32 0, i32 1
  %15 = load i8*, i8** %14, align 8, !tbaa !7
  br label %16

16:                                               ; preds = %13, %10
  %17 = phi i8* [ %12, %10 ], [ %15, %13 ]
  ret i8* %17
}

declare i64 @rb_sprintf(i8*, ...) local_unnamed_addr #0

; Function Attrs: nounwind ssp uwtable
define void @stopInDebugger() local_unnamed_addr #1 {
  tail call void asm sideeffect "int $$3", "~{dirflag},~{fpsr},~{flags}"() #7, !srcloc !8
  ret void
}

declare i64 @rb_str_new(i8*, i64) local_unnamed_addr #0

declare i64 @rb_ary_new_from_values(i64, i64*) local_unnamed_addr #0

declare i64 @rb_intern2(i8*, i64) local_unnamed_addr #0

declare i64 @rb_funcallv(i64, i64, i32, i64*) local_unnamed_addr #0

declare %struct.rb_iseq_struct* @rb_iseq_new(%struct.rb_ast_body_struct*, i64, i64, i64, %struct.rb_iseq_struct*, i32) local_unnamed_addr #0

declare void @rb_gc_register_mark_object(i64) local_unnamed_addr #0

declare i8* @ruby_xmalloc2(i64, i64) local_unnamed_addr #0

declare void @rb_iseq_insns_info_encode_positions(%struct.rb_iseq_struct*) local_unnamed_addr #0

; Function Attrs: nofree norecurse nounwind ssp uwtable
define i64** @sorbet_setRubyStackFrame(i8* %0) local_unnamed_addr #3 {
  %2 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !9
  %3 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %2, i64 0, i32 2
  %4 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %3, align 8, !tbaa !11
  %5 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %4, i64 0, i32 2
  %6 = bitcast %struct.rb_iseq_struct** %5 to i8**
  store i8* %0, i8** %6, align 8, !tbaa !14
  %7 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %4, i64 0, i32 4
  %8 = load i64*, i64** %7, align 8, !tbaa !16
  %9 = load i64, i64* %8, align 8, !tbaa !17
  %10 = and i64 %9, -129
  store i64 %10, i64* %8, align 8, !tbaa !17
  %11 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %4, i64 0, i32 0
  ret i64** %11
}

declare i64 @rb_ary_new() local_unnamed_addr #0

declare i64 @rb_ary_dup(i64) local_unnamed_addr #0

; Function Attrs: argmemonly nounwind willreturn
declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #4

declare i64 @rb_ary_entry(i64, i64) local_unnamed_addr #0

; Function Attrs: argmemonly nounwind willreturn
declare void @llvm.lifetime.end.p0i8(i64 immarg, i8* nocapture) #4

; Function Attrs: nounwind ssp
define internal void @"Constr_stackFramePrecomputed_func_<root>.<static-init>$111"() #5 {
entryInitializers:
  %0 = tail call i64 @rb_str_new(i8* getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 16) #7
  %1 = tail call i64 @rb_str_new(i8* getelementptr inbounds ([32 x i8], [32 x i8]* @"str_test/testdata/compiler/splat.rb", i64 0, i64 0), i64 31) #7
  %2 = tail call i64 @rb_str_new(i8* getelementptr inbounds ([32 x i8], [32 x i8]* @"str_test/testdata/compiler/splat.rb", i64 0, i64 0), i64 31) #7
  %3 = tail call %struct.rb_iseq_struct* @rb_iseq_new(%struct.rb_ast_body_struct* null, i64 %0, i64 %1, i64 %2, %struct.rb_iseq_struct* null, i32 1) #7
  %4 = ptrtoint %struct.rb_iseq_struct* %3 to i64
  tail call void @rb_gc_register_mark_object(i64 %4) #7
  %5 = tail call i8* @ruby_xmalloc2(i64 8, i64 8) #7
  %6 = tail call i8* @ruby_xmalloc2(i64 8, i64 4) #7
  %7 = bitcast i8* %6 to i32*
  store i32 0, i32* %7, align 4, !tbaa !0
  %8 = bitcast i8* %5 to i32*
  store i32 4, i32* %8, align 4, !tbaa !18
  %9 = getelementptr inbounds i8, i8* %6, i64 4
  %10 = bitcast i8* %9 to i32*
  store i32 1, i32* %10, align 4, !tbaa !0
  %11 = getelementptr inbounds i8, i8* %5, i64 8
  %12 = bitcast i8* %11 to i32*
  store i32 5, i32* %12, align 4, !tbaa !18
  %13 = getelementptr inbounds i8, i8* %6, i64 8
  %14 = bitcast i8* %13 to i32*
  store i32 2, i32* %14, align 4, !tbaa !0
  %15 = getelementptr inbounds i8, i8* %5, i64 16
  %16 = bitcast i8* %15 to i32*
  store i32 6, i32* %16, align 4, !tbaa !18
  %17 = getelementptr inbounds i8, i8* %6, i64 12
  %18 = bitcast i8* %17 to i32*
  store i32 3, i32* %18, align 4, !tbaa !0
  %19 = getelementptr inbounds i8, i8* %5, i64 24
  %20 = bitcast i8* %19 to i32*
  store i32 7, i32* %20, align 4, !tbaa !18
  %21 = getelementptr inbounds i8, i8* %6, i64 16
  %22 = bitcast i8* %21 to i32*
  store i32 4, i32* %22, align 4, !tbaa !0
  %23 = getelementptr inbounds i8, i8* %5, i64 32
  %24 = bitcast i8* %23 to i32*
  store i32 8, i32* %24, align 4, !tbaa !18
  %25 = getelementptr inbounds i8, i8* %6, i64 20
  %26 = bitcast i8* %25 to i32*
  store i32 5, i32* %26, align 4, !tbaa !0
  %27 = getelementptr inbounds i8, i8* %5, i64 40
  %28 = bitcast i8* %27 to i32*
  store i32 9, i32* %28, align 4, !tbaa !18
  %29 = getelementptr inbounds i8, i8* %6, i64 24
  %30 = bitcast i8* %29 to i32*
  store i32 6, i32* %30, align 4, !tbaa !0
  %31 = getelementptr inbounds i8, i8* %5, i64 48
  %32 = bitcast i8* %31 to i32*
  store i32 10, i32* %32, align 4, !tbaa !18
  %33 = getelementptr inbounds i8, i8* %6, i64 28
  %34 = bitcast i8* %33 to i32*
  store i32 7, i32* %34, align 4, !tbaa !0
  %35 = getelementptr inbounds i8, i8* %5, i64 56
  %36 = bitcast i8* %35 to i32*
  store i32 11, i32* %36, align 4, !tbaa !18
  %37 = getelementptr inbounds %struct.rb_iseq_struct, %struct.rb_iseq_struct* %3, i64 0, i32 2
  %38 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %37, align 8, !tbaa !20
  %39 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %38, i64 0, i32 5, i32 0
  %40 = bitcast %struct.rb_code_position_struct** %39 to i8**
  store i8* %5, i8** %40, align 8, !tbaa !22
  %41 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %38, i64 0, i32 5, i32 1
  %42 = bitcast i32** %41 to i8**
  store i8* %6, i8** %42, align 8, !tbaa !31
  %43 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %38, i64 0, i32 1
  store i32 8, i32* %43, align 4, !tbaa !32
  %44 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %38, i64 0, i32 5, i32 2
  store i32 8, i32* %44, align 8, !tbaa !33
  tail call void @rb_iseq_insns_info_encode_positions(%struct.rb_iseq_struct* %3) #7
  %45 = load %struct.rb_iseq_constant_body*, %struct.rb_iseq_constant_body** %37, align 8, !tbaa !20
  %46 = getelementptr inbounds %struct.rb_iseq_constant_body, %struct.rb_iseq_constant_body* %45, i64 0, i32 2
  store i64* null, i64** %46, align 8, !tbaa !34
  store %struct.rb_iseq_struct* %3, %struct.rb_iseq_struct** bitcast (i8** @"stackFramePrecomputed_func_<root>.<static-init>$111" to %struct.rb_iseq_struct**), align 8
  ret void
}

; Function Attrs: nounwind ssp
define internal void @"Constr_rubyIdPrecomputed_<top (required)>"() #5 {
constr:
  %0 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 16) #7
  store i64 %0, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  ret void
}

; Function Attrs: nounwind ssp
define internal void @"Constr_rubyIdPrecomputed_[]"() #5 {
constr:
  %0 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([3 x i8], [3 x i8]* @"str_[]", i64 0, i64 0), i64 2) #7
  store i64 %0, i64* @"rubyIdPrecomputed_[]", align 8
  ret void
}

; Function Attrs: nounwind ssp
define internal void @Constr_rubyIdPrecomputed_puts() #5 {
constr:
  %0 = tail call i64 @rb_intern2(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @str_puts, i64 0, i64 0), i64 4) #7
  store i64 %0, i64* @rubyIdPrecomputed_puts, align 8
  ret void
}

; Function Attrs: nounwind sspreq
define void @Init_test_testdata_compiler_splat() local_unnamed_addr #6 {
typeTestSuccess.i:
  %callArgs.i = alloca [7 x i64], align 16
  %0 = load i64, i64* @rb_cObject, align 8
  %1 = bitcast [7 x i64]* %callArgs.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 56, i8* nonnull %1)
  %"rubyId_[].i" = load i64, i64* @"rubyIdPrecomputed_[]", align 8
  %rubyId_puts.i = load i64, i64* @rubyIdPrecomputed_puts, align 8
  %"stackFrame_func_<root>.<static-init>$11135.i" = load i64, i64* bitcast (i8** @"stackFramePrecomputed_func_<root>.<static-init>$111" to i64*), align 8
  %2 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !9
  %3 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %2, i64 0, i32 2
  %4 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %3, align 8, !tbaa !11
  %5 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %4, i64 0, i32 2
  %6 = bitcast %struct.rb_iseq_struct** %5 to i64*
  store i64 %"stackFrame_func_<root>.<static-init>$11135.i", i64* %6, align 8, !tbaa !14
  %7 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %4, i64 0, i32 4
  %8 = load i64*, i64** %7, align 8, !tbaa !16
  %9 = load i64, i64* %8, align 8, !tbaa !17
  %10 = and i64 %9, -129
  store i64 %10, i64* %8, align 8, !tbaa !17
  %11 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %4, i64 0, i32 0
  store i64* inttoptr (i64 8 to i64*), i64** %11, align 8, !tbaa !9
  %callArgsAddr.i = getelementptr inbounds [7 x i64], [7 x i64]* %callArgs.i, i64 0, i64 0
  %callArgsAddr103.i = getelementptr inbounds [7 x i64], [7 x i64]* %callArgs.i, i64 0, i64 1
  %callArgsAddr105.i = getelementptr inbounds [7 x i64], [7 x i64]* %callArgs.i, i64 0, i64 2
  %12 = bitcast [7 x i64]* %callArgs.i to <4 x i64>*
  store <4 x i64> <i64 3, i64 5, i64 7, i64 9>, <4 x i64>* %12, align 16
  %callArgsAddr109.i = getelementptr inbounds [7 x i64], [7 x i64]* %callArgs.i, i64 0, i64 4
  %13 = bitcast i64* %callArgsAddr109.i to <2 x i64>*
  store <2 x i64> <i64 11, i64 13>, <2 x i64>* %13, align 16
  %callArgsAddr113.i = getelementptr inbounds [7 x i64], [7 x i64]* %callArgs.i, i64 0, i64 6
  store i64 15, i64* %callArgsAddr113.i, align 16
  %14 = call i64 @rb_ary_new_from_values(i64 7, i64* nonnull %callArgsAddr.i) #7
  store i64 %14, i64* %callArgsAddr.i, align 16
  %15 = bitcast i64* %callArgsAddr103.i to <2 x i64>*
  store <2 x i64> <i64 3, i64 5>, <2 x i64>* %15, align 8
  %16 = inttoptr i64 %14 to %struct.RBasic*
  %17 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %16, i64 0, i32 0
  %18 = load i64, i64* %17, align 8, !tbaa !4, !noalias !35
  %19 = and i64 %18, 8192
  %20 = icmp eq i64 %19, 0
  br i1 %20, label %24, label %21

21:                                               ; preds = %typeTestSuccess.i
  %22 = lshr i64 %18, 15
  %23 = and i64 %22, 3
  br label %rb_array_len.exit.i.i

24:                                               ; preds = %typeTestSuccess.i
  %25 = inttoptr i64 %14 to %struct.RArray*
  %26 = getelementptr inbounds %struct.RArray, %struct.RArray* %25, i64 0, i32 1, i32 0, i32 0
  %27 = load i64, i64* %26, align 8, !tbaa !7, !noalias !35
  br label %rb_array_len.exit.i.i

rb_array_len.exit.i.i:                            ; preds = %24, %21
  %28 = phi i64 [ %23, %21 ], [ %27, %24 ]
  %29 = trunc i64 %28 to i32
  %30 = sub i32 3, %29
  %31 = icmp sgt i32 %30, 0
  br i1 %31, label %32, label %sorbet_splatIntrinsic.exit.i

32:                                               ; preds = %rb_array_len.exit.i.i
  %33 = call i64 @rb_ary_dup(i64 %14) #7, !noalias !35
  br label %34

34:                                               ; preds = %34, %32
  %35 = phi i32 [ 0, %32 ], [ %37, %34 ]
  %36 = call i64 @rb_ary_push(i64 %33, i64 8) #7, !noalias !35
  %37 = add nuw nsw i32 %35, 1
  %38 = icmp eq i32 %37, %30
  br i1 %38, label %sorbet_splatIntrinsic.exit.i, label %34

sorbet_splatIntrinsic.exit.i:                     ; preds = %34, %rb_array_len.exit.i.i
  %39 = phi i64 [ %14, %rb_array_len.exit.i.i ], [ %33, %34 ]
  %40 = and i64 %39, 7
  %41 = icmp ne i64 %40, 0
  %42 = and i64 %39, -9
  %43 = icmp eq i64 %42, 0
  %44 = or i1 %41, %43
  br i1 %44, label %sorbet_isa_Array.exit.thread.i, label %sorbet_isa_Array.exit.i, !prof !38

sorbet_isa_Array.exit.thread.i:                   ; preds = %sorbet_splatIntrinsic.exit.i
  store i64 1, i64* %callArgsAddr.i, align 16
  br label %"slowSymCallIntrinsic_[]153.i"

sorbet_isa_Array.exit.i:                          ; preds = %sorbet_splatIntrinsic.exit.i
  %45 = inttoptr i64 %39 to %struct.RBasic*
  %46 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %45, i64 0, i32 0
  %47 = load i64, i64* %46, align 8, !tbaa !4
  %48 = and i64 %47, 31
  %49 = icmp eq i64 %48, 7
  store i64 1, i64* %callArgsAddr.i, align 16
  br i1 %49, label %"fastSymCallIntrinsic_[]154.i", label %"slowSymCallIntrinsic_[]153.i", !prof !39, !misexpect !40

"afterSymCallIntrinsic_[]152.i":                  ; preds = %"fastSymCallIntrinsic_[]154.i", %"slowSymCallIntrinsic_[]153.i"
  %"symIntrinsicRawPhi_[]14915.i" = phi i64 [ %92, %"fastSymCallIntrinsic_[]154.i" ], [ %89, %"slowSymCallIntrinsic_[]153.i" ]
  %"symIntrinsicRawPhi_[]913.i" = phi i64 [ %91, %"fastSymCallIntrinsic_[]154.i" ], [ %88, %"slowSymCallIntrinsic_[]153.i" ]
  %"symIntrinsicRawPhi_[]164.i" = phi i64 [ %93, %"fastSymCallIntrinsic_[]154.i" ], [ %90, %"slowSymCallIntrinsic_[]153.i" ]
  store i64* inttoptr (i64 16 to i64*), i64** %11, align 8, !tbaa !9
  store i64 %"symIntrinsicRawPhi_[]913.i", i64* %callArgsAddr.i, align 16
  store i64 %"symIntrinsicRawPhi_[]14915.i", i64* %callArgsAddr103.i, align 8
  store i64 %"symIntrinsicRawPhi_[]164.i", i64* %callArgsAddr105.i, align 16
  %50 = call i64 @rb_ary_new_from_values(i64 3, i64* nonnull %callArgsAddr.i) #7
  store i64 %50, i64* %callArgsAddr.i, align 16
  %51 = call i64 @rb_funcallv(i64 %0, i64 %rubyId_puts.i, i32 1, i64* nonnull %callArgsAddr.i) #7
  store i64* inttoptr (i64 32 to i64*), i64** %11, align 8, !tbaa !9
  %52 = bitcast [7 x i64]* %callArgs.i to <2 x i64>*
  store <2 x i64> <i64 3, i64 5>, <2 x i64>* %52, align 16
  %53 = call i64 @rb_ary_new_from_values(i64 2, i64* nonnull %callArgsAddr.i) #7
  store i64 %53, i64* %callArgsAddr.i, align 16
  store <2 x i64> <i64 3, i64 5>, <2 x i64>* %15, align 8
  %54 = inttoptr i64 %53 to %struct.RBasic*
  %55 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %54, i64 0, i32 0
  %56 = load i64, i64* %55, align 8, !tbaa !4, !noalias !41
  %57 = and i64 %56, 8192
  %58 = icmp eq i64 %57, 0
  br i1 %58, label %62, label %59

59:                                               ; preds = %"afterSymCallIntrinsic_[]152.i"
  %60 = lshr i64 %56, 15
  %61 = and i64 %60, 3
  br label %rb_array_len.exit.i4.i

62:                                               ; preds = %"afterSymCallIntrinsic_[]152.i"
  %63 = inttoptr i64 %53 to %struct.RArray*
  %64 = getelementptr inbounds %struct.RArray, %struct.RArray* %63, i64 0, i32 1, i32 0, i32 0
  %65 = load i64, i64* %64, align 8, !tbaa !7, !noalias !41
  br label %rb_array_len.exit.i4.i

rb_array_len.exit.i4.i:                           ; preds = %62, %59
  %66 = phi i64 [ %61, %59 ], [ %65, %62 ]
  %67 = trunc i64 %66 to i32
  %68 = sub i32 3, %67
  %69 = icmp sgt i32 %68, 0
  br i1 %69, label %70, label %sorbet_splatIntrinsic.exit5.i

70:                                               ; preds = %rb_array_len.exit.i4.i
  %71 = call i64 @rb_ary_dup(i64 %53) #7, !noalias !41
  br label %72

72:                                               ; preds = %72, %70
  %73 = phi i32 [ 0, %70 ], [ %75, %72 ]
  %74 = call i64 @rb_ary_push(i64 %71, i64 8) #7, !noalias !41
  %75 = add nuw nsw i32 %73, 1
  %76 = icmp eq i32 %75, %68
  br i1 %76, label %sorbet_splatIntrinsic.exit5.i, label %72

sorbet_splatIntrinsic.exit5.i:                    ; preds = %72, %rb_array_len.exit.i4.i
  %77 = phi i64 [ %53, %rb_array_len.exit.i4.i ], [ %71, %72 ]
  %78 = and i64 %77, 7
  %79 = icmp ne i64 %78, 0
  %80 = and i64 %77, -9
  %81 = icmp eq i64 %80, 0
  %82 = or i1 %79, %81
  br i1 %82, label %sorbet_isa_Array.exit6.thread.i, label %sorbet_isa_Array.exit6.i, !prof !38

sorbet_isa_Array.exit6.thread.i:                  ; preds = %sorbet_splatIntrinsic.exit5.i
  store i64 1, i64* %callArgsAddr.i, align 16
  br label %"slowSymCallIntrinsic_[]228.i"

sorbet_isa_Array.exit6.i:                         ; preds = %sorbet_splatIntrinsic.exit5.i
  %83 = inttoptr i64 %77 to %struct.RBasic*
  %84 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %83, i64 0, i32 0
  %85 = load i64, i64* %84, align 8, !tbaa !4
  %86 = and i64 %85, 31
  %87 = icmp eq i64 %86, 7
  store i64 1, i64* %callArgsAddr.i, align 16
  br i1 %87, label %"fastSymCallIntrinsic_[]229.i", label %"slowSymCallIntrinsic_[]228.i", !prof !39, !misexpect !40

"slowSymCallIntrinsic_[]153.i":                   ; preds = %sorbet_isa_Array.exit.i, %sorbet_isa_Array.exit.thread.i
  %88 = call i64 @rb_funcallv(i64 %39, i64 %"rubyId_[].i", i32 1, i64* nonnull %callArgsAddr.i) #7
  store i64 -3, i64* %callArgsAddr.i, align 16
  %89 = call i64 @rb_funcallv(i64 %39, i64 %"rubyId_[].i", i32 1, i64* nonnull %callArgsAddr.i) #7
  store i64 -1, i64* %callArgsAddr.i, align 16
  %90 = call i64 @rb_funcallv(i64 %39, i64 %"rubyId_[].i", i32 1, i64* nonnull %callArgsAddr.i) #7
  br label %"afterSymCallIntrinsic_[]152.i"

"fastSymCallIntrinsic_[]154.i":                   ; preds = %sorbet_isa_Array.exit.i
  %91 = call i64 @rb_ary_entry(i64 %39, i64 0) #7
  store i64 -3, i64* %callArgsAddr.i, align 16
  %92 = call i64 @rb_ary_entry(i64 %39, i64 -2) #7
  store i64 -1, i64* %callArgsAddr.i, align 16
  %93 = call i64 @rb_ary_entry(i64 %39, i64 -1) #7
  br label %"afterSymCallIntrinsic_[]152.i"

"afterSymCallIntrinsic_[]227.i":                  ; preds = %"fastSymCallIntrinsic_[]229.i", %"slowSymCallIntrinsic_[]228.i"
  %"symIntrinsicRawPhi_[]22424.i" = phi i64 [ %135, %"fastSymCallIntrinsic_[]229.i" ], [ %132, %"slowSymCallIntrinsic_[]228.i" ]
  %"symIntrinsicRawPhi_[]2091822.i" = phi i64 [ %134, %"fastSymCallIntrinsic_[]229.i" ], [ %131, %"slowSymCallIntrinsic_[]228.i" ]
  %"symIntrinsicRawPhi_[]239.i" = phi i64 [ %136, %"fastSymCallIntrinsic_[]229.i" ], [ %133, %"slowSymCallIntrinsic_[]228.i" ]
  store i64* inttoptr (i64 40 to i64*), i64** %11, align 8, !tbaa !9
  store i64 %"symIntrinsicRawPhi_[]2091822.i", i64* %callArgsAddr.i, align 16
  store i64 %"symIntrinsicRawPhi_[]22424.i", i64* %callArgsAddr103.i, align 8
  store i64 %"symIntrinsicRawPhi_[]239.i", i64* %callArgsAddr105.i, align 16
  %94 = call i64 @rb_ary_new_from_values(i64 3, i64* nonnull %callArgsAddr.i) #7
  store i64 %94, i64* %callArgsAddr.i, align 16
  %95 = call i64 @rb_funcallv(i64 %0, i64 %rubyId_puts.i, i32 1, i64* nonnull %callArgsAddr.i) #7
  store i64* inttoptr (i64 56 to i64*), i64** %11, align 8, !tbaa !9
  %96 = call i64 @rb_ary_new() #7
  store i64 %96, i64* %callArgsAddr.i, align 16
  store <2 x i64> <i64 3, i64 5>, <2 x i64>* %15, align 8
  %97 = inttoptr i64 %96 to %struct.RBasic*
  %98 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %97, i64 0, i32 0
  %99 = load i64, i64* %98, align 8, !tbaa !4, !noalias !44
  %100 = and i64 %99, 8192
  %101 = icmp eq i64 %100, 0
  br i1 %101, label %105, label %102

102:                                              ; preds = %"afterSymCallIntrinsic_[]227.i"
  %103 = lshr i64 %99, 15
  %104 = and i64 %103, 3
  br label %rb_array_len.exit.i2.i

105:                                              ; preds = %"afterSymCallIntrinsic_[]227.i"
  %106 = inttoptr i64 %96 to %struct.RArray*
  %107 = getelementptr inbounds %struct.RArray, %struct.RArray* %106, i64 0, i32 1, i32 0, i32 0
  %108 = load i64, i64* %107, align 8, !tbaa !7, !noalias !44
  br label %rb_array_len.exit.i2.i

rb_array_len.exit.i2.i:                           ; preds = %105, %102
  %109 = phi i64 [ %104, %102 ], [ %108, %105 ]
  %110 = trunc i64 %109 to i32
  %111 = sub i32 3, %110
  %112 = icmp sgt i32 %111, 0
  br i1 %112, label %113, label %sorbet_splatIntrinsic.exit3.i

113:                                              ; preds = %rb_array_len.exit.i2.i
  %114 = call i64 @rb_ary_dup(i64 %96) #7, !noalias !44
  br label %115

115:                                              ; preds = %115, %113
  %116 = phi i32 [ 0, %113 ], [ %118, %115 ]
  %117 = call i64 @rb_ary_push(i64 %114, i64 8) #7, !noalias !44
  %118 = add nuw nsw i32 %116, 1
  %119 = icmp eq i32 %118, %111
  br i1 %119, label %sorbet_splatIntrinsic.exit3.i, label %115

sorbet_splatIntrinsic.exit3.i:                    ; preds = %115, %rb_array_len.exit.i2.i
  %120 = phi i64 [ %96, %rb_array_len.exit.i2.i ], [ %114, %115 ]
  %121 = and i64 %120, 7
  %122 = icmp ne i64 %121, 0
  %123 = and i64 %120, -9
  %124 = icmp eq i64 %123, 0
  %125 = or i1 %122, %124
  br i1 %125, label %sorbet_isa_Array.exit1.thread.i, label %sorbet_isa_Array.exit1.i, !prof !38

sorbet_isa_Array.exit1.thread.i:                  ; preds = %sorbet_splatIntrinsic.exit3.i
  store i64 1, i64* %callArgsAddr.i, align 16
  br label %"slowSymCallIntrinsic_[]298.i"

sorbet_isa_Array.exit1.i:                         ; preds = %sorbet_splatIntrinsic.exit3.i
  %126 = inttoptr i64 %120 to %struct.RBasic*
  %127 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %126, i64 0, i32 0
  %128 = load i64, i64* %127, align 8, !tbaa !4
  %129 = and i64 %128, 31
  %130 = icmp eq i64 %129, 7
  store i64 1, i64* %callArgsAddr.i, align 16
  br i1 %130, label %"fastSymCallIntrinsic_[]299.i", label %"slowSymCallIntrinsic_[]298.i", !prof !39, !misexpect !40

"slowSymCallIntrinsic_[]228.i":                   ; preds = %sorbet_isa_Array.exit6.i, %sorbet_isa_Array.exit6.thread.i
  %131 = call i64 @rb_funcallv(i64 %77, i64 %"rubyId_[].i", i32 1, i64* nonnull %callArgsAddr.i) #7
  store i64 -3, i64* %callArgsAddr.i, align 16
  %132 = call i64 @rb_funcallv(i64 %77, i64 %"rubyId_[].i", i32 1, i64* nonnull %callArgsAddr.i) #7
  store i64 -1, i64* %callArgsAddr.i, align 16
  %133 = call i64 @rb_funcallv(i64 %77, i64 %"rubyId_[].i", i32 1, i64* nonnull %callArgsAddr.i) #7
  br label %"afterSymCallIntrinsic_[]227.i"

"fastSymCallIntrinsic_[]229.i":                   ; preds = %sorbet_isa_Array.exit6.i
  %134 = call i64 @rb_ary_entry(i64 %77, i64 0) #7
  store i64 -3, i64* %callArgsAddr.i, align 16
  %135 = call i64 @rb_ary_entry(i64 %77, i64 -2) #7
  store i64 -1, i64* %callArgsAddr.i, align 16
  %136 = call i64 @rb_ary_entry(i64 %77, i64 -1) #7
  br label %"afterSymCallIntrinsic_[]227.i"

"slowSymCallIntrinsic_[]298.i":                   ; preds = %sorbet_isa_Array.exit1.i, %sorbet_isa_Array.exit1.thread.i
  %137 = call i64 @rb_funcallv(i64 %120, i64 %"rubyId_[].i", i32 1, i64* nonnull %callArgsAddr.i) #7
  store i64 -3, i64* %callArgsAddr.i, align 16
  %138 = call i64 @rb_funcallv(i64 %120, i64 %"rubyId_[].i", i32 1, i64* nonnull %callArgsAddr.i) #7
  store i64 -1, i64* %callArgsAddr.i, align 16
  %139 = call i64 @rb_funcallv(i64 %120, i64 %"rubyId_[].i", i32 1, i64* nonnull %callArgsAddr.i) #7
  br label %"func_<root>.<static-init>$111.exit"

"fastSymCallIntrinsic_[]299.i":                   ; preds = %sorbet_isa_Array.exit1.i
  %140 = call i64 @rb_ary_entry(i64 %120, i64 0) #7
  store i64 -3, i64* %callArgsAddr.i, align 16
  %141 = call i64 @rb_ary_entry(i64 %120, i64 -2) #7
  store i64 -1, i64* %callArgsAddr.i, align 16
  %142 = call i64 @rb_ary_entry(i64 %120, i64 -1) #7
  br label %"func_<root>.<static-init>$111.exit"

"func_<root>.<static-init>$111.exit":             ; preds = %"slowSymCallIntrinsic_[]298.i", %"fastSymCallIntrinsic_[]299.i"
  %"symIntrinsicRawPhi_[]29433.i" = phi i64 [ %141, %"fastSymCallIntrinsic_[]299.i" ], [ %138, %"slowSymCallIntrinsic_[]298.i" ]
  %"symIntrinsicRawPhi_[]2792731.i" = phi i64 [ %140, %"fastSymCallIntrinsic_[]299.i" ], [ %137, %"slowSymCallIntrinsic_[]298.i" ]
  %"symIntrinsicRawPhi_[]309.i" = phi i64 [ %142, %"fastSymCallIntrinsic_[]299.i" ], [ %139, %"slowSymCallIntrinsic_[]298.i" ]
  store i64* inttoptr (i64 64 to i64*), i64** %11, align 8, !tbaa !9
  store i64 %"symIntrinsicRawPhi_[]2792731.i", i64* %callArgsAddr.i, align 16
  store i64 %"symIntrinsicRawPhi_[]29433.i", i64* %callArgsAddr103.i, align 8
  store i64 %"symIntrinsicRawPhi_[]309.i", i64* %callArgsAddr105.i, align 16
  %143 = call i64 @rb_ary_new_from_values(i64 3, i64* nonnull %callArgsAddr.i) #7
  store i64 %143, i64* %callArgsAddr.i, align 16
  %144 = call i64 @rb_funcallv(i64 %0, i64 %rubyId_puts.i, i32 1, i64* nonnull %callArgsAddr.i) #7
  call void @llvm.lifetime.end.p0i8(i64 56, i8* nonnull %1)
  ret void
}

attributes #0 = { "addedToSilenceEmptyAttrsError" }
attributes #1 = { nounwind ssp uwtable }
attributes #2 = { norecurse nounwind readnone ssp uwtable }
attributes #3 = { nofree norecurse nounwind ssp uwtable }
attributes #4 = { argmemonly nounwind willreturn }
attributes #5 = { nounwind ssp }
attributes #6 = { nounwind sspreq }
attributes #7 = { nounwind }

!0 = !{!1, !1, i64 0}
!1 = !{!"int", !2, i64 0}
!2 = !{!"omnipotent char", !3, i64 0}
!3 = !{!"Simple C/C++ TBAA"}
!4 = !{!5, !6, i64 0}
!5 = !{!"RBasic", !6, i64 0, !6, i64 8}
!6 = !{!"long", !2, i64 0}
!7 = !{!2, !2, i64 0}
!8 = !{i32 1088}
!9 = !{!10, !10, i64 0}
!10 = !{!"any pointer", !2, i64 0}
!11 = !{!12, !10, i64 16}
!12 = !{!"rb_execution_context_struct", !10, i64 0, !6, i64 8, !10, i64 16, !10, i64 24, !10, i64 32, !1, i64 40, !1, i64 44, !10, i64 48, !10, i64 56, !10, i64 64, !6, i64 72, !6, i64 80, !10, i64 88, !6, i64 96, !10, i64 104, !10, i64 112, !6, i64 120, !6, i64 128, !2, i64 136, !2, i64 137, !6, i64 144, !13, i64 152}
!13 = !{!"", !10, i64 0, !10, i64 8, !6, i64 16, !2, i64 24}
!14 = !{!15, !10, i64 16}
!15 = !{!"rb_control_frame_struct", !10, i64 0, !10, i64 8, !10, i64 16, !6, i64 24, !10, i64 32, !10, i64 40, !10, i64 48}
!16 = !{!15, !10, i64 32}
!17 = !{!6, !6, i64 0}
!18 = !{!19, !1, i64 0}
!19 = !{!"iseq_insn_info_entry", !1, i64 0, !1, i64 4}
!20 = !{!21, !10, i64 16}
!21 = !{!"rb_iseq_struct", !6, i64 0, !6, i64 8, !10, i64 16, !2, i64 24}
!22 = !{!23, !10, i64 120}
!23 = !{!"rb_iseq_constant_body", !2, i64 0, !1, i64 4, !10, i64 8, !24, i64 16, !26, i64 64, !29, i64 120, !10, i64 152, !10, i64 160, !10, i64 168, !10, i64 176, !10, i64 184, !10, i64 192, !10, i64 200, !30, i64 208, !1, i64 240, !1, i64 244, !1, i64 248, !1, i64 252, !1, i64 256, !2, i64 260}
!24 = !{!"", !25, i64 0, !1, i64 4, !1, i64 8, !1, i64 12, !1, i64 16, !1, i64 20, !1, i64 24, !1, i64 28, !10, i64 32, !10, i64 40}
!25 = !{!"", !1, i64 0, !1, i64 0, !1, i64 0, !1, i64 0, !1, i64 0, !1, i64 0, !1, i64 0, !1, i64 0}
!26 = !{!"rb_iseq_location_struct", !6, i64 0, !6, i64 8, !6, i64 16, !6, i64 24, !1, i64 32, !27, i64 36}
!27 = !{!"rb_code_location_struct", !28, i64 0, !28, i64 8}
!28 = !{!"rb_code_position_struct", !1, i64 0, !1, i64 4}
!29 = !{!"iseq_insn_info", !10, i64 0, !10, i64 8, !1, i64 16, !10, i64 24}
!30 = !{!"", !6, i64 0, !6, i64 8, !6, i64 16, !10, i64 24}
!31 = !{!23, !10, i64 128}
!32 = !{!23, !1, i64 4}
!33 = !{!23, !1, i64 136}
!34 = !{!23, !10, i64 8}
!35 = !{!36}
!36 = distinct !{!36, !37, !"sorbet_splatIntrinsic: argument 0"}
!37 = distinct !{!37, !"sorbet_splatIntrinsic"}
!38 = !{!"branch_weights", i32 1073205, i32 2146410443}
!39 = !{!"branch_weights", i32 2000, i32 1}
!40 = !{!"misexpect", i64 0, i64 2000, i64 1}
!41 = !{!42}
!42 = distinct !{!42, !43, !"sorbet_splatIntrinsic: argument 0"}
!43 = distinct !{!43, !"sorbet_splatIntrinsic"}
!44 = !{!45}
!45 = distinct !{!45, !46, !"sorbet_splatIntrinsic: argument 0"}
!46 = distinct !{!46, !"sorbet_splatIntrinsic"}
