; ModuleID = 'payload'
source_filename = "llvm-link"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

%struct.rb_vm_struct = type { i64, %struct.rb_global_vm_lock_struct, %struct.rb_thread_struct*, %struct.rb_thread_struct*, i8*, i64, %union.pthread_mutex_t, %struct.list_head, %struct.list_head, %struct.list_head, %struct.list_head, i64, i32, i32, i8, i32, i64, [5 x i64], i64, i64, i64, i64, i64, i64, i64, %struct.st_table*, %struct.st_table*, %struct.anon.5, %struct.rb_hook_list_struct, %struct.st_table*, %struct.rb_postponed_job_struct*, i32, i32, %struct.list_head, %union.pthread_mutex_t, i64, i64, i64, i64, i64, i32, %struct.st_table*, %struct.rb_objspace*, %struct.rb_at_exit_list*, i64*, %struct.st_table*, %struct.rb_builtin_function*, i32, %struct.anon.6, [29 x i16] }
%struct.rb_global_vm_lock_struct = type { %struct.rb_thread_struct*, %union.pthread_mutex_t, %struct.list_head, %struct.rb_thread_struct*, i32, %union.pthread_cond_t, %union.pthread_cond_t, i32, i32 }
%union.pthread_cond_t = type { %struct.__pthread_cond_s }
%struct.__pthread_cond_s = type { %union.anon, %union.anon, [2 x i32], [2 x i32], i32, i32, [2 x i32] }
%union.anon = type { i64 }
%struct.rb_thread_struct = type { %struct.list_node, i64, %struct.rb_vm_struct*, %struct.rb_execution_context_struct*, i64, %struct.rb_calling_info*, i64, i64, i64, i8, i8, i32, %struct.native_thread_data_struct, i8*, i64, i64, i64, i64, %union.pthread_mutex_t, %struct.rb_unblock_callback, i64, %struct.rb_mutex_struct*, %struct.rb_thread_list_struct*, %union.anon.10, i32, i64, %struct.rb_fiber_struct*, [5 x i8*], i64 }
%struct.list_node = type { %struct.list_node*, %struct.list_node* }
%struct.rb_execution_context_struct = type { i64*, i64, %struct.rb_control_frame_struct*, %struct.rb_vm_tag*, %struct.rb_vm_protect_tag*, i32, i32, %struct.rb_fiber_struct*, %struct.rb_thread_struct*, %struct.st_table*, i64, i64, i64*, i64, %struct.rb_ensure_list*, %struct.rb_trace_arg_struct*, i64, i64, i8, i8, i64, %struct.anon.7 }
%struct.rb_control_frame_struct = type { i64*, i64*, %struct.rb_iseq_struct*, i64, i64*, i8*, i64* }
%struct.rb_iseq_struct = type { i64, i64, %struct.rb_iseq_constant_body*, %union.anon.17 }
%struct.rb_iseq_constant_body = type { i32, i32, i64*, %struct.anon, %struct.rb_iseq_location_struct, %struct.iseq_insn_info, i64*, %struct.iseq_catch_table*, %struct.rb_iseq_struct*, %struct.rb_iseq_struct*, %union.iseq_inline_storage_entry*, %struct.rb_call_data*, %struct.anon.16, i32, i32, i32, i32, i32, i8, i64 }
%struct.anon = type { %struct.anon.0, i32, i32, i32, i32, i32, i32, i32, i64*, %struct.rb_iseq_param_keyword* }
%struct.anon.0 = type { i16, [2 x i8] }
%struct.rb_iseq_param_keyword = type { i32, i32, i32, i32, i64*, i64* }
%struct.rb_iseq_location_struct = type { i64, i64, i64, i64, i32, %struct.rb_code_location_struct }
%struct.rb_code_location_struct = type { %struct.rb_code_position_struct, %struct.rb_code_position_struct }
%struct.rb_code_position_struct = type { i32, i32 }
%struct.iseq_insn_info = type { %struct.iseq_insn_info_entry*, i32*, i32, %struct.succ_index_table* }
%struct.iseq_insn_info_entry = type opaque
%struct.succ_index_table = type opaque
%struct.iseq_catch_table = type opaque
%union.iseq_inline_storage_entry = type { %struct.iseq_inline_cache_entry }
%struct.iseq_inline_cache_entry = type { i64, %struct.rb_cref_struct*, i64 }
%struct.rb_cref_struct = type { i64, i64, i64, %struct.rb_cref_struct*, %struct.rb_scope_visi_struct }
%struct.rb_scope_visi_struct = type { i8, [3 x i8] }
%struct.rb_call_data = type { %struct.rb_call_cache, %struct.rb_call_info }
%struct.rb_call_cache = type { i64, [3 x i64], %struct.rb_callable_method_entry_struct*, i64, i64 (%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_calling_info*, %struct.rb_call_data*)*, %union.anon.15 }
%struct.rb_callable_method_entry_struct = type { i64, i64, %struct.rb_method_definition_struct*, i64, i64 }
%struct.rb_method_definition_struct = type { i64, %union.anon.13, i64, i64 }
%union.anon.13 = type { %struct.rb_method_cfunc_struct }
%struct.rb_method_cfunc_struct = type { i64 (...)*, i64 (i64, i32, i64*, i64 (...)*)*, i32 }
%union.anon.15 = type { i32 }
%struct.rb_call_info = type { i64, i32, i32 }
%struct.anon.16 = type { i64, i64, i64, i64* }
%union.anon.17 = type { %struct.anon.18 }
%struct.anon.18 = type { i64, i32 }
%struct.rb_vm_tag = type { i64, i64, [5 x i8*], %struct.rb_vm_tag*, i32 }
%struct.rb_vm_protect_tag = type { %struct.rb_vm_protect_tag* }
%struct.rb_ensure_list = type { %struct.rb_ensure_list*, %struct.rb_ensure_entry }
%struct.rb_ensure_entry = type { i64, i64 (i64)*, i64 }
%struct.rb_trace_arg_struct = type { i32, %struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, i64, i64, i64, i64, i64, i32, i32, i64 }
%struct.anon.7 = type { i64*, i64*, i64, [1 x %struct.__jmp_buf_tag] }
%struct.__jmp_buf_tag = type { [8 x i64], i32, %struct.__sigset_t }
%struct.__sigset_t = type { [16 x i64] }
%struct.rb_calling_info = type { i64, i64, i32, i32 }
%struct.native_thread_data_struct = type { %struct.list_head, %union.anon.9 }
%union.anon.9 = type { %union.pthread_cond_t }
%struct.rb_unblock_callback = type { void (i8*)*, i8* }
%struct.rb_mutex_struct = type opaque
%struct.rb_thread_list_struct = type { %struct.rb_thread_list_struct*, %struct.rb_thread_struct* }
%union.anon.10 = type { %struct.anon.11 }
%struct.anon.11 = type { i64, i64, i32 }
%struct.rb_fiber_struct = type opaque
%struct.anon.5 = type { [65 x i64] }
%struct.rb_hook_list_struct = type { %struct.rb_event_hook_struct*, i32, i32, i32 }
%struct.rb_event_hook_struct = type opaque
%struct.rb_postponed_job_struct = type opaque
%struct.list_head = type { %struct.list_node }
%union.pthread_mutex_t = type { %struct.__pthread_mutex_s }
%struct.__pthread_mutex_s = type { i32, i32, i32, i32, i32, i16, i16, %struct.__pthread_internal_list }
%struct.__pthread_internal_list = type { %struct.__pthread_internal_list*, %struct.__pthread_internal_list* }
%struct.rb_objspace = type opaque
%struct.rb_at_exit_list = type { void (%struct.rb_vm_struct*)*, %struct.rb_at_exit_list* }
%struct.st_table = type { i8, i8, i8, i32, %struct.st_hash_type*, i64, i64*, i64, i64, %struct.st_table_entry* }
%struct.st_hash_type = type { i32 (i64, i64)*, i64 (i64)* }
%struct.st_table_entry = type opaque
%struct.rb_builtin_function = type opaque
%struct.anon.6 = type { i64, i64, i64, i64 }
%struct.SorbetLineNumberInfo = type { i32, %struct.iseq_insn_info_entry*, i64* }
%struct.FunctionInlineCache = type { %struct.rb_kwarg_call_data }
%struct.rb_kwarg_call_data = type { %struct.rb_call_cache, %struct.rb_call_info_with_kwarg }
%struct.rb_call_info_with_kwarg = type { %struct.rb_call_info, %struct.rb_call_info_kw_arg* }
%struct.rb_call_info_kw_arg = type { i32, [1 x i64] }
%struct.iseq_inline_iv_cache_entry = type { i64, i64 }

@ruby_current_vm_ptr = external local_unnamed_addr global %struct.rb_vm_struct*, align 8
@ruby_current_execution_context_ptr = external local_unnamed_addr global %struct.rb_execution_context_struct*, align 8
@rb_eRuntimeError = external local_unnamed_addr global i64, align 8
@.str.8 = private unnamed_addr constant [95 x i8] c"sorbet_getBuildSCMRevision: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@.str.9 = private unnamed_addr constant [93 x i8] c"sorbet_getIsReleaseBuild: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@"stackFramePrecomputed_func_<root>.<static-init>$152" = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@"rubyIdPrecomputed_<top (required)>" = internal unnamed_addr global i64 0, align 8
@"str_<top (required)>" = private unnamed_addr constant [17 x i8] c"<top (required)>\00", align 1
@"rubyStrFrozen_<top (required)>" = internal unnamed_addr global i64 0, align 8
@"rubyStrFrozen_test/testdata/compiler/splat_assign.rb" = internal unnamed_addr global i64 0, align 8
@"str_test/testdata/compiler/splat_assign.rb" = private unnamed_addr constant [39 x i8] c"test/testdata/compiler/splat_assign.rb\00", align 1
@iseqEncodedArray = internal global [13 x i64] zeroinitializer
@fileLineNumberInfo = internal global %struct.SorbetLineNumberInfo zeroinitializer
@"str_<build-array>" = private unnamed_addr constant [14 x i8] c"<build-array>\00", align 1
@"str_<expand-splat>" = private unnamed_addr constant [15 x i8] c"<expand-splat>\00", align 1
@"rubyIdPrecomputed_[]" = internal unnamed_addr global i64 0, align 8
@"str_[]" = private unnamed_addr constant [3 x i8] c"[]\00", align 1
@"ic_[]" = internal global %struct.FunctionInlineCache zeroinitializer
@"ic_[].1" = internal global %struct.FunctionInlineCache zeroinitializer
@"ic_[].2" = internal global %struct.FunctionInlineCache zeroinitializer
@ic_puts = internal global %struct.FunctionInlineCache zeroinitializer
@rubyIdPrecomputed_puts = internal unnamed_addr global i64 0, align 8
@str_puts = private unnamed_addr constant [5 x i8] c"puts\00", align 1
@"ic_[].3" = internal global %struct.FunctionInlineCache zeroinitializer
@"ic_[].4" = internal global %struct.FunctionInlineCache zeroinitializer
@"ic_[].5" = internal global %struct.FunctionInlineCache zeroinitializer
@ic_puts.6 = internal global %struct.FunctionInlineCache zeroinitializer
@"ic_[].7" = internal global %struct.FunctionInlineCache zeroinitializer
@"ic_[].8" = internal global %struct.FunctionInlineCache zeroinitializer
@"ic_[].9" = internal global %struct.FunctionInlineCache zeroinitializer
@ic_puts.10 = internal global %struct.FunctionInlineCache zeroinitializer

declare %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64, i64, i64, i64, %struct.rb_iseq_struct*, i32, i32, %struct.SorbetLineNumberInfo*, i64*, i32, i32) local_unnamed_addr #0

declare void @sorbet_initLineNumberInfo(%struct.SorbetLineNumberInfo*, i64*, i32) local_unnamed_addr #0

declare i64 @sorbet_readRealpath() local_unnamed_addr #0

declare void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache*, i64, i32, i32, i32, i64*) local_unnamed_addr #0

declare i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache*, i64) local_unnamed_addr #0

declare void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_iseq_struct*) local_unnamed_addr #0

declare i64 @sorbet_vm_expandSplatIntrinsic(i64, i64, i64) local_unnamed_addr #0

declare i64 @sorbet_rb_array_square_br_slowpath(i64, i64, i32, i64*, i64 (i64, i64, i32, i64*, i64)*, i64) local_unnamed_addr #0

declare i64 @rb_intern2(i8*, i64) local_unnamed_addr #0

declare i64 @rb_ary_new_from_values(i64, i64*) local_unnamed_addr #0

declare i64 @rb_fstring_new(i8*, i64) local_unnamed_addr #0

declare void @rb_gc_register_mark_object(i64) local_unnamed_addr #0

; Function Attrs: noreturn
declare void @rb_raise(i64, i8*, ...) local_unnamed_addr #1

declare i64 @rb_ary_entry(i64, i64) local_unnamed_addr #0

declare i64 @rb_ary_new() local_unnamed_addr #0

declare i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct*, i32) local_unnamed_addr #0

; Function Attrs: alwaysinline nounwind ssp uwtable
define noalias nonnull i8* @sorbet_allocateParamInfo() local_unnamed_addr #2 {
  %1 = tail call noalias nonnull i8* @ruby_xcalloc(i64 noundef 1, i64 noundef 64) #8
  ret i8* %1
}

; Function Attrs: allocsize(0,1)
declare noalias nonnull i8* @ruby_xcalloc(i64, i64) local_unnamed_addr #3

; Function Attrs: nounwind ssp uwtable
define weak i32 @sorbet_getIsReleaseBuild() local_unnamed_addr #4 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !4
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* noundef getelementptr inbounds ([93 x i8], [93 x i8]* @.str.9, i64 0, i64 0)) #9
  unreachable
}

; Function Attrs: nounwind ssp uwtable
define weak i8* @sorbet_getBuildSCMRevision() local_unnamed_addr #4 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !4
  tail call void (i64, i8*, ...) @rb_raise(i64 %1, i8* noundef getelementptr inbounds ([95 x i8], [95 x i8]* @.str.8, i64 0, i64 0)) #9
  unreachable
}

; Function Attrs: sspreq
define void @Init_splat_assign() local_unnamed_addr #5 {
entry:
  %callArgs.i = alloca [8 x i64], align 8
  %locals.i.i = alloca i64, i32 0, align 8
  %realpath = tail call i64 @sorbet_readRealpath()
  %0 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 noundef 16) #10
  store i64 %0, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %1 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([14 x i8], [14 x i8]* @"str_<build-array>", i64 0, i64 0), i64 noundef 13) #10
  %2 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([15 x i8], [15 x i8]* @"str_<expand-splat>", i64 0, i64 0), i64 noundef 14) #10
  %3 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([3 x i8], [3 x i8]* @"str_[]", i64 0, i64 0), i64 noundef 2) #10
  store i64 %3, i64* @"rubyIdPrecomputed_[]", align 8
  %4 = tail call i64 @rb_intern2(i8* noundef getelementptr inbounds ([5 x i8], [5 x i8]* @str_puts, i64 0, i64 0), i64 noundef 4) #10
  store i64 %4, i64* @rubyIdPrecomputed_puts, align 8
  %5 = tail call i64 @rb_fstring_new(i8* noundef getelementptr inbounds ([17 x i8], [17 x i8]* @"str_<top (required)>", i64 0, i64 0), i64 noundef 16) #10
  tail call void @rb_gc_register_mark_object(i64 %5) #10
  store i64 %5, i64* @"rubyStrFrozen_<top (required)>", align 8
  %6 = tail call i64 @rb_fstring_new(i8* noundef getelementptr inbounds ([39 x i8], [39 x i8]* @"str_test/testdata/compiler/splat_assign.rb", i64 0, i64 0), i64 noundef 38) #10
  tail call void @rb_gc_register_mark_object(i64 %6) #10
  store i64 %6, i64* @"rubyStrFrozen_test/testdata/compiler/splat_assign.rb", align 8
  tail call void @sorbet_initLineNumberInfo(%struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef getelementptr inbounds ([13 x i64], [13 x i64]* @iseqEncodedArray, i32 0, i32 0), i32 noundef 13)
  %"rubyId_<top (required)>.i.i" = load i64, i64* @"rubyIdPrecomputed_<top (required)>", align 8
  %"rubyStr_<top (required)>.i.i" = load i64, i64* @"rubyStrFrozen_<top (required)>", align 8
  %"rubyStr_test/testdata/compiler/splat_assign.rb.i.i" = load i64, i64* @"rubyStrFrozen_test/testdata/compiler/splat_assign.rb", align 8
  %7 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 %"rubyStr_<top (required)>.i.i", i64 %"rubyId_<top (required)>.i.i", i64 %"rubyStr_test/testdata/compiler/splat_assign.rb.i.i", i64 %realpath, %struct.rb_iseq_struct* noundef null, i32 noundef 0, i32 noundef 5, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef nonnull %locals.i.i, i32 noundef 0, i32 noundef 8)
  store %struct.rb_iseq_struct* %7, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_<root>.<static-init>$152", align 8
  %"rubyId_[].i" = load i64, i64* @"rubyIdPrecomputed_[]", align 8, !dbg !8
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @"ic_[]", i64 %"rubyId_[].i", i32 noundef 16, i32 noundef 1, i32 noundef 0, i64* noundef null), !dbg !8
  %"rubyId_[]1.i" = load i64, i64* @"rubyIdPrecomputed_[]", align 8, !dbg !8
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @"ic_[].1", i64 %"rubyId_[]1.i", i32 noundef 16, i32 noundef 1, i32 noundef 0, i64* noundef null), !dbg !8
  %"rubyId_[]3.i" = load i64, i64* @"rubyIdPrecomputed_[]", align 8, !dbg !8
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @"ic_[].2", i64 %"rubyId_[]3.i", i32 noundef 16, i32 noundef 1, i32 noundef 0, i64* noundef null), !dbg !8
  %rubyId_puts.i = load i64, i64* @rubyIdPrecomputed_puts, align 8, !dbg !13
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_puts, i64 %rubyId_puts.i, i32 noundef 20, i32 noundef 1, i32 noundef 0, i64* noundef null), !dbg !13
  %"rubyId_[]6.i" = load i64, i64* @"rubyIdPrecomputed_[]", align 8, !dbg !14
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @"ic_[].3", i64 %"rubyId_[]6.i", i32 noundef 16, i32 noundef 1, i32 noundef 0, i64* noundef null), !dbg !14
  %"rubyId_[]8.i" = load i64, i64* @"rubyIdPrecomputed_[]", align 8, !dbg !14
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @"ic_[].4", i64 %"rubyId_[]8.i", i32 noundef 16, i32 noundef 1, i32 noundef 0, i64* noundef null), !dbg !14
  %"rubyId_[]10.i" = load i64, i64* @"rubyIdPrecomputed_[]", align 8, !dbg !14
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @"ic_[].5", i64 %"rubyId_[]10.i", i32 noundef 16, i32 noundef 1, i32 noundef 0, i64* noundef null), !dbg !14
  %rubyId_puts12.i = load i64, i64* @rubyIdPrecomputed_puts, align 8, !dbg !15
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_puts.6, i64 %rubyId_puts12.i, i32 noundef 20, i32 noundef 1, i32 noundef 0, i64* noundef null), !dbg !15
  %"rubyId_[]15.i" = load i64, i64* @"rubyIdPrecomputed_[]", align 8, !dbg !16
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @"ic_[].7", i64 %"rubyId_[]15.i", i32 noundef 16, i32 noundef 1, i32 noundef 0, i64* noundef null), !dbg !16
  %"rubyId_[]17.i" = load i64, i64* @"rubyIdPrecomputed_[]", align 8, !dbg !16
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @"ic_[].8", i64 %"rubyId_[]17.i", i32 noundef 16, i32 noundef 1, i32 noundef 0, i64* noundef null), !dbg !16
  %"rubyId_[]19.i" = load i64, i64* @"rubyIdPrecomputed_[]", align 8, !dbg !16
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @"ic_[].9", i64 %"rubyId_[]19.i", i32 noundef 16, i32 noundef 1, i32 noundef 0, i64* noundef null), !dbg !16
  %rubyId_puts21.i = load i64, i64* @rubyIdPrecomputed_puts, align 8, !dbg !17
  call void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_puts.10, i64 %rubyId_puts21.i, i32 noundef 20, i32 noundef 1, i32 noundef 0, i64* noundef null), !dbg !17
  %8 = load %struct.rb_vm_struct*, %struct.rb_vm_struct** @ruby_current_vm_ptr, align 8, !tbaa !18
  %9 = getelementptr inbounds %struct.rb_vm_struct, %struct.rb_vm_struct* %8, i64 0, i32 18
  %10 = load i64, i64* %9, align 8, !tbaa !20
  %11 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !tbaa !18
  %12 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %11, i64 0, i32 2
  %13 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %12, align 8, !tbaa !30
  %14 = bitcast [8 x i64]* %callArgs.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 64, i8* nonnull %14)
  %stackFrame.i = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_<root>.<static-init>$152", align 8
  %15 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %12, align 8, !tbaa !30
  %16 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %15, i64 0, i32 2
  store %struct.rb_iseq_struct* %stackFrame.i, %struct.rb_iseq_struct** %16, align 8, !tbaa !33
  %17 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %15, i64 0, i32 4
  %18 = load i64*, i64** %17, align 8, !tbaa !35
  %19 = load i64, i64* %18, align 8, !tbaa !4
  %20 = and i64 %19, -33
  store i64 %20, i64* %18, align 8, !tbaa !4
  call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* %11, %struct.rb_control_frame_struct* %15, %struct.rb_iseq_struct* %stackFrame.i) #10
  %21 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %13, i64 0, i32 0
  store i64* getelementptr inbounds ([13 x i64], [13 x i64]* @iseqEncodedArray, i64 0, i64 5), i64** %21, align 8, !dbg !36, !tbaa !18
  %callArgs0Addr.i = getelementptr [8 x i64], [8 x i64]* %callArgs.i, i32 0, i64 0, !dbg !37
  %callArgs1Addr.i = getelementptr [8 x i64], [8 x i64]* %callArgs.i, i32 0, i64 1, !dbg !37
  %callArgs2Addr.i = getelementptr [8 x i64], [8 x i64]* %callArgs.i, i32 0, i64 2, !dbg !37
  %22 = bitcast i64* %callArgs0Addr.i to <4 x i64>*, !dbg !37
  store <4 x i64> <i64 3, i64 5, i64 7, i64 9>, <4 x i64>* %22, align 8, !dbg !37
  %callArgs4Addr.i = getelementptr [8 x i64], [8 x i64]* %callArgs.i, i32 0, i64 4, !dbg !37
  %23 = bitcast i64* %callArgs4Addr.i to <2 x i64>*, !dbg !37
  store <2 x i64> <i64 11, i64 13>, <2 x i64>* %23, align 8, !dbg !37
  %callArgs6Addr.i = getelementptr [8 x i64], [8 x i64]* %callArgs.i, i32 0, i64 6, !dbg !37
  store i64 15, i64* %callArgs6Addr.i, align 8, !dbg !37
  %24 = getelementptr [8 x i64], [8 x i64]* %callArgs.i, i64 0, i64 0, !dbg !37
  call void @llvm.experimental.noalias.scope.decl(metadata !38) #10, !dbg !37
  %25 = call i64 @rb_ary_new_from_values(i64 noundef 7, i64* noundef nonnull align 8 %24) #10, !dbg !37
  store i64 %25, i64* %callArgs0Addr.i, align 8, !dbg !8
  %26 = bitcast i64* %callArgs1Addr.i to <2 x i64>*, !dbg !8
  store <2 x i64> <i64 3, i64 5>, <2 x i64>* %26, align 8, !dbg !8
  call void @llvm.experimental.noalias.scope.decl(metadata !41) #10, !dbg !8
  %27 = load i64, i64* %24, align 8, !dbg !8, !tbaa !4, !alias.scope !41
  %28 = getelementptr inbounds i64, i64* %24, i64 1, !dbg !8
  %29 = getelementptr inbounds i64, i64* %24, i64 2, !dbg !8
  %30 = call i64 @sorbet_vm_expandSplatIntrinsic(i64 %27, i64 3, i64 5) #10, !dbg !8, !noalias !41
  %31 = and i64 %30, 7, !dbg !8
  %32 = icmp ne i64 %31, 0, !dbg !8
  %33 = and i64 %30, -9, !dbg !8
  %34 = icmp eq i64 %33, 0, !dbg !8
  %35 = or i1 %32, %34, !dbg !8
  br i1 %35, label %"alternativeCallIntrinsic_Array_[]141.i", label %sorbet_isa_Array.exit, !dbg !8

sorbet_isa_Array.exit:                            ; preds = %entry
  %36 = inttoptr i64 %30 to %struct.iseq_inline_iv_cache_entry*, !dbg !8
  %37 = getelementptr inbounds %struct.iseq_inline_iv_cache_entry, %struct.iseq_inline_iv_cache_entry* %36, i64 0, i32 0, !dbg !8
  %38 = load i64, i64* %37, align 8, !dbg !8, !tbaa !44
  %39 = and i64 %38, 31, !dbg !8
  %40 = icmp eq i64 %39, 7, !dbg !8
  br i1 %40, label %"fastSymCallIntrinsic_Array_[].i", label %"alternativeCallIntrinsic_Array_[]141.i", !dbg !8, !prof !46

"fastSymCallIntrinsic_Array_[].i":                ; preds = %sorbet_isa_Array.exit
  %"rubyId_[].i1" = load i64, i64* @"rubyIdPrecomputed_[]", align 8, !dbg !8
  store i64 1, i64* %callArgs0Addr.i, align 8, !dbg !8
  call void @llvm.experimental.noalias.scope.decl(metadata !47) #10, !dbg !8
  %41 = load i64, i64* %24, align 8, !dbg !8, !tbaa !4, !alias.scope !47
  %42 = and i64 %41, 1, !dbg !8
  %43 = icmp eq i64 %42, 0, !dbg !8
  br i1 %43, label %47, label %44, !dbg !8, !prof !50

44:                                               ; preds = %"fastSymCallIntrinsic_Array_[].i"
  %45 = ashr i64 %41, 1, !dbg !8
  %46 = call i64 @rb_ary_entry(i64 %30, i64 %45) #10, !dbg !8
  br label %sorbet_rb_array_square_br.exit371.i, !dbg !8

47:                                               ; preds = %"fastSymCallIntrinsic_Array_[].i"
  %48 = call i64 @sorbet_rb_array_square_br_slowpath(i64 %30, i64 %"rubyId_[].i1", i32 noundef 1, i64* noundef nonnull %24, i64 (i64, i64, i32, i64*, i64)* noundef null, i64 noundef 0) #10, !dbg !8
  br label %sorbet_rb_array_square_br.exit371.i, !dbg !8

sorbet_rb_array_square_br.exit371.i:              ; preds = %47, %44
  %49 = phi i64 [ %48, %47 ], [ %46, %44 ], !dbg !8
  %50 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !8, !tbaa !18
  %51 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %50, i64 0, i32 5, !dbg !8
  %52 = load i32, i32* %51, align 8, !dbg !8, !tbaa !51
  %53 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %50, i64 0, i32 6, !dbg !8
  %54 = load i32, i32* %53, align 4, !dbg !8, !tbaa !52
  %55 = xor i32 %54, -1, !dbg !8
  %56 = and i32 %55, %52, !dbg !8
  %57 = icmp eq i32 %56, 0, !dbg !8
  br i1 %57, label %"fastSymCallIntrinsic_Array_[]128.i", label %58, !dbg !8, !prof !46

58:                                               ; preds = %sorbet_rb_array_square_br.exit371.i
  %59 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %50, i64 0, i32 8, !dbg !8
  %60 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %59, align 8, !dbg !8, !tbaa !53
  %61 = call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* %60, i32 noundef 0) #10, !dbg !8
  br label %"fastSymCallIntrinsic_Array_[]128.i", !dbg !8

"fastSymCallIntrinsic_Array_[]128.i":             ; preds = %58, %sorbet_rb_array_square_br.exit371.i
  %"rubyId_[]130.i" = load i64, i64* @"rubyIdPrecomputed_[]", align 8, !dbg !8
  store i64 -3, i64* %callArgs0Addr.i, align 8, !dbg !8
  call void @llvm.experimental.noalias.scope.decl(metadata !54) #10, !dbg !8
  %62 = load i64, i64* %24, align 8, !dbg !8, !tbaa !4, !alias.scope !54
  %63 = and i64 %62, 1, !dbg !8
  %64 = icmp eq i64 %63, 0, !dbg !8
  br i1 %64, label %68, label %65, !dbg !8, !prof !50

65:                                               ; preds = %"fastSymCallIntrinsic_Array_[]128.i"
  %66 = ashr i64 %62, 1, !dbg !8
  %67 = call i64 @rb_ary_entry(i64 %30, i64 %66) #10, !dbg !8
  br label %sorbet_rb_array_square_br.exit372.i, !dbg !8

68:                                               ; preds = %"fastSymCallIntrinsic_Array_[]128.i"
  %69 = call i64 @sorbet_rb_array_square_br_slowpath(i64 %30, i64 %"rubyId_[]130.i", i32 noundef 1, i64* noundef nonnull %24, i64 (i64, i64, i32, i64*, i64)* noundef null, i64 noundef 0) #10, !dbg !8
  br label %sorbet_rb_array_square_br.exit372.i, !dbg !8

sorbet_rb_array_square_br.exit372.i:              ; preds = %68, %65
  %70 = phi i64 [ %69, %68 ], [ %67, %65 ], !dbg !8
  %71 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !8, !tbaa !18
  %72 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %71, i64 0, i32 5, !dbg !8
  %73 = load i32, i32* %72, align 8, !dbg !8, !tbaa !51
  %74 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %71, i64 0, i32 6, !dbg !8
  %75 = load i32, i32* %74, align 4, !dbg !8, !tbaa !52
  %76 = xor i32 %75, -1, !dbg !8
  %77 = and i32 %76, %73, !dbg !8
  %78 = icmp eq i32 %77, 0, !dbg !8
  br i1 %78, label %"fastSymCallIntrinsic_Array_[]142.i", label %79, !dbg !8, !prof !46

79:                                               ; preds = %sorbet_rb_array_square_br.exit372.i
  %80 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %71, i64 0, i32 8, !dbg !8
  %81 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %80, align 8, !dbg !8, !tbaa !53
  %82 = call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* %81, i32 noundef 0) #10, !dbg !8
  br label %"fastSymCallIntrinsic_Array_[]142.i", !dbg !8

afterSend139.i:                                   ; preds = %129, %sorbet_rb_array_square_br.exit373.i, %"alternativeCallIntrinsic_Array_[]141.i"
  %"symIntrinsicRawPhi_[]12616.i" = phi i64 [ %send137.i, %"alternativeCallIntrinsic_Array_[]141.i" ], [ %70, %sorbet_rb_array_square_br.exit373.i ], [ %70, %129 ]
  %"symIntrinsicRawPhi_[]1014.i" = phi i64 [ %send.i, %"alternativeCallIntrinsic_Array_[]141.i" ], [ %49, %sorbet_rb_array_square_br.exit373.i ], [ %49, %129 ]
  %"symIntrinsicRawPhi_[]140.i" = phi i64 [ %send151.i, %"alternativeCallIntrinsic_Array_[]141.i" ], [ %120, %sorbet_rb_array_square_br.exit373.i ], [ %120, %129 ], !dbg !8
  store i64* getelementptr inbounds ([13 x i64], [13 x i64]* @iseqEncodedArray, i64 0, i64 6), i64** %21, align 8, !dbg !36, !tbaa !18
  store i64 %"symIntrinsicRawPhi_[]1014.i", i64* %callArgs0Addr.i, align 8, !dbg !57
  store i64 %"symIntrinsicRawPhi_[]12616.i", i64* %callArgs1Addr.i, align 8, !dbg !57
  store i64 %"symIntrinsicRawPhi_[]140.i", i64* %callArgs2Addr.i, align 8, !dbg !57
  call void @llvm.experimental.noalias.scope.decl(metadata !58) #10, !dbg !57
  %83 = call i64 @rb_ary_new_from_values(i64 noundef 3, i64* noundef nonnull %24) #10, !dbg !57
  %84 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %13, i64 0, i32 1, !dbg !13
  %85 = load i64*, i64** %84, align 8, !dbg !13, !tbaa !61
  %86 = getelementptr inbounds i64, i64* %85, i64 1, !dbg !13
  store i64 %10, i64* %85, align 8, !dbg !13, !tbaa !4
  %87 = getelementptr inbounds i64, i64* %86, i64 1, !dbg !13
  store i64* %87, i64** %84, align 8, !dbg !13, !tbaa !61
  store i64 %83, i64* %86, align 8, !dbg !13, !tbaa !4
  %send167.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @ic_puts, i64 0) #10, !dbg !13
  store i64* getelementptr inbounds ([13 x i64], [13 x i64]* @iseqEncodedArray, i64 0, i64 8), i64** %21, align 8, !dbg !13, !tbaa !18
  %88 = bitcast i64* %callArgs0Addr.i to <2 x i64>*, !dbg !62
  store <2 x i64> <i64 3, i64 5>, <2 x i64>* %88, align 8, !dbg !62
  call void @llvm.experimental.noalias.scope.decl(metadata !63) #10, !dbg !62
  %89 = call i64 @rb_ary_new_from_values(i64 noundef 2, i64* noundef nonnull %24) #10, !dbg !62
  store i64 %89, i64* %callArgs0Addr.i, align 8, !dbg !14
  store <2 x i64> <i64 3, i64 5>, <2 x i64>* %26, align 8, !dbg !14
  call void @llvm.experimental.noalias.scope.decl(metadata !66) #10, !dbg !14
  %90 = load i64, i64* %24, align 8, !dbg !14, !tbaa !4, !alias.scope !66
  %91 = call i64 @sorbet_vm_expandSplatIntrinsic(i64 %90, i64 3, i64 5) #10, !dbg !14, !noalias !66
  %92 = and i64 %91, 7, !dbg !14
  %93 = icmp ne i64 %92, 0, !dbg !14
  %94 = and i64 %91, -9, !dbg !14
  %95 = icmp eq i64 %94, 0, !dbg !14
  %96 = or i1 %93, %95, !dbg !14
  br i1 %96, label %"alternativeCallIntrinsic_Array_[]223.i", label %sorbet_isa_Array.exit3, !dbg !14

sorbet_isa_Array.exit3:                           ; preds = %afterSend139.i
  %97 = inttoptr i64 %91 to %struct.iseq_inline_iv_cache_entry*, !dbg !14
  %98 = getelementptr inbounds %struct.iseq_inline_iv_cache_entry, %struct.iseq_inline_iv_cache_entry* %97, i64 0, i32 0, !dbg !14
  %99 = load i64, i64* %98, align 8, !dbg !14, !tbaa !44
  %100 = and i64 %99, 31, !dbg !14
  %101 = icmp eq i64 %100, 7, !dbg !14
  br i1 %101, label %"fastSymCallIntrinsic_Array_[]196.i", label %"alternativeCallIntrinsic_Array_[]223.i", !dbg !14, !prof !46

"alternativeCallIntrinsic_Array_[]141.i":         ; preds = %entry, %sorbet_isa_Array.exit
  %102 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %13, i64 0, i32 1, !dbg !8
  %103 = load i64*, i64** %102, align 8, !dbg !8, !tbaa !61
  %104 = getelementptr inbounds i64, i64* %103, i64 1, !dbg !8
  store i64 %30, i64* %103, align 8, !dbg !8, !tbaa !4
  %105 = getelementptr inbounds i64, i64* %104, i64 1, !dbg !8
  store i64* %105, i64** %102, align 8, !dbg !8, !tbaa !61
  store i64 1, i64* %104, align 8, !dbg !8, !tbaa !4
  %send.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @"ic_[]", i64 0) #10, !dbg !8
  %106 = load i64*, i64** %102, align 8, !dbg !8, !tbaa !61
  %107 = getelementptr inbounds i64, i64* %106, i64 1, !dbg !8
  store i64 %30, i64* %106, align 8, !dbg !8, !tbaa !4
  %108 = getelementptr inbounds i64, i64* %107, i64 1, !dbg !8
  store i64* %108, i64** %102, align 8, !dbg !8, !tbaa !61
  store i64 -3, i64* %107, align 8, !dbg !8, !tbaa !4
  %send137.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @"ic_[].1", i64 0) #10, !dbg !8
  %109 = load i64*, i64** %102, align 8, !dbg !8, !tbaa !61
  %110 = getelementptr inbounds i64, i64* %109, i64 1, !dbg !8
  store i64 %30, i64* %109, align 8, !dbg !8, !tbaa !4
  %111 = getelementptr inbounds i64, i64* %110, i64 1, !dbg !8
  store i64* %111, i64** %102, align 8, !dbg !8, !tbaa !61
  store i64 -1, i64* %110, align 8, !dbg !8, !tbaa !4
  %send151.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @"ic_[].2", i64 0) #10, !dbg !8
  br label %afterSend139.i, !dbg !8

"fastSymCallIntrinsic_Array_[]142.i":             ; preds = %79, %sorbet_rb_array_square_br.exit372.i
  %"rubyId_[]144.i" = load i64, i64* @"rubyIdPrecomputed_[]", align 8, !dbg !8
  store i64 -1, i64* %callArgs0Addr.i, align 8, !dbg !8
  call void @llvm.experimental.noalias.scope.decl(metadata !69) #10, !dbg !8
  %112 = load i64, i64* %24, align 8, !dbg !8, !tbaa !4, !alias.scope !69
  %113 = and i64 %112, 1, !dbg !8
  %114 = icmp eq i64 %113, 0, !dbg !8
  br i1 %114, label %118, label %115, !dbg !8, !prof !50

115:                                              ; preds = %"fastSymCallIntrinsic_Array_[]142.i"
  %116 = ashr i64 %112, 1, !dbg !8
  %117 = call i64 @rb_ary_entry(i64 %30, i64 %116) #10, !dbg !8
  br label %sorbet_rb_array_square_br.exit373.i, !dbg !8

118:                                              ; preds = %"fastSymCallIntrinsic_Array_[]142.i"
  %119 = call i64 @sorbet_rb_array_square_br_slowpath(i64 %30, i64 %"rubyId_[]144.i", i32 noundef 1, i64* noundef nonnull %24, i64 (i64, i64, i32, i64*, i64)* noundef null, i64 noundef 0) #10, !dbg !8
  br label %sorbet_rb_array_square_br.exit373.i, !dbg !8

sorbet_rb_array_square_br.exit373.i:              ; preds = %118, %115
  %120 = phi i64 [ %119, %118 ], [ %117, %115 ], !dbg !8
  %121 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !8, !tbaa !18
  %122 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %121, i64 0, i32 5, !dbg !8
  %123 = load i32, i32* %122, align 8, !dbg !8, !tbaa !51
  %124 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %121, i64 0, i32 6, !dbg !8
  %125 = load i32, i32* %124, align 4, !dbg !8, !tbaa !52
  %126 = xor i32 %125, -1, !dbg !8
  %127 = and i32 %126, %123, !dbg !8
  %128 = icmp eq i32 %127, 0, !dbg !8
  br i1 %128, label %afterSend139.i, label %129, !dbg !8, !prof !46

129:                                              ; preds = %sorbet_rb_array_square_br.exit373.i
  %130 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %121, i64 0, i32 8, !dbg !8
  %131 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %130, align 8, !dbg !8, !tbaa !53
  %132 = call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* %131, i32 noundef 0) #10, !dbg !8
  br label %afterSend139.i, !dbg !8

"fastSymCallIntrinsic_Array_[]196.i":             ; preds = %sorbet_isa_Array.exit3
  %"rubyId_[]198.i" = load i64, i64* @"rubyIdPrecomputed_[]", align 8, !dbg !14
  store i64 1, i64* %callArgs0Addr.i, align 8, !dbg !14
  call void @llvm.experimental.noalias.scope.decl(metadata !72) #10, !dbg !14
  %133 = load i64, i64* %24, align 8, !dbg !14, !tbaa !4, !alias.scope !72
  %134 = and i64 %133, 1, !dbg !14
  %135 = icmp eq i64 %134, 0, !dbg !14
  br i1 %135, label %139, label %136, !dbg !14, !prof !50

136:                                              ; preds = %"fastSymCallIntrinsic_Array_[]196.i"
  %137 = ashr i64 %133, 1, !dbg !14
  %138 = call i64 @rb_ary_entry(i64 %91, i64 %137) #10, !dbg !14
  br label %sorbet_rb_array_square_br.exit374.i, !dbg !14

139:                                              ; preds = %"fastSymCallIntrinsic_Array_[]196.i"
  %140 = call i64 @sorbet_rb_array_square_br_slowpath(i64 %91, i64 %"rubyId_[]198.i", i32 noundef 1, i64* noundef nonnull %24, i64 (i64, i64, i32, i64*, i64)* noundef null, i64 noundef 0) #10, !dbg !14
  br label %sorbet_rb_array_square_br.exit374.i, !dbg !14

sorbet_rb_array_square_br.exit374.i:              ; preds = %139, %136
  %141 = phi i64 [ %140, %139 ], [ %138, %136 ], !dbg !14
  %142 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !14, !tbaa !18
  %143 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %142, i64 0, i32 5, !dbg !14
  %144 = load i32, i32* %143, align 8, !dbg !14, !tbaa !51
  %145 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %142, i64 0, i32 6, !dbg !14
  %146 = load i32, i32* %145, align 4, !dbg !14, !tbaa !52
  %147 = xor i32 %146, -1, !dbg !14
  %148 = and i32 %147, %144, !dbg !14
  %149 = icmp eq i32 %148, 0, !dbg !14
  br i1 %149, label %"fastSymCallIntrinsic_Array_[]210.i", label %150, !dbg !14, !prof !46

150:                                              ; preds = %sorbet_rb_array_square_br.exit374.i
  %151 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %142, i64 0, i32 8, !dbg !14
  %152 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %151, align 8, !dbg !14, !tbaa !53
  %153 = call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* %152, i32 noundef 0) #10, !dbg !14
  br label %"fastSymCallIntrinsic_Array_[]210.i", !dbg !14

"fastSymCallIntrinsic_Array_[]210.i":             ; preds = %150, %sorbet_rb_array_square_br.exit374.i
  %"rubyId_[]212.i" = load i64, i64* @"rubyIdPrecomputed_[]", align 8, !dbg !14
  store i64 -3, i64* %callArgs0Addr.i, align 8, !dbg !14
  call void @llvm.experimental.noalias.scope.decl(metadata !75) #10, !dbg !14
  %154 = load i64, i64* %24, align 8, !dbg !14, !tbaa !4, !alias.scope !75
  %155 = and i64 %154, 1, !dbg !14
  %156 = icmp eq i64 %155, 0, !dbg !14
  br i1 %156, label %160, label %157, !dbg !14, !prof !50

157:                                              ; preds = %"fastSymCallIntrinsic_Array_[]210.i"
  %158 = ashr i64 %154, 1, !dbg !14
  %159 = call i64 @rb_ary_entry(i64 %91, i64 %158) #10, !dbg !14
  br label %sorbet_rb_array_square_br.exit375.i, !dbg !14

160:                                              ; preds = %"fastSymCallIntrinsic_Array_[]210.i"
  %161 = call i64 @sorbet_rb_array_square_br_slowpath(i64 %91, i64 %"rubyId_[]212.i", i32 noundef 1, i64* noundef nonnull %24, i64 (i64, i64, i32, i64*, i64)* noundef null, i64 noundef 0) #10, !dbg !14
  br label %sorbet_rb_array_square_br.exit375.i, !dbg !14

sorbet_rb_array_square_br.exit375.i:              ; preds = %160, %157
  %162 = phi i64 [ %161, %160 ], [ %159, %157 ], !dbg !14
  %163 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !14, !tbaa !18
  %164 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %163, i64 0, i32 5, !dbg !14
  %165 = load i32, i32* %164, align 8, !dbg !14, !tbaa !51
  %166 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %163, i64 0, i32 6, !dbg !14
  %167 = load i32, i32* %166, align 4, !dbg !14, !tbaa !52
  %168 = xor i32 %167, -1, !dbg !14
  %169 = and i32 %168, %165, !dbg !14
  %170 = icmp eq i32 %169, 0, !dbg !14
  br i1 %170, label %"fastSymCallIntrinsic_Array_[]224.i", label %171, !dbg !14, !prof !46

171:                                              ; preds = %sorbet_rb_array_square_br.exit375.i
  %172 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %163, i64 0, i32 8, !dbg !14
  %173 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %172, align 8, !dbg !14, !tbaa !53
  %174 = call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* %173, i32 noundef 0) #10, !dbg !14
  br label %"fastSymCallIntrinsic_Array_[]224.i", !dbg !14

afterSend221.i:                                   ; preds = %218, %sorbet_rb_array_square_br.exit376.i, %"alternativeCallIntrinsic_Array_[]223.i"
  %"symIntrinsicRawPhi_[]20828.i" = phi i64 [ %send219.i, %"alternativeCallIntrinsic_Array_[]223.i" ], [ %162, %sorbet_rb_array_square_br.exit376.i ], [ %162, %218 ]
  %"symIntrinsicRawPhi_[]1942126.i" = phi i64 [ %send205.i, %"alternativeCallIntrinsic_Array_[]223.i" ], [ %141, %sorbet_rb_array_square_br.exit376.i ], [ %141, %218 ]
  %"symIntrinsicRawPhi_[]222.i" = phi i64 [ %send233.i, %"alternativeCallIntrinsic_Array_[]223.i" ], [ %209, %sorbet_rb_array_square_br.exit376.i ], [ %209, %218 ], !dbg !14
  store i64* getelementptr inbounds ([13 x i64], [13 x i64]* @iseqEncodedArray, i64 0, i64 9), i64** %21, align 8, !dbg !36, !tbaa !18
  store i64 %"symIntrinsicRawPhi_[]1942126.i", i64* %callArgs0Addr.i, align 8, !dbg !78
  store i64 %"symIntrinsicRawPhi_[]20828.i", i64* %callArgs1Addr.i, align 8, !dbg !78
  store i64 %"symIntrinsicRawPhi_[]222.i", i64* %callArgs2Addr.i, align 8, !dbg !78
  call void @llvm.experimental.noalias.scope.decl(metadata !79) #10, !dbg !78
  %175 = call i64 @rb_ary_new_from_values(i64 noundef 3, i64* noundef nonnull %24) #10, !dbg !78
  %176 = load i64*, i64** %84, align 8, !dbg !15, !tbaa !61
  %177 = getelementptr inbounds i64, i64* %176, i64 1, !dbg !15
  store i64 %10, i64* %176, align 8, !dbg !15, !tbaa !4
  %178 = getelementptr inbounds i64, i64* %177, i64 1, !dbg !15
  store i64* %178, i64** %84, align 8, !dbg !15, !tbaa !61
  store i64 %175, i64* %177, align 8, !dbg !15, !tbaa !4
  %send250.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @ic_puts.6, i64 0) #10, !dbg !15
  store i64* getelementptr inbounds ([13 x i64], [13 x i64]* @iseqEncodedArray, i64 0, i64 11), i64** %21, align 8, !dbg !36, !tbaa !18
  call void @llvm.experimental.noalias.scope.decl(metadata !82) #10, !dbg !85
  %179 = call i64 @rb_ary_new() #10, !dbg !85
  store i64 %179, i64* %callArgs0Addr.i, align 8, !dbg !16
  store <2 x i64> <i64 3, i64 5>, <2 x i64>* %26, align 8, !dbg !16
  call void @llvm.experimental.noalias.scope.decl(metadata !86) #10, !dbg !16
  %180 = load i64, i64* %24, align 8, !dbg !16, !tbaa !4, !alias.scope !86
  %181 = call i64 @sorbet_vm_expandSplatIntrinsic(i64 %180, i64 3, i64 5) #10, !dbg !16, !noalias !86
  %182 = and i64 %181, 7, !dbg !16
  %183 = icmp ne i64 %182, 0, !dbg !16
  %184 = and i64 %181, -9, !dbg !16
  %185 = icmp eq i64 %184, 0, !dbg !16
  %186 = or i1 %183, %185, !dbg !16
  br i1 %186, label %"alternativeCallIntrinsic_Array_[]300.i", label %sorbet_isa_Array.exit2, !dbg !16

sorbet_isa_Array.exit2:                           ; preds = %afterSend221.i
  %187 = inttoptr i64 %181 to %struct.iseq_inline_iv_cache_entry*, !dbg !16
  %188 = getelementptr inbounds %struct.iseq_inline_iv_cache_entry, %struct.iseq_inline_iv_cache_entry* %187, i64 0, i32 0, !dbg !16
  %189 = load i64, i64* %188, align 8, !dbg !16, !tbaa !44
  %190 = and i64 %189, 31, !dbg !16
  %191 = icmp eq i64 %190, 7, !dbg !16
  br i1 %191, label %"fastSymCallIntrinsic_Array_[]273.i", label %"alternativeCallIntrinsic_Array_[]300.i", !dbg !16, !prof !46

"alternativeCallIntrinsic_Array_[]223.i":         ; preds = %afterSend139.i, %sorbet_isa_Array.exit3
  %192 = load i64*, i64** %84, align 8, !dbg !14, !tbaa !61
  %193 = getelementptr inbounds i64, i64* %192, i64 1, !dbg !14
  store i64 %91, i64* %192, align 8, !dbg !14, !tbaa !4
  %194 = getelementptr inbounds i64, i64* %193, i64 1, !dbg !14
  store i64* %194, i64** %84, align 8, !dbg !14, !tbaa !61
  store i64 1, i64* %193, align 8, !dbg !14, !tbaa !4
  %send205.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @"ic_[].3", i64 0) #10, !dbg !14
  %195 = load i64*, i64** %84, align 8, !dbg !14, !tbaa !61
  %196 = getelementptr inbounds i64, i64* %195, i64 1, !dbg !14
  store i64 %91, i64* %195, align 8, !dbg !14, !tbaa !4
  %197 = getelementptr inbounds i64, i64* %196, i64 1, !dbg !14
  store i64* %197, i64** %84, align 8, !dbg !14, !tbaa !61
  store i64 -3, i64* %196, align 8, !dbg !14, !tbaa !4
  %send219.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @"ic_[].4", i64 0) #10, !dbg !14
  %198 = load i64*, i64** %84, align 8, !dbg !14, !tbaa !61
  %199 = getelementptr inbounds i64, i64* %198, i64 1, !dbg !14
  store i64 %91, i64* %198, align 8, !dbg !14, !tbaa !4
  %200 = getelementptr inbounds i64, i64* %199, i64 1, !dbg !14
  store i64* %200, i64** %84, align 8, !dbg !14, !tbaa !61
  store i64 -1, i64* %199, align 8, !dbg !14, !tbaa !4
  %send233.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @"ic_[].5", i64 0) #10, !dbg !14
  br label %afterSend221.i, !dbg !14

"fastSymCallIntrinsic_Array_[]224.i":             ; preds = %171, %sorbet_rb_array_square_br.exit375.i
  %"rubyId_[]226.i" = load i64, i64* @"rubyIdPrecomputed_[]", align 8, !dbg !14
  store i64 -1, i64* %callArgs0Addr.i, align 8, !dbg !14
  call void @llvm.experimental.noalias.scope.decl(metadata !89) #10, !dbg !14
  %201 = load i64, i64* %24, align 8, !dbg !14, !tbaa !4, !alias.scope !89
  %202 = and i64 %201, 1, !dbg !14
  %203 = icmp eq i64 %202, 0, !dbg !14
  br i1 %203, label %207, label %204, !dbg !14, !prof !50

204:                                              ; preds = %"fastSymCallIntrinsic_Array_[]224.i"
  %205 = ashr i64 %201, 1, !dbg !14
  %206 = call i64 @rb_ary_entry(i64 %91, i64 %205) #10, !dbg !14
  br label %sorbet_rb_array_square_br.exit376.i, !dbg !14

207:                                              ; preds = %"fastSymCallIntrinsic_Array_[]224.i"
  %208 = call i64 @sorbet_rb_array_square_br_slowpath(i64 %91, i64 %"rubyId_[]226.i", i32 noundef 1, i64* noundef nonnull %24, i64 (i64, i64, i32, i64*, i64)* noundef null, i64 noundef 0) #10, !dbg !14
  br label %sorbet_rb_array_square_br.exit376.i, !dbg !14

sorbet_rb_array_square_br.exit376.i:              ; preds = %207, %204
  %209 = phi i64 [ %208, %207 ], [ %206, %204 ], !dbg !14
  %210 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !14, !tbaa !18
  %211 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %210, i64 0, i32 5, !dbg !14
  %212 = load i32, i32* %211, align 8, !dbg !14, !tbaa !51
  %213 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %210, i64 0, i32 6, !dbg !14
  %214 = load i32, i32* %213, align 4, !dbg !14, !tbaa !52
  %215 = xor i32 %214, -1, !dbg !14
  %216 = and i32 %215, %212, !dbg !14
  %217 = icmp eq i32 %216, 0, !dbg !14
  br i1 %217, label %afterSend221.i, label %218, !dbg !14, !prof !46

218:                                              ; preds = %sorbet_rb_array_square_br.exit376.i
  %219 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %210, i64 0, i32 8, !dbg !14
  %220 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %219, align 8, !dbg !14, !tbaa !53
  %221 = call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* %220, i32 noundef 0) #10, !dbg !14
  br label %afterSend221.i, !dbg !14

"fastSymCallIntrinsic_Array_[]273.i":             ; preds = %sorbet_isa_Array.exit2
  %"rubyId_[]275.i" = load i64, i64* @"rubyIdPrecomputed_[]", align 8, !dbg !16
  store i64 1, i64* %callArgs0Addr.i, align 8, !dbg !16
  call void @llvm.experimental.noalias.scope.decl(metadata !92) #10, !dbg !16
  %222 = load i64, i64* %24, align 8, !dbg !16, !tbaa !4, !alias.scope !92
  %223 = and i64 %222, 1, !dbg !16
  %224 = icmp eq i64 %223, 0, !dbg !16
  br i1 %224, label %228, label %225, !dbg !16, !prof !50

225:                                              ; preds = %"fastSymCallIntrinsic_Array_[]273.i"
  %226 = ashr i64 %222, 1, !dbg !16
  %227 = call i64 @rb_ary_entry(i64 %181, i64 %226) #10, !dbg !16
  br label %sorbet_rb_array_square_br.exit370.i, !dbg !16

228:                                              ; preds = %"fastSymCallIntrinsic_Array_[]273.i"
  %229 = call i64 @sorbet_rb_array_square_br_slowpath(i64 %181, i64 %"rubyId_[]275.i", i32 noundef 1, i64* noundef nonnull %24, i64 (i64, i64, i32, i64*, i64)* noundef null, i64 noundef 0) #10, !dbg !16
  br label %sorbet_rb_array_square_br.exit370.i, !dbg !16

sorbet_rb_array_square_br.exit370.i:              ; preds = %228, %225
  %230 = phi i64 [ %229, %228 ], [ %227, %225 ], !dbg !16
  %231 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !16, !tbaa !18
  %232 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %231, i64 0, i32 5, !dbg !16
  %233 = load i32, i32* %232, align 8, !dbg !16, !tbaa !51
  %234 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %231, i64 0, i32 6, !dbg !16
  %235 = load i32, i32* %234, align 4, !dbg !16, !tbaa !52
  %236 = xor i32 %235, -1, !dbg !16
  %237 = and i32 %236, %233, !dbg !16
  %238 = icmp eq i32 %237, 0, !dbg !16
  br i1 %238, label %"fastSymCallIntrinsic_Array_[]287.i", label %239, !dbg !16, !prof !46

239:                                              ; preds = %sorbet_rb_array_square_br.exit370.i
  %240 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %231, i64 0, i32 8, !dbg !16
  %241 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %240, align 8, !dbg !16, !tbaa !53
  %242 = call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* %241, i32 noundef 0) #10, !dbg !16
  br label %"fastSymCallIntrinsic_Array_[]287.i", !dbg !16

"fastSymCallIntrinsic_Array_[]287.i":             ; preds = %239, %sorbet_rb_array_square_br.exit370.i
  %"rubyId_[]289.i" = load i64, i64* @"rubyIdPrecomputed_[]", align 8, !dbg !16
  store i64 -3, i64* %callArgs0Addr.i, align 8, !dbg !16
  call void @llvm.experimental.noalias.scope.decl(metadata !95) #10, !dbg !16
  %243 = load i64, i64* %24, align 8, !dbg !16, !tbaa !4, !alias.scope !95
  %244 = and i64 %243, 1, !dbg !16
  %245 = icmp eq i64 %244, 0, !dbg !16
  br i1 %245, label %249, label %246, !dbg !16, !prof !50

246:                                              ; preds = %"fastSymCallIntrinsic_Array_[]287.i"
  %247 = ashr i64 %243, 1, !dbg !16
  %248 = call i64 @rb_ary_entry(i64 %181, i64 %247) #10, !dbg !16
  br label %sorbet_rb_array_square_br.exit369.i, !dbg !16

249:                                              ; preds = %"fastSymCallIntrinsic_Array_[]287.i"
  %250 = call i64 @sorbet_rb_array_square_br_slowpath(i64 %181, i64 %"rubyId_[]289.i", i32 noundef 1, i64* noundef nonnull %24, i64 (i64, i64, i32, i64*, i64)* noundef null, i64 noundef 0) #10, !dbg !16
  br label %sorbet_rb_array_square_br.exit369.i, !dbg !16

sorbet_rb_array_square_br.exit369.i:              ; preds = %249, %246
  %251 = phi i64 [ %250, %249 ], [ %248, %246 ], !dbg !16
  %252 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !16, !tbaa !18
  %253 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %252, i64 0, i32 5, !dbg !16
  %254 = load i32, i32* %253, align 8, !dbg !16, !tbaa !51
  %255 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %252, i64 0, i32 6, !dbg !16
  %256 = load i32, i32* %255, align 4, !dbg !16, !tbaa !52
  %257 = xor i32 %256, -1, !dbg !16
  %258 = and i32 %257, %254, !dbg !16
  %259 = icmp eq i32 %258, 0, !dbg !16
  br i1 %259, label %"fastSymCallIntrinsic_Array_[]301.i", label %260, !dbg !16, !prof !46

260:                                              ; preds = %sorbet_rb_array_square_br.exit369.i
  %261 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %252, i64 0, i32 8, !dbg !16
  %262 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %261, align 8, !dbg !16, !tbaa !53
  %263 = call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* %262, i32 noundef 0) #10, !dbg !16
  br label %"fastSymCallIntrinsic_Array_[]301.i", !dbg !16

"alternativeCallIntrinsic_Array_[]300.i":         ; preds = %afterSend221.i, %sorbet_isa_Array.exit2
  %264 = load i64*, i64** %84, align 8, !dbg !16, !tbaa !61
  %265 = getelementptr inbounds i64, i64* %264, i64 1, !dbg !16
  store i64 %181, i64* %264, align 8, !dbg !16, !tbaa !4
  %266 = getelementptr inbounds i64, i64* %265, i64 1, !dbg !16
  store i64* %266, i64** %84, align 8, !dbg !16, !tbaa !61
  store i64 1, i64* %265, align 8, !dbg !16, !tbaa !4
  %send282.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @"ic_[].7", i64 0) #10, !dbg !16
  %267 = load i64*, i64** %84, align 8, !dbg !16, !tbaa !61
  %268 = getelementptr inbounds i64, i64* %267, i64 1, !dbg !16
  store i64 %181, i64* %267, align 8, !dbg !16, !tbaa !4
  %269 = getelementptr inbounds i64, i64* %268, i64 1, !dbg !16
  store i64* %269, i64** %84, align 8, !dbg !16, !tbaa !61
  store i64 -3, i64* %268, align 8, !dbg !16, !tbaa !4
  %send296.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @"ic_[].8", i64 0) #10, !dbg !16
  %270 = load i64*, i64** %84, align 8, !dbg !16, !tbaa !61
  %271 = getelementptr inbounds i64, i64* %270, i64 1, !dbg !16
  store i64 %181, i64* %270, align 8, !dbg !16, !tbaa !4
  %272 = getelementptr inbounds i64, i64* %271, i64 1, !dbg !16
  store i64* %272, i64** %84, align 8, !dbg !16, !tbaa !61
  store i64 -1, i64* %271, align 8, !dbg !16, !tbaa !4
  %send310.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @"ic_[].9", i64 0) #10, !dbg !16
  br label %"func_<root>.<static-init>$152.exit", !dbg !16

"fastSymCallIntrinsic_Array_[]301.i":             ; preds = %260, %sorbet_rb_array_square_br.exit369.i
  %"rubyId_[]303.i" = load i64, i64* @"rubyIdPrecomputed_[]", align 8, !dbg !16
  store i64 -1, i64* %callArgs0Addr.i, align 8, !dbg !16
  call void @llvm.experimental.noalias.scope.decl(metadata !98) #10, !dbg !16
  %273 = load i64, i64* %24, align 8, !dbg !16, !tbaa !4, !alias.scope !98
  %274 = and i64 %273, 1, !dbg !16
  %275 = icmp eq i64 %274, 0, !dbg !16
  br i1 %275, label %279, label %276, !dbg !16, !prof !50

276:                                              ; preds = %"fastSymCallIntrinsic_Array_[]301.i"
  %277 = ashr i64 %273, 1, !dbg !16
  %278 = call i64 @rb_ary_entry(i64 %181, i64 %277) #10, !dbg !16
  br label %sorbet_rb_array_square_br.exit.i, !dbg !16

279:                                              ; preds = %"fastSymCallIntrinsic_Array_[]301.i"
  %280 = call i64 @sorbet_rb_array_square_br_slowpath(i64 %181, i64 %"rubyId_[]303.i", i32 noundef 1, i64* noundef nonnull %24, i64 (i64, i64, i32, i64*, i64)* noundef null, i64 noundef 0) #10, !dbg !16
  br label %sorbet_rb_array_square_br.exit.i, !dbg !16

sorbet_rb_array_square_br.exit.i:                 ; preds = %279, %276
  %281 = phi i64 [ %280, %279 ], [ %278, %276 ], !dbg !16
  %282 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_execution_context_ptr, align 8, !dbg !16, !tbaa !18
  %283 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %282, i64 0, i32 5, !dbg !16
  %284 = load i32, i32* %283, align 8, !dbg !16, !tbaa !51
  %285 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %282, i64 0, i32 6, !dbg !16
  %286 = load i32, i32* %285, align 4, !dbg !16, !tbaa !52
  %287 = xor i32 %286, -1, !dbg !16
  %288 = and i32 %287, %284, !dbg !16
  %289 = icmp eq i32 %288, 0, !dbg !16
  br i1 %289, label %"func_<root>.<static-init>$152.exit", label %290, !dbg !16, !prof !46

290:                                              ; preds = %sorbet_rb_array_square_br.exit.i
  %291 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %282, i64 0, i32 8, !dbg !16
  %292 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %291, align 8, !dbg !16, !tbaa !53
  %293 = call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* %292, i32 noundef 0) #10, !dbg !16
  br label %"func_<root>.<static-init>$152.exit", !dbg !16

"func_<root>.<static-init>$152.exit":             ; preds = %"alternativeCallIntrinsic_Array_[]300.i", %sorbet_rb_array_square_br.exit.i, %290
  %"symIntrinsicRawPhi_[]28540.i" = phi i64 [ %send296.i, %"alternativeCallIntrinsic_Array_[]300.i" ], [ %251, %sorbet_rb_array_square_br.exit.i ], [ %251, %290 ]
  %"symIntrinsicRawPhi_[]2713338.i" = phi i64 [ %send282.i, %"alternativeCallIntrinsic_Array_[]300.i" ], [ %230, %sorbet_rb_array_square_br.exit.i ], [ %230, %290 ]
  %"symIntrinsicRawPhi_[]299.i" = phi i64 [ %send310.i, %"alternativeCallIntrinsic_Array_[]300.i" ], [ %281, %sorbet_rb_array_square_br.exit.i ], [ %281, %290 ], !dbg !16
  store i64* getelementptr inbounds ([13 x i64], [13 x i64]* @iseqEncodedArray, i64 0, i64 12), i64** %21, align 8, !dbg !36, !tbaa !18
  store i64 %"symIntrinsicRawPhi_[]2713338.i", i64* %callArgs0Addr.i, align 8, !dbg !101
  store i64 %"symIntrinsicRawPhi_[]28540.i", i64* %callArgs1Addr.i, align 8, !dbg !101
  store i64 %"symIntrinsicRawPhi_[]299.i", i64* %callArgs2Addr.i, align 8, !dbg !101
  call void @llvm.experimental.noalias.scope.decl(metadata !102) #10, !dbg !101
  %294 = call i64 @rb_ary_new_from_values(i64 noundef 3, i64* noundef nonnull %24) #10, !dbg !101
  %295 = load i64*, i64** %84, align 8, !dbg !17, !tbaa !61
  %296 = getelementptr inbounds i64, i64* %295, i64 1, !dbg !17
  store i64 %10, i64* %295, align 8, !dbg !17, !tbaa !4
  %297 = getelementptr inbounds i64, i64* %296, i64 1, !dbg !17
  store i64* %297, i64** %84, align 8, !dbg !17, !tbaa !61
  store i64 %294, i64* %296, align 8, !dbg !17, !tbaa !4
  %send327.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @ic_puts.10, i64 0) #10, !dbg !17
  call void @llvm.lifetime.end.p0i8(i64 64, i8* nonnull %14)
  ret void
}

; Function Attrs: inaccessiblememonly nofree nosync nounwind willreturn
declare void @llvm.experimental.noalias.scope.decl(metadata) #6

; Function Attrs: argmemonly nofree nosync nounwind willreturn
declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #7

; Function Attrs: argmemonly nofree nosync nounwind willreturn
declare void @llvm.lifetime.end.p0i8(i64 immarg, i8* nocapture) #7

attributes #0 = { "addedToSilenceEmptyAttrsError" }
attributes #1 = { noreturn }
attributes #2 = { alwaysinline nounwind ssp uwtable }
attributes #3 = { allocsize(0,1) }
attributes #4 = { nounwind ssp uwtable }
attributes #5 = { sspreq }
attributes #6 = { inaccessiblememonly nofree nosync nounwind willreturn }
attributes #7 = { argmemonly nofree nosync nounwind willreturn }
attributes #8 = { nounwind allocsize(0,1) }
attributes #9 = { noreturn nounwind }
attributes #10 = { nounwind }

!llvm.module.flags = !{!0}
!llvm.dbg.cu = !{!1}

!0 = !{i32 2, !"Debug Info Version", i32 3}
!1 = distinct !DICompileUnit(language: DW_LANG_C, file: !2, producer: "Sorbet LLVM", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, enums: !3)
!2 = !DIFile(filename: "test/testdata/compiler/splat_assign.rb", directory: ".")
!3 = !{}
!4 = !{!5, !5, i64 0}
!5 = !{!"long", !6, i64 0}
!6 = !{!"omnipotent char", !7, i64 0}
!7 = !{!"Simple C/C++ TBAA"}
!8 = !DILocation(line: 5, column: 1, scope: !9)
!9 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.<static-init>$152", scope: null, file: !2, line: 5, type: !10, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !1, retainedNodes: !3)
!10 = !DISubroutineType(types: !11)
!11 = !{!12}
!12 = !DIBasicType(name: "VALUE", size: 64, encoding: DW_ATE_signed)
!13 = !DILocation(line: 6, column: 1, scope: !9)
!14 = !DILocation(line: 8, column: 1, scope: !9)
!15 = !DILocation(line: 9, column: 1, scope: !9)
!16 = !DILocation(line: 11, column: 1, scope: !9)
!17 = !DILocation(line: 12, column: 1, scope: !9)
!18 = !{!19, !19, i64 0}
!19 = !{!"any pointer", !6, i64 0}
!20 = !{!21, !5, i64 400}
!21 = !{!"rb_vm_struct", !5, i64 0, !22, i64 8, !19, i64 192, !19, i64 200, !19, i64 208, !26, i64 216, !6, i64 224, !23, i64 264, !23, i64 280, !23, i64 296, !23, i64 312, !5, i64 328, !25, i64 336, !25, i64 340, !25, i64 344, !25, i64 344, !25, i64 344, !25, i64 344, !25, i64 348, !5, i64 352, !6, i64 360, !5, i64 400, !5, i64 408, !5, i64 416, !5, i64 424, !5, i64 432, !5, i64 440, !5, i64 448, !19, i64 456, !19, i64 464, !27, i64 472, !28, i64 992, !19, i64 1016, !19, i64 1024, !25, i64 1032, !25, i64 1036, !23, i64 1040, !6, i64 1056, !5, i64 1096, !5, i64 1104, !5, i64 1112, !5, i64 1120, !5, i64 1128, !25, i64 1136, !19, i64 1144, !19, i64 1152, !19, i64 1160, !19, i64 1168, !19, i64 1176, !19, i64 1184, !25, i64 1192, !29, i64 1200, !6, i64 1232}
!22 = !{!"rb_global_vm_lock_struct", !19, i64 0, !6, i64 8, !23, i64 48, !19, i64 64, !25, i64 72, !6, i64 80, !6, i64 128, !25, i64 176, !25, i64 180}
!23 = !{!"list_head", !24, i64 0}
!24 = !{!"list_node", !19, i64 0, !19, i64 8}
!25 = !{!"int", !6, i64 0}
!26 = !{!"long long", !6, i64 0}
!27 = !{!"", !6, i64 0}
!28 = !{!"rb_hook_list_struct", !19, i64 0, !25, i64 8, !25, i64 12, !25, i64 16}
!29 = !{!"", !5, i64 0, !5, i64 8, !5, i64 16, !5, i64 24}
!30 = !{!31, !19, i64 16}
!31 = !{!"rb_execution_context_struct", !19, i64 0, !5, i64 8, !19, i64 16, !19, i64 24, !19, i64 32, !25, i64 40, !25, i64 44, !19, i64 48, !19, i64 56, !19, i64 64, !5, i64 72, !5, i64 80, !19, i64 88, !5, i64 96, !19, i64 104, !19, i64 112, !5, i64 120, !5, i64 128, !6, i64 136, !6, i64 137, !5, i64 144, !32, i64 152}
!32 = !{!"", !19, i64 0, !19, i64 8, !5, i64 16, !6, i64 24}
!33 = !{!34, !19, i64 16}
!34 = !{!"rb_control_frame_struct", !19, i64 0, !19, i64 8, !19, i64 16, !5, i64 24, !19, i64 32, !19, i64 40, !19, i64 48}
!35 = !{!34, !19, i64 32}
!36 = !DILocation(line: 0, scope: !9)
!37 = !DILocation(line: 5, column: 11, scope: !9)
!38 = !{!39}
!39 = distinct !{!39, !40, !"sorbet_buildArrayIntrinsic: argument 0"}
!40 = distinct !{!40, !"sorbet_buildArrayIntrinsic"}
!41 = !{!42}
!42 = distinct !{!42, !43, !"sorbet_expandSplatIntrinsic: argument 0"}
!43 = distinct !{!43, !"sorbet_expandSplatIntrinsic"}
!44 = !{!45, !5, i64 0}
!45 = !{!"RBasic", !5, i64 0, !5, i64 8}
!46 = !{!"branch_weights", i32 2000, i32 1}
!47 = !{!48}
!48 = distinct !{!48, !49, !"sorbet_rb_array_square_br: argument 0"}
!49 = distinct !{!49, !"sorbet_rb_array_square_br"}
!50 = !{!"branch_weights", i32 1, i32 2000}
!51 = !{!31, !25, i64 40}
!52 = !{!31, !25, i64 44}
!53 = !{!31, !19, i64 56}
!54 = !{!55}
!55 = distinct !{!55, !56, !"sorbet_rb_array_square_br: argument 0"}
!56 = distinct !{!56, !"sorbet_rb_array_square_br"}
!57 = !DILocation(line: 6, column: 6, scope: !9)
!58 = !{!59}
!59 = distinct !{!59, !60, !"sorbet_buildArrayIntrinsic: argument 0"}
!60 = distinct !{!60, !"sorbet_buildArrayIntrinsic"}
!61 = !{!34, !19, i64 8}
!62 = !DILocation(line: 8, column: 11, scope: !9)
!63 = !{!64}
!64 = distinct !{!64, !65, !"sorbet_buildArrayIntrinsic: argument 0"}
!65 = distinct !{!65, !"sorbet_buildArrayIntrinsic"}
!66 = !{!67}
!67 = distinct !{!67, !68, !"sorbet_expandSplatIntrinsic: argument 0"}
!68 = distinct !{!68, !"sorbet_expandSplatIntrinsic"}
!69 = !{!70}
!70 = distinct !{!70, !71, !"sorbet_rb_array_square_br: argument 0"}
!71 = distinct !{!71, !"sorbet_rb_array_square_br"}
!72 = !{!73}
!73 = distinct !{!73, !74, !"sorbet_rb_array_square_br: argument 0"}
!74 = distinct !{!74, !"sorbet_rb_array_square_br"}
!75 = !{!76}
!76 = distinct !{!76, !77, !"sorbet_rb_array_square_br: argument 0"}
!77 = distinct !{!77, !"sorbet_rb_array_square_br"}
!78 = !DILocation(line: 9, column: 6, scope: !9)
!79 = !{!80}
!80 = distinct !{!80, !81, !"sorbet_buildArrayIntrinsic: argument 0"}
!81 = distinct !{!81, !"sorbet_buildArrayIntrinsic"}
!82 = !{!83}
!83 = distinct !{!83, !84, !"sorbet_buildArrayIntrinsic: argument 0"}
!84 = distinct !{!84, !"sorbet_buildArrayIntrinsic"}
!85 = !DILocation(line: 11, column: 11, scope: !9)
!86 = !{!87}
!87 = distinct !{!87, !88, !"sorbet_expandSplatIntrinsic: argument 0"}
!88 = distinct !{!88, !"sorbet_expandSplatIntrinsic"}
!89 = !{!90}
!90 = distinct !{!90, !91, !"sorbet_rb_array_square_br: argument 0"}
!91 = distinct !{!91, !"sorbet_rb_array_square_br"}
!92 = !{!93}
!93 = distinct !{!93, !94, !"sorbet_rb_array_square_br: argument 0"}
!94 = distinct !{!94, !"sorbet_rb_array_square_br"}
!95 = !{!96}
!96 = distinct !{!96, !97, !"sorbet_rb_array_square_br: argument 0"}
!97 = distinct !{!97, !"sorbet_rb_array_square_br"}
!98 = !{!99}
!99 = distinct !{!99, !100, !"sorbet_rb_array_square_br: argument 0"}
!100 = distinct !{!100, !"sorbet_rb_array_square_br"}
!101 = !DILocation(line: 12, column: 6, scope: !9)
!102 = !{!103}
!103 = distinct !{!103, !104, !"sorbet_buildArrayIntrinsic: argument 0"}
!104 = distinct !{!104, !"sorbet_buildArrayIntrinsic"}
