Begin {
  stmts = [
    DefMethod {
      name = <U symbolic_and>
      params = Params {
        params = [
          Param {
            name = <U x>
          }
          Param {
            name = <U y>
          }
        ]
      }
      body = Begin {
        stmts = [
          And {
            left = Send {
              receiver = LVar {
                name = <U x>
              }
              method = <U <method-name-missing>>
              args = [
              ]
            }
            right = LVar {
              name = <U y>
            }
          }
          Send {
            receiver = NULL
            method = <U after_and>
            args = [
            ]
          }
        ]
      }
    }
    DefMethod {
      name = <U symbolic_or>
      params = Params {
        params = [
          Param {
            name = <U x>
          }
          Param {
            name = <U y>
          }
        ]
      }
      body = Begin {
        stmts = [
          Or {
            left = Send {
              receiver = LVar {
                name = <U x>
              }
              method = <U <method-name-missing>>
              args = [
              ]
            }
            right = LVar {
              name = <U y>
            }
          }
          Send {
            receiver = NULL
            method = <U after_or>
            args = [
            ]
          }
        ]
      }
    }
  ]
}
