# typed: autogenerated

class BadNamespace::Foo < BadParent # error: Unable to resolve constant `BadParent`
  include BadMixin # error-with-dupes: Unable to resolve constant `BadMixin`

  def foo
    @foo
  end
end
