# typed: autogenerated

# Simulates a situation where we've run missing methods to find things, but
# we've updated the code to no longer define things referred to by the
# generated RBIs.
#
# RBI generation should not output NonexistentThing, or StubModule.

module RBIGen::Public
  class AlsoDefinedInRBIFile
    include NonexistentThing
  end
end

