# ParsedFile: test/testdata/autogen/no_dsls.rb
requires: []
## defs:
[def id=0]
 type=module
 defines_behavior=0
 is_empty=0
[def id=1]
 type=casgn
 defines_behavior=1
 is_empty=0
 defining_ref=[A]
## refs:
[ref id=0]
 scope=[]
 name=[A]
 nesting=[]
 resolved=[A]
 loc=test/testdata/autogen/no_dsls.rb:3
 is_defining_ref=1
[ref id=1]
 scope=[]
 name=[Struct]
 nesting=[]
 resolved=[Struct]
 loc=test/testdata/autogen/no_dsls.rb:3
 is_defining_ref=0
