cc_library(
    name = "parser",
    srcs = [
        "builder.cc",
        "builder.h",
        "parser.cc",
    ],
    hdrs = [
        "parser.h",
    ],
    visibility = ["//visibility:public"],
    deps = ["@parser//:parser"],
)
