# frozen_string_literal: true

# Make sure that sorbet-runtime does not do any early
# initialization that would affect the ability to change
# the checked level default value
require "./lib/sorbet-runtime"
T::Configuration.default_checked_level = :always

task default: %i[test rubocop]

def require_tests
  Dir
    .glob('./test/**/*.rb')
    .reject {|path| path.match(%r{^./test/types/fixtures/})}
    .reject {|path| path.match(%r{^./test/wholesome/})}
    .each(&method(:require))
end

task :test do
  require_tests
end

task :test_vm_serde do
  T::Configuration.enable_vm_prop_serde
  require_tests
end

require 'rubocop/rake_task'
RuboCop::RakeTask.new(:rubocop) do |t|
  t.requires << 'rubocop-performance'
end

begin
  require './bench/tasks'
rescue LoadError
  # Expected when using packaged gem
end
