filegroup(
    name = "vm_append_files",
    srcs = [
        "array.c",
        "hash.c",
        "numeric.c",
        "object.c",
        "vm_insnhelper.c",
    ],
    visibility = ["//visibility:public"],
)
