class <emptyTree><<C <root>>> < (::<todo sym>)
  class <emptyTree>::<C A><<C <todo sym>>> < (::<todo sym>)
    def foo<<todo method>>(&<blk>)
      <emptyTree>
    end

    def test_missing_rhs<<todo method>>(x, &<blk>)
      y = <emptyTree>::<C <ErrorNode>>
    end

    def test_variable_after_method<<todo method>>(x, &<blk>)
      begin
        <self>.puts("before")
        y = <emptyTree>::<C <ErrorNode>>
      end
    end
  end
end
