codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "80...100"

  status:
    project: off
    patch: yes
    changes: no

comment:
  layout: "diff, files"
  behavior: default
  require_changes: no

