cc_library(
    name = "definition_checker",
    srcs = [
        "DefinitionLinesDenylistEnforcer.cc",
    ],
    hdrs = ["DefinitionLinesDenylistEnforcer.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//ast/treemap",
        "//core",
    ],
)
