package(default_visibility = ["//visibility:public"])

cc_library(
    name = "common",
    srcs = glob(["*.cc"]) + glob(["*.h"]),
    hdrs = [
        "common.h",
        "typecase.h",
    ],
    visibility = ["//visibility:public"],
    deps = [],
)
