cc_library(
    name = "interface",
    hdrs = ["SemanticExtension.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "none",
    srcs = ["DefaultImplementation.cc"],
    visibility = ["//visibility:public"],
    deps = ["interface"],
)
