#!/bin/bash

set -euo pipefail
if [ "HEAD" == "${BUILDKITE_COMMIT}" ]; then
  echo "not using commit marks as this is HEAD build"
else
  .buildkite/hooks/gh-status stripe/sorbet "${BUILDKITE_COMMIT}" pending "${BUILDKITE_BUILD_URL}#${BUILDKITE_JOB_ID}" "${BUILDKITE_LABEL}"
fi
