--- Makefile	2019-08-14 00:49:17.000000000 +0000
+++ Makefile.1	2019-08-14 00:49:02.000000000 +0000
@@ -2,7 +2,7 @@
 SHELL = /bin/sh
 
 # V=0 quiet, V=1 verbose.  other values don't work.
-V = 0
+V = 1
 Q1 = $(V:1=)
 Q = $(Q1:0=@)
 ECHO1 = $(V:1=@ :)
@@ -88,7 +88,7 @@
 CXXFLAGS = $(CCDLFLAGS) $(cxxflags) $(ARCH_FLAG)
 ldflags  = -L. -L/Users/dmitry/.rbenv/versions/2.4.5/lib  -fstack-protector -L/usr/local/lib
 dldflags = -L/Users/dmitry/.rbenv/versions/2.4.5/lib  -Wl,-undefined,dynamic_lookup -Wl,-multiply_defined,suppress 
-ARCH_FLAG = 
+ARCH_FLAG = -g -O0 -S -emit-llvm
 DLDFLAGS = $(ldflags) $(dldflags) $(ARCH_FLAG)
 LDSHARED = $(CC) -dynamic -bundle
 LDSHAREDXX = $(CXX) -dynamic -bundle
