# An LLVM instrumentation profile of sorbet typechecking a large Ruby codebase. See README.md and `--config=pgo-linux`.
fdo_profile(
    name = "linux-x86_64",
    profile = "linux-x86_64.profdata",
    visibility = ["//visibility:public"],
)
