{
    "jsonrpc": "2.0",
    "id": 1,
    "requestMethod": "textDocument/documentSymbol",
    "result": [
        {
            "name": "A",
            "detail": "",
            "kind": 5,
            "range": {
                "start": {
                    "line": 2,
                    "character": 0
                },
                "end": {
                    "line": 16,
                    "character": 3
                }
            },
            "selectionRange": {
                "start": {
                    "line": 2,
                    "character": 0
                },
                "end": {
                    "line": 2,
                    "character": 19
                }
            },
            "children": [
                {
                    "name": "@bar",
                    "detail": "",
                    "kind": 8,
                    "range": {
                        "start": {
                            "line": 6,
                            "character": 8
                        },
                        "end": {
                            "line": 6,
                            "character": 11
                        }
                    },
                    "selectionRange": {
                        "start": {
                            "line": 6,
                            "character": 8
                        },
                        "end": {
                            "line": 6,
                            "character": 11
                        }
                    },
                    "children": []
                },
                {
                    "name": "@foo",
                    "detail": "",
                    "kind": 8,
                    "range": {
                        "start": {
                            "line": 5,
                            "character": 9
                        },
                        "end": {
                            "line": 5,
                            "character": 12
                        }
                    },
                    "selectionRange": {
                        "start": {
                            "line": 5,
                            "character": 9
                        },
                        "end": {
                            "line": 5,
                            "character": 12
                        }
                    },
                    "children": []
                },
                {
                    "name": "bar",
                    "detail": "",
                    "kind": 7,
                    "range": {
                        "start": {
                            "line": 6,
                            "character": 2
                        },
                        "end": {
                            "line": 6,
                            "character": 19
                        }
                    },
                    "selectionRange": {
                        "start": {
                            "line": 6,
                            "character": 2
                        },
                        "end": {
                            "line": 6,
                            "character": 19
                        }
                    },
                    "children": []
                },
                {
                    "name": "bar=",
                    "detail": "",
                    "kind": 7,
                    "range": {
                        "start": {
                            "line": 6,
                            "character": 2
                        },
                        "end": {
                            "line": 6,
                            "character": 19
                        }
                    },
                    "selectionRange": {
                        "start": {
                            "line": 6,
                            "character": 2
                        },
                        "end": {
                            "line": 6,
                            "character": 19
                        }
                    },
                    "children": []
                },
                {
                    "name": "checked_qux",
                    "detail": "",
                    "kind": 7,
                    "range": {
                        "start": {
                            "line": 12,
                            "character": 2
                        },
                        "end": {
                            "line": 12,
                            "character": 26
                        }
                    },
                    "selectionRange": {
                        "start": {
                            "line": 12,
                            "character": 2
                        },
                        "end": {
                            "line": 12,
                            "character": 26
                        }
                    },
                    "children": []
                },
                {
                    "name": "checked_zap",
                    "detail": "",
                    "kind": 7,
                    "range": {
                        "start": {
                            "line": 15,
                            "character": 2
                        },
                        "end": {
                            "line": 15,
                            "character": 26
                        }
                    },
                    "selectionRange": {
                        "start": {
                            "line": 15,
                            "character": 2
                        },
                        "end": {
                            "line": 15,
                            "character": 26
                        }
                    },
                    "children": []
                },
                {
                    "name": "foo",
                    "detail": "",
                    "kind": 7,
                    "range": {
                        "start": {
                            "line": 5,
                            "character": 2
                        },
                        "end": {
                            "line": 5,
                            "character": 21
                        }
                    },
                    "selectionRange": {
                        "start": {
                            "line": 5,
                            "character": 2
                        },
                        "end": {
                            "line": 5,
                            "character": 21
                        }
                    },
                    "children": []
                },
                {
                    "name": "initialize",
                    "detail": "",
                    "kind": 9,
                    "range": {
                        "start": {
                            "line": 2,
                            "character": 0
                        },
                        "end": {
                            "line": 16,
                            "character": 3
                        }
                    },
                    "selectionRange": {
                        "start": {
                            "line": 2,
                            "character": 0
                        },
                        "end": {
                            "line": 2,
                            "character": 19
                        }
                    },
                    "children": []
                },
                {
                    "name": "qux",
                    "detail": "",
                    "kind": 7,
                    "range": {
                        "start": {
                            "line": 8,
                            "character": 2
                        },
                        "end": {
                            "line": 8,
                            "character": 18
                        }
                    },
                    "selectionRange": {
                        "start": {
                            "line": 8,
                            "character": 2
                        },
                        "end": {
                            "line": 8,
                            "character": 18
                        }
                    },
                    "children": []
                },
                {
                    "name": "zap",
                    "detail": "",
                    "kind": 7,
                    "range": {
                        "start": {
                            "line": 9,
                            "character": 2
                        },
                        "end": {
                            "line": 9,
                            "character": 20
                        }
                    },
                    "selectionRange": {
                        "start": {
                            "line": 9,
                            "character": 2
                        },
                        "end": {
                            "line": 9,
                            "character": 20
                        }
                    },
                    "children": []
                },
                {
                    "name": "zap=",
                    "detail": "",
                    "kind": 7,
                    "range": {
                        "start": {
                            "line": 9,
                            "character": 2
                        },
                        "end": {
                            "line": 9,
                            "character": 20
                        }
                    },
                    "selectionRange": {
                        "start": {
                            "line": 9,
                            "character": 2
                        },
                        "end": {
                            "line": 9,
                            "character": 20
                        }
                    },
                    "children": []
                }
            ]
        }
    ]
}
