{
    "jsonrpc": "2.0",
    "id": 1,
    "requestMethod": "textDocument/documentSymbol",
    "result": [
        {
            "name": "Test",
            "detail": "",
            "kind": 5,
            "range": {
                "start": {
                    "line": 2,
                    "character": 0
                },
                "end": {
                    "line": 8,
                    "character": 3
                }
            },
            "selectionRange": {
                "start": {
                    "line": 2,
                    "character": 0
                },
                "end": {
                    "line": 2,
                    "character": 10
                }
            },
            "children": [
                {
                    "name": "b_func",
                    "detail": "",
                    "kind": 6,
                    "range": {
                        "start": {
                            "line": 4,
                            "character": 4
                        },
                        "end": {
                            "line": 6,
                            "character": 7
                        }
                    },
                    "selectionRange": {
                        "start": {
                            "line": 4,
                            "character": 4
                        },
                        "end": {
                            "line": 4,
                            "character": 14
                        }
                    },
                    "children": []
                },
                {
                    "name": "self.a_func",
                    "detail": "",
                    "kind": 6,
                    "range": {
                        "start": {
                            "line": 3,
                            "character": 2
                        },
                        "end": {
                            "line": 7,
                            "character": 5
                        }
                    },
                    "selectionRange": {
                        "start": {
                            "line": 3,
                            "character": 2
                        },
                        "end": {
                            "line": 3,
                            "character": 17
                        }
                    },
                    "children": []
                }
            ]
        }
    ]
}
