#!/bin/bash
set -eo pipefail

base="$( dirname "${BASH_SOURCE[0]}" )"/..

if [ -f main/sorbet ]; then
    sorbet=main/sorbet
    ld=external/llvm_toolchain/bin/ld
else
    sorbet="$base/bazel-bin/main/sorbet"
    ld="$base/bazel-sorbet_llvm/external/llvm_toolchain/bin/ld"
    if [ ! -f "$sorbet" ]; then
        cd "$base"
        bazel build @llvm_toolchain//:bin/ld main:sorbet 2> /dev/null
        cd - > /dev/null
    fi
fi

llvmir=$1
shift

if [ "$#" -eq 0 ]; then
    # No args passed. Run `srb` to find the right place
    SRB_SORBET_EXE=$sorbet srb tc --silence-dev-message --no-error-count --suppress-non-critical --llvm-ir-folder "$llvmir"
else
    $sorbet --silence-dev-message --no-error-count --suppress-non-critical --llvm-ir-folder "$llvmir" "$@"
fi

for o in "$llvmir"/*.o; do
    if [ ! -f "$o" ]; then
        echo "No .o files output from Sorbet"
        exit 1;
    fi

    bundle="${o%.o}.bundle"
    "$ld" -bundle -o "$bundle" "$o" -undefined dynamic_lookup -macosx_version_min 10.14 -lSystem
done
