#!/bin/bash
set -exo pipefail

base="$( dirname "${BASH_SOURCE[0]}" )"/..

if [ -f main/sorbet ]; then
    sorbet=main/sorbet
else
    sorbet="$base/bazel-bin/main/sorbet"
    if [ ! -f "$sorbet" ]; then
        cd "$base"
        cd - > /dev/null
    fi
fi

llvmir=$1
shift

if [ "$#" -eq 0 ]; then
    # No args passed. Run `srb` to find the right place
    SRB_SORBET_EXE=$sorbet srb tc --silence-dev-message --no-error-count --suppress-non-critical --llvm-ir-folder "$llvmir"
else
    $sorbet --silence-dev-message --no-error-count --suppress-non-critical --llvm-ir-folder "$llvmir" "$@"
fi

outputfiles=$(find "$llvmir" -maxdepth 1 -name "*.rb.so" -o -name "*.rb.bundle")
if [! ${#output[@]} -gt 0 ]; then 
        echo "No output files output from Sorbet"
        exit 1;
fi
