#!/bin/bash
set -eo pipefail

root="$( dirname "${BASH_SOURCE[0]}" )"/..

if [ -f main/sorbet ]; then
    sorbet=main/sorbet
    ld=external/llvm_toolchain/bin/ld
else
    cd "$root"
    bazel build @llvm_toolchain//:bin/ld main:sorbet 2> /dev/null
    cd - > /dev/null
    sorbet="$root/bazel-bin/main/sorbet"
    ld="$root/bazel-sorbet_llvm/external/llvm_toolchain/bin/ld"
fi

llvmir=$1
rb=$2

"$sorbet" --silence-dev-message --no-error-count --typed=true --llvm-ir-folder "$llvmir" "$rb"

underscores=${rb//\//_}
o="$llvmir/$underscores.o"
bundle="$llvmir/$underscores.bundle"
"$ld" -bundle -o "$bundle" "$o" -undefined dynamic_lookup -macosx_version_min 10.14 -lSystem
echo "$bundle"
