#!/bin/bash
set -eo pipefail

base="$( dirname "${BASH_SOURCE[0]}" )"/..

if [ -z "$runfile" ]; then
    llvmir=$(mktemp -d)
    runfile=$(mktemp)
    rmtmp=1
fi

cleanup() {
    if [ -n "$rmtmp" ]; then
        rm -r "$llvmir" "$runfile"
    fi
}

trap cleanup EXIT

echo "require './$base/run/preamble.rb';" > "$runfile"
echo "require './$base/run/patch_require.rb';" >> "$runfile"

rb=$1
shift
echo "require '$rb';" >> "$runfile"

args=("$rb")
if [ -n "${root:-''}" ]; then
    args+=("$root")
fi
"$base/run/compile" "$llvmir" "${args[@]}"

if [ -f "$base/external/ruby_2_6_3/ruby" ]; then
    ruby="$base/external/ruby_2_6_3/ruby"
else
    ruby="$base/bazel-bin/external/ruby_2_6_3/ruby"
    if [ ! -f "$ruby" ]; then
        cd "$base"
        bazel build @ruby_2_6_3//:ruby --config=dbg 2> /dev/null
        cd - > /dev/null
    fi
fi
$ruby "$runfile" "$@"
