#!/bin/bash
set -eo pipefail

base="$( cd "$(dirname "$0")" ; pwd -P )"/..

if [ -f "$base/external/ruby_2_6_3/ruby" ]; then
    ruby="$base/external/ruby_2_6_3/ruby"
else
    ruby="$base/bazel-bin/external/ruby_2_6_3/ruby"
    if [ ! -f "$ruby" ]; then
        cd "$base"
        bazel build @ruby_2_6_3//:ruby --config=dbg 2> /dev/null
        cd - > /dev/null
    fi
fi
$ruby -r "$base/run/preamble.rb" -r "$base/run/patch_require.rb" "$@"
