# -- test/testdata/packager/import_subpackage/a/__package.rb --
class <emptyTree><<C <root>>> < (::<todo sym>)
  class ::<PackageSpecRegistry>::Root<<C Root>> < (::Sorbet::Private::Static::PackageSpec)
    <self>.import(::<PackageSpecRegistry>::<C Root>::<C B>)
  end
end
# -- test/testdata/packager/import_subpackage/a/b/__package.rb --
class <emptyTree><<C <root>>> < (::<todo sym>)
  class ::<PackageSpecRegistry>::Root::B<<C B>> < (::Sorbet::Private::Static::PackageSpec)
    <self>.export(<emptyTree>::<C Root>::<C B>::<C Foo>)
  end
end
# -- test/testdata/packager/import_subpackage/a/b/foo.rb --
class <emptyTree><<C <root>>> < (::<todo sym>)
  module ::Root::B::Foo<<C Foo>> < ()
  end
end
