{core::Symbols::BasicObject(), "==", "sorbet_int_rb_obj_equal"},
    {core::Symbols::BasicObject(), "!", "sorbet_int_rb_obj_not"},
    {core::Symbols::BasicObject(), "!=", "sorbet_int_rb_obj_not_equal"},
    {core::Symbols::Array(), "initialize_copy", "sorbet_int_rb_ary_replace"},
    {core::Symbols::Array(), "[]", "sorbet_int_rb_ary_aref"}, {core::Symbols::Array(), "at", "sorbet_int_rb_ary_at"},
    {core::Symbols::Array(), "last", "sorbet_int_rb_ary_last"},
    {core::Symbols::Array(), "<<", "sorbet_int_rb_ary_push"},
    {core::Symbols::Array(), "each", "sorbet_int_rb_ary_each"},
    {core::Symbols::Array(), "sort", "sorbet_int_rb_ary_sort"},
    {core::Symbols::Array(), "sort!", "sorbet_int_rb_ary_sort_bang"},
    {core::Symbols::Array(), "delete", "sorbet_int_rb_ary_delete"},
    {core::Symbols::Array(), "clear", "sorbet_int_rb_ary_clear"},
    {core::Symbols::Array(), "include?", "sorbet_int_rb_ary_includes"},
    {core::Symbols::Array(), "<=>", "sorbet_int_rb_ary_cmp"},
    {core::Symbols::Array(), "assoc", "sorbet_int_rb_ary_assoc"},
    {core::Symbols::Array(), "rassoc", "sorbet_int_rb_ary_rassoc"},
    {core::Symbols::Array(), "+", "sorbet_int_rb_ary_plus"},
    {core::Symbols::String(), "initialize_copy", "sorbet_int_rb_str_replace"},
    {core::Symbols::String(), "==", "sorbet_int_rb_str_equal"},
    {core::Symbols::String(), "eql?", "sorbet_int_rb_str_eql"},
    {core::Symbols::String(), "+", "sorbet_int_rb_str_plus"}, {core::Symbols::String(), "*", "sorbet_int_rb_str_times"},
    {core::Symbols::String(), "length", "sorbet_int_rb_str_length"},
    {core::Symbols::String(), "succ", "sorbet_int_rb_str_succ"},
    {core::Symbols::String(), "freeze", "sorbet_int_rb_str_freeze"},
    {core::Symbols::String(), "inspect", "sorbet_int_rb_str_inspect"},
    {core::Symbols::String(), "dump", "sorbet_int_rb_str_dump"},
    {core::Symbols::String(), "<<", "sorbet_int_rb_str_concat"},
    {core::Symbols::String(), "intern", "sorbet_int_rb_str_intern"},
    {core::Symbols::String(), "ord", "sorbet_int_rb_str_ord"},
    {core::Symbols::String(), "encoding", "sorbet_int_rb_obj_encoding"},
    {core::Symbols::BasicObject(), "instance_eval", "sorbet_int_rb_obj_instance_eval"},
    {core::Symbols::BasicObject(), "instance_exec", "sorbet_int_rb_obj_instance_exec"},
    {core::Symbols::BasicObject(), "__send__", "sorbet_int_rb_f_send"},
    {core::Symbols::Integer(), "odd?", "sorbet_int_rb_int_odd_p"},
    {core::Symbols::Integer(), "<=>", "sorbet_int_rb_int_cmp"},
    {core::Symbols::Integer(), "-@", "sorbet_int_rb_int_uminus"},
    {core::Symbols::Integer(), "+", "sorbet_int_rb_int_plus"},
    {core::Symbols::Integer(), "-", "sorbet_int_rb_int_minus"},
    {core::Symbols::Integer(), "*", "sorbet_int_rb_int_mul"}, {core::Symbols::Integer(), "/", "sorbet_int_rb_int_div"},
    {core::Symbols::Integer(), "div", "sorbet_int_rb_int_idiv"},
    {core::Symbols::Integer(), "%", "sorbet_int_rb_int_modulo"},
    {core::Symbols::Integer(), "divmod", "sorbet_int_rb_int_divmod"},
    {core::Symbols::Integer(), "fdiv", "sorbet_int_rb_int_fdiv"},
    {core::Symbols::Integer(), "**", "sorbet_int_rb_int_pow"},
    {core::Symbols::Integer(), "pow", "sorbet_int_rb_int_powm"},
    {core::Symbols::Integer(), "abs", "sorbet_int_rb_int_abs"},
    {core::Symbols::Integer(), "===", "sorbet_int_rb_int_equal"},
    {core::Symbols::Integer(), ">", "sorbet_int_rb_int_gt"}, {core::Symbols::Integer(), ">=", "sorbet_int_rb_int_ge"},
    {core::Symbols::Integer(), "&", "sorbet_int_rb_int_and"},
    {core::Symbols::Integer(), "<<", "sorbet_int_rb_int_lshift"},
    {core::Symbols::Float(), "-@", "sorbet_int_rb_float_uminus"},
    {core::Symbols::Float(), "+", "sorbet_int_rb_float_plus"}, {core::Symbols::Float(), "*", "sorbet_int_rb_float_mul"},
    {core::Symbols::Float(), "**", "sorbet_int_rb_float_pow"}, {core::Symbols::Float(), ">", "sorbet_int_rb_float_gt"},
    {core::Symbols::Float(), "abs", "sorbet_int_rb_float_abs"},
    {core::Symbols::Float(), "infinite?", "sorbet_int_rb_flo_is_infinite_p"},
    {core::Symbols::Float(), "finite?", "sorbet_int_rb_flo_is_finite_p"},
    {core::Symbols::Integer(), "gcd", "sorbet_int_rb_gcd"}, {core::Symbols::Integer(), "lcm", "sorbet_int_rb_lcm"},
    {core::Symbols::Integer(), "gcdlcm", "sorbet_int_rb_gcdlcm"},
    {core::Symbols::BasicObject(), "__id__", "sorbet_int_rb_obj_id"},
