{core::Symbols::Array(), "initialize_copy", "sorbet_int_rb_ary_replace"},
    {core::Symbols::Array(), "[]", "sorbet_int_rb_ary_aref"}, {core::Symbols::Array(), "at", "sorbet_int_rb_ary_at"},
    {core::Symbols::Array(), "last", "sorbet_int_rb_ary_last"},
    {core::Symbols::Array(), "<<", "sorbet_int_rb_ary_push"},
    {core::Symbols::Array(), "each", "sorbet_int_rb_ary_each"},
    {core::Symbols::Array(), "sort", "sorbet_int_rb_ary_sort"},
    {core::Symbols::Array(), "sort!", "sorbet_int_rb_ary_sort_bang"},
    {core::Symbols::Array(), "delete", "sorbet_int_rb_ary_delete"},
    {core::Symbols::Array(), "clear", "sorbet_int_rb_ary_clear"},
    {core::Symbols::Array(), "include?", "sorbet_int_rb_ary_includes"},
    {core::Symbols::Array(), "<=>", "sorbet_int_rb_ary_cmp"},
    {core::Symbols::Array(), "assoc", "sorbet_int_rb_ary_assoc"},
    {core::Symbols::Array(), "rassoc", "sorbet_int_rb_ary_rassoc"},
    {core::Symbols::Array(), "+", "sorbet_int_rb_ary_plus"},
    {core::Symbols::Complex(), "real", "sorbet_int_rb_complex_real"},
    {core::Symbols::Complex(), "imaginary", "sorbet_int_rb_complex_imag"},
    {core::Symbols::Complex(), "-@", "sorbet_int_rb_complex_uminus"},
    {core::Symbols::Complex(), "+", "sorbet_int_rb_complex_plus"},
    {core::Symbols::Complex(), "-", "sorbet_int_rb_complex_minus"},
    {core::Symbols::Complex(), "*", "sorbet_int_rb_complex_mul"},
    {core::Symbols::Complex(), "/", "sorbet_int_rb_complex_div"},
    {core::Symbols::Complex(), "**", "sorbet_int_rb_complex_pow"},
    {core::Symbols::Complex(), "abs", "sorbet_int_rb_complex_abs"},
    {core::Symbols::Complex(), "arg", "sorbet_int_rb_complex_arg"},
    {core::Symbols::Complex(), "conjugate", "sorbet_int_rb_complex_conjugate"},
    {core::Symbols::Hash(), "rehash", "sorbet_int_rb_hash_rehash"},
    {core::Symbols::Hash(), "[]", "sorbet_int_rb_hash_aref"}, {core::Symbols::Hash(), "[]=", "sorbet_int_rb_hash_aset"},
    {core::Symbols::Hash(), "default_proc=", "sorbet_int_rb_hash_set_default_proc"},
    {core::Symbols::Hash(), "size", "sorbet_int_rb_hash_size"},
    {core::Symbols::Hash(), "keys", "sorbet_int_rb_hash_keys"},
    {core::Symbols::Hash(), "values", "sorbet_int_rb_hash_values"},
    {core::Symbols::Hash(), "values_at", "sorbet_int_rb_hash_values_at"},
    {core::Symbols::Hash(), "fetch_values", "sorbet_int_rb_hash_fetch_values"},
    {core::Symbols::Hash(), "delete_if", "sorbet_int_rb_hash_delete_if"},
    {core::Symbols::Hash(), "keep_if", "sorbet_int_rb_hash_keep_if"},
    {core::Symbols::Hash(), "select", "sorbet_int_rb_hash_select"},
    {core::Symbols::Hash(), "select!", "sorbet_int_rb_hash_select_bang"},
    {core::Symbols::Hash(), "reject", "sorbet_int_rb_hash_reject"},
    {core::Symbols::Hash(), "reject!", "sorbet_int_rb_hash_reject_bang"},
    {core::Symbols::Hash(), "clear", "sorbet_int_rb_hash_clear"},
    {core::Symbols::Hash(), "assoc", "sorbet_int_rb_hash_assoc"},
    {core::Symbols::Hash(), "rassoc", "sorbet_int_rb_hash_rassoc"},
    {core::Symbols::Hash(), "include?", "sorbet_int_rb_hash_has_key"},
    {core::Symbols::Hash(), "compare_by_identity?", "sorbet_int_rb_hash_compare_by_id_p"},
    {core::Symbols::Integer(), "odd?", "sorbet_int_rb_int_odd_p"},
    {core::Symbols::Integer(), "<=>", "sorbet_int_rb_int_cmp"},
    {core::Symbols::Integer(), "-@", "sorbet_int_rb_int_uminus"},
    {core::Symbols::Integer(), "+", "sorbet_int_rb_int_plus"},
    {core::Symbols::Integer(), "-", "sorbet_int_rb_int_minus"},
    {core::Symbols::Integer(), "*", "sorbet_int_rb_int_mul"}, {core::Symbols::Integer(), "/", "sorbet_int_rb_int_div"},
    {core::Symbols::Integer(), "div", "sorbet_int_rb_int_idiv"},
    {core::Symbols::Integer(), "%", "sorbet_int_rb_int_modulo"},
    {core::Symbols::Integer(), "divmod", "sorbet_int_rb_int_divmod"},
    {core::Symbols::Integer(), "fdiv", "sorbet_int_rb_int_fdiv"},
    {core::Symbols::Integer(), "**", "sorbet_int_rb_int_pow"},
    {core::Symbols::Integer(), "pow", "sorbet_int_rb_int_powm"},
    {core::Symbols::Integer(), "abs", "sorbet_int_rb_int_abs"},
    {core::Symbols::Integer(), "===", "sorbet_int_rb_int_equal"},
    {core::Symbols::Integer(), ">", "sorbet_int_rb_int_gt"}, {core::Symbols::Integer(), ">=", "sorbet_int_rb_int_ge"},
    {core::Symbols::Integer(), "&", "sorbet_int_rb_int_and"},
    {core::Symbols::Integer(), "<<", "sorbet_int_rb_int_lshift"},
    {core::Symbols::Float(), "-@", "sorbet_int_rb_float_uminus"},
    {core::Symbols::Float(), "+", "sorbet_int_rb_float_plus"}, {core::Symbols::Float(), "*", "sorbet_int_rb_float_mul"},
    {core::Symbols::Float(), "**", "sorbet_int_rb_float_pow"}, {core::Symbols::Float(), ">", "sorbet_int_rb_float_gt"},
    {core::Symbols::Float(), "abs", "sorbet_int_rb_float_abs"},
    {core::Symbols::Float(), "infinite?", "sorbet_int_rb_flo_is_infinite_p"},
    {core::Symbols::Float(), "finite?", "sorbet_int_rb_flo_is_finite_p"},
    {core::Symbols::Integer(), "gcd", "sorbet_int_rb_gcd"}, {core::Symbols::Integer(), "lcm", "sorbet_int_rb_lcm"},
    {core::Symbols::Integer(), "gcdlcm", "sorbet_int_rb_gcdlcm"},
