class <emptyTree><<C <root>>> < ()
  module <emptyTree>::<C Interface><<C <todo sym>>> < ()
    def some_method<<C <todo sym>>>(&<blk>)
      <emptyTree>
    end
  end

  class <emptyTree>::<C SomeClass><<C <todo sym>>> < (::<todo sym>)
    <self>.include(<emptyTree>::<C Interface>)

    def other_method<<C <todo sym>>>(&<blk>)
      <emptyTree>
    end
  end

  class <emptyTree>::<C Other><<C <todo sym>>> < (::<todo sym>)
    def self.wrap_instance<<C <todo sym>>>(x, y = nil, &<blk>)
      <emptyTree>
    end
  end

  def testit<<C <todo sym>>>(&<blk>)
    begin
      s = <emptyTree>::<C SomeClass>.new()
      wrap = ::T.let(s, <emptyTree>::<C Interface>)
      <emptyTree>::<C T>.assert_type!(wrap, <emptyTree>::<C Interface>)
      wrap.other_method()
      wrap.some_method()
      <emptyTree>::<C Other>.wrap_instance("hi", "there")
      o = <emptyTree>::<C Other>
      o.wrap_instance("hi")
    end
  end
end
