name: CI

on:
  pull_request:
    types: [opened]

jobs:
  request-review:
    runs-on: ubuntu-latest
    steps:
    - name: "Request review for external contribution"
      if: github.event.pull_request.head.repo.fork == true
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
        --header 'authorization: Bearer ${{ secrets.JEZ_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{ "team_reviewers": [ "runner" ] }'
    - name: "Request review for internal contribution"
      if: github.event.pull_request.head.repo.fork == false
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
        --header 'authorization: Bearer ${{ secrets.JEZ_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{ "team_reviewers": [ "core-reviewers" ] }'
