name: CI

on:
  pull_request:
    types: [opened]

jobs:
  request-review:
    runs-on: ubuntu-latest
    steps:
    - name: "Request review for external contribution"
      if: github.event.pull_request.head.repo.fork == true
      uses: jez/review-request-action@92ec94478b94204018cc846a273d9d4c857d622a
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        team-reviewers: "runner"
    - name: "Request review for internal contribution"
      if: github.event.pull_request.head.repo.fork == false
      uses: jez/review-request-action@92ec94478b94204018cc846a273d9d4c857d622a
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        team-reviewers: "core-reviewers"
